### ISSUE TITLE
1.5.4 changes when extra_vars are bound, breaks conditional roles

### ISSUE THREAD

**Issue by nathanhruby** [ansible/ansible#6898] opened 2014-04-08 17:29 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.4
##### Environment:

Ubuntu 12.04
##### Summary:

Overriding vars via -e switch now happens much later in 1.5.4.  This causes pre-defined vars in group_var files to be present during fact gathering, which impacts conditional roles based on those vars, notably if the roles require lookup files that are not on the host (nor should they be, since the role doesn't apply).

https://github.com/ansible/ansible/compare/release1.5.3...release1.5.4#diff-fc760c36dc6711859d36682f1b52b8f9L430

Current use case: we have a prod_role var defined as "staging" in group_vars/all and override this var to be "developer" on the cli with -e using vagrant.  Several plays then have when: clauses on their roles so that developer / staging / production roles are applied to the correct hosts.  Several of these roles use lookup() to read file data to populate variables with credentials, for the developer roles those creds don't exist on the dev hosts, so we skip them.
##### Steps To Reproduce:
- make a role with a vars file that does a lookup for a non existing file
- make a play with that role, and use "when: somevar" to conditionally require it
- define somevar in group file to True
- attempt to redefine somevar via -e somevar=False on teh cli
##### Expected Results:

with -e somevar=False no error, since role is not parsed
##### Actual Results:

role is run and/or parsed and errors with lookup issues

**Comment by nathanhruby** [comment] 2014-04-08 17:45
sigh, I'm running on a tight deadline so this bug may be misleading....  

This bug does happen, but after attempting to simple change our default to fix the conditional roles, the lookup errors in the vars files for the should-not-be-include roles were still being hit.  commenting out the roles in the play made things work.  Perhaps ansible is just trying to parse the vars files found in the roles without applying the conditional.

**Comment by mpdehaan** [comment] 2014-04-09 12:17
I am having a hard time following the description above, can you provide a minimal playbook that explains the problem you are having?

Also, can you test on the development branch?  Various handling on extra vars has already been tweaked there, so this may be a moot point, but I want to be sure.

Thank you!

**Comment by nathanhruby** [comment] 2014-04-09 16:14
Hi, 

Sorry for the confusion.  Sure I can get to this this afternoon to evening.

-n

**Comment by mpdehaan** [comment] 2014-04-15 20:39
Any update on this one?  Thanks!

**Comment by nathanhruby** [comment] 2014-04-24 19:06
Sorry this took so long.

Below links to a tarball with a sample playbook and role.  Extract it and run with
`ansible-playbook -e userole=False -i test.inv testvars.yml` 
to see the failure.  Before 1.5.4 this worked and the vars file would not be parsed.

https://drive.google.com/file/d/0B7vhBal_UqRNR3FrUEEwVlZTLWs/edit?usp=sharing

**Comment by jimi-c** [comment] 2014-04-24 19:16
I can confirm the error shows up on the 1.5.x branch up to 1.5.5, however it does appear to be resolved in devel:

<pre>
# ansible-playbook -e userole=False -i test.inv testvars.yml
PLAY [test role vars] ********************************************************* 
GATHERING FACTS *************************************************************** 
ok: [localhost]
TASK: [vartest | debug var=userole] ******************************************* 
skipping: [localhost]
PLAY RECAP ******************************************************************** 
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
</pre>

Since this is fixed in devel and we're aiming to release 1.6.0 before the end of the month, I'm going to go ahead and close this. 

If you have any further questions regarding this issue, please let us know. Thanks!

**Closed as completed by jimi-c** 2014-04-24 19:16 UTC
Labels: needs_info, bug

**Comment by nathanhruby** [comment] 2014-04-24 19:17
hotness, thanks!
