### ISSUE TITLE
v2 ValueError: Circular reference detected

### ISSUE THREAD

**Issue by skornehl** [ansible/ansible#13033] opened 2015-11-04 11:15 UTC
I have a template for some Debug Informations, it looks like:

tasks/main.yaml

```
- name: Dump all vars
  action: template src=dumpall.j2 dest=/tmp/ansible.all
```

templates/dumpall.j2

```
Environment Variables ("environment"):
--------------------------------
{{ environment | to_nice_json }} 

GROUP NAMES Variables ("group_names"):
--------------------------------
{{ group_names | to_nice_json }}

GROUPS Variables ("groups"):
--------------------------------
{{ groups | to_nice_json }}

HOST Variables ("hostvars"):
--------------------------------
{{ hostvars | to_nice_json }} 
```

This works with ansible 1.9 but with the actual HEAD this results in:

```
TASK [debugging : Dump all vars] ***********************************************
task path: [some path]/roles/debugging/tasks/main.yaml:1
fatal: [172.23.11.169]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"dest": "/tmp/ansible.all", "src": "dumpall.j2"}, "module_name": "template"}, "msg": "ValueError: Circular reference detected"} 
```

I just can't see any circular reference here ...

**Comment by bcoca** [comment] 2015-11-04 13:37
so the issue is that you seem to use the 'environment' directive as a variable, not sure how this works in 1.9 either as they will be in conflict.

**Comment by bcoca** [comment] 2015-11-04 13:41
If i set environment, it runs w/o errors

**Comment by basz** [comment] 2015-11-08 15:56
same thing here... (HEAD) @da4b4a2

**Comment by jimi-c** [comment] 2015-11-09 19:52
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-11-09 19:52 UTC
Labels: bug
