### ISSUE TITLE
Local_action makes ansible_host localhost.

### ISSUE THREAD

**Issue by Brian-Williams** [ansible/ansible#16139] opened 2016-06-05 20:51 UTC
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /root/ansible/ansible.cfg
  configured module search path = ['./library']
```
##### CONFIGURATION

```
[ssh_connection]
scp_if_ssh=True
```
##### OS / ENVIRONMENT

# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

# uname -a
Linux localhost.localdomain 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
##### SUMMARY

Ansible_host variable is localhost when performing local_actions.
##### STEPS TO REPRODUCE

```
# from playbook
- debug: var=ansible_host
- local_action: debug var=ansible_ssh_host
- local_action: debug var=ansible_host
```
##### EXPECTED RESULTS

I expected the ansible_host to be Branch1_Sky as that was the system defined from hosts.
##### ACTUAL RESULTS

Local_action causes ansible_ssh_host and ansible_host to become localhost. Is this working as intended? It surprised me when I was doing a RESTful API call from localhost at a target machine and it was putting in localhost.

```
# output
TASK [debug] *******************************************************************
ok: [Branch1_Sky] => {
    "ansible_host": "Branch1_Sky"
}

TASK [debug] *******************************************************************
ok: [Branch1_Sky -> localhost] => {
    "ansible_ssh_host": "localhost"
}

TASK [debug] *******************************************************************
ok: [Branch1_Sky -> localhost] => {
    "ansible_host": "localhost"
}
```

**Comment by alikins** [comment] 2016-06-06 15:37
I can reproduce this with latest from git in devel/ branch:

Using hosts:

```
192.168.1.30  # routable ip to localhost
127.0.0.1
localhost
adrian-wired.g.a   # resolvable name to 192.168.1.30
```

and site.yml:

```
---
- name: site playbook
  hosts: all
  tasks:
    - name: debug ansible_host
      debug: var=ansible_host
    - name: local_action debug ansible_ssh_host
      local_action: debug var=ansible_ssh_host
    - name: local_action debug ansible_host
      local_action: debug var=ansible_host
```

Output is:

```
11:35 $ ansible-playbook -i hosts site.yml 

PLAY [site playbook] ***********************************************************

TASK [setup] *******************************************************************
ok: [adrian-wired.g.a]
ok: [192.168.1.30]
ok: [127.0.0.1]
ok: [localhost]

TASK [debug ansible_host] ******************************************************
ok: [192.168.1.30] => {
    "ansible_host": "192.168.1.30"
}
ok: [127.0.0.1] => {
    "ansible_host": "127.0.0.1"
}
ok: [localhost] => {
    "ansible_host": "localhost"
}
ok: [adrian-wired.g.a] => {
    "ansible_host": "adrian-wired.g.a"
}

TASK [local_action debug ansible_ssh_host] *************************************
ok: [192.168.1.30 -> localhost] => {
    "ansible_ssh_host": "localhost"
}
ok: [127.0.0.1 -> localhost] => {
    "ansible_ssh_host": "localhost"
}
ok: [localhost -> localhost] => {
    "ansible_ssh_host": "localhost"
}
ok: [adrian-wired.g.a -> localhost] => {
    "ansible_ssh_host": "localhost"
}

TASK [local_action debug ansible_host] *****************************************
ok: [192.168.1.30 -> localhost] => {
    "ansible_host": "localhost"
}
ok: [127.0.0.1 -> localhost] => {
    "ansible_host": "localhost"
}
ok: [localhost -> localhost] => {
    "ansible_host": "localhost"
}
ok: [adrian-wired.g.a -> localhost] => {
    "ansible_host": "localhost"
}

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=4    changed=0    unreachable=0    failed=0   
192.168.1.30               : ok=4    changed=0    unreachable=0    failed=0   
adrian-wired.g.a           : ok=4    changed=0    unreachable=0    failed=0   
localhost                  : ok=4    changed=0    unreachable=0    failed=0   

```

**Comment by alikins** [comment] 2016-06-06 15:45
> It surprised me when I was doing a RESTful API call from localhost at a target machine and it was putting in localhost.

Got a playbook snippet and/or ansible-playbook output showing this?

**Comment by alikins** [comment] 2016-06-06 15:46
Something like:

```
---
- name: site playbook
  hosts: all
  tasks:
    - name: debug ansible_host
      debug: var=ansible_host
    - name: local_action debug ansible_ssh_host
      local_action: debug var=ansible_ssh_host
    - name: local_action debug ansible_host
      local_action: debug var=ansible_host
    - name: local_action uri test
      local_action: uri url=https://api.github.com/repos/ansible/ansible/issues/16139 method=GET
      register: github_api_result
    - name: debug github_api_result
      debug: var=github_api_result
    - name: local_action uri at ansible_host
      local_action: uri url=http://{{ ansible_host }}/index.html method=GET
      register: uri_result
    - name: debug uri_result
      debug: var=debug_uri_result
```

For the 'local_Action uri at ansible_host', I see requests to http://localhost/index.html.

I'm note entirely sure what the correct behavior here is supposed to be.

**Comment by sivel** [comment] 2016-06-06 15:49
So, just as a note, the documentation does specify that `local_action` is roughly shorthand for `delegate_to: localhost`.  In which case, I feel that `ansible_host` being listed as `localhost` seems correct.

Some solutions are:
1. use `inventory_hostname`
2. if you need `ansible_host` for the actual host (not localhost), and `invenentory_hostname` does not suffice, try: `hostvars[inventory_hostname]['ansible_host']`

**Comment by bcoca** [comment] 2016-06-06 15:51
This is expected as the `ansible_host` reflects the host 'to connect/connected to' not the ip of `inventory_hostname` unless that is what was connected to. 

Closing as it is not a bug

**Closed as completed by bcoca** 2016-06-06 15:51 UTC
Labels: bug
