### ISSUE TITLE
Silent pass of missing handler on notify

### ISSUE THREAD

**Issue by sdarwin** [ansible/ansible#16099] opened 2016-06-02 12:00 UTC
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel f9c4fdab40) last updated 2016/05/24 13:16:23 (GMT +200)
  lib/ansible/modules/core: (detached HEAD a64d72d7bc) last updated 2016/05/24 13:16:41 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD d2900e856b) last updated 2016/05/24 13:16:48 (GMT +200)
  config file =
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

none
##### OS / ENVIRONMENT

Ubuntu 16.04
##### SUMMARY

If a handler is notified, then even if the handler is missing the playbook completes successfully without errors or warnings.
##### STEPS TO REPRODUCE

```
- debug: msg="test handler"
  changed_when: true
  notify:
    - nonexistent_handler
```

then run the playbook.

##### EXPECTED RESULTS

PLAY RECAP , failed=1
##### ACTUAL RESULTS

```
NOTIFIED HANDLER nonexistent_handler
ok: [localhost] => {
    "msg": "test handler"
}

PLAY RECAP *********************************************************************
localhost                  : ok=12   changed=1    unreachable=0    failed=0
```

**Comment by dagwieers** [comment] 2016-06-09 14:13
This is a duplicate of #14923

**Comment by bcoca** [comment] 2016-06-09 14:18
closing as dupe

**Closed as completed by bcoca** 2016-06-09 14:18 UTC
Labels: bug
