### ISSUE TITLE
Please un-deprecate hash_behaviour=merge

### ISSUE THREAD

**Issue by lawsontyler** [ansible/ansible#72421] opened 2020-10-30 19:19 UTC
##### SUMMARY

Removing `hash_behaviour=merge` will decimate the maintainability of variables in Ansible.  It will be easier to find a new tool than try and deal with re-writing every single permutation of every single hash merge...and then try to _maintain_ that over time.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

core

##### ADDITIONAL INFORMATION

Ansible's sane management of variable precedence + `hash_behaviour=merge` allows me to manage the complexity of my systems very well.

Removing `hash_behaviour=merge` is going to explode the complexity of my, and likely many other users', variables - instead of a few hundred lines of variables, we're going to have to manage thousands of lines of the exact same variables & values over and over.

Could you imagine if, instead of `from ansible import constants as C` in the Ansible core, you re-wrote all the constants over and over in each file that needs it?

Obviously, that's really dumb.  A quick search shows that it's used in 81 different places.  No reputable developer would think "It makes perfect sense to duplicate these lines 81 times!"

That's the core of the issue here.  I don't want to make the same code change 81 times.  I want to make one change, once.  If you think of variables as "code", a way to solve complex problems in a concise way, using `merge_behaviour=hash` is an extremely easy way to achieve it.

Please don't punish users who use it correctly because some users use it wrong.

**Comment by sivel** [comment] 2020-10-30 19:20
Duplicate of https://github.com/ansible/ansible/issues/72021

**Closed as completed by sivel** 2020-10-30 19:20 UTC

**Comment by GhengisKeen** [comment] 2020-11-09 08:16
We are in the same situation as lawsontyler and others who are in the ticket marked as duplicate (which has also been closed).
What is the appropriate location to 'appeal' this change if this is not the right spot?

We are now put into quite a bind just because a few people do not read up on the implications of enabling this flag.
