### ISSUE TITLE
apt autoremove not working

### ISSUE THREAD

**Issue by mboehm21** [ansible/ansible#59293] opened 2019-07-19 12:01 UTC
##### SUMMARY
apt-module does not autoremove old packages.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
apt

##### ANSIBLE VERSION

```
ansible 2.8.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15+ (default, Nov 27 2018, 23:36:35) [GCC 7.3.0]
```

##### CONFIGURATION

```

```

##### OS / ENVIRONMENT
Ubuntu 18.04

##### STEPS TO REPRODUCE
Task
```
- name: Cleaning up (apt)
  become: yes
  apt:
    autoclean: yes
    autoremove: yes
    update_cache: yes
    purge: yes
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

```
On run:
```
TASK [setup : Cleaning up (apt)] ********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
 [WARNING]: Could not find aptitude. Using apt-get instead

changed: [server]

```

##### EXPECTED RESULTS
Old dependencies are gone.

##### ACTUAL RESULTS
Old packages are still there:

```
root@server:~# LANG=C apt-get autoremove
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  linux-headers-4.15.0-43 linux-headers-4.15.0-43-generic linux-image-4.15.0-43-generic linux-modules-4.15.0-43-generic linux-modules-extra-4.15.0-43-generic
0 upgraded, 0 newly installed, 5 to remove and 0 not upgraded.
After this operation, 334 MB disk space will be freed.
Do you want to continue? [Y/n] 

```

```paste below

```

**Comment by mkrizek** [comment] 2019-07-19 12:07
This has been already reported. Closing this as a duplicate of https://github.com/ansible/ansible/issues/38791.

As a workaround use `autoclean` and `autoremove` in separate tasks.

If you have further questions please stop by IRC or the mailing list:

* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Closed as completed by mkrizek** 2019-07-19 12:07 UTC
