### ISSUE TITLE
OpenBSD md5 problem (fixed in upstream, still want to workaround? [mpd])

### ISSUE THREAD

**Issue by mbucc** [ansible/ansible#3754] opened 2013-08-04 23:36 UTC
The copy task (ansible 1.2.2) returns

```
warning: md5sum command failed unusually, please report this to the list so it can be fixed
```

if the destination file does not exist.  For example,

```
- name: Create rc.conf.local to startup nginx and Redis
  copy: src=rc.conf.local dest=/etc/rc.conf.local
```

outputs 

```
TASK: [Create rc.conf.local to startup nginx and Redis] ****************************
warning: md5sum command failed unusually, please report this to the list so it can be fixed
command: [u'(/usr/bin/md5sum /etc/rc.conf.local 2>/dev/null)', u'(/sbin/md5sum -q /etc/rc.conf.local 2>/dev/null)', u'(/usr/bin/digest -a md5 /etc/rc.conf.local 2>/dev/null)', u'(/sbin/md5 -q /etc/rc.conf.local 2>/dev/null)', u'(/usr/bin/md5 -n /etc/rc.conf.local 2>/dev/null)', u'(/bin/md5 -q /etc/rc.conf.local 2>/dev/null)']
----
output: {'stdout': '', 'stderr': '', 'rc': 0}
```

---

When I run the command manually, the output (on stderr) is:

```
$ /bin/md5 -q /etc/rc.conf.local
md5: cannot open /etc/rc.conf.local: No such file or directory
$
```

**Comment by eest** [comment] 2013-08-04 23:55
This is not something that is wrong with ansible. The problem is that the md5 binary on OpenBSD had a bug that made it return 0 even when the file did not exist. I ran into this and patched it: http://marc.info/?l=openbsd-tech&m=136448136005238&w=2

This was later commited to the tree: http://marc.info/?l=openbsd-cvs&m=136461136711218&w=2

I think the proper fix is to patch the md5 binary (it is what i have been doing personally) based on what is in OpenBSD CVS.

**Comment by mpdehaan** [comment] 2013-08-05 00:00
The above sounds reasonable.  Though I'm wondering a bit if we can still read through the output and workaround this for those that haven't applied the latest updates.

**Comment by eest** [comment] 2013-08-05 00:26
That is up to you of course. I have used the copy module in my playbooks to install a fixed version of the binary early on. It will only be necessary for 5.3 and earlier. The problem with this approach is of course that it is not easy to figure it out for someone who just triggered the problem.

**Comment by mbucc** [comment] 2013-08-05 00:40
I will apply the patch and rebuild md5.  Thanks Patrik.

**Comment by mpdehaan** [comment] 2013-09-09 15:34
Sounds like fix is upstream, so closing.

**Closed as completed by mpdehaan** 2013-09-09 15:34 UTC
Labels: bug, bsd
