### ISSUE TITLE
Inventory vars, vars_files and role vars inconsistencies (?)

### ISSUE THREAD

**Issue by gmiroshnykov** [ansible/ansible#4172] opened 2013-09-19 12:19 UTC
Okay, first of all let me point you to the repository I've created to illustrate these bug(s) and provide the actual steps to reproduce:
https://github.com/laggyluke/ansible-bug

**If the following explanations turns out too complicated, just run the example and compare expected output to actual output.**

So here's the long story.

My inventory file looks like this:

```
127.0.0.1

[all:vars]
env=development
```

I'm using the `env` inventory variable to differentiate between development, staging and production environments by loading variables from files like this:

```
vars_files:
  - "environments/common.yml"
  - "environments/{{ env }}.yml"
```

So `environments/common.yml` contains the common variables for all environments, while `environments/development.yml` contains the variables specific to development environment.

To illustrate this bug, I'm defining and re-defining a single variable - `message`.

Next, I'm using this variable in two contexts - directy:

```
tasks:
  - debug: msg="task message - {{ message }}"
```

and indirectly, by assigning it to `echo.message` variable that is being used by `echo` role:

```
roles:
  - role: echo
    echo:
      message: '{{ message }}'
```

Internally, `echo` role does basically the same thing:

```
- debug: msg="role message - {{ echo.message }}"
```

Now, my whole playbook looks like this:

```
- hosts: all
  gather_facts: false
  connection: local

  vars_files:
    - "environments/common.yml"
    - "environments/{{ env }}.yml"

  roles:
    - role: echo
      echo:
        message: '{{ message }}'

  tasks:
    - debug: msg="task message - {{ message }}"
```

So my expected output would be:

```
PLAY [all] ********************************************************************
127.0.0.1: importing .../ansible-bug/environments/development.yml

TASK: [debug msg="role message - this is development"] ********************************
ok: [127.0.0.1] => {"item": "", "msg": "role message - this is development"}

TASK: [debug msg="task message - this is development"] ********************************
ok: [127.0.0.1] => {"msg": "task message - this is development"}

PLAY RECAP ********************************************************************
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0
```

And the actual output is:

```
PLAY [all] ********************************************************************
127.0.0.1: importing .../ansible-bug/environments/development.yml

TASK: [debug msg="role message - this is common"] *****************************
ok: [127.0.0.1] => {"item": "", "msg": "role message - this is common"}

TASK: [debug msg="task message - this is common"] *****************************
ok: [127.0.0.1] => {"msg": "task message - this is development"}

PLAY RECAP ********************************************************************
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0
```

I tried to debug this on my own, but the variable handling code is way out of my comfort zone :(

**Comment by mpdehaan** [comment] 2013-09-19 12:30
edit: nm

**Comment by mpdehaan** [comment] 2013-09-19 12:36
I may be a bit confused here, I see you have common listed before env and I was thinking you had them backwards.  We'll investigate.

**Comment by gmiroshnykov** [comment] 2013-09-19 12:39
Ah, thanks!

The reason I'm not using group_vars here is because my actual setup is a bit more complicated.
I use two directories - `environments` for public variables and `secrets` for somewhat secret production variables like DB passwords etc.
I keep `environments` in the main repository and add `secrets` as a git submodule, so that if a developer doesn't have access to `secrets`, he can still bring up a local development environment.

My current code looks like this:

```
vars_files:
  - "environments/common.yml"
  - [ "environments/{{ env }}.yml", "environments/empty.yml" ]
  - [ "secrets/{{ env }}.yml", "environments/empty.yml" ]
```

(`empty.yml` is just an empty YAML file (`{}`), so that Ansible won't complain when environments/something.yml or secrets/something.yml is not found)

I'm afraid I won't be able to do the same with group_vars.
Maybe with some symlinks juggling... but I'd rather avoid that.

**Comment by resmo** [comment] 2013-09-24 14:04
passing vars works as expected:

```
ansible-playbook -i inventory bug.yml --extra-vars env=development
```

hope that helps for debugging...

**Comment by mpdehaan** [comment] 2013-09-26 16:00
This is actually not a bug and it took us a while to realize.

Because task variable name information is not inventory scoped, (headers apply to different hosts and it could be different for each host)

As you will notice it is correct when actually passed to the module

If anything the one thing we could do is detect there was an inventory sourced variable also defined and _not_ template the task name.

**Comment by mpdehaan** [comment] 2013-09-26 16:03
Wait, I think I confused myself

**Comment by mpdehaan** [comment] 2013-09-26 16:03
It looks like role variables are evaluated too soon until at last possible time.

**Comment by mpdehaan** [comment] 2013-09-26 16:03
the task name is not a bug, the action value being wrong is, in other words

**Comment by jimi-c** [comment] 2013-10-07 14:55
@laggyluke I think role defaults and group/host variables are more suited for what you're trying to accomplish above. For instance, if you create `roles/echo/defaults/main.yml` with this content:

<pre>
message: this is the default message
</pre>

And then run it, you'll see this (note: I've created `name:` entries for your debug statements, since as @mpdehaan pointed out that's a known limitation with inventory variables):

<pre>
PLAY [all] ******************************************************************** 
TASK: [echo | role message] *************************************************** 
ok: [127.0.0.1] => {"item": "", "msg": "role message - this is the default message"}
TASK: [task message] ********************************************************** 
ok: [127.0.0.1] => {"msg": "task message - this is the default message"}
</pre>

Now, if you create `group_vars/all` with this content:

<pre>
---
environment: development
</pre>

You'll see this during the run:

<pre>
PLAY [all] ******************************************************************** 
127.0.0.1: importing /root/testing/copied/ansible-bug/environments/development.yml
TASK: [echo | role message] *************************************************** 
ok: [127.0.0.1] => {"item": "", "msg": "role message - this is development"}
TASK: [task message] ********************************************************** 
ok: [127.0.0.1] => {"msg": "task message - this is development"}
</pre>

Finally, as @resmo pointed out above, using `--extra-vars` also causes your playbook to run as expected.

**Comment by jimi-c** [comment] 2013-10-07 15:14
After a little more discussion, we're going to go ahead and close this, if you continue to have problems regarding this issue, please let us know. Thanks!

**Closed as completed by jimi-c** 2013-10-07 15:14 UTC
Labels: bug

**Comment by gmiroshnykov** [comment] 2013-10-07 20:34
Thanks @jimi-c!

As I've mentioned before, my actual setup is a bit more complicated and I'd rather not use group_vars in this case.
I tried to keep test case as simple as possible to illustrate this bug, but I can provide a more complex test case that better reflects my intentions, as this one clearly looks silly.

I don't actually care about task names, that known issue doesn't bother me much.
What I care about is role vars values.
I do use defaults in my actual code, I just skipped them here because they don't affect this behaviour.

The workaround by @resmo does work, but it's just that - a workaround.
I still believe original bug exists and should be fixed.
Unfortunately, I'm not that familiar with the codebase, so I can only ask for help here.

To be honest, I've stumbled on this bug when I tried to fix yet another bug - the inconsistency in hash_behaviour=merge, because apparently #3114 didn't cover all the cases.
I thought that when I'll see the actual fix for this bug, I'll be able to come up with a fix for hash_behaviour on my own.

**Comment by resmo** [comment] 2013-10-07 21:21
This was just a quick debugging test, not really a workaround.

And I also tested this:

```
ansible-playbook -i development bug.yml
```

so the inventory_file basename is `development`

```
- hosts: all 
  gather_facts: false
  connection: local

  vars_files:
    - environments/common.yml
    - environments/{{ inventory_file }}.yml

  roles:
    - role: echo
      echo:
        message: '{{ message }}'

  tasks:
    - debug: msg="task message - {{ message }}
```

but this not work neither as I would have expected. I don't like this behaviour, it looks wrong to me.
