### ISSUE TITLE
Alphabetical group_var precedence is not documented

### ISSUE THREAD

**Issue by GriffithLea** [ansible/ansible#19604] opened 2016-12-21 16:23 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vars in inventory file

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

RHEL 7.2

##### SUMMARY

Just changing the name of a group alters the var values that hosts get.

##### STEPS TO REPRODUCE

Given this inventory file:

glm1 
glm2 
glm3

[CG_xyzzy]
glm1
glm3

[CG_xyzzy:vars]
testvar=xyzzy

[IG_GriffIG]
glm1
glm2
glm3

[IG_GriffIG:vars]
testvar=GriffIG

...I run this command:

# ansible CG_xyzzy -m debug -a var=testvar
glm3 | SUCCESS => {
    "testvar": "GriffIG"
}
glm1 | SUCCESS => {
    "testvar": "GriffIG"
}

I then change the name of the group “CG_xyzzy” to “xyzzy”:

glm1 
glm2 
glm3

[xyzzy]
glm1
glm3

[xyzzy:vars]
testvar=xyzzy

[IG_GriffIG]
glm1
glm2
glm3

[IG_GriffIG:vars]
testvar=GriffIG

…and re-run the command (adjusting for the name change):

# ansible xyzzy -m debug -a var=testvar
glm1 | SUCCESS => {
    "testvar": "xyzzy"
}
glm3 | SUCCESS => {
    "testvar": "xyzzy"

```yaml

```

##### EXPECTED RESULTS

I expected the result to be the same regardless of what I called the group.

##### ACTUAL RESULTS

The result changes depending on the name of the group.

```

```

**Comment by nitzmahone** [comment] 2016-12-22 20:18
This is by design: Ansible inventory is *not hierarchical*, it's flat. Group vars are applied alphabetically (to provide stability within an otherwise static inventory). When the same var is defined by more than one group, hosts that belong to multiple defining groups will see the value from the alphabetically last defining group.

**Comment by GriffithLea** [comment] 2016-12-30 02:33
OK, thanks for the explanation. I thought that from reading http://docs.ansible.com/ansible/playbooks_variables.html that the last one loaded would win, which I guess is still true - I just didn't expect the group name to affect the load order. File order is what I would have expected, either first found or last. Where in the docs can I find information about this alphabetical sorting of the group names? Before I filed the issue I suspected that an alpha sort was being performed on the group names, so I looked around and could not find anything about it one way or another.

**Comment by nitzmahone** [comment] 2017-01-03 17:26
Hrm, looks like that particular detail got lost in the variable precedence docs rewrite that happened during 2.0...

**Comment by bcoca** [comment] 2017-01-03 17:30
we are also adding a new 'priority' feature to let users change this

**Comment by GriffithLea** [comment] 2017-03-08 19:53
@nitzmahone, I am not completely convinced that the group names are sorted alphabetically. Consider the following inventory file:
```
beehive02
beehive03
beehive04

[ANDYS_NODES]
beehive03
beehive04

[ANDYS_NODES:vars]
testvar=foo

[GRIFFS_NODES]
beehive03
beehive04

[GRIFFS_NODES:vars]
testvar=bar

[YSOBELS_NODES]
beehive03
beehive04

[YSOBELS_NODES:vars]
testvar=baz
```
If I run:
```
# ansible ANDYS_NODES -m debug -a 'var=testvar'
beehive04 | SUCCESS => {
    "testvar": "foo"
}
beehive03 | SUCCESS => {
    "testvar": "foo"
}
# ansible GRIFFS_NODES -m debug -a 'var=testvar'
beehive04 | SUCCESS => {
    "testvar": "foo"
}
beehive03 | SUCCESS => {
    "testvar": "foo"
}
# ansible YSOBELS_NODES -m debug -a 'var=testvar'
beehive03 | SUCCESS => {
    "testvar": "foo"
}
beehive04 | SUCCESS => {
    "testvar": "foo"
}
```
...shouldn't I get "baz" for all of these? Thinking perhaps you misspoke and it's actually the alphabetically _first_ defining group, I changed ANDYS_NODES to ZANDYS_NODES in the inventory file and ran:
```
# ansible ZANDYS_NODES -m debug -a 'var=testvar'
beehive04 | SUCCESS => {
    "testvar": "foo"
}
beehive03 | SUCCESS => {
    "testvar": "foo"
}
```
Now I'm really confused. Why am I still getting "foo"? Moving the group that defines testvar=foo to the other end of the alphabet should have produced a different result, if what you say is true.

This was all done with:
```
# ansible --version
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

**Comment by andygeorge** [comment] 2017-10-31 17:40
@bcoca Is the configurable priority still something you guys are planning on adding?

**Comment by bcoca** [comment] 2017-10-31 18:49
@andygeorge already exists, look at http://docs.ansible.com/ansible/devel/intro_inventory.html#how-variables-are-merged

which also contains the docs that this ticket was a request for, so closing now.

**Closed as completed by bcoca** 2017-10-31 18:49 UTC
Labels: affects_2.2, affects_2.3, support:core, bug, docs
