### ISSUE TITLE
Role dependencies are skipped incorrectly when a dep has multiple parents and the first of those parents is skipped

### ISSUE THREAD

**Issue by ivanshaovchev** [ansible/ansible#9292] opened 2014-10-08 15:04 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.2
##### Environment:

Centos 6
##### Summary:

Role dependencies are not executed if the the role is alphabetically below the dependency.
##### Steps To Reproduce:

```
playbook.yml 
roles:
  - {role: maven, tags: ["maven"]}
  - {role: scala, tags: ["scala"]}
  - {role: openjdk, tags: ["openjdk"]}

roles/maven/tasks/main.yml
- name: Install Maven
  ...
roles/maven/meta/main.yml
dependencies:
  - {role: openjdk}

roles/scala/tasks/main.yml
- name: Install Scala
  ...
roles/scala/meta/main.yml
dependencies:
  - {role: openjdk}

roles/openjdk/tasks/main.yml
- name: Install OpenJDK
  ...
```

If you run the playbook with tags=maven the OpenJDK dependency is executed. If you run it with tags=scala  OpenJDK dependency is not executed.
##### Expected Results:

Role dependency to be executed. 
##### Actual Results:

Not executed.

**Comment by jimi-c** [comment] 2014-10-08 18:22
@ivanshaovchev this has nothing to do with the roles being alphabetical, and is a coincidence. The issue here is that the common dependency is marked as skipped when the first parent including it is skipped, so that when the second parent role is run the dep is still marked as skipped.

**Comment by solomongifford** [comment] 2015-01-22 21:06
Confirmed that this bug still exists.

**Comment by dexterbt1** [comment] 2015-06-02 17:10
I was hit by this bug also; subscribing...

**Comment by jimi-c** [comment] 2015-06-24 03:26
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is sample output using your example above:

<pre>
# ansible-playbook -vv test.yml --tags=scala
1 plays in test.yml
PLAY: ***************************************************************************
TASK [openjdk : openjdk : debug msg=in the openjdk tasks] ***********************
ok: [localhost] => {
    "msg": "in the openjdk tasks", 
    "changed": false
}
TASK [scala : scala : debug msg=in the scala tasks] *****************************
ok: [localhost] => {
    "msg": "in the scala tasks", 
    "changed": false
}
PLAY RECAP **********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
# ansible-playbook -vv test.yml --tags=maven
1 plays in test.yml
PLAY: ***************************************************************************
TASK [openjdk : openjdk : debug msg=in the openjdk tasks] ***********************
ok: [localhost] => {
    "msg": "in the openjdk tasks", 
    "changed": false
}
TASK [maven : maven : debug msg=in the maven tasks] *****************************
ok: [localhost] => {
    "msg": "in the maven tasks", 
    "changed": false
}
PLAY RECAP **********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-06-24 03:26 UTC
Labels: P2, bug
