### ISSUE TITLE
TestModules.py fails on library/windows/setup.ps1

### ISSUE THREAD

**Issue by tima** [ansible/ansible#7865] opened 2014-06-20 14:36 UTC
We're getting a failed unit test that seems to be related to the Windows additions. 

Seems TestModules.py is checking every modules with ast however library/windows/setup.ps1 is not something ast can parse hence the test failure.

Since library/windows/\* is in powershell should this module be skipping those or doing a different type of syntax test?

00:00:31.360 ======================================================================
00:00:31.360 FAIL: test_ast_parse (TestModules.TestModules)
00:00:31.360 ----------------------------------------------------------------------
00:00:31.360 Traceback (most recent call last):
00:00:31.360   File "/.statelite/tmpfs/data/VCS/est-ax008-d/logs01/jenkins/workspace/ansible-devel/test/units/TestModules.py", line 30, in test_ast_parse
00:00:31.360     assert len(ERRORS) == 0, "get_docstring errors: %s" % ERRORS
00:00:31.360 AssertionError: get_docstring errors: [('/.statelite/tmpfs/data/VCS/est-ax008-d/logs01/jenkins/workspace/ansible-devel/library/windows/setup.ps1', SyntaxError('invalid syntax', ('<unknown>', 23, 1, '$result = New-Object psobject @{\n'))), ('/.statelite/tmpfs/data/VCS/est-ax008-d/logs01/jenkins/workspace/ansible-devel/library/windows/slurp.ps1', SyntaxError('invalid syntax', ('<unknown>', 20, 1, '$params = Parse-Args $args;\n'))), ('/.statelite/tmpfs/data/VCS/est-ax008-d/logs01/jenkins/workspace/ansible-devel/library/windows/win_feature.ps1', SyntaxError('invalid syntax', ('<unknown>', 22, 27, 'Import-Module Servermanager;\n'))), ('/.statelite/tmpfs/data/VCS/est-ax008-d/logs01/jenkins/workspace/ansible-devel/library/windows/win_get_url.ps1', SyntaxError('invalid syntax', ('<unknown>', 22, 1, '$params = Parse-Args $args;\n'))), ('/.statelite/tmpfs/data/VCS/est-ax008-d/logs01/jenkins/workspace/ansible-devel/library/windows/win_msi.ps1', SyntaxError('invalid syntax', ('<unknown>', 22, 1, '$params = Parse-Args $args;\n'))), ('/.statelite/tmpfs/data/VCS/est-ax008-d/logs01/jenkins/workspace/ansible-devel/library/windows/win_ping.ps1', SyntaxError('invalid syntax', ('<unknown>', 20, 1, '$params = Parse-Args $args;\n'))), ('/.statelite/tmpfs/data/VCS/est-ax008-d/logs01/jenkins/workspace/ansible-devel/library/windows/win_stat.ps1', SyntaxError('invalid syntax', ('<unknown>', 20, 1, '$params = Parse-Args $args;\n'))), ('/.statelite/tmpfs/data/VCS/est-ax008-d/logs01/jenkins/workspace/ansible-devel/library/windows/win_user.ps1', SyntaxError('invalid syntax', ('<unknown>', 23, 1, '$adsi = [ADSI]"WinNT://$env:COMPUTERNAME"\n'))), ('/.statelite/tmpfs/data/VCS/est-ax008-d/logs01/jenkins/workspace/ansible-devel/library/windows/setup.ps1', SyntaxError('invalid syntax', ('<unknown>', 23, 1, '$result = New-Object psobject @{\n'))), ('/.statelite/tmpfs/data/VCS/est-ax008-d/logs01/jenkins/workspace/ansible-devel/library/windows/slurp.ps1', SyntaxError('invalid syntax', ('<unknown>', 20, 1, '$params = Parse-Args $args;\n'))), ('/.statelite/tmpfs/data/VCS/est-ax008-d/logs01/jenkins/workspace/ansible-devel/library/windows/win_feature.ps1', SyntaxError('invalid syntax', ('<unknown>', 22, 27, 'Import-Module Servermanager;\n'))), ('/.statelite/tmpfs/data/VCS/est-ax008-d/logs01/jenkins/workspace/ansible-devel/library/windows/win_get_url.ps1', SyntaxError('invalid syntax', ('<unknown>', 22, 1, '$params = Parse-Args $args;\n'))), ('/.statelite/tmpfs/data/VCS/est-ax008-d/logs01/jenkins/workspace/ansible-devel/library/windows/win_msi.ps1', SyntaxError('invalid syntax', ('<unknown>', 22, 1, '$params = Parse-Args $args;\n'))), ('/.statelite/tmpfs/data/VCS/est-ax008-d/logs01/jenkins/workspace/ansible-devel/library/windows/win_ping.ps1', SyntaxError('invalid syntax', ('<unknown>', 20, 1, '$params = Parse-Args $args;\n'))), ('/.statelite/tmpfs/data/VCS/est-ax008-d/logs01/jenkins/workspace/ansible-devel/library/windows/win_stat.ps1', SyntaxError('invalid syntax', ('<unknown>', 20, 1, '$params = Parse-Args $args;\n'))), ('/.statelite/tmpfs/data/VCS/est-ax008-d/logs01/jenkins/workspace/ansible-devel/library/windows/win_user.ps1', SyntaxError('invalid syntax', ('<unknown>', 23, 1, '$adsi = [ADSI]"WinNT://$env:COMPUTERNAME"\n')))]

**Comment by jimi-c** [comment] 2014-06-20 15:09
Closing, dupe of #7864.

**Closed as completed by jimi-c** 2014-06-20 15:09 UTC
Labels: windows
