### ISSUE TITLE
template_from_string and template_from_file not existing anymore in Ansible 2.x and no available documentation

### ISSUE THREAD

**Issue by ansiblejunky** [ansible/ansible#19778] opened 2017-01-02 15:53 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
template.py

##### ANSIBLE VERSION
ansible 2.2.0.0
  config file = /automation/ansible/playbooks/ansible.cfg
  configured module search path = ['library', '../library']

##### CONFIGURATION
Creating a custom action_plugin called "template_config" that uses the template module.

##### OS / ENVIRONMENT
CentOS 6.5

##### SUMMARY
We are upgrading our plugins/modules to Ansible 2.2.x and we used the following functions that existed in Ansible 1.8.2 source (lib\ansible\utils\template.py):

template_from_string
template_from_file

However, these are no longer available in the Ansible 2.2.x source. Why were they removed and what is the recommended replacement? I find many times functions replaced but no documentation that helps us replace deprecated functions. In this case it was not deprecated but eliminated. 
How do we perform these 2 operations with Ansible 2.2.x?

##### STEPS TO REPRODUCE
Try to use/find the above listed functions

##### EXPECTED RESULTS
Same as it did in Ansible 1.8.2

##### ACTUAL RESULTS
Functions do not exist in Ansible 2.2.x

**Comment by bcoca** [comment] 2017-01-02 17:14
Those functions were not for use in custom plugins, they are internal to the Ansible API, which is not guaranteed to be available across versions.  As such we do not deprecate these functions as we do with `module_utils/` code that is implicitly shared for modules.

We ARE working on creating a documented part of the API we will make efforts to keep backwards compatible, but the templating interface was completely rewritten in 2.0, I would advise looking at the new template class. I'm going to go even farther and advise more not using such a module and using the existing template one, modules that combine existing modules and filters are normally a bad idea, it is better to create a role. 

So I'm sorry to say, I'm going to close this as it is not a bug and not something we ever claimed to support, if you need more help adapting your module please try the devel mailing list or IRC channel.

   * IRC: #ansible-devel on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-devel

**Closed as completed by bcoca** 2017-01-02 17:14 UTC
Labels: affects_2.2, module
