### ISSUE TITLE
Increase Ansible's performance

### ISSUE THREAD

**Issue by DebianRoxx** [ansible/ansible#17528] opened 2016-09-12 19:16 UTC
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

core
##### ANSIBLE VERSION

```
ansible 2.1.1.0 (detached HEAD 35da6ba9d1) last updated 2016/07/22 09:48:22 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 45128c8bab) last updated 2016/08/31 10:57:13 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 511752e53a) last updated 2016/08/31 10:57:13 (GMT +200)
  config file = /root/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
stdout_callback = skippy
callback_whitelist = timer, profile_tasks
pipelining = True
```
##### OS / ENVIRONMENT

Debian GNU/Linux 8.5 (jessie)
##### SUMMARY

Performance could be better.
##### STEPS TO REPRODUCE

```

---
 - name: perfs tests
   hosts: localhost
   connection: local
   vars:
     db:
         - "db1"
         - "dbXXX" (XXX = 2 to 200)
   tasks:
     - command: ls "{{ item }}"
       with_items: "{{ db }}"
```
##### EXPECTED RESULTS

Shell execution of same work take less than 1 second.
So, there is much room to improve performance.
In real production with a lot of parametrized roles, tasks, dependencies, and lot of variables, execution is very slow.

```
 time for i in {1..200}; do ls "db$i"; done
real    0m0.240s
user    0m0.016s
sys     0m0.036s
```
##### ACTUAL RESULTS

```
Monday 12 September 2016  21:16:27 +0200 (0:00:37.596)       0:00:37.623 ****** 
=============================================================================== 
command ---------------------------------------------------------------- 37.60s
Playbook run took 0 days, 0 hours, 0 minutes, 37 seconds
```

**Comment by sivel** [comment] 2016-09-12 19:28
Just as a reference, `raw` is more similar to your shell command, than running via `command`.  There is also a speed improvement by setting `gather_facts: false`.

**Comment by DebianRoxx** [comment] 2016-09-12 19:51
Ok, I have disabled gather_facts, there is no much improvement.

For shell, I have replaced command by this, it's more similar ? 
`time for i in {1..200}; do sh -c "ls db$i"; done`

It took less than 1 second for shell execution.

I have the feeling that there is a thing in Ansible that slowdown product : in my real playbooks/roles, even tasks in skipped block are slow to be skipped so I make small tests perfs to try showing you the problem and to improve Ansible.

**Comment by robinro** [comment] 2016-09-16 16:01
@DebianRoxx To see what's going on, you can set `export ANSIBLE_DEBUG=1` in your environment. This generates very verbose output including timing of internal commands.

For your example I get for one iteration

```
  4210 1474040202.50248: transferring module to remote
  4210 1474040202.50570: done transferring module to remote
  4210 1474040202.50590: _low_level_execute_command(): starting
  4210 1474040202.50597: _low_level_execute_command(): executing: /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python XXX/.ansible/tmp/ansible-tmp-1474040202.49-43571704664512/command; rm -rf "XXX/.ansible/tmp/ansible-tmp-1474040202.49-43571704664512/" > /dev/null 2>&1 && sleep 0'
  4210 1474040202.50601: in local.exec_command()
  4210 1474040202.50605: opening command with Popen()
  4210 1474040202.50844: done running command with Popen()
  4210 1474040202.50855: getting output with communicate()
  4210 1474040202.64399: done communicating
  4210 1474040202.64407: done with local.exec_command()
  4210 1474040202.64414: _low_level_execute_command() done: rc=0, stdout=
{"changed": true, "end": "2016-09-16 17:36:42.632281", "stdout": "", "cmd": ["ls", "db4"], "rc": 2, "start": "2016-09-16 17:36:42.629654", "stderr": "ls: cannot access db4: No such file or directory", "delta": "0:00:00.002627", "invocation": {"module_args": {"warn": true, "executable": null, "_uses_shell": false, "_raw_params": "ls \"db4\"", "removes": null, "creates": null, "chdir": null}}, "warnings": []}
, stderr=
  4210 1474040202.64430: done with _execute_module (command, {'_ansible_version': '2.1.1.0', '_ansible_selinux_special_fs': ['fuse', 'nfs', 'vboxsf', 'ramfs'], '_ansible_no_log': False, u'_raw_params': u'ls "db4"', '_ansible_verbosity': 0, '_ansible_syslog_facility': 'LOG_USER', '_ansible_diff': False, '_ansible_debug': True, '_ansible_check_mode': False})
  4210 1474040202.64438: handler run complete
  4210 1474040202.64451: attempt loop complete, returning result
  4129 1474040202.64589: worker 0 has data to read
  4129 1474040202.64638: got a result from worker 0: <ansible.executor.task_result.TaskResult object at 0x7f570bed5c10>
  4129 1474040202.64643: sending result: [u'v2_runner_item_on_failed', u'<ansible.executor.task_result.TaskResult object at 0x7f570bed5c10>']
  4129 1474040202.64647: done sending result
  4126 1474040202.64905: got result from result worker: [u'v2_runner_item_on_failed', u'<ansible.executor.task_result.TaskResult object at 0x7f570b793490>']
failed: [localhost] (item=db4) => {"changed": true, "cmd": ["ls", "db4"], "delta": "0:00:00.002627", "end": "2016-09-16 17:36:42.632281", "failed": true, "item": "db4", "rc": 2, "start": "2016-09-16 17:36:42.629654", "stderr": "ls: cannot access db4: No such file or directory", "stdout": "", "stdout_lines": [], "warnings": []}
  4210 1474040202.65070: starting attempt loop
  4210 1474040202.65074: running the handler
  4210 1474040202.65158: ZIPLOADER: using cached module: XXX/.ansible/tmp/ansible-local-tmpv2yH2s/ziploader_cache/command-ZIP_DEFLATED
  4210 1474040202.65271: _low_level_execute_command(): starting
  4210 1474040202.65277: _low_level_execute_command(): executing: /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1474040202.65-236075696653050 `" && echo ansible-tmp-1474040202.65-236075696653050="` echo $HOME/.ansible/tmp/ansible-tmp-1474040202.65-236075696653050 `" ) && sleep 0'
  4210 1474040202.65284: in local.exec_command()
  4210 1474040202.65288: opening command with Popen()
  4210 1474040202.65690: done running command with Popen()
  4210 1474040202.65704: getting output with communicate()
  4210 1474040202.66361: done communicating
  4210 1474040202.66369: done with local.exec_command()
  4210 1474040202.66376: _low_level_execute_command() done: rc=0, stdout=ansible-tmp-1474040202.65-236075696653050=XXX/.ansible/tmp/ansible-tmp-1474040202.65-236075696653050
, stderr=
```

That's 161 ms, which is close enough to your total timing. Of those 135 ms are spent waiting for the `command` module. The `raw` module get's the same job done in 3 ms, which is close to your shell time.

The thing that would potentially speed this up with the `command` module as well would be to pass the full list to the module instead of calling it 200 times. This is done for the `apt`,`yum`,`zypper`, ... modules. 

So this bug is either
- the `command` module is slow (which is known, since it tests/validates a lot of things) or
- `with_items` is slow, which can be worked around in some places by passing lists to modules

**Comment by DebianRoxx** [comment] 2016-09-16 16:37
Thanks, I didn't know the ANSIBLE_DEBUG variable. This might be useful to understand why my production playbook and roles with a lot of tasks are slow (even the skipped one).
I have also shown that a playbook with a lot of parametrized roles can be really really slow to execute, more there are roles, more the timelapse beetween tasks increase.
I'll try to make a dedicated example next week to isolate problem.

**Comment by jimi-c** [comment] 2016-09-20 19:06
@DebianRoxx Ansible is doing a lot more than simply running that shell command locally. As such, you are comparing apples to oranges here. We are always interested in making Ansible faster, however it will never be as fast as simply running a shell command directly.

**Comment by DebianRoxx** [comment] 2016-09-20 19:21
@jimi-c A lot more is a bit exaggerated, see the command module here, it's pretty simple : https://github.com/ansible/ansible-modules-core/blob/devel/commands/command.py
As I said before,  I'll try to make a dedicated example this week to isolate problem if I have time.

For now, I'm optimizing roles to bypass execution of lot of tasks : make multiples `include xxx.yml` + `when` in `role-xxx/tasks/main.yml` instead of big `main.yml` with when on some big `block`. With theses measures, I reduced a lot of execution time, for example on one my playbook, Ansible executes ~350 tasks instead of ~1600 for the same job !

**Comment by jimi-c** [comment] 2016-09-20 19:23
@DebianRoxx it's really not. We parse inventory, we parse vars, we do a lot of work on top of simply running the command. On top of that, the command is run through Python, not directly, so there's overhead there which is unavoidable. Optimizing playbooks and roles is always advisable, but there is a floor to the performance you'll hit and it will be well above executing commands directly.

**Comment by DebianRoxx** [comment] 2016-09-20 19:44
Yes, i'm aware that there is necessarily some pre operations before running commands.
I make a dumb example which do nothing (`toto` variable is undefined) to illustrate my feeling :

```
---
 - name: Test
   hosts: localhost
   connection: local
   vars:
     server: "localhost"

   roles:
     - { role: /srv/ansible/playbooks/test_perfs/test_role, var="db1" }
    and so on until 200
     - { role: /srv/ansible/playbooks/test_perfs/test_role, var="db200" }
```

file test_role/tasks/main.yml :

```
---
- block:

  - name: test
    apt:
      name: htop
      state: present

  - name: test2
    command: ls

  when: "toto is defined"
  delegate_to: "{{ server }}"
```

Playbook run took 0 days, 0 hours, 0 minutes, 28 seconds. 

Perhaps this dumb test will help to show my feeling. In all cases, I'm pleased that you are interesting about Ansible performance.

**Comment by diclophis** [comment] 2016-10-03 21:54
Our entire devops team has been extremely upset with the performance in the `2.1.1.0` version.

In our benchmarks, our playbook execution time has more than doubled... and the CPU load is un-acceptable in terms of being able to run more than 1/2 `ansible-playbook` processes at a given time.

**Comment by jimi-c** [comment] 2016-10-04 04:31
@diclophis have you tested out devel (now 2.2 RC1)? There have been a lot of improvements over 2.1.

**Comment by pshchelo** [comment] 2016-10-05 18:09
@jimi-c 2.2 RC1 is even worse.

executing a simple playbook that presumably does nothing eats one entire core on my Core i5:

```
$ ansible-playbook 2.2.0.0 (detached HEAD 44faad0593) last updated 2016/10/05 19:42:09 (GMT +300)
  lib/ansible/modules/core: (detached HEAD d66983b43e) last updated 2016/10/05 19:42:16 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD 35132b892f) last updated 2016/10/05 19:42:16 (GMT +300)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

$ cat testcpu.yaml
---
- hosts: all
  gather_facts: no
  tasks:
    - name: do nothing
      command: sleep 30

$ /usr/bin/time --format "%Us user\n%P CPU" ansible-playbook testcpu.yaml --limit localhost
PLAY [all] *********************************************************************

TASK [do nothing] **************************************************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0   

28.50s user
100% CPU
```

devel is the same. On released 2.1.2.0 from PyPI I get about 9% CPU (which is still too much for doing nothing IMO, but way better than 2.2 RC1).

I tend to blame the code in base strategy plugin (and thus default linear strategy), as switching to `strategy: free` results in drop from 100% to 25%.

I have a PR #16560 that tried to address that, and it worked ~3 weeks ago, but since then the code in base strategy plugin has been reworked and I can no longer figure out where the problem is.
Most probably it is around
https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/strategy/__init__.py#L219
(those short sleeps my PR was addressing) but I am not sure any more.

Update: also, using the "raw" module instead of "command" and remote host instead of localhost changes nothing.

**Comment by jimi-c** [comment] 2016-10-05 20:08
@pshchelo this seems to address it:

<pre>
diff --git a/lib/ansible/plugins/strategy/__init__.py b/lib/ansible/plugins/strategy/__init__.py
index 02610e4..57fc83b 100644
--- a/lib/ansible/plugins/strategy/__init__.py
+++ b/lib/ansible/plugins/strategy/__init__.py
@@ -533,6 +535,8 @@ class StrategyBase:
 
             results = self._process_pending_results(iterator)
             ret_results.extend(results)
+            if self._pending_results > 0:
+                time.sleep(0.005)
 
         display.debug("no more pending results, returning what we have") 
</pre>

Thanks for catching that. I'll do some more testing with the above to make sure and then merge it.

**Comment by pshchelo** [comment] 2016-10-06 06:28
@jimi-c my pleasure. With the above fix and the same synthetic "do nothing" playbook now I get about 3% CPU load. Will the fix be backported to stable-2.2?

**Comment by jimi-c** [comment] 2016-10-06 13:45
Yes it will.

**Comment by jimi-c** [comment] 2016-10-06 13:49
@pshchelo I'm going to set it to 0.001 (which it usually was in the past) to make sure there's no major impact in performance, which gives me about 8% usage in your test.

**Comment by jimi-c** [comment] 2016-10-06 13:51
@pshchelo commited in both devel and stable-2.2 now.

**Comment by diclophis** [comment] 2016-10-06 17:23
I feel like adjusting this `sleep` timeout is largely placebo in terms of rooting out the real performance problem...

For example, see attached movie... it shows 1 python process (of the many spawned during a playbook execution) generating >20k unix system calls per second...

![python-making-thousands-of-system-calls-per-second](https://cloud.githubusercontent.com/assets/10122/19162841/63991ddc-8bae-11e6-8c0f-9d5762f9bb84.gif)

What additional research / fixes are being made to address this horrible performance problem? Why has the 15 minute old ansible python process managed to generate over 3 million context switch operations... compared against say, my `mysqld` process on my workstation, which has been running for _weeks_ has only generated less than 1 million?

Also, could we make this timeout configurable via an `ENV` or something...? I have seen no less than 3 PRs changing this value in the past couple of months....

**Comment by pshchelo** [comment] 2016-10-06 18:05
@diclophis that's exactly what PR #16560 is doing - making this sleep interval configurable in ansible.cfg

**Comment by diclophis** [comment] 2016-10-13 23:29
Here is another screenshot of the type of horrible performance we are seeing with the current version of ansible 2.x

<img width="1264" alt="absurd-cpu-usage-for-tasks" src="https://cloud.githubusercontent.com/assets/10122/19370660/eef9fd16-9161-11e6-9210-546edd213575.png">

we are ansible'ing ~16 hosts, and the current tasks present in the screenshot are, adding a user to a group, and ensuring a directory is present, and updating a template file... note there are 2 python process with >80% cpu utilization and several other python processes present

**Comment by lassizci** [comment] 2016-10-20 10:11
Using `hostvars` in templates seems extremely expensive. E.g with something like vpn network role where it's necessary to use every host's hostvars on every host, it will take half an hour with my inventory that's approximately 150 hosts and there are 100-190 variables for each host. Takes a little less if I run it with variables stripped to 20 per host, but the difference isn't too significant. And it's the same with 2.1, 2.2 and current devel. Horribly slow.

But if I use `set_fact` with `run_once` the time taken is about 1/10, even I `set_fact` with a template:

```
- name: gather subset of hostvars
  set_fact:
    __hostvars: "{{ lookup('template', '_variablehelper.j2') }}"
  run_once: true
```

and `_variablehelper.j2` being something like:

```
{% set _gather_keys = ["vpn_networks", "inventory_hostname", "inventory_hostname_short", "external_ip"] %}
{% set _gathered_hostvars = {} %}
{% for _vpn_net in vpn_networks %}
{%   set _ = _gather_keys.append("vpn_ip_" + _vpn_net) %}
{% endfor %}
{% for host in groups.all %}
{%   set _host_vars = {} %}
{%   for var in _gather_keys %}
{%     set _ = _host_vars.update( {var: hostvars[host][var]} ) %}
{%   endfor %}
{%   set _ = _gathered_hostvars.update( {host: _host_vars} ) %}
{% endfor %}
{{ _gathered_hostvars }}
```

then I can use `__hostvars` in templates and that reduced 30 minutes to 3 minutes. I think that's very ugly way and I shouldn't be doing this, but It's 10x speed boost. Still I feel like even that 3 minutes is long time for a single role. Fact gathering isn't the issue here.

**Comment by DebianRoxx** [comment] 2016-11-18 14:01
I just updated Ansible to 2.3.0 (detached HEAD f6437f1b6e).
Can't done yet percentage of gains (some bugs) but things are far faster between tasks. :)

**Comment by jimi-c** [comment] 2016-11-18 19:37
@lassizci hostvars with large inventories (especially if there is a large amount of group_vars/all variables) has always been a very expensive thing to use, unfortunately.

**Comment by jimi-c** [comment] 2016-11-18 19:38
@DebianRoxx if things are looking better, I'll leave it up to you to close this issue. Performance is always an ongoing thing, so I'd hate to leave an issue open indefinitely for it.

**Comment by DebianRoxx** [comment] 2016-11-18 20:18
@jimi-c I will validate and close the ticket next week. First test gave me x5 boost (20 min -> 4 mins) :)

**Comment by DebianRoxx** [comment] 2016-11-23 17:44
First example is always slow, even more : 41 seconds but in my real playbooks, switching between tasks are far faster (x5).

Here first test in debug, we can see that there is 100ms "lost" beetwen "getting output with communicate()" and "done communicating".
If this part could be optimized, I think it will be wonderful.
I'll close ticket tomorrow if there is no other reply.

```
 74600 1479922472.57222: Loading FilterModule 'core' from /root/ansible/lib/ansible/plugins/filter/core.py (found_in_cache=True, class_only=False)
 74600 1479922472.57277: Loading FilterModule 'ipaddr' from /root/ansible/lib/ansible/plugins/filter/ipaddr.py (found_in_cache=True, class_only=False)
 74600 1479922472.57331: Loading FilterModule 'json_query' from /root/ansible/lib/ansible/plugins/filter/json_query.py (found_in_cache=True, class_only=False)
 74600 1479922472.57383: Loading FilterModule 'mathstuff' from /root/ansible/lib/ansible/plugins/filter/mathstuff.py (found_in_cache=True, class_only=False)
 74600 1479922472.57472: Loading TestModule 'core' from /root/ansible/lib/ansible/plugins/test/core.py (found_in_cache=True, class_only=False)
 74600 1479922472.57524: Loading TestModule 'files' from /root/ansible/lib/ansible/plugins/test/files.py (found_in_cache=True, class_only=False)
 74600 1479922472.57573: Loading TestModule 'mathstuff' from /root/ansible/lib/ansible/plugins/test/mathstuff.py (found_in_cache=True, class_only=False)
 74600 1479922472.57901: Loading ActionModule 'normal' from /root/ansible/lib/ansible/plugins/action/normal.py (found_in_cache=True, class_only=False)
 74600 1479922472.57960: starting attempt loop
 74600 1479922472.58013: running the handler
 74600 1479922472.58100: ANSIBALLZ: using cached module: /root/.ansible/tmp/ansible-local-74593lHoERo/ansiballz_cache/command-ZIP_DEFLATED
 74600 1479922472.58263: _low_level_execute_command(): starting
 74600 1479922472.58318: _low_level_execute_command(): executing: /bin/sh -c '/usr/bin/python && sleep 0'
 74600 1479922472.58375: in local.exec_command()
 74600 1479922472.58426: opening command with Popen()
 74600 1479922472.59141: done running command with Popen()
 74600 1479922472.59218: getting output with communicate()
 74600 1479922472.81117: done communicating
 74600 1479922472.81161: done with local.exec_command()
 74600 1479922472.81206: _low_level_execute_command() done: rc=0, stdout=
{"changed": true, "end": "2016-11-23 18:34:32.792499", "stdout": "", "cmd": ["ls", "db13"], "rc": 2, "start": "2016-11-23 18:34:32.774065", "stderr": "ls: impossible d'acc\u00e9der \u00e0 db13: Aucun fichier ou dossier de ce type", "delta": "0:00:00.018434", "invocation": {"module_args": {"warn": true, "executable": null, "_uses_shell": false, "_raw_params": "ls \"db13\"", "removes": null, "creates": null, "chdir": null}}, "warnings": []}
, stderr=
 74600 1479922472.81270: done with _execute_module (command, {'_ansible_version': '2.3.0', '_ansible_selinux_special_fs': ['fuse', 'nfs', 'vboxsf', 'ramfs'], '_ansible_no_log': False, '_ansible_module_name': u'command', u'_raw_params': u'ls "db13"', '_ansible_verbosity': 0, '_ansible_syslog_facility': u'LOG_USER', '_ansible_diff': False, '_ansible_debug': True, '_ansible_check_mode': False})
 74600 1479922472.81312: handler run complete
 74600 1479922472.81352: attempt loop complete, returning result
failed: [localhost] (item=db13) => {"changed": true, "cmd": ["ls", "db13"], "delta": "0:00:00.018434", "end": "2016-11-23 18:34:32.792499", "failed": true, "item": "db13", "rc": 2, "start": "2016-11-23 18:34:32.774065", "stderr": "ls: impossible d'accéder à db13: Aucun fichier ou dossier de ce type", "stdout": "", "stdout_lines": [], "warnings": []}
```

**Comment by bcoca** [comment] 2016-11-23 17:52
Not sure we can do much there, this is the actual code (using python's multiprocess library):
```
        display.debug("getting output with communicate()")
        stdout, stderr = p.communicate(in_data)
        display.debug("done communicating")
```

**Closed as completed** 2016-11-25 20:39 UTC
Labels: performance, affects_2.1, bug
