### ISSUE TITLE
Ansible 2.0.0.2 command --list-tags shows no tags

### ISSUE THREAD

**Issue by 196194** [ansible/ansible#14125] opened 2016-01-26 10:28 UTC
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible-playbook 2.0.0.2
##### Ansible Configuration:

nothing special
##### Environment:

Debian 8.2
##### Summary:

Ansible-playbook option --list-tags shows no tags
##### Steps To Reproduce:

ansible-playbook -i inventories/tad-hosts 05-apache.yml -l tadprsc01 --list-tags
##### Expected Results:

playbook: 05-apache.yml

  play #1 (apache-hosts):       TAGS: [tag1,tag2,tag3]
      TASK TAGS: [tag1,tag2,tag3]
##### Actual Results:

playbook: 05-apache.yml

  play #1 (apache-hosts):       TAGS: []
      TASK TAGS: []

**Comment by jimi-c** [comment] 2016-01-26 21:40
Can you share an example of the playbook(s) causing this? It is a known issue that tags from include files do not show up in --list-tags output, so if your playbooks are comprised of all includes this would be expected.

**Comment by a31amit** [comment] 2016-02-29 23:55
@jimi-c .. Thanks for the info.. I noticed the same problem in my case, I am using roles and there are multiple include files ...

**Comment by briceburg** [comment] 2016-03-03 02:25
99% of our tags are defined in "included" tasks -- as we organize our playbooks into boilerplate base playbooks that include tasks from shared/non-boilerplate common tasks. The use of `ansible-playbook --list-tags` is prevelant under this architecture and this bug is preventing us from upgrading to 2.0 (which is something we really want to do for the docker connection driver & exception handling). I read that this would be fixed shortly after the release -- any update here?

Thanks!

**Comment by vallettea** [comment] 2016-03-03 08:53
I upgraded to 2.0.1.0 and I still have the problem.
Here is my configuration in `all.yml`:

```
---
# This playbook deploys all our services

- name: apply common configuration to all nodes (tooling)
  hosts: all
  remote_user: root
  roles:
    - common
  tags: common

- name: deploy a service called immoviz
  hosts: immoviz
  remote_user: root
  vars:
    service_name: immoviz
  roles:
    - immoviz
  tags: immoviz
```

and when I use `ansible-playbook all.yml -t immoviz` the roles of `common` are also played.

**Comment by digi691** [comment] 2016-03-15 21:31
I'm in a similar boat as briceburg with pretty much all my tags sitting in the include files.  Jimi-c points out that this is expected in 2.0.1.0.  Since this is still open, I'm assuming the expected behavior is that it should be showing your tags?  The same behavior is also happening with --list-tasks, I assume for the same reason...

**Comment by vallettea** [comment] 2016-03-22 15:25
Can anyone at ansible consider giving an explanation about how to deal with tags in the 2.0 ? I provided some code samples.

**Comment by vallettea** [comment] 2016-03-23 09:26
For my side of the problem, I finally understood what was going on. If your top task (immoviz and common) in the example I provided have a tag and you use `ansible-playbook all.yml -t immoviz`, ansible still plays the `setup` of the common but none of the inner tasks are executed.

**Comment by jimi-c** [comment] 2016-05-11 13:56
Based on testing against all stable branches and devel, it appears this issue is resolved. As such we will close it now. If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2016-05-11 13:56 UTC
Labels: bug

**Comment by briceburg** [comment] 2016-05-12 03:13
@jimi-c is there a commit you can link that contains the fix for this? Would be interested to see code changes. I'll test using -devel tomorrow. Thanks!

**Comment by jimi-c** [comment] 2016-05-12 14:13
@briceburg no, sorry. You could probably dig one up using git blame if you really wanted to know.
