### ISSUE TITLE
Check mode should be more obvious and should be available inside playbook

### ISSUE THREAD

**Issue by njia** [ansible/ansible#15424] opened 2016-04-15 02:33 UTC
##### ISSUE TYPE

- Feature Idea
##### ANSIBLE VERSION

```
ansible 2.0.1.0
```
##### SUMMARY

--check currently is only available as command line option and sometimes people forget so it would be nice if there is something like `check_mode: True` in playbook so we don't have to worry about command line options.

The output of check mode run should be more obvious to indicate that this is a check only.

Thanks

**Comment by robinro** [comment] 2016-05-30 17:27
This is a duplicate of https://github.com/ansible/ansible/issues/12498.

**Comment by bcoca** [comment] 2016-06-01 16:13
closing as dupe

**Closed as completed by bcoca** 2016-06-01 16:13 UTC
Labels: feature
