### ISSUE TITLE
Python path isn't always /usr/bin

### ISSUE THREAD

**Issue by egon1024** [ansible/ansible#205] opened 2012-04-23 18:09 UTC
Trying to get ansible working on FreeBSD, during the initial setup the 'ansible all -m ping --ask-pass' command is failing with the following:

```
ctuininga@erbium$ ansible all -m ping --ask-pass
SSH password: 
127.0.0.1 | FAILED >> {
    "failed": true,
    "msg": "",
    "parsed": false
}

stderr: [127.0.0.1] => bash: /tmp/ansible.a9YwrP/ping: /usr/bin/python: bad interpreter: No such file or directory
```

On FreeBSD systems, Python is often installed at /usr/local/bin.  A more flexible shebang line would be something along the lines of:
# !/usr/bin/env python

(env is pretty consistently found in /usr/bin/ across platforms)

**Comment by skinp** [comment] 2012-04-23 18:17
In Arch, I also had to change for:

```
#!/usr/bin/env python2
```

since by default /usr/bin/python is version 3 and /usr/bin/env python also uses python3...

**Comment by mpdehaan** [comment] 2012-04-23 19:34
We use env in the integration branch already...this will be released tonight

**Comment by mpdehaan** [comment] 2012-04-23 19:34
(closing, since we use env already on the integration branch)

**Closed as completed by mpdehaan** 2012-04-23 19:34 UTC

**Comment by voidzero** [comment] 2012-10-07 12:26
I cloned the repo today, yet can still reproduce this error. Could you please explain how to make ansible use /usr/bin/env (FreeBSD) and /usr/bin/python2 (Archlinux)?

**Comment by mpdehaan** [comment] 2012-10-07 13:10
Usr bin env will look for something named python (not python2) in your path so I would just make a symlink in ~/usr/bin named python linking to python2 and ensuring that was at the top of your path

See also docs on ansible_python_interpreter for the remote side
