### ISSUE TITLE
Share vars/defaults across roles with include_role does not work

### ISSUE THREAD

**Issue by sjentzsch** [ansible/ansible#26294] opened 2017-06-30 17:26 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
include_role

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
(defaults)

##### OS / ENVIRONMENT
Ubuntu 16.04

##### SUMMARY
Using include_role defaults/vars cannot be shared across roles, even when setting `private` to False/no.

##### STEPS TO REPRODUCE
```yaml
---
- hosts: localhost

#  roles:
#    - role1
#    - role2

  tasks:
    - include_role:
        name: role1
        private: no

    - include_role:
        name: role2
        private: no
```

Inside role1 there is vars/main.yml with:
```
role1_var: "role1var"
```

And on role2 there is:
```
- debug:
  msg: "{{ role1_var }}"
```

Execute: `ansible-playbook -i localhost -v test.yml`

##### EXPECTED RESULTS
I expected no errors.

##### ACTUAL RESULTS

```
TASK [role2 : debug] ***************************************************************************************************************************************************************************************
task path: /home/sjentzsch/Seafile/Eigene Dokumente/Server/setup/ansible/roles/role2/tasks/main.yml:6
fatal: [localhost]: FAILED! => {
    "failed": true, 
    "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'role1_var' is undefined\n\nThe error appears to have been in '/home/sjentzsch/Seafile/Eigene Dokumente/Server/setup/ansible/roles/role2/tasks/main.yml': line 6, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- debug:\n  ^ here\n"
}
```

**Comment by sjentzsch** [comment] 2017-09-20 22:25
Any updates? (-:

**Comment by duck-rh** [comment] 2017-10-12 08:09
Quack,

I've got the same situation with 2.3.2 and a similar case: in my situation role2 include_role on role1 and need to use its variables in vars/main.yml. Setting private to False or forcing vars_from does not help.

I tested on 2.4.0 and same behavior.

**Comment by pilou-** [comment] 2017-10-20 10:53
I have investigated a little bit:
- I found a recent problem with the unit tests related to `include_role` on devel branch: #31920 
- `private` parameter isn't tested
- I am not sure if the value of `private` parameter is taken in account

Using roles and playbook in the description of this issue and a custom unit test, I wasn't able to found a revision were `defaults/main.yml` or `vars/main.yml` were shared across roles.

**Comment by bcoca** [comment] 2017-10-20 15:59
dupe of #21890

**Closed as completed by bcoca** 2017-10-20 15:59 UTC
Labels: affects_2.3, module, c:executor/task_executor, c:playbook/role_include, support:core, include_role, bug
