### ISSUE TITLE
windows modules not working

### ISSUE THREAD

**Issue by masti93** [ansible/ansible#49360] opened 2018-11-30 10:06 UTC
##### SUMMARY

Windows modules are not working

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_ping

##### ANSIBLE VERSION

```paste below
ansible 2.7.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]

```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/var/scripts/ansible/hosts']
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/var/scripts/ansible/roles']

```

##### OS / ENVIRONMENT

lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.6 (stretch)
Release:        9.6
Codename:       stretch

##### STEPS TO REPRODUCE

```yaml

ansible -m win_ping --ask-vault-pass hostname -vvv
```

##### ACTUAL RESULTS

```
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/windows/win_ping.ps1
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 139, in run
    res = self._execute()
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 603, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/action/normal.py", line 46, in run
    result = merge_hash(result, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/action/__init__.py", line 829, in _execute_module
    cmd = self._connection._shell.build_module_command(environment_string, shebang, cmd, arg_path=args_file_path).strip()
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/shell/powershell.py", line 1591, in build_module_command
    bootstrap_wrapper = pkgutil.get_data("ansible.executor.powershell", "bootstrap_wrapper.ps1")
  File "/usr/lib/python2.7/pkgutil.py", line 591, in get_data
    return loader.get_data(resource_name)
  File "/usr/lib/python2.7/pkgutil.py", line 255, in get_data
    return open(pathname, "rb").read()
IOError: [Errno 2] No such file or directory: '/usr/lib/python2.7/dist-packages/ansible/executor/powershell/bootstrap_wrapper.ps1'

hostname | FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}


```

**Comment by jborean93** [comment] 2018-11-30 10:16
Duplicate of https://github.com/ansible/ansible/issues/49353. Thanks for reporting this @masti93, please follow 49353 for more details.

**Closed as completed by jborean93** 2018-11-30 10:16 UTC
Labels: windows
