### ISSUE TITLE
Tasks aren't loaded when 'include_tasks' task is tagged

### ISSUE THREAD

**Issue by machacekondra** [ansible/ansible#35183] opened 2018-01-22 14:13 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

include_tasks

##### ANSIBLE VERSION

```
ansible-playbook 2.5.0 (fix_disk_fail_state baa7f749aa) last updated 2018/01/19 16:12:12 (GMT +200)
  config file = ~.ansible.cfg
  configured module search path = [u'/home/omachace/workspace/ansible/lib/ansible/modules/cloud/ovirt']
  python version = 2.7.14 (default, Jan 17 2018, 14:28:32) [GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]
```

##### SUMMARY

When user uses tags and he tag a `include_tasks` task, this task isn't executed, but any other task, is executed.

##### STEPS TO REPRODUCE

```yaml

tasks.yml
---------------------------------------------
- hosts: localhost
  connection: local

  tasks:
    - name: Include tasks1
      include_tasks: tasks1.yml
      tags:
        - tasks1

    - name: Include tasks2
      include_tasks: tasks2.yml
      tags:
        - tasks2

tasks1.yml:
------------------------------------------------
- name: Task1
  debug:
    msg: "Task 1"

tasks2.yml:
------------------------------------------------
- name: Task2
  debug:
    msg: Task 2
```

##### EXPECTED RESULTS

```bash
ansible-playbook --tags tasks1 tasks.yml 

PLAY [localhost] **************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [Include tasks1] *********************************************************************************************************************************************************************************************
included: /home/omachace/playbooks/tasks1.yml for 127.0.0.1

TASK [Task1] ******************************************************************************************************************************************************************************************************
ok: [127.0.0.1] => {
    "msg": "Task 1"
}

PLAY RECAP ********************************************************************************************************************************************************************************************************
127.0.0.1                  : ok=3    changed=0    unreachable=0    failed=0   

```

##### ACTUAL RESULTS

```bash
$ ansible-playbook --tags tasks1 tasks.yml 

PLAY [localhost] **************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [Include tasks1] *********************************************************************************************************************************************************************************************
included: /home/omachace/playbooks/tasks1.yml for 127.0.0.1

PLAY RECAP ********************************************************************************************************************************************************************************************************
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0   
```

```

```

This is regression from: https://github.com/ansible/ansible/pull/33595

**Comment by machacekondra** [comment] 2018-01-22 14:14
@maorlipchuk

**Comment by sivel** [comment] 2018-01-22 15:38
The problem is related to whether attributes should be merged down onto the tasks within an include.

For 2.4.3 we plan to restore this functionality, but have no plans of restoring it for 2.5:

See https://github.com/ansible/ansible/issues/35065 for more info.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Closed as completed by sivel** 2018-01-22 15:38 UTC
Labels: module, support:core, affects_2.5, bug
