### ISSUE TITLE
traceback in authorized_key module

### ISSUE THREAD

**Issue by jcftang** [ansible/ansible#4677] opened 2013-10-26 03:39 UTC
As of commit 43f48a2e021f12cfe3547904ce0a97c7dfdbf893 the authorized_keys module isn't behaving the same as previously... 

```
TASK: [authorized_key user=root key="{{lookup('file', '~/.ssh/id_rsa.pub')}}"] *** 
fatal: [192.168.251.101] => failed to parse: Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-1382758475.3-265029518752899/authorized_key", line 1306, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-1382758475.3-265029518752899/authorized_key", line 367, in main
    results = enforce_state(module, module.params)
  File "/home/vagrant/.ansible/tmp/ansible-1382758475.3-265029518752899/authorized_key", line 338, in enforce_state
    existing_keys[parsed_new_key[0]] = parsed_new_key
TypeError: list indices must be integers, not str

fatal: [192.168.251.102] => failed to parse: Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-1382758475.31-217556902122643/authorized_key", line 1306, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-1382758475.31-217556902122643/authorized_key", line 367, in main
    results = enforce_state(module, module.params)
  File "/home/vagrant/.ansible/tmp/ansible-1382758475.31-217556902122643/authorized_key", line 338, in enforce_state
    existing_keys[parsed_new_key[0]] = parsed_new_key
TypeError: list indices must be integers, not str

fatal: [192.168.251.103] => failed to parse: Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-1382758475.31-93600817829628/authorized_key", line 1306, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-1382758475.31-93600817829628/authorized_key", line 367, in main
    results = enforce_state(module, module.params)
  File "/home/vagrant/.ansible/tmp/ansible-1382758475.31-93600817829628/authorized_key", line 338, in enforce_state
    existing_keys[parsed_new_key[0]] = parsed_new_key
TypeError: list indices must be integers, not str

fatal: [192.168.251.100] => failed to parse: Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-1382758475.3-50489411809009/authorized_key", line 1306, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-1382758475.3-50489411809009/authorized_key", line 367, in main
    results = enforce_state(module, module.params)
  File "/home/vagrant/.ansible/tmp/ansible-1382758475.3-50489411809009/authorized_key", line 338, in enforce_state
    existing_keys[parsed_new_key[0]] = parsed_new_key
TypeError: list indices must be integers, not str


FATAL: all hosts have already failed -- aborting
```

**Comment by jimi-c** [comment] 2013-10-26 06:29
Are you testing with the latest version of devel? This seems to be a duplicate of #4599, which I thought was fixed by some patches I have recently committed. If not, you may wish to try the patch @jctanner posted in #4596.

**Comment by jcftang** [comment] 2013-10-26 14:21
@jimi-c I'm running the latest head, and it does appear to be a duplicate of #4599, it's currently broken with the above output. I tried the patches in #4596 but they don't apply cleanly to the latest devel branch.

Apologies for creating a duplicate, we can move this discussion to #4599 if necessary.

**Comment by jimi-c** [comment] 2013-10-26 14:33
Sure, I'll rebase that patch and get it to you ASAP.

**Comment by jcftang** [comment] 2013-10-26 14:43
Okay, thanks. I probably won't be able to test till monday.

**Comment by jcftang** [comment] 2013-10-27 23:26
Not to loose track of things, but commit 9b1fe455c65e901c9d50a75b68eae77f231aa51d breaks lookups (I guess this should be logged as a new ticket if it hasn't already), so I'm not sure if it affect this regression.

**Comment by jimi-c** [comment] 2013-10-28 15:05
@jctanner Could you please open a new issue for that? I don't believe anyone else has reported it and we do not want to lose track of it as you mention.

**Comment by jctanner** [comment] 2013-10-28 15:06
@jcftang

**Comment by phillipuniverse** [comment] 2013-10-28 15:53
Definitely confirm that this is happening with me with latest devel (73dbab7). I attempted to pull in the changes from @jctanner in #4596 (did not apply cleanly, attempted manually) but I still get the stack trace.

Also, to @jcftang's comment about broken lookups; I saw the same thing but it looks like the latest devel has that problem resolved.

Ready to test once anybody has a fix in for this.

**Comment by jimi-c** [comment] 2013-10-28 16:55
Here is a diff that should apply cleanly against devel: https://gist.github.com/jimi-c/7200498

Let me know if this fixes the issue for you.

**Comment by phillipuniverse** [comment] 2013-10-28 18:22
@jimi-c tried it out, works with some keys and fails with others. Stack trace:

``` console
fatal: [<removed-ip>] => failed to parse: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1382984611.84-100490294667312/authorized_key", line 1337, in <module>
    main()
  File "/root/.ansible/tmp/ansible-1382984611.84-100490294667312/authorized_key", line 375, in main
    results = enforce_state(module, module.params)
  File "/root/.ansible/tmp/ansible-1382984611.84-100490294667312/authorized_key", line 346, in enforce_state
    existing_keys[parsed_new_key[0]] = parsed_new_key
TypeError: list indices must be integers, not str
```

**Comment by phillipuniverse** [comment] 2013-10-28 18:26
Gimme a few and I'll post some failing keys

**Comment by jimi-c** [comment] 2013-10-28 18:30
Could you also verify what revision you're testing against? The last line in your traceback above is 346, but that line on my system (with my patch above applied) is 339.

**Comment by phillipuniverse** [comment] 2013-10-28 18:38
FYI, looks like this happens whenever the authorized_keys file does not already exist on the remote machine. When the file already exists it works as expected (no matter what key).

The above was tested on 73dbab7 but it looks like there have been a few changes since then. Testing with absolute latest now (9249cf578d5214cd8b8687c63aa9f24a0e3ea405)

**Comment by jimi-c** [comment] 2013-10-28 18:49
Ahh yes, I can reproduce that, nice catch! I'll fix this in a moment.

**Comment by jimi-c** [comment] 2013-10-28 18:52
This was the culprit:

<pre>
diff --git a/library/system/authorized_key b/library/system/authorized_key
index 2695d2c..5c40e7d 100644
--- a/library/system/authorized_key
+++ b/library/system/authorized_key
@@ -238,7 +238,7 @@ def parsekey(raw_key):
 def readkeys(filename):
 
     if not os.path.isfile(filename):
-        return []
+        return {}
 
     keys = {}
     f = open(filename)
</pre>

I'm going to push all of this up to devel now, so you can re-pull in a minute.

**Comment by phillipuniverse** [comment] 2013-10-28 18:52
Ok awesome, thanks.

**Closed as completed** 2013-10-28 18:53 UTC
Labels: needs_info, bug

**Comment by phillipuniverse** [comment] 2013-10-28 19:00
Sweet, looks like everything is in working order with your latest push to devel. Thanks a ton for the quick resolution!

**Comment by jimi-c** [comment] 2013-10-28 19:02
No problem, thanks again for isolating the issue :)

**Comment by jcftang** [comment] 2013-10-28 23:49
+1 it's closed and all, but its working for me now as well

**Comment by jimi-c** [comment] 2013-10-29 00:28
@jcftang Yeah I closed it via the commit, as I had enough reports of things being fixed to feel confident in pushing it up. Thanks!
