### ISSUE TITLE
ansible_sudo ignored when ansible_ssh_user is not set

### ISSUE THREAD

**Issue by DSpeichert** [ansible/ansible#10317] opened 2015-02-22 01:05 UTC
Issue Type: Bug Report
Ansible Version: ansible 1.8.4
Environment: Debian 8.0
Summary: ansible_sudo ignored when anisble_ssh_user is not set
Steps To Reproduce:
- be root
- in /root/.ssh/config set a username and key for a host
- put the host in a group and in group_vars add "sudo: yes"

Expected Results: Ansible uses sudo
Actual Results: Ansible does not use sudo
Workaround: repeate the username in group_vars as ansible_ssh_user

**Comment by bcoca** [comment] 2015-02-23 15:40
From the code, sudo should get ignored if the user is already root, I'm not sure how your workaround would change this.

**Comment by DSpeichert** [comment] 2015-02-23 19:14
The user is root on the machine running Ansible, the remote user is still not root because of this (/root/.ssh/config):

```
Host 10.0.*
User ubuntu
IdentityFile /etc/ansible/keys/admin-test.pem
```

**Comment by bcoca** [comment] 2015-02-23 23:09
are you specifying  -u in the ansible-playbook commandline?

**Comment by DSpeichert** [comment] 2015-02-24 05:58
No, why?

**Comment by bcoca** [comment] 2015-02-24 14:01
it could cause this issue you are seeing, when you specify a user with -u it won't read your .ssh/config

**Comment by DSpeichert** [comment] 2015-02-24 16:47
I am not specifying a user with -u and it does correctly read my .ssh/config. Otherwise, I'd never be able to connect. The problem is in executing commands, Ansible connects fine, inspects the nodes but obviously fails to install packages as it runs with regular user permissions instead of using sudo.

**Comment by bcoca** [comment] 2015-02-24 17:05
I cannot reproduce the problem, can you post a minimal reproduction?

**Comment by jctanner** [comment] 2016-05-26 21:36
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us. 

Testing this on the version you have specified, we cannot reproduce this problem.

Our reasons and evidence for this are:
- Version 2.x's "become" keyword makes your scenario functional based on my testing.

And we suggest that:

Example inventory:

```
$ cat inventory 
[agroup]
el6host

[agroup:vars]
ansible_become=yes
ansible_become_pass=redhat
```

As such, we are most likely going to close this ticket.  Should you disagree with this conclusion, you may also wish to join our mailing lists, which are very active:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Closed as completed by jctanner** 2016-05-26 21:36 UTC
Labels: P2, bug
