### ISSUE TITLE
ENV var set in raw module incorrect

### ISSUE THREAD

**Issue by Hubbitus** [ansible/ansible#11849] opened 2015-08-04 16:06 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible --version
$ ansible --version
ansible 2.0.0

$ rpm -q ansible
ansible-2.0-0.2.git.7d8afad.fc24.noarch
##### Ansible Configuration:

Irrelevant
##### Environment:

Fedora 22.
##### Summary:

When you using raw module you can't set variables as it possible in bash and sh.
##### Steps To Reproduce:

Playbook:

```
- hosts: 127.0.0.1
  connection: local

  tasks:
    - name: EAXMPLE raw commands
      raw: date ; hostname

    - name: EAXMPLE raw vars0 - run, but variable not set
      raw: VAR="qwerty"; echo $VAR

    - name: EAXMPLE raw vars1 - fail
      raw: VAR="qwerty" ; echo $VAR
```

Result:

```
TASK [setup] ********************************************************************
ok: [127.0.0.1]

TASK [EAXMPLE raw commands] *****************************************************
ok: [127.0.0.1] => {"changed": false, "rc": 0, "stderr": "", "stdout": "Вт авг  4 18:59:51 MSK 2015\nhubbitus.taskdata.note\n"}

TASK [EAXMPLE raw vars0 - run, but variable not set] ****************************
ok: [127.0.0.1] => {"changed": false, "rc": 0, "stderr": "", "stdout": "\n"}

TASK [EAXMPLE raw vars1 - fail] *************************************************
fatal: [127.0.0.1]: FAILED! => {
    "changed": false, 
    "rc": 1, 
    "stderr": "/bin/sh: -c: line 0: syntax error near unexpected token `;'\n/bin/sh: -c: line 0: `; echo $VAR'\n", 
    "stdout": ""
}
```
##### Expected Results:
1. Both variants: 'raw: VAR="qwerty"; echo $VAR' and 'raw: VAR="qwerty" ; echo $VAR' run normally and on stdout return string 'qwerty'
##### Actual Results:

"stdout": "\n" in one case and fail to run in another.

**Comment by bcoca** [comment] 2015-08-04 16:45
so I cannot reproduce, I get:

```
ok: [localhost] => {"changed": false, "rc": 0, "stderr": "", "stdout": "Tue Aug  4 12:44:50 EDT 2015\nlocalhost\n", "stdout_lines": ["Tue Aug  4 12:44:50 EDT 2015", "localhost"]}
...
ok: [localhost] => {"changed": false, "rc": 0, "stderr": "", "stdout": "qwerty\n", "stdout_lines": ["qwerty"]}
...
ok: [localhost] => {"changed": false, "rc": 0, "stderr": "", "stdout": "qwerty\n", "stdout_lines": ["qwerty"]}

```

**Comment by Hubbitus** [comment] 2015-08-04 16:54
What version you are use?

**Comment by bcoca** [comment] 2015-08-04 17:01
ansible 2.0.0 (devel 1ad3e44650) last updated 2015/08/04 11:56:19 (GMT -400)

**Comment by cchurch** [comment] 2015-08-04 18:39
Could this be a result of the same issue fixed by https://github.com/ansible/ansible/pull/11835, where `raw` was silently discarding `key=value` args?

**Comment by Hubbitus** [comment] 2015-08-05 09:07
Yes! It work in faf4c3bb6cfc99b50db696d0bead9861c5ff562c. Thank you.

**Comment by cchurch** [comment] 2015-08-05 09:10
:grin:

**Closed as completed by cchurch** 2015-08-05 09:10 UTC
Labels: needs_info, bug
