### ISSUE TITLE
Since upgrading to Ansible 2.3, Ansible insists on evaluating group_vars even when overriden in hosts:vars

### ISSUE THREAD

**Issue by JeanFred** [ansible/ansible#28990] opened 2017-09-04 13:42 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Variable handling

##### ANSIBLE VERSION

```
ansible 2.3.1.0
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY

Ansible now insists on evaluating variables in  `group_vars` even if overridden in  `hosts`

##### STEPS TO REPRODUCE
In `group_vars` i have a file `all` (for all my environments), in which I have `testing_host: "{{ groups.loadbalancer_production[0] }}"

In my `hosts` directory, the `stage` hostfiles contains `testing_host=127.0.0.1`
Before upgrading to 2.3, this was working fine.

##### EXPECTED RESULTS
`testing_host` correctly contains 127.0.0.1

##### ACTUAL RESULTS
```
'dict object' has no attribute 'loadbalancer_production'
```

**Comment by victorock** [comment] 2017-10-26 10:58
@JeanFred  where is located your inventory file?

**Comment by JeanFred** [comment] 2017-10-26 11:01
> @JeanFred where is located your inventory file?
It is usually in `<app>/hosts` or `app/hosts/production` files, and selected via `-i`

**Comment by sivel** [comment] 2018-06-26 14:41
Duplicate of https://github.com/ansible/ansible/issues/33320

**Closed as completed by sivel** 2018-06-26 14:41 UTC
Labels: affects_2.3, support:core, bug
