### ISSUE TITLE
ansible-playbook does not require --ask-vault-pass for single vaulted json file

### ISSUE THREAD

**Issue by dewyze** [ansible/ansible#20530] opened 2017-01-20 22:51 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ansible-vault

##### ANSIBLE VERSION

```
→ ansible --version
ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

I have no unique configuration

##### OS / ENVIRONMENT

OS X El Capitan 10.11.6

##### SUMMARY

If the first/only file I encrypt via ansible-vault is a json file (the json credentails downloaded from GCE for a service account), then ansible-playbook will not prompt for a vault password and `--ask-vault-pass` is not required to run a playbook successfully.

##### STEPS TO REPRODUCE

I imagine this could work similar with anything that involves a json file, but here is what I did.

1. Download a GCE credentials .json file (I imagine this would work with aws or anything that uses json?).
2. Move it to be `group_vars/devboxes/credentials.json`
3. Create the `create_vm.yml` playbook below and the `group_vars/devboxes/vars.yml` listed below.
4. Run the playbook at least once successfully `ansible-playbook create_vm.yml` before encrypting.
    - When I tried this on another machine, it failed until I ran the playbook once with a decrypted creds.json, but then after encrypting the below behavior still occurred)
5. `ansible-vault encrypt group_vars/devboxes/credentials.json`
6. Run the playbook again the same as in step 4
    - Note that `--ask-vault-pass` was not required, but the decryption still occurred.
7. (Optional) If you modify the credentials.json file (after decrypting it) and then re-encrypt it, the playbook will fail. So it doesn't seem to be storing a cached file anywhere, it just does not seem to recognize this playbook as requiring a password.

```yaml
# create_vm.yml playbook
- hosts: localhost
  connection: local
  vars_files:
    - "group_vars/devboxes/vars.yml"
  gather_facts: False
  tasks:
  - name: "Creating virtual machine"
    gce:
      instance_names: my-test-instance1
      zone: us-central1-a
      machine_type: g1-small
      image: debian-8
      state: present
      service_account_email: "{{ gce_service_account_email }}"
      credentials_file: "{{ gce_credentials_file }}"
      project_id: "{{ gce_project_id }}"
    register: gce


# group_vars/devboxes/vars.yml
devboxes_gce_project_id: <GCE_PROJECT_ID>
devboxes_gce_service_account_email: <GCE_SERVICE_EMAIL>
devboxes_gce_credentials_file: "{{ playbook_dir }}/group_vars/devboxes/credentials.json"
```

##### EXPECTED RESULTS

I expected to ansible to give me a warning that a file was not decrypted, and require a password prompt or password file.

##### ACTUAL RESULTS

I was not prompted for a password and the play completed successfully.

```
→ ansible-vault encrypt group_vars/devboxes/creds.json
Vault password: 
Encryption successful

→ ansible-playbook create_vm.yml                      

PLAY [localhost] ***************************************************************

TASK [Actually creating machine] ***********************************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0   
```

**Comment by dewyze** [comment] 2017-01-21 15:15
I can also add that when I added an encrypted `vault.yml` that was referenced by the `vars.yml`, I was required to enter a password via `--ask-vault-pass`. However, even with that, it failed until I ran it once successfully without the file being encrypted.

```
→ ansible-playbook create_vm.yml --ask-vault-pass
Vault password: 

PLAY [localhost] ***************************************************************

TASK [Actually creating machine] ***********************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "RSA key format is not supported"}
        to retry, use: --limit @/Users/john/dev/orchestra/create_vm.retry

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1  

→ ansible-vault decrypt group_vars/devboxes/creds.json 
Vault password: 
Decryption successful

→ ansible-playbook create_vm.yml --ask-vault-pass
Vault password: 

PLAY [localhost] ***************************************************************

TASK [Actually creating machine] ***********************************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0

→ ansible-vault encrypt group_vars/devboxes/creds.json
Vault password:
Encryption successful

→ ansible-playbook create_vm.yml --ask-vault-pass
Vault password: 

PLAY [localhost] ***************************************************************

TASK [Actually creating machine] ***********************************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0
```

**Comment by alikins** [comment] 2017-01-23 16:48
Attempted to setup a repro for this without using the gce module at https://github.com/alikins/ansible-bug-repro/tree/master/vault_enc_json_20530/

I get 'ERROR! Decryption failed' errors without --ask-vault-pass

When I try to reproduce without ask-vault-pass (ala the 'runme.sh' there), I get:

```
[fedora-25:vault_enc_json_20530 (master %)]$ bash -x ./runme.sh 
+ ansible-playbook -i hosts -vvv test.yml
Using /home/adrian/.ansible.cfg as config file
ERROR! Decryption failed on /home/adrian/src/ansible-bug-repro/vault_enc_json_20530/group_vars/devboxes/credentials.json
```

running with --ask-vault-pass ('runme-ask-vault-pass.sh') I get:

```
[fedora-25:vault_enc_json_20530 (master %)]$ bash -x ./runme-ask-vault-pass.sh 
+ ansible-playbook -i hosts -vvv --ask-vault-pass test.yml
Using /home/adrian/.ansible.cfg as config file
Vault password: 

PLAYBOOK: test.yml *************************************************************
1 plays in test.yml

PLAY [localhost] ***************************************************************

TASK [debug vaulted json files credentials_file] *******************************
task path: /home/adrian/src/ansible-bug-repro/vault_enc_json_20530/test.yml:8
ok: [localhost] => {
    "_ansible_no_log": false, 
    "_ansible_verbose_always": true, 
    "changed": false, 
    "devboxes_gce_credentials_file": "/home/adrian/src/ansible-bug-repro/vault_enc_json_20530/group_vars/devboxes/credentials.json", 
    "invocation": {
        "module_args": {
            "var": "devboxes_gce_credentials_file"
        }, 
        "module_name": "debug"
    }
}

TASK [copy creds file to /tmp] *************************************************
task path: /home/adrian/src/ansible-bug-repro/vault_enc_json_20530/test.yml:12
Using module file /home/adrian/src/ansible/lib/ansible/modules/core/files/stat.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: adrian
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1485190027.74-25780158552342 `" && echo ansible-tmp-1485190027.74-25780158552342="` echo ~/.ansible/tmp/ansible-tmp-1485190027.74-25780158552342 `" ) && sleep 0'
<localhost> PUT /tmp/tmpETODVs TO /home/adrian/.ansible/tmp/ansible-tmp-1485190027.74-25780158552342/stat.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/adrian/.ansible/tmp/ansible-tmp-1485190027.74-25780158552342/ /home/adrian/.ansible/tmp/ansible-tmp-1485190027.74-25780158552342/stat.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/adrian/.ansible/tmp/ansible-tmp-1485190027.74-25780158552342/stat.py; rm -rf "/home/adrian/.ansible/tmp/ansible-tmp-1485190027.74-25780158552342/" > /dev/null 2>&1 && sleep 0'
Using module file /home/adrian/src/ansible/lib/ansible/modules/core/files/file.py
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1485190027.92-256255119806833 `" && echo ansible-tmp-1485190027.92-256255119806833="` echo ~/.ansible/tmp/ansible-tmp-1485190027.92-256255119806833 `" ) && sleep 0'
<localhost> PUT /tmp/tmpFXCjdq TO /home/adrian/.ansible/tmp/ansible-tmp-1485190027.92-256255119806833/file.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/adrian/.ansible/tmp/ansible-tmp-1485190027.92-256255119806833/ /home/adrian/.ansible/tmp/ansible-tmp-1485190027.92-256255119806833/file.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/adrian/.ansible/tmp/ansible-tmp-1485190027.92-256255119806833/file.py; rm -rf "/home/adrian/.ansible/tmp/ansible-tmp-1485190027.92-256255119806833/" > /dev/null 2>&1 && sleep 0'
ok: [localhost] => {
    "_ansible_no_log": false, 
    "_ansible_parsed": true, 
    "changed": false, 
    "checksum": "80a0170a54b450c409fb8a0afb280ddc4babca08", 
    "dest": "/tmp/vault_enc_json_20530_credentials_file", 
    "diff": {
        "after": {
            "path": "/tmp/vault_enc_json_20530_credentials_file"
        }, 
        "before": {
            "path": "/tmp/vault_enc_json_20530_credentials_file"
        }
    }, 
    "gid": 1000, 
    "group": "adrian", 
    "invocation": {
        "module_args": {
            "backup": null, 
            "content": null, 
            "delimiter": null, 
            "dest": "/tmp/vault_enc_json_20530_credentials_file", 
            "diff_peek": null, 
            "directory_mode": null, 
            "follow": false, 
            "force": false, 
            "group": null, 
            "mode": null, 
            "original_basename": "credentials.json", 
            "owner": null, 
            "path": "/tmp/vault_enc_json_20530_credentials_file", 
            "recurse": false, 
            "regexp": null, 
            "remote_src": null, 
            "selevel": null, 
            "serole": null, 
            "setype": null, 
            "seuser": null, 
            "src": "credentials.json", 
            "state": null, 
            "unsafe_writes": null, 
            "validate": null
        }
    }, 
    "mode": "0664", 
    "owner": "adrian", 
    "path": "/tmp/vault_enc_json_20530_credentials_file", 
    "secontext": "unconfined_u:object_r:user_tmp_t:s0", 
    "size": 89, 
    "state": "file", 
    "uid": 1000
}

TASK [debug not_encrytped_credentials json] ************************************
task path: /home/adrian/src/ansible-bug-repro/vault_enc_json_20530/test.yml:17
ok: [localhost] => {
    "_ansible_no_log": false, 
    "_ansible_verbose_always": true, 
    "changed": false, 
    "devboxes_not_encrypted_credentials_file": "/home/adrian/src/ansible-bug-repro/vault_enc_json_20530/group_vars/devboxes/not_encrypted_credentials.json", 
    "invocation": {
        "module_args": {
            "var": "devboxes_not_encrypted_credentials_file"
        }, 
        "module_name": "debug"
    }
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0   

[fedora-25:vault_enc_json_20530 (master %)]$ cat /tmp/vault_enc_json_20530_credentials_file
{"password": "some_password", "user": "some_user", "groups": ["some_user", "some_group"]}
```

**Comment by alikins** [comment] 2017-01-23 16:50
Was this working before 2.2.1?

**Comment by dewyze** [comment] 2017-01-23 21:40
@alikins I was able to produce an error scenario using your test repo. Would you prefer a PR to that repo or just paste the file contents here?

Additionally, I just started using ansible recently, 2.2.1 is my first version.

**Comment by dewyze** [comment] 2017-01-24 05:01
Here is a bare minimum working case, this assumes you have run this once before encrypting and you have something in your `creds.json`:

```
# test.yml
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: "Creating virtual machine"
    lineinfile:
      dest: "{{ playbook_dir }}/group_vars/devboxes/creds.json"
      line: "test"
      state: absent

# groups_vars/devboxes/creds.json
test
{"password": "some_password", "user": "some_user", "groups": ["some_user", "some_group"]}
```

Here is my output:

```
→ ansible-playbook test.yml                           
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [Creating virtual machine] ************************************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0   

→ ansible-vault encrypt group_vars/devboxes/creds.json                                                                                                                            
Vault password: 
Encryption successful

→ ansible-playbook test.yml                           
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [Creating virtual machine] ************************************************
ok: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   

→ ansible-playbook -i hosts test.yml              
ERROR! Decryption failed on /Users/john/dev/orchestra/group_vars/devboxes/creds.json

→ mv group_vars/devboxes/creds.json group_vars/all/ # THIS INCLUDES UPDATING test.yml

→ ansible-playbook test.yml                        
 [WARNING]: provided hosts list is empty, only localhost is available

ERROR! Decryption failed on /Users/john/dev/orchestra/group_vars/all/creds.json
```

What I have noticed:
- If you run `ansible-playbook -i hosts test.yml` you will get the decryption error.
- If you run `ansible-playbook test.yml` you will not get the decryption error, even if the file is encrypted.
- If you move the `creds.json` file to `group_vars/all/creds.json` (and the reference in the file), then you will always get the decryption error.

**Comment by alikins** [comment] 2017-01-24 16:29
The result I get when duplicating (including some inline comment as shell comments explaining):

```

[repro]$ ansible-playbook -vvv test2.yml
Using /home/adrian/.ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available


PLAYBOOK: test2.yml ************************************************************************************************************************************************************************************************
1 plays in test2.yml

PLAY [localhost] ***************************************************************************************************************************************************************************************************

TASK [Creating virtual machine] ************************************************************************************************************************************************************************************
task path: /home/adrian/src/ansible-bug-repro/vault_enc_json_20530/test2.yml:5
Using module file /home/adrian/src/ansible/lib/ansible/modules/files/lineinfile.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: adrian
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1485274349.63-173252776127846 `" && echo ansible-tmp-1485274349.63-173252776127846="` echo ~/.ansible/tmp/ansible-tmp-1485274349.63-173252776127846 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpcUEmGp TO /home/adrian/.ansible/tmp/ansible-tmp-1485274349.63-173252776127846/lineinfile.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/adrian/.ansible/tmp/ansible-tmp-1485274349.63-173252776127846/ /home/adrian/.ansible/tmp/ansible-tmp-1485274349.63-173252776127846/lineinfile.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /home/adrian/.ansible/tmp/ansible-tmp-1485274349.63-173252776127846/lineinfile.py; rm -rf "/home/adrian/.ansible/tmp/ansible-tmp-1485274349.63-173252776127846/" > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {
    "_ansible_no_log": false,
    "_ansible_parsed": true,
    "backup": "",
    "changed": true,
    "diff": [
        {
            "after": "",
            "after_header": "/home/adrian/src/ansible-bug-repro/vault_enc_json_20530/group_vars/devboxes/creds.json (content)",
            "before": "",
            "before_header": "/home/adrian/src/ansible-bug-repro/vault_enc_json_20530/group_vars/devboxes/creds.json (content)"
        },
        {
            "after_header": "/home/adrian/src/ansible-bug-repro/vault_enc_json_20530/group_vars/devboxes/creds.json (file attributes)",
            "before_header": "/home/adrian/src/ansible-bug-repro/vault_enc_json_20530/group_vars/devboxes/creds.json (file attributes)"
        }
    ],
    "found": 1,
    "invocation": {
        "module_args": {
            "attributes": null,
            "backrefs": false,
            "backup": false,
            "content": null,
            "create": false,
            "delimiter": null,
            "dest": "/home/adrian/src/ansible-bug-repro/vault_enc_json_20530/group_vars/devboxes/creds.json",
            "directory_mode": null,
            "follow": false,
            "force": null,
            "group": null,
            "insertafter": null,
            "insertbefore": null,
            "line": "test",
            "mode": null,
            "owner": null,
            "path": "/home/adrian/src/ansible-bug-repro/vault_enc_json_20530/group_vars/devboxes/creds.json",
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "state": "absent",
            "unsafe_writes": null,
            "validate": null
        },
        "module_name": "lineinfile"
    },
    "msg": "1 line(s) removed"
}

PLAY RECAP *********************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0

[repro]$ cat group_vars/devboxes/creds.json
{"password": "some_password", "user": "some_user", "groups": ["some_user", "some_group"]}

[repro]$ ansible-vault encrypt group_vars/devboxes/creds.json
Vault password:
Encryption successful
[repro]$ ansible-playbook -vvv test2.yml
Using /home/adrian/.ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available


PLAYBOOK: test2.yml ************************************************************************************************************************************************************************************************
1 plays in test2.yml

PLAY [localhost] ***************************************************************************************************************************************************************************************************

TASK [Creating virtual machine] ************************************************************************************************************************************************************************************
task path: /home/adrian/src/ansible-bug-repro/vault_enc_json_20530/test2.yml:5
Using module file /home/adrian/src/ansible/lib/ansible/modules/files/lineinfile.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: adrian
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1485274387.66-237588583344351 `" && echo ansible-tmp-1485274387.66-237588583344351="` echo ~/.ansible/tmp/ansible-tmp-1485274387.66-237588583344351 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpLRSWfW TO /home/adrian/.ansible/tmp/ansible-tmp-1485274387.66-237588583344351/lineinfile.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/adrian/.ansible/tmp/ansible-tmp-1485274387.66-237588583344351/ /home/adrian/.ansible/tmp/ansible-tmp-1485274387.66-237588583344351/lineinfile.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /home/adrian/.ansible/tmp/ansible-tmp-1485274387.66-237588583344351/lineinfile.py; rm -rf "/home/adrian/.ansible/tmp/ansible-tmp-1485274387.66-237588583344351/" > /dev/null 2>&1 && sleep 0'
ok: [localhost] => {
    "_ansible_no_log": false,
    "_ansible_parsed": true,
    "backup": "",
    "changed": false,
    "diff": [
        {
            "after": "",
            "after_header": "/home/adrian/src/ansible-bug-repro/vault_enc_json_20530/group_vars/devboxes/creds.json (content)",
            "before": "",
            "before_header": "/home/adrian/src/ansible-bug-repro/vault_enc_json_20530/group_vars/devboxes/creds.json (content)"
        },
        {
            "after_header": "/home/adrian/src/ansible-bug-repro/vault_enc_json_20530/group_vars/devboxes/creds.json (file attributes)",
            "before_header": "/home/adrian/src/ansible-bug-repro/vault_enc_json_20530/group_vars/devboxes/creds.json (file attributes)"
        }
    ],
    "found": 0,
    "invocation": {
        "module_args": {
            "attributes": null,
            "backrefs": false,
            "backup": false,
            "content": null,
            "create": false,
            "delimiter": null,
            "dest": "/home/adrian/src/ansible-bug-repro/vault_enc_json_20530/group_vars/devboxes/creds.json",
            "directory_mode": null,
            "follow": false,
            "force": null,
            "group": null,
            "insertafter": null,
            "insertbefore": null,
            "line": "test",
            "mode": null,
            "owner": null,
            "path": "/home/adrian/src/ansible-bug-repro/vault_enc_json_20530/group_vars/devboxes/creds.json",
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "state": "absent",
            "unsafe_writes": null,
            "validate": null
        },
        "module_name": "lineinfile"
    },
    "msg": ""
}

PLAY RECAP *********************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0

[repro]$ cat group_vars/devboxes/creds.json
$ANSIBLE_VAULT;1.1;AES256
39303864346230393435323666643462313936373234626133623462313731393166303435393530
6134316262623234646537333066373163643637316363610a323333383566333538343230313238
34363239656436633739303762343135346534306162316264613132386133643561343534363837
6261306661343134330a356337336363333431306133663134333461636438313166323730616239
33373466383062326666666235646264636430396139306261313062333735623864353963633232
30613766326435353665393666663263656263313836663261393366626465396138666332316532
61353037383063393239633962383163653161643566313730306337336566383236653461623462
61336537666337373238656636343036383864373966366437323036353137656130313663363663
3738
[repro]$ # creds.json was encrypted, the lineinfile line=test state=absent ran and looked at the encrypted file and got success on state=absect
[repro]$ # ansible-playbook -i hosts -vvv test2.yml # without the '-i hosts' the group 'devboxes' is unknown, so nothing tries to open group_vars/devboxes/creds.json
[repro]$ ansible-playbook -i hosts -vvv test2.yml
Using /home/adrian/.ansible.cfg as config file
ERROR! Decryption failed on /home/adrian/src/ansible-bug-repro/vault_enc_json_20530/group_vars/devboxes/creds.json
[repro]$ # ^ attempt to read encrypted group_vars for 'devboxes' now that it knows about that group and fails because of no vault pass
[repro]$ mkdir group_vars/all
mkdir: cannot create directory ‘group_vars/all’: File exists
[repro]$ mv group_vars/devboxes/creds.json group_vars/all/ # THIS INCLUDES UPDATING test.yml
[repro]$ # note 'all' group will match any hosts or groups including just 'localhost' from not having an inventory file
[repro]$ vim test2.yml
[repro]$ grep 'dest' test2.yml
      dest: "{{ playbook_dir }}/group_vars/all/creds.json"
[repro]$ ansible-playbook -vvv test2.yml
Using /home/adrian/.ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available

ERROR! Decryption failed on /home/adrian/src/ansible-bug-repro/vault_enc_json_20530/group_vars/all/creds.json
```

**Comment by dewyze** [comment] 2017-01-24 19:00
Is it not an issue that it does not attempt to decrypt the file to check for `lineinfile`? Shouldn't that notice it is encrypted and give the warning? I understand if it hasn't tried to load the file it wouldn't warn, but that in some cases it did read the file.

In the original post, when using this with the `gce` module, it is able to use those credentials to create vms (and thus I assume, do any other actions) without decrypting the file. That seems like it could be a security concern? Or at least in that case it actually does read the file in order to use those to talk to gce, but still doesn't ask for the password.

**Comment by alikins** [comment] 2017-01-24 20:43
> Is it not an issue that it does not attempt to decrypt the file to check for lineinfile? Shouldn't that notice it is encrypted and give the warning? I understand if it hasn't tried to load the file it wouldn't warn, but that in some cases it did read the file.

group_vars/devboxes/creds.json gets read as data to be used for the playbook run (config file, more or less). File with playbook vars and info are checked if they are encrypted.

In that playbook with:
```
   dest: "{{ playbook_dir }}/group_vars/devboxes/creds.json"
```

The playbook typically means to check that file path on the remote host. In this case, the remote==localhost and {{playbook_dir}} is a full path, so the task ends up looking at the same file, but only by coincidence. 
So local controller side files in a playbook may be encrypted, but not files local to the remote client.

**Comment by alikins** [comment] 2017-01-24 20:48
> In the original post, when using this with the gce module, it is able to use those credentials to create vms (and thus I assume, do any other actions) without decrypting the file. That seems like it could be a security concern? Or at least in that case it actually does read the file in order to use those to talk to gce, but still doesn't ask for the password.

For the 'gce' module, the 'credentials_file' isnt the content of the file, but just a path name. I believe libcould ends up actually reading the contents of the file. I'd have to see more verbose output, but I suspect the gce module and/or libcloud fail back to other sources for the credentials_file path (GCE_CREDENTIALS_FILE_PATH env var for ex).

**Comment by dewyze** [comment] 2017-01-24 20:50
And the `gce` module would just decrypt in the background? Libcloud decrypts and reads it? I don't have another copy of the file other than the encrypted that could be used.

**Comment by samdoran** [comment] 2019-04-12 15:11
Closing this per above conversation. This appears to be a misunderstanding of intended functionality. If you feel this is still an issue in a recent version of Ansible, please open a new issue.

**Closed as completed by samdoran** 2019-04-12 15:11 UTC
Labels: affects_2.2, c:parsing/data_loader, c:parsing/vault/, support:core, bug
