### ISSUE TITLE
delegate_to and changed_when: never returns changed task

### ISSUE THREAD

**Issue by trondhindenes** [ansible/ansible#11809] opened 2015-07-30 21:14 UTC
##### Issue Type:

Can you help us out in labelling this by telling us what kind of ticket this this?  You can say:
- Bug Report
##### Ansible Version:

winrm_v2_fixes b07f8e7a7e (currently in PR, shouldn't matter)
##### Ansible Configuration:

N/A
##### Environment:

Control node: ubuntu 14.04, target node Windows 2012R2
##### Summary:

I have a role with a delegate_to: 127.0.0.1 which loops but should never report "changed". Although changed_when: Never is set, it reports changed on V2. The V1 branch stays silent as it should
##### Steps To Reproduce:

Use the role trondhindenes.win_reboot with the following vars:
winreboot_simulate: yes (note that this will reboot the target node)
##### Expected Results:

None of the task in the role should report change
##### Actual Results:

The task "Looping while waiting for WinRM" reports changed.

**Comment by jimi-c** [comment] 2015-08-03 21:18
@trondhindenes the value you have set is literally `Never`? I believe that would be the cause, as it should be some kind of boolean there. Does the same thing happen if you set `changed_when: False`?

**Comment by jimi-c** [comment] 2015-09-01 21:17
@trondhindenes any follow-up here? If you're still seeing this please let us know, otherwise I'll go ahead and close this issue. Based on your other issue regarding `delegate_to: 127.0.0.1`, this may be a duplicate issue related to the IP vs. localhost name.

Thanks!

**Comment by trondhindenes** [comment] 2015-09-01 22:19
Hi, sorry for the delay. I'll have a close look tomorrow and report back.

**Comment by trondhindenes** [comment] 2015-09-03 21:38
So, I've done a few updates in the module, among others replacing 127.0.0.1 with localhost which fixes the most major issue. Still, it seems that a looping task always returns "changed" although "changed_when" is set to false. This is the relevant part of my role (the play which reports changed: true)

```
- name: Looping while waiting for WinRM
  command: /tmp/{{ inventory_hostname }}.sh
  delegate_to: localhost
  changed_when: False
  register: result2
  retries: "{{ winreboot_winrm_retries }}"
  delay: "{{ winreboot_winrm_delay }}"
  until: result2.stdout.find("Online") != -1
  when: do_reboot == true
```

Btw, the whole role is at https://github.com/trondhindenes/ansibleroles-winreboot. The other (non-looping) tasks reports changed_false as designed, so I'm assuming this error is related to looping. Tested on the latest commit on devel.

**Comment by jimi-c** [comment] 2015-09-15 17:39
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-09-15 17:39 UTC
Labels: P2, bug
