### ISSUE TITLE
Using win_regedit with binary values always results in "changed" state

### ISSUE THREAD

**Issue by jmighion** [ansible/ansible#18880] opened 2016-12-07 16:45 UTC
_From @jmighion on October 10, 2016 20:18_

##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

win_regedit
##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

OS : OS X 10.11.6
Managing: Windows 2008 R2 MS and Windows 2012 R2 DC
##### SUMMARY

Module changed data when it didn't need to when setting binary values without 2 bytes represented by hex.
I'm trying to set a registry data to 0 when the datatype is binary. The module reports the data changed unless you provide the data as data: hex:0,0 or data: 0x0,0x0. Windows represents those slightly differently in the registry. The default binary value is shown as 00, but passing 0x0,0x0 shows in Windows as 0000. Manually editing the registry allows 1 octect, but the module requires 2 to verify if a change is needed.
##### STEPS TO REPRODUCE

```
- name: "Set binary data"
  win_regedit: 
      key: 'HKLM:\System\CurrentControlSet\Control\Lsa'
      value: FullPrivilegeAuditing
      data: 0x0
      datatype: binary
```

##### EXPECTED RESULTS

After 2nd run : 

```
ok: [] => {
    "changed": false, 
    "data_changed": false, 
    "data_type_changed": false, 
    "invocation": {
        "module_name": "win_regedit"
    }
}
```
##### ACTUAL RESULTS

```
changed: [] => {
    "changed": true, 
    "data_changed": true, 
    "data_type_changed": false, 
    "invocation": {
        "module_name": "win_regedit"
    }
}
```

_Copied from original issue: ansible/ansible-modules-extras#3134_

**Comment by jmighion** [comment] 2016-12-07 16:45
_From @ansibot on October 10, 2016 20:25_



@joshludwig, @smadam813, ping. This issue is waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jmighion** [comment] 2016-12-07 16:45
_From @ansibot on October 26, 2016 8:34_

@joshludwig, @smadam813, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jmighion** [comment] 2016-12-07 16:45
_From @ansibot on November 10, 2016 13:7_

@joshludwig, @smadam813, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jmighion** [comment] 2016-12-07 16:45
_From @ansibot on November 26, 2016 9:29_

@joshludwig, @smadam813, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jmighion** [comment] 2016-12-07 16:45
_From @ansibot on December 7, 2016 14:26_

This repository has been locked. All new issues and pull requests should be filed in https://github.com/ansible/ansible

Please read through the <a href="http://docs.ansible.com/ansible/dev_guide/repomerge.html#move-issues-and-prs-to-new-repo">repomerge</a> page in the dev guide. The guide contains links to tools which automatically move your issue or pull request to the ansible/ansible repo.

**Comment by dagwieers** [comment] 2017-02-04 00:31
@jmighion Is this issue still valid ? If so, please post a minimal reproducer that displays the problem.

**Comment by jhawkesworth** [comment] 2017-02-27 13:35
This needs @jmighion to retry using latest devel version of ansible following recent changes to this module.

needs_info

**Comment by dagwieers** [comment] 2017-02-27 14:36
And possibly propose integration tests so we can ensure this is and will be working fine.

**Comment by jmighion** [comment] 2017-02-27 19:08
Tested against today's devel : ansible-2.3.0-100.git201702271740.89bf14e.devel.el7.noarch.rpm
Windows 2008 R2 and 2012 member servers

Problem still exists.

Test playbook :
```---
- name: binary test
  hosts: all
  tasks:
    - name: single 0x0 binary test
      win_regedit:
        key: 'HKLM:\System\CurrentControlSet\Control\Lsa'
        value: testing
        data: 0x0
        datatype: binary
```

Full output of `ansible-playbook binary.yml -vvvvvv --diff` and without `--diff` : 
http://pastebin.com/HdFkKtGY

Diff snippet from `ansible-playbook binary.yml -vvvvvv --diff` : 
``` [HKLM:\System\CurrentControlSet\Control\Lsa]
-"testing" = "binary:0"
+"testing" = "binary:0"
changed: [2012_ms] => {
    "changed": true, 
    "data_changed": true, 
    "data_type_changed": false, 
    "diff": {
        "prepared": " [HKLM:\\System\\CurrentControlSet\\Control\\Lsa]\n-\"testing\" = \"binary:0\"\n+\"testing\" = \"binary:0\""
    }
}
```

The diff looks like the same data before and after.

**Comment by jhawkesworth** [comment] 2017-03-24 07:47
I am investigating this at the moment. 

I suspect the problem is in Convert-RegExportHexStringToByteArray which does a lot of munging of the string input in order to create suitable hex needed to actually apply the change.

**Comment by jhawkesworth** [comment] 2017-03-27 07:58
Just to say I'm still on this but its slow going without the ability to keep remote files at the moment.
Trying to work out a repeatable way to debug on the windows host at the moment.

**Comment by jhawkesworth** [comment] 2017-03-29 06:51
Sorry, no further progress at the moment and I want to move on to other bug fixes that I can progress before 2.3 ships. I will try and pick it up again during 2.4 development.

As a workaround I suggest using
changed_when: False 
on this task.  See http://docs.ansible.com/ansible/playbooks_error_handling.html#overriding-the-changed-result

**Comment by dagwieers** [comment] 2017-07-04 10:05
At [19:00 UTC](http://www.thetimezoneconverter.com/?t=19:00&tz=UTC) this ticket will be processed during [the first Windows Sprint](https://github.com/ansible/community/wiki/Windows:-sprints#2017-07-04-1900-utc-sprint-1), we would appreciate if you could join the Sprint to help out with fixing/closing this issue.

**Comment by jborean93** [comment] 2017-07-06 01:57
Hey @jmighion, in the current rewrite for win_regedit https://github.com/ansible/ansible/pull/26468 I can confirm that checking binary values is idempotent. My testing details are below

Playbook:
```
---
- name: test win_regedit stuff
  hosts: 2012R2
  tasks:
  - name: create new entry
    win_regedit:
      path: HKCU:\SOFTWARE\Test
      name: FullPrivilegeAuditing
      data: 0x0
      type: binary
      state: present

  - name: test idempotency
    win_regedit:
      path: HKCU:\SOFTWARE\Test
      name: FullPrivilegeAuditing
      data: 0x0
      type: binary
      state: present
```

Output:
```
(ansible-py27) (ansible-py27) [jborean@jordan-fedora module-tester]$ ansible-playbook -i inventory.ini win_regedit_tests.yml

PLAY [test win_regedit stuff] ********************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************
Thursday 06 July 2017  11:54:59 +1000 (0:00:00.019)       0:00:00.019 *********
ok: [Server2012R2]

TASK [create new entry] **************************************************************************************************************************************
Thursday 06 July 2017  11:55:03 +1000 (0:00:03.315)       0:00:03.334 *********
changed: [Server2012R2]

TASK [test idempotency] **************************************************************************************************************************************
Thursday 06 July 2017  11:55:04 +1000 (0:00:01.716)       0:00:05.050 *********
ok: [Server2012R2]

PLAY RECAP ***************************************************************************************************************************************************
Server2012R2               : ok=3    changed=1    unreachable=0    failed=0
```

Registry
![image](https://user-images.githubusercontent.com/8462645/27892309-45c44c94-6242-11e7-856d-a77f3831b556.png)


It would be great if you could test out the PR and post your results and state whether it works for you or not.

**Comment by dagwieers** [comment] 2017-07-17 03:09
resolved_by_pr #26468

**Closed as completed** 2017-08-09 13:27 UTC
Labels: windows, affects_2.2, module, support:core, bug
