### ISSUE TITLE
Traceback in 'unarchive' module

### ISSUE THREAD

**Issue by jnojr** [ansible/ansible#10934] opened 2015-05-06 18:39 UTC
Issue Type: Bug Report

Ansible Version: 1.9.0.1

Environment: Mac OS X 10.10.3 "Yosemite", Xcode 6.3

Summary: Traceback in 'unarchive' module

Steps To Reproduce:

```
  - name: Untar DoD certificate installer
    unarchive: src=dod_java_certs.tgz dest=/tmp/ copy=yes
```

Expected Results:

Tarball should be extracted to remote machine.  There is no file called 'certs/._DODCA_25.cer' in my tarball... I just verified.  No idea what ansible is doing here :-)  That could be a problem on my end, or it could be another bug?

Actual Results:

```
TASK: [Untar DoD certificate installer] *************************************** 
failed: [quad] => {"failed": true, "parsed": false}

BECOME-SUCCESS-lhnvcmobwguzqtoldtfxkrmvxagqpstv
Traceback (most recent call last):
  File "/Users/joliver.sa/.ansible/tmp/ansible-tmp-1430936195.2-109021003332611/unarchive", line 1890, in <module>
    main()
  File "/Users/joliver.sa/.ansible/tmp/ansible-tmp-1430936195.2-109021003332611/unarchive", line 289, in main
    res_args['changed'] = module.set_fs_attributes_if_different(file_args, res_args['changed'])
  File "/Users/joliver.sa/.ansible/tmp/ansible-tmp-1430936195.2-109021003332611/unarchive", line 1090, in set_fs_attributes_if_different
    file_args['path'], file_args['mode'], changed
  File "/Users/joliver.sa/.ansible/tmp/ansible-tmp-1430936195.2-109021003332611/unarchive", line 928, in set_mode_if_different
    path_stat = os.lstat(path)
OSError: [Errno 2] No such file or directory: '/tmp/dod_java_certs/certs/._DODCA_25.cer'
Shared connection to quad closed.
```

**Comment by mightydok** [comment] 2015-05-10 15:26
@jnojr can you manually unpack tgz file?
Have you write rights to /tmp/ folder?
Can you upload that archive somhere, i can try to repeat this error, but i need original file.

**Comment by sivel** [comment] 2015-05-10 15:51
The cause of this issue was resolved on the mailing list.

https://groups.google.com/forum/m/?utm_medium=email&utm_source=footer#!msg/ansible-project/lD_9syqJFOQ/VcboqgRyiR4J

However, the traceback is a bug and should be fixed.

However, this issue was logged on the wrong repo and should be opened on ansible-modules-core.

**Comment by mightydok** [comment] 2015-05-10 16:10
@sivel i steel need tgz file to fix error.

**Comment by mightydok** [comment] 2015-05-10 21:26
Ok, i understood problem, MacOSx create resource forks for files prefixed by ._ symbols. This files is "AppleDouble encoded Macintosh file" and when i untar archive on HFS+ filesystem, that files dont exist in directory. Thats why module unarchive raise an error, tar -tzf show ._ files and that module build _files_in_archive list but later cant find this files only on MacOSx filesystem.
I will patch module later. Thanks for issue.

**Comment by jnojr** [comment] 2015-05-11 16:08
mightydok - LMK if you need a sample tarball or anything else from a Mac that might help.

**Closed as completed** 2015-05-12 02:46 UTC
Labels: P2, m:unarchive, bug

**Comment by mightydok** [comment] 2015-05-17 16:15
Ok, try except is better solution. Than skiping ._ files for macosx.
