### ISSUE TITLE
include_role error with with_items (2.3.0 devel)

### ISSUE THREAD

**Issue by gtirloni** [ansible/ansible#21285] opened 2017-02-11 12:55 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
include_role

##### ANSIBLE VERSION
ansible 2.3.0 (devel 59306e2aef) last updated 2017/02/11 12:44:45 (GMT +000)

##### OS / ENVIRONMENT
N/A

##### SUMMARY
include_role fails to execute when used with_items (similar to issue #17966)

##### STEPS TO REPRODUCE

```yaml
- hosts: all
  tasks:
    - include_role:
        name: '{{ item }}'
      with_items:
        - role1
        - role2
```

##### EXPECTED RESULTS
include_role loops over list and updates item variable

##### ACTUAL RESULTS
```
TASK [include_role] 
ERROR! 'item' is undefined
```

**Comment by smemsh** [comment] 2017-03-20 17:29
also affects 2.2

**Comment by smemsh** [comment] 2017-03-20 17:33
note, I couldn't get the `name:` value to expand from *any* variable set at play scope, not just the with_items loop var.

**Comment by Dixon3** [comment] 2017-03-27 20:31
The same issue...

**Comment by snowsky** [comment] 2017-03-27 20:33
yes, loop_var not working with include_role.

**Comment by jbilbro** [comment] 2017-04-07 18:08
I'm hitting this, too.  Any work around you guys have discovered?

**Comment by bearrito** [comment] 2017-05-03 17:22
I've reproduced this. Does the maintainer need information?

**Comment by broferek** [comment] 2017-05-05 12:31
I also came to this issue, I need to be able to loop over a list of roles from a fact set in a previous play.

**Comment by lennyby93** [comment] 2017-05-08 00:05
There is a pull request that contains a fix here: 
[here](https://github.com/ansible/ansible/pull/23104)

**Comment by jbilbro** [comment] 2017-05-08 21:30
@lennyby93 have you tried it with success?

**Comment by lennyby93** [comment] 2017-05-08 22:09
yes, I got 'item' to resolve correctly. It looks like the generic vars (like inventory_hostname) still do not resolve. This works now for me:
```
- name: load and run services
  include_role:
    name: "resource_{{ item.resource }}"
  with_items:
    - "{{ services }}"

```

**Comment by jbilbro** [comment] 2017-05-09 19:02
Posted this on that pull request, too.

I have tried installing these two files on my Ansible 2.3 install on my Ansible Tower 3.1.3 server. When trying to execute a job template, it fails immediately when trying to update from SCM. If I revert these two files everything works fine (other than you know, include_roles failing to take a variable).

`TASK [Set the git repository version] ****************************************** An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'module' object has no attribute 'NAMESPACE_FACTS' fatal: [localhost]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}`

**Comment by holmesb** [comment] 2017-06-29 18:27
Same happens when trying to loop over tasks_from eg:
```
    - include_role:
        name: a_role
        tasks_from: "{{ item }}"
      with_items:
        - a_task_in_a_role
        - another_task_in_a_role
```
Get error "ERROR! Could not find specified file in role: tasks/{{ item }}".

**Comment by balpert89** [comment] 2017-07-07 18:35
Still getting error "ERROR! 'item' is undefined"

```bash
- debug: var=objects

- debug: var=item
  with_items: "{{ objects }}"

- name: Tear down created objects
  include_role:
    name: "teardown_{{ item }}"
  with_items: "{{ objects }}"
```

Output: 
```bash
TASK [teardown : debug] 
*************************************
ok: [localhost] => {
    "objects": [
        "subnet",
        "vpc"
    ]
}

TASK [teardown : debug]
 **************************
ok: [localhost] => (item=vpc) => {
    "item": "vpc"
}
ok: [localhost] => (item=subnet) => {
    "item": "subnet"
}

TASK [teardown : Tear down created objects]
 ***************************************************
ERROR! 'item' is undefined
```

Is there an ETA for the fix? Or a workaround?

**Comment by subsy** [comment] 2017-07-11 13:55
Been affecting us also - have effectively had to not use roles for our parameterised app deployments and revert to calling playbooks.

Can we help with any further information?

**Comment by balpert89** [comment] 2017-07-19 09:59
@jimi-c @bcoca You two are both assigned to this task, according to lennyby93's comment there is a pull request targeting this issue: https://github.com/ansible/ansible/pull/23104

Can you please review this and merge it? I am blocked by this issue because I need "include_role" to iterate over a list.

Best regards

**Comment by ghost** [comment] 2017-07-28 22:33
Got the same issue here for a similar problem. 
Ansible 2.3.1

**Comment by ssbarnea** [comment] 2017-09-19 15:56
This is still an issue with Ansible 2.4.0, if that is not supported for good reasons it should not accept with_items parameter anyway.

**Comment by hadrien-toma** [comment] 2017-09-26 14:07
This also happens with Ansible `2.5.0`. Moreover, this error does not seem to increase the failure counter.

**Comment by hadrien-toma** [comment] 2017-09-27 10:20
A not really wonderful workaround (but which enabled me to use this really enjoying feature) for those who use a graphical environment as their Ansible controller.
* Before, you need to install a terminals's manager that allows you to open a new shell window and to automatically run a script/command inside it ([`terminator`](https://github.com/software-jessies-org/jessies/wiki/Terminator) for instance).
* Tasks to implement:
. Template a playbook that loops over the roles you wanted to include (including them roughly in a new file).
. Open a new terminal window using the Ansible `command` module and tell it to execute (as first command) this freshly templated playbook.

Notes: You can either detach or not the auxiliary terminal window, according to your needs.

**Comment by ghost** [comment] 2017-10-13 20:55
Hi, 
I really would like to know if this is gonna be implemented properly or if this is a "no-go". My playbooks depend on it for provisioning. If this is an "anti-pattern" and a bad practice and wont be implemented, then i will scrap it and think of something else. Right now i have a monkeypatch and have to maintain it for every release. I want to avoid this kind of mess so please tell us if this is gonna be fixed / included in near future.

**Comment by jimi-c** [comment] 2017-11-30 16:44
Fixed by https://github.com/ansible/ansible/pull/33386, which has been merged.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2017-11-30 16:44 UTC
Labels: affects_2.3, support:core, include_role, bug

**Comment by thiagoalves** [comment] 2018-03-22 19:39
I am not sure whether the information below is useful, but I was able to make it work with hostvars:

      include_role:
        name: "{{ hostvars['localhost']['rolename'] }}"
        tasks_from: taskname

I hope this is useful to someone else
