### ISSUE TITLE
Feature: Extended Vault support: copying files, lookup plugin

### ISSUE THREAD

**Issue by kolypto** [ansible/ansible#7298] opened 2014-05-06 14:02 UTC
When there's a need to keep some sensitive data close to a playbook, Vault is great for ciphering variables. However, what about encrypting files that are transferred to the target host?

Suggesting the following:
- Decrypt Vault-protected files on-the-fly with the `copy` module
- Implement a lookup plugin to read data from Vault-protected files, like `lookup('vault', 'path/to/file')`

**Comment by ruudk** [comment] 2014-05-12 12:34
This would be really great to have. A simpel `decrypt=yes` flag for the `copy` module is all I need :)

**Comment by bcoca** [comment] 2014-07-13 01:13
this could be provided by #8110

**Comment by AnneTheAgile** [comment] 2014-08-21 02:18
@bcoca , do I understand correctly that your PR #8110  Lookup vault file, aka #8533 , does not decrypt yet, but that you could add the feature? From your docs there it seems like the lookup will simply show the fact that a file is vaulted. ty!

**Comment by bcoca** [comment] 2014-08-21 11:29
no, it is supposed to decrypt it if it dectects it is encrypted and the
password is available.​

it does add the facility for other lookups to do the same but I did not
implement the decryption outside the file lookup.

**Comment by rouge8** [comment] 2015-01-07 23:38
Is there any plan to update #8533 to resolve this?

**Comment by soichih** [comment] 2015-01-08 17:01
+1 for "Decrypt Vault-protected files on-the-fly with the copy module" option.

**Comment by thedodd** [comment] 2015-01-10 03:35
+1 for a simple `decrypt=yes` flag for the `copy` module.

**Comment by flmmartins** [comment] 2015-02-06 18:10
+1 to previous comment!

**Comment by dwt** [comment] 2015-02-16 13:40
There seem to be some pull requests that provide this functionality for lookup() - still what I really want is to be able to use vault encrypted files transparently everywhere in ansible - so I think this pull request provides something unique.

See:
- https://github.com/ansible/ansible/pull/8533
- https://github.com/ansible/ansible/pull/8110

**Comment by mcreenan** [comment] 2015-04-27 19:16
Please consider adding this functionality.  Doing it other ways ends up being very convoluted.

**Comment by brandonheller** [comment] 2015-05-01 21:59
This would be great - without this, I have to write a script to copy from the vault, so that copy can do its thing.

**Comment by afeinberg** [comment] 2015-05-01 22:05
+1 for this, please

**Comment by flmmartins** [comment] 2015-05-11 15:13
This issue is making one year old! Please add this! ^^

**Comment by ant8e** [comment] 2015-06-02 12:28
+1 
I'm just starting to use Vault and was very surprised not to be able do crypt arbitrary files

**Comment by mauricios** [comment] 2015-06-05 15:08
+1 for encrypted file support for keys, certificates, and such. Currently the only way to do this is using variables with the content of the certificate, then encrypt the variables file. Is there a better way to do this?

**Comment by acorncom** [comment] 2015-06-05 18:03
This tool was built for Puppet originally, I wonder if it'd help with this here?
https://github.com/StackExchange/blackbox

**Comment by leonard84** [comment] 2015-06-12 11:19
+1 this feature is really needed by anyone who cares about security

**Comment by se7entyse7en** [comment] 2015-06-17 14:45
+1

**Comment by riguy724** [comment] 2015-06-18 17:53
+1

**Comment by eviln1** [comment] 2015-06-19 13:48
+1

**Comment by mingqiancoding** [comment] 2015-06-23 22:53
+1

**Comment by glassresistor** [comment] 2015-06-24 23:00
+1

**Comment by yasserg** [comment] 2015-06-24 23:14
+1

**Comment by yasserg** [comment] 2015-06-24 23:54
Until this is implemented, here is a workaround: http://stackoverflow.com/a/31039053/405418

**Comment by vpetersson** [comment] 2015-06-25 08:52
+1

**Comment by theikkila** [comment] 2015-06-30 15:24
+1

**Comment by dkerwin** [comment] 2015-07-02 13:06
+1

**Comment by cambell-prince** [comment] 2015-07-03 08:37
Wanting to do the same thing I created an action plugin to implement the feature.  This is available via [github](https://github.com/saygoweb/ansible-plugin-copyv).  The plugin is exactly the copy action plugin as shipped with ansible, but with support for vault decryption.

You can use it like this:

```
- name: Copy Some Secret File
  copyv: src="secret.txt" dest="/tmp/"
```

if secret.txt is encrypted (and the vault password is supplied) then it will be decrypted and copied.

**Comment by abourget** [comment] 2015-07-08 19:10
+1

**Comment by jeremychase** [comment] 2015-07-11 16:18
+1

**Comment by mpailloncy** [comment] 2015-07-12 08:45
+1

**Comment by kampka** [comment] 2015-07-12 08:51
Can you guys please stop with the +1s ?
It doesn't help, it just generates a lot of spam for everyone subscribed here.
Thank you.

**Comment by daurnimator** [comment] 2015-07-12 11:58
> Can you guys please stop with the +1s ?
> It doesn't help, it just generates a lot of spam for everyone subscribed here.

Is there any other way to show the importance of this issue to people?
It been prioritised as only P4.

**Comment by bcoca** [comment] 2015-07-12 17:27
So I was keeping this around as a reminder, there were already 2 PRs to solve this issue for v1, but not in a good manner (the original was mine, the 2nd was a rebase based on my PR).  I closed my PR #8553 (originally #8110) but left this ticket and the 2nd #10048 open to show that the issue is will eventually be dealt with.

This is a feature that ansible team does want to add, but non trivial to implement. The v2 core rewrite made the previous PRs obsolete and opened a much cleaner way to add this feature. 

Adding noise to this ticket distracts us from actually doing other work, we really don't need more +1s as we are well aware that the community wants this (so did I, as I opened the PR long before becoming a maintainer). Please keep the discussion civil and on point or there won't be much reason to keep this ticket open. @kampka I also get the emails, but I would not try to stop people for making their interests known even if it is redundant at this point.

Our first priority is getting v2 into parity with the old v1 so we can release 2.0 without breaking playbooks. That said, this is one of the short list of features we want to implement for 2.0 if we have time, or shortly after. Even though there is a workaround by making your files into variables, we know it is far from optimal.

We are also working through an huge contribution backlog and trying to add fixes/features/modules from the community as we don't want people getting too frustrated about issues being open a long time (like this one), so we split our time accordingly.  We have made big inroads into the backlog, but we still have a ways to go before we can bring it in to a more reasonable state and lead times.

That we have not gotten to implement this yet (I have added some code in this direction but nowhere near closed to finished) does not mean we wont add the feature. But it will have to wait a bit longer while we deal with the things I mentioned above, please be patient with us, we'll get to it as soon as we can. This applies to most open PR, bug and feature request tickets, many have been fixed already in the v2 rewrite, but now we have to hunt down, test and close those tickets.

**Comment by glatapoui** [comment] 2015-12-09 21:37
What is the status on this feature ? Any chance in seeing that for 2.0 ?

**Comment by namero999** [comment] 2016-01-22 11:14
Seems like the best shot for this to be fixed is #13849, hopefully with unarchive support as well.

**Comment by cjrd** [comment] 2016-02-25 02:22
+1

**Comment by jamesongithub** [comment] 2016-02-29 19:38
looks like slated for `v2.1.0` #14079

**Comment by cambell-prince** [comment] 2016-02-29 23:55
Until this becomes available (likely in v.2.1.x) you can use [this action plugin](https://github.com/saygoweb/ansible-plugin-copyv) to implement the feature.  The plugin is exactly the copy action plugin as shipped with ansible, but with support for vault decryption.  There is a version for 1.9.x and also 2.0.x on a separate branch.

You can use it like this:

```
- name: Copy Some Secret File
  copyv: src="secret.txt" dest="/tmp/"
```

if secret.txt is encrypted (and the vault password is supplied) then it will be decrypted and copied.

**Comment by jamesongithub** [comment] 2016-03-01 00:03
i just used file lookup and then content instead of src for the copy module -- file lookup seems to support encrypted files natively

**Comment by abourget** [comment] 2016-03-04 15:33
@jamesongithub in Ansible 2.0 ?  Can you confirm it solves this issue ?

**Comment by jamesongithub** [comment] 2016-03-05 04:40
it's more of workaround. ive only tried on v2. it might work on older versions.

**Comment by bcoca** [comment] 2016-04-19 14:24
merged  #15417 into devel, which allows `copy` to transparently use vaulted files, this should be available in 2.1 release. Leaving this open as we still want lookups/filters to do the same.

**Comment by namero999** [comment] 2016-04-19 14:27
Great! Will test. Will unarchive work as well?

**Comment by bcoca** [comment] 2016-04-19 14:33
@namero999, no,  I only mentiond `copy` for a reason. If this works well, it can be added to more action plugins to do same.

**Comment by namero999** [comment] 2016-04-19 14:39
Thanks for the info. It is already valuable nonetheless.

2016-04-19 16:34 GMT+02:00 Brian Coca notifications@github.com:

**Comment by hlm** [comment] 2016-05-31 13:56
+1

**Comment by adrianmoisey** [comment] 2016-05-31 14:10
This was added in Ansible 2.1: https://github.com/ansible/ansible/blob/devel/CHANGELOG.md#21-the-song-remains-the-same---active-development

> copy module can now transparently use a vaulted file as source, if vault passwords were provided it will decrypt and copy on the fly

**Comment by jimi-c** [comment] 2016-07-09 20:30
# Switch to Proposal

Hi!

As of April of 2016, we have started using the Ansible Proposal process for large feature ideas or changes in current functionality, such as this. Because this issue has been open for so long without any action, we are going to go ahead and close it at this time. If you are still interested in seeing this new feature get into Ansible, please submit a proposal for it using this process.

https://github.com/ansible/proposals/blob/master/proposals_process_proposal.md

If you have any further questions, please let us know by stopping by our devel mailing list, or our devel IRC channel:
- #ansible-devel on Freenode
- https://groups.google.com/forum/#!forum/ansible-devel

Thank you!

**Closed as completed by jimi-c** 2016-07-09 20:30 UTC
Labels: feature
