### ISSUE TITLE
When conditions broken if they contain a comma

### ISSUE THREAD

**Issue by jurgenhaas** [ansible/ansible#15572] opened 2016-04-25 06:30 UTC
My original task looked like this:

```
  - name: "Check Ansible version"
    run_once: true
    debug: msg="You need at least version 2.0.0.0, currently using version {{ ansible_version.full }}"
    failed_when: "{{ ansible_version.full | version_compare('2.0.0.0', operator='lt', strict=False)}}"
```

and that results in `The conditional check '{{ ansible_version.full|version_compare(\"2.0.0.0\" ' failed. The error was: template error while templating string: unexpected end of template, expected ','.. String: {{ ansible_version.full|version_compare(\"2.0.0.0\" "}`

Following advise from Brian in the forum I changed the condition to `failed_when: ansible_version.full | version_compare('2.0.0.0', operator='lt', strict=False)` which then throws a different error `The error was: template error while templating string: unexpected '}', expected ')'. String: {% if ansible_version.full|version_compare('2.0.0.0' %} True {% else %} False {% endif %}"}`

Looks like a bug to me, isn't it?

**Comment by infernix** [comment] 2016-04-25 09:33
The same problem happens with this:

```
- name: fix apt
 shell: apt-get -f -y install
 register: aptgetfinstall
 changed_when: "'0 upgraded, 0 newly installed' not in aptgetfinstall.stdout"
```

Error message:

```
fatal: [1cb72c01c5f3]: FAILED! => {"failed": true, "msg": "The conditional check '\"0 upgraded' failed. The error was: template error while templating string: unexpected char u'\"' at 6. String: {% if \"0 upgraded %} True {% else %} False {% endif %}"}
```

Somehow in the 2.0.2 release, a comma gets interpreted wrongly as some sort of field separator or terminator. 

This isn't happening on 2.0.1 and I can't find any syntax to fix it; swapping single vs double quotes makes no difference.

**Comment by debugloop** [comment] 2016-04-25 09:55
The same applies to the following, confirming @infernix' suggestion of the comma interpreted as a separator:

``` yaml
- name: ensure the firewalld service is running
  service: name=firewalld state=started
  register: service_state
  failed_when: "service_state.failed|default(False) and not ('No ActiveState value in systemctl' in service_state.msg and lookup('env', 'COBBLER_INSTALL')|default(0) == '1')"
```

Result is:

```
TASK [common_firewall : ensure the firewalld service is running] ***************
fatal: [default]: FAILED! => {"failed": true, "msg": "The conditional check 'service_state.failed|default(False) and not ('No ActiveState value in systemctl' in service_state.msg and lookup('env'' failed. The error was: template error while templating string: unexpected '}', expected ')'. String: {% if service_state.failed|default(False) and not ('No ActiveState value in systemctl' in service_state.msg and lookup('env' %} True {% else %} False {% endif %}"}
```

Maybe @jurgenhaas can rename the issue to something more general than the version_compare filter, a la "when condition broken when containing comma"?

**Comment by infernix** [comment] 2016-04-25 09:57
A git bisect shows that this bug was fixed in 30a38f94ce81314019fb2d9496602eef0a5b36fe so this is a duplicate of #15291

**Comment by bcoca** [comment] 2016-04-25 12:58
closing as per fix above

**Closed as completed by bcoca** 2016-04-25 12:58 UTC
Labels: bug

**Comment by jurgenhaas** [comment] 2016-04-25 13:26
Confirmed, this is working for my examples above too
