### ISSUE TITLE
List variables in inventory behave differently in jinja templates depending on location and quoting

### ISSUE THREAD

**Issue by fthommen** [ansible/ansible#44126] opened 2018-08-14 15:36 UTC
##### SUMMARY
list variables which are declared in the inventory are interpreted differently by jinja templates depending on where they are placed and how they are quoted: list variables following a host name have to be double quoted to be interpreted correctly, while global or group variables must not be quoted.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

template

##### ANSIBLE VERSION

```
ansible 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/thommen/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### OS / ENVIRONMENT

CentOS 7.x, x86_64

##### STEPS TO REPRODUCE

Running playbook
```yaml
---
- hosts: myhost
  tasks:
  - template:
      src:   template.j2
      dest:  /tmp/listtest
      force: yes
  - command: cat /tmp/listtest
    register: out
  - debug: var=out.stdout_lines
```

with inventory
```
[all:vars]
userlist1=['alice', 'bob']

[testhosts]
myhost

[testhosts:vars]
userlist2="['user4', 'user5']"
```

results in 
```
PLAY [myhost] ********************************

TASK [Gathering Facts] ********************************
ok: [myhost]

TASK [template] ********************************
ok: [myhost]

TASK [command] ********************************
changed: [myhost]

TASK [debug] ********************************
ok: [myhost] => {
    "out.stdout_lines": [
        "# USERLIST1", 
        "Key: alice", 
        "Key: bob", 
        "", 
        "# USERLIST2", 
        "Key: [", 
        "Key: '", 
        "Key: u", 
        "Key: s", 
        "Key: e", 
        "Key: r", 
        "Key: 4", 
        "Key: '", 
        "Key: ,", 
        "Key:  ", 
        "Key: '", 
        "Key: u", 
        "Key: s", 
        "Key: e", 
        "Key: r", 
        "Key: 5", 
        "Key: '", 
        "Key: ]"
    ]
}

PLAY RECAP ********************************
myhost                  : ok=4    changed=1    unreachable=0    failed=0   
```

while running the playbook with the following inventory:
```
[all:vars]
userlist1=['alice', 'bob']

[testhosts]
myhost userlist2=['user4', 'user5']
```

results in a syntax errror:
```
 [WARNING]:  * Failed to parse /data/homes/ansible/ansible-config/ft/ansible-deploy/listtest/ansible-hosts with yaml plugin: Syntax Error
while loading YAML.   found unexpected ':'  The error appears to have been in '/data/homes/ansible/ansible-config/ft/ansible-
deploy/listtest/ansible-hosts': line 1, column 5, but may be elsewhere in the file depending on the exact syntax problem.  The offending
line appears to be:   [all:vars]     ^ here

 [WARNING]:  * Failed to parse /data/homes/ansible/ansible-config/ft/ansible-deploy/listtest/ansible-hosts with ini plugin:
/data/homes/ansible/ansible-config/ft/ansible-deploy/listtest/ansible-hosts:5: Expected key=value host variable assignment, got: user5]

 [WARNING]: Unable to parse /data/homes/ansible/ansible-config/ft/ansible-deploy/listtest/ansible-hosts as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

 [WARNING]: Could not match supplied host pattern, ignoring: myhost
```

and running it with the inventory

```
[all:vars]
userlist1=['alice', 'bob']

[testhosts]
myhost userlist2="['user4', 'user5']"
```

finally results in what we want:
```
PLAY [myhost] ********************************

TASK [Gathering Facts] ********************************
ok: [myhost]

TASK [template] ********************************
ok: [myhost]

TASK [command] ********************************
changed: [myhost]

TASK [debug] ********************************
ok: [myhost] => {
    "out.stdout_lines": [
        "# USERLIST1", 
        "Key: alice", 
        "Key: bob", 
        "", 
        "# USERLIST2", 
        "Key: user4", 
        "Key: user5"
    ]
}

PLAY RECAP ********************************
myhost                  : ok=4    changed=1    unreachable=0    failed=0   
```

##### EXPECTED RESULTS

Even though the documentation says "Values passed in the INI format using the key=value syntax are not interpreted as Python literal structure (strings, numbers, tuples, lists, dicts, booleans, None), but as a string" (https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html) I'd expect the variables to behave the same way wether their declaration follows a hostname or not.

**Comment by sivel** [comment] 2018-08-14 15:38
Duplicate of https://github.com/ansible/ansible/issues/36544

**Closed as completed by sivel** 2018-08-14 15:38 UTC
