### ISSUE TITLE
ansible can't exclude hostgroup playbook when facts_cache expires

### ISSUE THREAD

**Issue by xiaocaisgit** [ansible/ansible#30611] opened 2017-09-20 08:32 UTC
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

```

##### CONFIGURATION
my ansible configured as follow:
```
[defaults]
gathering = smart
fact_caching_timeout = 2592000
fact_caching = redis
fact_caching_connection = localhost:6379
host_key_checking = False
[privilege_escalation]
[paramiko_connection]
[ssh_connection]
pipelining = False
[persistent_connection]
connect_timeout = 30
connect_retries = 30
connect_interval = 1
[accelerate]
[selinux]
[colors]
[diff]
```
##### OS / ENVIRONMENT
```
CentOS Linux release 7.2.1511 (Core)
Linux localhost.localdomain 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Python 2.7.5
```
##### SUMMARY

**I use redis to cache ansible facts, but when redis's key expires, I can't use ansible-plabook to perform the host group operation, but I can use Playbook for a single host operation
also,If I cache facts early, then this playbook can be normal。
**
##### STEPS TO REPRODUCE

the full traceback was:
```
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 109, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 154, in run
    results = pbex.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 153, in run
    result = self._tqm.run(play=play)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 264, in run
    start_at_done = self._start_at_done,
  File "/usr/lib/python2.7/site-packages/ansible/executor/play_iterator.py", line 213, in __init__
    if host.name in variable_manager._fact_cache and variable_manager._fact_cache.get(host.name).get('module_setup', False):
AttributeError: 'NoneType' object has no attribute 'get'
```

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by bcoca** [comment] 2017-09-21 00:33
duplicate of #28937, fixed by #29048

**Closed as completed by bcoca** 2017-09-21 00:33 UTC
Labels: affects_2.3, support:core, bug
