### ISSUE TITLE
GCE dynamic inventory script is not compatible with apache-libcloud (v0.20.0)

### ISSUE THREAD

**Issue by d3rzky** [ansible/ansible#13594] opened 2015-12-18 11:38 UTC
Hi,

I tried generating dynamic inventory using properly configured (secrets.py) gce.py script and got next issue while running it:

> Please Go to the following URL and sign in:
> https://accounts.google.com/o/oauth2/auth?BUNCH_OF_PARAMETERS
> Enter Code: 

Following the link I got 

> Error: redirect_uri_mismatch
> ..
> The redirect URI in the request: urn:ietf:wg:oauth:2.0:oob can only be used by a Client ID for native application. It is not allowed for the &#39;WEB&#39; client type. You can create a Client ID for native application in the Credentials section of the Google Developers Console.

Everything works fine if apache-libcloud is downgraded to 0.19.0 version.

**Comment by abadger** [comment] 2015-12-18 23:49
@erjohnso Looks like one you might want to look into.

**Comment by viglesiasce** [comment] 2015-12-21 21:15
I was able to reproduce this as well when developing https://github.com/ansible/ansible/pull/13623. This also effects the GCE modules themselves. I'll take a look at this in libcloud.

**Comment by viglesiasce** [comment] 2015-12-21 22:13
This should be fixed in the next rev of libcloud:
https://issues.apache.org/jira/browse/LIBCLOUD-785

**Comment by erjohnso** [comment] 2015-12-22 15:57
Yes, this will impact users with new service accounts. Any existing service accounts will be fine, but we'll likely start to see this more and more until the next version of libcloud makes it out.

**Comment by ghost** [comment] 2016-03-29 13:55
Damn, I just stumbled upon this. I have tried libcloud 0.20.1 and 1.0.0-pre1 but no luck with neither of them :(

**Comment by alex-leonhardt** [comment] 2016-06-12 08:41
updated to latest version of apache libcloud (and ansible) and at least i'm no longer getting the same error message.. 

```
apache-libcloud==0.20.1
```

and fwiw, with correct time (local host's time) & cred settings, all seems to work fine now ...

**Comment by supertom** [comment] 2016-06-30 17:10
This works for me with current ansible and apache_libcloud==0.20.1 as well.  I recommend we close.  OK with you, @ryansb ?

**Comment by ryansb** [comment] 2016-07-05 19:46
Yup, this works for me.

**Closed as completed by ryansb** 2016-07-05 19:46 UTC
Labels: cloud, gce, bug
