### ISSUE TITLE
Sum of lists becomes a unicode string in ansible 2.0

### ISSUE THREAD

**Issue by iskrant** [ansible/ansible#14074] opened 2016-01-22 11:29 UTC
## Enviroment:

Ansible: 2.0.0.2
OS: Ubuntu 14.04.3 LTS
Python: 2.7.6
## Steps To Reproduce:

TASK:

```
- name: test_1
  copy: src={{ secure_vault }}/google-authentificator/{{ item['name'] }}/.google_authenticator dest=/home/{{ item['name'] }}/.google_authenticator backup=yes owner={{ item['name'] }} mode=0400
  with_items: administrators + developers
```

VARS:

```
administrators:
  - { name: bob.ai, mail: bob_ai@test.com }
  - { name: john, mail: john_pa@test.com }

developers:
  - { name: frank_a, mail: office@test.com }
  - { name: mario_a, mail: office@test.com }
```
## When executing this on Ansible 2.0:

```
...
TASK [vpn-access-server | test_1] **********
fatal: [vpn03]: FAILED! => {"failed": true, "msg": "ERROR! 'unicode object' has no attribute 'name'"}
...
```
## When executing this on Ansible 1.9.4:

```
TASK: [vpn-access-server | test_1] ******** 

ok: [vpn03] => (item={'mail': 'bob_ai@test.com', 'name': 'bob.ai'})

ok: [vpn03] => (item={'mail': 'john_pa@test.com', 'name': 'john'})

ok: [vpn03] => (item={'mail': 'office@test.com', 'name': 'frank_a'})

ok: [vpn03] => (item={'mail': 'office@test.com', 'name': 'mario_a'})
```

**Comment by bcoca** [comment] 2016-01-23 03:57
have you tried?
`with_items: "{{administrators + developers}}"`

**Comment by selivan** [comment] 2016-01-23 14:13
@bcoca: I had the same problem, and changing
`with_items: var_list1 + var_list2`
to
`with_items: "{{ var_list1 + var_list2 }}"`
fixed it, thanks :+1: .

Is this a regression in 2.0 or just syntax became more strict? It should be documented, probably

**Comment by hloeffler** [comment] 2016-01-25 09:30
where is this documented?

**Comment by sivel** [comment] 2016-01-25 18:07
I would actually go as far as to say that you shouldn't try concatenating the lists via jinja2, but instead use the existing functionality of `with_items` to flatten the lists.

Example:

```
---
- hosts: all
  gather_facts: false
  vars:
    one:
      - foo
      - bar
    two:
      - baz
      - qux
  tasks:
    - debug: msg="{{ item }}"
      with_items:
        - "{{ one }}"
        - "{{ two }}"
```

This produces output similar to:

```
ok: [localhost] => (item=foo) => {
    "item": "foo",
    "msg": "foo"
}
ok: [localhost] => (item=bar) => {
    "item": "bar",
    "msg": "bar"
}
ok: [localhost] => (item=baz) => {
    "item": "baz",
    "msg": "baz"
}
ok: [localhost] => (item=qux) => {
    "item": "qux",
    "msg": "qux"
}
```

**Comment by selivan** [comment] 2016-01-25 18:19
@sivel: if this is not supported, then it should be explicitly documented and should produce explicit errors, something like `ERROR: Jinja2 variable concatenating inside task files is not supported, use loops instead`. Though it seems like regression in 2.0 to me.

**Comment by sivel** [comment] 2016-01-25 18:25
I'm not saying it couldn't or shouldn't work.  Just stating what I believe to be the best practice for looping over multiple flattened lists.

**Comment by selivan** [comment] 2016-01-25 18:31
Yep, it probably is. But now many people have tons and tons of ansible code in production, written with all possible hacks you can imagine. So it's not good thing to break compatibility. I think this should be fixed or at least explicitly documented as broken/deprecated.

**Comment by bcoca** [comment] 2016-01-26 03:26
So I'm going to close this as this is not a bug, the reason this worked in 1.9.4 was lax syntax checking (it really never should have). 

We have already documented in the changelog that the parser is stricter and reports errors better, but in this case it has a really hard time trying to distinguish between concatenating 2 strings and adding 2 lists, there are probably more corner cases like this it will be unable to distinguish. This is why we are trying to remove the 'bare' templating from `with_` as if it clear when using `{{ }}` if it is a string it is quoted, if not it is a var.

This ticket should serve as documentation for this specific case.

**Closed as completed by bcoca** 2016-01-26 03:26 UTC
