### ISSUE TITLE
Variable in dependency-roles do not get propagated correctly in 2.1.x

### ISSUE THREAD

**Issue by stehefan** [ansible/ansible#18484] opened 2016-11-14 17:17 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
dependency

##### ANSIBLE VERSION
```
ansible 2.1.3.0
  config file =
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
default configuration without any changes

##### OS / ENVIRONMENT
N/A (tested on Mac and Windows)

##### SUMMARY
Variables that get available by using dependencies in `meta`-information of a role do not propagate their variables correctly if they got set during inclusion of the role.

I have not found anything in the changelog or documentation stating that this is now changed and correct behaviour, so I assume that it is a bug. 

##### STEPS TO REPRODUCE
One has two roles, one base-role and one role that will be used as a dependency role in the base role:

###### example-role

`meta/main.yml`

```yaml
---

dependencies:
  - role: dependency-role
    base_path: "/another/base"
```

`tasks/main.yml`

```yaml
---

- name: show example role ouput
  debug: 
    msg: "base_path={{ base_path }}, detailled_path={{ detailled_path }}"
````

###### dependency-role
`vars/main.yml`

```yaml
---

base_path: "/some/base/path"

detailled_path: "{{ base_path }}/detailed"
```

`tasks/main.yml`

```yaml
---

- name: show example role ouput
  debug: 
    msg: "base_path={{ base_path }}, detailled_path={{ detailled_path }}"
```

###### playbook

```yaml
---

- hosts: localhost
  gather_facts: no
  connection: local
  become: no
  roles:
    - dependency-role
    - example-role
```
 
##### EXPECTED RESULTS
As of Ansible 2.0.2.0, the variable adjusted by including the dependency-role is available in the example-role after solving the dependency:

```
No config file found; using defaults

PLAYBOOK: play.yml *************************************************************
1 plays in play.yml

PLAY [localhost] ***************************************************************

TASK [dependency-role : Show dependency debut output] **************************
task path: /Users/stli/projects/ansible-test/roles/dependency-role/tasks/main.yml:3
ok: [localhost] => {
    "msg": "base_path=/some/base/path, detailled_path=/some/base/path/detailed"
}

TASK [dependency-role : Show dependency debut output] **************************
task path: /Users/stli/projects/ansible-test/roles/dependency-role/tasks/main.yml:3
ok: [localhost] => {
    "msg": "base_path=/another/base, detailled_path=/another/base/detailed"
}

TASK [example-role : show example role ouput] **********************************
task path: /Users/stli/projects/ansible-test/roles/example-role/tasks/main.yml:3
ok: [localhost] => {
    "msg": "base_path=/another/base, detailled_path=/another/base/detailed"
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0   
```

##### ACTUAL RESULTS
In Ansible 2.1.3.0 (also tested in 2.1.0.0 - 2.1.2.0), the variable will use its defaults afterwards, without taking the included variable in account

```
No config file found; using defaults

PLAYBOOK: play.yml *************************************************************
1 plays in play.yml

PLAY [localhost] ***************************************************************

TASK [dependency-role : Show dependency debut output] **************************
task path: /Users/stli/projects/ansible-test/roles/dependency-role/tasks/main.yml:3
ok: [localhost] => {
    "msg": "base_path=/some/base/path, detailled_path=/some/base/path/detailed"
}

TASK [dependency-role : Show dependency debut output] **************************
task path: /Users/stli/projects/ansible-test/roles/dependency-role/tasks/main.yml:3
ok: [localhost] => {
    "msg": "base_path=/another/base, detailled_path=/another/base/detailed"
}

TASK [example-role : show example role ouput] **********************************
task path: /Users/stli/projects/ansible-test/roles/example-role/tasks/main.yml:3
ok: [localhost] => {
    "msg": "base_path=/some/base/path, detailled_path=/some/base/path/detailed"
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0   
```

The whole test can be found in a [repo of mine](https://github.com/stehefan/ansible-dependency-bug-report), including the output of the different versions I tried this with.

**Comment by jctanner** [comment] 2016-11-14 19:01
Just for clarity, this is the diff between 2.0.2 and 2.1.3 in "example-role : show example role ouput"...

```
[jtanner@fedmac AP-18484]$ diff out.2.0.2 out.2.1.3
24c24
<     "msg": "base_path=/another/base, detailled_path=/another/base/detailed"
---
>     "msg": "base_path=/some/base/path, detailled_path=/some/base/path/detailed"
```

Here's a diff for the example repo to flag the expectation ...

```
diff --git a/roles/example-role/tasks/main.yml b/roles/example-role/tasks/main.yml
index 3b16c59..6b19cf0 100644
--- a/roles/example-role/tasks/main.yml
+++ b/roles/example-role/tasks/main.yml
@@ -3,3 +3,8 @@
 - name: show example role ouput
   debug:
     msg: "base_path={{ base_path }}, detailled_path={{ detailled_path }}"
+
+- name: make sure base_path is correct
+  assert:
+    that:
+        - "{{ base_path == '/another/base' }}"
```

**Comment by jctanner** [comment] 2016-11-14 20:02
I think this is a duplicate of https://github.com/ansible/ansible/issues/15996 based on bisection to https://github.com/ansible/ansible/commit/33de7707c9027ace26ec62bff8f58717f4080538

https://github.com/ansible/ansible/issues/16332 was opened in reference to #15996, in which jimi-c stated:

> Closing, as this required fixes were all in stable-2.1 already.

**Comment by jctanner** [comment] 2016-11-14 20:12
@jimi-c can you take a look?

**Comment by jimi-c** [comment] 2016-11-14 21:17
This does not appear related to that.

**Comment by jimi-c** [comment] 2016-11-15 17:50
After reviewing this, I believe the "Actual" output is correct. Because the base_path variable is being set in the meta data, it is overriding the value only for the dependent role and not for example-role, which is what I expect to happen. If you want the value to override the base_path value for both the example AND the dependent role, the variable should be set in the params for example-role in the playbook.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2016-11-15 17:50 UTC
Labels: affects_2.1, affects_2.2, affects_2.3, bug
