### ISSUE TITLE
Bug: new versions of "system/service.py" module fail to start php5-fpm service on ubuntu-14.04

### ISSUE THREAD

**Issue by fdupoux** [ansible/ansible#10675] opened 2015-04-13 12:06 UTC
Issue Type: Bug introduced by commit 8d53ef2f6055e174a10795bc5a084c3a36389678

Ansible Version: stable-1.9 branch is affected, version 1.8.4 works ok

Environment: Ubuntu-14.04 LTS with php5-fpm 5.5.9+dfsg-1ubuntu4.7 and upstart 1.12.1

Steps To Reproduce:
- Install Ubuntu-14.04 LTS with the php5-fpm package
- Get ansible to do a restart of the php5-fpm service
  MODULE_ARGS = 'name=php5-fpm state=restarted'

Expected Results:
Ansible should be able to restart the service (assuming the config is ok) using upstart

Actual Results:
Ansible uses /etc/init.d/php5-fpm to perform the restart and it fails

Comments: 
We are using ansible from a git clone, not from the apt package. I found this problem was introduced by commit 8d53ef2f6055e174a10795bc5a084c3a36389678 in service.py. Reverting this small changed makes it work for me. I tested by making the change in the temporary file on the target server in ~/.ansible/tmp/

**Comment by bcoca** [comment] 2015-04-13 13:13
try current devel, I believe this has already been fixed

**Comment by fdupoux** [comment] 2015-04-13 13:22
We actually had the problems in the "devel" branch initially, and the last commit in this branch on  ansible-modules-core/system/service.py is the actual change which caused the regression even though it is supposed to fix that sort of problems.

**Comment by otakup0pe** [comment] 2015-04-29 00:11
Looks like this might have slipped out with `1.9.1`? Yeah I just confirmed that it _is_ working wth `1.9.0.1` but _not_ with `1.9.1` :imp:

**Comment by mechastorm** [comment] 2015-04-29 02:02
I can confirm as well that this is still happening from the latest apt install as well. Doing an explicit version install to 1.9.0.1 seemed to fix it.

**Comment by elnur** [comment] 2015-04-29 16:57
Failing here. Version 1.9.1.

**Comment by zamoose** [comment] 2015-04-30 16:43
Confirming that we're running into it over on http://github.com/wpengine/hgv as well.

**Comment by elasticdog** [comment] 2015-05-01 15:14
I have also seen this behavior causing restart issues for the ssh daemon, where the OpenSSH package installs both an Upstart job (`/etc/init/ssh`) as well as a SysV init script (`/etc/init.d/ssh`). Definitely still broken for us running the latest devel version.

**Comment by tvaughan** [comment] 2015-05-01 15:23
To add some detail to what @elasticdog said:

```
$ ll /etc/init/ssh.conf /etc/init.d/ssh 
-rwxr-xr-x 1 root root 4077 May  2  2014 /etc/init.d/ssh*
-rw-r--r-- 1 root root  641 May  2  2014 /etc/init/ssh.conf
$ sudo ansible -m service -a "name=ssh state=restarted" 127.0.0.1
127.0.0.1 | FAILED >> {
    "failed": true,
    "msg": ""
}

$ sudo mv /etc/init.d/ssh /tmp/foobar                                                                                                              
$ sudo ansible -m service -a "name=ssh state=restarted" 127.0.0.1                                                                                          
127.0.0.1 | success >> {
    "changed": true,
    "name": "ssh",
    "state": "started"
}

$ sudo mv /tmp/foobar /etc/init.d/ssh                                                                                                              
$ sudo ansible -m service -a "name=ssh state=restarted" 127.0.0.1
127.0.0.1 | FAILED >> {
    "failed": true,
    "msg": ""
}
```

**Comment by hourliert** [comment] 2015-05-02 00:28
Failing here for docker service. Version 1.9.1. Works in 1.9.0.1

```
TASK: [docker.ubuntu | Reload docker] *****************************************
<git.wid.la> ESTABLISH CONNECTION FOR USER: thomas
<git.wid.la> REMOTE_MODULE service name=docker state=reloaded
<git.wid.la> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/thomashourlier/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=thomas -o ConnectTimeout=10 git.wid.la /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1430525354.33-155452269393607 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1430525354.33-155452269393607 && echo $HOME/.ansible/tmp/ansible-tmp-1430525354.33-155452269393607'
<git.wid.la> PUT /var/folders/f0/wcq2dmks3n985dd2bdcj34v00000gn/T/tmpO6Nm8l TO /home/thomas/.ansible/tmp/ansible-tmp-1430525354.33-155452269393607/service
<git.wid.la> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/thomashourlier/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=thomas -o ConnectTimeout=10 git.wid.la /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=udemwvbgvlxmmmangvtfguvgorvaihyi] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-udemwvbgvlxmmmangvtfguvgorvaihyi; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/thomas/.ansible/tmp/ansible-tmp-1430525354.33-155452269393607/service; rm -rf /home/thomas/.ansible/tmp/ansible-tmp-1430525354.33-155452269393607/ >/dev/null 2>&1'"'"''
failed: [git.wid.la] => {"failed": true}
msg:  * Docker is managed via upstart, try using service docker reload
```

**Comment by Invisibility** [comment] 2015-05-03 20:25
I debug this a little bit. It looks like there was a changed in ansible in handling the case when upstart is installed. Previously, ansible starts/stops/restarts/reloads php-fpm using service command, but now it uses /etc/init.d/php5-fpm start or /etc/init.d/php5-fpm stop instead. On the other hand, /etc/init.d/php5-fpm does nothing when the system has upstart.

This is the commit which changes the behavior of ansible service - https://github.com/ansible/ansible-modules-core/commit/29d211e7ab74300e9f96bced8e14fcb038eb7b43. More specifically, 

29d211e service cleanup
Brian Coca authored on Nov 17, 2014
449	            if location.get('start', False):
450	                # upstart -- rather than being managed by one command, start/stop/restart are actual commands
451	                self.svc_cmd = ''
452

**Comment by otakup0pe** [comment] 2015-05-04 03:11
@elasticdog I also saw this fail on ssh with Ubuntu 14.04 LTS.  Rolled back to 1.9.0.1 before investigating further.

**Comment by bcoca** [comment] 2015-05-04 18:36
closing as dupe of  https://github.com/ansible/ansible-modules-core/issues/1170, which has also been resolved

**Closed as completed by bcoca** 2015-05-04 18:36 UTC
Labels: P2, bug

**Comment by zamoose** [comment] 2015-05-04 18:41
@bcoca I'm confused. That appears to be a doc fix from a year ago...?

**Comment by bcoca** [comment] 2015-05-04 18:44
sorry, since this is in wrong repo I forgot to put full link

**Comment by elasticdog** [comment] 2015-05-04 18:51
@bcoca has the patch from that issue been merged somewhere else and it just hasn't been closed yet?

**Comment by bcoca** [comment] 2015-05-04 18:56
it is being worked on, closed this ticked more due to it being a duplicate in the wrong repo, keep track of the referenced ticket for the final resolution.

**Comment by tvaughan** [comment] 2015-05-27 14:14
> sorry, since this is in wrong repo I forgot to put full link
> 
> keep track of the referenced ticket for the final resolution.

@bcoca Sorry, I don't understand. Which link? Which referenced ticket? Thanks.

**Comment by oskarpearson** [comment] 2015-05-29 09:48
@tvaughan This is the issue - https://github.com/ansible/ansible-modules-core/issues/1170

It's been marked as fixed there, but it doesn't appear to be pushed into a release yet.

**Comment by tkellen** [comment] 2015-06-16 13:35
Any word on when this will make it into an official release?

**Comment by MauroNigrele** [comment] 2015-07-26 10:20
Still happen in 1.9.1.1
