### ISSUE TITLE
Allow playbook execution with default values, if decryption fails

### ISSUE THREAD

**Issue by soar** [ansible/ansible#16528] opened 2016-06-30 16:58 UTC
##### ISSUE TYPE
- Feature Idea
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /home/soar/ansible2/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

When I build new project with Ansible, I place all sensitive information to vault-encrypted files. I follow KISS principles and this files are included as `group_vars` (or `host_vars`). All works perfectly. So I have files like:

```
├── ansible.cfg
├── inventory
│   └── projectname
│       ├── group_vars
│       │   ├── hosts.yml
│       │   ├── somegroup.yml
│       │   └── somegroup-encrypted.yml
│       └── projectname
├── playbooks
│   ├── deploy-something.yml
│   └── test.yml
└── roles
    ├── somerole
    │   ├── defaults
    │   │   └── main.yml
```

But recently I started to use automated tests for my Ansible projects. So after commiting to repository, I run something like:

``` bash
ansible-playbook -vvv --syntax-check playbooks/test.yml
ansible-playbook -vvv --connection=local --sudo playbooks/test.yml
```

And check output. I want to run this tests without my encrypted data, and all variables are defined with default values in `rolename/defaults/main.yml`. But... I get only `ERROR! Decryption failed`.

I think, there should be some command-line switch, to run playbook without decryption for test purposes.

I know, that I can use `vars_files` or `-e` command-line switch, but then I should type them on every run. And I think encrypted files should be places in `inventory` with appropriate hosts, and not in playbooks directory.

And, of course, please don't forget about https://github.com/ansible/ansible/issues/14721

**Comment by nitzmahone** [comment] 2016-06-30 22:45
Duplicate of https://github.com/ansible/ansible/issues/13244, closing

**Closed as completed by nitzmahone** 2016-06-30 22:45 UTC
Labels: feature

**Comment by soar** [comment] 2016-07-01 06:12
Okay, but https://github.com/ansible/ansible/issues/13244 isn't clear description of a problem.

**Comment by nitzmahone** [comment] 2016-07-01 17:22
This one will be linked in there, so more "ammunition" for the feature (thanks for the detailed description of what you're after, BTW!). #13244 is a placeholder for this feature owned by an Ansible committer, and we don't want to keep two issues open for tracking purposes.
