### ISSUE TITLE
Module openssl_csr not working on MacOS 10.14.3

### ISSUE THREAD

**Issue by msnelling** [ansible/ansible#54303] opened 2019-03-24 13:02 UTC
##### SUMMARY
When trying to generate a CSR **locally** (for use with acme_certificate) on my Mac I get the following error: `You need to have PyOpenSSL>=0.15 to generate CSRs`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`lib/ansible/modules/crypto/openssl_csr.py`
##### ANSIBLE VERSION

```paste below
ansible 2.7.9
  config file = /Users/mark/.ansible.cfg
  configured module search path = ['/Users/mark/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.7.9/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.2 (default, Feb 12 2019, 08:15:36) [Clang 10.0.0 (clang-1000.11.45.5)]
```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(/Users/mark/.ansible.cfg) = False
```

##### OS / ENVIRONMENT

MacOS 10.14.3
Python 3.7.2
```
MacBook-Pro:~ mark$ pip3 freeze
asn1crypto==0.24.0
cffi==1.12.2
cryptography==2.6.1
pycparser==2.19
pyOpenSSL==19.0.0
six==1.12.0
```

##### STEPS TO REPRODUCE

Ensure PyOpenSSL is installed with `pip3 install pyopenssl`

```yaml
- hosts: all
  connection: local
  gather_facts: false
  tasks:
  - openssl_csr:
      path: /tmp/example.csr
      privatekey_path: /tmp/example.pem
      common_name: example.com
      subject_alt_name: DNS:www.example.com
      state: present
```

##### EXPECTED RESULTS

I would expect the playbook to generate a .csr file (or at least not complain about PyOpenSSL)

##### ACTUAL RESULTS

```paste below
TASK [openssl_csr] *****************************************************************************************************************
task path: /Users/mark/Developer/HomeLab/ansible-homelab-certs/site.yml:22
Trying secret ScriptVaultSecret(filename='/Users/mark/Developer/HomeLab/ansible-homelab-certs/get_vault_pass.sh') for vault_id=default
Trying secret ScriptVaultSecret(filename='/Users/mark/Developer/HomeLab/ansible-homelab-certs/get_vault_pass.sh') for vault_id=default
Using module file /usr/local/Cellar/ansible/2.7.9/libexec/lib/python3.7/site-packages/ansible/modules/crypto/openssl_csr.py
<mercury> ESTABLISH LOCAL CONNECTION FOR USER: mark
<mercury> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /usr/local/Cellar/ansible/2.7.9/libexec/lib/python3.7/site-packages/ansible/modules/crypto/openssl_csr.py
Using module file /usr/local/Cellar/ansible/2.7.9/libexec/lib/python3.7/site-packages/ansible/modules/crypto/openssl_csr.py
<10.118.251.116> ESTABLISH LOCAL CONNECTION FOR USER: mark
<10.118.251.116> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
<pluto> ESTABLISH LOCAL CONNECTION FOR USER: mark
<pluto> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/var/folders/ks/5f5f9c6d76g_4qdvd5yw3btc0000gn/T/ansible_openssl_csr_payload_FwdtRr/__main__.py", line 574, in main
    getattr(crypto.X509Req, 'get_extensions')

fatal: [mercury]: FAILED! => changed=false 
  invocation:
    module_args:
      attributes: null
      backup: null
      basicConstraints: null
      basicConstraints_critical: false
      commonName: example.com
      common_name: example.com
      content: null
      countryName: null
      delimiter: null
      digest: sha256
      directory_mode: null
      emailAddress: null
      extendedKeyUsage: null
      extendedKeyUsage_critical: false
      follow: false
      force: false
      group: null
      keyUsage: null
      keyUsage_critical: false
      localityName: null
      mode: null
      ocspMustStaple: false
      ocspMustStaple_critical: false
      organizationName: null
      organizationalUnitName: null
      owner: null
      path: /tmp/example.csr
      privatekey_passphrase: null
      privatekey_path: /tmp/example.pem
      regexp: null
      remote_src: null
      selevel: null
      serole: null
      setype: null
      seuser: null
      src: null
      state: present
      stateOrProvinceName: null
      subject: null
      subjectAltName:
      - DNS:www.example.com
      subjectAltName_critical: false
      subject_alt_name: DNS:www.example.com
      unsafe_writes: null
      version: 1
  msg: You need to have PyOpenSSL>=0.15 to generate CSRs
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/var/folders/ks/5f5f9c6d76g_4qdvd5yw3btc0000gn/T/ansible_openssl_csr_payload_LpCwLo/__main__.py", line 574, in main
    getattr(crypto.X509Req, 'get_extensions')
```

**Comment by felixfontein** [comment] 2019-03-25 16:45
!component =lib/ansible/modules/crypto/openssl_csr.py

**Comment by felixfontein** [comment] 2019-03-25 18:52
cc @MarkusTeufelberger @Shaps @Spredzy @Xyon @puiterwijk @resmo

**Comment by felixfontein** [comment] 2019-03-25 18:57
Should be fixed in 2.8 by using the cryptography backend. @Shaps wants to investigate it so we can see what's happening with pyOpenSSL.

**Comment by loski07** [comment] 2019-03-28 15:26
I can reproduce the error in the current development branch:

```
ansible 2.8.0.dev0
  config file = /Users/pdiazfernand/workspace/adp/adp-iaas/ansible.cfg
  configured module search path = [u'/Users/pdiazfernand/workspace/adp/adp-iaas/library']
  ansible python module location = /Users/pdiazfernand/software/runtimes/ansible-devel-python_venv/lib/python2.7/site-packages/ansible
  executable location = /Users/pdiazfernand/software/runtimes/ansible-devel-python_venv/bin/ansible
  python version = 2.7.10 (default, Aug 17 2018, 19:45:58) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)]
```

```
[2019-03-28 16:23] TASK [monitoring/prometheus-server : Generate a OpenSSL certificate signing request] *****************************************************************************************************************************************************************
task path: /Users/pdiazfernand/workspace/adp/adp-iaas/roles/monitoring/prometheus-server/tasks/main.yml:19
<toolchain-prometheus-server> ESTABLISH LOCAL CONNECTION FOR USER: pdiazfernand
<toolchain-prometheus-server> EXEC /bin/sh -c 'echo ~pdiazfernand && sleep 0'
<toolchain-prometheus-server> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/pdiazfernand/.ansible/tmp/ansible-tmp-1553786634.51-6291694186274 `" && echo ansible-tmp-1553786634.51-6291694186274="` echo /Users/pdiazfernand/.ansible/tmp/ansible-tmp-1553786634.51-6291694186274 `" ) && sleep 0'
Using module file /Users/pdiazfernand/software/runtimes/ansible-devel-python_venv/lib/python2.7/site-packages/ansible/modules/crypto/openssl_csr.py
<toolchain-prometheus-server> PUT /Users/pdiazfernand/.ansible/tmp/ansible-local-3673qeAckV/tmpvT47d3 TO /Users/pdiazfernand/.ansible/tmp/ansible-tmp-1553786634.51-6291694186274/AnsiballZ_openssl_csr.py
<toolchain-prometheus-server> EXEC /bin/sh -c 'chmod u+x /Users/pdiazfernand/.ansible/tmp/ansible-tmp-1553786634.51-6291694186274/ /Users/pdiazfernand/.ansible/tmp/ansible-tmp-1553786634.51-6291694186274/AnsiballZ_openssl_csr.py && sleep 0'
<toolchain-prometheus-server> EXEC /bin/sh -c 'no_proxy=localhost,127.0.0.1,.allianz https_proxy=http://svr001-e1-svr.zone2.proxy.allianz:8090 http_proxy=http://svr001-e1-svr.zone2.proxy.allianz:8090 /usr/bin/python /Users/pdiazfernand/.ansible/tmp/ansible-tmp-1553786634.51-6291694186274/AnsiballZ_openssl_csr.py && sleep 0'
<toolchain-prometheus-server> EXEC /bin/sh -c 'rm -f -r /Users/pdiazfernand/.ansible/tmp/ansible-tmp-1553786634.51-6291694186274/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/var/folders/g5/gjxq61196z39v1cjb4tslfww0000gn/T/ansible_openssl_csr_payload_SmQ8Gs/__main__.py", line 349, in <module>
    import cryptography

fatal: [toolchain-prometheus-server]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "attributes": null, 
            "backup": null, 
            "basic_constraints": null, 
            "basic_constraints_critical": false, 
            "common_name": "toolchain-prometheus-server.apps.tools.adp.allianz", 
            "content": null, 
            "country_name": "DE", 
            "delimiter": null, 
            "digest": "sha256", 
            "directory_mode": null, 
            "email_address": "adp-service@allianz.de", 
            "extended_key_usage": null, 
            "extended_key_usage_critical": false, 
            "follow": false, 
            "force": false, 
            "group": null, 
            "key_usage": null, 
            "key_usage_critical": false, 
            "locality_name": null, 
            "mode": null, 
            "ocsp_must_staple": false, 
            "ocsp_must_staple_critical": false, 
            "organization_name": "AZTECH", 
            "organizational_unit_name": null, 
            "owner": null, 
            "path": "/Users/pdiazfernand/workspace/adp/adp-iaas/workspace/toolchain-prometheus-server/toolchain-prometheus-server.apps.tools.adp.allianz.csr", 
            "privatekey_passphrase": null, 
            "privatekey_path": "/Users/pdiazfernand/workspace/adp/adp-iaas/workspace/toolchain-prometheus-server/toolchain-prometheus-server.apps.tools.adp.allianz.pem", 
            "regexp": null, 
            "remote_src": null, 
            "select_crypto_backend": "auto", 
            "selevel": null, 
            "serole": null, 
            "setype": null, 
            "seuser": null, 
            "src": null, 
            "state": "present", 
            "state_or_province_name": null, 
            "subject": null, 
            "subject_alt_name": null, 
            "subject_alt_name_critical": false, 
            "unsafe_writes": null, 
            "use_common_name_for_san": true, 
            "version": 1
        }
    }, 
    "msg": "Can detect none of the Python libraries cryptography (>= 1.3) and pyOpenSSL (>= 0.15)"
}
```
pip freeze
```
adal==1.2.1
ansible==2.8.0.dev0
asn1crypto==0.24.0
bcrypt==3.1.6
cachetools==3.1.0
certifi==2019.3.9
cffi==1.12.2
chardet==3.0.4
cryptography==2.6.1
dictdiffer==0.8.0
enum34==1.1.6
google-auth==1.6.3
idna==2.8
ipaddress==1.0.22
Jinja2==2.10
kubernetes==8.0.1
MarkupSafe==1.1.1
oauthlib==3.0.1
openshift==0.8.7
paramiko==2.4.2
pyasn1==0.4.5
pyasn1-modules==0.2.4
pycparser==2.19
PyJWT==1.7.1
PyNaCl==1.3.0
python-dateutil==2.8.0
python-string-utils==0.6.0
pyvmomi==6.7.1.2018.12
PyYAML==5.1
requests==2.21.0
requests-oauthlib==1.2.0
rsa==4.0
ruamel.ordereddict==0.4.13
ruamel.yaml==0.15.89
six==1.12.0
urllib3==1.24.1
websocket-client==0.56.0
```

**Comment by loski07** [comment] 2019-03-28 16:12
It also affects to `openssl_certificate` module

**Comment by loski07** [comment] 2019-03-28 17:37
I found the problem in my case, even though I have set `connection: local` in the play I needed to specify the `ansible_python_interpreter` for the host where I have the modules installed

**Comment by felixfontein** [comment] 2019-03-28 17:50
@loski07 thanks for resolving this (at least in your case)! This is what I would have guessed from the output you posted above (otherwise the Ansible modules should have found the Python modules).

@msnelling can you check whether this is also the problem in your case?

**Comment by msnelling** [comment] 2019-03-28 21:57
I'm not sure if @loski07 has the same problem. I have one host, my Mac, that I am trying to run the `openssl_csr` task on using the local connection. There are two python interpreters, the default one installed at `/usr/bin/python` and one from Homebrew at `/usr/local/bin/python3`. Both of these have the same error if I specify `ansible_python_interpreter` in the `ansible.cfg`. Is this the right place to configure the interpreter?

**Comment by felixfontein** [comment] 2019-03-29 05:31
You have to set `ansible_python_interpreter` in the inventory variables; I think you can also just set it for one task:
```.yaml
- openssl_csr:
    ...
  vars:
    ansible_python_interpreter: ...
```
Though it could be that this only will work for 2.8, and not for 2.7.x. I don't think you can configure it in `ansible.cfg`; at least https://docs.ansible.com/ansible/latest/reference_appendices/config.html doesn't mention it (in 2.8, you will be able to mention it with `interpreter_python` in the `defaults` section; see also https://docs.ansible.com/ansible/devel/reference_appendices/interpreter_discovery.html).

**Comment by msnelling** [comment] 2019-04-13 12:47
Setting the `ansible_python_interpreter` variable on the `openssl_csr` task does indeed work for ansible 2.7. What I don't like about this approach is that it isn't portable between my Mac laptop and Linux workstation.

**Comment by loski07** [comment] 2019-04-13 13:39
You can always pass an extra var to the ansible-playbook script. It will apply to all hosts

**Comment by felixfontein** [comment] 2019-04-13 17:21
@msnelling you could also install pyOpenSSL for the Python installation used by Ansible by default, then you don't have to specify `ansible_python_interpreter`. But if you install it for another Python installation than the default one, you need `ansible_python_interpreter` to tell Ansible which one to use.

**Comment by felixfontein** [comment] 2019-04-13 18:17
Closing this issue since this is not a module bug.

notabug

**Closed as completed** 2019-04-13 18:22 UTC
Labels: python3, module, support:community, bug, traceback, affects_2.7, macos, crypto
