### ISSUE TITLE
when conditional does not allow for "truthy" checks with strings

### ISSUE THREAD

**Issue by rommsen** [ansible/ansible#20392] opened 2017-01-18 12:17 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
when conditional

##### ANSIBLE VERSION
```
ansible 2.2.1.0
```

##### SUMMARY
When testing for variables we have a lot of tasks that simply check for 
```
when: variable
```
where variable is a string. 

See for example: https://github.com/ANXS/postgresql/blob/master/tasks/install.yml#L21

This role worked for us until now but after upgrading to `2.2.1.0` we get errors (see below)
It looks like the conditional does not use *truthy* checks for strings anymore?
Am I completely wrong here? Or did this behaviour change?

##### STEPS TO REPRODUCE

```yaml
---
- hosts: all
  remote_user: "{{ deploy_user }}"

  vars:
    test: "deb http://apt.postgresql"

  tasks:
    - debug: var=test
      when: test
```

##### EXPECTED RESULTS
```
ok: [testserver1] => {
    "test": "deb http://apt.postgresql"
}
 _
```

##### ACTUAL RESULTS
```
fatal: [testserver1]: FAILED! => {
    "failed": true, 
    "msg": "The conditional check 'test' failed. The error was: expected token 'end of statement block', got 'http'\n  line 1\n\nThe error appears to have been in '/home/roman/development/deployment/ansible/test.yml': line 10, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - debug: var=test\n      ^ here\n"
}
```

**Comment by mikestankavich** [comment] 2017-01-19 15:25
It appears that the variable contents are being evaluated. This test case produces a divide by zero error. 

```
---
- name: Truthy string variable conditional test case
  hosts: all
  ignore_errors: yes
  vars:
    my_string: "1/0"
  tasks:
    - name: Conditionally display my_string value using explicit conditional
      debug: var=my_string
      when: my_string | default('') != ''
    - name: Conditionally display my_string value using truthy conditional
      debug: var=my_string
      when: my_string
```

#### **Expected result:** 
```
TASK [Conditionally display my_string value using explicit conditional] ********
ok: [localhost] => {
    "my_string": "1/0"
}

TASK [Conditionally display my_string value using truthy conditional] **********
ok: [localhost] => {
    "my_string": "1/0"
}
```

#### **Actual result:** 

```
TASK [Conditionally display my_string value using explicit conditional] ********
ok: [localhost] => {
    "my_string": "1/0"
}

TASK [Conditionally display my_string value using truthy conditional] **********
fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check 
'my_string' failed. The error was: division by zero\n\nThe error appears to have 
been in '/Users/jmstanka/ansiblewtf/inline.yml': line 11, column 7, but may\nbe 
elsewhere in the file depending on the exact syntax problem.\n\nThe offending 
line appears to be:\n\n
      when: my_string | default('') != ''\n    - name: Conditionally display my_string 
value using truthy conditional\n      ^ here\n"}
```

**Comment by geerlingguy** [comment] 2017-01-19 16:22
I haven't had the time to write up my own test cases, but this does look fairly major—I hate to admit, but I often am lazy enough to rely on python's duck typing in my `when` conditionals, and I can imagine a lot of my roles breaking if certain 'truthy' checks start getting more strict.

**Comment by nitzmahone** [comment] 2017-01-19 18:49
@jimi-c this looks like fallout from recent eval stuff at fiirst glance...

**Comment by pabelanger** [comment] 2017-01-21 22:54
Same issue here:

```
2017-01-21 22:49:11.650125 | TASK [openstack.ssh : Create ssh private key.] *********************************
2017-01-21 22:49:11.672733 | fatal: [nodepool]: FAILED! => {"failed": true, "msg": "The conditional check 'ssh_key_private_content' failed. The error was: expected token 'end of statement block', got 'RSA'\n  line 1\n\nThe error appears to have been in '/home/jenkins/workspace/gate-windmill-deploy-ubuntu-xenial/playbooks/roles/openstack.ssh/tasks/config.yaml': line 34, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create ssh private key.\n  ^ here\n"}
```

**Comment by jimi-c** [comment] 2017-02-16 19:19
@MikeStankavich that actually happens on older versions of Ansible as well, so that case is not a regression, it's just a side-effect of the fact that we allow bare variables like this in conditionals. The correct solution is to use `is defined` in these kinds of situations where the variable may not contain a boolean value.

**Comment by jimi-c** [comment] 2017-02-16 19:28
As far as I can tell (looking back to 1.9.6), this is not a regression - conditionals have always behaved this way. If you use a bare variable, it will substitute it and use the contents for the conditional, which allows things like this:
<pre>
- assert:
    that: item
  with_items: [true, false]
</pre>
(as the assert module uses conditionals too under the hood).

**Comment by jimi-c** [comment] 2017-02-16 19:30
Based on the above, I will close this now. The correct solution is to use `is defined` (or `is not defined`) on variables to check that they're set (or not).

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2017-02-16 19:30 UTC
Labels: P2, affects_2.2, c:playbook/conditional, bug

**Comment by mikestankavich** [comment] 2017-02-20 15:22
Thank you for following up on this. While I appreciate your clarification, I find that `is defined` does not behave the same with empty strings. In the case of empty string, the JavaScript truthy paradigm results in a `false` value, whereas the ansible `var is defined` conditional results in a `true` when the variable is defined and contains empty string. 

So if I understand correctly, the preferred syntax for the "variable is defined and contains a truthy value" case would be `var is defined and var != ''` or `var | default('') != ''`.

**Comment by jimi-c** [comment] 2017-02-24 05:09
@MikeStankavich `default()` also takes an option to operate on the variable based on the boolean value as well: `default('something', boolean=True)`. Using this, the default would replace an empty string. For more info see: http://jinja.pocoo.org/docs/2.9/templates/#default

**Comment by mikestankavich** [comment] 2017-02-24 14:36
@jimi-c Thanks for the followup. So what that means is that we can get the desired behavior with `default(false)`, as the variable containing an empty string evaluates to falsy, thus triggering the default. That's more concise than the `var is defined and var != ''` that I have been using. 

So just to close the loop on this, in the case where you want a task to run only when a related variable is defined and does not contain an empty string, use either `when: var | default(false)` or `when: var is defined and var != ''`. 

I put together a gist with tests to validate the various options that have been discussed at  https://gist.github.com/MikeStankavich/37030769deee90da0b08134ac72c9ac0
