### ISSUE TITLE
playbook hangs when --ask-sudo-pass not supplied and is required (vs error msg raised) [edited description]

### ISSUE THREAD

**Issue by brodul** [ansible/ansible#7204] opened 2014-04-29 09:48 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.5
##### Environment:

Running from NixOs, managing GCE (small instance) Debian 7.4 without backports.
##### Summary:

The problem is that the file and unarchive (possibly others) freeze when using sudo user option on a task. This basically breaks the deploy process.
##### Steps To Reproduce:

The bug can be reproduced with this playbook:
https://gist.github.com/brodul/11395154

One liner also freezes (after the user is created):

```
ansible -i tmp_inventory all -m file -a 'path=/srv/pikapika/engine/current/ state=directory' --sudo-user=pikapika --sudo
```
##### Expected Results:

There should be a failure, not a freeze. Or even better a directory called `/srv/pikapika/engine/current/` owned by 'pikapika'
##### Actual Results:

The whole thing freezes

https://gist.github.com/brodul/11395399

Notice there are some anomalies in the gist above:
I changed the project user from 'nomnom' to 'pikapika'. But the 'nomnom' still persist.

Tnx for reading this. If you need additional info don't hasitate to ask.
Here is a llama: https://flic.kr/p/9ybQmk

**Comment by brodul** [comment] 2014-04-29 11:18
It seems that the unarchive module is not working even without the sudo_user.

**Comment by mpdehaan** [comment] 2014-04-29 12:44
Did you need to supply --ask-sudo-pass ?

There is a open ticket about sudo prompt detection needing to be ironed out somewhat such that if it is waiting for a prompt it will report that a password is supplied.

This seems exactly like what is going on for me, as sudo support is known to work well (there would be villagers with pitchforks if not).

**Comment by brodul** [comment] 2014-04-29 13:34
I added the `-K` option. It's working now. Tnx

Huh, this is super confusing because I have a
`brodul ALL=NOPASSWD: ALL` entry in my `/etc/sudoers`
I guess I should not be prompt for the sudo password?

This will make spawning new instances hard because I need to ssh to the instance and set my password. Note that when I am calling sudo from the shell I don't need a password.

**Comment by brodul** [comment] 2014-04-30 08:51
Aha, I have found my misconfiguration.
In the sudoers file there should be an entry `brodul ALL= (ALL) NOPASSWD: ALL` and not `brodul ALL=NOPASSWD: ALL`.

**Comment by jimi-c** [comment] 2015-06-22 04:45
Hi @brodul, looking back at this issue it seems like this issue was misconfiguration issue and not something Ansible was doing incorrectly? If you're still having a problem with this please let us know, otherwise we'll close this issue out.

**Comment by jctanner** [comment] 2016-05-27 12:11
Duplicate of https://github.com/ansible/ansible/issues/7165

**Closed as completed by jctanner** 2016-05-27 12:11 UTC
Labels: bug
