### ISSUE TITLE
docker_image module object has no attribute APIError

### ISSUE THREAD

**Issue by zjeraar** [ansible/ansible#8011] opened 2014-07-01 20:01 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

1.6.5
##### Environment:

control OS: Ubuntu 14.04
managed OS: Ubuntu 14.04
##### Summary:

The docker_image module gives me an error every time I try to run it, no matter what state I use.
##### Steps To Reproduce:

docker_image:
    name='user/app'
    tag='1.0'
    path='/build/path'
    state=build
##### Expected Results:

A user/app image, with no error reported back.
##### Actual Results:

The build itself actually works (image is present afterwards), but I get the following error:

fatal: [my.server.com] => failed to parse: SUDO-SUCCESS-zifpeodwifbudvwfyirskzschingrdvb
{"msg": "Image builded: 8b63a1d631f0", "failed": false, "changed": true, "image_id": "8b63a1d631f0"}
Traceback (most recent call last):
  File "/home/tds/.ansible/tmp/ansible-tmp-1404244300.34-22987635386790/docker_image", line 1455, in <module>
    main()
  File "/home/tds/.ansible/tmp/ansible-tmp-1404244300.34-22987635386790/docker_image", line 229, in main
    except docker.client.APIError as e:
AttributeError: 'module' object has no attribute 'APIError'

**Comment by myhro** [comment] 2014-07-02 03:43
Experienced something like this, except that I couldn't build the image. Downgrading to `docker-py==0.3.1` solved the problem.

**Comment by jimi-c** [comment] 2014-07-05 05:38
We've had a couple of these, due to the docker API changing. Have you tested this against devel to see if this was one of the errors we've fixed already?

**Comment by zjeraar** [comment] 2014-07-09 09:28
No I did not test it on devel, will try asap.

**Comment by fangpenlin** [comment] 2014-07-09 23:19
got the same issue here

**Comment by prune998** [comment] 2014-07-10 13:00
same issue. While the APIError exception not existing is an error, the exception is triggered in the create_containers() function.
digging in it right now.

**Comment by jimi-c** [comment] 2014-07-10 13:13
I believe this was fixed here: https://github.com/ansible/ansible/pull/7029

**Comment by prune998** [comment] 2014-07-10 13:13
docker version

```
Client version: 1.0.1
Client API version: 1.12
Go version (client): go1.2.1
Git commit (client): 990021a
Server version: 1.0.1
Server API version: 1.12
Go version (server): go1.2.1
Git commit (server): 990021a
```

Docker-py version : 0.3.2
Server version : ubuntu 14.04 :

```
Linux docker-0 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

In the python file generated by ansible to create a container, the create_containers() function define the creation parameters as :

```
        params = {'image':        self.module.params.get('image'),
                  'command':      self.module.params.get('command'),
                  'volumes_from': self.module.params.get('volumes_from'),
                  'mem_limit':    _human_to_bytes(self.module.params.get('memory_limit')),
                  'environment':  self.module.params.get('env'),
                  'dns':          self.module.params.get('dns'),
                  'hostname':     self.module.params.get('hostname'),
                  'detach':       self.module.params.get('detach'),
                  'privileged':   self.module.params.get('privileged'),
                  }
```

But the "privileged" parameter does not exist on the docker-py side, leading to a :

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: create_container() got an unexpected keyword argument 'privileged'
```

**Comment by prune998** [comment] 2014-07-10 13:15
this seems to be corrected in the trunk... please, release a stable version as this is production blocking !

**Comment by jimi-c** [comment] 2014-07-10 13:16
Ahh I see, so the fix above is related to the proper module location for APIError, but is there another underlying issue we need to address with the incorrect parameter above?

**Comment by rubycut** [comment] 2014-07-23 12:43
+1 same issue here.

Docker version 1.1.1, build bd609d2
ansible 1.6.6

**Comment by prune998** [comment] 2014-07-23 12:46
rubycut, it seems the problem is gone for me... did a pip install --upgrade ansible
...

**Comment by hjwp** [comment] 2014-07-30 17:27
hmmm.  I'm still seeing this in ansible 1.6.10 / dockerpy 0.3.2

**Comment by yongjunj** [comment] 2014-08-01 23:14
I'm seeing this with:

```
ansible 1.6.10

docker:
Client version: 1.1.2
Client API version: 1.13
Go version (client): go1.2.1
Git commit (client): d84a070
Server version: 1.1.2
Server API version: 1.13
Go version (server): go1.2.1
Git commit (server): d84a070

docker-py 0.4.0 as well as 0.3.1
```

I can also confirm that it's fixed in `devel`.

**Comment by jimi-c** [comment] 2014-08-11 19:01
@yongjunj thanks for confirming it's fixed in devel. If others can confirm as well, I'll go ahead and close this, or if others are still seeing this in devel I can look into it further.

**Comment by jimi-c** [comment] 2014-08-15 17:00
# Closing This Ticket

Hi!

We believe the above issue has been resolved, and was included in the 1.7.0 release,

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2014-08-15 17:00 UTC
Labels: cloud, P2, docker, bug

**Comment by tcurdt** [comment] 2014-11-14 16:47
Just for the record.

```
msg: Docker API error: client and server don't have same version (client : 1.15, server: 1.12)

$ docker version
Client version: 1.3.0
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): c78088f
OS/Arch (client): darwin/amd64
Server version: 1.3.1
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): 4e9bbfa

$ ansible --version
ansible 1.7.2
```

Now trying to reach someone on IRC or the mailing list.

**Comment by vincentvdk** [comment] 2014-11-19 07:35
@tcurdt have you found a solution for this? Experience the same on 1.8-0.git201411182342

**Comment by vincentvdk** [comment] 2014-11-19 08:30
Found the issue. I had docker-py==0.6.0 installed. Downgraded to 0.4.0 and works now.

**Comment by tcurdt** [comment] 2014-11-19 08:46
@vincentvdk my ansible was talking to the wrong docker instance. using `connection: local` did the trick.

**Comment by joestubbs** [comment] 2015-01-21 17:31
downgrading to docker-py==0.4.0 worked for me as well.

**Comment by sebgoa** [comment] 2015-01-27 11:25
it seems to be reoccurring on ansible 1.8.2, docker 1.4.1, ubuntu 14.04, python 2.7.6 and docker-py (0.4.0 or 0.7.1)

**Comment by sebgoa** [comment] 2015-01-27 11:44
ok my bad, I was pointing to some old ansible core modules installed via source. never mind.

**Comment by sredni** [comment] 2015-02-09 16:10
just use docker_api_version=<version>
docker-py trying use latest api but you can force using specific version of api.

**Comment by hvpareja** [comment] 2015-03-26 21:15
I think we should reopen this issue, still happens with the latest versions of both docker-py and docker API:

Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef

docker-py == 1.1.0

**Comment by abadger** [comment] 2015-03-26 22:57
@hvpareja Please open a new ticket.  This issue, as originally reported, has been fixed.  So there's something new going on.  Including enough information for us to reproduce will be of great help.  thanks!
