### ISSUE TITLE
Colon in lineinfile argument cause Syntax Error

### ISSUE THREAD

**Issue by r0bj** [ansible/ansible#5087] opened 2013-11-27 22:31 UTC
I'm trying to edit /etc/aliases and add a root forward like this:

`lineinfile: dest=/etc/aliases regexp="^root:\s+{{ root_mail_forward }}" line="root: {{ root_mail_forward }}"`

It generates error:

`ERROR: Syntax Error while loading YAML script`

I read YAML Gotchas and try different syntax:

```
lineinfile: dest=/etc/aliases regexp="^root:\s+{{ root_mail_forward }}" 'line=root: "{{ root_mail_forward }}"'
lineinfile: dest=/etc/aliases regexp="^root:\s+{{ root_mail_forward }}" "line=root: '{{ root_mail_forward }}'"
lineinfile: dest=/etc/aliases regexp="^root:\s+{{ root_mail_forward }}" "line=root: \"{{ root_mail_forward }}\""
lineinfile: "dest=/etc/aliases regexp='^root:\s+{{ root_mail_forward }}' line=root: '{{ root_mail_forward }}'"
lineinfile: "dest=/etc/aliases regexp='^root:\s+{{ root_mail_forward }}' 'line=root: {{ root_mail_forward }}'"
```

None of them works. I'm using ansible 1.4.

**Comment by mpdehaan** [comment] 2013-11-27 22:34
Yeah this is just a YAML thing.  

The last one looks correct to me but we'll take a look:

```
lineinfile: "dest=/etc/aliases regexp='^root:\s+{{ root_mail_forward }}' 'line=root: {{ root_mail_forward }}'"
```

**Comment by mpdehaan** [comment] 2013-11-27 22:35
Incidentally, not sure if you knew you can do this:

```
- name: yada yada
  module_name:
      arg1: foo
      arg2: bar
```

Might make it a little easier.

**Comment by sivel** [comment] 2013-11-27 22:46
I've also had luck with the following (folded) syntax:

```
lineinfile: >
    dest=/etc/aliases regexp="^root:\s+{{ root_mail_forward }}" line="root: {{ root_mail_forward }}"
```

**Comment by mpdehaan** [comment] 2013-11-28 02:37
BTW, this is more of a user question, not a bug, so I'm closing the ticket.

I'd suggest joining the mailing list!

**Closed as completed by mpdehaan** 2013-11-28 02:37 UTC

**Comment by r0bj** [comment] 2013-11-28 17:13
Thanks. BTW, I found a working syntax :)

`lineinfile: 'dest=/etc/aliases regexp="^root:\s+{{ root_mail_forward }}" "line=root: {{ root_mail_forward }}"'`

**Comment by pmackay** [comment] 2015-01-04 19:13
The syntax @r0bj has used worked for me too, and is different to the example in the docs. Would it be worth updating the docs with some more examples?
