### ISSUE TITLE
AttributeError: 'Block' object has no attribute 'notified_hosts'

### ISSUE THREAD

**Issue by snuser** [ansible/ansible#59855] opened 2019-07-31 09:51 UTC
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.8.2
```

##### CONFIGURATION

```paste below
 DEFAULT_FORKS(/root/k_img_deploy/ansible.cfg) = 4
DEFAULT_HOST_LIST(/root/k_img_deploy/ansible.cfg) = [u'/root/k_img_deploy/hosts']
DEFAULT_LOG_PATH(/root/k_img_deploy/ansible.cfg) = /root/k_img_deploy/logs/ansible.log
DEFAULT_ROLES_PATH(/root/k_img_deploy/ansible.cfg) = [u'/root/k_img_deploy/roles']
DEFAULT_TIMEOUT(/root/k_img_deploy/ansible.cfg) = 30
```

##### OS / ENVIRONMENT

CentOS release 6.10 (Final)

##### STEPS TO REPRODUCE

```yaml
 tasks:
  - set_fact:
      kproxy_service_vars:
        service_name: kproxy
        conf_path: "{{nginx_kwork_conf_path}}"
      kwork_service_vars:
        service_name: kwork
        conf_path: "{{nginx_kproxy_conf_path}}"

  - name: xxx
    copy: src="{{local_template_path}}" dest="{{node_template_path}}" force=yes

  - name: xxx
    copy: src="{{nginx_kproxy_template_conf_path}}" dest="{{nginx_kproxy_conf_path}}" force=yes
    notify:
      -  reload nginx_kproxy

  - name: xxx
    copy: src="{{nginx_kwork_template_conf_path}}" dest="{{nginx_kwork_conf_path}}" force=yes
    notify:
      -  reload nginx_kwork

  handlers:
  - name: reload nginx_kproxy
    import_role:
      name: nginx_service
    vars:
      service_vars: kproxy_service_vars

  - name: reload nginx_kwork
    import_role:
      name: nginx_service
    vars:
      service_vars: kwork_service_vars
```

##### ACTUAL RESULTS

```paste below

```

**Comment by snuser** [comment] 2019-07-31 09:52
ERROR! Unexpected Exception, this is probably a bug: 'Block' object has no attribute 'notified_hosts'
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 110, in <module>
    exit_code = cli.run()
  File "/usr/local/python2.7/lib/python2.7/site-packages/ansible/cli/playbook.py", line 123, in run
    results = pbex.run()
  File "/usr/local/python2.7/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 169, in run
    result = self._tqm.run(play=play)
  File "/usr/local/python2.7/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 249, in run
    play_return = strategy.run(iterator, play_context)
  File "/usr/local/python2.7/lib/python2.7/site-packages/ansible/plugins/strategy/linear.py", line 263, in run
    results.extend(self._execute_meta(task, play_context, iterator, host))
  File "/usr/local/python2.7/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 1003, in _execute_meta
    self.run_handlers(iterator, play_context)
  File "/usr/local/python2.7/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 855, in run_handlers
    if handler.notified_hosts:
AttributeError: 'Block' object has no attribute 'notified_hosts'

**Comment by mkrizek** [comment] 2019-07-31 10:36
Duplicate of https://github.com/ansible/ansible/issues/20493

**Closed as completed by mkrizek** 2019-07-31 10:36 UTC
