### ISSUE TITLE
ec2_lc doesn't update launch config when parameter value changed on subsequent runs

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#8927] opened 2014-09-08 19:12 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

1.7.1
##### Environment:

EC2
##### Summary:

I created a new launch configuration using the ec2_lc module without issue.  After the LC had been created, I had to change instance_monitoring to yes.  When I reran my playbook to create the LC, the task came back as OK and was unchanged.  I am not sure if other parameters would fall into this same issue.

Initial run:
- name: create launch configuration
  local_action:
    module: ec2_lc
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    name: my_lc
    state: present
    region: us-east-1
    key_name: "{{ aws_key }}"
    image_id: ami-12345678
    instance_type: "{{ instance_type }}"
    security_groups: "sg-12345678"
    user_data: "{{ lookup('file', 'user-data.txt') }}"
  register: lc

Subsequent runs:
- name: create launch configuration
  local_action:
    module: ec2_lc
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    name: my_lc
    state: present
    region: us-east-1
    key_name: "{{ aws_key }}"
    image_id: ami-12345678
    instance_type: "{{ instance_type }}"
    security_groups: "sg-12345678"
    user_data: "{{ lookup('file', 'user-data.txt') }}"
    instance_monitoring: yes
  register: lc
##### Steps To Reproduce:

Create a task to create an EC2 launch configuration.  
Run it and verify the LC has been created as specified
Modify the task to add instance_monitoring: yes
Rerun the task
The state returned is unchanged
##### Expected Results:

The LC would be updated with the new configuration
##### Actual Results:

The LC was unmodified

**Comment by jsmartin** [comment] 2014-09-09 17:03
This is because launch configs are immutable.  This is how Amazon has designed it.  You must create a new launch config and assign it to the autoscale group.

**Comment by mpdehaan** [comment] 2014-09-11 20:11
We should probably add a note to the docs on this maybe.

**Closed as completed** 2014-09-19 20:21 UTC
Labels: cloud, P2, bug

**Comment by jimi-c** [comment] 2014-09-19 20:28
Note added, so closing this.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
