### ISSUE TITLE
Top-level playbook: tags broken

### ISSUE THREAD

**Issue by jan-g** [ansible/ansible#11309] opened 2015-06-18 10:34 UTC
See the attachment. With ansible 1.7.2 this works as expected:

% ansible-playbook --version
ansible-playbook 1.7.2
% ansible-playbook -i hosts/localhost a.yml --tags b

PLAY [localhost] 

---

GATHERING FACTS 

---

ok: [localhost]

TASK: [debug msg="b"] 

---

ok: [localhost] => {
    "msg": "b"
}

PLAY RECAP 

---

localhost                  : ok=2    changed=0    unreachable=0  
failed=0   

With 1.9.1 it's broken:

% ansible-playbook --version
ansible-playbook 1.9.1
% ansible-playbook -i hosts/localhost a.yml --tags b
ERROR: tag(s) not found in playbook: b.  possible values:

**Comment by jan-g** [comment] 2015-06-18 10:37
a.yml:

```
- include: b.yml tags=b
- include: c.yml tags=c
```

b.yml:

```
- hosts: localhost
  tasks:
  - debug: msg="b"
```

c.yml:

```
- hosts: localhost
  tasks:
  - debug: msg="c"
```

**Comment by bcoca** [comment] 2015-06-18 14:32
closing as duplicate of #9862

**Closed as completed by bcoca** 2015-06-18 14:32 UTC
Labels: bug
