### ISSUE TITLE
Winrm connections are not closed, resulting in multiple winrshost.exe processes on target node

### ISSUE THREAD

**Issue by trondhindenes** [ansible/ansible#12275] opened 2015-09-07 20:27 UTC
Issue Type:
Bug Report

Ansible Version:
Latest, running from devel

Ansible Configuration:
Using kerberos winrm authentication

Environment:
Ubuntu 14.04 control node, Windows 2012R2 nodes

Summary:
After running big playbooks, I see a lot of processes from the ansible user account. I get the feeling that Ansible doesn't correctly "hang up" the connection. Working on repro across more nodes.

Steps To Reproduce:
fire a multi-task playbook against a windows node. Using taskmanager, view all the winrshost.exe processes that get spawned but not terminated

Expected Results:
Ansible should close the winrm connection, causing the winrshost processes to terminate

Actual Results:
See steps to repro

**Comment by trondhindenes** [comment] 2015-09-08 20:26
Yep, confirmed. I can repro this across PSv4 and PSv5 nodes (not tested on PSv3).

**Comment by trondhindenes** [comment] 2015-09-08 20:29
ping @jimi-c @cchurch could this be related to the winrm changes done the last months?

**Comment by cchurch** [comment] 2015-09-08 20:43
It was fixed via https://github.com/ansible/ansible/pull/11719/files#diff-76ffc0551f8cf3d6255500316568e60bR130 -- unless something has broken it since.

**Comment by bcoca** [comment] 2015-09-08 20:46
Yes, that 'fix' introduced connection closing after each task, which should
not be the case, I removed it because it closed the ssh control persist
making it useless.

Any open connections should close at the end of the run, unless this is not
possible with winrm?

## 

Brian Coca

**Comment by trondhindenes** [comment] 2015-09-08 20:56
The problem as it sits right now is that any given user is (by default) limited to 30 simultaneous winrm sessions against a given node, so any playbook with more than 30 "interactions" with a node will throw an error - which is very bad. Again I'm afraid I'm pretty useless in the python department so I can only report these errors. Chris, are you able to repro on the current devel? You should see a bunch of winrshost.exe processes from the same user when testing. WinRM will close these out after a (configurable) timeout, but we can't rely on that for production usage.

**Comment by bcoca** [comment] 2015-09-08 20:58
can we not reuse these connections?

## 

Brian Coca

**Comment by cchurch** [comment] 2015-09-09 03:37
I'm able to reproduce against 1f4c65ab9a36f46d215636eb75385691d8faccbc.  Closing the TCP connection does not cleanup the remote WinRM session; it's necessary to send one additional command to close the remote shell that was previously opened.  The only way I can think of to reuse WinRM connections would be to share the remote shell_id (GUID) for a given host across tasks.

Since closing the connection per task was removed via 23a22397bfdbcf9d8a4b9037fc5fb63ae8dcefc1, I can't find code that ever calls `connection.close()`.  With the paramiko connection, it leaves `max(# tasks, #forks)` open until the end of the playbook run when all the workers are stopped.

**Comment by bcoca** [comment] 2015-09-09 18:37
so i reverted the removal of connection closing, we'll revisit this in the future but it requires a broader way of handling connections. I also disabled closing ssh connections for the time being to avoid canceling the benefits of control master/persist.

fixed by 0dbebfddaa6a82538ea16e64c4f3ebc8d2083e07

**Closed as completed by bcoca** 2015-09-09 18:37 UTC
Labels: P2, windows, bug

**Comment by trondhindenes** [comment] 2015-09-09 18:39
thanks!

**Comment by jhawkesworth** [comment] 2015-09-09 20:01
Adding my thanks too - I have playbooks running daily which would be hit by this.

**Comment by ctgaff** [comment] 2015-11-22 09:13
This is still severely broken and about to land in Ansible 2.0.  Any task with multiple items will cause all connections to stay open except for the last one.   This not only causes all future connections to be rejected when MaxShellsPerUser is hit, but there will be 2 processes that never exit for each connection on the Windows host that consume memory.  A quick fix is to close each connection inside _execute for winrm connection types.

Reference: https://github.com/ansible/ansible/issues/9980

I made changes I am testing right now that utilize a SyncManager to reuse each hosts GUID that seems to be working quite well.

**Comment by cchurch** [comment] 2015-11-23 15:09
@ctgaff This specific issue was fixed where connections weren't getting closed between tasks.  #9980 and #12910 seem to indicate a more specific case where connections aren't closed when using winrm + with_items.
