### ISSUE TITLE
"ansible-galaxy collection list" should include collections installed by the ansible package

### ISSUE THREAD

**Issue by dmsimard** [ansible/ansible#72913] opened 2020-12-09 03:33 UTC
##### SUMMARY

Many collections are included in the Ansible package and it would be nice if the ``ansible-galaxy collection list`` command included the location where they are installed so they are accurately reported.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

ansible-galaxy collection list

##### ADDITIONAL INFORMATION

I managed to list the installed collections by setting [ANSIBLE_COLLECTIONS_PATH](https://docs.ansible.com/ansible/latest/reference_appendices/config.html#collections-paths) to the location where they're installed by the package and it works:
```
> export ANSIBLE_COLLECTIONS_PATH=~/dev/virtualenvs/ansible/lib/python3.9/site-packages/ansible_collections/
> ansible-galaxy collection list

# /home/dmsimard/dev/virtualenvs/ansible/lib/python3.9/site-packages/ansible_collections
Collection                Version
------------------------- -------
amazon.aws                1.2.1  
ansible.netcommon         1.4.1  
ansible.posix             1.1.1  
ansible.windows           1.2.0  
arista.eos                1.2.0  
awx.awx                   14.1.0 
azure.azcollection        1.2.0  
check_point.mgmt          1.0.6  
chocolatey.chocolatey     1.0.2  
cisco.aci                 1.1.1  
cisco.asa                 1.0.4  
cisco.intersight          1.0.8  
cisco.ios                 1.2.1  
cisco.iosxr               1.2.0  
cisco.meraki              2.1.2  
cisco.mso                 1.0.1  
cisco.nxos                1.3.1  
cisco.ucs                 1.6.0  
cloudscale_ch.cloud       1.3.0  
community.aws             1.2.1  
community.azure           1.0.0  
community.crypto          1.3.0  
community.digitalocean    1.0.0  
community.docker          1.0.0  
community.general         1.3.0  
# ...
```

But otherwise the command returns only the one collection I have installed in the default path:
```
> ansible-galaxy collection list

# /home/dmsimard/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
recordsansible.ara 0.0.4  
```

If we set ``ANSIBLE_COLLECTIONS_PATH`` to multiple paths like ``/home/dmsimard/dev/virtualenvs/ansible/lib/python3.9/site-packages/ansible_collections:/home/dmsimard/.ansible/collections/ansible_collections``, it already works and lists collections from both locations.

Is it possible to find out the path where the package installs the collections dynamically and add it to the default list of paths ?

**Comment by dmsimard** [comment] 2020-12-09 03:35
I'm not familiar with the galaxy CLI code yet but experimented a bit around these bits:
https://github.com/ansible/ansible/blob/e5ccd18be4d8cec6445f96c2868e0820de0afed8/lib/ansible/cli/galaxy.py#L268-L278
https://github.com/ansible/ansible/blob/e5ccd18be4d8cec6445f96c2868e0820de0afed8/lib/ansible/cli/galaxy.py#L1284-L1296

I think it's doable but haven't figured out the right way to do it yet :)

**Comment by felixfontein** [comment] 2020-12-09 06:40
Duplicate of #70147 :)

**Comment by mkrizek** [comment] 2020-12-09 07:48
Closing per above.

**Closed as completed by mkrizek** 2020-12-09 07:48 UTC
Labels: python3, support:core, feature, affects_2.11

**Comment by dmsimard** [comment] 2020-12-09 13:39
@felixfontein ah, thanks, I searched and couldn't find it !
