### ISSUE TITLE
ansible_sudo_pass override from inventory affects all subsequent hosts in a run

### ISSUE THREAD

**Issue by spacerodent** [ansible/ansible#9823] opened 2014-12-15 22:32 UTC
##### Summary:

It appears that inventory variables are not limited to the host they are for
##### Steps To Reproduce:

Create a inventory file with three hosts listed.  The second one should specify the sudo password using ansible_sudo_pass.

[host one]
127.0.0.1
[host two]
127.0.0.1 ansible_sudo_pass=some_password
[host three]
127.0.0.1

Run the ping command using one fork

ansible -m ping -K -f 1

Assume host one and host two using a sudo password other than "some_password"
##### Expected Results:

The ansible_sudo_pass option is only applied to the host it is listed for
##### Actual Results:

Using my example inventory host three fails with a failed sudo password error

Original issue text:

In my hosts file I have a couple of hosts that specify the sudo password using the "ansible_sudo_pass" option.  Example:

[alpha]
192.168.10.1
[localhost]
127.0.0.1 ansible_sudo_pass=vagrant
[beta]
192.178.10.2

I found when doing a command on all (Example: ansible all -m ping -K) that some of my hosts would fail due to invalid sudo password.  It appeared to be semi-random until I set the forks value to 1.  Now every host that comes after localhost complains about an invalid sudo password.  

It appears to me that the ansible_sudo_pass value is being used for hosts other than the ones I specified it for.

I am running on OSX 10.10.1.  I am using the system python interpreter which is (2.7.6) and am using Ansible (1.8.2) installed via Brew (0.9.5).

**Comment by mscherer** [comment] 2014-12-17 09:43
I think that by design, variable are not reset to 0 after a play, in order to be able to reuse them. For example, that's how you can use facts from 1 server on the others. I would be tempted to say "this is working on purpose" but i indeed see how this is a problem in the case you gave. I wonder if that's the same with ansible_ssh_port and others variables, maybe that's a bug.

**Comment by redbaron** [comment] 2014-12-18 14:31
that is by design. Variables are kept per host name. if you don't want them to mixup, use different hostname pointing to the same IP address

**Comment by spacerodent** [comment] 2014-12-18 16:37
I don't think I did a good enough job of setting up the error condition so let me use a better example.

inventory file:
[alpha]
alpha.example.com
[beta]
beta.example.com
[vagrant]
localhost ansible_sudo_pass=vagrant
[gamma]
gamma.example.com
[delta]
delta.example.com

now if you do  "ansible -K -o -m ping all" you will see something like

beta.example.com | success >> { "changed": false, "ping": "pong" }
delta.example.com | success >> { "changed": false, "ping": "pong" }
localhost | success >> { "changed": false, "ping": "pong" }
gamma.example.com | FAILED => Incorrect sudo password
alpha.example.com | FAILED => Incorrect sudo password

alpha, beta, delta, gamma all have the same sudo password and locahost has one provided in the inventory file.

It appears in my example above that the provided sudo password for localhost was used for the gamma and alpha hosts and I don't think that is by design.

**Comment by bcoca** [comment] 2014-12-18 16:49
@spacerodent agreed, I understood the issue, that is why I changed the title as I think others were getting confused about it.

**Comment by basictheprogram** [comment] 2015-01-21 20:27
I believe I hit this same bug as discussed at http://bit.ly/183SzAh

**Comment by abadger** [comment] 2016-03-20 17:32
This seems to be fixed in devel (In my extremely limited testing, in 2.0.1.0 as well) but there's a new bug.  The command line flag always overrides the setting of ansible_sudo_pass in the inventory (it does not override the setting of ansible_become_pass in inventory so that's a valid workaround).

I've got a potential fix for that behaviour.  I'll push it as a PR momentarily.

**Comment by abadger** [comment] 2016-03-20 17:45
Closing this bug as the behaviour here has been fixed in current 2.x.  Please watch PR #15055 if the new buggy behaviour I discovered is also an issue for you.

**Closed as completed by abadger** 2016-03-20 17:45 UTC
Labels: P2, bug
