### ISSUE TITLE
cannot unmarshal array into Go value

### ISSUE THREAD

**Issue by danielhauagge** [ansible/ansible#15504] opened 2016-04-20 14:43 UTC
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0
  config file = 
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Ubuntu 14.04
Docker version 1.10.3, build 20f81dd (also tried version 1.11.0 with same error)
Docker-Py version 1.8.0
##### SUMMARY

I get the error "cannot unmarshal array into Go value" when I try to launch a docker container with volumes attached to it. The error only occurs when I specify a mounting point.
##### STEPS TO REPRODUCE

Just run `ansible-playbook test2.yml`

```

---
- hosts: dl2
  tasks:
  - name: Launch ubuntu
    docker:
      state: started
      image: ubuntu
      command: sleep 1d
      volumes:
        - "/tmp:/inbox"
```
###### short version of output

```
PLAY [dl2] *********************************************************************

TASK [setup] *******************************************************************
ok: [dl2]

TASK [Launch ubuntu] ***********************************************************
fatal: [dl2]: FAILED! => {"changed": false, "failed": true, "msg": "Docker API Error: json: cannot unmarshal array into Go value of type string"}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @test2.retry

PLAY RECAP *********************************************************************
dl2                        : ok=1    changed=0    unreachable=0    failed=1   

```
###### verbose version of output

```
No config file found; using defaults
Loaded callback default of type stdout, v2.0

PLAYBOOK: test2.yml ************************************************************
1 plays in test2.yml

PLAY [dl2] *********************************************************************

TASK [setup] *******************************************************************
<dl2> ESTABLISH LOCAL CONNECTION FOR USER: daniel
<dl2> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1461163032.16-7353653514461 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1461163032.16-7353653514461 `" )'
<dl2> PUT /tmp/tmpg0NEE7 TO /home/daniel/.ansible/tmp/ansible-tmp-1461163032.16-7353653514461/setup
<dl2> EXEC /bin/sh -c 'LANG=en_US LC_ALL=en_US LC_MESSAGES=en_US /usr/bin/python /home/daniel/.ansible/tmp/ansible-tmp-1461163032.16-7353653514461/setup; rm -rf "/home/daniel/.ansible/tmp/ansible-tmp-1461163032.16-7353653514461/" > /dev/null 2>&1'
ok: [dl2]

TASK [Launch ubuntu] ***********************************************************
task path: .../test2.yml:4
<dl2> ESTABLISH LOCAL CONNECTION FOR USER: daniel
<dl2> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1461163032.75-245772432711048 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1461163032.75-245772432711048 `" )'
<dl2> PUT /tmp/tmpX_tBFI TO /home/daniel/.ansible/tmp/ansible-tmp-1461163032.75-245772432711048/docker
<dl2> EXEC /bin/sh -c 'LANG=en_US LC_ALL=en_US LC_MESSAGES=en_US /usr/bin/python /home/daniel/.ansible/tmp/ansible-tmp-1461163032.75-245772432711048/docker; rm -rf "/home/daniel/.ansible/tmp/ansible-tmp-1461163032.75-245772432711048/" > /dev/null 2>&1'
fatal: [dl2]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"cap_add": null, "cap_drop": null, "command": "sleep 1d", "count": 1, "cpu_set": null, "cpu_shares": 0, "debug": false, "detach": true, "devices": null, "dns": null, "docker_api_version": "1.22", "docker_url": null, "docker_user": null, "domainname": null, "email": null, "entrypoint": null, "env": null, "env_file": null, "expose": null, "extra_hosts": null, "hostname": null, "image": "ubuntu", "insecure_registry": false, "labels": {}, "links": null, "log_driver": null, "log_opt": null, "lxc_conf": null, "memory_limit": "0", "memory_swap": "0", "name": null, "net": null, "password": null, "pid": null, "ports": null, "privileged": false, "publish_all_ports": false, "pull": "missing", "read_only": null, "registry": null, "restart_policy": null, "restart_policy_retry": 0, "signal": null, "state": "started", "stdin_open": false, "stop_timeout": 10, "timeout": 60, "tls_ca_cert": null, "tls_client_cert": null, "tls_client_key": null, "tls_hostname": null, "tty": false, "ulimits": null, "use_tls": null, "username": null, "volumes": ["/tmp:/inbox"], "volumes_from": null}, "module_name": "docker"}, "msg": "Docker API Error: json: cannot unmarshal array into Go value of type string"}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @test2.retry

PLAY RECAP *********************************************************************
dl2                        : ok=1    changed=0    unreachable=0    failed=1   
```

**Comment by sivel** [comment] 2016-04-20 14:52
Duplicate of https://github.com/ansible/ansible-modules-core/pull/3496

**Closed as completed by sivel** 2016-04-20 14:52 UTC
