### ISSUE TITLE
with_subelements: Allow subelement property to be nested

### ISSUE THREAD

**Issue by alanvdam** [ansible/ansible#9863] opened 2014-12-19 13:30 UTC
```
"rax": {
  "instances": [{
    "id": 0,
    "rax_addresses": {
       "public" : [ { "addr": "10.2.2.2" }, { "addr": "10.0.0.1" } ]
     }
  }]
}

- action: some attr=item.0.id ip=item.1.addr
  with_subelements:
    - rax.instances
    - rax_addresses.public 
```
##### Issue Type:

Bug Report
##### Ansible Version:

1.8.2
##### Environment:

Mac OS X 10.10.1
##### Summary:

`with_subelements` should be able to loop over nested property.
The rax_addresses.public or tax_addresses['public'] does not work with the with_subelements. Only the first argument seems to support nested property names.
##### Steps To Reproduce:

See code above
##### Expected Results:

Be able to loop over the addr properties
##### Actual Results:

Fails with can not find `tax_addresses.public`

**Comment by mhoglan** [comment] 2015-03-23 21:35
I ran into the same need when trying to define a list of users and wanted to include their MySQL configuration in the same dict.  Wanted to have one user dict that contained all the different applications configs for the user.   

example type of structure

``` yaml
---
users:
  - user: bob
    password: system-password
    mysql:
      password: mysql-password
      hosts:
        - "%"
        - "{{ ansible_hostname }}"
        - "127.0.0.1"
        - "::1"
        - "localhost"
      privs:
        - "*.*:SELECT"
        - "DB1.*:ALL"
```

wanted to be able to do something along the lines of

```
- name: Setup MySQL users
  mysql_user: name={{ item.0.user }} password={{ item.0.mysql.password }} host={{ item.1 }} priv={{ item.0.mysql.privs | join('/') }}
  with_subelements:
    - users
    - mysql.hosts
```

I worked around this, and I am sure there are a dozen ways to achieve similar behavior.   The ability to specify the second element to be a nested element or pass in jinja to perform it would be nice.

**Comment by srgvg** [comment] 2015-04-29 20:58
@alanvdam @mhoglan could you test the updated plugin as per PR #10880 for your use cases?

**Comment by landryb** [comment] 2015-08-25 12:44
Stumbled upon the same issue when trying to access a sub-property of a resultset..

```
- name: list already loaded extensions
  sudo: yes
  sudo_user: postgres
  command: psql -d {{ item.name }} -t -c "\dx"
  register: loaded_extensions
  with_items: postgresql_dbs

- name: debug
  debug: var={{ item[0] }}
  when: "item[0].stdout is defined and 'item[1]' not in item[0].stdout"
  with_subelements:
  - loaded_extensions.results
  - item.extensions
```

where postgresql_dbs is an array of hashes, one of the properties (extensions) being an array.

Previously, using ansible from 4ff841c2a283f6b1fc3aaf98f489095fd0274f40 (yeah i know, old), it failed with:

```
fatal: [db.tiger] => could not find 'item['extensions']' key in iterated item '{u'changed': True, u'stdout': u' plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language', u'warnings': [], u'delta': u'0:00:00.084085', 'stdout_lines': [u' plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language'], u'end': u'2015-08-25 13:44:39.322583', u'start': u'2015-08-25 13:44:39.238498', u'cmd': [u'psql', u'-d', u'qadastre', u'-t', u'-c', u'\\dx'], 'item': {'owner': 'qadastre', 'extensions': ['postgis'], 'name': 'qadastre', 'encoding': 'UTF8'}, u'stderr': u'', u'rc': 0, 'invocation': {'module_name': u'command', 'module_args': u'psql -d qadastre -t -c "\\dx"'}}'

```

pull'ing my local copy of ansible to current HEAD, i can confirm that this usecase using nested subelements from a result registered from a previous task seems fixed by #10995, but of course now most of my playbooks dont run anymore and need to be updated for v2 :)

Looks to me that current devel branch is a minefield.....

**Comment by landryb** [comment] 2015-08-25 12:57
But the ticket itself should be closed afaict.

**Comment by srgvg** [comment] 2015-08-25 13:09
@landryb not sure what you mean, allowing to target subelements is a new feature, available in current devel/v2; that was never possible before.

**Comment by landryb** [comment] 2015-08-25 14:35
Yes i know - you mean you only close tickets when a release has been made with the corresponding code ?

**Comment by bcoca** [comment] 2015-08-25 14:47
no, we close tickets once the issue is fixed in devel, so ... closing

**Comment by srgvg** [comment] 2015-08-25 14:47
I was referring to you saying you needed to update your playbooks.

**Closed as completed by bcoca** 2015-08-25 14:47 UTC
Labels: feature
