### ISSUE TITLE
powershell.ps1: Implement dict parameter type

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#25358] opened 2017-06-05 13:32 UTC
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

module_utils/powershell.ps1

##### ANSIBLE VERSION

v2.4

##### SUMMARY

The **win_nssm** module implements a parameter using a "dict" type as value. This is currently unimplemented (and taken care of by the win_nssm module itself). We should move this support to powershell.ps1, and support both the YAML syntax, as well as the legacy "key=value" string syntax.

(For the win_nssm module, there's also a `dependencies` parameter that currently expects a comma-separated string, which should become of type "list" too.)

And the win_nssm module does not have integration tests, nor does it have check-mode support.

This relates to #25358

**Comment by sivel** [comment] 2017-06-05 13:46
This sounds to be a duplicate of https://github.com/ansible/ansible/pull/25356

**Comment by trondhindenes** [comment] 2017-06-05 14:26
yup, they discuss the same thing. Just for clarity: mine is a pr. Very open to suggestions on how we solve these.

**Comment by dagwieers** [comment] 2017-06-05 18:50
This relates to #25358

**Closed as completed** 2017-06-06 08:26 UTC
Labels: windows, c:module_utils/, affects_2.4, feature
