### ISSUE TITLE
Feature request: portage - support for update yes/no

### ISSUE THREAD

**Issue by janreges** [ansible/ansible#18982] opened 2016-12-08 11:51 UTC
Hi,

i'm from Gentoo community and "portage" has one inconvenience/restriction.

Attribute "update" is not possible to set to "no" value. It have to be "yes", or undefined (so implicit "no")

I need to implement feature, that all our roles and "portage" tasks has been called with update=yes, or update=no (controlled by common variable, for example ```portage: ... update="{{ portage_update }}"```

So, request to update any package will be controlled by my common "portage_update" variable.

On daily basis, package updating is undesirable. But weekly/monthly i need to execute all roles with ```portage_update: true```.

Could you accept also "update=no" in "portage"?

Thank you.

**Comment by bcoca** [comment] 2016-12-16 21:12
If i understand your request correctly, you want 'no' to be a valid value for `update`.

It already is as `update` is defined as a boolean, so yes/no/true/false are all valid. you can also always use the `omit` key.

**Comment by Lujeni** [comment] 2016-12-27 23:24
Hello @janreges @bcoca 

I use Gentoo with ansible but i cant reproduce your case.
It's seems that the `update` field can be set with `no` value (the portage option `--update` is added when update value is True [here](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/os/portage.py#L328)).

ansible version: 2.2.0.0

```yaml
- name: test portage update
  hosts: all
  become: true
  tasks:
   - name: test portage update
     portage:
       name: vim
       update: no
```

```bash
# result with `no` in debug mode (print the arguments)
✔ ~/works/repos/perso/ansible/issue_18982 
00:06 $ ansible-playbook -i localhost, test.yml -c local -v
No config file found; using defaults

PLAY [test portage update *************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [test portage update] *****************************************************
changed: [localhost] => {"changed": true, "msg": []}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0
```

```bash
# result with `yes`
✔ ~/works/repos/perso/ansible/issue_18982 
00:06 $ ansible-playbook -i localhost, test.yml -c local -v
No config file found; using defaults

PLAY [test portage update *************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [test portage update] *****************************************************
changed: [localhost] => {"changed": true, "msg": ["--update"]}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0
```

**Comment by bcoca** [comment] 2017-01-05 21:55
closing as this already is the case.

**Closed as completed** 2017-01-05 21:55 UTC
Labels: affects_2.3

**Comment by janreges** [comment] 2017-01-17 21:45
Thank you @bcoca.

In latest Ansible version, it is possible to set ```update="no"``` :-)
