### ISSUE TITLE
delegate_to reuses SSH port (and ansible_python_interpreter) from host

### ISSUE THREAD

**Issue by SleeplessAnnoyedNerd** [ansible/ansible#1225] opened 2012-10-04 15:49 UTC
ansible 0.8 (devel 761330b125) last updated 2012/10/04 10:13:36 (GMT +200)

Hello,

I have a host in the inventory which uses a non-standard SSH port (in my case: 2222).
If I use delegate_to to delegate to another host, ansible connects to the host (vz112.local) with the port from the host (10.20.20.208) which is processed by the playbook (port 2222 in my case). Of course this fails.

It seems I'm not able to override the port via "delegate_to: otherhost:22".

Is this a bug, feature or do I something wrong?
(Well, workaround is to use redir on the delegate_to host for now.)

Thanks,
Dietmar

---

[xxx]
10.20.20.208:2222

---
- name: Create base Nagios host configuration
  action: template src=files/etc/nagios/hosts/host.cfg.j2 dest=/etc/nagios/hosts/${ansible_hostname}.cfg
  delegate_to: vz112.local

---

TASK: [Create base Nagios host configuration] ********************\* 
fatal: [10.20.20.208] => failed to transfer file to /source:

Connecting to vz112.local...
ssh: connect to host vz112.local port 2222: Connection refused
Couldn't read packet: Connection reset by peer

FATAL: all hosts have already failed -- aborting

**Comment by SleeplessAnnoyedNerd** [comment] 2012-10-04 15:53
Hi,

forgot to mention: I use ssh transport.

Thanks,
Dietmar

**Comment by SleeplessAnnoyedNerd** [comment] 2012-10-04 16:28
Hi,

I think there may be a conflict with "Use localhost ansible_python_interpreter with local_action/delegate_to".
(Refering to this statement: "I think it's important to pass on ansible_python_interpreter to whichever host I'm delegating to; "localhost" and "127.0.0.1" as well." -- I think this should be controllable.)

Thanks,
Dietmar

**Comment by mpdehaan** [comment] 2012-10-04 23:23
thanks for the report. 

this is more or less a duplicate of #1019 and will be addressed at the same time

**Comment by mpdehaan** [comment] 2012-10-25 11:51
looks like we still need to do something about the ansible_*_interpreter vars

**Comment by mpdehaan** [comment] 2012-10-26 23:54
done!

**Closed as completed by mpdehaan** 2012-10-26 23:54 UTC
