### ISSUE TITLE
How deep is "defined"

### ISSUE THREAD

**Issue by xalkina** [ansible/ansible#27200] opened 2017-07-23 04:59 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
Conditionals

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### OS / ENVIRONMENT

Have discovered this with Ubuntu 17.04 managing Centos 7.3.
Reproduced for this report with Ubuntu 17.04 targeting itself.

##### SUMMARY
is defined works as expected when the variable it is used against is not defined.
However, when the variable exists, but depends on an undefined variable, it fails, instead of returning false.

##### STEPS TO REPRODUCE
Will upload a minimal test case role.

Run:
ansible-playbook -i inventory playbook.yml

```yaml

```

##### EXPECTED RESULTS
The role def has 2 conditional steps. Since the variables are (directly or indirectly) not defined, they should both be skipped.

##### ACTUAL RESULTS

The 2nd task makes the playbook fail.

```
TASK [def : Problematic step.] **********************************************************************************************************************************************************************
fatal: [thismachine]: FAILED! => {"failed": true, "msg": "The conditional check 'dependent is defined' failed. The error was: error while evaluating conditional (dependent is defined): I use {{ variable }}.: 'variable' is undefined\n\nThe error appears to have been in '/home/xalkina/tmp/defined/roles/def/tasks/main.yml': line 9, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Problematic step.\n  ^ here\n"}
        to retry, use: --limit @/home/xalkina/tmp/defined/playbook.retry
```

**Comment by xalkina** [comment] 2017-07-23 05:00
The test-case files.

**Comment by alikins** [comment] 2017-07-24 16:11
> The test-case files.

@xalkina Doesn't look like any test cases were attached or referenced?

**Comment by xalkina** [comment] 2017-07-24 19:05
Suppose it made it this time...


[defined.zip](https://github.com/ansible/ansible/files/1170907/defined.zip)

**Comment by sivel** [comment] 2018-06-21 21:55
Duplicate of https://github.com/ansible/ansible/issues/23675

**Closed as completed by sivel** 2018-06-21 21:55 UTC
Labels: affects_2.3, test, support:community, bug
