### ISSUE TITLE
Results of macros are converted to Python data structures if possible in ansible-core 2.13

### ISSUE THREAD

**Issue by felixfontein** [ansible/ansible#78141] opened 2022-06-24 11:53 UTC
### Summary

While templating a JSON file where the JSON was created as part of a template (without using `to_json`) and where a macro was used to template some repeated parts, we found out that the generated JSON file was invalid JSON after switching from ansible-core 2.12 to ansible-core 2.13.

The problem seems to be that if the output of a macro looks like something that could be a Pyhon `repr()` result, it is converted back to Python datastructures.

### Issue Type

Bug Report

### Component Name

templar

### Ansible Version

```console
2.13.0
devel branch
```

### Configuration

```console
default
```

### OS / Environment

Linux

### Steps to Reproduce

```.bash
ansible localhost -m debug -a "msg='{% macro foo() %}{ "'"'"foo"'"'": "'"'"bar"'"'" }{% endmacro %}Test: {{ foo() }}'"
```
Or as a task:
```.yaml
- hosts: localhost
  tasks:
  - debug:
      msg: >-
        {% macro foo() %}{ "foo": "bar" }{% endmacro %}Test: {{ foo() }}
```

### Expected Results

```
"Test: {\"foo\": \"bar\"}"
```

### Actual Results

```console
"Test: {'foo': 'bar'}"
```
(This has `'` instead of `"`, so this isn't valid JSON.)
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by felixfontein** [comment] 2022-06-24 11:55
Similar to https://github.com/ansible/ansible/issues/77272#issuecomment-1066498206 this appears to be a bug in Jinja2:
```
>>> from jinja2.nativetypes import NativeEnvironment
>>> NativeEnvironment().from_string('{% macro foo() %}{ "foo": "bar" }{% endmacro %}Test: {{ foo() }}').render()
"Test: {'foo': 'bar'}"
```

**Comment by felixfontein** [comment] 2022-06-24 11:56
(I'm using Jinja2 3.1.2)

**Comment by mkrizek** [comment] 2022-06-24 12:39
From a quick glance it sounds like we would need to set the concat function on the environment class for macros to one that does not do `literal_eval` to keep backwards compat. I am not sure how to differentiate between macros and the rest of the template structures yet.

**Comment by felixfontein** [comment] 2022-06-24 18:16
Interestingly it's not only a Jinja2 problem; for example if the generated JSON contains `true` (lower-case), Jinja2 does not convert it, while ansible-core does:
```
>>> from jinja2.nativetypes import NativeEnvironment
>>> NativeEnvironment().from_string('{% macro foo() %}{ "foo": true }{% endmacro %}Test: {{ foo() }}').render()
'Test: { "foo": true }'
```
vs.
```
$ ansible localhost -m debug -a "msg='{% macro foo() %}{"'"'"foo"'"'": true}{% endmacro %}Test: {{ foo() }}'"
localhost | SUCCESS => {
    "msg": "Test: {'foo': True}"
}
```

**Comment by mkrizek** [comment] 2022-06-27 07:43
So to explain this behavior a bit more:

1. This is not related to upstream Jinja2. Your example with `NativeEnvironment` yields expected output, the result of macro is a `dict` literal and `NativeEnvironment` (`ast.literal`) converts it to such.
2. This is not something that is really new to 2.13. `safe_eval` prior to 2.13 did the same thing but in a different stage of templating which results in this particular example to have different outputs on 2.12 (and prior) and 2.13 but consider different example:
```yaml
- hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg: >-
          {% macro foo() %}{ "foo": "bar" }{% endmacro %}{{ foo() }}
```

The above would result on 2.12 and 2.13 the same, the result is converted to a Python data structure:
```
TASK [debug] *************************************************************************************************************************************************
ok: [localhost] => {
    "msg": {
        "foo": "bar"
    }
}
```

The reason your example `{% macro foo() %}{ "foo": "bar" }{% endmacro %}Test: {{ foo() }}` is processed differently is because `safe_eval` did the evaluation at the final result of templating while `jinja2_native` is able to process the immediate result of the macro. `safe_eval` then evaluates `Test: { "foo": "bar" }` which is arbitrary string as opposed to something that can be evaluated to a Python type.

3. Regarding booleans this is indeed specific to Ansible. The origin of the functionality appears to be in https://github.com/ansible/ansible/pull/14293 (or [see the current code base](https://github.com/ansible/ansible/blob/4594c0c6094fcf801caeef27a5170d39d2207b08/lib/ansible/template/native_helpers.py#L23)).

4. Ultimately I am not sure we should change anything about this. Not converting the result of macros would break the following playbook:
```yaml
- hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        var: item
      loop: "{% macro foo() %}['foo', 'bar']{% endmacro %}{{ foo() }}"
```

**Comment by bcoca** [comment] 2022-06-28 15:07
closing as per above

**Comment by user318** [comment] 2022-06-29 15:06
> Ultimately I am not sure we should change anything about this. Not converting the result of macros would break the following playbook

@mkrizek The question is how one can return the json string from macro without it being interpreted as an object. I have such macros that is now broken when run under ansible-core 2.13 and jinja2-3.1 (it works if it is either ansible-core 2.12 or jinja2-3.0).
Here is the example:
test-json.j2:
```
{% macro t(x) %}
{{ x|to_json }}
{% endmacro %}
{{ t([])|from_json }}
```
With 2.12 or jinja 3.0 I'm getting ```[]``` in output. With 2.13 & jinja 3.1 I'm getting an error now:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ): the JSON object must be str, bytes or bytearray, not list
fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleError: Unexpected templating type error occurred on ({% macro t(x) %}\n{{ x|to_json }}\n{% endmacro %}\n{{ t([])|from_json }}\n): the JSON object must be str, bytes or bytearray, not list"}
```

**Comment by mkrizek** [comment] 2022-06-30 07:42
Would explicitly casting to a string like so `{{ t([])|string|from_json }}` help?

**Comment by user318** [comment] 2022-06-30 07:52
> Would explicitly casting to a string like so `{{ t([])|string|from_json }}` help?

I also thought about that. But it works only for simple cases like ```[]```, and even for ```["x"]``` it will break already.

**Comment by mkrizek** [comment] 2022-06-30 08:31
So I think there is a different issue here.

Converting to Python types is expected when macros are used inline in playbooks as in the original reproducer. However that should not be the case in the `template` module. Additionally you can opt out from the conversion by specifying `convert_data=False` in the `template` lookup:
```
"{{ lookup('template', '78141.j2', convert_data=False) }}"
```

This should be the fix (against `devel`):
```diff
diff --git a/lib/ansible/template/__init__.py b/lib/ansible/template/__init__.py
index 31cc1fa4ec2..175aa835692 100644
--- a/lib/ansible/template/__init__.py
+++ b/lib/ansible/template/__init__.py
@@ -1098,15 +1098,15 @@ class Templar:
             # save/restore cur_context to prevent overriding __UNSAFE__.
             cached_context = self.cur_context

+            original_concat = self.environment.concat
+            if not self.jinja2_native and not convert_data:
+                self.environment.concat = ansible_concat
+
             self.cur_context = t.new_context(jvars, shared=True)
             rf = t.root_render_func(self.cur_context)

             try:
-                if not self.jinja2_native and not convert_data:
-                    res = ansible_concat(rf)
-                else:
-                    res = self.environment.concat(rf)
-
+                res = self.environment.concat(rf)
                 unsafe = getattr(self.cur_context, 'unsafe', False)
                 if unsafe:
                     res = wrap_var(res)
@@ -1120,6 +1120,7 @@ class Templar:
                     raise AnsibleError("Unexpected templating type error occurred on (%s): %s" % (to_native(data), to_native(te)))
             finally:
                 self.cur_context = cached_context
+                self.environment.concat = original_concat

             if isinstance(res, string_types) and preserve_trailing_newlines:
                 # The low level calls above do not preserve the newline
```

I am going to play with it a bit more and turn it into a PR. @user318 would you be able to test the above diff to see if it fixes your issue when templating your macro via the `template` module or `template` lookup (with `convert_data=False`)?

**Comment by user318** [comment] 2022-06-30 09:06
> I am going to play with it a bit more and turn it into a PR. @user318 would you be able to test the above diff to see if it fixes your issue when templating your macro via the template module or template lookup (with convert_data=False)?

You mean put the macro in a separate template and call it via lookup? I'll try, but it is a quite diffetent use case. In my case, I use a template with several macros like a library of "functions". And macros in that template may use each other. So splitting each of them to separate templates looks not that convenient.
I raised the question also because those json-returning macros worked without a clue before, but you are saying that inline macro calls are expected to be converted to Python types and that contradicts my previous experience. So I'm lost now of how to do it right and also in a manner that it works the same on different ansible versions. :)

**Comment by user318** [comment] 2022-06-30 09:25
Sorry, I probably misunderstood you. You mean they should be converted to the Python types when they called inline in playbooks and in templates they shouldn't. I tried your patch and it fixes both the simple examples I showed above and my production ansible templates. So probably that was the cause of it. Thanks.

**Comment by bcoca** [comment] 2022-06-30 13:19
`|string` might be the workaround in this case

**Comment by ahuffman** [comment] 2022-07-14 13:58
I'm having this issue as well when building up a json string, and there was not a problem until core 2.13.1.

I build the json string up with this ugly line:

```
ansible.builtin.set_fact:
    __k4k8s_deploy_admin_gui_session_conf_string__: "{\"cookie_name\": \"{{ k4k8s_deploy_admin_gui_sessions_settings['cookie_name'] | string }}\", \"secret\": \"{{ k4k8s_deploy_admin_gui_sessions_settings['secret'] | string }}\"{% if 'cookie_lifetime' in k4k8s_deploy_admin_gui_sessions_settings %}, \"cookie_lifetime\": {{ k4k8s_deploy_admin_gui_sessions_settings['cookie_lifetime'] | int }}{% endif %}{% if 'cookie_renew' in k4k8s_deploy_admin_gui_sessions_settings %}, \"cookie_renew\": {{ k4k8s_deploy_admin_gui_sessions_settings['cookie_renew'] | int }}{% endif %}{% if 'cookie_samesite' in k4k8s_deploy_admin_gui_sessions_settings %}, \"cookie_samesite\": \"{{ k4k8s_deploy_admin_gui_sessions_settings['cookie_samesite'] | string }}\"{% endif %}{% if 'cookie_secure' in k4k8s_deploy_admin_gui_sessions_settings %}, \"cookie_secure\": {% if k4k8s_deploy_admin_gui_sessions_settings['cookie_secure'] | bool %}true{% else %}false{% endif %}{% endif %}{% if 'storage' in k4k8s_deploy_admin_gui_sessions_settings %}, \"storage\": \"{{ k4k8s_deploy_admin_gui_sessions_settings['storage'] | string }}\"{% endif %}{% if 'cookie_domain' in k4k8s_deploy_admin_gui_sessions_settings %}, \"cookie_domain\": \"{{ k4k8s_deploy_admin_gui_sessions_settings['cookie_domain'] }}\"{% endif %}}"
```

Ansible thinks the json is a dictionary, so using the string filter should in theory convert it.

I have to do this to get it work properly now in my template:
`{{ __k4k8s_deploy_admin_gui_session_conf_string__ | string | to_json | from_json | regex_replace('True', 'true') | regex_replace('False', 'false') | regex_replace('\'', '"') | b64encode }}`

The odd thing is that if you do an ansible.builtin.debug of `__krk8s_deploy_admin_gui_session_conf_string__ | string | to_json | from_json` it looks fine on stdout.  However when the j2 template receives it, the var has single quotes and capitalized bools making it improper json.

Previously I was just using ` var | string | b64encode` in the template.

**Comment by mkrizek** [comment] 2022-07-14 14:04
@ahuffman would you be able to test https://github.com/ansible/ansible/pull/78259 and confirm it fixes your issue?

**Closed as completed** 2022-07-14 19:14 UTC
Labels: support:core, bug, has_pr, native_jinja, affects_2.13
