### ISSUE TITLE
ansible-doc -l errors

### ISSUE THREAD

**Issue by ghostwords** [ansible/ansible#11697] opened 2015-07-22 15:40 UTC
Ansible on Ubuntu 14.04 from ppa:ansible/ansible:

```
$ ansible --version
ansible 1.9.2
  configured module search path = None
```

Running `$ ansible-doc -l` produces the following (in addition to expected output):

```
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ansible/utils/module_docs.py", line 55, in get_docstring
    doc = yaml.safe_load(child.value.s)
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 93, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/lib/python2.7/dist-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 382, in parse_block_sequence_entry
    if self.check_token(BlockEntryToken):
  File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 220, in fetch_more_tokens
    return self.fetch_value()
  File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 576, in fetch_value
    self.get_mark())
ScannerError: mapping values are not allowed here
  in "<string>", line 36, column 64:
     ...  the first line of your template:
                                         ^
Traceback (most recent call last):
  File "/usr/bin/ansible-doc", line 201, in get_module_list_text
    desc = tty_ify(doc.get('short_description', '?')).strip()
AttributeError: 'NoneType' object has no attribute 'get'
ERROR: module win_template has a documentation error formatting or is missing documentation
less 458 (GNU regular expressions)
Copyright (C) 1984-2012 Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Homepage: http://www.greenwoodsoftware.com/less
```

**Comment by bcoca** [comment] 2015-07-22 15:41
i cannot reproduce with the stock ansible, are you using any custom modules?

**Comment by ghostwords** [comment] 2015-07-22 16:03
I don't think so ... I just added the PPA, that's all.

Here are my modules according to `ansible-doc -l | cut -d " " -f 1`:

```
a10_server
a10_service_group
a10_virtual_server
acl
add_host
airbrake_deployment
alternatives
apache2_module
apt
apt_key
apt_repository
apt_rpm
assemble
assert
at
authorized_key
azure
bigip_facts
bigip_monitor_http
bigip_monitor_tcp
bigip_node
bigip_pool
bigip_pool_member
bigpanda
boundary_meter
bower
bzr
campfire
capabilities
cloudformation
command
composer
copy
cpanm
cron
crypttab
datadog_event
debconf
debug
digital_ocean
digital_ocean_domain
digital_ocean_sshkey
django_manage
dnf
dnsimple
dnsmadeeasy
docker
docker_image
easy_install
ec2
ec2_ami
ec2_ami_search
ec2_asg
ec2_eip
ec2_elb
ec2_elb_lb
ec2_facts
ec2_group
ec2_key
ec2_lc
ec2_metric_alarm
ec2_scaling_policy
ec2_snapshot
ec2_tag
ec2_vol
ec2_vpc
ejabberd_user
elasticache
facter
fail
fetch
file
filesystem
fireball
firewalld
flowdock
gc_storage
gce
gce_img
gce_lb
gce_net
gce_pd
gem
get_url
getent
git
github_hooks
glance_image
gluster_volume
group
group_by
grove
haproxy
hg
hipchat
homebrew
homebrew_cask
homebrew_tap
hostname
htpasswd
include_vars
ini_file
irc
jabber
jboss
jira
kernel_blacklist
keystone_user
known_hosts
layman
librato_annotation
lineinfile
linode
lldp
locale_gen
logentries
lvg
lvol
lxc_container
macports
mail
modprobe
mongodb_user
monit
mount
mqtt
mysql_db
mysql_replication
mysql_user
mysql_variables
nagios
netscaler
newrelic_deployment
nexmo
nova_compute
nova_keypair
npm
ohai
open_iscsi
openbsd_pkg
openvswitch_bridge
openvswitch_port
opkg
osx_say
ovirt
pacman
pagerduty
patch
pause
ping
pingdom
pip
pkg5
pkg5_publisher
pkgin
pkgng
pkgutil
portage
portinstall
postgresql_db
postgresql_ext
postgresql_lang
postgresql_privs
postgresql_user
quantum_floating_ip
quantum_floating_ip_associate
quantum_network
quantum_router
quantum_router_gateway
quantum_router_interface
quantum_subnet
rabbitmq_parameter
rabbitmq_plugin
rabbitmq_policy
rabbitmq_user
rabbitmq_vhost
raw
rax
rax_cbs
rax_cbs_attachments
rax_cdb
rax_cdb_database
rax_cdb_user
rax_clb
rax_clb_nodes
rax_dns
rax_dns_record
rax_facts
rax_files
rax_files_objects
rax_identity
rax_keypair
rax_meta
rax_network
rax_queue
rax_scaling_group
rax_scaling_policy
rds
rds_param_group
rds_subnet_group
redhat_subscription
redis
replace
rhn_channel
rhn_register
riak
rollbar_deployment
route53
rpm_key
s3
script
seboolean
selinux
service
set_fact
setup
shell
slack
slurp
snmp_facts
sns
stackdriver
stat
subversion
supervisorctl
svc
svr4pkg
swdepot
synchronize
sysctl
template
twilio
typetalk
ufw
unarchive
uptimerobot
uri
urpmi
user
virt
vsphere_guest
wait_for
win_chocolatey
win_copy
win_feature
win_file
win_get_url
win_group
win_msi
win_ping
win_service
win_stat
win_updates
win_user
xattr
yum
zabbix_group
zabbix_maintenance
zfs
zypper
zypper_repository
```

**Comment by bcoca** [comment] 2015-07-22 16:23
so the error is on win_template, can you check you have a proper copy of win_template.py ?

**Comment by ghostwords** [comment] 2015-07-22 17:40
When you say, proper copy, what do you mean?

In `/usr/lib/pymodules/python2.7/ansible`:

```
$ find . -iname "*win_template*"
./modules/core/windows/win_template.py
./modules/core/windows/win_template.pyc
./runner/action_plugins/win_template.py
./runner/action_plugins/win_template.pyc

$  ls -lh ./modules/core/windows/win_template.py
lrwxrwxrwx 1 root root 64 Jun 26 09:14 ./modules/core/windows/win_template.py -> /usr/share/pyshared/ansible/modules/core/windows/win_template.py

$ ls -lh /usr/share/pyshared/ansible/modules/core/windows/win_template.py
-rw-r--r-- 1 root root 2.4K Jun 25 20:25 /usr/share/pyshared/ansible/modules/core/windows/win_template.py
```

Contents of `/usr/share/pyshared/ansible/modules/core/windows/win_template.py`:

``` python
# this is a virtual module that is entirely implemented server side

DOCUMENTATION = '''
---
module: win_template
version_added: "1.9.2"
short_description: Templates a file out to a remote server.
description:
     - Templates are processed by the Jinja2 templating language
       (U(http://jinja.pocoo.org/docs/)) - documentation on the template
       formatting can be found in the Template Designer Documentation
       (U(http://jinja.pocoo.org/docs/templates/)).
     - "Six additional variables can be used in templates: C(ansible_managed) 
       (configurable via the C(defaults) section of C(ansible.cfg)) contains a string
       which can be used to describe the template name, host, modification time of the
       template file and the owner uid, C(template_host) contains the node name of 
       the template's machine, C(template_uid) the owner, C(template_path) the
       absolute path of the template, C(template_fullpath) is the absolute path of the 
       template, and C(template_run_date) is the date that the template was rendered. Note that including
       a string that uses a date in the template will result in the template being marked 'changed'
       each time."
options:
  src:
    description:
      - Path of a Jinja2 formatted template on the local server. This can be a relative or absolute path.
    required: true
    default: null
    aliases: []
  dest:
    description:
      - Location to render the template to on the remote machine.
    required: true
    default: null
notes:
  - "templates are loaded with C(trim_blocks=True)."
  - By default, windows line endings are not created in the generated file.
  - In order to ensure windows line endings are in the generated file,
    add the following header as the first line of your template:
    "#jinja2: newline_sequence:'\r\n'"
    and ensure each line of the template ends with \r\n
  - Beware fetching files from windows machines when creating templates
    because certain tools, such as Powershell ISE,  and regedit's export facility
    add a Byte Order Mark as the first character of the file, which can cause tracebacks.  
  - Use "od -cx" to examine your templates for Byte Order Marks.
requirements: []
author: "Jon Hawkesworth (@jhawkesworth)"
'''

EXAMPLES = '''
# Playbook Example  (win_template can only be run inside a playbook)
- win_template: src=/mytemplates/file.conf.j2 dest=C:\\temp\\file.conf 


'''
```

**Comment by bcoca** [comment] 2015-07-22 18:45
so you seem to have extra set of modules, it looks like you have overlapping installations

**Comment by ghostwords** [comment] 2015-07-22 18:58
Sorry, could you explain a bit more? I suppose I'll try reinstalling later.

**Comment by alakra** [comment] 2015-07-27 19:42
:+1: I'm also running into this issue with 1.9.2 on OSX.

**Comment by bcoca** [comment] 2015-07-27 19:43
closing this as it is not really an ansible bug, but either a bad install or a bad custom module

**Closed as completed by bcoca** 2015-07-27 19:43 UTC

**Comment by alakra** [comment] 2015-07-28 16:35
@ghostwords  This was problem with the `win_template.py` core module in ansible not having parseable yaml.  It appears to be fixed at the `HEAD` of `ansible-modules-core`.

**Comment by vikas027** [comment] 2015-07-29 02:40
This issue still persists if someone uses EPEL repo. Use the below commands to fix it. Hope this helps.

``` bash
# rm /usr/lib/python2.6/site-packages/ansible/modules/core/windows/win_template.py  /usr/lib/python2.6/site-packages/ansible/runner/action_plugins/win_template.py

# wget https://raw.githubusercontent.com/ansible/ansible-modules-core/devel/windows/win_template.py -P /usr/lib/python2.6/site-packages/ansible/runner/action_plugins/

# wget https://raw.githubusercontent.com/ansible/ansible-modules-core/devel/windows/win_template.py -P /usr/lib/python2.6/site-packages/ansible/modules/core/windows/
```
