### ISSUE TITLE
Template command fails during automatic configuration on local node only 

### ISSUE THREAD

**Issue by ajaybhatnagar** [ansible/ansible#20572] opened 2017-01-23 19:10 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
template

##### ANSIBLE VERSION
2.2.1.0

##### CONFIGURATION
Default file  /etc/ansible/ansible.cfg with ansible

##### OS / ENVIRONMENT
Ubuntu 16.04 - 4.4.0-57-generic

##### SUMMARY
Template command works correctly if executed from controller node or executed on the node shell but fails when executed during boot process with all playbook on the node itself and executed on local node only.

##### STEPS TO REPRODUCE
single task playbook with a template file 

```
---
  - block:
    - name: Update Properties File
      template: src=templates/IntroscopeEPAgent.properties.j2  dest=/var/tmp/IntroscopeEPAgent.properties
    become: yes
    become_user: root
    become_method: sudo
```

##### EXPECTED RESULTS
Template file available on destination
##### ACTUAL RESULTS
verbose logs in both cases are given below:

`` Failed LOGS when executed in shell at boot time:

```

Jan 23 18:17:56 ans-esmaster01a rc.local[509]: + ansible-playbook -vvvv local.yml --extra-vars=env=thor -f 1
Jan 23 18:17:56 ans-esmaster01a rc.local[509]: Using /ansible/ansible.cfg as config file
Jan 23 18:17:56 ans-esmaster01a rc.local[509]:  [WARNING]: provided hosts list is empty, only localhost is available
Jan 23 18:17:56 ans-esmaster01a rc.local[509]: Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/dist-packages/ansible/plugins/callback/__init__.pyc
Jan 23 18:17:56 ans-esmaster01a rc.local[509]: PLAYBOOK: local.yml ************************************************************
Jan 23 18:17:56 ans-esmaster01a rc.local[509]: 1 plays in local.yml
Jan 23 18:17:56 ans-esmaster01a rc.local[509]: PLAY [Install  Wily setup for ELK] *********************************************
Jan 23 18:17:56 ans-esmaster01a rc.local[509]: TASK [setup] *******************************************************************
Jan 23 18:17:56 ans-esmaster01a rc.local[509]: Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/system/setup.py
Jan 23 18:17:56 ans-esmaster01a rc.local[509]: <127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
Jan 23 18:17:56 ans-esmaster01a rc.local[509]: <127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1485195476.72-26022585930503 `" && echo ansible-tmp-1485195476.72-26022585930503="` echo ~/.ansible/tmp/ansible-tmp-1485195476.72-26022585930503 `" ) && sleep 0'
Jan 23 18:17:56 ans-esmaster01a rc.local[509]: <127.0.0.1> PUT /tmp/tmp6CUh9V TO ~/.ansible/tmp/ansible-tmp-1485195476.72-26022585930503/setup.py
Jan 23 18:17:56 ans-esmaster01a rc.local[509]: <127.0.0.1> EXEC /bin/sh -c 'chmod u+x '"'"'~/.ansible/tmp/ansible-tmp-1485195476.72-26022585930503/'"'"' '"'"'~/.ansible/tmp/ansible-tmp-1485195476.72-26022585930503/setup.py'"'"' && sleep 0'
Jan 23 18:17:56 ans-esmaster01a rc.local[509]: <127.0.0.1> EXEC /bin/sh -c '/usr/bin/python '"'"'~/.ansible/tmp/ansible-tmp-1485195476.72-26022585930503/setup.py'"'"'; rm -rf "~/.ansible/tmp/ansible-tmp-1485195476.72-26022585930503/" > /dev/null 2>&1 && sleep 0'
Jan 23 18:17:56 ans-esmaster01a ansible-setup[3395]: Invoked with filter=* gather_subset=['all'] fact_path=/etc/ansible/facts.d gather_timeout=10
Jan 23 18:17:56 ans-esmaster01a rc.local[509]: ok: [localhost]
Jan 23 18:17:56 ans-esmaster01a rc.local[509]: TASK [test/1.0.0 : Update Properties File] *************************************
Jan 23 18:17:56 ans-esmaster01a rc.local[509]: task path: /ansible/test/1.0.0/tasks/main.yml:3
Jan 23 18:17:57 ans-esmaster01a rc.local[509]: <127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
Jan 23 18:17:57 ans-esmaster01a rc.local[509]: <127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1485195477.0-90841139958 `" && echo ansible-tmp-1485195477.0-90841139958="` echo ~/.ansible/tmp/ansible-tmp-1485195477.0-90841139958 `" ) && sleep 0'
Jan 23 18:17:57 ans-esmaster01a rc.local[509]: Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/files/stat.py
Jan 23 18:17:57 ans-esmaster01a rc.local[509]: <127.0.0.1> PUT /tmp/tmpQfw60z TO ~/.ansible/tmp/ansible-tmp-1485195477.0-90841139958/stat.py
Jan 23 18:17:57 ans-esmaster01a rc.local[509]: <127.0.0.1> EXEC /bin/sh -c 'chmod u+x '"'"'~/.ansible/tmp/ansible-tmp-1485195477.0-90841139958/'"'"' '"'"'~/.ansible/tmp/ansible-tmp-1485195477.0-90841139958/stat.py'"'"' && sleep 0'
Jan 23 18:17:57 ans-esmaster01a rc.local[509]: <127.0.0.1> EXEC /bin/sh -c '/usr/bin/python '"'"'~/.ansible/tmp/ansible-tmp-1485195477.0-90841139958/stat.py'"'"' && sleep 0'
Jan 23 18:17:57 ans-esmaster01a ansible-stat[3430]: Invoked with checksum_algorithm=sha1 mime=False get_checksum=True path=/var/tmp/IntroscopeEPAgent.properties checksum_algo=sha1 follow=False get_md5=False
Jan 23 18:17:57 ans-esmaster01a rc.local[509]: <127.0.0.1> PUT /tmp/tmpU4KurG TO ~/.ansible/tmp/ansible-tmp-1485195477.0-90841139958/source
Jan 23 18:17:57 ans-esmaster01a rc.local[509]: <127.0.0.1> EXEC /bin/sh -c 'chmod u+x '"'"'~/.ansible/tmp/ansible-tmp-1485195477.0-90841139958/'"'"' '"'"'~/.ansible/tmp/ansible-tmp-1485195477.0-90841139958/source'"'"' && sleep 0'
Jan 23 18:17:57 ans-esmaster01a rc.local[509]: Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/files/copy.py
Jan 23 18:17:57 ans-esmaster01a rc.local[509]: <127.0.0.1> PUT /tmp/tmpCaRClD TO ~/.ansible/tmp/ansible-tmp-1485195477.0-90841139958/copy.py
Jan 23 18:17:57 ans-esmaster01a rc.local[509]: <127.0.0.1> EXEC /bin/sh -c 'chmod u+x '"'"'~/.ansible/tmp/ansible-tmp-1485195477.0-90841139958/'"'"' '"'"'~/.ansible/tmp/ansible-tmp-1485195477.0-90841139958/copy.py'"'"' && sleep 0'
Jan 23 18:17:57 ans-esmaster01a rc.local[509]: <127.0.0.1> EXEC /bin/sh -c '/usr/bin/python '"'"'~/.ansible/tmp/ansible-tmp-1485195477.0-90841139958/copy.py'"'"' && sleep 0'
Jan 23 18:17:57 ans-esmaster01a ansible-copy[3443]: Invoked with src=/root/.ansible/tmp/ansible-tmp-1485195477.0-90841139958/source directory_mode=None force=True remote_src=None unsafe_writes=None selevel=None seuser=None setype=None group=None content=NOT_LOGGING_PARAMETER dest=/var/tmp/IntroscopeEPAgent.properties serole=None original_basename=IntroscopeEPAgent.properties.j2 delimiter=None mode=None regexp=None owner=None follow=True validate=None backup=False
Jan 23 18:17:57 ans-esmaster01a rc.local[509]: <127.0.0.1> EXEC /bin/sh -c 'rm -f -r '"'"'~/.ansible/tmp/ansible-tmp-1485195477.0-90841139958/'"'"' > /dev/null 2>&1 && sleep 0'
Jan 23 18:17:57 ans-esmaster01a rc.local[509]: fatal: [localhost]: FAILED! => {
Jan 23 18:17:57 ans-esmaster01a rc.local[509]:     "changed": true,
Jan 23 18:17:57 ans-esmaster01a rc.local[509]:     "failed": true,
Jan 23 18:17:57 ans-esmaster01a rc.local[509]:     "invocation": {
Jan 23 18:17:57 ans-esmaster01a rc.local[509]:         "module_args": {
Jan 23 18:17:57 ans-esmaster01a rc.local[509]:             "backup": false,
Jan 23 18:17:57 ans-esmaster01a rc.local[509]:             "content": null,
Jan 23 18:17:57 ans-esmaster01a rc.local[509]:             "delimiter": null,
Jan 23 18:17:57 ans-esmaster01a rc.local[509]:             "dest": "/var/tmp/IntroscopeEPAgent.properties",
Jan 23 18:17:57 ans-esmaster01a rc.local[509]:             "directory_mode": null,
Jan 23 18:17:57 ans-esmaster01a rc.local[509]:             "follow": true,
Jan 23 18:17:57 ans-esmaster01a rc.local[509]:             "force": true,
Jan 23 18:17:57 ans-esmaster01a rc.local[509]:             "group": null,
Jan 23 18:17:57 ans-esmaster01a rc.local[509]:             "mode": null,
Jan 23 18:17:57 ans-esmaster01a rc.local[509]:             "original_basename": "IntroscopeEPAgent.properties.j2",
Jan 23 18:17:57 ans-esmaster01a rc.local[509]:             "owner": null,
Jan 23 18:17:57 ans-esmaster01a rc.local[509]:             "regexp": null,
Jan 23 18:17:57 ans-esmaster01a rc.local[509]:             "remote_src": null,
Jan 23 18:17:57 ans-esmaster01a rc.local[509]:             "selevel": null,
Jan 23 18:17:57 ans-esmaster01a rc.local[509]:             "serole": null,
Jan 23 18:17:57 ans-esmaster01a rc.local[509]:             "setype": null,
Jan 23 18:17:57 ans-esmaster01a rc.local[509]:             "seuser": null,
Jan 23 18:17:57 ans-esmaster01a rc.local[509]:             "src": "/root/.ansible/tmp/ansible-tmp-1485195477.0-90841139958/source",
Jan 23 18:17:57 ans-esmaster01a rc.local[509]:             "unsafe_writes": null,
Jan 23 18:17:57 ans-esmaster01a rc.local[509]:             "validate": null
Jan 23 18:17:57 ans-esmaster01a rc.local[509]:         }
Jan 23 18:17:57 ans-esmaster01a rc.local[509]:     },
Jan 23 18:17:57 ans-esmaster01a rc.local[509]:     "msg": "Source /root/.ansible/tmp/ansible-tmp-1485195477.0-90841139958/source not found"
Jan 23 18:17:57 ans-esmaster01a rc.local[509]: }
Jan 23 18:17:57 ans-esmaster01a rc.local[509]:         to retry, use: --limit @/home/local/local.retry
Jan 23 18:17:57 ans-esmaster01a rc.local[509]: PLAY RECAP *********************************************************************
Jan 23 18:17:57 ans-esmaster01a rc.local[509]: localhost                  : ok=1    changed=0    unreachable=0    failed= 1


```
================================

Runs OK when executed on the node as root:

```
root@ans-esmaster01a:/ansible# ansible-playbook -vvvv local.yml --extra-vars=env=thor -f 1
Using /ansible/ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available

Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/dist-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: local.yml ************************************************************
1 plays in local.yml

PLAY [Install  Wily setup for ELK] *********************************************

TASK [setup] *******************************************************************
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/system/setup.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1485195606.14-11225926039776 `" && echo ansible-tmp-1485195606.14-11225926039776="` echo ~/.ansible/tmp/ansible-tmp-1485195606.14-11225926039776 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpOuRiH3 TO /root/.ansible/tmp/ansible-tmp-1485195606.14-11225926039776/setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1485195606.14-11225926039776/ /root/.ansible/tmp/ansible-tmp-1485195606.14-11225926039776/setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1485195606.14-11225926039776/setup.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1485195606.14-11225926039776/" > /dev/null 2>&1 && sleep 0'
ok: [localhost]

TASK [test/1.0.0 : Update Properties File] *************************************
task path: /ansible/test/1.0.0/tasks/main.yml:3
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1485195606.38-148223215695068 `" && echo ansible-tmp-1485195606.38-148223215695068="` echo ~/.ansible/tmp/ansible-tmp-1485195606.38-148223215695068 `" ) && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/files/stat.py
<127.0.0.1> PUT /tmp/tmpW3o_TP TO /root/.ansible/tmp/ansible-tmp-1485195606.38-148223215695068/stat.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1485195606.38-148223215695068/ /root/.ansible/tmp/ansible-tmp-1485195606.38-148223215695068/stat.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1485195606.38-148223215695068/stat.py && sleep 0'
<127.0.0.1> PUT /tmp/tmpXCL5WJ TO /root/.ansible/tmp/ansible-tmp-1485195606.38-148223215695068/source
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1485195606.38-148223215695068/ /root/.ansible/tmp/ansible-tmp-1485195606.38-148223215695068/source && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/files/copy.py
<127.0.0.1> PUT /tmp/tmpGD_KQu TO /root/.ansible/tmp/ansible-tmp-1485195606.38-148223215695068/copy.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1485195606.38-148223215695068/ /root/.ansible/tmp/ansible-tmp-1485195606.38-148223215695068/copy.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1485195606.38-148223215695068/copy.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1485195606.38-148223215695068/ > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {
    "changed": true,
    "checksum": "f52bff0e86439a5441a94037160acdfc86d4ff55",
    "dest": "/var/tmp/IntroscopeEPAgent.properties",
    "gid": 0,
    "group": "root",
    "invocation": {
        "module_args": {
            "backup": false,
            "content": null,
            "delimiter": null,
            "dest": "/var/tmp/IntroscopeEPAgent.properties",
            "directory_mode": null,
            "follow": true,
            "force": true,
            "group": null,
            "mode": null,
            "original_basename": "IntroscopeEPAgent.properties.j2",
            "owner": null,
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": "/root/.ansible/tmp/ansible-tmp-1485195606.38-148223215695068/source",
            "unsafe_writes": null,
            "validate": null
        }
    },
    "md5sum": "510d02b5e3c468e1a81c71c68809b4e9",
    "mode": "0600",
    "owner": "root",
    "size": 2470,
    "src": "/root/.ansible/tmp/ansible-tmp-1485195606.38-148223215695068/source",
    "state": "file",
    "uid": 0
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0


```

**Comment by alikins** [comment] 2017-01-23 20:39
Was this working in earlier versions of ansible (2.2.0?)

**Comment by alikins** [comment] 2017-01-23 20:49
For the case where ansible-playbook is running on boot, what user is it running as?

**Comment by ajaybhatnagar** [comment] 2017-01-23 20:53
yes, it was working with earlier version(s). On boot, script is started by root user.

**Comment by ajaybhatnagar** [comment] 2017-01-23 21:40
Same playbook executed with ansible version 2.1.4.0 works well. See logs below:
root@ans-esmaster01a:/var/tmp# ansible --version
ansible 2.1.4.0

Jan 23 21:35:40 ans-esmaster01a rc.local[526]: + ansible-playbook -vvvv local.yml --extra-vars=env=thor -f 1
Jan 23 21:35:41 ans-esmaster01a rc.local[526]: Using /ansible/ansible.cfg as config file
Jan 23 21:35:41 ans-esmaster01a rc.local[526]:  [WARNING]: Host file not found: /etc/ansible/hosts
Jan 23 21:35:41 ans-esmaster01a rc.local[526]:  [WARNING]: provided hosts list is empty, only localhost is available
Jan 23 21:35:41 ans-esmaster01a rc.local[526]: Loaded callback default of type stdout, v2.0
Jan 23 21:35:41 ans-esmaster01a rc.local[526]: PLAYBOOK: local.yml ************************************************************
Jan 23 21:35:41 ans-esmaster01a rc.local[526]: 1 plays in local.yml
Jan 23 21:35:41 ans-esmaster01a rc.local[526]: PLAY [Install  Wily setup for ELK] *********************************************
Jan 23 21:35:41 ans-esmaster01a rc.local[526]: TASK [setup] *******************************************************************
Jan 23 21:35:41 ans-esmaster01a rc.local[526]: <127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
Jan 23 21:35:41 ans-esmaster01a rc.local[526]: <127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1485207341.42-262124253378092 `" && echo ansible-tmp-1485207341.42-262124253378092="` echo $HOME/.ansible/tmp/ansible-tmp-1485207341.42-262124253378092 `" ) && sleep 0'
Jan 23 21:35:41 ans-esmaster01a rc.local[526]: <127.0.0.1> PUT /tmp/tmp52pQJa TO /.ansible/tmp/ansible-tmp-1485207341.42-262124253378092/setup
Jan 23 21:35:41 ans-esmaster01a rc.local[526]: <127.0.0.1> EXEC /bin/sh -c 'chmod u+x /.ansible/tmp/ansible-tmp-1485207341.42-262124253378092/ /.ansible/tmp/ansible-tmp-1485207341.42-262124253378092/setup && sleep 0'
Jan 23 21:35:41 ans-esmaster01a rc.local[526]: <127.0.0.1> EXEC /bin/sh -c 'LANG=en_CA.UTF-8 LC_ALL=en_CA.UTF-8 LC_MESSAGES=en_CA.UTF-8 /usr/bin/python /.ansible/tmp/ansible-tmp-1485207341.42-262124253378092/setup && sleep 0'
Jan 23 21:35:41 ans-esmaster01a ansible-basic.py[13850]: Invoked with filter=* gather_subset=['all'] fact_path=/etc/ansible/facts.d
Jan 23 21:35:41 ans-esmaster01a rc.local[526]: ok: [localhost]
Jan 23 21:35:41 ans-esmaster01a rc.local[526]: TASK [test/1.0.0 : Update Properties File] *************************************
Jan 23 21:35:41 ans-esmaster01a rc.local[526]: task path: /ansible/test/1.0.0/tasks/main.yml:3
Jan 23 21:35:41 ans-esmaster01a rc.local[526]: <127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
Jan 23 21:35:41 ans-esmaster01a rc.local[526]: <127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1485207341.96-154531094338841 `" && echo ansible-tmp-1485207341.96-154531094338841="` echo $HOME/.ansible/tmp/ansible-tmp-1485207341.96-154531094338841 `" ) && sleep 0'
Jan 23 21:35:41 ans-esmaster01a rc.local[526]: <127.0.0.1> PUT /tmp/tmp7QQVbr TO /.ansible/tmp/ansible-tmp-1485207341.96-154531094338841/stat
Jan 23 21:35:41 ans-esmaster01a rc.local[526]: <127.0.0.1> EXEC /bin/sh -c 'chmod u+x /.ansible/tmp/ansible-tmp-1485207341.96-154531094338841/ /.ansible/tmp/ansible-tmp-1485207341.96-154531094338841/stat && sleep 0'
Jan 23 21:35:41 ans-esmaster01a rc.local[526]: <127.0.0.1> EXEC /bin/sh -c 'LANG=en_CA.UTF-8 LC_ALL=en_CA.UTF-8 LC_MESSAGES=en_CA.UTF-8 /usr/bin/python /.ansible/tmp/ansible-tmp-1485207341.96-154531094338841/stat && sleep 0'
Jan 23 21:35:42 ans-esmaster01a ansible-basic.py[13899]: Invoked with checksum_algorithm=sha1 mime=False get_checksum=True path=/var/tmp/IntroscopeEPAgent.properties checksum_algo=sha1 follow=False get_md5=False
Jan 23 21:35:42 ans-esmaster01a rc.local[526]: <127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1485207342.14-127792145962499 `" && echo ansible-tmp-1485207342.14-127792145962499="` echo $HOME/.ansible/tmp/ansible-tmp-1485207342.14-127792145962499 `" ) && sleep 0'
Jan 23 21:35:42 ans-esmaster01a rc.local[526]: <127.0.0.1> PUT /tmp/tmpUxf9Oz TO /.ansible/tmp/ansible-tmp-1485207342.14-127792145962499/file
Jan 23 21:35:42 ans-esmaster01a rc.local[526]: <127.0.0.1> EXEC /bin/sh -c 'chmod u+x /.ansible/tmp/ansible-tmp-1485207342.14-127792145962499/ /.ansible/tmp/ansible-tmp-1485207342.14-127792145962499/file && sleep 0'
Jan 23 21:35:42 ans-esmaster01a rc.local[526]: <127.0.0.1> EXEC /bin/sh -c 'LANG=en_CA.UTF-8 LC_ALL=en_CA.UTF-8 LC_MESSAGES=en_CA.UTF-8 /usr/bin/python /.ansible/tmp/ansible-tmp-1485207342.14-127792145962499/file && sleep 0'
Jan 23 21:35:42 ans-esmaster01a ansible-basic.py[13915]: Invoked with directory_mode=None force=False remote_src=None path=/var/tmp/IntroscopeEPAgent.properties owner=None follow=False group=None state=None content=NOT_LOGGING_PARAMETER serole=None diff_peek=None setype=None dest=/var/tmp/IntroscopeEPAgent.properties selevel=None original_basename=IntroscopeEPAgent.properties.j2 regexp=None validate=None src=IntroscopeEPAgent.properties.j2 seuser=None recurse=False delimiter=None mode=None backup=None
Jan 23 21:35:42 ans-esmaster01a rc.local[526]: ok: [localhost] => {"changed": false, "checksum": "f52bff0e86439a5441a94037160acdfc86d4ff55", "dest": "/var/tmp/IntroscopeEPAgent.properties", "diff": {"after": {"path": "/var/tmp/IntroscopeEPAgent.properties"}, "before": {"path": "/var/tmp/IntroscopeEPAgent.properties"}}, "gid": 0, "group": "root", "invocation": {"module_args": {"backup": null, "content": null, "delimiter": null, "dest": "/var/tmp/IntroscopeEPAgent.properties", "diff_peek": null, "directory_mode": null, "follow": false, "force": false, "group": null, "mode": null, "original_basename": "IntroscopeEPAgent.properties.j2", "owner": null, "path": "/var/tmp/IntroscopeEPAgent.properties", "recurse": false, "regexp": null, "remote_src": null, "selevel": null, "serole": null, "setype": null, "seuser": null, "src": "IntroscopeEPAgent.properties.j2", "state": null, "validate": null}}, "mode": "0600", "owner": "root", "path": "/var/tmp/IntroscopeEPAgent.properties", "size": 2470, "state": "file", "uid": 0}
Jan 23 21:35:42 ans-esmaster01a rc.local[526]: PLAY RECAP *********************************************************************
### **Jan 23 21:35:42 ans-esmaster01a rc.local[526]: localhost                  : ok=2    changed=0    unreachable=0    failed=0**

**Comment by adamnoll** [comment] 2017-01-23 22:20
We are seeing the same kinds of issues, but with copy:

ansible 2.2.1.0
Ubuntu 16.04.1 LTS

- name: set timezone in timezone file
  copy: content="{{ timezone }}\n" dest=/etc/timezone

timezone: America/New_York

Run Locally:
TASK [ubuntu : set timezone in timezone file] **********************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "checksum": "ec3db0f5f9dd340fa169824332903411285b1d52", "failed": true, "msg": "Source /root/.ansible/tmp/ansible-tmp-1485208526.28-172388170768814/source not found"}

**Comment by alikins** [comment] 2017-01-23 22:51
When you say the playbook is executed at startup, what mechanism are you using to do that? (systemd service? init script? )

**Comment by ajaybhatnagar** [comment] 2017-01-24 02:13
It is being executed by context script at the time of vm launch. Env is kvm using opennebula.

**Comment by ajaybhatnagar** [comment] 2017-01-24 14:18
It is executed by context script for vm as root user after all initialization is done. Observed same issue when tried to use copy instead of template. Ansible version 2.1.4 works fine.

**Comment by bcoca** [comment] 2017-01-24 14:23
this is probably a dupe of  #20332, try using the PR #20486

**Comment by ApsOps** [comment] 2017-01-26 05:34
I'm hitting this when using copy module when running playbook with local connection via cloud-init on boot.

**Comment by bcoca** [comment] 2017-01-26 16:38
@ApsOps check my PR above, this is an issue with the cloud-init shell not following POSIX standard translation of ~/

**Comment by ajaybhatnagar** [comment] 2017-01-26 20:55
This does not explain why version ansible 2.14 works but not 2.2.1 with same OS and environment.

**Comment by bcoca** [comment] 2017-01-26 21:12
the difference is because before it use `$HOME` which was not getting translated in many cases and creating  the directories in unexpected locations, we switched to `~/` which is always supposed to get translated, but cloud-init seems to invoke shells in a way that does not comply with the POSIX standard.

**Comment by bcoca** [comment] 2017-01-26 21:19
since my fix seems to solve this issue for all cases, i'm closing this ticket

**Closed as completed by bcoca** 2017-01-26 21:19 UTC
Labels: affects_2.2, module, bug
