### ISSUE TITLE
git module fails when using sudo on Ansible 1.5.1/1.5.2

### ISSUE THREAD

**Issue by dmkoch** [ansible/ansible#6443] opened 2014-03-12 15:55 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.2
##### Environment:

Ubuntu 13.04 x86_64 on Ansible system and managed host
##### Summary:

git module broken as of Ansible 1.5.1/1.5.2 when running with sudo
##### Steps To Reproduce:

Run a git task over ssh as root, using sudo to an unprivileged user

```
- name: checkout project from git
  git: repo={{ my_repo }} dest=/srv/myproject accept_hostkey=yes
  sudo: yes
  sudo_user: myuser
```

/srv/myproject is owned by myuser.
##### Expected Results:

A copy of myproject from my_repo would be checked out in /srv/myproject
##### Actual Results:

```
failed: [host1.example.net] => {"cmd": ["/usr/bin/git", "ls-remote", "git@github.com:example/example.git", "-t", "refs/tags/HEAD"], "failed": true, "item": "", "rc": 128}
stderr: fatal: failed to stat '.': Permission denied

msg: fatal: failed to stat '.': Permission denied

FATAL: all hosts have already failed -- aborting

```

The task runs as expected when I downgrade Ansible to 1.5.0.

**Comment by mpdehaan** [comment] 2014-03-12 16:02
Can you check this on the devel branch?  We are working on a 1.5.3 candidate using some cherry-picks off there and this seems ok, despite some minor issues with adding host keys multiple times that we are chasing.

There was an issue with the way the host key commands were being passed not through the shell in that version.

Thanks!

**Comment by yuriks** [comment] 2014-03-12 17:00
I can confirm and have the same issue. What seems to be happening is that sudo doesn't change the cwd, it stays in root's cwd, then git tries to read the cwd and fails.

**Comment by dmkoch** [comment] 2014-03-12 17:45
The same error occurs with the devel branch at https://github.com/ansible/ansible/commit/ebfc776

**Comment by packetcollision** [comment] 2014-03-12 18:00
It's probably an ubuntu-specific issue. Ubuntu does not reset the HOME env when doing sudo, whereas Debian (and probably others) do. You can always override HOME by using "sudo -H" so maybe that should be the default if it isn't already.

**Comment by yuriks** [comment] 2014-03-12 18:08
`ansible -vvvv` indicates that `-H` is already being passed to sudo:

```
<provision> ESTABLISH CONNECTION FOR USER: root
<provision> REMOTE_MODULE git repo=git@github.com:digEcor/glide-cm.git dest=/home/tas-cm/glide-cm version=develop
<provision> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/yuriks/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', 'provision', "/bin/sh -c 'mkdir -p /tmp/ansible-tmp-1394642512.26-129235138633063 && chmod a+rx /tmp/ansible-tmp-1394642512.26-129235138633063 && echo /tmp/ansible-tmp-1394642512.26-129235138633063'"]
<provision> PUT /tmp/tmpB4urkl TO /tmp/ansible-tmp-1394642512.26-129235138633063/git
<provision> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/yuriks/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', 'provision', "/bin/sh -c 'chmod a+r /tmp/ansible-tmp-1394642512.26-129235138633063/git'"]
<provision> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/yuriks/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', 'provision', u'/bin/sh -c \'sudo -k && sudo -H -S -p "[sudo via ansible, key=tbxfsjxzrlebggeprctzpayylllvresn] password: " -u tas-cm /bin/sh -c \'"\'"\'echo SUDO-SUCCESS-tbxfsjxzrlebggeprctzpayylllvresn; /usr/bin/python /tmp/ansible-tmp-1394642512.26-129235138633063/git\'"\'"\'\'']
failed: [provision] => {"cmd": ["/usr/bin/git", "ls-remote", "git@github.com:digEcor/glide-cm.git", "-h", "refs/heads/develop"], "failed": true, "item": "", "rc": 128}
stderr: fatal: failed to stat '.': Permission denied

msg: fatal: failed to stat '.': Permission denied

FATAL: all hosts have already failed -- aborting
```

**Comment by mpdehaan** [comment] 2014-03-12 19:22
@jimi-c has been chasing this right now as well.

we will take a look at this.

**Comment by jimi-c** [comment] 2014-03-12 19:37
I've merged in #6451 above, which should resolve the issue. Please let us know if you continue seeing this problem. Thanks!

**Closed as completed** 2014-03-12 19:37 UTC
Labels: needs_info, bug

**Comment by yuriks** [comment] 2014-03-14 21:12
I still have the exact same issue with 1.5.3:

```
yuriks@glide-dev:~/src/glide-server/ansible$ ansible-playbook --version
ansible-playbook 1.5.3
yuriks@glide-dev:~/src/glide-server/ansible$ ansible-playbook -i yuriks.inventory site.yml

PLAY [glide-servers] **********************************************************

GATHERING FACTS ***************************************************************
ok: [provision]

[~~~snip~~~]

TASK: [cm | check out glide-cm] ***********************************************
failed: [provision] => {"cmd": ["/usr/bin/git", "ls-remote", "git@github.com:digEcor/glide-cm.git", "-h", "refs/heads/develop"], "failed": true, "item": "", "rc": 128}
stderr: fatal: failed to stat '.': Permission denied

msg: fatal: failed to stat '.': Permission denied

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/yuriks/site.retry

provision                  : ok=9    changed=0    unreachable=0    failed=1
```

**Comment by jctanner** [comment] 2014-03-14 21:16
@yuriks would you mind opening a new bug with all the relevant detail?
