### ISSUE TITLE
Blockinfile does not honour insertbefore/insertafter when both markers for beginning and ending of block are present

### ISSUE THREAD

**Issue by mivanov-its** [ansible/ansible#69372] opened 2020-05-07 12:44 UTC
##### SUMMARY
Blockinfile does not honour insertbefore/insertafter when both markers for beginning and ending of block are present.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
File  lib/ansible/modules/files/blockinfile.py

##### ANSIBLE VERSION
```
ansible 2.7.7
  config file = /home/user/.ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3 (default, Apr  3 2019, 05:39:12) [GCC 8.3.0]
```

##### CONFIGURATION
```
ALLOW_WORLD_READABLE_TMPFILES(/home/user/.ansible.cfg) = True
ANSIBLE_NOCOWS(/home/user/.ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/user/.ansible.cfg) = -o ForwardAgent=yes
DEFAULT_FORKS(/home/user/.ansible.cfg) = 50
DEFAULT_GATHERING(/home/user/.ansible.cfg) = explicit
DEFAULT_HOST_LIST(/home/user/.ansible.cfg) = ['/home/user/inventories/common/hosts']
DEFAULT_ROLES_PATH(/home/user/.ansible.cfg) = ['/home/user/roles']
DEFAULT_SCP_IF_SSH(/home/user/.ansible.cfg) = True
DEFAULT_SUDO_FLAGS(/home/user/.ansible.cfg) = -i
DEFAULT_TRANSPORT(/home/user/.ansible.cfg) = smart
HOST_KEY_CHECKING(/home/user/.ansible.cfg) = True
RETRY_FILES_ENABLED(/home/user/.ansible.cfg) = False
```

##### OS / ENVIRONMENT
debian

##### STEPS TO REPRODUCE

```
---
- hosts: localhost
  tasks:
    - name: test
      blockinfile:
        path: test
        insertbefore: x
        marker: "# {mark} ANSIBLE MANAGED BLOCK for a"
        block: |
          a
```

##### EXPECTED RESULTS

try this on a file with contents:

```
x
# BEGIN ANSIBLE MANAGED BLOCK for a
a
# END ANSIBLE MANAGED BLOCK for a

```

the block should be moved before the line "x"

##### ACTUAL RESULTS

the file is not changed

```
ansible-playbook local.yml        
[DEPRECATION WARNING]: DEFAULT_SUDO_FLAGS option, In favor of Ansible Become, which is a generic framework. See become_flags. , use become instead. This feature will be removed in version 2.8. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
 [WARNING]: Unable to parse /home/user/inventories/common/hosts as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [localhost] ************************************************************************************************************************************************************************************************

TASK [test] *****************************************************************************************************************************************************************************************************
ok: [localhost]

PLAY RECAP ******************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   

```

**Comment by mivanov-itsonix** [comment] 2020-05-07 12:46
The related lines in the code are:

https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/blockinfile.py#L279-L286

**Comment by Shrews** [comment] 2020-05-07 14:36
Hi,

If blockinfile finds both begin and end marker lines (which it will do in your example), then the insertafter/insertbefore behavior is ignored. This is working as designed. It is not intended to move an existing block to a new location. The intent of the insertbefore/insertafter options are for inserting the begin/end markers in a file that does not yet have them.

Given that I don't believe this to be a bug, I will close this issue.

**Closed as completed by Shrews** 2020-05-07 14:36 UTC
Labels: python3, module, support:core, affects_2.7, files

**Comment by mivanov-itsonix** [comment] 2020-05-08 07:10
This is no way mentioned in the documentation [1] which states:

```
insertafter string | Choices:EOF ←*regex* | If specified, the block will be inserted after the last match of specified regular expression.A special value is available; EOF for inserting the block at the end of the file.If specified regular expression has no matches, EOF will be used instead.
-- | -- | --
insertbefore string | Choices:BOF*regex* | If specified, the block will be inserted before the last match of specified regular expression.A special value is available; BOF for inserting the block at the beginning of the file.If specified regular expression has no matches, the block will be inserted at the end of the file.
```

It would be good to update that so that it clearly states that the block is never moved.

Thank you.

References:

1: https://docs.ansible.com/ansible/latest/modules/blockinfile_module.html

**Comment by Shrews** [comment] 2020-05-08 17:38
Hi @mivanov-itsonix,

I agree with you. I opened https://github.com/ansible/ansible/pull/69396 that should hopefully clarify that in the future.

Thanks!

**Comment by mivanov-itsonix** [comment] 2020-05-11 11:27
Hi @Shrews,

thank you for the update of the documentation.

I have to point out one more thing here, which needs to be updated in the documentation.

Please consider the case where the contents of the target file are:

```
# BEGIN ANSIBLE MANAGED BLOCK for a
x
# END ANSIBLE MANAGED BLOCK for a

# BEGIN ANSIBLE MANAGED BLOCK for a
y
# END ANSIBLE MANAGED BLOCK for a

# BEGIN ANSIBLE MANAGED BLOCK for a
z
# END ANSIBLE MANAGED BLOCK for a
```

When you execute the playbook:

```
$ ansible-playbook a.yml
[DEPRECATION WARNING]: DEFAULT_SUDO_FLAGS option, In favor of Ansible Become, which is a generic framework. See become_flags. , use become instead. This feature will be removed in version 2.8. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
 [WARNING]: Unable to parse /home/user/inventories/common/hosts as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [localhost] ************************************************************************************************************************************************************************************************

TASK [test] *****************************************************************************************************************************************************************************************************
changed: [localhost]

PLAY RECAP ******************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0   
```

the contents of the file are now:

```              
# BEGIN ANSIBLE MANAGED BLOCK for a
x
# END ANSIBLE MANAGED BLOCK for a

# BEGIN ANSIBLE MANAGED BLOCK for a
y
# END ANSIBLE MANAGED BLOCK for a

# BEGIN ANSIBLE MANAGED BLOCK for a
a
# END ANSIBLE MANAGED BLOCK for a
```
The documentation should clearly state that no warning or error message is issued in case the markers are present more than once in the file.

In case the markers are present more than once, the last block is modified.

In case the markers are inverted, the implementation silently rewrites them in the opposite order. This is imporant, consider the following initial contents:

```
# BEGIN ANSIBLE MANAGED BLOCK for a
x
# END ANSIBLE MANAGED BLOCK for a

# BEGIN ANSIBLE MANAGED BLOCK for a
y
# END ANSIBLE MANAGED BLOCK for a

# BEGIN ANSIBLE MANAGED BLOCK for a
```

here the END of the last block is missing!

The result after executing the playbook:

```
$ ansible-playbook a.yml
[DEPRECATION WARNING]: DEFAULT_SUDO_FLAGS option, In favor of Ansible Become, which is a generic framework. See become_flags. , use become instead. This feature will be removed in version 2.8. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
 [WARNING]: Unable to parse /home/user/inventories/common/hosts as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [localhost] ************************************************************************************************************************************************************************************************

TASK [test] *****************************************************************************************************************************************************************************************************
changed: [localhost]

PLAY RECAP ******************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0   
```

is

```              
# BEGIN ANSIBLE MANAGED BLOCK for a
x
# END ANSIBLE MANAGED BLOCK for a

# BEGIN ANSIBLE MANAGED BLOCK for a
y
# BEGIN ANSIBLE MANAGED BLOCK for a
a
# END ANSIBLE MANAGED BLOCK for a
```
