### ISSUE TITLE
ec2_vpc module arguments should be marked required?

### ISSUE THREAD

**Issue by kgxsz** [ansible/ansible#6763] opened 2014-03-30 15:07 UTC
##### Issue Type:

Bug, Docs/behaviour inconsistency
##### Ansible Version:

ansible 1.6 (devel cf434df6a4) last updated 2014/03/26 22:30:10 (GMT +100)
##### Environment:

OSX 10.9.2
##### Summary:

For ec2_vpc module, docs suggest that subnets and route_tables arguments are not required - this is contrary to behaviour
##### Steps To Reproduce:

From localhost with connection local:

```
  ec2_vpc:
    state=present
    cidr_block=172.0.0.0/16
    region=eu-west-1
```
##### Expected Results:

A successful run
##### Actual Results:

failed: [127.0.0.1] => {"failed": true}
msg: subnets needs to be a list of cidr blocks

(or when subnets are defined but not route_tables)

failed: [127.0.0.1] => {"failed": true}
msg: route tables need to be a list of dictionaries

**Comment by mpdehaan** [comment] 2014-03-30 16:05
Will take a look at this, thanks!

**Comment by jimi-c** [comment] 2014-04-08 20:49
@kgxsz could you try the following patch and see if it resolves your issue? 

<pre>
diff --git a/library/cloud/ec2_vpc b/library/cloud/ec2_vpc
index 44d207b..1b0d674 100644
--- a/library/cloud/ec2_vpc
+++ b/library/cloud/ec2_vpc
@@ -328,7 +328,7 @@ def create_vpc(module, vpc_conn):
 
 
     # Process all subnet properties
-    if not isinstance(subnets, list):
+    if subnets and not isinstance(subnets, list):
         module.fail_json(msg='subnets needs to be a list of cidr blocks')
     
     current_subnets = vpc_conn.get_all_subnets(filters={ 'vpc_id': vpc.id })
@@ -405,7 +405,7 @@ def create_vpc(module, vpc_conn):
     # think of without using painful aws ids.  Hopefully boto will add
     # the replace-route-table API to make this smoother and
     # allow control of the 'main' routing table.
-    if not isinstance(route_tables, list):
+    if route_tables and not isinstance(route_tables, list):
         module.fail_json(msg='route tables need to be a list of dictionaries')
     
 # Work through each route table and update/create to match dictionary array
</pre>

I believe the problem is, that if the subnets/route_tables are not defined they will be `None`, however they are both checked to be an instance of a list. This patch should correct that.

**Comment by jimi-c** [comment] 2014-04-23 15:09
I've gone ahead and merged the above commit in. If you continue experiencing any problems related to this issue, or if you have any further questions regarding this, please let us know. Thanks!

**Closed as completed** 2014-04-23 15:08 UTC
Labels: P2, docs

**Comment by kgxsz** [comment] 2014-04-23 15:34
Great! Thank you.
