### ISSUE TITLE
include_role erroneously skipped when including role is a dependency of a conditionally skipped role

### ISSUE THREAD

**Issue by ETSJustin** [ansible/ansible#51660] opened 2019-02-03 04:24 UTC
##### SUMMARY
The role test_1 uses include_role on test_2. When the role test_3, which depends on test_1, is a conditional (skipped) role in the playbook, the role test_2 is erroneously skipped.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
include_role

##### ANSIBLE VERSION

```paste below
ansible 2.7.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/suberjus/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Description:    Ubuntu 16.04.5 LTS

##### STEPS TO REPRODUCE

directory structure
```
├── roles
│   ├── test_1
│   │   └── tasks
│   │       └── main.yml
│   ├── test_2
│   │   └── tasks
│   │       └── main.yml
│   └── test_3
│       ├── meta
│       │   └── main.yml
│       └── tasks
│           └── main.yml
└── test.yml
```
./test.yml
```
---
- hosts: localhost
  roles:
    - test_1
    - role: test_3
      when: false
```
./roles/test_1/tasks/main.yml
```
---

- debug:
    msg: 'test_1'

- include_role:
    name: test_2

```
./roles/test_2/tasks/main.yml
```
---
- debug:
    msg: 'test_2'

```
./roles/test_3/meta/main.yml
```
---
dependencies:
  - test_1

```
./roles/test_3/tasks/main.yml
```
---
- debug:
    msg: 'test_3'

```

##### EXPECTED RESULTS

I expect the role test_1 to executed fully, including test_2, and test_3 should be skipped.
```
PLAY [localhost] ************************************************************************

TASK [Gathering Facts] ******************************************************************
ok: [localhost]

TASK [test_1 : debug] *******************************************************************
ok: [localhost] => {
    "msg": "test_1"
}

TASK [include_role : test_2] ************************************************************

TASK [test_2 : debug] *******************************************************************
ok: [localhost] => {
    "msg": "test_2"
}

TASK [test_3 : debug] *******************************************************************
skipping: [localhost]

PLAY RECAP ******************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0
```

##### ACTUAL RESULTS

The role test_1 runs; however the included role test_2 is erroneously skipped. test_3 is skipped as expected.

```paste below
PLAY [localhost] ************************************************************************

TASK [Gathering Facts] ******************************************************************
ok: [localhost]

TASK [test_1 : debug] *******************************************************************
ok: [localhost] => {
    "msg": "test_1"
}

TASK [include_role : test_2] ************************************************************

TASK [test_2 : debug] *******************************************************************
skipping: [localhost]

TASK [test_3 : debug] *******************************************************************
skipping: [localhost]

PLAY RECAP ******************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0

```

**Comment by Akasurde** [comment] 2019-03-12 04:58
@ETSJustin Just curious, I would like ask the use case behind running `test_1` role before `test_3` when `test_1` is already dependency of `test_3`.

**Comment by ETSJustin** [comment] 2019-03-13 03:35
> @ETSJustin Just curious, I would like ask the use case behind running `test_1` role before `test_3` when `test_1` is already dependency of `test_3`.

Hi Akasurde,
I am struggling to remember why I am explicitly running `test_1` first as this test case is miles away from the real issue I was experiencing, to distil the issue down to the bones. I suspect that I did this to prove that `test_1` is a valid role.
I commented out the explicit reference to `test_1` to see the impact and, now, I get:

> PLAY [localhost] *******************************************************************************************************************
> 
> TASK [Gathering Facts] *************************************************************************************************************
> ok: [localhost]
> 
> TASK [test_1 : debug] **************************************************************************************************************
> skipping: [localhost]
> 
> TASK [include_role : test_2] *******************************************************************************************************
> skipping: [localhost]
> 
> TASK [test_3 : debug] **************************************************************************************************************
> skipping: [localhost]
> 
> PLAY RECAP *************************************************************************************************************************
> localhost                  : ok=1    changed=0    unreachable=0    failed=0

Which indicates, to me, that the explicit reference does not have any baring to the issue I am experiencing.

**Comment by Akasurde** [comment] 2019-03-13 03:42
Yes, correct. When `test_1` is commented, `test_3` ran first. `test_3` uses `when: False` that then applies to `test_1` dependency and `include_role: test_2` then inherits it as well.

**Comment by s-hertel** [comment] 2021-07-06 13:01
Closing as a duplicate of #39543, so we can track this in one place.

**Closed as completed by s-hertel** 2021-07-06 13:02 UTC
Labels: support:core, bug, affects_2.7, P3
