### ISSUE TITLE
Synchronize doesn't "default" to files/

### ISSUE THREAD

**Issue by jjshoe** [ansible/ansible#6728] opened 2014-03-27 18:08 UTC
Given a role:

web_server /
  tasks /
    main.yml
  files /
    httpd.conf

And a task:
- name: sync | httpd confnig
  synchronize: src=httpd.conf dest=/etc/apache2/conf.d/widget.conf

You'll get an error because it assumes httpd.conf is based in the same directory you call ansible playbook from. The copy module however will happily check files/ for you.
##### Issue Type:

What kind of ticket is this?  You can say â€œBug Reportâ€, â€œFeature Ideaâ€, â€œFeature Pull Requestâ€, â€œNew Module Pull Requestâ€, â€œBugfix Pull Requestâ€, â€œDocumentation Reportâ€, or â€œDocs Pull Requestâ€.
##### Ansible Version:

Please supply the verbatim output from running â€œansible --versionâ€. 
##### Environment:

What OS are you running Ansible from and what OS are you managing?  Examples include RHEL 5/6, Centos 5/6, Ubuntu 12.04/13.10, *BSD, Solaris.  If this is a generic feature request or it doesnâ€™t apply, just say â€œN/Aâ€. 
##### Summary:

Please summarize your request in this space.  You will earn bonus points for being succinct, but please add enough detail so we can understand the request.
##### Steps To Reproduce:

If this is a bug ticket, please enter the steps you use to reproduce the problem in the space below.  If this is a feature request, please enter the steps you would use to use the feature.  If an example playbook is useful, please include a short reproducer inline, indented by four spaces.  If a longer one is necessary, please link one uploaded to gist.github.com. 
##### Expected Results:

Please enter your expected results in this space.  When running the steps supplied above, what would you expect to happen?  If showing example output, indent your output by four spaces so it will render correctly in GitHub. 
##### Actual Results:

Please enter your actual results in this space.  When running the steps supplied above, what actually happened?  If showing example output, indent your output by four spaces so it will render correctly in GitHub.

**Comment by mpdehaan** [comment] 2014-03-27 18:22
duplicate of #5307

**Closed as completed by mpdehaan** 2014-03-27 18:22 UTC
