### ISSUE TITLE
Issue a warning when trying to assign a value to a reserved variable 

### ISSUE THREAD

**Issue by TaiSHiNet** [ansible/ansible#16009] opened 2016-05-26 15:25 UTC
##### ISSUE TYPE

- Feature Idea
##### ANSIBLE VERSION

```
ansible 2.0.2.0
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

When trying to assign a value to a reserved variable name, there are no warnings which can lead to unexpected behavior
##### STEPS TO REPRODUCE

Create any role, assign a reserved variable a value 
inventory_file: "whatever"

```
playbook.yml:
- name: test
  roles:
    - test

roles/test/defaults/main.yml:
inventory_file: "inventory.csv"

roles/test/tasks/main.yml:
- debug: msg="{{ inventory_file }}"

ansible-playbook -i /dev/null playbook.yml
```

##### EXPECTED RESULTS

`WARNING: You're trying to assign a value to a reserved variable name
msg=/dev/null`

or 

```
msg="inventory.csv"
```
##### ACTUAL RESULTS

```
msg="/dev/null"
```

**Comment by bcoca** [comment] 2016-05-27 02:06
dupe of #4816

**Closed as completed by bcoca** 2016-05-27 02:06 UTC
Labels: feature

**Comment by TaiSHiNet** [comment] 2016-05-27 02:18
Thanks @bcoca, I did search but seems it wasn't enough
