### ISSUE TITLE
Issue with 'include' statements and role path

### ISSUE THREAD

**Issue by dp4qb** [ansible/ansible#10828] opened 2015-04-24 09:18 UTC
My ansible's 'include' statement was working fine, but recently after including ymls in subfolder, it somehow brokes the role's path.

Here's the tree of my project:

```
.
├── site.yml
├── inventory.ini
└── roles
    └── webservers
        ├── files
        │   └── crt.crt
        ├── tasks
        │   ├── main.yml
        │   ├── httpd.yml
        │   ├── dev
        │   │   ├── httpd.yml
        │   │   └── main.yml
        │   └── prod
        │       ├── httpd.yml
        │       └── main.yml
        ├── templates
        │   └── httpd_conf.j2
        └── vars
            └── main.yml
```

site.yml:

```
 - name: Install base software
   sudo: yes
   vars:
      profile:    "dev"
   roles:
      - webservers
```

roles/webservers/tasks/main.yml:

```
 - name: Install httpd
   include: httpd.yml

 - name: Including specific tasks
   include: "{{ profile }}/main.yml" 
```

Prior to this point, it works just fine. But the next step, after including the "profile"/main.yml, brokes the role's path.

roles/webservers/tasks/dev/main.yml:

```
 - name:  Create httpd.conf from template
   template: src=httpd_conf.j2 dest=/etc/httpd/conf/httpd.conf
   with_items: webservers_httpd_vhosts
```

results an error:

```
TASK: [webservers | Create httpd.conf from template] *********************
fatal: [192.168.0.2] => input file not found at /home/me/git/repo/projects/ans/roles/webservers/tasks/templates/httpd_conf.j2 or /home/me/git/repo/projects/ans/httpd_conf.j2

FATAL: all hosts have already failed -- aborting
```

So, after this 'include', it somehow thinks that role's root is located in 'webservers/tasks/', instead of 'webservers/'. But in the same time, it sees the variables in 'webservers/vars/' path.

Moreover, it was working fine and recently just broke. I haven't updated ansible, nor edited it's parameters, just updated the playbook.

If I specify the 'src=../../templates/httpd_conf.j2' it works fine, but since this behaviour just appeared like from nowhere, I can't rely on this path.

I've managed to use this workaround: template: src="{{ role_path }}/templates/httpd_conf.j2" dest=/etc/httpd/conf/httpd.conf But that's a workaround. The reason of auto-pathing is broke is still undiscovered.

Ansilbe's version: 1.9.0.1

**Comment by nickhammond** [comment] 2015-04-30 02:44
What's in dev/httpd.yml & prod/httpd.yml?

**Comment by dp4qb** [comment] 2015-05-02 23:17
There are some actions with templates, similar to dev/main.yml, they are failing too.

**Comment by vadanx** [comment] 2015-06-01 13:02
I'm seeing the same behaviour in ansible 1.8.2.

```
# file is site.yml
- include: "common.yml"
- include: "{{ site }}.yml"
```

We name all of our ansible plays according to their {{ site }} variable, so instead of including every single site play in site.yml. Spitting up an error where it cannot find the literal {{ site }}.yml file.

```
$ ansible-playbook /tmp/provision/site.yml 

ERROR: file could not read: /tmp/provision/{{ site }}.yml
```

It would be nice to include only those that are required.

**Comment by jimi-c** [comment] 2015-07-12 21:06
I believe this issue should be resolved in devel, however I'm not sure if there's enough information here to definitively test what you're seeing.  Could someone retry this in the current devel and let us know if it's still a problem? Thanks!

**Comment by jctanner** [comment] 2016-06-01 18:45
I was able to reproduce this issue with any 1.x version, but not with 2.x ...

| version | rc |
| --- | --- |
| v1.8.0 | 1 |
| v1.8.1 | 1 |
| v1.8.2 | 3 |
| v1.8.3 | 3 |
| v1.8.4 | 3 |
| v1.9.0-0.1.rc1 | 3 |
| v1.9.0-0.2.rc2 | 3 |
| v1.9.0-1 | 3 |
| v1.9.0-2 | 3 |
| v1.9.0.1-1 | 3 |
| v1.9.1-0.1.rc1 | 3 |
| v1.9.1-0.2.rc2 | 3 |
| v1.9.1-0.3.rc3 | 3 |
| v1.9.1-0.4.rc4 | 3 |
| v1.9.1-1 | 3 |
| v1.9.2-0.1.rc1 | 3 |
| v1.9.2-0.2.rc2 | 3 |
| v1.9.2-1 | 3 |
| v1.9.3-0.1.rc1 | 3 |
| v1.9.3-0.2.rc2 | 3 |
| v1.9.3-0.3.rc3 | 3 |
| v1.9.3-1 | 3 |
| v1.9.4-0.1.rc1 | 3 |
| v1.9.4-0.2.rc2 | 3 |
| v1.9.4-0.3.rc3 | 3 |
| v1.9.4-1 | 3 |
| v1.9.5-0.1.rc1 | 3 |
| v1.9.5-1 | 3 |
| v1.9.6-0.1.rc1 | 3 |
| v1.9.6-1 | 3 |
| v2.0.0-0.6.rc1 | 0 |
| v2.0.0-0.7.rc2 | 0 |
| v2.0.0-0.8.rc3 | 0 |
| v2.0.0-0.9.rc4 | 0 |
| v2.0.0.0-1 | 0 |
| v2.0.0.1-1 | 0 |
| v2.0.0.2-1 | 0 |
| v2.0.1.0-0.1.rc1 | 0 |
| v2.0.1.0-0.2.rc2 | 0 |
| v2.0.1.0-1 | 0 |
| v2.0.2.0-0.1.rc1 | 0 |
| v2.0.2.0-0.2.rc2 | 0 |
| v2.0.2.0-0.3.rc3 | 0 |
| v2.0.2.0-0.4.rc4 | 0 |
| v2.0.2.0-1 | 0 |
| v2.1.0.0-0.1.rc1 | 0 |
| v2.1.0.0-0.2.rc2 | 0 |
| v2.1.0.0-0.3.rc3 | 0 |
| v2.1.0.0-0.4.rc4 | 0 |
| v2.1.0.0-1 | 0 |

**Comment by jctanner** [comment] 2016-06-01 18:46
Hi!

We believe recent versions of ansible should resolve this question or problem for you.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Closed as completed by jctanner** 2016-06-01 18:46 UTC
Labels: P2, bug
