### ISSUE TITLE
Synchronize module doesn't prepend path to src when run locally

### ISSUE THREAD

**Issue by mishari** [ansible/ansible#9606] opened 2014-11-24 12:54 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

1.7.2
##### Environment:

Vagrant Ubuntu 14.04
##### Summary:

synchronize module doesn't prepend ansible role/xxx/files directory to src
##### Steps To Reproduce:

Have the following role:
- name: Copy solr directory to tomcat
  synchronize: src=solr dest="{{tomcat_dir}}"

Then run as normal from localhost:
ansible-playbook ansible/site-vagrant.yml -i ansible/stage --connection=local
##### Expected Results:

in the generated python file:
MODULE_COMPLEX_ARGS = '{"dest": "/home/vagrant/webapps/tomcat", "src": "/home/vagrant/ansible/roles/solr/files/solr"}'
##### Actual Results:

in the generated python file:
MODULE_COMPLEX_ARGS = '{"dest": "/home/vagrant/webapps/tomcat", "src": "solr"}'

**Comment by acorbi** [comment] 2014-11-24 12:56
+1

**Comment by mishari** [comment] 2014-11-25 04:31
I have a preliminary patch based on what I found in template.py but I believe it may still cause problems due to rsync's different remote/local syntax:

```
diff --git a/lib/ansible/runner/action_plugins/synchronize.py b/lib/ansible/runner/action_plugins/synchronize.py
old mode 100644
new mode 100755
index 8a8555a..252dcdc
--- a/lib/ansible/runner/action_plugins/synchronize.py
+++ b/lib/ansible/runner/action_plugins/synchronize.py
@@ -108,6 +108,11 @@ class ActionModule(object):
         src = template.template(self.runner.basedir, src, inject)
         dest = template.template(self.runner.basedir, dest, inject)

+        if '_original_file' in inject:
+            src = utils.path_dwim_relative(inject['_original_file'], 'files', src, self.runner.basedir)
+        else:
+            src = utils.path_dwim(self.runner.basedir, src)
+
         try:
             options['local_rsync_path'] = inject['ansible_rsync_path']
         except KeyError:
--
1.9.3 (Apple Git-50)
```

**Comment by mishari** [comment] 2014-11-25 05:14
In regarding to pull request #9614 I'm not sure how valid this is since synchronize.py is in a submodule. But the code seems to make the assumption that one side of the equation has to be a remote host, so I added an extra condition that is a catchall and prepends full path to the source.

**Comment by jimi-c** [comment] 2015-06-29 03:01
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0)

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by amenonsen** [comment] 2015-07-25 03:50
I can reproduce this behaviour even in devel. The command issued is:

```
"cmd": "rsync --delay-updates -F --compress --archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no' --out-format='<<CHANGED>>%i %n%L' \"a\" \"b\"",
```

Note "a", which should be "roles/foo/files/a".

**Comment by abadger** [comment] 2015-08-05 20:45
This should be fixed by: https://github.com/ansible/ansible/commit/e7b5cb87828a49cfc8771ab3d83fda157d42972f

let me know if that's not the case!

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Closed as completed by abadger** 2015-08-05 20:45 UTC
Labels: P2, bug
