### ISSUE TITLE
[v2] yum with_items not working

### ISSUE THREAD

**Issue by orderedchaosdev** [ansible/ansible#13087] opened 2015-11-09 06:14 UTC
Issue Type:

Bug Report

Ansible Version:

_this was the commit that broke it_
ansible checkout 5040abaaf24a3de32ac665a35e83a5348de43098

Ansible Configuration:

N/A

Environment:

Centos 6.7

Summary:

Steps To Reproduce:

```
yum: name={{ item }} state=installed
with_items: yum_pkgs
```

it just lists the the first item in yum_pkgs as every item so if for example

```
yum_pkgs:
 - vim
 - gedit
```

Expected Results:

It installs vim and gedit

Actual Results:

It would install vim and vim

it would act like the list was

```
yum_pkgs:
 - vim
 - vim
```

same thing for

```
yum: name={{ item }} state=installed
with_items: "{{ yum_pkgs }}"
```

and

```
yum: name={{ item}} state=installed
with_items: 
- "{{ yum_pkgs }}"
```

**Comment by jimi-c** [comment] 2015-11-09 19:08
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed** 2015-11-09 19:08 UTC
Labels: P1, bug, packaging

**Comment by jimi-c** [comment] 2015-11-09 19:09
@Yannig I'd be interested to see if this has any negative impact on performance, if you would like to retest against the sample you used in the original PR.

**Comment by Yannig** [comment] 2015-11-09 20:41
@jimi-c Well, it's seems to have some drawback on performance:
- before patch: 3.1s
- with last devel version: 5.6s

In fact, I was also working on another solution directly in task_executor. Here's the patch:

``` diff
diff --git a/lib/ansible/executor/task_executor.py b/lib/ansible/executor/task_executor.py
index 022243b..6092bff 100644
--- a/lib/ansible/executor/task_executor.py
+++ b/lib/ansible/executor/task_executor.py
@@ -256,7 +256,8 @@ class TaskExecutor:
                     variables['item'] = item
                     if self._task.evaluate_conditional(templar, variables):
                         if templar._contains_vars(name):
-                            new_item = templar.template(name)
+                            # Do not use template call here as item is changing everytime
+                            new_item = templar._do_template(name)
                             final_items.append(new_item)
                         else:
                             final_items.append(item)
```

The bad things is that I'm using a private method in template object but we can add a new one named something like template_item or template_no_cache.

The good thing is that this new version does not have drawback in regards of performance (3.1s like before)

What do you think about?

**Comment by Yannig** [comment] 2015-11-09 20:59
To be honest, I think that this commit did not have consequence on templating speed and the speed regression came from something else.

**Comment by Yannig** [comment] 2015-11-09 21:54
@jimi-c I have submited a new patch against last devel here: https://github.com/ansible/ansible/pull/13102
