### ISSUE TITLE
comma character breaks "changed_when/failed_when" directive

### ISSUE THREAD

**Issue by rnikaido** [ansible/ansible#15516] opened 2016-04-21 11:20 UTC
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
% ansible --version
ansible 2.0.2.0
  config file = 
  configured module search path = Default w/o overrides
```

This issue is not appeared in ansible 2.0.1.0 or 1.9.6
##### OS / ENVIRONMENT

mac OS X el capitan 10.11.4
##### SUMMARY

a comma breaks "changed_when/failed_when" directive
##### STEPS TO REPRODUCE

```
- hosts: localhost
  gather_facts: no
  tasks:
    - debug: msg=OK
      register: result
      changed_when: "100 | random(1,2) == 1"
#      changed_when: "100 | random == 1" is OK
```

##### EXPECTED RESULTS

```
TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "OK"
}
```
##### ACTUAL RESULTS

```
TASK [debug] *******************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check '100 | random(1' failed. The error was: template error while templating string: unexpected '}', expected ')'. String: {% if 100 | random(1 %} True {% else %} False {% endif %}"}
```

**Comment by bcoca** [comment] 2016-04-21 15:22
as workaround:

```
changed_when:
  - "100 | random(1,2) == 1"
```

or

```
changed_when: ["100 | random(1,2) == 1"]
```

**Comment by abadger** [comment] 2016-04-22 01:08
Duplicate of #15291   We're going to discuss what to do there so closing this issue for now.

**Closed as completed by abadger** 2016-04-22 01:08 UTC
