### ISSUE TITLE
ansible_winrm_transport credssp connection error on localized Windows Server 2012R2 (for example - Finnish, Russian)

### ISSUE THREAD

**Issue by dssdss** [ansible/ansible#69828] opened 2020-06-02 09:45 UTC
##### SUMMARY

Ansible can't connect to windows using ansible_winrm_transport credssp using default localized administrator name: Järjestelmänvalvoja, Администратор

In localized windows versions used "localized" "Administrator" Account Name, for example:
 https://social.technet.microsoft.com/wiki/contents/articles/13813.localized-names-for-administrator-account-in-windows.aspx
Language	Translation	   
Finnish	Järjestelmänvalvoja	   
French	Administrateur	   
Hungarian	Rendszergazda	   
Portuguese (Brazil)	Administrador	   
Portuguese (Portugal)	Administrador	   
Russian	Администратор	   
Spanish	Administrador	   
Swedish	Administratör	 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

All win components seem broken

##### ANSIBLE VERSION

```paste below
ansible 2.9.9
  config file = /home/dss/anstest/ansible.cfg
  configured module search path = ['/home/dss/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]
```

dss@wmgm:~/anstest$ pip3 list
Package             Version      
------------------- -------------
ansible             2.9.9        
asn1crypto          0.24.0       
certifi             2018.8.24    
cffi                1.14.0       
chardet             3.0.4        
cryptography        2.8          
distro-info         0.21         
entrypoints         0.3          
httplib2            0.11.3       
idna                2.6          
Jinja2              2.11.1       
jmespath            0.9.4        
kerberos            1.3.0        
keyring             17.1.1       
keyrings.alt        3.1.1        
MarkupSafe          1.1.1        
ntlm-auth           1.4.0        
pip                 18.1         
pyasn1              0.4.8        
pycparser           2.19         
pycrypto            2.6.1        
pycurl              7.43.0.2     
PyGObject           3.30.4       
pykerberos          1.2.1        
pyOpenSSL           19.1.0       
PySimpleSOAP        1.16.2       
python-apt          1.8.4.1      
python-debian       0.1.35       
python-debianbts    2.8.2        
pyvmomi             6.7.3        
pywinrm             0.4.1        
pyxdg               0.25         
PyYAML              5.3          
reportbug           7.5.3-deb10u1
requests            2.22.0       
requests-credssp    1.1.1        
requests-kerberos   0.12.0       
requests-ntlm       1.1.0        
SecretStorage       2.3.1        
setuptools          40.8.0       
six                 1.12.0       
unattended-upgrades 0.1          
urllib3             1.24.1       
wheel               0.32.3       
xmltodict           0.12.0       
zabbix-api          0.5.4     

##### CONFIGURATION

```paste below
DEFAULT_CALLBACK_PLUGIN_PATH(/home/dss/anstest/ansible.cfg) = ['/home/dss/anstest/callback_plugins']
DEFAULT_HOST_LIST(/home/dss/anstest/ansible.cfg) = ['/home/dss/anstest/hosts']
DEFAULT_VAULT_PASSWORD_FILE(/home/dss/anstest/ansible.cfg) = /home/dss/anstest/vault_pass
dss@wmgm:~/anstest$ 
```

##### OS / ENVIRONMENT

OS I'm managing:
PS C:\Users\testuser> gwmi win32_operatingsystem | select caption, OSArchitecture, Version, BuildNumber | fl

caption        : Microsoft Windows Server 2012 R2 Standard
OSArchitecture : 64-разрядная
Version        : 6.3.9600
BuildNumber    : 9600

PS C:\Users\testuser> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.34014
BuildVersion                   6.3.9600.17090
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2

Localization:

C:\Windows\system32>dism /online /get-intl

Deployment Image Servicing and Management tool
Version: 6.3.9600.17031

Image Version: 6.3.9600.17031

Reporting online international settings.

Default system UI language : ru-RU
The UI language fallback is : en-US
System locale : ru-RU
Default time zone : Russian Standard Time
Active keyboard(s) : 0419:00000419, 0409:00000409
Keyboard layered driver : PC/AT Enhanced Keyboard (101/102-Key)

Installed language(s): en-US
  Type : Fully localized language.
Installed language(s): ru-RU
  Type : Partially localized language, MUI type.
  Fallback Languages en-US

##### STEPS TO REPRODUCE

```yaml
Russian default administrator account:
~/ansible/host_vars/t3.comita.lan:
---
ansible_user: Администратор
#ansible_user: 'Järjestelmänvalvoja'
ansible_password: ChangePassw0rd2

ansible_winrm_transport: credssp

ansible_port: '5985'
ansible_connection: 'winrm'

ansible_winrm_server_cert_validation: ignore
validate_certs: false

~/ansible/hosts:
[test]
t3.comita.lan

```

##### ACTUAL RESULTS

```paste below
dss@wmgm:~/anstest$ ansible t3.comita.lan -m win_ping -vvvv
ansible 2.9.9
  config file = /home/dss/anstest/ansible.cfg
  configured module search path = ['/home/dss/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]
Using /home/dss/anstest/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/dss/anstest/hosts as it did not pass its verify_file() method
script declined parsing /home/dss/anstest/hosts as it did not pass its verify_file() method
auto declined parsing /home/dss/anstest/hosts as it did not pass its verify_file() method
Parsed /home/dss/anstest/hosts inventory source with ini plugin
Loading callback plugin minimal of type stdout, v2.0 from /usr/local/lib/python3.7/dist-packages/ansible/plugins/callback/minimal.py
META: ran handlers
Using module file /usr/local/lib/python3.7/dist-packages/ansible/modules/windows/win_ping.ps1
Pipelining is enabled.
<t3.comita.lan> ESTABLISH WINRM CONNECTION FOR USER: Администратор on PORT 5985 TO t3.comita.lan
t3.comita.lan | UNREACHABLE! => {
    "changed": false,
    "msg": "credssp: 'ascii' codec can't encode characters in position 0-12: ordinal not in range(128)",
    "unreachable": true
}
```

Finnish default administrator account:

~/ansible/host_vars/t3.comita.lan:
---
#ansible_user: Администратор
ansible_user: 'Järjestelmänvalvoja'
ansible_password: ChangePassw0rd2

ansible_winrm_transport: credssp

ansible_port: '5985'
ansible_connection: 'winrm'

ansible_winrm_server_cert_validation: ignore
validate_certs: false

dss@wmgm:~/anstest$ ansible t3.comita.lan -m win_ping 
t3.comita.lan | UNREACHABLE! => {
    "changed": false,
    "msg": "credssp: 'ascii' codec can't encode character '\\xe4' in position 1: ordinal not in range(128)",
    "unreachable": true
}

**Comment by jborean93** [comment] 2020-06-02 10:09
Curious, if you set `ansible_winrm_transport: ntlm` do you see the same issue? This will help track down whether the problem is with the requests-credssp library or ntlm-auth.

**Comment by dssdss** [comment] 2020-06-02 13:54
~/ansible/host_vars/t3.comita.lan:
`---
ansible_user: Администратор
#ansible_user: 'Järjestelmänvalvoja'
ansible_password: ChangePassw0rd2

ansible_winrm_transport: ntlm

ansible_port: '5985'
ansible_connection: 'winrm'

ansible_winrm_server_cert_validation: ignore
validate_certs: false

...`

`dss@wmgm:~/anstest$ ansible t3.comita.lan -m win_ping -vvvv
ansible 2.9.9
  config file = /home/dss/anstest/ansible.cfg
  configured module search path = ['/home/dss/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]
Using /home/dss/anstest/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/dss/anstest/hosts as it did not pass its verify_file() method
script declined parsing /home/dss/anstest/hosts as it did not pass its verify_file() method
auto declined parsing /home/dss/anstest/hosts as it did not pass its verify_file() method
Parsed /home/dss/anstest/hosts inventory source with ini plugin
Loading callback plugin minimal of type stdout, v2.0 from /usr/local/lib/python3.7/dist-packages/ansible/plugins/callback/minimal.py
META: ran handlers
Using module file /usr/local/lib/python3.7/dist-packages/ansible/modules/windows/win_ping.ps1
Pipelining is enabled.
<t3.comita.lan> ESTABLISH WINRM CONNECTION FOR USER: Администратор on PORT 5985 TO t3.comita.lan
t3.comita.lan | UNREACHABLE! => {
    "changed": false,
    "msg": "ntlm: 'ascii' codec can't encode characters in position 0-12: ordinal not in range(128)",
    "unreachable": true
}`

**Comment by jborean93** [comment] 2020-06-03 03:40
Thanks that confirms the problem is in ntlm-auth, can you run the following python script?

```python
from winrm.protocol import Protocol

p = Protocol(
    endpoint='http://t3.comita.lan:5985/wsman',
    username=u"Администратор",
    password=u"My password",
    transport='credssp')
shell_id = p.open_shell()
command_id = p.run_command(shell_id, 'hostname', [])
std_out, std_err, status_code = p.get_command_output(shell_id, command_id)
p.cleanup_command(shell_id, command_id)
p.close_shell(shell_id)
```

This will give us the exception traceback that tells what where in the code it is failing.

**Comment by dssdss** [comment] 2020-06-04 07:44
dss@wmgm:~/anstest$ /usr/bin/python3 --version
```bash
Python 3.7.3
```

===========

dss@wmgm:~/anstest$ cat test.py
```python
#!/usr/bin/python3
from winrm.protocol import Protocol

p = Protocol(
    endpoint='http://t3.comita.lan:5985/wsman',
    username=u"Администратор",
    password=u"ChangePassw0rd2",
    transport='credssp')
shell_id = p.open_shell()
command_id = p.run_command(shell_id, 'hostname', [])
std_out, std_err, status_code = p.get_command_output(shell_id, command_id)
p.cleanup_command(shell_id, command_id)
p.close_shell(shell_id)
```

===========

dss@wmgm:~/anstest$ ./test.py 
```python
Traceback (most recent call last):
  File "./test.py", line 9, in <module>
    shell_id = p.open_shell()
  File "/usr/local/lib/python3.7/dist-packages/winrm/protocol.py", line 166, in open_shell
    res = self.send_message(xmltodict.unparse(req))
  File "/usr/local/lib/python3.7/dist-packages/winrm/protocol.py", line 243, in send_message
    resp = self.transport.send_message(message)
  File "/usr/local/lib/python3.7/dist-packages/winrm/transport.py", line 310, in send_message
    self.build_session()
  File "/usr/local/lib/python3.7/dist-packages/winrm/transport.py", line 293, in build_session
    self.setup_encryption()
  File "/usr/local/lib/python3.7/dist-packages/winrm/transport.py", line 299, in setup_encryption
    self._send_message_request(prepared_request, '')
  File "/usr/local/lib/python3.7/dist-packages/winrm/transport.py", line 328, in _send_message_request
    response = self.session.send(prepared_request, timeout=self.read_timeout_sec)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 653, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests_credssp/credssp.py", line 448, in response_hook
    response = self.handle_401(response, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests_credssp/credssp.py", line 487, in handle_401
    out_token, step_name = credssp_gen.send(in_token)
  File "/usr/local/lib/python3.7/dist-packages/requests_credssp/credssp.py", line 127, in credssp_generator
    auth_step.send(bytes(ts_request['negoTokens'][0]['negoToken']))
  File "/usr/local/lib/python3.7/dist-packages/requests_credssp/spnego.py", line 522, in step
    msg3 = self._context.step(msg2)
  File "/usr/local/lib/python3.7/dist-packages/ntlm_auth/ntlm.py", line 86, in step
    cbt_data=self.cbt_data
  File "/usr/local/lib/python3.7/dist-packages/ntlm_auth/messages.py", line 339, in __init__
    self.user_name = user_name.encode(encoding_value)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-12: ordinal not in range(128)
```

**Comment by jborean93** [comment] 2020-06-06 00:03
Thanks for the details, it turns out I've already fixed this problem with https://github.com/jborean93/ntlm-auth/pull/26 and I just hadn't merged/created a release for it yet. The problem right now is that the ntlm-auth logic isn't using UTF-16 to encode the strings if the server supports it but the very basic ASCII encoding which only supports limited characters. The PR I linked will make sure it uses UTF-16 to encode characters sent in the NTLM message correctly.

I tested out the changes in that PR against a local user I created `ÜseӜ𝄞` with the password `Pӓ$sw0r̈d𝄞`. If you do get a chance to test it out that would be great but I'll try and release those changes on pypi sometime soon.

For now I'll keep this issue open until the release has been done.

**Comment by dssdss** [comment] 2020-06-08 09:11
Yes!!! Now, its working!

Thanks a lot! =)

Do I need to close issue, or you'll close it by yourself?

**Comment by jborean93** [comment] 2020-06-08 20:34
I'll keep it open until I've created the new ntlm-auth release. Thanks for confirming it fixes your problem as well.

**Comment by jborean93** [comment] 2020-06-16 08:52
ntlm-auth 1.5.0 has been [released](https://github.com/jborean93/ntlm-auth/releases/tag/v1.5.0) with this fix included. Thanks for reporting the error.

**Closed as completed by jborean93** 2020-06-16 08:52 UTC
Labels: windows, python3, support:core, bug, affects_2.9
