### ISSUE TITLE
Notification is executed when task was not changed

### ISSUE THREAD

**Issue by r0bj** [ansible/ansible#7571] opened 2014-05-27 19:42 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.2
##### Environment:

OS X 10.9.3
##### Summary:

Notification is executed when task was not changed.
This behaviour occurs only on ansible 1.6.2 - earlier versions are ok.
##### Steps To Reproduce:

Simple play:
  tasks:
    - name: write /etc/ntp
      copy: src=ntp.conf dest=/etc/ntp.conf owner=root group=root mode=0644
      notify: restart ntp

  handlers:
    - name: restart ntp
      service: name=ntp state=restarted

Two hosts: c01, c02. File /etc/ntp.conf is different than source on c01.
##### Expected Results:

TASK: [write /etc/ntp] ********************************************************
ok: [c02]
changed: [c01]

NOTIFIED: [restart ntp] *******************************************************
changed: [c01]

PLAY RECAP ********************************************************************
c01                        : ok=3    changed=2    unreachable=0    failed=0
c02                        : ok=2    changed=0    unreachable=0    failed=0
##### Actual Results:

TASK: [write /etc/ntp] ********************************************************
ok: [c02]
changed: [c01]

NOTIFIED: [restart ntp] *******************************************************
changed: [c01]
changed: [c02]

PLAY RECAP ********************************************************************
c01                        : ok=3    changed=2    unreachable=0    failed=0
c02                        : ok=3    changed=1    unreachable=0    failed=0

**Comment by jimi-c** [comment] 2014-05-28 02:04
This is a duplicate of #7559, so closing this. Thanks!

**Closed as completed by jimi-c** 2014-05-28 02:04 UTC
