### ISSUE TITLE
Cant pass in email address syntax to script or command. Cant esacpe @ char

### ISSUE THREAD

**Issue by stuartruss** [ansible/ansible#11344] opened 2015-06-22 13:39 UTC
IM having an issue where by 

script:  myscript.py --username=xxxx@company.com   --argument2=....

results in 
    myscript.py  --username=   -srgument2=....

the value for the username arguemnt is blank as soon as I place an ampersand. 

Even if I have this as a var 
var1:   username@company.com

and use:     {{var1}}

no amount of single or double quoting allowing the value to be passed onto the remote command or script. 
Im sure that its my mistake however I cannot find any fix for this and any yaml parsers seem to be able to parse the data and leave the @ intact. 
Even adding unicode doesnt seem to work.

**Comment by illogicalextend** [comment] 2015-07-08 02:15
When you say "script:", are you using the shell module? I could try and reproduce if I know enough of what steps you're taking.

**Comment by bcoca** [comment] 2015-07-13 13:12
# Can You Help Us Out?

Thanks for filing a ticket! I am the friendly GitHub Ansibot.

It looks like you might not have filled out the issue description based on our standard issue template.  You might not have known about that, and that's ok too, we'll tell you how to do it.

We have a standard template because Ansible is a really busy project and it helps to have some standard information in each ticket, and GitHub doesn't yet provide a standard facility to do this like some other bug trackers.  We hope you understand as this is really valuable to us!.

Solving this is simple: please copy the contents of this [template](https://raw.githubusercontent.com/ansible/ansible/devel/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket.  That's it!

# If You Had A Question To Ask Instead

If you happened to have a "how do I do this in Ansible" type of question, that's probably more of a user-list question than a bug report, and you should probably ask this question on the project mailing list instead.

However, if you think you have a bug, the report is the way to go!  We definitely want all the bugs filed :)  Just trying to help!

# About Priority Tags

Since you're here, we'll also share some useful information at this time.

In general tickets will be assigned a priority between P1 (highest) and P5, and then worked in priority order. We may also have some follow up questions along the way, so keeping up with follow up comments via GitHub notifications is a good idea.

Due to large interest in Ansible, humans may not comment on your ticket immediately.

# Mailing Lists

If you have concerns or questions, you're welcome to stop by the ansible-project or ansible-development mailing lists, as appropriate.  Here are the links:
- https://groups.google.com/forum/#!forum/ansible-project - for discussion of bugs and how-to type questions
- https://groups.google.com/forum/#!forum/ansible-devel - for discussion on how to implement a code change, or feature brainstorming among developers

Thanks again for the interest in Ansible!

**Comment by jimi-c** [comment] 2015-07-21 02:40
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
# cat test.yml 
- hosts: localhost
  gather_facts: no
  tasks:
  - script: test.sh --username=foo@bar.com
# cat test.sh
#!/bin/sh
while [ "$1" != "" ]; do
    PARAM=`echo $1 | awk -F= '{print $1}'`
    VALUE=`echo $1 | awk -F= '{print $2}'`
    case $PARAM in
        --username)
            USERNAME=$VALUE
            ;;
        *)
            echo "ERROR: unknown parameter \"$PARAM\""
            usage
            exit 1
            ;;
    esac
    shift
done
echo "the username specified is $USERNAME";
# ansible-playbook -vv test.yml
Using /etc/ansible/ansible.cfg as config file
1 plays in test.yml
PLAY ****************************************************************************
TASK [script] *******************************************************************
changed: [localhost] => {"changed": true, "rc": 0, "stderr": "", "stdout": "the username specified is foo@bar.com\n"}
PLAY RECAP **********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0   
</pre>

Per our normal policy, we close bug report issues when we see the issue has been corrected in the devel branch, so we will close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-07-21 02:40 UTC
Labels: needs_info, bug
