### ISSUE TITLE
jinja2_native = True converting the result of the 'template' module to a native data structure

### ISSUE THREAD

**Issue by corbinstuard** [ansible/ansible#53143] opened 2019-02-28 21:09 UTC
##### SUMMARY

If jinja2_native = True is set in ansible.cfg, the template module will always export the data structure per it's native syntax.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```
ansible 2.7.8
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/etc/ansible/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=2000s -o UserKnownHostsFile=/dev/null
ANSIBLE_SSH_CONTROL_PATH(/etc/ansible/ansible.cfg) = /tmp/%%h-%%p-%%r
ANSIBLE_SSH_CONTROL_PATH_DIR(/etc/ansible/ansible.cfg) = /tmp
ANSIBLE_SSH_RETRIES(/etc/ansible/ansible.cfg) = 3
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 5
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = explicit
DEFAULT_JINJA2_NATIVE(/etc/ansible/ansible.cfg) = True
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/modules']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
INVENTORY_IGNORE_EXTS(/etc/ansible/ansible.cfg) = [u'.pyc', u'.pyo', u'.swp', u'.bak', u'~', u'.rpm', u'.md', u'.txt', u'~', u'
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False

```

##### OS / ENVIRONMENT

CentOS 7,6

##### STEPS TO REPRODUCE

Set jinja2_native = True in ansible.cfg

Using the following template:

```yaml
- name: configure hal
  hosts: dps
 
  tasks:
    - copy:
        content: '{{ lookup("template", "dps_default.json.j2") | to_json }}'
        dest: /etc/dvn-dps/dp_default.json
   - copy:
        content: '{{ lookup("template", "dps_default.json.j2") | to_nice_json }}'
        dest: /etc/dvn-dps/dp_default.json
  - name: create dps config file from template
    template:
      src: dps_default.json.j2
      dest: /etc/dvn-dps/dps_default.json
```

Template:
```jinja2
{
  "dps_config": {
       "customer_id":"{{ customer_id }}",
       "db_name":"dvn",
       "db_pass":"NULL",
       "dps_id":"{{ inventory_hostname }}",
       "client_port":"{{ client_port }}",
       "admin_port":"{{ admin_port }}",
       "reg_port":"{{ reg_port }}",
       "db_port2":"3306",
       "db_remote":"no",
       "db_remote_ip":"127.0.0.1",
       "db_remote_port":"0",
       "dps_vtc_max":"20000",
{% if groups.hal|length > 0 %}
       "hal_db_name":"hal{{ groups.dps.index(inventory_hostname) + 1 }}",
       "hal_db_pass":"NULL",
       "hal_db_remote":"yes",
       "hal_db_remote_ip":"{{ hostvars[groups['hal'][0]].network[0].ipv4[0].ip }}",
       "hal_db_remote_port":"3306",
{% else %}
       "hal_db_name":"",
       "hal_db_pass":"NULL",
       "hal_db_remote":"no",
       "hal_db_remote_ip":"",
       "hal_db_remote_port":"",
{% endif %}
       "db_ssl":"no",
       "db_client_key":"",
       "db_client_cert":"",
       "db_ca_cert":"",
       "db_ssl_cipher":"",
       "hal_db_ssl":"no",
       "hal_db_client_key":"",
       "hal_db_client_cert":"",
       "hal_db_ca_cert":"",
       "hal_db_ssl_cipher":"",
       "web_cli_enabled":"yes",
       "web_cli_port":"8181"
  }
}
```
Task 1/2 results in:
```json
'{
  "dps_config": {
       "customer_id":"12345678",
       "db_name":"dvn",
       "db_pass":"NULL",
       "dps_id":"dps1-test",
       "client_port":"49001",
       "admin_port":"49011",
       "reg_port":"49012",
       "db_port2":"3306",
       "db_remote":"no",
       "db_remote_ip":"127.0.0.1",
       "db_remote_port":"0",
       "dps_vtc_max":"20000",
       "hal_db_name":"hal1",
       "hal_db_pass":"NULL",
       "hal_db_remote":"yes",
       "hal_db_remote_ip":"192.168.2.40",
       "hal_db_remote_port":"3306",
       "db_ssl":"no",
       "db_client_key":"",
       "db_client_cert":"",
       "db_ca_cert":"",
       "db_ssl_cipher":"",
       "hal_db_ssl":"no",
       "hal_db_client_key":"",
       "hal_db_client_cert":"",
       "hal_db_ca_cert":"",
       "hal_db_ssl_cipher":"",
       "web_cli_enabled":"yes",
       "web_cli_port":"8181"
  }
}'
```
Task 3 results in: 
```python
{'dps_config': {'hal_db_remote': 'yes', 'hal_db_client_key': '', 'web_cli_port': '8181', 'hal_db_remote_ip': '192.168.2.40', 'db_client_cert': '', 'customer_id': '12345678', 'hal_db_remote_port': '3306', 'hal_db_name': 'hal1', 'db_pass': 'NULL', 'db_client_key': '', 'admin_port': '49011', 'db_ssl_cipher': '', 'db_ssl': 'no', 'db_remote_ip': '127.0.0.1', 'client_port': '49001', 'db_name': 'dvn', 'hal_db_ssl': 'no', 'hal_db_ssl_cipher': '', 'db_ca_cert': '', 'hal_db_client_cert': '', 'reg_port': '49012', 'db_port2': '3306', 'web_cli_enabled': 'yes', 'db_remote_port': '0', 'hal_db_ca_cert': '', 'hal_db_pass': 'NULL', 'dps_id': 'dps1-test', 'db_remote': 'no', 'dps_vtc_max': '20000'}}
```

##### EXPECTED RESULTS
Template module to properly output a string despite DEFAULT_JINJA2_NATIVE = True

**Comment by sivel** [comment] 2019-02-28 21:28
Duplicate of https://github.com/ansible/ansible/issues/46169

**Closed as completed by sivel** 2019-02-28 21:28 UTC

**Comment by corbinstuard** [comment] 2019-02-28 21:31
@sivel That issue is closed, and so is the upstream one with Jinja2. Where is the open bug in either project to fix this issue?

**Comment by sivel** [comment] 2019-02-28 21:32
#46169 is still open.
