### ISSUE TITLE
include: an include_role: executes number of hosts times

### ISSUE THREAD

**Issue by etcmorph** [ansible/ansible#22071] opened 2017-02-28 11:00 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
include_role

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
Red Hat EL7

##### SUMMARY
include_role: executes an incorrect number of times. It seems to execute the number of hosts times, in the case where I include: a playbook that uses include_role: and the role name is determined by a variable.

I found a similar sounding issue https://github.com/ansible/ansible/issues/21279 but was unsure if it was the same root cause.

##### STEPS TO REPRODUCE
```
ansible-playbook include_play.yml
```

roles/test_role/tasks/main.yml
```yaml
- debug: msg="{{myrole}},{{ansible_host}}"
```
play.yml
```yaml
- name: test play
  hosts: all
  gather_facts: False
  tasks:
    - include_role:
        name: "{{myrole}}"
```
include_play.yml
```yaml
- include: play.yml myrole=test_role
```

##### EXPECTED RESULTS
```
PLAY [test play] ***************************************************************

TASK [test_role : debug] *******************************************************
ok: [host1] => {
    "msg": "test_role,host1"
}
ok: [host2] => {
    "msg": "test_role,host2"
}

PLAY RECAP *********************************************************************
host1                      : ok=1    changed=0    unreachable=0    failed=0
host2                      : ok=1    changed=0    unreachable=0    failed=0

```

##### ACTUAL RESULTS

```
PLAY [test play] ***************************************************************

TASK [include_role] ************************************************************

TASK [test_role : debug] *******************************************************
ok: [host1] => {
    "msg": "test_role,host1"
}
ok: [host2] => {
    "msg": "test_role,host2"
}

TASK [test_role : debug] *******************************************************
ok: [host1] => {
    "msg": "test_role,host1"
}
ok: [host2] => {
    "msg": "test_role,host2"
}

PLAY RECAP *********************************************************************
host1                      : ok=2    changed=0    unreachable=0    failed=0
host2                      : ok=2    changed=0    unreachable=0    failed=0

```

If I increase the number of hosts to 3, it executes 3 times on each host.
If I use --extra-vars="myrole=test_role" to override the include parameter,
it only executes once per host as expected, as does setting play vars
of "myrole: test_role".

**Comment by abadger** [comment] 2017-03-01 18:19
@bcoca

**Comment by bcoca** [comment] 2017-03-03 20:17
Dupe of #21279

**Closed as completed by bcoca** 2017-03-03 20:17 UTC
Labels: affects_2.2, module, bug
