### ISSUE TITLE
module.fail_json(**result) doesn't return failed:true 

### ISSUE THREAD

**Issue by yassinehamzaoui** [ansible/ansible#83531] opened 2024-07-04 09:25 UTC
### Summary

I'm working with the python ansible module to create my own module inside my role, the new custom module named vmware_info to grab information from vcenter is working fine but i have a strange behavior when i have an error in the execution the  **`module.fail_json(**result)`**  should return error message and also the attribute failed as True instead i got failed as False.
Even with a force to put the true like this **`result['failed'] = True`** it still giving the **false** value.

### Issue Type

Bug Report

### Component Name

module.fail_json()

### Ansible Version

```console
$ ansible --version
ansible [core 2.15]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.16 (main, May 31 2023, 12:21:58) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)]
  jinja version = 3.0.3
  libyaml = True

Additional information about the EE : 
ansible-core-2.13.10-1.el8ap.x86_64
ansible-lint-6.0.2-3.el8ap.noarch
ansible-runner-2.2.2-1.el8ap.noarch
ansible-test-2.13.10-1.el8ap.x86_64
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

RHEL 8

### Steps to Reproduce

```yaml (paste below)
    try:
        content = connect_to_vcenter(hostname, username, password, validate_certs)
        vm_info_list = gather_vm_info(content, customer, hostname)
        result['vm_info_list'] = vm_info_list
    except Exception as e:
        result['failed'] = True
        result['msg'] = str(e)
        module.fail_json(**result)

    module.exit_json(**result)

```

### Expected Results

```
{
  "msg": {
    "error": "Failed to connect to vCenter: (vim.fault.InvalidLogin) {\n   dynamicType = <unset>,\n   dynamicProperty = (vmodl.DynamicProperty) [],\n   msg = 'Cannot complete login due to an incorrect user name or password.',\n   faultCause = <unset>,\n   faultMessage = (vmodl.LocalizableMessage) []\n}",
    "failed": true,
    "changed": false
  },
  "_ansible_verbose_always": true,
  "_ansible_no_log": null,
  "changed": false
}
```

### Actual Results

```console
{
  "msg": {
    "error": "Failed to connect to vCenter: (vim.fault.InvalidLogin) {\n   dynamicType = <unset>,\n   dynamicProperty = (vmodl.DynamicProperty) [],\n   msg = 'Cannot complete login due to an incorrect user name or password.',\n   faultCause = <unset>,\n   faultMessage = (vmodl.LocalizableMessage) []\n}",
    "failed": false,
    "changed": false
  },
  "_ansible_verbose_always": true,
  "_ansible_no_log": null,
  "changed": false
}
```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by yassinehamzaoui** [comment] 2024-07-04 09:26
Last issue was closed without a valid justification this is an "**issue**" please take it in consideration

**Comment by mkrizek** [comment] 2024-07-04 09:41
Duplicate of #83524 

Please see https://github.com/ansible/ansible/issues/83524#issuecomment-2208524314, thanks!

If you have further questions please stop by IRC or the mailing list:
* IRC: #ansible on [irc.libera.chat](https://libera.chat/)
* mailing list: https://groups.google.com/forum/#!forum/ansible-project

See  this page for a complete and up to date list of communication channels and their purposes:

* https://docs.ansible.com/ansible/latest/community/communication.html

**Closed as completed by mkrizek** 2024-07-04 09:41 UTC
Labels: bug
