### ISSUE TITLE
when conditional fails on string variable

### ISSUE THREAD

**Issue by marcinhlybin** [ansible/ansible#41236] opened 2018-06-07 09:08 UTC
##### SUMMARY
I often initialize variables with null values to avoid undefined errors. I check if variable is null with when conditional `when: variable_name`. 

However when variable is a string Ansible returns error. See STEPS TO REPRODUCE for details on error. I figured out workaround by adding  `( )` or `default()` filter.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Ansible

##### ANSIBLE VERSION
```
ansible 2.5.4
  config file = None
  configured module search path = [u'/Users/ahes/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /private/tmp/ansible/venv/lib/python2.7/site-packages/ansible
  executable location = /private/tmp/ansible/venv/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### CONFIGURATION
Defaults

##### OS / ENVIRONMENT
Mac OS X

##### STEPS TO REPRODUCE
playbook.yml:

```yaml
- hosts: localhost
  become: false
  gather_facts: false
  vars:
    a: hello
  tasks:
    - name: Returns ERROR
      debug:
        msg: Hello World!
      ignore_errors: true
      when: a

    - name: Works fine
      debug:
        msg: Hello World!
      when: (a)

    - name: Works fine
      debug:
        msg: Hello World!
      when: a | default()

    - name: Works fine
      debug:
        msg: Hello World!
      when: a is defined
```

##### EXPECTED RESULTS
When condition should pass.

##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'a' failed. The error was: error while evaluating conditional (a): 'hello' is undefined\n\nThe error appears to have been in '/private/tmp/ansible/playbook.yml': line 8, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - name: Returns ERROR\n      ^ here\n"}
```

**Comment by sivel** [comment] 2018-06-07 14:19
Ultimately this is a duplicate of https://github.com/ansible/ansible/issues/34591

See the description at https://github.com/ansible/ansible/issues/34591#issuecomment-356081973

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Closed as completed by sivel** 2018-06-07 14:19 UTC
Labels: support:core, affects_2.5, bug
