### ISSUE TITLE
include_vars: foo.yml within a role no longer overrides roles/a/vars/main.yml

### ISSUE THREAD

**Issue by dstillman** [ansible/ansible#9498] opened 2014-11-06 09:41 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

8a1fbed5d6a61583950024df60ac74d5c98d6cca and later
##### Environment:

Amazon Linux AMI release 2014.09
##### Summary:

include_vars: foo.yml within a role no longer overrides variables set in roles/a/vars/main.yml
##### Steps To Reproduce:

main.yml:

```
- hosts: 127.0.0.1
  roles:
    - role: a
```

roles/a/vars/main.yml:

```
foo: BAD
```

roles/a/vars/foo.yml:

```
foo: GOOD
```

roles/a/tasks/main.yml:

```
- include_vars: foo.yml

- debug: var=foo

- assert: { that: "foo == 'GOOD'" }
```
##### Expected Results:

`foo` should be set to 'GOOD' because of the foo.yml include. This is the case in both 1.5.0 and 1.7.2.
##### Actual Results:

`foo` is set to 'BAD' in 8a1fbed5d6a61583950024df60ac74d5c98d6cca and up.

**Comment by jimi-c** [comment] 2014-11-17 21:55
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by dstillman** [comment] 2015-08-18 20:00
This appears to be broken again on devel:

```
ansible 2.0.0 (devel 5eeeb87d82) last updated 2015/08/18 13:13:57 (GMT -400)
  lib/ansible/modules/core: (detached HEAD dea5f5d15e) last updated 2015/08/18 15:45:23 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 210ee3febc) last updated 2015/08/18 15:45:23 (GMT -400)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/08/18 14:59:01 (GMT -400)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/08/18 14:59:03 (GMT -400)
```

**Comment by jimi-c** [comment] 2015-08-21 13:59
@dstillman I see where the problem is, and will have a patch merged in shortly.

**Comment by jimi-c** [comment] 2015-08-21 16:27
Fixed per the above commit.

**Closed as completed** 2015-08-21 16:26 UTC
Labels: P1, bug
