### ISSUE TITLE
[fetch module] home directories are expanded from control machine not managed machines

### ISSUE THREAD

**Issue by tahajahangir** [ansible/ansible#8942] opened 2014-09-09 15:50 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.1 / develop
##### Environment:

Running OS: Ubuntu 14.04
Managed OS: Debian 6 / FreeBSD 10 / Ubuntu 14.04 / CentOS 7 (I think this is a generic bug)
##### Summary:

This is a valid task:

``` yaml
- name: create .ssh directory
  file: dest=~user/.ssh state=directory mode=0700 owner=user group=user
```

But this does not work:

``` yaml
- name: fetching private keys
  fetch: src="~user/.ssh/id_rsa.pub" dest=dir
```

I found the ability to use `~user` directory paths from [this mailing list post](https://groups.google.com/forum/m/#!topic/ansible-project/f8V5V5B3-Vg)
##### Steps To Reproduce:

This is reproducalbe with trivial play book like: (assuming a `user` exists with id_res.pub file in his .ssh directory and the managed hosts are sshed with `root` user.)

``` yaml
- hosts: all
  tasks:
    - name: fetching private keys
      fetch: src=~user/.ssh/id_rsa.pub dest=directory
```
##### Expected Results:

The file should be fetched in destination directory (`directory`)
##### Actual Results:

The task fails with this error:

```
TASK: [fetching private keys] ************************************************* 
failed: [hostname] => {"failed": true, "file": "~user/.ssh/id_rsa.pub"}
msg: the remote file does not exist
```

**Comment by mscherer** [comment] 2014-09-10 08:55
For the record, I cannot reproduce on latest HEAD. Can you try with a newer snapshot and report ?

**Comment by tahajahangir** [comment] 2014-09-11 05:16
I tested with HEAD (ansible 1.8), and problem reamins. The problem also exists in Ubuntu 14.04 and CentOS 7 (as managed host).

After some tests, I noticed that `~user` works only for certains users (such as root).

part of /etc/passwd file:

```
root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/bin:/sbin/nologin
daemon:x:2:2:daemon:/sbin:/sbin/nologin
adm:x:3:4:adm:/var/adm:/sbin/nologin
sync:x:5:0:sync:/sbin:/bin/sync
shutdown:x:6:0:shutdown:/sbin:/sbin/shutdown
ntp:x:38:38::/etc/ntp:/sbin/nologin
```

and result of requesting a non-existant file `foobar` from each user's home:

```
$ ansible centos7server -m fetch -a "src=\"~root/foobar\" dest=test flat=yes fail_on_missing=yes"
centos7server | FAILED >> {
    "failed": true, 
    "file": "/root/foobar", 
    "msg": "the remote file does not exist"
}

$ ansible centos7server -m fetch -a "src=\"~bin/foobar\" dest=test flat=yes fail_on_missing=yes"
centos7server | FAILED >> {
    "failed": true, 
    "file": "/bin/foobar", 
    "msg": "the remote file does not exist"
}

$ ansible centos7server -m fetch -a "src=\"~daemon/foobar\" dest=test flat=yes fail_on_missing=yes"
centos7server | FAILED >> {
    "failed": true, 
    "file": "/usr/sbin/foobar", 
    "msg": "the remote file does not exist"
}

$ ansible centos7server -m fetch -a "src=\"~adm/foobar\" dest=test flat=yes fail_on_missing=yes"
centos7server | FAILED >> {
    "failed": true, 
    "file": "~adm/foobar", 
    "msg": "the remote file does not exist"
}

$ ansible centos7server -m fetch -a "src=\"~sync/foobar\" dest=test flat=yes fail_on_missing=yes"
centos7server | FAILED >> {
    "failed": true, 
    "file": "/bin/foobar", 
    "msg": "the remote file does not exist"
}

$ ansible centos7server -m fetch -a "src=\"~shutdown/foobar\" dest=test flat=yes fail_on_missing=yes"
centos7server | FAILED >> {
    "failed": true, 
    "file": "~shutdown/foobar", 
    "msg": "the remote file does not exist"
}

$ ansible centos7server -m fetch -a "src=\"~ntp/foobar\" dest=test flat=yes fail_on_missing=yes"
centos7server | FAILED >> {
    "failed": true, 
    "file": "~ntp/foobar", 
    "msg": "the remote file does not exist"
}
```

note that is some cases `~usr` is not expanded.

**Comment by tahajahangir** [comment] 2014-09-11 17:51
I found the bug! the users' home directory has been read from the node running the ansible (my computer!), NOT the managed hosts!

This is the `passwd` file in my own OS (ubuntu 14.04)

```
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
```

This is totally compatible with the results in previous note.

**Comment by jimi-c** [comment] 2014-09-23 20:34
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed** 2014-09-23 20:34 UTC
Labels: P2, bug
