### ISSUE TITLE
--limit no longer implicitly includes localhost

### ISSUE THREAD

**Issue by jbscare** [ansible/ansible#17105] opened 2016-08-16 15:37 UTC
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

Not sure about the component name -- whatever handles '--limit'.
##### ANSIBLE VERSION

```
ansible 2.1.1.0 (czen-2.1.1.0-1 607e86423a) last updated 2016/08/15 22:29:13 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 6b0588bd2c) last updated 2016/08/15 22:29:21 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 45e44f2f10) last updated 2016/08/10 17:49:33 (GMT -400)
  config file = /home/jsmift/ansible/dom/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

transport = ssh
private_key_file = /home/ansible/.ssh/id_rsa
remote_user = ansible
log_path = ../logs/ansible.log
ansible_managed = ansible managed via {host}
legacy_playbook_variables = no
host_key_checking = False
system_warnings = False
vault_password_file = /home/ansible/.vault-passfile
forks=20
retry_files_enabled = False
##### OS / ENVIRONMENT

Amazon Linux AMI release 2015.09 and 2016.03
##### SUMMARY

In Ansible 1.9, --limit implicitly included localhost; it seems not to any more.
##### STEPS TO REPRODUCE

This playbook:

```
- hosts: localhost 
  gather_facts: False 
  tasks: 
  - name: date on localhost 
    command: /bin/date 

- hosts: all 
  gather_facts: False 
  tasks:    
  - name: date on other hosts 
    command: /bin/date 
```

These commands:

```
ansible-playbook localhost.yml --limit host-01
ansible-playbook localhost.yml --limit host-0:localhost
```

And:

```
ansible-playbook localhost.yml --limit host-01 --list-hosts
ansible-playbook localhost.yml --limit host-01:localhost --list-hosts
```
##### EXPECTED RESULTS

I expected each command in the pair to produce the same results, i.e. to include localhost, like they did in Ansible 1.9.
##### ACTUAL RESULTS

The results of 'ansible-playbook localhost.yml --limit host-01' don't include localhost:

```
PLAY [all] *********************************************************************

TASK [date on other hosts] *****************************************************
changed: [host-01]
```

The results of 'ansible-playbook localhost.yml --limit host-0:localhost' do include localhost:

```
PLAY [localhost] ***************************************************************

TASK [date on localhost] *******************************************************
changed: [localhost]

PLAY [all] *********************************************************************

TASK [date on other hosts] *****************************************************
changed: [localhost]
changed: [host-01]
```

The results of 'ansible-playbook localhost.yml --limit host-01 --list-hosts' don't include localhost:

```
playbook: /home/jsmift/ansible/dom/playbooks/localhost.yml

  play #1 (localhost): localhost        TAGS: []
  pattern: [u'localhost']
  hosts (0):

  play #2 (all): all    TAGS: []
  pattern: [u'all']
  hosts (1):
    host-01
```

The results of 'ansible-playbook localhost.yml --limit host-01:localhost --list-hosts' do include localhost:

```
Executing ansible-playbook /home/jsmift/ansible/dom/playbooks/localhost.yml --limit host-01:localhost --list-hosts

playbook: /home/jsmift/ansible/dom/playbooks/localhost.yml

  play #1 (localhost): localhost        TAGS: []
  pattern: [u'localhost']
  hosts (1):
    localhost

  play #2 (all): all    TAGS: []
  pattern: [u'all']
  hosts (2):
    localhost
  host-01
```

**Comment by jbscare** [comment] 2016-08-16 15:38
https://groups.google.com/forum/#!topic/ansible-devel/vKtVvD_AosM also brought this up on ansible-devel, but no one replied there.

If it would help, I can probably rig things up to demonstrate the 1.9 behavior.

**Comment by robinro** [comment] 2016-08-25 17:49
The implicit inclusion of localhost might lead to problems with ansible-pull, see https://github.com/ansible/ansible/issues/13681. Please ensure to not regress there.

I also feel that is better design to explicitly require localhost in inventory/limit as in 2.0. Changing that behavior might break existing 2.0 uses, where using limit was used to exclude localhost.

**Comment by bcoca** [comment] 2016-08-26 13:15
dupe of #17012

**Closed as completed by bcoca** 2016-08-26 13:15 UTC
Labels: bug

**Comment by jbscare** [comment] 2016-08-30 16:57
This isn't a dupe of #17012 -- I created this one specifically because I realized that #17012 was describing a different problem.

**Comment by rangsan** [comment] 2017-06-22 04:30
I also got this problem too. When I use limit option (--limit ), the localhost does not match in the inventory but it work when I run without limit. Can someone please shed me the light ? Thanks
