### ISSUE TITLE
role dependencies: condition issue

### ISSUE THREAD

**Issue by hryamzik** [ansible/ansible#10168] opened 2015-02-05 11:32 UTC
I have a variable `hbase_standalone` that's set to `false` in defaults but for my current host it's `true`. And here's how my dependencies look like:

```
dependencies:
  - { role: hadoop, when: not hbase_standalone }
  - { role: oracle-jdk }
```

So `hadoop` role is not included, that's fine, but `oracle-jdk` is also ignored! Works fine if I change the order though:

```
dependencies:
  - { role: oracle-jdk }
  - { role: hadoop, when: not hbase_standalone }
```

Mac OS, ansible 1.8.1.

**Comment by bcoca** [comment] 2015-02-05 11:45
in the hadoop role, is oracle-jdk set as a dependency?

## 

Brian Coca

**Comment by hryamzik** [comment] 2015-02-05 12:02
@bcoca, good point, it is.

**Comment by bcoca** [comment] 2015-02-09 14:36
so I expect this behavior if you are preventing duplicate invocation of roles, closing this as it is not a bug and it can be controlled by ordering the dependencies.

**Closed as completed by bcoca** 2015-02-09 14:36 UTC
Labels: bug

**Comment by hryamzik** [comment] 2015-02-09 14:55
- hadoop requires java
- hbase requires java
- hbase could be installed standalone
- hadoop could be installed standalone
- non-standalone hbase requires hadoop and java

How should I write these dependencies?

**Comment by bcoca** [comment] 2015-02-09 15:21
@hryamzik as you did when openning the ticket (the working example), put the common dependency on top

**Comment by hryamzik** [comment] 2015-02-11 09:19
@bcoca, is this documented? Also, will [allow_duplicates](http://docs.ansible.com/playbooks_roles.html#role-dependencies) solve the issue?

**Comment by bcoca** [comment] 2015-02-11 13:53
I believe this is expected behavior when not allowing duplicates. I don't
know that it is explicitly documented as a case, but I found it an obvious
consequence.

## 

Brian Coca
