### ISSUE TITLE
lineinfile & tab character

### ISSUE THREAD

**Issue by faust64** [ansible/ansible#4818] opened 2013-11-06 07:28 UTC
Hi,
#4710 has been closed but not solved.

Using \t don't print a tab character.

In 1.3.1, then 1.3.4 from pip.

Regards.

**Comment by jctanner** [comment] 2013-11-06 14:19
@faust64 is this the task that is causing an error? ...

```
name: patch unbound init script (deb)
lineinfile: dest=/etc/init.d/unbound regexp='if ps ax | grep' line=" if ps ax | grep in/u[n]bound >/dev/null; then"
```

**Comment by faust64** [comment] 2013-11-06 20:53
Yes indeed.
The following produces a syntax error:
  lineinfile: dest=/etc/init.d/unbound regexp='if ps ax | grep' line='  if ps ax | grep "in/u[n]bound" >/dev/null; then'

While using \t, I actually have '\' and 't' chars:.
  lineinfile: dest=/etc/init.d/unbound regexp='if ps ax | grep' line="\tif ps ax | grep 'in/u[n]bound' >/dev/null; then"

**Comment by hyphen-jb** [comment] 2013-11-13 23:38
Using 1.3.2,  "\t" properly expanded only when I double-quoted the entire parameter line:

```
- lineinfile: "dest=/etc/init.d/unbound regexp='if ps ax | grep' line='\tif ps ax | grep in/u[n]bound >/dev/null; then'"
```

However I am fond of the readability from having each task parameter on a separate line.  Which means "\t" does not expand properly.  So I end up doing things like:

```
- lineinfile: 
    dest=/etc/init.d/unbound
    regexp='if ps ax | grep'
    line="{{'\t'}}if ps ax | grep 'in/u[n]bound' >/dev/null; then"
```

I was unclear if the single quotes in your final grep were desired.

I wouldn't say this bug is resolved, but it might be good to start over with a clearer premise and simpler test case(s) in a playbook.

**Comment by DaveQB** [comment] 2014-01-24 06:30
Brilliant. Thanks for the solution using the double quotes.

This page mentions the need for double quotes over the entire line due to a colon
http://docs.ansible.com/lineinfile_module.html

It says to refer to the Gotcha section in the YAML docs (no link on the page).

I found the referenced page here:
http://docs.ansible.com/YAMLSyntax.html#gotchas

But it does not mention any issues with \t (TAB) characters.
Perhaps it should be added.

**Comment by hyphen-jb** [comment] 2014-01-28 05:12
I don't know if the \t (TAB) expansion problem is a bug or just needs to documented as a gotcha.

If not fully quoting is a common mistake, an anti-example should be added to lineinfile_module.html
I also made a subtle change in the comment on Fully quoted.

```
# Add a line to a file if it does not exist, without passing regexp
- lineinfile: dest=/tmp/testfile line="192.168.1.99 foo.lab.net foo"

# Fully quoted line because of the ': '. See the Gotchas in the YAML docs.
- lineinfile: "dest=/etc/sudoers state=present regexp='^%wheel' line='%wheel ALL=(ALL) NOPASSWD: ALL'"
```

Anti-Example:

```
# Partially quoted line that does not hide the ': ' from the YAML parser, so it breaks.
- lineinfile: dest=/etc/sudoers state=present regexp='^%wheel' "line='%wheel ALL=(ALL) NOPASSWD: ALL'"
```

The YAMLSyntax.html#gotchas is a bit sparse.  If I have time to verify against current, I'll add a documentation issue on YAML problems I've had in the past.

**Comment by jimi-c** [comment] 2014-02-10 22:31
So, after reading through this, it sounds like this is a documentation issue and not a bug. @hyphen-jb , could you send us a PR for the above doc changes so that you get proper attribution? Beyond that, I'm going to go ahead and close this. If you have any further questions regarding this, please let us know. Thanks!

**Closed as completed by jimi-c** 2014-02-10 22:31 UTC
Labels: bug

**Comment by naoko** [comment] 2015-08-19 17:09
thank you @hyphen-jb, the solution worked perfectly!
