### ISSUE TITLE
Fact Caching is not working with Redis

### ISSUE THREAD

**Issue by kevintsai** [ansible/ansible#12019] opened 2015-08-20 07:59 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

1.9.1
##### Environment:

Host: MacOS 10.10.3 / Installed ansible 1.9.1 and redis 2.8.17 by Port. 
Target: CentOS 6.6
##### Steps To Reproduce:
- Enable the Redis server.
- The settings in ansible.cfg file:

``` ini
gathering = smart
fact_caching = redis
```
- Check Redis from Python

``` shell
$ python --version
Python 2.7.6
$ python -c "import redis ; print 'ok'"
ok
```
- The response when run the ansible-playbook try to deploy.

``` shell
The 'redis' python module is required, 'pip install redis'
```
##### Summary:

After upgraded Ansible to version 1.9.1, 
When enabled the Fact-caching with Redis. [1](http://docs.ansible.com/ansible/playbooks_variables.html#fact-caching)
The ansible-playbook seems not working with Redis.

The host environment was working on Ansible v1.9.0.

**Comment by jimi-c** [comment] 2015-08-28 15:44
Hi @KevinTsai, could you test this against 1.9.2 and/or devel to see if the problem continues to persist? The code actually runs `from redis import StrictRedis` to determine if the redis module is available, so perhaps they've changed that in the redis lib?

**Comment by toshywoshy** [comment] 2015-09-05 12:32
Tested and working against devel 70677b030bab1d397774c883523a644bdf4e1f90 with python-redis 2.10.3 and redis-3.0.3

**Comment by jimi-c** [comment] 2015-09-07 07:08
Great, as it is our policy to close github issues when the problem is resolved in devel, I'll go ahead and close this now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-09-07 07:08 UTC
Labels: needs_info, bug

**Comment by sortega** [comment] 2016-02-05 10:15
Hello, this is happening to me with a more recent version of ansible.

``` console
$ ansible --version                                         
ansible 1.9.3
  configured module search path = None
$ python -c "import redis ; print 'ok'"                                   
ok
$ ansible-playbook testset.yml --dry-run
The 'redis' python module is required, 'pip install redis'
```

Do you know what could be the problem?

**Comment by jimi-c** [comment] 2016-02-05 20:42
@sortega this has been corrected in devel/2.0, however if you see my above example it's actually a different class being imported from the redis library, so ensure that the above condition is met as well.

**Comment by jimi-c** [comment] 2016-02-05 20:43
If you continue seeing issues with this, please open a new issue rather than continuing to comment here.

Thanks!

**Comment by sortega** [comment] 2016-02-08 08:30
Is there any workaround for version 1.9.3? I cannot unilaterally use 2.0 at my company.

Thanks in advance

**Comment by jimi-c** [comment] 2016-02-08 16:06
@sortega can you share what you see when you import the correct StrictRedis import? That may provide a clue as to why. Otherwise, there was no patch to address this as far as I can see.

**Comment by sortega** [comment] 2016-02-09 08:22
@jimi-c. What do you mean by correct StrictRedis?

``` console
$ python
Python 2.7.10 (default, Sep 23 2015, 04:34:14)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from redis import StrictRedis
>>>
```

I don't see any error when importing StrictRedis.

**Comment by jimi-c** [comment] 2016-02-15 21:41
@sortega what you showed there is what I expect. So it does not appear that this is the same issue as the one above, and you should open a new issue. Thanks!
