### ISSUE TITLE
unarchive leaves archive on remote machine in /$USER/.ansible/tmp

### ISSUE THREAD

**Issue by dfaltyn** [ansible/ansible#14878] opened 2016-03-09 10:12 UTC
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible 2.0.1.0
##### Ansible Configuration:

export ANSIBLE_VAULT_PASSWORD_FILE=~/.ansible/.vault_pass
export ANSIBLE_SCP_IF_SSH=y
##### Environment:

Centos 7 3.10.0-327.3.1.el7.x86_64
##### Summary:

The unarchive task leaves the archive in /$USER/.ansible/tmp on a remote machine, after the playbook completes.
##### Steps To Reproduce:

Create a playbook which execute unarchive on a remote host, when the archive exists on the localhost.

1) Download the sample from https://github.com/dfaltyn/ansible-unarchive-error
2) Edit the inventory file "dev" to include an accessible host. In this example "coffeecup"
3) modify the other_host variable to the host or group added to the inventory file dev.
3) Execute the playbook  ansible-playbook -i dev -u root -k archive-issue.yml --extra-vars="other_host=coffeecup"

---
- hosts: 127.0.0.1
  tasks:
  - name: Createa dummy file
    file:
      path: /tmp/test.txt
      state: touch
  - name: Archive the dummy file
    command: "tar -pczf /tmp/test.tar.gz /tmp/test.txt"
    args:
      chdir: /tmp
- hosts: "{{ other_host }}"
  tasks:
  - name: Unarchive the pushed shib archive
    unarchive:
      src: "/tmp/test.tar.gz"
      dest: /tmp/
      owner: root
      group: root
##### Expected Results:

Nothing should be in /$USER/tmp/.ansible on the remote host at the end of the play
##### Actual Results:

 /$USER/tmp/.ansible contains a directory ansible-tmp-XXXXXXX.XX-XXXXXX with a file named "source" which is the compress archive.

**Comment by bcoca** [comment] 2016-03-09 15:16
dupe of #14867

**Closed as completed** 2016-03-09 15:18 UTC
Labels: m:unarchive

**Comment by dfaltyn** [comment] 2016-03-09 15:31
Thank you.
