### ISSUE TITLE
Why inventory file vars has higher precedence than playbook group_vars/all?

### ISSUE THREAD

**Issue by GoodHaHa** [ansible/ansible#18058] opened 2016-10-16 16:42 UTC
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

N/A
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

and

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o override
```
##### OS / ENVIRONMENT

Ubuntu
##### SUMMARY

inventory group_vars/<group> ---- "group" has highest precedence than inventory vars  and other group
##### STEPS TO REPRODUCE

Here is a simple repro. Create a file structure like this:

```
├── group_vars
│   ├── all
│   └── ansible_test
├── hosts
│   └── inventory_test
└── playbook_var.yaml
```

```
# cat hosts/inventory_test 
[ansible_test:children]
group1
group2

[group1]
10.15.222.207

[group2]
10.15.222.208
10.15.222.209

[ansible_test:vars]
vars_test="in inventory"

[group1:vars]
vars_test="in group1"

```

```
# cat group_vars/ansible_test 

---

vars_test: "in group_all/ansible_test"
```

```
# cat playbook_var.yaml 

---

- hosts: ansible_test                                                                                                                    
  tasks: 
    - debug: msg="{{ vars_test }}"

```

Run playbook_var.yaml  with this inventory:

```
#ansible-playbook --limit=ansible_test -i hosts/inventory_test playbook_var.yaml
```

##### EXPECTED RESULTS

```
ok: [10.15.222.208] => {
    "msg": "in inventory"
}
ok: [10.15.222.207] => {
    "msg": "in group1"
}
ok: [10.15.222.209] => {
    "msg": "in inventory"
}
```
##### ACTUAL RESULTS

```
TASK [debug] *******************************************************************
ok: [10.15.222.207] => {
    "msg": "in group_all/ansible_test"
}
ok: [10.15.222.208] => {
    "msg": "in group_all/ansible_test"
}
ok: [10.15.222.209] => {
    "msg": "in group_all/ansible_test"
}
```

**Comment by Sodki** [comment] 2016-10-17 13:52
The structure that you have doesn't seem to be correct according to Ansible devs. Can you try again, but with the following structure?

```
├── hosts
│   └── inventory_test
│   └── group_vars
│      ├── all
│      └── ansible_test
└── playbook_var.yaml
```

**Comment by bcoca** [comment] 2016-10-17 18:56
actually both structures are correct, but I see no bug, this follows expected rules: http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

as such, closing this as it is not a bug but expected and documented behavior.

**Closed as completed by bcoca** 2016-10-17 18:56 UTC

**Comment by GoodHaHa** [comment] 2016-10-19 08:04
```
├── hosts
│   └── inventory_test
│   └── group_vars
│      ├── all
│      └── ansible_test
└── playbook_var.yaml
```

I try, but get the same result:

```
[root@mesos]# ansible-playbook --limit=ansible_test -i hosts/inventory_test playbook_var.yml 

PLAY [ansible_test] ************************************************************

TASK [setup] *******************************************************************
ok: [10.15.222.209]
ok: [10.15.222.208]
ok: [10.15.222.207]

TASK [debug] *******************************************************************
ok: [10.15.222.207] => {
    "msg": "in group_all/ansible_test"
}
ok: [10.15.222.208] => {
    "msg": "in group_all/ansible_test"
}
ok: [10.15.222.209] => {
    "msg": "in group_all/ansible_test"
}

PLAY RECAP *********************************************************************
10.15.222.207              : ok=2    changed=0    unreachable=0    failed=0   
10.15.222.208              : ok=2    changed=0    unreachable=0    failed=0   
10.15.222.209              : ok=2    changed=0    unreachable=0    failed=0 
```

**Comment by GoodHaHa** [comment] 2016-10-19 08:13
Is document wrong? The results showed that the actual order of precedence:
- playbook group_vars/group
- inventory vars 
- playbook group_vars/all

**Comment by bcoca** [comment] 2016-10-19 15:32
In your last configuration, none are playbook, they are all inventory, but still same issue (from low to high):
- inventory file vars
- inventory group_vars/all
- inventory group_vars/rest

What is happening is that you are defining vars in the inventory file and they are getting overridden by inventory group_vars/all, which is expected, if you move group_vars to be playbook adjacent, the same result is also expected.

**Comment by GoodHaHa** [comment] 2016-10-20 04:03
Thinks very much. I tested it again, but I get (from low to high):
- inventory group_vars/all 
- inventory file vars
- inventory group_vars/rest

### structure

```
├── hosts
│   └── inventory_test
│   └── group_vars
│      ├── all
│      └── ansible_test
└── playbook_var.yaml
```

### invertory:

```
# cat hosts/inventory_test 
[ansible_test:children]
group1
group2

[group1]
10.15.222.207

[group2]
10.15.222.208
10.15.222.209

[ansible_test:vars]
vars_test="in inventory"

[group1:vars]
vars_test="in group1"
```

### inventory group_vars/all :

```

cat hosts/group_vars/all 
---

vars_test: "in group_vars/all"
```

### inventory group_vars/ansible_test

```
# cat hosts/group_vars/ansible_test 
---

vars_test: "in group_all/ansible_test"
```

### If I use group_vars/ansible_test, I can get:

```
# ansible-playbook --limit=ansible_test -i hosts/inventory_test playbook_var.yml 

PLAY [ansible_test] ************************************************************

TASK [setup] *******************************************************************
ok: [10.15.222.208]
ok: [10.15.222.207]
ok: [10.15.222.209]

TASK [debug] *******************************************************************
ok: [10.15.222.207] => {
    "msg": "in group_all/ansible_test"
}
ok: [10.15.222.208] => {
    "msg": "in group_all/ansible_test"
}
ok: [10.15.222.209] => {
    "msg": "in group_all/ansible_test"
}

PLAY RECAP *********************************************************************
10.15.222.207              : ok=2    changed=0    unreachable=0    failed=0   
10.15.222.208              : ok=2    changed=0    unreachable=0    failed=0   
10.15.222.209              : ok=2    changed=0    unreachable=0    failed=0   

```

### And then If I do not use group_vars/ansible_test, I can get:

```
# ansible-playbook --limit=ansible_test -i hosts/inventory_test playbook_var.yml 

PLAY [ansible_test] ************************************************************

TASK [setup] *******************************************************************
ok: [10.15.222.209]
ok: [10.15.222.207]
ok: [10.15.222.208]

TASK [debug] *******************************************************************
ok: [10.15.222.208] => {
    "msg": "in inventory"
}
ok: [10.15.222.207] => {
    "msg": "in group1"
}
ok: [10.15.222.209] => {
    "msg": "in inventory"
}

PLAY RECAP *********************************************************************
10.15.222.207              : ok=2    changed=0    unreachable=0    failed=0   
10.15.222.208              : ok=2    changed=0    unreachable=0    failed=0   
10.15.222.209              : ok=2    changed=0    unreachable=0    failed=0 
```

So I find the vars in the inventory group_vars/all  file will be overridden by in the inventory
