### ISSUE TITLE
"Edit this document" link is broken

### ISSUE THREAD

**Issue by krlinus** [ansible/ansible#69551] opened 2020-05-15 21:35 UTC
##### SUMMARY

On this page
https://docs.ansible.com/ansible/latest/modules/ec2_vol_info_module.html#ec2-vol-info-module

The "Edit this document" link goes to a 404 page on github

HINT: The Hint link is broken (See above)

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

I don't know and cant guess the rst file name. I believe information already provided is sufficient.

##### ANSIBLE VERSION

On the documentation page the version shows 2.9 and the dropdown shows "latest". There is no difference even if I select devel
```paste below

```

##### CONFIGURATION

Not relevant or possible to provide

```paste below

```

##### OS / ENVIRONMENT

Chrome browser (Version 81.0.4044.138 (Official Build) (64-bit)) on Windows 10 pro ver 1903 OS build 18362.836

##### ADDITIONAL INFORMATION

The documentation for ec2_vol_info is pathetic. By giving the people a chance to improve it it will be hopefully slightly functional as opposed to useless.

**Comment by mkrizek** [comment] 2020-05-16 07:06
Duplicate of https://github.com/ansible/ansible/issues/69155

**Closed as completed by mkrizek** 2020-05-16 07:06 UTC
