### ISSUE TITLE
Handlers defined in a role are not executed/discovered

### ISSUE THREAD

**Issue by ubergeek42** [ansible/ansible#11286] opened 2015-06-16 20:53 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

``` sh
$ ansible --version
ansible 2.0.0 (devel 605ddad37e) last updated 2015/06/16 13:51:29 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 9acc7c402f) last updated 2015/06/16 13:51:31 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 2f967a949f) last updated 2015/06/16 13:51:34 (GMT -400)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/06/16 13:51:36 (GMT -400)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/06/16 13:51:46 (GMT -400)
  configured module search path = None
```

Using `source hacking/env-setup`
##### Ansible Configuration:

N/A
##### Environment:

Ubuntu 14.04, managing Ubuntu 14.04.
##### Summary:

Handlers defined in a role are not executed. If the handler is moved into the play itself, then it will execute normally. See the commented out handler below; if it is uncommented this testcase works correctly. It seems to only be when the handler is defined in the role itself that it fails to execute.

Also, I noticed that if the handler is not defined anywhere, no error message is raised. Under v1 an error message is raised when the handler is to be notified. Everything works as expected if I `source v1/hacking/env-setup` instead.
##### Steps To Reproduce:

Create a role with:

roles/testrole/tasks/main.yml

``` yaml

---
- name: trigger handler
  debug: msg="Trigger a handler"
  changed_when: true
  notify: test handler
```

roles/testrole/handlers/main.yml

``` yaml

---
- name: test handler
  debug: msg="Message from handler"
```

play.yml

``` yaml
- hosts: all
#  handlers:
#    - name: test handler
#      debug: msg="Message from handler"
  roles:
    - testrole
```

Then run: `ansible-playbook -i 127.0.0.1, -c local play.yml`
##### Expected Results:

I expect the handler to run, and the output to be this:

```
PLAY: ***************************************************************************

TASK [setup] ********************************************************************
ok: [127.0.0.1]

TASK [testrole : trigger handler] ***********************************************
changed: [127.0.0.1] => {
    "msg": "Trigger a handler", 
    "changed": true
}

RUNNING HANDLER [test handler] **************************************************
ok: [127.0.0.1] => {
    "msg": "Message from handler", 
    "changed": false
}

PLAY RECAP **********************************************************************
127.0.0.1                  : ok=3    changed=1    unreachable=0    failed=0
```
##### Actual Results:

The handler is never notified, and if it is never defined then no error messages are raised.

```
PLAY: ***************************************************************************

TASK [setup] ********************************************************************
ok: [127.0.0.1]

TASK [testrole : trigger handler] ***********************************************
changed: [127.0.0.1] => {
    "msg": "Trigger a handler", 
    "changed": true
}

PLAY RECAP **********************************************************************
127.0.0.1                  : ok=2    changed=1    unreachable=0    failed=0
```

**Comment by jimi-c** [comment] 2015-06-21 04:51
# Closing This Ticket

Hi!

We believe the commit be81b650e80ca07fb3f669a13b4882919508c558 should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-06-21 04:51 UTC
Labels: P2, bug

**Comment by saulshanabrook** [comment] 2015-07-23 07:11
I am currently still seeing this issue with ansible 1.9.2

**Comment by jimi-c** [comment] 2015-07-23 13:24
@saulshanabrook please open a new issue, with an example that reproduces the error for you, or ask on the mailing list.

Thanks!
