### ISSUE TITLE
Role dependency never included again when skipped in a first role

### ISSUE THREAD

**Issue by broferek** [ansible/ansible#13480] opened 2015-12-09 08:01 UTC
Hi,

say that you have a common role including vars that a bunch of other roles always includes as dependency.

In a playbook, you call your different roles and the first one is skipped for some reason, then the role dependency is skipped which is normal.

But it is never called again by the other roles.

I understand the need to call the dependency only once but for me, it has to be executed at least once. If it is skipped in the first role, then it must be called again by another role to be able to include our vars in our case.

Please find below a copy of our playbook execution and a detailed explanation.

Thanks,

Ludo

We have a common role geppetto_include_vars which is included as meta in 2 other roles geppetto_create_node and geppetto_update_component.

As you can see, geppetto_include_vars is called by geppetto_create_node which is skipped which is fine.
But when executing the next role geppetto_update_component, the geppetto_include_vars dependency is not called. It should be as it has been skipped in the first role and the variables have not been loaded.

TASK: [geppetto_include_vars | Load Geppetto vars if needed] *****************\* 
|- 10:22:24.117946 start tasks for all host
skipping: [127.0.0.1]

TASK: [geppetto_create_node | Call geppetto web service] *********************\* 
|- 10:22:24.151637 start tasks for all host
skipping: [127.0.0.1] => (item=geppetto_create_node_nodename_list)

TASK: [geppetto_update_component | Set geppetto_update_component_namespace] **\* 
|- 10:22:24.264924 start tasks for all host
fatal: [127.0.0.1 -> 127.0.0.1] => One or more undefined variables: 'geppetto' is undefined

**Comment by jimi-c** [comment] 2015-12-09 16:17
@broferek with which version of Ansible are you seeing this? This is a bug in 1.9.x, however it has been fixed in the upcoming 2.0 release. Due to the complexity involved here, unfortunately this bugfix will not be back-ported to the stable-1.9 branch.

**Comment by chrrrles** [comment] 2015-12-09 16:17
Hello Ludo,

Can you submit this bug report using our template below?  Also, I don't see a playbook for duplicating this condition.

##### Issue Type:

Can you help us out in labelling this by telling us what kind of ticket this this?  You can say:
  - Bug Report
  - Feature Idea
  - Feature Pull Request
  - New Module Pull Request
  - Bugfix Pull Request
  - Documentation Report
  - Docs Pull Request

##### Ansible Version:

Let us know what version of Ansible you are using.  Please supply the verbatim output from running “ansible --version”.  If you're filing a ticket on a version of Ansible which is not the latest, we'd greatly appreciate it if you could retest on the latest version first.  We don't expect you to test against the development branch most of the time, but we may ask for that if you have cycles.  Thanks!

##### Ansible Configuration:

What have you changed about your Ansible installation?  What configuration settings have you changed/added/removed?  Compare your /etc/ansible/ansible.cfg against a clean version from Github and let us know what's different.

##### Environment:

What OS are you running Ansible from and what OS are you managing?  Examples include RHEL 5/6, Centos 5/6, Ubuntu 12.04/13.10, *BSD, Solaris.  If this is a generic feature request or it doesn’t apply, just say “N/A”.  Not all tickets may be about operating system related things and we understand that.

##### Summary:

Please summarize your request in this space.  You will earn bonus points for being succinct, but please add enough detail so we can understand the request.  Thanks!

##### Steps To Reproduce:

If this is a bug ticket, please enter the steps you use to reproduce the problem in the space below.  If this is a feature request, please enter the steps you would use to use the feature.  If an example playbook is useful, please include a short reproducer inline, indented by four spaces.  If a longer one is necessary, linking to one uploaded to gist.github.com would be great.  Much appreciated!

##### Expected Results:

Please enter your expected results in this space.  When running the steps supplied above in the previous section, what did you expect to happen?  If showing example output, please indent your output by four spaces so it will render correctly in GitHub's viewer thingy.

##### Actual Results:

Please enter your actual results in this space.  When running the steps supplied above, what actually happened?  If you are showing example output, please indent your output by four spaces so it will render correctly in GitHub.  Thanks again!

**Comment by broferek** [comment] 2015-12-09 16:25
Hi,

thanks for your reply, version 1.9.4 indeed.

Cool if it has been fixed in 2.0. We'll upgrade soon and see if it is well fixed.

Thanks,

Ludo

**Comment by jimi-c** [comment] 2015-12-09 16:38
Thanks, I'll go ahead and close this now then.

**Closed as completed by jimi-c** 2015-12-09 16:38 UTC
Labels: pending_action, bug
