### ISSUE TITLE
winrm: can't login with russian symbols

### ISSUE THREAD

**Issue by lexxcbrm** [ansible/ansible#21183] opened 2017-02-09 09:39 UTC
ISSUE TYPE

Bug Report

COMPONENT NAME

Ansible

ANSIBLE VERSION

ansible 2.2.0.1

CONFIGURATION

not any special configuration

OS / ENVIRONMENT

control machine: debian jessy minimal
remote machine: Windows 2012 R2

SUMMARY

running:
ansible 192.168.40.105 -u Админ -m win_ping

result:

192.168.40.105 | UNREACHABLE! => {
    "changed": false,
    "msg": "ssl: 'latin-1' codec can't encode characters in position 0-4: ordinal not in range(256)",
    "unreachable": true
}

STEPS TO REPRODUCE
Create accout on Windows 2012 R2 with name Админ (russian letters).

EXPECTED RESULTS

Pass authentication.

**Comment by nitzmahone** [comment] 2017-02-10 00:05
Is your control machine configured to use a UTF8 locale?

**Comment by lexxcbrm** [comment] 2017-02-10 06:12
Yes. My control machine configure to use UTF8. 
When I use ssh separately it works perfect. I mean then I type "ssh Админ@my_ip" in same case.

**Comment by jhawkesworth** [comment] 2017-02-10 06:30
I doesn't look like you are getting a winrm connection (still trying ssh I think). 
do you have windows group_vars set up as described here: http://docs.ansible.com/ansible/intro_windows.html#inventory

Also please try running 

ansible 192.168.40.105 -u Админ -m win_ping -vvv

(this should show connection type and give information on how far it is getting)

needs_info

**Comment by lexxcbrm** [comment] 2017-02-10 07:29
I got this stage already. If I try to do something with account created with english letters, then I works fine (e.g.  "ansible 192.168.40.105 -u admin -m win_ping -vvv"). But it fails if account name contains russian symbols.

**Comment by jhawkesworth** [comment] 2017-02-10 08:19
Please can you run with -vvvvv and copy the output here as this will help work out where the problem is.

Many thanks,

needs_info

**Comment by lexxcbrm** [comment] 2017-02-10 08:36
root@ansible: ansible 192.168.40.105 -u test_admin -m win_ping
192.168.40.105 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
![users](https://cloud.githubusercontent.com/assets/19706817/22819832/00d065b2-ef85-11e6-8ae2-6a03460f3a5e.JPG)
![users](https://cloud.githubusercontent.com/assets/19706817/22819848/15a478e8-ef85-11e6-8354-148cebed1c47.JPG)
root@ansible:~# ansible 192.168.40.105 -u Админ -m win_ping -vvvvv
Using /etc/ansible/ansible.cfg as config file
Loading callback plugin minimal of type stdout, v2.0 from /usr/lib/python2.7/dist-packages/ansible/plugins/callback/__init__.pyc
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/windows/win_ping.ps1
<192.168.40.105> ESTABLISH WINRM CONNECTION FOR USER: Админ on PORT 5986 TO 192.168.40.105
<192.168.40.105> WINRM CONNECT: transport=ssl endpoint=https://192.168.40.105:5986/wsman
<192.168.40.105> WINRM CONNECTION ERROR: 'latin-1' codec can't encode characters in position 0-4: ordinal not in range(256)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/connection/winrm.py", line 154, in _winrm_connect
    self.shell_id = protocol.open_shell(codepage=65001)  # UTF-8
  File "/usr/local/lib/python2.7/dist-packages/winrm/protocol.py", line 132, in open_shell
    res = self.send_message(xmltodict.unparse(req))
  File "/usr/local/lib/python2.7/dist-packages/winrm/protocol.py", line 207, in send_message
    return self.transport.send_message(message)
  File "/usr/local/lib/python2.7/dist-packages/winrm/transport.py", line 181, in send_message
    prepared_request = self.session.prepare_request(request)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 407, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 306, in prepare
    self.prepare_auth(auth, url)
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 543, in prepare_auth
    r = auth(self)
  File "/usr/local/lib/python2.7/dist-packages/requests/auth.py", line 97, in __call__
    r.headers['Authorization'] = _basic_auth_str(self.username, self.password)
  File "/usr/local/lib/python2.7/dist-packages/requests/auth.py", line 61, in _basic_auth_str
    username = username.encode('latin1')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-4: ordinal not in range(256)

192.168.40.105 | UNREACHABLE! => {
    "changed": false,
    "msg": "ssl: 'latin-1' codec can't encode characters in position 0-4: ordinal not in range(256)",
    "unreachable": true
}

**Comment by lexxcbrm** [comment] 2017-02-10 08:39
Sorry. I have posted same image double time.

**Comment by lexxcbrm** [comment] 2017-02-20 14:35
Hello! Do you have a solution?

**Comment by jhawkesworth** [comment] 2017-02-20 17:39
So it looks like the point where it is failing is in requests library where it attempts to create the Authorization header by base64 encoding the username and password

```python
def _basic_auth_str(username, password):
    """Returns a Basic Auth string."""

    authstr = 'Basic ' + to_native_string(
        b64encode(('%s:%s' % (username, password)).encode('latin1')).strip()
    )

    return authstr
```

So I think the issue is really an issue with requests, not ansible, and would need raising on their bug tracking system.

**Comment by jhawkesworth** [comment] 2017-02-21 05:25
I looked a bit more at this.
The problem definitely occurs in requests.  A little script like the below will reproduce this.


```

#!/usr/bin/python
# -*- coding: utf-8 -*-

from base64 import b64encode

username = 'Админ'
password = 'a_password_would_go_here'

authstr = b64encode(('%s:%s' % (username, password)).encode('latin-1')).strip()

print authstr
```

I suggest you raise the issue on the requests issue tracker here: https://github.com/kennethreitz/requests/issues

Because the problem lies outside ansible I am going to close this issue.

**Closed as completed by jhawkesworth** 2017-02-21 05:25 UTC
Labels: windows, affects_2.2, c:plugins/connection/winrm, bug

**Comment by lexxcbrm** [comment] 2017-02-21 06:38
Thank you kindly
