### ISSUE TITLE
Include Role does not allow dynamic name specification.

### ISSUE THREAD

**Issue by kert-io** [ansible/ansible#28179] opened 2017-08-14 17:41 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
- include_role

##### ANSIBLE VERSION
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible', u'/etc/ansible/library']
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

##### OS / ENVIRONMENT
mac 
##### SUMMARY
Include_role does not parse variable in the name: field. e.g.:
```yaml
 - name: create configs
    include_role:
      name: "{{ deployment.name }}"
```
This works with include:  

Yes, deployment is defined. And deployment is successfully passed in the vars passed into the include_role call if I manually override the name field.  The issue seems to be solely in the treatment of the name field or it's context is other than the location where called.  

I would expect to be able to pass the role in dynamically so that I don't need to have the mess of several redundant includes utilizing when statements.

##### ACTUAL RESULTS

ERROR! 'deployment' is undefined

**Comment by bcoca** [comment] 2017-08-14 17:48
dupe of #22571

**Closed as completed by bcoca** 2017-08-14 17:48 UTC
Labels: affects_2.3, module, support:core, bug
