### ISSUE TITLE
ansible-galaxy collection init doesn't generate meta/runtime.yml making upload to automation hub fail

### ISSUE THREAD

**Issue by ericzolf** [ansible/ansible#77460] opened 2022-04-04 16:27 UTC
### Summary

`ansible-galaxy collection init` doesn't generate `meta/runtime.yml` which leads to the following error when trying to upload it to (private) automation hub:

```
ERROR! Galaxy import process failed: 'requires_ansible' in meta/runtime.yml is mandatory, but no meta/runtime.yml found (Code: UNKNOWN)
```

### Issue Type

Bug Report

### Component Name

ansible-galaxy

### Ansible Version

```console
$ ansible-galaxy --version
ansible-galaxy [core 2.12.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/elavarde/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/elavarde/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-galaxy
  python version = 3.10.4 (main, Mar 25 2022, 00:00:00) [GCC 11.2.1 20220127 (Red Hat 11.2.1-9)]
  jinja version = 3.0.1
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
<nothing>
```

### OS / Environment

Fedora 35

### Steps to Reproduce

```
ansible-galaxy collection init mynamespace.mycollection
cd mynamespace.mycollection
ansible-galaxy collection build .
ansible-galaxy collection publish -s https://autohub.example.com/api/galaxy/content/inbound-mynamespace/ --token mytoken --ignore-certs mynamespace-mycollection-1.0.0.tar.gz 
```

### Expected Results

successful upload

### Actual Results

```console
ERROR! Galaxy import process failed: 'requires_ansible' in meta/runtime.yml is mandatory, but no meta/runtime.yml found (Code: UNKNOWN)
```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by sivel** [comment] 2022-04-04 16:29
Duplicate of https://github.com/ansible/ansible/pull/77418

**Closed as completed** 2022-04-05 15:35 UTC
Labels: support:core, bug, affects_2.12
