### ISSUE TITLE
ec2 module is broken in ansible 1.8.3

### ISSUE THREAD

**Issue by awasilyev** [ansible/ansible#10289] opened 2015-02-19 09:48 UTC
Trying to launch ec2 instance using ansible 1.8.3 gives me:

Traceback (most recent call last):
File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1424337493.09-167968274609306/ec2", line 2998, in <module>
    main()
   File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1424337493.09-167968274609306/ec2", line 1203, in main
     (tagged_instances, instance_dict_array, new_instance_ids, changed) = enforce_count(module, ec2)
   File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1424337493.09-167968274609306/ec2", line 682, in enforce_count
     = create_instances(module, ec2, override_count=to_create)
   File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1424337493.09-167968274609306/ec2", line 817, in create_instances
     params['tenancy'] = tenancy
 NameError: global name 'tenancy' is not defined

Same recipe in the 1.8.2 works ok.

**Comment by bcoca** [comment] 2015-02-19 14:12
closing as duplicate of https://github.com/ansible/ansible-modules-core/issues/808

**Closed as completed by bcoca** 2015-02-19 14:12 UTC
