### ISSUE TITLE
Group module fails when trying to add/update a group which already exist in the attached AD

### ISSUE THREAD

**Issue by xrow** [ansible/ansible#11421] opened 2015-06-29 15:27 UTC
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
group module

##### ANSIBLE VERSION
 1.9

##### SUMMARY
Hi,

the group module seems to not work right. I am using centos 7. The expected result is that it wouldn't fail since the group is properly present. The group was added by ´yum install docker´ 

Task:

``` yaml
- group: name=dockerroot state=present gid=989
```

Sample

``` bash
TASK: [newrelic | Configure New Relic Sysmond] ******************************** 
changed: [192.168.0.244]

TASK: [newrelic | group name=dockerroot state=present gid=989] **************** 
failed: [192.168.0.244] => {"failed": true, "name": "dockerroot"}
msg: groupmod: GID '989' already exists


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/vmbuilder.retry

192.168.0.244              : ok=73   changed=17   unreachable=0    failed=1   

[root@172-17-42-1 ~]# ansible-playbook --version
ansible-playbook 1.9.0.1
  configured module search path = None
[root@172-17-42-1 ~]# grep -i "989" /etc/group  
dockerroot:x:989:newrelic
```

**Comment by jhitt25** [comment] 2015-07-02 18:15
Verified also an issue on Oracle Linux 7, Ansible 1.9.1
This also occurs in the opposite direction.  If the group does not exist, instead of being created it errors out with: "groupmod: group 'newgroup' does not exist in /etc/group"

```
ansible> cat /etc/os-release
NAME="Oracle Linux Server"
VERSION="7.1"
ID="ol"
VERSION_ID="7.1"
PRETTY_NAME="Oracle Linux Server 7.1"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:1"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.1
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.1
ansible> ansible-playbook --version
ansible-playbook 1.9.1
  configured module search path = None
```

**Comment by xrow** [comment] 2015-07-03 09:00
@jhitt25 thanks for the feedback. I hope someone will pick it up.

**Comment by bcoca** [comment] 2015-07-08 02:20
can you run in verbose? -vvvv

**Comment by bcoca** [comment] 2015-07-08 02:22
i cannot reproduce against centos6 or 7 nor in debian based distros, I don't have access to Oracle Linux.

**Comment by jhitt25** [comment] 2015-07-08 13:43
I just ran two new tests.  The first i used "group: name=test gid=55555 state=present".  This suceeded.  The second, i used "group: name=dba gid=55555 state=present", which resulted in the error.

Output from
    ansible> ansible-playbook -vvv -i dev playbooks/single.yml --ask-vault-pass -l MYHOST -K -u MYACCOUNT

```
PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
<MYHOST> ESTABLISH CONNECTION FOR USER:
<MYHOST> REMOTE_MODULE setup
<MYHOST> EXEC ssh -C -v -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/MYACCOUNT/.ansible/cp/ansible-ssh-%h-%p-%r" -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User= -o ConnectTimeout=10 MYHOST /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=pyewwtfebpjrlowdecbxwbgyvkypcbzj] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-pyewwtfebpjrlowdecbxwbgyvkypcbzj; LANG=C LC_CTYPE=C /usr/bin/python'"'"''
ok: [MYHOST]

TASK: [test | Create test group] **********************************************
<MYHOST> ESTABLISH CONNECTION FOR USER:
<MYHOST> REMOTE_MODULE group name=dba gid=54320 state=present
<MYHOST> EXEC ssh -C -v -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/MYACCOUNT/.ansible/cp/ansible-ssh-%h-%p-%r" -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User= -o ConnectTimeout=10 MYHOST /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=csvtaczsfelezzxuywgacnyartjkrolq] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-csvtaczsfelezzxuywgacnyartjkrolq; LANG=C LC_CTYPE=C /usr/bin/python'"'"''
failed: [MYHOST] => {"failed": true, "name": "dba"}
msg: groupmod: group 'dba' does not exist in /etc/group


FATAL: all hosts have already failed -- aborting
```

So it appears that for me the issue isn't a gid check, but possibly an explicit test for a group name.

**Comment by xrow** [comment] 2015-07-08 13:46
Good I wasn`t able to reproduce it anymore. I don't know why. Can you add the contents of your task yaml?

**Comment by jhitt25** [comment] 2015-07-08 18:53
The playbook i used:

```
---
# file: single.yml
- hosts: all
  sudo: yes
  tasks:
    - group: name=dba gid=55555 state=present
```

**Comment by bcoca** [comment] 2015-07-08 18:57
so issue is trying to create group with existing gid assigned to diff group?

**Comment by jhitt25** [comment] 2015-07-08 19:24
No, The error i listed, "groupmod: group 'dba' does not exist in /etc/group" occurs when the group does not exist in /etc/group at all (either by name or by gid).  If the group already exists the playbook shows 'changed', even though it obviously has changed nothing.

**Comment by bcoca** [comment] 2015-07-08 20:23
in my tests it creates the group

**Comment by jhitt25** [comment] 2015-07-08 23:12
On Oracle Linux 7 (or possibly RHEL7, which is what it is based on)?

**Comment by xrow** [comment] 2015-07-09 09:42
There shall be no differences in Oracle, CentOS, RedHat Linux 7 accept for some additional repositories/packages.

I can't reproduce it with your script. There might be some side effect which we havn't discovered yet.

``` bash
[root@172-17-42-1 ~]# ansible-playbook ~/provision/single.yml -i ~/provision/hosts               

PLAY [local] ****************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [group name=dba gid=55555 state=present] ******************************** 
changed: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=1    unreachable=0    failed=0   

[root@172-17-42-1 ~]# ansible-playbook ~/provision/single.yml -i ~/provision/hosts

PLAY [local] ****************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [group name=dba gid=55555 state=present] ******************************** 
ok: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=0    unreachable=0    failed=0   

[root@172-17-42-1 ~]# ansible-playbook ~/provision/single.yml -i ~/provision/hosts

PLAY [local] ****************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [group name=dba gid=55555 state=present] ******************************** 
ok: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=0    unreachable=0    failed=0   

[root@172-17-42-1 ~]# 
```

**Comment by jhitt25** [comment] 2015-07-09 13:14
After more research, i located the issue.  We use AD integrated logins/groups via SSSD, and a 'dba' group exists there.  This causes a 'groupmod' to be issued instead of a 'groupadd'.  'groupmod' is not capable of updating our AD groups, and on top of that the account i want to add to the 'dba' group is a local account, so i need an /etc/group entry as well.  Maybe the 'group' command needs a local-only option?

**Comment by bcoca** [comment] 2015-07-10 14:49
not sure how that will work as the error is coming from the server's group utilities, which is what the group module uses.

**Comment by xrow** [comment] 2015-07-10 16:11
Hi,

just for the record. I wasn`t connected to any AD, but I can`t reproduce it anymore.

**Comment by caljess599** [comment] 2016-01-12 18:31
I just experienced this issue because the host I'm working on IS connected to a NIS. (NIS is really old, but we still use it where I work). The workaround is to stop the ypbind service before the task runs (and then start it again after you've created the groups). The duplication of names won't bother NIS when it is configured (as it is with us) to look locally first. 
I would love to see an option build into the group module that would allow you to specify what if any services you needed to stop before/start after, but adding the two service statements wasn't hard.

**Comment by jgrigonis** [comment] 2016-07-14 20:52
In my case I had to stop sssd before adding the local (sort of duplicate) group. Then I restarted the sssd service afterwards, and all was fine.

Basically, the ldap already had the same group.

**Comment by roumano** [comment] 2017-01-03 11:05
Same issue as jgrigonis
for me, to bypass this issue i need these 2 task : 

 - name: Disable temporary sssd service
   service: name=sssd state=stopped
 - name: remove sssd cache
   command: sss_cache -E

**Comment by jctanner** [comment] 2017-01-23 23:47
@xrow can you confirm is starting/stopping sssd helps your situation?

needs_info

**Comment by xrow** [comment] 2017-01-24 08:56
@jctanner As said before, I can't reproduce it anymore. I don`t have any sssd installed.

**Comment by evadeflow** [comment] 2017-01-26 20:56
Not sure it's related, but I've *just* run into a (seemingly) similar issue on Raspian Jesse. In case it helps, here's the task I'm trying to run:

```
---                                       
- name: Create groups for homeassistant user 
  group:
    name: "{{ item }}"
    system: yes
    state: present
  with_items:
    - dialout
    - gpio
    - video
  become: yes
    
- name: Create homeassistant user 
  user:
    name: homeassistant
    system: yes
    groups:
      - dialout
      - gpio
      - video
  become: yes
```

When I run my playbook, I'm getting this error—whether the `gpio` user exists beforehand or not:

```
TASK [homeassistant : Create homeassistant user] *******************************
task path: /home/pi/ansible-rpi-homeassistant/roles/homeassistant/tasks/main.yml:13
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/core/system/user.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: pi
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1485084836.04-79151705210754 `" && echo ansible-tmp-1485084836.04-79151705210754="` echo ~/.ansible/tmp/ansible-tmp-1485084836.04-79151705210754 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpcG6nfc TO /home/pi/.ansible/tmp/ansible-tmp-1485084836.04-79151705210754/user.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/pi/.ansible/tmp/ansible-tmp-1485084836.04-79151705210754/ /home/pi/.ansible/tmp/ansible-tmp-1485084836.04-79151705210754/user.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-kypgkydtpivwhbeqjerlzzuxhlfdqxfw; /usr/bin/python /home/pi/.ansible/tmp/ansible-tmp-1485084836.04-79151705210754/user.py; rm -rf "/home/pi/.ansible/tmp/ansible-tmp-1485084836.04-79151705210754/" > /dev/null 2>&1'"'"' && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "append": false, 
            "comment": null, 
            "createhome": true, 
            "expires": null, 
            "force": false, 
            "generate_ssh_key": null, 
            "group": null, 
            "groups": "['dialout', 'gpio', 'video']", 
            "home": null, 
            "login_class": null, 
            "move_home": false, 
            "name": "homeassistant", 
            "non_unique": false, 
            "password": null, 
            "remove": false, 
            "seuser": null, 
            "shell": null, 
            "skeleton": null, 
            "ssh_key_bits": 0, 
            "ssh_key_comment": "ansible-generated on raspberrypi", 
            "ssh_key_file": null, 
            "ssh_key_passphrase": null, 
            "ssh_key_type": "rsa", 
            "state": "present", 
            "system": true, 
            "uid": null, 
            "update_password": "always"
        }, 
        "module_name": "user"
    }, 
    "msg": "Group  'gpio' does not exist"
}
        to retry, use: --limit @/home/pi/ansible-rpi-homeassistant/playbook.retry

PLAY RECAP *********************************************************************
localhost                  : ok=8    changed=0    unreachable=0    failed=1
```

Just thought I'd toss that out there in case it helps. Here's my Ansible version:

```
$ ansible-playbook --version
ansible-playbook 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides
```

**UPDATE**:  Just wanted to say, in case it matters, that I'm not running `sssd`.

**Comment by evadeflow** [comment] 2017-01-26 21:33
FWIW, I tried deleting both the `homeassistant` user and the `gpio` group and re-running. It still fails:

```
TASK [homeassistant : Create groups for homeassistant user] ********************
ok: [localhost] => (item=dialout)
changed: [localhost] => (item=gpio)
ok: [localhost] => (item=video)

TASK [homeassistant : Create homeassistant user] *******************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Group  'gpio' does not exist"}
        to retry, use: --limit @/home/pi/ansible-rpi-homeassistant/playbook.retry

PLAY RECAP *********************************************************************
localhost                  : ok=8    changed=1    unreachable=0    failed=1
```

For a goof, I tried changing the name of the group as follows:

```diff
--- main.yml.orig    2017-01-22 07:09:56.999994197 -0500
+++ main.yml       2017-01-22 07:09:50.929994200 -0500
@@ -6,7 +6,7 @@
     state: present
   with_items:
     - dialout
-    - gpio
+    - xxx
     - video
   become: yes
     
@@ -15,6 +15,6 @@
     name: homeassistant
     groups:
       - dialout
-      - gpio
+      - xxx
       - video
   become: yes
```

I got the same error, but for a different group:

```
TASK [homeassistant : Create homeassistant user] *******************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Group ['dialout' does not exist"}
        to retry, use: --limit @/home/pi/ansible-rpi-homeassistant/playbook.retry
```

That's probably a helpful clue to somebody, but... I'm not that guy. `:-]  I'll post here again if I manage to finger-mumble my way out of this...

**Comment by evadeflow** [comment] 2017-01-27 14:20
I'm not sure I'll have time to finish this investigation, so I'm posting what I've discovered thus far. The problem lies in the `get_groups_set()` function in `ansible/modules/core/system/user.py`, near line 522. As this `pdb-clone` session shows, `self.groups`  contains the string `"['dialout', 'gpio', 'video']"`:

```
(Pdb) l
517  
518         def get_groups_set(self, remove_existing=True):
519             if self.groups is None:
520                 return None
521             info = self.user_info()
522  ->         groups = set(filter(None, self.groups.split(',')))
523             for g in set(groups):
524                 if not self.group_exists(g):
525                     self.module.fail_json(msg="Group %s does not exist" % (g))
526                 if info and remove_existing and self.group_info(g)[2] == info[3]:
527                     groups.remove(g)
(Pdb) self.groups
"['dialout', 'gpio', 'video']"
(Pdb) n
> /tmp/ansible_RGmdW2/ansible_module_user.py(523)get_groups_set()
-> for g in set(groups):
(Pdb) groups
set([" 'gpio'", "['dialout'", " 'video']"])
(Pdb)
```

It seems the code expects `self.groups` to be `"dialout,gpio,video"` instead. If I manually set it to that value, the task succeeds:

```
$ pdb-attach
Connected to ansible_module_user.py at ('127.0.0.1', 7935), pid: 20560.
> /tmp/ansible_xHPNKI/ansible_module_user.py(522)get_groups_set()
-> groups = set(filter(None, self.groups.split(',')))
(Pdb) l
517         def get_groups_set(self, remove_existing=True):
518             if self.groups is None:
519                 return None
520             info = self.user_info()
521             from pdb_clone import pdb; pdb.set_trace_remote()
522  ->         groups = set(filter(None, self.groups.split(',')))
523             for g in set(groups):
524                 if not self.group_exists(g):
525                     self.module.fail_json(msg="Group %s does not exist" % (g))
526                 if info and remove_existing and self.group_info(g)[2] == info[3]:
527                     groups.remove(g)
(Pdb) self.groups
"['dialout', 'gpio', 'video']"
(Pdb) self.groups = "dialout,gpio,video"
(Pdb) c
('127.0.0.1', 7935) socket closed by pdb.
Closed by remote.
```

When I puppet-string it this way, the last thing printed to the terminal in which I ran the playbook is:

```
PLAY RECAP *********************************************************************
localhost                  : ok=9    changed=1    unreachable=0    failed=0
```

I checked Github to see if there was any recent activity in that code, but it looks like it hasn't been touched in quite awhile, see:

* https://github.com/ansible/ansible/blame/devel/lib/ansible/modules/system/user.py#L550

Seems like a bug(?)

**Comment by evadeflow** [comment] 2017-01-27 14:35
I just confirmed that changing my task as follows gets rid of the `Group 'gpio' does not exist` error:

```diff
--- main.yml.orig       2017-01-22 09:21:21.619999587 -0500
+++ main.yml    2017-01-22 09:21:00.699999594 -0500
@@ -14,8 +14,5 @@
   user:
     name: homeassistant
     system: yes
-    groups:
-      - dialout
-      - gpio
-      - video
+    groups: dialout,gpio,video
   become: yes
```

The [user module docs](http://docs.ansible.com/ansible/user_module.html) have this to say about the `groups` option:

>Before version 2.3, the only input format allowed was a 'comma separated string', now it should be able to accept YAML lists also.

Since I'm using version 2.2.1, this behavior is, I suppose, not entirely surprising. Although... it's a bit more stringent than the docs imply. It really wants a "comma separated string *with no spaces*". One of the first things I tried was:

```
    groups: dialout, gpio, video
```

But this results in the same error, because the code winds up checking for a group named `" gpio"` (note the leading space), which doesn't exist.

Anyway, sorry for the noise. I'm gonna drop the spaces and move on...

**Comment by jctanner** [comment] 2017-03-29 17:08
@evadeflow please open a new issue with the information you have provided so far.

@xrow since you can no longer reproduce, I'm going to close this issue.

**Closed as completed by jctanner** 2017-03-29 17:08 UTC
Labels: affects_1.9, module, bug
