### ISSUE TITLE
Order of inventory groups in inventory file matters when using EC2.py groups created from instance tags

### ISSUE THREAD

**Issue by tegryan** [ansible/ansible#5207] opened 2013-12-06 19:22 UTC
The ec2.py script now creates host groups based on instance tags, but I think there might be two issues.  
1.  The order of your inventory file needs to go:

non-tag groups
tag groups

for the tag groups to work.  For example:

```
[local]
127.0.0.1

[eh_web]
x.x.x.x

[tag_Class_web]
x.x.x.x
```

Is valid where x.x.x.x is a static IP.  But:

```
[local]
127.0.0.1

[tag_Class_web]
x.x.x.x

[eh_web]
x.x.x.x
```

Only runs plays on x.x.x.x if you use the tag_Class_web group.
1.  I'm not sure this is a bug, but I would imagine the hostgroup should be allowed to be empty in the inventory file.  Should this not work?  Neither this format nor leaving the host group out entirely causes the EC2.py script to run.

```
[local]
127.0.0.1

[tag_Class_web]

[eh_web]
x.x.x.x
```

**Comment by mpdehaan** [comment] 2013-12-07 13:24
This seems to be a duplicate of #5196 where the host records between the inventory script and the INI file are not merged.

Generally speaking, most people will just rely on the EC2 inventory exclusively in a cloud context.

I'm linking these tickets and feel free to comment on this one or the other.

Thanks!

**Closed as completed by mpdehaan** 2013-12-07 13:24 UTC
Labels: cloud, bug
