### ISSUE TITLE
session object has no attribute 'merge

### ISSUE THREAD

**Issue by hairatheeav** [ansible/ansible#50611] opened 2019-01-07 16:48 UTC
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by sivel** [comment] 2019-01-07 21:41
Duplicate of https://github.com/ansible/ansible/issues/50612

**Closed as completed by sivel** 2019-01-07 21:41 UTC
Labels: support:core, bug, affects_2.8
