### ISSUE TITLE
When condition evaluation is ignored for register

### ISSUE THREAD

**Issue by paul-vasiliev** [ansible/ansible#12779] opened 2015-10-16 13:19 UTC
##### Issue type:
- Bug Report
##### Ansible Version:
- 1.9.2
##### Environment:
- Red Hat Enterprise Linux Server release 7.1 (Maipo) for both control and configured node
##### Summary:
- **register** is evaluated before **when** when task is ran. This leads to a situation when empty variable is registered even if when condition is false.
##### Steps To Reproduce:

Run the following playbook:

<pre>
- hosts: "localhost"
  tasks:

    - set_fact: ready_to_rock="true"

    - name: Simple cmd
      command: ls
      register: download
      when: ready_to_rock

    - name: Simple cmd
      command: ls
      when: not ready_to_rock
      register: download

    - debug: msg="{{ download }}"
</pre>

##### Expected Results:
- **download** variable should contain output of ls command
##### Actual Results:
- **download** variable is empty

There is an old issue #5817 that was opened for the same case, but correct behavior for multiple hosts should be to register a var only for hosts for which when is evaluated to true.

**Comment by sivel** [comment] 2015-10-16 13:29
This is expected behavior.  Part of the benefit is to have a registered variable that would include information that the task was skipped so you can do things like the following in a future task:

```
when: foo|skipped
```

**Comment by jimi-c** [comment] 2015-10-16 13:33
Hi @paul-vasiliev, closing as @sivel pointed out this is a feature, not a bug.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-10-16 13:33 UTC
Labels: bug

**Comment by paul-vasiliev** [comment] 2015-10-16 13:49
@sivel As I understand you are talking about the following example:

<pre>
- name: Task 1
  register: tmp
  when: condition
- name: Future task
  when: tmp
</pre>

But if you are making task conditional with **when** and then future tasks use information about whether it was skipped or not in form of registered variable, isn't it more correct to rely on **when** condition itself rather than on empty variable?

For example:

<pre>
- set_fact: condition=whatever
- name: Task 1
  register: tmp
  when: condition
- name: Future task
  when: condition
</pre>

And in future versions it may be handled by using blocks.

**Comment by jimi-c** [comment] 2015-10-17 14:17
@paul-vasiliev no, because you may care specifically if it was skipped or failed (which many people do).
