### ISSUE TITLE
ansible/ansible Github Issue Template Does Not Reflect Repomerge

### ISSUE THREAD

**Issue by kkirsche** [ansible/ansible#18870] opened 2016-12-07 16:20 UTC
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME

Github Issues Template 

##### ANSIBLE VERSION

```
N/A
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Issues template says to create issues in modules repositories, but issues get closed there due to repo merge.

##### STEPS TO REPRODUCE

Post issue in ansible/ansible-modules-extra and wait for @ansibot to close it

ansible/ansible-modules-extras#3677

##### EXPECTED RESULTS

That my issue should have been asked there. Based on this issue's template:

```
Please do not report issues/requests related to Ansible modules here !!

Report them to the appropriate modules-core or modules-extras project:
  - https://github.com/ansible/ansible-modules-core/issues
  - https://github.com/ansible/ansible-modules-extras/issues

Also verify first that your issue/request is not already reported in GitHub
```

##### ACTUAL RESULTS

The issue was closed

```
This repository has been locked. All new issues and pull requests should be filed in https://github.com/ansible/ansible

Please read through the repomerge page in the dev guide.
```

**Comment by dagwieers** [comment] 2016-12-07 16:26
This is a duplicate of #18820 and the patch is not correct.

**Comment by sivel** [comment] 2016-12-07 16:29
Closing in favor of #18820

**Closed as completed by sivel** 2016-12-07 16:29 UTC
