### ISSUE TITLE
sudo_user parameter from vars_files is taken from skipped host

### ISSUE THREAD

**Issue by dhorbach** [ansible/ansible#4137] opened 2013-09-17 12:42 UTC
A couple of month's ago (https://github.com/ansible/ansible/issues/3146) sudo_user started to accept vars from vars_files. We discovered problem when some of hosts was skipped - next host task will get wrong variable

inventory

``` yaml
[hosts]
192.168.33.10
192.168.33.11
```

playbook.yml

``` yaml
- hosts: hosts

  vars_files:
    - '{{ ansible_hostname }}.yml'


  tasks:
    - debug: msg="{{ user }}"

    - shell: echo {{ user }}

    - shell: echo {{ user }}
      when: user == "userB"
      sudo: yes
      sudo_user: ${user}
```

vm10.yml

``` yaml
user: userA
```

vm11.yml

``` yaml
user: userB
```

Result

``` shell
PLAY [hosts] ******************************************************************

GATHERING FACTS ***************************************************************
ok: [192.168.33.10]
ok: [192.168.33.11]
192.168.33.10: importing /test-concurrent-sudo-parameter/vm10.yml
192.168.33.11: importing /test-concurrent-sudo-parameter/vm11.yml

TASK: [debug msg="{{user}}"] **************************************************
ok: [192.168.33.10] => {"msg": "userA"}
ok: [192.168.33.11] => {"msg": "userB"}

TASK: [shell echo {{user}}] ***************************************************
changed: [192.168.33.10] => {"changed": true, "cmd": "echo userA ", "delta": "0:00:00.003827", "end": "2013-09-17 12:26:28.207193", "rc": 0, "start": "2013-09-17 12:26:28.203366", "stderr": "", "stdout": "userA"}
changed: [192.168.33.11] => {"changed": true, "cmd": "echo userB ", "delta": "0:00:00.003967", "end": "2013-09-17 12:26:27.170518", "rc": 0, "start": "2013-09-17 12:26:27.166551", "stderr": "", "stdout": "userB"}

TASK: [shell echo {{user}}] ***************************************************
skipping: [192.168.33.10]
failed: [192.168.33.11] => {"failed": true, "parsed": false}
invalid output was: sudo: unknown user: userA
sudo: unable to initialize policy plugin


PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/user/playbook.retry

192.168.33.10              : ok=3    changed=1    unreachable=0    failed=0
192.168.33.11              : ok=3    changed=1    unreachable=0    failed=1
```

As it's seen - userA belongs to host 192.168.33.10 but after skip used for second host
When we move user variable to shell command - it is resolved correctly (so only sudo_user is affected)

**Comment by mpdehaan** [comment] 2013-09-17 17:25
I'm not understanding what your problem is here.

Looks like it is still using user A and user B as appropriate.

**Comment by resmo** [comment] 2013-09-17 19:56
@mpdehaan 

this should not have failed (or failed saying `unknown user: userB`) because node .11 having `var11.yml` vars_file, in which we have userB.  

failed: [ **192.168.33.11** ] => {"failed": true, "parsed": false}
invalid output was: sudo: unknown user: **userA**

But the play is saying, unkonwn userA from vars_file var10.yml which is only used for .10.

**Comment by dhorbach** [comment] 2013-09-17 21:15
yes problem in "invalid output was: sudo: unknown user: userA". This should complain about unknown userB for this host but instead complains about userA for already skipped host.
I tried to minimize amount of information so this playbook is rather artificial. Everything is correct untill one of hosts is skipped.

**Comment by jimi-c** [comment] 2013-10-09 22:06
I am unable to reproduce this with the current development branch:

<pre>
PLAY [centos6] **************************************************************** 
GATHERING FACTS *************************************************************** 
ok: [awxtest1]
ok: [awxtest2]
awxtest1: importing /root/testing/awtest2.yml
awxtest2: importing /root/testing/awtest.yml
TASK: [debug msg="{{user}}"] ************************************************** 
ok: [awxtest2] => {"msg": "test2"}
ok: [awxtest1] => {"msg": "test1"}
TASK: [shell echo {{user}}] *************************************************** 
changed: [awxtest1]
changed: [awxtest2]
TASK: [shell echo {{user}}] *************************************************** 
changed: [awxtest2]
PLAY RECAP ******************************************************************** 
awxtest1                   : ok=3    changed=1    unreachable=0    failed=0   
awxtest2                   : ok=4    changed=2    unreachable=0    failed=0   
</pre>

The only thing I changed were your usernames.

**Comment by jimi-c** [comment] 2013-10-09 23:07
After further discussion, we're going to go ahead and close this, as we are unable to reproduce it. If you continue having issues, we recommend that you upgrade to the latest version, or try running ansible from source to verify that your issue will be resolved in the next release. Thanks!

**Closed as completed by jimi-c** 2013-10-09 23:07 UTC
Labels: needs_info, bug

**Comment by dhorbach** [comment] 2013-10-10 08:09
I'm still able to reproduce it with 1.3.2

```
TASK: [shell echo {{user}}] ***************************************************
skipping: [192.168.33.10]
failed: [192.168.33.11] => {"failed": true, "parsed": false}
invalid output was: sudo: unknown user: userA
sudo: unable to initialize policy plugin
```

Look at invalid output - "userA" migrated from 10 host to 11 which is wrong.

Also tested with latest ansible 1.4 (devel 3f968ff46a) last updated 2013/10/10 11:08:40 (GMT +400)

Do you need some more information?

**Comment by dhorbach** [comment] 2013-10-11 08:15
In your test you don't have "skipped" host - only in this case the issue is reproduced?
Should I raise another issue?
