### ISSUE TITLE
ansible pip module does not support range versions

### ISSUE THREAD

**Issue by gdmello** [ansible/ansible#20103] opened 2017-01-10 18:55 UTC
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
Module: ansible/lib/ansible/modules/packaging/language/pip.py

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.2.0.0
config file = 
configured module search path = Default w/o overrides
```

##### CONFIGURATION
No base config

##### OS / ENVIRONMENT
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty
```

##### SUMMARY
The pip module verifies that python libraries with a particular version are installed on the target host. However, it does not support range versions.

##### STEPS TO REPRODUCE
With support for a range version, the module could be used in a task as follows-
```yaml
- name: Verify dependencies
  pip:
    name: docker-py
    version: > 1.7.0
```

**Comment by sivel** [comment] 2017-01-10 19:01
This is a duplicate of https://github.com/ansible/ansible/pull/19690 which includes the change to support this.

**Closed as completed by sivel** 2017-01-10 19:01 UTC
