### ISSUE TITLE
--start-at-step is broken in ansible 2.0.1

### ISSUE THREAD

**Issue by goozbach** [ansible/ansible#15032] opened 2016-03-18 01:03 UTC
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

No changes
##### Environment:

CentOS 7 managing CentOS7
##### Summary:

--start-at-step switch doesn't work
##### Steps To Reproduce:

https://github.com/goozbach/ansible-steps

Use this playbook to execute the following command:

```
ansible-playbook -i inv/ site.yml --start-at-task=bar
```
##### Expected Results:

The playbook would start at the 'bar' task and complete from there:

```
[vagrant@localhost steps]$ ansible-playbook -i inv/ site.yml

PLAY [step broken] *************************************************************

TASK [bar] *********************************************************************
ok: [localhost] => {
    "msg": "bar"
}

TASK [baz] *********************************************************************
ok: [localhost] => {
    "msg": "baz"
}

TASK [qux] *********************************************************************
ok: [localhost] => {
    "msg": "qux"
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0
```
##### Actual Results:

Play doesn't run any tasks:

``````
[vagrant@localhost steps]$ ansible-playbook -i inv/ site.yml --start-at-task=bar

PLAY [step broken] *************************************************************

PLAY RECAP *********************************************************************```
``````

**Comment by mscherer** [comment] 2016-03-18 16:56
Maybe related to #15010 (as I expect they use the same code)

**Comment by nitzmahone** [comment] 2016-03-18 22:53
Yep, duplicate of #15010

**Closed as completed by nitzmahone** 2016-03-18 22:53 UTC
Labels: bug
