### ISSUE TITLE
dynamic inventory slow in 1.7

### ISSUE THREAD

**Issue by liedekef** [ansible/ansible#9291] opened 2014-10-08 13:28 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.2
##### Environment:

Centos 6
##### Summary:

dynamic inventory slow in 1.7: ansible goes through all hosts in the dynamic inventory without respect for the filtered hosts
##### Steps To Reproduce:

 When using ansible-1.4.5, the following call happens relatively fast:

ansible-playbook playbooks/test.yml -i hosts.spacewalk --extra-vars='hosts=one_server' --list-hosts

(the result should be 1 server).

With ansible-1.7.2 however, I see that ansible does the following for each host in spacewalk (in fact for each server in the output from "./hosts.spacewalk --list") the following:
hosts.spacewalk --host

This results in the script being executed about 2000 times, just to have the result for 1 server ...
##### Expected Results:

Speedy begin of ansible task after hosts info has been found
##### Actual Results:

Very slow begin of ansible because of the xxx times the script is needlessly executed.

**Comment by srgvg** [comment] 2014-10-08 17:13
@liedekef That is indeed a new behaviour starting from 1.7, but the root cause here is your inventory script which isn't optimized yet to return all data in 1 call (Throught the --list option, hence avoiding multiple calls to --host).

See http://docs.ansible.com/developing_inventory.html#tuning-the-external-inventory-script for details/

**Comment by liedekef** [comment] 2014-10-09 09:38
Although I can accept the suggestion, it is still wrong "new" behaviour IMHO.
Also, I checked the inventory scripts on https://github.com/ansible/ansible/tree/devel/plugins/inventory and it seems not many of those do that too.
So I believe the default behaviour should be corrected ... but I will try the suggestion in the link you provided.

**Comment by srgvg** [comment] 2014-10-09 09:57
Not sure why you say "wrong new behaviour". This is part of a bigger refactor of the inventory, that speeds up a lot of other things. The --host option to inventory scripts, why still supported, has always meant slower execution when loys of hosts are in the run. That is why the prefered way is to have host vars in the _meta key in the --list output.

Yes, it means some more init time at the start of the playbook, but when not limiting, you will see it's a lot faster.

I guess until now, noone really cared to update the example plugins. It doesn't mean it's the optimal situation though.

**Comment by mpdehaan** [comment] 2014-10-09 12:28
# Is This A Bug?

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We're not sure this is a bug, and we don't mean for this to be confrontational.  Let's explain what we're thinking:
- the _meta trick is how inventory needs to be optimized
- it is important for hosts not in inventory to be returned and available with variables
- the 1.7.X behavior is correct for loading the entire inventory
- not optimizing the inventory script with _meta will result in an unhappy inventory script, as shown in the docs

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists 
to talk about this and we might be persuaded otherwise.
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!

**Closed as completed by mpdehaan** 2014-10-09 12:28 UTC
Labels: bug
