### ISSUE TITLE
uri with http proxy

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#31342] opened 2017-10-05 08:47 UTC
##### ISSUE TYPE

Bug Report
##### ANSIBLE VERSION

```
2.4.0.0
```

##### OS / ENVIRONMENT

SLES 12.2
##### SUMMARY

The module not use the system proxy setting.
##### STEPS TO REPRODUCE

With a shell task and curl, the request works perfectly. However, the module does not use the system proxy settings. The set of environment variables is also ignored.  

```yaml
- name: Check is the application over the proxy available
  uri:
    url: "http://intern.example.local"
    status_code: "200"
  register: result
  until: result.status == 200
  retries: "6"
  delay: "10"
  delegate_to: localhost
  environment:
    no_proxy: .example.local
    http_proxy:
    https_proxy:

```

##### EXPECTED RESULTS

The module use the sysem proxy setting.
##### ACTUAL RESULTS

The module NOT use the sysem proxy setting.

```

```

**Comment by nitzmahone** [comment] 2017-10-06 01:04
Just out of curiosity- what does the following task output for you on the same host when run with `-v` (trying to narrow down the issue):
```
  - shell: echo $dude
    environment:
      dude: mar
```

also, are you using a shell other than bash on the SLES host?

**Comment by ghost** [comment] 2017-10-09 12:08
I have run this: 

```
---
- hosts: "some host name"
  tasks:
  - shell: echo $dude $no_proxy $http_proxy $https_proxy
    delegate_to: localhost
    environment:
      dude: mar
      no_proxy: .example.local
      http_proxy:
      https_proxy:
```
and the output was this:

```
PLAY [some host name] **********************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
ok: [host.example.local]

TASK [command] ******************************************************************************************************************************************************************************************************************************
changed: [host.example.local -> localhost] => {"changed": true, "cmd": "echo $dude $no_proxy $http_proxy $https_proxy", "delta": "0:00:00.002261", "end": "2017-10-09 13:55:08.924784", "failed": false, "rc": 0, "start": "2017-10-09 13:55:08.922523", "stderr": "", "stderr_lines": [], "stdout": "mar .example.local None None", "stdout_lines": ["mar .example.local None None"]}

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
host.example.local           : ok=2    changed=1    unreachable=0    failed=0

```

**Comment by croensch** [comment] 2017-10-10 14:51
I can confirm
```
TASK [geerlingguy.composer : Download Composer installer.] ***********************************************************************************************************************************************************************************
task path: /home/toolbox/entwicklung/devops/modules/geerlingguy.composer/tasks/main.yml:11
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/net_tools/basics/get_url.py
<192.168.9.10> ESTABLISH SSH CONNECTION FOR USER: ansible
<192.168.9.10> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansible -o ConnectTimeout=10 -o ControlPath=/home/toolbox/.ansible/cp/6907b8f5fd 192.168.9.10 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<192.168.9.10> (0, '/home/ansible\n', 'OpenSSH_6.7p1 Debian-5+deb8u3, OpenSSL 1.0.1t  3 May 2016\r\ndebug1: Reading configuration data /home/toolbox/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 29519\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<192.168.9.10> ESTABLISH SSH CONNECTION FOR USER: ansible
<192.168.9.10> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansible -o ConnectTimeout=10 -o ControlPath=/home/toolbox/.ansible/cp/6907b8f5fd 192.168.9.10 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/ansible/.ansible/tmp/ansible-tmp-1507646555.11-66549056461527 `" && echo ansible-tmp-1507646555.11-66549056461527="` echo /home/ansible/.ansible/tmp/ansible-tmp-1507646555.11-66549056461527 `" ) && sleep 0'"'"''
<192.168.9.10> (0, 'ansible-tmp-1507646555.11-66549056461527=/home/ansible/.ansible/tmp/ansible-tmp-1507646555.11-66549056461527\n', 'OpenSSH_6.7p1 Debian-5+deb8u3, OpenSSL 1.0.1t  3 May 2016\r\ndebug1: Reading configuration data /home/toolbox/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 29519\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<192.168.9.10> PUT /tmp/tmpwvrsPm TO /home/ansible/.ansible/tmp/ansible-tmp-1507646555.11-66549056461527/get_url.py
<192.168.9.10> SSH: EXEC sftp -b - -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansible -o ConnectTimeout=10 -o ControlPath=/home/toolbox/.ansible/cp/6907b8f5fd '[192.168.9.10]'
<192.168.9.10> (0, 'sftp> put /tmp/tmpwvrsPm /home/ansible/.ansible/tmp/ansible-tmp-1507646555.11-66549056461527/get_url.py\n', 'OpenSSH_6.7p1 Debian-5+deb8u3, OpenSSL 1.0.1t  3 May 2016\r\ndebug1: Reading configuration data /home/toolbox/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 29519\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug2: Remote version: 3\r\ndebug2: Server supports extension "posix-rename@openssh.com" revision 1\r\ndebug2: Server supports extension "statvfs@openssh.com" revision 2\r\ndebug2: Server supports extension "fstatvfs@openssh.com" revision 2\r\ndebug2: Server supports extension "hardlink@openssh.com" revision 1\r\ndebug2: Server supports extension "fsync@openssh.com" revision 1\r\ndebug3: Sent message fd 6 T:16 I:1\r\ndebug3: SSH_FXP_REALPATH . -> /home/ansible size 0\r\ndebug3: Looking up /tmp/tmpwvrsPm\r\ndebug3: Sent message fd 6 T:17 I:2\r\ndebug3: Received stat reply T:101 I:2\r\ndebug1: Couldn\'t stat remote file: No such file or directory\r\ndebug3: Sent message SSH2_FXP_OPEN I:3 P:/home/ansible/.ansible/tmp/ansible-tmp-1507646555.11-66549056461527/get_url.py\r\ndebug3: Sent message SSH2_FXP_WRITE I:4 O:0 S:32768\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 4 32768 bytes at 0\r\ndebug3: Sent message SSH2_FXP_WRITE I:5 O:32768 S:32768\r\ndebug3: Sent message SSH2_FXP_WRITE I:6 O:65536 S:24421\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 5 32768 bytes at 32768\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 6 24421 bytes at 65536\r\ndebug3: Sent message SSH2_FXP_CLOSE I:4\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<192.168.9.10> ESTABLISH SSH CONNECTION FOR USER: ansible
<192.168.9.10> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansible -o ConnectTimeout=10 -o ControlPath=/home/toolbox/.ansible/cp/6907b8f5fd 192.168.9.10 '/bin/sh -c '"'"'chmod u+x /home/ansible/.ansible/tmp/ansible-tmp-1507646555.11-66549056461527/ /home/ansible/.ansible/tmp/ansible-tmp-1507646555.11-66549056461527/get_url.py && sleep 0'"'"''
<192.168.9.10> (0, '', 'OpenSSH_6.7p1 Debian-5+deb8u3, OpenSSL 1.0.1t  3 May 2016\r\ndebug1: Reading configuration data /home/toolbox/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 29519\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<192.168.9.10> ESTABLISH SSH CONNECTION FOR USER: ansible
<192.168.9.10> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansible -o ConnectTimeout=10 -o ControlPath=/home/toolbox/.ansible/cp/6907b8f5fd -tt 192.168.9.10 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-dhmxclapnauymwparcjcnotshsqlhfke; /usr/bin/python /home/ansible/.ansible/tmp/ansible-tmp-1507646555.11-66549056461527/get_url.py; rm -rf "/home/ansible/.ansible/tmp/ansible-tmp-1507646555.11-66549056461527/" > /dev/null 2>&1'"'"'"'"'"'"'"'"' && sleep 0'"'"''
```
settings are in ```/etc/environment``` as well as ```/etc/sudoers.d/10proxy```: ```Defaults env_keep += HTTP_PROXY``` ...and so on. They work for commands with become.
After reading module_utils/urls.py has wrappers and stuff i tried to get the imports of requests/urllib3/pyopenssl running.. ```requests.packages.urllib3.contrib.pyopenssl``` is still not importable on vagrant debian stretch (requests-2.12.4)
Might be influenced by https://github.com/requests/requests/issues/3287

**Comment by tallandtree** [comment] 2017-11-01 15:55
I have the same issue. The module uri does use the http_proxy setting, but ignores the no_proxy setting if the format '.domain.org' is being used for no_proxy.

This fails with a gateway timeout due to arriving at our http proxy instead at server.domain.org:

```
--
- hosts: "all"
  environment:
    http_proxy: 'http://proxy:8080'
    https_proxy: 'http://proxy:8080'
    no_proxy: '.domain.org'
  tasks:
  - name: uri
    uri:
      url: "http://server.domain.org:8081"

```

This runs ok:
```
--
- hosts: "all"
  environment:
    http_proxy: 'http://proxy:8080'
    https_proxy: 'http://proxy:8080'
    no_proxy: 'server.domain.org'
  tasks:
  - name: uri
    uri:
      url: "http://server.domain.org:8081"
```

**Comment by ghost** [comment] 2017-11-04 11:31
I will check this. I think this is the solution fro my. 
Thank you.

**Comment by ghost** [comment] 2017-11-06 08:01
This work for my:

<pre>
- name: Check is the application over the proxy available
  uri:
    url: "http://intern.example.local"
    status_code: "200"
  register: result
  until: result.status == 200
  retries: "6"
  delay: "10"
  delegate_to: localhost
  environment:
    no_proxy: intern.example.local
    http_proxy:
    https_proxy:
</pre>

**Comment by bcoca** [comment] 2019-04-05 15:04
closing as per above

**Closed as completed by bcoca** 2019-04-05 15:04 UTC
Labels: affects_2.4, support:core, bug
