### ISSUE TITLE
with_items does not work as expected in yum module

### ISSUE THREAD

**Issue by Firehed** [ansible/ansible#10355] opened 2015-02-27 19:38 UTC
An optimization in executing the yum module (and by the looks of it, also apt, pkgng, and zypper) causes dynamic names not to be evaluated as expected. An example of this problem is demonstrated in this gist: https://gist.github.com/Firehed/7e044873b371fcbdceb8

The source of the issue appears to be in `runner/__init__.py:750-758`

While using a less-dynamic approach was suggested in IRC, it's not an acceptable solution for the infrastructure we're using. It's easy enough to work around with more verbose syntax, but the point still stands that the interaction between `with_items` and `yum` doesn't work as expected.

Suggestion for resolution: expand the jinja2 templating when converting the item list to a single item. I'd include a patch but don't know the internals well enough at the moment. If such a resolution would be accepted with a patch, I'm willing to do some research and create one.

If it's relevant, this is from 1.8.2_1 installed via homebrew on OS X.

**Comment by bcoca** [comment] 2015-02-27 19:42
closing this as it is a dupe of https://github.com/ansible/ansible/issues/9235

@Firehed this has been on my todo list to make the feature 'smarter' for a while, but I'll be happy if someone else is able to make a patch for it.

**Comment by Firehed** [comment] 2015-02-27 19:43
Ah, only searched for yum and not apt. Sorry about the dupe! I'll look into creating a patch if I get some extra time.

**Closed as completed by bcoca** 2015-02-27 19:42 UTC
Labels: bug, packaging

**Comment by Firehed** [comment] 2015-02-27 20:48
Just in case someone comes across this later - here was my workaround: https://gist.github.com/Firehed/e2330c101d070cc22316
