### ISSUE TITLE
etcd lookup plugin does not support v2 API

### ISSUE THREAD

**Issue by scheetz** [ansible/ansible#16071] opened 2016-05-31 16:22 UTC
##### ISSUE TYPE

- Feature Idea
##### ANSIBLE VERSION

```
ansible 1.9.4
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

The current version of etcd (2.x) does not support the deprecated v1 api.  The v1 api is the only one supported by the etcd ansible lookup plugin.
##### STEPS TO REPRODUCE
1. Deploy a current version of etcd: `docker run --net=host --rm quay.io/coreos/etcd:v2.3.6`
2. Add key to etcd: `etcdctl set foo bar`
3. Create a playbook named etcd.yml as shown below
4. Run playbook: `ansible-playbook -i "localhost," etcd.yml`

```

---
- name: Test etcd lookup
  hosts: localhost
  tasks:
    - debug: msg="etcd foo = {{ lookup('etcd2', 'foo') }}"
```
##### EXPECTED RESULTS

```
PLAY [Test etcd lookup] *******************************************************

GATHERING FACTS ***************************************************************
ok: [localhost]

TASK: [debug msg="etcd foo = bar"] ********************************************
ok: [localhost] => {
    "msg": "etcd foo = bar"
}

PLAY RECAP ********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```
##### ACTUAL RESULTS

```
PLAY [Test etcd lookup] *******************************************************

GATHERING FACTS ***************************************************************
ok: [localhost]

TASK: [debug msg="etcd foo = "] ***********************************************
ok: [localhost] => {
    "msg": "etcd foo = "
}

PLAY RECAP ********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

**Comment by bcoca** [comment] 2016-06-28 18:39
closing as duplicate of #13946

**Closed as completed by bcoca** 2016-06-28 18:39 UTC
Labels: feature
