### ISSUE TITLE
Cannot use include_role with vars as documented

### ISSUE THREAD

**Issue by snowleopard75** [ansible/ansible#38220] opened 2018-04-03 14:32 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
include_role

##### ANSIBLE VERSION
2.4.2
```
ansible 2.4.2.0
  config file = /ansible/ansible.cfg
  configured module search path = [u'/ansible']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
ANSIBLE_SSH_ARGS(/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=60s -o ForwardAgent=yes
ANSIBLE_SSH_CONTROL_PATH_DIR(/ansible/ansible.cfg) = ./.ansible/cp
COMMAND_WARNINGS(/ansible/ansible.cfg) = False
DEFAULT_BECOME(/ansible/ansible.cfg) = True
DEFAULT_GATHERING(/ansible/ansible.cfg) = smart
DEFAULT_GATHER_TIMEOUT(/ansible/ansible.cfg) = 60
DEFAULT_HOST_LIST(/ansible/ansible.cfg) = [u'/ansible/inventories/local.py']
DEFAULT_LOCAL_TMP(/ansible/ansible.cfg) = /tmp/ansible-local-71nKyyh2
DEFAULT_MODULE_PATH(/ansible/ansible.cfg) = [u'/ansible']
DEFAULT_REMOTE_TMP(/ansible/ansible.cfg) = /tmp
DEFAULT_ROLES_PATH(/ansible/ansible.cfg) = [u'/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/ansible/ansible.cfg) = default
DEFAULT_TIMEOUT(/ansible/ansible.cfg) = 60
DEFAULT_VAULT_PASSWORD_FILE(/ansible/ansible.cfg) = /home/tv-ansible/.ansible/.vault-pass
DEPRECATION_WARNINGS(/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/ansible/ansible.cfg) = False
PERSISTENT_CONNECT_TIMEOUT(/ansible/ansible.cfg) = 30
RETRY_FILES_ENABLED(/ansible/ansible.cfg) = False
SYSTEM_WARNINGS(/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT
Ubuntu 16.04.1

##### SUMMARY
As documented in the examples here: http://docs.ansible.com/ansible/latest/modules/include_role_module.html, it seems we should be able to specify vars along with the include_role module.

##### STEPS TO REPRODUCE
Run the following playbook (test.yml):
```yaml
- hosts: localhost
  gather_facts: false

  tasks:
    - name: "Call some role"
      include_role:
        name: "some-role"
      vars:
        some_var: "foo"
```

##### EXPECTED RESULTS
Expected 'some_var' to be passed to 'some-role'.  Role 'some-role' should exist somewhere, but even if it doesn't, as in this test, it fails before role evaluation. I tried to keep the example simple.

I thought at first this was an indentation error on my part, but I've tried everything and cannot get this to work. I've seen multiple examples of this usage online, did something change and the documentation is out of date?

##### ACTUAL RESULTS
**ERROR! conflicting action statements: include_role, vars**

ansible-playbook test.yml
```
ansible-playbook 2.4.2.0
  config file = /ansible/ansible.cfg
  configured module search path = [u'/ansible']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
Using /ansible/ansible.cfg as config file
Parsed /ansible/inventories/local.py inventory source with script plugin
ERROR! conflicting action statements: include_role, vars

The error appears to have been in '/ansible/test.yml': line 5, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: "Call some role"
      ^ here

```

**Comment by sivel** [comment] 2018-04-03 14:42
This is likely the result of having a file named something like:

* `vars`
* `vars.yml`
* `vars.py`
* `vars.json`

Living in a directory where ansible looks for modules.  Potentially either within `/ansible` or within a directory called `library` next to your playbook. The extension does not matter, as it is not considered when looking for modules.

There is an open pull request that should help provide a better error message in the future at https://github.com/ansible/ansible/pull/34649

needs_info

**Comment by sivel** [comment] 2018-04-26 20:04
I'm going to go ahead and close this as the issue is related to extraneous user files.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Closed as completed by sivel** 2018-04-26 20:04 UTC
Labels: affects_2.4, support:core, bug
