### ISSUE TITLE
ansible-vault decrypt doesn't recognise --vault-password-file

### ISSUE THREAD

**Issue by fawkesley** [ansible/ansible#8940] opened 2014-09-09 14:19 UTC
##### Issue Type:

“Bug Report”
##### Ansible Version:

ansible 1.7.1
##### Environment:

Ubuntu 12.04, Python 2.7.3 in virtualenv.
##### Summary:

I use this often with no problem:

```
ansible-vault edit myfile.yml.encrypted --vault-password-file=~/ansible_password
```

But this fails:

```
ansible-vault decrypt myfile.yml.encrypted --vault-password-file=~/ansible_password
```

with `ERROR: Values instance has no attribute 'vault_password_file'`
##### Steps To Reproduce:

```
openssl rand -base64 12 > /tmp/ansible-password
echo 'foo: bar' > /tmp/file.yml
ansible-vault encrypt /tmp/file.yml --vault-password-file=/tmp/ansible-password
ansible-vault edit /tmp/file.yml --vault-password-file=/tmp/ansible-password
ansible-vault decrypt /tmp/file.yml --vault-password-file=/tmp/ansible-password
```
##### Expected Results:

The decrypt command should decrypt the file.
##### Actual Results:

I get `ERROR: Values instance has no attribute 'vault_password_file'`

**Comment by abadger** [comment] 2014-09-09 16:53
# Closing This Ticket

Hi @paulfurley, This looks like a duplicate of #8752  which should be fixed by 206c201d871beeaa903954b7d5f56a77b99b044d

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Closed as completed by abadger** 2014-09-09 16:53 UTC
Labels: P1, bug

**Comment by abadger** [comment] 2014-09-09 16:55
@paulfurley - Just so you know, I verified that your test case decrypts the file with the code in the development tree.  Thanks again for reporting!

**Comment by fawkesley** [comment] 2014-09-09 16:57
Thanks @abadger and apologies for the dupe - I looked but github's issue list isn't the best :)
