### ISSUE TITLE
Docs: Add version selector for ansible core and module documentation

### ISSUE THREAD

**Issue by mightydok** [ansible/ansible#21283] opened 2017-02-11 11:36 UTC
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
Ansible core and all modules

##### ANSIBLE VERSION
all

##### SUMMARY
Documentation at http://docs.ansible.com/ dont allow to choose version, but sphinx and RTD have that options: http://joxi.ru/RmzQPL3teMvKrO

**Comment by bcoca** [comment] 2017-02-13 17:29
closing as dupe of #13858

**Closed as completed by bcoca** 2017-02-13 17:29 UTC
Labels: affects_2.3, docs, feature
