### ISSUE TITLE
Ansible uses "command" module instead of "shell"

### ISSUE THREAD

**Issue by aabdnn** [ansible/ansible#21244] opened 2017-02-10 13:19 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible-playbook

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
```
ANSIBLE_HOST_KEY_CHECKING=no
ANSIBLE_SSH_PIPELINING=yes
ANSIBLE_INVENTORY=/Users/anandb/repo/ansible/hosts
ANSIBLE_GATHERING=smart
ANSIBLE_REMOTE_TEMP=/tmp
ANSIBLE_SSH_CONTROL_PATH=/tmp/%%r@%%h
ANSIBLE_HASH_BEHAVIOUR=merge
ANSIBLE_TIMEOUT=75
ANSIBLE_RETRY_FILES_ENABLED=no
```

##### OS / ENVIRONMENT
MacOS X 10.12.3

##### SUMMARY
A task in a playbook is defined to use the "shell" module, but ansible runs this task with the "command" module instead.

##### STEPS TO REPRODUCE
Run this task using ansible-playbook on some host:

```yaml
- name: run a shell command
  shell: pkill -HUP /usr/bin/nsd || true
```

##### EXPECTED RESULTS
The pkill should have failed, and caused the shell to run "true" and the overall task should have passed.

##### ACTUAL RESULTS
Instead, it gets run with the "command" module, and since the command module does not know about the shell operators, it fails: 
```
Using module file /usr/local/lib/python2.7/site-packages/ansible/modules/core/commands/command.py
<ns1.nl-ams.testdns.ripe.net> ESTABLISH SSH CONNECTION FOR USER: None
<ns1.nl-ams.testdns.ripe.net> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=75 -o ControlPath=/tmp/%r@%h ns1.nl-ams.testdns.ripe.net '/bin/sh -c '"'"'sudo -H -S  -p "[sudo via ansible, key=ylyilxbqksbykhyhzjdjgqvuodnhjvcy] password: " -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-ylyilxbqksbykhyhzjdjgqvuodnhjvcy; /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
fatal: [ns1.nl-ams.testdns.ripe.net]: FAILED! => {
    "changed": true, 
    "cmd": "pkill -HUP -f /usr/bin/nsd || true", 
    "delta": "0:00:00.023935", 
    "end": "2017-02-10 13:05:19.495286", 
    "failed": true, 
    "invocation": {
        "module_args": {
            "_raw_params": "pkill -HUP -f /usr/bin/nsd || true", 
            "_uses_shell": true, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "warn": true
        }, 
        "module_name": "command"
    }, 
    "rc": -1, 
    "start": "2017-02-10 13:05:19.471351", 
    "stderr": "", 
    "stdout": "", 
    "stdout_lines": [], 
    "warnings": []
}
```

**Comment by jctanner** [comment] 2017-02-10 14:01
The shell and command modules are the same module. The only difference is that final call to subprocess.Popen includes "shell=True" as an argument.

https://docs.python.org/2/library/subprocess.html#popen-constructor

So the issue is not with the module, but with the commands. Try removing the double pipe + true to validate the initial command works under subproce.Popen and then go from there.

needs_info

**Comment by aabdnn** [comment] 2017-02-10 14:21
Hi @jctanner. On the target server, the command works as I expect:

```
# pkill -HUP -f /usr/bin/nsd
# echo $?
1
# pkill -HUP -f /usr/bin/nsd || true
# echo $?
0
```

So the pkill is failing with exit code 1. You can see that in the first output. So then I add "|| true", and as expected, the exit code is 0.

If I do this with ansible, then this is what I see:

```
fatal: [ns1.nl-ams.testdns.ripe.net]: FAILED! => {
    "changed": true, 
    "cmd": "pkill -HUP -f /usr/bin/nsd", 
    "delta": "0:00:00.024562", 
    "end": "2017-02-10 14:19:30.121218", 
    "failed": true, 
    "invocation": {
        "module_args": {
            "_raw_params": "pkill -HUP -f /usr/bin/nsd", 
            "_uses_shell": true, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "warn": true
        }, 
        "module_name": "command"
    }, 
    "rc": 1, 
    "start": "2017-02-10 14:19:30.096656", 
    "stderr": "", 
    "stdout": "", 
    "stdout_lines": [], 
    "warnings": []
}
```

Notice that the return code is 1 (and that's why the task fails). Finally, if I add "|| true" to the task, then I get a different return code:

```
fatal: [ns1.nl-ams.testdns.ripe.net]: FAILED! => {
    "changed": true, 
    "cmd": "pkill -HUP -f /usr/bin/nsd || true", 
    "delta": "0:00:00.015186", 
    "end": "2017-02-10 14:21:06.950913", 
    "failed": true, 
    "invocation": {
        "module_args": {
            "_raw_params": "pkill -HUP -f /usr/bin/nsd || true", 
            "_uses_shell": true, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "warn": true
        }, 
        "module_name": "command"
    }, 
    "rc": -1, 
    "start": "2017-02-10 14:21:06.935727", 
    "stderr": "", 
    "stdout": "", 
    "stdout_lines": [], 
    "warnings": []
}
```

I get -1 as the exit code, whereas I expected the return code to be 0, and the task to succeed.

**Comment by bcoca** [comment] 2017-02-10 14:24
@aabdnn the task should succeed, but it is not due to using the wrong module.

As a workaround I suggest using `failed_when: False`

**Comment by aabdnn** [comment] 2017-02-10 14:27
@bcoca thanks. I actually applied a work-around by adding "ignore_errors: true" to the task, but there does seem to be a bug in the command module.

**Comment by dagwieers** [comment] 2017-02-13 11:36
aabdnn: Does the default shell actually work ? Through sudo. Otherwise you have to tell the shell-action to use a different executable using `executable: /bin/bash`. Or try using the `raw` module (hoping it may trigger something useful).

The return code -1 is very peculiar as this is not a shell return code. So somehow I assume that Ansible/SSH is unable to do something basic to your server somehow. I cannot find a -1 return code in these codepaths in Ansible though :-/

You could also test yourself end-to-end without the use of Ansible.

```
ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=75 -o ControlPath=/tmp/%r@%h ns1.nl-ams.testdns.ripe.net '/bin/sh -c '"'"'sudo -H -S  -p "[sudo via ansible, key=ylyilxbqksbykhyhzjdjgqvuodnhjvcy] password: " -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-ylyilxbqksbykhyhzjdjgqvuodnhjvcy; /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
```

BTW that quoting looks horrible :-/

**Comment by sivel** [comment] 2018-06-26 19:15
I am going to proceed with closing this issue.

There have been no updates in over a year, and the OP reported having implemented a working solution.

If you are still having problems, feel free to open a new issue with a full reproducer.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Closed as completed by sivel** 2018-06-26 19:15 UTC
Labels: affects_2.2, module, support:core, bug
