### ISSUE TITLE
'make deb' fails because of inconsistency in the archive name

### ISSUE THREAD

**Issue by themr0c** [ansible/ansible#13429] opened 2015-12-04 08:43 UTC
`make deb` is first creating `dist/ansible-2.1.0.tar.gz`, but then tries to open  `dist/ansible-2.1.tar.gz`.

It should use the same name for that archive.

```
make deb
[... snip ...]
hard linking packaging/rpm/ansible.spec -> ansible-2.1.0/packaging/rpm
Writing ansible-2.1.0/setup.cfg
creating dist
Creating tar archive
removing 'ansible-2.1.0' (and everything under it)
tar: dist/ansible-2.1.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
sed: can't read deb-build/unstable/ansible-2.1/debian/changelog: No such file or directory
Makefile:220: recipe for target 'debian' failed
make: *** [debian] Error 2

ls dist/ -alh
total 1.4M
drwxr-xr-x 1 fft fft   40 Dec  4 09:35 .
drwxr-xr-x 1 fft fft  598 Dec  4 09:35 ..
-rw-r--r-- 1 fft fft 1.4M Dec  4 09:35 ansible-2.1.0.tar.gz
```

**Comment by archonik** [comment] 2015-12-04 09:22
make rpm has the same error

```
removing 'ansible-2.1.0' (and everything under it)
error: File /var/www/ansible/rpm-build/ansible-2.1.tar.gz: No such file or directory
make: *** [rpm] Error 1
```

**Comment by abadger** [comment] 2015-12-04 23:27
Did this fix things? 1eb0a1ddf7cf2f9501ea48915307652e8ab55049

**Comment by archonik** [comment] 2015-12-05 09:05
Yep that fixed it at least in make rpm

```
+ exit 0
#############################################
Ansible RPM is built:
    rpm-build/ansible-2.1.0-0.git201512050647.fa71c38.devel.el6.noarch.rpm
#############################################
```

**Comment by bcoca** [comment] 2015-12-05 15:16
i need to call my grade school math teacher and let her know that trailing 0s right of the dot are still significant!

**Comment by themr0c** [comment] 2015-12-10 10:16
it's a good workaround, but it won't fix deeply the issue: the Makefile doesn't use the same source of information to define a name to create the archive, and then to define it again to decompress it.

**Comment by bcoca** [comment] 2015-12-10 14:44
@themr0c agreed, its been on my list to fix that, but if anyone can beat me too it....

**Comment by abadger** [comment] 2015-12-10 15:46
<nod>  Going to close this issue since the problem is fixed but I definitely agree with @bcoca that we'd love a cleanup that puts the version string in one place.  @jimi-c had some idea of which place he wanted to be the canonical source but I don't think he'd decided which of those places was the one he liked most.

**Closed as completed by abadger** 2015-12-10 15:46 UTC
Labels: pending_action, bug
