### ISSUE TITLE
Unarchive fails unpacking non-ascii file on OS X

### ISSUE THREAD

**Issue by joemaller** [ansible/ansible#17022] opened 2016-08-09 19:11 UTC
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

Unarchive module
##### ANSIBLE VERSION

Both 2.1.1.0 and 2.1.0.0 on multiple Macs.

```
ansible 2.1.1.0
  config file = 
  configured module search path = Default w/o overrides
```

also 

```
ansible 2.1.0.0
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

No special settings. default config.
##### OS / ENVIRONMENT

Mac OS X version 10.11.6, installed via Homebrew
##### SUMMARY

The Unarchive module fails when trying to _locally_ download/expand the current Ansible snapshot from GitHub. (https://github.com/ansible/ansible/archive/devel.zip The playbook in this report is downloading the equivalent archive based on the last-commited hash.)

Note that the archive can be manually downloaded and expanded on OS X.

Found this while trying to isolate a different problem with the Unarchive module related to #17009.
##### STEPS TO REPRODUCE

Ran this command: 

```
ansible-playbook -vvv ~/Desktop/ansible-local-test.yaml
```

Complete playbook:

```

---

- hosts: localhost
  become: no
  connection: local

  tasks:
    - name: Download & Unpack zip archive
      unarchive: 
        src: https://github.com/ansible/ansible/archive/df81f1197f01ff29e2f3afeea228daf7d3ec81bb.zip
        dest: /tmp/
        copy: no


```
##### EXPECTED RESULTS

Archive downloads and unpacks. 
##### ACTUAL RESULTS

Module failure.

```
No config file found; using defaults
 [WARNING]: Host file not found: /usr/local/etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available


PLAYBOOK: ansible-local-test.yaml **********************************************
1 plays in /Users/joe/Desktop/ansible-local-test.yaml

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: joe
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1470768855.09-223451903953364 `" && echo ansible-tmp-1470768855.09-223451903953364="` echo $HOME/.ansible/tmp/ansible-tmp-1470768855.09-223451903953364 `" ) && sleep 0'
<127.0.0.1> PUT /var/folders/f2/lskp80tm8xj5230059b53f580000gp/T/tmpUDTEJa TO /Users/joe/.ansible/tmp/ansible-tmp-1470768855.09-223451903953364/setup
<127.0.0.1> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /Users/joe/.ansible/tmp/ansible-tmp-1470768855.09-223451903953364/setup; rm -rf "/Users/joe/.ansible/tmp/ansible-tmp-1470768855.09-223451903953364/" > /dev/null 2>&1 && sleep 0'
ok: [localhost]

TASK [Download & Unpack zip archive] *******************************************
task path: /Users/joe/Desktop/ansible-local-test.yaml:16
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: joe
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1470768856.18-10151565722253 `" && echo ansible-tmp-1470768856.18-10151565722253="` echo $HOME/.ansible/tmp/ansible-tmp-1470768856.18-10151565722253 `" ) && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1470768856.29-136530177465962 `" && echo ansible-tmp-1470768856.29-136530177465962="` echo $HOME/.ansible/tmp/ansible-tmp-1470768856.29-136530177465962 `" ) && sleep 0'
<127.0.0.1> PUT /var/folders/f2/lskp80tm8xj5230059b53f580000gp/T/tmp5mz6bv TO /Users/joe/.ansible/tmp/ansible-tmp-1470768856.29-136530177465962/stat
<127.0.0.1> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /Users/joe/.ansible/tmp/ansible-tmp-1470768856.29-136530177465962/stat; rm -rf "/Users/joe/.ansible/tmp/ansible-tmp-1470768856.29-136530177465962/" > /dev/null 2>&1 && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1470768856.64-39284039925999 `" && echo ansible-tmp-1470768856.64-39284039925999="` echo $HOME/.ansible/tmp/ansible-tmp-1470768856.64-39284039925999 `" ) && sleep 0'
<127.0.0.1> PUT /var/folders/f2/lskp80tm8xj5230059b53f580000gp/T/tmpwQtO7G TO /Users/joe/.ansible/tmp/ansible-tmp-1470768856.64-39284039925999/unarchive
<127.0.0.1> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /Users/joe/.ansible/tmp/ansible-tmp-1470768856.64-39284039925999/unarchive; rm -rf "/Users/joe/.ansible/tmp/ansible-tmp-1470768856.64-39284039925999/" > /dev/null 2>&1 && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /Users/joe/.ansible/tmp/ansible-tmp-1470768856.18-10151565722253/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {"changed": false, "dest": "/tmp/", "failed": true, "gid": 0, "group": "wheel", "handler": "TgzArchive", "invocation": {"module_args": {"backup": null, "content": null, "copy": false, "creates": null, "delimiter": null, "dest": "/tmp/", "directory_mode": null, "exclude": [], "extra_opts": [], "follow": false, "force": null, "group": null, "keep_newer": false, "list_files": false, "mode": null, "original_basename": "df81f1197f01ff29e2f3afeea228daf7d3ec81bb.zip", "owner": null, "regexp": null, "remote_src": null, "selevel": null, "serole": null, "setype": null, "seuser": null, "src": "https://github.com/ansible/ansible/archive/df81f1197f01ff29e2f3afeea228daf7d3ec81bb.zip"}}, "mode": "01777", "msg": "Unexpected error when accessing exploded file: [Errno 2] No such file or directory: '/tmp/ansible-df81f1197f01ff29e2f3afeea228daf7d3ec81bb/'", "owner": "root", "size": 1224, "src": "/private/var/folders/f2/lskp80tm8xj5230059b53f580000gp/T/ansible_uoZAK4/df81f1197f01ff29e2f3afeea228daf7d3ec81bb.zip", "state": "directory", "uid": 0}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @/Users/joe/Desktop/ansible-local-test.retry

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   

```

**Comment by dagwieers** [comment] 2016-08-11 14:10
Right, if you specify a URL (so it needs to download something) it requires/assumes you are using `copy: yes`. As a result Ansible assumes the fancy URL is an existing file name (remote, but in your case local).

I know that the whole naming of the option **copy** is highly confusing (and I think it was a big mistake, not just the naming, but also adding too much functionality to a module). The option **copy** basically means "the file is not already there by some other means" and _there_ means the target system.

In the latest version it was decided to rename the **copy** option, **remote_src** which does not fix the confusion because in your case the remote system is actually your local system. Just so you know.

_(Good naming is so important, but often easily overlooked IMO)_

notabug

**Comment by dagwieers** [comment] 2016-08-11 14:14
Well, it is not a bug, but I do think there is room for improvement, i.e. we could make URL detection possible and simply do the right thing if we detect that a (supported) URL is specified. That way it wouldn't matter what the **copy** or **remote_src** option states.

**Comment by bcoca** [comment] 2016-08-11 14:36
I'm of a mind to deprecate this feature. 

Adding features of existing modules into other modules end up with not only duplicate code, but it lacks completeness and ends up failing with the corner cases the specialized module already handles.

**Comment by dagwieers** [comment] 2016-08-11 15:21
@bcoca I agree wholeheartedly. Although I do understand it is convenient to have a single task do the copy/use/remove, which is something that Ansible has no easy solution for.

But in this case there is a whole set of options (certificate, authentication, protocols, etc...) that it becomes a mess really quickly if we accept every possible use-case from within unarchive.

Maybe this fits in the whole plan to deprecate **unachive** in favor of an **uncompress** module that is pure-python and supports compressed files. (cfr. a new pure-python **compress** module)

**Comment by joemaller** [comment] 2016-08-11 15:23
@bcoca my workaround for https://github.com/ansible/ansible-modules-core/pull/4244 (and #17009) will likely be reverting to a pre-2.0 get_url + unarchive set of tasks. I do appreciate the convenience of one-step download-and-expand task since it's such a common need, but two simple and explicit tasks are easier to debug.

**Comment by bcoca** [comment] 2016-08-11 17:13
@dagwieers , @joemaller  need to get `include_role` working an then all these issues are mute.

**Comment by dagwieers** [comment] 2016-08-11 22:38
@bcoca Do you have a link to understand how this helps ?

**Comment by bcoca** [comment] 2016-08-11 23:51
feel free to ignore my rants, but https://github.com/ansible/proposals/blob/master/roles_revamp.md and https://github.com/ansible/proposals/pull/27#issuecomment-239060368

**Comment by dagwieers** [comment] 2016-08-12 10:59
Can we close this issue ? Or turn it into an improvement ?

**Comment by joemaller** [comment] 2016-08-12 11:25
@dagwieers I think this issue revealed a specific problem with unarchive module file handling on Macs. It should probably have been reported on [ansible/ansible-modules-core](https://github.com/ansible/ansible-modules-core). I will check whether it's fixed in devel later this morning.

**Comment by dagwieers** [comment] 2016-08-12 12:13
@joemaller As I noted [here](https://github.com/ansible/ansible/issues/17022#issuecomment-239172265) the problem is that you provided a URL, but stated **copy: no**. It should state **copy: yes** if you are going to provide a URL and you expect Ansible to download the file for you.

So it is not a bug, and it is not specific to MacOSX.

notabug

**Comment by bcoca** [comment] 2016-08-12 14:21
closing as per above

**Closed as completed by bcoca** 2016-08-12 14:21 UTC
Labels: m:unarchive, bug, macos

**Comment by joemaller** [comment] 2016-08-12 14:25
I believe there is still an issue here, and it's not related to `copy: no`, which wouldn't have applied to v2.1.0.0 anyway. 

However, https://github.com/ansible/ansible-modules-core/issues/4390 maybe confounding the error. 

Test version:

```
ansible 2.2.0 (devel 4cee67452b) last updated 2016/08/12 10:35:32 (GMT -400)
  lib/ansible/modules/core: (devel decb2ec9fa) last updated 2016/08/12 10:36:22 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 61d5fe148c) last updated 2016/08/12 10:35:58 (GMT -400)
  config file = 
  configured module search path = Default w/o overrides
```

I further reduced the playbook to remove the local action, remote_src and stopped targeting Macs:

```
---

- hosts: all

  tasks:
    - name: Unpack zip archive
      unarchive: 
        # snapshot of Ansible repo from GitHub
        # https://github.com/ansible/ansible/archive/df81f1197f01ff29e2f3afeea228daf7d3ec81bb.zip
        src: /tmp/df81f1197f01ff29e2f3afeea228daf7d3ec81bb.zip
        dest: /tmp/
```

Running against an Ubuntu 14.04 VM, I get this error, which matches my original report:

```
fatal: [vagrant]: FAILED! => {
  "changed": true,
  "dest": "/tmp/",
  "extract_results": {
    "cmd": "...",
    "err": "",
    "out": "...",
    "rc": 0
  },
  "failed": true,
  "gid": 0,
  "group": "root",
  "handler": "ZipArchive",
  "mode": "01777",
  "msg": "Unexpected error when accessing exploded file: [Errno 2] No such file or directory: '/tmp/ansible-df81f1197f01ff29e2f3afeea228daf7d3ec81bb/test/integration/roles/test_unarchive/files/test-unarchive-nonascii-\\xe3\\x81\\x8f\\xe3\\x82\\x89\\xe3\\x81\\xa8\\xe3\\x81\\xbf.tar.gz'",
  "owner": "root",
  "size": 4096,
  "src": "/home/vagrant/.ansible/tmp/ansible-tmp-1471011213.69-111868542975585/source",
  "state": "directory",
  "uid": 0
}
```

The file transfers and expands, the error seems to happen while trying to match the special characters in the expanded filename.

A second run (with the files already transferred and expanded) produces this:

```
PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [vagrant]

TASK [Unpack zip archive] ******************************************************
fatal: [vagrant]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_y5fmkt/ansible_module_unarchive.py\", line 824, in <module>\r\n    main()\r\n  File \"/tmp/ansible_y5fmkt/ansible_module_unarchive.py\", line 783, in main\r\n    check_results = handler.is_unarchived()\r\n  File \"/tmp/ansible_y5fmkt/ansible_module_unarchive.py\", line 444, in is_unarchived\r\n    if crc != self._crc32(path):\r\n  File \"/tmp/ansible_y5fmkt/ansible_module_unarchive.py\", line 201, in _crc32\r\n    return self._infodict[path]\r\nKeyError: 'ansible-df81f1197f01ff29e2f3afeea228daf7d3ec81bb/test/integration/roles/test_unarchive/files/test-unarchive-nonascii-#U304f#U3089#U3068#U307f.tar.gz'\r\n", "msg": "MODULE FAILURE", "parsed": false}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @/tmp/ansible-17022.retry

PLAY RECAP *********************************************************************
vagrant                    : ok=1    changed=0    unreachable=0    failed=1   

```

Other files work correctly. I suspect this is triggered by the funky-named test file in the Ansible repo.

**Comment by joemaller** [comment] 2016-08-12 14:27
@bcoca please see above, there is a reproducible bug here that is unresolved. The issue title should be edited to remove OS X.

**Comment by bcoca** [comment] 2016-08-12 14:40
This bug would still be in the wrong repo, since the linked one is in the correct one, leaving that to track the issue.

**Comment by joemaller** [comment] 2016-08-12 14:48
@bcoca @dagwieers https://github.com/ansible/ansible-modules-core/issues/4390 is a different bug. This one specifically reveals a failure when trying to verify an unpacked archive containing non-ascii names. (coincidentally Ansible)

I will migrate the info from my last comment to a new issue in the correct repo. Thanks!
