### ISSUE TITLE
'Service' module not starting service (w/ custom init script)

### ISSUE THREAD

**Issue by danielgroves** [ansible/ansible#7284] opened 2014-05-05 20:01 UTC
**Issue Type:** Bug Report

**Ansible Version:** 1.5.5

**Environment:** OS X 10.9.2 -> Ubuntu 12.04 x64
##### Summary:

I am writing a playbook to install the [GitLab CI Runner](/gitlabhq/gitlab-ci-runner/). The system provides an [init.d script](/gitlabhq/gitlab-ci-runner/blob/master/lib/support/init.d/gitlab_ci_runner) which does work. I have manually verified that the installation works as expected, it starts, stops, restarts, the service as normal via the service command, for example by running `sudo service gitlab-ci-runner start`. 

Despite this having been verified as working manually, it does not work with Ansible starting the service. 
##### Steps To Reproduce:

Install GitLab CI Runner with a working GitLab CI instance via their [instructions](/gitlabhq/gitlab-ci-runner). I have done this by automating it with Ansible, but their is no reason why this part could not be done manually. 

Once done, run a Ansible playbook with the following in `tasks/main.yml`:

```
- name: start gitlab ci
  sudo: yes
  service: name=gitlab-ci-runner state=started
  register: start

- name: start output
  debug: var=start
```

The service will not start. 
##### Expected Results:

For the service to be started and running. This does work if I manually log into the virtual machine and run `sudo service gitlab-ci-runner start` however it does not start with Ansible. 
##### Actual Results:

Nothing on the system changes. Output from running below:

```
TASK: [gitlab-ci-runner | start gitlab ci] ************************************ 
ok: [default]

TASK: [gitlab-ci-runner | start output] *************************************** 
ok: [default] => {
    "item": "", 
    "start": {
        "changed": false, 
        "invocation": {
            "module_args": "name=gitlab-ci-runner state=started", 
            "module_name": "service"
        }, 
        "item": "", 
        "name": "gitlab-ci-runner", 
        "state": "started"
    }
}
```

Output with verbose set to 'vvvv'

```
TASK: [gitlab-ci-runner | start gitlab ci] ************************************ 
<192.168.120.130> ESTABLISH CONNECTION FOR USER: vagrant
<192.168.120.130> REMOTE_MODULE service name=gitlab-ci-runner state=started
<192.168.120.130> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/danielsgroves/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=22', '-o', 'IdentityFile=/Users/danielsgroves/.vagrant.d/insecure_private_key', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=vagrant', '-o', 'ConnectTimeout=10', '192.168.120.130', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1399319105.95-21881512167993 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1399319105.95-21881512167993 && echo $HOME/.ansible/tmp/ansible-tmp-1399319105.95-21881512167993'"]
<192.168.120.130> PUT /var/folders/jh/8f7bz2g50c7bc7_nc_ws6dwr0000gn/T/tmpa4tdE6 TO /home/vagrant/.ansible/tmp/ansible-tmp-1399319105.95-21881512167993/service
<192.168.120.130> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/danielsgroves/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=22', '-o', 'IdentityFile=/Users/danielsgroves/.vagrant.d/insecure_private_key', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=vagrant', '-o', 'ConnectTimeout=10', '192.168.120.130', '/bin/sh -c \'sudo -k && sudo -H -S -p "[sudo via ansible, key=ebhzijwsiqterppkujfagvarqigiidpl] password: " -u root /bin/sh -c \'"\'"\'echo SUDO-SUCCESS-ebhzijwsiqterppkujfagvarqigiidpl; /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1399319105.95-21881512167993/service; rm -rf /home/vagrant/.ansible/tmp/ansible-tmp-1399319105.95-21881512167993/ >/dev/null 2>&1\'"\'"\'\'']
ok: [default] => {"changed": false, "item": "", "name": "gitlab-ci-runner", "state": "started"}

TASK: [gitlab-ci-runner | start output] *************************************** 
<192.168.120.130> ESTABLISH CONNECTION FOR USER: vagrant
ok: [default] => {
    "item": "", 
    "start": {
        "changed": false, 
        "invocation": {
            "module_args": "name=gitlab-ci-runner state=started", 
            "module_name": "service"
        }, 
        "item": "", 
        "name": "gitlab-ci-runner", 
        "state": "started"
    }
}
```
##### Alternate Approach:

Finding this did not work, I tried running a 'command': sudo service gitlab-ci-runner start instead. 

```
- name: start gitlab ci
  sudo: yes
  command: service gitlab-ci-runner start
  register: start

- name: start output
  debug: var=start
```

Doing this the service _does_ start as expected, however it is my understanding that this _should_ be handled by the 'service' module.

**Comment by jimi-c** [comment] 2014-05-05 20:28
Could you share your installation playbook, so it's a bit easier for me to setup a test to try and replicate this? Thanks!

**Comment by danielgroves** [comment] 2014-05-06 10:13
Yep, just finalised a few bits and published it open source. Repository at [danielgroves/Ansible-GitLab-CI-Runner-Installer](/danielgroves/Ansible-GitLab-CI-Runner-Installer)

**Comment by jimi-c** [comment] 2014-05-06 12:37
Thanks, looking into this now.

**Comment by 1player** [comment] 2014-05-29 15:33
Any update? I have the same problem with a custom init.d script that works if started from shell.

**Comment by 1player** [comment] 2014-05-29 15:37
BTW, I had the exact same problem starting a service from fabric: init.d scripts don't work if executed from a pseudo-tty, see http://www.fabfile.org/faq.html#init-scripts-don-t-work

Maybe this is related.

**Comment by xals** [comment] 2014-06-03 10:23
Hi,
I have exactly the same issue.  I am trying to start libvirt-bin daemon on a Debian Wheezy, the task says "changed", but the service doesn't start. I tried to run it using the shell module, same behaviour.

Like 1player, I had the same problem using Fabric months ago for other services (one of them was pgbouncer if I remember well)

Maybe someone has an idea :-)

**Comment by jimi-c** [comment] 2014-06-03 14:02
Part of the issue with debugging this is the complex gitlab/ci setup. If someone has an easier way to reproduce this problem please let us know.

**Comment by xals** [comment] 2014-06-03 14:45
@jimi-c You should try to install libvirt-bin (`apt-get install libvirt-bin`), and then have a task with module service:
`service: name=libvirt-bin state=started`

Be sure libvirt-bin service is stopped before running the task (`service libvirt-bin stop`).

This is how I had the bug this morning, hopefully you will be able to reproduce :-)

**Comment by xals** [comment] 2014-06-03 14:47
I have not tried to run directly the module with `ansible -m`, but always with `ansible-playbook`

**Comment by xals** [comment] 2014-06-03 14:48
And, well, I am using Debian GNU/Linux Wheezy.

**Comment by jimi-c** [comment] 2014-06-03 15:40
@xals thanks, I'll give that a try on my debian 7 vm.

**Comment by jimi-c** [comment] 2014-06-03 17:07
@xals no luck, unfortunately:

<pre>
root@debian71:~# service libvirt-bin stop
[ ok ] Stopping libvirt-bin (via systemctl): libvirt-bin.service.
root@debian71:~# service libvirt-bin status
libvirt-bin.service - LSB: libvirt management daemon
      Loaded: loaded (/etc/init.d/libvirt-bin)
      Active: inactive (dead) since Tue, 03 Jun 2014 12:50:12 -0400; 1s ago
     Process: 25955 ExecStop=/etc/init.d/libvirt-bin stop (code=exited, status=0/SUCCESS)
     Process: 25856 ExecStart=/etc/init.d/libvirt-bin start (code=exited, status=0/SUCCESS)
      CGroup: name=systemd:/system/libvirt-bin.service
Jun 03 12:48:41 debian71.sngx.net libvirt-bin[25856]: Starting libvirt management daemon: libvirtd.
Jun 03 12:50:12 debian71.sngx.net libvirt-bin[25955]: Stopping libvirt management daemon: libvirtd.
</pre>

The running an ad-hoc command to start it:

<pre>
$ ansible -m service -a "name=libvirt-bin state=started" debian7 -vvv
<192.168.122.115> ESTABLISH CONNECTION FOR USER: root
<192.168.122.115> REMOTE_MODULE service name=libvirt-bin state=running
<192.168.122.115> EXEC ['ssh', '-C', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/root/.ansible/cp/%h-%r', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', '192.168.122.115', u"/bin/sh -c 'LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8 /usr/bin/python'"]
192.168.122.115 | success >> {
    "changed": true, 
    "name": "libvirt-bin", 
    "state": "started"
}
</pre>

And checking:

<pre>
root@debian71:~# service libvirt-bin status
libvirt-bin.service - LSB: libvirt management daemon
      Loaded: loaded (/etc/init.d/libvirt-bin)
      Active: active (running) since Tue, 03 Jun 2014 12:50:20 -0400; 16s ago
     Process: 25955 ExecStop=/etc/init.d/libvirt-bin stop (code=exited, status=0/SUCCESS)
     Process: 26022 ExecStart=/etc/init.d/libvirt-bin start (code=exited, status=0/SUCCESS)
      CGroup: name=systemd:/system/libvirt-bin.service
          └ 26028 /usr/sbin/libvirtd -d
Jun 03 12:50:20 debian71.sngx.net libvirt-bin[26022]: Starting libvirt management daemon: libvirtd.
</pre>

So the service started without any problems.

Have you modified any settings in your ansible.cfg or anything else environmentally that might be modifying how ansible is running things?

**Comment by 1player** [comment] 2014-06-03 18:04
I had the problem with a regular, custom init.d script, while no issue
using an upstart script under Ubuntu 14.04

I guess systemd handles it correctly as well.

I'll try to create a reproducible playbook with sample init.d script

**Comment by pdeva** [comment] 2014-06-20 03:03
i am running into the same issues with a slightly modified version of 
https://github.com/ansible/ansible-examples/blob/master/tomcat-standalone%2Froles%2Ftomcat%2Ffiles%2Ftomcat-initscript.sh

using `state=restarted` works but `state=started` doesnt

**Comment by hepabolu** [comment] 2014-06-21 20:59
I can confirm pdeva's comment. I'm using the same init script and 'state=started' doesn't work, but 'state=restarted' does. 'state=stopped' does work. I'm using Ansible 1.6.3

**Comment by jvrplmlmn** [comment] 2014-07-20 18:08
+1 to @pdeva and @hepabolu, I'm running into the same issue using that example.

Ansible Version:

```
(DevOps)➜  Tomcat git:(tomcat) ✗ ansible --version
ansible 1.6.3
(DevOps)➜  Tomcat git:(tomcat) ✗
```

Playbook execution:

```
PLAY [tomcat-servers] *********************************************************

GATHERING FACTS ***************************************************************
<192.168.33.10> ESTABLISH CONNECTION FOR USER: vagrant
<192.168.33.10> REMOTE_MODULE setup
<192.168.33.10> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/javier/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'IdentityFile=/Users/javier/.vagrant.d/insecure_private_key', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=vagrant', '-o', 'ConnectTimeout=10', '192.168.33.10', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1405879505.96-42123573947271 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1405879505.96-42123573947271 && echo $HOME/.ansible/tmp/ansible-tmp-1405879505.96-42123573947271'"]
<192.168.33.10> PUT /var/folders/py/3fxk2cjd299467477n2yzc880000gn/T/tmpTQCTwZ TO /home/vagrant/.ansible/tmp/ansible-tmp-1405879505.96-42123573947271/setup
<192.168.33.10> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/javier/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'IdentityFile=/Users/javier/.vagrant.d/insecure_private_key', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=vagrant', '-o', 'ConnectTimeout=10', '192.168.33.10', u'/bin/sh -c \'sudo -k && sudo -H -S -p "[sudo via ansible, key=ijwusktciuyalgczpgszirnbvibuhbca] password: " -u root /bin/sh -c \'"\'"\'echo SUDO-SUCCESS-ijwusktciuyalgczpgszirnbvibuhbca; LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8 /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1405879505.96-42123573947271/setup; rm -rf /home/vagrant/.ansible/tmp/ansible-tmp-1405879505.96-42123573947271/ >/dev/null 2>&1\'"\'"\'\'']
ok: [tomcat-vm0.example.org]
Perform task: tomcat | Start Tomcat (y/n/c): y

Perform task: tomcat | Start Tomcat (y/n/c):  *********************************
<192.168.33.10> ESTABLISH CONNECTION FOR USER: vagrant
<192.168.33.10> REMOTE_MODULE service name=tomcat state=started enabled=yes
<192.168.33.10> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/javier/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'IdentityFile=/Users/javier/.vagrant.d/insecure_private_key', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=vagrant', '-o', 'ConnectTimeout=10', '192.168.33.10', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1405879511.31-157443206384596 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1405879511.31-157443206384596 && echo $HOME/.ansible/tmp/ansible-tmp-1405879511.31-157443206384596'"]
<192.168.33.10> PUT /var/folders/py/3fxk2cjd299467477n2yzc880000gn/T/tmpQfdEg_ TO /home/vagrant/.ansible/tmp/ansible-tmp-1405879511.31-157443206384596/service
<192.168.33.10> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/javier/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'IdentityFile=/Users/javier/.vagrant.d/insecure_private_key', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=vagrant', '-o', 'ConnectTimeout=10', '192.168.33.10', u'/bin/sh -c \'sudo -k && sudo -H -S -p "[sudo via ansible, key=oecibtxzqlhrgfnstkhlwflrqdlreetq] password: " -u root /bin/sh -c \'"\'"\'echo SUDO-SUCCESS-oecibtxzqlhrgfnstkhlwflrqdlreetq; LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8 /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1405879511.31-157443206384596/service; rm -rf /home/vagrant/.ansible/tmp/ansible-tmp-1405879511.31-157443206384596/ >/dev/null 2>&1\'"\'"\'\'']
ok: [tomcat-vm0.example.org] => {"changed": false, "enabled": true, "name": "tomcat", "state": "started"}
```

Checked the status of the service in the server and it's not running:

```
[vagrant@tomcat-vm0 tmp]$ sudo service tomcat status
Tomcat is not running
[vagrant@tomcat-vm0 tmp]$
```

**Comment by joestubbs** [comment] 2014-08-06 21:21
I ran into a similar issue with a tomcat startup script. I believe my issue was related to this block of the get_service_status method in the LinuxService class of the service module:

```
    if self.running is None:
        if rc in [1, 2, 3, 4, 69]:
            self.running = False
        elif rc == 0:
            self.running = True
```

My tomcat init.d script was issuing a return code of 0 on a call to status when the service was stopped (indeed, it appears many tomcat scripts found on the web have this behavior). Changing my startup script to exit with a different return code fixed the issue.

**Comment by jimi-c** [comment] 2014-08-06 21:32
@joestubbs ahh yes, that would explain things.

**Comment by mnewell** [comment] 2014-08-13 14:23
@joestubbs I tried the same approach (status returns nonzero for not-running daemon), but Ansible is bizarre about it. If the tomcat daemon is up, Ansible correctly determines that the service is up and does nothing. If the service is stopped, Ansible will start it succesfully _and_ return an error:

```
TASK: [start wh] ************************************************************** 
<tst_wh_3> REMOTE_MODULE service name=tomcat state=started 
failed: [tst_wh_3] => {"failed": true} 
msg: Starting Tomcat...

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
to retry, use: --limit @/Users/max/startsite.retry

tst_wh_3 : ok=1 changed=0 unreachable=0 failed=1
```

**Comment by shuhaowu** [comment] 2014-09-07 05:48
I think I'm experiencing a similar issue with tinc in debian.

**Comment by tuukkamustonen** [comment] 2014-09-10 06:14
I'm experiencing similar issue with Amazon Linux and InfluxDB. I tried:
- using service module (`name=influxdb state=started`) through playbook...
- ...and as individual command (`-m "service" -a "name=influxdb state=started"`)
- I also ran raw `-a "sudo service influxdb start"` and `-a "sudo /etc/init.d/influxdb start"`.

The results is always the same (ansible returns ok, but service doesn't start). Doing things manually on shell always works. Having `state=started` or `state=restarted` makes no change.

InfluxDB init script correctly reports return code `1` for `status` when the service is not running:

```
$ sudo service influxdb status
1
```

Also:

```
$ sudo service influxdb start
Starting the process influxdb [ OK ]
influxdb process was started [ OK ]
$ echo $?
0
$ sudo /etc/init.d/influxdb start
influxdb process is running [ FAILED ]
$ echo $?
1
$ echo $?
0
$ sudo /etc/init.d/influxdb stop
influxdb process is not running [ FAILED ]
$ echo $?
0
```

Restart:

```
$ sudo /etc/init.d/influxdb restart
influxdb process is not running [ FAILED ]
Starting the process influxdb [ OK ]
influxdb process was started [ OK ]
$ echo $?
0
$ sudo /etc/init.d/influxdb restart
influxdb process was stopped [ OK ]
Starting the process influxdb [ OK ]
influxdb process was started [ OK ]
$ echo $?
0
```

This doesn't start the service either:

```
$ ssh -t ec2-user@myhost "sudo service influxdb start"
Starting the process influxdb [ OK ]
influxdb process was started [ OK ]
Connection to myhost closed.
```

Running ansible 1.7.1

**Comment by jimi-c** [comment] 2014-09-10 15:31
@tuukkamustonen / @shuhaowu does the use of the `pattern=` parameter to the service module help resolve the issue? See http://docs.ansible.com/service_module.html for more details on the use of that parameter.

**Comment by tuukkamustonen** [comment] 2014-09-11 06:48
@jimi-c Even with `pattern=/usr/bin/influxdb`, no change in behavior.

**Comment by jimi-c** [comment] 2014-09-11 14:26
@tuukkamustonen I'm curious if your issue is different than the original issue, in that it seems like the influx DB instance is stopping as soon as the connection is closed? If that's accurate, could you please open a new issue for this?

Regardless, if you could detail how you've installed/configured that system to help us reproduce the issue that would be very helpful.

**Comment by jimi-c** [comment] 2014-09-11 17:16
# Closing This Ticket

Hi!

We believe the above commit should resolve several of the issues reported above, such as the tomcat initscript issue. 

Since this issue has become clouded by multiple, un-related reports, we are going to close and lock it, and encourage users to either open new issues if the above commit does not resolve their problem, or to please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you!

**Closed as completed** 2014-09-11 17:15 UTC
Labels: P1, bug
