### ISSUE TITLE
vars_files do not expand inventory_file

### ISSUE THREAD

**Issue by senz** [ansible/ansible#8534] opened 2014-08-09 19:15 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.10
##### Environment:

OSX 10.7.5
Darwin 11.4.2 Darwin Kernel Version 11.4.2: Thu Aug 23 16:26:45 PDT 2012; root:xnu-1699.32.7~1/RELEASE_I386
##### Summary:

Expansion of inventory_file magic var does not work in vars_files directive. Altho, debug module outputs expansion correct.
##### Steps To Reproduce:

Create vars/production.yml:
    ---
    list:
      key1: "val1"

Create PB with:
    ---
    - hosts: all
      vars_files:
        - "vars/{{ inventory_file|basename }}.yml"
    tasks:
    - name: test
      debug: var=int_addrs
##### Expected Results:

ok: [all] => {
    "list": { "key1": "val1"}
}
##### Actual Results:

ok: [all] => {
    "list": "{{ list }}"
}

**Comment by yaegashi** [comment] 2014-08-10 09:34
I have a similar problem with `vars_files`, but for me it's `inventory_dir`.

##### Ansible Version:

ansible 1.7

##### Environment:

Ubuntu 14.04

```
Linux ans 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

##### Steps To Reproduce:

File `hosts`:

```
localhost
```

File `vars/main.yml`:

``` yml
----
a: 1
```

File `playbooks/bug.yml`:

``` yml
---
- hosts: all
  gather_facts: false
  vars_files:
    - "{{inventory_dir}}/vars/main.yml"
  tasks:
    - debug: var=a
```

Run:

```
$ ansible-playbook -i hosts playbooks/bug.yml
```

##### Expected Results:

```
TASK: [debug var=a] *********************************************************** 
ok: [localhost] => {
    "a": "1"
}
```

##### Actual Results:

```
TASK: [debug var=a] *********************************************************** 
ok: [localhost] => {
    "a": "{{ a }}"
}
```

##### Other Things Observed:

If the `vars_files` entry is a relative path, it works as expected results.

``` yml
  vars_files:
    - "../vars/main.yml"
```

If the `vars_files` entry is in a list, it raises a fatal error.

``` yml
  vars_files:
    - ["{{inventory_dir}}/vars/main.yml"]
```

```
PLAY [all] ******************************************************************** 
localhost: not importing file: /home/yaegashi/ansible/playbooks/{{inventory_dir}}/vars/main.yml
ERROR: localhost: FATAL, no files matched for vars_files import sequence: [u'/home/yaegashi/ansible/playbooks/{{inventory_dir}}/vars/main.yml']
```

I wanted to rather give a dedicated multi-level dir to playbooks than scatter them in the top dir.  It would be nice if it could refer an absolute path using `inventory_dir` or some other variables in `vars_files`.

**Comment by mpdehaan** [comment] 2014-08-11 11:58
(Internal note to us - there's code in the system that doesn't evaluate things early if variables are not yet defined, that should be working in this case.   So something different may be afoot than the question of whether they need to be moved up in scope, for instance, facts are valid in such paths)

**Comment by jimi-c** [comment] 2014-08-12 00:25
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed** 2014-08-12 00:24 UTC
Labels: P2, bug
