### ISSUE TITLE
Got error for shell with grep highlighting 

### ISSUE THREAD

**Issue by tbicr** [ansible/ansible#11155] opened 2015-06-03 19:47 UTC
Not work shell with grep pipline:

```
- shell: find /TEST/PATH -name requirements.txt -exec cat {} \; | grep -o '^[^#]*'
- shell: "find /TEST/PATH -name requirements.txt -exec cat {} \\; | grep -o '^[^#]*'"
- shell: find /TEST/PATH -name requirements.txt -exec cat {} \; | grep test
- shell: "find /TEST/PATH -name requirements.txt -exec cat {} \\; | grep test"
- shell: find /TEST/PATH -name requirements.txt -print0 | xargs -0 cat | grep  -o '^[^#]*'
- shell: "find /TEST/PATH -name requirements.txt -print0 | xargs -0 cat | grep  -o '^[^#]*'"
- shell: find /TEST/PATH -name requirements.txt -print0 | xargs -0 cat | grep  test
- shell: "find /TEST/PATH -name requirements.txt -print0 | xargs -0 cat | grep  test"
```

with next message:

```
failed: [test-instance] => {"changed": true, "cmd": "find  /TEST/PATH -name requirements.txt -exec cat {} \\; | grep -o '^[^#]*'", "delta": "0:00:00.003797", "end": "2015-06-03 21:40:57.502797", "rc": 1, "start": "2015-06-03 21:40:57.499000", "warnings": []}

FATAL: all hosts have already failed -- aborting
```

When I replace `grep something` for example to `tail` all work, this commands also work fine on shell on instance for bash and sh, also this work for python `subprocess.Popen` with shell=True.

**Comment by tbicr** [comment] 2015-06-03 20:10
When I add `| cat` after `grep` all work fine, maybe it depends on highlighting.

**Comment by sivel** [comment] 2015-06-03 20:17
I cannot duplicate that on the devel branch:

```
ansible all -i localhost, -c local -m shell -a 'find /tmp/ -name requirements.txt -exec cat {} \; | grep -o "^[^#]*"'
localhost | SUCCESS => {
    "changed": true,
    "end": "2015-06-03 15:16:12.619316",
    "stdout": "foo",
    "cmd": "find /tmp/ -name requirements.txt -exec cat {} \\; | grep -o \"^[^#]*\"",
    "start": "2015-06-03 15:16:12.605591",
    "delta": "0:00:00.013725",
    "stderr": "",
    "rc": 0,
    "invocation": {
        "module_name": "command",
        "module_args": {
            "_raw_params": "find /tmp/ -name requirements.txt -exec cat {} \\; | grep -o \"^[^#]*\"",
            "_uses_shell": true
        }
    },
    "stdout_lines": [
        "foo"
    ],
    "warnings": []
}
```

**Comment by bcoca** [comment] 2015-06-03 20:23
I cannot reproduce this either

**Comment by bcoca** [comment] 2015-06-03 20:24
``````
nyx | SUCCESS => {
    "changed": true, 
    "end": "2015-06-03 18:15:24.741186", 
    "stdout": "Flask==0.8\nJinja2==2.6\nWerkzeug==0.8.3\nargparse==1.2.1\ncertifi==0.0.8\nchardet==2.1.1\ncoverage==3.5.3\nsetuptools==1.4\neventlet==0.9.17\ngreenlet==0.4.0\nhttplib2==0.8\njsonpath==0.54\nlxml==2.3.2\nmock==1.0.1\nnose==1.2.1\nnosexcover==1.0.8\npsycopg2==2.4.5\npymongo==2.4.2\npython-Levenshtein==0.10.2\nrequests==0.8.2\nrequests-oauth==0.4.1\nwsgiref==0.1.2\nargparse==1.1\ndistribute==0.7.3\ndocutils==0.11\nfunkload==1.16.1\nwebunit==1.3.10\nwsgiref==0.1.2\nargparse\npyvmomi\nrequests\nsuds>=0.4,<0.7", 
    "cmd": "find ~/ -name requirements.txt -exec cat {} \\; | grep -o '^[^#]*'", 
    "start": "2015-06-03 18:14:57.616266", 
    "delta": "0:00:27.124920", 
    "stderr": "", 
    "rc": 0, 
    "invocation": {
        "module_name": "command", 
        "module_args": {
            "_raw_params": "find ~/ -name requirements.txt -exec cat {} \\; | grep -o '^[^#]*'", 
            "_uses_shell": true
        }
    }, 
...
    ```
``````

**Comment by tbicr** [comment] 2015-06-03 20:36
Guys, can you check how it work for you when output highlights:

![highliting](https://cloud.githubusercontent.com/assets/416731/7970753/d880c20a-0a48-11e5-83c0-ebe425d64bca.png)

**Comment by bcoca** [comment] 2015-06-03 20:53
no change, but older versions of ansible could choke on some of the terminal color chars

**Comment by tbicr** [comment] 2015-06-04 05:30
I use ansible 1.9.1 from pypi.

**Comment by jimi-c** [comment] 2015-07-15 16:54
@tbicr since this does not seem to be an issue on devel, we're going to go ahead and close this per our normal procedures.

**Comment by jimi-c** [comment] 2015-07-15 16:55
If you do happen to test this on devel and still see this problem occur, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-07-15 16:55 UTC
Labels: needs_info, bug
