### ISSUE TITLE
It seems the cron module does not handle the user  name property properly

### ISSUE THREAD

**Issue by berenddeboer** [ansible/ansible#3933] opened 2013-08-23 22:00 UTC
I have two lines:

cron: name="Fetch ports" job="/usr/sbin/portsnap cron" minute="15" hour="4" state=present

cron: name="Logcheck" job="/usr/local/sbin/logcheck cron" minute="5" user="logcheck" state=present

The second line should go to the logcheck user, but wipes out the root user entries instead, i.e. the previous entry.

**Comment by jimi-c** [comment] 2013-08-24 01:31
What OS/version of ansible was this on?

I tested on a Fedora 17 system using the HEAD of the devel branch, and was unable to reproduce this:

<pre>
$ ansible-playbook -i localhost, ~/test_cron.yml 
PLAY [all] ******************************************************************** 
TASK: [cron name="Fetch ports" job="/usr/sbin/portsnap cron" minute="15" hour="4" state=present] *** 
changed: [localhost]
TASK: [cron name="Logcheck" job="/usr/local/sbin/logcheck cron" minute="5" user="testing" state=present] *** 
changed: [localhost]
PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=2    unreachable=0    failed=0   
$ crontab -l
#Ansible: Fetch ports
15 4 * * * /usr/sbin/portsnap cron
$ crontab -l -u testing
#Ansible: Logcheck
5 * * * * /usr/local/sbin/logcheck cron
</pre>

**Comment by berenddeboer** [comment] 2013-08-24 05:03
> > > > > "James" == James Cammarata notifications@github.com writes:

```
James> What OS/version of ansible was this on?
```

Ubuntu 12.04, ansible from git.

(if I haven't made any mistake in pulling the latest from git that is).

## 

All the best,

Berend de Boer

```
      ------------------------------------------------------
      Awesome Drupal hosting: https://www.xplainhosting.com/
```

**Comment by berenddeboer** [comment] 2013-08-24 05:04
> > > > > "James" == James Cammarata notifications@github.com writes:

```
James> What OS/version of ansible was this on?
```

Eh, sorry, Ubuntu was where I ran the playbook, target was FreeBSD 9.1.

## 

All the best,

Berend de Boer

```
      ------------------------------------------------------
      Awesome Drupal hosting: https://www.xplainhosting.com/
```

**Comment by jimi-c** [comment] 2013-08-25 02:39
I just pushed a fix up for this. I tested it on FreeBSD 9.1 as well and it seems to be working now. The issue was that the module was running "crontab /path/to/tempfile -u foo", which crontab on freebsd apparently doesn't like. I fixed it so that the path comes after the "-u foo" portion. Let us know if you have any further issues with this, and thanks for reporting it!

**Closed as completed by jimi-c** 2013-08-25 02:39 UTC
Labels: bug, bsd

**Comment by berenddeboer** [comment] 2013-08-25 21:11
Fixed!

**Comment by jimi-c** [comment] 2013-08-25 21:12
Great, thanks again!
