### ISSUE TITLE
referencing VLAN interfaces in templates does not work

### ISSUE THREAD

**Issue by cultcom** [ansible/ansible#10233] opened 2015-02-13 10:54 UTC
From an host I get the following facts including a vlan enabled interface:

```
        "ansible_bond0.1062": {
            "active": true,
            "device": "bond0.1062",
            "ipv4": {
                "address": "XX",
                "netmask": "255.255.255.0",
                "network": "XX"
            },
            "ipv6": [
                {
                    "address": "...",
                    "prefix": "64",
                    "scope": "link"
                }
            ],
            "macaddress": "...",
            "mtu": 1500,
            "promisc": false,
            "type": "ether"
        },
```

unfortunately it is impossible for me to reference the IP address within a template:

```
{% if hostvars[host]['ansible_hostname'] is defined %}
  [mon.{{ hostvars[host]['ansible_hostname'] }}]
    host = {{ hostvars[host]['ansible_hostname'] }}
    mon addr = "{{ hostvars[host]['ansible_' + monitor_interface]['ipv4']['address'] }}"
  {% endif %}
```

where monitor_interface is defined in the inventory file like this:
ceph04 monitor_interface=bond0.1062

the template results in the following errors.

```
TASK: [ceph-common | Generate Ceph configuration file] ************************ 
fatal: [ceph04] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'ansible_bond0.1062'", 'failed': True}
fatal: [ceph04] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'ansible_bond0.1062'", 'failed': True}
```

**Comment by bcoca** [comment] 2015-02-13 13:30
The issue seems to be the name ansible_bond0.1062, its confusing jinja which is looking for a dictionary entry ['ansible_bond0']['1062'] instead of ['ansible_bond0.1062']

**Comment by jimi-c** [comment] 2015-07-04 18:58
Hi @cultcom, looking back at this issue, I don't have any vlan interfaces but in testing with other fact keys with spaces I wasn't able to reproduce this with the current devel. For example:

<pre>
# cat 10233.yml 
- hosts: localhost
  vars:
    foo: 'lvm.lv'
  tasks:
  - debug: msg="it is {{ansible_cmdline['rd.' + foo]}}"
# ansible-playbook -vv 10233.yml 
1 plays in 10233.yml
PLAY: ***************************************************************************
TASK [setup] ********************************************************************
ok: [localhost]
TASK [debug msg=it is fedora/root] **********************************************
ok: [localhost] => {
    "msg": "it is fedora/root", 
    "changed": false
}
PLAY RECAP **********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
</pre>

Are you still seeing this issue with the current devel branch?

**Comment by daysofwineandroses** [comment] 2015-09-29 05:58
The issue still seems to persist, even on current devel:

```
$ ansible --version
[WARNING]: log file at /var/log/ansible.log is not writeable, aborting

ansible 2.0.0 (devel 7a4266e9c5) last updated 2015/09/28 20:59:18 (GMT +200)
  lib/ansible/modules/core: (detached HEAD a4ac171a07) last updated 2015/09/28 20:59:32 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 3c8c716801) last updated 2015/09/28 20:59:44 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = None
```

`setup` shows the tagged VLAN interface and `filter` allows for extraction:

```
$ ansible -i hosts testhost -m setup -a 'filter=ansible_bond0.1840'
testhost | success >> {
    "ansible_facts": {
        "ansible_bond0.1840": {
            "active": true,
            "device": "bond0.1840",
            "ipv4": {
                "address": "10.110.0.18",
                "netmask": "255.255.255.240",
                "network": "10.0.0.16"
            },
....
```

Overview of required ansible config:

```
$ cat 10233.play
---
- hosts: testhost
  tasks:
  - template: src=motd.j2 dest=/etc/motd 
```

```
$ cat hosts
[all]
testhost
```

```
$ cat motd.j2 
bond0.1840: {{ ansible_bond0.1840['ipv4']['address'] }}
```

On latest dev as shown above: 

```
$ ansible-playbook -i hosts 10233.play 
[WARNING]: log file at /var/log/ansible.log is not writeable, aborting


PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [testhost]

TASK [template dest=/etc/motd src=motd.j2] *************************************
fatal: [testhost]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: ERROR! dict object has no element 1840"}

PLAY RECAP *********************************************************************
testhost                   : ok=1    changed=0    unreachable=0    failed=1   
```

On 1.9.2 stable, just FYI:

```
$ ansible-playbook -i hosts 10233.play 

PLAY [testhost] *************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [testhost]

TASK: [template src=motd.j2 dest=/etc/motd] *********************************** 
fatal: [testhost] => {'msg': 'AnsibleUndefinedVariable: One or more undefined variables: dict object has no element 1840', 'failed': True}
fatal: [testhost] => {'msg': 'AnsibleUndefinedVariable: One or more undefined variables: dict object has no element 1840', 'failed': True}

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/bert/10233.play.retry

testhost                   : ok=1    changed=0    unreachable=1    failed=0   
```

It's pretty annoying since this prevents me from creating fully dynamic motd configs containing server IP addresses.

Skimmed the ansible codebase to see if I could fix it myself, but this one goes too deep into the trenches for me to easily figure out.

Relevant jinja variable parsing doc:
http://jinja.pocoo.org/docs/dev/templates/#variables

**Comment by basigabri** [comment] 2016-05-19 10:19
Correct syntax whcih worked into a template

{{ hostvars[inventory_hostname]['ansible_bond0.11']['ipv4']['address'] }}

**Comment by bcoca** [comment] 2017-01-23 18:05
Closing this issue as there is no way for us to fix this in code, it is a consequence of the underlying technologies used (python, jinja2). As several answers post, you cannot use naked names with . in them, use the ['quoted.name'] interface instead.

**Closed as completed by bcoca** 2017-01-23 18:05 UTC
Labels: affects_2.0, affects_2.3, c:template/templar, c:module_utils/facts, bug
