### ISSUE TITLE
Ubuntu 20.04 - WSL on Win10: Unable to run playbook using localhost 

### ISSUE THREAD

**Issue by dpkshetty** [ansible/ansible#71181] opened 2020-08-10 13:46 UTC
##### SUMMARY
Unable to run playbook on ubuntu 20.04, gives auth/perm error

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
kubernetes module, but should re-create with any module

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/dpkshetty/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.2 (default, Apr 27 2020, 15:53:34) [GCC 9.3.0]

```

##### CONFIGURATION

```paste below
dpkshetty@DESKTOP-L94HV3O:~/ansible-2004/ocp$ ansible-config dump --only-changed
dpkshetty@DESKTOP-L94HV3O:~/ansible-2004/ocp$ 
```

##### OS / ENVIRONMENT
Ubuntu 20.04 on WSL (windows subsystem for linux) on Win10
```
uname -a
Linux DESKTOP-L94HV3O 4.4.0-18362-Microsoft #836-Microsoft Mon May 05 16:04:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
```

##### STEPS TO REPRODUCE
Please see the ansible playbook yml below

```yaml
cat ./k8s-info-list-pods.yml
---
- hosts: localhost
  gather_facts: false

  collections:
    - community.kubernetes

  tasks:
    - name: Get a list of all pods from any namespace
      k8s_info:
              host: <<redacted>>
              api_key: <<redacted>>
              validate_certs: no
              namespace: test
              kind: Pod
      register: podlist
```

##### EXPECTED RESULTS
I should be able to list all the Pods of my openshift cluster for the given namespace

##### ACTUAL RESULTS
```
ansible-playbook ./k8s-info-list-pods.yml
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
PLAY [localhost] ***********************************************************************************************************************************************************
TASK [Get a list of all pods from any namespace] ***************************************************************************************************************************
fatal: [localhost]: UNREACHABLE! => {"changed": false, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo /tmp/ansible/ansible-tmp-1597055373.258955-159832533067188 `\" && echo ansible-tmp-1597055373.258955-159832533067188=\"` echo /tmp/ansible/ansible-tmp-1597055373.258955-159832533067188 `\" ), exited with result 1, stdout output: ansible-tmp-1597055373.258955-159832533067188=/tmp/ansible/ansible-tmp-1597055373.258955-159832533067188\n", "unreachable": true}
PLAY RECAP *****************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0

```

```paste below

```

**Comment by dpkshetty** [comment] 2020-08-10 13:49
I did some google search and got some links which said changing the default remote_tmp location might help.. this I changed my ansible.cfg to make `remote_tmp = /tmp/ansible` but still it doesn't work.

As you can see below /tmp and /tmp/ansible both are world-writable, still I get the error as mentioned above
```
ls -l /tmp/ | grep ansible
drwxrwxrwx 1 dpkshetty dpkshetty  4096 Aug 10 16:11 ansible

dpkshetty@DESKTOP-L94HV3O:~/ansible-2004/ocp$ ls -l / | grep tmp
drwxrwxrwt  1 root root   4096 Aug 10 16:11 tmp
```

**Comment by dpkshetty** [comment] 2020-08-10 13:50
Running as user `dpkshetty`
```
id
uid=1000(dpkshetty) gid=1000(dpkshetty) groups=1000(dpkshetty),4(adm),20(dialout),24(cdrom),25(floppy),27(sudo),29(audio),30(dip),44(video),46(plugdev),117(netdev)
```

**Comment by sivel** [comment] 2020-08-10 13:59
Duplicate of https://github.com/ansible/ansible/issues/70580

You will need to switch to WSL2.  See https://github.com/ansible/ansible/issues/70580#issuecomment-658368325

**Closed as completed by sivel** 2020-08-10 13:59 UTC
Labels: python3, support:core, bug, affects_2.9
