### ISSUE TITLE
ansible 2.0 no longer looks for ansible.cfg in playbook directory

### ISSUE THREAD

**Issue by oppianmatt** [ansible/ansible#14016] opened 2016-01-20 11:14 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

```
~ # ansible-playbook --version
ansible-playbook 2.0.0.2
  config file =
  configured module search path = Default w/o overrides
~ # ansible --version
ansible 2.0.0.2
  config file =
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

ansible.cfg

```
[defaults]
hostfile = ./hosts
nocows = 1
ansible_managed = Ansible managed, do not edit directly: {file} by {uid} on {host}

[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=30m -o ForwardAgent=yes
pipelining=True

```
##### Environment:

Ubuntu 12.04.5 LTS
Ubuntu 12.04.5 LTS
##### Summary:

Database copy script that has been running pre ansible 2.0 has started failing.
##### Steps To Reproduce:

Upgrade to ansible 2.0. Difference is that ansible 2.0 isn't picking up the ansible.cfg file that's in the same directory as the playbook and so uses default options for ssh. Don't know why the defaults for ssh fail but the fix is the cd into the directory first. Pre ansible 2.0 looked for config in the current play directory.
##### Expected Results:

```
# su copy_database -c '/usr/local/bin/ansible-playbook -f 1 /mnt/ssd/django/pitchup_prod/ansible/playbooks/pitchup/copy_database.yaml -i /
mnt/ssd/django/pitchup_prod/ansible/playbooks/pitchup/inventory/dev -vvvv'
Using /mnt/ssd/django/pitchup_prod/ansible/playbooks/pitchup/ansible.cfg as config file
[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and make sure become_method is 'sudo' (default). This feature will be removed in a future
release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
Loaded callback default of type stdout, v2.0
1 plays in /mnt/ssd/django/pitchup_prod/ansible/playbooks/pitchup/copy_database.yaml

PLAY [copy database] ***********************************************************


TASK [setup] *******************************************************************
<devpitchup.pitchup.com> ESTABLISH SSH CONNECTION FOR USER: None
<devpitchup.pitchup.com> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=30m -o ForwardAgent=yes -o KbdInteractiveAuthentication=no -o PreferredAuthentica
tions=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/copy_database/.ansible/cp/ansible-ssh-%h-%
p-%r devpitchup.pitchup.com '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-fgoaqjgnoouwszjfrcebkeazxrevfxfg; LANG=en_GB.UTF-8 LC
_ALL=en_GB.UTF-8 LC_MESSAGES=en_GB.UTF-8 /usr/bin/python'"'"'"'"'"'"'"'"''"'"''
ok: [devpitchup.pitchup.com]

...
```
##### Actual Results:

```
~ # su copy_database -c '/usr/local/bin/ansible-playbook -f 1 /mnt/ssd/django/pitchup_prod/ansible/playbooks/pitchup/copy_database.yaml -i /mnt/ssd/django/pitchup_prod/
ansible/playbooks/pitchup/inventory/dev -vvvv'
No config file found; using defaults
[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and make sure become_method is 'sudo' (default). This feature will be removed in a future
release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
Loaded callback default of type stdout, v2.0
1 plays in /mnt/ssd/django/pitchup_prod/ansible/playbooks/pitchup/copy_database.yaml

PLAY [copy database] ***********************************************************

TASK [setup] *******************************************************************
<devpitchup.pitchup.com> ESTABLISH SSH CONNECTION FOR USER: None
<devpitchup.pitchup.com> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mi
c,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/copy_database/.ansible/cp/ansible-ssh-%h-%p-%r -tt devpitchup.
pitchup.com '( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1453287563.5-209169123401042 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1453287563.5
-209169123401042 )" )'
<devpitchup.pitchup.com> PUT /tmp/tmprYQf0w TO       ^/setup
<devpitchup.pitchup.com> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-w
ith-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/copy_database/.ansible/cp/ansible-ssh-%h-%p-%r '[devpitc
hup.pitchup.com]'
fatal: [devpitchup.pitchup.com]: FAILED! => {"failed": true, "msg": "ERROR! failed to transfer file to       ^/setup:\nsftp> put /tmp/tmprYQf0w '      ^/setup'\nUploadi
ng /tmp/tmprYQf0w to /home/copy_database/      ^/setup\n\nOpenSSH_5.9p1 Debian-5ubuntu1.7, OpenSSL 1.0.1 14 Mar 2012\ndebug1: Reading configuration data /etc/ssh/ssh_co
nfig\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client
_hello_exchange: master version 4\r\ndebug3: mux_client_request_forwards: requesting forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\nd
ebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 25855\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: m
ux_client_request_session: master session id: 2\r\ndebug2: Remote version: 3\r\ndebug2: Server supports extension \"posix-rename@openssh.com\" revision 1\r\ndebug2: Ser
ver supports extension \"statvfs@openssh.com\" revision 2\r\ndebug2: Server supports extension \"fstatvfs@openssh.com\" revision 2\r\ndebug2: Server supports extension
\"hardlink@openssh.com\" revision 1\r\ndebug3: Sent message fd 3 T:16 I:32698\r\ndebug3: SSH_FXP_REALPATH . -> /home/copy_database\r\ndebug3: Looking up /tmp/tmprYQf0w\
r\ndebug3: Sent message fd 3 T:17 I:32699\r\ndebug3: Received stat reply T:101 I:32699\r\ndebug1: Couldn't stat remote file: No such file or directory\r\ndebug3: Sent m
essage SSH2_FXP_OPEN I:32700 P:/home/copy_database/      ^/setup\r\nremote open(\"/home/copy_database/      ^/setup\"): No such file or directory\r\ndebug3: mux_client_
read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n"}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
devpitchup.pitchup.com     : ok=0    changed=0    unreachable=0    failed=1
```

**Comment by jimi-c** [comment] 2016-01-20 15:40
This appears to be a duplicate of this issue: https://github.com/ansible/ansible/issues/13199

If you're using the fish shell (or some other alternate shell) you'll need to set the ansible_shell variable for your hosts.

**Comment by oppianmatt** [comment] 2016-01-20 16:22
No it's not a duplicate. The issue you linked to is the reason why sftp isn't working (thanks) but that's not this issue.

This issue is that ansible-playbook now no longer looks for an ansible.cfg file in the current directory of the playbook file (which triggers the sftp issue you linked to, but it's a separate issue). I'll update the title to reflect

**Comment by oppianmatt** [comment] 2016-01-20 16:23
If I `cd` first into the directory where the playbook is it works since it still looks for the cfg in the cwd.

**Comment by bcoca** [comment] 2016-01-20 16:28
AFAIK ansible has never looked at ansible.cfg in the playbook directory, there is actually a long time open feature request to add this #11175

**Comment by abadger** [comment] 2016-02-05 22:13
Took a look and it appears that ansible.cfg is found in the playbook directory in 1.9.4:

```
$ strace ansible-playbook ping.yml 2>&1 | grep ansible.cfg       (14:12:31)
stat("/srv/ansible/troubleshooting/ansible.cfg", {st_mode=S_IFREG|0644, st_size=10300, ...}) = 0
open("/srv/ansible/troubleshooting/ansible.cfg", O_RDONLY) = 6
$ ansible-playbook --version                                     (14:12:45)
ansible-playbook 1.9.4 (stable-1.9 3d7efff30c) last updated 2016/02/05 10:34:01 (GMT -700)
```

**Comment by abadger** [comment] 2016-02-05 22:15
_sigh_ forgot that that's being picked up because it is the cwd.

**Comment by sivel** [comment] 2016-02-05 22:15
@abadger is that the CWD?  CWD is one of the search locations.  If I understand your example, CWD is your playbook dir.

**Comment by abadger** [comment] 2016-02-05 22:16
ansible 1.9.4 does not pick up alongside the playbook:

```
$ strace ansible-playbook troubleshooting/ping.yml 2>&1 | grep ansible.cfg       (14:15:25)
stat("/srv/ansible/ansible.cfg", 0x7ffd41d3b9b0) = -1 ENOENT (No such file or directory)
stat("/home/badger/.ansible.cfg", 0x7ffd41d3b9b0) = -1 ENOENT (No such file or directory)
stat("/etc/ansible/ansible.cfg", {st_mode=S_IFREG|0644, st_size=10299, ...}) = 0
open("/etc/ansible/ansible.cfg", O_RDONLY) = 6
```

I'm going to close this in favor of the feature request ticket.

**Closed as completed by abadger** 2016-02-05 22:16 UTC
Labels: bug

**Comment by chichusam** [comment] 2016-09-21 05:27
how to compare two folder files in ansible
i have always single file in first directory
Folder1 : ls
sam.txt
cat sam.txt
 ram,ganesh

Folder2: ls
file1.txt 
file2.txt

cat file1.txt
ram,ganesh

cat file2.txt
ganesh,lathis

I need to compare the first directory files  with all the second directory files 
and if difference found then we need to print file name in new direcoty with file name , Please help on this
