### ISSUE TITLE
Using Packer with docker builder docker:     "msg": "failed to transfer file to /home/andy/.ansible/tmp/ansible-local-28321205jvrbj0f/tmpco4b64dw

### ISSUE THREAD

**Issue by andycockers** [ansible/ansible#76570] opened 2021-12-15 17:06 UTC
### Summary

I am using packer with docker builder and ansible provisioner.

Ansible version: 5.0.1 (pip3)

### Issue Type

Bug Report

### Component Name

ansible

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.1]
  config file = None
  configured module search path = ['/home/andy/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/andy/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/andy/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/andy/.local/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
  jinja version = 3.0.1
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
No output
```

### OS / Environment

Ubuntu 20.04
Packer version: 1.7.4

### Steps to Reproduce

```{
    "variables": {
        "password": "{{env `PASSWORD`}}"
      },

    "builders": [
        {
            "type": "docker",
            "image": "golang",
            "commit": true,
            "run_command": ["-d", "-i", "-t", "{{.Image}}", "/bin/sh"]

        }
    ],

    "provisioners": [
        {
            "type": "ansible",
            "playbook_file": "../../ansible/install-terraform.yml",
            "ansible_env_vars": ["ANSIBLE_PYTHON_INTERPRETER=/usr/bin/python3", "ANSIBLE_HOST_KEY_CHECKING=False"],
            "extra_arguments": ["-vvv"]
        }
    ],

    "post-processors": [
        [
        {
            "type": "docker-tag",
            "repository": "calmmopey/terratest-terraform",
            "tag": "latest"
        },

        {
            "type": "docker-push",
            "login": true,
            "login_username": "calmmopey",
            "login_password": "{{ user `password` }}"
        }
    ]
]



}
```
playbook
```
---
- hosts: all
  roles:
    - role: install-unzip
    - role: install-terraform
```

### Expected Results

I expected packer to build a new image using ansible provisioner.

### Actual Results

```console
==> docker: Creating a temporary directory for sharing data...
==> docker: Pulling Docker image: golang
    docker: Using default tag: latest
    docker: latest: Pulling from library/golang
    docker: Digest: sha256:eb61213fe612b6af346cab13c2b81f1b8113f9ccf23a5ca6b54fede8ffd63bc7
    docker: Status: Image is up to date for golang:latest
    docker: docker.io/library/golang:latest
==> docker: Starting docker container...
    docker: Run command: docker run -v /home/andy/.packer.d/tmp940286880:/packer-files -d -i -t golang /bin/sh
    docker: Container ID: 2229f699291545ab5b2c95cd590ec11b8ede383b6c0943208e90327f74657b10
==> docker: Using docker communicator to connect: 172.17.0.3
==> docker: Provisioning with Ansible...
    docker: Setting up proxy adapter for Ansible....
==> docker: Executing Ansible: ansible-playbook -e packer_build_name="docker" -e packer_builder_type=docker -vvv -e ansible_ssh_private_key_file=/tmp/ansible-key191122150 -i /tmp/packer-provisioner-ansible052019469 /home/andy/github/gcp-automation/ansible/install-terraform.yml
    docker: ansible-playbook [core 2.12.1]
    docker:   config file = None
    docker:   configured module search path = ['/home/andy/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
    docker:   ansible python module location = /home/andy/.local/lib/python3.8/site-packages/ansible
    docker:   ansible collection location = /home/andy/.ansible/collections:/usr/share/ansible/collections
    docker:   executable location = /home/andy/.local/bin/ansible-playbook
    docker:   python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
    docker:   jinja version = 3.0.1
    docker:   libyaml = True
    docker: No config file found; using defaults
    docker: host_list declined parsing /tmp/packer-provisioner-ansible052019469 as it did not pass its verify_file() method
    docker: script declined parsing /tmp/packer-provisioner-ansible052019469 as it did not pass its verify_file() method
    docker: auto declined parsing /tmp/packer-provisioner-ansible052019469 as it did not pass its verify_file() method
    docker: Parsed /tmp/packer-provisioner-ansible052019469 inventory source with ini plugin
    docker: Skipping callback 'default', as we already have a stdout callback.
    docker: Skipping callback 'minimal', as we already have a stdout callback.
    docker: Skipping callback 'oneline', as we already have a stdout callback.
    docker:
    docker: PLAYBOOK: install-terraform.yml ************************************************
    docker: 1 plays in /home/andy/github/gcp-automation/ansible/install-terraform.yml
    docker:
    docker: PLAY [all] *********************************************************************
    docker:
    docker: TASK [Gathering Facts] *********************************************************
    docker: task path: /home/andy/github/gcp-automation/ansible/install-terraform.yml:2
    docker: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: andy
    docker: <127.0.0.1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=40059 -o 'IdentityFile="/tmp/ansible-key191122150"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="andy"' -o ConnectTimeout=10 -o ControlPath=/home/andy/.ansible/cp/0a86fe56ca 127.0.0.1 '/bin/sh -c '"'"'echo ~andy && sleep 0'"'"''
    docker: <127.0.0.1> (0, b'~andy\n', b"Warning: Permanently added '[127.0.0.1]:40059' (RSA) to the list of known hosts.\r\nX11 forwarding request failed\r\n")
    docker: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: andy
    docker: <127.0.0.1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=40059 -o 'IdentityFile="/tmp/ansible-key191122150"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="andy"' -o ConnectTimeout=10 -o ControlPath=/home/andy/.ansible/cp/0a86fe56ca 127.0.0.1 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo ~andy/.ansible/tmp `"&& mkdir "` echo ~andy/.ansible/tmp/ansible-tmp-1639587343.0352461-2835464-171413303330390 `" && echo ansible-tmp-1639587343.0352461-2835464-171413303330390="` echo ~andy/.ansible/tmp/ansible-tmp-1639587343.0352461-2835464-171413303330390 `" ) && sleep 0'"'"''
    docker: <127.0.0.1> (0, b'ansible-tmp-1639587343.0352461-2835464-171413303330390=~andy/.ansible/tmp/ansible-tmp-1639587343.0352461-2835464-171413303330390\n', b'X11 forwarding request failed\r\n')
    docker: Using module file /home/andy/.local/lib/python3.8/site-packages/ansible/modules/setup.py
    docker: <127.0.0.1> PUT /home/andy/.ansible/tmp/ansible-local-2835459ms_8z15m/tmp6ox457rv TO ~andy/.ansible/tmp/ansible-tmp-1639587343.0352461-2835464-171413303330390/AnsiballZ_setup.py
    docker: <127.0.0.1> SSH: EXEC scp -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=40059 -o 'IdentityFile="/tmp/ansible-key191122150"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="andy"' -o ConnectTimeout=10 -o ControlPath=/home/andy/.ansible/cp/0a86fe56ca /home/andy/.ansible/tmp/ansible-local-2835459ms_8z15m/tmp6ox457rv '[127.0.0.1]:'"'"'~andy/.ansible/tmp/ansible-tmp-1639587343.0352461-2835464-171413303330390/AnsiballZ_setup.py'"'"''
    docker: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: andy
    docker: <127.0.0.1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=40059 -o 'IdentityFile="/tmp/ansible-key191122150"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="andy"' -o ConnectTimeout=10 -o ControlPath=/home/andy/.ansible/cp/0a86fe56ca 127.0.0.1 '/bin/sh -c '"'"'rm -f -r '"'"'"'"'"'"'"'"'~andy/.ansible/tmp/ansible-tmp-1639587343.0352461-2835464-171413303330390/'"'"'"'"'"'"'"'"' > /dev/null 2>&1 && sleep 0'"'"''
    docker: <127.0.0.1> (0, b'', b'X11 forwarding request failed\r\n')
    docker: fatal: [default]: FAILED! => {
    docker:     "msg": "failed to transfer file to /home/andy/.ansible/tmp/ansible-local-2835459ms_8z15m/tmp6ox457rv ~andy/.ansible/tmp/ansible-tmp-1639587343.0352461-2835464-171413303330390/AnsiballZ_setup.py:\n\n\n"
    docker: }
    docker:
    docker: PLAY RECAP *********************************************************************
    docker: default                    : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
    docker:
==> docker: Provisioning step had errors: Running the cleanup provisioner, if present...
==> docker: Killing the container: 2229f699291545ab5b2c95cd590ec11b8ede383b6c0943208e90327f74657b10
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by sivel** [comment] 2021-12-15 17:10
Duplicate of https://github.com/ansible/ansible/issues/74072

This is caused by the proxy that packer attempts to use.  Your best bet is to disable the proxy:

https://www.packer.io/docs/provisioners/ansible/ansible#use_proxy

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.libera.chat
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Closed as completed by sivel** 2021-12-15 17:10 UTC

**Comment by andycockers** [comment] 2021-12-15 17:15
Sadly, setting "use_proxy": false still fails:
```
docker: output will be in this color.

==> docker: Creating a temporary directory for sharing data...
==> docker: Pulling Docker image: golang
    docker: Using default tag: latest
    docker: latest: Pulling from library/golang
    docker: Digest: sha256:eb61213fe612b6af346cab13c2b81f1b8113f9ccf23a5ca6b54fede8ffd63bc7
    docker: Status: Image is up to date for golang:latest
    docker: docker.io/library/golang:latest
==> docker: Starting docker container...
    docker: Run command: docker run -v /home/andy/.packer.d/tmp001663705:/packer-files -d -i -t golang /bin/sh
    docker: Container ID: f674eea9567408514e0a7f4d465c0ade76231d420be37052e0e3800820d97471
==> docker: Using docker communicator to connect: 172.17.0.3
==> docker: Provisioning with Ansible...
==> docker: Warning: use_proxy is false, but instance does not have an IP address to give to Ansible. Falling back to use localhost proxy.
==> docker: Warning: use_proxy is false, but communicator is neither ssh nor winrm, so without the proxy ansible will not function. Falling back to localhost proxy.
    docker: Setting up proxy adapter for Ansible....
==> docker: Executing Ansible: ansible-playbook -e packer_build_name="docker" -e packer_builder_type=docker -vvv -e ansible_ssh_private_key_file=/tmp/ansible-key171947856 -i /tmp/packer-provisioner-ansible862275695 /home/andy/github/gcp-automation/ansible/install-terraform.yml
    docker: ansible-playbook [core 2.12.1]
    docker:   config file = None
    docker:   configured module search path = ['/home/andy/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
    docker:   ansible python module location = /home/andy/.local/lib/python3.8/site-packages/ansible
    docker:   ansible collection location = /home/andy/.ansible/collections:/usr/share/ansible/collections
    docker:   executable location = /home/andy/.local/bin/ansible-playbook
    docker:   python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
    docker:   jinja version = 3.0.1
    docker:   libyaml = True
    docker: No config file found; using defaults
    docker: host_list declined parsing /tmp/packer-provisioner-ansible862275695 as it did not pass its verify_file() method
    docker: script declined parsing /tmp/packer-provisioner-ansible862275695 as it did not pass its verify_file() method
    docker: auto declined parsing /tmp/packer-provisioner-ansible862275695 as it did not pass its verify_file() method
    docker: Parsed /tmp/packer-provisioner-ansible862275695 inventory source with ini plugin
    docker: Skipping callback 'default', as we already have a stdout callback.
    docker: Skipping callback 'minimal', as we already have a stdout callback.
    docker: Skipping callback 'oneline', as we already have a stdout callback.
    docker:
    docker: PLAYBOOK: install-terraform.yml ************************************************
    docker: 1 plays in /home/andy/github/gcp-automation/ansible/install-terraform.yml
    docker:
    docker: PLAY [all] *********************************************************************
    docker:
    docker: TASK [Gathering Facts] *********************************************************
    docker: task path: /home/andy/github/gcp-automation/ansible/install-terraform.yml:2
    docker: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: andy
    docker: <127.0.0.1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=38583 -o 'IdentityFile="/tmp/ansible-key171947856"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="andy"' -o ConnectTimeout=10 -o ControlPath=/home/andy/.ansible/cp/faf1118d9d 127.0.0.1 '/bin/sh -c '"'"'echo ~andy && sleep 0'"'"''
    docker: <127.0.0.1> (0, b'~andy\n', b"Warning: Permanently added '[127.0.0.1]:38583' (RSA) to the list of known hosts.\r\nX11 forwarding request failed\r\n")
    docker: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: andy
    docker: <127.0.0.1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=38583 -o 'IdentityFile="/tmp/ansible-key171947856"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="andy"' -o ConnectTimeout=10 -o ControlPath=/home/andy/.ansible/cp/faf1118d9d 127.0.0.1 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo ~andy/.ansible/tmp `"&& mkdir "` echo ~andy/.ansible/tmp/ansible-tmp-1639588471.992309-2839149-139352755440181 `" && echo ansible-tmp-1639588471.992309-2839149-139352755440181="` echo ~andy/.ansible/tmp/ansible-tmp-1639588471.992309-2839149-139352755440181 `" ) && sleep 0'"'"''
    docker: <127.0.0.1> (0, b'ansible-tmp-1639588471.992309-2839149-139352755440181=~andy/.ansible/tmp/ansible-tmp-1639588471.992309-2839149-139352755440181\n', b'X11 forwarding request failed\r\n')
    docker: Using module file /home/andy/.local/lib/python3.8/site-packages/ansible/modules/setup.py
    docker: <127.0.0.1> PUT /home/andy/.ansible/tmp/ansible-local-2839144zzp4jh6q/tmpbdsdnw9r TO ~andy/.ansible/tmp/ansible-tmp-1639588471.992309-2839149-139352755440181/AnsiballZ_setup.py
    docker: <127.0.0.1> SSH: EXEC scp -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=38583 -o 'IdentityFile="/tmp/ansible-key171947856"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="andy"' -o ConnectTimeout=10 -o ControlPath=/home/andy/.ansible/cp/faf1118d9d /home/andy/.ansible/tmp/ansible-local-2839144zzp4jh6q/tmpbdsdnw9r '[127.0.0.1]:'"'"'~andy/.ansible/tmp/ansible-tmp-1639588471.992309-2839149-139352755440181/AnsiballZ_setup.py'"'"''
    docker: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: andy
    docker: <127.0.0.1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=38583 -o 'IdentityFile="/tmp/ansible-key171947856"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="andy"' -o ConnectTimeout=10 -o ControlPath=/home/andy/.ansible/cp/faf1118d9d 127.0.0.1 '/bin/sh -c '"'"'rm -f -r '"'"'"'"'"'"'"'"'~andy/.ansible/tmp/ansible-tmp-1639588471.992309-2839149-139352755440181/'"'"'"'"'"'"'"'"' > /dev/null 2>&1 && sleep 0'"'"''
    docker: <127.0.0.1> (0, b'', b'X11 forwarding request failed\r\n')
    docker: fatal: [default]: FAILED! => {
    docker:     "msg": "failed to transfer file to /home/andy/.ansible/tmp/ansible-local-2839144zzp4jh6q/tmpbdsdnw9r ~andy/.ansible/tmp/ansible-tmp-1639588471.992309-2839149-139352755440181/AnsiballZ_setup.py:\n\n\n"
    docker: }
    docker:
    docker: PLAY RECAP *********************************************************************
    docker: default                    : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
    docker:
==> docker: Provisioning step had errors: Running the cleanup provisioner, if present...
==> docker: Killing the container: f674eea9567408514e0a7f4d465c0ade76231d420be37052e0e3800820d97471
Build 'docker' errored after 3 seconds 856 milliseconds: Error executing Ansible: Non-zero exit status: exit status 2
```

**Comment by sivel** [comment] 2021-12-15 17:26
It appears as though you are connecting via SSH to a user that doesn't appear to exist in the docker container, and thus `echo ~andy` is failing to properly expand.  That should expand to something like `/home/andy` but it is not.  There are other various reasons this may not work.  You may need to adjust your `remote_tmp` setting to use `$HOME` instead of `~`.
