### ISSUE TITLE
Type conversion error in k8s lookup plugin on Python3

### ISSUE THREAD

**Issue by kuwv** [ansible/ansible#69836] opened 2020-06-02 14:52 UTC
##### SUMMARY

Doing a `cluster_info` with the k8s lookup plugin returns TypeError using Python3.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

k8s lookup https://github.com/ansible-collections/community.kubernetes/blob/master/plugins/lookup/k8s.py

##### ANSIBLE VERSION

```paste below
ansible 2.9.9
  config file = /Users/kuwv/.ansible.cfg
  configured module search path = ['/Users/kuwv/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/kuwv/.local/share/virtualenvs/openshift_deployment-0LT7SYuW/lib/python3.7/site-packages/ansible
  executable location = /Users/kuwv/.local/share/virtualenvs/openshift_deployment-0LT7SYuW/bin/ansible
  python version = 3.7.7 (default, Mar 10 2020, 15:43:33) [Clang 11.0.0 (clang-1100.0.33.17)]
```
Tested with Python versions: 2.7.16 and 3.7.7
Tested with Ansible versions: 2.8, and 2.7.
Tested with openshift (openshift-restclient-python) versions: 0.11.0, 0.10.0, 0.9.0, and 0.8.0
Tested against CRC, MiniShift, and MiniKube.

##### CONFIGURATION

```paste below
COLOR_VERBOSE(/Users/kuwv/.ansible.cfg) = bright blue
DEFAULT_ROLES_PATH(env: ANSIBLE_ROLES_PATH) = ['/Users/kuwv/devel/ansible_collections/example/deployment/roles']
HOST_KEY_CHECKING(/Users/kuwv/.ansible.cfg) = False
INTERPRETER_PYTHON(/Users/kuwv/.ansible.cfg) = /usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/bin/python3
```

##### OS / ENVIRONMENT

MacOS Catalina
Fedora 31
CentOS 7

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost

  tasks:
    - name: Get api groups
      set_fact:
        api_groups: "{{ lookup('k8s', cluster_info='api_groups') }}"

    - debug:
        var: api_groups
```

##### EXPECTED RESULTS

```
TASK [Get api groups] ************************************************************************************************************************************************************************************
task path: ~/devel/ansible_collections/example/deployment/playbooks/get-cluster-info.yml:6
ok: [localhost] => {
    "ansible_facts": {
        "api_groups": [
            "", 
            "certificates.k8s.io", 
            "events.k8s.io", 
            "authorization.k8s.io", 
            "apiextensions.k8s.io", 
            "node.k8s.io", 
            "autoscaling", 
            "apps", 
            "batch", 
            "apiregistration.k8s.io", 
            "discovery.k8s.io", 
            "networking.k8s.io", 
            "extensions", 
            "storage.k8s.io", 
            "policy", 
            "coordination.k8s.io", 
            "rbac.authorization.k8s.io", 
            "scheduling.k8s.io", 
            "admissionregistration.k8s.io", 
            "authentication.k8s.io"
        ]
    }, 
    "changed": false
}
```

##### ACTUAL RESULTS

```
TASK [Get api groups] ************************************************************************************************************************************************************************************
task path: ~/devel/ansible_collections/example/deployment/playbooks/get-cluster-info.yml:5
[WARNING]: Failure using method (v2_runner_on_ok) in callback plugin (<ansible.plugins.callback.default.CallbackModule object at 0x10a0408d0>): Object of type set is not JSON serializable
Callback Exception: 
  File "~/.local/share/virtualenvs/venv/lib/python3.7/site-packages/ansible/executor/task_queue_manager.py", line 324, in send_callback
    method(*new_args, **kwargs)
   File "~/.local/share/virtualenvs/venv/lib/python3.7/site-packages/ansible/plugins/callback/default.py", line 156, in v2_runner_on_ok
    msg += " => %s" % (self._dump_results(result._result),)
   File "~/.local/share/virtualenvs/venv/lib/python3.7/site-packages/ansible/plugins/callback/__init__.py", line 135, in _dump_results
    ensure_ascii=False, sort_keys=False)
   File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
   File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
   File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
   File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
   File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
   File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
   File "~/.local/share/virtualenvs/venv/lib/python3.7/site-packages/ansible/module_utils/common/json.py", line 59, in default
    value = super(AnsibleJSONEncoder, self).default(o)
   File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
```

**Comment by kuwv** [comment] 2020-06-02 14:54
Moved here on request:
https://github.com/ansible-collections/community.kubernetes/issues/111#issuecomment-636969342
https://github.com/ansible-collections/community.kubernetes/issues/111#issuecomment-636970438

**Comment by sivel** [comment] 2020-06-02 14:59
I believe this is an issue with the lookup.  I talked to @Akasurde yesterday about why we don't automatically convert `set` to `list` for JSON encoding. That is typically a controversial topic, because a set has special meaning, that is lost in JSON encoding.  So it requires making some assumptions.

Because the JSON encoder we use here is general purpose, my belief is that it should be up to the individual plugins to perform this type change as needed for their purpose, before the data is sent for JSON encoding.

**Comment by Akasurde** [comment] 2020-06-02 14:59
Reproducer - https://github.com/Akasurde/ansible-reproducers/tree/master/111

**Comment by kuwv** [comment] 2020-06-02 16:14
@sivel @Akasurde Should we continue here or in the Kubernetes community?

**Comment by jimi-c** [comment] 2020-06-02 19:00
As this has been moved to the proper collection, we'll go ahead and close it here. Please move all discussion to the new issue(s).

Thanks!

**Closed as completed by jimi-c** 2020-06-02 19:00 UTC
