### ISSUE TITLE
fileglob lookup doesn't return directories or special files

### ISSUE THREAD

**Issue by jkleint** [ansible/ansible#3012] opened 2013-05-24 15:40 UTC
```

---
- hosts: all
  gather_facts: False

  tasks:
  - debug: msg={{ item }}
    with_fileglob: /usr/*
  - debug: msg={{ item }}
    with_fileglob: /dev/*
```

```
$ ansible-playbook fileglob.yml

PLAY [all] ******************************************************************** 

TASK: [debug msg={{item}}] **************************************************** 
skipping: [localhost]

TASK: [debug msg={{item}}] **************************************************** 
ok: [localhost] => (item=/dev/MAKEDEV)
ok: [localhost] => (item=/dev/core)

PLAY RECAP ******************************************************************** 
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```

Version 1d3782cfc7 on CentOS 5.9.  Ideally it'd return all files by default, with options to filter by type (dir, link, FIFO, etc.).  And I guess this is more of a feature request, but it'd be nice to have an option to recurse, too -- incidentally, this would net everyone's favorite feature request, recursive copy, for free.  (Ooo ooh, and while we're dreaming, an option to strip paths, too!)

**Comment by bcoca** [comment] 2013-05-24 21:25
with_pipe or with_lines:   find ....

already does what you want.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by mpdehaan** [comment] 2013-05-25 13:17
Yeah it's "with_FILEglob" so it returns files :)

However, you could have another lookup plugin added that is with_tree (is that a bad name?  with_fileglob_recursive is so long), and I would gladly take a patch for that.   Not sure if path/to/foo/\* should return everything under "_" if "_" is a directory or what though.

(BTW I really think people want recursive copy to be native, really, rather than having to do  "with_" because you only get one "with_")

I want to add native recursive copy for 1.2 though we'll see if it can happen.

**Comment by mpdehaan** [comment] 2013-05-25 13:18
closing this as it is working as designed, but open to the above module idea

**Closed as completed by mpdehaan** 2013-05-25 13:18 UTC

**Comment by jkleint** [comment] 2013-05-25 22:26
I actually started work on just such a plugin, and couldn't think of a good name either, ended up going with with_tree as well.  :)  I thought about with_files (plural) maybe?  But that could be confusingly close to with_file... anyway I'll post my lookup plugin and you can see if you'd rather go native module.  Check out #3021.

**Comment by bcoca** [comment] 2013-05-28 19:20
with_subtree
with_recursive
with_subdirs
with_tar
with_?insanity?

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno
