### ISSUE TITLE
Loop on too many items with include + with_items

### ISSUE THREAD

**Issue by tcottier-enalean** [ansible/ansible#11872] opened 2015-08-06 11:45 UTC
## Issue Type:

```
Bug Report
```
## Ansible Version:

ansible 2.0.0 (devel 151010920d) last updated 2015/08/06 13:20:04 (GMT +200)
## Ansible Configuration:

N/A
## Environment:

Fedora 21
## Summary:

When I use a playbook using ansible v2 capabilities of include + with_items, It fails with "Unexpected Exception: 'results'". It seems the loop on items iterate too much
## Steps To Reproduce:

Create a playbook like this one: 

```
- hosts: localhost
  tasks:
    - include: debug.yml letter={{item}}
      with_items: letters
  vars:
    - letters:
      - a
      - b
      - c
```

Debug.yml file:

```
- debug: var=letter
```

Then run:

```
ansible-playbook -i inventory/localhost test.yml -vvv
```
## Expected Results:

Each letter is printed, the script exits without error
## Actual Results:

```
TASK [include letter={{item}}] **************************************************
included: debug.yml for localhost => (item=a)
included: debug.yml for localhost => (item=b)
included: debug.yml for localhost => (item=c)
included: debug.yml for localhost
Unexpected Exception: 'results'
the full traceback was:

Traceback (most recent call last):
  File "/home/tcottier/src/ansible/bin/ansible-playbook", line 80, in <module>
    sys.exit(cli.run())
  File "/home/tcottier/src/ansible/lib/ansible/cli/playbook.py", line 142, in run
    results = pbex.run()
  File "/home/tcottier/src/ansible/lib/ansible/executor/playbook_executor.py", line 141, in run
    result = self._tqm.run(play=play)
  File "/home/tcottier/src/ansible/lib/ansible/executor/task_queue_manager.py", line 192, in run
    return strategy.run(iterator, play_context)
  File "/home/tcottier/src/ansible/lib/ansible/plugins/strategies/linear.py", line 242, in run
    included_files = IncludedFile.process_include_results(host_results, self._tqm, iterator=iterator, loader=self._loader, variable_manager=self._variable_manager)
  File "/home/tcottier/src/ansible/lib/ansible/playbook/included_file.py", line 54, in process_include_results
    include_results = res._result['results']
KeyError: 'results'
```

**Comment by udondan** [comment] 2015-08-10 15:12
Confirming this.

```
- include: foo.yml
  with_items: [a,b,c]
```

> TASK [foo-playbook : include] *************************************************
> included: foo.yml for localhost => (item=a)
> included: foo.yml for localhost => (item=b)
> included: foo.yml for localhost => (item=c)
> included: foo.yml for localhost
> Unexpected Exception: 'results'

Same goes for `with_dict`. (probably for all `with_*`).

**Comment by srgvg** [comment] 2015-08-10 16:19
I'm seeing an extra loop item on a regular lookup loop (not combined with an include), but no hard fail:

```
TASK [rackufw : allow ports before enabling firewall] **************************
ok: [hydargos] => (item={u'port': 80, u'proto': u'tcp'})
ok: [hydargos] => (item={u'port': 443, u'proto': u'tcp'})
ok: [hydargos] => (item={u'port': 5222, u'proto': u'tcp'})
ok: [hydargos] => (item={u'port': 5269, u'proto': u'tcp'})
ok: [hydargos]
```

running on `2.0.0 (devel e32d887609)`

**Comment by jimi-c** [comment] 2015-08-10 17:35
Working on this now, there's definitely some oddities popping up since the way results are passed back with loop items was changed.

**Comment by jimi-c** [comment] 2015-08-11 05:34
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-08-11 05:34 UTC
Labels: bug

**Comment by udondan** [comment] 2015-08-11 09:09
Confirmed, works with in current devel branch. Thanks!
