### ISSUE TITLE
--start-at-tasks is no longer working

### ISSUE THREAD

**Issue by jgrigonis** [ansible/ansible#12718] opened 2015-10-13 01:00 UTC
This was working as few as 2 weeks ago.

**Comment by jimi-c** [comment] 2015-10-13 01:21
Hi @jgrigonis, could you provide some examples that reproduce the issue your seeing?

Thanks!

**Comment by jgrigonis** [comment] 2015-10-13 01:31
ansible-playbook any.yml --start-at-task="foo bar"

**Comment by jgrigonis** [comment] 2015-10-13 01:41
Actually, it's not reproducing as easy as I thought. I have a pretty large yml that is causing it.






# This only installs the client software
# You will need to make configuration changes to neptunemon to actually monitor
---
- hosts: "infrastructure,testservers,devservers"
  vars:
    nrpe_version: 2.15
  remote_user: root
  tasks:
    - name: install wget
      yum: name=wget state=latest
    - include: tasks/install_rpmforge.yml
    - name: install utilities
      yum: "name={{ item }} state=latest"
      with_items:
        - gcc
        - make
        - automake
        - openssl
        - openssl-devel
        - xinetd
    - name: add nagios group
      group: name=nagios gid=9000 state=present
    - name: add nagios user
      user: name=nagios group=nagios uid=9000 home=/usr/local/nagios comment="Nagios NRPE"
    - name: "get NRPE version {{ nrpe_version }}"
      get_url: "url=http://sourceforge.net/projects/nagios/files/nrpe-2.x/nrpe-{{ nrpe_version }}/nrpe-{{ nrpe_version }}.tar.gz dest=/usr/src"
    # unarchive reports changed incorrectly
    - name: unarchive nrpe
      unarchive: "src=/usr/src/nrpe-{{ nrpe_version }}.tar.gz dest=/usr/src/ copy=no"
    - name: run configure script
      command: ./configure --sysconfdir=/usr/local/nagios/etc --enable-ssl --enable-command-args
      args:
        chdir: "/usr/src/nrpe-{{ nrpe_version }}"
    - name: make nrpe
      command: make
      args:
        chdir: "/usr/src/nrpe-{{ nrpe_version }}"
    - name: make install nrpe
      command: make install
      args:
        chdir: "/usr/src/nrpe-{{ nrpe_version }}"
    - name: Install libselinux
      include: tasks/libselinux-python.yml
    - name: assures libexec dir exists
      file: dest=/usr/local/nagios/libexec state=directory
    - name: copy nagios libraries
      copy: "src={{ item }} dest=/usr/local/nagios/libexec/ owner=nagios group=nagios mode=0755"
      with_fileglob:
        - binaries/nagios/*
    - name: assures etc dir exists
      file: path=/usr/local/nagios/etc/ state=directory owner=nagios group=nagios
    - name: create nrpe.cfg
      copy: src=files/nrpe.cfg dest=/usr/local/nagios/etc/nrpe.cfg owner=nagios group=nagios force=no backup=yes
    - name: assures xinet.d dir exists
      file: path=/etc/xinetd.d/ state=directory
    - name: create nrpe file
      copy: src=files/nrpe dest=/etc/xinetd.d/nrpe
    - name: update services
      lineinfile: 'dest=/etc/services state=present line="nrpe\t\t5666/tcp\t\t# Nagios NRPE"'
    - name: start xinetd
      service: name=xinetd state=restarted
    - include: tasks/nagios_iptables.yml
    # This is pretty weak way to do this
    - name: update bashrc
      lineinfile: dest=/root/.bashrc insertafter="^fi" line='alias nagios="cd /usr/local/nagios/etc"'
    - name: update nrpe.cfg
      lineinfile: dest=/usr/local/nagios/etc/nrpe.cfg line='dont_blame_nrpe=1'


Trying ansible-playbook install_nagios_nrpe.yml --start-at-task="update nrpe.cfg"

**Comment by jgrigonis** [comment] 2015-10-13 01:43
Github won't let me upload .yml...

**Comment by jgrigonis** [comment] 2015-10-13 01:44
http://pastebin.com/fcGdGUQX

Trying ansible-playbook install_nagios_nrpe.yml --start-at-task="update nrpe.cfg"

**Comment by jimi-c** [comment] 2015-10-13 16:47
@jgrigonis Is the task you're starting at inside one of the includes?

**Comment by jimi-c** [comment] 2015-10-13 16:59
Running with a simulated playbook (15 debug tasks with different names followed by one with the same title as yours), I see this working as expected:

<pre>
# ansible-playbook -vv test.yml --start-at-task="update nrpe.cfg"
Using /etc/ansible/ansible.cfg as config file
1 plays in test.yml
PLAY ***************************************************************************
TASK [update nrpe.cfg] *********************************************************
ok: [localhost -> localhost] => {
    "changed": false, 
    "msg": "this is the one i want"
}
PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
</pre>

**Comment by jgrigonis** [comment] 2015-10-13 16:59
It's not. I just searched the whole code, but there's definitely other
weird behavior around --start-at-task.

**Comment by jgrigonis** [comment] 2015-10-13 17:07
Here's another run exhibiting very odd behavior. Note the setup running
twice. Note that update nrpe.cfg is the very last task, so none of these
other tasks should be running at all.  I had to Control C as it either
hung, or was obviously off in the woods.

(ansible)Joshuas-MacBook-Pro:playbooks jgrigonis$ ansible-playbook
install_nagios_nrpe.yml --start-at-task="update nrpe.cfg"

PLAY

---

TASK [setup]

---

ok: [neptunego -> localhost]

ok: [neptuneref -> localhost]

ok: [marsdb -> localhost]

ok: [neptunepipe -> localhost]

ok: [marspipe -> localhost]

ok: [saturnpipe -> localhost]

ok: [marsweb -> localhost]

ok: [testrefgo -> localhost]

ok: [devpipe3 -> localhost]

ok: [neptunermq -> localhost]

ok: [devrmq -> localhost]

ok: [devref -> localhost]

ok: [dbrep2 -> localhost]

ok: [devpipe -> localhost]

ok: [devdb -> localhost]

ok: [parsetest1 -> localhost]

ok: [dbrep1 -> localhost]

ok: [devweb -> localhost]

TASK [setup]

---

ok: [jenkins -> localhost]

ok: [neptunego -> localhost]

ok: [neptuneref -> localhost]

ok: [marsdb -> localhost]

ok: [neptunepipe -> localhost]

ok: [neptunermq -> localhost]

ok: [marspipe -> localhost]

ok: [marsweb -> localhost]

ok: [testrefgo -> localhost]

ok: [saturnpipe -> localhost]

ok: [devrmq -> localhost]

ok: [devref -> localhost]

ok: [devpipe3 -> localhost]

ok: [dbrep2 -> localhost]

ok: [devpipe -> localhost]

ok: [dbrep1 -> localhost]

ok: [devdb -> localhost]

ok: [parsetest1 -> localhost]

ok: [devweb -> localhost]

TASK [update nrpe.cfg]

---

included: tasks/install_rpmforge.yml for marsdb

included: tasks/install_rpmforge.yml for neptunego

included: tasks/install_rpmforge.yml for neptunepipe

included: tasks/install_rpmforge.yml for neptuneref

included: tasks/install_rpmforge.yml for marsweb

included: tasks/install_rpmforge.yml for saturnpipe

included: tasks/install_rpmforge.yml for testrefgo

included: tasks/install_rpmforge.yml for marspipe

included: tasks/install_rpmforge.yml for devpipe

included: tasks/install_rpmforge.yml for devpipe3

included: tasks/install_rpmforge.yml for devref

included: tasks/install_rpmforge.yml for devrmq

included: tasks/install_rpmforge.yml for dbrep1

included: tasks/install_rpmforge.yml for dbrep2

included: tasks/install_rpmforge.yml for parsetest1

ok: [jenkins -> localhost]

included: tasks/install_rpmforge.yml for neptunermq

included: tasks/install_rpmforge.yml for devdb

included: tasks/install_rpmforge.yml for devweb

TASK [include_vars]

---

ok: [marsdb -> localhost]

ok: [neptunego -> localhost]

ok: [neptunepipe -> localhost]

ok: [neptuneref -> localhost]

ok: [neptunermq -> localhost]

ok: [marsweb -> localhost]

ok: [saturnpipe -> localhost]

ok: [testrefgo -> localhost]

ok: [marspipe -> localhost]

ok: [devdb -> localhost]

ok: [devpipe -> localhost]

ok: [devpipe3 -> localhost]

ok: [devref -> localhost]

ok: [devrmq -> localhost]

ok: [devweb -> localhost]

ok: [dbrep1 -> localhost]

ok: [dbrep2 -> localhost]

ok: [parsetest1 -> localhost]

TASK [get rpmforge]

---

^C

PLAY RECAP

---

dbrep1                     : ok=4    changed=0    unreachable=0
failed=0

dbrep2                     : ok=4    changed=0    unreachable=0
failed=0

devdb                      : ok=4    changed=0    unreachable=0
failed=0

devpipe                    : ok=4    changed=0    unreachable=0
failed=0

devpipe3                   : ok=4    changed=0    unreachable=0
failed=0

devref                     : ok=4    changed=0    unreachable=0
failed=0

devrmq                     : ok=4    changed=0    unreachable=0
failed=0

devweb                     : ok=4    changed=0    unreachable=0
failed=0

jenkins                    : ok=2    changed=0    unreachable=0
failed=0

marsdb                     : ok=4    changed=0    unreachable=0
failed=0

marspipe                   : ok=4    changed=0    unreachable=0
failed=0

marsweb                    : ok=4    changed=0    unreachable=0
failed=0

neptunego                  : ok=4    changed=0    unreachable=0
failed=0

neptunepipe                : ok=4    changed=0    unreachable=0
failed=0

neptuneref                 : ok=4    changed=0    unreachable=0
failed=0

neptunermq                 : ok=4    changed=0    unreachable=0
failed=0

parsetest1                 : ok=4    changed=0    unreachable=0
failed=0

saturnpipe                 : ok=4    changed=0    unreachable=0
failed=0

testrefgo                  : ok=4    changed=0    unreachable=0
failed=0

**Comment by jgrigonis** [comment] 2015-10-13 17:11
Here's another oddball output. Note the double setup again, note that
"install utilities" has nothing to do with the included task
install_rpmforge and it was intentionally skipped because it doesn't work
on puck.  Then see how the machine fails, but then they come back and are
both running tasks again.  Bizarre.

(ansible)Joshuas-MacBook-Pro:playbooks jgrigonis$ ansible-playbook
install_nagios_nrpe_prod.yml -l oberon,puck --start-at-task="install
utilities"

PLAY

---

TASK [setup]

---

ok: [puck -> localhost]

TASK [setup]

---

ok: [oberon -> localhost]

ok: [puck -> localhost]

TASK [install utilities]

---

included: tasks/install_rpmforge.yml for puck

ok: [oberon] => (item=gcc,make,automake,openssl,openssl-devel,xinetd)

TASK [include_vars]

---

ok: [puck -> localhost]

TASK [get rpmforge]

---

ok: [puck -> localhost]

TASK [install rpmforge from an rpm]

---

fatal: [puck]: FAILED! => {"changed": true, "failed": true, "msg": "(1,
[u'Please report this error in
https://bugzilla.redhat.com/enter_bug.cgi?product=Red%20Hat%20Enterprise%20Linux%205&component=yum'])\n",
"rc": 1, "results": ["Loaded plugins: fastestmirror, replace\nLoading
mirror speeds from cached hostfile\n \* addons: mirrors.xmission.com\n *
base: mirrors.unifiedlayer.com\n \* epel: mirror.sfo12.us.leaseweb.net\n *
extras: mirror.keystealth.org\n \* ius: mirror.symnds.com\n \* rpmforge:
mirror.hmc.edu\n \* updates: mirror.tocici.com\nSetting up Install
Process\nExamining /opt/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm:
rpmforge-release-0.5.3-1.el6.rf.x86_64\nMarking
/opt/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm as an update to
rpmforge-release-0.5.2-2.el5.rf.x86_64\nResolving Dependencies\n--> Running
transaction check\n---> Package rpmforge-release.x86_64 0:0.5.3-1.el6.rf
set to be updated\n--> Finished Dependency Resolution\n\nDependencies
Resolved\n\n================================================================================\n
Package\n     Arch     Version           Repository

Size\n================================================================================\nUpdating:\n
rpmforge-release\n     x86_64   0.5.3-1.el6.rf
/rpmforge-release-0.5.3-1.el6.rf.x86_64    13 k\n\nTransaction
Summary\n================================================================================\nInstall
      0 Package(s)\nUpgrade       1 Package(s)\n\nTotal size: 13
k\nDownloading Packages:\nRunning rpm_check_debug\nERROR with
rpm_check_debug vs depsolve:\nrpmlib(FileDigests) is needed by
rpmforge-release-0.5.3-1.el6.rf.x86_64\nrpmlib(PayloadIsXz) is needed by
rpmforge-release-0.5.3-1.el6.rf.x86_64\nComplete!\n"]}

TASK [add nagios group]

---

ok: [oberon -> localhost]

TASK [add nagios user]

---

ok: [oberon -> localhost]

TASK [get NRPE version 2.15]

---

ok: [oberon -> localhost]

TASK [unarchive nrpe]

---

changed: [oberon -> localhost]

TASK [run configure script]

---

changed: [oberon -> localhost]

TASK [make nrpe]

---

changed: [oberon -> localhost]

TASK [make install nrpe]

---

changed: [oberon -> localhost]

TASK [Install libselinux]

---

included: tasks/libselinux-python.yml for oberon

TASK [install libselinux-python]

---

ok: [oberon -> localhost]

TASK [assures libexec dir exists]

---

ok: [oberon -> localhost]

ok: [puck] => (item=gcc,make,automake,openssl,openssl-devel,xinetd)

TASK [copy nagios libraries]

---

ok: [puck -> localhost]

ok: [oberon] =>
(item=/Users/jgrigonis/projects/omicia_misc/playbooks/binaries/nagios/check_disk)

ok: [oberon] =>
(item=/Users/jgrigonis/projects/omicia_misc/playbooks/binaries/nagios/check_load)

ok: [oberon] =>
(item=/Users/jgrigonis/projects/omicia_misc/playbooks/binaries/nagios/
check_mem.pl)

ok: [oberon] =>
(item=/Users/jgrigonis/projects/omicia_misc/playbooks/binaries/nagios/check_procs)

ok: [oberon] =>
(item=/Users/jgrigonis/projects/omicia_misc/playbooks/binaries/nagios/check_recent_log.sh)

ok: [oberon] =>
(item=/Users/jgrigonis/projects/omicia_misc/playbooks/binaries/nagios/check_swap)

ok: [oberon] =>
(item=/Users/jgrigonis/projects/omicia_misc/playbooks/binaries/nagios/check_users)

TASK [assures etc dir exists]

---

ok: [puck -> localhost]

ok: [oberon -> localhost]

TASK [create nrpe.cfg]

---

ok: [oberon -> localhost]

ok: [puck -> localhost]

TASK [assures xinet.d dir exists]

---

ok: [oberon -> localhost]

changed: [puck -> localhost]

TASK [create nrpe file]

---

ok: [oberon -> localhost]

changed: [puck -> localhost]

TASK [update services]

---

changed: [puck -> localhost]

ok: [oberon -> localhost]

TASK [start xinetd]

---

changed: [puck -> localhost]

changed: [oberon -> localhost]

TASK [include]

---

included: tasks/nagios_prod_iptables.yml for oberon

included: tasks/libselinux-python.yml for puck

TASK [get iptables rules]

---

ok: [oberon -> localhost]

TASK [open firewall for nrpe]

---

changed: [oberon -> localhost]

TASK [open firewall for nrpe localhost]

---

changed: [oberon -> localhost]

TASK [save iptables]

---

changed: [oberon -> localhost]
- [WARNING]: Consider using service module rather than running service*

TASK [restart iptables]

---

changed: [oberon -> localhost]

TASK [update bashrc]

---

ok: [oberon -> localhost]

ok: [puck -> localhost]

TASK [update nrpe.cfg]

---

ok: [oberon -> localhost]

ok: [puck] =>
(item=/Users/jgrigonis/projects/omicia_misc/playbooks/binaries/nagios/check_disk)

ok: [puck] =>
(item=/Users/jgrigonis/projects/omicia_misc/playbooks/binaries/nagios/check_load)

ok: [puck] =>
(item=/Users/jgrigonis/projects/omicia_misc/playbooks/binaries/nagios/
check_mem.pl)

ok: [puck] =>
(item=/Users/jgrigonis/projects/omicia_misc/playbooks/binaries/nagios/check_procs)

ok: [puck] =>
(item=/Users/jgrigonis/projects/omicia_misc/playbooks/binaries/nagios/check_recent_log.sh)

ok: [puck] =>
(item=/Users/jgrigonis/projects/omicia_misc/playbooks/binaries/nagios/check_swap)

ok: [puck] =>
(item=/Users/jgrigonis/projects/omicia_misc/playbooks/binaries/nagios/check_users)

TASK [assures etc dir exists]

---

ok: [puck -> localhost]

TASK [create nrpe.cfg]

---

ok: [puck -> localhost]

TASK [assures xinet.d dir exists]

---

ok: [puck -> localhost]

TASK [create nrpe file]

---

ok: [puck -> localhost]

TASK [update services]

---

ok: [puck -> localhost]

TASK [start xinetd]

---

changed: [puck -> localhost]

TASK [include]

---

included: tasks/nagios_prod_iptables.yml for puck

TASK [update bashrc]

---

ok: [puck -> localhost]

TASK [update nrpe.cfg]

---

ok: [puck -> localhost]

PLAY RECAP

---

oberon                     : ok=27   changed=9    unreachable=0
failed=0

puck                       : ok=25   changed=5    unreachable=0    failed=1

**Comment by evanccnyc** [comment] 2015-10-26 19:39
I just ran across this, it seems to be ignoring --start-at-task no matter what I put and just goes from the beginning. The task in question is in a role if that helps.

**Comment by jimi-c** [comment] 2015-10-27 20:32
@jgrigonis I pushed 87269599a0c5e3457ff6df58dd75245f60f545b6 to fix @evanccnyc's issue above, and while I don't think it's necessarily related to yours you may want to double check now to verify.

**Comment by evanccnyc** [comment] 2015-10-27 21:03
@jimi-c This fix just makes ansible skip all tasks now, before it ran everything.

**Comment by jimi-c** [comment] 2015-10-28 13:19
@evanccnyc not for me:

<pre>
# ansible-playbook -vv test.yml --start-at-task="main task"
Using /etc/ansible/ansible.cfg as config file
1 plays in test.yml
PLAY ***************************************************************************
TASK [main task] ***************************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "this should be the last one"
}
PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
# ansible-playbook -vv test.yml --start-at-task="b : role task 9"
Using /etc/ansible/ansible.cfg as config file
1 plays in test.yml
PLAY ***************************************************************************
TASK [b : role task 9] *********************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "here we are"
}
TASK [main task] ***************************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "this should be the last one"
}
PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
</pre>

There are two roles (a and b), each with 9 tasks and a single task in the `tasks` section of the `test.yml` file. In all of my testing, things work as expected.

**Comment by evanccnyc** [comment] 2015-11-03 15:52
Hmm I still am having problems with this not working. I will try and track down exactly whats going when I have a chance.

**Comment by evanccnyc** [comment] 2015-11-03 20:41
I think this is due to combing --limit and --start-at-task

**Comment by amenonsen** [comment] 2015-11-19 05:18
@evanccnyc were you able to put together a way to reproduce the problem?

**Comment by jgrigonis** [comment] 2015-11-19 17:30
I haven't been able to easily reproduce this, but I'm also thinking it
requires a fairly complex case.

Maybe with included tasks, limit and start-at-task all combined.

I haven't needed to use that combination much lately.

On Wed, Nov 18, 2015 at 9:18 PM, Abhijit Menon-Sen <notifications@github.com

**Comment by evanccnyc** [comment] 2015-11-19 17:46
Sorry busy day here, hopefully I will get a chance to test reproduction tomorrow.

**Comment by jgrigonis** [comment] 2015-11-20 18:16
This is definitely still broken.

Here's the playbook:
http://pastebin.com/Zas0Zcwr

Here's the command I used to start it:
ansible-playbook -i etc/ansible/gel_hosts configure_percona.yml --start-at-task="setup root bashrc"

Here's the output until I ctrl-c broke out, RUN AWAY!

http://pastebin.com/9aEx2Xh3

**Comment by mburz** [comment] 2016-02-09 18:05
Just to report, the problem seems to be there with Ansible 2.0.0.2, Ansible only executes the [setup] task and nothing else. Worked flawlessly with the latest 1.9 stable.

**Comment by jgrigonis** [comment] 2016-02-10 18:18
This is still a problem for me.

**Comment by mtnbikenc** [comment] 2016-03-09 15:16
Ran across this issue today.  Here is a test from a simple playbook against recent devel branch.

```
[root@rhel72 test]# ansible --version
ansible 2.1.0 (devel 49bb4803b5) last updated 2016/03/08 11:05:53 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 45745424f7) last updated 2016/03/08 11:05:56 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD b51efc51bc) last updated 2016/03/08 11:05:59 (GMT -400)
  config file =
  configured module search path = Default w/o overrides
```

```
[root@rhel72 test]# cat test.yml
---

- name: Test Start At Task
  hosts: localhost

  tasks:
    - name: First Task
      debug:
        msg: "This is the first task"

    - name: Second Task
      debug:
        msg: "This is the second task"

    - name: Third Task
      debug:
        msg: "This is the third task"
```

```
[root@rhel72 test]# ansible-playbook test.yml

PLAY [Test Start At Task] ******************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [First Task] **************************************************************
ok: [localhost] => {
    "msg": "This is the first task"
}

TASK [Second Task] *************************************************************
ok: [localhost] => {
    "msg": "This is the second task"
}

TASK [Third Task] **************************************************************
ok: [localhost] => {
    "msg": "This is the third task"
}

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0
```

```
[root@rhel72 test]# ansible-playbook test.yml --start-at-task="Second Task"

PLAY [Test Start At Task] ******************************************************

TASK [setup] *******************************************************************
ok: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```

```
[root@rhel72 test]# ansible-playbook test.yml --list-tasks

playbook: test.yml

  play #1 (localhost): Test Start At Task   TAGS: []
    tasks:
      First Task    TAGS: []
      Second Task   TAGS: []
      Third Task    TAGS: []
```

**Comment by jsumners** [comment] 2016-03-14 14:32
I get the same results as @mtnbikenc.

**Comment by mtnbikenc** [comment] 2016-03-28 17:34
I tested after commit f4eb9aa by @jimi-c and `--start-at-task` is fixed.
Also referenced in #15010.

**Comment by jimi-c** [comment] 2016-03-31 19:43
Thanks @mtnbikenc, I'll go ahead and close this then.

**Closed as completed by jimi-c** 2016-03-31 19:43 UTC
Labels: bug
