### ISSUE TITLE
[shell module] Cannot source file containing standard input redirection

### ISSUE THREAD

**Issue by NBardelot** [ansible/ansible#30866] opened 2017-09-25 16:27 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
shell

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /home/adminomc/ANS-NOEE-1.9.13-SNAPSHOT/playbooks/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]

```
##### OS / ENVIRONMENT
RHEL7/CentOS7

##### SUMMARY
I think there is a side-effect when using the standard input redirect `<` in conjonction with the `source` directive.

##### STEPS TO REPRODUCE

Task : 

```
- name: "Run some shell command"
  shell:
   cmd: source /home/myuser/outer.sh && echo "FOO? $FOO" && echo "BAR? $BAR"
  environment:
    WITH_FOO:  1 # or 0 
```

And some files: 

```
> cat /home/myuser/outer.sh
#!/bin/bash
echo "outer before"
source /home/myuser/inner.sh
echo "outer after"
```

```
> cat /home/myuser/inner.sh
#!/bin/bash
echo "inner.sh"
if [ "WITH_FOO" -gt 0 ]
then
  source /home/myuser/variables.sh
else
  # this is a correct syntax, and works when tested outside of Ansible
  source <(grep -v FOO variables.sh)
fi
```

```
> cat /home/myuser/variables.sh
#!/bin/bash
export FOO="foo"
export BAR="bar"
```

##### EXPECTED RESULTS

Both tasks should work without any error syntax.

##### ACTUAL RESULTS

Ansible outputs an error in any case (both WITH_FOO values of 0 and 1 behave the same way).

When verbosity is set to 3 (with `-vvv`), Ansible's shell module indicates a syntax error indicating an issue with the character `(` on the line using the `<` standard input operator.  

When I run the very same shell commands by myself the behaviour is correct. There is no syntax error, and both branches of the if-then statement behave as expected (FOO is exported in one case, and not in the other case).

**Comment by NBardelot** [comment] 2017-09-25 16:32
Please not that while this is a strange bug, for a strange use of the `source` directive, anyone having the same issue can use the following workaround (it worked for me at least): 

```
grep -v FOO /home/myuser/variables.sh | source /dev/stdin
```

Edit: 

We changed our workaround to generate a temporary Shell file and source that file, then `rm` it.

**Comment by sivel** [comment] 2017-09-25 16:50
Can you please provide the actual output from that playbook, using -vvv

needs_info

I am guessing that the problem is invoking `/bin/sh` as the shell, and getting an error similar to:

```
/bin/sh: -c: line 0: syntax error near unexpected token `('
```

Which indicates that the `executable` being used does not support your syntax.

**Comment by NBardelot** [comment] 2017-10-11 13:14
@sivel you must be right, we use `#!/bin/sh` as `/bin/sh` is in reality `/bin/bash`. It might have to do with that. The fact that `ksh` is also installed on some of our hosts might also be the issue. Especially since some users on those hosts use `/bin/ksh` as their shell. 

Anyway, as mentionned, we have a workaround that works so we didn't spend more time on the issue. I think this issue can be closed. I don't believe it's an Ansible bug anymore.

**Comment by sivel** [comment] 2017-10-11 15:02
Closing as requested

**Closed as completed by sivel** 2017-10-11 15:02 UTC
Labels: affects_2.3, module, support:core, bug

**Comment by ronaldvanrij** [comment] 2018-08-06 08:29
Ran into this error today too (albeit several months later). The command executes fine on a regular shell, but used in Ansible to does not. I'd rather use this oneliner, rather than having to go through temporary shell scripts, which would simply clutter my Ansible setup and make it not very readable. Does anyone have any other suggestions? 

```
ansible-playbook 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/var/lib/jenkins/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```
Task:
```
shell: "diff -w <(hdfs dfs -cat /test/wordcount-output/*) <(printf \"dear  1\nhello 1\nworld 2\n\")"
```
Output:
```
"/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `diff -w <(hdfs dfs -cat /test/wordcount-output/*) <(printf \\\"dear 1\\nhello 1\\nworld 2\\n\\\")'
```
