### ISSUE TITLE
are the unbalanced quotes for values in ini files intentional ?

### ISSUE THREAD

**Issue by g-k-r** [ansible/ansible#5760] opened 2014-01-25 00:32 UTC
daf797804b8f439d665e48996fe9cf1d2d632635 introduced whitespaces around the assignement operator for key value pairs. it also introduced unbalanced quotes in test/complex_hosts. this is very inconvenient as it breaks parsing the ini files with ConfigParser. So is this a bug or a feature ?

**Comment by mpdehaan** [comment] 2014-01-25 01:15
Are you talking about in the tests or in the results of using the INI module?

If reporting a bug, please include steps to reproduce (playbook would be great) and before/after output.

Thanks!

**Comment by mpdehaan** [comment] 2014-01-25 01:26
(tagged for investigation)

**Comment by g-k-r** [comment] 2014-01-26 15:38
hi @mpdehaan i was referring to lines **41** and **42** in file **test/complex_host** in commit daf797804b8f439d665e48996fe9cf1d2d632635

``` ini
    i = ' i "
    j = " j 
```

**Comment by jimi-c** [comment] 2014-01-27 15:48
@g-k-r this seems to be by design, specifically to test parsing of unbalanced quotes in the INI. Could you tell us what your use-case is for that file, since it is only a testing file?

**Comment by g-k-r** [comment] 2014-01-28 12:31
@jimi-c to check #5749 i created a test and also reviewed the parsing code. the code fails when there are hash `#` signs in a quoted value which is probably why the corresponding test is commented out. unbalanced quotes are difficult to parse and I don't see a real usage for that feature. the parsing routine could probably be simplified by disallowing unballanced quotes and defining each line to be parsable by shlex. 
BTW: is the grammar for these ini file like structures explicitly defined anywhere except in the code ?

**Comment by jimi-c** [comment] 2014-01-28 16:20
@g-k-r I'm fine with removing those lines from the test, as I agree, the test doesn't seem to provide any useful function.

**Comment by g-k-r** [comment] 2014-01-28 17:21
@jimi-c good, do you want a pull request ?

**Comment by jimi-c** [comment] 2014-01-28 17:27
@g-k-r yes please, and make sure you put "Fixes #5760" in the commit so it will auto-close this issue.

Thanks!

**Comment by mpdehaan** [comment] 2014-02-10 04:30
Closing this ticket as we have a pull request tracking this now, thanks!

**Closed as completed by mpdehaan** 2014-02-10 04:30 UTC
Labels: needs_info, bug
