### ISSUE TITLE
Allow for installing of required roles when using ansible-pull

### ISSUE THREAD

**Issue by MrMMorris** [ansible/ansible#10636] opened 2015-04-08 00:21 UTC
I have required roles in requirements.txt:

``` yaml
- src: https://github.com/picotrading/ansible-ulimit
  name: ulimit
```

Ansible-pull has no way of being able to run `ansible-galaxy install -r requirements.yml` which means in order to run any role where the dependancies are installed with requirements.txt, I have to store them in my ansible repo which is a PITA.

Maybe add a flag like `-r requirements.txt` that tells ansible pull to look for a file in the repo root that contains roles to be installed before running the playbook?

**Comment by bcoca** [comment] 2016-09-26 15:22
closing as dupe of https://github.com/ansible/proposals/issues/7

**Closed as completed by bcoca** 2016-09-26 15:22 UTC
Labels: feature
