### ISSUE TITLE
--syntax-check doesn't work while specifying vault credentials

### ISSUE THREAD

**Issue by aknapp** [ansible/ansible#8342] opened 2014-07-29 21:09 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

`ansible 1.6.6`
##### Environment:

Running from Ubuntu 14.04 and managing Ubuntu 14.04.
##### Summary:

Ran into this issue while trying to setup some encrypted files in my project. I use `--syntax-check` in my build steps to verify that everything is good in my project, but when I added some encrypted files with vault, it would always error with:

`ERROR: A vault password must be specified to decrypt data`

This happened no matter what I specified on the command line, `--ask-vault-pass` (it never prompted me for a password and just showed the error above) or `--vault-password-file <file>` (it just showed the error above). `ansible-playbook` runs just fine with encrypted files when I don't put `--syntax-check` on it, but it won't run in that state.
##### Steps To Reproduce:

Encrypt a file with vault, then try to run syntax check on a playbook that requires that file.
##### Expected Results:

Either it would prompt you for a password (if using `--ask-vault-pass`) or just work (if using `--vault-password-file <file>`).
##### Actual Results:

No matter which option I try, it just errors with:

`ERROR: A vault password must be specified to decrypt data`

**Comment by aknapp** [comment] 2014-09-18 20:28
It looks like this may have been fixed? I just tested it in 1.7.1 and it works now.

**Comment by resmo** [comment] 2016-08-15 22:08
could not reproduce with 2.1.1. closing

**Closed as completed by resmo** 2016-08-15 22:08 UTC
Labels: bug
