### ISSUE TITLE
with_items not showing output until done

### ISSUE THREAD

**Issue by chromerobv** [ansible/ansible#14276] opened 2016-02-02 19:40 UTC
with this in 1.\* ansible it would show output during each iteration, in 2.0 it shows nothing until it is done. when this is a large with list it prints nothing for a long time then spits out everything.

  template: src=check.json.j2
            dest={{ sensu_confs_directory}}/{{ item.name }}.json
            mode=0640
            owner={{ sensu_user }}
            group={{ sensu_group }}
  with_items: sensu_checks | default([])

is there someway to tell it not to buffer the output and to show something during each iteration like it used to ?

thanks!

**Comment by bcoca** [comment] 2016-02-02 19:46
dupe of #14072

**Closed as completed by bcoca** 2016-02-02 19:46 UTC
