### ISSUE TITLE
Ansible 2 tags don't work

### ISSUE THREAD

**Issue by vallettea** [ansible/ansible#14638] opened 2016-02-24 13:09 UTC
##### Issue Type:
- Bug Report
##### Ansible Version:

```
2.0.0.2
```
##### Environment:

OSX El Capitan
##### Summary:

since I upgraded to ansible 2, the tags filter doesn't work anymore:

```
ansible-playbook -i hosts all.yml -t foo
```

starts but plays all tasks and not only the one tagged with foo

**Comment by bcoca** [comment] 2016-02-29 20:34
so, I cannot reproduce with a local example, can you give us reproducer?

**Comment by a31amit** [comment] 2016-02-29 23:52
This looks to related to same issue - I also noticed that list-tags don't filter tags from include file. 

https://github.com/ansible/ansible/issues/14125

**Comment by bcoca** [comment] 2016-03-01 04:02
closing as dupe of #14125, this is an issue with the new dynamic includes

**Closed as completed by bcoca** 2016-03-01 04:02 UTC
Labels: bug
