### ISSUE TITLE
Become or sudo with password hangs in v2 regardless of whether password is passed

### ISSUE THREAD

**Issue by cpswan** [ansible/ansible#11248] opened 2015-06-12 17:01 UTC
Issue Type: Bug Report
Ansible Version:  2.0.0 (devel acda3efe7a)
Ansible Configuration: default
Environment: ansible / ubuntu14.04-ansible from Docker Hub updated to 2.0.0

Summary:

If the host requires a password for sudo then ansible-playbook hangs when it reaches that command regardless of whether no password is passed, a password is passed via a variable or a password is passed by the --ansible-sudo-pass (or --ansible-become-pass) command line flag.

Steps To Reproduce:
1. Create a host that has a user that requires a password to sudo
2. Try to do any change on that host via an ansible-playbook that requires sudo

Expected Results:
1. The command should succeed when a correct password is passed via a variable or command line flag
2. The command should fail if an incorrect password is passed via a variable or command line flag
3. The command will hang if no password is passed (this isn't a desirable result, but is is what's expected)

Actual Results:

The command hangs

**Comment by bcoca** [comment] 2015-06-12 17:03
closing as dupe of #11169

**Closed as completed by bcoca** 2015-06-12 17:03 UTC
