### ISSUE TITLE
Check ansible.cfg location relatively to playbook file

### ISSUE THREAD

**Issue by akamensky** [ansible/ansible#17087] opened 2016-08-15 09:54 UTC
##### ISSUE TYPE

Not sure whether `Bug Report` or `Feature Idea`
##### COMPONENT NAME

?
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file =
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

`None`
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Currently Ansible checks for location of ansible.cfg relatively to CWD, HOME or in /etc/[ansible/]ansible.cfg

Whereas lookup for templates and files used in playbook happens relatively to playbook file
##### STEPS TO REPRODUCE
1. Create some playbook
2. Place in same directory ansible.cfg with some settings (for example `retry_files_enabled = False`)
3. Run playbook from another location using `ansible-playbook /path/to/playbook.yml`
4. Verify whether ansible.cfg was used or not
##### EXPECTED RESULTS

`ansible.cfg` in location relative to playbook was used
##### ACTUAL RESULTS

`ansible.cfg` in location relative to playbook is not used. Used relatively to CWD instead (why?)

**Comment by bcoca** [comment] 2016-08-15 15:08
dupe of #11175

**Closed as completed by bcoca** 2016-08-15 15:08 UTC
