### ISSUE TITLE
Tracebacks when calling `ansible-doc -l`

### ISSUE THREAD

**Issue by jlaska** [ansible/ansible#9221] opened 2014-09-30 14:53 UTC
##### Issue Type:

Can you help us out in labelling this by telling us what kind of ticket this this?  You can say “Bug Report”, “Feature Idea”, “Feature Pull Request”, “New Module Pull Request”, “Bugfix Pull Request”, “Documentation Report”, or “Docs Pull Request”.
##### Ansible Version:

```
# ansible-doc --version
ansible-doc 1.8 (devel 7d9661a266) last updated 2014/09/30 10:46:06 (GMT -400)
  lib/ansible/modules/core: (detached HEAD db5668b84c) last updated 2014/09/29 11:27:31 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 110250d344) last updated 2014/09/29 11:27:34 (GMT -400)
  configured module search path = None
```
##### Environment:

Mac OSX
##### Summary:

The command `ansible-doc -l` emits tracebacks while scanning modules.
##### Steps To Reproduce:
1. `. hacking/env-setup`
2. `ansible-doc -l`
##### Expected Results:

No tracebacks on stderr
##### Actual Results:

```
﻿﻿# ansible-doc  -l 1>/dev/null 2| pbcopy 
Traceback (most recent call last):
  File "/Users/jlaska/Downloads/ansible.git/lib/ansible/utils/module_docs.py", line 50, in get_docstring
    M = ast.parse(''.join(open(filename)))
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    gitdir: ../../../../.git/modules/lib/ansible/modules/core
          ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/jlaska/Downloads/ansible.git/bin/ansible-doc", line 184, in get_module_list_text
    desc = tty_ify(doc.get('short_description', '?'))
AttributeError: 'NoneType' object has no attribute 'get'
ERROR: module .git has a documentation error formatting or is missing documentation
Traceback (most recent call last):
  File "/Users/jlaska/Downloads/ansible.git/lib/ansible/utils/module_docs.py", line 50, in get_docstring
    M = ast.parse(''.join(open(filename)))
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 2
    *.py[co]
    ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/jlaska/Downloads/ansible.git/bin/ansible-doc", line 184, in get_module_list_text
    desc = tty_ify(doc.get('short_description', '?'))
AttributeError: 'NoneType' object has no attribute 'get'
ERROR: module .gitignore has a documentation error formatting or is missing documentation
Traceback (most recent call last):
  File "/Users/jlaska/Downloads/ansible.git/lib/ansible/utils/module_docs.py", line 50, in get_docstring
    M = ast.parse(''.join(open(filename)))
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    Welcome To Ansible GitHub
             ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/jlaska/Downloads/ansible.git/bin/ansible-doc", line 184, in get_module_list_text
    desc = tty_ify(doc.get('short_description', '?'))
AttributeError: 'NoneType' object has no attribute 'get'
ERROR: module CONTRIBUTING.md has a documentation error formatting or is missing documentation
Traceback (most recent call last):
  File "/Users/jlaska/Downloads/ansible.git/lib/ansible/utils/module_docs.py", line 50, in get_docstring
    M = ast.parse(''.join(open(filename)))
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    GNU GENERAL PUBLIC LICENSE
   ^
IndentationError: unexpected indent
Traceback (most recent call last):
  File "/Users/jlaska/Downloads/ansible.git/bin/ansible-doc", line 184, in get_module_list_text
    desc = tty_ify(doc.get('short_description', '?'))
AttributeError: 'NoneType' object has no attribute 'get'
ERROR: module COPYING has a documentation error formatting or is missing documentation
Traceback (most recent call last):
  File "/Users/jlaska/Downloads/ansible.git/lib/ansible/utils/module_docs.py", line 50, in get_docstring
    M = ast.parse(''.join(open(filename)))
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 2
    ====================
     ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/jlaska/Downloads/ansible.git/bin/ansible-doc", line 184, in get_module_list_text
    desc = tty_ify(doc.get('short_description', '?'))
AttributeError: 'NoneType' object has no attribute 'get'
ERROR: module README.md has a documentation error formatting or is missing documentation
Traceback (most recent call last):
  File "/Users/jlaska/Downloads/ansible.git/bin/ansible-doc", line 184, in get_module_list_text
    desc = tty_ify(doc.get('short_description', '?'))
AttributeError: 'NoneType' object has no attribute 'get'
ERROR: module __init__.py has a documentation error formatting or is missing documentation
Traceback (most recent call last):
  File "/Users/jlaska/Downloads/ansible.git/lib/ansible/utils/module_docs.py", line 50, in get_docstring
    M = ast.parse(''.join(open(filename)))
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
TypeError: compile() expected string without null bytes
Traceback (most recent call last):
  File "/Users/jlaska/Downloads/ansible.git/bin/ansible-doc", line 184, in get_module_list_text
    desc = tty_ify(doc.get('short_description', '?'))
AttributeError: 'NoneType' object has no attribute 'get'
ERROR: module __init__.pyc has a documentation error formatting or is missing documentation
Traceback (most recent call last):
  File "/Users/jlaska/Downloads/ansible.git/bin/ansible-doc", line 184, in get_module_list_text
    desc = tty_ify(doc.get('short_description', '?'))
AttributeError: 'NoneType' object has no attribute 'get'
ERROR: module async_wrapper.py has a documentation error formatting or is missing documentation
```

**Comment by resmo** [comment] 2014-09-30 22:02
duplicate of #5612 ?

**Comment by jimi-c** [comment] 2014-10-27 14:46
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by jimi-c** [comment] 2014-10-27 14:46
@resmo can you confirm if this was a duplicate of #5612 for sure? If so, I can close that as well.

Thanks!

**Closed as completed by jimi-c** 2014-10-27 14:46 UTC
Labels: P2, bug
