### ISSUE TITLE
[Package modules] Add a state=facts with status of package if its installed or not.

### ISSUE THREAD

**Issue by kiranos** [ansible/ansible#6925] opened 2014-04-09 18:31 UTC
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.5.4
##### Environment:

Debian 7
##### Summary:

Hi I'm using Debian and miss to be able to nicely add conditions which incorporates the state of a package, ie only run a command if a package is not installed. (in my caste debconf commands should only be run if the package is not installed)

Got the idea from: https://github.com/ansible/ansible/issues/6886 where a condition with debconf will always be "changed"
##### Steps To Reproduce:

not able to retrieve status of a package to a variable today.
##### Expected Results:

something like this below but you proably know syntax better than me :)

```
ansible -m apt -a name=mysql-server state=facts
```

which would give me a variable back with the status if its installed or not.
With this variable I can then run a command based upon if the package is missing or not. (when: variable=true) from my playbook.
##### Actual Results:

not able to retrieve status of a package to a variable

**Comment by mpdehaan** [comment] 2014-04-14 15:44
This is a duplicate of a previous idea about having more package listing modules, this is probably something that will be done in the future.

**Closed as completed by mpdehaan** 2014-04-14 15:44 UTC
Labels: feature

**Comment by kiranos** [comment] 2014-04-14 16:03
@mpdehaan do you have a link to this idea or is it outside of github?
