### ISSUE TITLE
Feature: loop threads

### ISSUE THREAD

**Issue by HanXHX** [ansible/ansible#18744] opened 2016-12-05 08:41 UTC
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

When you have "long" tasks in a loop or a very large list, it's very hard to optimize. Async tasks is not a solution when need "right now" to parse a registered vars.

My idea is to create a new feature on a task: `loop_threads`. A loop thread is launched *per host* (if you run your task on 10 hosts with 3 `loop_threads`, you have up to 30 threads).

Features:

- new ansible.cfg var (`max_loop_threads`)
- keep order on registered var (task 1, is on first place on registered var ".results")
- loop thread should be transparent for user to keep backward compatibility

Please note, all modules can't be compatible with `loop_threads`: like apt (system lock). Globally, every module with a list param should not be compatible.

##### STEPS TO REPRODUCE

Example 1:

```yaml
- name: COMMAND | Long tasks
  command: "sleep {{ item }}"
  with_items: [10, 20, 30]
  loop_threads: 3
```

Example 2:

```yaml
- name: COMMAND | Long tasks
  command: "sleep {{ item }}"
  with_items: [10, 20, 30, 40, 50]
  loop_threads: 3
```

##### EXPECTED RESULTS

- Example 1: max(10, 20, 30) = 30 sec
- Example 2: max(10, 20, 30) + max(40, 50) = 80 sec

##### ACTUAL RESULTS

- Example 1 (without `loop_threads`): 10 + 20 + 30 = 60 sec
- Example 2 (without `loop_threads`): 10 + 20 + 30 + 40 + 50 = 150 sec

**Comment by gregorg** [comment] 2016-12-05 09:08
:+1:

**Comment by alikins** [comment] 2016-12-05 14:01
@jimi-c  Could this be implemented as a strategy plugin?

**Comment by jimi-c** [comment] 2016-12-05 19:26
You can essentially do this already with a fire-and-forget async task with a registered result which you check later using async_status in a loop. The only downside to doing so is it waits for each item in the loop - ie. if you have items [1,2,3,4,5] and item `1` takes 60 seconds but the rest take 1 second, it wouldn't check on the status of the rest of the tasks until item `1` is done. This is generally what you want, though, so beyond optimizing async_status to check on multiple items in one shot I'm not sure what more this feature would do?

**Comment by bcoca** [comment] 2016-12-17 03:39
dupe of 'forks' feature in #12086

**Closed as completed by bcoca** 2016-12-17 03:39 UTC
Labels: affects_2.3, feature
