### ISSUE TITLE
Upload wheels to pypi

### ISSUE THREAD

**Issue by asottile** [ansible/ansible#73043] opened 2020-12-21 18:33 UTC
##### SUMMARY

currently, ansible takes nearly ~240s on my machine to build from source and install via `pip install ansible`, however it appears that a working wheel is created as an intermediate step.  if this wheel were to be uploaded to pypi, almost all of that installation time is saved (~20s on my machine)

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
n/a

##### ADDITIONAL INFORMATION

I believe this would just involve running `pip wheel --no-deps .` before uploading the distributions to pypi

**Comment by sivel** [comment] 2020-12-21 18:36
Duplicate of https://github.com/ansible/ansible/issues/71992

We will be experimenting with updating our build toolchain during the 2.11 release, and may, if it works out, include such changes in 2.12 or later.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Closed as completed by sivel** 2020-12-21 18:36 UTC

**Comment by asottile** [comment] 2020-12-21 18:38
@sivel interesting, well then either the information in that closed issue is incorrect or the installation is currently invalid.  pip installs from source by producing a wheel and then installing that.  CC @webknjaz

**Comment by asottile** [comment] 2020-12-21 18:45
here's a demo:

```bash
#!/usr/bin/env bash
set -euxo pipefail
rm -rf venv ~/.cache/pip
virtualenv venv
venv/bin/pip install ansible
rm -rf venv
virtualenv venv
venv/bin/pip install ansible
```

```console
$ bash t.sh 
+ rm -rf venv /home/asottile/.cache/pip
+ virtualenv venv
created virtual environment CPython3.8.5.final.0-64 in 161ms
  creator CPython3Posix(dest=/tmp/y/z/venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/asottile/.local/share/virtualenv)
    added seed packages: pip==20.3.1, setuptools==51.0.0, wheel==0.36.1
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
+ venv/bin/pip install ansible
Collecting ansible
  Downloading ansible-2.10.4.tar.gz (28.6 MB)
     |████████████████████████████████| 28.6 MB 141 kB/s 
Collecting ansible-base<2.11,>=2.10.3
  Downloading ansible-base-2.10.4.tar.gz (5.7 MB)
     |████████████████████████████████| 5.7 MB 50.4 MB/s 
Collecting cryptography
  Downloading cryptography-3.3.1-cp36-abi3-manylinux2010_x86_64.whl (2.6 MB)
     |████████████████████████████████| 2.6 MB 952 kB/s 
Collecting cffi>=1.12
  Downloading cffi-1.14.4-cp38-cp38-manylinux1_x86_64.whl (411 kB)
     |████████████████████████████████| 411 kB 30.6 MB/s 
Collecting jinja2
  Downloading Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
     |████████████████████████████████| 125 kB 25.8 MB/s 
Collecting MarkupSafe>=0.23
  Downloading MarkupSafe-1.1.1-cp38-cp38-manylinux1_x86_64.whl (32 kB)
Collecting packaging
  Downloading packaging-20.8-py2.py3-none-any.whl (39 kB)
Collecting pycparser
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
     |████████████████████████████████| 112 kB 20.4 MB/s 
Collecting pyparsing>=2.0.2
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB 528 kB/s 
Collecting PyYAML
  Downloading PyYAML-5.3.1.tar.gz (269 kB)
     |████████████████████████████████| 269 kB 12.9 MB/s 
Collecting six>=1.4.1
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Building wheels for collected packages: ansible, ansible-base, PyYAML
  Building wheel for ansible (setup.py) ... done
  Created wheel for ansible: filename=ansible-2.10.4-py3-none-any.whl size=47089993 sha256=3332ca0d325cd38ca3367af0249f92d9662df947450a89e436b7bc4fe439c5cc
  Stored in directory: /home/asottile/.cache/pip/wheels/a7/9a/67/3aac32008b30630fab5899d0618c1d46e04a2c9a19614ec6be
  Building wheel for ansible-base (setup.py) ... done
  Created wheel for ansible-base: filename=ansible_base-2.10.4-py3-none-any.whl size=1868522 sha256=6e3976a2075ee6b4fda3d6318f248c5b38d9f8c24273d21b24a266eb1f02fb4e
  Stored in directory: /home/asottile/.cache/pip/wheels/06/63/a2/bda2e97bcb84ab543994ab4bb8552866d0f1c074a3a0794979
  Building wheel for PyYAML (setup.py) ... done
  Created wheel for PyYAML: filename=PyYAML-5.3.1-cp38-cp38-linux_x86_64.whl size=637748 sha256=7bc68c61fcd98cdf9c30a207215bc2adc1156d63b4dbce769e4b978d985bfc53
  Stored in directory: /home/asottile/.cache/pip/wheels/13/90/db/290ab3a34f2ef0b5a0f89235dc2d40fea83e77de84ed2dc05c
Successfully built ansible ansible-base PyYAML
Installing collected packages: pycparser, six, pyparsing, MarkupSafe, cffi, PyYAML, packaging, jinja2, cryptography, ansible-base, ansible
Successfully installed MarkupSafe-1.1.1 PyYAML-5.3.1 ansible-2.10.4 ansible-base-2.10.4 cffi-1.14.4 cryptography-3.3.1 jinja2-2.11.2 packaging-20.8 pycparser-2.20 pyparsing-2.4.7 six-1.15.0
WARNING: You are using pip version 20.3.1; however, version 20.3.3 is available.
You should consider upgrading via the '/tmp/y/z/venv/bin/python -m pip install --upgrade pip' command.
+ rm -rf venv
+ virtualenv venv
created virtual environment CPython3.8.5.final.0-64 in 219ms
  creator CPython3Posix(dest=/tmp/y/z/venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/asottile/.local/share/virtualenv)
    added seed packages: pip==20.3.1, setuptools==51.0.0, wheel==0.36.1
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
+ venv/bin/pip install ansible
Collecting ansible
  Using cached ansible-2.10.4-py3-none-any.whl
Collecting ansible-base<2.11,>=2.10.3
  Using cached ansible_base-2.10.4-py3-none-any.whl
Collecting cryptography
  Using cached cryptography-3.3.1-cp36-abi3-manylinux2010_x86_64.whl (2.6 MB)
Collecting cffi>=1.12
  Using cached cffi-1.14.4-cp38-cp38-manylinux1_x86_64.whl (411 kB)
Collecting jinja2
  Using cached Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
Collecting MarkupSafe>=0.23
  Using cached MarkupSafe-1.1.1-cp38-cp38-manylinux1_x86_64.whl (32 kB)
Collecting packaging
  Using cached packaging-20.8-py2.py3-none-any.whl (39 kB)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Collecting pyparsing>=2.0.2
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting PyYAML
  Using cached PyYAML-5.3.1-cp38-cp38-linux_x86_64.whl
Collecting six>=1.4.1
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Installing collected packages: pycparser, six, pyparsing, MarkupSafe, cffi, PyYAML, packaging, jinja2, cryptography, ansible-base, ansible
Successfully installed MarkupSafe-1.1.1 PyYAML-5.3.1 ansible-2.10.4 ansible-base-2.10.4 cffi-1.14.4 cryptography-3.3.1 jinja2-2.11.2 packaging-20.8 pycparser-2.20 pyparsing-2.4.7 six-1.15.0
WARNING: You are using pip version 20.3.1; however, version 20.3.3 is available.
You should consider upgrading via the '/tmp/y/z/venv/bin/python -m pip install --upgrade pip' command.
```

the important lines here being:

(from the first, uncached install):

```
  Building wheel for ansible (setup.py) ... done
  Created wheel for ansible: filename=ansible-2.10.4-py3-none-any.whl size=47089993 
```

(from the second, cached install)

```
Collecting ansible
  Using cached ansible-2.10.4-py3-none-any.whl
```

**Comment by sivel** [comment] 2020-12-21 18:46
Unfortunately due to some name changes in the package, we are doing some dynamic sanity, and due to the way pip works, the only time we can run that dynamic code is during the `wheel` build.

We do realize that if you install from a cached wheel, then our dynamic code doesn't run.

But it's the best option we have right now.

**Comment by asottile** [comment] 2020-12-21 18:49
as shown above the dynamic code isn't even firing in the general case -- is there somewhere to track this instead of closing and locking the issues asking for this?

**Comment by asottile** [comment] 2020-12-21 18:49
> Again, this is on our roadmap

ok, I didn't see you mention this -- where can the roadmap be viewed?

**Comment by sivel** [comment] 2020-12-21 18:56
We are in the process of changing how our development is handled.  During a single release we will work on "experimental features" that will not land in the upcoming release, and we will also have public documented roadmap.

As of now we do not publicly document our "experimental features" roadmap.  Switching the build tooling is part of the work that will allow us to ship a new package called `fallible` which will be ansible-core + experimental features.

Should the change to build tooling work well for shipping `fallible`, we plan to port it into `ansible-core`, potentially in the 2.12 release at earliest.

We may create a project in github to track these experimental features in the future.

Do note that we do not keep feature requests open for the sake of having an issue to record it.  If we are tracking it elsewhere, or have no intention of implementation, we do not keep them open.

**Comment by asottile** [comment] 2020-12-21 18:59
it's pretty disappointing that there's zero transparency into this

**Comment by webknjaz** [comment] 2020-12-21 22:08
Hey Anthony, thanks for raising this! I've been trying to convince folks to move to wheels for some time now but there were even more blockers in the past, than there are now. We used to have quite ancient setups in the CI matrix and dropped Python 2.6 just about a year ago. Also, there's an internal mechanism for tracking the module renames that relies on symlinks that old distutils uses to preserve but setuptools don't. Multiply that by versions of the packaging libs that ununtu 12/14 used to ship to understand some of the restrictions.
Today we have some framework to replace the module renaming/depreciation mechanism but somebody still needs to put in the work and we have a number of things to implement for the next release. For example, I and a few other people work on replacing the dependency resolver used in the `ansible-galaxy` CLI for installing collections with the one new pip uses (resolvelib). And we have a few other related UX improvements coming up after this big refactoring. Others, work a lot on moving hundreds of test envs from Shippable (that is being sunset) to Azure Pipelines that includes updating the bot integrations and other related things. Some work on allowing `ansible-test` to treat the controller code separately from things that run on target nodes so we could use Python 3.8 in many places while still allowing 2.6 on remotes. There's many activities and just about a dozen core engineers who try to keep up with everything going on around the project. Also, as sivel mentioned, there's a fallible project where we're trying out new things that may feel too risky to throw into the main repo right away.
We don't intentionally hide the road map, we just don't have much resources to keep all the places up-to-date. Thankfully, some of the community team folks try to help with this as much as possible and so folks who follow the community channels usually know most of what we do. People are active on freenode and in mailing lists. That being said, we can't track the closed issues and that's why we try to redirect folks to places where the community is active and the issue authors have a better chance of getting support from the community.
There's a chance that we may start using Discussions for some of the things but that's not decided atm.
FWIW, the community team is running the Bullhorn newsletter so you may want to follow that to get the news.

P.S. As for the "dynamic code is not executed when the cache is used", it's known and I believe that the workaround is documented. I'd like to drop it altogether in favor of wheels but it'll take some time for us to be able to do that.
P.P.S. You mentioned that the install first creates wheels but that's only half-true. I'm pretty sure that it's only happening in the `wheel` package is installed next to pip. Otherwise it goes for the code path that does something like `setup.py install` directly.
