### ISSUE TITLE
Wrong disk size, 21TB instead of 3TB

### ISSUE THREAD

**Issue by agrrh** [ansible/ansible#9549] opened 2014-11-13 08:09 UTC
This is a bug report (attaching a label currently unavailable for me)

Hello!

I've got an issue using ansible 1.7.2 from OS X 10.9.5 to Debian 7.7:

```
$ ansible --version
ansible 1.7.2
```

See the root size of 21+ TB after executing `$ ansible groupname -i hosts -m setup`:

```
"sdb": {
                "holders": [], 
                "host": "SATA controller: Intel Corporation 7 Series Chipset Family 6-port SATA Controller [AHCI mode] (rev 04)", 
                "model": "WDC WD30EFRX-68A", 
                "partitions": {
                    "sdb1": {
                        "sectors": "5860530176", 
                        "sectorsize": 512, 
                        "size": "2.73 TB", 
                        "start": "2048"
                    }
                }, 
                "removable": "0", 
                "rotational": "1", 
                "scheduler_mode": "cfq", 
                "sectors": "5860533168", 
                "sectorsize": "4096", 
                "size": "21.83 TB", 
                "support_discard": "0", 
                "vendor": "ATA"
            }
```

but this is actually the 3 TB disk:

```
$ df -h | grep sdb
/dev/sdb1                                               2.7T  124G  2.6T   5% /mnt/mountpoint

# hdparm -I /dev/sdb | grep 'device size'
    device size with M = 1024*1024:     2861588 MBytes
    device size with M = 1000*1000:     3000592 MBytes (3000 GB)
```

`/dev/sda` is detected correctly.

Please tell me if I should provide something more.

**Comment by Jmainguy** [comment] 2014-11-21 13:38
I can confirm I have seen this as well

**Comment by justinwyer** [comment] 2014-12-01 11:33
Can't reproduce this in either release1.7.2 branch or on devel running against a debian 7.7 vagrant box

**Comment by agrrh** [comment] 2014-12-01 12:32
Reproduced from Debian to same Debian machine with Ansible 1.7.2 from stable repos:

```
root@core:~# cat /etc/debian_version
7.7
root@core:~# ansible --version
ansible 1.7.2
root@core:~# ansible all -i hosts -m setup | grep \"size\" | grep 21
                "size": "21.83 TB",
```

Looks like this is the following formula result:

```
size=(5860533168*4096)/(1024**4) # ~= 21.8
```

where 5860533168 is `/sys/block/sdb/size` contents and 4096 is from `"sectorsize": "4096",`, not sure where Ansible gets this value.

BUT `/sys/block/sdb/size` is for 512 byte sectors count, so it should be something like:

```
size=(5860533168*512)/(1024**4) # ~= 2.7
```

**Comment by agrrh** [comment] 2014-12-01 12:53
Looks like I've found the cause:

`/sys/block/sdb/queue/physical_block_size` is preferred over `/sys/block/sdb/queue/hw_sector_size` , but this order is incorrect.

Created pull request, where I reversed the order for physical disks (partitions section left untouched):

https://github.com/ansible/ansible/pull/9681

Now it works fine for both disks:

```
# ansible all -i hosts -m setup | grep \"size\"
                        "size": "232.88 GB",
                "size": "232.89 GB",
                        "size": "2.73 TB",
                "size": "2.73 TB",
```

Please tell me if I should provide more tests.

**Comment by justinwyer** [comment] 2014-12-01 14:46
What does /sys/block/sdb/queue/physical_block_size contain ?

**Comment by Jmainguy** [comment] 2014-12-01 14:48
On my physical server, it contains 4096

**Comment by justinwyer** [comment] 2014-12-01 14:55
Thanks @Jmainguy what about /sys/block/sdb/size ?

**Comment by justinwyer** [comment] 2014-12-01 14:58
maybe an fdisk -l while you're at it, this is an above 2TB drive problem, and I don't have that available :8ball:

**Comment by Jmainguy** [comment] 2014-12-01 15:05
```
# cat /sys/block/sdb/size
5860533168
```

```
Disk /dev/sdb: 3000.6 GB, 3000592982016 bytes, 5860533168 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disk label type: dos
Disk identifier: 0x00000000

   Device Boot      Start         End      Blocks   Id  System
/dev/sdb1               1  4294967295  2147483647+  ee  GPT
Partition 1 does not start on physical sector boundary.

Disk /dev/sda: 3000.6 GB, 3000592982016 bytes, 5860533168 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disk label type: dos
Disk identifier: 0x00000000
```

I believe you are likely correct that it is a above 2TB issue, I have seen this on a few servers, and not seen it on others, I believe the ones I didnt see it on had less than 2TB.

**Comment by justinwyer** [comment] 2014-12-01 15:08
We may want to consider using logical_block_size instead of physical_block_size for disk size calculations, physical_block_size on advanced drives does not correlate with sectors but it does correlate to the logical_block_size.

**Comment by justinwyer** [comment] 2014-12-01 15:26
@agrrh- / @Jmainguy  does it report correctly with my change?

**Comment by Jmainguy** [comment] 2014-12-01 15:40
@justinwyer yes #9683 does appear to fix the issue.

```
# ansible localhost -m setup -a "filter=ansible_devices"
localhost | success >> {
    "ansible_facts": {
        "ansible_devices": {
            "sda": {
                "holders": [], 
                "host": "", 
                "model": "ST3000DM001-9YN1", 
                "partitions": {
                    "sda1": {
                        "sectors": "1048577", 
                        "sectorsize": 512, 
                        "size": "512.00 MB", 
                        "start": "2048"
                    }, 
                    "sda2": {
                        "sectors": "4292870145", 
                        "sectorsize": 512, 
                        "size": "2.00 TB", 
                        "start": "1052672"
                    }, 
                    "sda3": {
                        "sectors": "2014", 
                        "sectorsize": 512, 
                        "size": "1007.00 KB", 
                        "start": "34"
                    }, 
                    "sda4": {
                        "sectors": "1566610311", 
                        "sectorsize": 512, 
                        "size": "747.02 GB", 
                        "start": "4293922824"
                    }
                }, 
                "removable": "0", 
                "rotational": "1", 
                "scheduler_mode": "cfq", 
                "sectors": "5860533168", 
                "sectorsize": "512", 
                "size": "2.73 TB", 
                "support_discard": "0", 
                "vendor": "ATA"
            }, 
            "sdb": {
                "holders": [], 
                "host": "", 
                "model": "ST3000DM001-9YN1", 
                "partitions": {
                    "sdb1": {
                        "sectors": "1048577", 
                        "sectorsize": 512, 
                        "size": "512.00 MB", 
                        "start": "2048"
                    }, 
                    "sdb2": {
                        "sectors": "4292870145", 
                        "sectorsize": 512, 
                        "size": "2.00 TB", 
                        "start": "1052672"
                    }, 
                    "sdb3": {
                        "sectors": "2014", 
                        "sectorsize": 512, 
                        "size": "1007.00 KB", 
                        "start": "34"
                    }, 
                    "sdb4": {
                        "sectors": "1566610311", 
                        "sectorsize": 512, 
                        "size": "747.02 GB", 
                        "start": "4293922824"
                    }
                }, 
                "removable": "0", 
                "rotational": "1", 
                "scheduler_mode": "cfq", 
                "sectors": "5860533168", 
                "sectorsize": "512", 
                "size": "2.73 TB", 
                "support_discard": "0", 
                "vendor": "ATA"
            }
        }
    }, 
    "changed": false
}
```

**Comment by agrrh** [comment] 2014-12-01 15:43
Ah, so sad my very first pull request (for real software) declined. :)

Just tested it, `logical_block_size` works fine, if You meant such code:

```
            d['sectorsize'] = get_file_content(sysdir + "/queue/logical_block_size")
            if not d['sectorsize']:
                d['sectorsize'] = get_file_content(sysdir + "/queue/hw_sector_size",512)
```

Outputs:

```
root@core:~# ansible all -i hosts -m setup | grep \"size\"
                        "size": "232.88 GB",
                "size": "232.89 GB",
                        "size": "2.73 TB",
                "size": "2.73 TB",
```

Fine for both disks here, also works correctly for
- OpenVZ container using ploop image
- Raspberry Pi (using SD card)
- KVM server

**Comment by Jmainguy** [comment] 2014-12-01 15:44
=) I know how you feel, it is a team effort though, and if you had not reported it and tested it, would not have gotten this far.

**Comment by jimi-c** [comment] 2015-07-01 18:15
Closing, as @Jmainguy's patch has been merged.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-07-01 18:15 UTC
Labels: P2, bug
