### ISSUE TITLE
Errors out when user can't write to /var/log even if they can to /var/log/ansible.log (regression)

### ISSUE THREAD

**Issue by jhawkesworth** [ansible/ansible#15970] opened 2016-05-23 14:19 UTC
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0 (detached HEAD 9e622dcf31) last updated 2016/05/23 13:18:43 (GMT +100)
  lib/ansible/modules/core: (detached HEAD bc2e2e7dd9) last updated 2016/05/23 13:18:54 (GMT +100)
  lib/ansible/modules/extras: (detached HEAD 646880bf7a) last updated 2016/05/23 13:19:11 (GMT +100)
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/etc/ansible/library']

```
##### CONFIGURATION

log_path = /var/log/ansible.log
##### OS / ENVIRONMENT

Running ansible from Centos 6.5, Centos 7.2
##### SUMMARY

Looks like this issue https://github.com/ansible/ansible/issues/4852 which was fixed in the 1.x codebase by jctanner under https://github.com/jinnko/ansible/commit/d4ec7b2e96bb8cf86a6118e6303e1edafda687af is occurring again.  The logic has now moved to 

`./ansible/lib/ansible/utils/display.py`

but changing the 'or' to an 'and' appears to fix the issue.  I suspect the fix just got lost during the port to the 2.x codebase.
##### STEPS TO REPRODUCE

See steps to reproduce on https://github.com/ansible/ansible/issues/4852

```
<!--- Paste example playbooks or commands between quotes -->
```

##### EXPECTED RESULTS

Ansible to run with log data to go into /var/log/ansible.log
##### ACTUAL RESULTS

```
log file at /var/log/ansible.log is not writeable, aborting
```

**Comment by jctanner** [comment] 2016-05-25 13:51
@jhawkesworth I'm unable to reproduce ...

```
[jtanner@fedmac AP-15970]$ ls -al /var/ | fgrep log
drwxrwxr-x. 16 root root 4096 May 25 09:41 log
[jtanner@fedmac AP-15970]$ ls -al /var/log/ansible.log 
-rwxrwxr-x 1 root jtanner 424 May 25 09:48 /var/log/ansible.log
[jtanner@fedmac AP-15970]$ touch /var/log/ansible.log 
[jtanner@fedmac AP-15970]$ ansible localhost -m ping                                               
 [WARNING]: Host file not found: /etc/ansible/hosts

localhost | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
[jtanner@fedmac AP-15970]$ sudo chown root:root /var/log/ansible.log 
[jtanner@fedmac AP-15970]$ ls -al /var/log/ansible.log 
-rwxrwxr-x 1 root root 636 May 25 09:50 /var/log/ansible.log
[jtanner@fedmac AP-15970]$ ansible localhost -m ping
[WARNING]: log file at /var/log/ansible.log is not writeable and we cannot create it, aborting

 [WARNING]: Host file not found: /etc/ansible/hosts

localhost | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
```

Am I missing something?

**Comment by jhawkesworth** [comment] 2016-05-26 07:35
Thank you for picking this up.
Most likely it is me missing something.
I will double check the file permissions needed to reproduce this.

**Comment by jctanner** [comment] 2016-06-03 01:32
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We're not sure this is a bug, and we don't mean for this to be confrontational. 

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists 
to talk about this and we might be persuaded otherwise.
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!

**Closed as completed by jctanner** 2016-06-03 01:32 UTC
Labels: easyfix, bug

**Comment by jhawkesworth** [comment] 2016-06-06 07:27
Sorry I have been ill, I will re-raise once I have exact perms to reproduce.
