### ISSUE TITLE
delegate_to: "{{ inventory_hostname }}" ignored if connection: local provided in ansible 2.9.10 and higher

### ISSUE THREAD

**Issue by lazarg-bf** [ansible/ansible#80035] opened 2023-02-19 11:14 UTC
### Summary

If my playbook has `connection: local` at play level, every `delegate_to:` in any task from that play is ignored.
The use-case is as follows:
Most of my tasks in a play should be executed locally, so that's why the `connections: local`. However, some of the tasks i need to be executed on the remote host, so i add `delegate_to: "{{ inventory_hostname }}"` on those tasks, but this directive is ignored, and those tasks are also executed locally.

IMPORTANT!!!
This happens only from ansible version 2.9.10 upwards. Using ansible 2.9.9 delegate_to works as expected in conjunction with connection: local

### Issue Type

Bug Report

### Component Name

N/A

### Ansible Version

```console
ansible 2.9.10
```

### Configuration

```console
(venv) lazarg@macos:~/ansible_testing$ ansible-config dump --only-changed
(venv) lazarg@macos:~/ansible_testing$
```

### OS / Environment

macOS Monterey in python3 virtualenv

### Steps to Reproduce

Have the following playbook with name test_play.yml

```yaml (paste below)
---
- hosts: all
  gather_facts: False
  connection: local

  tasks:

    - name: T1
      shell: uname -a
      register: output
      delegate_to: "{{ inventory_hostname }}"

    - name: Debug output
      debug:
        msg: "{{ output.stdout_lines }}"
```
executed with this command:
```
ansible-playbook -i '192.168.56.7,' test_play.yml -u lazarg --private-key=id_rsa
```

### Expected Results

the expected result is the `uname -a` command to be run on 192.168.56.7 (a Linux host)
```
TASK [T1] *******************************************************************************************************************************************************************************
changed: [192.168.56.7 -> 192.168.56.7]

TASK [Debug output] *********************************************************************************************************************************************************************
ok: [192.168.56.7] => {
    "msg": [
        "Linux consul 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux"
    ]
}

PLAY RECAP ******************************************************************************************************************************************************************************
192.168.56.7               : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Actual Results

The actual result is the T1 task runs on localhost (macos)
```

TASK [T1] *******************************************************************************************************************************************************************************
[WARNING]: Platform darwin on host 192.168.56.7 is using the discovered Python interpreter at /Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7, but future installation
of another Python interpreter could change this. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.
changed: [192.168.56.7]

TASK [Debug output] *********************************************************************************************************************************************************************
ok: [192.168.56.7] => {
    "msg": [
        "Darwin macos 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64"
    ]
}

PLAY RECAP ******************************************************************************************************************************************************************************
192.168.56.7               : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by flowerysong** [comment] 2023-02-19 17:59
This is not a bug. Logically, `delegate_to: "{{ inventory_hostname }}"` should never have any effect on the resolution of connection settings because `inventory_hostname` was already the targeted host.

If it previously did have an effect, that was a bug.

There are a number of ways to achieve what you're trying to do, but the most straightforward is to remove `connection: local` from the play and set `delegate_to: localhost` on the tasks that you want to run locally (you can [group them together using `block:`](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_blocks.html#grouping-tasks-with-blocks) if there are a large number of consecutive tasks.)

**Comment by lazarg-bf** [comment] 2023-02-21 13:28
Thanks for clarifications.

**Comment by mkrizek** [comment] 2023-02-21 15:14
Closing per above.

If you have further questions please stop by IRC or the mailing list:
* IRC: #ansible on irc.libera.chat
* mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Closed as completed by mkrizek** 2023-02-21 15:14 UTC
Labels: bug, affects_2.9
