### ISSUE TITLE
Playbook syntax errors need to include file and line

### ISSUE THREAD

**Issue by ingmar** [ansible/ansible#5797] opened 2014-01-28 15:17 UTC
With ansible 1.4.4, an error in any of the YAML files of a large playbook leads to a rather nonspecific error message such as:

```
$ ansible-playbook site.yml 
playbook: site.yml
ERROR: fail is not a legal parameter in an Ansible Playbook
```

Now it's up to the user to guess where this error occurred. I think it would make every sense in the world if Ansible added the location of the error, for example:

```
ERROR (in ./tasks/prereqs.yml, line 5): fail is not a legal parameter in an Ansible Playbook
```

**Comment by bcoca** [comment] 2014-01-28 16:03
it seems to be evaluating the task as a play

**Comment by ingmar** [comment] 2014-01-28 16:24
Yes, that is the cause in this case, but it doesn't say where, so one has to go look for it. This can be quite tedious when using roles and includes. Ansible does output the location for other errors, e.g.:

```
ERROR: Syntax Error while loading YAML script, /wherethingsare/roles/common/handlers/main.yml
Note: The error may actually appear before this position: line 4, column 1

- name: Show the error you get when missing an indent
service: name=show state=restarted
^
```

This would be nice to have here.

**Comment by ingmar** [comment] 2014-01-29 13:08
Another example where the location is missing from the error message:

```
$ ansible-playbook site.yml
ERROR: pi is not a legal parameter in an Ansible task or handler
```

This was a missing p (from pip) in roles/common/main.yml - again, pointing out where Ansible found this would've been immensely helpful :)

**Comment by mpdehaan** [comment] 2014-02-05 00:37
Yeah I filed one of these a while ago, I closed it.  It was involved (and I closed it)

Would be nice to have, patches would be considered, but might take some doing.

**Comment by brianmhunt** [comment] 2014-06-03 15:08
I am also experiencing difficulties with the terse error messages when a playbook fails. Strangely Ansible 1.5.5 works fine, but I get an inexplicable and (practically speaking) impossible to locate error with Ansible 1.6.2: `ERROR: command is not a legal parameter in an Ansible task or handler`. It is emitted from [`playbook/task.py:110`](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/task.py#L110).

I did not notice any comments in the changelog that would indicate what might have gone awry between versions 1.5.5 and 1.6.2.

Some more information would be very handy, whether a stack trace, a corresponding file + line number, or just a print-out of all the parameters of the task. Then I can hopefully root out the problem and upgrade to play with the cool kids. :)

**Comment by PatBee** [comment] 2014-09-05 18:33
As I work on more and more advanced, involved playbooks I find this a time sync as well.  I admit the root cause is often a typo error of my own, but determining which file it occurs in a tedious exercise in commenting things out and rerunning until you can figure out which role or included file is causing the error.

The ideal solution would be file, line number, and print the line.   But anything that helps would be appreciated

Currently I'd be happy if it could print the file name where the error occurred as that is a big start.

**Comment by MicahElliott** [comment] 2015-02-16 01:12
Parsability of these error messages is pretty essential for tools that jump to them, like vim's quickfix (see errorformat/gfortan example here: http://vim.wikia.com/wiki/Errorformats). In vim, one can set "makeprg=ansible ..." and then jump right to the point of error if this is implemented with a simple approximate line number.

The existing 2-line ERROR lines ingmar refers to (having filename, lineno, colno) should be just fine as a parsable format; just need more of them to cover other error cases.

Looks like emacs could also use the error messages: http://emacs.stackexchange.com/questions/5858/what-emacs-feature-is-nearest-to-vims-quickfix

This would be a really great feature.

**Comment by jimi-c** [comment] 2015-02-27 15:39
The upcoming V2 release addresses this, and has been working there for some time. As a result, we're going to go ahead and close this issue now as it will not be included in the 1.x series of releases. If you have any further questions regarding this, please direct them to one of our mailing lists, as appropriate: 
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-02-27 15:39 UTC
Labels: feature

**Comment by ye** [comment] 2015-08-17 16:00
It's been 20 months now since the original the issue was raised this hasn't been resolved. It's such a crucial core feature that any compiler / parser would have for debugging erroneous playbook receipts that regardless of v1 or v2. It's fine if you can release v2 earlier. But another half years passed after you file it under v2, and where is the v2 now?

It's just very frustrated to waste time not knowing which line was the error coming from and knowing that the project owners take no action on a fundamental bug for 20 months with an "active" community.

**Comment by vmalyi** [comment] 2015-09-02 08:09
+1

**Comment by clok** [comment] 2015-12-17 16:23
+1

**Comment by sysreq0** [comment] 2016-02-01 18:12
+1

**Comment by jayunit100** [comment] 2016-04-28 18:10
+1

**Comment by nhooey** [comment] 2016-04-28 18:14
@jayunit100 Please start using the "reaction" feature on the issue description instead of writing a message, which notifies everyone subscribed.
