### ISSUE TITLE
include_role broken on 2.2.2.0

### ISSUE THREAD

**Issue by bearrito** [ansible/ansible#23457] opened 2017-04-10 13:46 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
include_role

##### ANSIBLE VERSION

```
ansible 2.2.2.0
  config file = /home/barrett/Git/ansible-dock-robot/ansible.cfg
  configured module search path = Default w/o overrides

```

##### OS / ENVIRONMENT
Ubuntu 14.04

##### SUMMARY
include_role fails and complains with little useful output

##### STEPS TO REPRODUCE
1. I cloned https://github.com/elastic/ansible-elasticsearch as a submodule into my roles directory as `elastic-elasticsearch`
2.  I then attempt to include the role as below from my role titled `elasticsearch`

```
- include_role:
    name: elastic-elasticsearch
    tasks_from: main
```

The result output is

```
statically included: /home/barrett/Git/ansible-dock-robot/roles/elastic-elasticsearch/tasks/./xpack/security/elasticsearch-security-native.yml
statically included: /home/barrett/Git/ansible-dock-robot/roles/elastic-elasticsearch/handlers/elasticsearch-templates.yml
ERROR! Syntax Error while loading YAML.


The error appears to have been in '/home/barrett/Git/ansible-dock-robot/roles/elasticsearch/defaults/main.yml': line 12, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

(specified line no longer in file, maybe it changed?)

```

The imported role has no issue running by itself.

**Comment by Lujeni** [comment] 2017-04-14 14:02
Hello @bearrito,

Can you test the role without the `include_role` directive please ?
Seems to be an error with the role directly or your ansible version + role.

Thanks

**Comment by bearrito** [comment] 2017-04-14 15:18
I mentioned in the bottom of the ticket 

> The imported role has no issue running by itself.

Meaning if I just run the "elastic-elasticsearch" role directly, then I have no issues.

This is a fairly well used role and the maintainers claim
> The latest Elasticsearch versions of 5.x are actively tested. Only Ansible versions > 2.2.0 are supported.

So I'm doubtful it lies in the role itself.

**Comment by bearrito** [comment] 2017-05-03 17:20
Does the maintainer  need more information on this issue?

**Comment by Lujeni** [comment] 2017-05-09 16:20
@bearrito Do you have the same problem with another role ?
I am unable to reproduce the bug

```
---
- name: Simple Example
  hosts: all
  tasks:
    - include_role:
        name: ansible-elasticsearch
        tasks_from: main
  vars:
    es_instance_name: "node1"
. . .
```

**Comment by bearrito** [comment] 2017-05-09 16:51
That was the only one I attempted it with.  I recently cleaned up my local python path and virtual envs maybe I had something going on with the paths. 

I will try again shortly and post back the results.

**Comment by bearrito** [comment] 2017-05-09 17:22
This appears to be working now. I cannot say for certain what the change was that caused it to begin working.

For anyone seeing this in the future I'd advice to check whether you virutalenv is using site or dist packages and whether your PYTHONPATH might be picking up unwanted libraries

**Comment by sivel** [comment] 2018-04-17 20:33
Closing as the issue is resolved.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Closed as completed by sivel** 2018-04-17 20:33 UTC
Labels: affects_2.2, support:core, include_role, bug
