### ISSUE TITLE
Improve error: `Failed to connect to the host via ssh.` even without verbose

### ISSUE THREAD

**Issue by nhooey** [ansible/ansible#15706] opened 2016-05-03 17:58 UTC
##### ISSUE TYPE
- Feature Idea
##### ANSIBLE VERSION
- >= 2.0.2.0
##### CONFIGURATION

n/a
##### OS / ENVIRONMENT

n/a
##### SUMMARY

Ansible obscures the real SSH error with or without verbose, and prints a useless error message. It should print the connection error even with verbose turned off, because it's always important to the user to know why the SSH connection failed.
##### STEPS TO REPRODUCE

Run a playbook to a host that can't be connected to with SSH.
##### EXPECTED RESULTS

```
fatal: [name-of-host]: UNREACHABLE! => {
    "changed": false,
    "msg": "SSH Failure: 'Connection timeout'",
    "unreachable": true
}

fatal: [name-of-host]: UNREACHABLE! => {
    "changed": false,
    "msg": "SSH Failure: 'Denied (pubkey, password)'",
    "unreachable": true
}

fatal: [name-of-host]: UNREACHABLE! => {
    "changed": false,
    "msg": "SSH Failure: 'Unknown host'",
    "unreachable": true
}
```
##### ACTUAL RESULTS

```
fatal: [name-of-host]: UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh.",
    "unreachable": true
}
```

**Comment by CloudNinja42** [comment] 2016-05-11 12:09
+1 New to Ansible and don't know where my setup goes wrong :(

Seems its enough to try and ping the hosts:
ansible -m ping -u vagrant all
(In other words its not necessary to create a playbook for the Ssh host)

**Comment by GerDner** [comment] 2016-05-27 12:03
Same problem.

Ansible 2.1.0

**Comment by lihan** [comment] 2016-06-02 08:43
+1

**Comment by fallspectrum** [comment] 2016-06-03 18:21
+1

**Comment by sixth** [comment] 2016-06-04 02:24
+1

**Comment by sunggun-yu** [comment] 2016-06-04 03:57
+1

**Comment by cwhsu1984** [comment] 2016-06-12 08:57
+1

ansible 2.1.0.0

With root account and ssh key, it works

```
ansible test -a "/usr/bin/foo"
test | FAILED | rc=2 >>
[Errno 2] No such file or directory
```

With normal user account, it doesn't work

```
ansible test -a "/usr/bin/foo" -u cwhsu
test | UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh.", 
    "unreachable": true
}

```

This is pretty strange because I am sure that my account could access the server via ssh!

**Comment by chusiang** [comment] 2016-06-13 09:07
Maybe you can check your **ssh_connection** option at `ansible.cfg`. I has same problem with setting `ssh_config`.

it's working after I add **ssh_connection** option. now.
- ssh_config.
  
  ```
  $ cat ~/.ssh/config
  Host         node1
  Hostname     node1.example.tw
  Identityfile ~/.ssh/id_rsa
  ForwardAgent yes
  Compression  yes
  ControlMaster auto
  ControlPath  /tmp/ssh-%r@%h:%p
  ControlPersist 1h
  ```
- inventory file.
  
  ```
  $ cat staging
  node1  ansible_ssh_host=node1.example.tw
  ```
- ansible.cfg
  
  ```
  $ cat ./ansible.cfg
  [defaults]
  hostfile = staging
  remote_user = ubuntu
  host_key_checking = False
  retry_files_save_path = ./ansible-retry
  ...
  
  [ssh_connection]
  pipelining = True
  control_path = /tmp/ansible-ssh-%%h-%%p-%%r
  ```

## Reference
- [Wrong error message when unable to connect via ssh · Issue #12916 · ansible/ansible](https://github.com/ansible/ansible/issues/12916)

**Comment by jalevin** [comment] 2016-08-11 01:30
+1

**Comment by brandonheller** [comment] 2016-08-27 01:41
+1

**Comment by bezgubov** [comment] 2016-09-01 15:38
+1

**Comment by Ameausoone** [comment] 2016-09-02 13:20
+1

**Comment by Ameausoone** [comment] 2016-09-02 13:21
@Github Could you add a "+1" button on issues plz :)

**Comment by Hooddominator** [comment] 2016-09-09 12:46
same issue, but when connecting manually a warning about differing ECDSA host key appears and acknowledge for continue is needet. I removed relevant lines in ~/.ssh/known_hosts and connect manually again to add ECDSA in list back. Now ssh-connections in ansible works for me.

**Comment by yssvic** [comment] 2016-09-12 09:19
+1 I have same problem with some setups

**Comment by alikins** [comment] 2016-09-15 20:40
https://github.com/ansible/ansible/pull/16649 is a wip pr related to this.
Basically attempting to capture any 'ssh' command stderr to pass it back for display
(and if it is something specific we recognize raise an approriate exception...)

**Comment by alikins** [comment] 2016-09-15 22:01
https://github.com/ansible/ansible/pull/17598  is a more minimal fix for this.
Could folks seeing problems try out that branch?

**Comment by foxylion** [comment] 2016-09-19 08:02
It would be great when that gets merged quickly. In our case we occasionally get this error and without enabled debugging we aren't able to isolate the exact issue. Running always in debug mode is no option (giant log files).

**Comment by keNzi** [comment] 2016-09-22 10:32
+1

**Comment by maxisme** [comment] 2016-09-26 21:46
+1

**Comment by sherpaurgen** [comment] 2016-09-29 11:22
same issue in ansible version 2.1.1

**Comment by jctanner** [comment] 2016-09-30 13:35
Related https://github.com/ansible/ansible/pull/17813

**Comment by bcoca** [comment] 2016-10-03 02:45
fixed via 9ec69ee7eaf6386e0931a7826cc413f128554d89

**Closed as completed by bcoca** 2016-10-03 02:45 UTC
Labels: P2, affects_2.0, bug

**Comment by nhooey** [comment] 2016-10-03 10:37
The change just adds the hostname or IP. It doesn't state the reason for the failed connection, which was the whole point of this issue.

**Comment by nhooey** [comment] 2016-10-03 10:40
Nevermind, I jumped the gun.

**Comment by Freyja-Folkvangr** [comment] 2016-10-04 15:16
+1

**Comment by yogeshdarji** [comment] 2016-11-04 16:28
+1

**Comment by Idanatcox** [comment] 2016-11-04 17:47
+1

**Comment by andylemin** [comment] 2016-11-22 22:49
+10 Can't believe this is still not fixed in HEAD.. Disapointing, new users are struggling

**Comment by ekeyte** [comment] 2016-12-07 00:59
+1 I'm seeing this intermittently and it's very frustrating.

**Comment by chinni505** [comment] 2017-01-19 20:25
+1 intermittently getting this error.
ansible --version
ansible 2.2.0.0

**Comment by stigglor** [comment] 2017-01-25 22:00
Just upgraded from 2.0.0.1 -> 2.2.1.0, getting this exact issue intermittently across test environments. Same AWS AMI is being used to build nodes, using the same key, works sometimes in some envs, others it fails. Confirming I can access the nodes via the SSH command ansible is using, keys have the correct perms / correct user is being specified etc

**Comment by pavelzag** [comment] 2017-02-26 13:36
Experiencing it with 2.2.1.0 
TASK [setup] *******************************************************************
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/system/setup.py
<console.pavelz.io> ESTABLISH SSH CONNECTION FOR USER: root
<console.pavelz.io> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%C console.pavelz.io '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
fatal: [console.pavelz.io]: UNREACHABLE! => {
    "changed": false, 
    "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", 
    "unreachable": true
}

I definitely have a ping there

**Comment by jseadragon** [comment] 2017-03-02 16:46
I was seeing this issue consistently on certain hosts, and after manually pulling in the patch, I discovered that I had two hosts with the same name (but different IPs) in one of the files in my `hosts` directory. This was not obvious at all until I added in the patch in https://github.com/ansible/ansible/issues/15706#issuecomment-251016313

Specifying the file instead of the full dir is the change I'm making to my workflow.

     # Instead of this
     ansible-playbook -i hosts play.yml

     # I'll do this
     ansible-playbook -i hosts/site_i_want play.yml 

In this case it's totally my fault, just adding this for reference in case anyone else makes the same mistake.

**Comment by aaronshaver** [comment] 2017-03-18 22:31
+1

Seeing this on Ansible 2.1.1.0 on Ubuntu 16.10 64-bit. Doing `ansible <hosts> -m ping` seems to be a workaround that helps (temporarily).

**Comment by naveennitk2009** [comment] 2017-12-08 06:31
The problem is ssh known hosts prompt. You need to disable this in ansible. Open your ansible.cfg and add this (if not present, if present uncomment this)- 
host_key_checking = False

**Comment by shahzad73** [comment] 2018-03-19 10:35
My environment is a Ubuntu VM in virtualbox windows 10  and  cygwin in windows 10     ansible is installed in cygwin. here are the steps i used 

1.  i install cygwin in windows 10
2. deploy a ubuntu VM in virtualbox
3.  created ssh key and install it in my ubuntu without any password
4.  ssh into my VM from cygwin was successful as  shahzad@192.168.99.100 without any password

ansible.cfg file is    
[defaults]
hostfile = hosts

hosts file is 
[apache]
192.168.99.100 ansible_ssh_user=shahzad


When i run     ansible apache -m ping -vvvv

got this error 

ansible 2.4.3.0
  config file = /home/Shahzad Aslam/playbooks/ansible.cfg
  configured module search path = [u'/home/Shahzad Aslam/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Oct 31 2017, 21:12:13) [GCC 6.4.0]
Using /home/Shahzad Aslam/playbooks/ansible.cfg as config file
[DEPRECATION WARNING]: [defaults]hostfile option, The key is misleading as it can also be a list of hosts, a directory or a list of paths . This feature will
be removed in version 2.8. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
setting up inventory plugins
Parsed /home/Shahzad Aslam/playbooks/hosts inventory source with ini plugin
Loading callback plugin minimal of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/minimal.pyc
META: ran handlers
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/ping.py
<192.168.99.100> ESTABLISH SSH CONNECTION FOR USER: shahzad
<192.168.99.100> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=shahzad -o ConnectTimeout=10 -o 'ControlPath=/home/Shahzad Aslam/.ansible/cp/45dad2d866' 192.168.99.100 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<192.168.99.100> (255, '', 'command-line line 0: garbage at end of line; "Aslam/.ansible/cp/45dad2d866".\r\n')
192.168.99.100 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: command-line line 0: garbage at end of line; \"Aslam/.ansible/cp/45dad2d866\".\r\n",
    "unreachable": true
}
