### ISSUE TITLE
custom module fail with ssh pipelining

### ISSUE THREAD

**Issue by r0bj** [ansible/ansible#14193] opened 2016-01-28 21:52 UTC
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible 2.0.0.2
##### Ansible Configuration:

ansible.cfg:

```
[defaults]
library = ./libraries

[ssh_connection]
pipelining = True
```
##### Environment:

Managing from: OS X 10.11.3
Managed host: Ubuntu 15.10
##### Summary:

Using custom module with `ssh pipelining` enabled generates error: `MODULE FAILURE`.
Module works ok with `ssh pipelining` disabled. Ansible 1.9.x worked ok it this use case.
##### Steps To Reproduce:

test.yml:

```

---

- name: test
  hosts: all
  tasks:
    - name: test task3
      testmodule:
```

testmodule:

```
#!/bin/bash

echo '{"rc": 0, "msg": "ok"}'
```
##### Expected Results:

`ssh pipelining` disabled:

```
ansible-playbook -i hosts test.yml

PLAY [test] ********************************************************************

TASK [setup] *******************************************************************
ok: [vagrant]

TASK [test task3] **************************************************************
ok: [vagrant]

PLAY RECAP *********************************************************************
vagrant                    : ok=2    changed=0    unreachable=0    failed=0
```
##### Actual Results:

`ssh pipelining` enabled:

```
ansible-playbook -i hosts test.yml

PLAY [test] ********************************************************************

TASK [setup] *******************************************************************
ok: [vagrant]

TASK [test task3] **************************************************************
fatal: [vagrant]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}

PLAY RECAP *********************************************************************
vagrant                    : ok=1    changed=0    unreachable=0    failed=1
```

**Comment by bcoca** [comment] 2016-01-28 23:25
closing as dupe of #13815

**Closed as completed by bcoca** 2016-01-28 23:25 UTC
