### ISSUE TITLE
name clash of global var and var in include breaks interpolation

### ISSUE THREAD

**Issue by cigor** [ansible/ansible#816] opened 2012-08-09 12:35 UTC
Assume the following playbooks:

--- test1.yml

```
- name: included subtask
  action: command echo $myvar
```

-- test.yml

```
- name: test playbook
  vars:
    myvar: somevalue
  user: root
  hosts: all
  tasks:
   - include: test1.yml myvar=$myvar
```
## 

The included tasks will not have $myvar replaced (it stays as the literal $myvar). 
If instead of myvar=$myvar one uses myvar=${myvar}_test (or some other expression), ansible-playbook will exit with
ERROR: template recursion depth exceeded

This seems fragile and counterintuitive to me.

This is with git rev 093bbd1c825458fbe4acdcd9b0290d30e9942cff from Aug-09-2012

**Comment by mpdehaan** [comment] 2012-08-09 12:44
what version of ansible are you using?

(ansible --version) ?

**Comment by cigor** [comment] 2012-08-09 12:48
ansible 0.7 (devel 093bbd1c82) last updated 2012/08/09 10:56:18 (GMT +200)

**Comment by mpdehaan** [comment] 2012-08-09 12:51
thanks, will look into it.

**Comment by mpdehaan** [comment] 2012-08-09 13:17
I'm not saying this is not a bug (because it seems rather confusing), but wanted to share -- if you set myvar in "vars" you shouldn't have to pass it to the include like that.

**Comment by mpdehaan** [comment] 2012-08-10 00:27
from email I believe the issue is that vars passed to includes just don't work, which is more generic than name reuse -- I will need to look at both

**Comment by mpdehaan** [comment] 2012-08-10 01:10
Hi, should be fixed in commit 6c6a42b -- which I've just pushed.   Let me know if you encounter any problems with this or anything else with task includes.   Thanks!

**Closed as completed by mpdehaan** 2012-08-10 01:10 UTC

**Comment by crucialfelix** [comment] 2013-03-18 19:06
including and passing in variable names that are already defined as general host variables still causes 

fatal: [basicbox] => {'msg': 'template recursion depth exceeded', 'failed': True}

ansible 1.1

renaming the variables to a unique name for use in local scope avoids the problem

**Comment by mpdehaan** [comment] 2013-03-18 21:18
while this error should not occur, I should mention you don't have to
forward that variable along to the template to get it to see that.  Play
level vars can be seen by the include.
