### ISSUE TITLE
Ansible is overzealous with respect to SSH key

### ISSUE THREAD

**Issue by assarbad** [ansible/ansible#11659] opened 2015-07-20 17:47 UTC
##### Issue Type:
- Bug Report

##### Ansible Version:

Used version:

```
# ansible-playbook --version
ansible-playbook 2.0.0
  configured module search path = /data/ansible/library
```

**NB:** Meanwhile it turns out that the official PPA distributed a DEB for `trusty` that self-reports as `2.0.0-0.0.preppa~trusty` on 2015-06-25! In fact the version seems to be off of the 1.9.x line.
##### Ansible Configuration:

Can't find the vanilla version on Github. Your template should contain a link to that.
##### Environment:

Ubuntu 14.04.2 (x86_64)
##### Summary:

Despite having `connection: local` in my playbook, the following error causes the whole playbook to fail:

```
fatal: [host.lan] => private_key_file (/data/ansible/.ssh/id_rsa) is group-readable or world-readable and thus insecure - you will probably get an SSH failure
```
##### Steps To Reproduce:

The problem is created when using the `acl` module to add an `user:oliver:r-x` to the directory with the key and another `user:oliver:r--` to the `id_rsa` file. This results in the Unix file permission `r` being added for the group and therefore to the above error. Because of the overzealous check (_despite running locally!_) the next step of removing the `r` bit fails. Catch 22.
##### Expected Results:

Ansible should not care about my private SSH key for `connection: local`.
##### Actual Results:

It errors out, see above.

---

If more information is needed, let me know, please.

Oliver

**Comment by bcoca** [comment] 2015-07-20 17:52
Can You Help Us Out?
====================

Thanks for filing a ticket! I am the friendly GitHub Ansibot.

It looks like you might not have filled out the issue description based on our standard issue template.  You might not have known about that, and that's ok too, we'll tell you how to do it.

We have a standard template because Ansible is a really busy project and it helps to have some standard information in each ticket, and GitHub doesn't yet provide a standard facility to do this like some other bug trackers.  We hope you understand as this is really valuable to us!.

Solving this is simple: please copy the contents of this [template](https://raw.githubusercontent.com/ansible/ansible/devel/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket.  That's it!

If You Had A Question To Ask Instead
====================================

If you happened to have a "how do I do this in Ansible" type of question, that's probably more of a user-list question than a bug report, and you should probably ask this question on the project mailing list instead.

However, if you think you have a bug, the report is the way to go!  We definitely want all the bugs filed :)  Just trying to help!

About Priority Tags
===================

Since you're here, we'll also share some useful information at this time.

In general tickets will be assigned a priority between P1 (highest) and P5, and then worked in priority order. We may also have some follow up questions along the way, so keeping up with follow up comments via GitHub notifications is a good idea.

Due to large interest in Ansible, humans may not comment on your ticket immediately.

Mailing Lists
=============

If you have concerns or questions, you're welcome to stop by the ansible-project or ansible-development mailing lists, as appropriate.  Here are the links:

  * https://groups.google.com/forum/#!forum/ansible-project - for discussion of bugs and how-to type questions
  * https://groups.google.com/forum/#!forum/ansible-devel - for discussion on how to implement a code change, or feature brainstorming among developers

Thanks again for the interest in Ansible!

**Comment by assarbad** [comment] 2015-07-21 21:41
As a side-note it is not possible for me to edit the label at all, so I cannot comply to that request by the Github Ansibot.

**Comment by bcoca** [comment] 2015-07-21 21:51
soo, the steps to reproduce, can you show us the play that is causing this? with what you supply i cannot reproduce the problem.

**Comment by assarbad** [comment] 2015-07-21 23:25
I will try to come up with a minimal working example for you, but likely after some sleep.

**Comment by assarbad** [comment] 2015-07-24 20:33
Apologies for the delay. So this is how the error materializes:

![defect](https://cloud.githubusercontent.com/assets/3238620/8883914/f3f5e3c8-3241-11e5-90eb-f9e08cfbaea7.png)

I cannot attach a .tgz, so here are the two files used:

### `group_vars/all`

```
---
ansible:
  base: "/data/ansible"
  pubkey: "/data/ansible/.ssh/id_rsa.pub"
  seckey: "/data/ansible/.ssh/id_rsa"
  lxclog: "/var/log/lxc"
```

### `playbooks/trust.yml`

```
---
- name: Make sure the users root inside the containers trust us
  hosts: lxchost
  sudo: True
  connection: local
  gather_facts: False
  tasks:
    - name: Build /etc/ssh/ssh_known_hosts
      template: >
          owner=root
          group=root
          mode='u=rw,go=r'
          dest=/etc/ssh/ssh_known_hosts
          src={{ ansible.base }}/templates/ssh_known_hosts.j2
    - name: Build /etc/ssh/ssh_config
      template: >
          owner=root
          group=root
          mode='u=rw,go=r'
          dest=/etc/ssh/ssh_config
          src={{ ansible.base }}/templates/ssh_config.j2
    - name: Ensure ansible/.ssh exists
      file: >
          state=directory
          name={{ ansible.pubkey | dirname }}
          owner=root
          group=root
          mode='u=rwX,g=rX,o='
    - name: Ensure access to the SSH key directory
      acl: >
          entity=oliver
          etype=user
          name={{ ansible.seckey | dirname }}
          permissions=rx
          state=present
    - name: Create private key for Ansible host
      command: >
          ssh-keygen -t rsa -b 4096 -C "ansible@{{ inventory_hostname_short }}" -N '' -o -f {{ ansible.seckey }}
          creates={{ ansible.seckey }}
      register: result
    - name: Ensure access to the SSH secret key
      acl: >
          entity=oliver
          etype=user
          name={{ ansible.seckey }}
          permissions=r
          state=present
    - name: Ensure ansible/.ssh/id_rsa has correct permissions
      file: >
          state=file
          name={{ ansible.seckey }}
          owner=root
          group=root
          mode='u=rw,g=,o='
```

The `lxchost` can be a group or a single host. Please note that in my case the `lxchost` is also the host running Ansible. I am using the latest version available in your Ubuntu 14.04 repository.

All of these tasks are running on the host and the playbook contains no other tasks. Yet it fails because of some check of the private key. In my real playbook there is another play with more tasks following on another group of hosts, but I was able to reproduce the issue with what I provided to you above!

I think Ansible should either not assume something like this about the secret key _or_ should allow me to suppress it. Clearly in this case there is no need for an SSH connection and if the play would finish the problem would likely not even occur the way it is predicted by Ansible here.

**Comment by mscherer** [comment] 2015-07-25 09:01
So the problem is that ansible systematically check the permission on https://github.com/ansible/ansible/blob/devel/v1/ansible/runner/connection.py#L34 

But that's old v1 code, not sure how it is handled in the v2.

**Comment by sanear** [comment] 2015-09-02 17:38
I have also run into this issue. My use-case is pretty simple:

```
- hosts: localhost
  connection: local
  tags:
    - sg
    - key
    - always
  tasks:
    - name: Make sure ssh key directory exists
      file: path=files/ state=directory mode=0755

    - name: Download ssh keys from S3
      s3: bucket=my-org-deploy-keys object=/{{item}} dest=files/{{item}} mode=get
      with_items:
        - "{{aws_ssh_key}}"
        - "{{aws_ssh_key}}.pub"
```

Given that this is a local action, it seems I should be able to just add another task afterwards that sets correct permissions on the two keys, but Ansible chokes after the first item in the loop with

```
TASK: [Download ssh keys from S3] ********************************************* 
changed: [localhost] => (item=kafka-key)
fatal: [localhost] => private_key_file (files/kafka-key) is group-readable or world-readable and thus insecure - you will probably get an SSH failure

FATAL: all hosts have already failed -- aborting
```

Seems like Ansible should skip checking permissions on `{{ansible_ssh_private_key_file}}` when the connection is local.

Edit: Forgot to mention, this is from an OSX machine running the latest homebrew version, 1.9.2.

**Comment by vnitinv** [comment] 2015-09-15 18:09
same case for me too

ansible all -m ping -s -k -u regress
SSH password: 
xx.xxx.xxx.xxx | FAILED => private_key_file (/Users/nitins/nitins.pub) is group-readable or world-readable and thus insecure - you will probably get an SSH failure

running on Mac with ansible 1.9.3

**Comment by bykbtzr** [comment] 2015-09-16 20:55
IMHO this should be just an warn...

**Comment by XedinUnknown** [comment] 2015-10-14 23:22
+1 for warning. I'm  on Windows 10. I know Ansible doesn't officially support Windows, but I managed to install and run it no prob following instructions [here](http://www.azavea.com/blogs/labs/2014/10/running-vagrant-with-ansible-provisioning-on-windows/). How the heck does one correct permissions on Windows? :laughing:

**Comment by cooniur** [comment] 2015-10-15 23:08
+1 Ansible shouldn't care about whether the private key file is whatever readable/writable. Just use it as is please, even running against a remote server.

I got the same error while setting the devel environment for one of our new developers in Windows.

We use Vagrant to create a virtual box for each developer to have their own devel env. Ansible is used to provision the virtual box. The Ansible running in cygwin env is of version `1.9.4`.

**Comment by 4levity** [comment] 2015-10-30 23:42
Ansible v1.9.2 does not even do the SSH key permission check correctly i.e. it does not respect that group-readable keys actually _are_ supposed to be allowed as long as they are not owned by the user who is using them. (NB: Yes, this is in fact true.)

On my system (CentOS 7.1) I have an SSH key with owner=root group=admin , with permissions 0640. CentOS "ssh" command allows me to use this key, but Ansible does not.

**Comment by bcoca** [comment] 2015-10-31 00:17
i cannot reproduce in current devel, please check if this is still an issue for you on that version.

**Comment by selfevolv** [comment] 2015-11-11 02:24
this is my solution:(1.9.2/debian)

## chmod 700 /root/.ssh/rsa

so,as mscherer say,"ansible systematically check the permission"

**Comment by bcoca** [comment] 2015-11-14 17:58
so aside from the complaints about 1.9.x, which i cannot fix retroactively, current devel does not seem to have this problem any more. Unless i can get a reproducible example against 2.0 I'm going to close this as solved.

**Comment by assarbad** [comment] 2015-11-14 20:23
@bcoca I'm confused, my initial report and the subsequent provided YAML was all for Ansible 2.0.0. What am I missing? Of course I don't expect anything to be fixed retroactively.

Does the `ansible-playbook --version` output not indicate the Ansible version? It still reports as the same, btw.

**Comment by bcoca** [comment] 2015-11-14 23:04
as i've stated above I cannot reproduce the issue, after that there are other posts about 1.9 here with the same issue. Also note that the error you display is not currently in the Ansible codebase.

**Comment by assarbad** [comment] 2015-11-15 01:02
@bcoca I understand, but you did not state _what_ you tested. My assumption was that you'd go by the specifications I gave. And when I grep through my `/usr/share` after installing Ansible 2.0 according to the instructions given for Ubuntu, I **can** find:

```
# grep -R 'is group-readable or world-readable and thus insecure' /usr/share 2>/dev/null
/usr/share/pyshared/ansible/runner/connection.py:                raise AnsibleError("private_key_file (%s) is group-readable or world-readable and thus insecure - "
```

So evidently it _is_ in the version packaged and distributed as 2.0.0. To be precise:

```
# dpkg -l|grep ansible
ii  ansible                             2.0.0-0.0.preppa~trusty              all          A radically simple IT automation platform
```

Now, this is a long shot, but is it possible that someone messed up the package build for Ubuntu and ended up packaging something from the 1.x branches rather than the _actual_ 2.x?

I configured the PPA as outlined in [your Installation documentation](http://docs.ansible.com/ansible/intro_installation.html#latest-releases-via-apt-ubuntu) _months ago_, which resulted in:

```
# grep -R ansible /etc/apt
/etc/apt/sources.list.d/ansible-ansible-trusty.list:deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main
/etc/apt/sources.list.d/ansible-ansible-trusty.list:# deb-src http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main
```

Now, when I look at the [`trusty` packages](https://launchpad.net/~ansible/+archive/ubuntu/ansible?field.series_filter=trusty) on that PPA, they carry no such version. Which makes me think that someone actually put something live accidentally, my machine picked it up and I ended up with a package state that won't update, because any of your new 1.9.x releases are still going to be deemed _older_ by `apt` than what I have. The accidentally put up package got pulled again, no one knows a thing and I seem to be talking nonsense, although I just followed the documentation. My server just happened to pull the Ansible package between the time it was released and then pulled again.

However, since I am using `apt-cacher-ng` I can even prove that I received the package from your PPA:

```
./ppa.launchpad.net/ansible/ansible/ubuntu/pool/main/a/ansible
./ppa.launchpad.net/ansible/ansible/ubuntu/pool/main/a/ansible/ansible_1.9.1-1ppa~trusty_all.deb
./ppa.launchpad.net/ansible/ansible/ubuntu/pool/main/a/ansible/ansible_1.9.1-1ppa~trusty_all.deb.head
./ppa.launchpad.net/ansible/ansible/ubuntu/pool/main/a/ansible/ansible_2.0.0-0.0.preppa~trusty_all.deb
./ppa.launchpad.net/ansible/ansible/ubuntu/pool/main/a/ansible/ansible_2.0.0-0.0.preppa~trusty_all.deb.head
```

What I can't _prove_ is that this release was signed by you folks. But then it reasonably must have, since I have not in any way suppressed checking of `Release.gpg` against `Release`. However, since `apt-cacher-ng` fetches new versions of these files, I do not have the original files (`Release*`) from the time that package was live. Timestamp of the files is: 2015-06-25 20:44 (UTC). And:

```
# cat ansible_2.0.0-0.0.preppa~trusty_all.deb.head
HTTP/1.1 200 OK
Last-Modified: Thu, 25 Jun 2015 20:28:17 GMT
Content-Length: 690192
Connection: Keep-Alive
Content-Type: application/x-debian-package
X-Original-Source: http://ppa.launchpad.net/ansible/ansible/ubuntu/pool/main/a/ansible/ansible_2.0.0-0.0.preppa~trusty_all.deb
Date: Thu Jun 25 20:44:20 2015
```

Of course my findings so far seem to strengthen your point about this being a 1.9.x problem. Apparently a version was released via your PPA on 2015-06-25 which is some kind of mix of 2.x and 1.9.x version.

I'll undo this for myself now, obviously, but that means I have to go back to 1.9.x. And as you already stated, you're not going to fix that. I'll keep a copy of the DEB in case you or your team wants to have a look.

edit: I wrote the above in the order it appears in my post. So some of the initial statements may seem to contradict the later findings.

**Comment by assarbad** [comment] 2015-11-15 01:15
In other words, feel free to close if you don't support 1.9.x anymore.

However, it's a little bit strange you should not provide newer (actual 2.x) packages but cease support for 1.9.x packages that are still provided on the PPA of the Ansible project.

**Comment by sivel** [comment] 2015-11-15 02:10
Just as an FYI, there was a documented "errant build problem" on June 25, 2015:  https://groups.google.com/forum/#!topic/ansible-devel/ux4cP_e0pFo

**Comment by assarbad** [comment] 2015-11-15 09:32
@sivel Thanks, that would explain it then, I suppose.

**Comment by bcoca** [comment] 2015-11-15 19:38
ok, this clears things up, the initial report was on 2.0, but you seem to have a mixed installed as the error is coming from a 1.9 file. That explains why I cannot reproduce the issue in 2.0.

I'm reclassifying this for 1.9, at this point it is not clear if there will be a 1.9.5 release for which this might be fixed and part of. As it stands I'm considering this 'fixed' in current devel and in consideration for a backport.

**Comment by jctanner** [comment] 2017-03-09 16:34
1.9 will have no more releases.

**Closed as completed by jctanner** 2017-03-09 16:34 UTC
Labels: backport, affects_2.0, bug
