### ISSUE TITLE
selinux AVC denial around /tmp/.ansible-lock.0 (needs info?)

### ISSUE THREAD

**Issue by nirik** [ansible/ansible#5399] opened 2013-12-22 19:31 UTC
Downstream bug report: 

https://bugzilla.redhat.com/show_bug.cgi?id=1043734

User is seeing avc denials on the ansible-lock, possibly related to it not being removed on every run?

**Comment by mpdehaan** [comment] 2013-12-23 00:03
"There is no evidence that I know of that they don't care about selinux."

Agree, we do care about SELinux, and test on it frequently, and have zillions of users running SELinux.   I'm curious here what the expectation is as I haven't heard any reports of problems in this area and the lock code is not new.

"Clearly there's a filehandle leak in ansible."

Where?  Show me.    (Also show me docs on opening with 'we' ?)

"When running ansible with command executed in SELinux domain which does not have access to /tmp/.ansible-lock.0, AVC denial is logged."

Sounds like the compliant is that someone took away access to the file in /tmp and then are complaining it can't access the file in /tmp.   I'm not trying to be difficult here, but this sounds like a "doctor, my arm hurts when I do this" kind of scenario.  Help me understand?

Why would a file not being removed produce an avc denial?   It seems creating the file would produce a denial and removing it would not, and SELinux shouldn't track whether a file is created and not removed?

Also Jan's being quite incorrect about Cobbler - cobbler worked fine with SELinux and we had to go through some hell with EL4 until EL5 made things like public_content_t and we couldn't support SELInux on EL4 -- at the advice of Dan Walsh no less.  It supported SELinux on EL5 quite fine (and I maintained the package for a long time in EPEL so there were no patches on top).   And how many crazy years ago was that to even bother bringing that up?  SELinux usability has advanced quite a bit since.

**Comment by adelton** [comment] 2013-12-23 03:09
> "There is no evidence that I know of that they don't care about selinux."

I was talking about cobbler, not ansible. If the policy towards SELinux is better in ansible, that's good to hear.

> Agree, we do care about SELinux, and test on it frequently, and have zillions of users running SELinux. I'm curious here what the expectation is as I haven't heard any reports of problems in this area and the lock code is not new.
> 
> "Clearly there's a filehandle leak in ansible."
> 
> Where? Show me. (Also show me docs on opening with 'we' ?)

Well, the

```
ansible -c local -i localhost, all -m shell -a "/usr/sbin/semanage fcontext -a -t var_log_t /tmp/test"
```

is the show, isn't it?

The "e" mode is discussed at http://bugs.python.org/issue16850. There can of course be many different ways, my patch was just an example of possible solution.

> "When running ansible with command executed in SELinux domain which does not have access to /tmp/.ansible-lock.0, AVC denial is logged."
> 
> Sounds like the compliant is that someone took away access to the file in /tmp and then are complaining it can't access the file in /tmp. I'm not trying to be difficult here, but this sounds like a "doctor, my arm hurts when I do this" kind of scenario. Help me understand?

There is no close-on-exec set on that filehandle. I don't understand your doctor example.

> Why would a file not being removed produce an avc denial? It seems creating the file would produce a denial and removing it would not, and SELinux shouldn't track whether a file is created and not removed?

There are two issues -- first is, the filehandle leaks to the forked process and SELinux fortunately catches the situation.

Second is that the lock file stays around after the ansible run has finished which I find suboptimal.

I really care about the first issue only, the second is just an observation.

> Also Jan's being quite incorrect about Cobbler - cobbler worked fine with SELinux and we had to go through some hell with EL4 until EL5 made things like public_content_t and we couldn't support SELInux on EL4 -- at the advice of Dan Walsh no less. It supported SELinux on EL5 quite fine (and I maintained the package for a long time in EPEL so there were no patches on top). And how many crazy years ago was that to even bother bringing that up? SELinux usability has advanced quite a bit since.

My comments on cobbler are based on https://github.com/cobbler/cobbler/wiki/Selinux and experience with EPEL 6 / Fedoras: https://bugzilla.redhat.com/show_bug.cgi?id=838898#c7.

**Comment by mpdehaan** [comment] 2013-12-23 17:20
To be clear, I'm asking for an end-user example of what  happened -- why did you execute the above ansible command?   What did it do relative to what you expected and what did you hope it would do?

"There are two issues -- first is, the filehandle leaks to the forked process"

I don't see why that's a problem that we're allowing filehandle usage by subprocesses in that we're explicitly using multiprocessing for multiprocessing.   A fork is allowed to inherit memory from the patent -- Perhaps you can elaborate.   It would definitely be a problem if stock SELinux policy caused a problem, but it does not, and as a result all of our users are ok.

Whether it's leaking a filehandler or not seems immaterial to the direct question -- are people broken?  And it seems nobody is, except you, and I want to understand why.  So far, the use case seems arbitrarily constructed to construct a problem, and I need to know more.

So -- note -- I don't pretend to completely understand why you are executing the command that you did -- it seems you executed a command to make SELinux more restrictive (some additional rules on a var_log_t instead of the default type), and are now saying the application has policies with your context change.   You're actually changing the context of files Ansible is using while it's running, it seems like, which just seems unusual and perhaps, arbitrary, hence wanting to understand more.

What I'm most interested in is this -- nobody else has reported a problem yet -- so with the userbase of our size, this makes me curious -- and the code around this is very very not new, so I'm curious what scenario you got into where you encountered a problem that affected you as a user, so we can understand the underlying circumstances.

I'm mostly getting a "code" discussion here and would like to understand the first part first -- why did you need to execute the above command on /tmp in the middle of an Ansible run?

As far as the part about doing a "open with we", the ticket you opened implies that will raise an exception on platforms where that is not supported, and that sounds disadvantageous to me for cross platform support reasons.   Can you point me to more information about why this mode would be advantageous and documentation on SELinux policy configurations that would enforce this?  (Again, regular SELinux users not having any problems with Ansible -- I need to understand more about why we might want to make that kind of change, rather than just seeing a proposed patch).

I'm not disputing that there is a problem, but so far the conversation hasn't included any use cases or explanation around that, and is only talking in purely technical terms.   I'm missing the big picture of what you are trying to do.

**Comment by mpdehaan** [comment] 2013-12-23 17:32
Note:  aforementioned Cobbler issues are after my time.   @jimi-c does work for us, and I fully support his decisions in the past -- it can be frustrating to work on ever-moving targets with the Fedora release cycle, while also dealing with lots of other moving targets.   

When someone has a lot of other priorities, spending weeks working with a distribution developer to make sure a bug is resolved in rawhide or the latest Fedora release can be difficult , and I respect that decision for any open source project that wishes to make it.

However, I'll say it now, there's no reason to bring that up in relation to Ansible, this is not that project, and Cobbler has had (historically) many challenges working with keeping SELinux happy because it surfaces content up via multiple content types and talks to a lot of different services.   

Ansible is mostly doing basic OS level things every normal user does, and has an easier time.  To those reading the ticket, also note the file module has full awareness of how to work with SELinux types.   Our product also works fine with SELinux enforcing too.

We would like to make this work for anyone, and it is our position that Ansible run fine from an SELinux enforcing machine, and currently believe that it does, which is why we need more information on the above.

Let's not cast aspersions on this project based on unrelated technical details of another.

**Comment by adelton** [comment] 2013-12-24 02:19
> To be clear, I'm asking for an end-user example of what happened -- why did you execute the above ansible command? What did it do relative to what you expected and what did you hope it would do?

The full end-user example is internal. The command was executed to set some fcontext on completely unrelated directory. Perhaps the user writing the command needed that directory to have the fcontext? It caused AVC denial to be logged and I'd expect no-AVC denials.

You seem to be distracted by the fact that the command that I showed in the example is SELinux-related. So maybe this one will be better:

```
# ansible -c local -i localhost, all -m shell -a "passwd"
```

and it leads to

  type=AVC msg=audit(1387850292.233:1842): avc:  denied  { write } for  pid=18200 comm="passwd" path="/tmp/.ansible-lock.0" dev=dm-0 ino=1966087 scontext=unconfined_u:unconfined_r:passwd_t:s0-s0:c0.c1023 tcontext=unconfined_u:object_r:user_tmp_t:s0 tclass=file

Or command in any other domain which does not have allow for user_tmp_t.

> I don't see why that's a problem that we're allowing filehandle usage by subprocesses in that we're explicitly using multiprocessing for multiprocessing. A fork is allowed to inherit memory from the patent -- Perhaps you can elaborate. It would definitely be a problem if stock SELinux policy caused a problem, but it does not, and as a result all of our users are ok.

Are you saying it's OK that user programs that are run by ansible get to mess up with its lockfile (unless of course prevented to do so on SELinux enforced system)? I would understand that you might need to inherit the lockfile for the purpose of synchronization itself (even if looking at the code base, it does not seem to be the case -- the LOG_LOCK variable is only used to create and lock the file, nothing else) but user commands? How are the user commands to know which filehandle is the ansible lock filehandle -- do you export some environment variable with the fileno? Again, looking at the code you don't.

It looks like a bug but if it is intended behaviour, maybe it would be good to document it because it is certainly not standard approach to security.

Note that it _is_ stock SELinux policy that I'm using. The fact that the command I happened to use is semanage has nothing to do with the fact that the lockfile handle does not have close-on-exec.

> Whether it's leaking a filehandler or not seems immaterial to the direct question -- are people broken? And it seems nobody is, except you, and I want to understand why. So far, the use case seems arbitrarily constructed to construct a problem, and I need to know more.

I can't give you more reasoning than wanting code to run without AVC denials.

> So -- note -- I don't pretend to completely understand why you are executing the command that you did -- it seems you executed a command to make SELinux more restrictive (some additional rules on a var_log_t instead of the default type), and are now saying the application has policies with your context change. You're actually changing the context of files Ansible is using while it's running, it seems like, which just seems unusual and perhaps, arbitrary, hence wanting to understand more.

No, see above.

> What I'm most interested in is this -- nobody else has reported a problem yet -- so with the userbase of our size, this makes me curious -- and the code around this is very very not new, so I'm curious what scenario you got into where you encountered a problem that affected you as a user, so we can understand the underlying circumstances.

The scenario is that due to a bug in ansible code, running some commands will log AVC denial. Nothing else.

> I'm mostly getting a "code" discussion here and would like to understand the first part first -- why did you need to execute the above command on /tmp in the middle of an Ansible run?

Because in the real scenario, it's probably not on /tmp but on some other directory that is being set up as part of some big software project installation. The /tmp is just an example and as shown above, it can be passwd instead of semanage.

> As far as the part about doing a "open with we", the ticket you opened implies that will raise an exception on platforms where that is not supported, and that sounds disadvantageous to me for cross platform support reasons. Can you point me to more information about why this mode would be advantageous and documentation on SELinux policy configurations that would enforce this? (Again, regular SELinux users not having any problems with Ansible -- I need to understand more about why we might want to make that kind of change, rather than just seeing a proposed patch).

http://danwalsh.livejournal.com/53603.html

**Comment by mpdehaan** [comment] 2013-12-24 18:03
Sounds like the problem is because you are still running with a non stock SELinux configuration, these statements appear to be at odds.

"Or command in any other domain which does not have allow for user_tmp_t"

"Note that it is stock SELinux policy that I'm using"

This seems to be what audit2allow is for in your case.

**Comment by adelton** [comment] 2013-12-25 01:03
> Sounds like the problem is because you are still running with a non stock SELinux configuration, these statements appear to be at odds.
> 
> "Or command in any other domain which does not have allow for user_tmp_t"
> 
> "Note that it is stock SELinux policy that I'm using"
> 
> This seems to be what audit2allow is for in your case.

Did you even try to run

```
# ansible -c local -i localhost, all -m shell -a "passwd"
```

on stock RHEL 6 installation?

**Comment by martinpovolny** [comment] 2014-01-03 11:00
@mpdehaan : I understand that ansible is doing exactly what is explained in http://danwalsh.livejournal.com/53603.html -- leaking the FD to the child process.

It there a problem to add the `FD_CLOEXEC` flag when opening the temp file?

It seems to me it should not cause any trouble to people who don't care about SELinux and would help those who do care about security.

Thank you!

**Comment by mscherer** [comment] 2014-01-07 23:52
I tested and I am running the default selinux policy on rhel6, updated in 6.5 and i can reproduce. 
I tested on F20 and cannot reproduce
I tested with git head of ansible on EL6, and the AVC is triggered.
As the reporter say, this is likely a FD leak, and so should be fixed. 

The patch in https://bugzilla.redhat.com/show_bug.cgi?id=1043734#c2 is working fine, I can provide a PR if we agree that the correct fix. I quickly tested on RHEL5, and it doesn't explode, I will do more tests tomorrow.

**Comment by mpdehaan** [comment] 2014-01-08 00:00
" would help those who do care about security"

Your tone here implies that I do not, which is rather insulting.

**Comment by mpdehaan** [comment] 2014-01-08 00:05
@mscherer, I'm not confident this patch is supported on all possible
pythons we are using and still haven't seen good documentation for 'we'.

I'll admit I don't fully understand the ramifications of what you are
doing, but could _NOT_ reproduce this myself when I was trying it.   Are
you also running additional SELinux commands on top of a stock install to
fiddle with things in /tmp?

It may be helpful if you provide steps to reproduce the problem.

The documentation on 'we' seems to indicate that on systems and platforms
where 'we' is not supported this raises an exception, which implies this
patch isn't sufficient, and at least needs to test for the capability.
http://bugs.python.org/issue16850 ... this looks like this would break on
all pythons where this isn't available, which would be quite bad.

If that is handled, we are willing to test with the lockfile code to see if
the lock is still usable, though it seems to defeat the purpose of the
lockfile on initial review if it's closed, but I may be misunderstanding
the ramifications.

**Comment by adelton** [comment] 2014-01-08 02:29
> It may be helpful if you provide steps to reproduce the problem.
1. Have RHEL 6.5 with stock SELinux policy, SELinux enabled.
2. Install ansible from EPEL 6 (ansible-1.4.1-1.el6.noarch).
3. Run `ansible -c local -i localhost, all -m shell -a "passwd"`
4. Run `grep AVC /var/log/audit/audit.log`

Actual results:

Something like

```
type=AVC msg=audit(1388631051.402:67): avc:  denied  { write } for  pid=7273 comm="passwd" path="/tmp/.ansible-lock.0" dev=dm-0 ino=393222 scontext=unconfined_u:unconfined_r:passwd_t:s0-s0:c0.c1023 tcontext=unconfined_u:object_r:user_tmp_t:s0 tclass=file
```

will be in the audit.log.

Expected results:

No AVC denial.

**Comment by mscherer** [comment] 2014-01-08 07:08
@mpdehaan yeah, that's also the first time I heard about the 'e' flag, and the documentation on it is nearly inexistant on the python side, but you have to look on the glibc side in man fopen, where it explain it is just using O_CLOEXEC. Another solution could be to explicitly close the fd on exec, but that's IMHO error prone. We could also call fnctl ourself, we do not care about the race condition IMHO.

**Comment by martinpovolny** [comment] 2014-01-10 16:39
@mpdehaan : "Your tone here implies that I do not, which is rather insulting." Sorry for that, it was not my intention.

In my defense I have to say, that your previous reactions seemed a bit marginalising to me (hope that's the correct and polite word).

I meant no offense.

**Closed as completed** 2014-02-10 21:53 UTC
Labels: bug

**Comment by jimi-c** [comment] 2014-02-10 21:55
The above patch should correct the problem, I am no longer seeing any AVC's on CentOS 6.5 with that change in place. If you continue having any issues with this, please let us know. Thanks!
