### ISSUE TITLE
raw does not work on windows 

### ISSUE THREAD

**Issue by yanivrefael** [ansible/ansible#23785] opened 2017-04-20 06:28 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
raw module 

##### ANSIBLE VERSION
2.3

##### CONFIGURATION
windows server 2012 R2

##### OS / ENVIRONMENT
windows server 2012 R2

##### SUMMARY
Execute raw command on windows 

##### STEPS TO REPRODUCE
Execute raw command on windows fail since I upgraded the ansible to 2.3

```

**Comment by jhawkesworth** [comment] 2017-04-20 13:19
Please provide an example minimal playbook,  inventory and group vars to reproduce this.
Also please advise which OS you are running ansible on

needs_info

**Comment by jborean93** [comment] 2017-08-30 07:31
Closing as raw works for me and without further details from the issue author we can't do much.

**Closed as completed by jborean93** 2017-08-30 07:31 UTC
Labels: needs_info, windows, affects_2.3, module, support:core, bug
