### ISSUE TITLE
Feature Suggestion: Ansible to establish SSH session

### ISSUE THREAD

**Issue by westover** [ansible/ansible#13277] opened 2015-11-24 05:23 UTC
I find myself in many situations executing Ansible to deploy systems but frequently want to use the same credential set to SSH to those machines. Currently for static hosts I am keeping two lists of the same information `.ssh/config` and a hosts file.

So what I am suggesting would be to use Ansible's inventory to enable more rapid SSH connections including but not limited to connecting to static hosts and to dynamic inventory when the result set is a single node.

**Comment by amenonsen** [comment] 2015-11-24 06:42
== #12852

**Comment by bcoca** [comment] 2015-11-24 15:58
closing as duplicate of #12852

**Closed as completed by bcoca** 2015-11-24 15:58 UTC
Labels: feature
