### ISSUE TITLE
utf8 exception thrown when using fetch

### ISSUE THREAD

**Issue by jsmartin** [ansible/ansible#4046] opened 2013-09-06 06:15 UTC
relevant snippet:

```
- name: grab benchmark results
  fetch: src={{ result.test_archive }} dest="{{ staging_dir }}/{{ ansible_hostname }}/" flat=yes


TASK: [grab benchmark results] ************************************************ 
fatal: [10.42.0.200] => Traceback (most recent call last):
  File "/Users/jmartin/work/code/workspaces/ansible/ansible-core/lib/ansible/runner/__init__.py", line 393, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/Users/jmartin/work/code/workspaces/ansible/ansible-core/lib/ansible/runner/__init__.py", line 482, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/Users/jmartin/work/code/workspaces/ansible/ansible-core/lib/ansible/runner/__init__.py", line 657, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/Users/jmartin/work/code/workspaces/ansible/ansible-core/lib/ansible/runner/action_plugins/fetch.py", line 82, in run
    remote_md5 = utils.md5s(remote_data)
  File "/Users/jmartin/work/code/workspaces/ansible/ansible-core/lib/ansible/utils/__init__.py", line 397, in md5s
    digest.update(data.encode('utf-8'))
  File "/Users/jmartin/.virtualenvs/ansible-git/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8b in position 1: invalid start byte


FATAL: all hosts have already failed -- aborting
```

**Comment by jsmartin** [comment] 2013-09-06 13:03
This is reproducible with ansible 1.3 (devel aa0a31c0fc) last updated 2013/09/06 07:58:27 (GMT -400)

There is no issue with:

ansible 1.2 (release1.2 8584a945d6) last updated 2013/09/06 08:58:57 (GMT -400)

I'm trying to track down the commit that is causing the problem.

**Comment by jimi-c** [comment] 2013-09-06 13:16
This is a duplicate of this issue: #4014, so closing this.

**Closed as completed by jimi-c** 2013-09-06 13:16 UTC
