### ISSUE TITLE
mysql_db import action fails with confusing error when database does not exist

### ISSUE THREAD

**Issue by packetcollision** [ansible/ansible#6214] opened 2014-02-27 22:02 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.4.4
##### Environment:

N/A (but I'm on a mac, trying to send commands to a machine running Ubuntu 12.04)
##### Summary:

If you try to run "mysql_db: name=nonexistantdb state=import target=/foo.sql" and the database doesn't exist, the command fails with "unable to connect, check login_user and login_password are correct, or alternatively check ~/.my.cnf contains credentials"
##### Steps To Reproduce:

run "mysql_db: name=nonexistantdb state=import target=/foo.sql" when the database does not exist. Make sure to use the right credentials (or have them specified in .my.cnf)
##### Expected Results:

It really should output the actual SQL error, which is: 1049, "Unknown database 'nonexistantdb'"
##### Actual Results:

the command fails with "unable to connect, check login_user and login_password are correct, or alternatively check ~/.my.cnf contains credentials"

**Comment by DSpeichert** [comment] 2014-03-19 18:43
I just had the same problem, I think the database should be created automatically.
Ubuntu 14.04 / Ansible 1.5.3-trusty-unstable-ppa2

**Comment by josef-spak** [comment] 2014-03-28 09:05
I can reproduce this exactly, with the latest dev version as well.

ansible-playbook 1.6 (devel 3b285d736c)

**Comment by Jmainguy** [comment] 2014-03-30 17:21
The reason it is failing is because it uses the database name to connect with initially, so if it doesn't exist, it cant work. 

That being said the code could be changed to connect to to db=mysql in the event of state=import and database does not exist. If this seems like a good idea I can take a stab at adding it in.

**Comment by varas** [comment] 2014-05-08 09:03
Same issue: 
- Version: 1.5.5
- Modules: mysql_user, mysql_db
- Target: ubuntu 14.04

Msg:

```
unable to connect to database, check login_user and login_password are correct or ~/.my.cnf has the credentials
```

**Comment by Jmainguy** [comment] 2014-07-11 18:58
Added error message for when db does not exist to import. #8103

**Comment by jimi-c** [comment] 2014-07-11 19:47
The above PR has been merged in, which should correct this. Thanks!

**Closed as completed by jimi-c** 2014-07-11 19:47 UTC
Labels: bug, mysql
