### ISSUE TITLE
vars resolving/ group_by: special case of bad resolving in group_by where key points to a var holding another var

### ISSUE THREAD

**Issue by srgvg** [ansible/ansible#10327] opened 2015-02-24 11:12 UTC
##### Issue Type:

Fancy Corner Case Bug
##### Ansible Version:

Introduced in current devel as well as 1.8.2 and up.
In the 1.8 tree, the bug was introduced by 4cd87ec93ec1f5266e5afaaa8e6734d642284afe

Note that while the bug is unrelated, this "faulty" commit is the same as for #9753
##### Environment:

N/A (tested on Ubuntu 14.04)
##### Summary:

Using a key pointing to a variable, that itself is defined as another variable construct, in combination with group_by, the resulting key (probably that subvar) is onlky calculated once for the first host, so all hosts are put in the same group.
##### Steps To Reproduce:

Create an inventory `hosts` file with some hosts where the first three chars point to a datacenter:

```
dc1-ch1-bl1                                                                     
dc2-ch1-bl2                                                                     
dc1-ch1-bl3                                                                     
dc2-ch1-bl4                                                                     
dc2-ch1-bl5   
```

and provide this variable in `group_vars/all.yml`:

```
datacenter: '{{ inventory_hostname[:3] }}'
```

Test with the commmand 
`ansible all -i hosts -c local -m group_by -a key={{datacenter}}`

Also change the _first_ host in the inventory file from `dc1-ch1-bl1` to `dc2-ch1-bl1` and observe the difference.
##### Expected Results:

Works with ansible release1.8.1 ad675235e2 last updated 2014/12/02 10:53:48 (GMT +200):

```
$ ansible all -i hosts -c local -m group_by -a key={{datacenter}}
dc1-ch1-bl1 | success >> {
    "changed": true, 
    "groups": {
        "dc1": [
            "dc1-ch1-bl1", 
            "dc1-ch1-bl3"
        ], 
        "dc2": [
            "dc2-ch1-bl2", 
            "dc2-ch1-bl4", 
            "dc2-ch1-bl5"
        ]
    }
}
```
##### Actual Results:

```
dc1-ch1-bl1 | success >> {
    "changed": true,
    "groups": {
        "dc1": [
            "dc1-ch1-bl1",
            "dc2-ch1-bl2",
            "dc1-ch1-bl3",
            "dc2-ch1-bl4",
            "dc2-ch1-bl5"
        ]
    }
}
```

or after changing the _first_ host in the inventory file from `dc1-ch1-bl1` to `dc2-ch1-bl1`:

```
dc2-ch1-bl1 | success >> {
    "changed": true,
    "groups": {
        "dc2": [
            "dc2-ch1-bl1",
            "dc2-ch1-bl2",
            "dc1-ch1-bl3",
            "dc2-ch1-bl4",
            "dc2-ch1-bl5"
        ]
    }
}
```

**Comment by srgvg** [comment] 2015-02-24 11:17
FYI, in v2 this command gets totally broken, seems like group_vars are not even parsed?

```
$ ansible --version
ansible 2.0 (devel 65e68cdff9) last updated 2015/02/24 10:37:03 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 706be79f8f) last updated 2015/02/24 12:07:22 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 2ffd7235e5) last updated 2015/02/24 12:07:22 (GMT +200)
  v2/ansible/modules/core: (detached HEAD 34784b7a61) last updated 2015/02/24 12:07:22 (GMT +200)
  v2/ansible/modules/extras: (detached HEAD 312d59061c) last updated 2015/02/24 12:07:22 (GMT +200)
  configured module search path = None
$ ansible all -i hosts -c local -m group_by -a key={{datacenter}}
dc2-ch1-bl1 | FAILED! => {'msg': "ERROR! the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'datacenter' is undefined", 'failed': True}
dc2-ch1-bl2 | FAILED! => {'msg': "ERROR! the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'datacenter' is undefined", 'failed': True}
dc1-ch1-bl3 | FAILED! => {'msg': "ERROR! the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'datacenter' is undefined", 'failed': True}
dc2-ch1-bl4 | FAILED! => {'msg': "ERROR! the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'datacenter' is undefined", 'failed': True}
dc2-ch1-bl5 | FAILED! => {'msg': "ERROR! the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'datacenter' is undefined", 'failed': True}
```

**Comment by srgvg** [comment] 2015-02-24 11:27
Sounds very familiar with #9037
Also possibly related to #7540

**Comment by jimi-c** [comment] 2015-06-22 05:34
@svg, this sounds like a duplicate of #7199 (closed #7540 for the same reason). Since group_by is a BYPASS_HOST_LOOP action plugin and inventory_hostname is based on the host, it will only ever be the first host in the list as that's where BYPASS_HOST_LOOP actions run by default. Not really sure if there's a good solution here unless we implement the opposite of the `run_once` flag for tasks to make something which would normally be a bypass touch every host (though I'm pretty sure that'd have ugly consequences too).

If you agree, I'll close this here as a dupe.

**Comment by srgvg** [comment] 2015-06-22 07:09
OK, that makes sense. I agree with you that extra code above this might get ugly very fast.

Given the comments on those other tickets, I think the least that should be done is issue a warning when combining a coditional and a bypass action plugin?

**Comment by jimi-c** [comment] 2015-06-22 11:48
Yes, we can discuss that on the original issue. I would hate to issue a blanket warning at execution time, so I was leaning towards clear documentation with bright warnings, however I'm open to other suggestions.

Thanks!

**Closed as completed by jimi-c** 2015-06-22 11:48 UTC
Labels: P2, bug
