### ISSUE TITLE
inventory_dir not getting passed via group vars in 2.0.0, but was in 1.9.3

### ISSUE THREAD

**Issue by jpooler** [ansible/ansible#12653] opened 2015-10-06 20:12 UTC
Issue Type:

Bug Report

Ansible Version:
jarrod @ Jarrods-MacBook-Pro:[~] $ ansible --version
ansible 2.0.0 (devel 5ae74f7d38) last updated 2015/10/06 15:15:05 (GMT -400)
  lib/ansible/modules/core: (detached HEAD d659c79db7) last updated 2015/10/06 15:15:11 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 0ff1776a84) last updated 2015/10/06 15:15:15 (GMT -400)
  config file =
  configured module search path = None

OS is OSX 10.10.5 (yosemite)

Summary:

The inventory_dir variable doesn't get passed to a task in a role via the inventory group_var file.

Steps To Reproduce:
## playbook.yml:
- hosts: '{{target}}'
  serial: 1
  gather_facts: yes
  sudo: yes
  
  vars:
    target: 'service'
  
  pre_tasks:
  - datadog_event: title="Deployment of service" text="BEGIN - SERVICE deployment" priority="low" api_key="{{datadog_api_key}}"
  
  post_tasks:
  - datadog_event: title="Deployment of service" text="END - SERVICE deployment" priority="low" api_key="{{datadog_api_key}}"
  
  roles:
  - service.haproxy

inventory/service/group_vars/haproxy.yml

---

haproxy:
  fragments:
    server:
      src: '{{inventory_dir}}/../../roles/service/templates/haproxy.cfg.j2'

TASK [service.haproxy : debug var=inventory_dir] *******************************
ok: [HOST.amazonaws.com] => {
    "changed": false,
    "inventory_dir": null
}

TASK [service.haproxy : Copy fragments] ****************************************
failed: [HOST.amazonaws.com] => (item={'value': {u'src': u'/../../roles/service/templates/haproxy.cfg.j2'}, 'key': u'haproxy'}) => {"failed": true, "item": {"key": "haproxy", "value": {"src": "/../../roles/service/templates/haproxy.cfg.j2"}}, "msg": "IOError: [Errno 2] No such file or directory: u'/roles/service/templates/haproxy.cfg.j2'"}

jarrod @ Jarrods-MacBook-Pro:[~] $  ansible-playbook -i inventory/service/ playbooks/service/main.yml  --extra-vars="target=service" -u ec2-user -M modules/ --private-key ~/.ssh/root_key

EXPECTED RESULTS:

"inventory_dir": "/path/to/inv"

ACTUAL RESULTS:

"inventory_dir": "null"

This works in 1.9.3, but does not in 2.0.0 latest

**Comment by jimi-c** [comment] 2015-10-07 05:34
Hi @jpooler, I am unable to reproduce this against the current devel, using the following setup (which I've tried to setup to mirror your example above as closely as possible):

<pre>
# cat test.yml 
- hosts: localhost
  gather_facts: no
  roles:
  - test
# cat service/inventory/inv 
[foo]
localhost ansible_connection=local
# cat service/inventory/group_vars/foo.yml 
haproxy:
  fragments:
    server:
      src: '{{inventory_dir}}/../../roles/service/templates/foo.j2'
# cat roles/test/tasks/main.yml 
---
# tasks file for roles/test
- debug: var=inventory_dir
- template: src="{{item.fragments.server.src}}" dest=/tmp/12653.txt
  with_items:
  - "{{haproxy}}"
# cat roles/service/templates/foo.j2 
this is from {{inventory_hostname}}
</pre>

When run:

<pre>
# ansible-playbook -vv test.yml -i service/inventory/inv 
Using /etc/ansible/ansible.cfg as config file
1 plays in test.yml
PLAY ***************************************************************************
TASK [test : debug var=inventory_dir] ******************************************
ok: [localhost] => {
    "changed": false, 
    "inventory_dir": "/root/testing/12653/service/inventory"
}
TASK [test : template dest=/tmp/12653.txt src={{item.fragments.server.src}}] ***
changed: [localhost] => (item={u'fragments': {u'server': {u'src': u'/root/testing/12653/service/inventory/../../roles/service/templates/foo.j2'}}}) => {"changed": true, "checksum": "cbe3146bbf258bd60a7f8978f1aff51567fefb8c", "dest": "/tmp/12653.txt", "gid": 0, "group": "root", "item": {"fragments": {"server": {"src": "/root/testing/12653/service/inventory/../../roles/service/templates/foo.j2"}}}, "md5sum": "c81c94446c1f06f45b35a9802fd18c9f", "mode": "0644", "owner": "root", "secontext": "unconfined_u:object_r:user_tmp_t:s0", "size": 23, "src": "/root/.ansible/tmp/ansible-tmp-1444195925.46-90037951658775/source", "state": "file", "uid": 0}
PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0   
</pre>

Can you provide any further clarification about your setup or try with the latest pull to verify you're still seeing the problem?

**Comment by jimi-c** [comment] 2015-10-13 16:17
As there has been no follow-up on this, and we were unable to reproduce the issue, we're going to go ahead and close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-10-13 16:17 UTC
Labels: needs_info, bug
