### ISSUE TITLE
v2: delegate_to stopped working

### ISSUE THREAD

**Issue by mgedmin** [ansible/ansible#12347] opened 2015-09-14 07:05 UTC
**Issue Type**: Bug Report
**Ansible Version**:

```
ansible 2.0.0 (devel f0efe1ecb0) last updated 2015/09/14 08:22:22 (GMT +300)
  lib/ansible/modules/core: (detached HEAD 4de4bd0be6) last updated 2015/09/14 08:22:31 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD ea1bd0b078) last updated 2015/09/14 08:22:31 (GMT +300)
```

**Environment**: Ubuntu
**Summary:**

I've got an Ansible playbook that works on 1.9.3 but fails on today's v2.

the failing task looks like this:

``` yaml
- name: user for accepting pushed backups on the backup buddy
  user: name="{{ backup_user }}" state=present
  delegate_to: "{{ backup_buddy }}"
  when: backup_buddy != ""
  tags: [ backups, user ]
```

I'm testing with two Vagrant machines: 'trusty' is inventory_hostname, 'precise' is the value of '{{backup_buddy}}'.  Ansible 1.9.3 produces this output:

```
TASK: [backup-pusher | user for accepting pushed backups on the backup buddy] *** 
ok: [trusty -> precise]
```

Ansible v2 fails this way:

```
TASK [backup-pusher : user for accepting pushed backups on the backup buddy] ***
fatal: [trusty]: UNREACHABLE! => {"changed": false, "msg": "ERROR! SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue", "unreachable": true}
```

If I run with `-vvv`, I also see

```
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: None
<127.0.0.1> EXEC ssh -C -tt -q -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null -o ControlPath="/home/mg/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=2222 -o IdentityFile="/home/mg/.vagrant.d/insecure_private_key" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 127.0.0.1 (umask 22 && mkdir -p "$HOME/.ansible/tmp/ansible-tmp-1442214221.49-192764384815548" && echo "$HOME/.ansible/tmp/ansible-tmp-1442214221.49-192764384815548")
```

The bug appears to be "USER: None".  1.9.3 produces this in -vvv mode:

```
TASK: [backup-pusher | user for accepting pushed backups on the backup buddy] *** 
<127.0.0.1> ESTABLISH CONNECTION FOR USER: vagrant
<127.0.0.1> REMOTE_MODULE user name="uploader" state=present
<127.0.0.1> EXEC ssh -C -tt -v -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null -o ControlPath="/home/mg/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=2222 -o IdentityFile="/home/mg/.vagrant.d/insecure_private_key" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 127.0.0.1 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1442214292.97-211965356081084 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1442214292.97-211965356081084 && echo $HOME/.ansible/tmp/ansible-tmp-1442214292.97-211965356081084'
<127.0.0.1> PUT /tmp/tmpI4aQaN TO /home/vagrant/.ansible/tmp/ansible-tmp-1442214292.97-211965356081084/user
<127.0.0.1> EXEC ssh -C -tt -v -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null -o ControlPath="/home/mg/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=2222 -o IdentityFile="/home/mg/.vagrant.d/insecure_private_key" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 127.0.0.1 /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=hyvvusnhutcrtmeznucnzvnloorzyldy] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-hyvvusnhutcrtmeznucnzvnloorzyldy; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1442214292.97-211965356081084/user; rm -rf /home/vagrant/.ansible/tmp/ansible-tmp-1442214292.97-211965356081084/ >/dev/null 2>&1'"'"''
ok: [trusty -> precise] => {"append": false, "changed": false, "comment": "", "group": 1002, "home": "/home/uploader", "move_home": false, "name": "uploader", "shell": "/bin/sh", "state": "present", "uid": 1002}
```

**Comment by halberom** [comment] 2015-09-14 21:02
related to #12053 ?

**Comment by mgedmin** [comment] 2015-09-15 05:15
Some possibly relevant details:
- `precise` is a Vagrant VM on localhost:2222 (ansible v2 gets this correct)
- the user name it should be using is specified in the $ANSIBLE_CONFIG file I use for Vagrant connections:

``` ini
[defaults]
inventory = .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory
remote_user = vagrant
private_key_file = ~/.vagrant.d/insecure_private_key
host_key_checking = false

[privilege_escalation]
become = true

[ssh_connection]
ssh_args = -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null
```
- regular playbooks against `precise` work fine, it's just `delegate_to` that has the problem.

**Comment by jimi-c** [comment] 2015-09-17 20:23
I would say this is most likely related to https://github.com/ansible/ansible/issues/12127 rather than the other suggested above.

**Comment by jimi-c** [comment] 2015-09-18 19:26
@mgedmin I believe 1f5584aa5b9d1142e67fed209bbeea1ca99fc307 should also fix this, however I'd like to make sure you've tested it before I close this as the Vagrant setup might be a bit more involved.

**Comment by mgedmin** [comment] 2015-09-21 06:38
All my tasks that involve `delegate_to` fail with current devel (3f5ea43fb8), but differently.  The UI seems to indicate no delegation taking place, so I think my tasks end up being executed on the wrong host.

Shall I file a new bug for that, or continue on this one?

**Comment by jimi-c** [comment] 2015-09-21 16:05
@mgedmin keep it here. Can you share an example that reproduces that here as well?

**Comment by mgedmin** [comment] 2015-09-22 05:59
Hm.  It looks like the output is no longer providing any indication about delegation, but delegation itself works.  Here's a playbook:

``` yml
- hosts: trusty
  gather_facts: no
  tasks:
    - command: hostname
      register: x

    - command: hostname
      delegate_to: precise
      register: y

    - debug: 'msg="direct: {{x.stdout}}, delegated: {{y.stdout}}"'
```

Here's a Vagrantfile to create the 'trusty' and 'precise' hosts:

``` ruby
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  release_names = ["precise", "trusty"]
  release_names.each do |release|
    config.vm.define release do |machine|
      machine.vm.box = "ubuntu/#{release}64"
    end
  end
  config.ssh.forward_agent = true
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "nothing.yml"
    ansible.sudo = true
    ansible.groups = {
        "vagrant" => release_names,
    }
  end
end
```

The "nothing.yml" is just there to have Vagrant create an inventory for ansible, it does nothing:

``` yml
---
- hosts: all
  gather_facts: no
```

And here's ansible.cfg I use for Vagrant testing

``` ini
[defaults]
inventory = .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory
remote_user = vagrant
private_key_file = ~/.vagrant.d/insecure_private_key
host_key_checking = false
# NB: host_key_checking prevents connection errors from changed host keys,
# but mismatched host keys disable ForwardAgent and make some git clones hang

gathering = smart
fact_caching = jsonfile
fact_caching_connection = .cache/facts/
fact_caching_timeout = 86400

[privilege_escalation]
become = true

[ssh_connection]
# I want two extra things here: agent forwarding (NB: use -o ForwardAgent=yes
# instead of -A, since these arguments are also used for scp invocations) and
# -o UserKnownHostsFile=/dev/null.  The ControlMaster/ControlPersist stuff is
# copied from the default ssh_args, since losing them would slow things down.
ssh_args = -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null
```

Given all that, here's the output of ansible 1.9.3:

```

PLAY [trusty] ***************************************************************** 

TASK: [command hostname] ****************************************************** 
changed: [trusty]

TASK: [command hostname] ****************************************************** 
changed: [trusty -> precise]

TASK: [debug msg="direct: {{x.stdout}}, delegated: {{y.stdout}}"] ************* 
ok: [trusty] => {
    "msg": "direct: vagrant-ubuntu-precise-64, delegated: vagrant-ubuntu-trusty-64"
}

PLAY RECAP ******************************************************************** 
trusty                     : ok=3    changed=2    unreachable=0    failed=0   
```

And here's the output of ansible 2.0.0 (devel ecf7d8c9ee):

```
PLAY ***************************************************************************

TASK [command] *****************************************************************
changed: [trusty]

TASK [command] *****************************************************************
changed: [trusty]

TASK [debug msg=direct: {{x.stdout}}, delegated: {{y.stdout}}] *****************
ok: [trusty] => {
    "changed": false, 
    "msg": "direct: vagrant-ubuntu-precise-64, delegated: vagrant-ubuntu-trusty-64"
}

PLAY RECAP *********************************************************************
trusty                     : ok=3    changed=2    unreachable=0    failed=0   
```

You can see how the lack of `-> precise` in the output migh've confused me.

I'll keep investigating why the delegated tasks fail in my real playbook, and file separate issues.  One is trying to rsync from host A to host B and is failing with a file not found error (but only on ansible v2); the other is installing authorized keys from host A on host B, and is showing "changed" when it shouldn't be (again, only on ansible v2).

**Comment by mgedmin** [comment] 2015-09-22 06:15
Augh, I cannot reproduce this with Vagrant.  The real playbook, when run with -vvv, indicates that the ssh'ing is happening onto inventory_hostname instead of the delegated_to host.

**Comment by mgedmin** [comment] 2015-09-22 06:18
Reproduced!   No vagrant needed, but you need to use your own machine instead of 'fridge.pov.lt':

``` yml
- hosts: localhost
  gather_facts: no
  tasks:
    - command: hostname
      register: x

    - command: hostname
      delegate_to: fridge.pov.lt
      register: y

    - debug: 'msg="direct: {{x.stdout}}, delegated: {{y.stdout}}"'
```

Ansible v2 outputs:

```

PLAY ***************************************************************************

TASK [command] *****************************************************************
changed: [localhost]

TASK [command] *****************************************************************
changed: [localhost]

TASK [debug msg=direct: {{x.stdout}}, delegated: {{y.stdout}}] *****************
ok: [localhost] => {
    "changed": false, 
    "msg": "direct: platonas, delegated: platonas"
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=0   

```

Ansible 1.9.3 outputs:

```

PLAY [localhost] ************************************************************** 

TASK: [command hostname] ****************************************************** 
changed: [localhost]

TASK: [command hostname] ****************************************************** 
changed: [localhost -> fridge.pov.lt]

TASK: [debug msg="direct: {{x.stdout}}, delegated: {{y.stdout}}"] ************* 
ok: [localhost] => {
    "msg": "direct: platonas, delegated: fridge"
}

PLAY RECAP ******************************************************************** 
localhost                  : ok=3    changed=2    unreachable=0    failed=0   

```

Looks like Ansible v2 doesn't like a full hostname in `delegate_to`, but instead of complaining, it silently ignores it.  Not nice!

**Comment by jimi-c** [comment] 2015-09-22 06:36
@mgedmin just pushed 18adfc6d1a3b0a8485c5d9310869b89d20cee13c to address the above, if you'd like to test that out.

**Comment by mgedmin** [comment] 2015-09-22 06:44
ansible 2.0.0 (devel 18adfc6d1a) almost works for me \o/

There's only one remaining error, for a task that looks like this:

``` yml
- name: copy the private key and certificate
  synchronize: mode=push src="{{ item }}" dest="{{ item }}"
  delegate_to: "{{ pov_lt_ssl_cert_source }}"
  with_items:
    - /etc/ssl/certs/AlphaSSL_intermediate.crt
    - /etc/ssl/certs/AlphaSSL_wildcard.pov.lt.crt
    - /etc/ssl/private/wildcard.pov.lt.key
```

Here `pov_lt_ssl_cert_source` evaluates to `fridge.pov.lt`, and the errors I get on v2 look like this:

```
failed: [mercury] => (item=/etc/ssl/private/wildcard.pov.lt.key) => {"cmd": "rsync --delay-updates -F --compress --dry-run --archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no' --out-format='<<CHANGED>>%i %n%L' \"/etc/ssl/private/wildcard.pov.lt.key\" \"root@[mercury]:/etc/ssl/private/wildcard.pov.lt.key\"", "failed": true, "item": "/etc/ssl/private/wildcard.pov.lt.key", "msg": "rsync: change_dir \"/etc/ssl/private\" failed: Permission denied (13)\nrsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]\n", "rc": 23}
```

My ansible.cfg specifies

```
remote_user = root
```

but the "Permission denied" error hints that ansible v2 is perhaps ssh'ing as my regular user instead of root.

**Comment by mgedmin** [comment] 2015-09-22 06:51
Uhh, ansible-playbook -vvv shows this for the above:

```
ESTABLISH LOCAL CONNECTION FOR USER: root
mercury EXEC mkdir -p "$HOME/.ansible/tmp/ansible-tmp-1442904537.66-66196634415896" && echo "$HOME/.ansible/tmp/ansible-tmp-1442904537.66-66196634415896"
mercury PUT /tmp/tmpkLTB8y TO /home/mg/.ansible/tmp/ansible-tmp-1442904537.66-66196634415896/synchronize
mercury EXEC LANG=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /home/mg/.venv/bin/python /home/mg/.ansible/tmp/ansible-tmp-1442904537.66-66196634415896/synchronize; rm -rf "/home/mg/.ansible/tmp/ansible-tmp-1442904537.66-66196634415896/" > /dev/null 2>&1
```

I don't see any SSH lines.  Maybe it's specific to the synchronize module?

**Comment by mgedmin** [comment] 2015-09-22 06:54
A `debug: msg="the source is {{ pov_lt_ssl_cert_source }}"` confirms that `pov_lt_ssl_cert_source` is `fridge` (just the short name this time instead of the full hostname, like I thought; my ~/.ssh/config aliases it to fridge.pov.lt).

**Comment by mgedmin** [comment] 2015-09-22 07:03
Here's ansible 1.9.3 -vvv output:

```
<fridge> ESTABLISH CONNECTION FOR USER: root
<fridge> EXEC ssh -C -tt -v -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/mg/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 fridge /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1442905331.44-4373358555971 && echo $HOME/.ansible/tmp/ansible-tmp-1442905331.44-4373358555971'
<fridge> PUT /tmp/tmppO9vBW TO /root/.ansible/tmp/ansible-tmp-1442905331.44-4373358555971/synchronize
<fridge> EXEC ssh -C -tt -v -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/mg/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 fridge /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1442905331.44-4373358555971/synchronize; rm -rf /root/.ansible/tmp/ansible-tmp-1442905331.44-4373358555971/ >/dev/null 2>&1'
ok: [mercury -> fridge] => (item=/etc/ssl/certs/AlphaSSL_intermediate.crt) => {"changed": false, "cmd": "rsync --delay-updates -F --compress --dry-run --archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no' --out-format='<<CHANGED>>%i %n%L' \"/etc/ssl/certs/AlphaSSL_intermediate.crt\" \"root@mercury:/etc/ssl/certs/AlphaSSL_intermediate.crt\"", "item": "/etc/ssl/certs/AlphaSSL_intermediate.crt", "msg": "", "rc": 0, "stdout_lines": []}
```

**Comment by jimi-c** [comment] 2015-09-22 07:10
Ok, so it looks like the above is specific to the synchronize module, which has special considerations. Please open a new issue for this, and we'll close this one.

Thanks!

**Closed as completed by jimi-c** 2015-09-22 07:10 UTC
Labels: P2, bug
