### ISSUE TITLE
SELinux + overlayfs + copy module failed with "invalid selinux context"

### ISSUE THREAD

**Issue by TristanCacqueray** [ansible/ansible#10930] opened 2015-05-06 14:27 UTC
Hi there,

it seems very related to #7009, but this time with an overlayfs mountpoint.
The support for SELinux context within overlayfs seems on the way, but this issue might happen again with others fs anyway.

Could we have a parameter in the copy module to manually prevent the setting of these context ?

Steps to reproduce (using updated fedora 21):
$ sudo mkdir -p /var/lib/overlayfs/{upper,lower,work,mountpoint}
$ sudo mount -o workdir=/var/lib/overlayfs/work,upperdir=/var/lib/overlayfs/upper,lowerdir=/var/lib/overlayfs/lower/ -t overlay overlayfs /var/lib/overlayfs/mountpoint/
$ sudo ansible localhost -m copy -a "src=/etc/fstab dest=/var/lib/overlayfs/mountpoint/fstab"
localhost | FAILED >> {
[...]
"msg": "invalid selinux context",
[...]
}

**Comment by bcoca** [comment] 2015-05-12 02:58
closing as dupe of #10931

**Closed as completed by bcoca** 2015-05-12 02:58 UTC
Labels: bug
