### ISSUE TITLE
unarchive module does not clean up

### ISSUE THREAD

**Issue by profhase** [ansible/ansible#14078] opened 2016-01-22 15:25 UTC
##### Issue Type:

 Bug Report
##### Ansible Version:

2.0.0.1
##### Ansible Configuration:

[defaults]
host_key_checking = False
hostfile = inventory/test
pipelining = True
##### Environment:

From Ubuntu 14.04 to sles12
##### Summary:

After Running the `unarchive` module the `$HOME/.ansible` is not cleaned up
##### Steps To Reproduce:

```
- name: extract large file
  unarchive:
  src=large_file.tar.gz
  dest=/tmp
```
##### Expected Results:

`$HOME/.ansible` on target machine is small after playbook has finished
##### Actual Results:

`$HOME/.ansible` is about the size of the archive extracted

**Comment by shirou** [comment] 2016-03-03 13:06
same here.  It's not occurred at `1.9.4`. And it seems does not related to `ANSIBLE_KEEP_REMOTE_FILES`.

**Comment by dagwieers** [comment] 2016-03-30 13:59
This is a duplicate of #14917.

**Comment by bcoca** [comment] 2016-03-30 15:28
closing as dupe

**Closed as completed by bcoca** 2016-03-30 15:28 UTC
Labels: m:unarchive, bug
