### ISSUE TITLE
wait_for ignores timeout when using file=present if the path doesn't immediately exist.

### ISSUE THREAD

**Issue by specialkevin** [ansible/ansible#8527] opened 2014-08-08 19:20 UTC
##### Issue Type:

"Bug Report"
##### Ansible Version:

ansible 1.7
##### Environment:

"N/A"
##### Summary:

The [fix](https://github.com/ansible/ansible/commit/6efc8008daa8bb70ccbf51df0ff14f81843fc59e) in the wait_for module to fail fast on missing path ignores the timeout value when it is passed. If this is the expected behavior it changed between 1.6 and 1.7 without a documentation change.
##### Steps To Reproduce:

This can be reproduced by using wait_for to wait until a file is created by an outside script. I was using this during a postgres recovery that creates a recovery.done upon completion. Below is the task that I used. Without any changes it worked in 1.6 but broke in 1.7.
- wait_for: path="{{pg_data}}/recovery.done" state=present timeout=1800
##### Expected Results:

Previous behavior would wait to error out about a missing path until the timeout elapsed. I would expect the task to fail immediately if the path can't be found and a timeout value isn't passed.
##### Actual Results:

The task immediately errors out stating that it can't stat the path irregardless of a timeout value or not.

**Comment by jimi-c** [comment] 2014-08-12 21:07
Hi @specialkevin. This would seem to be an issue with the permissions to the file, rather than the file not being present at the time. The patch you reference specifically checks for the error code, which is 2 when the file is not found. I definitely think we should show an appropriate message if the error code is 13 (permission denied) to make the problem clearer.

Can you confirm that the playbook user has access to the path you're checking with the wait_for?

**Comment by jimi-c** [comment] 2014-08-12 21:12
@specialkevin I have also created the above commit, which gives a more explicit error when the error is related to permissions on the target path, if you'd like to test it.

**Comment by specialkevin** [comment] 2014-08-12 21:30
@jimi-c I will try out that commit when I get a chance. The playbook does have access to the path. The file permissions are the same for the path of recovery.conf which works if I use wait_for until that file is absent.

**Comment by sivel** [comment] 2014-08-12 21:32
Of interest here, see #8550 which addressed exactly the issue mentioned here.

**Comment by specialkevin** [comment] 2014-08-12 21:34
@sivel I will check that out when I get a chance. It sounds like it might be the same problem I am running into.

**Comment by jimi-c** [comment] 2014-08-12 21:59
Ahh thanks @sivel, I had not seen that was merged in, and would explain why I cannot reproduce this now.

**Comment by jimi-c** [comment] 2014-08-18 18:24
# Closing This Ticket

Hi!

We believe the above commit has resolved this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2014-08-18 18:24 UTC
Labels: needs_info, P1, bug
