### ISSUE TITLE
Combination of include_role and when condition

### ISSUE THREAD

**Issue by andreaskumlehn** [ansible/ansible#19598] opened 2016-12-21 11:45 UTC
The following combination of `include_role` and `when` condition in one of my roles results in the error message posted below.

`myrole/tasks/main.yml`:

     ---
     - include_role: name=mydebug
       when: project == "some-project"

Error:

    fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check 'p' failed. The error was: error while evaluating conditional (p): 'p' is undefined\n\nThe error appears to have been in '/opt/ansible/roles/proj-conf/tasks/main.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- include_role: name=mydebug\n  ^ here\n"}

Without the condition, the role runs fine. Any clue what's causing this behavior?

For information:
    ansible 2.2.0.0

The `mydebug` role is a simple wrapper around the predefined `debug` role.

`mydebug/tasks/main.yml`:

    ---
    - debug:
      msg: "test"

My playbook:

    ---
    - hosts: '{{ target }}'
      roles:
        - { role: myrole, project: '{{ project }}'}

**Comment by bcoca** [comment] 2016-12-21 15:19
duplicate of #19472

**Closed as completed by bcoca** 2016-12-21 15:19 UTC
Labels: affects_2.3
