### ISSUE TITLE
2.3 regression: ansible-vault does not correctly use '-' argument for stdout

### ISSUE THREAD

**Issue by gumho** [ansible/ansible#24383] opened 2017-05-08 21:44 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible-vault

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
Have reproduced this on latest OS X and CentOS 6.8 Docker image

##### SUMMARY
ansible-vault is no longer using the `-` argument for --output. Based on the output, it seems like it thinks the `-` is the literal name of the output file.

##### STEPS TO REPRODUCE
echo myPassword | ansible-vault encrypt  --output=-

##### EXPECTED RESULTS
On < 2.3, the following output is seen:

```
Vault password: 
$ANSIBLE_VAULT;1.1;AES256
32663537353138656134386139666466306466316530653432353734386632343531663132636539
3635303239373734303161613630663163613264303730350a633466376433363934356534326464
32663736393037313830316336363339633235383464313030653264613833386664346130363934
3234346139656432300a633738383737623162313930663462636665353332376265633361356336
6565
Encryption successful
```

##### ACTUAL RESULTS
On 2.3, the following output is seen:

```
New Vault password: 
Confirm New Vault password: 
ERROR! [Errno 2] No such file or directory: '/Users/rchsu/cwd/-'
```

**Comment by sivel** [comment] 2017-05-08 21:46
Closing this as a duplicate of the already resolved https://github.com/ansible/ansible/pull/23583 that will be included in an upcoming 2.3.1 release.

**Closed as completed by sivel** 2017-05-08 21:46 UTC
