### ISSUE TITLE
Role level lookup_plugins

### ISSUE THREAD

**Issue by michaeljs1990** [ansible/ansible#11685] opened 2015-07-21 21:17 UTC
I was making an ansible-galaxy role today and when placing the lookup_folder plugin at the same level as the rest of the folders and then using it it returns that it can't find the plugin. Do we have anyway to use lookup_plugins at a role level without forcing uses to manually add it to there playbook?

Here is the repo in question. Master is how i got it to work for testing that the lookup_plugins folder only works when at the same level as the playbook https://github.com/nowait-tools/ansible-rabbitmq the branch galaxy test is the one that fails.

**Comment by sky-shiny** [comment] 2015-07-24 09:45
+1

**Comment by jimi-c** [comment] 2015-07-25 13:08
I cannot reproduce this on the current devel branch:

<pre>
# cat test.yml 
- hosts: localhost
  gather_facts: no
  roles:
  - test
# cat roles/test/lookup_plugins/include_test.py
from __future__ import (absolute_import, division)
__metaclass__ = type
import os
from ansible.plugins.lookup import LookupBase
class LookupModule(LookupBase):
    def run(self, terms, variables, **kwargs):
        if isinstance(terms, basestring):
            terms = [ terms ]
        ret = []
        for term in terms:
            ret.append(term.upper())
        return ret
# cat roles/test/defaults/main.yml
foo: this
# cat roles/test/tasks/main.yml
- debug: msg="the test filter makes {{lookup('include_test', foo)}} bigger!"
</pre>

Can you let us know if you're still seeing this on devel? Otherwise we'll close this issue.

Thanks!

**Comment by jimi-c** [comment] 2015-07-25 13:10
Forgot to include the output of the above:

<pre>
PLAY ****************************************************************************
TASK [test : debug msg=the test filter makes {{lookup('include_test', foo)}} bigger!] ***
ok: [localhost] => {
    "changed": false, 
    "msg": "the test filter makes THIS bigger!"
}
PLAY RECAP **********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
</pre>

**Comment by sky-shiny** [comment] 2015-07-25 14:20
I'm still seeing this on devel with my existing plugins.   So, changes to plugin loading is not backwards compatible.  These are the changes required to current lookup plugins to get them to load:

```
+from __future__ import (absolute_import, division)
+__metaclass__ = type

+from ansible.plugins.lookup import LookupBase
-class LookupModule(object):
+class LookupModule(LookupBase):

-    def __init__(self, basedir=None, **kwargs):
-        self.basedir = basedir
```

**Comment by bcoca** [comment] 2015-07-25 14:26
v1 lookup plugins don't work in v2, there are some changes needed (also callbacks and connection plugins).  Other plugins should not need to change, so modules will still work (aside from 'command' but we took care of that already).

There will be a howto that explains how to make plugins v1 and v2 compatible.

**Comment by jimi-c** [comment] 2015-07-25 17:10
Ah hah, yes, thought this might be the case. As @bcoca mentioned, we will be writing up some documentation on how to make certain plugins with API changes cross-version compatible. A rough example of this is here: https://gist.github.com/jimi-c/5ceb4dc6cfedea4b3a87, though I would like to create a better example showing less code duplication.

We'll continue to hold this open, until such a time as that documentation is created.

Thanks!

**Comment by michaeljs1990** [comment] 2015-07-25 17:35
Thanks for the quick response. I was able to switch my lookup to a module for the time being which worked out well as a quick fix.

**Comment by jimi-c** [comment] 2015-09-25 16:20
cc'ing @drybjed, who has been doing some stuff along these lines for his DebOps work, so perhaps it's just time to document what he's doing.

**Comment by drybjed** [comment] 2015-09-25 16:49
I've based changes of the project's [lookup plugins](https://github.com/debops/debops-playbooks/tree/master/playbooks/lookup_plugins) on what @jimi-c gave me, but the modifications seem to be incomplete. On Ansible v1 plugins work as expected, on Ansible v2 they also work, but in specific instances, for example when I run roles with any tags that skip use of the plugins I get:

```
TASK [debops.auth : DebOps pre_tasks hook] *************************************
/home/drybjed/.local/share/debops/debops-playbooks/playbooks/lookup_plugins/task_src.py:31: RuntimeWarning: Parent module 'ansible.plugins.lookup' not fou
nd while handling absolute import
  import os
/home/drybjed/.local/share/debops/debops-playbooks/playbooks/lookup_plugins/task_src.py:33: RuntimeWarning: Parent module 'ansible.plugins.lookup' not fou
nd while handling absolute import
  from debops import *
/home/drybjed/.local/share/debops/debops-playbooks/playbooks/lookup_plugins/task_src.py:34: RuntimeWarning: Parent module 'ansible.plugins.lookup' not fou
nd while handling absolute import
  from debops.cmds import *
/home/drybjed/.local/share/debops/debops-playbooks/playbooks/lookup_plugins/task_src.py:42: RuntimeWarning: Parent module 'ansible.plugins.lookup' not fou
nd while handling absolute import
  from distutils.version import LooseVersion
/home/drybjed/.local/share/debops/debops-playbooks/playbooks/lookup_plugins/task_src.py:43: RuntimeWarning: Parent module 'ansible.plugins.lookup' not fou
nd while handling absolute import
  from ansible import __version__ as __ansible_version__
/home/drybjed/.local/share/debops/debops-playbooks/playbooks/lookup_plugins/task_src.py:91: RuntimeWarning: Parent module 'ansible.plugins.lookup' not fou
nd while handling absolute import
  from ansible.errors import AnsibleError
/home/drybjed/.local/share/debops/debops-playbooks/playbooks/lookup_plugins/task_src.py:92: RuntimeWarning: Parent module 'ansible.plugins.lookup' not fou
nd while handling absolute import
  from ansible.plugins.lookup import LookupBase
```

The task is still skipped and Ansible goes along fine, it just shows up that traceback in the output. @jimi-c any suggestions how to fix this?

**Comment by jimi-c** [comment] 2015-09-26 12:40
Hrm, sounds like a python pathing issue, where it's finding a directory that matches the import path relative to your lookup plugins, but that's overriding the site-packages path. Kind of guessing here, without seeing your full setup.

**Comment by amenonsen** [comment] 2015-11-19 05:15
@drybjed any further details to share here?

**Comment by drybjed** [comment] 2015-11-19 11:23
@amenonsen I don't think so. In current Ansible `devel` branch above errors don't show up anymore, I guess whatever caused them to show up was either removed or fixed. Other than that, the lookup plugins work as expected in Ansible v1 and Ansible v2, seems like a good method to write them. The common code could probably be moved to a separate function to make everything cleaner, but I'm not that good in Python.

**Comment by jimi-c** [comment] 2016-06-27 21:52
Since there have been no major updates on this in over 6 months, and the window for those writing lookups for the 1.x series is mostly closed, we're going to go ahead and close this now.

If there are any further issues regarding this, please let us know. Thanks!

**Closed as completed by jimi-c** 2016-06-27 21:52 UTC
Labels: bug, docs
