### ISSUE TITLE
Inconsistent behavior with provided variable from ansible-playbook cli

### ISSUE THREAD

**Issue by gaelL** [ansible/ansible#23485] opened 2017-04-11 08:45 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

`ansible`

`(when condition on a task)`

##### ANSIBLE VERSION

```
ansible --version
ansible 2.2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
Nothing particular

##### OS / ENVIRONMENT

```
Debian GNU/Linux 9 \n \l
```

##### SUMMARY

Provide a boolean variable from `ansible-playbook` have an inconsistend behavior when we are using it in a `when` condition with a single or multiple conditions.

##### STEPS TO REPRODUCE

```
cat test.yml
- hosts: localhost
  gather_facts: no
  tasks:
    - debug: var=foo
      when: true and foo

ansible-playbook   -e foo=false test.yml
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [debug] *******************************************************************
ok: [localhost] => {
    "foo": "false"
}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```

```
cat test.yml
- hosts: localhost
  gather_facts: no
  tasks:
    - debug: var=foo
      when: foo

ansible-playbook   -e foo=false test.yml
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [debug] *******************************************************************
skipping: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=0   
```
##### EXPECTED RESULTS

Expecting to have a similar behavior with a `when` and a single condition vs multiple condition (eg put `|bool` in both case)

##### ACTUAL RESULTS

With a single condition, the variable behavior looks like a boolean but in a multiple condition, we can have unexpected results.

**Comment by nrwahl2** [comment] 2017-09-02 17:29
To clarify, this seems to be happening ONLY when passing in a variable from the CLI. Wonder if it hasn't been interpolated at the time the condition is evaluated and it's being evaluated as string 'foo'? That doesn't completely add up either, since adding another debug task before this one led to the same results.
```
[reid@laptop ~/git]$ cat playbook.yml 
---
- hosts: localhost
  gather_facts: no
  vars:
    # foo: False
    # bar: False
  tasks:
  - debug: var=foo
    when: foo and bar
[reid@laptop ~/git]$ ansible-playbook playbook.yml -i hosts.ini -e 'foo=false bar=false'

PLAY [localhost] **************************************************************************************************************************************************************************************************

TASK [debug] ******************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "foo": "false"
}

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   

[reid@laptop ~/git]$ vim playbook.yml 
[reid@laptop ~/git]$ cat playbook.yml 
---
- hosts: localhost
  gather_facts: no
  vars:
    foo: False
    bar: False
  tasks:
  - debug: var=foo
    when: foo and bar
[reid@laptop ~/git]$ ansible-playbook playbook.yml -i hosts.ini

PLAY [localhost] **************************************************************************************************************************************************************************************************

TASK [debug] ******************************************************************************************************************************************************************************************************
skipping: [localhost]

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=0  
```

```
[reid@laptop ~/git]$ cat playbook.yml 
---
- hosts: localhost
  gather_facts: no
  vars:
    # foo: False
  tasks:
  - debug: var=foo
    when: foo and True
[reid@laptop ~/git]$ ansible-playbook playbook.yml -i hosts.ini -e 'foo=false'

PLAY [localhost] **************************************************************************************************************************************************************************************************

TASK [debug] ******************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "foo": "false"
}

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   

[reid@laptop ~/git]$ vim playbook.yml 
[reid@laptop ~/git]$ cat playbook.yml 
---
- hosts: localhost
  gather_facts: no
  vars:
    foo: False
  tasks:
  - debug: var=foo
    when: foo and True
[reid@laptop ~/git]$ ansible-playbook playbook.yml -i hosts.ini

PLAY [localhost] **************************************************************************************************************************************************************************************************

TASK [debug] ******************************************************************************************************************************************************************************************************
skipping: [localhost]

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=0   
```

**Comment by nrwahl2** [comment] 2017-09-03 20:05
After getting more familiar with the playbook debugger... it's Unicode translation.

Still haven't pinned down exact root cause.
```
[reid@laptop ~/git]$ ansible-playbook playbook.yml -i hosts.ini -e foo=False

PLAY [localhost] **************************************************************************************************************************************************************************************************

TASK [debug] ******************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "foo": false
}

TASK [debug] ******************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "foo": false
}

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   

[reid@laptop ~/git]$ ansible-playbook playbook.yml -i hosts.ini -e u'foo'=False

PLAY [localhost] **************************************************************************************************************************************************************************************************

TASK [debug] ******************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "foo": false
}

TASK [debug] ******************************************************************************************************************************************************************************************************
skipping: [localhost]

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   

```

**Comment by nrwahl2** [comment] 2017-09-03 20:55
On the right track, but not quite. It's treating 'False' as a unicode string rather than a boolean value. Inspecting the playbook debugger when using a var `foo: False` in the playbook, we see this:
```
 u'foo': False,
```
And when overriding the playbook var with a CLI extra_var:
```
 u'foo': u'False',
```

`playbook/conditional.py` avoids this situation for a single boolean, but if anything accompanies it (such as an `and True`), it's treated as a string:
```
        try:
            # this allows for direct boolean assignments to conditionals "when: False"
            if isinstance(self.when, bool):
                return self.when

            for conditional in self.when:
                if not self._check_conditional(conditional, templar, all_vars):
                    return False
```

**Comment by nrwahl2** [comment] 2017-09-03 22:38
@gaelL : I've submitted PR #28976 and working on the build failures. Hopefully it will be fixed up and reviewed soon as a bugfix since we're nearing the 2.4 stable rollout.

**Comment by nrwahl2** [comment] 2017-09-17 17:58
Sooooo I'm kind of upset with myself for just now finding this on the Variables documentation page:

>    Note

>    Values passed in using the key=value syntax are interpreted as strings. Use the JSON format if you need to pass in anything that shouldn’t be a string (Booleans, integers, floats, lists etc).

It may still be worth adding this feature if/when it works to everyone's satisfaction, so that we have behavior that's more consistent with what a user would reasonably expect. However, JSON is a perfectly valid way to specify type and I'm okay if we want to let it be in favor of JSON for this role.

**Comment by samdoran** [comment] 2019-04-26 15:27
Closing per above explanation in documentation.

**Closed as completed by samdoran** 2019-04-26 15:27 UTC
Labels: affects_2.2, c:playbook/task, support:core, bug
