### ISSUE TITLE
Trailing newline added to stdout

### ISSUE THREAD

**Issue by jcgarrido** [ansible/ansible#23730] opened 2017-04-19 08:51 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

stdout from script module in Windows

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /home/juancarlos/shared/Git/bitbucket/edosdp-ansible-roles/pbotools/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.6.6 (r266:84292, Aug 18 2016, 14:53:48) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
```

##### CONFIGURATION

```
[defaults]
host_key_checking = False

log_path = /home/juancarlos/shared/ansible.log
```

##### OS / ENVIRONMENT

Running Ansible from CentOS 6.8
Managing Windows 2012 servers

##### SUMMARY

Ansible 2.3.0 is adding a traling newline to stdout, and this is making some string comparisons fail.

This does not happen with Ansible 2.2.1, because that version does not append newline to stdout. 

##### STEPS TO REPRODUCE

Use the script module to run a powershell script in Windows and register the output. For example:

```
- name: Check version installed
  script: ./powershell_scripts/compareVersion.ps1 "{{ guid[tool] }}" "{{ installer_version | default('0.0') }}" -executionpolicy remotesigned
  register: check_version

```

##### EXPECTED RESULTS

With Ansible 2.2.1 we don't have a trailing newline in stdout:

```
2017-04-19 10:03:59,523 p=5261 u=juancarlos |  ok: [eselivrnd248] => {
    "check_version": {
        "changed": true, 
        "rc": 0, 
        "stderr": "", 
        "stdout": "notinstalled", 
        "stdout_lines": [
            "notinstalled"
        ]
    }
} 

```
##### ACTUAL RESULTS

With Ansible 2.3.0 we have a trailing newline in stdout:

```
2017-04-19 10:15:49,485 p=5592 u=juancarlos |  ok: [eselivrnd248] => {
    "changed": false, 
    "check_version": {
        "changed": true, 
        "rc": 0, 
        "stderr": "", 
        "stdout": "notinstalled\r\n", 
        "stdout_lines": [
            "notinstalled"
        ]
    }
}

```

**Comment by gundalow** [comment] 2017-04-19 14:34
@jcgarrido Thanks for this.

Marking as 2.3 blocking as it's a regression

**Comment by jborean93** [comment] 2017-09-29 02:23
I believe this change was made to align the script module with `win_command` and `win_shell`. It could also potentially be due to the change in the exec wrapper but I don't believe we want to revert back to the older behaviour. If you still wish to compare string without the last `\r\n` you can always do `{{result.stdout_lines|join("\r\n")}}` to achieve the same result.

Going to close the ticket as this is the intended behaviour.

**Closed as completed by jborean93** 2017-09-29 02:23 UTC
Labels: windows, affects_2.3, module, support:core, bug
