### ISSUE TITLE
ansible.builtin.include_tasks has not the same behavior as include_tasks

### ISSUE THREAD

**Issue by sylvainOL** [ansible/ansible#72082] opened 2020-10-02 15:34 UTC
##### SUMMARY
when using "FQCN" with ansible, behavior for include_tasks (at least) is not the same anymore

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible.builtin

##### ANSIBLE VERSION
I also had the issue with 2.10
```
ansible 2.9.1
  config file = /Users/sylvain/.ansible.cfg
  configured module search path = ['/Users/sylvain/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/sylvain/.pyenv/versions/3.7.5/envs/ansible/lib/python3.7/site-packages/ansible
  executable location = /Users/sylvain/.pyenv/versions/ansible/bin/ansible
  python version = 3.7.5 (default, Nov  6 2019, 08:38:28) [Clang 11.0.0 (clang-1100.0.33.8)]
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/Users/xxx/.ansible.cfg) = True
DEFAULT_FORKS(/Users/xxx/.ansible.cfg) = 50
DEFAULT_LOAD_CALLBACK_PLUGINS(/Users/xxx/.ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/Users/xxx/.ansible.cfg) = yaml
DEFAULT_VAULT_PASSWORD_FILE(/Users/xxx/.ansible.cfg) = /Users/sylvain/.local/.vault
HOST_KEY_CHECKING(/Users/xxx/.ansible.cfg) = False
RETRY_FILES_ENABLED(/Users/xxx/.ansible.cfg) = False
```

##### OS / ENVIRONMENT
mac OS but also on Linux

##### STEPS TO REPRODUCE
create three yml files (`failed.yml`, `working.yml` and `other.yml` in my case)

failed.yml:
```yaml
- hosts: localhost
  gather_facts: false
  tasks:
    - ansible.builtin.include_tasks: other.yml
```

working.yml:
```yaml
- hosts: localhost
  gather_facts: false
  tasks:
    - include_tasks: other.yml
```

other.yml:
```yaml
---
- debug: msg="hello"
```

##### EXPECTED RESULTS
same behavior between `failed.yml`and `working.yml`

here's output when launching `working.yml`:

```
PLAY [localhost] *******************************************************************************************************************************************************************************************************************************************************

TASK [include_tasks] ***************************************************************************************************************************************************************************************************************************************************
included: /tmp/other.yml for localhost

TASK [debug] ***********************************************************************************************************************************************************************************************************************************************************
ok: [localhost] =>
  msg: hello

PLAY RECAP *************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

##### ACTUAL RESULTS
here's the output of `failed.yml`
```
ERROR! this task 'ansible.builtin.include_tasks' has extra params, which is only allowed in the following modules: win_command, include, include_tasks, shell, add_host, include_vars, meta, import_tasks, import_role, set_fact, win_shell, command, raw, script, group_by, include_role

The error appears to be in '/tmp/test.yaml': line 4, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - ansible.builtin.include_tasks: other.yml
      ^ here
```

**Comment by sivel** [comment] 2020-10-02 15:36
Duplicate of https://github.com/ansible/ansible/issues/71817

**Closed as completed by sivel** 2020-10-02 15:36 UTC

**Comment by sylvainOL** [comment] 2020-10-02 15:38
you're right, it's a duplicate, I was looking for already reported but couldn't find sorry
