### ISSUE TITLE
assign to a vars dictionary itself genereate a recursive loop error

### ISSUE THREAD

**Issue by Raffaello** [ansible/ansible#72647] opened 2020-11-17 16:02 UTC
##### SUMMARY

if overriding to varA the same varA dictionary, it is generating a recursive error loop and then it could be considered a bug as it should be possible to assign to a var itself, right? (generating a warning if you like)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible variable assignment. 

##### ANSIBLE VERSION

```yaml
---
defaultRoleAVarsDict:
  a: "a"
  b: "c"
---
roles:
  role: roleA
  vars:
    defaultRoleAVarsDict: "{{ defaultRoleAVarsDict }}" # ok, it is silly but pipe with a filter like combine would make more sense
```

##### CONFIGURATION

all default
```paste below

```

##### OS / ENVIRONMENT

fedora32

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

should assign the variable to itself, at least generating a warning as a redundant operation (warning optional)

##### ACTUAL RESULTS

error recursive loop detected

```paste below
recursive loop detected
```

**Comment by Raffaello** [comment] 2020-11-17 16:03
reported as a feature to use it looking ahead to the removal of `hash_behavior=merge`
https://github.com/ansible/ansible/issues/72646

**Comment by jborean93** [comment] 2020-11-19 19:10
Duplicate of https://github.com/ansible/ansible/issues/72646, will be discussed further there.

**Closed as completed by jborean93** 2020-11-19 19:10 UTC
Labels: support:core, bug, affects_2.11
