### ISSUE TITLE
Default Filter does not work in /vars/*.yml Files

### ISSUE THREAD

**Issue by alwinmark** [ansible/ansible#12470] opened 2015-09-22 11:36 UTC
Hi,

when I try doing sth like for example in a /vars/main.yml:

``` yaml
variable: {{ var | DEFAULT('Foo') }}
```

and run my playbook with `ansible-playbook -e "var=Bar"` then even though I set the variable to Bar it will be defaultet to Foo.

```
ansible 1.8.4
  configured module search path = None
```

This is working in ansible 1.6.10

**Comment by jimi-c** [comment] 2015-09-22 12:15
Hi @alwinmark, I've just confirmed this works on both 1.9.x and 2.0 (devel). Per our normal policy of closing issues when they're resolved in the devel branch, I'm going to go ahead and close this now.

One thing to note, on both of the above versions Ansible returns an error saying DEFAULT is not a valid filter (they are case-sensitive), but changing it to simply `default` works.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-09-22 12:15 UTC
