### ISSUE TITLE
Ansible fails to lookup entries of dict

### ISSUE THREAD

**Issue by john-dodson** [ansible/ansible#12700] opened 2015-10-09 22:03 UTC
**Issue Type:**

Bug Report

**Ansible Version:**

Ansible devel

**Ansible Configuration:**

Default configuration

**Environment:**

Debian, Ubuntu

**Summary:**

Ansible fails with the following error when trying to access data from a dict.

TASK [Launch instance] *********************************************************
changed: [localhost -> localhost]

TASK [Add new instance to host group] ******************************************
 [WARNING]: Error when using <bound method CallbackModule.v2_runner_on_ok of <ansible.plugins.callback.default.CallbackModule object at 0x7f5fd8979c90>>:
global name 'get' is not defined

**Example Playbook:**
- name: Create Server
&nbsp;&nbsp;hosts: localhost
&nbsp;&nbsp;connection: local
&nbsp;&nbsp;gather_facts: False
&nbsp;&nbsp;vars_files:
&nbsp;&nbsp;&nbsp;&nbsp;- vars/credentials.yml
&nbsp;&nbsp;&nbsp;&nbsp;- vars/ec2.yml
&nbsp;&nbsp;tasks:
&nbsp;&nbsp;&nbsp;&nbsp;- name: Launch instance
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ec2:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;key_name: "{{ keypair }}"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;group: "{{ security_group }}"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;instance_type: "{{ instance_type }}"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;image: "{{ ami }}"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;wait: true
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;region: "{{ region }}"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;vpc_subnet_id: "{{ subnet }}"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;assign_public_ip: yes
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;aws_access_key: "{{ access_key_id }}"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;aws_secret_key: "{{ secret_access_key }}"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;register: ec2
&nbsp;&nbsp;&nbsp;&nbsp;- name: Add new instance to host group
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;add_host: hostname={{ item.public_ip }} groupname=launched
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;with_items: ec2.instances

**Comment by abadger** [comment] 2015-10-16 20:58
Hi, the error looks like ec2.instances is not a list of dictionaries.  Could you show us what it is?  perhaps with

```
- debug: var=ec2.instances
```

**Comment by abadger** [comment] 2015-10-23 21:22
I'm unable to reproduce here.  I do notice that the fragment of error message that you're getting: "Error when using" is probably happening when callbacks are being invoked.  Do you have any special callbacks enabled perhaps?

**Comment by abadger** [comment] 2015-10-27 16:14
Without more information we won't be able to debug this, marking pending_closure.  If anyone can provide the requested information we can take a look at what might be going on otherwise I'll close this in a few days.

**Comment by abadger** [comment] 2015-10-29 17:27
Closing issue.  Feel free to open a new one if it happens again and you can help us reproduce it.

**Closed as completed by abadger** 2015-10-29 17:27 UTC
Labels: needs_info, pending_action, bug
