### ISSUE TITLE
Dynamic Inventory + static group_vars -> not loading group_vars

### ISSUE THREAD

**Issue by sirkubax** [ansible/ansible#11238] opened 2015-06-11 13:33 UTC
Related issues:
https://github.com/ansible/ansible/issues/8605
https://github.com/ansible/ansible/issues/6563

ansible 1.9.1

I'd like to load some variables for newly created AWS EC2 instances from my static inventory.
(I would like to define ansible_ssh_user for a dynamic group)

I do create some EC2 instances with a playbook (as in basic example):

```
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:

    - name: Provision a set of instances
      ec2:
          region: eu-central-1
          key_name: kuba_aws
          group: default
          instance_type: t2.micro
          image: ami-accff2b1
          vpc_subnet_id: subnet-xxxxxx
          wait: yes
          exact_count: 3
          count_tag:
             Name: Demo
          instance_tags:
             Name: Demo
             test_tag: Demo
      register: ec2
```

I do have static group_vars defined:
**group_vars/tag_Name_Demo**

```
cat group_vars/tag_Name_Demo  #or group_vars/ec2_tag_Name_Demo  ??

---
ansible_ssh_private_key_file: ~/.ssh/mykey
ansible_ssh_user: ubuntu
```

But when I lunch:
**ansible -m ping tag_Name_Demo -vvv**
<172.16.1.12> ESTABLISH CONNECTION FOR USER: **xxxxx**

So the files are not read. I thought that the inventories are not combined, so I did create directory combining static and dynamic inventory, but no luck

```
ls ~/inv/
ec2.py  inventory-qa.ini
```

**ansible -m ping tag_Name_Demo -vvv -i ~/inv/**
<172.16.1.12> ESTABLISH CONNECTION FOR USER: xxxxx

I was sure, that ansible would match group_vars from static inventory and assign proper variables for groups in dynamic_inventory ...
Any suggestions - probably there is some step missing? Or based on provided issues (top of the post), this is some bug?

offtopic:
http://grokbase.com/t/gg/ansible-project/149bqh8m05/setting-host-vars-programmatically-with-dynamic-inventory

**Comment by sirkubax** [comment] 2015-06-11 13:37
quick-test command

**ansible  tag_Name_Demo -vvvvv -m debug -a var=ansible_ssh_user**
172.16.1.12 | success >> {
    "var": {
        "ansible_ssh_user": "xxxxx"
    }
}

(ansible_ssh_user should be: ubuntu)

**Comment by bcoca** [comment] 2015-06-11 13:41
does the static inventory contain a tag_Name_Demo group?

**Comment by sirkubax** [comment] 2015-06-11 13:55
I think I've found the answer:

In my case, dir structure is (for easy update it is in virtualenv)

```
.
├── bin
│   ├── init_env
│   ├── list_instances.py
│   ├── setup-env
│   └── setup-env-aws
├── env
│   ├── bin/
│   ├── include/
│   ├── lib/
│   └── local/
├── etc
│   ├── ansible.cfg
│   ├── group_vars/
│   ├── host_vars/
│   ├── inventory.ini
│   ├── playbooks/
├── lib
│   ├── module_common.py
│   └── modules/
└── opt
    ├── ec2.ini
    └── ec2.py


```

since my 
ANSIBLE_HOSTS=/home/xxxxx/ansible/opt/ec2.py
the host_vars and group_vars are expected to be in opt/ subdirs

so, after moving the group_vars and host_vars dir into opt/ dir where ANSIBLE_HOSTS script is located:

```
├── opt
│   ├── ec2.ini
│   ├── ec2.py
│   ├── group_vars
│   └── inventory.ini
```

**tag_Name_Demo -vvvvv -m debug -a var=ansible_ssh_user**

```
172.16.1.12 | success >> {
    "var": {
        "ansible_ssh_user": "ubuntu"
    }
}
```

So, _it is not the bug, it's a feature_
The inventory script (ec2.ini) should either be placed in etc/ dir (or the place where You keep the configuration), or there might be a nice_to_have some variables in ansible.cfg pointing to host_vars and group_vars in the future

**Comment by bcoca** [comment] 2015-06-11 14:07
FYI, host/group_vars can be 'adjacent' to inventory or play.

closing this ticket then as it is not a bug.

**Closed as completed by bcoca** 2015-06-11 14:07 UTC
Labels: P2, bug
