### ISSUE TITLE
Unexpected default sudo_user behavior

### ISSUE THREAD

**Issue by herd-the-cats** [ansible/ansible#10219] opened 2015-02-11 18:28 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

1.8.2
##### Environment: Fedora control host to Debian Wheezy target host

all logins are through a regular user that uses sudo to become root. Root login via ssh is restricted and root does not have a password. (Standard Google Compute Engine setup)
##### Summary:

I had root set as the default user for sudo. The deployment user has full sudo privileges to any other user and command. I then tried to indicate sudo_user on a single task in a role to pull down a git repo with the correct permissions, and used -K on the command line to enter the sudo password for the deployment user, but kept getting hangs with: "ssh connection error waiting for sudo or su password prompt"
##### Steps To Reproduce:

Start playbook with:

```
-   hosts: targethost
    remote_user: deploymentuser
    sudo: yes
    roles:
      - rolename
```

In the role tasks:

```
    - name: pull down git repo as application user
      sudo_user: appuser
      git:
       accept_hostkey: yes
       dest: /path/to/directory
       key_file: /path/to/.ssh/secretkey.pem
       version: master
       repo: repourl
```
##### Expected Results:

The playbook would sudo to root as default unless otherwise indicated, and sudo would all work with the same supplied password for the deployment user.
##### Actual Results:

Auth log on the target host indicated failed attempts at sudo password and playbook did not work until I manually specified:

```
-   hosts: targethost
    remote_user: deploymentuser
    sudo: yes
    *sudo_user: root*
     roles:
      - rolename
```

At the beginning of the playbook. Then the playbook executed as expected, and the git repo was pulled down as the appuser. So there is some difference between manually specifying the sudo user and relying on the configured default in ansible.cfg.

This may be related to open issue # 9616. It sounds similar.

**Comment by jctanner** [comment] 2016-05-26 21:12
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us. 

Testing this on the version you have specified and the latest release, we cannot reproduce this problem.

Our reasons and evidence for this are:
- sudo_user set "-u appuser" for a task in a playbook or in a role with ansible 1.8 and 2.1

And we suggest that:
- Retest with a more recent version of ansible and if needed, file a new bug with full -vvvv output.

As such, we are most likely going to close this ticket.  Should you disagree with this conclusion, you may also wish to join our mailing lists, which are very active:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Closed as completed by jctanner** 2016-05-26 21:12 UTC
Labels: P2, bug
