### ISSUE TITLE
'allow_duplicates:no' behaves incorrectly involving conditionally skipped roles

### ISSUE THREAD

**Issue by AndreBremer** [ansible/ansible#7646] opened 2014-06-03 03:07 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7 (devel 6bc056e012) last updated 2014/06/02 19:46:03 (GMT -700)
##### Environment:

Mac OS X 10.9.3
##### Summary:

Subsequent dependent roles are ignored when a role containing the dependency is conditionally skipped and the dependency is marked `allow_duplicates: no`.
##### Steps To Reproduce:

Playbook contains:

```
roles:
    - { role: role_a, when: false }
    - role_b
```

`role_a` and `role_b` have dependencies in `meta/main.yml`:

```
dependencies:
  - role_c
```

`role_c` disables duplicates in `meta/main.yml`:

```
allow_duplicates: no
```
##### Expected Results:
1. `role_c` is skipped, `role_a` is skipped. 
2. `role_c` executes as a dependency of `role_b`
3. `role_b` executes.
##### Actual Results:
1. `role_c` is skipped, `role_a` is skipped. 
2. `role_b` executes, but `role_c` dependency is never satisfied.

**Comment by jimi-c** [comment] 2014-06-03 03:38
This is a duplicate of https://github.com/ansible/ansible/issues/7353. Thanks!

**Closed as completed by jimi-c** 2014-06-03 03:38 UTC
