### ISSUE TITLE
include_role doesn't get default variable values

### ISSUE THREAD

**Issue by es1o** [ansible/ansible#31980] opened 2017-10-20 12:25 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
include_role module

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /home/esio/work/ansible/ansible.cfg
  configured module search path = [u'/home/esio/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Sep  5 2017, 08:53:59) [GCC 7.1.1 20170622 (Red Hat 7.1.1-3)]

```

##### CONFIGURATION
```
ANSIBLE_NOCOWS(/home/esio/work/ansible/ansible.cfg) = True
DEFAULT_BECOME_EXE(/home/esio/work/ansible/ansible.cfg) = sudo su -
DEFAULT_BECOME_METHOD(/home/esio/work/ansible/ansible.cfg) = su
DEFAULT_HASH_BEHAVIOUR(/home/esio/work/ansible/ansible.cfg) = merge
DEFAULT_HOST_LIST(/home/esio/work/ansible/ansible.cfg) = [u'/home/esio/work/ansible/inventories/test/hosts']
DEFAULT_REMOTE_TMP(/home/esio/work/ansible/ansible.cfg) = /tmp/.ansible-${USER}/tmp # workaround become permission issues
DEFAULT_ROLES_PATH(/home/esio/work/ansible/ansible.cfg) = [u'/home/esio/work/ansible/roles', u'/home/esio/work/ansible/vendor']
HOST_KEY_CHECKING(/home/esio/work/ansible/ansible.cfg) = False
RETRY_FILES_SAVE_PATH(/home/esio/work/ansible/ansible.cfg) = /home/esio/work/ansible/.retryfiles
```
##### OS / ENVIRONMENT
Fedora 26 x86_64

##### SUMMARY
When I use include_role ansible doesn't apply default variables.
##### STEPS TO REPRODUCE
I have directories and files in my ansible config:
```
└── roles
    ├── r1
    │   └── tasks
    │       └── main.yml
    └── r2
        ├── defaults
        │   └── main.yml
        └── tasks
            └── main.yml
```
In roles/r1/tasks/main.yml
```yaml
- name: Run role r2
  include_role:
    name: gpdw.deploy-hdfs-component
  vars:
    artifact_version: "{{ x[2] }}"
    artifact_id: "{{ x[1] }}"
  with_list: "{{ list }}"
  loop_control:
    loop_var: x
```
In roles/r2/tasks/main.yml
```yaml
- name: debug
  debug:
    msg: "{{ artifact_extension }}
```
In roles/r2/defaults/main.yml
```yaml
artifact_extension: "tar.gz"
```

##### EXPECTED RESULTS
It should work and print tar.gz as debug.

##### ACTUAL RESULTS
Ansible fails with error, that variable artifact_extension is undefined. In my opinion ansible should use variables from defaults/main.yml file in included role.

```
fatal: [ap-hdpen1t]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'artifact_extension' is undefined\n\nThe error appears to have been in '/home/esio/work/ansible/roles/gpdw.deploy-dq-all/tasks/main.yml': line 29, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: debug\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'artifact_extension' is undefined"
}
```

**Comment by mkrizek** [comment] 2017-10-20 12:44
cc @bcoca

**Comment by bcoca** [comment] 2017-10-20 16:00
dupe of #21890

**Closed as completed by bcoca** 2017-10-20 16:00 UTC
Labels: module, affects_2.4, support:core, bug

**Comment by languitar** [comment] 2018-08-17 09:42
Can someone explain why this is a duplicate of #21890? I think the original request here was to use default at all, not to expose them to the rest of the world.
