### ISSUE TITLE
extra-vars not accessible from within dynamic inventory (missing feature or design decision ?)

### ISSUE THREAD

**Issue by michal3141** [ansible/ansible#10282] opened 2015-02-18 20:00 UTC
##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
extra-vars and dynamic inventory

##### ANSIBLE VERSION
N/A

##### SUMMARY

I think it would be nice to have extra-vars propagated as command line arguments to dynamic inventory script. Also I don't get the purpose of:
cmd = [ self.filename, "--list" ](in: https://github.com/ansible/ansible/blob/devel/lib/ansible/inventory/script.py:40)
 (passing '--list' as a second argument seems to me kinda pointless)
EDIT:
Now the ugly workaround for requested feature is: 
$ echo "myparam1=value1 myparam2=value2" | ansible-playbook play.yml
and reading sys.stdin from dynamic inventory script

**Comment by bcoca** [comment] 2015-02-18 20:38
inventory are passed minimal information, extra vars (and almost anything else) are not passed by design.

**Comment by michal3141** [comment] 2015-02-18 21:39
I understand your point. Since the proposed feature is going somehow against Ansible design and I can do without it there is nothing left to add but close the issue.

**Comment by bcoca** [comment] 2015-02-18 22:38
that it was by design does not mean it will not be considered

**Comment by srgvg** [comment] 2015-02-20 21:20
The idea of passing --extra-vars to the dynamic inventory is actually good, I think.

> passing '--list' as a second argument seems to me kinda pointless

The idea was, you can also run the script with `--host $inventoryhostname` to retrieve host specific variables. This was however not a good idea performance wise (script called for every host), so the json now also allows to return host vars in the `_meta` key.

I think we should consider to deprecate the `--host` option.
(Sanitizing the dynamic inventory json api might be a thing, too. That `_meta` key always felt very ugly, Perhaps to consider for v2 or beyond?)

**Comment by bcoca** [comment] 2015-02-26 00:05
@svg, yes, after v2 is out we are planning on revamping how inventory works.

**Comment by majidaldo** [comment] 2015-05-21 21:43
just have a wrapper script that can make the inventory script behave any way you like or env vars.

**Comment by sebi-hgdata** [comment] 2016-01-12 13:33
+1

**Comment by udondan** [comment] 2016-06-08 13:02
It looks like this issue was scheduled for 2.1 but I don't see a related commit and it's still open. I guess it did not make it into the 2.1 release?

**Comment by ko-christ** [comment] 2016-09-09 22:44
A dirty workaround using `$PPID` to parse `-e/--extra-vars` from process snapshot.

```
ansible-playbook -i inventory.sh deploy.yml -e cluster=cl_01
```

```
> cat inventory.sh
#!/bin/bash
if [[ $1 != "--list" ]]; then exit 1; fi
cluster_extra_var=`ps -f --pid $PPID | grep ansible-playbook | grep -oh "cluster=\w*" | tail -1 | cut -f2 -d=`
./inventory.py --cluster $cluster_extra_var
```

`inventory.py` returns inventory in JSON for cl_01 only.

**Comment by bcoca** [comment] 2017-01-23 18:08
we can reconsider this once this proposal is started https://github.com/ansible/proposals/issues/41

**Comment by bcoca** [comment] 2017-06-01 23:42
merged #23001, which implements the proposal above

i'm still not sure extra vars is correct way to go, since environment vars are already available

**Closed as completed** 2017-10-24 18:50 UTC
Labels: affects_2.0, affects_2.3, c:inventory/script, c:inventory/inventory, support:community, feature

**Comment by aneagoe** [comment] 2019-03-05 10:08
It looks like this functionality was added at some point however in version 2.7.8 this still doesn't work. running ansible-playbook with an dynamic inventory and -e (EXTRA_VARS) basically ignores the passed EXTRA_VARS.

**Comment by bcoca** [comment] 2019-03-05 14:48
@aneagoe, extra vars are available, the inventory plugin MUST specifically access them though

**Comment by prabakd** [comment] 2019-03-14 00:13
@bcoca If this feature is available, Can u please give some example how to use the extra vars inside the custom script.
