### ISSUE TITLE
run_once dynamically evaluated to false causes variables being overwritten

### ISSUE THREAD

**Issue by kostrzewa9ld** [ansible/ansible#41895] opened 2018-06-25 09:07 UTC
##### SUMMARY
When there are more hosts than `ANSIBLE_FORKS` and `run_once` is evaluated from a variable then when one of the hosts, which gets provisioned not in the first batch, is skipped then variables registered with `register` are skipped on all hosts provisioned before the skipped host.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.5.5
  config file = /work/git/bigdata/bigdata/platform/ansible/ansible.cfg
  configured module search path = [u'/work/git/bigdata/bigdata/platform/ansible/library']
  ansible python module location = /tmp/241/local/lib/python2.7/site-packages/ansible
  executable location = /tmp/241/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]
```
Originally discovered on 2.4.1.0.

##### CONFIGURATION

```
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
```

##### OS / ENVIRONMENT
Linux Mint 18.1 Serena with ansible installed within virtualenv with pip.

##### STEPS TO REPRODUCE

```yaml
- hosts: all
  vars:
    not_once: true
  tasks:
  - set_fact: skipped_host={{ ansible_play_hosts|last }}
  - block:
    - command: echo "foo"
      register: foo_
    - debug: var=foo_
    - set_fact: foo={{ foo_.stdout }}
    when: inventory_hostname != skipped_host
    run_once: "{{ not not_once }}"
```
Executed with:
```
ANSIBLE_FORKS=2 ansible-playbook -i 192.168.7.216,192.168.7.230,192.168.6.237 test.yml -u user -e ansible_password=password -vv
```
Please note the number of hosts is greater than `ANSIBLE_FORKS`.

##### EXPECTED RESULTS
The play succeeds on all hosts.

##### ACTUAL RESULTS

```
ansible-playbook 2.5.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home2/kostrzewa/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /tmp/241/local/lib/python2.7/site-packages/ansible
  executable location = /tmp/241/bin/ansible-playbook
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]
Using /etc/ansible/ansible.cfg as config file

PLAYBOOK: test.yml ****************************************************************************************************************************************************************************
1 plays in test.yml

PLAY [all] ************************************************************************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************************************************************
task path: /tmp/test.yml:1
ok: [192.168.7.216]
ok: [192.168.7.230]
ok: [192.168.6.237]
META: ran handlers

TASK [set_fact] *******************************************************************************************************************************************************************************
task path: /tmp/test.yml:5
ok: [192.168.7.216] => {"ansible_facts": {"skipped_host": "192.168.6.237"}, "changed": false}
ok: [192.168.7.230] => {"ansible_facts": {"skipped_host": "192.168.6.237"}, "changed": false}
ok: [192.168.6.237] => {"ansible_facts": {"skipped_host": "192.168.6.237"}, "changed": false}

TASK [command] ********************************************************************************************************************************************************************************
task path: /tmp/test.yml:7
changed: [192.168.7.216] => {"changed": true, "cmd": ["echo", "foo"], "delta": "0:00:00.001974", "end": "2018-06-25 09:04:56.114970", "rc": 0, "start": "2018-06-25 09:04:56.112996", "stderr": "", "stderr_lines": [], "stdout": "foo", "stdout_lines": ["foo"]}
skipping: [192.168.6.237] => {"changed": false, "skip_reason": "Conditional result was False"}
changed: [192.168.7.230] => {"changed": true, "cmd": ["echo", "foo"], "delta": "0:00:00.002036", "end": "2018-06-25 09:04:56.395101", "rc": 0, "start": "2018-06-25 09:04:56.393065", "stderr": "", "stderr_lines": [], "stdout": "foo", "stdout_lines": ["foo"]}

TASK [debug] **********************************************************************************************************************************************************************************
task path: /tmp/test.yml:9
ok: [192.168.7.216] => {
    "foo_": {
        "changed": false, 
        "skip_reason": "Conditional result was False", 
        "skipped": true
    }
}
skipping: [192.168.6.237] => {"skip_reason": "Conditional result was False"}
ok: [192.168.7.230] => {
    "foo_": {
        "changed": true, 
        "cmd": [
            "echo", 
            "foo"
        ], 
        "delta": "0:00:00.002036", 
        "end": "2018-06-25 09:04:56.395101", 
        "failed": false, 
        "rc": 0, 
        "start": "2018-06-25 09:04:56.393065", 
        "stderr": "", 
        "stderr_lines": [], 
        "stdout": "foo", 
        "stdout_lines": [
            "foo"
        ]
    }
}

TASK [set_fact] *******************************************************************************************************************************************************************************
task path: /tmp/test.yml:10
fatal: [192.168.7.216]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'stdout'\n\nThe error appears to have been in '/tmp/test.yml': line 10, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n    - debug: var=foo_\n    - set_fact: foo={{ foo_.stdout }}\n      ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes.  Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}
skipping: [192.168.6.237] => {"changed": false, "skip_reason": "Conditional result was False"}
ok: [192.168.7.230] => {"ansible_facts": {"foo": "foo"}, "changed": false}
	to retry, use: --limit @/tmp/test.retry

PLAY RECAP ************************************************************************************************************************************************************************************
192.168.6.237              : ok=2    changed=0    unreachable=0    failed=0   
192.168.7.216              : ok=4    changed=1    unreachable=0    failed=1   
192.168.7.230              : ok=5    changed=1    unreachable=0    failed=0   
```

##### ADDITIONAL OBSERVATIONS
1. When `run_once` is set explicitly to `false` or removed the play passes

**Comment by sivel** [comment] 2018-06-25 14:01
Duplicate of https://github.com/ansible/ansible/issues/19966

**Closed as completed by sivel** 2018-06-25 14:01 UTC
Labels: support:core, affects_2.5, bug

**Comment by kostrzewa9ld** [comment] 2018-06-25 19:15
@sivel 
In which aspect this is a duplicate of #19966? as far as I can tell #19966 is about `pause` being skipped if first host is skipped. How does is it relate to this ticket?

**Comment by bcoca** [comment] 2018-06-25 19:55
@kostrzewa9ld the issue is the same, 'run_once' makes the task run on the first host that reaches it AND apply the results to all the hosts currently in the same batch. Pause has the same effect because it has a built in 'run_once' as it is a task that bypasses the host loop (same thing, but not user controllable).

**Comment by kostrzewa9ld** [comment] 2018-06-25 20:11
@bcoca 
But in my case `run_once` evaluates to `false` though through a variable `not_once`, if I set it directly to `false` than everything works as expected. It also works when I increase the batch to the number of hosts or larger.

**Comment by bcoca** [comment] 2018-06-25 20:15
well, if `false` its not `run_once` ... so expected, unsure what you mean by number of hosts, you have not shown that above.

**Comment by kostrzewa9ld** [comment] 2018-06-25 20:20
@bcoca 
In my example I execute the play on 3 hosts with `ANSIBLE_FORKS` set to 2. If I increase `ANSIBLE_FORKS` to 3 the issue does not occur, on both non-skipped hosts variable `foo_` contains `stdout` property.
I have run the experiment on 30 hosts with default `ANSIBLE_FORKS` and there if e.g. 10 host was skipped then all the hosts processed before the skipped one did not have expected variable set but all the next ones had it.

**Comment by bcoca** [comment] 2018-06-25 20:30
but .. what you are a saying is that run_once is irrelevant here cause it is always `false`? I'm unsure what the issue is then.

**Comment by kostrzewa9ld** [comment] 2018-06-25 20:35
@bcoca 
Please have a look at the attached example in which `run_once` is evaluated from expression `"{{ not not_once }}"` where `not_once` is set to `true` for the entire play. As such `run_once`, in my understanding, should evaluate to `false`.
However, when I remove the `run_once` clause (or set it directly to `false` or `no`) then the issue does not occur.

**Comment by bcoca** [comment] 2018-06-25 20:52
yes, which is my point above, this is then unrelated to `run_once`, your title/subject are misleading

**Comment by kostrzewa9ld** [comment] 2018-06-25 20:57
how is it unrelated if:
* when `run_once: "{{ not not_once }}"` is present the play fails
* when `run_once` is removed the play succeeds

**Comment by kostrzewa9ld** [comment] 2018-06-26 03:45
@sivel @bcoca 
I still don't see resemblance to #19966. If it is the title that's misleading, please feel free to change to it.
