### ISSUE TITLE
add possibility to add  custom/additional ssh_known_hosts_files in ansible.cfg

### ISSUE THREAD

**Issue by kowalskey** [ansible/ansible#10207] opened 2015-02-10 21:47 UTC
##### Ansible Version:

```
ansible 1.8.2
  configured module search path = None
```
##### Environment:

OS running ansible: archlinux latest (up to date as of 2015-02-10)
managed OS: Ubuntu LTS 14.04.1 (up to date as of 2015-02-10)
##### Summary:

Here's the thing:

We use SSH jump hosts  so we (ab)use `ProxyCommand` ssh option . 
That in turn requires to have some configuration in ssh_config file (e.g ~/.ssh/config)

I created ssh_config file which is kept in repository with ansible stuff.
It's referenced in shipped ansible.cfg by means of

``` ini
[ssh_connection]
ssh_args                = -F ssh_config

```

So I figured that it would be nice idea to also add ssh_known_hosts file to repo. 
That way if I provision some new hosts  I confirm their identities then noone else will need to do the same.

When custom ssh known hosts file is referenced in custom ssh config file and is different than one of defaults which are checked in `lib/ansible/runner/connection_plugins/ssh.py`
then ansible will assume that hosts don't have their keys accepted and will instead run in serial mode. Serialization is also forced in aforementioned file.

Whether to keep ssh known hosts file in VCS or not is subject for another discussion , but please notice that root cause is custom ssh known hosts file path and not versioning.

Function which checks whether hosts key is already accepted is defined  in

```
lib/ansible/runner/connection_plugins/ssh.py
```

and is called 

``` python
not_in_host_file(self, host):
```
##### Steps To Reproduce:
- Set custom ssh_known_hosts file path in your ssh config e.g.:

``` bash
Host *
    UserKnownHostsFile /tmp/ssh_known_hosts
```
- Execute any playbooks on multiple hosts using `ssh` connection (not local)
##### Expected Results:

Playbooks run on multiple hosts run in parallel
##### Actual Results:

Playbook run on multiple hosts serially

**Comment by mihirvj** [comment] 2015-02-22 15:13
I am not able to understand this completely. When I tried to reproduce it, ansible asks for authentication for the first time with all the hosts (I think this is what you mean by serial execution). However, from next execution, it runs fine (because it finds entries for hosts in custom ssh_known_hosts file). And otherwise, it works as expected. My host OS is Mint and managed OS in Ubuntu. (Is this why I am not able to reproduce the issue?).

I am not sure if I understand this completely. I am new to this project so please let me know if I am missing something.

**Comment by bcoca** [comment] 2015-02-23 20:34
known_hosts access is only serialized if it needs to write, otherwise we could end up with an inconsistent file. 

Unless you continually have new hosts on every run this should only be a factor on an initial run. 

There are ways to get around this:

- set UserKnownHostsFile in your command line or ssh/config file which you prepopulated with all hosts.
- use host keys that are centrally signed so you can verify new hosts w/o having them in known_hosts.  
- set a system wide known hosts (/etc/ssh/ssh_known_hosts), which can be updated when rolling out a host so individual users don't need to have them in their known_hosts.

**Comment by kowalskey** [comment] 2015-02-23 23:23
Hello @mihirvj  Looks like I screwed up something.

My problems were probably caused by funny interactions of pipelining (ControlMaster,ControlPath,ControlPersist) and ProxyCommand ssh options. In the meantime I reworked ansible inventories to use VPN instead of proxied ssh connections and everything worked perfectly fine since then. So I guess that was misconfiguration on my part.

**Comment by mihirvj** [comment] 2015-02-23 23:41
I see. Then this issue should be closed I guess. It has a wrong "Feature_idea" label. Thanks for letting me know though.

**Comment by jimi-c** [comment] 2016-07-13 21:30
Closing per the above.

**Closed as completed by jimi-c** 2016-07-13 21:30 UTC
Labels: feature
