### ISSUE TITLE
Definition of separate SSH user for the same host

### ISSUE THREAD

**Issue by uzyn** [ansible/ansible#5438] opened 2013-12-27 06:21 UTC
I would like to ideally define at inventory:

```
[webservers]
192.168.33.10 ansible_ssh_user=root ansible_ssh_pass=root

[deploy:children]
webservers

[deploy:vars]
ansible_ssh_user=webuser
ansible_ssh_pass=webuser
```

so that an ansible playbook can work on `[webservers]` for sysadmin matters that require root access; while work on `[deploy]` for deployment tasks that do not require root.

I have learned that the above does not work, neither the following, explicitly redefining the same group twice:

```
[webservers]
192.168.33.10 ansible_ssh_user=root ansible_ssh_pass=root

[deploy]
192.168.33.10 ansible_ssh_user=webuser ansible_ssh_pass=webuser
```

This would simply overwrite `ansible_ssh_user` even for `[webservers]` group definition.

**Comment by bcoca** [comment] 2013-12-27 14:46
group vars get merged aside from overriding in the command line you could
make it separate inventory files

deploy
[webservers]
192.168.33.10

[deploy:children]
webservers

[deploy:vars]
ansible_ssh_user=webuser
ansible_ssh_pass=webuser

admin
[webservers]
192.168.33.10 ansible_ssh_user=root ansible_ssh_pass=root

and have deployment commands use -i deploy and admin commands use -i admin

**Comment by mpdehaan** [comment] 2013-12-27 19:23
What Brian said above.

Yep, or even just pass in "-u sysadmin_user_account".

For more user related questions, since this is not a bug per se, please stop by the ansible-project mailing list.

Thanks!

**Closed as completed by mpdehaan** 2013-12-27 19:23 UTC

**Comment by uzyn** [comment] 2013-12-28 04:49
Thanks @bcoca @mpdehaan 

I just felt rather counter-intuitive – not expecting definition under separate groups to be merged.

Thanks.
