### ISSUE TITLE
As of v2 limiting is broken with static inventory.

### ISSUE THREAD

**Issue by gregswift** [ansible/ansible#14098] opened 2016-01-25 05:51 UTC
##### Ansible Version:

$ ansible --version
ansible 2.0.0.2
  config file = /home/xaeth/.ansible.cfg
  configured module search path = Default w/o overrides
##### Ansible Configuration:

What have you changed about your Ansible installation?

My /etc/ansible/ansible.cfg is default Fedora version, which appears to be the stock examples cfg.  My cfg changes the following:

```
[ssh_connection]
ssh_args = -o ForwardAgent=yes -o PubkeyAuthentication=yes
```
##### Environment:

Fedora 22
##### Summary:

As of v2 limiting is broken with static inventory.
##### Reproduction:

Using the attached [inventory.txt](https://github.com/ansible/ansible/files/102805/inventory.txt)
- Ansible 1.9.4

```
$ ansible all --list-hosts -i inventory.txt -l 'app1'
    app1-n01.dc1.dev.example.com
    app1-n02.dc1.dev.example.com
    app1-n01.dc2.dev.example.com
    app1-n02.dc2.dev.example.com
$ ansible all  --list-hosts -i inventory.txt -l 'app2'
    app2-n01.dc1.dev.example.com
    app2-n02.dc1.dev.example.com
    app2-n01.dc2.dev.example.com
    app2-n02.dc2.dev.example.com
$ ansible all --list-hosts -i inventory.txt -l 'app1:&dc1'
    app1-n01.dc1.dev.example.com
    app1-n02.dc1.dev.example.com
```
- Ansible 2.0.0.2

```
$ ansible all --list-hosts -i inventory.txt -l 'app1'
  hosts (8):
    app2-n01.dc1.dev.example.com
    app2-n02.dc1.dev.example.com
    app2-n01.dc2.dev.example.com
    app2-n02.dc2.dev.example.com
    app1-n01.dc1.dev.example.com
    app1-n02.dc1.dev.example.com
    app1-n01.dc2.dev.example.com
    app1-n02.dc2.dev.example.com
$ ansible all  --list-hosts -i inventory.txt -l 'app2'
  hosts (8):
    app2-n01.dc1.dev.example.com
    app2-n02.dc1.dev.example.com
    app2-n01.dc2.dev.example.com
    app2-n02.dc2.dev.example.com
    app1-n01.dc1.dev.example.com
    app1-n02.dc1.dev.example.com
    app1-n01.dc2.dev.example.com
    app1-n02.dc2.dev.example.com
$ ansible all --list-hosts -i inventory.txt -l 'app1:&dc1'
  hosts (8):
    app2-n01.dc1.dev.example.com
    app2-n02.dc1.dev.example.com
    app2-n01.dc2.dev.example.com
    app2-n02.dc2.dev.example.com
    app1-n01.dc1.dev.example.com
    app1-n02.dc1.dev.example.com
    app1-n01.dc2.dev.example.com
    app1-n02.dc2.dev.example.com
```

**Comment by sivel** [comment] 2016-01-25 12:27
Closing as a duplicate of https://github.com/ansible/ansible/issues/13848

**Closed as completed by sivel** 2016-01-25 12:27 UTC
