### ISSUE TITLE
apt module upgrades package, but log message is green rather than yellow

### ISSUE THREAD

**Issue by akurilin** [ansible/ansible#4418] opened 2013-10-09 21:12 UTC
Was chatting with @mpdehaan , he suggested I post issue here. 

Nginx 1.4.3 was released today, and the corresponding launchpad.net PPA I was using was updated as well. Version 1.4.1 for precise was removed, replaced with 1.4.3. My apt directive was:

```
- name: install nginx
  sudo: yes
  apt: pkg=nginx=1.4.1-1ppa1~precise state=present update_cache=yes
```

and the error message I got this morning was:

```
TASK: [install nginx] *********************************************************
failed: [api.mydomain.com] => {"failed": true, "item": ""}
msg: 'apt-get install 'nginx=1.4.1-1ppa1~precise' ' failed: E: Version '1.4.1-1ppa1~precise' for 'nginx' was not found

FATAL: all hosts have already failed -- aborting
```

No problem. I updated the apt directive to the following:

```
- name: install nginx
  sudo: yes
  apt: pkg=nginx=1.4.3-1~precise0 state=present update_cache=yes
```

and re-ran the playbook, everything passed, but I got the following green message:

```
TASK: [install nginx] *********************************************************
ok: [api.mydomain.com]
```

That's odd. I expected a yellow "changed" message to indicate that the version got updated from 1.4.1 to 1.4.3. Ok maybe it didn't get updated, so I checked:

```
[/]$ ./usr/sbin/nginx -v
nginx version: nginx/1.4.3
```

Yep.. looks like at least the binary got updated, but I have no idea if nginx itself was restarted as part of it, or if I'm actually still running the previous version. I can't even use the handler for [install nginx] since the instruction is completed as green, and so it's never called.

Would love to know if I'm configuring ansible wrong here, or if there's a glitch somewhere in here.

**Comment by mpdehaan** [comment] 2013-10-09 22:41
Likely a bug when doing a specific version request.   I've tagged it as such.

Thanks for the heads up!

**Comment by jctanner** [comment] 2013-10-17 20:43
@AKurilin I am not able to reproduce with the following playbook:

<pre>
- hosts: localhost
  #connection: local
  gather_facts: False
  vars:
    - pname: libcurl3
    - oldver: 7.29.0-1ubuntu3
    - newver: 7.29.0-1ubuntu3.2
  tasks:
    - shell: apt-cache madison {{ pname }}
      register: versions
    - debug: var=versions
    - name: remove package
      apt: pkg={{ pname }} state=absent update_cache=yes
    - name: remove deps
      shell: apt-get autoremove
    - name: install old version
      apt: pkg={{ pname }}={{ oldver }} state=present update_cache=yes
    - name: install new version
      apt: pkg={{ pname }}={{ newver }} state=present update_cache=yes
</pre>

The last play does result in a "changed=True" state, and the logging color is yellow. If you can, please attempt to reproduce the issue with -vvvv so that we can validate that "changed" is actually True.

**Comment by jctanner** [comment] 2013-10-17 20:49
I'm going to go ahead and close this now. Please open a new bug if you see a task with changed=True and color=Green.

**Closed as completed by jctanner** 2013-10-17 20:49 UTC
Labels: needs_info, bug

**Comment by akurilin** [comment] 2013-10-18 01:46
I've exercised this scenario again recently with a different package and didn't repro this issue either. I'll keep an open eye for it in the future.
