### ISSUE TITLE
unarchive module: diff fails when using sudo

### ISSUE THREAD

**Issue by phraktle** [ansible/ansible#5431] opened 2013-12-26 20:27 UTC
The unarchive module supports --diff for tar.gz files, which is great. Unfortunately this always fails when specifying a sudo_user for the task, since tar reports an altered uid/gid.

**Comment by mpdehaan** [comment] 2013-12-26 20:32
Not much to go on here -- no ansible version or explanation of what "fails" means, or example from your playbook or playbook output.

Can you please supply more information?

Thanks!

**Comment by phraktle** [comment] 2013-12-26 21:34
Sorry I wasn't clear. I meant that unarchive normally detects that a .tar.gz is unchanged and thus the task is skipped. This fails if you set a sudo_user for the task, since tar --diff reports the gid/uid are different.

Example (running as root):

```
- name: upload and extract stuff
   sudo_user: foo
   unarchive: src=stuff.tar.gz dest=/home/foo/
```

This always uncompressess the archive. When removing sudo_user, it uncompresses only when the archive is in fact different.

ansible version: 1.4.3

**Comment by risaacson** [comment] 2014-02-12 08:04
@phraktle I am not able to duplicate this bug on the current 1.5(devel). Can you test this to see if you still have a problem? If not let's close this issue out.

**Comment by phraktle** [comment] 2014-02-12 13:25
I have tested again with 1.5 head, but I still see the issue. Note, that the tar was not created with the sudo_user's uid/gid (i.e. the tar it has uid 0, as is typical in tar.gz distributions). In this case when you use a sudo_user for unarchive, it will always yield a "changed" state since tar will indicate a difference (as the decompressed files got a different uid/gid):

hello/hello.txt: Uid differs
hello/hello.txt: Gid differs

**Comment by risaacson** [comment] 2014-02-12 17:19
Confirmed.
We need to see where if it is worth fixing this or just to unarchive the file(s) again. The current behavior matches what happens with ZIP files.

**Comment by mpdehaan** [comment] 2014-02-12 17:40
This command should be expected to work with sudo.

**Comment by mpdehaan** [comment] 2014-02-12 17:40
--diff I'm less concerned about, this an action plugin, I wouldn't expect it need to report a diff at all, but the changed reporting should be (needs to be) correct.

**Comment by mpdehaan** [comment] 2014-09-29 20:44
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Closed as completed by mpdehaan** 2014-09-29 20:44 UTC
Labels: m:unarchive, bug
