### ISSUE TITLE
`ansible_env` is undefined in playbook

### ISSUE THREAD

**Issue by lig** [ansible/ansible#14655] opened 2016-02-25 09:54 UTC
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.1.0
  config file = /<project_dir>/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

```
[defaults]
inventory = ./hosts
roles_path = ./roles
```
##### Environment:

Ansible run on Fedora 23 managing Centos 7 with EPEL latest updates but it looks like it does not matter.
##### Summary:

Getting `FAILED! => {"failed": true, "msg": "'ansible_env' is undefined"}` on  `TASK [setup]`
##### Steps To Reproduce:

`ansible_env` is used inside playbook. Sample playbook:

```
- hosts: <group_name>
  roles:
  - { role: role1, tags: ['tag1', 'tag2'] }
  - { role: role2, tags: ['tag3', 'tag2'] }
  environment:
    PATH: "/usr/pgsql-9.4/bin:/usr/local/bin:{{ ansible_env.PATH }}"
  become: true
```
##### Expected Results:

As in Ansible 2.0.0.1 it is expected to have managed host PATH environment variable to be altered. 
##### Actual Results:

```
PLAY ***************************************************************************

TASK [setup] *******************************************************************
fatal: [<host_name>]: FAILED! => {"failed": true, "msg": "'ansible_env' is undefined"}

NO MORE HOSTS LEFT *************************************************************
```

**Comment by indistinctTalk** [comment] 2016-02-26 07:28
I'm getting the same for 2.0.1.0 and running ubuntu 14.04 on host/targets.

**Comment by reidblomquist** [comment] 2016-02-26 20:34
+1 getting this as well on 2.0.1.0 with ubuntu 14.04 targets (OSX host)

**Comment by bcoca** [comment] 2016-02-26 20:45
This is caused because the setup task in gathering facts now correctly inherits all properties form the play, in this case you are trying to template environment for the task that actually sets it.

```
environment:
    PATH: "/usr/pgsql-9.4/bin:/usr/local/bin:{{ (ansible_env|default({})).PATH|default('') }}"
```

**Comment by lig** [comment] 2016-02-27 05:02
@bcoca well, I cannot understand what the code you've provided is supposed to do or fix.

The way it used to be done was quite understandable. The code you posted is too complex for such a simple but absolutely required task as updating PATH variable on target machine.

Is it the way we are forced to set PATH from now on? I'm sorry, but It just doesn't look right.

**Comment by bcoca** [comment] 2016-02-27 05:46
it is the way you deal with undefined vars when you are passing data to the task that needs to define the var you are using.

**Comment by lig** [comment] 2016-02-27 15:58
I do not need to define any var. I just want to set PATH based on its value. Ok, I understand that this means that the `ansible_env` should be updated after that.

I just wonder why it worked before and why it is broken in the minor release... And nothing I could find in the Changelog about that.

And the resulting playbook code is quite ugly after all. It looks like lack of Ansible support for this behavior. Especially after it was nice.

**Comment by bcoca** [comment] 2016-02-27 16:27
The change that was made was to have the `setup` task implicit in `gather_facts: True` inherit all properties from the play, previously this was not happening and it ran in an 'uncontrolled context'.

So you won't see 'path cannot be set in environment using facts at play level' change, it is a consequence of making the implicit `setup` behave more consistently with other tasks.

**Comment by bcoca** [comment] 2016-02-29 20:44
so I'm going to close this as it is not a bug, but an expected consequence of making the implied fact gathering behave as other tasks. I'll make a note in the change log that the behavior can cause issues.

**Closed as completed by bcoca** 2016-02-29 20:44 UTC
Labels: bug

**Comment by indistinctTalk** [comment] 2016-03-01 14:01
Fair enough, probably want to update the [docs](http://docs.ansible.com/ansible/faq.html#how-can-i-set-the-path-or-any-other-environment-variable-for-a-task-or-entire-playbook) to reflect this change.

**Comment by bcoca** [comment] 2016-03-01 14:21
done in  d6716a2f9054f3426d558576d9e3ebf7937aa888

**Comment by yoshiwaan** [comment] 2016-03-03 00:39
So if the setup task is being standardised in this way then why doesn't it also have the same consistent variable(s?), like ansible_env, that other tasks do?
The syntax you provided works, but it's far from easily comprehensible for what must be a fairly common thing to do.

**Comment by bcoca** [comment] 2016-03-03 01:46
@yoshiwaan because the setup task is the one that sets the variable.

**Comment by lig** [comment] 2016-03-03 12:16
@bcoca Maybe, this could be separated in the future? Like "audit" and "setup" tasks?
Audit could just gather facts and then setup will be able to use them.
Moreover this will allow to run audit alone and just see the reports about hosts state…

**Comment by bcoca** [comment] 2016-03-03 15:04
@lig setup ONLY gathers facts ....what use is there renaming it to audit? then keeping a setup also?

in this case the facts are being used in the task definition, not in the module itself, I think you are confusing issues.

**Comment by lig** [comment] 2016-03-03 17:47
@bcoca ok.
here we have:
1. task definition
2. host preparation definition (e.g. setting environment)
3. gathering facts
4. actual host preparation
- 3 depends on 1.
- 2 depends on 3 but included 1.

And if setup does only 3 then when 4 is happening? I believe it just affects every task inside host. This means we need a place in the host definition that will be evaluated after setup have gathered facts. Sounds logical, doesn't it?

**Comment by bcoca** [comment] 2016-03-03 18:13
you are making assumptions that are not true:
1. task definition
2. host definition (inventory), order of these 2 really don't matter
3. tasks run (gathering facts is just a task)

3 depends on both 1 and 2, environment is part of task definition, but tasks can depend on data returned from previous tasks, so 3 can depend on 3 also.

**Comment by yoshiwaan** [comment] 2016-03-03 20:07
Okay I  made the change suggested and now I'm actually running into another problem in Ansible 2.0.1.0

So with a play like this:

```
  - hosts: my_hosts
    roles:
      - my_role
```

things work, except for the task that needs the path alteration I need.

With a play like this:

```
  - hosts: my_hosts
    environment:
      PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    roles:
      - my_role
```

I get the error described in this case.

And with the suggested fix in a play like this:

```
  - hosts: my_hosts
    environment:
      PATH: "/usr/local/bin:{{ (ansible_env|default({})).PATH|default('') }}"
    roles:
      - my_role
```

I start to get these failures when using the yum module

```
TASK [yum_update : YUM - update all] *******************************************
task path: /vagrant/roles/yum_update/tasks/main.yml:12
ESTABLISH LOCAL CONNECTION FOR USER: vagrant
my_host EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1457035399.81-231060722497621 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1457035399.81-231060722497621 `" )'
my_host PUT /tmp/tmpJdZJBr TO /home/vagrant/.ansible/tmp/ansible-tmp-1457035399.81-231060722497621/yum
my_host EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-ffkjsywbtyctudygyvrhraawkpmqkgxr; /bin/sh -c '"'"'"'"'"'"'"'"'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 PATH=/usr/local/bin:/usr/local/bin: /usr/bin/python -tt /home/vagrant/.ansible/tmp/ansible-tmp-1457035399.81-231060722497621/yum; rm -rf "/home/vagrant/.ansible/tmp/ansible-tmp-1457035399.81-231060722497621/" > /dev/null 2>&1'"'"'"'"'"'"'"'"''"'"''
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1457035399.81-231060722497621/yum", line 3795, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1457035399.81-231060722497621/yum", line 1028, in main
    disablerepo, disable_gpg_check, exclude, repoquery)
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1457035399.81-231060722497621/yum", line 951, in ensure
    res = latest(module, pkgs, repoq, yum_basecmd, conf_file, en_repos, dis_repos)
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1457035399.81-231060722497621/yum", line 762, in latest
    rc, out, err = module.run_command(yum_basecmd + ['check-update'])
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1457035399.81-231060722497621/yum", line 2806, in run_command
    args = [ os.path.expandvars(os.path.expanduser(x)) for x in args ]
  File "/usr/lib64/python2.6/posixpath.py", line 251, in expanduser
    if not path.startswith('~'):
AttributeError: 'NoneType' object has no attribute 'startswith'

fatal: [my_host]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "yum"}, "parsed": false}
```

I'm not convinced this case should be closed yet...

Edit:
Here are a couple of examples of yum tasks that are failing. It's nothing special

```
- name: YUM - libselinux-python
  yum:
    state: present
    name: libselinux-python
  tags:
    - yum
    - selinux
```

```
  - name: YUM - update all
    yum:
      name: '*'
      state: latest
```

If the current state of the yum package is correct (i.e. if it's already installed and the state is present) then there is no error, it's only when yum is actually invoked.

**Comment by indistinctTalk** [comment] 2016-03-04 01:34
Using suggested fix I also started running into issues; I haven't saved them unfortunately but it was complaining about missing the head command. To get around it I just added that path back in manually. Anyway, I'm cautiously putting forward support for the idea that maybe this isn't resolved.

**Comment by yoshiwaan** [comment] 2016-03-09 19:56
@bcoca anything to add to this?
My only option right now on the latest version is to go and define PATH in every single module call that needs a specific path, instead of setting it generically in the playbook.

**Comment by rgwozdz** [comment] 2016-03-14 22:08
When I use the proposed `(ansible_env|default({})).PATH|default('')` solution, I get other problems, like:

```
"stderr": "/bin/bash: tar: command not found"
```

**Comment by yoshiwaan** [comment] 2016-03-14 22:31
I have the feeling that using this 'work around' just sets it to nothing in the setup task, which is supposed to define it for the rest of the run, and ends up having a knock on effect where it's undefined or only defined as the single path you specify in the playbook.

**Comment by indistinctTalk** [comment] 2016-03-15 01:41
I get the feeling you're right.

**Comment by jimi-c** [comment] 2016-03-19 13:59
The other option is to instead set the environment on the tasks where you need it. Most likely there are just a few places where it is actually required to set the path.

**Comment by staticfloat** [comment] 2016-05-05 06:30
My solution to this problem is to just save the default `PATH` in a variable first, e.g.:

``` yaml
- hosts: servers
  tasks:
    - command: echo "$PATH"
      register: default_path

- hosts: servers
  environment:
    PATH: "{{default_path.stdout}}:/usr/local/bin"
...
```

This is a little more verbose, but is simple and works.

**Comment by indistinctTalk** [comment] 2016-05-05 13:31
@staticfloat, nice, I like that.

**Comment by TheFrozenFire** [comment] 2016-05-06 21:25
I've been fighting this too. This change to make the environment section execute for the setup phase should be reverted with a prejudice. It causes more regressions than it's worth.

My solution has been to simply execute a no-op task on the same hosts before the play with the environment section. This ensures that the setup phase has run before the actual setup phase is run (yo dawg).

**Comment by lig** [comment] 2016-05-09 01:33
@bcoca That is what I was talking about. There are two actual phases: Audit and Setup. As for now Ansible does Audit as part of Setup. It looks like it is error prone and the change breaks the compatibility with a lot of playbooks out there.

Logically if the Audit phase is implicit then its results should be available in setup. That how things used to work. If now we cannot use audit results in setup task because they affect the audit part itself then it looks like we need to separate the Audit part from Setup to be able to use the Audit results in the Setup phase.

**Comment by kozyr** [comment] 2016-06-21 18:33
Why is this closed? Official doc says:
environment:
  PATH: "{{ ansible_env.PATH }}:/thingy/bin"
  SOME: value

Please either put a working example into the doc, or reopen this and fix it.

**Comment by reidblomquist** [comment] 2016-06-22 20:01
this is a non-starter for me in terms of upgrading.

**Comment by bendoh** [comment] 2016-08-30 14:54
Ran into this problem too; similar to @staticfloat, I just did a null play before the play that needs `ansible_env`:

``` yaml
---
- hosts: web

- hosts: web
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
  roles: 
    - ...
```

So the setup is run and facts are gathered before the second play at which point it's known.

**Comment by pgmillon** [comment] 2016-08-30 15:18
Hi there,
I used the following workaround in a role :

``` yml
- setup: filter=ansible_env
- name: Install Node6 dependencies
  npm: name={{item.name}} version={{item.version}} global=yes
  with_items:
...
  environment:
    PATH: /opt/build/tools/node-v6.4.0-linux-x64/bin:{{ansible_env.PATH}}
```

**Comment by ehiggs** [comment] 2016-10-03 13:38
A lot of these workarounds seem to fail when using `--start-at-task`. I'm not very experienced at Ansible but (ignorant comment incoming!)... wouldn't it make sense or the implicit setup/gather_facts task to be treated as special (as it's implicit and hence special already) and run as a distinct task before every job unless disabled either at the command line or in the first task being run?

**Comment by karthiksadhasivam** [comment] 2016-12-19 22:33
The issue still persists. Any other workaround?

**Comment by reidblomquist** [comment] 2016-12-20 18:20
@karthiksadhasivam my workaround is to keep using 1.9 when I want this functionality - lol. couple other things broken in 2 that make me not want to upgrade

**Comment by artburkart** [comment] 2017-06-23 17:54
I have a lot of different playbooks that build different AMIs and I wanted to add `/usr/local/bin` to my PATH. My workaround for this was to use visudo to add `/usr/local/bin` to the `secure_path`

**Comment by shitalm** [comment] 2017-07-05 06:24
Has this been fixed yet?

**Comment by artburkart** [comment] 2017-07-05 12:07
I believe it was ruled as expected behavior because `ansible_env.PATH` is set at a later time now.
