### ISSUE TITLE
Issues with the service module and td-agent

### ISSUE THREAD

**Issue by hernandesbsousa** [ansible/ansible#9119] opened 2014-09-24 14:40 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.10 and 1.7.1
##### Environment:

Running Ansible from OSX to Debian Wheezy.
##### Summary:

Running the `service` module with the state `started` or `restarted` with the wrong configuration file outputs `changed` even though the service did not actually start (if you run it on the command line the return code is 1).
##### Steps To Reproduce:

```
  - apt_key: url=http://packages.treasure-data.com/redhat/RPM-GPG-KEY-td-agent state=present

  - apt_repository: repo=deb\ http://packages.treasuredata.com/2/debian/wheezy/\ wheezy\ contrib

  - apt: pkg=td-agent state=present

  - lineinfile: dest=/etc/td-agent/td-agent.conf line="dummycommandforerror"

  - service: name=td-agent state=started
```
##### Expected Results:

The playbook execution should be stopped and an error shown, since the return code was 1.
##### Actual Results:

I get changed as if the service started correctly.

**Comment by mscherer** [comment] 2014-09-24 19:25
I cannot reproduce the issue on HEAD nor on 1.7.1 with the playbook you gave as a reproducer. Did you change something else ( since log show me that it treat the wrong configuration as a non blocking error, ie just a warning )

**Comment by mscherer** [comment] 2014-09-24 19:28
To be clearer, by "I cannot reproduce", everything start fine and the process is started.

**Comment by hernandesbsousa** [comment] 2014-09-24 19:41
@mscherer I thought the config would break with anything, please try with:

```
lineinfile: dest=/etc/td-agent/td-agent.conf line="<source>"
```

**Comment by mscherer** [comment] 2014-09-24 21:29
Well, I had to add it by hand at the right place, but looking at it, the problem is that the init script return 0 even when it fail to start. The reporting is however indeed too simplistic, since it assume that if we asked to start and that no error was reported by the script, then we started successfully. The return of status is not taken in account ( despites the fact this would have been correctly detected ).

**Comment by mpdehaan** [comment] 2014-09-25 13:05
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We're not sure this is a bug, and we don't mean for this to be confrontational.  Let's explain what we're thinking:
-  the init script is not reporting accurate exit codes
-  the "pattern" option on the service module can be used to work around the problem with a bad init script
-  a bug should probably be filed with the distribution about the init script exit codes
- normally, we shouldn't have to rely on checking "service status" when "service start" returns ok, per normal expectations of init scripts, so I don't think we need to double check on that.  A service should return 0 only when it starts successfully.  At that time the service may not be 100% ready (I'm looking at you, JBoss), but it has started successfully

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists 
to talk about this and we might be persuaded otherwise.
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!

**Closed as completed by mpdehaan** 2014-09-25 13:05 UTC
