### ISSUE TITLE
`-meta: refresh_inventory` breaks `hostvars`

### ISSUE THREAD

**Issue by jaddison** [ansible/ansible#14766] opened 2016-03-03 04:49 UTC
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.1.0
  config file = /Users/jaddison/projects/jollygood.com-config/aws/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

ansible.cfg:

```
[defaults]
inventory = inventory/ec2.py

[ssh_connection]
control_path = /tmp/%%h-%%p-%%r
```
##### Environment:

Running ansible on OSX 10.11.3. Managing Ubuntu 16.04 EC2 instances using ec2.py inventory.

ec2.ini (comments removed for brevity):

```
[ec2]
regions = us-west-2
regions_exclude =
destination_variable = public_dns_name
vpc_destination_variable = ip_address
route53 = False
all_instances = True
all_rds_instances = True
all_elasticache_replication_groups = True
all_elasticache_clusters = True
all_elasticache_nodes = True
cache_path = ~/.ansible/tmp
cache_max_age = 0
nested_groups = False
replace_dash_in_groups = True
expand_csv_tags = False
group_by_instance_id = True
group_by_region = True
group_by_availability_zone = True
group_by_ami_id = True
group_by_instance_type = True
group_by_key_pair = True
group_by_vpc_id = True
group_by_security_group = True
group_by_tag_keys = True
group_by_tag_none = True
group_by_route53_names = True
group_by_rds_engine = True
group_by_rds_parameter_group = True
group_by_elasticache_engine = True
group_by_elasticache_cluster = True
group_by_elasticache_parameter_group = True
group_by_elasticache_replication_group = True
```
##### Summary:

Using the `-meta: refresh_inventory` task breaks `hostvars` and thus plays.
##### Steps To Reproduce:

Run the sample playbook below. I ran mine against the ec2.py inventory, but I don't think it's platform-specific. Obviously the `hosts` tag group targeting would need to change for reproduction purposes.

If I remove the `-meta: refresh_inventory` line, the `ec2_id` variable is output correctly.

```
# this play does not (debug statement doesn't output anything - see following output)

- name: Common {{ env }} EC2 server setup/securing
  hosts: "tag_environment_{{ env }}:&tag_new_True"
  become: yes
  gather_facts: False
  vars:
    ansible_port: 22
  tasks:
    - meta: refresh_inventory
    - debug: var=ec2_id
```
##### Expected Results:

The debug statement to output the desired value.
##### Actual Results:

No output - it's like the play was never run.

Resulting output:

```
~/project AWS_PROFILE=jollygood ansible-playbook -vvvv test.yml --extra-vars "env=staging"
Using /Users/jaddison/projects/jollygood.com-config/aws/ansible.cfg as config file
Loaded callback default of type stdout, v2.0
1 plays in test.yml

PLAY [Common staging EC2 server setup/securing] ********************************

PLAY RECAP *********************************************************************

```

@bcoca on IRC stated that there was another issue related to `refresh_inventory` (see #14435, I assume) that covered this case, but I figured I might as well add in more details as its information was quite sparse.

**Comment by jaddison** [comment] 2016-03-03 04:50
Feel free to close if #14435 covers this.

**Comment by jimi-c** [comment] 2016-03-17 16:59
@jaddison I agree, this seems to be a dupe of #14435, so we'll go ahead and close this.

Thanks!

**Closed as completed** 2016-03-17 17:00 UTC
