### ISSUE TITLE
Using variable for task results in file could not be read

### ISSUE THREAD

**Issue by joehack3r** [ansible/ansible#9669] opened 2014-11-29 19:37 UTC
**Issue Type:**

Bug Report

**Ansible Version:**

ansible 1.8.1
  configured module search path = None

**Environment:**

Multiple (OSX, Ubuntu 12.04, Ubuntu 14.04)

**Summary:**

When I use variables to identify a task file to run, Ansible no longer resolves the variable and returns

`ERROR: file could not read:`

**Steps To Reproduce:**

`git clone https://github.com/joehack3r/temp.git`
`pip install ansible==1.7.2`
`ansible-playbook myPlaybook.yml`

`pip install ansible==1.8.1`
`ansible-playbook myPlaybook.yml`

**Expected Results:**
`PLAY [Start instance(s)] ******************************************************
skipping: no hosts matched`

PLAY RECAP ********************************************************************

**Actual Results:**

`ERROR: file could not read: /roles/myRole/tasks/{{my2015Tasks}}`

**Comment by abondis** [comment] 2014-12-01 20:32
same issue here. The problem is also present in 1.8.0, 1.7.2 is fine. I'm trying to find what changed.

**Comment by jimi-c** [comment] 2014-12-01 21:00
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2014-12-01 21:00 UTC
Labels: P1, bug
