### ISSUE TITLE
Include a playbook in background

### ISSUE THREAD

**Issue by regexcracker** [ansible/ansible#27825] opened 2017-08-06 22:00 UTC
##### ISSUE TYPE
 - ~~B ug Report~~
- Feature Idea
##### COMPONENT NAME
include

##### ANSIBLE VERSION
ansible 2.2.0.0
##### CONFIGURATION
No
##### OS / ENVIRONMENT
N/A (Not platform-specific)

##### SUMMARY
```
Trying to include playbooks abc.yml and xyz.yml in a master playbook master.yml and wanting to run them in background.

Suggest if there is any other way to achieve this.
 
```
##### STEPS TO REPRODUCE
Execute Master playbook : ansible-playbook -vvvv master.yml -u user1
master.yml 
```---
  - include: abc.yml
     async: 2000
     poll: 0
     register: playbook1

    - include: xyz.yml
      async: 2000
      poll: 0
      register: playbook2

   - name: Check status of playbook1
      async_status: jid={{playbook1.ansible_job_id}}
      register: status1_check
      until: status1_check.finished
      retries: 20
      delay: 5

   - name: Check status of playbook2
      async_status: jid={{playbook2.ansible_job_id}}
      register: status2_check
      until: status2_check.finished
      retries: 20
      delay: 5

abc.yml and xyz.yml are simple playbooks having echo statements under shell module
```
##### EXPECTED RESULTS
```
abc.yml and xyz.yml should run in background while including.
```
##### ACTUAL RESULTS

```
ERROR! 'async' is not a valid attribute for a PlaybookInclude

The error appears to have been in '/ngs/app/wordent/archive/background_execution.yml': line 6, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

#  tasks:
    - name: Include connectivity check playbook in background
      ^ here
```

**Comment by bcoca** [comment] 2017-08-07 19:21
This was never intended nor supported, so marking as a request for enhancement as this is not a bug.

**Comment by regexcracker** [comment] 2017-08-07 19:31
Hi,

Any other way to achieve this scenario.

**Comment by bcoca** [comment] 2017-08-07 19:46
many, but not one inherit to Ansible's playbook definitions. Use parallels or xargs or similar tool to run them in parallel.

**Comment by regexcracker** [comment] 2017-08-08 17:26
But I can not use Ansible definitions or modules to implement the same?

**Closed as completed** 2017-10-11 09:46 UTC
Labels: affects_2.2, module, deprecated, support:core, feature

**Comment by FlyingFishPeng** [comment] 2018-11-26 07:35
> definit
Hello~I want't to achieve the same scenario as you asked before. Have you ever solved it?
