### ISSUE TITLE
int filter not functioning properly

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#13574] opened 2015-12-16 16:15 UTC
Operating System: OSX
Ansible Version: 1.9.4

``` yaml
  - name: set fact
    set_fact:
      var1: 3
  - name: set fact
    set_fact:
      var2: "{{ var1 | int }}"

  - debug: var=var2
  - debug: msg={{ var1 | int }}
```

This playbook produces the following output:

```
ok: [10.2.51.196] => {
    "var": {
        "var2": "3"
    }
}
ok: [10.2.51.196] => {
    "msg": "3"
}
```

Expected is an integer value of 3 and not a string "3".

**Comment by abadger** [comment] 2015-12-18 23:39
Yeah, there's some work that could be done in this area.

Debug output can be deceiving, though.  it shows some things as strings that actually aren't.  assert tells us that although there is some work that could be done, there is also a way to workaround it:

```
---
- hosts: localhost
  tasks:
  - name: set fact
    set_fact:
      var1: 3
  - name: set fact
    set_fact:
      var2: "{{ var1 | int }}"

  - name: Variable stays a number
    assert:
      that:
      - var1 == 3
      - var1 != "3"
  - name: Variable filtered by int is still a number
    assert:
      that:
      - "{{ var1 | int }} == 3"
      - "{{ var1 | int }} != '3'"
  - name: Variable filtered by int now is a number
    assert:
      that:
      - "{{ var2 | int }} == 3"
      - "{{ var2 | int }} != '3'"
  - name: Variable filtered by int earlier is a number
    assert:
      that:
      - "var2 == 3"
    ignore_errors: True
  - name: Variable filtered by int earlier is a number
    assert:
      that:
      - "var2 != '3'"
    ignore_errors: True

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Variable stays a number] *************************************************
ok: [localhost]

TASK [Variable filtered by int is still a number] ******************************
ok: [localhost]

TASK [Variable filtered by int now is a number] ********************************
ok: [localhost]

TASK [Variable filtered by int earlier is a number] ****************************
fatal: [localhost]: FAILED! => {"assertion": "var2 == 3", "changed": false, "evaluated_to": false, "failed": true}
...ignoring

TASK [Variable filtered by int earlier is a number] ****************************
fatal: [localhost]: FAILED! => {"assertion": "var2 != '3'", "changed": false, "evaluated_to": false, "failed": true}
...ignoring

PLAY RECAP *********************************************************************
localhost                  : ok=7    changed=0    unreachable=0    failed=0
```

So pushing it through the int filter at the point at which you use it will make sure it is an int.  But applying the int filter earlier does not.  So you can use that as a workaround for now (despite what the debug output might lead you to believe).

Note that this is a tough issue because jinja2 (which handles the variable templating) is essentially a text templating tool.  So it returns everything as a string and we have to figure out ways to decide if the variable should really end up as something other than a string in the end.

**Comment by hdsiles** [comment] 2016-01-25 04:48
Operating System: OSX
Ansible Version: 2.0.0.2

I am also seeing this as an issue with version 2.0.0.2.  In my case I am trying to read a variable out of a file, and use it with the jira module. The instance on the other side of the API is requiring a numeric value (integer) but it seems to be failing to pass it as anything other than a string.  If I hard code it with a number without quoting it works just fine.   The verbose data flag also appears to indicate that using a jinja2 filter of {{ variable | int }} is not correctly forcing the type to be the correct type.

**Comment by bcoca** [comment] 2016-01-25 19:55
you cannot really force the type on the definition that way, the filter is meant to be used on 'usage':

This is wrong:

```
vars:
# The type at this point is defined by YAML, NOT jinja2, this will be a YAML string due to quoting, no matter what jinja2 says
  var2: "{{3|int}}" 

...

when: var2 == 3
```

This is how you use it correctly:

```
vars:
  var2: 3  # here its a int in YAML, but we are not going to rely on that.

...

when: var2|int == 3
```

closing this as it is not a bug but a misunderstanding on when to use the type filters

**Closed as completed by bcoca** 2016-01-25 19:55 UTC
Labels: bug
