### ISSUE TITLE
want to have an option to provide the sudo_pass via inventory

### ISSUE THREAD

**Issue by lied** [ansible/ansible#4492] opened 2013-10-14 08:19 UTC
I have a deployment where I need to be able to provide a password for sudo and I don't want to use the -K option as we like to fire up the deployment process complete automatically.

It would be nice if I have the option to specify the sudo_pass in the inventory file.

**Comment by sivel** [comment] 2013-10-14 12:52
This is a duplicate of #4323

**Comment by mpdehaan** [comment] 2013-10-14 12:53
Yep, closing this one.

Thanks!

**Closed as completed by mpdehaan** 2013-10-14 12:53 UTC
Labels: feature
