### ISSUE TITLE
include with sudo: yes not working in latest devel 6154ed

### ISSUE THREAD

**Issue by sebi-hgdata** [ansible/ansible#12158] opened 2015-08-29 18:26 UTC
Hey,
  It seems that included tasks ignore the sudo: yes specifier. I've pushed  new commit on my https://github.com/sebi-hgdata/ansible_test repo to reproduce the issue

  @jimi-c

**Comment by chrrrles** [comment] 2015-09-02 21:44
Hi @sebi-hgdata, I am unable to reproduce your issue using:

```
ansible-playbook -i inventories/local/hosts build_admin_ui.yml
```

Here's my -vvvv output:

```
TASK: [include not taking in account sudo -> output should be root as we ahev sudo: yes in /build.yml] *** 
<127.0.0.1> ESTABLISH CONNECTION FOR USER: user
<127.0.0.1> REMOTE_MODULE command whoami #USE_SHELL
<127.0.0.1> EXEC ssh -C -tt -vvv -o ControlMaster=no -o ControlPersist=60s -o ControlPath="/home/user/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 127.0.0.1 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1441230057.36-259464032203616 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1441230057.36-259464032203616 && echo $HOME/.ansible/tmp/ansible-tmp-1441230057.36-259464032203616'
<127.0.0.1> PUT /tmp/tmpTl1pSA TO /home/user/.ansible/tmp/ansible-tmp-1441230057.36-259464032203616/command
<127.0.0.1> EXEC ssh -C -tt -vvv -o ControlMaster=no -o ControlPersist=60s -o ControlPath="/home/user/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 127.0.0.1 /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=sbxutbdsogptamywtoqjjquiwhvcuppw] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-sbxutbdsogptamywtoqjjquiwhvcuppw; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/user/.ansible/tmp/ansible-tmp-1441230057.36-259464032203616/command; rm -rf /home/user/.ansible/tmp/ansible-tmp-1441230057.36-259464032203616/ >/dev/null 2>&1'"'"''
changed: [admin_ui] => {"changed": true, "cmd": "whoami", "delta": "0:00:00.003134", "end": "2015-09-02 16:40:58.078419", "rc": 0, "start": "2015-09-02 16:40:58.075285", "stderr": "", "stdout": "root", "warnings": []}
```

Is there more to reproduce your issue?

**Comment by jimi-c** [comment] 2015-09-09 22:54
Since there has been no follow-up in the past 7 days, we're going to go ahead and close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-09-09 22:54 UTC
Labels: P2, pending_action, bug
