### ISSUE TITLE
Lookup plugins not found bug.

### ISSUE THREAD

**Issue by sky-shiny** [ansible/ansible#11706] opened 2015-07-23 13:56 UTC
Issue type:
Bug report

Ansible version:

```
ansible --version
ansible 2.0.0
  configured module search path = None
```

If I run the playbook on an earlier version of ansible 2.0.0, my plugin gets found and executes correctly.

---

I have lookup plugins defined in my ansible.cfg as:

```
lookup_plugins: ./lookup_plugins
```

ls lookup_plugins/os_private_fip.py

```
lookup_plugins/os_private_fip.py
```

When I run a play which does the following:

```
- add_host: name={{ lookup('os_private_fip', 'dbd-mysql-1').split(',') | join }} groups="{{ project_prefix }}_mysql"
```

I get:

```
[ERROR]: ERROR! lookup plugin (os_private_fip) not found
```

**Comment by bcoca** [comment] 2015-07-23 16:24
closing as dupe of #11685

**Closed as completed by bcoca** 2015-07-23 16:24 UTC
Labels: P2, bug
