### ISSUE TITLE
Service module does not work for docker containers

### ISSUE THREAD

**Issue by rsyring** [ansible/ansible#16405] opened 2016-06-23 00:30 UTC
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

I've seen the problem with both:

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible']
ansible 1.9.6
  configured module search path = /usr/share/ansible
```
##### CONFIGURATION

Only using default values.
##### OS / ENVIRONMENT

Control host: Ubuntu 14.04
Connecting to: Ubuntu 14.04 on Docker version 1.9.1, build a34a1d5
##### SUMMARY

When using Ansible to connect to a docker container, restarting services using the service module does not work.  The task returns with a "changed" status but the process has not actually been restarted.

Verified with both the sshd service and the nginx service.
##### STEPS TO REPRODUCE

Build a docker image that can be used for this.  Example Dockerfile:

``` Dockerfile
# Use phusion/baseimage as base image. To make your builds reproducible, make
# sure you lock down to a specific version, not to `latest`!
# See https://github.com/phusion/baseimage-docker/blob/master/Changelog.md for
# a list of version numbers.
FROM phusion/baseimage:0.9.18

# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]

RUN rm -f /etc/service/sshd/down

# Regenerate SSH host keys. baseimage-docker does not contain any, so you
# have to do that yourself. You may also comment out this instruction; the
# init system will auto-generate one during boot.
RUN /etc/my_init.d/00_regen_ssh_host_keys.sh

# Keep this all by it's lonesome so we use the Docker cache and speed up development.
RUN apt-get update -q \
    && apt-get install -y python2.7 \
    && ln -s /usr/bin/python2.7 /usr/bin/python

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
```

Work with the docker image to get a container running:

``` shell
$ docker build -t ansible-service-bug .
$ docker run ansible-service-bug /sbin/my_init --enable-insecure-key

# open new terminal
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS             PORTS               NAMES
310b7a26d6ed        nsible-service-bug   "/sbin/my_init --enab"   5 seconds ago       Up 5 seconds                            sad_goodall
$ docker inspect -f "{{ .NetworkSettings.IPAddress }}" sad_goodall
172.17.0.2
```

Download the insecure key, test the ssh connection, verify the port sshd is running on:

``` shell
$ curl -o insecure_key -fSL https://github.com/phusion/baseimage-docker/raw/master/image/services/sshd/keys/insecure_key
$ ssh -i insecure_key root@172.17.0.2
root@310b7a26d6ed: cat /var/run/sshd.pid
22  # this number could be different, but note it
```

Run the following playbook:

``` yaml
- hosts: all
  vars:
    ansible_ssh_user: root
  gather_facts: false
  tasks:
    - service: name=ssh state=restarted
```

With the following command:

``` shell
$ ansible-playbook -i 172.17.0.2, playbook.yaml --private-key insecure_key 

PLAY [all] ******************************************************************** 

TASK: [service name=ssh state=restarted] ************************************** 
changed: [172.17.0.2]

PLAY RECAP ******************************************************************** 
172.17.0.2                 : ok=1    changed=1    unreachable=0    failed=0  
```

Now, in the ssh connection that should still be open to the docker container:

``` shell
root@310b7a26d6ed: cat /var/run/sshd.pid
22  # this number could be different, but note it
```
##### EXPECTED RESULTS

I expected the pid of the sshd server to change.
##### ACTUAL RESULTS

The restart task returns with a "changed" status but the service is not actually restarted.
##### ADDITIONAL INFO
- I have verified the same behavior with nginx service.
- I have verified that the service module works correctly when connecting to a non-docker server running on Linode.
- I have verified that the service can be restarted using the init file directly and bypassing the service module.  See below for further details:

Change the playbook to:

``` yaml
- hosts: all
  vars:
    ansible_ssh_user: root
  gather_facts: false
  tasks:
    - command: /etc/init.d/ssh restart
```

Run it again:

``` shell
$ ansible-playbook -i 172.17.0.2, playbook.yaml --private-key insecure_key 

PLAY [all] ******************************************************************** 

TASK: [command /etc/init.d/ssh restart] *************************************** 
changed: [172.17.0.2]

PLAY RECAP ******************************************************************** 
172.17.0.2                 : ok=1    changed=1    unreachable=0    failed=0  
```

And in the ssh connection that should still be open to the docker container:

``` shell
root@310b7a26d6ed: cat /var/run/sshd.pid
132  # this number could be different, but it should be different from the commands ran earlier.
```

**Comment by bcoca** [comment] 2016-06-23 17:16
~~dupe of https://github.com/ansible/ansible-modules-core/issues/593~~ sorry, seems diff issue

**Comment by bcoca** [comment] 2016-06-23 17:19
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!

**Closed as completed by bcoca** 2016-06-23 17:19 UTC
Labels: docker, bug

**Comment by rsyring** [comment] 2016-06-23 17:27
I have resubmitted: https://github.com/ansible/ansible-modules-core/issues/4024
