### ISSUE TITLE
delegate_to with with_items runs only at the first item

### ISSUE THREAD

**Issue by kamsz** [ansible/ansible#14690] opened 2016-02-27 12:02 UTC
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

Default configuration.
##### Environment:

Running Ansible from Ubuntu 15.10, target machines are Ubuntu 14.04
##### Summary:

When using delegate_to with with_items consisting of host names that it should delegate, SSH connection is done only to the first host. Because of that, task that should be performed at the second host is performed twice at the first one.
##### Steps To Reproduce:

Example playbook:

```
- hosts: localhost
  vars:
    host1: 10.251.2.17
    host2: 10.251.2.21
  tasks:
    - name: test
      shell: echo "test"
      delegate_to: "{{item}}"
      with_items:
        - "{{host1}}"
        - "{{host2}}"
```

Inventory:

```
10.251.2.17 ansible_user=root
10.251.2.21 ansible_user=root
```
##### Expected Results:

The task should be performed at each of the hosts from with_items list.
##### Actual Results:

Task ran twice at the first host from the list despite the output saying it was delegated to the second one. 

```
Using /etc/ansible/ansible.cfg as config file
Loaded callback default of type stdout, v2.0

PLAYBOOK: test.yml *************************************************************
1 plays in test.yml

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ESTABLISH LOCAL CONNECTION FOR USER: kamil
127.0.0.1 EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1456574514.91-27382360578439 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1456574514.91-27382360578439 `" )'
127.0.0.1 PUT /tmp/tmpf6shKH TO /home/kamil/.ansible/tmp/ansible-tmp-1456574514.91-27382360578439/setup
127.0.0.1 EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/kamil/.ansible/tmp/ansible-tmp-1456574514.91-27382360578439/setup; rm -rf "/home/kamil/.ansible/tmp/ansible-tmp-1456574514.91-27382360578439/" > /dev/null 2>&1'
ok: [localhost]

TASK [test] ********************************************************************
task path: /home/kamil/Documents/bug_reproductions/ansible/delegate_to_with_items/test.yml:6
<10.251.2.17> ESTABLISH SSH CONNECTION FOR USER: root
<10.251.2.17> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/kamil/.ansible/cp/ansible-ssh-%h-%p-%r -tt 10.251.2.17 '/bin/sh -c '"'"'mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1456574515.23-244445542226991 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1456574515.23-244445542226991 `"'"'"''
<10.251.2.17> PUT /tmp/tmpY0P9eV TO /root/.ansible/tmp/ansible-tmp-1456574515.23-244445542226991/command
<10.251.2.17> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/kamil/.ansible/cp/ansible-ssh-%h-%p-%r '[10.251.2.17]'
<10.251.2.17> ESTABLISH SSH CONNECTION FOR USER: root
<10.251.2.17> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/kamil/.ansible/cp/ansible-ssh-%h-%p-%r -tt 10.251.2.17 '/bin/sh -c '"'"'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1456574515.23-244445542226991/command; rm -rf "/root/.ansible/tmp/ansible-tmp-1456574515.23-244445542226991/" > /dev/null 2>&1'"'"''
changed: [localhost -> 10.251.2.17] => (item=10.251.2.17) => {"changed": true, "cmd": "echo \"test\"", "delta": "0:00:00.001340", "end": "2016-02-27 12:01:55.523066", "invocation": {"module_args": {"_raw_params": "echo \"test\"", "_uses_shell": true, "chdir": null, "creates": null, "executable": null, "removes": null, "warn": true}, "module_name": "command"}, "item": "10.251.2.17", "rc": 0, "start": "2016-02-27 12:01:55.521726", "stderr": "", "stdout": "test", "stdout_lines": ["test"], "warnings": []}
<10.251.2.17> ESTABLISH SSH CONNECTION FOR USER: root
<10.251.2.17> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/kamil/.ansible/cp/ansible-ssh-%h-%p-%r -tt 10.251.2.17 '/bin/sh -c '"'"'mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1456574515.53-233203927776568 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1456574515.53-233203927776568 `"'"'"''
<10.251.2.17> PUT /tmp/tmpvZ9Nw1 TO /root/.ansible/tmp/ansible-tmp-1456574515.53-233203927776568/command
<10.251.2.17> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/kamil/.ansible/cp/ansible-ssh-%h-%p-%r '[10.251.2.17]'
<10.251.2.17> ESTABLISH SSH CONNECTION FOR USER: root
<10.251.2.17> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/kamil/.ansible/cp/ansible-ssh-%h-%p-%r -tt 10.251.2.17 '/bin/sh -c '"'"'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1456574515.53-233203927776568/command; rm -rf "/root/.ansible/tmp/ansible-tmp-1456574515.53-233203927776568/" > /dev/null 2>&1'"'"''
changed: [localhost -> 10.251.2.21] => (item=10.251.2.21) => {"changed": true, "cmd": "echo \"test\"", "delta": "0:00:00.001206", "end": "2016-02-27 12:01:55.682437", "invocation": {"module_args": {"_raw_params": "echo \"test\"", "_uses_shell": true, "chdir": null, "creates": null, "executable": null, "removes": null, "warn": true}, "module_name": "command"}, "item": "10.251.2.21", "rc": 0, "start": "2016-02-27 12:01:55.681231", "stderr": "", "stdout": "test", "stdout_lines": ["test"], "warnings": []}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0
```

**Comment by bcoca** [comment] 2016-02-29 16:03
closing as dupe of #14166

**Closed as completed by bcoca** 2016-02-29 16:03 UTC
