### ISSUE TITLE
Using template on a file without Jinja blocks results in the template being copied instead

### ISSUE THREAD

**Issue by DaCookie4u** [ansible/ansible#14497] opened 2016-02-16 09:30 UTC
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.0.2
  config file = 
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

No global or local changes to the ansible.cfg
##### Environment:

Mac OS X El Capitan
##### Summary:

Using the template module on a "template" without actual `{% ... %}` blocks result in ansible copying the file. This is a problem if there are actually Jinja comments in the file or even tags at the beginning.
##### Steps To Reproduce:

Create a template like this

```
#jinja2:lstrip_blocks: True

{# create dummy entry, otherwise delete throws a warning #}
set security policies default-policy deny-all
{# start with a clean slate #}
delete security policies
set security policies default-policy deny-all
```
##### Expected Results:

I would expect the comments and the jinja2 tag at the beginning to be stripped.
##### Actual Results:

The file will be created as is, without the removal of neither the tag nor the comments.

**Comment by bcoca** [comment] 2016-02-16 14:47
dupe of #13831

**Closed as completed by bcoca** 2016-02-16 14:47 UTC
