### ISSUE TITLE
ERROR! 'win_iis_website' is not a valid attribute for a Play

### ISSUE THREAD

**Issue by jirifusek** [ansible/ansible#13503] opened 2015-12-10 11:16 UTC
Issue Type: Bug Report
Ansible Version: 2.0.0 0.7.rc2
Commit: cc98528ecbadaff6d2401207c0fa002607768216
Ansible Configuration: no changes
Environment: Control system=Ubuntu 14.04 LTS / Client system=Windows 2012 R2 Datacenter

Direct ansible command works fine, but "playbook" version which is only slightly changed official example from ansible documentation not work. http://docs.ansible.com/ansible/win_iis_website_module.html#options

Any advice ?

![ansible_win_iis_website_playbook](https://cloud.githubusercontent.com/assets/16178711/11714070/a7914abe-9f37-11e5-82bc-72847ab0b0f5.png)
![ansible_error](https://cloud.githubusercontent.com/assets/16178711/11714072/a96e3a4a-9f37-11e5-840a-207b6a7cb050.png)

**Comment by jhawkesworth** [comment] 2015-12-10 12:46
I think possibly your playbook isn't specifying any hosts and this might be affecting the path which is being searched for ansible modules, so possibly you are only picking up the modules which run on linux.

I suggest adding 
hosts: windows 
at the beginning of your playbook and see if that fixes it.

**Comment by jirifusek** [comment] 2015-12-10 15:20
Thank you for advice. Code below works fine (sorry for formating)
- name: Create IIS site<br>
  hosts: windows<br>
  gather_facts: false<br>
  tasks:<br>
  - name: copy<br>
    win_iis_website:<br>
      name: "Acme"<br>
      state: started<br>
      port: 42991<br>
      physical_path: 'c:\data\IIS\MyApp\'<br>
    register: website<br>

**Comment by jhawkesworth** [comment] 2015-12-10 17:15
Please can you close this issue then?

If you aren't certain that some behavior you are seeing is a bug, it might be best to ask on the ansible-project google group: https://groups.google.com/forum/#!forum/ansible-project rather than here, or on the irc channel - #ansible on irc.freenode.net , as you will reach many more people, rather than just those who follow the bug reports.

**Comment by bcoca** [comment] 2015-12-13 17:30
closing this as it seemed to be a malformed play and I cannot reproduce the issue otherwise.

**Closed as completed by bcoca** 2015-12-13 17:30 UTC
Labels: windows
