### ISSUE TITLE
ansible-galaxy fails to create new collections from skeleton

### ISSUE THREAD

**Issue by greg-hellings** [ansible/ansible#72357] opened 2020-10-27 14:30 UTC
##### SUMMARY
Ansible Galaxy fails to create a new directory from a given collection skeleton directory, exiting with a Python stack trace

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Galaxy CLI

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.10.2
  config file = /home/ghelling/.ansible.cfg
  configured module search path = ['/home/ghelling/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ghelling/venv/tools3/lib64/python3.7/site-packages/ansible
  executable location = /home/ghelling/venv/tools3/bin/ansible
  python version = 3.7.9 (default, Aug 19 2020, 17:05:11) [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]
```

##### CONFIGURATION
```
ANSIBLE_COW_SELECTION(/home/ghelling/.ansible.cfg) = tux
ANSIBLE_NOCOWS(/home/ghelling/.ansible.cfg) = True
ANSIBLE_PIPELINING(/home/ghelling/.ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/ghelling/.ansible.cfg) = -o ControlMaster=auto -o ControlPersist=600s -o IdentitiesOnly=yes
ANSIBLE_SSH_CONTROL_PATH(/home/ghelling/.ansible.cfg) = %(directory)s/%%h-%%r
ANSIBLE_SSH_CONTROL_PATH_DIR(/home/ghelling/.ansible.cfg) = /tmp
COLLECTIONS_PATHS(env: ANSIBLE_COLLECTIONS_PATHS) = ['/home/ghelling/src', '/home/ghelling/.ansible']
DEFAULT_CALLBACK_WHITELIST(/home/ghelling/.ansible.cfg) = ['timer', 'profile_tasks']
DEFAULT_FORKS(/home/ghelling/.ansible.cfg) = 10
DEFAULT_STDOUT_CALLBACK(/home/ghelling/.ansible.cfg) = yaml
GALAXY_ROLE_SKELETON_IGNORE(/home/ghelling/.ansible.cfg) = ['^.git$', '^.*/.git_keep$', '\\..*.swp']
HOST_KEY_CHECKING(/home/ghelling/.ansible.cfg) = False
```

##### OS / ENVIRONMENT
Fedora 31 host local workstation
Ubuntu 18.04 host Github Actions
Ubuntu 20.04 host Github Actions

##### STEPS TO REPRODUCE
```shell
$ git clone https://github.com/oasis-roles/meta_ansible_collection_template
$ ansible-galaxy collection init --collection-sekeleton meta_ansible_collection_template test_ns.test_collection -vvv
```

##### EXPECTED RESULTS
A new collection is created based on the specified skeleton at test_ns/test_collection

##### ACTUAL RESULTS

Local run:

```paste
ansible-galaxy 2.10.2
  config file = /home/ghelling/.ansible.cfg
  configured module search path = ['/home/ghelling/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ghelling/venv/tools3/lib64/python3.7/site-packages/ansible
  executable location = /home/ghelling/venv/tools3/bin/ansible-galaxy
  python version = 3.7.9 (default, Aug 19 2020, 17:05:11) [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]
Using /home/ghelling/.ansible.cfg as config file
ERROR! Unexpected Exception, this is probably a bug: [Errno 2] No such file or directory: './test_ns/test_collection/.git/description'
the full traceback was:

Traceback (most recent call last):
  File "/home/ghelling/venv/tools3/bin/ansible-galaxy", line 123, in <module>
    exit_code = cli.run()
  File "/home/ghelling/venv/tools3/lib64/python3.7/site-packages/ansible/cli/galaxy.py", line 490, in run
    context.CLIARGS['func']()
  File "/home/ghelling/venv/tools3/lib64/python3.7/site-packages/ansible/cli/galaxy.py", line 909, in execute_init
    shutil.copyfile(os.path.join(root, f), os.path.join(obj_path, f_rel_path))
  File "/usr/lib64/python3.7/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: './test_ns/test_collection/.git/description'
```

*See also this* [Github Actions run](https://github.com/oasis-roles/meta_ansible_collection_template/runs/1315042644?check_suite_focus=true)

**Comment by sivel** [comment] 2020-10-27 14:33
Duplicate of https://github.com/ansible/ansible/issues/71977

**Closed as completed by sivel** 2020-10-27 14:33 UTC
