### ISSUE TITLE
Feature idea: Adding filter to with_subelements

### ISSUE THREAD

**Issue by udondan** [ansible/ansible#8097] opened 2014-07-11 08:46 UTC
##### Issue Type:

Feature Idea
##### Ansible Version:

Not applicable
##### Environment:

Not applicable
##### Summary:

I have a pretty complex and big configuration for a redis cluster, stored in my group-vars, defining multiple pools, multiple rings for each pool, replication paths, proxy config,...

Stripped down it looks like this:

``` yml
rediscluster:
  pools:
    - customer: abc
      instances:
        - &instance1
          host: A
          ring: master
        - &instance2
          host: B
          ring: master
        - &instance3
          host: A
          ring: readonly1
          slaveOf: *instance2
        - &instance4
          host: B
          ring: readonly1
          slaveOf: *instance1
    - customer: cde
      instances:
        -...
        -...
```

In my playbook to manage the cluster I loop trough all customers and their instances with:

```
  action: do somthing
  with_subelements:
     - rediscluster.pools
     - instances
  when: item[1].host == inventory_hostname
```

and that works fine. The only thing ugly here is it loops over every instance on every host, which in this example contains 4 skipped and 4 ok/changed tasks. In this small example that's not of a big issue but imagine there are 20 hosts, 5 customers and 3 rings. Then there are hundreds of skipped entries.

A solution would be to actually include the `when` condition _into_ the loop and not iterating over the entry if the condition fails.

Ideally one could use jinja filter like this:

```
  action: do somthing
  with_subelements:
     - rediscluster.pools
     - instances|selectattr('host', inventory_hostname)
```

Or you could set the condition as a 3rd element of the list:

```
  action: do somthing
  with_subelements:
     - rediscluster.pools
     - instances
     - item[1].host == inventory_hostname
```

First variant would be convenient as you have all the handy filters available, though you are limited in your condition to content of the inner loop. In the 2nd variant you could have a combined condition of the outer and inner element. (not required in my example, might be different use case)

I tried myself - w/o any Python knowledge - on this and was only able to come up with a bad solution of the 2nd variant. I saved it as another filter "subelements_filter.py" and it can be used like this:

```
  action: do something
  with_subelements_filter:
     - rediscluster.pools
     - instances
     - item[1]["host"] == "{{inventory_hostname}}"
```

So of course the inventory_hostname is not available in the python script so it needs to be evaluated in the playbooks tasks. And for some reason item[1].host throws a Python error (again, no Python experience available here) so it needs to be written as item[1]["host"]. Most ugly part though might be that I use `eval` to test the condition but I don't see a way around it.

Even though it's ugly it does the trick for me now. But I would really love to see such (improved) feature in a future version.

``` python
# (c) 2013, Serge van Ginderachter <serge@vanginderachter.be>
#
# This file is part of Ansible
#
# Ansible is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Ansible is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Ansible.  If not, see <http://www.gnu.org/licenses/>.

import ansible.utils as utils
import ansible.errors as errors

class LookupModule(object):

    def __init__(self, basedir=None, **kwargs):
        self.basedir = basedir


    def run(self, terms, inject=None, **kwargs):
        terms = utils.listify_lookup_plugin_terms(terms, self.basedir, inject)
        terms[0] = utils.listify_lookup_plugin_terms(terms[0], self.basedir, inject)

        if not isinstance(terms, list) or (not len(terms) == 2 and not len(terms) == 3):
            raise errors.AnsibleError(
                "subelements lookup expects a list of two items, first a dict or a list, and second a string")
        terms[0] = utils.listify_lookup_plugin_terms(terms[0], self.basedir, inject)
        if not isinstance(terms[0], (list, dict)) or not isinstance(terms[1], basestring):
            raise errors.AnsibleError(
                "subelements lookup expects a list of two items, first a dict or a list, and second a string")

        if isinstance(terms[0], dict): # convert to list:
            if terms[0].get('skipped',False) != False:
                # the registered result was completely skipped
                return []
            elementlist = []
            for key in terms[0].iterkeys():
                elementlist.append(terms[0][key])
        else: 
            elementlist = terms[0]
        subelement = terms[1]

        ret = []
        item = [0, 1]
        for item[0] in elementlist:
            if not isinstance(item[0], dict):
                raise errors.AnsibleError("subelements lookup expects a dictionary, got '%s'" %item[0])
            if item[0].get('skipped',False) != False:
                # this particular item is to be skipped
                continue 
            if not subelement in item[0]:
                raise errors.AnsibleError("could not find '%s' key in iterated item '%s'" % (subelement, item[0]))
            if not isinstance(item[0][subelement], list):
                raise errors.AnsibleError("the key %s should point to a list, got '%s'" % (subelement, item[0][subelement]))
            sublist = item[0].pop(subelement, [])

            for item[1] in sublist:
                if len(terms) != 3 or eval(terms[2]):
                    ret.append((item[0], item[1]))

        return ret
```

I changed the loop vars from `item0` to `item[0]` and `item1` to `item[1]` so the condition can be defined with the known item names from all other loops.
##### Steps To Reproduce:

Not applicable 
##### Expected Results:

Not applicable
##### Actual Results:

Not applicable

**Comment by tkellen** [comment] 2015-04-23 21:58
:+1:

**Comment by marcinhlybin** [comment] 2016-03-04 14:44
You could flatten the data and filter it before looping like this:

```
- hosts: localhost
  vars:
    rediscluster:
      abc:
        - { name: instance1, host: A, ring: master }
        - { name: instance2, host: B, ring: master }
        - { name: instance3, host: A, ring: readonly1, slaveOf: instance1 }
      def:
        - { name: instance4, host: A, ring: master }
        - { name: instance5, host: B, ring: master }
        - { name: instance6, host: A, ring: readonly1, slaveOf: instance4 }

  tasks:
    - set_fact:
        pools: "{{ rediscluster['abc'] | selectattr('host', 'equalto', 'A') | list}}"

    - debug: var=pools
```

The problem is with double looping - first is by customer and second is by pools. It can be solved with `include` and `with_items` construction but still you will have plenty of output while running playbooks.

If I would want to keep all servers in one place I would flatten the data structure completely and then do filtering when I need. For example:

```
rediscluster:
  - { customer: abc, name: instance1, host: A, ring: master }
  - { customer: abc, name: instance2, host: B, ring: master }
  - { customer: abc, name: instance3, host: A, ring: readonly1, slaveOf: instance1 }
  - { customer: def, name: instance4, host: A, ring: master }
  - { customer: def, name: instance5, host: B, ring: master }
  - { customer: def, name: instance6, host: A, ring: readonly1, slaveOf: instance4 }
```

However it is ideally to keep data per server in group_vars and host_vars and not to have enormous structure with all information. For example:

host_vars/A.yml:

```
redis_servers:
  - { name: instance1, customer: abc, role: master }
  - { name: instance2, customer: def, role: slave }
```

Kind regards.

**Comment by udondan** [comment] 2016-03-04 15:15
I'm not working on this project anymore, so currently I have no need for it. But in general now I do the filtering like you suggested.

```
selectattr('host', 'equalto', 'A')
```

Just curious, does this actually work for you? The `equalto` filter was never available for me in any version of Ansible from ~1.5 to the current 2.0.1. Ansible complains it does not know the filter. And this is not only on a single machine where I might have messed something up. It's in general on multiple CentOS based control hosts as well on my local Mac. I know it's a standard Jinja2 filter and always thought Ansible simply bundles a very old Jinja2 lib and therefore it's not available. Previously I implemented that filter myself with a custom filter plugin but now I simply use the `match` filter instead.

```
$ ansible localhost -m debug -a "msg='{{ [{'foo': 'bar'}] | selectattr('foo', 'equalto', 'bar') | list }}'"
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TemplateRuntimeError: no test named 'equalto'
localhost | FAILED! => {
    "failed": true, 
    "stdout": ""
}

$ ansible localhost -m debug -a "msg='{{ [{'foo': 'bar'}] | selectattr('foo', 'match', 'bar') | list }}'"
localhost | SUCCESS => {
    "msg": [
        {
            "foo": "bar"
        }
    ]
}
```

**Comment by marcinhlybin** [comment] 2016-03-04 15:39
Works for me. It is not a problem with `Ansible` version but `Jinja2`. Filter `equalto` was introduced in 2.8.

**Comment by jimi-c** [comment] 2016-07-09 20:32
# Switch to Proposal

Hi!

As of April of 2016, we have started using the Ansible Proposal process for large feature ideas or changes in current functionality, such as this. Because this issue has been open for so long without any action, we are going to go ahead and close it at this time. If you are still interested in seeing this new feature get into Ansible, please submit a proposal for it using this process.

https://github.com/ansible/proposals/blob/master/proposals_process_proposal.md

If you have any further questions, please let us know by stopping by our devel mailing list, or our devel IRC channel:
- #ansible-devel on Freenode
- https://groups.google.com/forum/#!forum/ansible-devel

Thank you!

**Closed as completed by jimi-c** 2016-07-09 20:32 UTC
Labels: feature
