### ISSUE TITLE
ansible-test behavior changes silently if collection not a git repo

### ISSUE THREAD

**Issue by goneri** [ansible/ansible#69953] opened 2020-06-08 20:42 UTC
#### SUMMARY

Hi all,

If we run `ansible-test sanity` in a collection that is not a git repository, we get a different result. This prevent us from testing a regular collection, installed by `ansible-galaxy`.

For instance, in `ansible-test sanity` call, `validate-module` fails:
https://c840b10bdb1c4ffd5f46-d4b4e639432347957be7d1e5f737e888.ssl.cf2.rackcdn.com/3/0a98184c5fcd07009cb520e5f8df76327169d19c/check/ansible-test-sanity-splunk/b39aa5a/job-output.html

If we run the same command in a git repository, `validate-module` succeed (there is still a `pylint` error). https://dashboard.zuul.ansible.com/t/ansible/build/ad498201ad6641238882d3b5bf919dd1

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible-test

##### ANSIBLE VERSION

```paste below
2.9
```

##### EXPECTED RESULTS

`ansible-test` should behave the same way in the two scenarios.

##### ACTUAL RESULTS

Fails if the collection is not a git repository.

**Comment by sivel** [comment] 2020-06-08 20:59
I'm not sure this is a difference in `ansible-test`, as much as it is that `ansible-galaxy collection build` dereferences symlinks.  This accounts for the `validate-modules` failures.

I've still not been able to replicate the `duplicate-code` pylint issue, but @pabelanger has been hitting this as well.

**Comment by pabelanger** [comment] 2020-06-08 21:05
How are people running ansible-test sanity from a git repo? because, i get an error locally:
```
$ ansible-test sanity
ERROR: The current working directory must be at or below:

 - an Ansible collection: {...}/ansible_collections/{namespace}/{collection}/

Current working directory: /home/pabelanger/src/github.com/ansible-collections/ansible.netcommon
```
However, for all other ansible-test things, we ansible-galaxy collection install, then run ansible-test from that folder, which causes the duplicate-code failures.

**Comment by maxamillion** [comment] 2020-06-08 21:07
@pabelanger it has to be checked out into a location that's in the [`COLLECTIONS_PATH`](https://docs.ansible.com/ansible/latest/reference_appendices/config.html#collections-paths).

**Comment by sivel** [comment] 2020-06-08 21:12
You would likely have to rename the dir, or copy to another location.  The current working dir for zuul is incompatible with the requirements of `ansible-test`.  As indicated by the error you would need to have the git clone accessible at a path that looks like:

```
{...}/ansible_collections/ansible/netcommon/
```

And you would need to be in that dir when launching `ansible-test`

**Comment by pabelanger** [comment] 2020-06-08 21:22
So, this is a little unfortunate for ansible-test sanity, we have to use a git repo, but for units and integration use compiled / installed collection. From a user POV, very confusing.

When we first started testing with ansible-test, we build everything around the idea of building the collection, installing, then tests. To give more real world setup.  What would be needed to add support for sanity for this to?

**Comment by sivel** [comment] 2020-06-08 21:27
> What would be needed to add support for sanity for this to?

I'm not sure which support you are asking for.

Ultimately the problem is more with `ansible-galaxy collection build/install` than `ansible-test`.  `install` doesn't support symlinks, so `build` de-references symlinks, but there are sanity tests that fail as a result of this de-referencing.  However, we cannot simply enable `build` to not de-reference, we need to wait until all supported Ansible versions properly support symlinks with `install` (which it doesn't yet). Otherwise installing a collection would only work with specifically linked ansible versions.  Also, we are unsure if galaxy can handle symlinks either.

**Comment by pabelanger** [comment] 2020-06-08 21:36
> > What would be needed to add support for sanity for this to?
> 
> I'm not sure which support you are asking for.
> 
Today, for sanity to work, if I am understanding properly, it has to be a git repo and not the pre-build collection downloaded from galaxy.  We'd like ansible-test sanity, to work properly with compiled collections from galaxy, this is how we do testing with all other ansible-test things.

We _can_ update our testing to use a git repo, but it would be helpful to understand why duplicate-code is not detected on git repos, but collections.

In the case of ansible.netcommon, I don't believe we have any symlinks, so I am trying to understand how that factors in here.

**Comment by sivel** [comment] 2020-06-08 21:40
I still have not been able to replicate the `duplicate-code` errors, even in this scenario.  I'll have to do more testing. My investigation has led me to believe that due to how we invoke `pylint` it should be impossible for `duplicate-code` to ever show up, but obviously something is causing it, that I cannot quantify.

**Comment by pabelanger** [comment] 2020-06-08 21:44
When I hacked on it last week, I was only able to disable 'duplicate-code' errors by adding it to the disable list: https://github.com/ansible/ansible/blob/devel/test/lib/ansible_test/_data/sanity/pylint/config/collection.cfg#L3

**Comment by sivel** [comment] 2020-06-08 21:44
Actually I missed a comment from above:

> If we run the same command in a git repository, validate-module succeed (there is still a pylint error)

So git repos seem to have nothing to do with `duplicate-code`.

But `validate-modules` is affected, which I expect due to the described behavior of `ansible-galaxy`.

**Comment by sivel** [comment] 2020-06-17 16:34
I'm going to close this now that https://github.com/ansible/ansible/pull/69959 is merged since the actual problem was in relation to `ansible-galaxy` not preserving symlinks.

**Closed as completed by sivel** 2020-06-17 16:34 UTC
Labels: support:core, bug, has_pr, affects_2.9
