### ISSUE TITLE
When built from source, ansible --version errors with "ImportError: No module named _text"

### ISSUE THREAD

**Issue by vielmetti** [ansible/ansible#20088] opened 2017-01-10 14:16 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

Ansible main program

##### ANSIBLE VERSION

```
root@docker-build-test:/mnt/src/ansible/ansible/bin# ./ansible --version
Traceback (most recent call last):
  File "./ansible", line 46, in <module>
    from ansible.module_utils._text import to_text
ImportError: No module named _text

```

##### CONFIGURATION

Building `ansible` from source. There is a system `ansible` installed, v2.0.0.2 installed from Ubuntu 16.04 for aarch64 .

##### OS / ENVIRONMENT

Ubuntu 16.04 on ARMv8 (aarch64) on 96-core server on Packet.net

##### SUMMARY

After I installed a bunch of test dependencies, all tests pass; but when I try to run `ansible --version` from the `bin/` directory of the distribution, that fails.

A similar bug identified (though not exactly the same) is #18582.

##### STEPS TO REPRODUCE

Pull the current distribution from github, this is on origin/devel.

```
# git status
On branch devel
Your branch is up-to-date with 'origin/devel'.
```

##### EXPECTED RESULTS

I expected `ansible --version` to print the version number.

##### ACTUAL RESULTS

```
root@docker-build-test:/mnt/src/ansible/ansible/bin# ./ansible -vvvv  --version
Traceback (most recent call last):
  File "./ansible", line 46, in <module>
    from ansible.module_utils._text import to_text
ImportError: No module named _text

```

**Comment by abadger** [comment] 2017-01-11 02:42
This is a duplicate of #18582.  The bin/ansible script that you are testing is most likely loading its library from the 2.0.0.2 Ubuntu package.  Ansible 2.0.x did not have the ansible.module_utils._text submodule and therefore this error will occur.  You need to either uninstall the older versions of ansible or tell python where the version of the library that you need is by setting the PYTHONPATH environment variable.

I'll paste the mailing list and IRC channel information below in case you need to seek further help.

List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Closed as completed by abadger** 2017-01-11 02:42 UTC
Labels: affects_2.3, bug
