### ISSUE TITLE
ec2_elb module: registering instance in EC2 ELB that has never been registered before errors (but succeeds)

### ISSUE THREAD

**Issue by jmhodges** [ansible/ansible#5305] opened 2013-12-16 09:47 UTC
Waitng for an EC2 instance that's never been registered in the EC2 ELB will toss an error out making it clear that there's a missing None check, but actually succeed in registering the instance. (Expected behavior is to succeed in registration, but not error out.)

   TASK: [Register ec2 instance in elb] *****************************************\* 
   failed: [ec2-54-203-235-190.us-west-2.compute.amazonaws.com] => (item=howsmyssl-simple-lb) => {"failed": true, "item": "howsmyssl-simple-lb", "parsed": false}
   invalid output was: Traceback (most recent call last):
     File "/home/vagrant/.ansible/tmp/ansible-1387186986.07-257339729518743/ec2_elb", line 1410, in <module>
       main()
     File "/home/vagrant/.ansible/tmp/ansible-1387186986.07-257339729518743/ec2_elb", line 333, in main
       elb_man.register(wait, enable_availability_zone)
     File "/home/vagrant/.ansible/tmp/ansible-1387186986.07-257339729518743/ec2_elb", line 168, in register
       self._await_elb_instance_state(lb, 'InService', initial_state)
     File "/home/vagrant/.ansible/tmp/ansible-1387186986.07-257339729518743/ec2_elb", line 213, in _await_elb_instance_state
       if instance_state.state != initial_state.state:
   AttributeError: 'NoneType' object has no attribute 'state'

with the task definition being:

```
 post_tasks:
   - name: Register ec2 instance in elb
     local_action: ec2_elb
     args:
       region: 'us-west-2'
       instance_id: "{{ ansible_ec2_instance_id }}"
       ec2_elbs: "{{ item }}"
       state: 'present'
       wait: yes # the important bit, I think.
     with_items: ec2_elbs
```

**Comment by lancelakey** [comment] 2014-01-06 18:40
Update: I just noticed this bug report appears to be related to the PR in #5506

Bug report:
ansible 1.5 (devel ccbc99fe4f) last updated 2014/01/06 16:57:45 (GMT +000)
boto==2.22.0

I too am seeing this error on the devel branch. I'm using the devel branch because of an ec2_elb bug which is fixed on the devel branch. Even though an error is produced the instance is actually registered with the ELB. At the moment I'm ignoring the error.

What I expected to happen:
Successful instance registration with ELB
No error thrown

What actually happened:
I consistently see either one of the two following errors:
AttributeError: 'NoneType' object has no attribute 'state'
The instance i-f72a41eb could not be put in service on LoadBalancer

``` shell
TASK: [ELB registration] ****************************************************** 
<host.example.com> REMOTE_MODULE ec2_elb region=us-west-1 instance_id=i-0e1faa99 ec2_elbs='example' state='present' wait='yes'
<host.example.com> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-1388946237.65-116608561295020 && echo $HOME/.ansible/tmp/ansible-1388946237.65-116608561295020']
<host.example.com> PUT /tmp/tmphX58ch TO /root/.ansible/tmp/ansible-1388946237.65-116608561295020/ec2_elb
<host.example.com> EXEC ['/bin/sh', '-c', '/usr/bin/python2 /root/.ansible/tmp/ansible-1388946237.65-116608561295020/ec2_elb; rm -rf /root/.ansible/tmp/ansible-1388946237.65-116608561295020/ >/dev/null 2>&1']
failed: [host.example.com] => (item=i-0e1faa99) => {"failed": true, "item": "i-0e1faa99", "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1388946237.65-116608561295020/ec2_elb", line 1410, in <module>
    main()
  File "/root/.ansible/tmp/ansible-1388946237.65-116608561295020/ec2_elb", line 333, in main
    elb_man.register(wait, enable_availability_zone)
  File "/root/.ansible/tmp/ansible-1388946237.65-116608561295020/ec2_elb", line 168, in register
    self._await_elb_instance_state(lb, 'InService', initial_state)
  File "/root/.ansible/tmp/ansible-1388946237.65-116608561295020/ec2_elb", line 213, in _await_elb_instance_state
    if instance_state.state != initial_state.state:
AttributeError: 'NoneType' object has no attribute 'state'
```

``` shell
<host.example.com> REMOTE_MODULE ec2_elb region=us-west-1 instance_id=i-f72a41eb ec2_elbs='example' state='present' wait='yes'
<host.example.com> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-1389028991.97-14471314645228 && echo $HOME/.ansible/tmp/ansible-1389028991.97-14471314645228']
<host.example.com> PUT /tmp/tmpygnwye TO /root/.ansible/tmp/ansible-1389028991.97-14471314645228/ec2_elb
<host.example.com> EXEC ['/bin/sh', '-c', '/usr/bin/python2 /root/.ansible/tmp/ansible-1389028991.97-14471314645228/ec2_elb; rm -rf /root/.ansible/tmp/ansible-1389028991.97-14471314645228/ >/dev/null 2>&1']
failed: [host.example.com] => (item=i-f72a41eb) => {"failed": true, "item": "i-f72a41eb"}
msg: The instance i-f72a41eb could not be put in service on LoadBalancer:example. Reason: Instance has not passed the configured HealthyThreshold number of health checks consecutively.
```

``` yml
- name: ELB registration
  ec2_elb:
    region={{region}}
    instance_id={{item}}
    ec2_elbs='example'
    state='present'
    wait='yes'
  with_items: hostvars[inventory_hostname]['ansible_ec2_instance_id']
  register: result
  ignore_errors: yes 
```

**Comment by andrewvc** [comment] 2014-02-14 21:31
+1 I think I'm seeing this as well.

Also, Hi @lancelakey , I'll see you at SCALE12x!

**Comment by ftokarev** [comment] 2014-02-17 10:19
+1, I'm seeing the same message: "Instance has not passed the configured HealthyThreshold number of health checks consecutively."

**Comment by majksner** [comment] 2014-02-20 14:57
I'm having slight different issue, but it seems it's caused by boto. It looks like boto doesn't read ENV variables. If I don't pass AWS keys directly as:

```
- name: Add Instance to Existing ELB
      ec2_elb:
        instance_id={{item}}
        ec2_elbs=elbname
        state=present
        wait=yes
      with_items: ansible_ec2_instance_id
      ignore_errors: true
```

I'm getting:

```
msg: No handler was ready to authenticate. 1 handlers were checked. ['QuerySignatureV2AuthHandler'] Check your credentials
```

If I do pass aws keys directly in ec2_elb:

```
fatal: [xx.xx.xx.xxx] => failed to parse: SUDO-SUCCESS-osfqsmbvtallovfmdeashwziidpbpptp
Traceback (most recent call last):
  File "/home/ubuntu/.ansible/tmp/ansible-1392907831.65-184796585941000/ec2_elb", line 1365, in <module>
    main()
  File "/home/ubuntu/.ansible/tmp/ansible-1392907831.65-184796585941000/ec2_elb", line 282, in main
    aws_secret_key, region=region)
  File "/home/ubuntu/.ansible/tmp/ansible-1392907831.65-184796585941000/ec2_elb", line 133, in __init__
    self.lbs = self._get_instance_lbs(ec2_elbs)
  File "/home/ubuntu/.ansible/tmp/ansible-1392907831.65-184796585941000/ec2_elb", line 229, in _get_instance_lbs
    elbs = elb.get_all_load_balancers()
  File "/usr/lib/python2.7/dist-packages/boto/ec2/elb/__init__.py", line 127, in get_all_load_balancers
    [('member', LoadBalancer)])
  File "/usr/lib/python2.7/dist-packages/boto/connection.py", line 882, in get_list
    response = self.make_request(action, params, path, verb)
  File "/usr/lib/python2.7/dist-packages/boto/connection.py", line 868, in make_request
    return self._mexe(http_request)
  File "/usr/lib/python2.7/dist-packages/boto/connection.py", line 794, in _mexe
    raise e
socket.gaierror: [Errno -2] Name or service not known

FATAL: all hosts have already failed -- aborting
```

**Comment by coopernurse** [comment] 2014-02-28 17:00
I'm also getting the error @majksner noted:

```
ec2-54-81-220-105.compute-1.amazonaws.com | FAILED => failed to parse: SUDO-SUCCESS-kdmrmxudcbrpisyakwwhueqqtnwfeiuo
Traceback (most recent call last):
  File "/home/ec2-user/.ansible/tmp/ansible-1393606590.31-92743205750234/ec2_elb", line 1365, in <module>
    main()
  File "/home/ec2-user/.ansible/tmp/ansible-1393606590.31-92743205750234/ec2_elb", line 282, in main
    aws_secret_key, region=region)
  File "/home/ec2-user/.ansible/tmp/ansible-1393606590.31-92743205750234/ec2_elb", line 133, in __init__
    self.lbs = self._get_instance_lbs(ec2_elbs)
  File "/home/ec2-user/.ansible/tmp/ansible-1393606590.31-92743205750234/ec2_elb", line 229, in _get_instance_lbs
    elbs = elb.get_all_load_balancers()
...
  File "/usr/lib/python2.6/site-packages/boto/https_connection.py", line 111, in connect
    sock.connect((self.host, self.port))
  File "<string>", line 1, in connect
socket.gaierror: [Errno -2] Name or service not known
```

This is with Ansible 1.4.5 and boto 2.26.0

**Comment by coopernurse** [comment] 2014-02-28 17:04
Ah, I think I see what's causing my error.  `region` can't be reliably inferred from the environment.  Passing that explicitly solved my problem.  If you're using EC2 dynamic inventory, you can do something like this:

```
- name: register with elb
  ec2_elb: >
    ec2_elbs={{ servicesELB }} instance_id={{ ec2_id }} state=present
    region={{ ec2_region }}
    aws_access_key={{ lookup('env','AWS_ACCESS_KEY_ID') }} 
    aws_secret_key={{ lookup('env','AWS_SECRET_ACCESS_KEY') }}
```

`ec2_region` will get scoped in automatically.

**Comment by jimi-c** [comment] 2014-03-06 20:02
I've gone ahead and merged the above patch into the development branch. Please let us know if you continue to see the issue described above. Thanks!

**Comment by mpeters** [comment] 2014-06-30 14:46
This seems to be a problem again. And looking at the code in library/cloud/ec2_elb.py it seems the patch from 7b5f881 has been reverted in the latest dev branch:

```
ansible 1.7 (devel 14cf3c4d2a) last updated 2014/06/30 14:24:17 (GMT +000)
```

**Comment by jimi-c** [comment] 2014-07-05 03:35
It was reverted due to a problem, however I'm a little fuzzy on the details now. The commit that backed it out was 6e809c2be360b9684baf72f52861add1dd5c1a45, which is reported as fixing https://github.com/ansible/ansible/issues/6543. So I guess we'll need to figure out a different fix for this. Re-opening.

**Comment by mpdehaan** [comment] 2014-09-29 20:45
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Closed as completed by mpdehaan** 2014-09-29 20:45 UTC
Labels: cloud, bug

**Comment by xuchen81** [comment] 2015-07-20 23:44
+1 seeing it on 1.9.2

**Comment by jimi-c** [comment] 2015-07-21 01:06
@cx44yale could you please open a new issue for that? Thanks!
