### ISSUE TITLE
Ansible pause module fails to abort 

### ISSUE THREAD

**Issue by binbashroot** [ansible/ansible#14749] opened 2016-03-02 12:23 UTC
##### Issue Type:

- Bug Report
  ##### Ansible Version:

```
ansible 2.0.1.0

```
##### Summary:

Ansible pause module fails to abort when more than one host is defined is defined in the inventory file
Bug first reported in Ansible 2.0.0.1  bug number 14252 which was closed but appears to still exist in latest stable (2.0.1.0)
##### Steps To Reproduce:

inventoryfile:
[alpha]
piansiapst01 ansible_connection=local
dgitapp01
alexandria

```
playbook:

---
- hosts: alpha
  gather_facts: True
  become: True
  tasks:
    - name: foo test
      pause: prompt="Proving that ctrl-c-a doesn't work"

    - debug:  msg="See what I mean"

```

##### Expected Results:

Expected the play to abort altogether.
##### Actual Results:

1st host aborts but remaining hosts continue with tasks

```
[root@piansiapst01 ansible]# ansible-playbook -i testLinux testpause.yaml -k -u foouser
SSH password:

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [piansiapst01]
ok: [alexandria]
ok: [dgitapp01]

TASK [foo test] ****************************************************************
[foo test]
Proving that ctrl-c-a doesn't work:
Press 'C' to continue the play or 'A' to abort
fatal: [piansiapst01]: FAILED! => {"failed": true, "msg": "user requested abort!"}

TASK [debug] *******************************************************************
ok: [dgitapp01] => {
    "msg": "See what I mean"
}
ok: [alexandria] => {
    "msg": "See what I mean"
}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
alexandria                 : ok=2    changed=0    unreachable=0    failed=0
dgitapp01                  : ok=2    changed=0    unreachable=0    failed=0
piansiapst01               : ok=1    changed=0    unreachable=0    failed=1

```

**Comment by bcoca** [comment] 2016-03-02 14:08
I cannot reproduce, my results for the same play:

```
 ______________ 
< PLAY [alpha] >
 -------------- 
     \
      \
          oO)-.                       .-(Oo
         /__  _\                     /_  __\
         \  \(  |     ()~()         |  )/  /
          \__|\ |    (-___-)        | /|__/
          '  '--'    ==`-'==        '--'  '

 _________________ 
< TASK [foo test] >
 ----------------- 
   \
    \
    ____  
   /# /_\_
  |  |/o\o\
  |  \\_/_/
 / |_   |  
|  ||\_ ~| 
|  ||| \/  
|  |||_    
 \//  |    
  ||  |    
  ||_  \   
  \_|  o|  
  /\___/   
 /  ||||__ 
    (___)_)

[foo test]
Proving that ctrl-c-a doesn't work:
Press 'C' to continue the play or 'A' to abort 
fatal: [piansiapst01]: FAILED! => {"failed": true, "msg": "user requested abort!"}
 ____________________ 
< NO MORE HOSTS LEFT >
 -------------------- 
       \    ____
        \  /    \
          | ^__^ |
          | (oo) |______
          | (__) |      )\/\
           \____/|----w |
                ||     ||

                 Moofasa

 ____________ 
< PLAY RECAP >
 ------------ 
        \    ,-^-.
         \   !oYo!
          \ /./=\.\______
               ##        )\/\
                ||-----w||
                ||      ||

               Cowth Vader

piansiapst01               : ok=0    changed=0    unreachable=0    failed=1   

bcoca@erebos:~/work/ansible(stable-2.0) $ vim play.yml 
bcoca@erebos:~/work/ansible(stable-2.0) $ ansible-playbook play.yml -c local -i test_inv -K
SUDO password: 
 ______________ 
< PLAY [alpha] >
 -------------- 
  \
   \
       __     
      UooU\.'@@@@@@`.
      \__/(@@@@@@@@@@)
           (@@@@@@@@)
           `YY~~~~YY'
            ||    ||

 ______________ 
< TASK [setup] >
 -------------- 
       \    ____
        \  /    \
          | ^__^ |
          | (oo) |______
          | (__) |      )\/\
           \____/|----w |
                ||     ||

                 Moofasa

ok: [dgitapp01]
ok: [alexandria]
ok: [piansiapst01]
 _________________ 
< TASK [foo test] >
 ----------------- 
  \                                  ,+*^^*+___+++_
   \                           ,*^^^^              )
    \                       _+*                     ^**+_
     \                    +^       _ _++*+_+++_,         )
              _+^^*+_    (     ,+*^ ^          \+_        )
             {       )  (    ,(    ,_+--+--,      ^)      ^\
            { (@)    } f   ,(  ,+-^ __*_*_  ^^\_   ^\       )
           {:;-/    (_+*-+^^^^^+*+*<_ _++_)_    )    )      /
          ( /  (    (        ,___    ^*+_+* )   <    <      \
           U _/     )    *--<  ) ^\-----++__)   )    )       )
            (      )  _(^)^^))  )  )\^^^^^))^*+/    /       /
          (      /  (_))_^)) )  )  ))^^^^^))^^^)__/     +^^
         (     ,/    (^))^))  )  ) ))^^^^^^^))^^)       _)
          *+__+*       (_))^)  ) ) ))^^^^^^))^^^^^)____*^
          \             \_)^)_)) ))^^^^^^^^^^))^^^^)
           (_             ^\__^^^^^^^^^^^^))^^^^^^^)
             ^\___            ^\__^^^^^^))^^^^^^^^)\\
                  ^^^^^\uuu/^^\uuu/^^^^\^\^\^\^\^\^\^\
                     ___) >____) >___   ^\_\_\_\_\_\_\)
                    ^^^//\\_^^//\\_^       ^(\_\_\_\)
                      ^^^ ^^ ^^^ ^

[foo test]
Proving that ctrl-c-a doesn't work:
Press 'C' to continue the play or 'A' to abort 
fatal: [piansiapst01]: FAILED! => {"failed": true, "msg": "user requested abort!"}
 ____________________ 
< NO MORE HOSTS LEFT >
 -------------------- 
       \    ____
        \  /    \
          | ^__^ |
          | (oo) |______
          | (__) |      )\/\
           \____/|----w |
                ||     ||

                 Moofasa

 ____________ 
< PLAY RECAP >
 ------------ 
 \     ____________ 
  \    |__________|
      /           /\
     /           /  \
    /___________/___/|
    |          |     |
    |  ==\ /== |     |
    |   O   O  | \ \ |
    |     <    |  \ \|
   /|          |   \ \
  / |  \_____/ |   / /
 / /|          |  / /|
/||\|          | /||\/
    -------------|   
        | |    | | 
       <__/    \__>

alexandria                 : ok=1    changed=0    unreachable=0    failed=0   
dgitapp01                  : ok=1    changed=0    unreachable=0    failed=0   
piansiapst01               : ok=1    changed=0    unreachable=0    failed=1   
```

**Comment by binbashroot** [comment] 2016-03-02 14:17
Just ran it to make sure I was indeed pressing ctrl-c-a and I get the same
failure results.  Even if I was pressing "C" instead of A, then the first
host shouldn't fail which it does in my example.   I will spin up a new
Ansible host with a fresh pip installation to make sure I'm not missing
something with my current Ansible installation in regards to
python/ansible, etc.

**Comment by bcoca** [comment] 2016-03-02 14:23
the behavior you describe was present in 2.0 but does not seem to be in 2.0.1, my guess is that you have old files that are being picked up instead of the new ones.

**Comment by binbashroot** [comment] 2016-03-02 14:45
I suspect you are right.  This was originally an RPM installation from EPEL
converted to PIP to make the jump to 2.0.  I'll rebuild this server and
confirm.  Thank you for your help.

**Comment by binbashroot** [comment] 2016-03-02 17:04
Fresh Ansible 2.0.1.0  install  on a newly built bare bones VMware VM
yields the same failed results.

[root@piansiapst02 yum.repos.d]# pip install ansible
You are using pip version 7.1.0, however version 8.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting ansible
  Using cached ansible-2.0.1.0.tar.gz
Collecting paramiko (from ansible)
  Using cached paramiko-1.16.0-py2.py3-none-any.whl
Collecting jinja2 (from ansible)
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting PyYAML (from ansible)
  Using cached PyYAML-3.11.tar.gz
Requirement already satisfied (use --upgrade to upgrade): setuptools in
/usr/lib/python2.7/site-packages (from ansible)
Collecting pycrypto>=2.6 (from ansible)
  Using cached pycrypto-2.6.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): ecdsa>=0.11 in
/usr/lib/python2.7/site-packages (from paramiko->ansible)
Collecting MarkupSafe (from jinja2->ansible)
  Using cached MarkupSafe-0.23.tar.gz
Installing collected packages: pycrypto, paramiko, MarkupSafe, jinja2,
PyYAML, ansible
  Running setup.py install for pycrypto
  Running setup.py install for MarkupSafe
  Running setup.py install for PyYAML
  Running setup.py install for ansible
Successfully installed MarkupSafe-0.23 PyYAML-3.11 ansible-2.0.1.0
jinja2-2.8 paramiko-1.16.0 pycrypto-2.6.1

[root@piansiapst02 ansible]# ansible-playbook -i conf/testLinux
plays/testpause.yaml -k -u foouser
SSH password:
PLAY

---

TASK [setup]

---

ok: [alexandria]
ok: [piansiapst02]
ok: [dgitapp01]
TASK [foo test]

---

[foo test]
Proving that ctrl-c-a doesn't work:
Press 'C' to continue the play or 'A' to abort
fatal: [alexandria]: FAILED! => {"failed": true, "msg": "user requested
abort!"}
TASK [debug]

---

ok: [piansiapst02] => {
    "msg": "See what I mean"
}
ok: [dgitapp01] => {
    "msg": "See what I mean"
}
NO MORE HOSTS LEFT

---

PLAY RECAP

---

alexandria                 : ok=1    changed=0    unreachable=0    failed=1
dgitapp01                  : ok=2    changed=0    unreachable=0    failed=0
piansiapst02               : ok=2    changed=0    unreachable=0    failed=0

**Comment by binbashroot** [comment] 2016-03-02 20:35
After installing Ansible from the git repo I was able to see the expected
behavior from the pause module

[root@piansiapst02 ansible]# ansible --version
ansible 2.1.0 (devel e438a26ada) last updated 2016/03/02 15:09:15 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 0bbb7ba38d) last updated
2016/03/02 15:09:21 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 39e4040685) last updated
2016/03/02 15:09:26 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = /root/ansible/lib/ansible/modules/
[root@piansiapst02 ansible]# ansible-playbook -i
/etc/ansible/conf/testLinux /etc/ansible/plays/testpause.yaml -k -u foouser
SSH password:
PLAY [alpha]

---

TASK [setup]

---

ok: [piansiapst02]
ok: [dgitapp01]
TASK [foo test]

---

[foo test]
Proving that ctrl-c-a doesn't work:
Press 'C' to continue the play or 'A' to abort
fatal: [dgitapp01]: FAILED! => {"failed": true, "msg": "user requested
abort!"}

NO MORE HOSTS LEFT

---

```
    to retry, use: --limit @/etc/ansible/plays/testpause.retry
```

PLAY RECAP

---

dgitapp01                  : ok=1    changed=0    unreachable=0    failed=1
piansiapst02               : ok=1    changed=0    unreachable=0    failed=0

Rolling back to the PIP installation, the pause bug reappears.
ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path =
/usr/lib/python2.7/site-packages/ansible/modules

[root@piansiapst02 ~]# ansible-playbook -i /etc/ansible/conf/testLinux
/etc/ansible/plays/testpause.yaml -k -u foouser
SSH password:
PLAY

---

TASK [setup]

---

ok: [dgitapp01]
ok: [piansiapst02]
TASK [foo test]

---

[foo test]
Proving that ctrl-c-a doesn't work:
Press 'C' to continue the play or 'A' to abort
fatal: [dgitapp01]: FAILED! => {"failed": true, "msg": "user requested
abort!"}
TASK [debug]

---

ok: [piansiapst02] => {
    "msg": "See what I mean"
}
NO MORE HOSTS LEFT

---

PLAY RECAP

---

dgitapp01                  : ok=1    changed=0    unreachable=0    failed=1
piansiapst02               : ok=2    changed=0    unreachable=0    failed=0

**Comment by bcoca** [comment] 2016-03-02 22:24
closing this then.

**Closed as completed by bcoca** 2016-03-02 22:24 UTC
Labels: needs_info
