### ISSUE TITLE
Using the word "path" as a variable name makes file module go boom

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#15739] opened 2016-05-05 16:31 UTC
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
╰$ ansible --version
ansible 2.0.0.2
  config file = /Users/sbrady/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
╰$ cat ~/.ansible.cfg
[defaults]
inventory = /Users/sbrady/src/infr/prov/ansible/hosts/
log_path = /Users/sbrady/src/infr/prov/ansible/log/ansible.log
roles_path = /Users/sbrady/src/infr/prov/ansible/roles
```
##### OS / ENVIRONMENT

10.11.4 (15E65)
##### SUMMARY

You get the following error when you use the word "path" as a variable name for the file module: `dict object' has no attribute 'path'.`Changing the variable name to anything else causes this code to run nominally. 
##### STEPS TO REPRODUCE

Task:

```
- name: File Attributes
  file: >
    path={{ item.path }}
    owner={{ item.owner }}
    group={{ item.group }}
    recurse={{ item.recurse }}
    state={{ item.state }}
  with_items: fileattr
```

Role:

```
fileattr:
  - path: /etc/asterisk/conf.d  
    state: directory
    owner: root
    group: asterisk
    mode: "0644"
    recurse: yes
```
##### EXPECTED RESULTS

Runs nominally
##### ACTUAL RESULTS

```
__________________________________________
< TASK [example : File Attributes] >
 ------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

task path: /Users/sbrady/src/infr/prov/ansible/roles/example/tasks/main.yml:10
fatal: [198.199.115.196]: FAILED! => {"failed": true, "msg": "ERROR! 'dict object' has no attribute 'path'"}
```

**Comment by jimi-c** [comment] 2016-06-07 18:20
Hi @TheSeanBrady, I just tested this on both devel and stable-2.1 and was unable to reproduce it. I even checked out `v2.0.0.2-1` and was unable to reproduce it, so I'm not quite sure where you may have been seeing this or what may have caused it in your case.

As such, we're going to go ahead and close this now. If you continue seeing any problems related to this issue or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2016-06-07 18:20 UTC
Labels: bug
