### ISSUE TITLE
inconsistent behavior for set_var with JSON data

### ISSUE THREAD

**Issue by ex-nerd** [ansible/ansible#6007] opened 2014-02-14 08:37 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

1.4.5
##### Environment:

OSX but probably N/A
##### Summary:

`set_var` sometimes interprets JSON formatted data into an object, and other times it keeps it as a unicode string.
##### Steps To Reproduce:

The following test playbook demonstrates inconsistent behavior with set_var in "short" vs "extended" mode.

``` yaml

---
- name: test
  hosts: localhost
  gather_facts: False
  tasks:
    - local_action: 'command echo ''{"a": 1, "b": 2}'''
      register: out
    - set_fact:
        foo: "{{ out.stdout }}"
    - set_fact: bar="{{ out.stdout }}"
    - set_fact: baz="{{ out.stdout | from_json }}"
    - debug: var=foo
    - debug: var=bar
    - debug: var=baz
    - debug: msg="{{ foo.a }}"
    - debug: msg="{{ bar.a }}"
      ignore_errors: True
    - debug: msg="{{ baz.a }}"
      ignore_errors: True
```
##### Expected Results:

`foo`, `bar`, and `baz` should all be interpolated into objects and behave like `foo` currently does.
##### Actual Results:

`bar` and `baz` stay as unicode strings (though with different formatting), resulting in failures (and it seems that debug doesn't do `ignore_errors` so ansible exits before you can see `baz.a` but it also throws an error like the attempt for `bar.a`)

**Comment by jerdfelt** [comment] 2014-02-17 20:22
This looks like a duplicate of issue #5463

**Comment by ex-nerd** [comment] 2014-02-21 08:04
Could be.  Another test I've run into can be shown here:

``` yml
---
- hosts: localhost
  gather_facts: False
  tasks:
    - set_fact:
        my_var: "{{ cli_var | default(False) | bool }}"
    - debug: var=my_var
    - debug: msg="my_var is true"
      when: my_var
    - debug: msg="my_var is false"
      when: not my_var
    - debug: msg="my_var is true_string"
      when: my_var == "True"
    - debug: msg="my_var is false_string"
      when: my_var == "False"
```

Though behavior is the same if I use `set_fact: my_var={{ cli_var | default(False) | bool }}`

Pass in `-e cli_var=yes` (or another boolean variant) has the expected behavior of setting my_var to the string "True" (which still evaluates to True, unlike the string "False") rather than an actual boolean value.  You would think if "True" evaluates to True, then "False" would at least evaluate to either True or False but it doesn't match either `when: my_var` or `when: not my_var`.

**Comment by mpdehaan** [comment] 2014-03-19 15:43
Closing as dup, these tickets will be linked, so we'll have notes.

**Closed as completed by mpdehaan** 2014-03-19 15:43 UTC
Labels: bug
