### ISSUE TITLE
Role variables referencing group_vars do not respect --extra-vars

### ISSUE THREAD

**Issue by rakuco** [ansible/ansible#10564] opened 2015-03-27 18:58 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

Ansible >= 1.8.0
##### Environment:

N/A
##### Summary:

Ever since 313f26f866cec92e4dbe0e1d713a0ab0da647c98, if a variable is set in `group_vars` and overridden via `--extra-vars`, the value from `group_vars` ends up being used when the variable is referenced in role variables.
##### Steps To Reproduce:

group_vars/all:

``` yaml
some_var: val1
```

roles/test-role/vars/main.yml:

``` yaml
derived_var: "{{ some_var }}"
```

roles/test-role/tasks/main.yml:

``` yaml

---
- action: debug var=derived_var
```

main.yml:

``` yaml

---
- hosts: all
  roles: [test-role]
```

Then call `ansible-playbook -e some_var=val2 main.yml`.
##### Expected Results:

```
ok: [localhost] => {
    "var": {
        "derived_var": "val2"
    }
}
```
##### Actual Results:

```
ok: [localhost] => {
    "var": {
        "derived_var": "val1"
    }
}
```

**Comment by srgvg** [comment] 2015-03-27 19:07
Interesting. At first I was going to say, no way, I often overrule inventory vars with --extra-vars.

So the specific part of this bug is about `when the variable is referenced in role variables.` Role _vars_ that is.

**Comment by seuf** [comment] 2015-03-31 13:54
I think it's the same bug mentioned in the issue #10251

**Comment by kottenator** [comment] 2015-04-13 16:42
This problem affects me too - 1.9.0.1

**Comment by bcoca** [comment] 2015-04-13 16:52
closing this as duplicate of #10251

**Closed as completed by bcoca** 2015-04-13 16:52 UTC
Labels: bug
