### ISSUE TITLE
Number of "files" in role directories could be reduced by 50%

### ISSUE THREAD

**Issue by mnieber** [ansible/ansible#25760] opened 2017-06-15 17:43 UTC
Roles would look cleaner if filenames were shortened from `roles/foo/tasks/main.yml` to `roles/foo/tasks.yml`. Counting a directory as a file, this would reduce the number of files inside role directories with 50%. Moreover, file lookup in editors such as sublime text would work better, because typing `roles/foo/tasks` is the shortest string that is guaranteed to give the correct file as the first hit.

Of course, the old structure should still be supported too, for backward compatibility.

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
roles

##### ANSIBLE VERSION

ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides

##### SUMMARY
Roles would look cleaner if filenames were shortened from roles/foo/tasks/main.yml to roles/foo/tasks.yml

**Comment by sivel** [comment] 2017-06-15 18:16
Closing as a duplicate of https://github.com/ansible/ansible/issues/15564

**Closed as completed by sivel** 2017-06-15 18:16 UTC
Labels: affects_2.2, feature
