### ISSUE TITLE
Unarchive function in ansible 2.0 does not takes copy=no into account

### ISSUE THREAD

**Issue by koss822** [ansible/ansible#11339] opened 2015-06-22 09:00 UTC
# info

same works perfectly under ansible 1.8
# code

```
- name: Unpack CloudWatch package
  unarchive: src=/tmp/cloudwatch.zip dest=/usr/local copy=no
  when: cloudwatch.stat.isdir is not defined or not cloudwatch.stat.isdir
```
# output

```
TASK [aws : Unpack CloudWatch package] ******************************************
fatal: [enigma14]: FAILED! => {"msg": "ERROR! file or module does not exist: /tmp/cloudwatch.zip", "failed": true}
```
# version

```
ansible --version
ansible 2.0.0 (devel ff251a0dcc) last updated 2015/06/22 10:38:58 (GMT +200)
  lib/ansible/modules/core: (detached HEAD d6ed6113a7) last updated 2015/06/22 09:38:14 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 57813a2e74) last updated 2015/06/22 09:38:14 (GMT +200)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/06/22 09:38:14 (GMT +200)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/06/22 09:38:14 (GMT +200)
  configured module search path = None
```
# server status

```
ubuntu@ubuntu:/tmp$ ls
cloudwatch.zip
```

**Comment by bennojoy** [comment] 2015-06-22 09:24
closing since a duplicate of #11274

**Closed as completed** 2015-06-22 09:24 UTC
Labels: m:unarchive
