### ISSUE TITLE
docker module: image build fails on first pass with ValueError decoding json

### ISSUE THREAD

**Issue by hjwp** [ansible/ansible#7367] opened 2014-05-12 10:47 UTC
Full traceback:

```
failed: [54.82.88.127] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1399891318.63-48689284481872/docker_image", line 1327, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1399891318.63-48689284481872/docker_image", line 217, in main
    image_id = manager.build()
  File "/root/.ansible/tmp/ansible-tmp-1399891318.63-48689284481872/docker_image", line 140, in build
    chunk_json = json.loads(chunk)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 368, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 87 - line 1 column 274067 (char 86 - 274066)
```

The operation completes if run a second time...

**Comment by hjwp** [comment] 2014-05-12 11:49
a print-based debug in decoder.py suggests the json may be malformed -- it looks like there are two
objects rather than one:

```
{"status":"Pulling image (trusty) from ubuntu","progressDetail":{},"id":"99ec81b80c55"}{"status":"Pu (rest of line truncated)
```

column 87 seems to be the point at which the first object ends and the second one begins, `}{`.

**Comment by sivel** [comment] 2014-05-12 13:44
It seems that the pull for the  base image shows up in a single 'chunk' from build with `stream=True`.

Not sure I terribly enjoy this solution, but here is something I tested:

```
diff --git a/library/cloud/docker_image b/library/cloud/docker_image
index 2f5a02b..f960aca 100644
--- a/library/cloud/docker_image
+++ b/library/cloud/docker_image
@@ -140,6 +140,9 @@ class DockerImageManager:
             if not chunk:
                 continue

+            if '"}{"' in chunk:
+                chunk = '{"%s' % chunk.split('"}{"')[-1]
+
             chunk_json = json.loads(chunk)

             if 'error' in chunk_json:
```

or

```
diff --git a/library/cloud/docker_image b/library/cloud/docker_image
index 2f5a02b..f1cba45 100644
--- a/library/cloud/docker_image
+++ b/library/cloud/docker_image
@@ -140,7 +140,10 @@ class DockerImageManager:
             if not chunk:
                 continue

-            chunk_json = json.loads(chunk)
+            try:
+                chunk_json = json.loads(chunk)
+            except ValueError:
+                continue

             if 'error' in chunk_json:
                 self.error_msg = chunk_json['error']
```

**Comment by jimi-c** [comment] 2014-05-12 17:30
@sivel are you going to send a PR to fix this?

**Comment by sivel** [comment] 2014-05-12 18:40
@jimi-c I absolutely can.  Do you have a preference in which version of the above you would be comfortable with?

**Comment by jimi-c** [comment] 2014-05-12 18:43
I think the later would be more preferable.

**Comment by sivel** [comment] 2014-05-12 18:44
Pull request will be sent shortly.

**Comment by sivel** [comment] 2014-05-12 18:56
Pull request #7373 submitted

**Comment by jimi-c** [comment] 2014-05-12 19:22
The above pull request has been merged in, and should resolve the issue. If you continue experiencing any problems related to this issue, please let us know. Thanks!

**Closed as completed** 2014-05-12 19:23 UTC
Labels: cloud, P2, docker, bug

**Comment by tnp** [comment] 2014-07-23 23:35
I have been getting exactly the same error on first build ("ValueError: Extra data") with the docker_image module from Ansible 1.6.6.

**Comment by my2ter** [comment] 2016-06-15 06:07
Hi,

I am getting this error on the latest version of ansible and stable-2.1

```
ansible 2.2.0 (devel 624e7dae54) last updated 2016/06/15 15:44:30 (GMT +1100)
  lib/ansible/modules/core: (detached HEAD e992cfd473) last updated 2016/06/15 15:44:49 (GMT +1100)
  lib/ansible/modules/extras: (detached HEAD 146c969c07) last updated 2016/06/15 15:45:04 (GMT +1100)
```

```
---
- name: Bring up docker containers
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create mysql container
      docker_container:
        name: "db"
        image: mysql:5.7
        pull: yes
        exposed:
          - 3306
        ports: 3310:3306
        state: started
        recreate: no
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
      tags:
        - docker
```

```
TASK [Create mysql container] **************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error pulling image mysql:5.7 - Extra data: line 2 column 1 - line 3 column 1 (char 94 - 150)"}
```

Cheers.

**Comment by chouseknecht** [comment] 2016-06-15 07:47
@myter not able to reproduce this. In my environment mysql:5.7 pulls and builds without issue. I can run your exact playbook. Can you provide more details? Which version of docker-py do you have installed? OS? Anything that might help.

**Comment by my2ter** [comment] 2016-06-17 00:33
@chouseknecht 

Sorry I should have specified that I am using Docker beta with xhyve. Not sure how everything is tied together so let me know what you need from me. On top of my head to help you.

```
OS X El Capitan 10.11.5
```

```
brew -v
Homebrew 0.9.9 (git revision 01b5; last commit 2016-06-14)
Homebrew/homebrew-core (git revision 0587; last commit 2016-06-14)
```

```
brew info ansible
ansible: stable 2.1.0.0 (bottled), HEAD
Automate deployment, configuration, and upgrading
https://www.ansible.com/
/usr/local/Cellar/ansible/1.9.4 (4,960 files, 48.9M)
  Poured from bottle on 2015-10-14 at 15:22:42
/usr/local/Cellar/ansible/2.0.0.2 (8,716 files, 90.6M)
  Poured from bottle on 2016-02-15 at 09:35:50
/usr/local/Cellar/ansible/2.0.1.0 (8,861 files, 92.3M)
  Poured from bottle on 2016-04-07 at 19:00:58
/usr/local/Cellar/ansible/2.1.0.0 (8,946 files, 95.1M) *
  Poured from bottle on 2016-06-02 at 18:02:58
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/ansible.rb
==> Dependencies
Build: pkg-config ✘
Required: libyaml ✔, openssl ✔
==> Caveats
Homebrew writes wrapper scripts that set PYTHONPATH in ansible's
execution environment, which is inherited by Python scripts invoked
by ansible. If this causes problems, you can modify your playbooks
to invoke python with -E, which causes python to ignore PYTHONPATH.
```

```
docker-compose -v
docker-compose version 1.7.1, build 0a9ab35
```

```
docker -v
Docker version 1.11.2, build b9f10c9

Version 1.11.2-beta15 (build: 9168)
603884f1679ff0528724854e9d27fc8e67fdfd8f
```

```
docker-machine -v
docker-machine version 0.7.0, build a650a40
```

```
python --version
Python 2.7.11
```

```
pip -V
pip 8.1.0 from /usr/local/lib/python2.7/site-packages (python 2.7)

pip list
docker-py (1.8.1)
pip (8.1.0)
```

**Comment by pmoosh** [comment] 2016-06-28 18:05
I see the same issue. It fails - although the container images get built. Running it a second time - when the container already exists -  it works.

**Comment by amukiza** [comment] 2016-07-26 16:28
I am experiencing the same Issue: using : - 
docker for mac - Version 1.12.0-rc4-beta20 (build: 10404) 32ce3bdb164320603f1c2d1fb2ba32a43477ef3d
ansible: stable 2.1.0.0 (bottled), HEAD

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/var/folders/1y/hqtt6675391gkyz7qz2tyqwm0000gn/T/ansible_4RjGKQ/ansible_module_docker_image.py", line 531, in <module>
    main()
  File "/var/folders/1y/hqtt6675391gkyz7qz2tyqwm0000gn/T/ansible_4RjGKQ/ansible_module_docker_image.py", line 523, in main
    ImageManager(client, results)
  File "/var/folders/1y/hqtt6675391gkyz7qz2tyqwm0000gn/T/ansible_4RjGKQ/ansible_module_docker_image.py", line 243, in __init__
    self.present()
  File "/var/folders/1y/hqtt6675391gkyz7qz2tyqwm0000gn/T/ansible_4RjGKQ/ansible_module_docker_image.py", line 272, in present
    self.results['image'] = self.build_image()
  File "/var/folders/1y/hqtt6675391gkyz7qz2tyqwm0000gn/T/ansible_4RjGKQ/ansible_module_docker_image.py", line 457, in build_image
    for line in self.client.build(**params):
  File "/usr/local/Cellar/ansible/2.1.0.0/libexec/vendor/lib/python2.7/site-packages/docker/client.py", line 233, in _stream_helper
    data = json.loads(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 369, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 2 column 1 - line 15 column 1 (char 62 - 985)

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "docker_image"}, "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/1y/hqtt6675391gkyz7qz2tyqwm0000gn/T/ansible_4RjGKQ/ansible_module_docker_image.py\", line 531, in <module>\n    main()\n  File \"/var/folders/1y/hqtt6675391gkyz7qz2tyqwm0000gn/T/ansible_4RjGKQ/ansible_module_docker_image.py\", line 523, in main\n    ImageManager(client, results)\n  File \"/var/folders/1y/hqtt6675391gkyz7qz2tyqwm0000gn/T/ansible_4RjGKQ/ansible_module_docker_image.py\", line 243, in __init__\n    self.present()\n  File \"/var/folders/1y/hqtt6675391gkyz7qz2tyqwm0000gn/T/ansible_4RjGKQ/ansible_module_docker_image.py\", line 272, in present\n    self.results['image'] = self.build_image()\n  File \"/var/folders/1y/hqtt6675391gkyz7qz2tyqwm0000gn/T/ansible_4RjGKQ/ansible_module_docker_image.py\", line 457, in build_image\n    for line in self.client.build(**params):\n  File \"/usr/local/Cellar/ansible/2.1.0.0/libexec/vendor/lib/python2.7/site-packages/docker/client.py\", line 233, in _stream_helper\n    data = json.loads(data)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py\", line 338, in loads\n    return _default_decoder.decode(s)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py\", line 369, in decode\n    raise ValueError(errmsg(\"Extra data\", s, end, len(s)))\nValueError: Extra data: line 2 column 1 - line 15 column 1 (char 62 - 985)\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
```

**Comment by jimi-c** [comment] 2016-07-27 16:56
@amukiza this is a very old issue, and the docker modules have been rewritten since the time this bug was created. If this is a bug on the new module, please open a new issue for it, and if it's a bug on the old module, please consider upgrading to use the new one.
