### ISSUE TITLE
"git" module error: "Failed to init/update submodules"

### ISSUE THREAD

**Issue by danieljaouen** [ansible/ansible#6750] opened 2014-03-28 23:52 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

± ansible --version
ansible 1.6 (devel 4dc598049e) last updated 2014/03/28 19:14:05 (GMT -400)
##### Environment:

OS X 
##### Summary:

Ansible's `git` module fails to keep a git repository up-to-date if it has submodules.
##### Steps To Reproduce:

Try to clone down a repository with submodules.  For example, `git://github.com/Valloric/YouCompleteMe.git`
##### Expected Results:

Ansible's `git` module clones down an updated version of a git repository with submodules. 
##### Actual Results:

Ansible fails: 

```
failed: [127.0.0.1] => (item={'repo': 'git://github.com/Valloric/YouCompleteMe.git', 'dest': u'/Users/dan/.vim/bundle/YouCompleteMe', 'name': 'YouCompleteMe'}) => {"failed": true, "
item": {"dest": "/Users/dan/.vim/bundle/YouCompleteMe", "name": "YouCompleteMe", "repo": "git://github.com/Valloric/YouCompleteMe.git"}}
msg: Failed to init/update submodules
```

This might be related to a commit made today: https://github.com/ansible/ansible/commit/11895fa43734ce246a7bf64746df618540251c1f

**Comment by mpdehaan** [comment] 2014-03-29 00:37
Hmm, in queue for testing.

If you'd like to attempt a fix that also attempts to get the fix of the above behavior down, that's also welcome.

**Comment by danieljaouen** [comment] 2014-03-29 18:39
From what I can tell, the command works when run via a local connection but not when run via an SSH connection.  

I'll continue to investigate.

**Comment by danieljaouen** [comment] 2014-03-31 14:30
Additionally, it seems like the repos are updated correctly before Ansible errors out, as a second run returns no errors (or changes).

**Comment by jctanner** [comment] 2014-04-03 18:31
Reproduced the error with a local connection.

**Comment by jctanner** [comment] 2014-04-03 18:35
Confirmed that removing '--remote' from line 391 in the module resolves the error.

If I expose the stderr, it looks like --remote is not a proper flag for submodules:

```
msg: Failed to init/update submodules: Usage: git submodule [--quiet] add [-b branch] [-f|--force] [--reference <repository>] [--] <repository> [<path>]
   or: git submodule [--quiet] status [--cached] [--recursive] [--] [<path>...]
   or: git submodule [--quiet] init [--] [<path>...]
   or: git submodule [--quiet] update [--init] [-N|--no-fetch] [-f|--force] [--rebase] [--reference <repository>] [--merge] [--recursive] [--] [<path>...]
   or: git submodule [--quiet] summary [--cached|--files] [--summary-limit <n>] [commit] [--] [<path>...]
   or: git submodule [--quiet] foreach [--recursive] <command>
   or: git submodule [--quiet] sync [--] [<path>...]
```

**Comment by jctanner** [comment] 2014-04-03 19:22
@danieljaouen This should be fixed for you. If not, then you should get a more informative error message at least.

**Closed as completed** 2014-04-03 19:22 UTC
Labels: P2, bug

**Comment by danieljaouen** [comment] 2014-04-03 19:32
A brief test shows that this is working as expected now.

Thanks!
