### ISSUE TITLE
mount: Bind Mount repeats mount command when using a bind mount

### ISSUE THREAD

**Issue by fti7** [ansible/ansible#8422] opened 2014-08-04 12:01 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7 (devel 189824dd76) last updated 2014/07/30 17:24:01 (GMT +200)
##### Environment:

Ubuntu 12.04 LTS
##### Summary:

The Mount Module is not idempotent if you are using an Bindmount with state=mounted.
It mounts it on every run
##### Steps To Reproduce:

<pre>
- name: BIND MOUNT | /usr/local/jdk1.7 -> /usr/lib/jvm/java-7-oracle
  mount: 
    name=/usr/local/jdk1.7
    src='/usr/lib/jvm/java-7-oracle' 
    fstype=none
    opts=bind
    state=mounted
</pre>

(No, i wont use Symlinks for this)
##### Expected Results:

Correct checking of the Mount Status and just execute it once if neccessary
##### Actual Results:

3x Run, 3x "Changed" ->
$ mount
/usr/lib/jvm/java-7-oracle on /usr/local/jdk1.7 type none (rw,bind)
/usr/lib/jvm/java-7-oracle on /usr/local/jdk1.7 type none (rw,bind)
/usr/lib/jvm/java-7-oracle on /usr/local/jdk1.7 type none (rw,bind)

**Comment by Jmainguy** [comment] 2014-08-08 14:17
This appears to be a duplicate of #7121. The issue comes down to python's os.path.ismount() does not  recognize bind mounts as mounts.

**Comment by mpdehaan** [comment] 2014-09-29 20:21
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Closed as completed by mpdehaan** 2014-09-29 20:21 UTC
Labels: bug
