### ISSUE TITLE
 Odd behavior on the stdout using ansible.playbook.PlayBook

### ISSUE THREAD

**Issue by vpuech** [ansible/ansible#4825] opened 2013-11-06 17:31 UTC
hello,
i've found an odd behavior using ansible.playbook.PlayBook on a Flask server.
- i pass a random number in extra_vars["myvar"] 
- i print it everywhere and it is the good number the first time
- The second time, it is still the good number except in data["stdout"] on the runner_on_ok, where it display the last myvar
- if i put this in a script and not in a Flask server it work each time, if i restart the Flask server it work each time the first time

thanks

----------ansible.playbook.PlayBook call-------------

``` python
    stats               = callbacks.AggregateStats()
    playbook_cb         = callbacks.PlaybookCallbacks(verbose=utils.VERBOSITY)
    runner_cb           = callbacks.PlaybookRunnerCallbacks(stats, verbose=utils.VERBOSITY)

    pb = ansible.playbook.PlayBook(
        playbook=app.config['REPO_PATH']+"main.yml",
        #host_list=target,
        forks=2,
        sudo_user="root",
        sudo_pass="xxxx",
        timeout=10,
        callbacks=playbook_cb,
        runner_callbacks=runner_cb,
        stats=stats,
        extra_vars=extra_vars
    )

    result = pb.run()
```

------- main.yml playbook ----------

```
- hosts: myhost*
  gather_facts: no
  connection: local
  #sudo: true
  vars_files:
    - vars.yml
  tasks:
    - name: echo
      shell: echo "$myvar"
```

------ callback_plugin ---

``` python
import os
import time
import json


def log(host, data):

        #import pdb; pdb.set_trace()
        print 'DEBUG3 '+str(data)

class CallbackModule(object):
    def runner_on_ok(self, host, res):
        log(host, res)
    def on_any(self, *args, **kwargs):
        play = getattr(self, 'play', None)
        task = getattr(self, 'task', None)
        if play :
            global gUUID
            print play.vars['myvar']
```

**Comment by mpdehaan** [comment] 2013-11-08 05:22
Closing this because it's a question, not a bug

Also, no ansible version reported.

Please stop by the development mailing list.

**Closed as completed by mpdehaan** 2013-11-08 05:22 UTC
Labels: bug
