### ISSUE TITLE
group_vars from group_by do not override group_vars/all since f6a55a3

### ISSUE THREAD

**Issue by direvus** [ansible/ansible#8664] opened 2014-08-18 08:38 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8 (devel 6180d9a693) last updated 2014/08/18 17:03:49 (GMT +1100)
##### Environment:

Bug discovered with Debian x86_64, confirmed and bisected with Gentoo x86_64.
##### Summary:

When using group_by to create a group on the fly (e.g. `group_by: key="{{ ansible_os_family }}"`), the group_vars fail to override vars in `group_vars/all`.

I bisected this to f6a55a35525a6ca0b56ad856f2ab11bbd226c1b4.
##### Steps To Reproduce:

`site.yml`:

``` yaml

---
- hosts: all
  tasks:
  - group_by: key={{ ansible_os_family }}
  - fail: msg="testvar = {{ testvar }}"
    when: testvar != "override OK"
```

`group_vars/all`:

``` yml

---
testvar: override FAIL
```

`group_vars/Gentoo` (where "Gentoo" is whatever your `ansible_os_family` actually resolves to):

``` yaml

---
testvar: override OK
```
##### Expected Results:

```
PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [group_by key={{ ansible_os_family }}] ********************************** 
changed: [127.0.0.1]

TASK: [fail msg="testvar = {{ testvar }}"] ************************************ 
skipping: [127.0.0.1]

PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=2    changed=1    unreachable=0    failed=0   
```
##### Actual Results:

```
PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [group_by key={{ansible_os_family}}] ************************************ 
changed: [127.0.0.1]

TASK: [fail msg="testvar = {{testvar}}"] ************************************** 
failed: [127.0.0.1] => {"failed": true}
msg: testvar = override FAIL

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/direvus/site.retry

127.0.0.1                  : ok=2    changed=1    unreachable=0    failed=1   

```

**Comment by srgvg** [comment] 2014-08-18 14:01
This looks the same as #8159 - I'll need to re-investigate.

**Comment by jimi-c** [comment] 2014-08-18 14:15
This does appear to be fixed with an up-to-date pull from devel:

<pre>
# ansible-playbook -vv 8664.yml 
PLAY [localhost] ************************************************************** 
GATHERING FACTS *************************************************************** 
<127.0.0.1> REMOTE_MODULE setup
ok: [127.0.0.1]
TASK: [group_by key={{ ansible_os_family }}] ********************************** 
created 'group_by' ActionModule: key=RedHat
changed: [127.0.0.1] => {"changed": true, "groups": {"RedHat": ["127.0.0.1"]}}
TASK: [fail msg="testvar = {{ testvar_8664 }}"] ******************************* 
skipping: [127.0.0.1]
PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=2    changed=1    unreachable=0    failed=0   
</pre>

@direvus could you update to the latest commit on devel and re-test to confirm?

**Comment by direvus** [comment] 2014-08-18 21:57
@jimi-c my test case is still failing, as of:

```
ansible 1.8 (devel 379e31883c) last updated 2014/08/19 07:13:27 (GMT +1100)
```

I am intrigued as to why your test case seems to be passing while mine is failing.  What are you using for inventory?  My test case is just one line "127.0.0.1", no groups defined.

I had upgraded my production Ansible from 1.6.9 to 1.7.1 to get around #7736, which is when I ran into this bug.  Unfortunately, this one is a total showstopper, so it looks like I'll have to roll back to 1.6.9 and just lump it with #7736 for a while.

@sergevanginderachter I had a look at #8159, but I think it is a separate issue (though both were apparently introduced in f6a55a3).

My `group_vars/Gentoo` is in fact being loaded, it just fails to override vars that are also defined in `group_vars/all`.  If I define some new var in `group_vars/Gentoo` only, and it doesn't appear in `group_vars/all`, then that var works as expected.

**Comment by jimi-c** [comment] 2014-08-19 01:58
@direvus in that case, it may actually be a duplicate of https://github.com/ansible/ansible/issues/8638, which reports the same issue (group_vars/all overrides vars/ files).

**Comment by direvus** [comment] 2014-08-19 02:41
@jimi-c Maybe, but I note that you bisected #8638 to a different commit.

For what it's worth, my test still fails with your proposed fix for that issue (jimi-c/ansible@2e87ef74fa36ca48407cc522ec2e89773e08e99b).

**Comment by srgvg** [comment] 2014-08-19 12:43
@direvus is right, it is related to the inventory refactor, and this is partly to the same problem as #8621, but also de newly created group gets a depth 0, which is the same priority as the all group, and hence the override also does not happen.

**Comment by srgvg** [comment] 2014-08-19 13:00
@direvus  can you test with my branch https://github.com/sergevanginderachter/ansible/tree/issue_8621_8664 ?

**Comment by direvus** [comment] 2014-08-19 13:31
@sergevanginderachter No change with my test case Serge.  Although I think making group_by groups children of 'all' makes a lot of sense, whether it helps with this bug or not!

I have been poking around the Ansible source today, trying to see what's going wrong with group_by.  I suspect that it's because group vars are now getting cached on the first pass through the inventory, and then when group_by gets executed, it doesn't end up using `combine_vars` to inject the new group vars back into the original cache.

That's just a rough guess though, I'm new to the Ansible code base.

**Comment by srgvg** [comment] 2014-08-19 13:47
No, that's why the group_by plugin deletes the cache for that host.
Very weird, I had a test case almost similar that I solved, now your exact example indeed still fails.
Hold on...

**Comment by srgvg** [comment] 2014-08-19 14:06
This is what I tested:

```
[A] serge@goldorak:~/work/test2$ cat inv/inventory 
localhost ansible_connection=local

[a_group]
localhost

[A] serge@goldorak:~/work/test2$ cat inv/group_vars/all 
foo: wrong value
testvar: override FAIL
[A] serge@goldorak:~/work/test2$ cat inv/group_vars/
all          superos.yml  
[A] serge@goldorak:~/work/test2$ cat inv/group_vars/superos.yml 
testvar: override OK
[A] serge@goldorak:~/work/test2$ cat playbook.yml 
- hosts: localhost
  gather_facts: no
  tasks:
    - name: This should be "foo"
      debug: var=foo
    - group_by: key=superos
    - debug: var=hostvars[inventory_hostname]
    - debug: var=testvar 
[A] serge@goldorak:~/work/test2$ 
```

I don't see why it works here with my patch, and not your example.

**Comment by srgvg** [comment] 2014-08-19 14:43
Seems related to your localhost not being in any group, so getting in the 'ungrouped' group, which seems to apply the vars from 'all' on host level, which happens because of e3895840, which fixed  "group_vars/all not imported for implicit localhost when using dynamic inventory" #6563 but that should not happen if localhost is explicit :) Also, should not load group variables for a host as host variables.

**Comment by srgvg** [comment] 2014-08-19 14:44
@direvus I updated my branch, can you re-check?

**Comment by direvus** [comment] 2014-08-20 00:37
That did it Serge.  My test passes as of your sergevanginderachter/ansible@0ab721d51e77ba4779b86b200128ca08cdcd6b7b

Thanks for your work on this!  Should we be adding something to the integration tests?

**Comment by srgvg** [comment] 2014-08-20 07:11
The fixes where just merged into devel now, so you should be good now.
You might want to look at test/integration/test_group_by.yml and perhaps add this use case in?

**Comment by jimi-c** [comment] 2014-08-20 14:00
#  Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2014-08-20 14:00 UTC
Labels: needs_info, P2, bug
