### ISSUE TITLE
apt upgrade ansible (5.7.0-1ppa~focal) fails

### ISSUE THREAD

**Issue by chrisvanmeer** [ansible/ansible#77735] opened 2022-05-04 20:00 UTC
### Summary

Apt update to ansible (5.7.0-1ppa~focal) fails.

### Issue Type

Bug Report

### Component Name

apt

### Ansible Version

```console
$ ansible --version

ansible [core 2.12.4]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/chris/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/chris/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
(END)
```

### OS / Environment

Ubuntu Server 20.04.4 LTS

### Steps to Reproduce

```bash
apt upgrade
```

### Expected Results

Setting up ansible (5.7.0-1ppa~focal) ...
$

### Actual Results

```console
Setting up ansible (5.7.0-1ppa~focal) ...
  File "/usr/lib/python3/dist-packages/ansible_collections/fortinet/fortios/plugins/modules/fortios_wireless_controller_hotspot20_h2qp_advice_of_charge.py", line 281
    filtered_data =
                  ^
SyntaxError: invalid syntax

  File "/usr/lib/python3/dist-packages/ansible_collections/fortinet/fortios/plugins/modules/fortios_wireless_controller_hotspot20_h2qp_osu_provider_nai.py", line 238
    filtered_data =
                  ^
SyntaxError: invalid syntax

  File "/usr/lib/python3/dist-packages/ansible_collections/fortinet/fortios/plugins/modules/fortios_wireless_controller_hotspot20_h2qp_terms_and_conditions.py", line 236
    filtered_data =
                  ^
SyntaxError: invalid syntax

dpkg: error processing package ansible (--configure):
 installed ansible package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 ansible
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by chrisvanmeer** [comment] 2022-05-04 20:01
### Solution


It appears that in the three files reported down below, lines got split up unintentionally. For example line 236 of fortios_wireless_controller_hotspot20_h2qp_terms_and_conditions.py:

```
    filtered_data =
     underscore_to_hyphen(filter_wireless_controller_hotspot20_h2qp_osu_provider_nai_data(wireless_controller_hotspot20_h2qp_osu_provider_nai_data))
```

Changing that into a one-liner

```
    filtered_data = underscore_to_hyphen(filter_wireless_controller_hotspot20_h2qp_osu_provider_nai_data(wireless_controller_hotspot20_h2qp_osu_provider_nai_data))
```

In all three files fixes it and after that `apt upgrade` can be run succesfully.

**Comment by sivel** [comment] 2022-05-04 20:02
Duplicate of https://github.com/ansible/ansible/issues/77730

**Closed as completed by sivel** 2022-05-04 20:02 UTC
