### ISSUE TITLE
'str' object has no attribute 'format'

### ISSUE THREAD

**Issue by sepich** [ansible/ansible#10036] opened 2015-01-18 11:46 UTC
##### Issue Type:

“Bug Report”, development branch regression
##### Environment:

Debian Lenny
##### Summary:

Parse error in latest dev. No such error in 1.8.2
##### Steps To Reproduce:

Any module except of 'raw' show such error: 

```
$ ansible server.domain.local -a 'pwd'
server.domain.local | FAILED >> {
    "failed": true,
    "msg": "Traceback (most recent call last):\r\n  File \"/home/aryabov/.ansible/tmp/ansible-tmp-1421578623.81-92739059794178/command\", line 130, in <module>\r\n    r'(^|\\s)({options_regex})=(?P<quote>[\\'\"])?(.*?)(?(quote)(?<!\\\\)(?P=quote))((?<!\\\\)(?=\\s)|$)'.format(\r\nAttributeError: 'str' object has no attribute 'format'\r\n",
    "parsed": false
}
```

when talking to the old lenny box (debian5) with such packages:

```
dpkg -l | grep python
ii  python                                 2.5.2-3                                An interactive high-level object-oriented language (default ve
ii  python-apt                             0.7.7.1+nmu1                           Python interface to libapt-pkg
ii  python-central                         0.6.8                                  register and build utility for Python packages
ii  python-gdbm                            2.5.2-1                                GNU dbm database support for Python
ii  python-minimal                         2.5.2-3                                A minimal subset of the Python language (default version)
ii  python-simplejson                      1.9.2-1                                Simple, fast, extensible JSON encoder/decoder for Python
ii  python-support                         0.8.4lenny2                            automated rebuilding support for Python modules
ii  python2.5                              2.5.2-15+lenny1                        An interactive high-level object-oriented language (version 2.
ii  python2.5-minimal                      2.5.2-15+lenny1                        A minimal subset of the Python language (version 2.5)
```
##### Expected Results:

No error as in 1.8.2:

```
$ ansible server.domain.local -a 'pwd'
server.domain.local | success | rc=0 >>
/home/user
```

**Comment by jonhadfield** [comment] 2015-01-27 13:57
This seems to be caused by https://github.com/ansible/ansible-modules-core/commit/8d9f6053d3c4f8c15bf2d1fdff79efe3f6637255 which makes use of string's format method introduced in python 2.6.
@sepich, I assume your agents are running lower than python 2.6? I'm being hit by this on my 2.4 agents and the documentation says that agents only need python 2.4.

**Comment by abadger** [comment] 2015-01-27 17:45
@jonhadfield Thanks for pinpointing that!

**Comment by abadger** [comment] 2015-01-27 17:50
Should be fixed in: https://github.com/ansible/ansible-modules-core/commit/98f0c0424aff0e333d52b60edf636b934ededcf9

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Closed as completed by abadger** 2015-01-27 17:50 UTC
Labels: bug
