### ISSUE TITLE
galaxy role file : path property ignored for dependencies

### ISSUE THREAD

**Issue by mrzor** [ansible/ansible#10342] opened 2015-02-25 15:12 UTC
Greetings!

I'm using the `path` property in my `galaxy_roles.yml` file to specify where the roles should be installed. Likewise:

```

---
    - src: modX
    - path: pathX
```

Unfortunately, `modX` dependencies are not installed in `pathX` - the system default is used instead (or - in recent enough ansibles, ansible.cfg `roles_path` should be used here).

This is inconsistent with the behavior of `ansible-galaxy install modX -p pathX` which will install dependencies in `pathX` as well.

Is this a bug?

**Comment by jctanner** [comment] 2016-11-01 01:37
Duplicate of https://github.com/ansible/ansible/issues/9572

**Closed as completed by jctanner** 2016-11-01 01:37 UTC
Labels: affects_2.0, bug
