### ISSUE TITLE
Feature idea: persist handlers

### ISSUE THREAD

**Issue by hryamzik** [ansible/ansible#21896] opened 2017-02-24 14:07 UTC
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
handlers

##### SUMMARY

Current issue with handlers is that you lose them once playbook execution stops for some reason, it may be an problem with playbook itself or a connection termination. Ansible puts failed hosts to a retry file – why not to save handler names as well to capture them on next execution?

**Comment by bcoca** [comment] 2017-10-02 19:39
dupe of #10647

**Closed as completed by bcoca** 2017-10-02 19:39 UTC
Labels: affects_2.3, support:core, feature
