### ISSUE TITLE
to_yaml and to_nice_yaml no longer output data faithfully

### ISSUE THREAD

**Issue by hfinucane** [ansible/ansible#11189] opened 2015-06-05 22:34 UTC
In 1.7.1

```
ansible all -m copy -a "dest=/tmp/z content=\"{{[{'foo': 'bar', 'baz': 'bang'}]|to_nice_yaml}}\""
cat /tmp/z
-   baz: bang
    foo: bar
```

In 1.9.1

```
ansible all -m copy -a "dest=/tmp/z content=\"{{[{'foo': 'bar', 'baz': 'bang'}]|to_nice_yaml}}\""
cat /tmp/z
-   baz: bang
foo: bar
```

The same is true for `to_yaml`.

**Comment by hfinucane** [comment] 2015-06-05 22:48
This is true on devel, but it looks like in v2, it's fixed. So there's that.

**Comment by bcoca** [comment] 2015-06-05 23:43
i'm confused ... v2 is IN devel right now

**Comment by bcoca** [comment] 2015-06-05 23:53
so I can reproduce the issue on 1.9 but not on 2.0 ... yet the code invoked by to_nice_yaml is exactly the same. the issue seems related to copy's content

**Comment by hfinucane** [comment] 2015-06-08 23:40
I don't think it's copy, I found it in a different context, and you can replicate it with 'debug'- it's just harder to read it since it comes out with escape characters.

```
ansible all -m debug -a "msg=\"{{[{'foo': 'bar', 'baz': 'bang'}]|to_nice_yaml}}\""
localhost | success >> {
    "msg": "-   baz: bang\nfoo: bar\n"
}
vs
localhost | success >> {
    "msg": "-   baz: bang\n    foo: bar\n"
}
```

**Comment by michael-donat** [comment] 2015-07-13 15:11
Guys, this is still broken in 1.9.2, any info on the fix?

**Comment by abadger** [comment] 2015-07-14 00:06
I think I've found a workaround for you if you are wanting to use to_nice_yaml in a playbook.  I'm not sure about a workaround for use with ansible on the command line.

Instead of using the key=value syntax in a playbook, use the dict parameter syntax instead:

```
---
- hosts: localhost
  vars:
    data: [{'foo': 'bar', 'baz': 'bang'}]
  tasks:
    - name: Do the right thing
      debug:
        msg: "{{data|to_nice_yaml}}"
    - name: Do the wrong thing
      debug: msg="{{data|to_nice_yaml}}"
```

This leads me to believe that key=value parameters is at the root of the problem on 1.9.x.  Since we've significantly revamped how we do key=value parameters in 2.0 that would explain why the 2.0 code works but 1.9.x does not.

However, since this is working in devel we may not get around to making this work in 1.9.x.  key=value handling in the 1.9.x code base was fraught with corner cases.  Part of the 2.0 work in this area was to make the code less fragile and make changes easier.  If someone would like to track down what is causing the problem to occur in 1.9.x and submit a pull request to fix it it may help to move this forward in time for 1.9.3 but there may still be significant work to figure out whether the pull request makes other corner cases fail so I can't promise that it will make it in.

If it turns out that the problem is not in key=value parsing then it may be easier to review a change for unintended side effects and get it into 1.9.x but I can't be certain without knowing what changes would actually need to be made.

**Comment by michael-donat** [comment] 2015-07-14 08:22
@abadger Thanks for coming back to me.

To explain my use case a little better.

I'm deploying a php-symfony based application with ansible. It so happens that depending on the environment we deploy to (dev, qa, stage etc) we override certain DI services via configuration.

Symfony uses mostly yaml for its config, also for services. I have a number of templates which after 'compiling' are vanilla yaml ingested by the framework and in variables I have a block of yaml that needs to be included in the template.

What I was initially trying to do is the following

template.yml

```
services: {{ service_override }}
```

vars.yml

```
services_override:
    some_service:
        class: My\A
        arguments: [1,2,3,4]
    some_other_service:
        public: false
```

expected result:

```
services:
   some_service:
        class: My\A
        arguments: [1,2,3,4]
    some_other_service:
        public: false
```

Changing `services: {{ service_override }}` to `services: {{ service_override | to_nice_yaml }}` was breaking the whitespacing making the resulting yaml invalid. Since JSON is valid yaml too (;) I tried with to_json but for some reason symfony was not happy with the JSON escaping of backslashes (php namespace separator is a `\`)

I spent some time digging in frustration and for some reason the simplest solution didn't occur to me. The service_override is really just a blob of text so why not treat it like one?

vars.yml

```
services_override: >
    some_service:
        class: My\A
        arguments: [1,2,3,4]
    some_other_service:
        public: false
```

Fixed all the problems.

The underlying issue of to_nice_yaml still remains, but using strings was the more straight forward approach anyway.

**Comment by jimi-c** [comment] 2015-07-15 19:02
Looking through the above, we're going to go ahead and close this issue, as the problem is no longer present in the devel branch and there are other workarounds available.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-07-15 19:02 UTC
Labels: P2, bug
