### ISSUE TITLE
Taking the subset group[0] should not clash with --limit'ing to another group

### ISSUE THREAD

**Issue by srgvg** [ansible/ansible#4335] opened 2013-10-02 11:57 UTC
As per https://groups.google.com/d/msg/ansible-project/obk46KO8fi8/qhhDDpBlGnIJ

Current behaviour:

```
$ ansible nexus[0] -m ping -o
nexus-on-1 | success >> {"changed": false, "ping": "pong"}

$ ansible nexus[0] -m ping -o --limit productie
No hosts matched
```

The [0] subset should be calculated on the --limit'ed subset.
The --limit subset should probably applied before the [0] subset.

**Comment by mpdehaan** [comment] 2013-10-02 12:01
This is a little different than the thing I asked to report too, so noting here

```
 - hosts: all[0]
```

I think you said in general terms that this didn't work.

Can you elaborate if this is the same thing?  The all group contains all hosts so I'm curious why it would be applicable to the above.

Thanks!

**Comment by srgvg** [comment] 2013-10-02 12:27
I noted the above to make it clear this just doesn't happen on the all[0] group but also specific groups, and used the ansible cli to quickly show this.

Not sure how that's different, given that I see the same problem
- on a specific group, or the special 'all' group
- whether noted in a playbook or on the ansible cli

Same goes for playbooks:

```
$ cat pb.yml; ansible-playbook pb.yml; ansible-playbook pb.yml --limit productie

- hosts: amqp[0]
  tasks:
  - raw: "echo flush arp cache"
    delegate_to: firewall-intern-2101


PLAY [amqp[0]] **************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [amqp-oe-1]

TASK: [raw echo flush arp cache] ********************************************** 
ok: [amqp-oe-1]

PLAY RECAP ******************************************************************** 
amqp-oe-1                  : ok=2    changed=0    unreachable=0    failed=0   


PLAY [amqp[0]] **************************************************************** 
skipping: no hosts matched

PLAY RECAP ******************************************************************** 

```

Let me know if you need more info or confirmation of something.

**Comment by mpdehaan** [comment] 2013-10-02 12:29
Got it!

Thanks!

**Comment by mpdehaan** [comment] 2013-10-02 12:29
I had thought you meant generally speaking "all[0]" didn't work, you meant
it didn't apply --limit first.

Which makes sense!

**Comment by srgvg** [comment] 2013-10-02 12:32
Human communication protocols are hard. Maybe we should just try moo'ing to each other.

**Comment by mpdehaan** [comment] 2013-10-07 17:48
moooooo
moo
mooooo
moo mooo
moo

**Comment by srgvg** [comment] 2013-10-07 17:54
I see you now fully got it :+1:

**Comment by jctanner** [comment] 2013-11-08 17:52
@sergevanginderachter Can you share an example inventory file to reproduce the behavior in https://github.com/ansible/ansible/issues/4335#issuecomment-25534214 ?

**Comment by srgvg** [comment] 2013-11-08 19:02
@jctanner : this should do it:

```
$ cat inventory

[A]
1
2
3
4
[B]
3
4

$  ansible -i inventory all --list-hosts

    1
    2
    3
    4

$  ansible -i inventory all[0] --list-hosts

    1

$  ansible -i inventory all[0] --list-hosts --limit B

No hosts matched

```

The last command is expected to return just the `3` host.

**Comment by jimi-c** [comment] 2014-02-06 20:24
After digging into this, I believe the issue here is where you're trying to grab the index in the wrong place. If you do the following, you get the expected result:

<pre>
# ansible -i ~/testing/test_4335.hosts --list-hosts --limit B[0] all
    3
</pre>

This is probably confusing since we allow indexes on both the limit and the primary group, which could lead to some weird syntax like `--limit B[0] all[1]`, which really doesn't make any sense in 99.999% of the use cases.

So, I'm going to close this as the above syntax works fine in devel. If you have any further questions about this, let us know. Thanks!

**Closed as completed by jimi-c** 2014-02-06 20:24 UTC
Labels: bug

**Comment by srgvg** [comment] 2014-02-06 20:27
I don't understand how you say I did this on the wrong place.
Doing this in the playbook - as opposite in the limit section - is quite a different thing, a different use case.
Also, I don't know what a 'primary' group is.
