### ISSUE TITLE
no_log does not hide env vars with higher verbosity

### ISSUE THREAD

**Issue by chanaka-jostle** [ansible/ansible#24181] opened 2017-05-01 21:33 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
no_log

##### ANSIBLE VERSION
2.3

##### OS / ENVIRONMENT
Centos

##### SUMMARY
Hello, we are using no_log and mysql module and both items are showing passwords in clear text. 

Example:
```
TASK [mysql_users : Grant all privileges to all schemas for REDACTED] ********** 
14:04:28 Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/database/mysql/mysql_user.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: REDACTED
<127.0.0.1> EXEC /bin/sh -c 'AWS_ACCESS_KEY_ID=REDACTED AWS_SECRET_ACCESS_KEY=REDACTED /usr/bin/python2 && sleep 0'
```
##### STEPS TO REPRODUCE
Tasks with mysql module or shell module with no_log: true are showing passwords

##### EXPECTED RESULTS
when using mysql module or shell with no_log: true all passwords or logs should be hidden.

##### ACTUAL RESULTS

```

**Comment by sivel** [comment] 2017-05-02 16:52
I've updated the title to better reflect the extent of the problem.

As I understand it, when using `no_log: true`, and a high verbosity, ansible will still display the user you are connecting to the server as, as well as any `environment` specified at the play or task level.

I'm not convinced exposing the user you are connecting to the target as, is a problem.

However it may be seen as a problem that specifying `no_log: true` does not hide the output of env vars specified in `environment` that may have sensitive information.

Example:

```
---
- hosts: all
  tasks:
    - shell: "echo $FOO"
      environment:
        FOO: bar
      no_log: true
```

```diff
task path: /Users/matt/python_venvs/ansibledev/playbooks/env.yml:4
Using module_utils file /Users/matt/python_venvs/ansibledev/ansible/lib/ansible/module_utils/basic.py
Using module_utils file /Users/matt/python_venvs/ansibledev/ansible/lib/ansible/module_utils/six/__init__.py
Using module_utils file /Users/matt/python_venvs/ansibledev/ansible/lib/ansible/module_utils/_text.py
Using module_utils file /Users/matt/python_venvs/ansibledev/ansible/lib/ansible/module_utils/pycompat24.py
Using module_utils file /Users/matt/python_venvs/ansibledev/ansible/lib/ansible/module_utils/six/_six.py
Using module file /Users/matt/python_venvs/ansibledev/ansible/lib/ansible/modules/commands/command.py
- <localhost> ESTABLISH LOCAL CONNECTION FOR USER: matt
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/matt/.ansible/tmp/ansible-tmp-1493743843.87-84227121055243 `" && echo ansible-tmp-1493743843.87-84227121055243="` echo /Users/matt/.ansible/tmp/ansible-tmp-1493743843.87-84227121055243 `" ) && sleep 0'
<localhost> PUT /tmp/tmpKJ_CV0 TO /Users/matt/.ansible/tmp/ansible-tmp-1493743843.87-84227121055243/command.py
<localhost> EXEC /bin/sh -c 'chmod u+x /Users/matt/.ansible/tmp/ansible-tmp-1493743843.87-84227121055243/ /Users/matt/.ansible/tmp/ansible-tmp-1493743843.87-84227121055243/command.py && sleep 0'
- <localhost> EXEC /bin/sh -c 'FOO=bar /usr/bin/python /Users/matt/.ansible/tmp/ansible-tmp-1493743843.87-84227121055243/command.py; rm -rf "/Users/matt/.ansible/tmp/ansible-tmp-1493743843.87-84227121055243/" > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result"}
META: ran handlers
META: ran handlers
```

I'm however not sure how feasible it would be to censor the env vars, while still allowing the line to be mostly useful.

**Comment by sivel** [comment] 2017-05-02 16:53
As far as Tower is concerned, researching how to reduce verbosity to not include those lines may be of benefit here.  For tower support or questions, please utilize https://access.redhat.com/products/ansible-tower-red-hat

**Comment by jctanner** [comment] 2019-04-29 13:34
duplicate of https://github.com/ansible/ansible/issues/17911

**Closed as completed by jctanner** 2019-04-29 13:34 UTC
Labels: affects_2.3, test, c:plugins/connection, c:utils/display, affects_2.4, support:community, bug
