### ISSUE TITLE
Publish to pypi

### ISSUE THREAD

**Issue by vmalloc** [ansible/ansible#1497] opened 2012-10-31 13:02 UTC
Although getting ansible through the "quick and dirty" manner is very useful for hacking scenarios, including it as a part of other projects requires being able to set it up from _easy_install_ or _pip_.

It would be great if this tool was published in pypi for each new release

**Comment by skorokithakis** [comment] 2012-11-01 17:53
This is a duplicate of #595.

**Comment by mpdehaan** [comment] 2012-11-01 23:39
Which should be doable once we adapt the pull request for #1509

**Comment by mpdehaan** [comment] 2012-11-02 00:35
I will take this personally when we release for 0.9.

**Comment by trompette** [comment] 2012-12-18 14:05
@mpdehaan what's the status of this issue now that 0.9 has been released?

**Comment by mpdehaan** [comment] 2012-12-19 01:46
status is mdehaan got distracted by new job.

Putting a note on my fridge to do it this week :)

**Comment by mpdehaan** [comment] 2012-12-23 17:40
done! see note on the mailing list for further details.

**Closed as completed by mpdehaan** 2012-12-23 17:40 UTC

**Comment by vmalloc** [comment] 2012-12-24 05:51
w00t!
