### ISSUE TITLE
Exception on include_role

### ISSUE THREAD

**Issue by olfway** [ansible/ansible#31093] opened 2017-09-29 13:19 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Module: include_role

##### ANSIBLE VERSION
```
ansible 2.4.0.0 (detached HEAD 2eac554eb4) last updated 2017/09/29 16:02:05 (GMT +300)
  config file = None
  configured module search path = [u'/Users/int/Projects/Ansible/Ansible/ansible-2.4/library']
  ansible python module location = /Users/int/Projects/Ansible/Ansible/ansible-2.4/lib/ansible
  executable location = /Users/int/Projects/Ansible/Ansible/ansible-2.4/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:54:19) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

##### CONFIGURATION
```
DEFAULT_MODULE_PATH(env: ANSIBLE_LIBRARY) = [u'/Users/int/Projects/Ansible/Ansible/ansible-2.4/library']
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Got exception on include_tasks -> include_role

This begins with commit 2eac554eb4cd636a334dbea1b0a6812b3be2ed73
```
commit 2eac554eb4cd636a334dbea1b0a6812b3be2ed73 (HEAD)
Author: Brian Coca <brian.coca+git@gmail.com>
Date:   Thu Sep 21 22:22:01 2017 -0400

    use set to quicken group host membership

    (cherry picked from commit 3f9a885b83aa7c7d4cc7c102c24340ebb432017c)
```
same error with latest devel (commit 916e6be888bb1f2f38be8dce126222fa63b772e2)
and latest stable-2.4 (commit adc3bedaa2f649dafbe2a991d190a99c4da8d3c4)

##### STEPS TO REPRODUCE
play.yml
```
---
- hosts: all
  gather_facts: no

  tasks:
    - include_tasks: play_include_role.yml
...
```
play_include_role.yml
```
---
- include_role: name=roleA
...
```
roles/roleA/tasks/main.yml
```
---
- debug:
    msg: "ok!"
...
```

ansible-playbook -i test1,test2,test3 play.yml

##### EXPECTED RESULTS
```
PLAY [all] ********************************************************************************************************************************************************************************************************

TASK [include_tasks] **********************************************************************************************************************************************************************************************
included: /Users/int/Projects/Ansible/Ansible/ansible-test/play_include_role.yml for test1, test2, test3

TASK [include_role] ***********************************************************************************************************************************************************************************************

TASK [roleA : debug] **********************************************************************************************************************************************************************************************
ok: [test2] => {
    "msg": "ok!"
}
ok: [test1] => {
    "msg": "ok!"
}
ok: [test3] => {
    "msg": "ok!"
}

PLAY RECAP ********************************************************************************************************************************************************************************************************
test1                      : ok=2    changed=0    unreachable=0    failed=0
test2                      : ok=2    changed=0    unreachable=0    failed=0
test3                      : ok=2    changed=0    unreachable=0    failed=0
```

##### ACTUAL RESULTS
```
PLAYBOOK: play.yml ************************************************************************************************************************************************************************************************
1 plays in play.yml

PLAY [all] ********************************************************************************************************************************************************************************************************
META: ran handlers

TASK [include_tasks] **********************************************************************************************************************************************************************************************
task path: /Users/int/Projects/Ansible/Ansible/ansible-test/play.yml:6
included: /Users/int/Projects/Ansible/Ansible/ansible-test/play_include_role.yml for test1, test2, test3

TASK [include_role] ***********************************************************************************************************************************************************************************************
task path: /Users/int/Projects/Ansible/Ansible/ansible-test/play_include_role.yml:2
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/int/Projects/Ansible/Ansible/ansible-2.4/lib/ansible/plugins/strategy/__init__.py", line 84, in results_thread_main
    result = strategy._final_q.get()
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/queues.py", line 117, in get
    res = self._recv()
  File "/Users/int/Projects/Ansible/Ansible/ansible-2.4/lib/ansible/inventory/host.py", line 37, in __setstate__
    return self.deserialize(data)
  File "/Users/int/Projects/Ansible/Ansible/ansible-2.4/lib/ansible/inventory/host.py", line 82, in deserialize
    g.deserialize(group_data)
  File "/Users/int/Projects/Ansible/Ansible/ansible-2.4/lib/ansible/inventory/group.py", line 77, in deserialize
    self._hosts = set(self.hosts)
  File "/Users/int/Projects/Ansible/Ansible/ansible-2.4/lib/ansible/inventory/host.py", line 48, in __hash__
    return hash(self.name)
AttributeError: 'Host' object has no attribute 'name'

^C [ERROR]: User interrupted execution
```

**Comment by bcoca** [comment] 2017-09-29 16:14
dupe of #30903

**Closed as completed by bcoca** 2017-09-29 16:14 UTC
Labels: module, affects_2.4, support:core, bug
