### ISSUE TITLE
Ansible 1.5.2 fails when gathering facts with trivial localhost playbook

### ISSUE THREAD

**Issue by FiloSottile** [ansible/ansible#6472] opened 2014-03-13 15:29 UTC
```
$ cat inventory.ini
[local]
localhost ansible_connection=local

$ cat test.yml
- hosts: local
  tasks:
    - git: dest=tmp repo=git@github.com:[REDACTED].git depth=1 version=master

$ ansible-playbook --version
ansible-playbook 1.5.2

$ ansible-playbook -i inventory.ini test.yml

PLAY [local] ******************************************************************

GATHERING FACTS ***************************************************************
failed: [localhost] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/Users/filosottile/.ansible/tmp/ansible-tmp-1394724478.91-116117321188700/setup", line 3442, in <module>
    main()
  File "/Users/filosottile/.ansible/tmp/ansible-tmp-1394724478.91-116117321188700/setup", line 2359, in main
    data = run_setup(module)
  File "/Users/filosottile/.ansible/tmp/ansible-tmp-1394724478.91-116117321188700/setup", line 2300, in run_setup
    facts = ansible_facts(module)
  File "/Users/filosottile/.ansible/tmp/ansible-tmp-1394724478.91-116117321188700/setup", line 2291, in ansible_facts
    facts.update(Network(module).populate())
TypeError: __init__() takes exactly 1 argument (2 given)


TASK: [git dest=tmp repo=git@github.com:[REDACTED].git depth=1 version=master] ***
FATAL: no hosts matched or all hosts have already failed -- aborting


PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/filosottile/test.retry

localhost                  : ok=0    changed=0    unreachable=0    failed=1   
```

**Comment by jctanner** [comment] 2014-03-13 15:54
duplicate of #6430

**Closed as completed by jctanner** 2014-03-13 15:54 UTC
Labels: bug
