### ISSUE TITLE
docker module doesn't restart container

### ISSUE THREAD

**Issue by rubycut** [ansible/ansible#8278] opened 2014-07-24 13:16 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.6
##### Environment:

Ubuntu 12.04, managing ubuntu 12.04
##### Summary:

Docker module doesn't restart container if wrong tag is running.
##### Steps To Reproduce:

start container with one tag

use docker module to put container in running state with another tag
##### Expected Results:

Container should be restarted with proper tag.
##### Actual Results:

Nothing happens, old version remains running, msg is:

```
"msg": "pull 0 restarted 0 started 0 created 0 stopped 0 removed 0 killed 0  container(s) running image docker.xxx.net/app:3.4.21 with command None"
```

**Comment by mpdehaan** [comment] 2014-07-24 13:32
Can you please share the ansible commands you used for each of the above steps?

It's unclear how to reproduce this for me right now and that would help a lot.

Thanks!

**Comment by rubycut** [comment] 2014-08-12 07:50
```
# Dockerfile
FROM ubuntu:12.04
RUN echo test image   
CMD sleep 1000
```

Make first image:

```
docker build -t test:1.0 .
```

Edit file:

```
 # Dockerfile 2.0
FROM ubuntu:12.04
RUN echo test image  2
CMD sleep 1000
```

Make second image:

```
docker build -t test:2.0 .
```

Ansible recipe:

```
- hosts:
    - myhost
  tasks:
    - docker: image=test:1.0  state=running
```

Run version 1:

```
ansible-playbook test_docker.yml
```

Try switching to version 2:

```
---
- hosts:
  - sysmon.jenkins
  tasks:
    - docker: image=test:2.0  state=running
```

Run version 2:

```
ansible-playbook test_docker.yml
```

docker image with tag 1.0 is still running, It was not restarted switched to image with version 2

**Comment by jimi-c** [comment] 2014-08-15 04:39
@rubycut I've created the above commit, which resolves the issue in my testing, if you'd like to test it out before I merge it.

**Comment by pr0xr** [comment] 2014-08-16 06:01
Note that docker has recently changed its behavior for restarting containers and will be included in the next release. https://github.com/docker/docker/issues/7226

**Comment by jimi-c** [comment] 2014-08-17 02:13
@pandrew I don't think this is necessarily related to that new behavior, as our module was only checking the name to determine if the container should be started. My patch above also has it check the tag, and if different, stop/remove the existing container and start it using the new image:tag.

**Comment by pr0xr** [comment] 2014-08-17 07:37
@jimi-c  nop not related to tags per se. Maybe it should be in a new PR.

**Comment by jimi-c** [comment] 2014-08-26 18:37
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2014-08-26 18:37 UTC
Labels: cloud, P2, docker, bug
