### ISSUE TITLE
Relative path not used in file module when creating directory

### ISSUE THREAD

**Issue by markaolson** [ansible/ansible#8508] opened 2014-08-08 03:26 UTC
##### Issue Type:

Bug Report

<br>
##### Ansible Version:

```
$ ansible --version
  ansible 1.7
```

<br>
##### Environment:

OS: Ubuntu 14.04.1

Running a playbook that runs on localhost. Does not run on a remote system.

The playbook was designed to create a stubbed out directory for a new Ansible role. 

<br>
##### Summary:

Here's a gist containing a playbook.
https://gist.github.com/maoja/a18b0927d10d353f2e45

Let's simplify the task

```
- name: create role directories
  file: path=roles/sample state=directory
```

<br>

Current working directory is ~/code/ansible 

In Ansible 1.6.x the current working directory (~/code/ansible) is pre-prended to path value (roles/sample) of the file module. 
The result is a new directory ~/code/ansible/roles/sample

In Ansible 1.7.0 the current working directory is NOT pre-pended to the path value.
In Ansible 1.7.0 the file module will attempt to create the directory under /. 
So it will attempt to create /roles/sample 

When not running with sudo the task will fail due to lack of permission to create a directory under /

<br>

I tried changing my task to look like this

```
- name: create role directories
  file: path=./roles/sample state=directory
```

Still didn't work in 1.7.0.  Even with the leading './' it still tries to create the directory in /roles

Then I changed it to 

```
- name: create role directories
  file: path=~/code/ansible/roles/sample state=directory
```

It correctly expands the ~ and creates the directory in my home directory (/home/majoa/code/ansible/roles/sample)

I really need it stay consistent with the 1.6.x behavior of pre-pending the current working directory to the path.

If I use ~/code/ansible and my co-worker uses ~/ansible_stuff we need the module to create directories relative to our current working directories (unless we explicitly specify a full path). 

<br>
##### Steps To Reproduce:

Install Ansible 1.7.0

Run this

```
cd ~/
wget https://gist.githubusercontent.com/maoja/06375aff6559534b628d/raw/cef8a5a6671ae69ba607f988e3ae09c3b8d09181/ansible_1.7_relative_path_test.sh
chmod +x ansible_1.7_relative_path_test.sh
./ansible_1.7_relative_path_test.sh
```

You will be prompted for a new role name. Just hit enter to accept the default value (sample).

<br>

<br>
##### Expected Results:

The following directory structure should be created.

```
~/code/
   ansible/
     roles/
       sample/
         defaults/
         files/
         handlers/
         meta/
         tasks/
         templates/
         vars/
```

<br>
##### Actual Results:

An error occurs because the file module is trying to create the directory under / instead of the current working directory which is ~/code/ansible

```
OSError: [Errno 13] Permission denied: '/roles'
```

**Comment by mpdehaan** [comment] 2014-08-08 13:57
Info not related to the above:

"The playbook was designed to create a stubbed out directory for a new Ansible role."

FYI, this is what the "ansible-galaxy init rolename" command does.

**Comment by mpdehaan** [comment] 2014-08-08 13:59
I'm not positive we ever defined the cwd for local ops, usually folks do "{{ playbook_basedir }}/path/foo" but I agree attempting to create in "/" would be unintuitive.

**Comment by markaolson** [comment] 2014-08-08 14:40
I just tried

```
file: path="{{ playbook_dir }}/roles/foo
```

and I got this error

```
fatal: [127.0.0.1] => One or more undefined variables: 'playbook_basedir' is undefined
```

So then I tried

```
  file: path="{{ playbook_dir }}/roles/foo"
```

and I got this error

```
OSError: [Errno 13] Permission denied: '/./roles'
```

See https://github.com/ansible/ansible/issues/8317

**Comment by jimi-c** [comment] 2014-08-12 14:06
cc @bcoca

**Comment by markaolson** [comment] 2014-08-14 02:01
Thank you for the workaround and for looking into the issue!

**Comment by jimi-c** [comment] 2014-08-18 18:23
# Closing This Ticket

Hi!

We believe the commit which fixed #8317 should resolve this question or problem for you. Using `playbook_dir` is the correct variable to use here, and in our testing we see this is resolved. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2014-08-18 18:23 UTC
Labels: P1, bug

**Comment by rkumar357** [comment] 2017-03-12 19:11
ansible --version
ansible 2.2.1.0
  config file = /Users/rkumar357/.ansible.cfg
  configured module search path = Default w/o overrides

Its still creating under my home dir, not using playbook_dir value, any help in this ?? 

Thanks

**Comment by jimi-c** [comment] 2017-08-18 13:32
@rkumar357 sorry for the late reply, but if you're still seeing this and you have a reproducer please open a new issue.

Thanks!
