### ISSUE TITLE
Bugged behavior using block with include tasks in a playbook

### ISSUE THREAD

**Issue by orderedchaosdev** [ansible/ansible#41042] opened 2018-06-02 01:22 UTC
##### SUMMARY

While using a block in a task added through include_tasks or import_tasks, I have noticed the output seems to desync and cause odd behavior and output.
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

block
include_tasks
import_tasks

##### ANSIBLE VERSION

```
ansible 2.4.4.0
  python version = 2.7.14 (default, Mar 21 2018, 16:45:24) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
ansible 2.5.4
  python version = 2.7.14 (default, Mar 21 2018, 16:45:24) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### OS / ENVIRONMENT

N/A
##### STEPS TO REPRODUCE

I have 5 hosts that this would run against.
while example was done in aws that is probably unrelated.

testing4.yml
```yaml
---

- hosts: tag_Name_seantests_{{ env }}_*
  user: ec2-user
  become: true
  gather_facts: true
  tasks:
    - name: setup facts
      set_fact:
        all_good: 1

    - name: setup one to fail
      set_fact:
        all_good: 0
      when: inventory_hostname == play_hosts[-1]

- hosts: tag_Name_seantests_{{ env }}_*
  user: ec2-user
  become: true
  gather_facts: true
  pre_tasks:
    - set_fact:
        current_run_timestamp: '{{ lookup("pipe", "date -u +%Y%m%d%H%M%S") }}'
      run_once: yes
      tags:
        - always
  roles:
    - { role: role-testing2 }

```
roles/role-testing2/tasks/main.yml
```yaml
---

- name: including tasks
  include_tasks: route1.yml

```
roles/role-testing2/tasks/route1.yml
```yaml
---

- name: Testing blocks
  block:
    # - debug: var=all_good
    - name: "Main block: Checking if all_good"
      assert:
        that: all_good == 1
        msg: "All good should be 1"
      register: assert_asserting
    - name: "Main block: Setting winners only fact"
      set_fact:
        we_win: true
  rescue:
    - name: "Rescue block: Debug assert_asserting"
      debug: var=assert_asserting
    - name: "Rescue block: Setting losers only fact"
      set_fact:
        we_lose: true
    - name: "Rescue block: Debug rescue all good"
      debug:
        msg: "All good was {{ all_good }}"
  always:
    - name: "Always block: Debug assert_asserting"
      debug: var=assert_asserting
    - fail:
        msg: "Failed asserting all good"
      when: assert_asserting is failed

- name: "Post block: Debug assert_asserting"
  debug:
    var: "assert_asserting"

```

##### EXPECTED RESULTS

This is what happens if I replace roles/role-testing2/tasks/main.yml with roles/role-testing2/tasks/route1.yml thus removing the include_tasks step
```
ansible-playbook testing4.yml -e "env=dev"


PLAY [tag_Name_seantests_dev_*] ***************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************
ok: [192.168.1.26]
ok: [192.168.1.28]
ok: [192.168.1.32]
ok: [192.168.1.20]
ok: [192.168.1.18]

TASK [setup facts] ***************************************************************************************************************************************************************
ok: [192.168.1.20]
ok: [192.168.1.28]
ok: [192.168.1.26]
ok: [192.168.1.18]
ok: [192.168.1.32]

TASK [setup one to fail] *********************************************************************************************************************************************************
skipping: [192.168.1.28]
ok: [192.168.1.20]
skipping: [192.168.1.26]
skipping: [192.168.1.18]
skipping: [192.168.1.32]

PLAY [tag_Name_seantests_dev_*] ***************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************
ok: [192.168.1.26]
ok: [192.168.1.20]
ok: [192.168.1.28]
ok: [192.168.1.18]
ok: [192.168.1.32]

TASK [set_fact] ******************************************************************************************************************************************************************
ok: [192.168.1.20]

TASK [role-testing2 : Main block: Checking if all_good] **************************************************************************************************************************
fatal: [192.168.1.20]: FAILED! => {
    "assertion": "all_good == 1",
    "changed": false,
    "evaluated_to": false,
    "failed": true,
    "msg": "All good should be 1"
}
ok: [192.168.1.28] => {
    "changed": false,
    "failed": false,
    "msg": "All assertions passed"
}
ok: [192.168.1.26] => {
    "changed": false,
    "failed": false,
    "msg": "All assertions passed"
}
ok: [192.168.1.18] => {
    "changed": false,
    "failed": false,
    "msg": "All assertions passed"
}
ok: [192.168.1.32] => {
    "changed": false,
    "failed": false,
    "msg": "All assertions passed"
}

TASK [role-testing2 : Main block: Setting winners only fact] *********************************************************************************************************************
ok: [192.168.1.28]
ok: [192.168.1.26]
ok: [192.168.1.18]
ok: [192.168.1.32]

TASK [role-testing2 : Rescue block: Debug assert_asserting] **********************************************************************************************************************
ok: [192.168.1.20] => {
    "assert_asserting": {
        "assertion": "all_good == 1",
        "changed": false,
        "evaluated_to": false,
        "failed": true,
        "msg": "All good should be 1"
    }
}

TASK [role-testing2 : Rescue block: Setting losers only fact] ********************************************************************************************************************
ok: [192.168.1.20]

TASK [role-testing2 : Rescue block: Debug rescue all good] ***********************************************************************************************************************
ok: [192.168.1.20] => {
    "msg": "All good was 0"
}

TASK [role-testing2 : Always block: Debug assert_asserting] **********************************************************************************************************************
ok: [192.168.1.20] => {
    "assert_asserting": {
        "assertion": "all_good == 1",
        "changed": false,
        "evaluated_to": false,
        "failed": true,
        "msg": "All good should be 1"
    }
}
ok: [192.168.1.28] => {
    "assert_asserting": {
        "changed": false,
        "failed": false,
        "msg": "All assertions passed"
    }
}
ok: [192.168.1.26] => {
    "assert_asserting": {
        "changed": false,
        "failed": false,
        "msg": "All assertions passed"
    }
}
ok: [192.168.1.18] => {
    "assert_asserting": {
        "changed": false,
        "failed": false,
        "msg": "All assertions passed"
    }
}
ok: [192.168.1.32] => {
    "assert_asserting": {
        "changed": false,
        "failed": false,
        "msg": "All assertions passed"
    }
}

TASK [role-testing2 : fail] ******************************************************************************************************************************************************
skipping: [192.168.1.28]
fatal: [192.168.1.20]: FAILED! => {"changed": false, "failed": true, "msg": "Failed asserting all good"}
skipping: [192.168.1.26]
skipping: [192.168.1.18]
skipping: [192.168.1.32]

TASK [role-testing2 : Post block: Debug assert_asserting] ************************************************************************************************************************
ok: [192.168.1.28] => {
    "assert_asserting": {
        "changed": false,
        "failed": false,
        "msg": "All assertions passed"
    }
}
ok: [192.168.1.26] => {
    "assert_asserting": {
        "changed": false,
        "failed": false,
        "msg": "All assertions passed"
    }
}
ok: [192.168.1.18] => {
    "assert_asserting": {
        "changed": false,
        "failed": false,
        "msg": "All assertions passed"
    }
}
ok: [192.168.1.32] => {
    "assert_asserting": {
        "changed": false,
        "failed": false,
        "msg": "All assertions passed"
    }
}

PLAY RECAP ***********************************************************************************************************************************************************************
192.168.1.18               : ok=7    changed=0    unreachable=0    failed=0
192.168.1.20               : ok=9    changed=0    unreachable=0    failed=2
192.168.1.26               : ok=7    changed=0    unreachable=0    failed=0
192.168.1.28               : ok=7    changed=0    unreachable=0    failed=0
192.168.1.32               : ok=7    changed=0    unreachable=0    failed=0
```
##### ACTUAL RESULTS

```
ansible-playbook testing4.yml -e "env=dev"

PLAY [tag_Name_seantests_dev_*] ***************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************
ok: [192.168.1.28]
ok: [192.168.1.32]
ok: [192.168.1.26]
ok: [192.168.1.20]
ok: [192.168.1.18]

TASK [setup facts] ***************************************************************************************************************************************************************
ok: [192.168.1.20]
ok: [192.168.1.28]
ok: [192.168.1.26]
ok: [192.168.1.18]
ok: [192.168.1.32]

TASK [setup one to fail] *********************************************************************************************************************************************************
skipping: [192.168.1.28]
ok: [192.168.1.20]
skipping: [192.168.1.26]
skipping: [192.168.1.18]
skipping: [192.168.1.32]

PLAY [tag_Name_seantests_dev_*] ***************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************
ok: [192.168.1.28]
ok: [192.168.1.20]
ok: [192.168.1.26]
ok: [192.168.1.32]
ok: [192.168.1.18]

TASK [set_fact] ******************************************************************************************************************************************************************
ok: [192.168.1.20]

TASK [role-testing2 : including tasks] *******************************************************************************************************************************************
included: yada/roles/role-testing2/tasks/route1.yml for 192.168.1.20, 192.168.1.28, 192.168.1.26, 192.168.1.18, 192.168.1.32

TASK [role-testing2 : Main block: Checking if all_good] **************************************************************************************************************************
fatal: [192.168.1.20]: FAILED! => {
    "assertion": "all_good == 1",
    "changed": false,
    "evaluated_to": false,
    "failed": true,
    "msg": "All good should be 1"
}
ok: [192.168.1.28] => {
    "changed": false,
    "failed": false,
    "msg": "All assertions passed"
}
ok: [192.168.1.26] => {
    "changed": false,
    "failed": false,
    "msg": "All assertions passed"
}
ok: [192.168.1.18] => {
    "changed": false,
    "failed": false,
    "msg": "All assertions passed"
}
ok: [192.168.1.32] => {
    "changed": false,
    "failed": false,
    "msg": "All assertions passed"
}

TASK [role-testing2 : Rescue block: Debug assert_asserting] **********************************************************************************************************************
ok: [192.168.1.20] => {
    "assert_asserting": {
        "assertion": "all_good == 1",
        "changed": false,
        "evaluated_to": false,
        "failed": true,
        "msg": "All good should be 1"
    }
}
ok: [192.168.1.28]
ok: [192.168.1.26]
ok: [192.168.1.18]
ok: [192.168.1.32]

TASK [role-testing2 : Rescue block: Setting losers only fact] ********************************************************************************************************************
ok: [192.168.1.20]
ok: [192.168.1.28] => {
    "assert_asserting": {
        "changed": false,
        "failed": false,
        "msg": "All assertions passed"
    }
}
ok: [192.168.1.26] => {
    "assert_asserting": {
        "changed": false,
        "failed": false,
        "msg": "All assertions passed"
    }
}
ok: [192.168.1.18] => {
    "assert_asserting": {
        "changed": false,
        "failed": false,
        "msg": "All assertions passed"
    }
}
ok: [192.168.1.32] => {
    "assert_asserting": {
        "changed": false,
        "failed": false,
        "msg": "All assertions passed"
    }
}

TASK [role-testing2 : Rescue block: Debug rescue all good] ***********************************************************************************************************************
skipping: [192.168.1.28]
ok: [192.168.1.20] => {
    "msg": "All good was 0"
}
skipping: [192.168.1.26]
skipping: [192.168.1.18]
skipping: [192.168.1.32]

TASK [role-testing2 : Always block: Debug assert_asserting] **********************************************************************************************************************
ok: [192.168.1.20] => {
    "assert_asserting": {
        "assertion": "all_good == 1",
        "changed": false,
        "evaluated_to": false,
        "failed": true,
        "msg": "All good should be 1"
    }
}
ok: [192.168.1.28] => {
    "assert_asserting": {
        "changed": false,
        "failed": false,
        "msg": "All assertions passed"
    }
}
ok: [192.168.1.26] => {
    "assert_asserting": {
        "changed": false,
        "failed": false,
        "msg": "All assertions passed"
    }
}
ok: [192.168.1.18] => {
    "assert_asserting": {
        "changed": false,
        "failed": false,
        "msg": "All assertions passed"
    }
}
ok: [192.168.1.32] => {
    "assert_asserting": {
        "changed": false,
        "failed": false,
        "msg": "All assertions passed"
    }
}

TASK [role-testing2 : fail] ******************************************************************************************************************************************************
fatal: [192.168.1.20]: FAILED! => {"changed": false, "failed": true, "msg": "Failed asserting all good"}

TASK [role-testing2 : Post block: Debug assert_asserting] ************************************************************************************************************************
ok: [192.168.1.20] => {
    "assert_asserting": {
        "assertion": "all_good == 1",
        "changed": false,
        "evaluated_to": false,
        "failed": true,
        "msg": "All good should be 1"
    }
}

PLAY RECAP ***********************************************************************************************************************************************************************
192.168.1.18               : ok=8    changed=0    unreachable=0    failed=0
192.168.1.20               : ok=11   changed=0    unreachable=0    failed=2
192.168.1.26               : ok=8    changed=0    unreachable=0    failed=0
192.168.1.28               : ok=8    changed=0    unreachable=0    failed=0
192.168.1.32               : ok=8    changed=0    unreachable=0    failed=0
```
Interesting note if you change the play_hosts part to play_hosts[0] the output is different and you won't see the rescue output statements at all.
Example of that below
```
ansible-playbook testing4.yml -e "env=dev"


PLAY [tag_Name_seantests_dev_*] ***************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************
ok: [192.168.1.18]
ok: [192.168.1.28]
ok: [192.168.1.20]
ok: [192.168.1.32]
ok: [192.168.1.26]

TASK [setup facts] ***************************************************************************************************************************************************************
ok: [192.168.1.20]
ok: [192.168.1.28]
ok: [192.168.1.26]
ok: [192.168.1.18]
ok: [192.168.1.32]

TASK [setup one to fail] *********************************************************************************************************************************************************
skipping: [192.168.1.20]
skipping: [192.168.1.28]
skipping: [192.168.1.26]
skipping: [192.168.1.18]
ok: [192.168.1.32]

PLAY [tag_Name_seantests_dev_*] ***************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************
ok: [192.168.1.20]
ok: [192.168.1.28]
ok: [192.168.1.18]
ok: [192.168.1.32]
ok: [192.168.1.26]

TASK [set_fact] ******************************************************************************************************************************************************************
ok: [192.168.1.20]

TASK [role-testing2 : including tasks] *******************************************************************************************************************************************
included: yada/roles/role-testing2/tasks/route1.yml for 192.168.1.20, 192.168.1.28, 192.168.1.26, 192.168.1.18, 192.168.1.32

TASK [role-testing2 : Main block: Checking if all_good] **************************************************************************************************************************
ok: [192.168.1.20] => {
    "changed": false,
    "failed": false,
    "msg": "All assertions passed"
}
ok: [192.168.1.28] => {
    "changed": false,
    "failed": false,
    "msg": "All assertions passed"
}
ok: [192.168.1.26] => {
    "changed": false,
    "failed": false,
    "msg": "All assertions passed"
}
ok: [192.168.1.18] => {
    "changed": false,
    "failed": false,
    "msg": "All assertions passed"
}
fatal: [192.168.1.32]: FAILED! => {
    "assertion": "all_good == 1",
    "changed": false,
    "evaluated_to": false,
    "failed": true,
    "msg": "All good should be 1"
}

TASK [role-testing2 : Main block: Setting winners only fact] *********************************************************************************************************************
ok: [192.168.1.20]
ok: [192.168.1.28]
ok: [192.168.1.26]
ok: [192.168.1.18]
ok: [192.168.1.32] => {
    "assert_asserting": {
        "assertion": "all_good == 1",
        "changed": false,
        "evaluated_to": false,
        "failed": true,
        "msg": "All good should be 1"
    }
}

TASK [role-testing2 : Always block: Debug assert_asserting] **********************************************************************************************************************
ok: [192.168.1.20] => {
    "assert_asserting": {
        "changed": false,
        "failed": false,
        "msg": "All assertions passed"
    }
}
ok: [192.168.1.28] => {
    "assert_asserting": {
        "changed": false,
        "failed": false,
        "msg": "All assertions passed"
    }
}
ok: [192.168.1.26] => {
    "assert_asserting": {
        "changed": false,
        "failed": false,
        "msg": "All assertions passed"
    }
}
ok: [192.168.1.18] => {
    "assert_asserting": {
        "changed": false,
        "failed": false,
        "msg": "All assertions passed"
    }
}
ok: [192.168.1.32]

TASK [role-testing2 : fail] ******************************************************************************************************************************************************
skipping: [192.168.1.20]
skipping: [192.168.1.28]
skipping: [192.168.1.26]
skipping: [192.168.1.18]
ok: [192.168.1.32] => {
    "msg": "All good was 0"
}

TASK [role-testing2 : Post block: Debug assert_asserting] ************************************************************************************************************************
ok: [192.168.1.20] => {
    "assert_asserting": {
        "changed": false,
        "failed": false,
        "msg": "All assertions passed"
    }
}
ok: [192.168.1.28] => {
    "assert_asserting": {
        "changed": false,
        "failed": false,
        "msg": "All assertions passed"
    }
}
ok: [192.168.1.26] => {
    "assert_asserting": {
        "changed": false,
        "failed": false,
        "msg": "All assertions passed"
    }
}
ok: [192.168.1.18] => {
    "assert_asserting": {
        "changed": false,
        "failed": false,
        "msg": "All assertions passed"
    }
}
ok: [192.168.1.32] => {
    "assert_asserting": {
        "assertion": "all_good == 1",
        "changed": false,
        "evaluated_to": false,
        "failed": true,
        "msg": "All good should be 1"
    }
}

TASK [role-testing2 : fail] ******************************************************************************************************************************************************
fatal: [192.168.1.32]: FAILED! => {"changed": false, "failed": true, "msg": "Failed asserting all good"}

TASK [role-testing2 : Post block: Debug assert_asserting] ************************************************************************************************************************
ok: [192.168.1.32] => {
    "assert_asserting": {
        "assertion": "all_good == 1",
        "changed": false,
        "evaluated_to": false,
        "failed": true,
        "msg": "All good should be 1"
    }
}

PLAY RECAP ***********************************************************************************************************************************************************************
192.168.1.18               : ok=8    changed=0    unreachable=0    failed=0
192.168.1.20               : ok=9    changed=0    unreachable=0    failed=0
192.168.1.26               : ok=8    changed=0    unreachable=0    failed=0
192.168.1.28               : ok=8    changed=0    unreachable=0    failed=0
192.168.1.32               : ok=10   changed=0    unreachable=0    failed=2
```

**Comment by orderedchaosdev** [comment] 2018-06-02 01:27
I updated it to add an additional bugged output from changing which playhost fails

**Comment by orderedchaosdev** [comment] 2018-06-02 01:39
I updated the ansible version to include ansible 2.5.4.0 as well.

**Comment by mkrizek** [comment] 2018-06-02 08:40
Note, this might be a duplicate of https://github.com/ansible/ansible/issues/35356. PR that attempts to fix that issue is https://github.com/ansible/ansible/pull/36056.

**Comment by mkrizek** [comment] 2018-06-04 10:32
Duplicate of #35356

**Closed as completed by mkrizek** 2018-06-04 10:32 UTC
Labels: module, affects_2.4, support:core, bug
