### ISSUE TITLE
Updating owner on existing directory using file module does not update parents

### ISSUE THREAD

**Issue by dandrestor** [ansible/ansible#25596] opened 2017-06-12 10:59 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
file module

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
If creating a directory with a certain owner, i.e. use file state=directory with a non-existing path, all the necessary parent directories will be created with the same owner. If the directory already exists with a different owner, it itself will be updated to the new owner, but not the parents.

##### STEPS TO REPRODUCE
Ensure `/some/test/path exists`, and that `/some` and `/some/test` are owned by `root`.

Run then the following task:

```yaml
- name: Test task
  file:
    path: "/some/test/path"
    state: directory
    owner: some_user
    group: some_group
    mode: 0750
  become: yes
```

##### EXPECTED RESULTS
Parent directories `/some` and `/some/test` updated to new owner `some_user`

##### ACTUAL RESULTS
Parent directories not updated

**Comment by bcoca** [comment] 2017-06-12 15:41
I don't think your expectation is correct, I would not expect all parents to change when creating a directory. For example `/` is also a parent here, would you also expect it to change?

**Comment by dandrestor** [comment] 2017-06-12 16:01
Sorry, I realize now I was unclear. I haven't tested the case when creating a directory with pre-existing parents, only 1) creating both the child and the parents at the same time (the result being that the parents are created with same permissions) and 2) updating an existing child (obviously with existing parents, the result being that the parents are not touched).

I see your point; however I would expect the task to be idempotent. Right now its behaviour with respect to the parents is not the same, depending on whether the parents already exist or not. Maybe it would be a good idea to introduce a parameter, something like 'update_parents'?

**Comment by bcoca** [comment] 2017-06-12 16:05
I would suggest that if you really want to ensure the parents permission, you have a file action per parent, I don't think this is a good idea nor should it ever be the default.  There is no way for Ansible to know 'which parents' it was responsible for creating nor where we should stop going up the tree.

I would even go as far as saying that autocreating the parents is bad behaviour but that has already been grandfathered in.

That said, I'm going to close this as it is not a bug.

**Closed as completed by bcoca** 2017-06-12 16:05 UTC
Labels: affects_2.3, module, bug

**Comment by dandrestor** [comment] 2017-06-12 16:13
I agree with auto-creating the parents by default being bad behaviour. If this is unlikely to change as you say, wouldn't it be a good idea to at least parametrize this and allow the user to get consistent behaviour, as a second-best alternative to being backwards-incompatible?

**Comment by bcoca** [comment] 2017-06-12 17:01
how do you get consistent behaviour?

machine A has `/some`, machine B has `/some/test` machine C has `/` ... once it runs the first time all 3 have `/some/test` ... how is it supposed to know on other runs which/what directories it much change permissions to?

**Comment by dandrestor** [comment] 2017-06-12 18:55
Make it behave like mkdir. Have a parameter `create_path`; this could default to `true` (shudder) if you want to be backwards-compatible.

Also, discern between the perms on the destination directory, and whether the directory is accessible (perms on the parents). Have another parameter `path_access` which controls the latter, something along the lines of:

- `none` - never change the parents
- `owner` - make `owner` own all the parents, and apply `u+x`
- `group` - make `group` own all the parents, and apply `g+x`
- `other` - make parents `o+x`
- `adapt` - do not change owner or group on parents, but grant `u+x`, `g+x` or `o+x` as appropriate to ensure access at each level.
- (these are off the top of my head, I'm sure more useful models could be found)

Fail when unable to satisfy the requested state. For instance, when the parents are owned by someone else with perms 700 and `path_access=none`, or when `create_path=false` and parents do not exist.

Now that I've written it, it does look quite complicated, however I believe the file module sets out do to quite a lot, so this level of complexity might be warranted. What do you think?

**Comment by bcoca** [comment] 2017-06-12 19:24
I think you should just use this:

```
file: path={{item}} < permissions.>
with_items:
   - /some
   - /some/test
```

**Comment by dandrestor** [comment] 2017-06-13 11:10
Thanks, I'm currently doing something similar. I wasn't asking for help though, rather I was making an improvement suggestion (again, as a second choice behind just deprecating the whole parent thing). What do you think of the idea?

**Comment by bcoca** [comment] 2017-06-13 13:13
I don't think it is viable, just look at the example i gave above, which directories should i change permissions and to what on each machine?

**Comment by dandrestor** [comment] 2017-06-13 15:28
In short, ansible should change it precisely as the user says it should. Your example above is no exception; say the user runs with `create_path=true` and `path_access=owner`, then ansible should create all the parents (if they don't exist) and change ownership to `owner`, just as described. This (and any other combination of parameters) would always have the same result on all three machines A, B and C, unlike the current behaviour of `file`.
