### ISSUE TITLE
Problem connection to Arista node when using ansible 2.3.2 and paramiko 1.16.0-1 (the official Ubuntu 16.04.3 deb)

### ISSUE THREAD

**Issue by rkandilarov** [ansible/ansible#28268] opened 2017-08-16 09:46 UTC
##### ISSUE TYPE

 - Bug Report
 
##### COMPONENT NAME

modules eos_*, paramiko 

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file = /home/ansible-manager/config/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

Default configuration

##### OS / ENVIRONMENT

- Answible running from Ubuntu 
```
lsb_release -a
```
> Distributor ID: Ubuntu
> Description:    Ubuntu 16.04.3 LTS
> Release:        16.04
> Codename:       xenial

```
dpkg -s ansible
```

> Package: ansible
> Status: install ok installed
> Priority: optional
> Section: admin
> Installed-Size: 15830
> Maintainer: Ansible, Inc. <info@ansible.com>
> Architecture: all
> Version: 2.3.2.0-1ppa\~xenial
> Depends: python-jinja2, python-yaml, python-paramiko, python-httplib2, python-six, python-crypto (>= 2.6), python-setuptools, sshpass, python-pkg-resources, python:any (<< 2.8), python:any (>= 2.7.5-5~)

```
dpkg -s python-paramiko
```
> Package: python-paramiko
> Status: install ok installed
> Priority: optional
> Section: python
> Installed-Size: 619
> Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
> Architecture: all
> Source: paramiko
> Version: 1.16.0-1
> Provides: python2.7-paramiko
> Depends: python-crypto (>= 2.1.0-2), python-ecdsa, python:any (<< 2.8), python:any (>= 2.7.5-5~)

- trying to control Arista (Virtual) switch 

```
show version
```
> Arista vEOS
> Software image version: 4.18.1F
> Architecture:           i386
> Internal build version: 4.18.1F-4591672.4181F
> Internal build ID:      6fcb426e-70a9-48b8-8958-54bb72ee28ed
> 

##### SUMMARY

This is not really ansible bug, but rather the official ubuntu paramiko package for 16.04.3  has some limitations. In short Paramiko 1.16.0-1 does not work with *ecdsa-sha2-nistp521* keys from *.ssh/known_hosts*. There is an [already fixed bug](https://github.com/paramiko/paramiko/issues/794) about that in paramiko. Arista switches have such type of key and it will be offered to ssh first.

When ssh adds automatically the node(Arista) ssh key to *.ssh/known_hosts* after simple logging into the Arista switch from bash
```bash
ssh administrator@test-arista-sw
```
> The authenticity of host 'test-arista-sw (192.168.100.128)' can't be established.
> ECDSA key fingerprint is SHA256:2CCjPqusOQ7wL8AvVXdM3968AClEQucxBXhVBTz1XH8.
> Are you sure you want to continue connecting (yes/no)? yes
> Warning: Permanently added '192.168.100.128' (ECDSA) to the list of known hosts.
 
an *ecdsa-sha2-nistp521* host key is offered from the arista switch and added. Assuming we have already valid key for the host ansible should connect without problems. But
```
export ANSIBLE_LOG_PATH=~/ansible.log
export ANSIBLE_DEBUG=True
ansible-playbook -vvvv get_arista_facts.yml
```
fails with 
> unable to open shell. Please see: https://docs.ansible.com/ansible/network_debug_troubleshooting.html#unable-to-open-shell

and in the ansible.log

> paramiko.hostkeys Unable to handle key of type ecdsa-sha2-nistp521
> paramiko.transport starting thread (client mode): 0x7327f650L
> paramiko.transport Local version/idstring: SSH-2.0-paramiko_1.16.0
> paramiko.transport Remote version/idstring: SSH-2.0-OpenSSH_6.6.1
> paramiko.transport Connected (version 2.0, client OpenSSH_6.6.1)
> paramiko.transport kex algos:[u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp521', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'diffie-hellman-group14-sha1'] server key:[u'ssh-rsa', u'ecdsa-sha2-nistp521', u'ssh-ed25519'] client encrypt:[u'aes256-gcm@openssh.com', u'aes128-gcm@openssh.com', u'aes256-ctr', u'aes192-ctr', u'aes128-ctr'] server encrypt:[u'aes256-gcm@openssh.com', u'aes128-gcm@openssh.com', u'aes256-ctr', u'aes192-ctr', u'aes128-ctr'] client mac:[u'hmac-sha2-512-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'hmac-sha2-512', u'hmac-sha2-256',u'hmac-sha1'] server mac:[u'hmac-sha2-512-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'hmac-sha2-512', u'hmac-sha2-256', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
> paramiko.transport Kex agreed: diffie-hellman-group14-sha1
> paramiko.transport Cipher agreed: aes128-ctr
> paramiko.transport MAC agreed: hmac-sha2-256
> paramiko.transport Compression agreed: none
> paramiko.transport kex engine KexGroup14 specified hash_algo <built-in function openssl_sha1>
> /usr/lib/python2.7/dist-packages/Crypto/Cipher/blockalgo.py:141: FutureWarning: CTR mode needs counter parameter, not IV 
> self._cipher = factory.new(key, *args, **kwargs)
> paramiko.transport Switch to new keys ...
> p=6763 u=ansible-manager |  connecting to host 192.168.100.128 returned an error
> p=6763 u=ansible-manager |  (14, 'Bad address')
> paramiko.transport EOF in transport thread
> p=6763 u=ansible-manager |  number of connection attempts exceeded, unable to connect to control socket
> p=6763 u=ansible-manager |  persistent_connect_interval=1, persistent_connect_retries=30
> p=6713 u=ansible-manager |  open_shell() returned 255   6763 1502874086.82866: Loading Connection 'ssh' from /usr/lib/python2.7/dist-packages/ansible/plugins/connection/ssh.py (found_in_cache=False, class_only=True)
>  failed to connect to control socket

Adding *ANSIBLE_PARAMIKO_HOST_KEY_AUTO_ADD=True* will override the key with the provided ssh-rsa.

Again - there is an [already fixed bug](https://github.com/paramiko/paramiko/issues/794) about that in paramiko. This bug report is just to save someone time as there are simple workarounds.

##### STEPS TO REPRODUCE

On clean Ubuntu installation run
```bash
apt-add-repository -y ppa:ansible/ansible
apt-get update
apt-get install ansible
```

```yaml
---
- name: Get facts on the Arista switch
  hosts: test-arista-sw
  connection: local

 tasks:
  - name: Get facts
    eos_facts:
      gather_subset: all
      provider: "{{ ans_provider }}"

  vars:
    ans_provider:
      host: "{{ inventory_hostname }}"
      username: administrator
      password: testtest
      authorize: yes
      transport: cli
      port: 22
```

##### EXPECTED RESULTS

Receive the facts object provided by the eos_facts module.

##### ACTUAL RESULTS

> MSG: unable to open shell. Please see: https://docs.ansible.com/ansible/network_debug_troubleshooting.html#unable-to-open-shell

```

```
##### Workarounds
One can do one of the:
- Remove manually the *ecdsa-sha2-nistp521* key from ~/.ssh/known_hosts and add ssh-rsa instead
- add *ANSIBLE_PARAMIKO_HOST_KEY_AUTO_ADD=True* which will override ~/.ssh/known_hosts and replace the *ecdsa-sha2-nistp521* with the *ssh-rsa*  provided by the arista switch.
- Update *python-paramiko* deb with py2deb or stdeb with version that includes the fixed bug.

**Comment by jborean93** [comment] 2017-08-17 01:23
Thanks @rkandilarov for the information, I'm not sure where the best location would be for it but it may be useful to put a quick note about it in the docs for paramiko on the Ansible site. I am going to close the issue as you have said it really isn't a bug but just for people to see, while it is closed the issue is still viewable by others.

**Closed as completed by jborean93** 2017-08-17 01:23 UTC
Labels: affects_2.3, support:core, bug
