### ISSUE TITLE
Ansible date variable not correct

### ISSUE THREAD

**Issue by dsgnr** [ansible/ansible#43665] opened 2018-08-04 20:49 UTC
##### SUMMARY

ansible_date_time.date not reporting correctly.
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

Not 100% sure which module this applies to...

##### ANSIBLE VERSION

```
ansible 2.6.2
config file = /etc/ansible/ansible.cfg
configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python2.7/dist-packages/ansible
executable location = /usr/bin/ansible
python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION

	ansible-config dump --only-changed
	ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
	ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=60s
	ANSIBLE_SSH_CONTROL_PATH(/etc/ansible/ansible.cfg) = /tmp/ansible-ssh-%%h-%%p-%%r
	CACHE_PLUGIN(/etc/ansible/ansible.cfg) = redis
	CACHE_PLUGIN_CONNECTION(/etc/ansible/ansible.cfg) = localhost:6379:0
	CACHE_PLUGIN_TIMEOUT(/etc/ansible/ansible.cfg) = 604800
	DEFAULT_FILTER_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/plugins/filter']
	DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 30
	DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = smart
	DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/hosts']
	DEFAULT_INTERNAL_POLL_INTERVAL(/etc/ansible/ansible.cfg) = 0.001
	DEFAULT_POLL_INTERVAL(/etc/ansible/ansible.cfg) = 15
	DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
	DEFAULT_VAULT_PASSWORD_FILE(/etc/ansible/ansible.cfg) = /etc/ansible/.vault_pass
	HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
	RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False

	
##### OS / ENVIRONMENT

Ubuntu 18.04, but also replicated on Centos 7.5

##### STEPS TO REPRODUCE

```---
- hosts: localhost

  tasks:
  - debug:
      msg: "{{ansible_date_time.date }}"
```

##### EXPECTED RESULTS

	root@vubnt004:/ansible# date
	Sat Aug  4 21:44:08 BST 2018
Playbook output:

	TASK [debug] **********************************************************************************************************************************************************
	ok: [localhost] => {
	    "msg": "2018-08-04"
	}
##### ACTUAL RESULTS

Using -vvv:

	PLAYBOOK: date.yml ****************************************************************************************************************************************************
	1 plays in date.yml

	PLAY [localhost] ******************************************************************************************************************************************************
	META: ran handlers

	TASK [debug] **********************************************************************************************************************************************************
	task path: /ansible/date.yml:5
	ok: [localhost] => {
	    "msg": "2018-08-01"
	}
	META: ran handlers
	META: ran handlers

```
 ap date.yml -vvv
```

**Comment by dsgnr** [comment] 2018-08-04 20:52
I'd also like to point out that the date is clearly wrong here also:

	---
	- hosts: localhost

	  tasks:
	  - debug:
	      msg: "{{ ansible_date_time }}"

Output:

	TASK [debug] **********************************************************************************************************************************************************
	ok: [localhost] => {
	    "msg": {
	        "date": "2018-08-01",
	        "day": "01",
	        "epoch": "1533127889",
	        "hour": "12",
	        "iso8601": "2018-08-01T12:51:29Z",
	        "iso8601_basic": "20180801T125129971928",
	        "iso8601_basic_short": "20180801T125129",
	        "iso8601_micro": "2018-08-01T12:51:29.972070Z",
	        "minute": "51",
	        "month": "08",
	        "second": "29",
	        "time": "12:51:29",
	        "tz": "UTC",
	        "tz_offset": "+0000",
	        "weekday": "Wednesday",
	        "weekday_number": "3",
	        "weeknumber": "31",
	        "year": "2018"
	    }
	}

System epoch:

    # date +%s
    1533416315
    # date -d @1533416315
    Sat Aug  4 21:58:35 BST 2018

**Comment by andreaso** [comment] 2018-08-05 05:49
This appear to be a case of Ansible's fact caching behaving in a non-obvious/non-desirable way.

`ansible_date_time` comes from the setup module, and appear to be treated just like any other fact.

No idea if there is a non-trivial way to get Ansible to ignore the cache for certain facts.

**Comment by dsgnr** [comment] 2018-08-05 10:47
Hmm, yeah. Completely removing the Redis configuration from the ansible.cfg file seems to have resolved that.

Running `ansible -m setup localhost` seems to clear it too.

I have been unable to see from the documentation whether there is a way to lower the cache TTL for certain facts so far.

Maybe it isn't a bug with Ansible, but I presume there some way to invalidate the cache for certain facts as I'm sure smart caching with Redis would be pretty common.

**Comment by andreaso** [comment] 2018-08-05 11:08
Might be possible to improve the situation somewhat by having your playbook explicitly call the setup module, together with its `gather_subset` parameter. That way you would only need to gather a subset of the facts on every run, and keep the cache advantage on the rest.

**Comment by sivel** [comment] 2018-08-06 14:56
Duplicate of https://github.com/ansible/ansible/issues/22561

**Closed as completed by sivel** 2018-08-06 14:56 UTC
Labels: support:core, bug, affects_2.6
