### ISSUE TITLE
conditionals: inconsistent order of evaluation in loops

### ISSUE THREAD

**Issue by b6d** [ansible/ansible#11149] opened 2015-06-03 16:13 UTC
##### Issue Type:

Bug Report, maybe (depending on assessment)
##### Ansible Version:

$ ansible --version
ansible 1.9.1
  configured module search path = None
##### Ansible Configuration:

Default configuration
##### Environment:

Control Machine: Ubuntu 14.04
Target Machines: Ubuntu 14.04
##### Summary:

How a collection variable is specified in a loop  (direct vs. templated) seems to have an influence on the order of evaluation - in the direct case, an associated conditional is evaluated _before_ the collection (making it possible to test the collection's existence) in the templated case it's the other way around.
##### Steps To Reproduce:

Run the following Playbook:

```

---
- hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    # this works (task is skipped)
    - debug:
        msg: 'do stuff with {{ item }}'
      with_items: nonexistent_list
      when: nonexistent_list is defined

    # this fails (instead of being skipped)
    - debug:
        msg: 'do stuff with {{ item }}'
      with_items: "{{ nonexistent_list }}"
      when: nonexistent_list is defined
```
##### Expected Results:

(For the second task in the Playbook)

```
skipping: [127.0.0.1] => (item=nonexistent_list)
```
##### Actual Results:

```
fatal: [127.0.0.1] => with_items expects a list or a set
```

**Comment by bcoca** [comment] 2015-06-03 16:16
not really, when ALWAYS gets evaluated after with_items, the issue is that in the 1st case it is ambiguous if the item is a string or a variable, in the 2nd case there is no ambiguity.

Closing this as we already have a ticket open about the ambiguity and this is a side effect.

**Closed as completed by bcoca** 2015-06-03 16:16 UTC
Labels: bug
