### ISSUE TITLE
raw isn't raw enough for fish

### ISSUE THREAD

**Issue by bonds** [ansible/ansible#11314] opened 2015-06-18 15:18 UTC
When using the [Fish shell](http://fishshell.com/) on the target machine, usage of the raw module errors out, complaining about the use of $SHELL to represent a command.

playbook snippet:

```
- name: python v2.7 is installed?
  raw: which python2.7
  ignore_errors: true
  changed_when: false
  register: which_python
```

output:

```
~/s/ansible (master|✚4…) [3] ❯❯❯ ansible-playbook util.yml
SUDO password: 

PLAY [util.ggr.com] *********************************************************** 

TASK: [bootstrap_openbsd | python v2.7 is installed?] ************************* 
failed: [util.ggr.com] => {"changed": false, "rc": 127, "stdout_lines": ["Variables may not be used as commands. In fish, please define a function or use 'eval SHELL'.", "fish: $SHELL -c 'sudo -k && sudo -H -S -p \"[sudo via ansible, key=iuasxrrlbnfaqceiisuufdciszdwqyqe] password: \" -u root $SHELL -c '\"'\"'echo BECOME-SUCCESS-iuasxrrlbnfaqceiisuufdciszdwqyqe; which python2.7'\"'\"''", "      ^"]}
stdout: Variables may not be used as commands. In fish, please define a function or use 'eval SHELL'.
fish: $SHELL -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=iuasxrrlbnfaqceiisuufdciszdwqyqe] password: " -u root $SHELL -c '"'"'echo BECOME-SUCCESS-iuasxrrlbnfaqceiisuufdciszdwqyqe; which python2.7'"'"''
      ^

...ignoring
```

yet, when using ansible with the raw module instead of ansible-playbook, it works fine:

```
~/s/ansible (master|✚4…) ❯❯❯ ansible util.ggr.com -m raw -a "which python2.7"
SUDO password: 
util.ggr.com | success | rc=0 >>
/usr/local/bin/python2.7


~/s/ansible (master|✚4…) ❯❯❯                        Thu Jun 18 08:16:32 PDT 2015
```

**Comment by bcoca** [comment] 2015-06-18 15:25
have you tried setting the shell type for those hosts(ansible_shell_type) to "fish"?

**Comment by bonds** [comment] 2015-06-18 15:33
@bcoca I just added `ansible_shell_type: fish` to the host_vars/util.ggr.com file and tried it again. Same result as before, Fish complains about the use of $SHELL to represent a command.

**Comment by bcoca** [comment] 2015-06-18 15:34
in ansible.cfg, set executable= "to fish"

**Comment by bonds** [comment] 2015-06-18 15:45
Just tried setting ansible.cfg executable=/bin/sh and then tried /usr/local/bin/fish, same error as before. It seems Ansible is running the executable on top of the default shell.

**Comment by bcoca** [comment] 2015-06-18 15:46
which version of ansible? os? python?

**Comment by bcoca** [comment] 2015-06-18 15:48
$SHELL should only appear if executable is not set, so once you do so the error should at least change

**Comment by bonds** [comment] 2015-06-18 15:52
Running Ansible from:
- OSX 10.10.3
- Python 2.7.9
- Ansible 1.9.1

Target machine is:
- OpenBSD 5.7-stable
- Python 2.7.9

**Comment by bonds** [comment] 2015-06-18 15:58
$SHELL still shows up, even when the executable is set in ~/.ansible.cfg. I've confirmed the cfg is being used by purposefully messing up the hostfile line and seeing it give an appropriate error.

**Comment by bcoca** [comment] 2015-06-18 16:35
I just realized raw can specify it's own executable inline, add executable= to the task

**Comment by bonds** [comment] 2015-06-18 16:48
That worked! Now its:

```
- name: python v2.7 is installed?
  raw: executable=/bin/ksh which python2.7
  ignore_errors: true
  changed_when: false
  register: which_python
```

**Comment by bcoca** [comment] 2015-06-18 16:50
closing this then as not a bug, i had not realized raw had it's own logic.

**Closed as completed by bcoca** 2015-06-18 16:50 UTC
