### ISSUE TITLE
Template update fails due to checksum error

### ISSUE THREAD

**Issue by lparsons** [ansible/ansible#14165] opened 2016-01-27 20:26 UTC
**Issue Type**: Bug Report

**Ansible Version**: 2.0.0.2

**Ansible Configuration**: `sudo_flags = -i
`
**Environment**:
Running ansible from OSX 10.11.2
Managing Centos 6.6

**Summary**:

When attempting to update a template, the tasks fails with `failed to checksum remote file. Checksum error code: 0`

**Steps To Reproduce**:

Attempt to update a template, using sudo

**Expected Results**:

```
changed: [dns.machine.com]
```

**Actual Results**:

```
fatal: [dns.machine.com]: FAILED! => {"changed": false, "failed": true, "msg": "failed to checksum remote file. Checksum error code: 0"}
```

**Comment by marcosg3** [comment] 2016-02-05 23:16
Ansible Version(s): 2.0.0 , 2.0.0.1, 2.0.0.2
Controller: Centos 6.7
Python:  2.6.6 using virtualenv to install different Ansible version

I am having the exact same issue, but not trying to update with Sudo.

I deploy my template with a playbook run with Sudo. Then I update the template with a playbook run as a standard user. 

The same process works if I switch to the Copy module but that defeats the purpose of using templates. I don't want to maintain several configs that are slightly different.

The template process works if I change nothing except switching to 1.9.4.

I saw similar bugs filed for version 1.8.x , did this issue get introduced again somehow?

**Comment by bcoca** [comment] 2016-02-06 06:12
we had checksum issues caused by changes to how shell commands got constructed, those should be fixed in current devel, can you test against that?

**Comment by marcosg3** [comment] 2016-02-09 00:29
Hi Brian,

I tested today and that fixes it! Thanks for the quick response as I was just about to branch my Ansible repo and develop my plays for 1.9.4!

Sincerely,
Marcos

**Comment by bcoca** [comment] 2016-02-09 00:47
closing as per above

**Closed as completed by bcoca** 2016-02-09 00:47 UTC
Labels: bug
