### ISSUE TITLE
A highly modular playbook results in an unnecessarily convoluted directory structure

### ISSUE THREAD

**Issue by KarlAmort** [ansible/ansible#15564] opened 2016-04-24 05:50 UTC
##### ISSUE TYPE

- Feature Idea
##### ANSIBLE VERSION

```
ansible 2.1.0
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

The directory structure would me much more compact if a file `roles/<X>/tasks.yml` were included as `roles/<X>/tasks/main.yml` is right now. 

When a project is organized in many, small(-ish) roles with only a few tasks/vars/etc each, the directory layout quickly becomes a nightmare to navigate. See the attached screenshot. 

While the standard layout tries to encourage a modular, include-based structure, many roles require just 2 or 3 tasks, which are easier to work with in a single file.

Many editors and IDEs also support a `go to file` shortcut with fuzzy matching. These become somewhat useless when all files are named `main.yml`. The same is true for labels on tabs etc.

![screen shot 2016-04-24 at 07 22 36](https://cloud.githubusercontent.com/assets/10232033/14765759/8c76ab74-09f0-11e6-9a5c-412ae880cd9e.png)
##### STEPS TO REPRODUCE

Create a file `tasks.yml`, `meta.yml`... in a role directory.
##### EXPECTED RESULTS

The tasks should be run, etc.
##### ACTUAL RESULTS

The tasks etc. are not run/included.

**Comment by syndbg** [comment] 2016-04-24 16:24
I think it's for the better if there's only one obvious way of doing things.

The current role directory structure may be hard (is it really?) for navigation, but it's modular enough and in the long term won't come biting you for choosing a single file instead of many modular ones.

**Comment by bcoca** [comment] 2016-04-25 16:22
closing as dupe of #4359

**Closed as completed by bcoca** 2016-04-25 16:22 UTC
Labels: feature
