### ISSUE TITLE
VARS: Doesn't expand nested variables

### ISSUE THREAD

**Issue by v1v** [ansible/ansible#9501] opened 2014-11-06 11:49 UTC
**Issue Type:**  “Bug Report”

**Ansible Version**: ansible 1.7.2

**Environment:** Fedora/Centos

**Summary:**

In order to configure two servers (backend & frontend) I need to expose the backend variables in order to configure the frontend playbook.  After that ansible-playbook is run and no variables defined in group_vars, it doesn't expand the nested variables.

**Steps To Reproduce:**

_Create group_vars/all_

``` yaml
backend_version: 2.0.0
```

_Create group_vars/backend_

``` yaml
backend_version: 2.3.0
backend_foldername: application
backend_name: "{{ backend_foldername }}-{{ backend_version }}"
```

_Create hosts_

``` yaml
[frontend]
test-server1 backend_server=test-server2 
[backend]
test-server2 
```

_Create site.yml_

``` yaml

---
- name: Configure and deploy Frontend
  hosts: frontend
  roles:
    - frontend

- name: Configure and deploy Backend
  hosts: backend
  roles:
    - backend
```

_Create role/frontend/tasks/main.yml_

``` yaml

---
- name: Does expand properties
  debug: msg={{ hostvars[item]['backend_version'] }}
  with_items: backend_server

- name: Does not expand nested properties
  debug: msg={{ hostvars[item]['backend_name'] }}
  with_items: backend_server
```

**Results:**

```
PLAY [Configure and deploy Frontend] **************** 

GATHERING FACTS *************************************************************** 
ok: [test-server1]

TASK: [frontend | Does expand properties] ***************************************************** 
ok: [test-server1] => (item=test-server2) => {
    "item": "test-server2", 
    "msg": " 2.3.0"
}

TASK: [frontend | Does not expand nested properties] ***************************************************** 
ok: [test-server1] => (item=test-server2) => {
    "item": "test-server2", 
    "msg": "{{adaptersuite_foldername}}-{{adaptersuite_version}}"
}
```

**Expected Results:**

```
PLAY [Configure and deploy Frontend] **************** 

GATHERING FACTS *************************************************************** 
ok: [test-server1]

TASK: [frontend | Does expand properties] ***************************************************** 
ok: [test-server1] => (item=test-server2) => {
    "item": "test-server2", 
    "msg": " 2.3.0"
}

TASK: [frontend | Does not expand nested properties] ***************************************************** 
ok: [test-server1] => (item=test-server2) => {
    "item": "test-server2", 
    "msg": " 2.3.0-application"
}
```

It doesn't expand those nested properties, likely because they aren't part of the visibility of the test-server1. But I guess just using {{ hostvars[item]['backend_name'] }} it will expand those properties...

Any ideas?

**Comment by v1v** [comment] 2014-11-06 12:10
I've just tried to use facts but still same issue:

_Create role/frontend/tasks/main.yml_

``` yaml
---
- set_fact: backend_version={{ hostvars[item]['backend_version'] }} backend_foldername={{ hostvars[item]['backend_foldername'] }}
  with_items: backend_server

- name: Does expand properties
  debug: msg={{ hostvars[item]['backend_version'] }}
  with_items: backend_server

- name: Does not expand nested properties
  debug: msg={{ hostvars[item]['backend_name'] }}
  with_items: backend_server

- name: Does expand properties set_fact
  debug: msg={{ backend_version }}-{{ backend_foldername }}
```

**Results:**

```
PLAY [Configure and deploy Frontend] **************** 

GATHERING FACTS *************************************************************** 
ok: [test-server1]

TASK: [frontend | set_fact backend_version={{ hostvars[item]['backend_version'] }} backend_foldername={{ hostvars[item]['backend_foldername'] }}] *** 
ok: [test-cent6-003] => (item=test-cent6-004)

TASK: [frontend | Does expand properties] ***************************************************** 
ok: [test-server1] => (item=test-server2) => {
    "item": "test-server2", 
    "msg": " 2.3.0"
}

TASK: [frontend | Does not expand nested properties] ***************************************************** 
ok: [test-server1] => (item=test-server2) => {
    "item": "test-server2", 
    "msg": "{{adaptersuite_foldername}}-{{adaptersuite_version}}"
}

TASK: [frontend | Does expand properties set_fact] ***************************************************** 
ok: [test-server1] {
    "msg": "2.3.0-application"
}
```

**Expected Results:**

```
PLAY [Configure and deploy Frontend] **************** 

GATHERING FACTS *************************************************************** 
ok: [test-server1]

TASK: [frontend | set_fact backend_version={{ hostvars[item]['backend_version'] }} backend_foldername={{ hostvars[item]['backend_foldername'] }}] *** 
ok: [test-cent6-003] => (item=test-cent6-004)

TASK: [frontend | Does expand properties] ***************************************************** 
ok: [test-server1] => (item=test-server2) => {
    "item": "test-server2", 
    "msg": " 2.3.0"
}

TASK: [frontend | Does not expand nested properties] ***************************************************** 
ok: [test-server1] => (item=test-server2) => {
    "item": "test-server2", 
    "msg": " 2.3.0-application"
}

TASK: [frontend | Does expand properties set_fact] ***************************************************** 
ok: [test-server1] {
    "msg": "2.3.0-application"
}
```

**Comment by v1v** [comment] 2014-11-06 12:39
# Workaround

Overwritten those variables using the set_fact tasks

_Create role/frontend/tasks/main.yml_

``` yaml
---
- set_fact: 
    backend_version={{ hostvars[item]['backend_version'] }} 
    backend_foldername={{ hostvars[item]['backend_foldername'] }}
  with_items: backend_server

- name: Does expand properties
  debug: msg={{ backend_version }}

- name: Does NOW expand nested properties
  debug: msg={{ backend_name }}
```

**Results:**

```
PLAY [Configure and deploy Frontend] **************** 

GATHERING FACTS *************************************************************** 
ok: [test-server1]

TASK: [frontend | set_fact backend_version={{ hostvars[item]['backend_version'] }} backend_foldername={{ hostvars[item]['backend_foldername'] }}] *** 
ok: [test-cent6-003] => (item=test-cent6-004)

TASK: [frontend | Does expand properties] ***************************************************** 
ok: [test-server1] => (item=test-server2) => {
    "item": "test-server2", 
    "msg": " 2.3.0"
}

TASK: [frontend | Does NOW expand nested properties] ***************************************************** 
ok: [test-server1] => (item=test-server2) => {
    "item": "test-server2", 
    "msg": " 2.3.0-application"
}
```

any ideas if I might improve it?

Thanks

**Comment by hughsaunders** [comment] 2014-11-24 14:39
Seems like a duplicate of https://github.com/ansible/ansible/issues/7844

**Closed as completed** 2015-06-28 01:05 UTC
Labels: bug
