### ISSUE TITLE
'groups' is undefined

### ISSUE THREAD

**Issue by rncry** [ansible/ansible#11343] opened 2015-06-22 13:14 UTC
I'm getting a strange error when trying to apply a role: apparently 'groups' (the builtin variable) is undefined. I've tested on a play in the same playbook and the variable works. Any ideas?

```
- name: wtf?
  gather_facts: True
  hosts: tag_Name_Consul_server
  sudo: True
  user: username
  tasks:
    - name: thing
      debug: msg="-join {{ groups['tag_consul_server'][0] }}"

- name: blah
  gather_facts: True
  hosts: tag_Name_Consul_server
  sudo: True
  user: username
  vars:
    consul_command: "-join {{ groups['tag_consul_server'][0] }}"
  roles:
    - consul_server
```

I've tried this with different roles, but it still fails. I'm using the latest pull from the git repo.

**Comment by bennojoy** [comment] 2015-06-22 13:35
@rncry this was fixed couple of days back , can you pull the latest code and check again please

**Comment by rncry** [comment] 2015-06-22 14:10
I'm on branch devel.. still seems broken, anything else I need to do to fix it?

**Comment by bennojoy** [comment] 2015-06-22 14:24
@rncry  hmm i can not able to reproduce this can you please do a 'ansible --version'

**Comment by bennojoy** [comment] 2015-06-22 14:26
also can you add the exact error you are getting.

**Comment by rncry** [comment] 2015-06-22 14:44
PLAY: wtf? **********************************************************************

TASK [setup] ********************************************************************
ok: [172.20.121.85]
ok: [172.20.121.87]

TASK [thing] ********************************************************************
ok: [172.20.121.87] => {
    "msg": "-join 172.20.121.29", 
    "changed": false
}
ok: [172.20.121.85] => {
    "msg": "-join 172.20.121.29", 
    "changed": false
}
ERROR! the field 'vars' has an invalid value, which appears to include a variable that is undefined. The error was: 'groups' is undefined

**Comment by rncry** [comment] 2015-06-22 14:44
ansible 2.0.0 (devel ff251a0dcc) last updated 2015/06/22 14:39:43 (GMT +000)
  lib/ansible/modules/core: (detached HEAD cf273bbaeb) last updated 2015/06/22 14:39:50 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD dd6e8f354a) last updated 2015/06/22 14:39:59 (GMT +000)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/06/22 14:40:03 (GMT +000)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/06/22 14:40:07 (GMT +000)
  configured module search path = None

**Comment by rncry** [comment] 2015-06-22 14:47
Simplest way to reproduce:

```
- name: wtf?
  gather_facts: True
  hosts: tag_Name_Consul_server
  sudo: True
  user: username
  vars:
    pumpkin: "{{ groups['tag_consul_server'] }}"
  tasks:
    - name: thing
      debug: msg={{ pumpkin }}
```

**Comment by rncry** [comment] 2015-06-22 14:48
Seems to be whenever the groups variable is used in vars

**Comment by bcoca** [comment] 2015-06-22 14:55
you probably don't have groups yet when you are at the vars level, in previous versions this error was ignored.

**Comment by rncry** [comment] 2015-06-22 14:56
It worked previously though? (with the correct vars being populated)

**Comment by jimi-c** [comment] 2015-06-22 15:00
This may be a bug, as the vars fields are being templated early on, however if this worked previously we may need to fix that so that vars are not.

**Comment by bcoca** [comment] 2015-06-22 15:01
it didn't and it did, still looking into it. previously we ignored a lot of errors so the nth time the var evaluated it might have groups available and then work. The play as you have defined SHOULD work, so this is a bug we need to fix.

**Comment by rncry** [comment] 2015-06-22 15:05
@bcoca thanks! Is this a quick thing to fix? Where is this happening in the code base?

**Comment by jimi-c** [comment] 2015-06-22 15:23
@rncry I'll have a patch committed in a few minutes.

**Closed as completed** 2015-06-22 15:25 UTC
Labels: P2, bug

**Comment by jimi-c** [comment] 2015-06-22 15:47
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by rncry** [comment] 2015-06-22 16:29
Hi @jimi-c thanks very much for the patch.. I'm just trying it out again now. It now fails as part of a larger playbook, it seems dependencies for the role, it it's applied twice (to different sets of hosts) are not being applied. Not sure if I should report this as a separate issue?

```
---

- name: Consul bootstrap server
  hosts: localhost
  gather_facts: False
  vars:
    launch_group: consul_bootstrap
    count: 1
    image: ami-e4ff5c93
    tags:
      Name: Ansible consul bootstrap
      consul: bootstrap
  roles:
    - ec2_start

- name: Consul servers
  hosts: localhost
  gather_facts: False
  vars:
    launch_group: consul_server
    count: 2
    image: ami-e4ff5c93
    tags:
      Name: Ansible consul server
      consul: server
  roles:
    - ec2_start

- name: setup fs and users
  gather_facts: True
  hosts: launched_ec2
  sudo: True
  user: centos
  roles:
    - cloud_base

- name: Bootstrap consul server
  gather_facts: True
  hosts: consul_bootstrap
  sudo: True
  user: username
  roles:
    - consul_server

- name: Add other consul servers
  gather_facts: True
  hosts: consul_server
  sudo: True
  user: username
  vars:
    consul_command: -join {{ hostvars[groups['consul_bootstrap'][0]]['ansible_eth0']['ipv4']['address'] }}
  roles:
    - consul_server
```

**Comment by rncry** [comment] 2015-06-22 16:35
(basically the Bootstrap consul server play works, but Add other consul servers fails, because the dependencies for the consul_server role are not being applied.. it goes straight into the role)

**Comment by jimi-c** [comment] 2015-06-22 16:55
@rncry yes, please open a new issue for that. Thanks!
