### ISSUE TITLE
Add support for state=status on service/systemd modules

### ISSUE THREAD

**Issue by dekimsey** [ansible/ansible#32087] opened 2017-10-24 16:53 UTC
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
systemd
service

##### ANSIBLE VERSION
2.4.0 as well.
```
ansible 2.3.2.0
  config file =
  configured module search path = Default w/o overrides
  python version = 3.6.2 (default, Jul 17 2017, 16:44:45) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
n/a

##### STEPS TO REPRODUCE
There are many times where I need to get information about a service without making changes to the system. The systemd and related service modules do not provide an interface to do this.

For instance, the systemd module reports lots of useful, parsed info about a service. But doesn't let me perform a NOOP query to get the information. Instead I have to affect the system in some regard (enabling, starting, reloading, etc).

##### EXPECTED RESULTS

```yaml
- systemd:
     name: foo
     state: status
  register: foo_service
```

There is a dead PR (for service only) from [ansible/ansible-core-modules#3316](https://github.com/ansible/ansible-modules-core/pull/3316) related to this.

**Comment by bcoca** [comment] 2017-10-24 17:18
dupe of #20177

**Closed as completed by bcoca** 2017-10-24 17:18 UTC
Labels: affects_2.3, module, support:core, feature
