### ISSUE TITLE
Role dependencies missing version documentation for remote role support

### ISSUE THREAD

**Issue by aotd1** [ansible/ansible#9280] opened 2014-10-07 09:56 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

1.7.1, 1.7.2, 1.8 ( e8aa847 2014-10-06 )
##### Environment:

OS X 10.10
##### Summary:

Remote roles, described as  { role: "git+http://gitlab.local/ansible/git.git,master" } not working. Ansible-playbook parse it as local path.
##### Steps To Reproduce:

Create role with dependences `meta/main.yml`:

``` yaml

---
dependencies:
  - { role: "git+http://gitlab.local/ansible/git.git,master,git" }
  - { role: apt,    tags: environment }
  - { role: nginx,  tags: nginx }

```

Run ansible-playbook, see error:

```
ERROR: cannot find role in /Users/aotd/www/favorites.ansible/roles/git+http:/gitlab.local/ansible/git.git,master or /Users/aotd/www/favorites.ansible/git+http:/gitlab.local/ansible/git.git,master or /etc/ansible/roles/git+http:/gitlab.local/ansible/git.git,master
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```
##### Expected Results:

Downloaded and used role from http://gitlab.local/ansible/git.git
As described in [documentation](http://docs.ansible.com/playbooks_roles.html#role-dependencies).
##### Actual Results:

```
ERROR: cannot find role in /Users/aotd/www/favorites.ansible/roles/git+http:/gitlab.local/ansible/git.git,master or /Users/aotd/www/favorites.ansible/git+http:/gitlab.local/ansible/git.git,master or /etc/ansible/roles/git+http:/gitlab.local/ansible/git.git,master
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by jimi-c** [comment] 2014-10-07 16:39
Hi @aotd1, this feature is new in Ansible 1.8, so you will need to be using the devel branch right now for this feature. That documentation is missing a note regarding that, so we will get that updated.

Thanks!

**Comment by aotd1** [comment] 2014-10-08 04:36
I already tried devel version (1.8 from 2014-10-06, commit e8aa847).
I see code for "git+" syntax in role_spec_parse (`~/ansible/lib/ansible/utils/__init__.py`), but can't understand why it doesn't work (i'm not Python developer).
Looks like this issue #9173 has the same root.

``` bash
aotd$ ansible --version
ansible 1.8
  configured module search path = None
```

**Comment by aotd1** [comment] 2014-10-08 04:41
Same behavior on devel bbd9921 2014-10-07

**Comment by jimi-c** [comment] 2014-10-08 18:03
I'd say similar but unrelated, the ansible-galaxy code does not share any code with the core stuff that would be causing your problem above.

**Comment by abadger** [comment] 2014-10-09 15:22
@aotd1 or @willthames what is the "git+http://" protocol?  How do I setup a server to serve it?  Is it the same as the "git://" protocol?  I wasn't able to find any documentation about it via google which makes me wonder if its a notation that only is present in ansible (and we should drop it in favor of whatever the canonical scheme is).

**Comment by aotd1** [comment] 2014-10-09 16:51
@abadger I agree, it's something strange. 
Moreover scm property never used in ansible-playbook, I see that it is used only in ansible-galaxy.

**Comment by willthames** [comment] 2014-10-09 23:45
@abadger `git+http` is not a protocol. The protocol is `http`, which differs from the `git` protocol (see http://git-scm.com/book/en/Git-on-the-Server-The-Protocols#The-Git-Protocol)

The `git+` prefix signifies that the repo is a git repo - as it is impossible in general to tell a git repo from an hg repo or a svn repo just from the URL.

This was well discussed on the list (that's not to say that documentation can't be improved)
https://groups.google.com/d/topic/ansible-project/TawjChwaV08/discussion

There is common code that handles the role path parsing in dependencies.

In general I would not expect ansible-playbook to install roles from URLs specified in dependencies. You should use ansible-galaxy to install those roles, and you'll typically need to specify them in a roles file. However, ansible-galaxy will install dependencies of the roles that it does install. (So if ansible-galaxy came across the above `meta/main.yml`, it would install the dependency).

**Comment by abadger** [comment] 2014-10-10 15:46
@willthames Thanks for the information l link to the list!  Very helpful!

I saw that you had noted an issue that I also noticed when I was looking at the code yesterday: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/ansible-project/TawjChwaV08/rGpDFc7JN40J

Did you and @mpdehaan come up with a way to alleviate those conflicts?

**Comment by willthames** [comment] 2014-10-11 01:41
I'm not sure there is a nice way of using yaml format for dependencies as it stands, you have to use the "scm+url,version,nice_role_name" format. In my understanding, how the yaml alternative would work is no further along than in that email thread.

I'm not convinced that passing role variables in dependencies is that useful (as you can just set the role variables in vars I would think). If that's the case then you could just use the same yaml format as in the ansible-galaxy roles file. But this would need to be further discussed on list.

**Comment by mattupstate** [comment] 2015-02-28 18:50
Has there been any movement on this? As it stands the docs are very misleading.

However, as someone in the forum mentioned, if you don't use a dictionary as a dependency, and simply a string, all works well. So in other words, the following doesn't work...

``` yaml
dependences:
  - role: git+git@....,master,friendlyname
```

but this does...

``` yaml
dependences:
  - git+git@....,master,friendlyname
```

**Comment by mattupstate** [comment] 2015-03-02 16:53
Upon further investigation, this seems to work:

```yaml
depedencies:
  - role: friendlyname
    scm: git
    src: git@server.com/repo.git
    name: friendlyname
```

**Comment by mattupstate** [comment] 2015-03-02 19:13
FWIW, I have a PR over [here](https://github.com/ansible/ansible/pull/10371) that works with all my roles that declare their dependencies either with a role name or remote info, as such:

``` yaml
dependencies:
  # A role available on galaxy.ansible.com
  - role: Stouts.python
  # A custom remote role
  - name: chatid.consul
    src: git+git@github.com:chatid/ansible-consul.git
    version: master
```

**Comment by jaytaylor** [comment] 2015-04-26 00:47
This is an issue I'd definitely like to see addressed and resolved.  The docs advertise:

``` yml
---
dependencies:
  - { role: 'git+https:/github.com/mhamrah/ansible-docker' }
```

yet in reality this functionality is not actually available at present.

``` bash
ERROR: cannot find role in /Users/jay/repos/my-playbook/roles/git+https:/github.com/mhamrah/ansible-docker or /Users/jay/repos/my-playbook/git+https:/github.com/mhamrah/ansible-docker or /Users/jay/repos/my-playbook/librarian_roles/git+https:/github.com/mhamrah/ansible-docker
```

This is using ansible version 1.9.0.1.

**Comment by bitmensch** [comment] 2015-04-28 19:28
It would be really great to see this fixed in the near future. Specifying dependencies as string-only does not work in all situations.

**Comment by jaytaylor** [comment] 2015-04-28 19:47
@benjixx I submitted a PR for this, I am using it now and it fixes most cases with just an extra 2 simple lines: https://github.com/ansible/ansible/pull/10846

Since it's only 2 lines, you can just edit the file yourself to include them and be on your way ;)

Also, if you test it and it works for you it's always good to comment on the PR so that the team knows it's good to merge.

**Comment by bitmensch** [comment] 2015-04-28 21:10
@jaytaylor Although it may work for your use case, I don't think this PR covers all the cases, e.g. different role name. I was finally able to solve my problems by using [ansible-role-manager](https://github.com/mirskytech/ansible-role-manager) instead of ansible-galaxy.

**Comment by jaytaylor** [comment] 2015-04-28 21:23
I see, thanks for sharing your solution!

On Tue, Apr 28, 2015 at 2:10 PM, Benjamin Schwarze <notifications@github.com

**Comment by willthames** [comment] 2015-04-29 10:38
I can't reproduce this bug. You can follow along using

```
git+ssh://git@bitbucket.org/willthames/git-ansible-galaxy,v1.5
hg+ssh://hg@bitbucket.org/willthames/hg-ansible-galaxy
```

I just updated git-ansible-galaxy v1.5 to use `- { role: "git+https://.../" }` and it works fine.

I notice you have an error in your URL - you're missing a slash in your http:// (and I have a feeling that the test for whether a role is local or remote looks for the string `://`)

EDIT: oops, the bug is when you run ansible-playbook, rather than when you run ansible-galaxy. Apologies.

**Comment by willthames** [comment] 2015-04-29 10:56
Added a proper fix for this bug. 

Run the full galaxy test suite against this (make galaxy_test from test/integration) and it works. But the test suite does not test this particular bug, so there is room for improvement.

**Comment by jaytaylor** [comment] 2015-04-29 15:36
That typo is on this issue only, surprised you can't reproduce.  If you have fixed it somewhere upstream already then that's great!  I'll try out your "proper" fix.

**Comment by bcoca** [comment] 2015-05-04 16:21
removed this from the docs via: #10860, we are actually moving away from specifying this in the role name and will use a src: field to pass URI to the role (the galaxy format) I'm still implementing this on the v2 tree but closing this as docs will be updated on next push and the confusing example will have been removed.

**Closed as completed by bcoca** 2015-05-04 16:21 UTC
Labels: P2, docs
