### ISSUE TITLE
Ansible 1.9.0.1 cannot start upstart service

### ISSUE THREAD

**Issue by aabdnn** [ansible/ansible#10553] opened 2015-03-26 23:42 UTC
Issue Type:

Bug Report

Ansible Version:

1.9.0.1

Environment:

Managing CentOS 6 from MacOS X 10.10.2

Summary:

The service module is failing to start an upstart service on CentOS 6

Steps To Reproduce:

ansible hostname -m service -a 'name=servicename state=started'

Expected Results:

I expected ansible to start the service. This works on 1.8.4, but fails on 1.9.0.1.

Actual Results:

Ansible fails with the following error:

```
$ ansible ns1.ams.as112.ripe.net -u root -m service -a 'name=ansible state=started'
ns1.ams.as112.ripe.net | FAILED >> {
    "failed": true, 
    "msg": "ansible: unrecognized service\n"
}
```

**Comment by bcoca** [comment] 2015-03-27 12:57
closing as duplicate of https://github.com/ansible/ansible-modules-core/pull/999, which is in the correct repo

**Closed as completed by bcoca** 2015-03-27 12:57 UTC
Labels: P2, bug
