### ISSUE TITLE
Tags are ignored at role level

### ISSUE THREAD

**Issue by theraser** [ansible/ansible#13795] opened 2016-01-11 11:43 UTC
Issue Type: Bug Report
Ansible Version: `ansible-playbook 2.1.0 (devel c3dd0213ef) last updated 2016/01/11 12:26:53 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 33014c6db1) last updated 2016/01/08 15:07:37 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 82a4cf84be) last updated 2016/01/08 15:07:37 (GMT +200)`
Environment: Ubuntu 15.04
Problem: Using tags defined for specific roles inside a playbook are ignored when running ansible-playbook with that tag, please see example for more details. Using version 1.94 this works perfectly. When tags are specified for some tasks inside this role they are usable just as expected with "--tags tag1".
Example:

```
[...]
- hosts: web_server
  roles:
  - role: role1
  - role: role2
  - role: ....
  tags: tag1
[...]
```

Running `ansible-playbook -i ~/.ansible/hosts ~/.ansible/site.yml -l somehost --tags tag1` results in skipping everything:

```
PLAY ***************************************************************************

PLAY ***************************************************************************

PLAY ***************************************************************************
skipping: no hosts matched

PLAY ***************************************************************************

PLAY ***************************************************************************
skipping: no hosts matched

PLAY ***************************************************************************
skipping: no hosts matched

PLAY ***************************************************************************
skipping: no hosts matched

PLAY ***************************************************************************
skipping: no hosts matched

PLAY ***************************************************************************
skipping: no hosts matched
[...]
```

**Comment by bcoca** [comment] 2016-01-11 16:39
when roles are skipped it does not produce a 'no hosts matched' message, that is probably related to your `-l  somehost`

**Comment by jimi-c** [comment] 2016-01-11 16:40
@theraser this doesn't appear to be related to tags at all, based on the output above (and my testing shows this works fine with tags). Rather, this appears to be a result of your `-l somehost` limit, so that you're filtering out all hosts.

Could you please share the inventory your using in this example, or some other inventory which reproduces the behavior?

**Comment by theraser** [comment] 2016-01-12 07:45
Thanks four your fast reply :-)

This indeed looks strange. When using Ansible 1.94 with exact same invocation role1, role2 [...] are executed just as expected. When Ansible development version is used I get this "skipping: no hosts matched" as you can see at top.

However I think I found the issue at my tags (syntax):
Writing something like this will work only with older Ansible versions: `tags: tag1,tag2,tag3`. This won't be recognized with newer versions, where you have to use the correct syntax like

```
tags:
  - tag1
  - tag2
  - tag3
```

That's why it skipped every role...

Sometimes it's that easy, sorry for wasting your time

**Comment by jimi-c** [comment] 2016-01-12 12:55
Hrm, that's odd, that should be split up correctly.

**Comment by theraser** [comment] 2016-01-12 13:04
I am not sure if the fact that it worked with the old version was a bug or a feature. I just rewrote my playbooks and this works now. If you need any further information please let me know, then I would try to post a complete setup

**Comment by jimi-c** [comment] 2016-01-12 13:19
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed** 2016-01-12 13:19 UTC
Labels: bug
