### ISSUE TITLE
sysctl no longer works on ansible 1.5 (centos 6.4)

### ISSUE THREAD

**Issue by dhorbach** [ansible/ansible#6272] opened 2014-03-04 15:24 UTC
##### Issue Type:

“Bug Report”
##### Ansible Version:

$ ansible --version
ansible 1.5
##### Environment:

Centos 6.4 x64
##### Summary:

sysctl module is broken after upgrade from 1.4.4 to 1.5
##### Steps To Reproduce:

```
- name: Update kernel params
  sysctl: name={{ item.name }} value={{ item.value }} state=present
  sudo: yes          
  with_items: oracle_kernel_params
```

```
oracle_kernel_params:
  - { name: fs.suid_dumpable, value: 1 }
  - { name: fs.aio-max-nr, value: 1048576 }
  - { name: fs.file-max, value: 6815744 }
  - { name: kernel.shmall, value: 2097152 }
  - { name: kernel.shmmax, value: 536870912 }
  - { name: kernel.shmmni, value: 4096 }
  - { name: kernel.sem, value: '"250 32000 100 128"' }
  - { name: net.ipv4.ip_local_port_range, value: '"9000 65500"' }
  - { name: net.core.rmem_default, value: 4194304 }
  - { name: net.core.rmem_max, value: 4194304 }
  - { name: net.core.wmem_default, value: 262144 }
  - { name: net.core.wmem_max, value: 1048586 }
```
##### Expected Results:

sysctl correctly updated
##### Actual Results:

```
amazon-ebs: <localhost> REMOTE_MODULE sysctl name=kernel.shmall value=2097152 state=present
amazon-ebs: failed: [localhost] => (item={'name': 'kernel.shmall', 'value': 2097152}) => {"failed": true, "item": {"name": "kernel.shmall", "value": 2097152}}
amazon-ebs: msg: Failed to reload sysctl: net.ipv4.ip_forward = 0
amazon-ebs: net.ipv4.conf.default.rp_filter = 1
amazon-ebs: net.ipv4.conf.default.accept_source_route = 0
amazon-ebs: kernel.sysrq = 0
amazon-ebs: kernel.core_uses_pid = 1
amazon-ebs: net.ipv4.tcp_syncookies = 1
amazon-ebs: kernel.msgmnb = 65536
amazon-ebs: kernel.msgmax = 65536
amazon-ebs: kernel.shmmax = 68719476736
amazon-ebs: kernel.shmall = 2097152
amazon-ebs: fs.suid_dumpable = 1
amazon-ebs: fs.aio-max-nr = 1048576
amazon-ebs: fs.file-max = 6815744
amazon-ebs: error: "net.bridge.bridge-nf-call-ip6tables" is an unknown key
amazon-ebs: error: "net.bridge.bridge-nf-call-iptables" is an unknown key
amazon-ebs: error: "net.bridge.bridge-nf-call-arptables" is an unknown key
```

**Comment by jctanner** [comment] 2014-03-04 15:46
@dhorbach I'm unable to reproduce on centos 6.5 x86_64 ...

```
- hosts: el6.lab.net
  gather_facts: False
  vars:
    oracle_kernel_params:
      - { name: fs.suid_dumpable, value: 1 }
      - { name: fs.aio-max-nr, value: 1048576 }
      - { name: fs.file-max, value: 6815744 }
      - { name: kernel.shmall, value: 2097152 }
      - { name: kernel.shmmax, value: 536870912 }
      - { name: kernel.shmmni, value: 4096 }
      - { name: kernel.sem, value: '"250 32000 100 128"' }
      - { name: net.ipv4.ip_local_port_range, value: '"9000 65500"' }
      - { name: net.core.rmem_default, value: 4194304 }
      - { name: net.core.rmem_max, value: 4194304 }
      - { name: net.core.wmem_default, value: 262144 }
      - { name: net.core.wmem_max, value: 1048586 }
  tasks:
      - sysctl: name={{ item.name }} value={{ item.value }} state=present
        with_items: oracle_kernel_params
```

Result:

```
$ ansible-playbook -i inventory site.yml

PLAY [el6.lab.net] ************************************************************

TASK: [sysctl name={{item.name}} value={{item.value}} state=present] **********
changed: [el6.lab.net] => (item={'name': 'fs.suid_dumpable', 'value': 1})
changed: [el6.lab.net] => (item={'name': 'fs.aio-max-nr', 'value': 1048576})
changed: [el6.lab.net] => (item={'name': 'fs.file-max', 'value': 6815744})
changed: [el6.lab.net] => (item={'name': 'kernel.shmall', 'value': 2097152})
changed: [el6.lab.net] => (item={'name': 'kernel.shmmax', 'value': 536870912})
changed: [el6.lab.net] => (item={'name': 'kernel.shmmni', 'value': 4096})
changed: [el6.lab.net] => (item={'name': 'kernel.sem', 'value': '"250 32000 100 128"'})
changed: [el6.lab.net] => (item={'name': 'net.ipv4.ip_local_port_range', 'value': '"9000 65500"'})
changed: [el6.lab.net] => (item={'name': 'net.core.rmem_default', 'value': 4194304})
changed: [el6.lab.net] => (item={'name': 'net.core.rmem_max', 'value': 4194304})
changed: [el6.lab.net] => (item={'name': 'net.core.wmem_default', 'value': 262144})
changed: [el6.lab.net] => (item={'name': 'net.core.wmem_max', 'value': 1048586})

PLAY RECAP ********************************************************************
el6.lab.net                : ok=1    changed=1    unreachable=0    failed=0
```

Spot check:

```
[root@el6 ~]# sysctl -A | fgrep kernel.sem
kernel.sem = 250        32000   100     128
```

Did I overlook something in your description?

**Comment by dhorbach** [comment] 2014-03-04 16:13
initially found that on AWS VM
Now checking with vagrant box (6.4 centos too)

1 VM  where those settings already applied

TASK: [Update kernel params] **************************************************
ok: [oracledb] => (item={'name': 'fs.suid_dumpable', 'value': 1})
ok: [oracledb] => (item={'name': 'fs.aio-max-nr', 'value': 1048576})
ok: [oracledb] => (item={'name': 'fs.file-max', 'value': 6815744})
ok: [oracledb] => (item={'name': 'kernel.shmall', 'value': 2097152})
ok: [oracledb] => (item={'name': 'kernel.shmmax', 'value': 536870912})
ok: [oracledb] => (item={'name': 'kernel.shmmni', 'value': 4096})
ok: [oracledb] => (item={'name': 'kernel.sem', 'value': '"250 32000 100 128"'})
ok: [oracledb] => (item={'name': 'net.ipv4.ip_local_port_range', 'value': '"9000 65500"'})
ok: [oracledb] => (item={'name': 'net.core.rmem_default', 'value': 4194304})
ok: [oracledb] => (item={'name': 'net.core.rmem_max', 'value': 4194304})
ok: [oracledb] => (item={'name': 'net.core.wmem_default', 'value': 262144})
ok: [oracledb] => (item={'name': 'net.core.wmem_max', 'value': 1048586})

2 VM where its new settings

TASK: [Update kernel params] **************************************************
failed: [server] => (item={'name': 'fs.suid_dumpable', 'value': 1}) => {
        "failed": true,
        "item": {
        "name": "fs.suid_dumpable",
        "value": 1}
}
msg: Failed to reload sysctl: net.ipv4.ip_forward = 0
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.default.accept_source_route = 0
kernel.sysrq = 0
kernel.core_uses_pid = 1
net.ipv4.tcp_syncookies = 1
kernel.msgmnb = 65536
kernel.msgmax = 65536
kernel.shmmax = 68719476736
kernel.shmall = 4294967296
fs.suid_dumpable = 1
error: "net.bridge.bridge-nf-call-ip6tables" is an unknown key
error: "net.bridge.bridge-nf-call-iptables" is an unknown key
error: "net.bridge.bridge-nf-call-arptables" is an unknown key

failed: [server] => (item={'name': 'fs.aio-max-nr', 'value': 1048576}) => {
        "failed": true,
        "item": {
        "name": "fs.aio-max-nr",
        "value": 1048576}
}
msg: Failed to reload sysctl: net.ipv4.ip_forward = 0
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.default.accept_source_route = 0
kernel.sysrq = 0
kernel.core_uses_pid = 1
net.ipv4.tcp_syncookies = 1
kernel.msgmnb = 65536
kernel.msgmax = 65536
kernel.shmmax = 68719476736
kernel.shmall = 4294967296
fs.suid_dumpable = 1
fs.aio-max-nr = 1048576
error: "net.bridge.bridge-nf-call-ip6tables" is an unknown key
error: "net.bridge.bridge-nf-call-iptables" is an unknown key
error: "net.bridge.bridge-nf-call-arptables" is an unknown key
 etc

Will try to find out more

**Comment by jctanner** [comment] 2014-03-05 16:15
@dhorbach so this only occurs if the key was never set before? I'll try to test for that scenario.

EDIT: reproduced the issue on a clean centos vm.

**Comment by jctanner** [comment] 2014-03-05 17:59
@dhorbach Unfortunately this error is inherent to how sysctl -p works, rather than how the module is writing the file.

This should be fixed by https://github.com/ansible/ansible/pull/5872 if you add "ignoreerrors=yes" to your task.

**Closed as completed by jctanner** 2014-03-05 17:59 UTC
Labels: bug
