### ISSUE TITLE
Live output from remote processes

### ISSUE THREAD

**Issue by dwt** [ansible/ansible#4870] opened 2013-11-11 09:51 UTC
Hi there,

we're currently test driving some of our old scripts remotely from ansible and if we choose to use it probably will for some time.

On the one hand ansible makes it really easy to automate workflows that span multiple servers (that we'd like to use) on the other hand though it makes it really hard to see live whats going on on the other system.

What we would like is a way to see the output of the task on the target system as live feedback (possibly if requested via an option in a playbook).

As far as I can see that is not possible with the current design of playbooks as the underlying callback object does not get callbacks for individual lines in the playbook.

As far as I understand how ansible works (ssh into the other machine run a command) this should not be difficult to implement as the output is streamed live to the local machine anyway (or could be easily).

So that's the feature request: show live output of remote tasks/commands. How about it? Would you be willing to do that in ansible? Would you accept a pull request? Is it already possible?

Best regards and thanks for the great tool!

**Comment by jctanner** [comment] 2013-11-11 14:18
Closing as a duplicate of #3887

**Closed as completed by jctanner** 2013-11-11 14:18 UTC
Labels: feature

**Comment by rferrerme** [comment] 2015-07-14 23:55
I tried to comment in the original one, but it is locked. This is what I'm doing to see live output, in case it is useful: http://rferrer.me/articles/live-ansible-stdout.html.

**Comment by bcoca** [comment] 2015-07-15 02:22
@rferrerme it might just be easier to attach gdb and clone stdout to a tmp file

```
gdb -p (pid)
(gdb) call creat("/tmp/stdout", 0600)
$1 = 3
(gdb) call dup2(3, 1)
```

no need to modify code and it should work will all/any process

**Comment by ssbarnea** [comment] 2015-09-22 07:46
can we reopen this and implement a `--live` option in ansible?

**Comment by dwt** [comment] 2015-09-22 12:33
You have my vote. :-)

**Comment by amenonsen** [comment] 2015-09-22 12:44
And my axe!

**Comment by topikito** [comment] 2016-03-05 09:26
+1

**Comment by agaurav** [comment] 2016-04-30 06:25
+1

**Comment by ktosiek** [comment] 2016-04-30 10:57
There was a major refactor and a change of project lead since this issue was rejected as "Won't Fix". Is it a good time to rethink this?
I would really use that in a few places (for specific tasks, like running Django migrations or restoring a postgresql slave), and those would be very specific, few-hosts-at-a-time, tasks.

**Comment by steveholden** [comment] 2016-05-01 17:00
+1 - Happy to hear that the "wontfix" may no longer apply

**Comment by ngrilly** [comment] 2016-05-04 19:58
I'd like this too for the same use case as @ktosiek, which is running database migrations.

**Comment by schast** [comment] 2016-10-21 07:21
+1

**Comment by zfy0701** [comment] 2016-10-28 10:35
+1

**Comment by KroArtem** [comment] 2016-11-18 09:11
+1

**Comment by nethershaw** [comment] 2017-02-23 18:02
This conversation remains salient.

We have a need to audit the output of a running realtime process in order to discern subtleties of an application's behavior under rigorously pre-defined circumstances. There exist conditions where 'async' will correctly return that the process is still executing, but a message has been emitted that indicates _later_ failure or a less fatal condition will occur, and it is unsustainable to wait for the output stream to terminate before an operator or a build system can make that determination. Log shipping or tailing the process out-of-band with Ansible complicates the setup and teardown of surrounding automation and using the results to signal subsequent actions.

This need exists only when we are managing few enough hosts (that is to say, exactly one) for display of a real-time output to be meaningful. The use case is therefore self-limiting; it would be both impractical and undesirable to read the live tail of multiple concurrent real-time tasks. The retrieval and display of such real-time streams should have similar constraints -- perhaps by enabling it with a task parameter that is only valid when the parallelism of that task is not greater than 1.

**Comment by rorybrowne** [comment] 2017-11-17 12:29
Fully agree with your first paragraph @nethershaw ; however with regard to the second paragraph, I think it's possible to meaningfully retrieve the output from multiple hosts.

Two possibilities I can think of are split screen ( with (n)curses ), and colour-coded output.

I also agree that problems deploying to a single host (or indeed a small number of hosts - < 5) should not be dismissed, just because a potential solution doesn't scale to hundreds of hosts.

**Comment by ocervell** [comment] 2017-12-13 00:15
I started doing application / system administration from ansible using tags, and this would be a killer feature to monitor app / sys logs. 
@nethershaw  I'm willing to help on this. I don't know much about ansible code, but I do know how to do this with Fabric that uses paramiko as well.

**Comment by uriklagnes** [comment] 2018-01-08 18:32
+1

**Comment by ThenukaD** [comment] 2018-02-07 13:47
I have the same issue and all other POC work is done except for this live log feature. 
+1 for implementing this as a feature in Ansible

**Comment by Mebus** [comment] 2018-03-23 10:56
+1 :blush:

**Comment by grantcurell** [comment] 2018-03-24 19:34
+1

**Comment by cyrilthank** [comment] 2018-07-25 16:56
+1

**Comment by cyrilthank** [comment] 2018-07-25 16:56
+1
