### ISSUE TITLE
vars with quotes in them can cause odd parameter parsing

### ISSUE THREAD

**Issue by wu-lee** [ansible/ansible#9320] opened 2014-10-13 10:41 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

Current latest devel.  Also 1.6 and assorted versions in between.

```
$ ansible --version
ansible 1.8 (devel 2eda9a3a47) last updated 2014/10/10 18:43:36 (GMT +100)
  lib/ansible/modules/core: (detached HEAD 5af8d55b03) last updated 2014/10/10 18:43:44 (GMT +100)
  lib/ansible/modules/extras: (detached HEAD 681db4ce2c) last updated 2014/10/10 18:43:45 (GMT +100)
  v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/10/08 10:13:54 (GMT +100)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/10/08 10:14:38 (GMT +100)
```
##### Environment:

Ansible run on Ubuntu 12.04.5 LTS.  Clients Centos 6.5 (the bug manifests locally and remotely).
##### Summary:

Ansible's 'copy' module has a parameter, 'content'.  Although jinja2 expansions in the content parameter appear to be supported, they don't work as expected, specifically they do not mimic the behaviour of the template module with the same content.  Quoting appears to be mangled in some cases, and ansible can be made to throw exceptions with others. A content value '{{x}}', where a var x is defined with quotes within, will not necessarily result in the quotes (and whitespace) being preserved.
##### Steps To Reproduce:

Create a playbook called 'test.yml':

```

---
- name: quote mangling
  hosts: all

  vars:
    content: a="q "

  tasks:
    - name: test copy
      action: copy
              content="{{content}}"
              dest=/tmp/content
```

You may also need an ansible_hosts like this:

```
localhost
```

Then run ansible-playbook like this:

```
ansible-playbook -l localhost -c local test.yml
```

Output looks like this:

```
PLAY [quote mangling] ************************************************************* 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [test copy] ************************************************************* 
ok: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
```
##### Expected Results:

The expected result is a file in /tmp/content containing this:

```
a="q "
```
##### Actual Results:

What I actually get in the file is:

```
"a="q
```

No trailing space; quotes have been re-inserted wrongly.
##### Other cases

Remove the second quote in the var definition.  Ansible rejects the input:

```
fatal: [localhost] => error parsing argument string 'content="a="q" dest=/tmp/content', try quoting the entire line.
```

I believe I managed to make ansible throw an exception with one variation, however I cannot reproduce that now; possibly dependent on the version of ansible.

**Comment by CorbanR** [comment] 2014-10-15 21:28
+1
I get the exact same problem as described in the closed bug report https://github.com/ansible/ansible/issues/9321

**Comment by jimi-c** [comment] 2014-10-22 20:34
Hi @wu-lee, this is occuring due to the use of the same kinds of quotes in both the variable and the quoting around the variable name. After the variable is templated, the result is `content="a=" ""`, so the argument parser splits it up in the way you're seeing. If instead, you use single-quotes you will then get `content='a="q "'` which is then parsed correctly. Alternatively, you can use the "complex args" format as follows:

<pre>
    - name: test copy
      copy:
        content: "{{content}}"
        dest: /tmp/content
</pre>

which does not suffer from the same quote parsing issue, regardless of the quotes used around the variable name.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by wu-lee** [comment] 2014-10-22 22:31
Thanks for the explanation of how this happens, although I confess I still don't understand _why_ this is apparently considered correct and reasonable. If the template mechanism inserts quotes into the content=".." parameter, why are they not inserted with proper escapes?  Under what circumstances would this not be pathological behaviour?  After all, stitching variables into SQL without escaping them is a well known route to dangerously fragile systems.

You do suggest a work around: that I should not embed content with the same quotes as around the content. Except, what if I can't ensure the variable is free of the wrong sort of quote?  What if the content necessarily contains _both_ kinds of quote?  

In any case, this still seems like a nasty trap for the unwary that warrants an eye-catching warning in the documentation at the very least.  Why? Because it is surprising behaviour which can kill your server, by inserting non-functional configuration in arbitrarily critical places.

Also, I'm sure you don't mean to appear brusque and disinterested in my response, despite the discouraging paragraph at the end there, so will ignore it and reply here anyway.

**Comment by jimi-c** [comment] 2014-10-23 00:20
@wu-lee we have mechanisms in place to prevent the addition of other parameters through templating, though in this case you've introduced an empty quoted string so it's simply ignored.

I do agree that perhaps escaping any quotes might be the proper fix so that it works in all cases, so I'll reopen this, though demote it to a P3.

**Comment by jimi-c** [comment] 2014-10-23 00:21
I've also updated the title to properly reflect the bug.

**Comment by CorbanR** [comment] 2014-10-23 01:59
Issue Type: Bug Report
Ansible Version: ansible 1.7.2
Environment: CentOS
Summary: Variable content gets newlines when pasted into a file via the copy module

@jimi-c I'm not sure why the bug report https://github.com/ansible/ansible/issues/9321 was closed. It states that it's a duplicate of this bug, but i'm not entirely sure that's accurate. 

I have the exact same problem as described in https://github.com/ansible/ansible/issues/9321

For some of my playbooks I use ansible-vault to store my ssl keys in a vars file, I then use something like 

`- name: Install SSL private key
  copy: dest="{{ ssl.keyfile_location }}"
        owner=root
        group=root
        mode=0600
        content="{{ ssl_private_key }}"`

to save my private key. It seems to be saving my private key with spaces in between each line, which of course is not read as a valid key.

I don't think that issue https://github.com/ansible/ansible/issues/9321 is an exact duplicate of this issue, although i'm sure it's related. The issue described in https://github.com/ansible/ansible/issues/9321 does not seem to be present in Ansible 1.7.1

**Comment by jimi-c** [comment] 2015-06-27 02:56
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is sample output using your example above:

<pre>
# cat /tmp/content
a="q "
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-06-27 02:56 UTC
Labels: bug
