### ISSUE TITLE
dnf database locked failure during ansible-playbook run

### ISSUE THREAD

**Issue by myllynen** [ansible/ansible#46167] opened 2018-09-26 14:43 UTC
##### SUMMARY
Playbook fails with dnf database locked failure when running `ansible-playbook` on a playbook.

After installing Fedora 29 Workstation Beta and running the playbook at https://github.com/myllynen/misc/blob/master/fedora-init.yml on console (so no active GNOME session nor user using PackageKit) I saw this error:

```
...
TASK [Check RPM Fusion repository] ********************************************************************************************************************************************************************************
ok: [localhost]

TASK [Enable RPM Fusion repository] *******************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: RuntimeError: C++ std::exception: Exec failed: database is locked
failed: [localhost] (item=https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-29.noarch.rpm) => {"changed": false, "item": "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-29.noarch.rpm", "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_vq4vtcqn/ansible_module_dnf.py\", line 534, in <module>\n    main()\n  File \"/tmp/ansible_vq4vtcqn/ansible_module_dnf.py\", line 530, in main\n    ensure(module, base, params['state'], params['name'], params['autoremove'])\n  File \"/tmp/ansible_vq4vtcqn/ansible_module_dnf.py\", line 448, in ensure\n    if not base.resolve(allow_erasing=allow_erasing):\n  File \"/usr/lib/python3.7/site-packages/dnf/base.py\", line 736, in resolve\n    self._transaction = self._goal2transaction(goal)\n  File \"/usr/lib/python3.7/site-packages/dnf/base.py\", line 633, in _goal2transaction\n    ts.add_install(pkg, obs, reason)\n  File \"/usr/lib/python3.7/site-packages/dnf/db/group.py\", line 256, in add_install\n    ti_new = self.new(new, libdnf.transaction.TransactionItemAction_INSTALL, reason)\n  File \"/usr/lib/python3.7/site-packages/dnf/db/group.py\", line 219, in new\n    rpm_item = self._pkg_to_swdb_rpm_item(pkg)\n  File \"/usr/lib/python3.7/site-packages/dnf/db/group.py\", line 210, in _pkg_to_swdb_rpm_item\n    rpm_item = self.history.swdb.createRPMItem()\n  File \"/usr/lib/python3.7/site-packages/dnf/db/history.py\", line 291, in swdb\n    self._swdb = libdnf.transaction.Swdb(self.dbpath)\n  File \"/usr/lib64/python3.7/site-packages/libdnf/transaction.py\", line 729, in __init__\n    this = _transaction.new_Swdb(*args)\nRuntimeError: C++ std::exception: Exec failed: database is locked\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: RuntimeError: C++ std::exception: Exec failed: database is locked
failed: [localhost] (item=https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-29.noarch.rpm) => {"changed": false, "item": "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-29.noarch.rpm", "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_vgafvfaf/ansible_module_dnf.py\", line 534, in <module>\n    main()\n  File \"/tmp/ansible_vgafvfaf/ansible_module_dnf.py\", line 530, in main\n    ensure(module, base, params['state'], params['name'], params['autoremove'])\n  File \"/tmp/ansible_vgafvfaf/ansible_module_dnf.py\", line 448, in ensure\n    if not base.resolve(allow_erasing=allow_erasing):\n  File \"/usr/lib/python3.7/site-packages/dnf/base.py\", line 736, in resolve\n    self._transaction = self._goal2transaction(goal)\n  File \"/usr/lib/python3.7/site-packages/dnf/base.py\", line 633, in _goal2transaction\n    ts.add_install(pkg, obs, reason)\n  File \"/usr/lib/python3.7/site-packages/dnf/db/group.py\", line 256, in add_install\n    ti_new = self.new(new, libdnf.transaction.TransactionItemAction_INSTALL, reason)\n  File \"/usr/lib/python3.7/site-packages/dnf/db/group.py\", line 219, in new\n    rpm_item = self._pkg_to_swdb_rpm_item(pkg)\n  File \"/usr/lib/python3.7/site-packages/dnf/db/group.py\", line 210, in _pkg_to_swdb_rpm_item\n    rpm_item = self.history.swdb.createRPMItem()\n  File \"/usr/lib/python3.7/site-packages/dnf/db/history.py\", line 291, in swdb\n    self._swdb = libdnf.transaction.Swdb(self.dbpath)\n  File \"/usr/lib64/python3.7/site-packages/libdnf/transaction.py\", line 729, in __init__\n    this = _transaction.new_Swdb(*args)\nRuntimeError: C++ std::exception: Exec failed: database is locked\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
	to retry, use: --limit @/root/fedora-init.retry

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=14   changed=5    unreachable=0    failed=1   
```

I'm not sure is this report helpful enough or not but I'm probably unable to provide more relevant information since this is not reproducing.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
dnf

##### ANSIBLE VERSION
```
# ansible --version
ansible 2.6.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.0 (default, Aug 30 2018, 14:32:33) [GCC 8.2.1 20180801 (Red Hat 8.2.1-2)]
```

##### CONFIGURATION
```
# ansible-config dump --only-changed
# 
```

##### OS / ENVIRONMENT
Fedora 29 Workstation Beta

##### STEPS TO REPRODUCE
See above, not reproducing easily.

##### EXPECTED RESULTS
Playbook completes without such failure.

##### ACTUAL RESULTS
```
Traceback (most recent call last):
  File "/tmp/ansible_vq4vtcqn/ansible_module_dnf.py", line 534, in <module>
    main()
  File "/tmp/ansible_vq4vtcqn/ansible_module_dnf.py", line 530, in main
    ensure(module, base, params['state'], params['name'], params['autoremove'])
  File "/tmp/ansible_vq4vtcqn/ansible_module_dnf.py", line 448, in ensure
    if not base.resolve(allow_erasing=allow_erasing):
  File "/usr/lib/python3.7/site-packages/dnf/base.py", line 736, in resolve
    self._transaction = self._goal2transaction(goal)
  File "/usr/lib/python3.7/site-packages/dnf/base.py", line 633, in _goal2transaction
    ts.add_install(pkg, obs, reason)
  File "/usr/lib/python3.7/site-packages/dnf/db/group.py", line 256, in add_install
    ti_new = self.new(new, libdnf.transaction.TransactionItemAction_INSTALL, reason)
  File "/usr/lib/python3.7/site-packages/dnf/db/group.py", line 219, in new
    rpm_item = self._pkg_to_swdb_rpm_item(pkg)
  File "/usr/lib/python3.7/site-packages/dnf/db/group.py", line 210, in _pkg_to_swdb_rpm_item
    rpm_item = self.history.swdb.createRPMItem()
  File "/usr/lib/python3.7/site-packages/dnf/db/history.py", line 291, in swdb
    self._swdb = libdnf.transaction.Swdb(self.dbpath)
  File "/usr/lib64/python3.7/site-packages/libdnf/transaction.py", line 729, in __init__
    this = _transaction.new_Swdb(*args)
RuntimeError: C++ std::exception: Exec failed: database is locked
```

**Comment by sivel** [comment] 2018-09-26 15:00
There was a recent PR merged to handle the case where yum/dnf is running: https://github.com/ansible/ansible/pull/45359

Although I'm unsure whether this error indicates the same scenario.

cc @maxamillion

**Comment by maxamillion** [comment] 2018-09-26 15:39
@sivel is correct and the fix is in https://github.com/ansible/ansible/pull/45359. The issue is that we were previously issuing dnf API calls that resulted in writes to the dnf transaction database without checking for the lockfiles ourselves, but that turned out to be bad because we had made the incorrect assumption that dnf API would properly lock around write operations to it's internal data storage backend, we were wrong.

**Closed as completed by maxamillion** 2018-09-26 15:39 UTC

**Comment by myllynen** [comment] 2018-09-26 16:30
Ok, thanks for your prompt response!
