### ISSUE TITLE
Templating a destination which is a link incorrectly modifies the link target (was: changing target files with --check key)

### ISSUE THREAD

**Issue by vshkolin** [ansible/ansible#8998] opened 2014-09-14 01:58 UTC
##### Issue Type:

bug report
##### Ansible Version:

release1.7.1
##### Environment:

centos 6.4 (ansible server), centos 5.9 (managed system)
##### Summary:

When I run playbook with "template" action and "--check" key, if the destination file is symlink, the symlink will be broken.
##### Steps To Reproduce:

action in playbook:

```
- name: "named: configure named.conf"
  action: template src=named.conf.j2
           dest=/etc/named.conf
           backup=yes force=yes
           owner=root group=named mode=0640 setype=_default
  notify:
    - restart named
```

before running playbook:

```
[root@gw.home.loc ~]#ls -l /etc/named.conf
lrwxrwxrwx 1 root root 32 Sep 14 05:13 /etc/named.conf -> /var/named/chroot/etc/named.conf
```

command:

```
[cfg@cfg ansible]$ ansible-playbook -l vsh ~/conf/named.yml -v  --diff --check
```

command output:

```
TASK: [named | named: configure named.conf] ***********************************

changed: [vsh] => {"changed": true, "dest": "/etc/named.conf", "item": "", "src": "named.conf.j2", "state": "absent"}

NOTIFIED: [named | restart named] *********************************************

changed: [vsh] => {"changed": true, "item": "", "msg": "service state changed"}

PLAY RECAP ********************************************************************
```

 the result on target system (broken link):

```
[root@gw.home.loc ~]#ls -l /etc/named.conf
lrwxrwxrwx 1 root named 13 Sep 14 05:28 /etc/named.conf -> named.conf.j2
```

The symlink have broked only if the target file has same content, as generated from the template. If no, all work fine.

I have changed the template and run this command again:

before command:

```
[root@gw.home.loc ~]#ls -l /etc/named.conf
lrwxrwxrwx 1 root root 32 Sep 14 05:29 /etc/named.conf -> /var/named/chroot/etc/named.conf
```

command:

```
[cfg@cfg conf]$ ansible-playbook -l vsh ~/conf/named.yml -v  --diff --check
```

command output:

```
TASK: [named | named: configure named.conf] ***********************************

--- before: /etc/named.conf
+++ after: /home/cfg/conf/roles/named/templates/named.conf.j2

@@ -39,20 +39,21 @@
 //        listen-on-v6 port 53 { ::1; };
         directory         "/var/named";
         dump-file         "/var/named/data/cache_dump.db";
         statistics-file "/var/named/data/named_stats.txt";
         memstatistics-file "/var/named/data/named_mem_stats.txt";

         allow-query       { none; };
         allow-query-cache { none; };
         allow-recursion   { none; };
         allow-transfer    { none; };
+

         recursion no;
         additional-from-cache no;

 #        forwarders { 192.168.77.1; };
 #        forwarders { 172.20.1.5; 172.20.1.6; }; # westcall
 };

 include "/etc/rndc.key";

changed: [vsh] => {"changed": true, "item": ""}

NOTIFIED: [named | restart named] *********************************************

changed: [vsh] => {"changed": true, "item": "", "msg": "service state changed"}

PLAY RECAP ********************************************************************

vsh                        : ok=7    changed=2    unreachable=0    failed=0
```

the result:

```
[root@gw.home.loc ~]#ls -l /etc/named.conf
lrwxrwxrwx 1 root root 32 Sep 14 05:29 /etc/named.conf -> /var/named/chroot/etc/named.conf
```
##### Expected Results:

symlink is not changed
##### Actual Results:

symlink is broken

**Comment by mscherer** [comment] 2014-09-14 19:32
I cannot reproduce it neither on latest HEAD or on the tag 1.7.1 on a RHEL7.

```
$ date > test.target
$ echo Test > test.j2
$ ls -l test
lrwxrwxrwx. 1 misc misc 11 14 sept. 21:25 test -> test.target
$ ansible-playbook --diff -v --check -c local -i '127.0.0.1,' e.yml

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 

ok: [127.0.0.1]

TASK: [template] ************************************************************** 
--- before: /tmp/test
+++ after: /tmp/test.j2
@@ -1 +1 @@
-dim. sept. 14 21:25:33 CEST 2014
+Test

changed: [127.0.0.1] => {"changed": true}

PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=2    changed=1    unreachable=0    failed=0   
 $ ls -l test                                                       
 lrwxrwxrwx. 1 misc misc 11 14 sept. 21:25 test -> test.target
$ cat e.yml

---
- hosts: all
  tasks:
  - name: "template"
    action: template src=test.j2
        dest=/tmp/test
        backup=yes force=yes
```

**Comment by vshkolin** [comment] 2014-09-14 20:35
Hi!

You must change "echo Test > test.j2" to "cat test.target > test.j2".

This bug will be exhibited, if the template rendering result will be equal  
the target file content.

```
 [cfg@cfg test]$ ln -s test.target test
 [cfg@cfg test]$ cat test.target >test.j2
 [cfg@cfg test]$ ls -l test
 lrwxrwxrwx. 1 cfg cfg 11 Sep 15 00:31 test -> test.target
 [cfg@cfg test]$ ansible-playbook --diff -v --check -c local -i  
```

'127.0.0.1,' test.yml

```
 PLAY [all]  
```

---

```
 GATHERING FACTS  
```

---

```
 ok: [127.0.0.1]

 TASK: [template]  
```

---

```
 changed: [127.0.0.1] => {"changed": true, "dest": "/tmp/test/test",  
```

"gid": 500, "group": "cfg", "mode": "0777", "owner": "cfg", "secontext":  
"unconfined_u:object_r:user_home_t:s0", "size": 7, "src": "test.j2",  
"state": "link", "uid": 500}

```
 PLAY RECAP  
```

---

```
 127.0.0.1 : ok=2 changed=1 unreachable=0 failed=0

 [cfg@cfg test]$ ls -l test
 lrwxrwxrwx. 1 cfg cfg 7 Sep 15 00:31 test -> test.j2
```

## 

WBR, Vadim Shkolin

**Comment by jimi-c** [comment] 2014-09-15 15:27
Thanks @vshkolin, I can reproduce this and am looking into it now.

**Comment by jimi-c** [comment] 2014-09-15 20:55
Re-opened and modified subject to reflect the updated underlying issue.

**Comment by jimi-c** [comment] 2014-09-16 17:07
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed** 2014-09-16 17:07 UTC
Labels: P1, bug
