### ISSUE TITLE
apt_repository: Failed to validate the SSL certificate for launchpad.net:443

### ISSUE THREAD

**Issue by maedox** [ansible/ansible#9966] opened 2015-01-09 14:12 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8.2
  configured module search path = /usr/share/ansible
##### Environment:

Running from: Linux Mint 17.1 (based on Ubuntu 14.04)
Managing: Ubuntu 10.04, 12.04
##### Summary:

Adding a PPA with the apt_repository module fails with certificate validation problems.
Manually running add-apt-repository on the host works.
##### Steps To Reproduce:

``` yaml
- name: "PHP: Add PHP 5.4 PPA"
  apt_repository:
    repo: ppa:ondrej/php5-oldstable
```
##### Expected Results:

PPA added under /etc/apt/sources.list.d/
##### Actual Results:

```
TASK: [php | PHP: Add PHP 5.4 PPA] ******************************************** 
failed: [host.example.com] => {"failed": true}
msg: Failed to validate the SSL certificate for launchpad.net:443. Use validate_certs=no or make sure your managed systems have a valid CA certificate installed. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible
```

**Comment by jimi-c** [comment] 2015-07-01 19:41
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
root@ubuntu1404:~# ansible-playbook -vv 9966.yml -i localhost, -c local
1 plays in 9966.yml
PLAY: ***************************************************************************
TASK [PHP: Add PHP 5.4 PPA] *****************************************************
changed: [localhost] => {"repo": "ppa:ondrej/php5-oldstable", "invocation": {"module_name": "apt_repository", "module_args": {"repo": "ppa:ondrej/php5-oldstable"}}, "state": "present", "changed": true}
PLAY RECAP **********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0   
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by basictheprogram** [comment] 2015-12-10 06:07
I think we have a regression.

```
$ ansible --version
ansible 2.1.0 (devel 30e729557f) last updated 2015/12/09 22:10:16 (GMT -500)
  lib/ansible/modules/core: (detached HEAD 0b5555b62c) last updated 2015/12/09 22:10:16 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD cbed642009) last updated 2015/12/09 22:10:16 (GMT -500)
  config file = /Users/tanner/projects/ansible.git/playbooks.git/ansible.cfg
  configured module search path = Default w/o overrides
```

```
- name: add zfs-native apt repository
  apt_repository: >
      repo="ppa:zfs-native/stable"
      update_cache="yes"
```

```
FAILED! => {"changed": false, "failed": true, "msg": "Failed to validate the SSL certificate for launchpad.net:443. Make sure your managed systems have a valid CA certificate installed.  If the website serving the url uses SNI you need python >= 2.7.9 on your managed machine.  You can use validate_certs=False if you do not need to confirm the server\\s identity but this is unsafe and not recommended Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible"}
```

The managed machine is a fully patched Ubuntu 14.04 and it's python 2.7.6

**Comment by my2ter** [comment] 2016-06-14 04:47
Hi, 

I am using the official docker image for Ubuntu:14.04. https://hub.docker.com/_/ubuntu/ And the following task fails:

```
  name: Add repository to install last PHP version
  apt_repository:
    repo="ppa:ondrej/php5-5.6"
    update_cache=yes
```

Ansible installed with homebrew:

```
ansible --version
ansible 2.1.0.0
```

```
FAILED! => {"changed": false, "failed": true, "msg": "Failed to validate the SSL certificate for launchpad.net:443. Make sure your managed systems have a valid CA certificate installed. If the website serving the url uses SNI you need python >= 2.7.9 on your managed machine or you can install the `urllib3`, `pyopenssl`, `ndg-httpsclient`, and `pyasn1` python modules to perform SNI verification in python >= 2.6. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible"}
```

Should this be fixed?

Thanks

**Comment by arikon** [comment] 2016-07-07 05:33
Same error as above ⬆️ on the latest state of `stable-2.1` branch

**Comment by arikon** [comment] 2016-07-07 05:35
@jimi-c Have a look at the above comments, please

**Comment by resmo** [comment] 2016-07-07 05:49
reopen it based on the recent comments.

**Comment by kuza55** [comment] 2016-07-25 20:51
I'm also running into this targeting a fresh install of 14.04, is there a workaround for this issue?

[EDIT]: I think in my case this might be because I was trying to configure a VM with hostonly network access, and no route to the internet, so if nothing else maybe the error message could be improved to not be misleading.

**Comment by otanner** [comment] 2016-07-26 07:55
I'm experiencing the same Ubuntu 14.04 issue. I also tried updating to Python 2.7.12 before running Ansible, didn't help.

**Comment by prevostc** [comment] 2016-09-12 14:33
Same issue with ansible 2.1.1.0 on ubuntu 14.04 and python 2.7.6: `Failed to validate the SSL certificate for deb.nodesource.com:443. ...`

**Comment by prevostc** [comment] 2016-09-12 14:52
@boris-hocde (in my company) found a solution:

Before python 2.7.9:

```
- name: Add nodesource apt key
  become: yes
  shell: curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
```

After python 2.7.9

```
- name: Add nodesource apt key
  become: yes
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present
```

**Comment by bcoca** [comment] 2017-01-23 17:41
These now give a proper error instead of the misleading generic:

```
"Failed to validate the SSL certificate for deb.nodesource.com:443. Make sure your managed systems have a valid CA certificate installed. If the website serving the url uses SNI you need python >= 2.7.9 on your managed machine or you can install the `urllib3`, `pyopenssl`, `ndg-httpsclient`, and `pyasn1` python modules to perform SNI verification in python >= 2.6. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible. The exception msg was: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure."
```

So I'm going to go ahead and close the issue as we won't be autoupgrading the target pythons.

**Closed as completed by bcoca** 2017-01-23 17:41 UTC
Labels: affects_1.8, bug

**Comment by elnur** [comment] 2017-02-25 06:34
Installing the `ca-certificates` APT package in LXC containers solved the issue for me.

**Comment by kartsims** [comment] 2017-08-14 12:40
Same solution as @elnur for Debian container on Docker

**Comment by aaksarin** [comment] 2017-08-18 11:50
Installing apt packages python-urllib3, python-openssl, python-pyasn1, python-pip and pip package ndg-httpsclient solved issue for me. Thanks to Yuri Kanivetsky from this thread https://groups.google.com/forum/#!msg/ansible-project/p4dQ0c25bpM/qSsI4JQqBAAJ.

**Comment by nvtkaszpir** [comment] 2017-08-29 08:29
Too bad the message is hiding underlying network issues like problems with routing.
