### ISSUE TITLE
copy module can't overwrite/replace read-only files

### ISSUE THREAD

**Issue by ciupicri** [ansible/ansible#1768] opened 2012-12-13 18:45 UTC
Create `somefile` and run:

```
ansible localhost -c local -m copy -a 'src=somefile dest=/tmp/destfile mode=444'    
```

Now modify `/tmp/destfile` and re-run the previous command. The result will be:

```
localhost | FAILED >> {
    "failed": true, 
    "msg": "Destination /tmp/destfile not writable"
}
```

ansible should be able to update that file (just like vi can with `w!`).

This happens with version f2893b64183992e48bc1d5c63564e7bfa40a8200.

**Comment by mpdehaan** [comment] 2012-12-13 20:50
It is running as your present username remotely, are you sure that user has
permission?

**Comment by dhozac** [comment] 2012-12-13 21:28
Yeah, it is all the checking the copy module does. I'm working on less checking and more error handling, leaving the actual checking up to the operating system.

**Comment by blair** [comment] 2013-02-10 05:14
I think it's this code.  Maybe these checks should be removed, since the file is being atomically replaced anyway, it's original read and write privileges don't matter:

```
    if not os.access(dest, os.W_OK):
        module.fail_json(msg="Destination %s not writable" % (dest))
    if not os.access(dest, os.R_OK):
        module.fail_json(msg="Destination %s not readable" % (dest))
```

Also, instead of making a copy using

```
        shutil.copyfile(src, dest_tmp)
```

making a hardlink to it for the backup path and then using the atomic replace will avoid the issue of having read privileges on it.

**Comment by bcoca** [comment] 2013-02-12 16:50
I would change the check to see if the directory (not file) is writable, then proceed with hardlink and rest

**Comment by mpdehaan** [comment] 2013-02-16 02:18
somebody send me a patch!

**Comment by bcoca** [comment] 2013-02-16 03:28
So i have a semi working patch, it has the side effect that if the file is
not readable md5 hash always returns empty and forces a copy of the file,
as long as permissions aren't changed.

Is this acceptable?

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by mpdehaan** [comment] 2013-02-16 03:36
Under what scenarios does that extra xfer happen?

**Comment by kavink** [comment] 2013-02-16 03:43
Im sorry , we just have nothing to do on Friday night :) , I just checked in similar stuff at exact same time ... Let me know if you want me to cancel my pull request.. Basically i still wanted the destination to be readable hence kept the check, and that would also make sure md5sum is always matched.

**Comment by kavink** [comment] 2013-02-16 03:44
#2099 Here is my pull request, let me know, Either way i am ok with it.

**Comment by bcoca** [comment] 2013-02-16 03:55
extra transfer happens when directory is writable and the file is not
readable, the file always appears to be different and will always be
overwritten

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by bcoca** [comment] 2013-02-16 03:56
I posted a comment of what a merged patch could look like on #2099

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by mpdehaan** [comment] 2013-02-16 18:59
Yep, this should be fixed once #2099 gets rebased.

**Comment by kavink** [comment] 2013-02-17 00:45
Confused , I thought #2100 was going to be merge, but anyways i have rebased, Let me know if i should send another pull requested ?

**Comment by mpdehaan** [comment] 2013-02-17 00:49
still says it can't auto merge, so you may need to.

**Comment by kavink** [comment] 2013-02-17 00:52
Done. #2102

**Comment by mpdehaan** [comment] 2013-02-17 18:09
fix commited by rebasing 2100.

Extreme apologies on the confusion in having two of these pull requests going at once.   I guess a good problem to have!

Thanks everyone and let me know if you encounter any problems with this.

**Closed as completed by mpdehaan** 2013-02-17 18:09 UTC

**Comment by ghost** [comment] 2013-11-23 23:07
It looks like the get_url script has the same problem - I'm wondering if the same fix could apply

**Comment by lindes** [comment] 2014-11-07 05:08
for get_url, using dest=./pathname instead of dest=pathname seems to be a viable workaround, at least in the case I was hitting.

**Comment by nhooey** [comment] 2016-02-17 17:22
I can confirm that the `get_url` has the same issue. I'm getting `Destination /etc not writable` with this directive where `become: root` is set with Ansible 2.0.0.2:

``` yaml
get_url: url=http://icanhazip.com dest=/etc/publicip mode="u+rw,go+r"
```

Is there a GitHub issue tracking this for the `get_url` module?

**Comment by nhooey** [comment] 2016-02-17 17:30
@lindes Is setting `get_url: url=whatever.com dest=./etc/file` going to work when `/etc/file` is supposed to be an absolute path?

**Comment by splashx** [comment] 2016-04-11 22:05
@nhooey no, it won't. I'm also stuck with this problem :/

**Comment by splashx** [comment] 2016-04-11 22:11
@voltagex @nhooey  try `dest=/path/to/folder` (and not `dest=/path/to/folder/file`) if it works o.O

**Comment by qwuscu** [comment] 2019-04-18 17:11
> @voltagex @nhooey try `dest=/path/to/folder` (and not `dest=/path/to/folder/file`) if it works o.O

I have tried both dest=/path/to/folder and dest=/path/to/folder/file, both doesn't work. Any idea? thanks!
