### ISSUE TITLE
copy leaves temp dir behind when force=no

### ISSUE THREAD

**Issue by twouters** [ansible/ansible#5739] opened 2014-01-23 16:31 UTC
When using force=no with a copy action, the tmp directory created in remote_tmp is not removed when there are no differences in the source and destination file.

```
$ ansible --version
ansible 1.5
```

**Comment by risaacson** [comment] 2014-01-28 17:42
@twouters from the word that I am getting back and from my testing this has been fixed and will be in the 1.5 release.

Can you pull the latest from devel and test this to verify those findings?

If it is still a problem can you also include the host OS that you are executing from and what the remote OSes are?

Thanks!

**Comment by twouters** [comment] 2014-01-28 22:08
I've just installed the latest master b6875b3b874aebd4ef3cf576fbbdfa8bcf5ea101
The issue still remains, this task leaves a tmp folder behind if the destination file exists.

```
- name: Copy testfile
  copy: src=testfile dest=/opt/ force=no
  register: result
```

**Comment by risaacson** [comment] 2014-01-28 23:05
I have confirmed this behavior as described.

Initial run with force=no and no existing file yields no leftover directory under ~/.ansible/tmp/.
Secondary run with force=no and an existing file yields an empty ansible-tmp-\* directory under ~/.ansible/tmp/.

Initial run with force=yes and no existing file yields no leftover directory under ~/.ansible/tmp.
Secondary run with force=yes and an existing file yields no leftover directory under ~/.ansible/tmp.

I am working on a fix to clean this up.

**Comment by jimi-c** [comment] 2014-02-03 15:56
The above PR was merged in to correct this. Thanks!

**Comment by risaacson** [comment] 2014-02-04 18:34
This was reverted as the fix was partially correct.

**Comment by risaacson** [comment] 2014-02-10 17:24
This is tested as resolved with the recent fixes.

**Closed as completed by risaacson** 2014-02-10 17:24 UTC
Labels: bug

**Comment by mowgli** [comment] 2017-07-01 09:48
Sorry, I have to reopen this old bug.

I have the following task:
```
- copy:
     dest: /etc/ansible/vault.pw
     force: no
     mode: 0400
     content: "{{ lookup('pipe', 'dd status=none if=/dev/random bs=1 count=24 | base64') }}\n"
```

Every time it is running, it left behind a temp file in /tmp with the output of the pipe.

I'll open a new bug as I cannot reopen this one.

**Comment by jimi-c** [comment] 2017-08-16 19:34
@mowgli please open a new issue for this, as we don't typically reopen issues on the basis that the root cause is (most likely) different.

Thanks!
