### ISSUE TITLE
ssh + sudo password can hang indefinitely

### ISSUE THREAD

**Issue by stanhu** [ansible/ansible#9544] opened 2014-11-12 15:15 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

$ ansible --version
ansible 1.7.2
##### Environment:

MacOS (also occurs on Ubuntu 14.04)
##### Summary:

ssh logins that require sudo passwords can hang indefinitely.
##### Steps To Reproduce:

I think the bug could be be reproduced if you enable sudo passwords and change sudo to a program that runs 'sleep 10' before it executes. Then run a playbook with the "--ask-sudo" parameter with that machine in the inventory.

Here is what I think is happening:
1. Ansible attempts to ssh into a machine.
2. Ansible successfully logs in and attempts to run 'sudo'.
3. sudo takes a while and requires a password to be entered.
4. Ansible does a select() on the read socket.
5. The select() times out after 10 seconds. Ansible waits for the SSH process to terminate (from ansible/runner/connection_plugins/ssh.py):

```
         if not rfd:
                    # timeout. wrap up process communication                                                                                                                                 
                    stdout = p.communicate()
                    raise errors.AnsibleError('ssh connection error waiting for sudo or su password prompt')
```

However, since Ansible is logged in and sudo is running, the process never terminates. communicate() gets stuck.

Essentially, I think this is a corner case where the ssh login succeeds, but the time it takes for sudo to execute and ask for a password exceeds the timeout. Since the ssh session was successful, the ssh process will never return, causing Ansible to hang indefinitely.

I verified this was happening by adding a 'continue', here:

```
   if not rfd:
                    continue
                    # timeout. wrap up process communication                                                                                                                                 
                    stdout = p.communicate()
```

This worked--essentially a short time later, the select() returned successfully, and Ansible functioned well. To confirm this, I added some debug statements using time.time(). Here is what I saw:
1. t = 0: start of first select()
2. t = 10.000742: timeout occurs
3. t = 10.000874: second select() returns successfully

How to fix this? Ideally, we would have some way of knowing that the ssh session successfully logged in but was waiting for sudo. I don't think there is a foolproof way of knowing this. 

In any case, communicate() should have a timeout, so that if ssh fails to terminate, we either terminate the ssh process or run select() again just to be sure. There are some ideas here for how to implement a timeout:

http://stackoverflow.com/questions/1191374/subprocess-with-timeout 

For now, I've worked around the problem by changing timeout = 20, but I think the code still needs to prevent communicate() from getting stuck.
##### Expected Results:

ssh logins and sudo executes fine
##### Actual Results:

ssh process never returns and causes Ansible to get stuck

I think a similar issue was reported in issue #8058.

**Comment by stanhu** [comment] 2014-11-12 15:39
I think the right solution is to use the Python 3.2 backport module of subprocess. See:

http://bugs.python.org/issue5673
https://pypi.python.org/pypi/subprocess32

**Comment by directionless** [comment] 2015-01-29 04:18
I think I'm running into this. Is there a solution, and I see that the PR was denied. Is there a solution?

**Comment by directionless** [comment] 2015-01-29 04:55
Following up from twitter, I'm really much of a python dev, so I'm not sure what level of detail will help. I'm also not totally sure it's _this_ bug, but given my environment, it's a reasonable first guess. (Also, I have to elide a lot of internal details, I know it makes it hard)

ansible (version 1.8.2) with -vvvv

with connection = ssh:

```
<hostaac> ESTABLISH CONNECTION FOR USER: seph
<hostaac> REMOTE_MODULE command yum -y update
<hostaac> EXEC ssh -C -vvv -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 hostaac /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=KEY] password: " -u root /bin/sh -c '"'"'echo SUDO-SUCCESS-KEY; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python'"'"''
fatal: [hostaac] => ssh connection error waiting for sudo or su password prompt
```

with connection = paramiko

```
<hostaac> ESTABLISH CONNECTION FOR USER: seph on PORT 22 TO hostaac
<hostaac> REMOTE_MODULE command yum -y update
<hostaac> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1422506993.14-271781994674754 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1422506993.14-271781994674754 && echo $HOME/.ansible/tmp/ansible-tmp-1422506993.14-271781994674754'
<hostaac> PUT /tmp/tmpxb7Og0 TO /home/seph/.ansible/tmp/ansible-tmp-1422506993.14-271781994674754/command
<hostaac> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=KEY] password: " -u root /bin/sh -c '"'"'echo SUDO-SUCCESS-KEY; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/seph/.ansible/tmp/ansible-tmp-1422506993.14-271781994674754/command; rm -rf /home/awph/.ansible/tmp/ansible-tmp-1422506993.14-271781994674754/ >/dev/null 2>&1'"'"''
(hangs forever)
```

hostaac is up, and I do have sudo access on it.

**Comment by Vladimir-csp** [comment] 2016-02-15 19:58
Hi!
I'm experiencing sudo hang issue on FreeBSD clients. It seems that ansible can not parse sudo's lecture on first time usage. If I log in to client machine and run `sudo true` before using ansible, then hang does not happen.

**Comment by deggis** [comment] 2016-02-26 10:26
I experienced just now the exact looking hang @directionless was experiencing with paramiko. Last line is the EXEC /bin/sh sudo [FLAGS] line. There might be something to do with this connection using the sudo command the first time and getting the multiline warning instead of just oneliner prompt.

I was using a ansible_sudo_exe=dzdo, but after checking it seems to react to all flags the same way as sudo.

I looked into it and found that lib/ansible/plugins/connection/paramiko_ssh.py was comparing the expected one-line password prompt to a multiline prompt that begins by telling the administrator warnings. The prompt is then not recognized and the process keeps waiting for more input, expecting to recognize a line with prompt. After adding a second comparison for seeing if the prompt is only in the last line I got it working.

Seems that the original sudo command prints those warnings also first time. I'm not sure if my ansible configuration is missing a flag that would prevent that.

As a workaround I added an extra check for last line of become_ouput after these two prompt checks after:

https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/connection/paramiko_ssh.py#L289

EDIT: I was running ansible 2.0.0.2 7de237c5a1.

**Comment by deggis** [comment] 2016-02-26 10:34
Right. Looks like there was already a pull-request on this, #14400

**Comment by d3matt** [comment] 2016-04-19 17:49
should be able to close this now that #14400 is merged... I should've gone looking for tickets when I fixed that

**Comment by jctanner** [comment] 2016-05-27 12:25
Duplicate of https://github.com/ansible/ansible/issues/7165

**Closed as completed by jctanner** 2016-05-27 12:25 UTC
Labels: bug
