### ISSUE TITLE
v2 playbook with --tags are not working (same playbook works fine in v1)

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible#11320] opened 2015-06-19 00:27 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

$ ansible --version
ansible 2.0.0 (devel 98fee172ee) last updated 2015/06/18 13:05:15 (GMT -500)
  lib/ansible/modules/core: (detached HEAD 9acc7c402f) last updated 2015/06/10 17:06:47 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD 2f967a949f) last updated 2015/06/10 17:06:47 (GMT -500)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/06/03 00:37:54 (GMT -500)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/06/03 00:37:58 (GMT -500)
  configured module search path = None
##### Ansible Configuration:

I was (aka using v1 code base)
$ source v1/hacking/env-setup

Now I'm (using v2 code base)
$ source hacking/env-setup
##### Environment:

OS X Yosemite 10.10.3

$ python -V
Python 2.7.6

$ pip freeze
ansible==2.0.0
ecdsa==0.13
epdb==0.12
httplib2==0.9.1
isodate==0.5.1
Jinja2==2.7.3
kerberos==1.2.2
MarkupSafe==0.23
nose==1.3.7
paramiko==1.15.2
passlib==1.6.2
pycrypto==2.6.1
pywinrm==0.0.3
PyYAML==3.11
six==1.9.0
xmltodict==0.9.2
##### Summary:

Playbooks in v2 using --tags do not run the plays.
##### Steps To Reproduce:

VMware virtual host running linux.
Snapshot to save the unpatched state.

```
$ source v1/hacking/env-setup
$ cd ../playbooks/
$ ansible-playbook --ask-pass --ask-sudo-pass  -i testing-servers linux-servers.yml --tags "apt"
SSH password:
SUDO password[defaults to SSH password]:
PLAY [linux-servers] **********************************************************
GATHERING FACTS ***************************************************************
ok: [host.domain.com]
TASK: [common | package update (apt)] *****************************************
ok: [host.domain.com]
TASK: [common | package upgrade (apt)] ****************************************
changed: [host.domain.com]
PLAY RECAP ********************************************************************
host.domain.com     : ok=2    changed=1    unreachable=0    failed=0
```

Roll back virtual machine to unpatch state.

```
$ source hacking/env-setup
$ cd ../playbooks/
$ ansible-playbook --ask-pass --ask-sudo-pass  -i testing-servers linux-servers.yml --tags "apt"
SSH password:
SUDO password[defaults to SSH password]:
PLAY: ***************************************************************************
TASK [setup] ********************************************************************
ok: [host.domain.com]
PLAY RECAP **********************************************************************
host.domain.com    : ok=1    changed=0    unreachable=0    failed=0
```

I know for sure there's 2 plays, so "ok=1" isn't right. I also know there are multiple patches to this virtual machine so "changed=0" is not right.

```

---
# file: linux-servers.yml

- hosts: linux-servers
  remote_user: ansible-user
  roles:
    - common
```

```

---
# file: roles/common/tasks/main.yml

- include: redhat.yml
  when: ansible_os_family == 'RedHat'
- include: debian.yml
  when: ansible_os_family == 'Debian'
- include: suse.yml
  when: ansible_os_family == 'Suse' or ansible_os_family == 'openSUSE'
- include: solaris.yml
  when: ansible_os_family == 'Solaris'
```

The virtual machine is debian.

```

---
# tasks file for roles/common/tasks/debian.yml

# Only run "update_cache=yes" if the last one is more than 3600 seconds ago
- name: package update (apt)
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes
  always_run: yes
  tags: apt

# Update all packages to the latest version
- name: package upgrade (apt)
  apt: upgrade=dist
  sudo: yes
  always_run: yes
  tags:  apt
```
##### Expected Results:

I assume the plays would run to completion like then do in v1.
##### Actual Results:

```
$ source hacking/env-setup
$ cd ../playbooks/
$ ansible-playbook --ask-pass --ask-sudo-pass  -i testing-servers linux-servers.yml --tags "apt"
SSH password:
SUDO password[defaults to SSH password]:
PLAY: ***************************************************************************
TASK [setup] ********************************************************************
ok: [host.domain.com]
PLAY RECAP **********************************************************************
host.domain.com    : ok=1    changed=0    unreachable=0    failed=0
```

**Comment by basictheprogram** [comment] 2015-06-19 14:51
Without --tags plays run as expected.

```
$ ansible-playbook --ask-pass --ask-sudo-pass  -i testing-servers linux-servers.yml --check
SSH password:
SUDO password[defaults to SSH password]:
PLAY: ***************************************************************************
TASK [setup] ********************************************************************
ok: [host.domain.com]
TASK [common : common : include] ************************************************
skipping: [host.domain.com]
TASK [common : common : include] ************************************************
included: debian.yml for host.domain.com
TASK [common : common : package update (apt)] ***********************************
ok: [host.domain.com]
TASK [common : common : Ensure core packages are installed (apt)] ***************
<snip>
ok: [host.domain.com]
TASK [common : common : package upgrade (apt)] **********************************
ok: [host.domain.com]
TASK [common : common : autoremove (apt)] ***************************************
ok: [host.domain.com]
TASK [common : common : Ensure core services are running] ***********************
<snip>
changed: [host.domain.com]
NO MORE HOSTS LEFT **************************************************************
PLAY RECAP **********************************************************************
host.domain.com : ok=6    changed=2    unreachable=0    failed=1
```

**Comment by basictheprogram** [comment] 2015-06-23 20:04
Looks like --check isn't working. I do not know if this is related to this problem, but when I invoke

```
$ ansible-playbook --ask-pass --ask-sudo-pass  -i production-servers linux-servers.yml --check
SSH password:
SUDO password[defaults to SSH password]:
PLAY: ***************************************************************************
TASK [setup] ********************************************************************
ok: [host.domain.com]
TASK [common : common : include] ************************************************
skipping: [host.domain.com]
TASK [common : common : include] ************************************************
included: debian.yml for host.domain.com
TASK [common : common : package update (apt)] ***********************************
ok: [host.domain.com]
TASK [common : common : Ensure core packages are installed (apt)] ***************
{'invocation': {'module_name': u'apt', 'module_args': {'_ansible_check_mode': True, u'state': u'present', u'name': u'apticron,bash,bind9-host,bzr,deborphan,git-core,iptables,localepurge,ntp,python,python-simplejson,traceroute,resolvconf,rsyslog,ssh,vim'}}, 'item': u'apticron,bash,bind9-host,bzr,deborphan,git-core,iptables,localepurge,ntp,python,python-simplejson,traceroute,resolvconf,rsyslog,ssh,vim', u'changed': False, u'cache_update_time': 0, u'cache_updated': False}
ok: [host.domain.com]
TASK [common : common : package upgrade (apt)] **********************************
changed: [host.domain.com]
TASK [common : common : autoremove (apt)] ***************************************
ok: [host.domain.com]
TASK [common : common : Ensure core services are running] ***********************
{u'name': u'ntp', u'changed': False, u'enabled': True, 'item': u'ntp', u'state': u'started', 'invocation': {'module_name': u'service', 'module_args': {'_ansible_check_mode': True, u'state': u'running', u'enabled': u'yes', u'name': u'ntp'}}}
{'invocation': {'module_name': u'service', 'module_args': {'_ansible_check_mode': True, u'state': u'running', u'enabled': u'yes', u'name': u'rsyslog'}}, 'item': u'rsyslog', u'changed': False}
{'invocation': {'module_name': u'service', 'module_args': {'_ansible_check_mode': True, u'state': u'running', u'enabled': u'yes', u'name': u'ssh'}}, 'item': u'ssh', u'changed': False}
{u'msg': u'service state changed', 'invocation': {'module_name': u'service', 'module_args': {'_ansible_check_mode': True, u'state': u'running', u'enabled': u'yes', u'name': u'open-vm-tools'}}, u'changed': True, 'item': u'open-vm-tools'}
changed: [host.domain.com]
NO MORE HOSTS LEFT **************************************************************

PLAY RECAP **********************************************************************
host.domain.com : ok=6  changed=3    unreachable=0    failed=0

```

Ansible still made changes. I thought --check won't make any changes?

Seems like ansible is ignoring command line options?

```
$ ansible --version
ansible 2.0.0 (devel 0b16580567) last updated 2015/06/23 14:16:14 (GMT -500)
  lib/ansible/modules/core: (detached HEAD a1181b490b) last updated 2015/06/23 14:16:16 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD 44eb758dc7) last updated 2015/06/23 14:16:17 (GMT -500)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/06/03 00:37:54 (GMT -500)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/06/03 00:37:58 (GMT -500)
  configured module search path = None
```

**Comment by basictheprogram** [comment] 2015-06-25 02:35
$ ansible-playbook --ask-pass --ask-sudo-pass  -i production-servers --tags apt linux-servers.yml

This play works. Tagged tasks work if it's in in the main.yml. But the same task in the debian.yml does not get run. So it looks like an -include: or when: problem.

Using the debugger and playing around in taggble.py I never see the tasks in the -include: files get processed.

Does playbook/include_file.py have the logic for including files? 
Maybe playbook_include.py?

``` yaml
---
# file: roles/common/tasks/main.yml

- include: redhat.yml
  when: ansible_os_family == 'RedHat'
- include: debian.yml
  when: ansible_os_family == 'Debian'
- include: suse.yml
  when: ansible_os_family == 'Suse' or ansible_os_family == 'openSUSE'
- include: solaris.yml
  when: ansible_os_family == 'Solaris'

# Update all packages to the latest version
- name: package upgrade (apt)
  apt: upgrade=dist
  sudo: yes
  always_run: yes
  tags:  apt
```

**Comment by basictheprogram** [comment] 2015-06-25 03:04
The play

``` yaml
---
# file: roles/common/tasks/main.yml

- include: redhat.yml
  when: ansible_os_family == 'RedHat'
- include: debian.yml
  when: ansible_os_family == 'Debian'
- include: suse.yml
  when: ansible_os_family == 'Suse' or ansible_os_family == 'openSUSE'
- include: solaris.yml
  when: ansible_os_family == 'Solaris'

- include: missing.yml
```

v1 run

```
$ source v1/hacking/env-setup
$ ansible-playbook --ask-pass --ask-sudo-pass  -i production-servers --tags apt linux-servers.yml
SSH password:
SUDO password[defaults to SSH password]:
ERROR: file could not read: /Users/tanner/projects/ansible.git/playbooks/roles/common/tasks/missing.yml
```

v2 run

```
$ source hacking/env-setup
$ ansible-playbook --ask-pass --ask-sudo-pass  -i production-servers --tags apt linux-servers.yml
SSH password:
SUDO password[defaults to SSH password]:
PLAY: ***************************************************************************
TASK [setup] ********************************************************************
ok: [<snip>]
PLAY RECAP **********************************************************************
<snip> : ok=1    changed=0    unreachable=0    failed=0
```

ansible-playbook v2 is not process includes, even ones that do not exist.

```
$ ansible --version
ansible 2.0.0 (issue#11320 332ca927d9) last updated 2015/06/24 21:07:21 (GMT -500)
  lib/ansible/modules/core: (detached HEAD 725ce906f6) last updated 2015/06/24 21:04:35 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD 44eb758dc7) last updated 2015/06/23 14:16:17 (GMT -500)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/06/03 00:37:54 (GMT -500)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/06/03 00:37:58 (GMT -500)
  configured module search path = None
```

**Comment by basictheprogram** [comment] 2015-07-15 09:12
I'm looking to see if --tags are implemented in v2 code base. 
The --list-tags does not work in v2 code either.

class Play(Base, Taggable, Become) looks to inherit from Taggable, but I do not find Taggable._load_tags invoked anywhere in the code?

I use --tags a lot and I've run the code with epdb but I cannot find where or how tags get processed.

Any assistance would be appreciated. 

Thanks.

**Comment by jimi-c** [comment] 2015-07-17 19:52
Hi @basictheprogram, using a simple reproducer it looks like the tag issue (where the tags are only defined in tasks inside the role) has been resolved, as is the check mode issue:

<pre>
# ansible-playbook -vv --tags=foo test.yml --check
Using /etc/ansible/ansible.cfg as config file
1 plays in test.yml
PLAY: ***************************************************************************
TASK [setup] ********************************************************************
ok: [localhost]
TASK [test : test : command] ****************************************************
changed: [localhost] => {"changed": true, "cmd": ["echo", "this is task 1"], "delta": "0:00:00.003187", "end": "2015-07-17 15:51:47.510107", "rc": 0, "start": "2015-07-17 15:51:47.506920", "stderr": "", "stdout": "this is task 1", "stdout_lines": ["this is task 1"], "warnings": []}
TASK [test : test : command] ****************************************************
skipping: [localhost] => {"changed": false, "msg": "remote module does not support check mode", "skipped": true}
PLAY RECAP **********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0   
</pre>

Since your play is a bit more involved, could you please let us know if you're still seeing this issue there, and if so could you post a full example in a gist?

**Comment by basictheprogram** [comment] 2015-07-18 09:03
```
ansible-playbook -k -K -i production-servers  --tags=apt linux-servers.yml --check
```

After several

ok: [host1.domain.com]
ok: [host2.domain.com]
ok: [host3.domain.com]
[ERROR]: Unexpected Exception: 'NoneType' object is not iterable

No --check

```
ansible-playbook -k -K -i production-servers  --tags=apt  linux-servers.yml 
```

ok: [host1.domain.com]
ok: [host2.domain.com]
ok: [differenthost3.domain.com]
[ERROR]: Unexpected Exception: 'NoneType' object is not iterable

No --check and -vvv

```
ansible-playbook -k -K -i production-servers  --tags=apt  -vvv linux-servers.yml 

ok: [host.domain.com]
 [ERROR]: Unexpected Exception: 'NoneType' object is not iterable

the full traceback was:

Traceback (most recent call last):
  File "/Volumes/Warrior1TB/Users/tanner/projects/ansible.git/ansible/bin/ansible-playbook", line 77, in <module>
    sys.exit(cli.run())
  File "/Volumes/Warrior1TB/Users/tanner/projects/ansible.git/ansible/lib/ansible/cli/playbook.py", line 162, in run
    results = pbex.run()
  File "/Volumes/Warrior1TB/Users/tanner/projects/ansible.git/ansible/lib/ansible/executor/playbook_executor.py", line 139, in run
    result = self._tqm.run(play=play)
  File "/Volumes/Warrior1TB/Users/tanner/projects/ansible.git/ansible/lib/ansible/executor/task_queue_manager.py", line 258, in run
    return strategy.run(iterator, connection_info)
  File "/Volumes/Warrior1TB/Users/tanner/projects/ansible.git/ansible/lib/ansible/plugins/strategies/linear.py", line 141, in run
    host_tasks = self._get_next_task_lockstep(hosts_left, iterator)
  File "/Volumes/Warrior1TB/Users/tanner/projects/ansible.git/ansible/lib/ansible/plugins/strategies/linear.py", line 103, in _get_next_task_lockstep
    return _advance_selected_hosts(hosts, lowest_cur_block, PlayIterator.ITERATING_TASKS)
  File "/Volumes/Warrior1TB/Users/tanner/projects/ansible.git/ansible/lib/ansible/plugins/strategies/linear.py", line 85, in _advance_selected_hosts
    (s, t) = host_tasks[host.name]
TypeError: 'NoneType' object is not iterable
```

Several runs and the [host.domain.com] is different each time. Should I run it --forks=1 ?

And finally --list-tags still doesn't work.

```
$ ansible-playbook -i production-servers  --list-tags linux-servers.yml
playbook: linux-servers.yml
  PLAY:: tags count=0
```

**Comment by jimi-c** [comment] 2015-07-18 12:28
@basictheprogram that's an interesting failure. Could you please share the full playbook causing that, if possible? Feel free to redact whatever you need, and turn things into debug/command statements if needed.

Also, we're aware that we haven't implemented --list-tags yet, which is still on our list of features to port over to the new code base.

**Comment by basictheprogram** [comment] 2015-07-20 02:51
Playbook that demonstrates the problem is at https://github.com/basictheprogram/issue1320

If you look at [main.yml](https://github.com/basictheprogram/issue1320/blob/master/roles/tasks/main.yml) I have a play "- name: package update (apt)" in the main.yml but that play is also in the [debian.yml](https://github.com/basictheprogram/issue1320/blob/master/roles/tasks/debian.yml). I forgot and left the "- name: package update (apt)" in the main.yml during a debug session. 

If the "- name: package update (apt)" is in both the main.yml and debian.yml then I get the "TypeError: 'NoneType' object is not iterable" 

IF I remove the "- name: package update (apt)" from the main.yml the TypeError is no longer thrown but none of the plays in the debian.yml are not played.

## Sample Runs

---

Play --tags=apt and "- name: package update (apt)" in both the main.yml and debian.yml. Result TypeError thrown.

```
$ ansible-playbook -k -K --tags=apt -i issue11320-inventory issue11320.yml -vvv
<snip>
ok: [druid.real-time.com]
 [ERROR]: Unexpected Exception: 'NoneType' object is not iterable
the full traceback was:
Traceback (most recent call last):
  File "/Volumes/Warrior1TB/Users/tanner/projects/ansible.git/ansible/bin/ansible-playbook", line 77, in <module>
    sys.exit(cli.run())
  File "/Volumes/Warrior1TB/Users/tanner/projects/ansible.git/ansible/lib/ansible/cli/playbook.py", line 162, in run
    results = pbex.run()
  File "/Volumes/Warrior1TB/Users/tanner/projects/ansible.git/ansible/lib/ansible/executor/playbook_executor.py", line 139, in run
    result = self._tqm.run(play=play)
  File "/Volumes/Warrior1TB/Users/tanner/projects/ansible.git/ansible/lib/ansible/executor/task_queue_manager.py", line 258, in run
    return strategy.run(iterator, connection_info)
  File "/Volumes/Warrior1TB/Users/tanner/projects/ansible.git/ansible/lib/ansible/plugins/strategies/linear.py", line 141, in run
    host_tasks = self._get_next_task_lockstep(hosts_left, iterator)
  File "/Volumes/Warrior1TB/Users/tanner/projects/ansible.git/ansible/lib/ansible/plugins/strategies/linear.py", line 103, in _get_next_task_lockstep
    return _advance_selected_hosts(hosts, lowest_cur_block, PlayIterator.ITERATING_TASKS)
  File "/Volumes/Warrior1TB/Users/tanner/projects/ansible.git/ansible/lib/ansible/plugins/strategies/linear.py", line 85, in _advance_selected_hosts
    (s, t) = host_tasks[host.name]
TypeError: 'NoneType' object is not iterable
```

--tags=apt and "- name: package update (apt)" only in the debian.yml. Result none of the tags: apt plays in the debian.yml are played.

```
$ ansible-playbook -k -K --tags=apt -i issue11320-inventory issue11320.yml
SSH password:
SUDO password[defaults to SSH password]:
PLAY: ***************************************************************************
TASK [setup] ********************************************************************
<snip>
PLAY RECAP **********************************************************************
<snip>
```

And I get a different behavior when 1 of the hosts from the [inventory file](https://github.com/basictheprogram/issue1320/blob/master/issue11320-inventory) is offline. Just so happened one of the web servers was down for maintenance when I was testing this is the play and output.

```
$ ansible-playbook -k -K --tags=apt -i issue11320-inventory issue11320.yml
SSH password:
SUDO password[defaults to SSH password]:
PLAY: ***************************************************************************
TASK [setup] ********************************************************************
<snip>
fatal: [www.bright-futures.org]: FAILED! => {
    "failed": true,
    "msg": "ERROR! [Errno 51] Network is unreachable"
}
<snip>
NO MORE HOSTS LEFT **************************************************************
PLAY RECAP **********************************************************************
<snip>
```

Maybe the NO MORE HOSTS LEFT is proper output but I'm making note of it here.

```
$ ansible --version
ansible 2.0.0 (devel a8ba9cac3f) last updated 2015/07/19 20:29:00 (GMT -500)
  lib/ansible/modules/core: (detached HEAD 291fef3b34) last updated 2015/07/14 19:16:39 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD ff2386faf4) last updated 2015/07/14 19:16:39 (GMT -500)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/06/03 00:37:54 (GMT -500)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/06/03 00:37:58 (GMT -500)
  configured module search path = None
```

Did a lot of playing around. It seems like --tags defined in the roles main.yml work but --tags defined in another .yml file included by the main.yml do NOT get processed.

**Comment by basictheprogram** [comment] 2015-07-20 08:15
Using the same playbook at https://github.com/basictheprogram/issue1320 here are some other results.

Shouldn't ansible throw an error that it could not find missing.yml? It's not.

```
---
# tasks/main.yml

- include: missing.yml

- include: redhat.yml
  when: ansible_os_family == 'RedHat'
- include: debian.yml
  when: ansible_os_family == 'Debian'
- include: suse.yml
  when: ansible_os_family == 'Suse' or ansible_os_family == 'openSUSE'
- include: solaris.yml
  when: ansible_os_family == 'Solaris'
```

```
$ ansible-playbook -k -K --tags=apt -i issue11320-inventory issue11320.yml 
SSH password:
SUDO password[defaults to SSH password]:
PLAY: ***************************************************************************
TASK [setup] ********************************************************************
<snip>
PLAY RECAP **********************************************************************
<snip>
```

None of the include files exist. Shouldn't ansible throw errors about this missing includes? It's not.

```
---
# tasks/main.yml

- include: redhatX.yml
  when: ansible_os_family == 'RedHat'
- include: debianX.yml
  when: ansible_os_family == 'Debian'
- include: suseX.yml
  when: ansible_os_family == 'Suse' or ansible_os_family == 'openSUSE'
- include: solarisX.yml
  when: ansible_os_family == 'Solaris'
```

```
$ ansible-playbook -k -K --tags=apt -i issue11320-inventory issue11320.yml
SSH password:
SUDO password[defaults to SSH password]:
PLAY: ***************************************************************************
TASK [setup] ********************************************************************
<snip>
PLAY RECAP **********************************************************************
<snip>
```

Some debug plays in the main.yml with apt tags.  Debug info is displayed.

```
---
# tasks/main.yml

- include: redhat.yml
  when: ansible_os_family == 'RedHat'
- include: debian.yml
  when: ansible_os_family == 'Debian'
- include: suse.yml
  when: ansible_os_family == 'Suse' or ansible_os_family == 'openSUSE'
- include: solaris.yml
  when: ansible_os_family == 'Solaris'

- name: ansible_os_family
  debug: msg="Operating system {{ ansible_os_family }}"
  tags: apt
```

```
$ ansible-playbook -k -K --tags=apt -i issue11320-inventory issue11320.yml  --limit dns-1.real-time.com
SSH password:
SUDO password[defaults to SSH password]:
PLAY: ***************************************************************************
TASK [setup] ********************************************************************
ok: [dns-1.real-time.com]
TASK [issue11320 : issue11320 : ansible_os_family] ******************************
ok: [dns-1.real-time.com] => {
    "changed": false,
    "msg": "Operating system Debian"
}
PLAY RECAP **********************************************************************
dns-1.real-time.com        : ok=2    changed=0    unreachable=0    failed=0
```

Same debug play in debian.yml and it's not displayed.

```
---
# tasks/debian.yml

- name: ansible_os_family
  debug: msg="Operating system {{ ansible_os_family }}"
  tags: apt

# Only run "update_cache=yes" if the last one is more than 3600 seconds ago
- name: package update (apt)
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes
  always_run: yes
  tags: apt

# Update all packages to the latest version
- name: package upgrade (apt)
  apt: upgrade=dist
  sudo: yes
  always_run: yes
  tags: apt
```

```
$ ansible-playbook -k -K --tags=apt -i issue11320-inventory issue11320.yml  --limit dns-1.real-time.com
SSH password:
SUDO password[defaults to SSH password]:
PLAY: ***************************************************************************
TASK [setup] ********************************************************************
ok: [dns-1.real-time.com]
PLAY RECAP **********************************************************************
dns-1.real-time.com        : ok=1    changed=0    unreachable=0    failed=0
```

Make the play in the main.yml have a different tag, apt2, still ask for --tags=apt. Debug is not displayed.

```
---
# tasks/main.yml

- include: redhat.yml
  when: ansible_os_family == 'RedHat'
- include: debian.yml
  when: ansible_os_family == 'Debian'
- include: suse.yml
  when: ansible_os_family == 'Suse' or ansible_os_family == 'openSUSE'
- include: solaris.yml
  when: ansible_os_family == 'Solaris'

- name: ansible_os_family
  debug: msg="Operating system {{ ansible_os_family }}"
  tags: apt2
```

```
$ ansible-playbook -k -K --tags=apt -i issue11320-inventory issue11320.yml  --limit dns-1.real-time.com
SSH password:
SUDO password[defaults to SSH password]:
PLAY: ***************************************************************************
TASK [setup] ********************************************************************
ok: [dns-1.real-time.com]
PLAY RECAP **********************************************************************
dns-1.real-time.com        : ok=1    changed=0    unreachable=0    failed=0
```

Don't know if the above is helpful. 

Tried to follow the code with epdb and for the life of me I could not find the code that checks for "- include:" and processes the file. I thought it would be in playbook_include.py (or base.py) but could not find it.

**Comment by jimi-c** [comment] 2015-07-20 12:02
@basictheprogram the way I rewrote the include portions is to mark hosts as failed when the file was not found. The reason I did it this way was because of the change to make includes more dynamic, whereas before they were essentially preprocessor declarations (so throwing errors in the past was more appropriate). I'm guessing something else is breaking here so that it's not even getting to that.

Thanks for the example, I'll look into this today.

**Comment by jimi-c** [comment] 2015-07-20 20:26
@basictheprogram running the above, I get slightly different output:

<pre>
# ansible-playbook -vv test.yml --tags=apt 
Using /etc/ansible/ansible.cfg as config file
1 plays in test.yml
PLAY ****************************************************************************
TASK [setup] ********************************************************************
ok: [ubuntu1404]
TASK [issue11320 : issue11320 : package update (apt)] ***************************
ok: [ubuntu1404] => {"cache_update_time": 1437423611, "cache_updated": true, "changed": false}
PLAY RECAP **********************************************************************
ubuntu1404                 : ok=2    changed=0    unreachable=0    failed=0   
</pre>

So you can see it correctly ran the one task tagged, however it didn't run those that were in the include. The reason for this is simple - the include is not tagged so it was excluded. If I add the apt tag to the `debian.yml` include, it works as expected (I commented out the full dist upgrade, as it was time and bandwidth consuming...):

<pre>
# ansible-playbook -vv test.yml --tags=apt 
Using /etc/ansible/ansible.cfg as config file
1 plays in test.yml
PLAY ****************************************************************************
TASK [setup] ********************************************************************
ok: [ubuntu1404]
TASK [issue11320 : issue11320 : include] ****************************************
included: debian.yml for ubuntu1404
TASK [issue11320 : issue11320 : package update (apt)] ***************************
ok: [ubuntu1404] => {"cache_update_time": 1437423837, "cache_updated": true, "changed": false}
TASK [issue11320 : issue11320 : ansible_os_family] ******************************
ok: [ubuntu1404] => {
    "changed": false, 
    "msg": "Operating system Debian"
}
TASK [issue11320 : issue11320 : package update (apt)] ***************************
ok: [ubuntu1404] => {"cache_update_time": 1437423851, "cache_updated": true, "changed": false}
PLAY RECAP **********************************************************************
ubuntu1404                 : ok=5    changed=0    unreachable=0    failed=0   
</pre>

Based on the --version string in your original post above, it looks like you're using a slightly out of date pull. Could you please do a `git pull --rebase` and make sure you're running the latest version of devel?

**Comment by basictheprogram** [comment] 2015-07-20 20:29
Can you show me the test.yml? I do not know the syntax for tagging an include. 

Never mind. This seems to work.

``` yaml
---
# tasks/main.yml

- include: redhat.yml
  when: ansible_os_family == 'RedHat'
- include: debian.yml
  when: ansible_os_family == 'Debian'
  tags: apt
- include: suse.yml
  when: ansible_os_family == 'Suse' or ansible_os_family == 'openSUSE'
- include: solaris.yml
  when: ansible_os_family == 'Solaris'
```

Solution seems convoluted to me. It means I have to maintain tags in multiple places. Inside the included .yml files and in the main.yml file. Feels like a place for a lot of problems to occur.

```
$ ansible --version
ansible 2.0.0 (devel fadd8f23f1) last updated 2015/07/20 15:38:56 (GMT -500)
  lib/ansible/modules/core: (detached HEAD 291fef3b34) last updated 2015/07/14 19:16:39 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD ff2386faf4) last updated 2015/07/14 19:16:39 (GMT -500)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/06/03 00:37:54 (GMT -500)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/06/03 00:37:58 (GMT -500)
  configured module search path = None
```

And now a sample run. Result: This working as expected.

```
$ ansible-playbook -k -K --tags=apt -i issue11320-inventory issue11320.yml  --limit dns-1.real-time.com
SSH password:
SUDO password[defaults to SSH password]:
PLAY ****************************************************************************
TASK [setup] ********************************************************************
ok: [dns-1.real-time.com]
TASK [issue11320 : issue11320 : include] ****************************************
included: debian.yml for dns-1.real-time.com
TASK [issue11320 : issue11320 : package update (apt)] ***************************
ok: [dns-1.real-time.com]
TASK [issue11320 : issue11320 : package upgrade (apt)] **************************
ok: [dns-1.real-time.com]
TASK [issue11320 : issue11320 : ansible_os_family from debian.yml] **************
ok: [dns-1.real-time.com] => {
    "changed": false,
    "msg": "Operating system Debian"
}
PLAY RECAP **********************************************************************
dns-1.real-time.com        : ok=5    changed=0    unreachable=0    failed=0
```

**Comment by basictheprogram** [comment] 2015-07-20 20:54
Unexpected side effect now. Here is my debian.yml and I've added a new play with tags: apt2. Result: Even the apt2 tagged play get played.

``` yaml
---
# tasks/debian.yml

# Only run "update_cache=yes" if the last one is more than 3600 seconds ago
- name: package update (apt)
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes
  always_run: yes
  tags: apt

# Update all packages to the latest version
- name: package upgrade (apt)
  apt: upgrade=dist
  sudo: yes
  always_run: yes
  tags: apt

- name: ansible_os_family from debian.yml apt
  debug: msg="Operating system {{ ansible_os_family }}"
  tags: apt

- name: ansible_os_family from debian.yml apt2
  debug: msg="Operating system {{ ansible_os_family }}"
  tags: apt2
```

### Example run

```
$ ansible-playbook -k -K --tags=apt -i issue11320-inventory issue11320.yml  --limit dns-1.real-time.com
SSH password:
SUDO password[defaults to SSH password]:
PLAY ****************************************************************************
TASK [setup] ********************************************************************
ok: [dns-1.real-time.com]
TASK [issue11320 : issue11320 : include] ****************************************
included: debian.yml for dns-1.real-time.com
TASK [issue11320 : issue11320 : package update (apt)] ***************************
ok: [dns-1.real-time.com]
TASK [issue11320 : issue11320 : package upgrade (apt)] **************************
ok: [dns-1.real-time.com]
TASK [issue11320 : issue11320 : ansible_os_family from debian.yml apt] **********
ok: [dns-1.real-time.com] => {
    "changed": false,
    "msg": "Operating system Debian"
}
TASK [issue11320 : issue11320 : ansible_os_family from debian.yml apt2] *********
ok: [dns-1.real-time.com] => {
    "changed": false,
    "msg": "Operating system Debian"
}
PLAY RECAP **********************************************************************
dns-1.real-time.com        : ok=6    changed=0    unreachable=0    failed=0
```

So it looks like tagging the include does process the include file but then per play tags are not being processed or honored?

**Comment by jimi-c** [comment] 2015-07-21 01:06
You don't have to add the tags everywhere, if you just add it on the include it will apply to all tasks in the included file.

**Comment by basictheprogram** [comment] 2015-07-21 02:25
zowie, I guess I  have a different design philosophy for my plays. I'll rework them around the tag on the include vs the tag on the play. Thanks.

**Comment by jimi-c** [comment] 2015-07-21 16:30
@basictheprogram sorry, it's not really about a philosophy. In 1.9.x and lower, includes were pre-processor statements, meaning they were always expanded inline and the associated tasks basically had any tags/conditionals applied to them.

Now in devel/2.0, includes are just regular tasks which are not evaluated until it is their turn in the list of execution. The consequence of this is that tags on things inside those included files won't be evaluated if the include task is skipped. As I stated above, the benefit is that the tag applied to the include is still applied to all tasks in that file, so it is actually nicer to tag just the include rather than each task individually.

I am going to hold this issue open for now, to determine if we should always run include tasks regardless of tags, to make sure we preserve backwards compatibility for playbooks like yours.

**Comment by jimi-c** [comment] 2015-07-21 16:38
# Closing This Ticket

Ok, the above commit should make this behave as it did in 1.9.x and before.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed** 2015-07-21 16:38 UTC
Labels: needs_info, P2, bug
