### ISSUE TITLE
Python module not working

### ISSUE THREAD

**Issue by Drabble** [ansible/ansible#2523] opened 2013-03-28 14:12 UTC
Hi,
I began working with ansible this morning, and I need to run a module in Python. 
But it doesn't work, I created this module named "test":
# !/usr/bin/python
# Antoine Drabble
#28.03.2013

DOCUMENTATION = '''
Test module in Python
'''

def main():
    cmd = "test"

main()

And when I run it with this command:
-ansible all -m test

I get this error:
chx-training-01 | FAILED >> {
    "failed": true,
    "msg": "",
    "parsed": false
}

Thanks in advance !

**Comment by lwade** [comment] 2013-03-28 14:43
You might want to consider taking this to the mailing list.  I believe Ansible considers your module action/task to have failed, since there is no return.  You should look at this guide http://ansible.cc/docs/moduledev.html

**Comment by Drabble** [comment] 2013-03-28 14:53
Thank you for the fast answer !

I tried a return but it doesn't work :/

I copy/pasted this code:
#!/usr/bin/python

import datetime
import json

date = str(datetime.datetime.now())
print json.dumps({
    "time" : date
})

And it also doesn't work:

chx-training-01 | FAILED >> {
    "failed": true,
    "msg": "  File \"/root/.ansible/tmp/ansible-1364482349.33-22858180162885/test\", line 9\r\n    \r\n                     ^\r\nSyntaxError: invalid syntax\r\n",
    "parsed": false
}

**Comment by mpdehaan** [comment] 2013-03-28 17:56
I would suggest debugging your module with ./hacking/test-module until you
get it operational with that script.

**Comment by mpdehaan** [comment] 2013-03-28 17:56
this is Q&A and not a bug, so moving this to the mailing list.

**Closed as completed by mpdehaan** 2013-03-28 17:56 UTC
