### ISSUE TITLE
Role variable being ignored in some roles

### ISSUE THREAD

**Issue by kuza55** [ansible/ansible#16866] opened 2016-07-29 02:48 UTC
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Ansible running on Ubuntu on Windows 10
Managing Ubuntu 14.0.4
##### SUMMARY

In some cases, I variables passed into roles are ignored and the defaults are used.
##### STEPS TO REPRODUCE

I was trying to use this role from galaxy: https://github.com/nickpack/ansible-role-android-sdk

When I used the role pulled from galaxy, passing the android_sdk_tools_to_install variables to the role has no impact and the default is used:

```

  vars:
    android_sdk_tools:
      - build-tools-23.0.2
      - build-tools-19.1.0
      - platform-tools
      - tools
      - extra-android-support
      - extra-google-m2repository
      - extra-android-m2repository
      - sys-img-armeabi-v7a-google_apis-19
      - sys-img-x86-google_apis-19

  roles:
    - jpnewman.java
    - { role: nickp666.android-sdk, android_sdk_tools_to_install: "{{android_sdk_tools}}" }
#    - { role: ansible-role-android-sdk, android_sdk_tools_to_install: "{{android_sdk_tools}}" }

```

I was able to work around this issue by cloning that repo into my roles folder and then adding some debug tasks, though I tried commenting out those debug tasks and it still works, so I'm really not sure where the core issue is. I passed the variable in the same way (as you can see in the commented line above). The Galaxy role is stsill failing for me though.
##### EXPECTED RESULTS

I expected the role variable passed in the role to be used and my list of tools to be installed.
##### ACTUAL RESULTS

The role only installs the default sdk tool list.

[EDIT]: May be related to https://github.com/ansible/ansible/issues/16775 ?

**Comment by jimi-c** [comment] 2016-09-22 15:39
I am unable to reproduce this, and I have tested 2.1.0, 2.1.1 and both the stable-2.1 and devel branch. I have used the role verbatum as well as your example playbook. As a result, I will go ahead and close this now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2016-09-22 15:39 UTC
Labels: P2, affects_2.1, bug
