### ISSUE TITLE
Feature: calling roles as tasks and post

### ISSUE THREAD

**Issue by bjne** [ansible/ansible#15247] opened 2016-04-02 00:03 UTC
The ability to have role dependencies is nice, but it would be even better to be able to
call a role as a task with parameters.  It would still be ok having to define the role as a
dependency in meta, but perhaps with a run tag, for example:

meta/main.yml

```
dependencies:
  -  role: pre
     arg: bar 
  -  role: bar
     auto: false
  -  role: finalize
     auto: post
```

the default is then, as now, auto: pre
and then in tasks/main.yml

```
- name: do something that I do alot from different places
  role: bar arg=baz
```

**Comment by bcoca** [comment] 2016-04-02 00:36
marking as dupe of this proposal https://github.com/ansible/proposals/pull/4

**Closed as completed by bcoca** 2016-04-02 00:36 UTC

**Comment by bjne** [comment] 2016-04-02 23:26
This is not a duplicate, it is a completely different approach.
