### ISSUE TITLE
ansible-pull does not read config file from working directory

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#14370] opened 2016-02-08 14:21 UTC
I'm running ansible-pull v2.0.0.2 as follows:

> ansible-pull --accept-host-key --url git@[git_repo_url] --checkout release ./ansible/inventory/localhosts --verbose ./ansible/playbooks/aplaybook.yml

And getting this even though there is a _ansible.cfg_ file in the working directory:

> No config file found; using defaults

This worked in v1.9. 

If I run _ansible-pull_ prefixed by _ANSIBLE_CONFIG=[path of working dir + ansible.cfg]_ it works but there is no way I can see to determine that path upfront.

**Comment by bcoca** [comment] 2016-02-08 14:55
closing as dupe of #13688, fix will be in next releases

**Closed as completed by bcoca** 2016-02-08 14:55 UTC
Labels: P2, bug
