### ISSUE TITLE
Docker - dns argument not working

### ISSUE THREAD

**Issue by huguesalary** [ansible/ansible#7360] opened 2014-05-11 04:48 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

Ansible 1.7 (but had the same issue with 1.6.1 and 1.6)
##### Environment:

Running ansible from Mac OS
Managing Debian 
##### Summary:

With the docker module, using the `dns` argument does not add the dns to the container. (nothing's added to the container's /etc/resolv.conf)
##### Steps To Reproduce:

```
    - name: Create docker proxy
      docker: image=ubuntu name=test hostname=test count=1 privileged=yes dns=127.0.0.1 command=/bin/bash

```
##### Expected Results:

```
ssh containers_ip
cat /etc/resolv.conf
```

`nameserver 127.0.0.1` should appear at the top of the file
##### Actual Results:

`nameserver 127.0.0.1` does not appear

**Comment by jimi-c** [comment] 2014-08-09 02:06
# Cannot Reproduce

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us. 

Testing this on the version you have specified, we cannot reproduce this problem. Our reasons and evidence for this are:
- Using your example playbook, with the current devel branch and release1.6.4, and with `docker-py (0.3.2)` installed, the resolve.conf entry is created correctly. This indicates that the issue may be the version of docker-py that is installed, so updating that may resolve the issue for you.

As such, we are most likely going to close this ticket.  Should you disagree with this conclusion, you may also wish to join one of our two mailing lists which is very active:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Closed as completed by jimi-c** 2014-08-09 02:06 UTC
Labels: cloud, docker, bug
