### ISSUE TITLE
copy module failed to work for file with "raw" string in in

### ISSUE THREAD

**Issue by djatlantic** [ansible/ansible#4377] opened 2013-10-04 23:39 UTC
Hi,

There is a lengthy discussion in Google Groups and here is the link.

https://groups.google.com/forum/#!topic/ansible-project/egViP_1sGkw

Steven.

**Comment by mpdehaan** [comment] 2013-10-04 23:43
BTW, please post the description in the bug reports -- forum can be down independently and requires a click, plus it's also a long thread.

Simple steps to reproduce and output is sufficient.

Thanks!

**Comment by mpdehaan** [comment] 2013-10-04 23:44
note to self -- looks like this bug is only triggered if the MD5 already matches, i.e the second time 

see

https://github.com/ansible/ansible/blob/devel/lib/ansible/runner/action_plugins/copy.py

Line 171

**Comment by mpdehaan** [comment] 2013-10-06 14:37
This is now fixed on the development branch.  Thanks!

**Closed as completed by mpdehaan** 2013-10-06 14:37 UTC
Labels: bug
