### ISSUE TITLE
role parameters replaced

### ISSUE THREAD

**Issue by hryamzik** [ansible/ansible#15823] opened 2016-05-11 14:53 UTC
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
 2.0.1.0
```
##### CONFIGURATION

```
[defaults]
retry_files_save_path = ./retry/
roles_path = ./roles:~/ansible/roles
ansible_managed = Ansible managed: file modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
nocows = 1
callback_whitelist = timer
sudo_flags = -E
stdout_callback = skippy
display_skipped_hosts = False
```
##### OS / ENVIRONMENT

Mac OS => Linux
##### SUMMARY

Role gets wrong parameter values
##### STEPS TO REPRODUCE

```
playbook.yml
a
├── defaults
│   └── main.yml
└── tasks
    └── main.yml
b
└── meta
    └── main.yml
```

playbook.yml:

``` yml
- hosts: localhost
  become: no
  gather_facts: no
  roles:
      - role: b
      - role: a
```

a/defaults/main.yml:

``` yml
var: 1
```

a/tasks/main.yml:

``` yml
- debug: msg="var={{ var }}"
```

b/meta/main.yml:

``` yml
dependencies:
    - role: a
      var: 3
```
##### EXPECTED RESULTS

```
TASK [a : debug] ***************************************************************
ok: [localhost] => {
    "msg": "var=3"
}

TASK [a : debug] ***************************************************************
ok: [localhost] => {
    "msg": "var=1"
}
```
##### ACTUAL RESULTS

```
TASK [a : debug] ***************************************************************
ok: [localhost] => {
    "msg": "var=3"
}

TASK [a : debug] ***************************************************************
ok: [localhost] => {
    "msg": "var=3"
}
```

**Comment by jctanner** [comment] 2016-06-09 13:44
Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

I reproduced the issue with ansible 2.0.1 and then found it was resolved in 2.0.2 and 2.1.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Closed as completed by jctanner** 2016-06-09 13:44 UTC
Labels: P2, bug
