### ISSUE TITLE
Unknown error connecting to vCenter or ESXi API

### ISSUE THREAD

**Issue by brunocalogero** [ansible/ansible#32477] opened 2017-11-02 01:40 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
- vmware_vm_facts (under cloud/vmware)

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /Users/bcaloger/Desktop/test_ansible/ansible.cfg
  configured module search path = [u'/Users/bcaloger/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible-2.4.0.0-py2.7.egg/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### SUMMARY

 I’ve been having some issues using the vmware_vm_facts Ansible command, it seems like a login issue at first but I’m not sure at all, I triple checked the credentials with and without quotation marks.. the username includes a "\" symbol which might pose some issues but unclear at this point. 
The playbook connects properly to the windows host that runs the vmare vsphere software.. I also do not validate certs to avoid ssl errors as I generally do.  

##### STEPS TO REPRODUCE

``` 
ansible-playbook test_ans.yml -i ansible-hosts -vvv
```

```
---
- name: testing
  hosts: windows_jumphost_1
  tasks:
    - ping:
    - name: Gather all registered virtual machines
      vmware_vm_facts:
         hostname: "svl-fab2.thingy.com"
         username: "CISCO\username"
         password: "password"
         validate_certs: False
      register: vmfacts

    - debug:
      var: vmfacts.virtual_machines
```

##### EXPECTED RESULTS

I would expect a list with all the registered VMs on svl-fab2.thingy.com

##### ACTUAL RESULTS

Running with extra verbosity I instead obtain the following full traceback: 
```
The full traceback is:
  File "/var/folders/ht/bgw3x1bs6mbfp55kc53wfd3r0000gp/T/ansible_PjWSox/ansible_modlib.zip/ansible/module_utils/vmware.py", line 403, in connect_to_api
    service_instance = connect.SmartConnect(host=hostname, user=username, pwd=password, sslContext=ssl_context)
  File "/Library/Python/2.7/site-packages/pyVim/connect.py", line 856, in SmartConnect
    mechanism=mechanism)
  File "/Library/Python/2.7/site-packages/pyVim/connect.py", line 266, in Connect
    keyFile, certFile, thumbprint, sslContext, connectionPoolTimeout)
  File "/Library/Python/2.7/site-packages/pyVim/connect.py", line 390, in __Login
    x = content.sessionManager.Login(user, pwd, None)
  File "/Library/Python/2.7/site-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/Library/Python/2.7/site-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/Library/Python/2.7/site-packages/pyVmomi/SoapAdapter.py", line 1366, in InvokeMethod
    raise obj # pylint: disable-msg=E0702

fatal: [win-jmp-1]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "hostname": "svl-fab2.thingy.com", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "username": "CISCO\bcaloger", 
            "validate_certs": false
        }
    }, 
    "msg": "Unknown error connecting to vCenter or ESXi API at svl-fab2.thingy.com: (vmodl.fault.InvalidRequest) {\n   dynamicType = <unset>,\n   dynamicProperty = (vmodl.DynamicProperty) [],\n   msg = '\\nError returned by expat parser: not well-formed (invalid token)\\n\\nwhile parsing serialized value of type string\\nat line 3, column 90\\n\\nwhile parsing call information for method Login\\nat line 3, column 14\\n\\nwhile parsing SOAP body\\nat line 3, column 0\\n\\nwhile parsing SOAP envelope\\nat line 2, column 0\\n\\nwhile parsing HTTP request for method login\\non object of type vim.SessionManager\\nat line 1, column 0',\n   faultCause = <unset>,\n   faultMessage = (vmodl.LocalizableMessage) []\n}"
}
```

**Comment by brunocalogero** [comment] 2017-11-02 02:02
for some reason it didn't display what I wrote for OS environment: 

Running ansible-playbook on MAC OS Sierra 10.12.6, and host is a windows jump server that has vmware vsphere client installed inside of it

**Comment by Akasurde** [comment] 2017-11-02 07:06
@brunocalogero Thanks for reporting this issue. Could you please also check the version `pyvmomi` library ?

**Comment by Akasurde** [comment] 2017-11-02 07:17
@brunocalogero There is an existing issue in `pyvmomi` related to this stack trace - https://github.com/vmware/pyvmomi/issues/586

**Comment by brunocalogero** [comment] 2017-11-02 17:34
running the following: pyvmomi==6.5.0.2017.5.post1, i'll try using that single quote advice and report back

**Comment by brunocalogero** [comment] 2017-11-02 20:56
update: still same issue, checked on the windows host the version of **vsphere client is 6.0.0** although there are multiple other versions installed on there and I'm not sure which one is selected by default but hopefully the latest version is.. Hence I guess it should be working with pyvmomi 6.5 which is installed on my local machine ?

**Comment by Akasurde** [comment] 2017-11-03 15:58
@brunocalogero I suspect due to multiple other `pyvmomi` versions installed, this could be the error. Could you please try with only latest version ? Also, what is username used in pb ?

**Comment by Akasurde** [comment] 2017-11-03 16:11
Do you have any non-ascii characters in your username ?

**Comment by brunocalogero** [comment] 2017-11-03 17:24
the complete username is "CISCO\bcaloger" so there is a " \ " character which might be an issue.. I've tried also using single quotes or no quotes at all but it did not solve the issue. for the pyvmomi lib should I just run a pyenv and have the latest pyvmomi or would that still be an issue and be in conflict with other versions ? last time i checked I only had one version of pyvmomi installed locally.. thanks !!

**Comment by jctanner** [comment] 2017-11-08 14:32
!component =lib/ansible/modules/cloud/vmware/vmware_vm_facts.py
!component =lib/ansible/module_utils/vmware.py

**Comment by brunocalogero** [comment] 2017-11-08 18:35
@jctanner what are you implying I should do ? haha

**Comment by brunocalogero** [comment] 2017-11-08 18:41
@jctanner what are you implying I should do ? haha

**Comment by jctanner** [comment] 2017-11-08 22:53
@brunocalogero nothing, just clarifying the relevant files for the bot.

**Comment by brunocalogero** [comment] 2017-11-10 21:42
any updates ? :/

**Comment by Akasurde** [comment] 2017-11-11 10:08
@brunocalogero The above traceback is thrown by `pyVmomi`. I am not able to reproduce this error on my setup. I agree that Ansible module should handle this traceback. 

Could you please try using "CISCO@bcaloger" instead of "CISCO\bcaloger" ? I am suspecting this as '\b' is translated as '\x08' in Python and internally going to ESXi server.

```
>>> a = "CISCO\bcaloger"
>>> a
'CISCO\x08caloger'
```

**Comment by brunocalogero** [comment] 2017-11-11 22:37
Very good catch akasurde, will give it a go :)

**Comment by brunocalogero** [comment] 2017-11-15 01:46
ok so it turns out I can use "bcaloger@cisco" as a username.. so I used it as a username but now I'm dealing with a new error, this is what was displayed as I ran with -vvvv flag and setup a logger, getting a `NoneType' object has no attribute 'hardware'` error now, and the log doesn;t tell me much at all..: 

```2017-11-14 17:42:16,610 p=33430 u=bcaloger |  TASK [Gather all registered virtual machines] **************************************************************************************************************************************************************
2017-11-14 17:42:16,610 p=33430 u=bcaloger |  task path: /Users/bcaloger/Desktop/test_ansible/test_ans.yml:6
2017-11-14 17:42:16,829 p=33430 u=bcaloger |  Using module file /Library/Python/2.7/site-packages/ansible-2.4.0.0-py2.7.egg/ansible/modules/cloud/vmware/vmware_vm_facts.py
2017-11-14 17:42:43,100 p=33430 u=bcaloger |  The full traceback is:
  File "/var/folders/ht/bgw3x1bs6mbfp55kc53wfd3r0000gp/T/ansible_Hd5hm5/ansible_module_vmware_vm_facts.py", line 103, in main
    _virtual_machines = get_all_virtual_machines(content)
  File "/var/folders/ht/bgw3x1bs6mbfp55kc53wfd3r0000gp/T/ansible_Hd5hm5/ansible_module_vmware_vm_facts.py", line 75, in get_all_virtual_machines
    for dev in vm.config.hardware.device:

2017-11-14 17:42:43,101 p=33430 u=bcaloger |  fatal: [win-jmp-1]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "hostname": "svl-fab2.thingy.com", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "username": "bcaloger@cisco", 
            "validate_certs": false
        }
    }, 
    "msg": "'NoneType' object has no attribute 'hardware'"
}
2017-11-14 17:42:43,102 p=33430 u=bcaloger |  	to retry, use: --limit @/Users/bcaloger/Desktop/test_ansible/test_ans.retry

2017-11-14 17:42:43,103 p=33430 u=bcaloger |  PLAY RECAP *************************************************************************************************************************************************************************************************
2017-11-14 17:42:43,103 p=33430 u=bcaloger |  win-jmp-1     ```

**Comment by Akasurde** [comment] 2017-11-15 09:04
@brunocalogero Cool, that trick worked for you. Could you please check above PR for your "AttributeError" for last comment ?

**Comment by brunocalogero** [comment] 2017-11-15 20:42
hey @Akasurde should I pull 2.5devel in that case and how can I see when the PR will be merged sorry I'm a little new to this part of github

**Comment by Akasurde** [comment] 2017-11-16 02:30
@brunocalogero Generally, PR needs to have two 'shipit' tags to get merged. If it is working for you then you can add 'shipit' to PR. Once we have two of them, I will merge it.

Yes. To test above changes you need to pull latest devel (i.e. 2.5) branch.

**Comment by Akasurde** [comment] 2017-11-16 02:30
resolved_by_pr #32924

**Closed as completed** 2017-11-17 06:02 UTC
Labels: cloud, vmware, module, affects_2.4, support:core, bug
