### ISSUE TITLE
Module unarchive doesn't work on *BSD using tar

### ISSUE THREAD

**Issue by sstreiner** [ansible/ansible#16276] opened 2016-06-14 14:21 UTC
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

2.1
##### OS / ENVIRONMENT

OpenBSD 5.9
##### SUMMARY

Using unarchvie for tar-archives on OpenBSD (and possibly FreeBSD/NetBSD) causes an error (Unexpected error when accessing exploded file: [Errno 2] No such file or directory).
From looking at the ansible 2.0 output it looks like ansible would make use of the tar argument --diff. OpenBSD and FreeBSD doesn't have an --diff, -d, --compare option for tar.

It runs fine against any Linux host (tested with CentOS 6.8).
##### STEPS TO REPRODUCE

run unarchive with a tar.gz against OpenBSD 5.9

e.g.
- name: unarchive mmonit
  unarchive:
    copy: no  
    creates: /usr/local/mmonit-3.5.1
    dest: /usr/local
    src: https://mmonit.com/dist/mmonit-3.5.1-openbsd-x64.tar.gz
##### EXPECTED RESULTS

Command works
##### ACTUAL RESULTS

Command failed.

fatal: [xxx]: FAILED! => {"changed": false, "failed": true, "msg": "Unexpected error when accessing exploded file: [Errno 2] No such file or directory: '/usr/local/mmonit-3.5.1'", "stat": {"exists": false}}
        to retry, use: --limit @site.retry

**Comment by sstreiner** [comment] 2016-06-14 18:33
As a workaround, I've installed gtar and it worked like charm...
Maybe add gtar as a dependency to Ports?

**Comment by ghost** [comment] 2016-06-15 09:52
This has stung me too, on FreeBSD 10.3.

I ended up using shell: tar zxvf.....

And putting up with the warning that Ansible doesn't like it.

**Comment by sstreiner** [comment] 2016-06-15 16:07
Install gtar either from pkg or from ports.
gtar is listed as dependency in the unarchive module. It's not my favorite solution, but it works.

**Comment by nitzmahone** [comment] 2016-06-16 16:56
This should probably be closed and reopened in https://github.com/ansible/ansible-modules-core/ as the bits in question live there.

**Comment by nitzmahone** [comment] 2016-06-16 17:56
Also duplicate of https://github.com/ansible/ansible-modules-core/issues/3952 - closing this one (since 3952 is already in the correct repo)

**Closed as completed by nitzmahone** 2016-06-16 17:56 UTC
Labels: m:unarchive, bug, bsd

**Comment by vbotka** [comment] 2017-10-09 11:51
ansible/ansible-modules-core#3952 is reported on OSX. OSX solution doesn't necessarily have to fit BSD, at least one can't be sure, I think. I propose to consider and open this one for BSD.

FYI, I reported about BSD today at
https://github.com/ansible/ansible-modules-core/issues/3952
