### ISSUE TITLE
ansible_failed_task is undefined 

### ISSUE THREAD

**Issue by zaskan** [ansible/ansible#64795] opened 2019-11-13 16:57 UTC
##### SUMMARY

Ansible returns VARIABLE IS NOT DEFINED! when we use ansible_failed_task and ansible_failed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible_failed_task
ansible_failed_result

##### ANSIBLE VERSION

```
2.9.0
```

##### CONFIGURATION

```
ansible 2.9.0
  config file = None
  configured module search path = ['/home/zaskan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Aug  7 2019, 17:28:10) [GCC 4.8.5 20150623 (Re
```

##### OS / ENVIRONMENT

CentOS Linux release 7.7.1908 (Core)

##### STEPS TO REPRODUCE

This is the correct behavior extracted from previous version execution

```
- hosts: localhost
  gather_facts: no
  vars:
    ansible_connection: local
    data:
      - name: a1
      - name: a2
      - name: a3

  tasks:
    - name: Block START
      block:

      - name: LOOP TASK
        debug:
          msg: "The element is: {{data[1].name}}"
        failed_when: data[1].name == 'a2'

      rescue:
        - name: Set error info report
          set_fact:
            error_info:
              title: "{{ansible_failed_task}}"
              details: "{{ansible_failed_result}}"
          ignore_errors: true

        - name: print ansible_failed_task
          debug:
            var: ansible_failed_task

        - name: print ansible_failed_result
          debug:
            var: ansible_failed_result
```

##### EXPECTED RESULTS

```
PLAY [localhost] *****************************************************************************************************************************************************************

TASK [LOOP TASK] *****************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {
    "msg": "The element is: a2"
}

TASK [Set error info report] *****************************************************************************************************************************************************
ok: [localhost]

TASK [print ansible_failed_task] *************************************************************************************************************************************************
ok: [localhost] => {
    "ansible_failed_task": {
        "action": "debug", 
        "any_errors_fatal": false, 
        "args": {
            "msg": "The element is: a2"
        }, 
        "async": 0, 
        "async_val": 0, 
        "become": false, 
        "become_flags": null, 
        "become_method": "sudo", 
        "become_user": null, 
        "changed_when": [], 
        "check_mode": false, 
        "collections": null, 
        "connection": "smart", 
        "debugger": null, 
        "delay": 5, 
        "delegate_facts": null, 
        "delegate_to": null, 
        "diff": false, 
        "environment": [
            {}
        ], 
        "failed_when": [
            "data[1].name == 'a2'"
        ], 
        "finalized": false, 
        "ignore_errors": null, 
        "ignore_unreachable": null, 
        "loop": null, 
        "loop_control": null, 
        "loop_with": null, 
        "module_defaults": [], 
        "name": "LOOP TASK", 
        "no_log": null, 
        "notify": null, 
        "parent": {
            "any_errors_fatal": false, 
            "become": false, 
            "become_flags": null, 
            "become_method": "sudo", 
            "become_user": null, 
            "check_mode": false, 
            "collections": null, 
            "connection": "smart", 
            "debugger": null, 
            "delegate_facts": null, 
            "delegate_to": null, 
            "dep_chain": null, 
            "diff": false, 
            "environment": null, 
            "eor": false, 
            "ignore_errors": null, 
            "ignore_unreachable": null, 
            "module_defaults": null, 
            "name": "Block START", 
            "no_log": null, 
            "port": null, 
            "remote_user": null, 
            "run_once": null, 
            "tags": [], 
            "vars": {}, 
            "when": []
        }, 
        "parent_type": "Block", 
        "poll": 10, 
        "port": null, 
        "register": null, 
        "remote_user": null, 
        "retries": 3, 
        "run_once": null, 
        "squashed": false, 
        "tags": [], 
        "until": [], 
        "uuid": "5254005d-975a-8e3d-f8a1-00000000000b", 
        "vars": {}, 
        "when": []
    }
}

TASK [print ansible_failed_result] ***********************************************************************************************************************************************
ok: [localhost] => {
    "ansible_failed_result": {
        "changed": false, 
        "failed": true, 
        "failed_when_result": true, 
        "msg": "The element is: a2"
    }
}

PLAY RECAP ***********************************************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=1    ignored=0   

```
##### ACTUAL RESULTS

Playbook returns `VARIABLE IS NOT DEFINED` in the ansible_failed_task and ansible_failed_result calls

```
PLAY [localhost] *****************************************************************************************************************************************************************

TASK [LOOP TASK] *****************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {
    "msg": "The element is: a2"
}

TASK [Set error info report] *****************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'ansible_failed_task' is undefined\n\nThe error appears to be in '/home/zaskan/playbook.yml': line 20, column 11, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n      rescue:\n        - name: Set error info report\n          ^ here\n"}
...ignoring

TASK [print ansible_failed_task] *************************************************************************************************************************************************
ok: [localhost] => {
    "ansible_failed_task": "VARIABLE IS NOT DEFINED!"
}

TASK [print ansible_failed_result] ***********************************************************************************************************************************************
ok: [localhost] => {
    "ansible_failed_result": "VARIABLE IS NOT DEFINED!"
}

PLAY RECAP ***********************************************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=1    ignored=1   
```

**Comment by sivel** [comment] 2019-11-13 16:58
Duplicate of https://github.com/ansible/ansible/issues/64789

**Closed as completed by sivel** 2019-11-13 16:58 UTC
