### ISSUE TITLE
Don't throw error stopping/disabling unknown service

### ISSUE THREAD

**Issue by phemmer** [ansible/ansible#16134] opened 2016-06-05 00:34 UTC
##### ISSUE TYPE
- Bug Report
- Feature Idea

(regression from 1.9.4, but not sure if deliberate)
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /Users/phemmer/git/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
[defaults]
retry_files_enabled = False
pipelining=True
```
##### OS / ENVIRONMENT

Client: OS-X
Server: CentOS/7
##### SUMMARY

When attempting to disable or stop a non-existent service, an error is thrown. This is a regression from 1.9.
This should not throw an error as ansible is a declarative language. The task is an instruction to make sure a service is stopped or disabled. If the service does not exist, it is quite obviously stopped and disabled.

See also: #13259 ansible/ansible-modules-core#2724 ansible/ansible-modules-core#751 ansible/ansible-modules-core#2149 ansible/ansible-modules-core#2816 

This is not the same as many of those above referenced issues, as most of them are about adding a `must_exist` parameter. This request is to automatically enable the behavior `must_exist: false` would provide if the action is to stop or disable the service.
##### STEPS TO REPRODUCE

```
- service: name=doesnotexist state=stopped enabled=false
```
##### EXPECTED RESULTS

Not error
##### ACTUAL RESULTS

```
FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "systemd could not find the requested service \"'doesnotexist'\": "
}
```

**Comment by bcoca** [comment] 2017-02-07 16:47
closing as dupe of #13259

**Closed as completed by bcoca** 2017-02-07 16:47 UTC
Labels: affects_2.1, bug, feature

**Comment by phemmer** [comment] 2017-02-07 16:49
I wouldn't classify this as a dup. Related sure. But I commented this in the description:

> This is not the same as many of those above referenced issues, as most of them are about adding a must_exist parameter. This request is to automatically enable the behavior must_exist: false would provide if the action is to stop or disable the service.
