### ISSUE TITLE
delegate_facts is ignored when run_once is set

### ISSUE THREAD

**Issue by turb** [ansible/ansible#22604] opened 2017-03-14 13:25 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
core, setup

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

Ubuntu Yakkety Yack for Ansible
Debian stable for nodes

##### SUMMARY

We have to load facts from nodes that have been excluded by `--limit`.

The way to achieve this is  `setup:`, with `delegate_to` in conjunction with `delegate_facts` set to `True`. Everything works fine. Facts are attributed to the delegated host.

However, if the number of nodes is n, we have n^2 setups, which takes some time (while Ansible taking 100% CPU).

The solution we wanted to test: use `run_once` to have each excluded node being setuped only once.

Problem: `delegate_facts` seems now ignored, and facts from the delegated host are now transferred to the one selected by `run_once`.

##### STEPS TO REPRODUCE

```yaml
- hosts: all # Two hosts here, orc1 and orc2
  tasks:
  - name: Additional setup 
    setup:
    delegate_to: "{{item}}"
    delegate_facts: True
    with_items: "{{groups['all']}}"
    run_once: True
  - debug: msg="{{ ansible_hostname }}"
```

(in our real useful case the additional setup should carry `when: "item not in play_hosts"` and we would have more hosts, but it is not the point here)

##### EXPECTED RESULTS

```
PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [orc2]
ok: [orc1]

TASK [Additional setup] *******************************************************************
ok: [orc1 -> orc1] => (item=orc1)
ok: [orc1 -> orc2] => (item=orc2)

TASK [debug] *******************************************************************
ok: [orc1] => {
    "msg": "orc1"
}
ok: [orc2] => {
    "msg": "orc2"
}

PLAY RECAP *********************************************************************
orc1                       : ok=3    changed=0    unreachable=0    failed=0
orc2                       : ok=2    changed=0    unreachable=0    failed=0

```

##### ACTUAL RESULTS

```
PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [orc1]
ok: [orc2]

TASK [Additional setup] ********************************************************
ok: [orc1 -> orc1] => (item=orc1)
ok: [orc1 -> orc2] => (item=orc2)

TASK [debug] *******************************************************************
ok: [orc1] => {
    "msg": "orc2"
}
ok: [orc2] => {
    "msg": "orc2"
}

PLAY RECAP *********************************************************************
orc1                       : ok=3    changed=0    unreachable=0    failed=0
orc2                       : ok=2    changed=0    unreachable=0    failed=0
```

If we remove `run_once: True`, "Additional setup" is run 4 times, and the `debug` is correct.

If we remove next `delegate_facts: True`, "Additionnal setup is still run 4 times and we have the same `debug` result as the faulty output.

The actual result with -vvv:
```
Using /etc/ansible/ansible.cfg as config file

PLAYBOOK: play.yml *************************************************************
1 plays in play.yml

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/system/setup.py
<orc2> ESTABLISH SSH CONNECTION FOR USER: root
<orc2> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/sveyrie/.ansible/cp/ansible-ssh-%h-%p-%r orc2 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1489496280.84-248745293629877 `" && echo ansible-tmp-1489496280.84-248745293629877="` echo $HOME/.ansible/tmp/ansible-tmp-1489496280.84-248745293629877 `" ) && sleep 0'"'"''
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/system/setup.py
<orc1> ESTABLISH SSH CONNECTION FOR USER: root
<orc1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/sveyrie/.ansible/cp/ansible-ssh-%h-%p-%r orc1 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1489496280.85-18939121102418 `" && echo ansible-tmp-1489496280.85-18939121102418="` echo $HOME/.ansible/tmp/ansible-tmp-1489496280.85-18939121102418 `" ) && sleep 0'"'"''
<orc2> PUT /tmp/tmpQkvBKk TO /root/.ansible/tmp/ansible-tmp-1489496280.84-248745293629877/setup.py
<orc2> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/sveyrie/.ansible/cp/ansible-ssh-%h-%p-%r '[orc2]'
<orc1> PUT /tmp/tmpAuXYKK TO /root/.ansible/tmp/ansible-tmp-1489496280.85-18939121102418/setup.py
<orc1> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/sveyrie/.ansible/cp/ansible-ssh-%h-%p-%r '[orc1]'
<orc2> ESTABLISH SSH CONNECTION FOR USER: root
<orc2> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/sveyrie/.ansible/cp/ansible-ssh-%h-%p-%r orc2 '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1489496280.84-248745293629877/ /root/.ansible/tmp/ansible-tmp-1489496280.84-248745293629877/setup.py && sleep 0'"'"''
<orc1> ESTABLISH SSH CONNECTION FOR USER: root
<orc1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/sveyrie/.ansible/cp/ansible-ssh-%h-%p-%r orc1 '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1489496280.85-18939121102418/ /root/.ansible/tmp/ansible-tmp-1489496280.85-18939121102418/setup.py && sleep 0'"'"''
<orc2> ESTABLISH SSH CONNECTION FOR USER: root
<orc2> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/sveyrie/.ansible/cp/ansible-ssh-%h-%p-%r -tt orc2 '/bin/sh -c '"'"'/usr/bin/python /root/.ansible/tmp/ansible-tmp-1489496280.84-248745293629877/setup.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1489496280.84-248745293629877/" > /dev/null 2>&1 && sleep 0'"'"''
<orc1> ESTABLISH SSH CONNECTION FOR USER: root
<orc1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/sveyrie/.ansible/cp/ansible-ssh-%h-%p-%r -tt orc1 '/bin/sh -c '"'"'/usr/bin/python /root/.ansible/tmp/ansible-tmp-1489496280.85-18939121102418/setup.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1489496280.85-18939121102418/" > /dev/null 2>&1 && sleep 0'"'"''
ok: [orc2]
ok: [orc1]

TASK [Additional setup] ********************************************************
task path: /tmp/ansible/play.yml:3
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/system/setup.py
<orc1> ESTABLISH SSH CONNECTION FOR USER: root
<orc1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/sveyrie/.ansible/cp/ansible-ssh-%h-%p-%r orc1 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1489496282.29-273180020166881 `" && echo ansible-tmp-1489496282.29-273180020166881="` echo $HOME/.ansible/tmp/ansible-tmp-1489496282.29-273180020166881 `" ) && sleep 0'"'"''
<orc1> PUT /tmp/tmpr0kW7S TO /root/.ansible/tmp/ansible-tmp-1489496282.29-273180020166881/setup.py
<orc1> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/sveyrie/.ansible/cp/ansible-ssh-%h-%p-%r '[orc1]'
<orc1> ESTABLISH SSH CONNECTION FOR USER: root
<orc1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/sveyrie/.ansible/cp/ansible-ssh-%h-%p-%r orc1 '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1489496282.29-273180020166881/ /root/.ansible/tmp/ansible-tmp-1489496282.29-273180020166881/setup.py && sleep 0'"'"''
<orc1> ESTABLISH SSH CONNECTION FOR USER: root
<orc1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/sveyrie/.ansible/cp/ansible-ssh-%h-%p-%r -tt orc1 '/bin/sh -c '"'"'/usr/bin/python /root/.ansible/tmp/ansible-tmp-1489496282.29-273180020166881/setup.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1489496282.29-273180020166881/" > /dev/null 2>&1 && sleep 0'"'"''
ok: [orc1 -> orc1] => (item=orc1)
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/system/setup.py
<orc2> ESTABLISH SSH CONNECTION FOR USER: root
<orc2> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/sveyrie/.ansible/cp/ansible-ssh-%h-%p-%r orc2 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1489496283.33-94625198778322 `" && echo ansible-tmp-1489496283.33-94625198778322="` echo $HOME/.ansible/tmp/ansible-tmp-1489496283.33-94625198778322 `" ) && sleep 0'"'"''
<orc2> PUT /tmp/tmpQ0fKgy TO /root/.ansible/tmp/ansible-tmp-1489496283.33-94625198778322/setup.py
<orc2> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/sveyrie/.ansible/cp/ansible-ssh-%h-%p-%r '[orc2]'
<orc2> ESTABLISH SSH CONNECTION FOR USER: root
<orc2> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/sveyrie/.ansible/cp/ansible-ssh-%h-%p-%r orc2 '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1489496283.33-94625198778322/ /root/.ansible/tmp/ansible-tmp-1489496283.33-94625198778322/setup.py && sleep 0'"'"''
<orc2> ESTABLISH SSH CONNECTION FOR USER: root
<orc2> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/sveyrie/.ansible/cp/ansible-ssh-%h-%p-%r -tt orc2 '/bin/sh -c '"'"'/usr/bin/python /root/.ansible/tmp/ansible-tmp-1489496283.33-94625198778322/setup.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1489496283.33-94625198778322/" > /dev/null 2>&1 && sleep 0'"'"''
ok: [orc1 -> orc2] => (item=orc2)

TASK [debug] *******************************************************************
task path: /tmp/ansible/play.yml:9
ok: [orc1] => {
    "msg": "orc2"
}
ok: [orc2] => {
    "msg": "orc2"
}

PLAY RECAP *********************************************************************
orc1                       : ok=3    changed=0    unreachable=0    failed=0
orc2                       : ok=2    changed=0    unreachable=0    failed=0
```

**Comment by bcoca** [comment] 2017-03-14 14:29
dupe of #15365

**Closed as completed by bcoca** 2017-03-14 14:29 UTC
Labels: affects_2.2, bug
