### ISSUE TITLE
Unable to ping hosts with new ansible setup

### ISSUE THREAD

**Issue by jeuniii** [ansible/ansible#16668] opened 2016-07-10 23:44 UTC
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
[root@master ~]# ansible --version
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### SUMMARY

I just setup 2 boxes with RHEL 6.6 and installed ansible on the master node. I setup passwordless ssh for root user between the 2 nodes and can successfully ssh from A (ansible machine) to B without entering password.

Now I am trying to run the command:

ansible all -m ping -i /app/ansible/env

But am getting the ERROR everytime

10.0.0.23 | FAILED! => {
    "failed": true, 
    "msg": "failed to resolve remote temporary directory from ansible-tmp-1468175944.42-138203382041728: `( umask 77 && mkdir -p \"` echo $HOME/.ansible/tmp/ansible-tmp-1468175944.42-138203382041728 `\" && echo ansible-tmp-1468175944.42-138203382041728=\"` echo $HOME/.ansible/tmp/ansible-tmp-1468175944.42-138203382041728 `\" )` returned empty string"
}
##### STEPS TO REPRODUCE

```
ansible all -m ping -i /app/ansible/env
```

##### EXPECTED RESULTS

Was expecting a successful ping 
##### ACTUAL RESULTS

```
10.0.0.23 | FAILED! => {
    "failed": true, 
    "msg": "failed to resolve remote temporary directory from ansible-tmp-1468175944.42-138203382041728: `( umask 77 && mkdir -p \"` echo $HOME/.ansible/tmp/ansible-tmp-1468175944.42-138203382041728 `\" && echo ansible-tmp-1468175944.42-138203382041728=\"` echo $HOME/.ansible/tmp/ansible-tmp-1468175944.42-138203382041728 `\" )` returned empty string"
}
```

**Comment by Trozz** [comment] 2016-07-13 08:20
can you check the ownership of the `$HOME/.ansible/` and `$HOME/.ansible/tmp/` folders, if the `.ansible` folder does not exist can you check the permissions of your `$HOME` directory.

**Comment by jimi-c** [comment] 2016-09-24 20:15
Duplicate of https://github.com/ansible/ansible/issues/13876, so closing.

**Closed as completed by jimi-c** 2016-09-24 20:15 UTC
Labels: P2, affects_2.1, bug
