### ISSUE TITLE
ansible playbook tags exclusion

### ISSUE THREAD

**Issue by aletessier** [ansible/ansible#12701] opened 2015-10-09 22:33 UTC
Would it be nice to have tags exclusion the same way you can do with hosts (all:&pr) ?

```
% ansible-playbook install-servers.yml -t ntp --list-tasks

playbook: install-servers.yml

  play #1 (Install servers):    TAGS: []
    pacman ntp  TAGS: [ntp, pacman]
    template /etc/ntp.conf  TAGS: [ntp, template]
    service ntp TAGS: [ntp, service]
```

For example, in this use case i would like to exclude pacman and service tasks:

```
% ansible-playbook install-servers.yml -t 'ntp,&template' --list-tasks 

playbook: install-servers.yml

  play #1 (Install servers):    TAGS: []
    template /etc/ntp.conf  TAGS: [ntp, template]
```

```
% ansible-playbook --version                                              
ansible-playbook 1.9.3
  configured module search path = None
```

**Comment by bcoca** [comment] 2015-10-09 22:38
closing as dupe of #11396

**Closed as completed by bcoca** 2015-10-09 22:38 UTC
