### ISSUE TITLE
Subversion fails when using export option

### ISSUE THREAD

**Issue by justintaft** [ansible/ansible#10102] opened 2015-01-26 18:30 UTC
When using `export=True`, `svn info` runs and fails because there is no .svn folder.

With export method, a different way to detect change is required.

https://github.com/ansible/ansible-modules-core/blob/19b328c4df2157b6c0191e9144236643ce2be890/source_control/subversion.py#L225

**Comment by abadger** [comment] 2015-01-26 18:45
Thanks.  This is a duplicate of: https://github.com/ansible/ansible-modules-core/issues/388  There's a pull request which contains a fix for that here: https://github.com/ansible/ansible-modules-core/pull/506  but we're currently trying to figure out how the changes in that pull request interact with the force parameter.

**Closed as completed by abadger** 2015-01-26 18:45 UTC
