### ISSUE TITLE
The logging setup by utils.display only creates a Logger() if a log_path is provided.

### ISSUE THREAD

**Issue by alikins** [ansible/ansible#25759] opened 2017-06-15 17:38 UTC
##### SUMMARY

display.py only creates the display Logger() if a log_file path is set.

The Logger() should always be created, but it only needs to be associated with a log file if log_path is set. If not logging to a file, the Logger() created can be associated with a NullHandler().

This would allow other code to attach additional log handlers (like a syslog handler for ex, or the various handlers used for shipping logs to log aggregating tools).

##### ISSUE TYPE

 - ~Bug  Report~
- Feature Idea

##### COMPONENT NAME

lib/ansible/utils/display.py

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel 44687bb917) last updated 2017/06/15 13:12:13 (GMT -400)
  config file = None
  configured module search path = [u'/home/adrian/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/adrian/src/ansible/lib/ansible
  executable location = /home/adrian/src/ansible/bin/ansible
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]

```

##### CONFIGURATION

```
[defaults]
log_path = /path/to/log.log
```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by bcoca** [comment] 2017-06-15 17:59
this was by design as the preferred method of 'hooking into' the events are the callback plugins

**Comment by s-hertel** [comment] 2020-11-13 16:01
We're going to go ahead to close this. This came up in backlog and we have larger design plans for display.

**Closed as completed by s-hertel** 2020-11-13 16:01 UTC
Labels: c:utils/display, affects_2.4, support:core, has_pr, feature
