### ISSUE TITLE
ERROR! Unexpected Exception, this is probably a bug: 'CallbackModule' object has no attribute 'set_options'

### ISSUE THREAD

**Issue by fildred13** [ansible/ansible#31805] opened 2017-10-16 18:32 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible-playbook

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/sean/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
 No settings changed, confirmed with "ansible-config dump --only-changed" outputting nothing.

##### OS / ENVIRONMENT
Ubuntu 16.04 managing Ubuntu 16.04

##### SUMMARY
Exception when running playbook: "ERROR! Unexpected Exception, this is probably a bug: 'CallbackModule' object has no attribute 'set_options'"

A coworker with a Mac host runs the same playbook without issue.

##### STEPS TO REPRODUCE
1) Create a playbook. I created one that just prints a debug message and nothing else.
2) Attempt to run the playbook with  `ansible-playbook --inventory-file=/path/to/inventory -vvv main.yml`

```yaml
#main.yml
- hosts: development                                                               
  become: yes                                                                      
  gather_facts: no                                                                 
                                                                                   
  tasks:                                                                           
    - name: print debug msg                                                        
      debug:                                                                       
        msg: 'Hello, World!' 
```

##### EXPECTED RESULTS
The playbook would run normally.

##### ACTUAL RESULTS
```
ansible-playbook 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/sean/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
Using /etc/ansible/ansible.cfg as config file
Parsed /path/to/inventory inventory source with ini plugin
ERROR! Unexpected Exception, this is probably a bug: 'CallbackModule' object has no attribute 'set_options'
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 106, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/playbook.py", line 130, in run
    results = pbex.run()
  File "/usr/lib/python2.7/dist-packages/ansible/executor/playbook_executor.py", line 90, in run
    self._tqm.load_callbacks()
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_queue_manager.py", line 203, in load_callbacks
    callback_obj .set_options(C.config.get_plugin_options('callback', callback_plugin._load_name))
AttributeError: 'CallbackModule' object has no attribute 'set_options'
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by bcoca** [comment] 2017-10-18 15:39
duplicate of #30597, fixed by #30625

**Closed as completed by bcoca** 2017-10-18 15:39 UTC
Labels: affects_2.4, support:core, bug
