### ISSUE TITLE
SSH failure on certain hosts

### ISSUE THREAD

**Issue by monitorjbl** [ansible/ansible#4249] opened 2013-09-25 19:13 UTC
I have been using Ansible on 12 hosts with no issues at all. For some reason, when I tried to add the 13th host (lucky, lucky), the tool threw an error I hadn't seen before:

```
FAILED => failed to resolve remote temporary directory from 
$HOME/.ansible/tmp/ansible-1380135548.99-254800519176889: `mkdir -p 
$HOME/.ansible/tmp/ansible-1380135548.99-254800519176889 && chmod a+rx 
$HOME/.ansible/tmp/ansible-1380135548.99-254800519176889 && echo 
$HOME/.ansible/tmp/ansible-1380135548.99-254800519176889` returned empty string
```

Google failed me utterly, so I did some digging through the source. I found that the ansible/runner/connection_plugins/paramiko_ssh.py script simply wasn't returning any response from the this host. The public key was set up just like the other 12, and I was able to SSH in without a password, but Paramiko just wouldn't return any data.

After much head scratching and discovering quite possibly the most usefully arcane Stackoverflow response I've ever seen (http://stackoverflow.com/a/18472049/484661), I found that that the only way to get this particular host to return anything was by calling the get_pty() function on the Paramiko channel that exec_command opens:

```
178     def exec_command(self, cmd, tmp_path, sudo_user, sudoable=False, executable='/bin/sh'):
179         ''' run a command on the remote host '''
180     
181         bufsize = 4096
182         try:
183             chan = self.ssh.get_transport().open_session()
184             chan.get_pty()
185         except Exception, e:
186             msg = "Failed to open session"
187             if len(str(e)) > 0:
188                 msg += ": %s" % str(e)
189             raise errors.AnsibleConnectionFailed(msg)
```

Adding this made Ansible work with this host, and it did not cause any issue with the previous 12. I realize this is more of a Paramiko issue than an Ansible one, but I figured this should be reported as an Ansible bug for now since you can work around it with the get_pty() function.

**Comment by srgvg** [comment] 2013-09-25 19:18
@monitorjbl can you confirm which version of Ansible and paramiko, and which OS/ distro & version you use?

**Comment by jimi-c** [comment] 2013-09-25 19:25
Closing, this appears to be a dupe of https://github.com/ansible/ansible/issues/4227

**Closed as completed by jimi-c** 2013-09-25 19:25 UTC

**Comment by monitorjbl** [comment] 2013-09-25 20:01
Yeah, this does indeed appear to be the same root cause, sorry for the duplicate. Just for posterity though, I'm using Paramiko 1.11.1 and I found the reason for this host requiring the interactive shell. It turned out someone had messed with the .bashrc and added this gem to it:

```
 [ -z "$PS1" ] && exit
```

This just terminates non-interactive shells, so the actual reason for this error was definitely not Ansible or Paramiko. Still, it would be nice if Ansible could catch this and report more meaningful errors in this case. Maybe just see if stdout and stderr are blank and offer up a helpful suggestion? Would have saved me several hours :(
