### ISSUE TITLE
Git Module - Permission Denied and Traceback Error

### ISSUE THREAD

**Issue by jamesgoodhouse** [ansible/ansible#7383] opened 2014-05-13 16:10 UTC
**Issue Type:**

Bug Report

**Ansible Version:**

Ansible 1.6.1 and possible Ansible 1.6

**Environment:**

Ansible is running from OS/X Mavericks 10.9.2
I am managing an Ubuntu 12.04 instance

**Summary:**

When cloning a repo using the Git module, I receive a traceback error as well as a permission denied error. This error never occurred using Ansible 1.5.5.

**Steps To Reproduce:**

Running the following task results in an error:

```
- name: copy code from repository
  sudo_user: deploy_user
  git: repo={{ git['repo_url'] }}
       dest={{ install_dir }}
       key_file="/home/deploy_user/.ssh/deploy.key"
       version={{ git['branch'] }}
       depth=1
       accept_hostkey=yes
  register: clone_result
  notify: restart php5-fpm
```

This task is ran via a remote user that has sudo privileges.

**Expected Results:**

I expect to have the task run without error, as it did when running Ansible 1.5.5.

**Actual Results:**

The following error is generated when the task is ran:

```
TASK: [deploy | copy code from repository] ************************************
<33.33.33.71> ESTABLISH CONNECTION FOR USER: vagrant
<33.33.33.71> REMOTE_MODULE git repo=git@github.com:company/project.git dest=/srv/project key_file="/home/deploy_user/.ssh/deploy.key" version=master depth=1 accept_hostkey=yes
<33.33.33.71> EXEC ['ssh', '-C', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/local_user/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'IdentityFile=/Users/local_user/.vagrant.d/insecure_private_key', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=vagrant', '-o', 'ConnectTimeout=10', '33.33.33.71', u'/bin/sh -c \'sudo -k && sudo -H -S -p "[sudo via ansible, key=bjabkvmkprzchfetqhbbnzyubjbrjjoq] password: " -u deploy_user /bin/sh -c \'"\'"\'echo SUDO-SUCCESS-bjabkvmkprzchfetqhbbnzyubjbrjjoq; LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8 /usr/bin/python\'"\'"\'\'']
failed: [prod.project.dev] => {"failed": true, "item": "", "parsed": false}
invalid output was: Traceback (most recent call last):
  File "<stdin>", line 1911, in <module>
  File "<stdin>", line 503, in main
  File "<stdin>", line 184, in write_ssh_wrapper
  File "/usr/lib/python2.7/tempfile.py", line 300, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib/python2.7/tempfile.py", line 235, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 13] Permission denied: '/home/vagrant/ysynAz'
debug3: mux_client_read_packet: read header failed: Broken pipe
debug2: Received exit status from master 1


FATAL: all hosts have already failed -- aborting
```

**Comment by jimi-c** [comment] 2014-05-13 17:22
Seems to be related to #7375, as they're both failing at the same spot.

**Comment by jimi-c** [comment] 2014-05-13 17:24
I'm going to go ahead and close this as a dupe of the above issue, since they're both related to using the key_file parameter when also using sudo. If there are any further follow-ups, just use #7375. Thanks!

**Closed as completed by jimi-c** 2014-05-13 17:24 UTC
Labels: P2, bug
