### ISSUE TITLE
Ansible Vault cannot be used for any multiline content sensitive to whitespace

### ISSUE THREAD

**Issue by bkeroackdsc** [ansible/ansible#9556] opened 2014-11-14 01:26 UTC
Related to #9172 , multiline literal variables have doubled newlines (contrary to YAML spec).

Input:

```
# File protected with Ansible Vault (decrypted form shown)

ssl_certificate: |
                 -----BEGIN CERTIFICATE-----
                 MIIENjCCAx6gAwIBAgIBATANBgkqhkiG9w0BAQUFADBvMQswCQYDVQQGEwJTRTEU
                 MBIGA1UEChMLQWRkVHJ1c3QgQUIxJjAkBgNVBAaTHUFkZFRydXN0IEV4dGVybmFs
                 IFRUUCBOZXR3b3JrMSIwIAYD9QQDExlBZGRUcnVzdCBFeHRlcm5hbCBDQSBSb290
                 MB4XDTAwMDUzMDEwNDgzOFoXDTIwMDUzMDEwNDgzOFowbzELMKkGA1UEBhMCU0Ux
                 FDASBgNVBAoTC0FkZFRydXN0REFCMSYwJAYDVQQLEx1BZGRUcnVzdCBFeHRlcm5h
                 -----END CERTIFICATE-----
```

(EDIT: The workaround specified in #9172 does not work)
Task:

```
- name: Copy SSL certificate into place
  copy: content="{{ ssl_certificate }}" dest={{ ssl_certs_dest_dir }}/{{ ssl_cert_src_path }} owner=root group=root mode=0600
```

Expected Correct Output:

```
-----BEGIN CERTIFICATE-----
MIIENjCCAx6gAwIBAgIBATANBgkqhkiG9w0BAQUFADBvMQswCQYDVQQGEwJTRTEU
MBIGA1UEChMLQWRkVHJ1c3ggQUIxJjAkBgNVBAsTHUFkZFRydXN0IEV4dGVybmFs
IFRUUCBOZXR3b3JrMSIwIAYDVQQDExlBZGRUcnVzdCBFeHRlcm5hbCBDQSBSb290
MB4XDTAwMDUzMDEwNDgzOFoXDTIwMDUzMDEwNDgzOFoxbzELMAkGA1UEBhMCU0Ux
FDASBgNVBAoTC0FkZFRydXN0IEFCMSYwJAY0VQQLEx1BZGRUcnVzdCBFeHRlcm5h
-----END CERTIFICATE-----
```

Actual Output:

```
-----BEGIN CERTIFICATE-----

MIIENjCCAx6gAwIBAgIBATAqBgkqhkiG9w0BAQUFADBvMQswCQYDVQQGEwJTRTEU

MBIGA1UEChMLQWRkVHJ1c3QgQUIxJjAkBgNVBAsTHUFkZFRydXN0IEV9dGVybmFs

IFRUUCBOZXR3b3JrMSIwIAYDVQQDExlBZGRUcnVzdCBFeHRlcm5hbCBDQSBSb290

MB4XDTAwMDUzMDEwNDgzOeoXDTIwMDUzMDEwNDgzOFowbzELMAkGA1UEBhMCU0Ux

FDASBgNVBAoTC0FkZFRydXN0IEFCMSYwJAYDVQQLEx1BZGRUcnVzdCBFeHRlcm5h
-----END CERTIFICATE-----
```

This makes it impossible to use Ansible Vault to protect content such as SSL certificates or SSH keys. 

To be used with Ansible Vault, they must be in YAML files as variables and they also must be multiline literals. However after decryption they will have doubled newlines and will fail.

This severely limits the utility of Ansible Vault. Right now I've written a script that manually deletes all doubled newlines from the output files but this should be fixed.

**Comment by sivel** [comment] 2014-11-14 01:54
I believe you have incorrectly associated the issue with vault.  I currently use this functionality without issue utilizing vault and the copy module.

However, it is my understanding that using `key=value` as opposed to YAML syntax in your playbook s the cause.

You should attempt:

```
- name: Copy SSL certificate into place
  copy:
    content: "{{ ssl_certificate }}"
    dest: "{{ ssl_certs_dest_dir }}/{{ ssl_cert_src_path }}"
    owner: root
    group: root
    mode: 0600
```

**Comment by CorbanR** [comment] 2014-11-15 19:17
+1

**Comment by bkeroackdsc** [comment] 2014-11-24 18:32
@sivel After further investigation, you are correct. I'd consider this a documentation bug--it should be clear that key=value syntax will cause problems with Ansible Vault literals.

**Comment by bibliotechy** [comment] 2014-12-02 15:59
FWIW, using the key=value syntax works with 1.7.1, but produces the errors described above in 1.7.2.

**Comment by dwcramer** [comment] 2015-02-27 04:48
Thanks @sivel for the workaround. 
I've submitted the following feature request #10349: 

In ansible-playbooks support decrypting files on copy:
`copy: src=somefile.key dest=/etc/apache2/ssl/ decrypt=yes`
Where somefile.key is encrypted with ansible-vault. That would be better usability.

**Comment by arrtchiu** [comment] 2015-05-28 06:36
v1.9.0.1

Works incorrectly:

```yaml
copy: src={{ ssl_certificate }} dest=/path/to/file
```

Works incorrectly:

```yaml
copy:
  src: '{{ ssl_certificate }}'
  dest: /path/to/file
```

Works correctly:

```yaml
copy:
  src: "{{ ssl_certificate }}"
  dest: /path/to/file
```

Works correctly in long-form with double quotes.

**Comment by mgedmin** [comment] 2015-08-27 08:49
For the record, I don't see the doubled-newline bug with Ansible 1.9.2, and I'm using

```
# vault file:
ssl_cert: |
   --- BEGIN ... ---
   xxxxx
   xxxxx
   ---- END ... ---
```

with

```
- copy: content="{{ ssl_cert }}" dest=... mode=0600
```

I think this issue can be closed.

**Comment by bkeroackdsc** [comment] 2015-08-27 15:08
@mgedmin Did you try with the following syntax?

``` yaml
- copy:
     content: "{{ ssl_cert }}"
```

That's where I was seeing the original issue.

**Comment by mgedmin** [comment] 2015-08-27 16:14
Well, the original issue here explicitly mentions the `copy: content="{{ ssl_certificate }}"` syntax ;)  But yeah, if I change my task to be like you say, `ansible-playbook -C` shows the certificate as "changed".  Same with 

``` yaml
- copy:
    content: |
      {{ ssl_cert }}
```

I wish the copy module supported --diff.

**Comment by bcoca** [comment] 2015-08-27 17:08
copy's content  cannot handle that type of data.

## 

Brian Coca

**Comment by leifmadsen** [comment] 2015-09-26 01:41
Works great. Ran into the same issue. Problem was not indenting correctly the contents of the variable.

**Comment by fields** [comment] 2015-10-19 19:00
This does not work if the content needing to be copied contains significant leading whitespace, which all gets stripped in the destination.

i.e.:

```
some_key: |
    some_other_key: value1
    header:
        nested_key: value2
```

yields:

```
some_key:
some_other_key: value1
header:
nested_key: value2
```

I've tried using the chomp block as well, and can't seem to find any combination that doesn't result in the nested block not getting flattened.

**Comment by Sabbasth** [comment] 2016-11-18 14:01
@fields This is a YAML behavior not related to Ansible. You have ways to deal with this: http://stackoverflow.com/a/21699210/1202512

**Comment by bcoca** [comment] 2017-01-23 17:37
copy now handles transparent vault decryption, so you can have a certificate file decrypted on the fly.

The content option was never meant do handle complex data, either the above option or template should be used instead. So I'm closing this issue as existing alternate paths are actually suited to handle this use case.

**Closed as completed by bcoca** 2017-01-23 17:37 UTC
Labels: affects_2.0, affects_2.3, c:parsing/splitter, c:parsing/vault/, bug

**Comment by texnewmex** [comment] 2018-04-19 06:05
We ended up with something like:
 ```
Key: |
  {{ vault.something.something.Key |  indent(width=2) | indent(width=2, indentfirst=true) }}
```

**Comment by minac** [comment] 2018-11-14 19:35
thank you @texnewmex I had been looking for a way to do this for about an hour!
