### ISSUE TITLE
{{ var_exists |default('') }} role variables always evaluates to default('')

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/ansible#16193] opened 2016-06-08 19:59 UTC
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 1.9.6
  configured module search path = None
```
##### SUMMARY

Passing variables to roles from inventory-defined variables always results in the `|defaul('')` case; even when the variable exists.
##### STEPS TO REPRODUCE

http://filebin.ca/2jzNVNZXgpJ1/inventory_all_vars.tar.gz

##### EXPECTED RESULTS

For the variables defined in the inventory file to be echoed.
##### ACTUAL RESULTS

All variables are equal to ""

**Comment by sivel** [comment] 2016-06-08 20:06
I cannot duplicate this in 2.0+, but can in 1.9.  In 2.0, 2.1, and devel:

```
TASK [foobar : debug] **********************************************************
ok: [localhost] => {
    "msg": "1"
}

TASK [foobar : debug] **********************************************************
ok: [localhost] => {
    "msg": "2"
}

TASK [foobar : debug] **********************************************************
ok: [localhost] => {
    "msg": "1"
}

TASK [foobar : debug] **********************************************************
ok: [localhost] => {
    "msg": "2"
}

TASK [foobar : debug] **********************************************************
ok: [localhost] => {
    "msg": ""
}

TASK [foobar : debug] **********************************************************
ok: [localhost] => {
    "msg": ""
}
```

**Comment by bcoca** [comment] 2016-06-08 20:10
role parameters don't have access to the inventory?

**Comment by bcoca** [comment] 2016-06-08 20:13
tested and get same as @sivel,  only ones that are "" are the ones that are undefined or empty  (foobar_foobar, which depends on non existent foobar)

**Comment by chrismeyersfsu** [comment] 2016-06-09 14:22
This is only a problem on 1.9, not 2.0. Below is the output from 1.9.

```
PLAY [localish] ***************************************************************

TASK: [foobar | debug ] *******************************************************
ok: [localhost] => {
    "msg": ""
}

TASK: [foobar | debug ] *******************************************************
ok: [localhost] => {
    "msg": ""
}

TASK: [foobar | debug ] *******************************************************
ok: [localhost] => {
    "msg": ""
}

TASK: [foobar | debug ] *******************************************************
ok: [localhost] => {
    "msg": ""
}

TASK: [foobar | debug ] *******************************************************
ok: [localhost] => {
    "msg": ""
}

TASK: [foobar | debug ] *******************************************************
ok: [localhost] => {
    "msg": "37"
}

PLAY RECAP ********************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=0
```

**Comment by bcoca** [comment] 2016-06-09 14:35
so tried again and in 'clean room', i can reproduce in 1.9.7 but not in 2.0+, this seems related on how roles get processed, which changed in 2.0

**Comment by bcoca** [comment] 2016-06-09 14:49
After looking at this closer, this is not as much a bug as a new capability 2.0 offers that previous versions never did. 

The issue happens when on role import, in 1.9, the variables are evaluated, which triggers the `|default`since the variables they depend on are not there yet.

2.x evaluates variables 'lazily', which means on role import you don't evaluate the variables, so `|default` is not triggered and the variables are not 'set', the variables then get evaluated on 'consumption time' which does have the other variables defined already.

In 1.9 you can get around this several ways, the simplest is not using `|default` on role definition but defaults/main.yml in side of role. You can also remove`|default` from role definition and add it when you consume it (role import will fail to template, but 1.9 ignores these errors and will retry templating over and over at each stage until it succeeds or cannot fail anymore).

So I'm going to close this as 'not a bug' but a new feature that we are not backporting (as it requires enough of a rewrite of 1.9 that it will 'become' 2.0 anyways ....).

**Closed as completed by bcoca** 2016-06-09 14:49 UTC
Labels: bug

**Comment by chrismeyersfsu** [comment] 2016-06-09 16:08
The above was a simplified example. My end goal is to run a task, conditionally, based on the variable "passed" (templated) to the role-specific variable.

For example:
`role_name_variable: {{ variable }}` <-- I want conditionally execute a task if `variable` is provided. I want to determine this through examining `role_name_variable`. The role reference `variable` in any way because the user can template a variable other than `variable`.

role/foobar/tasks/main.yml

```
- name: "Echo foobar_xxx when defined"
  debug:
    msg: "{{ foobar_xxx }}"
  when: "foobar_xxx is defined'"
```

main.yml

```
- role: foobar
  foobar_xxx: "{{ variable_that_does_not_exist }}"
```

The role task executes because `foobar_xxx` is defined but fails when trying to echo `foobar_xxx` due to `variable_that_does_not_exist` being undefined.

I've tried variations of the when condition such as `when: "foobar_xxx is defined and foobar_xxx|default('') != ''"`, without success.

**Comment by bcoca** [comment] 2016-06-09 16:58
that won't work cause the undefined issue is with the internal variable, you need:

```
- name: "Echo foobar_xxx when defined"
  debug:
    msg: "{{ foobar_xxx }}"
  when: variable_that_does_not_exist is defined'
```

**Comment by bcoca** [comment] 2016-06-09 17:00
an alternative is in defaults/main.yml

```
foobar_xxx: 'novalue'
```

```
when: foobar_xxx != 'novalue'
```

**Comment by chrismeyersfsu** [comment] 2016-06-09 17:49
The pre-define `foobar_xxx` "trick" doesn't work :(
