### ISSUE TITLE
callback plugin outputs twice when same name as built in

### ISSUE THREAD

**Issue by marvin-sinister** [ansible/ansible#25793] opened 2017-06-16 12:52 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

logstash callback plugin
##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /root/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

```

##### CONFIGURATION

```
callback_plugins = callback_plugins
callback_whitelist = logstash
```
##### OS / ENVIRONMENT

centos7
##### SUMMARY

When custom callback plugin with same name as built in plugin is defined, the plugin gets called twice. The plugin called is the one in runtime folder.
##### STEPS TO REPRODUCE

Add a callback plugin to "runtime folder/callback_plugins" and enable it. Tested with logstash plugin only.

##### EXPECTED RESULTS

Only relevant lines i found are:
```
Using /root/ansible/ansible.cfg as config file
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc
Loading callback plugin logstash2 of type aggregate, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc
```
When using different name (logstash2).
##### ACTUAL RESULTS

```
Using /root/ansible/ansible.cfg as config file
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc
Loading callback plugin logstash of type aggregate, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc
Loading callback plugin logstash of type aggregate, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc
```
When using same name (logstash).

**Comment by bcoca** [comment] 2017-06-16 14:21
That is not unusual as they might be 'triggered' to load several times, but any subsequent 'loads' should be from the cache (the already loaded one).

**Comment by marvin-sinister** [comment] 2017-06-18 22:30
I might have not explanied this well enough, the problem is that i get the entries in logstash twice. This started to happen after upgrading to 2.3.0 and wasn't happening before. My guess is that 2.3.0 included logstash as built in callback plugin, while 2.2.0 didn't.

Is that really expected?

**Comment by bcoca** [comment] 2017-06-19 17:44
no, you just posted the 'loading' logs which is normal, the x2 output was not clearly mentioned

**Comment by ahmetcetin39** [comment] 2019-01-30 12:44
I am having the same problem with ansible 2.4.2 even though I changed the name of the plugin under callback_plugins

**Comment by sivel** [comment] 2020-08-18 14:52
Duplicate of https://github.com/ansible/ansible/issues/33484

**Closed as completed by sivel** 2020-08-18 14:52 UTC
Labels: affects_2.3, c:plugins/callback, support:community, bug
