### ISSUE TITLE
win_regedit is not idempotent for multistring datatypes

### ISSUE THREAD

**Issue by jmighion** [ansible/ansible#18883] opened 2016-12-07 16:47 UTC
_From @jmighion on November 21, 2016 22:44_

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

win_regedit
##### ANSIBLE VERSION

```
ansible --version
ansible 2.2.0.0
  config file = /Users/james/Documents/work/SCIF/git/windows_STIGs/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

[defaults]
inventory = ./hosts
log_path = ./ansible.log

##### OS / ENVIRONMENT

N/A

##### SUMMARY

The win_regedit module does not compare multistring data correctly to determine if it needs changing or not. For Windows, multistring values are null terminated strings https://msdn.microsoft.com/en-us/library/windows/desktop/ms724884(v=vs.85).aspx . The comparison does not take that into account, so the provided data to the module contains \0's which are not given by the OS when using `Get-ItemProperty -Path $registryKey | Select-Object -ExpandProperty $registryValue`. This means that even if the result would've been the same, the change is still made anyways, making this not idempotent.
##### STEPS TO REPRODUCE

Run the following multiple times. Each time will report as changed.

```
  win_regedit:
    key: 'HKLM:\Path\To\Test\Key'
    value: ValueName
    data: "Line one\0Line two"
    datatype: multistring
```

##### EXPECTED RESULTS

```
ok: [ip.ip.ip.ip] => {
    "changed": false, 
    "data_changed": false, 
    "data_type_changed": false, 
    "invocation": {
        "module_name": "win_regedit"
    }
}
```
##### ACTUAL RESULTS

```
changed: [ip.ip.ip.ip] => {
    "changed": true, 
    "data_changed": true, 
    "data_type_changed": false, 
    "invocation": {
        "module_name": "win_regedit"
    }
}
```

_Copied from original issue: ansible/ansible-modules-extras#3510_

**Comment by jmighion** [comment] 2016-12-07 16:47
_From @ansibot on November 21, 2016 22:46_


@joshludwig, @smadam813, ping. This issue is waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jmighion** [comment] 2016-12-07 16:47
_From @ansibot on December 7, 2016 15:48_

This repository has been locked. All new issues and pull requests should be filed in https://github.com/ansible/ansible

Please read through the <a href="http://docs.ansible.com/ansible/dev_guide/repomerge.html#move-issues-and-prs-to-new-repo">repomerge</a> page in the dev guide. The guide contains links to tools which automatically move your issue or pull request to the ansible/ansible repo.

**Comment by dagwieers** [comment] 2017-02-04 00:34
@jmighion The win_regedit module has been refactored quite a bit.
Can you please test if your issue still stands using the devel branch ?

**Comment by jhawkesworth** [comment] 2017-02-27 13:35
This needs @jmighion to retry using latest devel version of ansible following recent changes to this module.

needs_info

**Comment by jmighion** [comment] 2017-02-27 18:42
Tested against today's devel : ansible-2.3.0-100.git201702271740.89bf14e.devel.el7.noarch.rpm
Windows 2008 R2 and 2012 member servers

Problem still exists.

Test playbook : 
```---
- name: Testing windows bugs
  hosts: all
  tasks:
    - name: new check
      win_regedit:
        path: HKLM:\Software\Microsoft\
        name: ValueName
        data: "Line one\0Line two"
        type: multistring
```

Running the same playbook multiple times still causes `change: true`.



Output from `ansible-playbook test.yml -vvvvvv` :
http://pastebin.com/tMb73p0B

**Comment by dagwieers** [comment] 2017-02-27 18:44
@jmighion You can now add `--diff` to your run and you should be seeing the difference (and hopefully the underlying issue).

**Comment by jmighion** [comment] 2017-02-27 18:53
Oh cool. Didn't know that.

Here's the diff : 
``` [HKLM:\Software\Microsoft\]
-"ValueName" = "multistring:Line one Line two"
+"ValueName" = "multistring:Line oneLine two"
changed: [2012_ms] => {
    "changed": true, 
    "data_changed": true, 
    "data_type_changed": false, 
    "diff": {
        "prepared": " [HKLM:\\Software\\Microsoft\\]\n-\"ValueName\" = \"multistring:Line one Line two\"\n+\"ValueName\" = \"multistring:Line one\u0000Line two\""
    }
}
```

I haven't had time to figure out all the changes with windows module, but keeping the files remotely doesn't seem to work anymore. So I cannot dig into the powershell to see if it's still an issue with `Get-ItemProperty`, but it looks like it is from the diff.

**Comment by dagwieers** [comment] 2017-02-28 16:24
Ok, I found the problem and why I couldn't reproduce it.

There is a difference in how Yaml handles escaped characters. If you specify this:
```yaml
    data: "Line one\0Line two"
```
Ansible receives a NULL character as separator between "Line one" and "Line two".

If you specify:
```yaml
    data: 'Line one\0Linetwo'
```
The two lines are separated by the string '\0'. That is an important difference, because we either provide the NULL character, or the string '\0'. And in the second case it works correctly and it is idempotent.

If you don't quote the data:
```yaml
    data: Line one\0Line two
```
it also works correct and '\0' is not translated to the NULL character.

So my first interpretation is that this is the correct behaviour. If you want to use double quoting, you will have to escape the backslash:
```yaml
    data: "Line one\\0Line two"
```

Can you confirm that this is your problem ? We will have to make this clear in the documentation, even when this is how YAML works.

**Comment by jmighion** [comment] 2017-02-28 17:46
That does not leave the expected value in the registry though because the null character was not evaluated/interpolated. For Windows, multistring values are null terminated strings https://msdn.microsoft.com/en-us/library/windows/desktop/ms724884(v=vs.85).aspx.

Using single quote or no quotes leaves the registry entry like : 
```
Line one\0Line two
```

The desired state of the registry entry can be acheived with double quotes : 
```
Line one
Line two
```

The problem is that the Get-ItemProperty returns with a newline which I think gets turned into a space in the comparison.
```
PS C:\Users\Administrator> Get-ItemProperty -Path HKLM:\Software\Microsoft | Select-Object -ExpandProperty ValueName
Line one
Line two
```

While the diff shows \u0000 which is the null character that's needed to create the newline in multistring datatypes, so the Compare-Data function line `if ($ReferenceData -eq $DifferenceData)` might need to change or $data might need to have special characters interpolated before comparing.

**Comment by jmighion** [comment] 2017-02-28 18:18
After looking up some on escaping unicode characters, this seems to work on PowerShell but I'm having trouble getting it to work by editing the win_regedit.ps1 : 
```
PS C:\Users\Administrator> $old_data = (Get-ItemProperty -Path HKLM:\Software\Microsoft | Select-Object -ExpandProperty
ValueName)
PS C:\Users\Administrator> $old_data
Line one
Line two
PS C:\Users\Administrator> [regex]::Unescape("Line one\u0000Line two")
Line one Line two
PS C:\Users\Administrator> $new_data = [regex]::Unescape($old_data)
PS C:\Users\Administrator> $new_data
Line one Line two
```

From https://stackoverflow.com/questions/1056692/how-do-i-encode-unicode-character-codes-in-a-powershell-string-literal

Also a potentially better comparison for strings might be to use `$d = [string]::Compare($a, $b, $True)`
https://technet.microsoft.com/en-us/library/ee692804.aspx

**Comment by dagwieers** [comment] 2017-07-04 10:05
At [19:00 UTC](http://www.thetimezoneconverter.com/?t=19:00&tz=UTC) this ticket will be processed during [the first Windows Sprint](https://github.com/ansible/community/wiki/Windows:-sprints#2017-07-04-1900-utc-sprint-1), we would appreciate if you could join the Sprint to help out with fixing/closing this issue.

**Comment by jborean93** [comment] 2017-07-06 01:34
Hey @jmighion I'm unsure if this is still an issue for you but I've just raised a PR at https://github.com/ansible/ansible/pull/26468 which definitely fixes the issue for you. Unfortunately I don't want to add another check that will format the data when using multistring by `\0` when yaml already has a mechanism for this. I've tested it out with some results below.

Playbook
```
---
- name: test win_regedit stuff
  hosts: 2012R2
  tasks:
  - name: create new entry
    win_regedit:
      path: HKCU:\SOFTWARE\Test
      name: ValueName
      data: ["Line one", "Line two"]
      type: multistring
      state: present

  - name: test idempotency
    win_regedit:
      path: HKCU:\SOFTWARE\Test
      name: ValueName
      data: ["Line one", "Line two"]
      type: multistring
      state: present
```

Output
```
ansible-py27) (ansible-py27) [jborean@jordan-fedora module-tester]$ ansible-playbook -i inventory.ini win_regedit_tests.yml

PLAY [test win_regedit stuff] ********************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************
Thursday 06 July 2017  11:27:41 +1000 (0:00:00.018)       0:00:00.018 *********
ok: [Server2012R2]

TASK [create new entry] **************************************************************************************************************************************
Thursday 06 July 2017  11:27:43 +1000 (0:00:02.277)       0:00:02.296 *********
changed: [Server2012R2]

TASK [test idempotency] **************************************************************************************************************************************
Thursday 06 July 2017  11:27:44 +1000 (0:00:00.679)       0:00:02.976 *********
ok: [Server2012R2]

PLAY RECAP ***************************************************************************************************************************************************
Server2012R2               : ok=3    changed=1    unreachable=0    failed=0
```

The screenshot below shows you that there are 2 entries in the multistring `Line one` and `Line two`. They are split by the hex value `0x0000` as expected.
![image](https://user-images.githubusercontent.com/8462645/27891705-a5094834-623e-11e7-84f5-1fc94caf098d.png)

If you are able to test the PR mentioned and add a comment saying this works for you that would be great.

**Comment by jmighion** [comment] 2017-07-06 01:52
Sorry, I am not in a position to test this anymore. I don't have easy access to Windows hosts and not enough free time to spin up VMs to give a solid test.

**Comment by jborean93** [comment] 2017-07-06 02:13
no worries, I'm pretty confident it is covered in the PR and the new test suite. I'll come back and close the issue once it is merged.

**Comment by dagwieers** [comment] 2017-07-17 03:09
resolved_by_pr #26468

**Closed as completed** 2017-08-09 13:27 UTC
Labels: windows, affects_2.2, module, support:core, bug
