### ISSUE TITLE
[hosts] Entire line removed on name match / 127.0.0.1 killed

### ISSUE THREAD

**Issue by claco** [ansible/ansible#4926] opened 2013-11-16 19:32 UTC
When adding a host entry using the hosts module, if the name matches an existing entry with a different ip, the entire entry line is removed, even if it contains other aliases. I would expect it to leave the other entries in place.

Ever more so, if the entry for the current name/ip exists AND the name exists in another entry, the other entry line is removed and a second instance of the existing entry is added.

with `ip=192.168.3.10 hostname=vagrant-chef-server state=present`

```
127.0.0.1   vagrant-chef-server vagrant-chef-server localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
```

bacame:

```
192.168.3.10 vagrant-chef-server
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
```

and if I fix that file to put 127.0.0.1 back, the next run produces:

```
192.168.3.10 vagrant-chef-server
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
192.168.3.10 vagrant-chef-server
```

**Comment by claco** [comment] 2013-11-16 19:41
For the background on this, since the name sharing with the `127.0.0.1` is a bit odd.

I currently have 2 roles: `chef-server` and `chef-client`. For all of the machines, the `chef-client` role drops the chef server hostname/ip into the `/etc/hosts` file to make chef-client happy (as of Chef 11). This works great as none of those machines are the same hostname as the chef server hostname being dropped into the hosts file.

On the chef server, I also run the `chef-client` role as so the chef server becomes the first registered node and it runs the same set of base server recipes. It's at this point that the client role is adding the chef server entry to the chef servers own hosts file.  While this is probably not sensical, it doesn't causes problems except for the fact that the `host` module mangles the `127.0.0.1` entry and all hell breaks loose.

All of that aside, what this reveals is that the `host` module should only ever remove an entry if there are no aliases left in the line, otherwise, it should probably just remove that one hostname from the line with the old ip, and add the new line with the new ip and hostname.

This seems like the right thing to do, and as a byproduct, would also fix my issue where 127.0.0.1 completely disappears, when instead if should still contain `localhost localhost.localdomain localhost4.localdomain`

**Comment by mscherer** [comment] 2013-11-16 22:23
I cannot reproduce on git head using:

```
$ cat /etc/hosts
127.0.0.1  localhost vagrant-chef-server
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
```

```
$ ansible -c local -i '127.0.0.1,' all -m host -a 'ip=192.168.3.10 hostname=vagrant-chef-server state=present' 
127.0.0.1 | success >> {
    "changed": false, 
    "msg": "", 
    "state": "present"
}
```

Who became:

```
$ cat /etc/hosts                                                                                               
127.0.0.1  localhost vagrant-chef-server
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
192.168.3.10 vagrant-chef-server 
```

But I can reproduce with your test case.

**Comment by mscherer** [comment] 2013-11-16 22:27
Ok so: 

```
127.0.0.1  localhost vagrant-chef-server
```

is ok

```
127.0.0.1  vagrant-chef-server localhost
```

is not.

**Comment by mpdehaan** [comment] 2013-11-16 23:41
(A)

So I don't think anything about the module should imply a DNS lookup is going to happen.

This module is about the contents of the file, not DNS.

This other part though:

```
Ever more so, if the entry for the current name/ip exists AND the name exists in another entry, the other entry       line is removed and a second instance of the existing entry is added.
```

Seems like that behavior needs to be more consistently defined.

**Comment by resmo** [comment] 2013-11-18 06:41
works as intended imho:

Per definition of a /etc/hosts, 
- a hosts file hostname can have 1 IP. You can not use the hostname twice, e.g.

```
127.0.0.1  vagrant-chef-server localhost
192.168.123.456 vagrant-chef-server
```

`ping vagrant-chef-server` should ping which IP?
- using the same IP more than once is also not possible:

```
192.168.123.456 vagrant-chef-server
192.168.123.456 mail-server
```

make use of aliases for that:

```
192.168.123.456 vagrant-chef-server mail-server
```

This means:

if you have

```
127.0.0.1  vagrant-chef-server localhost
```

and your task is like 

```
ip=192.168.3.10 hostname=vagrant-chef-server state=present
```

Then IP will be changed, because you already have the hostname "vagrant-chef-server" defined. It is not very clever to define: 

```
127.0.0.1 vagrant-chef-server localhost
```

this should look like instead

```
127.0.0.1 localhost vagrant-chef-server
```

**Comment by claco** [comment] 2013-11-18 13:47
@resmo  Re: "127.0.0.1 vagrant-chef-server localhost"

This would be true if I were the one doing that. In this case, that's either vagrant, virtualbox, or some call into the os putting things in that order. This could just as well be and provisioner, cloud or otherwise.

Aside from that, `hosts` is still broken because:

1) it should not to do different things based on the order of the entry vs aliases, and
2) even if it removes the primary hostname for any ip, if should not just throw away the rest of the aliases but should instead keep them. That's the least surprising thing.

Of course the name should only be with one ip, and `hosts` is dutifully moving it from 127.0.0.1 to the ip I want. It's just mangling the 127.0.0.1 line in the process, which is def. not expected or desired.

Or really, let's put the 127.0.0.1/localhost line aside for a moment. This same thing will happen if I create an entry for:

```
192.168.10.1 foo bar baz
```

and later try to manage it to:

```
192.168.10.10 bar baz
192.168.10.1 foo
```

The aliases will get deleted. This is not what I expect or want, which now means I have to call `hosts` twice: once to lay down the entry for `foo` and a second time to fix the now deleted entry for `bar baz`

This seems like undefined behavior. When I ask `hosts` to ensure an entry is present, I don't have to expect to do that for all entries in the file just to ensure they're  still present, esp if they're entries  I'm changing ad-hoc and not specifically in a playbook with all of my historical entries.

I'm happy to file a bug against whoever else is dropping the /etc/hosts in that order (vagrant maybe), but can't can't really guarantee what you're going to get from and upstream cloud provider and we should do our best to not completely mangle if possible.

**Comment by resmo** [comment] 2013-11-18 13:55
lets discuss this on ML please.

**Comment by claco** [comment] 2013-11-18 14:07
Yes, I will send one when I get towards an office. On last item of note:

```
127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
```

The stock cent file has localhost / localhost.domain twice. So the minute I call `host` to read add the 127.0.0.1 line, the ::1 line disappears because it also contains localhost.

**Comment by resmo** [comment] 2013-11-18 14:24
I think the only bug is, that IPv4 and IPv6 should be handled separately. which means. 

```
ip=192.168.3.10 hostname=vagrant-chef-server state=present 
```

should not touch IPv6 entries.

**Comment by jimi-c** [comment] 2013-11-18 20:05
@claco I believe this module is acting exactly as it's supposed to, and isn't undefined behavior because it is operating on primary keys. The un-intuitive part is that each operation is all-or-nothing, so if you're reassigning the primary key the module correctly thinks that you want it completely replaced. Since the aliases that did not previously exist are no longer specified, it does not preserve them. In your setup, the aliases you're moving should be just that - aliases. Since it's the first item in the list, it then is acted upon as a primary key for the entry.

The second part you posted, in which duplicate entries are created, is a bug in my opinion - duplicate entries should never be created, so I will look into fixing that.

In order to make it work the way you're expecting, we would have to do the following:

1) Provide an option to promote one of the alias entries (assuming the first one?) to the primary key. This would be done only when the primary key is assigned to a new IP address.
2) Provide an append option, which would allow new values added to an existing entry to preserve them without having to specify them.

Requesting this functionality would be new feature request issues, so feel free to open them.

**Comment by jimi-c** [comment] 2013-11-18 20:06
Oh and @resmo, I think the issue there again is that the localhost name is assigned to the IPv6 address - in my opinion it shouldn't be (which is why the localhost6 name exists).

**Comment by claco** [comment] 2013-11-18 20:28
Just to illustrate, I think  the ideal here clashes w/the real world. Aka, even stock dist files have dupes, and "moving" and entry from the fqdn in the 127.0.0.1 to another line isn't terribly uncommon:  

http://projects.puppetlabs.com/issues/10704

Given all the possibilities and shenanigans out there, some not even of the end users doing, the safest thing might be the simple thing: just make sure the line I asked the module to ensure is present is present,  and leave other magic of what a "proper" file is aside.

**Comment by mpdehaan** [comment] 2013-11-18 22:34
So in that mode I would definitely expect an "append" mode.

BTW, citing the way a puppet module works is almost never a good way to point out the right way of doing something (they get it right sometimes, but often not, we are NOT trying to match puppet) :)

To me, the idea of acting on a primary key line only seems more intuitive.

**Comment by claco** [comment] 2013-11-18 22:38
I'm not even suggesting there is a right way. I only pointed to that because it points how messed up some hosts files are in the wild from vendors and that others have had these sorts of issues with managing that file as well.

**Comment by resmo** [comment] 2013-11-19 09:17
my words: the only bug is, that host module mixes up ipv6 and ipv4. You can define 2 identical hostnames but separated by IPv.

I am working on that fix.

**Comment by jimi-c** [comment] 2013-11-19 19:24
We've gone ahead and decided to remove this module from core for the time being. We'll be drawing up a spec on how we believe the module should behave, after which time @resmo you can tackle rewriting your module to match or we can start over from scratch.

**Closed as completed by jimi-c** 2013-11-19 19:24 UTC
Labels: bug

**Comment by resmo** [comment] 2013-11-20 10:19
I really agree with that decision. 
I currently rewriting this module according the needs of the others and what we learned. Expect a proposal from me soon.

**Comment by claco** [comment] 2013-11-20 14:43
Sorry for the chaos I started. :-/

**Comment by claco** [comment] 2013-12-01 14:04
FYI, just pointing to the bug filed in vagrant that started this thread: https://github.com/mitchellh/vagrant/issues/2508
