### ISSUE TITLE
Scripts should start with #!/usr/bin/python2

### ISSUE THREAD

**Issue by tebeka** [ansible/ansible#14238] opened 2016-02-01 14:02 UTC
I'm running Archlinx where the default system Python is 3.5. This cases the following code to fail:

```
$ ansible -i 127.0.0.1,localhost all -m ping
localhost | FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "", 
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/miki/.ansible/tmp/ansible-tmp-1454335202.76-249950301753567/ping\", line 44, in <module>\r\n    import exceptions\r\nImportError: No module named 'exceptions'\r\n", 
    "msg": "MODULE FAILURE", 
    "parsed": false
}
127.0.0.1 | FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "", 
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/miki/.ansible/tmp/ansible-tmp-1454335202.76-43713622814893/ping\", line 44, in <module>\r\n    import exceptions\r\nImportError: No module named 'exceptions'\r\n", 
    "msg": "MODULE FAILURE", 
    "parsed": false
}
```

Changing the #! line in ping.py to `#!/usr/bin/python2` fixes the problem.

**Comment by bcoca** [comment] 2016-02-01 14:08
duplicate of #13600, #8245, #4451, #4117, #3596

**Closed as completed by bcoca** 2016-02-01 14:08 UTC

**Comment by tebeka** [comment] 2016-02-01 15:14
Sorry. My search skills are bad.
