### ISSUE TITLE
Docker connection does not work with non-root user

### ISSUE THREAD

**Issue by ThomasSteinbach** [ansible/ansible#13219] opened 2015-11-19 18:54 UTC
Hi,
i have have started the official jenkins docker container, e.g. named as my-jenkins, and set up my inventory as follows:

```
my-jenkins ansible_connection=docker
```

All tasks of the playbook, which is targeted to `my-jenkins` as host, fail because the default user of the container is not root. Here the error message:

```
fatal: [localhost -> aci_jenkins]: FAILED! => {"changed": false, "failed": true, "msg": "/usr/bin/python: can't open file '/var/jenkins_home/.ansible/tmp/ansible-tmp-1447958715.53-194745014881692/apt': [Errno 13] Permission denied\n", "parsed": false}
```

When I start the container before with `docker_user: root` everything works fine.

**Comment by chromerobv** [comment] 2015-11-19 21:21
you need to enable the docker group and add user to it in order to have non root run docker commands.
- Add the docker group if it doesn't already exist.
  sudo groupadd docker
- Add users to the docker group.
  sudo gpasswd -a foo docker
- Restart the docker daemon.
  sudo service docker restart
- If the above still doesn't work you need to change the group owner ship of some files.
  chown root:docker /var/run/docker.sock
  chown root:docker /usr/bin/docker

**Comment by ThomasSteinbach** [comment] 2015-11-19 23:40
The user on the target (local) host is already in the docker group. I talk about the user within the container. Please execute the following tiny, stripped-down Playbook to see the behavior of the docker connection:

```
- name: example of (possible?) bug in docker connector
  hosts: localhost
  tasks:
    - docker: name=myjenkins image=jenkins state=reloaded #docker_user=root
    - add_host: name=myjenkins ansible_connection=docker
    - name: create a directory in jenkins-home
      delegate_to: myjenkins
      file: path="/var/jenkins_home/test" state=directory
```

For running the playbook you need to
- have the latest Ansible 2.0 installed, which supports the docker connection but includes the bug
- have the invetory entry `local ansible_connection=localhost`

Probably you will get the same output for the third task as I postet in the initial bug description. Please run the playbook a second time, but remove the '#' in the first task, such that `docker_user=root` works and the default user within the container is _root_. By default the user within a started jenkins container is _jenkins_.

You should notice, that the playbook would run fine with _root_ within the container. You also can convince yourself that the jenkins user within the container has acces to its home directory by running the following commands:

```
docker run jenkins mkdir /var/jenkins_home/works
docker run jenkins mkdir /usr/bin/shouldnotwork
```

**Comment by abadger** [comment] 2015-11-20 01:06
As a workaround it looks like you can turn pipelining on in your ansible.cfg and it will work.  That implies to me that the connection plugin is probably doing the right thing but creation of the initial temporary file to which the script is being uploaded (pipelining passes the script to python's stdin instead of uploading it to the host) is operating as the wrong user somehow.

**Comment by abadger** [comment] 2015-11-20 01:13
Which version of docker do you have installed?

**Comment by ThomasSteinbach** [comment] 2015-11-20 07:09
```
$ docker --version
Docker version 1.9.0, build 76d6bc9

$ ansible --version
ansible 2.0.0 (devel d75e707af5) last updated 2015/11/20 00:28:33 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 88e0bfd75d) last updated 2015/11/20 00:29:00 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 7da1f8d4ca) last updated 2015/11/20 00:29:27 (GMT +200)

# the following output is stripped down to the relevant packages
$ pip list
ansible (2.0.0)
docker-py (1.3.1)
httplib2 (0.9)
Jinja2 (2.8)
MarkupSafe (0.23)
paramiko (1.15.3)
PyYAML (3.11)
six (1.9.0)
```

**Comment by abadger** [comment] 2015-11-20 15:51
Okay, it looks like our use of docker cp is at fault: https://docs.docker.com/v1.8/reference/commandline/cp/

According to that doc, when you use docker cp to copy into the docker container, the file ends up owned by root:root.

**Comment by abadger** [comment] 2015-11-20 15:54
Committed to both devel and the stable-2.0 branch.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Closed as completed** 2015-11-20 15:54 UTC
Labels: docker, bug

**Comment by brainstorm** [comment] 2017-05-30 05:31
I'm not sure if this could be a regression, but I'm observing this error with newer versions of docker/ansible:

https://github.com/brainstorm/pcgr-deploy/blob/master/ansible/launch_aws.yaml#L107

```
TASK [Pull PCGR docker image] ****************************************************************************************************************************************************************************************************************
fatal: [ec2-54-79-78-190.ap-southeast-2.compute.amazonaws.com]: FAILED! => {"changed": false, "failed": true, "msg": "Error connecting: Error while fetching server API version: ('Connection aborted.', error(13, 'Permission denied'))"}
	to retry, use: --limit @/Users/romanvg/dev/pcgr-deploy/ansible/launch_aws.retry
```

I am using those versions on the client:

```
$ ansible --version
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:05:08) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
```

Then on the remote system:

```
ubuntu@ip-172-31-14-61:~$ docker --version
Docker version 1.12.6, build 78d1802
ubuntu@ip-172-31-14-61:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty
```
