### ISSUE TITLE
Ansible 2.0 gives an 'need more than 2 values to unpack' error if there are spaces in group names

### ISSUE THREAD

**Issue by iprok** [ansible/ansible#13960] opened 2016-01-18 16:58 UTC
Issue Type:
Bug Report

Ansible Version:
2.0.0.2
<=1.9.4 is not affected

Ansible Configuration:
Default (no ansible.cfg)

Environment:
Gentoo amd64

Summary:
After upgrading to ansible 2.0 (2.0.0.2) it began to give me an error 

```
"ERROR! need more than 2 values to unpack"
```

when I have spaces in group names in my inventory files. It was ok when I have ansible 1.9.4.

Steps To Reproduce:
Install ansible 2.0.
Make test inventory file:

```
$ cat hosts
[test group]
localhost
```

Expected Results:
`ansible -m ping -i hosts all`
should start successfully

Actual Results:

```
$ ansible -i hosts -m ping all -vvv
No config file found; using defaults
ERROR! need more than 2 values to unpack
```

**Comment by bcoca** [comment] 2016-01-19 14:21
closing as dupe of #13917

**Closed as completed by bcoca** 2016-01-19 14:21 UTC
Labels: bug
