### ISSUE TITLE
shell command with async/poll not seeing process when it finishes

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#4668] opened 2013-10-24 13:30 UTC
Hey,

shell command with async/poll not seeing process when it finishes. Background we have a script that runs for over an hour that updates certs for our application. I am noticing that the script finishes but ansible does not see this. 

--- Task:
- name: apply certkit backend
  shell: echo y | /ehbackups/{{ certkit_date }}/installCertKit_ansible.sh -b >> /cctools/depot/eHealthLogs/certKits/{{ certkit_month }}/stajo21/certKit.{{ inventory_hostname }}
  async: 4000
  poll: 5
  tags:
  - backend

--- Output:
<job 658017273616> polling, 1280s remaining
<ndcpeh661> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO ndcpeh661
<ndcpeh661> EXEC /bin/sh -c 'mkdir -p /tmp/.ansible/tmp/ansible-1382620272.44-109719282043140 && echo /tmp/.ansible/tmp/ansible-1382620272.44-109719282043140'
<ndcpeh661> REMOTE_MODULE async_status jid=658017273616
<ndcpeh661> PUT /tmp/tmpwv7OWI TO /tmp/.ansible/tmp/ansible-1382620272.44-109719282043140/async_status
<ndcpeh661> EXEC /bin/sh -c '/usr/bin/python /tmp/.ansible/tmp/ansible-1382620272.44-109719282043140/async_status; rm -rf /tmp/.ansible/tmp/ansible-1382620272.44-109719282043140/ >/dev/null 2>&1'
<job 658017273616> polling, 1275s remaining
<ndcpeh661> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO ndcpeh661
<ndcpeh661> EXEC /bin/sh -c 'mkdir -p /tmp/.ansible/tmp/ansible-1382620281.22-259647948671173 && echo /tmp/.ansible/tmp/ansible-1382620281.22-259647948671173'
<ndcpeh661> REMOTE_MODULE async_status jid=658017273616
<ndcpeh661> PUT /tmp/tmp8bIdnO TO /tmp/.ansible/tmp/ansible-1382620281.22-259647948671173/async_status
<ndcpeh661> EXEC /bin/sh -c '/usr/bin/python /tmp/.ansible/tmp/ansible-1382620281.22-259647948671173/async_status; rm -rf /tmp/.ansible/tmp/ansible-1382620281.22-259647948671173/ >/dev/null 2>&1'
<job 658017273616> polling, 1270s remaining
<ndcpeh661> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO ndcpeh661
<ndcpeh661> EXEC /bin/sh -c 'mkdir -p /tmp/.ansible/tmp/ansible-1382620291.41-32746599350756 && echo /tmp/.ansible/tmp/ansible-1382620291.41-32746599350756'
<ndcpeh661> REMOTE_MODULE async_status jid=658017273616
<ndcpeh661> PUT /tmp/tmpJ6E1z8 TO /tmp/.ansible/tmp/ansible-1382620291.41-32746599350756/async_status
<ndcpeh661> EXEC /bin/sh -c '/usr/bin/python /tmp/.ansible/tmp/ansible-1382620291.41-32746599350756/async_status; rm -rf /tmp/.ansible/tmp/ansible-1382620291.41-32746599350756/ >/dev/null 2>&1'
<job 658017273616> polling, 1265s remaining

--- ps from host
root@ndcpeh661 # /usr/ucb/ps auxwww | grep -i install
root     14827  0.0  0.0 1744 1392 pts/1    S 13:09:38  0:00 grep -i install
root@ndcpeh661 # /usr/ucb/ps auxwww | grep ans
root     14931  0.0  0.0 1744 1264 pts/1    S 13:10:40  0:00 grep ans

**Comment by jimi-c** [comment] 2013-10-24 16:37
Closing, exact dupe of #4667.

**Closed as completed by jimi-c** 2013-10-24 16:37 UTC
