### ISSUE TITLE
{{ foo }} not working in vars_files with foo defined in other var file

### ISSUE THREAD

**Issue by tyll** [ansible/ansible#5629] opened 2014-01-15 14:32 UTC
This playbook does not work, because dist_tag is not defined. It works with the commented, deprecated entry:

```
#$ cat vars/CentOS.yml
#---
#dist_release: "{{ ansible_distribution_version[0] }}"
#dist_tag: "el{{ dist_release }}"
#$cat global.yml
#---
#vars: "."
#---
- hosts: example
  vars_files:
    - global.yml
    # Not working:
    - "{{ vars }}/{{ ansible_distribution }}.yml"
    # Working, but deprecated:
    #- "{{ vars }}/${ansible_distribution}.yml"
  user: till
  sudo: True
  tasks:
    # acpid required for proper shutdown with libvirt
    - name: install acpid
      action: yum pkg=acpid state=latest
      when: dist_tag == "el6"
```

**Comment by mpdehaan** [comment] 2014-01-15 14:56
Can you rename this to another variable other than vars to see if this still occurs?  Vars has special meaning in Ansible.

Further, per contributing.md, please share the Ansible version you are using.

Thanks!

**Comment by tyll** [comment] 2014-01-15 15:13
On Wed, Jan 15, 2014 at 06:56:41AM -0800, Michael DeHaan wrote:

> Can you rename this to another variable other than vars to see if this still occurs?  Vars has special meaning in Ansible.

Yes, it occurs with "foo" instead of "vars" as well.

> Further, per contributing.md, please share the Ansible version you are using.

Sorry, I meant to mention that it is current git, e.g.:
332d3d6a0ee2bd1778c4cee15277d48e23f1bbc3

**Comment by DaddyOh** [comment] 2014-01-25 20:17
I have the same problem with some group_vars not resolving. Mac OS X 
ansible: 1.4.1

**Comment by DaddyOh** [comment] 2014-01-25 20:23
this happens on mac 1.4.4 also

**Comment by jimi-c** [comment] 2015-06-18 14:04
Hi @tyll, going back through older issues, and I see the issue here is most likely the fact that the vars_files entries can't use inventory variables (which ansible_distribution is).  Can you confirm if this happens with other non-inventory variables?

**Comment by vivekchauhan** [comment] 2015-08-13 09:30
I was facing a problem which is related to this issue which is detailed here with an example.
The version of Ansible is **1.9.2** on Yosemite (Mac)

_Layout Structure_
playbook
- inventory
  - group_vars
- roles

Content of **inventory** file

```
[group1]
xyz.tld ansible_ssh_user=root

[group2]
xyz.tld ansible_ssh_user=root
```

Now there are two files inside **group_vars** folder in the inventory named
- group1.yml
- group2.yml

having exactly same keys with different values

When the following command is executed for the second case
`ansible-playbook -i inventory group2.yml` 
It still picks up the values for group1.yml file present in **group_vars** directory.

The root cause here was that the host was same for both groups.

**Comment by jimi-c** [comment] 2015-08-15 12:05
@vivekchauhan yes, you can't re-use hostnames, they're unique keys into the inventory, so the second entry causes the first to be overwritten. I believe there was an issue already to potentially raise an error if a second host entry is found to alert the user of the situation.

**Comment by jimi-c** [comment] 2015-08-15 12:06
Seeing as there has been no follow-up on this, we're going to close the issue as expected behavior with respect to inventory variables as noted above.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-08-15 12:06 UTC
Labels: needs_info, bug
