### ISSUE TITLE
unable to install collections from requirements.yml file

### ISSUE THREAD

**Issue by chrobotm** [ansible/ansible#72675] opened 2020-11-19 15:07 UTC
##### SUMMARY
Ansible collections don't seem to be installing from requirements.yml using ansible-galaxy install -r requirements.yml

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
2.9.6
```

##### OS / ENVIRONMENT

Ubuntu 20.04

##### STEPS TO REPRODUCE

requirements.yml file with the following content

```
---

collections:
  - name: devsec.hardening
    source: https://galaxy.ansible.com
```

running `ansible-galaxy install -r requirements.yml` doesn't install the collections

running `ansible-galaxy collection install -r requirements.yml` works fine
##### EXPECTED RESULTS

Collections install

##### ACTUAL RESULTS

collections don't install

**Comment by sivel** [comment] 2020-11-19 15:11
Duplicate of https://github.com/ansible/ansible/issues/72596

The ability to install both roles and collections using a requirements file with a single command is only present in Ansible 2.10+.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Closed as completed by sivel** 2020-11-19 15:11 UTC
