### ISSUE TITLE
regex_replace with backrefs: different behaviour with python 3.6 and python 3.7

### ISSUE THREAD

**Issue by anxstj** [ansible/ansible#70412] opened 2020-07-01 14:36 UTC
##### SUMMARY

regex_replace has a different behaviour if executed with Python 3.6 or Python 3.7/3.8.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
regex_replace

##### ANSIBLE VERSION

```paste below
ansible 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

I have tested it with different versions of alpine linux in docker containers, but initially, this came up on a Fedora 32 host.

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  gather_facts: false

  vars:
    host_key_types: 'rsa'
    sshd_config_path: /usr/local/sshd

  tasks:
    - debug:
        msg: "{{ host_key_types | regex_replace('(.*)', sshd_config_path+'/ssh_host_\\1_key') }}"
```

##### EXPECTED RESULTS

The `host_key_types` should be appended to the `sshd_config_path`. This is simplest use case I could come up with to demonstrate the issue. It's not the actual problem I try to solve.

```
# ansible --version
ansible 2.9.10
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.9 (default, Oct 17 2019, 11:10:22) [GCC 8.3.0]
# ansible-playbook test2.yml
PLAY [localhost] *************************************************************

TASK [debug] ****************************************************************
ok: [localhost] => {
    "msg": "/usr/local/sshd/ssh_host_rsa_key"
}
```

##### ACTUAL RESULTS

The `sshd_config_path` is added twice to the returned string.

```paste below
# ansible --version
ansible 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]
# ansible-playbook test2.yml 

PLAY [localhost] ****************************************************************

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "/usr/local/sshd/ssh_host_rsa_key/usr/local/sshd/ssh_host__key"
}
```

**Comment by sivel** [comment] 2020-07-01 14:47
Duplicate of https://github.com/ansible/ansible/issues/63329

**Closed as completed by sivel** 2020-07-01 14:47 UTC
