### ISSUE TITLE
Variable expansion has changed when doing 'with_items' with the 'package' module

### ISSUE THREAD

**Issue by kees-closed** [ansible/ansible#27037] opened 2017-07-19 11:39 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
package

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

##### CONFIGURATION
No special configs in the scope of this bug.

##### OS / ENVIRONMENT
Ansible is ran from Fedora 25/26, managing hosts on Fedora 25/26 and Debian.

##### SUMMARY
When I used Ansible 2.2 I used group_vars to have common software package lists which I then used with the module 'package' to install them on RPM and DEB based systems. That way I didn't have to duplicate any package lists for the modules 'dnf' and 'apt' and also didn't have to administrate separate lists.

Now since 2.3 this has changed. It now checks these packages one-by-one when using these vars with the 'with_items' iteration function. I think [this](https://github.com/ansible/ansible/commit/c005ae3cd95bca0267f57e26abcbe0b8e128c8fd) commit is responsible for this new behavior. This kind of makes the 'package' module unfit now to be used as a universal module for all supported package managers... Please revert this change and fix whatever problems the expansion of variables creates, because disabling a feature isn't a fix in my opinion (nor a feature).

##### STEPS TO REPRODUCE
Create a group_var for a role and include e.g. the following.
```
ansible_dependencies_fedora:
  - python-dnf
  - libselinux-python
  - libsemanage-python
  - policycoreutils-python
```
Then use this variable in the appropriate role and expand it with the 'with_items' function within the 'package' module.
```
- name: install ansible dependencies
  package: name={{ item }} state=present
  with_items:
    - "{{ ansible_dependencies_fedora }}"
  when: ansible_distribution == "Fedora"
  tags:
    - setup_ansible
    - install_packages
```

##### EXPECTED RESULTS
In Ansible 2.2 this worked fine and this is desirable because the advantage of using variable expansion with a universal module for package management is to use a single set of packages for multiple systems with different package dependency solvers.

##### ACTUAL RESULTS
It iterates the items one-by-one instead of treating the expansion as one entire set of items. It's working fine when e.g. using the module 'dnf', but of course stating the explicit module for every package dependency solver results in duplication of this list. Which defeats the purpose of having a universal package module.

I've reverted the change of commit c005ae3cd95bca0267f57e26abcbe0b8e128c8fd manually on my system. Now everything works again as expected, please make this work again as it did in Ansible 2.2!

**Comment by bcoca** [comment] 2017-07-19 15:27
What you are seeing is the 'magic of squashing', this is a feature that affects specific modules that allow for taking a list. Under certain conditions Ansible then 'optimizes' the loop by passing the full list to the module, since Ansible does not know ahead of time if modules support this we list them in a configurable setting http://docs.ansible.com/ansible/intro_configuration.html#squash-actions.

the difference you are hitting is because `package` was initially added to the default, but we had to remove as not all 'package modules' supported it. This changed existing behaviour, but the choice was between playbooks breaking and playbooks not being 'optimal' so we chose the latter.

So the fix for you might just be adding `package` to this config, as such, this is not a bug and I'm closing the issue.

**Closed as completed by bcoca** 2017-07-19 15:27 UTC
Labels: affects_2.3, module, needs_maintainer, support:core, bug
