### ISSUE TITLE
Warn on empty role

### ISSUE THREAD

**Issue by KellerFuchs** [ansible/ansible#23837] opened 2017-04-20 21:08 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - role

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/overrides
  python version = 2.7.13 (default, Dec 21 2016, 07:16:46) [GCC 6.2.1 20160830]
```

##### OS / ENVIRONMENT

Arch Linux

##### SUMMARY

Roles where the directory `roles/${role_name}` exists but if empty are silently ignored.

##### STEPS TO REPRODUCE

0. Be @lrvick
1. Forget to run `git submodules update --init`
2. Call a playbook that uses role from the missing submodules

##### EXPECTED RESULTS

Ansible warns about the role being empty.

##### ACTUAL RESULTS

Missing roles are silently ignored.

**Comment by KellerFuchs** [comment] 2017-04-20 23:11
@lrvick If you could give a minimal reproducer, that would be cool.
I can't provide the logs for it since I'm not running Ansible 2.3 (though I would expect the issue to occur through 2.x)

**Comment by bcoca** [comment] 2017-04-21 01:37
roles are allowed to not have task/vars/other ... having a noop is not an error

**Comment by KellerFuchs** [comment] 2017-04-21 05:37
Right, I thought of that, fixed the issue title but not “expected result”.

**Comment by robinro** [comment] 2017-04-21 13:21
This is a duplicate of #15802.

@bcoca I agree this is not an error, but a warning if the folder does contain none of `tasks`, `vars`, `meta`, `handerls` would be helpful.

**Comment by bcoca** [comment] 2017-04-21 15:41
closing as dupe of above

**Closed as completed by bcoca** 2017-04-21 15:41 UTC
Labels: affects_2.3, bug
