### ISSUE TITLE
Lookup in vars file traceback (if invalid file path supplied to lookup)

### ISSUE THREAD

**Issue by nickstenning** [ansible/ansible#5014] opened 2013-11-22 14:09 UTC
Consider the following `group_vars/all.yml`:

``` yaml

---
users_active:
  - name: foo
    group: foo
    authorized:
      - "{{ lookup('file', 'path/to/pubkey.pub') }}"
```

And the following playbook

``` yaml

---
- hosts: all
  tasks:
    - name: DEBUG users
      action: debug msg="{{ item }}"
      with_items: users_active
```

I would expect output similar to the following (assuming `path/to/pubkey.pub` was correct):

```
PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [XX.XX.XX.XX]

TASK: [DEBUG users] ***********************************************************
ok: [XX.XX.XX.XX] => (item={'group': 'foo', 'name': 'foo', 'authorized': ['ssh-rsa AAAAB3Nza...dCOw== foo']}) => {
    "item": {
        "authorized": [
            "ssh-rsa AAAAB3Nza...dCOw== foo"
        ],
        "group": "foo",
        "name": "foo"
    },
    "msg": "{'group': 'foo', 'name': 'foo', 'authorized': ['ssh-rsa AAAAB3Nza...dCOw== foo']}"
}

PLAY RECAP ********************************************************************
XX.XX.XX.XX             : ok=2    changed=0    unreachable=0    failed=0
```

Instead, I see output as below. It seems that using a lookup in `group_vars/all.yml` completely breaks `with_items` to the extent that it no longer correctly retrieves the structured data for the items:

```
PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [XX.XX.XX.XX]

TASK: [DEBUG users] ***********************************************************
ok: [XX.XX.XX.XX] => (item=users_active) => {
    "item": "users_active",
    "msg": "users_active"
}

PLAY RECAP ********************************************************************
XX.XX.XX.XX             : ok=2    changed=0    unreachable=0    failed=0
```

If you now edit the vars file and replace the lookup with a simple string public key, the output will be as expected (the first playbook run above).

_Tested with Ansible 1.3.4 and 1.4_

**Comment by nickstenning** [comment] 2013-11-22 14:54
So, on further experiment, it seems this works absolutely _fine_ if you get the path to the file correct, but if you get the path to the file incorrect, the behaviour above is seen.

To my mind, while that invalidates my original bug report, it's worth keeping this open in order to fix the horrible (i.e. non-existent) error reporting in this case.

**Comment by mpdehaan** [comment] 2013-11-22 15:48
It would probably be better if we close this ticket and you open a ticket about the error message, or edit this one.

Thanks!

**Comment by jimi-c** [comment] 2014-02-10 19:58
I believe the issue here is being caused by the debug: msg="" part, since if you do `debug: var=` syntax instead you see the following (which is what I'd expect):

<pre>
PLAY [localhost] ************************************************************** 
TASK: [DEBUG users] *********************************************************** 
fatal: [127.0.0.1] => /root/testing/path/to/pubkey.pub does not exist
FATAL: all hosts have already failed -- aborting
PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/5014.retry
127.0.0.1                  : ok=0    changed=0    unreachable=1    failed=0   
</pre>

And with a correct path, the variable `{{item}}` is shown correctly with the contents of the file. This is most likely because the msg="" syntax does not correctly template out/etc. the item variable, which is not necessarily a bug, since that is what the var="" syntax is for now.

Based on this, I'm going to go ahead and close this issue. If you continue having issues, or if you have any other questions related to this, please let us know. Thanks!

**Closed as completed by jimi-c** 2014-02-10 19:58 UTC
Labels: bug
