### ISSUE TITLE
bash forloops are not executed remotely yet success is returned

### ISSUE THREAD

**Issue by kinvaris** [ansible/ansible#16540] opened 2016-07-01 08:26 UTC
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/lib/ansible']
```
##### CONFIGURATION

```
[defaults]
inventory      = /etc/ansible/hosts
library        = /usr/lib/ansible
forks          = 200
host_key_checking = False
callback_whitelist = profile_tasks
```
##### OS / ENVIRONMENT

```
Linux mon01 4.2.0-38-generic #45~14.04.1-Ubuntu SMP Thu Jun 9 09:27:51 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
##### SUMMARY

When trying to execute a for loop through the `ansible` command, it returns a success but nothing has happened on the remote nodes.

```
ops@mon01:~$ ansible storagenodes -m shell -a "for i in $(initctl list | grep alba-maint); do start $i; done" -u root -k
SSH password: 
cap-roub-02 | SUCCESS | rc=0 >>


cap-grav-04 | SUCCESS | rc=0 >>


cap-grav-06 | SUCCESS | rc=0 >>

...
```
##### STEPS TO REPRODUCE

`ansible storagenodes -m shell -a "for i in $(initctl list | grep alba-maint); do start $i; done`
##### EXPECTED RESULTS

remote execution
##### ACTUAL RESULTS

```
ops@mon01:~$ ansible storagenodes -m shell -a "for i in $(initctl list | grep alba-maint); do start $i; done" -u root -k -vvvv
Using /etc/ansible/ansible.cfg as config file
SSH password: 
Loaded callback minimal of type stdout, v2.0
<51.254.43.38> ESTABLISH SSH CONNECTION FOR USER: root
<51.254.43.37> ESTABLISH SSH CONNECTION FOR USER: root
<5.196.86.54> ESTABLISH SSH CONNECTION FOR USER: root
<51.254.43.39> ESTABLISH SSH CONNECTION FOR USER: root
<5.196.86.55> ESTABLISH SSH CONNECTION FOR USER: root
<5.196.85.28> ESTABLISH SSH CONNECTION FOR USER: root
<5.135.130.4> ESTABLISH SSH CONNECTION FOR USER: root
<5.135.130.3> ESTABLISH SSH CONNECTION FOR USER: root
<5.135.130.5> ESTABLISH SSH CONNECTION FOR USER: root
<51.254.43.37> SSH: EXEC sshpass -d28 ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ops/.ansible/cp/ansible-ssh-%h-%p-%r 51.254.43.37 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1467361550.96-224220335382273 `" && echo ansible-tmp-1467361550.96-224220335382273="` echo $HOME/.ansible/tmp/ansible-tmp-1467361550.96-224220335382273 `" ) && sleep 0'"'"''
<51.254.43.38> SSH: EXEC sshpass -d29 ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ops/.ansible/cp/ansible-ssh-%h-%p-%r 51.254.43.38 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1467361550.96-182801196017872 `" && echo ansible-tmp-1467361550.96-182801196017872="` echo $HOME/.ansible/tmp/ansible-tmp-1467361550.96-182801196017872 `" ) && sleep 0'"'"''
<51.254.43.39> SSH: EXEC sshpass -d30 ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ops/.ansible/cp/ansible-ssh-%h-%p-%r 51.254.43.39 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1467361550.96-248845277282550 `" && echo ansible-tmp-1467361550.96-248845277282550="` echo $HOME/.ansible/tmp/ansible-tmp-1467361550.96-248845277282550 `" ) && sleep 0'"'"''
<5.196.86.55> SSH: EXEC sshpass -d33 ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ops/.ansible/cp/ansible-ssh-%h-%p-%r 5.196.86.55 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1467361550.96-154827651245633 `" && echo ansible-tmp-1467361550.96-154827651245633="` echo $HOME/.ansible/tmp/ansible-tmp-1467361550.96-154827651245633 `" ) && sleep 0'"'"''
<5.196.86.54> SSH: EXEC sshpass -d32 ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ops/.ansible/cp/ansible-ssh-%h-%p-%r 5.196.86.54 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1467361550.96-140338349091932 `" && echo ansible-tmp-1467361550.96-140338349091932="` echo $HOME/.ansible/tmp/ansible-tmp-1467361550.96-140338349091932 `" ) && sleep 0'"'"''
<5.135.130.3> SSH: EXEC sshpass -d34 ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ops/.ansible/cp/ansible-ssh-%h-%p-%r 5.135.130.3 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1467361550.96-145754047544167 `" && echo ansible-tmp-1467361550.96-145754047544167="` echo $HOME/.ansible/tmp/ansible-tmp-1467361550.96-145754047544167 `" ) && sleep 0'"'"''
<5.135.130.4> SSH: EXEC sshpass -d35 ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ops/.ansible/cp/ansible-ssh-%h-%p-%r 5.135.130.4 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1467361550.96-113886335856495 `" && echo ansible-tmp-1467361550.96-113886335856495="` echo $HOME/.ansible/tmp/ansible-tmp-1467361550.96-113886335856495 `" ) && sleep 0'"'"''
<5.196.85.28> SSH: EXEC sshpass -d31 ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ops/.ansible/cp/ansible-ssh-%h-%p-%r 5.196.85.28 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1467361550.96-43272494492184 `" && echo ansible-tmp-1467361550.96-43272494492184="` echo $HOME/.ansible/tmp/ansible-tmp-1467361550.96-43272494492184 `" ) && sleep 0'"'"''
<5.135.130.5> SSH: EXEC sshpass -d36 ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ops/.ansible/cp/ansible-ssh-%h-%p-%r 5.135.130.5 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1467361550.96-204439665300915 `" && echo ansible-tmp-1467361550.96-204439665300915="` echo $HOME/.ansible/tmp/ansible-tmp-1467361550.96-204439665300915 `" ) && sleep 0'"'"''
<5.196.86.55> PUT /tmp/tmp8nUKKw TO /root/.ansible/tmp/ansible-tmp-1467361550.96-154827651245633/command
<5.196.86.55> SSH: EXEC sshpass -d33 sftp -o BatchMode=no -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ops/.ansible/cp/ansible-ssh-%h-%p-%r '[5.196.86.55]'
<51.254.43.38> PUT /tmp/tmpGobJ2Z TO /root/.ansible/tmp/ansible-tmp-1467361550.96-182801196017872/command
<51.254.43.38> SSH: EXEC sshpass -d29 sftp -o BatchMode=no -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ops/.ansible/cp/ansible-ssh-%h-%p-%r '[51.254.43.38]'
<5.196.86.55> ESTABLISH SSH CONNECTION FOR USER: root
<5.196.86.55> SSH: EXEC sshpass -d33 ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ops/.ansible/cp/ansible-ssh-%h-%p-%r -tt 5.196.86.55 '/bin/sh -c '"'"'LANG=en_GB.UTF-8 LC_ALL=en_GB.UTF-8 LC_MESSAGES=en_GB.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1467361550.96-154827651245633/command; rm -rf "/root/.ansible/tmp/ansible-tmp-1467361550.96-154827651245633/" > /dev/null 2>&1 && sleep 0'"'"''
<51.254.43.38> ESTABLISH SSH CONNECTION FOR USER: root
<51.254.43.38> SSH: EXEC sshpass -d29 ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ops/.ansible/cp/ansible-ssh-%h-%p-%r -tt 51.254.43.38 '/bin/sh -c '"'"'LANG=en_GB.UTF-8 LC_ALL=en_GB.UTF-8 LC_MESSAGES=en_GB.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1467361550.96-182801196017872/command; rm -rf "/root/.ansible/tmp/ansible-tmp-1467361550.96-182801196017872/" > /dev/null 2>&1 && sleep 0'"'"''
<5.196.85.28> PUT /tmp/tmpo18HUA TO /root/.ansible/tmp/ansible-tmp-1467361550.96-43272494492184/command
<5.196.85.28> SSH: EXEC sshpass -d31 sftp -o BatchMode=no -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ops/.ansible/cp/ansible-ssh-%h-%p-%r '[5.196.85.28]'
<5.196.85.28> ESTABLISH SSH CONNECTION FOR USER: root
<5.196.85.28> SSH: EXEC sshpass -d31 ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ops/.ansible/cp/ansible-ssh-%h-%p-%r -tt 5.196.85.28 '/bin/sh -c '"'"'LANG=en_GB.UTF-8 LC_ALL=en_GB.UTF-8 LC_MESSAGES=en_GB.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1467361550.96-43272494492184/command; rm -rf "/root/.ansible/tmp/ansible-tmp-1467361550.96-43272494492184/" > /dev/null 2>&1 && sleep 0'"'"''
<5.135.130.5> PUT /tmp/tmpMSzTv1 TO /root/.ansible/tmp/ansible-tmp-1467361550.96-204439665300915/command
<5.135.130.5> SSH: EXEC sshpass -d36 sftp -o BatchMode=no -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ops/.ansible/cp/ansible-ssh-%h-%p-%r '[5.135.130.5]'
cap-grav-06 | SUCCESS | rc=0 >>


cap-roub-02 | SUCCESS | rc=0 >>


cap-grav-04 | SUCCESS | rc=0 >>


<5.135.130.5> ESTABLISH SSH CONNECTION FOR USER: root
<5.135.130.5> SSH: EXEC sshpass -d36 ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ops/.ansible/cp/ansible-ssh-%h-%p-%r -tt 5.135.130.5 '/bin/sh -c '"'"'LANG=en_GB.UTF-8 LC_ALL=en_GB.UTF-8 LC_MESSAGES=en_GB.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1467361550.96-204439665300915/command; rm -rf "/root/.ansible/tmp/ansible-tmp-1467361550.96-204439665300915/" > /dev/null 2>&1 && sleep 0'"'"''
cap-stras-09 | SUCCESS | rc=0 >>


<51.254.43.39> PUT /tmp/tmpPXtKc2 TO /root/.ansible/tmp/ansible-tmp-1467361550.96-248845277282550/command
<51.254.43.39> SSH: EXEC sshpass -d30 sftp -o BatchMode=no -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ops/.ansible/cp/ansible-ssh-%h-%p-%r '[51.254.43.39]'
<5.196.86.54> PUT /tmp/tmp_TqbJY TO /root/.ansible/tmp/ansible-tmp-1467361550.96-140338349091932/command
<5.196.86.54> SSH: EXEC sshpass -d32 sftp -o BatchMode=no -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ops/.ansible/cp/ansible-ssh-%h-%p-%r '[5.196.86.54]'
<5.135.130.4> PUT /tmp/tmp4GI9Fw TO /root/.ansible/tmp/ansible-tmp-1467361550.96-113886335856495/command
<5.135.130.4> SSH: EXEC sshpass -d35 sftp -o BatchMode=no -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ops/.ansible/cp/ansible-ssh-%h-%p-%r '[5.135.130.4]'
<51.254.43.37> PUT /tmp/tmpTBszFs TO /root/.ansible/tmp/ansible-tmp-1467361550.96-224220335382273/command
<51.254.43.37> SSH: EXEC sshpass -d28 sftp -o BatchMode=no -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ops/.ansible/cp/ansible-ssh-%h-%p-%r '[51.254.43.37]'
<5.135.130.3> PUT /tmp/tmp8dXy71 TO /root/.ansible/tmp/ansible-tmp-1467361550.96-145754047544167/command
<5.135.130.3> SSH: EXEC sshpass -d34 sftp -o BatchMode=no -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ops/.ansible/cp/ansible-ssh-%h-%p-%r '[5.135.130.3]'
<5.135.130.3> ESTABLISH SSH CONNECTION FOR USER: root
<5.135.130.3> SSH: EXEC sshpass -d34 ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ops/.ansible/cp/ansible-ssh-%h-%p-%r -tt 5.135.130.3 '/bin/sh -c '"'"'LANG=en_GB.UTF-8 LC_ALL=en_GB.UTF-8 LC_MESSAGES=en_GB.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1467361550.96-145754047544167/command; rm -rf "/root/.ansible/tmp/ansible-tmp-1467361550.96-145754047544167/" > /dev/null 2>&1 && sleep 0'"'"''
<51.254.43.39> ESTABLISH SSH CONNECTION FOR USER: root
<51.254.43.39> SSH: EXEC sshpass -d30 ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ops/.ansible/cp/ansible-ssh-%h-%p-%r -tt 51.254.43.39 '/bin/sh -c '"'"'LANG=en_GB.UTF-8 LC_ALL=en_GB.UTF-8 LC_MESSAGES=en_GB.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1467361550.96-248845277282550/command; rm -rf "/root/.ansible/tmp/ansible-tmp-1467361550.96-248845277282550/" > /dev/null 2>&1 && sleep 0'"'"''
<5.196.86.54> ESTABLISH SSH CONNECTION FOR USER: root
<5.196.86.54> SSH: EXEC sshpass -d32 ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ops/.ansible/cp/ansible-ssh-%h-%p-%r -tt 5.196.86.54 '/bin/sh -c '"'"'LANG=en_GB.UTF-8 LC_ALL=en_GB.UTF-8 LC_MESSAGES=en_GB.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1467361550.96-140338349091932/command; rm -rf "/root/.ansible/tmp/ansible-tmp-1467361550.96-140338349091932/" > /dev/null 2>&1 && sleep 0'"'"''
cap-stras-07 | SUCCESS | rc=0 >>


<5.135.130.4> ESTABLISH SSH CONNECTION FOR USER: root
<5.135.130.4> SSH: EXEC sshpass -d35 ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ops/.ansible/cp/ansible-ssh-%h-%p-%r -tt 5.135.130.4 '/bin/sh -c '"'"'LANG=en_GB.UTF-8 LC_ALL=en_GB.UTF-8 LC_MESSAGES=en_GB.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1467361550.96-113886335856495/command; rm -rf "/root/.ansible/tmp/ansible-tmp-1467361550.96-113886335856495/" > /dev/null 2>&1 && sleep 0'"'"''
cap-roub-03 | SUCCESS | rc=0 >>


cap-grav-05 | SUCCESS | rc=0 >>


<51.254.43.37> ESTABLISH SSH CONNECTION FOR USER: root
<51.254.43.37> SSH: EXEC sshpass -d28 ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ops/.ansible/cp/ansible-ssh-%h-%p-%r -tt 51.254.43.37 '/bin/sh -c '"'"'LANG=en_GB.UTF-8 LC_ALL=en_GB.UTF-8 LC_MESSAGES=en_GB.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1467361550.96-224220335382273/command; rm -rf "/root/.ansible/tmp/ansible-tmp-1467361550.96-224220335382273/" > /dev/null 2>&1 && sleep 0'"'"''
cap-stras-08 | SUCCESS | rc=0 >>


cap-roub-01 | SUCCESS | rc=0 >>
```

**Comment by jctanner** [comment] 2016-07-01 14:44
@kinvaris please try with this loop command ...

```
"for i in \$(seq 1 10); do echo \$i; done"
```

**Comment by bcoca** [comment] 2016-07-01 15:31
or use single quotes, otherwise your shellism will be interpolated 'locally' before ansible even gets the string.

**Comment by kinvaris** [comment] 2016-07-07 09:27
@jctanner that did work indeed, thanks for the insight!

**Comment by bcoca** [comment] 2016-07-07 13:14
I'm going to close this as it is not a bug, but a misinterpretation of how the local shell was acting.

**Closed as completed by bcoca** 2016-07-07 13:14 UTC
Labels: bug
