### ISSUE TITLE
tags not working on post_tasks include?

### ISSUE THREAD

**Issue by davestern** [ansible/ansible#4750] opened 2013-10-31 17:55 UTC
I have this playbook:

```

---
# Admin Playbook
- hosts: admin
  user: username
  sudo: yes
  roles:
    - common
    - admin
  post_tasks:
    - include: roles/admin/tasks/test.yml tags=test
```

But when I try to run just the tests, I get this output:

```
$ ansible-playbook -i hosts playbook-admin.yml -t test
ERROR: tag(s) not found in playbook: test.  possible values: apache,config,crontab
```

Tags do not appear to work in post_tasks: include files

**Comment by mpdehaan** [comment] 2013-10-31 22:48
Testing this now.

In the future please report what version of Ansible you are running when filing tickets.  Thanks!

**Comment by mpdehaan** [comment] 2013-10-31 22:50
I can't reproduce this on 1.4 devel so I'm going to mark this as closed.

1.4 will be released towards the later half of next month (shooting for 11/20)

**Closed as completed by mpdehaan** 2013-10-31 22:50 UTC
Labels: needs_info, bug

**Comment by davestern** [comment] 2013-11-01 17:01
My apologies. I'm on 1.3.x (not at my other computer, don't know the rev). I'll add this in any future requests. Thanks for handling this! I can workaround it until 1.4 is out.
