### ISSUE TITLE
Problem with user module under FreeBSD when append=yes

### ISSUE THREAD

**Issue by tronner** [ansible/ansible#4461] opened 2013-10-11 16:36 UTC
The user module uses a list operation (extend) on a set, which causes ansible to crash (stacktrace). I will create a pull request.

**Comment by tronner** [comment] 2013-10-11 16:41
Hmm, I think just a pull request was enough. Now it created two issues. Sorry about that; I'm new to github :)

**Comment by jctanner** [comment] 2013-10-18 13:21
Duplicate of #4560

**Closed as completed by jctanner** 2013-10-18 13:21 UTC
Labels: bug, bsd
