### ISSUE TITLE
local_action file is not working correctly if ansible_ssh_host is defined

### ISSUE THREAD

**Issue by orderedchaosdev** [ansible/ansible#14914] opened 2016-03-11 05:40 UTC
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.1.0 (devel 8a42f3417c) last updated 2016/03/10 19:46:04 (GMT -700)
  lib/ansible/modules/core: (detached HEAD c86a0ef84a) last updated 2016/03/10 19:46:04 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 33a557cc59) last updated 2016/03/10 19:46:03 (GMT -700)
```
##### Ansible Configuration:

```
[defaults]
forks=24
transport=ssh
[ssh_connection]
pipelining=true
ssh_args=-o StrictHostKeyChecking=true
```
##### Environment:

Centos 6 up to date
##### Summary:

If ansible_ssh_host is defined then local_action: file fails
##### Steps To Reproduce:

production

```
host-1 ansible_ssh_host=192.168.1.5
```

```

---
- name: testing
  hosts: host-1
  tasks:
    - local_action: file dest=~/thisdir state=directory
```
##### Expected Results:

I expect it to create ~/thisdir if it doesn't exist on the local machine
##### Actual Results:

```
TASK [file] ********************************************************************
<111.111.111.111> ESTABLISH SSH CONNECTION FOR USER: servermgr
<111.111.111.111> SSH: EXEC ssh -C -vvv -o StrictHostKeyChecking=true -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=servermgr -o ConnectTimeout=10 192.168.1.5 '/bin/sh -c '"'"'LANG=en_US.utf8 LC_ALL=en_US.utf8 LC_MESSAGES=en_US.utf8 /usr/bin/python'"'"''
fatal: [host-1]: UNREACHABLE! => {"changed": false, "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", "unreachable": true}
```

**Comment by orderedchaosdev** [comment] 2016-03-11 05:41
just as a note if I instead use ansible_host then everything works as expected but ansible_ssh_host is only supposed to be deprecated not yet causing issues

**Comment by orderedchaosdev** [comment] 2016-03-16 21:24
Anyone else noticed this issue?

**Comment by bcoca** [comment] 2016-05-12 15:43
can you test with?:

```
- name: testing
  hosts: host-1
  gather_facts: no
  tasks:
    - local_action: file dest=~/thisdir state=directory
```

**Comment by jctanner** [comment] 2016-05-12 16:06
I am unable to reproduce this. I looked at all the factors given by the initial description:
- fact gathering doesn't seem to be in play because the failure example was in the task, not setup call
- transport = ssh in ansible.cfg does not override local_action in any version of ansible to date

The only way I could get local_action to force an ssh connection was to use -c ssh on the ansible command line.

**Comment by jimi-c** [comment] 2016-06-23 15:15
As there has been no follow-up on this for over a month and we were not able to reproduce the stated issue, we're going to go ahead and close this now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2016-06-23 15:15 UTC
Labels: bug
