### ISSUE TITLE
Provide a way for sanitizing item value in console output for with statement

### ISSUE THREAD

**Issue by fangpenlin** [ansible/ansible#8090] opened 2014-07-10 20:01 UTC
##### Issue Type:

Feature Idea
##### Ansible Version:

1.6.6
##### Environment:

N/A
##### Summary:

I developed a lookup plugin which is for pulling secret keys from the cloud server. However, when I use `with_secret` statement like this

``` yaml
- name: foo
  bar: secret={{ item }}
  with_secret: eggs/spam/secret.txt
```

and you will see something like this on the screen when you run ansible

```
ok: [default] => (item="MY_SUPER_SECRET_KEY_HERE")
```

I really don't like how this works, it displays your secret key on screen. If you redirect logging for ansible to a file or what, then all your secret keys are in the file now. 

And in other situations, like with_file, you may see something like

```
ok: [default] => (item="
thousand lines here
thousand lines here
thousand lines here
thousand lines here
thousand lines here
....
```

I think this is really bad for ansible to print literately everything it got from a lookup. So, I propose, for a lookup class, if a `sanitize` method is defined, ansible should then call the method for each item before printing it on the screen. So that for my secret getting lookup I can write something like this

``` python
def sanitize(self, item):
    return '*' * 8
```

And for huge file and other things, people can write something like

``` python
def sanitize(self, item):
    return 'File {} ({} bytes)'.format(item._filename, item._size)

def run(self, terms, inject=None, **kwargs):
    result = 'a long long long long file content'
    result._filename = terms
    result._size = len(result)
    return [result]
```
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by mahmoudimus** [comment] 2014-07-10 23:54
+1

**Comment by mpdehaan** [comment] 2014-07-11 12:46
We've actually proposed this already with making "no_log" hide the output, as well as disable remote syslog.  As a result, I'm going to close this as a duplicate of this idea, as we don't need to introduce new things for this and should be able to handle it with that parameter.

**Closed as completed by mpdehaan** 2014-07-11 12:46 UTC
Labels: feature

**Comment by mahmoudimus** [comment] 2014-07-11 18:35
@mpdehaan makes sense, after searching the github repository with `no_log`, I only found this issue, so linking here for reference's sake: https://github.com/ansible/ansible/pull/7642

If I missed any others, can you kindly link them on this issue?
