### ISSUE TITLE
mysql_user fails to delete user when reprovisioning.

### ISSUE THREAD

**Issue by CormacBracken** [ansible/ansible#4752] opened 2013-10-31 17:58 UTC
This task ran on first provision (when I assume there's no such user) but fails subsequently, with the output below.

However if I change /etc/hostname from ubuntu-64bit to ubuntu-sfbit, the task again runs correctly. It seems related to https://github.com/ansible/ansible/issues/4467 .

```
TASK: [mysql | delete the mysql root user for hostname] *********************** 
<dev.redhotlemon.com> ESTABLISH CONNECTION FOR USER: root
<dev.redhotlemon.com> EXEC ['ssh', '-tt', '-vvv', '-o', 'PasswordAuthentication=yes', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/tmp/ssh-%r@%h:%p', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', 'dev.redhotlemon.com', "/bin/sh -c 'mkdir -p /tmp/.ansible/ansible-1383171386.62-33641831700578 && echo /tmp/.ansible/ansible-1383171386.62-33641831700578'"]
<dev.redhotlemon.com> REMOTE_MODULE mysql_user user="root" host="Ubuntu-64bit" state="absent"
<dev.redhotlemon.com> PUT /tmp/tmpM9sm0s TO /tmp/.ansible/ansible-1383171386.62-33641831700578/mysql_user
<dev.redhotlemon.com> EXEC ['ssh', '-tt', '-vvv', '-o', 'PasswordAuthentication=yes', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/tmp/ssh-%r@%h:%p', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', 'dev.redhotlemon.com', "/bin/sh -c '/usr/bin/python /tmp/.ansible/ansible-1383171386.62-33641831700578/mysql_user; rm -rf /tmp/.ansible/ansible-1383171386.62-33641831700578/ >/dev/null 2>&1'"]

fatal: [dev.redhotlemon.com] => failed to parse: Traceback (most recent call last):
  File "/tmp/.ansible/ansible-1383171386.62-33641831700578/mysql_user", line 1400, in <module>
    main()
  File "/tmp/.ansible/ansible-1383171386.62-33641831700578/mysql_user", line 459, in main
    changed = user_delete(cursor, user, host)
  File "/tmp/.ansible/ansible-1383171386.62-33641831700578/mysql_user", line 210, in user_delete
    cursor.execute("DROP USER %s@%s", (user,host))
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.OperationalError: (1396, "Operation DROP USER failed for 'root'@'ubuntu-64bit'")
```

(The above output is from running 1.3.3, but I previously tested with 1.4 which failed at the same point with I believe the same output. )

**Comment by jctanner** [comment] 2013-10-31 18:05
@CormacBracken can you provide an example playbook I can use to reproduce this?

**Comment by CormacBracken** [comment] 2013-10-31 19:59
Of course (unfortunately it's a long one)

https://github.com/voceconnect/afterburner-ansible

**Comment by jctanner** [comment] 2013-11-11 21:08
@CormacBracken it seems like this issue really related to ansible_hostname doesn't match the user's hostname in the database. However, I can not reproduce the error with 1.3.3 or e2b75abb1dda5fd1ff3f7b6b2b5441992146c24d .

If you can, please try to simplify this down to a small reproducer.

**Comment by mpdehaan** [comment] 2013-12-01 22:22
Closing due to lack of a reproducer.

**Closed as completed by mpdehaan** 2013-12-01 22:22 UTC
Labels: needs_info, bug, mysql
