### ISSUE TITLE
ignore_errors with missings source files in synchronize module

### ISSUE THREAD

**Issue by hanswurscht** [ansible/ansible#11666] opened 2015-07-21 09:15 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

1.9.2
##### Ansible Configuration:

Clean setup
##### Environment:

Starting ansible-playbook from RHEL 6, targeting RHEL 6 and RHEL 7.
##### Summary:

missing source files in copy or synchronize module can't be caught with ignore_errors: yes.
##### Steps To Reproduce:

http://grokbase.com/t/gg/ansible-project/148w7rvbbe/how-to-sync-over-directories-that-exist-locally

```
- name: setup user home directories
    synchronize: src=homes/{{item.username}} dest=/home/{{item.username}}
          owner={{item.username}}
          group={{item.username}}
    with_items: ssh_users
    ignore_errors: yes
```

> So basically, I want it to copy a home directory for users that have one.
> Not everyone will have one because not everyone really needs, say, their
> own customized .vimrc, etc. In those cases, I'd like Ansible to just skip
> it.  
##### Expected Results:

Missing source files should be skipped
##### Actual Results:

```
TASK: [../users | setup user home directories]
********************************
fatal: [default] => input file not found at
/<redacted>/roles/users/files/homes/<redacted> or
<redacted>/roles/users/homes/<redacted>

FATAL: all hosts have already failed -- aborting
```

**Comment by bcoca** [comment] 2015-07-21 22:16
# Can You Help Us Out?

Thanks for filing a ticket! I am the friendly GitHub Ansibot.

It looks like you might not have filled out the issue description based on our standard issue template.  You might not have known about that, and that's ok too, we'll tell you how to do it.

We have a standard template because Ansible is a really busy project and it helps to have some standard information in each ticket, and GitHub doesn't yet provide a standard facility to do this like some other bug trackers.  We hope you understand as this is really valuable to us!.

Solving this is simple: please copy the contents of this [template](https://raw.githubusercontent.com/ansible/ansible/devel/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket.  That's it!

# If You Had A Question To Ask Instead

If you happened to have a "how do I do this in Ansible" type of question, that's probably more of a user-list question than a bug report, and you should probably ask this question on the project mailing list instead.

However, if you think you have a bug, the report is the way to go!  We definitely want all the bugs filed :)  Just trying to help!

# About Priority Tags

Since you're here, we'll also share some useful information at this time.

In general tickets will be assigned a priority between P1 (highest) and P5, and then worked in priority order. We may also have some follow up questions along the way, so keeping up with follow up comments via GitHub notifications is a good idea.

Due to large interest in Ansible, humans may not comment on your ticket immediately.

# Mailing Lists

If you have concerns or questions, you're welcome to stop by the ansible-project or ansible-development mailing lists, as appropriate.  Here are the links:
- https://groups.google.com/forum/#!forum/ansible-project - for discussion of bugs and how-to type questions
- https://groups.google.com/forum/#!forum/ansible-devel - for discussion on how to implement a code change, or feature brainstorming among developers

Thanks again for the interest in Ansible!

**Comment by abadger** [comment] 2016-01-26 20:48
Not able to reproduce this with a checkout of the 1.9.2 tag for either copy or synchronize.  Here's my playbook:

```
---
- hosts: rhel6-test
  vars:
    ssh_users:
    - {username: nonexistent}
    - {username: nothere}
    - {username: noonearound}
  tasks:
  - file:
      path: /nonexistent
      state: absent
  - synchronize: src=homes/{{item.username}} dest=/home/{{item.username}}
    with_items: ssh_users
    ignore_errors: yes
  - copy: src=homes/{{item.username}} dest=/home/{{item.username}} owner={{item.username}} group={{item.username}}
    with_items: ssh_users
    ignore_errors: yes

$ ansible-playbook 11666.yml                                     (12:38:19)

PLAY [rhel6-test] ************************************************************* 

GATHERING FACTS *************************************************************** 
ok: [rhel6-test]

TASK: [file ] ***************************************************************** 
ok: [rhel6-test]

TASK: [synchronize src=homes/{{item.username}} dest=/home/{{item.username}}] *** 
failed: [rhel6-test -> 127.0.0.1] => (item={'username': 'nonexistent'}) => {"cmd": "rsync --delay-updates -F --compre
ss --archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no' --out-format='<<CHANGED>>%i %n%L' \"homes/nonexistent\"
 \"badger@rhel6-test:/home/nonexistent\"", "failed": true, "item": {"username": "nonexistent"}, "rc": 23}
msg: rsync: change_dir "/srv/ansible/troubleshooting//homes" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1165) [sender=3.1.1]

...ignoring
failed: [rhel6-test -> 127.0.0.1] => (item={'username': 'nothere'}) => {"cmd": "rsync --delay-updates -F --compress -
-archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no' --out-format='<<CHANGED>>%i %n%L' \"homes/nothere\" \"badge
r@rhel6-test:/home/nothere\"", "failed": true, "item": {"username": "nothere"}, "rc": 23}
msg: rsync: change_dir "/srv/ansible/troubleshooting//homes" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1165) [sender=3.1.1]

...ignoring
failed: [rhel6-test -> 127.0.0.1] => (item={'username': 'noonearound'}) => {"cmd": "rsync --delay-updates -F --compre
ss --archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no' --out-format='<<CHANGED>>%i %n%L' \"homes/noonearound\"
 \"badger@rhel6-test:/home/noonearound\"", "failed": true, "item": {"username": "noonearound"}, "rc": 23}
msg: rsync: change_dir "/srv/ansible/troubleshooting//homes" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1165) [sender=3.1.1]

...ignoring
TASK: [copy src=homes/{{item.username}} dest=/home/{{item.username}} owner={{item.username}} group={{item.username}}]
 *** 
failed: [rhel6-test] => (item={'username': 'nonexistent'}) => {"failed": true, "item": {"username": "nonexistent"}}
msg: could not find src=/srv/ansible/troubleshooting/homes/nonexistent
...ignoring
failed: [rhel6-test] => (item={'username': 'nothere'}) => {"failed": true, "item": {"username": "nothere"}}
msg: could not find src=/srv/ansible/troubleshooting/homes/nothere
...ignoring
failed: [rhel6-test] => (item={'username': 'noonearound'}) => {"failed": true, "item": {"username": "noonearound"}}
msg: could not find src=/srv/ansible/troubleshooting/homes/noonearound
...ignoring

PLAY RECAP ******************************************************************** 
rhel6-test                 : ok=4    changed=0    unreachable=0    failed=0 
```

Also tried with 2.0.0.2 and similarly the errors are ignored.

I'm going to close this as it all seems to work.  If it's still an issue you can ask about it on the mailing list or IRC channel or if you can see some important difference between your reproducer and my test case feel free to open a new ticket with the information on how to reproduce it.

**Closed as completed by abadger** 2016-01-26 20:48 UTC
Labels: needs_info
