### ISSUE TITLE
Long delay in ansible-playbook, strace shows loop that stats non-existing module-files

### ISSUE THREAD

**Issue by jensdepuydt** [ansible/ansible#10165] opened 2015-02-05 07:51 UTC
Issue type: bug report
Ansible version: 

```
[jendep@be-plw-ans-0001 ansible]$ ansible --version
ansible 1.8.2
  configured module search path = /etc/ansible/library
```

Environment:

```
[jendep@be-plw-ans-0001 ansible]$ cat /etc/centos-release
CentOS Linux release 7.0.1406 (Core)
[jendep@be-plw-ans-0001 ansible]$ uname -r
3.10.0-123.13.2.el7.x86_64
```

Summary:
We're using Ansible for quite a while now and for now we're very happy about it. 
Only one small thing is bothering me and it's that there's a delay between launching ansible-playbook and the actual process of deploying. For some reason, I suspected something related to SSH but finally I've made some time free to investigate the "issue" and I see with strace that there is a loop, searching for non-existing module files. After some debugging, I found out that the problem should be in "/usr/lib/python2.7/site-packages/ansible/playbook/play.py" but I can't seem to find what the exact problem is.

Steps to reproduce:
Execute ansible-playbook
For example:

```
[jendep@be-plw-ans-0001 ansible]$ /usr/bin/ansible-playbook -i /etc/ansible/inventory/test/hosts /etc/ansible/playbooks/test.yml -l be-plw-ans-0007 -K
```

Expected results:
no delay between prompt for password and start of playbook-deployment

Actual results:
long (=-15s) delay between prompt for password and start of playbook-deployment

Fragment from the strace-output when the delay appears:

```
open("/usr/lib64/python2.7/distutils/version.py", O_RDONLY) = 4
fstat(4, {st_mode=S_IFREG|0644, st_size=11433, ...}) = 0
open("/usr/lib64/python2.7/distutils/version.pyc", O_RDONLY) = 8
fstat(8, {st_mode=S_IFREG|0644, st_size=7208, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f7704212000
read(8, "\3\363\r\n\357\204\240Sc\0\0\0\0\0\0\0\0\3\0\0\0@\0\0\0sq\0\0\0d\0"..., 4096) = 4096
fstat(8, {st_mode=S_IFREG|0644, st_size=7208, ...}) = 0
read(8, "\2\23\1(\2\36\2\t\1%\2c\2\0\0\0\3\0\0\0\7\0\0\0C\0\0\0s\265\0\0"..., 4096) = 3112
read(8, "", 4096)                       = 0
close(8)                                = 0
munmap(0x7f7704212000, 4096)            = 0
stat("/usr/lib64/python2.7/distutils/string", 0x7fff5db2ff90) = -1 ENOENT (No such file or directory)
open("/usr/lib64/python2.7/distutils/string.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/lib64/python2.7/distutils/stringmodule.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/lib64/python2.7/distutils/string.py", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/lib64/python2.7/distutils/string.pyc", O_RDONLY) = -1 ENOENT (No such file or directory)
stat("/usr/lib64/python2.7/distutils/re", 0x7fff5db2ff90) = -1 ENOENT (No such file or directory)
open("/usr/lib64/python2.7/distutils/re.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/lib64/python2.7/distutils/remodule.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/lib64/python2.7/distutils/re.py", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/lib64/python2.7/distutils/re.pyc", O_RDONLY) = -1 ENOENT (No such file or directory)
stat("/usr/lib64/python2.7/distutils/types", 0x7fff5db2ff90) = -1 ENOENT (No such file or directory)
open("/usr/lib64/python2.7/distutils/types.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/lib64/python2.7/distutils/typesmodule.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/lib64/python2.7/distutils/types.py", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/lib64/python2.7/distutils/types.pyc", O_RDONLY) = -1 ENOENT (No such file or directory)
close(4)
stat("/usr/lib/python2.7/site-packages/ansible/runner/filter_plugins/random", 0x7fff5db30500) = -1 ENOENT (No such file or directory)
open("/usr/lib/python2.7/site-packages/ansible/runner/filter_plugins/random.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/lib/python2.7/site-packages/ansible/runner/filter_plugins/randommodule.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/lib/python2.7/site-packages/ansible/runner/filter_plugins/random.py", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/lib/python2.7/site-packages/ansible/runner/filter_plugins/random.pyc", O_RDONLY) = -1 ENOENT (No such file or directory)
stat("/usr/lib/python2.7/site-packages/ansible/runner/filter_plugins/jinja2", 0x7fff5db30500) = -1 ENOENT (No such file or directory)
open("/usr/lib/python2.7/site-packages/ansible/runner/filter_plugins/jinja2.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/lib/python2.7/site-packages/ansible/runner/filter_plugins/jinja2module.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/lib/python2.7/site-packages/ansible/runner/filter_plugins/jinja2.py", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/lib/python2.7/site-packages/ansible/runner/filter_plugins/jinja2.pyc", O_RDONLY) = -1 ENOENT (No such file or directory)
close(3)                                = 0
stat("/etc/ansible/playbooks/roles/dns-server/files", 0x7fff5db31dd0) = -1 ENOENT (No such file or directory)
stat("/etc/ansible/playbooks/roles/dns-server/files", 0x7fff5db31dd0) = -1 ENOENT (No such file or directory)
stat("/etc/ansible/playbooks/library", 0x7fff5db31fd0) = -1 ENOENT (No such file or directory)
stat("/etc/ansible/library/action.py", 0x7fff5db31850) = -1 ENOENT (No such file or directory)
stat("/etc/ansible/library/action", 0x7fff5db31850) = -1 ENOENT (No such file or directory)
stat("/usr/lib/python2.7/site-packages/ansible/modules/action.py", 0x7fff5db31850) = -1 ENOENT (No such file or directory)
stat("/usr/lib/python2.7/site-packages/ansible/modules/action", 0x7fff5db31850) = -1 ENOENT (No such file or directory)
stat("/usr/lib/python2.7/site-packages/ansible/modules/core/action.py", 0x7fff5db31850) = -1 ENOENT (No such file or directory)
stat("/usr/lib/python2.7/site-packages/ansible/modules/core/action", 0x7fff5db31850) = -1 ENOENT (No such file or directory)
stat("/usr/lib/python2.7/site-packages/ansible/modules/extras/action.py", 0x7fff5db31850) = -1 ENOENT (No such file or directory)
stat("/usr/lib/python2.7/site-packages/ansible/modules/extras/action", 0x7fff5db31850) = -1 ENOENT (No such file or directory)
stat("/usr/lib/python2.7/site-packages/ansible/modules/core/cloud/action.py", 0x7fff5db31850) = -1 ENOENT (No such file or directory)
stat("/usr/lib/python2.7/site-packages/ansible/modules/core/cloud/action", 0x7fff5db31850) = -1 ENOENT (No such file or directory)
stat("/usr/lib/python2.7/site-packages/ansible/modules/core/commands/action.py", 0x7fff5db31850) = -1 ENOENT (No such file or directory)
stat("/usr/lib/python2.7/site-packages/ansible/modules/core/commands/action", 0x7fff5db31850) = -1 ENOENT (No such file or directory)
```

The above seems to loop for a while and eventually continues with the normal actions.

**Comment by mscherer** [comment] 2015-02-08 11:06
I think that's the regular way that python work. It do that for every python software I am aware of. And the fact that it does a lot of it might not be the real slowness. I think it would be better to use a proper profiler than strace, like cProfile module of python.

**Comment by bcoca** [comment] 2015-02-09 14:42
This is the python import loader, since the plugins were modified to support python import semantics and are added to PYTHONPATH, this is expected behavior.

Leaving this open to see if we can optimize it, I don't think wet can avoid it completely.

**Comment by cove** [comment] 2015-02-14 16:15
We have very slow start up times too, site.yml is close to 10mins. We had to break up our playbooks a lot, but they're still in the multiple of mins range. Enclosed is a ~5min startup profile.

![pycallgraph](https://cloud.githubusercontent.com/assets/612300/6200272/d658c3da-b424-11e4-8add-9aedc8a537de.png)

(Sorry, the call graph image is pretty big, Chrome and FF have trouble with it. Best to download and use an image viewer with it.)

**Comment by cove** [comment] 2015-02-16 08:37
Related PR: #10250

**Comment by jensdepuydt** [comment] 2015-02-16 09:52
To test, I applied your patch to our installed version and there indeed an improvement.
For me, the delay went from ~8s to ~5s.

Thanks.

**Comment by abadger** [comment] 2015-02-16 20:06
The original issue in this ticket is simply the way that python imports modules and since ansible has adopted that method we don't have much ability to change it.  However the stating shouldn't be a problem in most circumstances (as the callgraph seems to show).

If we want more speedups we'll probably need people to generate more callgraphs and concentrate on fixing things in the slow paths that those reveal.  Unless someone can point at the python import stats being the cause of slowness  we probably should close this and open new bugs as we identify and/or fix other specific issues.

**Comment by gtirloni** [comment] 2015-02-16 20:46
@jensdepuydt coud you run ansible through the profiler and attach the .pstats file here (adjust paths accordingly)?

```
python -m cProfile -o issue10165.pstats /usr/bin/ansible-playbook site.yml
```

**Comment by cove** [comment] 2015-02-17 08:44
FWIW here's the size of my env, which takes about 12mins to start for site.yml:
900 hosts
680 group_var files / 30k vars
190 roles
585 yaml files in total, 19k lines of yaml

Which doesn't really seem like enough to justify 12mins of 100% cpu util... it seem like there's some deep complexity or inefficiency in the loading algo... like it's O(n!)...

**Comment by jensdepuydt** [comment] 2015-02-17 09:57
@gtirloni You can find the output here:
http://jensd.be/temp/issue10165-1.pstats -> small playbook
http://jensd.be/temp/issue10165-2.pstats -> larger playbook

I perfectly understand that this is how Python works but it's not normal that this depends on the size of the playbook. To my understanding it should be suffucient to load/import the modules once for the whole playbook and not for every entry in it. The larger the playbook, the bigger the delay.

Our enviroment is about this size in Ansible:
+- 60 hosts
+-30 groups
+-80 roles
+-100 yaml files
Which can be considered as a small environment but the delay varies between 5 and 30s depending on the size of the playbook. Which can be annoying at times.

**Comment by gtirloni** [comment] 2015-02-17 10:58
If my understanding is right, we are spending most of the time in [utils.plugins.find_plugin](https://github.com/ansible/ansible/blob/devel/lib/ansible/utils/plugins.py#L158) for each [task](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/task.py#L48) that gets created.
- [issue10165-1.png](https://cloud.githubusercontent.com/assets/5902830/6227067/41a918a6-b682-11e4-96b5-e2afad2a67ac.png)
- [issue10165-2.png](https://cloud.githubusercontent.com/assets/5902830/6227068/41a94e66-b682-11e4-9abc-2f8403521bbf.png)

Would it make sense to have this information collected per play instead of per task? Like a cache of plugin/module location to avoid hitting the OS-level functions and instead, say, lookup it up in a dictionary in memory.

**Comment by bcoca** [comment] 2015-02-17 13:22
@cove, this should not be the case, 12 mins is way too much time for
initialization.
@giovanni, or at least we should be able to cache/shortcut the search to
only new plugins used.

## 

Brian Coca

**Comment by abadger** [comment] 2015-02-17 21:31
@jensdepuydt  @cove new pull request that optimizes the plugin loader for you guys to try:
https://github.com/ansible/ansible/pull/10268

getting new profiles/callgraphs with both this and @cove's recently merged cyaml commit would be useful.  My guess is that this will somewhat improve the time for @jensdepuydt's run but the speedup won't be recognizable in @cove's results because something else is dominating the time.  profiles/callgraphs may help to track down the next bottleneck but we may be dealing with different bottlenecks so we may want to open new tickets specific to each issue soon.

**Comment by jensdepuydt** [comment] 2015-02-18 09:31
@abadger Thanks for the work.
I set up a separate VM to try these changes and it seems that there is a nice performance improvement. On first sight, everything seems to work as it should.

Time for ansible-playbook before any adjustments (version 1.8.2 from the EPEL repo): 
real    0m25.351s
user    0m0.006s
sys     0m0.007s

Time after applying the changes in #10250:
real    0m22.672s
user    0m0.005s
sys     0m0.008s

Time after applying the changes in #10268:
real    0m4.120s
user    0m0.007s
sys     0m0.007s

So as you can see, this is a huge improvement.
One remark: after applying #10268, I has to create some folders manually:
/usr/share/ansible_plugins/cache_plugins
/usr/share/ansible_plugins/lookup_plugins
/usr/share/ansible_plugins/action_plugins
/usr/share/ansible_plugins/connection_plugins
/etc/ansible/shell_plugins
Didn't have time to check why exactly.
Edit: found out why and did an update for the pull request: #10275

**Comment by abadger** [comment] 2015-02-18 15:33
https://github.com/ansible/ansible/pull/10275 merged.  Thanks @jensdepuydt!

**Comment by abadger** [comment] 2015-02-23 15:14
Okay, I'm going to close this ticket now that we have the original issue down to a more reasonable speed.  @cove, We're still curious as to whether these changes have fixed your case or not.  We may not see new comments on a closed ticket so if you are still experiencing slow times please open a new ticket and we'll be sure to look at what could be happening.  12minute startups are definitely something we want to diagnose and find solutions for.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Closed as completed by abadger** 2015-02-23 15:14 UTC
Labels: bug
