### ISSUE TITLE
group_vars and host_vars not merged

### ISSUE THREAD

**Issue by jcassee** [ansible/ansible#4010] opened 2013-09-03 14:26 UTC
When `hash_behavior = merge` variables from `group_vars` and `host_vars` are not merged. See attached the test case here:

https://letscrate.com/f/jcassee/github/ansible-bug.tar.gz

**Comment by srgvg** [comment] 2013-09-03 14:59
You have a typo in ansible.cfg: it's `hash_behaviour` and _not_ `hash_behavior` :)

**Comment by jimi-c** [comment] 2013-09-10 17:36
Based on your sample, I cannot reproduce this (unless I also misspell hash_behaviour as hash_behavior, as @sergevanginderachter pointed out above). If you continue to have this issue, let us know, but I'm going to close this for now.

Thanks!

**Closed as completed by jimi-c** 2013-09-10 17:36 UTC
Labels: bug

**Comment by jcassee** [comment] 2013-09-10 21:39
Hi Serge and James, I thought I had closed this ticket. Thanks for looking into this and finding my typo!

**Comment by ghost** [comment] 2013-11-06 16:39
This typo is also in the documentation http://www.ansibleworks.com/docs/intro_configuration.html#hash-behavior
