### ISSUE TITLE
SSH connections should not use ControlPath by default.

### ISSUE THREAD

**Issue by roysmith** [ansible/ansible#9813] opened 2014-12-15 02:50 UTC
##### Summary:

The default behavior is to include "-o ControlPath="/Users/roy/.ansible/cp/ansible-ssh-%h-%p-%r" on the command line for ssh connections.  I just got through a painful debugging session caused by this.

I had just set spun up a new host and was starting to build a playbook for configuring it.  The first playbook I ran was against a very raw machine.  After doing that, I added myself to group admin, so I could sudo.  But, by the time I did that, there was already a control connection nailed up that it kept reusing, and in that connection's context, I was not yet in group admin.  This resulted in the extremely confusing situation of being able to sudo when I manually ssh'd into the box, but sudo failing when run by ansible.

The performance improvement from using ControlPath is extremely minor.  The potential for mystifying problems such as the one I ran into is large.  Go for correct first, then optimize for speed later.  The default should be to not use ControlPath, and allow users to turn that feature on if they want to get the added performance (but the docs should warn them about the potential problems).

**Comment by mpdehaan** [comment] 2014-12-15 13:36
Thanks for the report.

The benefit of Control Persist is not minor and we should use it by default - in some cases it can speed up Ansible runs by over 2x - in some cases, much more.  

I do understand this is a confusing situation, but I would prefer to have the performance increase in this case than the other.   Perhaps we should have some flag that allows closing them, or you could consider lowering the Control Persist timeout.

**Closed as completed by mpdehaan** 2014-12-15 13:36 UTC

**Comment by roysmith** [comment] 2014-12-15 14:13
This really is broken as the default behavior.  It leads to mysterious, hard to debug problems.  I don't deny that this is a useful speedup for production use, but like I said, go for correct first, then optimize for speed later.  Once somebody has built their configuration up to the point where connection startup time is a problem, it's easy enough for them to enable this in their playbooks, or globally via some config file flag.

At the very least, include the pid of the ansible process in the path.  Then you'll only pay the connection startup cost once per ansible invocation.

Actually, as I look at this more, I suspect there's more going on than I originally thought.  I see you also include "-o ControlPersist=60s", which should make these connections only last for 60 seconds.  But, I saw the problem persist over a much longer time span than that.  It was 100% reproducible that if I ran "ansible -i inventory all -a groups", I could see that the groups output did not include the admin group.  When I tracked down the ssh process which was holding the cached connection socket open and killed it, that immediately solved the problem.

**Comment by dukebody** [comment] 2015-05-15 12:30
I ran into exactly the same problem. Really hard to debug, luckily found this thread...

**Comment by dancingfrog** [comment] 2016-04-10 13:26
This option was sooooo hard to track down as the cause for the errors I was seeing, both in running play books and simply pinging my hosts. In case some one is googling in the same state of desperation I was, following the above advice from @roysmith and [disabling acceleration in ansible.cfg](http://stackoverflow.com/questions/31649421/ansible-wont-let-me-connect-through-ssh#answer-31668998) may solve:

`fatal: [default]: UNREACHABLE! => {"changed": false, "msg": "SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue", "unreachable": true}`

... and/or ...

```
_some_host_ | UNREACHABLE! => {
    "changed": false, 
    "msg": "SSH encountered an unknown error during the connection. \ 
                We recommend you re-run the command using -vvvv, which \ 
                will enable SSH debugging output to help diagnose the issue", 
    "unreachable": true
}
```

If you are using Ansible to provision a Vagrant vm, add this to your provision options in Vagrantfile:

```
    config.vm.provision "ansible" do |ansible|
        ...
        ansible.raw_ssh_args = "-o ControlMaster=no"
        ...
    end
```
