### ISSUE TITLE
ansible not deleting temporary files (in a few cases)

### ISSUE THREAD

**Issue by pmarkham** [ansible/ansible#5339] opened 2013-12-18 22:21 UTC
I've found two cases where Ansible isn't deleting the temporary files. We found this out when our filesystem ran out of inodes.

This was tested on the latest devel release (commit ansible-devel: 3f81c3c4168fd0368b18d0d3b93e27a2afd8053d)

The first one is: If the directory name specified in remote_tmp parameter doesn't contain 'tmp', directories and files will not be deleted.

e.g. The following works:

```
remote_tmp     = $HOME/.ansible/tmp
```

The following doesn't

```
remote_tmp     = $HOME/.ansible
```

The second issue is: The copy module leaves an empty directory. See the output below:

The first exec creates directory `$HOME/.ansible/tmp/ansible-1387404534.56-105865926927922`

The second exec creates directory `$HOME/.ansible/tmp/ansible-1387404535.8-27801105939035`

The first directory isn't deleted.

```
$ ansible localhost -vvvv -m copy -a "dest=/tmp/test content='hello'"
<localhost> ESTABLISH CONNECTION FOR USER: d303355
<localhost> EXEC ['ssh', '-tt', '-vvv', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', 'localhost', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1387404534.56-105865926927922 && chmod a+rx $HOME/.ansible/tmp/ansible-1387404534.56-105865926927922 && echo $HOME/.ansible/tmp/ansible-1387404534.56-105865926927922'"]
<localhost> EXEC ['ssh', '-tt', '-vvv', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', 'localhost', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1387404535.8-27801105939035 && chmod a+rx $HOME/.ansible/tmp/ansible-1387404535.8-27801105939035 && echo $HOME/.ansible/tmp/ansible-1387404535.8-27801105939035'"]
<localhost> EXEC ['ssh', '-tt', '-vvv', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', 'localhost', u'/bin/sh -c \'rc=0; [ -r "/tmp/test" ] || rc=2; [ -f "/tmp/test" ] || rc=1; [ -d "/tmp/test" ] && rc=3; (/usr/bin/md5sum /tmp/test 2>/dev/null) || (/sbin/md5sum -q /tmp/test 2>/dev/null) || (/usr/bin/digest -a md5 /tmp/test 2>/dev/null) || (/sbin/md5 -q /tmp/test 2>/dev/null) || (/usr/bin/md5 -n /tmp/test 2>/dev/null) || (/bin/md5 -q /tmp/test 2>/dev/null) || (/usr/bin/csum -h MD5 /tmp/test 2>/dev/null) || (echo "${rc}  /tmp/test")\'']
<localhost> PUT /tmp/tmpFY2Gxs TO /home/d303355/.ansible/tmp/ansible-1387404535.8-27801105939035/file
<localhost> EXEC ['ssh', '-tt', '-vvv', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', 'localhost', "/bin/sh -c '/usr/bin/python /home/d303355/.ansible/tmp/ansible-1387404535.8-27801105939035/file; rm -rf /home/d303355/.ansible/tmp/ansible-1387404535.8-27801105939035/ >/dev/null 2>&1'"]
localhost | success >> {
    "changed": false, 
    "gid": 43033558, 
    "group": "d303355", 
    "mode": "0600", 
    "owner": "d303355", 
    "path": "/tmp/test", 
    "size": 5, 
    "state": "file", 
    "uid": 43033558
}
```

**Comment by mpdehaan** [comment] 2013-12-18 23:44
(A) Yep, there's a safeguard in (1) that should not be as safe, perhaps.

(B) We'll have to investigate that second part.

Are you using the ssh_alt connection type by any chance?

**Comment by pmarkham** [comment] 2013-12-19 00:30
(A) If you're removing the specific directory you create, is there any possibility it can be unsafe in any way? Not a big deal now we know about it, but it ran one of our file systems out of inodes. Fortunately didn't cause any issues as it was on a play machine.

(B) No, we've got the connection type set to 'ssh' which is the Solaris 10 version of ssh in this case. It's only the copy module that I've found the issue with.

**Comment by jctanner** [comment] 2014-01-07 18:51
Looks like this was introduced by https://github.com/ansible/ansible/commit/5c965a75 , specifically lines 316 and 381.

**Comment by jctanner** [comment] 2014-01-07 18:55
@jeromew can you comment here on what the tmp.find("tmp") accomplishes for ssh_alt? Removing it per the patch below resolves this issue, but I'm unsure what impact that has on your optimizations for ssh_alt:

```
diff --git a/lib/ansible/runner/__init__.py b/lib/ansible/runner/__init__.py
index a81288a..e46781b 100644
--- a/lib/ansible/runner/__init__.py
+++ b/lib/ansible/runner/__init__.py
@@ -369,7 +369,9 @@ class Runner(object):
         cmd = " ".join([environment_string.strip(), shebang.replace("#!","").strip(), cmd])
         cmd = cmd.strip()

-        if tmp.find("tmp") != -1 and not C.DEFAULT_KEEP_REMOTE_FILES and not persist_files:
+        #import epdb; epdb.st()
+        #if tmp.find("tmp") != -1 and not C.DEFAULT_KEEP_REMOTE_FILES and not persist_files:
+        if not C.DEFAULT_KEEP_REMOTE_FILES and not persist_files:
             if not self.sudo or self.sudo_user == 'root':
                 # not sudoing or sudoing to root, so can cleanup files in the same step
                 cmd = cmd + "; rm -rf %s >/dev/null 2>&1" % tmp
@@ -382,7 +384,8 @@ class Runner(object):

         res = self._low_level_exec_command(conn, cmd, tmp, sudoable=sudoable, in_data=in_data)

-        if tmp.find("tmp") != -1 and not C.DEFAULT_KEEP_REMOTE_FILES and not persist_files:
+        #if tmp.find("tmp") != -1 and not C.DEFAULT_KEEP_REMOTE_FILES and not persist_files:
+        if not C.DEFAULT_KEEP_REMOTE_FILES and not persist_files:
             if self.sudo and self.sudo_user != 'root':
             # not sudoing to root, so maybe can't delete files as that other user
             # have to clean up temp files as original user in a second step
```

**Comment by jeromew** [comment] 2014-01-07 19:32
I use tmp.find("tmp") != -1 as a proxy to "has a temporary directory been created".

if no tmp file was created, there is no need to delete it.

I had foreseen/mentionned this potential bug in one previous comment but really did not think someone would not put tmp in these tmp dirs.

the best way to fix this imho is in def _make_tmp_path(self, conn):

replace

```
basefile = 'ansible-%s-%s' % (time.time(), random.randint(0, 2**48))
```

by

```
basefile = 'ansible-tmp-%s-%s' % (time.time(), random.randint(0, 2**48))
```

this part is not user-configurable and this way tmp will always be present.

note: this funky test (tmp.find("tmp") != -1) was already in the code somewhere before ssh_alt so I used it despite the bug. A more proper way to fix this would be to create a new function _tmp_path_exists(). The main part is that this function must be in "sync" with the fact that _make_tmp_path was called.

**Comment by jctanner** [comment] 2014-01-07 19:44
@jeromew do you have time to make a PR? If not, I can work on it.

**Comment by jeromew** [comment] 2014-01-07 20:46
ok i'm taking care of it. I'll send the PR in a few minutes

**Comment by jeromew** [comment] 2014-01-07 21:00
@jctanner the bug should be fixed by this. can you confirm ?

**Comment by jeromew** [comment] 2014-01-08 14:34
@jctanner as an afterthought my PR was for a fix of what is called the "first issue" in the OP. Clearly I can acknowledge that there was a bug when remote_tmp was configured to something not containing "tmp".

I just re-read the OP and saw the "second issue". I am not sure my PR fixes this I am going to check and will come back to you here.

**Comment by jeromew** [comment] 2014-01-08 15:26
@jctanner.
the "second issue" is fixed but in fact was fixed before my PR by 

commit 833e1f6e2aa1f38f611e2423aa5979aaed7ade8b
Author: Stephen Fromm sfromm@gmail.com
Date:   Fri Dec 20 14:46:44 2013 -0800

```
Make sure action plugin copy cleans up tmp dir

The copy action plugin creates its own tmp dir for each file that it
copies to the target machine.  However, it does not clean up the
original tmp path it was given when run() is called.  This cleans up the
tmp path before it begins looping on source files.
```

looking at the date of the OP it makes sense.

good that it was fixed by deleting the empty directory, but i could have been fixed by not creating the useless directory in the first place (wins a systematic 2x ssh roundtrip on each call to copy module)

I'll send a PR in a few minutes

**Comment by jctanner** [comment] 2014-01-08 15:30
So both issues mentioned in the description should now be fixed, thanks to @jeromew

**Closed as completed by jctanner** 2014-01-08 15:30 UTC
Labels: bug

**Comment by jeromew** [comment] 2014-01-08 15:46
@mpdehaan note that further improvements can be made to the copy module if performance is required.

currently the algo is (not counting the md5 roundtrips here & specifics to sudo mode)

```
4*N roundtrips
for each file
  create tmp dir (1)
  put source file as "source" (1)
  execute copy with persist_files = false (2)
```

it could become

```
2 + 3*N roundtrips
TRANSFERS_FILES = True (1)
for each file
  PUT source file as "source + random()" (1)
  execute copy module with persist_files = true except for last file (2 + 1 last)
```

or if copy has "batch copy"

```
3 + N roundtrips
TRANSFERS_FILES = True (1)
for each file
  PUT source file as "source + random()" (1)
execute copy module of all files at once with persist_files = false (2)
```

or by preparing a local archive

```
4 roundrips
```

anyway i think it's better not to do these modifications now ; ssh_alt will already be a speed boost if it becomes default with success.(fingers crossed ;-)

**Comment by ghost** [comment] 2016-08-31 01:29
I also find out (Ansible-playbook 2.0.2.0) template module also leave the empty directory in remote_tmp directory

**Comment by jhawkesworth** [comment] 2016-08-31 04:54
@hsienchengli I believe that the issue you are.seeing was fixed during the development of 2
1  please can you try ansible 2.1.1?

**Comment by ghost** [comment] 2016-08-31 04:59
Thank you very much, unfortunately I cannot use 2.1.

I also encountered one problem using 2.1.0.0.  We tried to run it work RPM
package upgrade by yum (run yum on remote hosts), but it doesn't actual
upgrade the RPM package.  So we decide we stay 2.0.2.0 .

HC

jhawkesworth notifications@github.com 於 2016年8月30日星期二 寫道：

**Comment by michaelkrupp** [comment] 2017-03-03 03:34
The `copy: content` module also leaves behind temporary files here.

ansible 2.2.1.0
debian 8.7 jessie

**Comment by jimi-c** [comment] 2017-03-03 20:26
@michaelkrupp i believe we have an issue for this already, but if not please open one.

**Comment by nleve** [comment] 2017-11-14 12:08
```copy: content``` does still have this issue on 2.4.1.0.

**Comment by acondrat** [comment] 2017-12-11 09:37
I'm using `get_url` and it does not clean up temporary files in 2.4.2.0. Had to downgrade to 2.3.2.0.

**Comment by vkakhnych** [comment] 2018-02-14 09:06
The same on 2.4.2.0

**Comment by vkakhnych** [comment] 2018-02-14 09:26
Ubuntu ansible 2.4.2.0, see in /usr/lib/python2.7/dist-packages/ansible/plugins/action/__init__.py:

```
    def _should_remove_tmp_path(self, tmp_path):
        '''Determine if temporary path should be deleted or kept by user request/config'''
        
        return tmp_path and self._cleanup_remote_tmp and not C.DEFAULT_KEEP_REMOTE_FILES and "-tmp-" in tmp_path
```

Of course my default `/tmp` doesn't contain that dashes.

**Comment by vkakhnych** [comment] 2018-02-14 10:01
But looks like work on 2.4.3.0

**Comment by vkakhnych** [comment] 2018-02-14 11:17
I found the root of my issue. If destination file already the same and option `force` is set to yes `/tmp` folder doesn't cleaning.

**Comment by plup** [comment] 2018-04-11 12:48
I have the same issue in 2.4.2.0 with `get_url` a `/tmp/tmpXXXXX` is created at download and stay after. Playing with `force` parameter doesn't chabge anything.

**Comment by vkakhnych** [comment] 2018-04-11 12:53
Just upgrade to the last version - 2.5.0. There are no this issue.

**Comment by plup** [comment] 2018-04-11 13:28
Problem is fixed in `2.5.0`

**Comment by zendritic** [comment] 2018-11-30 17:33
I think this might be related. Our Ansible is failing to remove empty folders in local_tmp (which we have set to /tmp). We also ran out of inodes as a result. We are on 2.6.2.

**Comment by jhawkesworth** [comment] 2018-12-01 10:00
@zendritic this is a really old issue, please can you raise a new one with a playbook that reproduces this issue (preferably using latest devel ansible) so this can be investigated.  I only happened to notice your comment by chance but closed issues aren't normally monitored so please create a new issue with a reproducer so this can be investigated.

**Comment by jmnavarrol** [comment] 2019-04-15 09:54
> @zendritic this is a really old issue, please can you raise a new one with a playbook that reproduces this issue (preferably using latest devel ansible) so this can be investigated. I only happened to notice your comment by chance but closed issues aren't normally monitored so please create a new issue with a reproducer so this can be investigated.

**Done:** I'm also impacted, so I created #55286 (this is still an issue up to 2.7.0).
