### ISSUE TITLE
Unable to run ansible commands

### ISSUE THREAD

**Issue by orderedchaosdev** [ansible/ansible#12676] opened 2015-10-07 23:21 UTC
Issue Type:

Bug Report

Ansible Version:

ansible 2.0.0 (devel d8769c93c7) last updated 2015/10/07 15:50:12 (GMT -700)
  lib/ansible/modules/core: (detached HEAD d659c79db7) last updated 2015/10/06 19:38:32 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 0ff1776a84) last updated 2015/10/06 19:38:33 (GMT -700)

Ansible Configuration:
[defaults]
remote_user=root
transport=ssh
[ssh_connection]
ssh_args=-o StrictHostKeyChecking=true

Environment:

Centos 6
Python 2.6.6

Summary:

Basic ansible command returns errors

Steps To Reproduce:

```
    ansible host-1 -m shell -a "hostname"
```

Expected Results:

```
    host-1 | SUCCESS | rc=0 >>
    host-1
```

Actual Results:
This is with -vvv
Edited to remove some information <homedir> put in place of full path to ansible directory

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "<homedir>/ansible/lib/ansible/executor/process/worker.py", line 117, in run
    executor_result = TaskExecutor(host, task, job_vars, play_context, self._new_stdin, self._loader, shared_loader_obj).run()
  File "<homedir>/ansible/lib/ansible/executor/task_executor.py", line 118, in run
    res = self._execute()
  File "<homedir>/ansible/lib/ansible/executor/task_executor.py", line 343, in _execute
    result = self._handler.run(task_vars=variables)
  File "<homedir>/ansible/lib/ansible/plugins/action/normal.py", line 26, in run
    results = self._execute_module(tmp=tmp, task_vars=task_vars)
  File "<homedir>/ansible/lib/ansible/plugins/action/__init__.py", line 366, in _execute_module
    tmp = self._make_tmp_path()
  File "<homedir>/ansible/lib/ansible/plugins/action/__init__.py", line 180, in _make_tmp_path
    result = self._low_level_execute_command(cmd, sudoable=False)
  File "<homedir>/ansible/lib/ansible/plugins/action/__init__.py", line 486, in _low_level_execute_command
    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "<homedir>/ansible/lib/ansible/plugins/connection/ssh.py", line 587, in exec_command
    raise e
TypeError: execv() arg 2 must contain only strings

host-1 | FAILED | rc=0 >>

```

**Comment by orderedchaosdev** [comment] 2015-10-08 17:19
still broken as of
ansible 2.0.0 (devel d1b98ec776) last updated 2015/10/08 10:18:10 (GMT -700)
  lib/ansible/modules/core: (detached HEAD d659c79db7) last updated 2015/10/06 19:38:32 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 0ff1776a84) last updated 2015/10/06 19:38:33 (GMT -700)

**Comment by jimi-c** [comment] 2015-10-08 18:00
Hi @orderedchaosdev, I am unable to reproduce this. I did run into some blunders caused by `.ssh/config` on my own system though (I had set `UserKnownHostsFile /dev/null` for my testing VM's, so I was getting an odd error), so you might want to make sure you don't have any config options in /etc/ssh/ssh_config or in your local .ssh/config that are causing this.

**Comment by orderedchaosdev** [comment] 2015-10-08 18:18
```
Host *
  GSSAPIAuthentication yes
# If this option is set to yes then remote X11 clients will have full access
# to the original X11 display. As virtually no X11 client supports the untrusted
# mode correctly we set this to yes.
  ForwardX11Trusted yes
# Send locale-related environment variables
  SendEnv LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
  SendEnv LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
  SendEnv LC_IDENTIFICATION LC_ALL LANGUAGE
  SendEnv XMODIFIERS
```

is the only not commented out part of my ssh_config it is just the default

**Comment by orderedchaosdev** [comment] 2015-10-08 18:19
I can't post the local ssh config file but all it has are a few entries for hosts. and ansible commands work in older versions of ansible

**Comment by orderedchaosdev** [comment] 2015-10-08 18:21
```
ansible 2.0.0 (detached HEAD 464a436f8f) last updated 2015/08/20 14:06:50 (GMT -700)
  lib/ansible/modules/core: (detached HEAD dea5f5d15e) last updated 2015/08/20 14:06:50 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 210ee3febc) last updated 2015/08/20 14:06:50 (GMT -700)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/08/20 14:06:50 (GMT -700)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/08/20 14:06:50 (GMT -700)
```

Is the version we are having to run in production right now since everytime we test a newer devel branch it breaks and one or more of our playbooks won't run. Devel used to be mostly stable and now the only reason we aren't on a stable 1.9 is we are using some v2 features.

**Comment by orderedchaosdev** [comment] 2015-10-08 18:24
our ansible server has all standard repos and epel. Centos 6 and is up to date. Other than the git checkout of ansible everything is standard so we don't have special versions of python or ssh or anything

**Comment by orderedchaosdev** [comment] 2015-10-08 18:36
I have 2 ansible directories on my system. I use a different bashrc and ansible.cfg file for each. The one in the home directory is the old one and another directory has the current devel branch so if the wrong files are being accessed that could be doing it.

**Comment by Zipps** [comment] 2015-10-09 06:16
Having the exact same issue as @orderedchaosdev. I just installed ansible on a new server (devel branch) and got the exact same error. I have ansible on another server with the exact same configuration but it is working fine.

**Comment by isiahw1** [comment] 2015-10-09 07:35
I'm also having the exact same issue as @orderedchaosdev. Fresh CentOS 6.7 install with devel branch.

**Comment by jimi-c** [comment] 2015-10-09 12:53
Ok just tried this on a CentOS 6 box and was able to reproduce it. Looking at it now.

**Comment by jimi-c** [comment] 2015-10-09 13:51
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed** 2015-10-09 13:50 UTC
Labels: needs_info, bug
