### ISSUE TITLE
Wrong vars inheritance when using roles statement

### ISSUE THREAD

**Issue by kvaps** [ansible/ansible#57191] opened 2019-05-30 17:07 UTC
##### SUMMARY
When using roles. Undefined vars are inheritance from the previous roles, even if they are not executed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

roles statement?

##### ANSIBLE VERSION

```paste below
ansible 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/kvaps/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3 (default, Mar 26 2019, 21:43:19) [GCC 8.2.1 20181127]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Arch Linux

##### STEPS TO REPRODUCE

```bash
mkdir /tmp/bug-57191

cd /tmp/bug-57191

mkdir -p roles/print_some_var/tasks/

cat > roles/print_some_var/tasks/main.yaml <<EOT
- debug:
    var: some_var
EOT

cat > playbook.yaml <<EOT
- hosts: localhost
  gather_facts: no
  roles:

  - name: print_some_var
    vars:
      some_var: aaa
    tags: aaa

  - name: print_some_var
    tags: bbb
EOT

ansible-playbook playbook.yaml --tag bbb
```

##### EXPECTED RESULTS
```paste below
ok: [localhost] => {
    "some_var": "VARIABLE IS NOT DEFINED!"
}
```

##### ACTUAL RESULTS

```paste below
ok: [localhost] => {
    "some_var": "aaa"
}
```

**Comment by sivel** [comment] 2019-05-30 17:13
This is expected.  Variables, applied via the `vars:` keyword on roles are scoped at the play level, not at the role level.

roles listed under the `roles:` are pre-processors and are merged into the play.

Duplicate of https://github.com/ansible/ansible/issues/56349

See https://github.com/ansible/ansible/issues/56349 for a more detailed explanation.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Closed as completed by sivel** 2019-05-30 17:13 UTC

**Comment by kvaps** [comment] 2019-05-30 17:37
So solution is:
```
cat > ansible.cfg <<EOT
[defaults]
private_role_vars = yes
EOT
```

thanks
