### ISSUE TITLE
Variable overding during nested includes issue

### ISSUE THREAD

**Issue by sebi-hgdata** [ansible/ansible#11881] opened 2015-08-06 19:53 UTC
It seems variables are not overridden when using nested includes (this works ok in v1 ) .This might be related to   #11353 . To reproduce the issue you can follow the steps from #11353 ... 
In build.yml I have a variable docker_tags what is overriden in  tasks/docker/base_build.yml... instead of printing the overridden value it prints the value from build.yml. See debug statements after running  'ansible-playbook -v build_admin_ui.yml -i inventories/local/hosts --extra-vars "admin_ui_version=1234"'

**Comment by bcoca** [comment] 2015-08-06 20:04
# Can You Help Us Out?

Thanks for filing a ticket! I am the friendly GitHub Ansibot.

It looks like you might not have filled out the issue description based on our standard issue template.  You might not have known about that, and that's ok too, we'll tell you how to do it.

We have a standard template because Ansible is a really busy project and it helps to have some standard information in each ticket, and GitHub doesn't yet provide a standard facility to do this like some other bug trackers.  We hope you understand as this is really valuable to us!.

Solving this is simple: please copy the contents of this [template](https://raw.githubusercontent.com/ansible/ansible/devel/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket.  That's it!

# If You Had A Question To Ask Instead

If you happened to have a "how do I do this in Ansible" type of question, that's probably more of a user-list question than a bug report, and you should probably ask this question on the project mailing list instead.

However, if you think you have a bug, the report is the way to go!  We definitely want all the bugs filed :)  Just trying to help!

# About Priority Tags

Since you're here, we'll also share some useful information at this time.

In general tickets will be assigned a priority between P1 (highest) and P5, and then worked in priority order. We may also have some follow up questions along the way, so keeping up with follow up comments via GitHub notifications is a good idea.

Due to large interest in Ansible, humans may not comment on your ticket immediately.

# Mailing Lists

If you have concerns or questions, you're welcome to stop by the ansible-project or ansible-development mailing lists, as appropriate.  Here are the links:
- https://groups.google.com/forum/#!forum/ansible-project - for discussion of bugs and how-to type questions
- https://groups.google.com/forum/#!forum/ansible-devel - for discussion on how to implement a code change, or feature brainstorming among developers

Thanks again for the interest in Ansible!

**Comment by sebi-hgdata** [comment] 2015-08-07 18:31
Hey,
   This happens on the latest devel branch, just re checked it now.  

```
seb@seb:~/hgdata/ansible_test$  ansible-playbook -v build_admin_ui.yml -i inventories/local/hosts --extra-vars "admin_ui_version=1234"
Using /home/seb/hgdata/ansible_test/ansible.cfg as config file

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [admin_ui]

TASK [include] *****************************************************************
included: tasks/docker/build.yml for admin_ui

TASK [include] *****************************************************************
included: base_build.yml for admin_ui

TASK [build base docker images] ************************************************
included: fragments/build.yml for admin_ui

TASK [debug msg=should be 'base' but it's {{ docker_tags }}] *******************
ok: [admin_ui] => {
    "changed": false, 
    "msg": "should be 'base' but it's [u'1234']"
}

TASK [debug1] ******************************************************************
ok: [admin_ui] => (item=[{u'path': u'/home/seb/hgdata/sfdc-ops/docker/apps/base/origin', u'name': u'origin'}, u'1234']) => {
    "item": [
        {
            "name": "origin", 
            "path": "/home/seb/hgdata/sfdc-ops/docker/apps/base/origin"
        }, 
        "1234"
    ], 
    "msg": "same as above 1234"
}
ok: [admin_ui] => {"changed": false, "msg": "All items completed"}

PLAY RECAP *********************************************************************
admin_ui                   : ok=6    changed=0    unreachable=0    failed=0   
```

**Comment by jimi-c** [comment] 2015-08-12 02:35
@sebi-hgdata could you gist or otherwise share a set of example files that will help us reproduce this clearly?

**Comment by sebi-hgdata** [comment] 2015-08-12 07:51
@jimi-c  you can clone  https://github.com/sebi-hgdata/ansible_test (it's the same repo as for #11353 ) and  run 'ansible-playbook -v build_admin_ui.yml -i inventories/local/hosts --extra-vars "admin_ui_version=1234" (above output is from this command). See the debug output saying  "should be 'base' but it's [u'1234']"

**Comment by jimi-c** [comment] 2015-08-12 13:44
@sebi-hgdata I have a preliminary patch here for you: https://gist.github.com/jimi-c/59d8f40e916f87a7978b

However, I'm seeing a problem with the `with_together` debug (which may simply be a bug in the way that debug works with with_ loops):

<pre>
TASK [debug1] ******************************************************************
ok: [admin_ui] => (item=[u'images', u'docker_tags']) => {
    "item": [
        "images", 
        "docker_tags"
    ], 
    "msg": "same as above docker_tags"
}
</pre>

Still looking into the above.

**Comment by jimi-c** [comment] 2015-08-12 14:51
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed** 2015-08-12 14:50 UTC
Labels: needs_info, bug

**Comment by jimi-c** [comment] 2015-08-12 14:51
The second issue mentioned was resolved as well, so you should be able to get past the original error.
