### ISSUE TITLE
ansible-vault overrides the symlink!

### ISSUE THREAD

**Issue by sirkubax** [ansible/ansible#20184] opened 2017-01-12 16:31 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
ansible-vault

##### ANSIBLE VERSION
```
ansible 2.2.1.0
```

##### SUMMARY
`ansible-vault edit some_symlink_file` 
removes the symlink and write the file **->** you end up with updated vault file in place of the symlink, and old not-updated vault file
This happen in the background, so you have no idea (unless you list symlinks) that the configuration mismatch has just been born!

##### EXPECTED RESULTS
Modify the source! 
or sys.exit(1) without any modification

##### REPRODUCE RESULTS
```
Before:
-rw-rw-r-- 1 x x 2.6K Nov 17 00:59 stg_default_vault
lrwxrwxrwx 1 x x   17 Nov 17 00:59 staging_vault -> stg_default_vault

Edit:
ansible-vault edit staging_vault

After:
-rw-rw-r-- 1 x x 2.6K Nov 17 00:59 stg_default_vault
-rw-rw-r-- 1 x x 2.6K Jan 12 17:29 staging_vault
```

**Comment by alikins** [comment] 2017-01-16 20:04
See also https://github.com/ansible/ansible/issues/20264

**Comment by bcoca** [comment] 2017-01-16 20:17
closing as dupe of #20264

**Closed as completed by bcoca** 2017-01-16 20:17 UTC
Labels: affects_2.2, c:cli/, bug

**Comment by sirkubax** [comment] 2017-01-19 10:46
@bcoca what was first, chicken or an egg :smile: 
Anyway, https://github.com/ansible/ansible/pull/20219 shall solve the issue (unless you would actually like to follow the link, and edit target file)
edit: I see @alikins did it https://github.com/alikins/ansible/commit/c502a6e50b902101834fa5b32d6945dd45d6d88c :+1:

**Comment by bcoca** [comment] 2017-01-19 20:59
@sirkubax this came first, but the other ticket had some comments on it already, so i chose to close this one

**Comment by sirkubax** [comment] 2017-01-19 23:11
Sure, not being upset :)
Just looks like I'd not do the homework before submitting the issue. 'Procesing on #20264' in the 'closing comment' might be a more precisely commented. 
Anyway, nice that the issues are processed. I'd try to help a little in my free time, until I'd get bored :) The 1500 issues backlog is huge :(
