### ISSUE TITLE
template with force=no reports 'changed' only in checkmode

### ISSUE THREAD

**Issue by ciphernaut** [ansible/ansible#12223] opened 2015-09-03 00:22 UTC
Issue Type:

```
Bug Report
```

Ansible Version:

ansible 1.9.2
  configured module search path = None

Ansible Configuration:

  not relevant

Environment:

  Fedora release 21 (Twenty One) 64bit intel

Summary:

Subsequent runs of plays using template with force=no work fine in normal run but trigger 'changed' in checkmode.

Steps To Reproduce:
template_no_force_check.yml

```
- hosts: localhost
  tasks:
    - name: copy template to /tmp
      template: src=template.j2 dest=/tmp/ansible_variables force=no
```

template.j2

```
{{ hostvars['localhost'] | to_yaml }}
```

Expected Results:
one would expect the following in both cases:

```
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

Actual Results:
(after initial first run)

```
mgrigull@dhcp-40-35:tmp:0$ ansible-playbook -C template_no_force_check.yml

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [copy template to /tmp] ************************************************* 
changed: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=1    unreachable=0    failed=0   

mgrigull@dhcp-40-35:tmp:0$ ansible-playbook  template_no_force_check.yml

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [copy template to /tmp] ************************************************* 
ok: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
```

**Comment by jctanner** [comment] 2016-06-04 02:15
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us. 

Testing this on the version you have specified, we cannot reproduce this problem.

Our reasons and evidence for this are:
- Tested against 1.9.2 and 2.1 and in both cases with the same template and playbook, the chaged value was 1.

And we suggest that:
- Re-test this with a clean install of ansible. If it still occurs, please provide -vvvv output when refiling a new issue.

As such, we are most likely going to close this ticket.  Should you disagree with this conclusion, you may also wish to join our mailing lists, which are very active:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Closed as completed by jctanner** 2016-06-04 02:15 UTC
Labels: P2, bug
