### ISSUE TITLE
`copy` for localhost seems to call `template` and fails

### ISSUE THREAD

**Issue by kenoss** [ansible/ansible#11100] opened 2015-05-30 18:38 UTC
Hello all,

**Issue Type**:

Bug Report

**Ansible Version**:

1.9.0.1

**Environment**:

OSX Yosemite

**Summary**:

I only uses `file` but `template`, although I've got an wierd error that comes from `/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/utils/template.py`.  I guess it will be raised only for `localhost`.  When I use ssh with other machine, all things are well-done.

Note that ansible seems hang slightly when outputs `GATHERING FACTS ***************************************************************`.

**Files**:

hosts:
empty, but also I tried dummy file that doesn't contain `localhost`.

hoge.yml :

``` yaml

---
- hosts: localhost
  roles:
    - hoge
```

roles/hoge/tasks/main.yml :

``` yaml
- name: Copy hoge
  action: copy src=hogehoge dest=~/hogehoge mode=0644
```

roles/hoge/files/hogehoge :
empty

**Command and resulting error**:

```
$ ansible-playbook -i hosts hoge.yml
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [hoge | Copy hoge] ****************************************************** 
fatal: [localhost] => template error while templating string: Encountered unknown tag 'H'.

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/myname/hoge.retry

localhost                  : ok=1    changed=0    unreachable=1    failed=0   
```

**Comment by bcoca** [comment] 2015-06-01 12:53
misleading error, templating happens internally in ansible to resolve variables and other things, this might just be an issue with a bad varaible in your definitions. This might error out even if not related to your current tasks, there were a couple of fixes to mitigate this in 1.9.1, please test with that and/or current devel.

**Comment by kenoss** [comment] 2015-06-01 15:38
Thank you for the advice.  I followed instraction here http://docs.ansible.com/intro_installation.html#running-from-source
and now I'm using devel, but almost nothing has been changed.

```
$ ansible --version
ansible 2.0.0 (devel e36b7130ff) last updated 2015/06/02 00:10:18 (GMT +900)
  lib/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/06/02 00:10:26 (GMT +900)
  lib/ansible/modules/extras: (detached HEAD 1276420a3a) last updated 2015/06/02 00:10:37 (GMT +900)
  v2/ansible/modules/core: (detached HEAD 85c8a892c8) last updated 2015/06/02 00:10:56 (GMT +900)
  v2/ansible/modules/extras: (detached HEAD 70ea058563) last updated 2015/06/02 00:11:03 (GMT +900)
  configured module search path = None
```

```
$ ansible-playbook hoge.yml -i hosts

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [hoge | Copy hoge] ****************************************************** 
fatal: [localhost] => Failed to template %F{red}%D{%H:%M:%S} ${USER}@${HOSTNAME} %! %(!.#.$)%k%f : template error while templating string: Encountered unknown tag 'H'.

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/myname/hoge.retry

localhost                  : ok=1    changed=0    unreachable=1    failed=0   
```

Do you need other info to fix it?

**Comment by jimi-c** [comment] 2015-07-15 05:50
Hi @kenoss, can you share the content of the source file?

**Comment by rvben** [comment] 2016-11-01 12:53
I tested this with the current devel version, and it works as expected. It seems that this issue has been solved already.

**Comment by bcoca** [comment] 2016-11-01 18:07
Since the original opener never responded to questions, we have never been able to reproduce and others confirm this works, I'm going to close this issue.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code
Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by bcoca** 2016-11-01 18:07 UTC
Labels: affects_1.9, bug
