### ISSUE TITLE
Failure to connect with SSH because Unix domain socket length is reached due to the length of the hostname

### ISSUE THREAD

**Issue by Heliosmaster** [ansible/ansible#16840] opened 2016-07-27 15:13 UTC
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /path/to/whatever/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
[ssh_connection]
pipelining=True
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Unix domain socket created by ansible was too long, therefore ssh fails.
The error message is very vague:

```
this-is-a-long-hostname.example.org | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh.",
    "unreachable": true
}
```

Giving the same ssh command as ansible, the error was more descriptive:

```
unix_listener: "/Users/user12/.ansible/cp/ansible-ssh-this-is-a-long-hostname.example.org-1022-user12345.ulAxrSDBy3jA13KO" too long for Unix domain socket
```

I was able to solve this by putting in my `ansible.cfg`

```
control_path = %(directory)s/%%h-%%r
```

The socket name that ansible sets is clearly way too long. This means that, as of now, long hostnames don't work with Ansible, and it can be quite restricting.
##### STEPS TO REPRODUCE
- Have a long hostname in your inventory (e.g. `this-is-a-long-hostname.example.org`)
- Try a simple ping command (with `ansible -vvvvvvvvvvvvv -m ping` to that host)
##### EXPECTED RESULTS

You can connect to the machine
##### ACTUAL RESULTS
- You cannot connect to the machine
- SSH error is very vague (maybe addressed by #16649 )

**Comment by jctanner** [comment] 2016-07-29 12:56
duplicate of https://github.com/ansible/ansible/issues/11536

**Closed as completed by jctanner** 2016-07-29 12:56 UTC
Labels: docs
