### ISSUE TITLE
Allow flat role structure (x.yml instead of x/main.yml)

### ISSUE THREAD

**Issue by Vladimir-csp** [ansible/ansible#11700] opened 2015-07-23 03:29 UTC
When writing simple roles without complex includes and conditionals, it would be nice to be able to reduce subdir clutter. Tasks, handlers, vars and meta could also be single files instead of subdirs, like so:

```
role/
  tasks.yml
  handlers.yml
  vars.yml
  meta.yml
```

**Comment by bcoca** [comment] 2015-07-23 03:35
closing as dupe of #4359

**Closed as completed by bcoca** 2015-07-23 03:35 UTC

**Comment by Vladimir-csp** [comment] 2015-07-23 03:39
Oops, sorry.
My +1 to #4359 then.
