### ISSUE TITLE
No error when using lookup on a file that does not exist

### ISSUE THREAD

**Issue by grahamrhay** [ansible/ansible#8619] opened 2014-08-14 12:52 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8 (devel 9818d72b8c) last updated 2014/08/14 10:44:44 (GMT +100)
##### Environment:

Mac OSX (Mavericks) -> Debian 7.5
##### Summary:

I have an authorized_key task using a lookup, but the file path is wrong (I moved it down a folder). I would expect that to error, but instead the task succeeds (unchanged).

The source (https://github.com/ansible/ansible/blob/devel/lib/ansible/runner/lookup_plugins/file.py#L57) suggests an error should be raised, but it seems to be swallowed somewhere.
##### Steps To Reproduce:

```
    - name: Key for ansible user
      authorized_key: user=ansible key="{{ lookup('file', './some_file_that_exists_not') }}"
```
##### Expected Results:

An error
##### Actual Results:

Task succeeds (green/unchanged)

**Comment by mpdehaan** [comment] 2014-08-14 14:59
As noted on the list, since lookup plugins are used for iteration and other things, this will need to be dealt with carefully.

It could be that this is something only the file lookup should do.

**Comment by jimi-c** [comment] 2014-08-14 15:41
Related to #7608.

**Comment by srgvg** [comment] 2014-08-20 11:30
caused by 2a976ac3137e3fb0a8cdbc68769b92e70bd460dc see #5059

**Comment by AlexRiedler** [comment] 2014-08-20 14:21
This is also related to #7370 which is related to #7608 (as in 7370 was fixed by 7608, but that was removed due to something else... and so forth). I am willing to work on this and fix it, it is about a small amount of code. If everyone has a bunch of small test files I think I could hash through this relatively easily today.

### undefined case (should raise error, is empty string)

``` yaml
---
- hosts: localhost
  tasks:
    - debug:
        msg: "{{lookup('template', 'undefined_vars.txt')}}"
```

undefined_vars.txt:

``` yaml
My name is {{this_is_undefined}} 
```

**Comment by romanrev** [comment] 2014-09-04 01:09
Again, an annoying issue that causes a lot of time to debug when it hits the fan. :+1:

**Comment by mpdehaan** [comment] 2014-09-11 20:39
If the string contains Jinja2 it should not be an error if it is undefined because it could be lazy loaded later, or if the 'template' call references a variable name (aka something unquoted) but if it's a hardcode, it should definitely do that.

This may be somewhat involved to ascertain.

**Comment by romanrev** [comment] 2014-09-11 22:44
@mpdehaan 

> If the string contains Jinja2 it should not be an error if it is undefined because it could be lazy loaded later

Could you provide a working example of that, please?

> or if the 'template' call references a variable name (aka something unquoted) but if it's a hardcode, it should definitely do that.

definitely do what?

**Comment by damncabbage** [comment] 2014-09-16 08:36
I want to +1 this ticket as being a problem; I've just worked around this issue in my own playbooks by using a [filter instead of a lookup](https://gist.github.com/damncabbage/12af8915e12fbf71b897), thanks to lookup() failures being silently ignored (and then cast to blank strings if used with, say, `content`).

**Comment by drybjed** [comment] 2014-09-30 07:08
```
- hosts: all
  vars:
    keyvar: '{{ lookup("pipe","ssh-add -L") }}'

  tasks:
    - authorized_key:
        user: 'username'
        key: '{{ keyvar }}'
        state: 'present'
      failed_when: (keyvar is undefined or (keyvar is defined and not keyvar))
```

That should fix your issues.

**Comment by romanrev** [comment] 2014-09-30 07:15
Oops, I mixed up the issues, sorry :-) I meant I was commenting on #7608

**Comment by bcoca** [comment] 2014-12-15 21:43
fixed in devel, now you get:

fatal: [localhost -> 127.0.0.1] => One or more undefined variables: 'this_is_undefined' is undefined

**Closed as completed by bcoca** 2014-12-15 21:43 UTC
Labels: P2, bug

**Comment by romanrev** [comment] 2014-12-15 21:47
Thank you, Brian @bcoca! I am just guessing the comments were swapped - the one above should go to #7370 :-)
