### ISSUE TITLE
support macros in jinja2 templates

### ISSUE THREAD

**Issue by georgewhewell** [ansible/ansible#3779] opened 2013-08-07 16:35 UTC
Having an issue using macros in jinja2 templates

template.j2

```
{% import "macro.j2" as tools %}
```

macro.j2

```
{% macro do_something() %}
Macro contents
{% endmacro %}
```

Running this template results in:

```
fatal: [127.0.0.1] => {'msg': "'NoneType' object has no attribute 'add_locals'", 'failed': True}
```

**Comment by mpdehaan** [comment] 2013-08-07 21:13
I'm not sure if code imports are the same as Jinja2 macro imports as I've never used those.

Code imports are explicitly not allowed, because that would allow templates to execute arbitrary code that can easily sneak by review because it was in a template file.  Imagine what happened if we would import the "os" module, etc?   The way to work around this is to add filter plugins for needed features explicitly.

Not sure about your macro issue, I'm open to pull requests that fix this provided we don't allow imports of arbitrary code and they are reasonably compact.

**Comment by mpdehaan** [comment] 2013-08-11 20:47
I am going to close this one and this is a feature that not too many people use.

I will still entertain pull requests to add this.

**Closed as completed by mpdehaan** 2013-08-11 20:47 UTC
Labels: feature

**Comment by wilsaj** [comment] 2013-08-12 21:40
@georgewhewell Try adding "with context" to the imports:

```
{% import "macro.j2" as tools with context %}
```

Does that work?

**Comment by digitalpbk** [comment] 2013-08-30 19:11
@wilsaj, that worked. 
But the variables set in the parent template is not passed to the macro template. 
Same happens when I use {% with var=1%} {% include ... %} {% endwith %} the var value is not present in the included template.

**Comment by bcoca** [comment] 2013-08-30 19:14
you might be missing 'context', check the docs on include on the jinja2
site.

**Comment by bcoca** [comment] 2013-08-30 19:14
nvmd, had not read up the thread.

**Comment by wilsaj** [comment] 2013-08-30 21:36
@digitalpbk I'm not 100% sure, but I think what you are describing is the expected behavior from jinja. Assigning variables inside a template (either using `{% with... %}` or `{% set... %}`) puts variables in a separate block from the template context. Only variables part of the template context (which is the current ansible vars if you're using `template:`) will be automatically available to `include`'d templates. You're probably better off restructuring your included template as a macro so you can explicitly pass variables into it. For example:

```
{% with var=1%} 
  {% include ... %} 
{% endwith %}
```

would instead be:

```
{% from '_macros.j2' import some_macro with context %}

{% with var=1%} 
  {{ some_macro(var) }} 
{% endwith %}
```

**Comment by digitalpbk** [comment] 2013-08-31 04:16
@wilsaj, I tried rendering the template directly using jinja2, and it works as expected, i.e,

```
  {% with var=1%} 
    {% include ... %} 
  {% endwith %}
```

works.

Ansible is overriding the default behaviour. 

Not sure but the following code seems to cause this:
https://github.com/ansible/ansible/blob/devel/lib/ansible/utils/template.py#L396-L404

**Comment by wilsaj** [comment] 2013-08-31 16:00
Ah, ok. Sorry for the confusion - I hadn't actually tried it.

In any case you can still use a macro as a workaround. I just tested that so I'm sure it will work.

**Comment by digitalpbk** [comment] 2013-08-31 16:25
Yup, ended up passing all the global variables to the macro, not pretty but works.

Thanks!

**Comment by alanfairless** [comment] 2013-10-27 20:10
FWIW, on newest devel this seems to now work as desired.  I'm successfully using Jinja2 import with context, and global variables are available inside the imported macros without me having  to pass them manually.  It's of course quite helpful for eliminating redundant idioms.  :)
