### ISSUE TITLE
service reload command doesn't seem to work ( Debian 7 iptables-persistent ) but reloaded does

### ISSUE THREAD

**Issue by binarytemple** [ansible/ansible#3326] opened 2013-06-23 23:04 UTC
So reloaded doesn't seem to do anything 'changed = false'.

```
% ansible xxxxxxxxxx.binarytemple.co.uk -m service -a " name=iptables-persistent state=reloaded "     
xxxxxxxxxx.binarytemple.co.uk | success >> {
    "changed": false, 
    "name": "iptables-persistent", 
    "state": "stopped"
}
```

But restarted, restarts the service.

```
% ansible xxxxxxxxxx.binarytemple.co.uk -m service -a " name=iptables-persistent state=restarted "
xxxxxxxxxx.binarytemple.co.uk | success >> {
    "changed": true, 
    "name": "iptables-persistent", 
    "state": "started"
}
```

The docs seem to indicated that reloaded will always take place.

**Comment by binarytemple** [comment] 2013-06-24 10:05
Forgot to mention the version - ansible 1.2

**Comment by binarytemple** [comment] 2013-06-24 10:19
Have discovered a workaround - explicitly specify enabled=true. A possible cause could be the fact that iptables-persistent does not have a 'status' command.

```
% ansible xxxxxxxxxx.binarytemple.co.uk -m service -a " name=iptables-persistent state=reloaded enabled=true"
xxxxxxxxxx.binarytemple.co.uk | success >> {
    "changed": true, 
    "enabled": true, 
    "name": "iptables-persistent", 
    "state": "stopped"
}

# service iptables-persistent status
Usage: /etc/init.d/iptables-persistent {start|restart|reload|force-reload|save|flush}
```

The OS is Debian 7

**Comment by mpdehaan** [comment] 2013-06-28 02:17
If services don't have a status command you should probably use "pattern=" to specify how to find it.

**Comment by binarytemple** [comment] 2013-07-01 17:23
Tricky in this particular case. iptables-persistent just loads iptables rules at startup ( or reloads when requested ) and saves iptables rules at shutdown.

**Comment by binarytemple** [comment] 2013-07-01 18:05
There is no process that will be running. Iptables runs inside kernel space.

**Comment by bcoca** [comment] 2013-07-08 19:31
Only way to know if iptables is "up" is actually to see if there are any rules 'iptables -L -vn', it will still be 'up' just accepting all (default). The other interpretation is 'is it in the kernel and loaded?' but that is not something you should be able to control from service module .... kernel recompile module?

**Comment by binarytemple** [comment] 2013-07-09 10:52
No bcoca. 

There may be any sort of cruft in the iptables -L -vn command. 

We are not interested in whether there exists any iptables rules, those rules may just be temporary rules created by the root user, exactly the sort of thing we  want to wipe out using the iptables-persistent reload" command. 

The fact is, this is an unusual service, it does not have a daemon, or any particular associated state (there might be iptables rules, or there might not). 

The only elegant solutions are:
a) Run a shell command.
 or 
b) Add a 'no_status' parameter to service module.
 or
c) Create a new module just for the purpose of reloading iptables-persistent.

**Comment by bcoca** [comment] 2013-07-09 15:08
see inline

On Tue, Jul 9, 2013 at 6:52 AM, Bryan Hunt notifications@github.comwrote:

> There may be any sort of cruft in the iptables -L -vn command.
> 
> Yes, it was just a simple example, normally I dump&diff to see if current
> rules are same as expected rules, this is not something I think service
> module should do.
> 
>  The fact is, this is an unusual service, it does not have a daemon, or
> any particular associated state (there might be iptables rules, or there
> might not).
> 
> The only elegant solutions are:
> a) Run a shell command.
> 
> what currently do, not pretty but it works.
> 
> b) Add a 'no_status' parameter to service module
> 
> we should do this anyways (i was thinking autodetect though), but probably
> won't help much with iptables as alternative it uses pgrep or ps+grep.
> 
> c) Create a new module just for the purpose of reloading
> iptables-persistent.
> 
> I'm thinking a full iptables module that also takes care of reloads.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by binarytemple** [comment] 2013-07-11 12:08
"c) Create a new module just for the purpose of reloading iptables-persistent.
I'm thinking a full iptables module that also takes care of reloads."

Just to be clear about option c. 

Debian AFAIK is the only distribution that works that way, Ubuntu bodges it with an abstraction layer call UFW (Ubuntu Firewall) that has totally different behavior. Fedora is somewhat similar but uses "/sbin/service iptables save "

http://docs.fedoraproject.org/en-US/Fedora/12/html/Security_Guide/sect-Security_Guide-IPTables-Saving_IPTables_Rules.html

So distribution by distribution the behaviour and semantics are possibly going to be quite different. IMHO - one size fits all might not be a sensitive strategy, given how particular people are about their firewall rules.

**Comment by jimi-c** [comment] 2013-09-12 05:01
I believe this was corrected by 26a8d4ce9f865426d1a056ba7db56b25b91c4533, if you can confirm.

**Comment by jimi-c** [comment] 2013-09-18 17:52
Seeing as there have been no replies on this for a week and the issue is quite old (and seems to be fixed), I'm going to close this. If you are still running into a problem you believe is related to this please open a new issue. Thanks!

**Closed as completed by jimi-c** 2013-09-18 17:52 UTC
Labels: bug

**Comment by binarytemple** [comment] 2013-09-20 08:07
Hi there, it wasn't fixed by:

https://github.com/ansible/ansible/commit/26a8d4ce9f865426d1a056ba7db56b25b91c4533

But it's of no consequence, the way that iptables-persistent works is so counter idiomatic that it's much better to just use some arbitrary conditional command.
