### ISSUE TITLE
remote_user on task ignored on delegate_to

### ISSUE THREAD

**Issue by resmo** [ansible/ansible#55644] opened 2019-04-23 12:18 UTC
##### SUMMARY

If `delegate_to` to a host not in an inventory (e.g. github.com), the user `cfg-user` defined in ansible.cfg is taken even if we defined a `remote_user` on task level. 

If we put the host (e.g. github.com) into the inventory, `remote_user` on task level is used.

I would have expected, that `remote_user` on task level is used in every case.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
tested with the 2.5, 2.6, 2.7, devel
```

##### CONFIGURATION

```paste below
DEFAULT_REMOTE_USER(/home/rmoser/tmp/ansible-remote-user/ansible.cfg) = cfg-user
```

##### STEPS TO REPRODUCE

inventory:
```
 $ cat hosts 
myhost
```

playbook:
```yaml
---
- hosts: myhost
  gather_facts: no
  tasks:
  - command: echo foo
    remote_user: task-user
    delegate_to: github.com
```

##### EXPECTED RESULTS

```
sing module file /home/rmoser/Projects/resmo/ansible/lib/ansible/modules/commands/command.py
<github.com> ESTABLISH SSH CONNECTION FOR USER: task-user
```

##### ACTUAL RESULTS

```paste below
sing module file /home/rmoser/Projects/resmo/ansible/lib/ansible/modules/commands/command.py
<github.com> ESTABLISH SSH CONNECTION FOR USER: cfg-user

```

(I wished that delegate_to to a host not in an inventory (except localhost...) would have failed and my suggestion is to deprecate this)

**Comment by mkrizek** [comment] 2019-04-24 08:14
Duplicate of https://github.com/ansible/ansible/issues/33516

**Closed as completed by mkrizek** 2019-04-24 08:14 UTC
Labels: support:core, affects_2.5, bug, affects_2.6, affects_2.7, affects_2.8, P3
