### ISSUE TITLE
add_host doesn't add/update hostvars for an inventory-defined host

### ISSUE THREAD

**Issue by Apsu** [ansible/ansible#4808] opened 2013-11-05 06:23 UTC
When using add_host for a new hostname, the plugin correctly adds the host/group and any custom variables, and subsequent calls will add/update as expected. If the hostname already exists in the inventory, however, it does not get updated.

**Comment by mpdehaan** [comment] 2013-11-16 18:19
What is "ansible --version"?

Always include this when reporting bugs.

Also, can you please provide a playbook you are using that showcases the problem?

**Comment by jimi-c** [comment] 2013-11-18 19:17
I am unable to reproduce this with the current head of devel (f270777):

<pre>
$ cat test_4808.yml 
---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - add_host: hostname=localhost ansible_ssh_hostname=127.0.0.2
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - debug: var=foo
$ cat inventory_4808 
localhost
$ cat host_vars/localhost 
---
foo: bar
$ ansible-playbook test_4808.yml -i inventory_4808 
PLAY [localhost] ************************************************************** 
TASK: [add_host hostname=localhost ansible_ssh_hostname=127.0.0.2] ************ 
ok: [localhost]
PLAY [localhost] ************************************************************** 
TASK: [debug var=foo] ********************************************************* 
ok: [localhost] => {
    "foo": "bar"
}
PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
</pre>

**Comment by mpdehaan** [comment] 2013-12-01 21:46
Closing due to no feedback on the above.

Thanks!

**Closed as completed by mpdehaan** 2013-12-01 21:46 UTC
Labels: needs_info, bug
