### ISSUE TITLE
[branch?] file.set_context_if_different() crashes with IndexError

### ISSUE THREAD

**Issue by jkleint** [ansible/ansible#227] opened 2012-04-24 21:45 UTC
file.set_context_if_different() contains this code:

```
for i in range(len(context)):
    if context[i] is not None and context[i] != cur_context[i]:
```

On my box `context` looks like this:

```
[None, None, None, u's0']
```

And `cur_context` looks like this:

```
[u'user_u', u'object_r', u'etc_t']
```

Point being that `cur_context[3]` doesn't exist, so it crashes with `list index out of range`.  I don't know anything about SELinux, so I have no idea what these mean or what the fix is.  Incidentally, this error is _not_ bubbled up to the user, so I just get an 'unreachable' error with a dict that looks like everything is fine.

**Comment by mpdehaan** [comment] 2012-04-24 22:23
assigning to sfromm who wrote the SELinux module.

Including the line from your playbook would be helpful in understanding what you are doing.

**Comment by jkleint** [comment] 2012-04-25 12:05
Sure; nothing special:

```
---
- hosts: box
  sudo: True
  tasks: 
  - name: Copy yum local.repo to /etc/yum.repos.d
    action: copy src=local.repo dest=/etc/yum.repos.d/local.repo owner=root group=root mode=0644
```

**Comment by mpdehaan** [comment] 2012-04-25 12:32
The example makes things much more clear, thanks.  You're not setting the selinux mode at all, so yeah, if sfromm doesn't get a chance to take a look I'll see what's up.

No one else has reported this yet, so that's a little strange.  We have copy tests already and they haven't exploded for me.

Also you didn't include the acutal error traceback?   Please do this.   Error reports are always better if they include the error :)

**Comment by mpdehaan** [comment] 2012-04-25 12:52
was this on master or the devel branch?

please test on both if you're only using devel, it will be helpful to know where this fix needs to be applied

**Comment by sfromm** [comment] 2012-04-25 15:52
i'll take a look.

**Comment by sfromm** [comment] 2012-04-25 16:21
jkleint, it appears this is on a rhel5 host.  Is that correct?

**Comment by jkleint** [comment] 2012-04-25 16:30
Yes, rhel5 with SELinux enabled, using the devel branch.  The copy actually succeeds, but then it tries to do some SELinux stuff after that which fails.  Like I said, it doesn't give me a traceback, I had to hack out a bunch of except clauses to get it to crash with the actual error.  It would be some work to do again, and I don't remember it being that enlightening, but I can if needed.

**Comment by sfromm** [comment] 2012-04-25 16:33
jkleint, the problem is that on el6 and fedora the python call to selinux returns the seuser, serole, setype, _and_ selevel.  I forgot that rhel5 is not selevel aware.  I should have a fix ready soon.

For comparison:

```
(fedora)$ ls -Z /etc/yum.conf 
-rw-r--r--. root root system_u:object_r:etc_t:s0       /etc/yum.conf
(rhel5)$ ls -Z /etc/yum.conf
-rw-r--r--  root root system_u:object_r:etc_t          /etc/yum.conf
```

**Comment by sfromm** [comment] 2012-04-25 16:58
Pull request 238: https://github.com/ansible/ansible/pull/238

**Comment by mcodd** [comment] 2012-04-25 19:26
I think there may still be an selinux-related problem here... I was seeing the same problem jkleint originally saw and this latest merge fixed it, but now I'm facing what's detailed below (please let me know if this should be reported as a separate Issue, I wasn't sure if it was caused specifically by this fix or not).  I am on Centos5 with "SELINUX=disabled" in my /etc/sysconfig/selinux file.

<pre>
[15:17]walutil1 /ansible/ansible# ansible -i /ansible/conf/hosts walmon1 -m copy -a "src=/etc/passwd dest=/tmp/foo owner=mcoddington group=root"
walmon1 | FAILED => {'invocation': u'copy src=/var/tmp/ansible.m27362/passwd dest=/tmp/foo', 'md5sum': 'a53274f3286fa1cee16210bfcaf59057', 'changed': False}
walmon1 | FAILED => {'invocation': u'copy src=/var/tmp/ansible.m27362/passwd dest=/tmp/foo', 'md5sum': 'a53274f3286fa1cee16210bfcaf59057', 'changed': False}
[15:17]walutil1 /ansible/ansible#
</pre>


If it helps in tracking down where this failure occurs, the file _does_ get copied to the remote host, but any owner/group permissions are not applied.

If I hack ansible/library/file such that HAVE_SELINUX=false all the time, things work just fine:

<pre>
[15:22]walutil1 /ansible/ansible# ansible -i /ansible/conf/hosts walmon1 -m copy -a "src=/etc/passwd dest=/tmp/foo owner=mcoddington group=root"
walmon1 | success >> {
    "changed": false, 
    "group": "root", 
    "md5sum": "a53274f3286fa1cee16210bfcaf59057", 
    "mode": 420, 
    "path": "/tmp/foo", 
    "state": "file", 
    "user": "mcoddington"
}

[15:22]walutil1 /ansible/ansible# 
</pre>

**Comment by mpdehaan** [comment] 2012-04-25 19:27
the code most definitely needs to run getenforce and decide whether or not it needs to run...

(though maybe also some other things are also busted, no reason to run this if not on, right?)

**Comment by sfromm** [comment] 2012-04-25 21:15
mcodd, I'll set up something with selinux disabled and try to duplicate.

**Comment by sfromm** [comment] 2012-04-25 22:25
i don't think it needs to run getenforce because selinux.lgetfilecon() will return [-1, None] if selinux is disabled.  It should just set HAVE_SELINUX false in that case.

**Comment by bear** [comment] 2012-04-26 06:25
in my current testing, HAVE_SELINUX is being set to true just because it can import the selinux module (see https://github.com/ansible/ansible/blob/master/library/file#L34 )

this is causing exceptions for me on hosts that have selinux disabled but still have libselinux-python installed:

stderr: [w2] => Traceback (most recent call last):

  File "/var/tmp/ansible.uN6162/file", line 294, in ?

```
changed = set_context_if_different(path, secontext, changed)
```

  File "/var/tmp/ansible.uN6162/file", line 182, in set_context_if_different

```
debug("current secontext is %s" % ':'.join(cur_context))
```

TypeError: sequence item 0: expected string, NoneType found

**Comment by mpdehaan** [comment] 2012-04-26 12:19
right -- you have the module, but it's old.   Looks like some try/catch is required for older distros maybe, because the SELinux library suffered a API break?

I would not expect to see FAILED without a message explaining why it failed, so this may actually just be a case where when the copy module is chaining into the file module it is not passing the right arguments.  I thought this was recently fixed, but I could be wrong.

Have you tried this on the most recent devel branch?

**Comment by bear** [comment] 2012-04-26 14:20
No but I can later tonight and report back.

**Comment by mcodd** [comment] 2012-04-26 14:26
Mike, the error you posted above is exactly what I was facing before I applied the latest devel changes (changes made for the initial issue described here)... after i applied it i got the error noted in my post from about 20 hours ago in this thread.  I suspect you will find the same.

Regarding sfromm's latest comment, it certainly seems "right" to me to simply set HAVE_SELINUX to false if it can be determined that selinux is off.  As I mentioned, hard coding it to false fixes the issue for me.

**Comment by sfromm** [comment] 2012-04-26 14:39
I submitted a patch against ansible/devel which I think should cover the variety of cases here: https://github.com/ansible/ansible/pull/251.

HAVE_SELINUX only means that _file_ can import the selinux module.  Another piece was added to _file_ to detect whether selinux is enabled.  If not enabled, it should skip the selinux operations.  At least it did in my testing on centos5 and centos6.  I tested with selinux disabled, enabled+permissive, and enabled+enforcing.  I also tested on debian to verify that it continues to work if python's selinux module is not present.

bear, mcodd, and jkleint, please test when you have an opportunity.

**Comment by mcodd** [comment] 2012-04-26 17:16
Thanks sfromm!  I'd like to test this but unfortunately I don't know enough git to apply the patch without it being merged into devel... if someone could point me towards the right way of doing that (or if we're just waiting for it to be merged that's cool too).

matt

**Comment by mpdehaan** [comment] 2012-04-26 23:26
fixed, mcodd -- pull the devel branch

**Closed as completed by mpdehaan** 2012-04-26 23:26 UTC

**Comment by mcodd** [comment] 2012-04-27 04:27
thanks, pulled latest devel and it's working for me just fine now!

**Comment by jkleint** [comment] 2012-04-27 14:28
Works for me, too.  Thanks!
