### ISSUE TITLE
Unexpected failure at "splitting arguments" for a valid YAML scalar content block

### ISSUE THREAD

**Issue by HouzuoGuo** [ansible/ansible#42559] opened 2018-07-10 07:53 UTC
##### SUMMARY
Unexpected failure at "splitting arguments" for a valid YAML scalar content block.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.6.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.14 (default, Mar 16 2018, 18:20:07) [GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]
```

##### CONFIGURATION

(empty output)

##### OS / ENVIRONMENT

Linux 4.14 on x86_64

##### STEPS TO REPRODUCE

```yaml
---
- name: a
  hosts: webtier_server
  tasks:
    - name: a
      win_shell: |
        # a'b
        echo "ha"
```

##### EXPECTED RESULTS

Task execution begins for task "a".

##### ACTUAL RESULTS

```
ERROR! failed at splitting arguments, either an unbalanced jinja2 block or quotes: # a'b
echo "ha"

The error appears to have been in '/home/ec2-user/test.yml': line 5, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: a
      ^ here
```

**Comment by sivel** [comment] 2018-07-15 15:47
Duplicate of https://github.com/ansible/ansible/issues/28674

**Closed as completed by sivel** 2018-07-15 15:47 UTC
Labels: support:core, bug, affects_2.6
