### ISSUE TITLE
variable names with - characters cause exception in some contexts

### ISSUE THREAD

**Issue by e0d** [ansible/ansible#3907] opened 2013-08-21 17:23 UTC
```
- name: analytics-experiments | install application requirements
  pip: 
    requirements={{ analytics-experiments_requirements_file }}
    virtualenv={{ analytics-experiments_venv_dir }} state=present
  sudo: true  
  sudo_user: "{{ analytics-experiments_user }}"
  tags:
  - analytics-experiments
  - deploy
  - install
  - update
```

```
Traceback (most recent call last):
  File "/home/edward/.virtualenvs/ansible/bin/ansible-playbook", line 241, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/edward/.virtualenvs/ansible/bin/ansible-playbook", line 187, in main
    pb.run()
  File "/home/edward/.virtualenvs/ansible/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 215, in run
    play = Play(self, play_ds, play_basedir)
  File "/home/edward/.virtualenvs/ansible/lib/python2.7/site-packages/ansible/playbook/play.py", line 111, in __init__
    self._tasks      = self._load_tasks(self._ds.get('tasks', []), load_vars)
  File "/home/edward/.virtualenvs/ansible/lib/python2.7/site-packages/ansible/playbook/play.py", line 288, in _load_tasks
    results += self._load_tasks(data, mv, included_additional_conditions, original_file=include_filename)
  File "/home/edward/.virtualenvs/ansible/lib/python2.7/site-packages/ansible/playbook/play.py", line 288, in _load_tasks
    results += self._load_tasks(data, mv, included_additional_conditions, original_file=include_filename)
  File "/home/edward/.virtualenvs/ansible/lib/python2.7/site-packages/ansible/playbook/play.py", line 290, in _load_tasks
    results.append(Task(self,x,module_vars=task_vars, additional_conditions=additional_conditions))
  File "/home/edward/.virtualenvs/ansible/lib/python2.7/site-packages/ansible/playbook/task.py", line 118, in __init__
    self.sudo_user    = template.template(play.basedir, ds.get('sudo_user', play.sudo_user), module_vars)
  File "/home/edward/.virtualenvs/ansible/lib/python2.7/site-packages/ansible/utils/template.py", line 308, in template
    varname = template_from_string(basedir, varname, vars)
  File "/home/edward/.virtualenvs/ansible/lib/python2.7/site-packages/ansible/utils/template.py", line 497, in template_from_string
    res = jinja2.utils.concat(t.root_render_func(t.new_context(_jinja2_vars(basedir, vars, t.globals), shared=True)))
  File "<template>", line 9, in root
TypeError: unsupported operand type(s) for -: 'StrictUndefined' and 'StrictUndefined'
```

Changing the sudo_user line to

```
sudo_user: "{{ analyticsexperiments_user }}"
```

fixes the issue.

**Comment by jimi-c** [comment] 2013-08-22 02:04
Variable names should never include dashes, they will be interpreted as a subtraction. This is pretty much true for any language, so stick with underscores.

**Closed as completed by jimi-c** 2013-08-22 02:04 UTC

**Comment by e0d** [comment] 2013-08-22 13:15
Well I'll leave aside the fact that this is factually untrue, but don't you think an error should be raised from ansible rather than having an opaque failure bubble up from the template engine?

**Comment by jimi-c** [comment] 2013-08-22 14:00
I'm not sure what part you're calling untrue, but I agree handling the error rather than dumping a stack trace is always a better solution. In 1.3 we have enabled strict undefined variable detection, which should have caught the above because it's attempting a subtraction between two undefined variables.

**Comment by e0d** [comment] 2013-08-22 17:52
I was referring to your comment about dashes in var names, which is the standard in some languages, like Lisp.

I'm glad this is being addressed in 1.3.

**Comment by jimi-c** [comment] 2013-08-22 18:29
Lisp is one of the few, by and large the vast majority of languages do not allow this (and Lisp only allows it because there are no in-fix operators to confuse it with).

**Comment by bcoca** [comment] 2013-08-22 19:16
some languages allow dashes, many don't. Since ansible is based on
python,yaml & jinja it suffers from the restrictions of these.

If it were written in lisp, you could have dashes in your variables, but
alas, it is not.

**Comment by Balajiswz** [comment] 2018-06-29 06:16
Here the issue is not with the variable name, but the value assigned to the variable. Why the values are not allowed to have "-" in them?
