### ISSUE TITLE
ansible-galaxy should not connect to API server unless its needed

### ISSUE THREAD

**Issue by hani** [ansible/ansible#9687] opened 2014-12-01 23:53 UTC
as title, currently trying to init or install (from scm) a role without external connectivity results in an error that the API server cannot be contacted.

**Comment by willthames** [comment] 2014-12-02 05:25
Use with `--offline`.

**Comment by hani** [comment] 2014-12-03 17:07
To clarify, while init does work with --offline, install does not. So I cannot for example use ansible-galaxy install --offline <internal scm repo>

**Comment by willthames** [comment] 2014-12-03 23:33
I know ansible-galaxy install works fine offline, because all the modifications I made to it were at a company where http to external urls were avoided where possible. 

`ansible-galaxy install` just works - it only contacts the galaxy api if you try and install a role from galaxy itself - if you point it an scm repo (so `git+http...` or `hg+http`) or a local tar file, galaxy won't be contacted. See https://github.com/ansible/ansible/blob/devel/bin/ansible-galaxy#L798

`ansible-galaxy init` does need `--offline` although it'd be nicer if the default template could just be handled without the API calls.

**Comment by voidengineer** [comment] 2016-04-05 06:18
Are there any news on this? This is a real blocker for updating to ansible 2.x.

**Comment by syndbg** [comment] 2016-04-25 16:07
Guess, how about it mentions in the error message that you can use `--offline`? 

E.g

```
~/work/devops/deployutils   ansible_deployutils ●  ansible-galaxy init -p roles common
ERROR! The API server (https://galaxy.ansible.com/api/) is not responding.
Please try again later or run with --offline.
```

**Comment by tknerr** [comment] 2016-07-08 07:59
Same here, the `--offline` switch is not supported in Ansible 2.0.0.2:

```
vagrant@vagrant:/vagrant$ ansible-galaxy install -r requirements.yml -vvv --offline
Usage: ansible-galaxy install [options] [-r FILE | role_name(s)[,version] | scm+role_repo_url[,version] | tar_file(s)]

ansible-galaxy: error: no such option: --offline
```

In my `requirements.yml` there is only an internal repo referenced:

``` yaml
- name: foo-roles
  src: ssh://git@stash.company.com:7999/ansible-roles/foo.git
  version: master
  path: roles
```

Same if I use `src: git+ssh://git@...` as the scm protocol

**Comment by compuguy** [comment] 2016-07-08 16:54
@tknerr 

This bug is fixed in ansible 2.1.0.0 (and I can confirm this as well).

**Comment by bcoca** [comment] 2016-07-08 17:11
closing as this was implemented in 2.1

**Closed as completed by bcoca** 2016-07-08 17:11 UTC
Labels: feature

**Comment by tknerr** [comment] 2016-07-09 06:11
@compuguy true, can confirm this is fixed in 2.1.0.0

Thanks!

**Comment by RichardHightower** [comment] 2016-09-14 18:02
I am getting this error with version 2.1.1.0 and there appears to be no offline mode.

#### No offline mode metioned for 2.1.1.0.

``` sh
$ ansible-galaxy -h
Usage: ansible-galaxy [delete|import|info|init|install|list|login|remove|search|setup] [--help] [options] ...

Options:
  -h, --help     show this help message and exit
  -v, --verbose  verbose mode (-vvv for more, -vvvv to enable connection
                 debugging)
  --version      show program's version number and exit
```

#### Proof that I am running 2.1.1.0

``` sh
bash-3.2$ ansible-galaxy --version
ansible-galaxy 2.1.1.0
  config file = 
  configured module search path = Default w/o overrides
```

#### Proof offline mode doet exist.

``` sh
$ sudo ansible-galaxy --offline install ansiblebit.oracle-java
Usage: ansible-galaxy install [options] [-r FILE | role_name(s)[,version] | scm+role_repo_url[,version] | tar_file(s)]

ansible-galaxy: error: no such option: --offline
```

#### Also I can reach the api URL

``` sh
$ curl -v https://galaxy.ansible.com/api/
*   Trying 40.118.209.130...
* Connected to galaxy.ansible.com (40.118.209.130) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /usr/local/etc/openssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* NPN, negotiated HTTP1.1
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Unknown (67):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*    subject: OU=Domain Control Validated; OU=Gandi Standard SSL; CN=galaxy.ansible.com
*    start date: Apr 26 00:00:00 2015 GMT
*    expire date: Jul 25 23:59:59 2018 GMT
*    subjectAltName: galaxy.ansible.com matched
*    issuer: C=FR; ST=Paris; L=Paris; O=Gandi; CN=Gandi Standard SSL CA 2
*    SSL certificate verify ok.
> GET /api/ HTTP/1.1
> Host: galaxy.ansible.com
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx/1.6.3
< Date: Wed, 14 Sep 2016 18:01:47 GMT
< Content-Type: application/json
< Transfer-Encoding: chunked
< Connection: keep-alive
< Vary: Accept,Cookie
< X-Frame-Options: SAMEORIGIN
< Allow: GET, HEAD, OPTIONS
< Set-Cookie: sessionid=5jm9rbzd5xg0vojlg14lh0h2qdhly7wq; expires=Wed, 28-Sep-2016 18:01:47 GMT; httponly; Max-Age=1209600; Path=/
< 
* Connection #0 to host galaxy.ansible.com left intact
{"available_versions":{"v1":"/api/v1/"},"description":"GALAXY REST API","current_version":"v1"}
```

**Comment by RichardHightower** [comment] 2016-09-14 18:14
https://github.com/ansible/ansible/issues/17570

**Comment by RichardHightower** [comment] 2016-09-14 18:33
I filed another issue and came up with a workaround. So if you are having this problem on a Mac with version 2.1.1.0. There is an issue filed here https://github.com/ansible/ansible/issues/17570 with a workaround in the comments.

**Comment by brainstorm** [comment] 2017-01-11 14:29
I'm seeing this issue with `ansible 2.2.0.0`, does not create `tasks` and other directories:

```
$ ansible-galaxy init foo
ERROR! Failed to get data from the API server (https://galaxy.ansible.com/api/): a bytes-like object is required, not 'str'
$ find foo | wc -l
       9
$ ansible-galaxy init bar --offline
- bar was created successfully
$ find bar | wc -l
      18
```

**Comment by asangal** [comment] 2017-01-24 23:31
If the same issue comes while doing `install` (vs init), then you can refer the solution here: http://stackoverflow.com/questions/41837789/ansible-galaxy-failing-for-init-install-failed-to-get-data-from-the-api-server
