### ISSUE TITLE
2.0.2.0 regression in handling of "until" directive

### ISSUE THREAD

**Issue by larsks** [ansible/ansible#15626] opened 2016-04-27 15:17 UTC
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

2.0.2.0
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Syntax that worked without a problem in 2.0.1.0 is causing an
templating failure in 2.0.2.0.  Specifically, given this:

```
until: "result.rc in [1, 2]"
```

Ansible says:

```
fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check 'result.rc in [1' failed. The error was: template error while templating string: unexpected '}', expected ']'. String: {% if result.rc in [1 %} True {% else %} False {% endif %}"}
```

It appears to be erroneously truncating the condition.  This seems to
be unique to the `until:` keyword; the same syntax works just fine in,
e.g., a `when:` statement.
##### STEPS TO REPRODUCE

Run the following playbook:

```
- hosts: localhost
  gather_facts: false
  tasks:

    - shell: exit $(( RANDOM % 10 ))
      register: result
      until: "result.rc in [1, 2]"
      retries: 10
      delay: 1
      ignore_errors: true
```
##### EXPECTED RESULTS

```
PLAY ***************************************************************************

TASK [command] *****************************************************************
FAILED - RETRYING: TASK: command (9 retries left). Result was: {u'changed': True, u'end': u'2016-04-27 11:14:21.288652', u'stdout': u'', u'cmd': u'exit $(( RANDOM % 10 ))', u'rc': 0, u'start': u'2016-04-27 11:14:21.285226', u'stderr': u'', u'delta': u'0:00:00.003426', 'invocation': {'module_name': u'command', u'module_args': {u'creates': None, u'executable': None, u'chdir': None, u'_raw_params': u'exit $(( RANDOM % 10 ))', u'removes': None, u'warn': True, u'_uses_shell': True}}, 'stdout_lines': [], u'warnings': []}
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "exit $(( RANDOM % 10 ))", "delta": "0:00:00.003918", "end": "2016-04-27 11:14:26.891044", "failed": true, "rc": 1, "start": "2016-04-27 11:14:26.887126", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}
...ignoring

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```
##### ACTUAL RESULTS

```
PLAY [localhost] ***************************************************************

TASK [command] *****************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check 'result.rc in [1' failed. The error was: template error while templating string: unexpected '}', expected ']'. String: {% if result.rc in [1 %} True {% else %} False {% endif %}"}
...ignoring

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```

**Comment by sivel** [comment] 2016-04-27 16:02
This is a duplicate of the already resolved https://github.com/ansible/ansible/issues/15291

The workaround currently is to use:

```
until:
    - "result.rc in [1, 2]"
```

**Closed as completed by sivel** 2016-04-27 16:02 UTC

**Comment by larsks** [comment] 2016-04-27 16:04
Awesome, thanks.
