### ISSUE TITLE
role task rpm_key: key=filename does not use roles/files/filename

### ISSUE THREAD

**Issue by vroetman** [ansible/ansible#10515] opened 2015-03-21 14:37 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

1.8.4
##### Environment:

centos6.6 running

```
ansible-playbook -i hosts -c local provision/playbook.yml
```

where hosts contains

```
127.0.0.1
```
##### Summary:

provision/roles/jenkins/files contains the file jenkins-ci.org.key

provision/roles/jenkins/tasks/main.yml contains the line

```
- rpm_key: state=present key=jenkins-ci.org.key
```

But this fails as it cannot find the key file. In the source the line that fails is line 92 in the file lib/ansible/modules/core/packaging/os/rpm_key.py) which is doing a remote os.path.isfile for the filename:

```
elif os.path.isfile(key):
```

However, when it is run from the playbook provision/playbook.yml with the keyfile in provision/files/jenkins-ci.org.key

```
-rpm_key: state=present key=files/jenkins-ci.org.key
```

Then it works. (probably because the playbook directory is the working directory when the rpm_key.py is run)
##### Steps To Reproduce:

``` bash
TR=testrpm_key
mkdir $TR
echo 127.0.0.1 > $TR/hosts
mkdir -p $TR/roles/jenkins/{files,tasks}
curl -o $TR/roles/jenkins/files/jenkins-ci.org.key http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
echo "- rpm_key: state=present key=jenkins-ci.org.key" >> $TR/roles/jenkins/tasks/main.yml
cat << EOF > $TR/playbook.yml
- hosts: 127.0.0.1

  roles:
    - jenkins
EOF
ansible-playbook -i $TR/hosts -c local $TR/playbook.yml
```
##### Expected Results:

```
PLAY [127.0.0.1] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [jenkins | rpm_key state=present key=jenkins-ci.org.key] **************** 
changed: [127.0.0.1]

PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=2    changed=1    unreachable=0    failed=0   
```
##### Actual Results:

```
PLAY [127.0.0.1] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [jenkins | rpm_key state=present key=jenkins-ci.org.key] **************** 
failed: [127.0.0.1] => {"failed": true}
msg: Not a valid key jenkins-ci.org.key

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/playbook.retry

127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=1   
```

**Comment by vroetman** [comment] 2015-03-22 14:45
Looking further at roles and how ansible works, it seems this is by design.
https://docs.ansible.com/playbooks_roles.html says:
- Any copy tasks can reference files in roles/x/files/ without having to path them relatively or absolutely
- Any script tasks can reference scripts in roles/x/files/ without having to path them relatively or absolutely
- Any template tasks can reference files in roles/x/templates/ without having to path them relatively or absolutely
- Any include tasks can reference files in roles/x/tasks/ without having to path them relatively or absolutely

This is not one of those.

**Comment by nordicmachine** [comment] 2015-04-09 18:51
Any reason that behavious shouldn't be changed?  For example, why wouldn't it make sense to do this instead of having to do three tasks:  Copy key, import, delete key?  Seems like a very useful modification indeed.

**Comment by bcoca** [comment] 2015-04-09 19:19
so reading this, it could be a feature like assemble and unarchive can use both a remote or local source,.

**Comment by vroetman** [comment] 2015-04-10 21:55
Of course, I agree it would be useful. (It took quite a bit of time for me to figure out why this wasn't working for me.) As it is, I have to copy the key someplace in order to install it. And then it takes pains to keep it from running each time if the copy is deleted.

**Comment by Julian** [comment] 2015-06-28 15:35
+1

**Comment by guillermo-carrasco** [comment] 2015-10-20 14:11
+1

**Comment by missnebun** [comment] 2016-01-23 20:39
+1

**Comment by runsisi** [comment] 2016-03-25 10:48
+1

**Comment by xenithorb** [comment] 2016-09-24 11:50
Using 2.1.1 surprised this isn't already the behavior. 

What's stranger is that this person suggests that it can be used that way: https://github.com/marbu/ansible-modules-core-issue-1853-reproducer/commit/41727b465533717015d8d55904c5a102fe248bc4

Related:

https://github.com/ansible/ansible-modules-core/issues/1853
https://github.com/ansible/ansible-modules-core/issues/3789

**Comment by bcoca** [comment] 2016-09-26 15:10
This feature requries an 'action plugin' to be created, as copy, template and other modules have. Only action plugins can get files from the 'controller' and follow role/play search logic.

**Comment by DanyC97** [comment] 2016-11-03 11:03
@bcoca will be nice if the priority will be increased (unfortunately i'm not in a position (yet) to contribute, still learning about it)

**Comment by jimi-c** [comment] 2017-01-05 17:04
As @bcoca noted, this is a module, so everything is taking place on the remote side. You should first push the key to the remote host and then use rpm_key to use it. This module does not do the copying out.

Per the above, I am going to close this now.  If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2017-01-05 17:04 UTC
Labels: affects_1.8, bug, feature

**Comment by xenithorb** [comment] 2017-01-05 17:14
> this is a module, so everything is taking place on the remote side. 

What is the distinction that separates `copy` and `synchronize` and `template` from this limitation? 

Is it supposed to be understood that "Files Modules" get an exception to acquire things from the control machine, but no other module class can do that?

I'm asking for future reference @jimi-c

**Comment by jimi-c** [comment] 2017-01-06 18:22
Each of those has an action plugin, as @bcoca noted, which perform controller-side actions before the module is executed remotely. So copy/etc. all actually result in multiple module executions. You could do the same thing for other modules, however we do not have any plans to create action plugins for every module.

**Comment by xenithorb** [comment] 2017-01-06 18:27
I see, I understand now. Thanks!
