### ISSUE TITLE
template is ignoring variables from defaults/main.yml

### ISSUE THREAD

**Issue by tkaymak** [ansible/ansible#12545] opened 2015-09-28 14:03 UTC
MacOS 10.10.5, ansible 1.9.2:

Error:

```
TASK: [elasticsearch | Copy elasticseach.yml] *********************************
fatal: [consumer-jail-19.acc] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'es_cluster_name' is undefined", 'failed': True}
fatal: [consumer-jail-19.acc] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'es_cluster_name' is undefined", 'failed': True}

FATAL: all hosts have already failed -- aborting
```

defaults/main.yml:

```

---
# ES ClusterName
es_cluster_name: 'bi_elasticsearch'
```

templates/elasticsearch.yml.j2:

```
cluster.name: {{es_cluster_name}}
```

tasks/main.yml:

```
- name: Copy elasticseach.yml
  template: src=elasticsearch.yml.j2 dest=/usr/local/etc/elasticsearch/elasticsearch.yml
```

**Comment by tkaymak** [comment] 2015-09-28 14:31
Removing the single quotes in "defaults/main.yml" did the trick. However, it seems odd that single quotes are breaking this.

**Comment by abadger** [comment] 2016-03-07 21:34
Just tested this with current stable-1.9 and was unable to reproduce so this seems to be fixed.  Going to close it.

**Closed as completed by abadger** 2016-03-07 21:34 UTC
Labels: P2, bug
