### ISSUE TITLE
Conditional check for block with include_role is beign ran for handlers from included role

### ISSUE THREAD

**Issue by samyray** [ansible/ansible#76914] opened 2022-02-01 15:01 UTC
### Summary

In a scenario, when trying to run roles using `loop` and `include_role` from a **playbook**, and if the _first_ role is trying to run task (or whole role) from the _second_ role when this `include_role` command is specified inside `block` with some conditionals, these conditionals will be applied to the `handlers` of the _second_ role when it will be executed later from the playbook, even when they have no relations to it.
And if variables from the conditionals are not defined in the _second_ role, it will fail with an **undefined** error.

### Issue Type

Bug Report

### Component Name

block

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.2]
  config file = None
  configured module search path = ['/Users/samyray/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/samyray/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.10 (main, Jan 26 2022, 14:40:28) [Clang 10.0.1 (clang-1001.0.46.4)]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
<empty>
```

### OS / Environment

ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H1713

### Steps to Reproduce

```yaml (paste below)
#.
#├── playbook.yml
#└── roles
#    ├── first
#    │   ├── defaults
#    │   │   └── main.yml
#    │   └── tasks
#    │       └── main.yml
#    └── second
#        ├── handlers
#        │   └── main.yml
#        ├── meta
#        │   └── main.yml
#        └── tasks
#            └── main.yml
#---------------------
#cat playbook.yml
---
- hosts: localhost
  gather_facts: False
  connection: local
  tasks:

    - name: Include roles
      include_role:
        name: "{{ item }}"
      loop:
        - first
        - second
#---------------------
#cat roles/first/defaults/main.yml
---
test_var: True
#---------------------
#cat roles/first/tasks/main.yml
---
 - block:
    - include_role:
        name: second
 
  when: test_var|bool
#---------------------
#cat roles/second/handlers/main.yml
---
 - name: run_handler
   debug:
    msg: "Handler"
#---------------------
#cat roles/second/meta/main.yml
---
allow_duplicates: true
#---------------------
#cat roles/second/tasks/main.yml
---
- shell: "echo 'Hello Bug'"
  notify:
    - run_handler
 
- meta: flush_handlers
```

### Expected Results

[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [localhost] ***************************************************************************************************************************************************************************************************************************************************

TASK [Include roles] ***********************************************************************************************************************************************************************************************************************************************

TASK [Include second role] *****************************************************************************************************************************************************************************************************************************************

TASK [second : Print hello] ****************************************************************************************************************************************************************************************************************************************
changed: [localhost]

TASK [second : meta] ***********************************************************************************************************************************************************************************************************************************************

RUNNING HANDLER [second : run_handler] *****************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "Handler"
}

TASK [second : Print hello] ****************************************************************************************************************************************************************************************************************************************
changed: [localhost]

TASK [second : meta] ***********************************************************************************************************************************************************************************************************************************************

RUNNING HANDLER [second : run_handler] *****************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "Handler"
}

PLAY RECAP *********************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=4    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

### Actual Results

```console
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [localhost] ***************************************************************************************************************************************************************************************************************************************************

TASK [Include roles] ***********************************************************************************************************************************************************************************************************************************************

TASK [Include second role] *****************************************************************************************************************************************************************************************************************************************

TASK [second : Print hello] ****************************************************************************************************************************************************************************************************************************************
changed: [localhost]

TASK [second : meta] ***********************************************************************************************************************************************************************************************************************************************
[WARNING]: flush_handlers task does not support when conditional

RUNNING HANDLER [second : run_handler] *****************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'test_var|bool' failed. The error was: error while evaluating conditional (test_var|bool): 'test_var' is undefined\n\nThe error appears to be in '/Users/samyray/work/development/playbook/roles/second/handlers/main.yml': line 3, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: run_handler\n  ^ here\n"}

NO MORE HOSTS LEFT *************************************************************************************************************************************************************************************************************************************************

PLAY RECAP *********************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by mkrizek** [comment] 2022-02-01 15:59
Closing as duplicate of https://github.com/ansible/ansible/issues/39543 (the underlying issue is the same) which we are leaving open. Unfortunately fixing this would break backward compatibility.

If you have further questions please stop by IRC or the mailing list:
* IRC: #ansible on irc.libera.chat
* mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Closed as completed by mkrizek** 2022-02-01 15:59 UTC
Labels: support:core, bug, affects_2.12
