### ISSUE TITLE
Regression in 2.1.1: {group,host}_vars from cwd get ignored if inventory is a directory

### ISSUE THREAD

**Issue by alvaroaleman** [ansible/ansible#16983] opened 2016-08-06 00:57 UTC
##### ISSUE TYPE
- Bug Report and regression, this works fine in 2.1.0
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### STEPS TO REPRODUCE

Create a directory layout like this:

``` yml

├── ansible.cfg
├── host_vars
│   └── localhost
├── inventory
│   └── hosts
└── playbooks
    └── playbook.yml

```

Execute `ansible-playbook playbooks/playbook.yml` from top level directory and try to use a variable that is defined in `host_vars/localhost`

A testcase can be found here: https://github.com/alvaroaleman/ansible-testcase-group_vars

**Comment by hswong3i** [comment] 2016-08-06 07:21
Confirm with the case as reported, all of my ansible roles/playbook pass test with Travis CI since the test case inventory file located one level above {group,host}_vars directory, but always ignore {group,host}_vars directory when running manually, e.g. https://github.com/pantarei/ansible-playbook-ubuntu/tree/master:

```
group_vars
└── all
host_vars
└── ubuntu.aio
inventory
└── ubuntu.aio
tests
├── group_vars
│   └── all
├── hosts
└── test.yml
playbooks
├── setup-everything.yml
├── setup-hosts.yml
├── setup-infrastructure.yml
└── setup-service.yml
```

Which means these works:

```
ansible-playbook -i tests/hosts tests/test.yml
ansible-playbook -i ubuntu.aio playbooks/setup-everything.yml
```

But this not works

```
ansible-playbook -i inventory/ubuntu.aio playbooks/setup-everything.yml
```

**Comment by bcoca** [comment] 2016-08-08 17:16
duplicate of #16956

**Closed as completed by bcoca** 2016-08-08 17:16 UTC
