### ISSUE TITLE
local variable 'incorrect_password' referenced before assignment

### ISSUE THREAD

**Issue by jgrigonis** [ansible/ansible#10436] opened 2015-03-11 20:02 UTC
I get a failure with the head revision on the 1.9 stable branch.

This yml code works fine with the 1.8 release.

This is running against a CentOS 6.6 machine.
- name: install semanage
  yum: name=policycoreutils-python state=latest

I get the following traceback:

TASK: [install semanage] *****************************************************\* 
fatal: [testrefgo] => Traceback (most recent call last):
  File "/Users/jgrigonis/github/ansible/lib/ansible/runner/**init**.py", line 582, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/Users/jgrigonis/github/ansible/lib/ansible/runner/__init__.py", line 785, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/Users/jgrigonis/github/ansible/lib/ansible/runner/__init__.py", line 1026, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/Users/jgrigonis/github/ansible/lib/ansible/runner/action_plugins/normal.py", line 57, in run
    return self.runner._execute_module(conn, tmp, module_name, module_args, inject=inject, complex_args=complex_args)
  File "/Users/jgrigonis/github/ansible/lib/ansible/runner/__init__.py", line 547, in _execute_module
    res = self._low_level_exec_command(conn, cmd, tmp, become=self.become, sudoable=sudoable, in_data=in_data)
  File "/Users/jgrigonis/github/ansible/lib/ansible/runner/__init__.py", line 1163, in _low_level_exec_command
    in_data=in_data)
  File "/Users/jgrigonis/github/ansible/lib/ansible/runner/connection_plugins/ssh.py", line 362, in exec_command
    (returncode, stdout, stderr) = self._communicate(p, stdin, in_data, sudoable=sudoable, prompt=prompt)
  File "/Users/jgrigonis/github/ansible/lib/ansible/runner/connection_plugins/ssh.py", line 176, in _communicate
    elif stdout.endswith("%s\r\n%s" % (incorrect_password, prompt)):
UnboundLocalError: local variable 'incorrect_password' referenced before assignment

FATAL: all hosts have already failed -- aborting

**Comment by bcoca** [comment] 2015-03-11 20:03
duplicate of #10434

**Closed as completed by bcoca** 2015-03-11 20:03 UTC

**Comment by jgrigonis** [comment] 2015-03-11 20:06
Sure is.
