### ISSUE TITLE
Various issues with assigning an only_if conditional to a variable.

### ISSUE THREAD

**Issue by dcoutu** [ansible/ansible#341] opened 2012-05-08 23:40 UTC
Defining a Conditional Execution Variable in a Playbook evaluate properly, however defining that same variable in an external variable file and importing it via vars_files in the Playbook fails.

i.e. is_backendserver: "'$class' == 'backend'"

fatal: [host01] => Traceback (most recent call last):
  File "/home/me/git/ansible/lib/ansible/runner.py", line 569, in _executor
    (host, ok, data, err) = self._executor_internal(host)
  File "/home/me/git/ansible/lib/ansible/runner.py", line 608, in _executor_internal
    result = self._execute_normal_module(conn, host, tmp, module_name)
  File "/home/me/git/ansible/lib/ansible/runner.py", line 341, in _execute_normal_module
    (result, err, executed) = self._execute_module(conn, tmp, module, self.module_args)
  File "/home/me/git/ansible/lib/ansible/runner.py", line 266, in _execute_module
    if not eval(conditional):
  File "<string>", line 1
    $is_backendserver
    ^
SyntaxError: invalid syntax

**Comment by mpdehaan** [comment] 2012-05-09 00:17
Hmm... vars_files is probably not double templated or something.

Assigning to the 0.4 release but possibly might have to wait for 0.5, depends if folks have cycles and want to fix it.

**Comment by mpdehaan** [comment] 2012-05-09 00:19
Here is the other report from dcoutu:

Defining the same task in the top level playbook works as expected, but when the task is defined in an external tasklist, i.e. - include: tasks/deploy-tasks.yml, the conditional execution is not evaluated properly.

Traceback (most recent call last):
File "/home/me/git/ansible/bin/ansible-playbook", line 109, in 
sys.exit(main(sys.argv[1:]))
File "/home/me/git/ansible/bin/ansible-playbook", line 86, in main
extravars=extra_vars
File "/home/me/git/ansible/lib/ansible/playbook.py", line 122, in __init_
self.playbook = self.parse_playbook(playbook)
File "/home/me/git/ansible/lib/ansible/playbook.py", line 206, in _parse_playbook
self._include_tasks(play, task, dirname, new_tasks)
File "/home/me/git/ansible/lib/ansible/playbook.py", line 172, in _include_tasks
included = utils.parse_yaml(included)
File "/home/me/git/ansible/lib/ansible/utils.py", line 255, in parse_yaml
return yaml.load(data)
File "/usr/lib64/python2.6/site-packages/yaml/init_.py", line 58, in load
return loader.get_single_data()
File "/usr/lib64/python2.6/site-packages/yaml/constructor.py", line 42, in get_single_data
node = self.get_single_node()
File "/usr/lib64/python2.6/site-packages/yaml/composer.py", line 36, in get_single_node
document = self.compose_document()
File "/usr/lib64/python2.6/site-packages/yaml/composer.py", line 55, in compose_document
node = self.compose_node(None, None)
File "/usr/lib64/python2.6/site-packages/yaml/composer.py", line 82, in compose_node
node = self.compose_sequence_node(anchor)
File "/usr/lib64/python2.6/site-packages/yaml/composer.py", line 111, in compose_sequence_node
node.value.append(self.compose_node(node, index))
File "/usr/lib64/python2.6/site-packages/yaml/composer.py", line 84, in compose_node
node = self.compose_mapping_node(anchor)
File "/usr/lib64/python2.6/site-packages/yaml/composer.py", line 127, in compose_mapping_node
while not self.check_event(MappingEndEvent):
File "/usr/lib64/python2.6/site-packages/yaml/parser.py", line 93, in check_event
self.current_event = self.state()
File "/usr/lib64/python2.6/site-packages/yaml/parser.py", line 434, in parse_block_mapping_key
"expected , but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block mapping
in "", line 11, column 5:
- name: deploy servercode
  ^
  expected , but found ''
  in "", line 13, column 16:
  only_if: ''$class' == 'backend''

**Comment by cocoy** [comment] 2012-05-09 09:02
When task is defined as external such as in include:

only_if: 'not ($is_favcolor_blue)'  

does _not_ work. 

But this work: 

only_if: "not ($is_favcolor_blue)"

See for example:  https://gist.github.com/2643148

**Comment by mpdehaan** [comment] 2012-05-09 12:27
It seems we should just construct a lot of unit tests for "only_if" behavior, ideally using playbooks, and see what tasks get executed and which do not.

**Comment by cocoy** [comment] 2012-05-10 08:48
Seems defining a variable on a playbook: 
is_favcolor_blue: "'$favcolor' == 'blue'"

And accessing it on the included task. with only_if statement: 
..
   only_if: "not ($is_favcolor_blue)" 

It always work with --double qoutes-- for me. Same with  var_files that are included using double qoute used in only_if.

**Comment by mpdehaan** [comment] 2012-05-10 12:10
yeah I need to remind myself of why that is since I think the varReplace function is the only thing being used here.

Probably by putting some debug into the crazy double_template call.   The template code should basically ignore quotes, and I thought YAML would have already eaten them, so that is interesting.   

```
  conditional = utils.double_template(self.conditional, inject, self.setup_cache)
    if not eval(conditional):
        return [ utils.smjson(dict(skipped=True)), None, 'skipped' ]
```

**Comment by jhoekx** [comment] 2012-05-11 10:09
These errors are generally caused by us templating the YAML before inclusion, leading to double quoting. Maybe I'm not seeing the big picture here, but why are doing that?

We can just include the include file and the templating will happen al right, both in the conditional and in the arguments?
(I tried this and the tests all passed, unsure how well this is tested)

**Comment by mpdehaan** [comment] 2012-05-11 23:14
merged some fixes for this.

https://github.com/ansible/ansible/pull/363

please test and see if they work for you.

how much and when we template is a little confusing at the moment, in 0.5 I hope to make this a lot more obvious, but it used to be that we could support a Jinja2 template and it made sense then because the Jinja2 might not be YAML legal.   That is not the case anymore, thankfully.

**Comment by mpdehaan** [comment] 2012-05-11 23:14
closing for now, let me know if I need to reopen

**Closed as completed by mpdehaan** 2012-05-11 23:14 UTC

**Comment by dcoutu** [comment] 2012-05-14 16:38
Pulled the latest devel version this morning, but looks like it is still broken with the same error message reported.  Looks like we need to re-open.

**Comment by dcoutu** [comment] 2012-05-14 16:45
Scratch the re-open request, user error on a syntax in the included vars_file.  Fixed the formatting and is working as expected now.  Thanks!
