### ISSUE TITLE
`collections` playbook keyword does not support templating

### ISSUE THREAD

**Issue by nkakouros** [ansible/ansible#69054] opened 2020-04-20 22:22 UTC
##### SUMMARY

The `collections` keyword does not support templating, contrary to other playbook keywords, such as `module_defaults`.

I am trying to specify the collections list at a single place and then just reference them in every playbook instead of bloating each playbook.

Alternatively, it would be great if there was a configuration variable, e.g. `ANSIBLE_DEFAULT_COLLECTIONS`, for that purpose.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

collections

##### ANSIBLE VERSION

```paste below
ansible 2.10.0.dev0
  config file = /home/nikos/Projects/ansible-demo/ansible.cfg
  configured module search path = ['/home/nikos/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/nikos/.local/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.1 (default, Jan 22 2020, 06:38:00) [GCC 9.2.0]
```

##### CONFIGURATION

```paste below
none
```

##### STEPS TO REPRODUCE

`play1.yml`
```yaml
---
- hosts: localhost
  gather_facts: no
  tags: qqq
  tasks:
    - set_fact:
        collections:
          - community.general
```

`play2.yml`
```
---

- hosts: localhost
  collections: "{{ collections }}"
  tasks:
    - debug:
        msg: "{{ list1 | union(list2) }}"
```

`playbook.yml`
```
---

- import_playbook: play1.yml

- import_playbook: play2.yml

```

##### EXPECTED RESULTS

I would expect the collections list to be resolved.

##### ACTUAL RESULTS

```paste below
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are modifying the Ansible engine, or trying out features under development. This is a rapidly changing source of code and can become unstable at any point.
ansible-playbook 2.10.0.dev0
  config file = /home/nikos/Projects/ansible-demo/ansible.cfg
  configured module search path = ['/home/nikos/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/nikos/.local/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.8.1 (default, Jan 22 2020, 06:38:00) [GCC 9.2.0]
Using /home/nikos/Projects/ansible-demo/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/nikos/Projects/ansible-demo/inventory/inventory.yml as it did not pass its verify_file() method
script declined parsing /home/nikos/Projects/ansible-demo/inventory/inventory.yml as it did not pass its verify_file() method
Parsed /home/nikos/Projects/ansible-demo/inventory/inventory.yml inventory source with yaml plugin
ERROR! Unexpected Exception, this is probably a bug: 'AnsibleUnicode' object has no attribute 'append'
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 123, in <module>
    exit_code = cli.run()
  File "/home/nikos/.local/lib/python3.8/site-packages/ansible/cli/playbook.py", line 127, in run
    results = pbex.run()
  File "/home/nikos/.local/lib/python3.8/site-packages/ansible/executor/playbook_executor.py", line 91, in run
    pb = Playbook.load(playbook_path, variable_manager=self._variable_manager, loader=self._loader)
  File "/home/nikos/.local/lib/python3.8/site-packages/ansible/playbook/__init__.py", line 51, in load
    pb._load_playbook_data(file_name=file_name, variable_manager=variable_manager)
  File "/home/nikos/.local/lib/python3.8/site-packages/ansible/playbook/__init__.py", line 96, in _load_playbook_data
    pb = PlaybookInclude.load(entry, basedir=self._basedir, variable_manager=variable_manager, loader=self._loader)
  File "/home/nikos/.local/lib/python3.8/site-packages/ansible/playbook/playbook_include.py", line 42, in load
    return PlaybookInclude().load_data(ds=data, basedir=basedir, variable_manager=variable_manager, loader=loader)
  File "/home/nikos/.local/lib/python3.8/site-packages/ansible/playbook/playbook_include.py", line 72, in load_data
    pb._load_playbook_data(file_name=file_name, variable_manager=variable_manager, vars=self.vars.copy())
  File "/home/nikos/.local/lib/python3.8/site-packages/ansible/playbook/__init__.py", line 103, in _load_playbook_data
    entry_obj = Play.load(entry, variable_manager=variable_manager, loader=self._loader, vars=vars)
  File "/home/nikos/.local/lib/python3.8/site-packages/ansible/playbook/play.py", line 116, in load
    return p.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/home/nikos/.local/lib/python3.8/site-packages/ansible/playbook/base.py", line 235, in load_data
    self._attributes[target_name] = method(name, ds[name])
  File "/home/nikos/.local/lib/python3.8/site-packages/ansible/playbook/collectionsearch.py", line 44, in _load_collections
    _ensure_default_collection(collection_list=ds)
  File "/home/nikos/.local/lib/python3.8/site-packages/ansible/playbook/collectionsearch.py", line 31, in _ensure_default_collection
    collection_list.append('ansible.legacy')
AttributeError: 'AnsibleUnicode' object has no attribute 'append'

```

**Comment by sivel** [comment] 2020-04-21 01:13
Ultimately this is expected, and a duplicate of https://github.com/ansible/ansible/issues/68704

However, we should not traceback here, so the traceback needs to be fixed.

cc @Shrews

**Comment by nkakouros** [comment] 2020-04-21 11:24
@sivel  Should I open a separate issue for the request to have a config option or sth similar for specifying default collections or is this out of the question already?

**Comment by sivel** [comment] 2020-04-21 14:34
I don't see it changing any time soon. When we evaluated the issue referenced above, we came to the conclusion that it's not currently feasible. At best, we *might* be able to support only `--extra-vars`, but even to do so would become complicated.

We have recorded this as a functionality that users have asked for already, so there is no need to create an issue for it.

**Closed as completed** 2020-04-28 15:47 UTC
Labels: python3, support:core, bug, has_pr, traceback, affects_2.10
