### ISSUE TITLE
poetry does not install all of ansible dependencies

### ISSUE THREAD

**Issue by david-griffiths-eigen** [ansible/ansible#66178] opened 2020-01-03 16:46 UTC
#66122 ### SUMMARY
When installing ansible using poetry the dependency cryptography is not automatically installed. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
PyPI JSON API for Ansible

##### ANSIBLE VERSION

```paste below
ansible 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/david.griffiths/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/david.griffiths/miniconda3/lib/python3.7/site-packages/ansible
  executable location = /home/david.griffiths/miniconda3/bin/ansible
  python version = 3.7.3 (default, Mar 27 2019, 22:11:17) [GCC 7.3.0]

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

From the poetry documentation https://python-poetry.org/blog/poetry-0-8-0-is-out.html 
```
Fallback mechanism for missing dependencies

poetry uses the PyPI JSON API to retrieve package information.
```
 However, upon inspection the ansible dependency cryptography is missing from info.requires_dist at https://pypi.org/pypi/ansible/json

As a work around we have needed to add cryptography to the toml file, along with ansible: 
```
[tool.poetry.dependencies]
python = "^3.7"
ansible = "^2.9.1"                  # GPL
certifi = "2019.6.16"               # MLP
cryptography = "^2.8"               # Apache 2.0
```
However, if the info.requires_dist were suitably populated then poetry would "know" to install cryptography by inspecting https://pypi.org/pypi/ansible/json

**Comment by sivel** [comment] 2020-01-03 16:48
Duplicate of https://github.com/ansible/ansible/issues/64299

**Closed as completed by sivel** 2020-01-03 16:48 UTC
