### ISSUE TITLE
LC_ALL sets when running ansible with become user (sudo) on remote host

### ISSUE THREAD

**Issue by bortek** [ansible/ansible#15138] opened 2016-03-24 12:36 UTC
I am using Ansible to execute remote java commands on multiple servers using sudo like this

ansible -o -i /my/hosts/file myhostname -m shell -a "java -jar myfile.jar" -b --become-user=remote_user --ask-become-pass -k

Since ver 2.0.0 of Ansible for some reason it adds "LC_ALL=en_US.UTF-8" to the process it starts. This causes a major issue since Java application reads locale from env variable and uses it instead of some other locale set in Java.

One can see this by looking at the output of this
cat /proc/PID/environ |strings|grep --color LC_

and what I see it this
SUDO_COMMAND=/bin/sh -c echo BECOME-SUCCESS-pczarfgulenmjcrbairsyfcajgcpuvtt; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /u            sr/bin/python /tmp/ansible-tmp-1458818705.34-210547486321208/command

I have tested this with Ansible 1.7.2 and there is no problem as it only sets LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 and not LC_ALL

How can you explain setting LC_ALL and why are you doing this?
How can this be disabled?
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

ansible 2.0.0
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

RHEL6.6
Linux 2.6.32-504.3.3.el6.x86_64
##### STEPS TO REPRODUCE

I run this example command to start my java process
ansible -o -i /my/hosts/file myhostname -m shell -a "java -jar myfile.jar" -b --become-user=remote_user --ask-become-pass -k

Then you can verify the actual LC_
##### EXPECTED RESULTS

LC_ALL and other LC_\* variables should NOT be altered
##### ACTUAL RESULTS

ansible changes LC_\* variables and test them to UTF-8

**Comment by abadger** [comment] 2016-03-30 20:50
@jimi-c made this change in 2.0 to avoid tracebacks when non-ascii values are processed.  What is the actual problem that you are encountering?  There are a few potential workarounds depending on your needs.

If this is something you wish to set for all modules, setting module_lang in ansible.cfg or setting the  ANSIBLE_MODULE_LANG environment variable will probably work for you.  Be sure to set this to a locale that uses utf-8 encoding or you may encounter the bug that changing this in the first place was intended to fix.

If you want to set this only when you call your java command, use the environment task attribute in a playbook like this:

```
- hosts: all
  tasks:
    - shell: java -jar myfile.jar
      environment:
        LC_ALL: fr_FR.utf-8
```

Note that environment is not a parameter of the shell module.  It is a task attribute and should be indented to the same level as "shell:"

**Comment by bortek** [comment] 2016-04-01 06:55
Well I am not running a ansible-playbook I run just "ansible" command to execute remote commands on multiple servers.

On a remote servers I execute a bash script which among other things contain these locale settings

LANG=en_US.ISO8859-1
LC_CTYPE=en_US.ISO8859-1
LC_NUMERIC=en_US.ISO8859-1
LC_TIME=en_US.ISO8859-1
LC_COLLATE=en_US.ISO8859-1
LC_MONETARY=en_US.ISO8859-1
LC_MESSAGES=C

But when I execute it with ansible, it sets 
LANG=en_US.UTF-8 
LC_ALL=en_US.UTF-8 

on a shell overwriting all my LC_ settings that I mention above thus locale in my Java becomes UTF-8.

**Comment by bortek** [comment] 2016-04-01 12:21
POST UPDATED:

Well I am not running a ansible-playbook I run just "ansible" command to execute remote commands on multiple servers.

On a remote servers I execute a bash script which among other things contain these locale settings

LANG=en_US.ISO8859-1
LC_CTYPE=en_US.ISO8859-1
LC_NUMERIC=en_US.ISO8859-1
LC_TIME=en_US.ISO8859-1
LC_COLLATE=en_US.ISO8859-1
LC_MONETARY=en_US.ISO8859-1
LC_MESSAGES=C

But when I execute it with ansible, it sets 
LANG=en_US.UTF-8 
LC_ALL=en_US.UTF-8 

variables.  And specifically LC_ALL will take precedence. It will effectively invalidate all my other LC_ settings. Therefore it does not matter what I have set in ly LC_COLLATE or LC_TIME or other LC_\* since LC_ALL will set all of LC_ to UTF-8. 

This mean that everything I execute with ansible will have locale and lang set to UTF-8 via these env variables.  

So now Image (as en example!) I start a Java application that reads some data from a filer or database or net socket. It expects the data to be in a special encoding (ISO8859-1) and then suddenly I see a garbage on the screen instead of valid data. Because now those bits and bytes are interpreted differently due to different encoding. 

I think you get the point?

**Comment by abadger** [comment] 2016-04-01 15:41
For your script example, have the script unset LC_ALL.

**Comment by abadger** [comment] 2016-04-01 15:55
Okay, @jimi-c thinks that setting module_lang in ansible.cfg or setting the ANSIBLE_MODULE_LANG to a non-utf8 encoding should work as well... I'm not so sure about it but you can give that a try too.

**Comment by bortek** [comment] 2016-04-04 12:10
Unseting LC_ALL works of course but that implies changing tenths of scripts in all my environments. Thats a lot of "unneccessary" work caused by a change in the "management" tool.

Now I am running latest ansible 2.1.0 fetched from github. I have tried setting ANSIBLE_MODULE_LANG (in /etc/ansible.cfg) to something other than UTF-8 and it has no effect, still UTF-8.

Can't you add a config parameter that would disable forwarding of 

"LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8" 

from the controller machine to remote machine? Kind of switch to allow a user to fallback me to old behavior.

I found others having had similar issues related to this:
https://github.com/ansible/ansible/issues/6169
https://github.com/ansible/ansible/issues/13399
https://github.com/ansible/ansible/issues/7060
https://groups.google.com/forum/#!topic/ansible-project/XwJmFPfMfo0
https://groups.google.com/forum/#!topic/ansible-devel/qF79dEV2Ml4

**Comment by wolfgangkarall** [comment] 2016-04-05 16:07
Using module_lang doesn't help, ansible should stop messing with LC_ALL completely. In my case, it breaks etckeeper sorting, even though it tries to be locale-independent by setting LC_COLLATE to C.

Basically the fix for #11055 should've never introduced the setting of LC_ALL.

**Comment by abadger** [comment] 2016-04-05 17:12
@wolfgangkarall Does envirnment: work for your case?

Assigning to @jimi-c as this is a policy question, not a code question (well, unless jimi-c thinks that module_lang should be working here in which case there may be a bug in the implementation of setting a different global LC_ALL.)

From what I remember of the original issue (not just the apt bug pointed out above but the discussions around setting LC_\* ), modules often have bugs[_] around non-ascii handling in non-utf8 locales which leads to tracebacks.  Setting a utf-8 locale unconditionally "fixes" that (in the sense that the code then handles non-ascii data correctly for any ut8 locale).  So if ansible continues setting a utf8 locale those bugs will have been essentially "fixed".  OTOH, if ansible goes back to not setting LC__ users will be able to rely on their remote user's environment settings taking precedence over any explicit settings that they make.

[_] My criteria for buggy here is that code should not rely on a specific environment to run. So although I think the hundreds of individual modules that are the basis of the arguments for setting of LC_ALL to be buggy I also think that @bortek's script is buggy for not unsetting LC_ALL at the same time as it sets all the other LC__ variables.  So jimi-c's going to be a much better decision maker on the policy we want than I.

**Comment by wolfgangkarall** [comment] 2016-04-05 19:18
Ok, just to be precise and avoid searching for bugs regarding module_lang: it does indeed work, i.e. when I set `module_lang = C` in ansible.cfg, it does show in the locale on the remote system, i.e.

`ansible <host> -a locale`

I get LANG, all LC_\* vars and also LC_ALL set to 'C', even tho the target host uses en_US.UTF-8 when I connect with plain ssh. I suppose using the 'environment' keyword will probably work as well.

But the issue is, setting LC_ALL overrides all decisions by software developers selectively setting other LC_\* variables than the default, because it made sense to them because they knew the effects.

Using that strong override as developer when calling a couple of known binaries as child processes (where one can hope to see the side effects easily) is one thing, using it when providing a wrapper mechanism to run arbitrary software on remote systems (like ansible's shell/command module does) is a whole different story.

**Comment by jimi-c** [comment] 2016-04-05 20:11
The broader problem is that some modules rely on scraping command output, which sometimes follows localization but which may also not like `C`. It was for this reason that we defaulted LC_ALL, so if you have an alternative which achieves both goals I'm open to suggestions. It was situations like this, however, for which we added the module_lang option.

**Comment by wolfgangkarall** [comment] 2016-04-05 22:07
If something is scraping locale-dependent command output and doesn't deal with setting up the locale properly itself, then it's broken. Basically, that's a case for 'developers selectively setting other LC_\* variables than the default, because it made sense to them because they knew the effects' I mention above, just the developer failing to do so.

Even so, if a user of ansible is confronted with such a case and can override the locale settings on a per-play/task basis, great, you have my full support. But setting LC_ALL on all shell/command module runs and thus override numbers of well-thought-out, specific LC_\* variables in 3rd party software is rather intrusive.

**Comment by wolfgangkarall** [comment] 2016-04-05 22:30
For reference:

glibc: https://sourceware.org/glibc/wiki/Locales (discourages usage outside of the scope of scripts with specific use case)
Debian: https://wiki.debian.org/Locale (discourages usage rather generally)
gettext: https://www.gnu.org/software/gettext/manual/html_node/Locale-Environment-Variables.html (discourages use in initialization of a shell, which fits the bill with the way ansible does it in its shell/command module)

**Comment by bortek** [comment] 2016-04-06 06:33
I completely agree with @wolfgangkarall , you underlined the problem pretty well in your posts. Setting LC_ALL overrides all the LC_\* settings which to me looks lite it was a quick and dirty fix tom some past problem had fixed.

@abadger I don't think I will be changing my remote scripts due to ansible changed it's behavior. It is the same as saying "all your remote scripts that you execute with ansible should by default have unset LC_ALL" cause we do not not how that will affect your applications. That sounds ridiculous. I would rather stop using ansible at all and use something else. 

@jimi-c What I suggest is to implement a a fallback mechanism through e.g a config parameter (via ansible.cfg) which will fallback to "old" behavior and will NOT set any of "LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8"

**Comment by wolfgangkarall** [comment] 2016-04-06 08:19
Just FTR: in #11055 (specifically https://github.com/ansible/ansible/issues/11055#issuecomment-105596308 ) it's mentioned that LC_MESSAGES does not work for apt-get/aptitude (at least 'AFAIK'), which is plain wrong as a quick tests shows:

```
# locale -a | grep utf8 | while read utf8locale; do
echo -n "$utf8locale: "
LC_MESSAGES=$utf8locale apt-get update | tail -n1
done
cs_CZ.utf8: Načítají se seznamy balíků…
de_DE.utf8: Paketlisten werden gelesen...
el_GR.utf8: Ανάγνωση Λιστών Πακέτων...
en_US.utf8: Reading package lists...
es_ES.utf8: Leyendo lista de paquetes...
fr_FR.utf8: Lecture des listes de paquets…
hr_HR.utf8: Reading package lists...
hu_HU.utf8: Csomaglisták olvasása...
it_IT.utf8: Lettura elenco dei pacchetti...
nb_NO.utf8: Leser pakkelister...
nl_NL.utf8: Pakketlijsten worden ingelezen...
nn_NO.utf8: Les pakkelister...
pl_PL.utf8: Czytanie list pakietów...
ru_RU.utf8: Чтение списков пакетов…
sk_SK.utf8: Načítavajú sa zoznamy balíkov...
sl_SI.utf8: Branje seznama paketov...
```

Which is not surprising, since LC_ALL is only an override for LC_MESSAGES.

**Comment by jimi-c** [comment] 2016-04-06 13:11
Does this patch resolve the issue for you?

<pre>
diff --git a/lib/ansible/plugins/shell/__init__.py b/lib/ansible/plugins/shell/__init__.py
index bef4541..39a6be0 100644
--- a/lib/ansible/plugins/shell/__init__.py
+++ b/lib/ansible/plugins/shell/__init__.py
@@ -33,7 +33,7 @@ class ShellBase(object):
     def __init__(self):
         self.env = dict(
             LANG        = C.DEFAULT_MODULE_LANG,
-            LC_ALL      = C.DEFAULT_MODULE_LANG,
+            #LC_ALL      = C.DEFAULT_MODULE_LANG,
             LC_MESSAGES = C.DEFAULT_MODULE_LANG,
         )
 </pre>

**Comment by wolfgangkarall** [comment] 2016-04-06 14:07
@jimi-c Yep, it does indeed.

Edit: for my specific case it's ok if LANG/LC_MESSAGES is set by ansible, but in general I guess ansible should leave the locale of the target system be. If a module is parsing output, that module needs to take care of setting up the locales.

**Comment by bortek** [comment] 2016-04-06 14:08
@jimi-c With this patch you completely remove LC_ALL and don't set it at all, right? 
Still it does not resolve my issue because besides LC_ALL I am using LC_MESSAGES and LANG too in my script. That means that they will still be re-set to UTF8 by Ansible.

How about introducing new config parameter for ansible.conf called e.g. SET_LOCALE. It would by default be True and would set LANG        LC_ALL      LC_ALL      to UTF8 as it is today. 

But if SET_LOCALE=False then it would not set them at all or whatever behavior it was before this was changed some time ago?

That way I could just set the parameter to False in ansible.conf and it would work y for me and other who need it.

**Comment by wolfgangkarall** [comment] 2016-04-06 14:19
I'd rather set the default to False (or maybe to True with a deprecation warning for a couple of versions) and fix the modules (at least apt and yum, according to #11055 and #9635) instead.

**Comment by jimi-c** [comment] 2016-04-06 16:20
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by jimi-c** [comment] 2016-04-06 16:21
@wolfgangkarall I'm not disabling that by default, it's something users will have to decide to disable. If we decide we really don't need LC_ALL we can remove it completely regardless.

**Comment by wolfgangkarall** [comment] 2016-04-06 17:55
@jimi-c I guess that's what openssl maintainers told themselves when dealing with ancient ciphers and protocols...

Thanks nonetheless for the quick implementation of the workaround, I hope the documentation for the new setting mentions a few of the pitfalls you can run into when using the provided default.

**Comment by bortek** [comment] 2016-04-07 11:36
Great job! Thanks @jimi-c and all the others involved for a quickly resolving this. I have now tested it and it works as I expected it. :)

**Comment by abadger** [comment] 2016-04-07 14:02
Some notes here:

@wolfgangkarall The reason LC_ALL is necessary for Ansible is exactly the rationale you bring up.  Since LC_ALL overrides all other LC\* env vars, Ansible has to set LC_ALL if it's trying to  sanitize the environment it's going to run itself in.  If you think LC_ALL is just a poorly designed interface (A setting that overrides more specific settings rather than a setting that establishes a default for more specific settings) then you'd have my 100% agreement :-)

@jimi-c If we're really making this setting just for screenscraping then I move into the camp of removing it altogether.  We should definitely be dealing with screenscraping by setting the locale explicitly when we call programs that we screenscrape data from.  Setting global LC_\* on the whole process just for that is wrong.  I also note that we've been taking patches to set LC_\* when screenscraping recently so I don't think that the settings are having the desired effect.  However, when this was added, the argument was that it protected python from tracebacking when modules mixed unicode and bytes.  I just tested this, though, and I don't think this argument is actually true...  I can definitely provoke tracebacks mixing unicode and bytes even though ansible is setting the locale.

**Comment by abadger** [comment] 2016-04-07 14:04
I'm reopening so that we remember to talk about this but changing to feature idea and targeting for devel because there's now a workaround in 2.0 that should fix the issue for both reporters.

**Comment by bortek** [comment] 2016-04-07 14:06
So your propossl is to remove it completely,  right?

**Comment by abadger** [comment] 2016-04-07 14:15
Ah -- the reason that screenscraping is not helped by this setting is probably in the default value that we assign:

```
DEFAULT_MODULE_LANG       = get_config(p, DEFAULTS, 'module_lang',      'ANSIBLE_MODULE_LANG',      os.              getenv('LANG', 'en_US.UTF-8'))
```

So we're not actually sanitizing the remote environment to a known value.  Instead we're setting the remote environment to the value of the local LANG if that's set.  This makes it unhelpful for screenscraping as we still don't have a predictable remote locale setting on which to base our scraping.

@bortek Correct.  After we discuss and @jimi-c maybe tells me what it is I'm missing, we'll either end up with this setting that @jimi-c added so that users can decide whether to set LC_\* or we won't add LC_\* at all.

**Comment by wolfgangkarall** [comment] 2016-04-07 15:16
@abadger Why and where does ansible has to sanitize its own environment regarding LC_ALL? AFAICT from the other issues, ansible _modules_ need to sanitize the environment of when calling external binaries whose output they want to scrape.

And I don't think LC_ALL is that bad a design (after all there's LANG too, and even LANGUAGE these days), it's just used in a wrong way here. It's meant for debugging and specific use cases, not for overriding locale in a multi-purpose shell (which ansible is in the case of shell/command module) which is likely to call other software using LC_\* variables.

**Comment by wolfgangkarall** [comment] 2016-04-07 15:19
@abadger btw, since you're looking into module_lang, the documentation even says, module_lang defaults to 'C' at http://docs.ansible.com/ansible/intro_configuration.html just to use en_US.UTF-8 in the block following that statement. :)

**Comment by abadger** [comment] 2016-04-07 17:33
@wolfgangkarall it's used in a wrong way everywhere.  Several distributions (well to be fair, the recent ones I've checked it's more accurate to say some packages within the distributions that drop things in /etc/profile.d/ so probably not distro-policy, just packaging bugs) set LC_ALL in login scripts.  LC_ALL should not be used but the only way to prevent it from being used is to not have it available in the first place.  Too many people use it without understanding that it's infectious nature.

Yeah, docs need updating.  I think previously module_lang was C but then was changed to en_US.utf8 in the discussions I referred to above.

**Comment by bortek** [comment] 2016-04-15 06:40
Guys do you have any updates on this ?

**Comment by abadger** [comment] 2016-04-20 21:04
Okay -- we discussed this at today's meeting and tentatively decided that setting LC_\* and LANG at the global level aren't the right way to go about this.  We should set these variables inside specific modules when they do specific things (for instance, when we screenscrape the output of a command line tool).  This is, however, something that could be backwards compatible and also could reveal a lot of bugs in modules which have been expecting that we set these values globally rather than each module needing to do it individually.

So the plan is to make use of the config value to allow toggling between behaviours.  For 2.1.x we'll leave the value as it is for backwards compatibility.  Once 2.1.x branches from devel we'll switch the default to not set the LC_\* and LANG vars and fix and fix modules that report problems because of that.  We'll evaluate before 2.1.x releases whether to leave the 2.1.x default no setting of the locales or turn it back on for backwards compatibility for another release.

Thanks everyone for input on this.

**Closed as completed by abadger** 2016-04-20 21:04 UTC
Labels: feature
