### ISSUE TITLE
Error: "No such file or directory" during provision with docker_image

### ISSUE THREAD

**Issue by bocharsky-bw** [ansible/ansible#10987] opened 2015-05-12 08:26 UTC
When I do `vagrant provision` using `Ansbile` as provisioner, I get next error:

``` bash
failed: [default] => {"changed": false, "failed": true}
msg: ConnectionError(ProtocolError('Connection aborted.', error(2, 'No such file or directory')),)

FATAL: all hosts have already failed -- aborting
```

My ansible playbook file is:

``` yaml

---
-   name: Vagrant provisioning using Ansible Playbook for Ubuntu 14.04
    hosts: all
    sudo: yes
    tasks:
        - name: check or build nginx image
          docker_image: path="/vagrant/docker/nginx" name="my/nginx" state=build
```

The `/vagrant/` dir is mount with vagrant as `nfs`. On VM `Dockerfile` exists by `/vagrant/docker/nginx/Dockerfile` path.

Is this a bug? Or I do something wrong with `docker_image: path` config?

**Comment by abadger** [comment] 2015-05-12 15:50
It would be good to get the full error (maybe with ansible-playbook running with -vvvv) to be sure but I think this error is being thrown before we run the task.  It looks to me like it's happening when we setup the ssh connection to the remote host.

**Comment by abadger** [comment] 2015-05-12 15:50
More complete error message and step-by-step information on how to reproduce would help in tracking this down.

**Comment by bocharsky-bw** [comment] 2015-05-13 20:55
There is more info about this https://github.com/ansible/ansible-docker-base/issues/13

**Comment by bocharsky-bw** [comment] 2015-05-22 12:03
@abadger  Sorry, I don't really know what caused this error, but few days later after update my box, restart laptop and run provision again all works.

I upload my work example on `ubuntu/trusty64` box with `Nginx` and `PHP-FPM` containers to [GitHub](https://github.com/bocharsky-bw/vagrant-ansible-docker/tree/44d8d07ddd80e6c550719f4297dd6b054e540540), maybe it helps anyone to start.

If nobody has this error, I think issue could be closed.

**Comment by jimi-c** [comment] 2015-07-13 18:48
Hi @bocharsky-bw, per the above I'm going to go ahead and close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-07-13 18:48 UTC
Labels: needs_info, P2, docker, bug
