### ISSUE TITLE
"script" module does not work in Windows (Authentication or permission failure)

### ISSUE THREAD

**Issue by stu-smith** [ansible/ansible#14085] opened 2016-01-23 12:31 UTC
It seems that the "script" module under Windows no longer works correctly. It now gives the error:

`Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in "/tmp".`

The "script" module works fine under `stable-1.9`, but does not work under `stable-2.0`. I believe it worked correctly under the main branch until a couple of weeks ago.

Example of output working correctly (as of a couple of weeks ago):

```
<10.51.30.57> ESTABLISH WINRM CONNECTION FOR USER: cloud on PORT 5986 TO 10.51.30.57
<10.51.30.57> WINRM CONNECT: transport=ssl endpoint=https://10.51.30.57:5986/wsman
<10.51.30.57> EXEC Set-StrictMode -Version Latest
(New-Item -Type Directory -Path $env:temp -Name "ansible-tmp-1453332209.69-193824785181852").FullName | Write-Host -Separator '';
<10.51.30.57> WINRM OPEN SHELL: 42FF6705-B264-4699-AF03-9D348978D09E
<10.51.30.57> WINRM EXEC u'PowerShell' [u'-NoProfile', u'-NonInteractive', u'-ExecutionPolicy', u'Unrestricted', u'-EncodedCommand', u'U...endcoded...=']
```

Example of latest, non-working output:

```
<10.184.44.122> ESTABLISH WINRM CONNECTION FOR USER: cloud on PORT 5986 TO 10.184.44.122
<10.184.44.122> WINRM CONNECT: transport=ssl endpoint=https://10.184.44.122:5986/wsman
<10.184.44.122> EXEC /bin/sh -c 'PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand U...encoded...A'
<10.184.44.122> WINRM OPEN SHELL: CA9D1FE9-250C-4C8D-B77A-9FAD7000B695
<10.184.44.122> WINRM EXEC 'PowerShell' ['-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Unrestricted', '-EncodedCommand', 'L...encoded...==']
<10.184.44.122> WINRM RESULT u'<Response code 1, out "", err "#< CLIXML\r\n<Objs Ver">'
<10.184.44.122> WINRM CLOSE SHELL: CA9D1FE9-250C-4C8D-B77A-9FAD7000B695
fatal: [te-h-amers2-20160123-004025-app_instance-ywak3o5la6oa]: UNREACHABLE! => {"changed": false, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\".
```

**Comment by jhawkesworth** [comment] 2016-01-23 14:24
Hello, 

Could you please share the playbook to reproduce this? 

Also please advise ansible version, Python version, controller operating system and windows target version. 

Also please can you run with -vvvvv and supply the output?

I used script in 2.0.0.2 many times yesterday so I am hoping this is either environmental or a platform-specific problem. 

Jon

**Comment by jhawkesworth** [comment] 2016-01-25 14:33
Does your remote temp directory exist?

If you run the following powershell on your windows host do you get an error?

``` powershell
gci -Path $env:temp
```

**Comment by jhawkesworth** [comment] 2016-01-25 14:35
Noticed that someone else had same error message back in Nov which makes me think this is possibly an environmental difference rather than necessarily a change introduced in Ansible 2.0.

See irc archive here: http://www.mattzone.com/ansible/ansible_20151103.html

**Comment by stu-smith** [comment] 2016-01-26 09:08
@jhawkesworth yes temp exists and is writable to the user in question (cloud). Looking in temp as you suggest gives me:

```
PS C:\Users\cloud> gci -Path $env:temp


    Directory: C:\Users\cloud\AppData\Local\Temp\2


Mode                LastWriteTime     Length Name
----                -------------     ------ ----
-a---         1/26/2016   9:07 AM        149 jusched.log
```

**Comment by stu-smith** [comment] 2016-01-26 09:36
OK I believe I have narrowed this down a little bit.

I have reduced my deploy script to deploying to a single Windows instance, with the following playbook:

```
---

- name: Test
  hosts: app:&iis
  gather_facts: false
  tasks:

    - name: Test
      script: scripts/test.ps1
```

(where `test.ps1` just does a `Write-Host`)

I am pulling Ansible using variations on the following command:

```
git clone https://github.com/ansible/ansible.git --recursive --branch xxx
```

...followed by a `make install`.

The following table lists which branches work and which don't:

| Branch | Works? |
| --- | --- |
| latest / no branch | No |
| stable-2.0.0.1 | Yes |
| stable-2.0 | No |
| stable-1.9 | Yes |

Since I would guess the differences between 2.0 and 2.0.0.1 are most likely to lead to finding the exact problem, I've included my command output for those two branches in full below:

```
an-ers2-20160123-103606-ansible-instance-yiwsqccpgwls:/home/cloud/test-deploy # ansible --version && ANSIBLE_CLOUDS_DIR=/home/cloud/clouds ANSIBLE_ENVIRONMENT=ci-orch  ansible-playbook -i inventory/ci-orch playbook.yml --limit "test-authentication:&ci-orch" --extra-vars "temp=/home/cloud/test-deploy/temp liquibase_launcher=/home/cloud/liquibase-launcher.sh build=66" --vault-password-file vault_pass.txt -vvvvv
ansible 2.0.0.0
  config file = /home/cloud/test-deploy/ansible.cfg
  configured module search path = Default w/o overrides
Using /home/cloud/test-deploy/ansible.cfg as config file
Loaded callback default of type stdout, v2.0
1 plays in playbook.yml

PLAY [Test] ********************************************************************

TASK [Test] ********************************************************************
task path: /home/cloud/test-deploy/playbook.yml:8
<10.206.148.110> ESTABLISH WINRM CONNECTION FOR USER: cloud on PORT 5986 TO 10.206.148.110
<10.206.148.110> WINRM CONNECT: transport=ssl endpoint=https://10.206.148.110:5986/wsman
<10.206.148.110> EXEC /bin/sh -c 'PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand UwBlAHQALQBTAHQAcgBpAGMAdABNAG8AZABlACAALQBWAGUAcgBzAGkAbwBuACAATABhAHQAZQBzAHQACgAoAE4AZQB3AC0ASQB0AGUAbQAgAC0AVAB5AHAAZQAgAEQAaQByAGUAYwB0AG8AcgB5ACAALQBQAGEAdABoACAAJABlAG4AdgA6AHQAZQBtAHAAIAAtAE4AYQBtAGUAIAAiAGEAbgBzAGkAYgBsAGUALQB0AG0AcAAtADEANAA1ADMAOAAwADAAMwA1ADYALgAyADQALQAyADUANAAzADYAOAA3ADkAMAA0ADYAMwA3ADUAOAAiACkALgBGAHUAbABsAE4AYQBtAGUAIAB8ACAAVwByAGkAdABlAC0ASABvAHMAdAAgAC0AUwBlAHAAYQByAGEAdABvAHIAIAAnACcAOwA='
<10.206.148.110> WINRM OPEN SHELL: 4C29958C-F154-4E3B-9CEC-9F3A38E38F54
<10.206.148.110> WINRM EXEC 'PowerShell' ['-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Unrestricted', '-EncodedCommand', 'LwBiAGkAbgAvAHMAaAAgAC0AYwAgACcAUABvAHcAZQByAFMAaABlAGwAbAAgAC0ATgBvAFAAcgBvAGYAaQBsAGUAIAAtAE4AbwBuAEkAbgB0AGUAcgBhAGMAdABpAHYAZQAgAC0ARQB4AGUAYwB1AHQAaQBvAG4AUABvAGwAaQBjAHkAIABVAG4AcgBlAHMAdAByAGkAYwB0AGUAZAAgAC0ARQBuAGMAbwBkAGUAZABDAG8AbQBtAGEAbgBkACAAVQB3AEIAbABBAEgAUQBBAEwAUQBCAFQAQQBIAFEAQQBjAGcAQgBwAEEARwBNAEEAZABBAEIATgBBAEcAOABBAFoAQQBCAGwAQQBDAEEAQQBMAFEAQgBXAEEARwBVAEEAYwBnAEIAegBBAEcAawBBAGIAdwBCAHUAQQBDAEEAQQBUAEEAQgBoAEEASABRAEEAWgBRAEIAegBBAEgAUQBBAEMAZwBBAG8AQQBFADQAQQBaAFEAQgAzAEEAQwAwAEEAUwBRAEIAMABBAEcAVQBBAGIAUQBBAGcAQQBDADAAQQBWAEEAQgA1AEEASABBAEEAWgBRAEEAZwBBAEUAUQBBAGEAUQBCAHkAQQBHAFUAQQBZAHcAQgAwAEEARwA4AEEAYwBnAEIANQBBAEMAQQBBAEwAUQBCAFEAQQBHAEUAQQBkAEEAQgBvAEEAQwBBAEEASgBBAEIAbABBAEcANABBAGQAZwBBADYAQQBIAFEAQQBaAFEAQgB0AEEASABBAEEASQBBAEEAdABBAEUANABBAFkAUQBCAHQAQQBHAFUAQQBJAEEAQQBpAEEARwBFAEEAYgBnAEIAegBBAEcAawBBAFkAZwBCAHMAQQBHAFUAQQBMAFEAQgAwAEEARwAwAEEAYwBBAEEAdABBAEQARQBBAE4AQQBBADEAQQBEAE0AQQBPAEEAQQB3AEEARABBAEEATQB3AEEAMQBBAEQAWQBBAEwAZwBBAHkAQQBEAFEAQQBMAFEAQQB5AEEARABVAEEATgBBAEEAegBBAEQAWQBBAE8AQQBBADMAQQBEAGsAQQBNAEEAQQAwAEEARABZAEEATQB3AEEAMwBBAEQAVQBBAE8AQQBBAGkAQQBDAGsAQQBMAGcAQgBHAEEASABVAEEAYgBBAEIAcwBBAEUANABBAFkAUQBCAHQAQQBHAFUAQQBJAEEAQgA4AEEAQwBBAEEAVgB3AEIAeQBBAEcAawBBAGQAQQBCAGwAQQBDADAAQQBTAEEAQgB2AEEASABNAEEAZABBAEEAZwBBAEMAMABBAFUAdwBCAGwAQQBIAEEAQQBZAFEAQgB5AEEARwBFAEEAZABBAEIAdgBBAEgASQBBAEkAQQBBAG4AQQBDAGMAQQBPAHcAQQA9ACcA']
<10.206.148.110> WINRM RESULT u'<Response code 1, out "", err "#< CLIXML\r\n<Objs Ver">'
<10.206.148.110> WINRM CLOSE SHELL: 4C29958C-F154-4E3B-9CEC-9F3A38E38F54
fatal: [te-h-amers1-20160120-161614-app_instance-ibrsao5jzsvm]: UNREACHABLE! => {"changed": false, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand UwBlAHQALQBTAHQAcgBpAGMAdABNAG8AZABlACAALQBWAGUAcgBzAGkAbwBuACAATABhAHQAZQBzAHQACgAoAE4AZQB3AC0ASQB0AGUAbQAgAC0AVAB5AHAAZQAgAEQAaQByAGUAYwB0AG8AcgB5ACAALQBQAGEAdABoACAAJABlAG4AdgA6AHQAZQBtAHAAIAAtAE4AYQBtAGUAIAAiAGEAbgBzAGkAYgBsAGUALQB0AG0AcAAtADEANAA1ADMAOAAwADAAMwA1ADYALgAyADQALQAyADUANAAzADYAOAA3ADkAMAA0ADYAMwA3ADUAOAAiACkALgBGAHUAbABsAE4AYQBtAGUAIAB8ACAAVwByAGkAdABlAC0ASABvAHMAdAAgAC0AUwBlAHAAYQByAGEAdABvAHIAIAAnACcAOwA=, exited with result 1", "unreachable": true}
```

```
an-ers2-20160123-103606-ansible-instance-yiwsqccpgwls:/home/cloud/test-deploy # ansible --version && ANSIBLE_CLOUDS_DIR=/home/cloud/clouds ANSIBLE_ENVIRONMENT=ci-orch  ansible-playbook -i inventory/ci-orch playbook.yml --limit "test-authentication:&ci-orch" --extra-vars "temp=/home/cloud/test-deploy/temp liquibase_launcher=/home/cloud/liquibase-launcher.sh build=66" --vault-password-file vault_pass.txt -vvvvv
ansible 2.0.0.2
  config file = /home/cloud/test-deploy/ansible.cfg
  configured module search path = Default w/o overrides
Using /home/cloud/test-deploy/ansible.cfg as config file
Loaded callback default of type stdout, v2.0
1 plays in playbook.yml

PLAY [Test] ********************************************************************

TASK [Test] ********************************************************************
task path: /home/cloud/test-deploy/playbook.yml:8
<10.206.148.110> ESTABLISH WINRM CONNECTION FOR USER: cloud on PORT 5986 TO 10.206.148.110
<10.206.148.110> WINRM CONNECT: transport=ssl endpoint=https://10.206.148.110:5986/wsman
<10.206.148.110> EXEC Set-StrictMode -Version Latest
(New-Item -Type Directory -Path $env:temp -Name "ansible-tmp-1453800579.24-246181514630938").FullName | Write-Host -Separator '';
<10.206.148.110> WINRM OPEN SHELL: 0371F241-5C30-4444-A7D7-5A58624B8B35
<10.206.148.110> WINRM EXEC u'PowerShell' [u'-NoProfile', u'-NonInteractive', u'-ExecutionPolicy', u'Unrestricted', u'-EncodedCommand', u'UwBlAHQALQBTAHQAcgBpAGMAdABNAG8AZABlACAALQBWAGUAcgBzAGkAbwBuACAATABhAHQAZQBzAHQACgAoAE4AZQB3AC0ASQB0AGUAbQAgAC0AVAB5AHAAZQAgAEQAaQByAGUAYwB0AG8AcgB5ACAALQBQAGEAdABoACAAJABlAG4AdgA6AHQAZQBtAHAAIAAtAE4AYQBtAGUAIAAiAGEAbgBzAGkAYgBsAGUALQB0AG0AcAAtADEANAA1ADMAOAAwADAANQA3ADkALgAyADQALQAyADQANgAxADgAMQA1ADEANAA2ADMAMAA5ADMAOAAiACkALgBGAHUAbABsAE4AYQBtAGUAIAB8ACAAVwByAGkAdABlAC0ASABvAHMAdAAgAC0AUwBlAHAAYQByAGEAdABvAHIAIAAnACcAOwA=']
<10.206.148.110> WINRM RESULT u'<Response code 0, out "C:\\Users\\cloud\\AppDa", err "">'
<10.206.148.110> PUT "/home/cloud/test-deploy/scripts/test.ps1" TO "C:\Users\cloud\AppData\Local\Temp\ansible-tmp-1453800579.24-246181514630938\test.ps1"
<10.206.148.110> WINRM PUT "/home/cloud/test-deploy/scripts/test.ps1" to "C:\Users\cloud\AppData\Local\Temp\ansible-tmp-1453800579.24-246181514630938\test.ps1" (offset=19 size=19)
<10.206.148.110> EXEC &  "C:\Users\cloud\AppData\Local\Temp\ansible-tmp-1453800579.24-246181514630938\test.ps1"
<10.206.148.110> WINRM EXEC 'PowerShell' ['-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Unrestricted', '-EncodedCommand', 'JgAgACAAIgBDADoAXABVAHMAZQByAHMAXABjAGwAbwB1AGQAXABBAHAAcABEAGEAdABhAFwATABvAGMAYQBsAFwAVABlAG0AcABcAGEAbgBzAGkAYgBsAGUALQB0AG0AcAAtADEANAA1ADMAOAAwADAANQA3ADkALgAyADQALQAyADQANgAxADgAMQA1ADEANAA2ADMAMAA5ADMAOABcAHQAZQBzAHQALgBwAHMAMQAiAA==']
<10.206.148.110> WINRM RESULT u'<Response code 0, out "Test\n", err "">'
<10.206.148.110> EXEC Set-StrictMode -Version Latest
Remove-Item "C:\Users\cloud\AppData\Local\Temp\ansible-tmp-1453800579.24-246181514630938" -Force -Recurse;
<10.206.148.110> WINRM EXEC u'PowerShell' [u'-NoProfile', u'-NonInteractive', u'-ExecutionPolicy', u'Unrestricted', u'-EncodedCommand', u'UwBlAHQALQBTAHQAcgBpAGMAdABNAG8AZABlACAALQBWAGUAcgBzAGkAbwBuACAATABhAHQAZQBzAHQACgBSAGUAbQBvAHYAZQAtAEkAdABlAG0AIAAiAEMAOgBcAFUAcwBlAHIAcwBcAGMAbABvAHUAZABcAEEAcABwAEQAYQB0AGEAXABMAG8AYwBhAGwAXABUAGUAbQBwAFwAYQBuAHMAaQBiAGwAZQAtAHQAbQBwAC0AMQA0ADUAMwA4ADAAMAA1ADcAOQAuADIANAAtADIANAA2ADEAOAAxADUAMQA0ADYAMwAwADkAMwA4ACIAIAAtAEYAbwByAGMAZQAgAC0AUgBlAGMAdQByAHMAZQA7AA==']
<10.206.148.110> WINRM RESULT u'<Response code 0, out "", err "">'
<10.206.148.110> WINRM CLOSE SHELL: 0371F241-5C30-4444-A7D7-5A58624B8B35
changed: [te-h-amers1-20160120-161614-app_instance-ibrsao5jzsvm] => {"changed": true, "invocation": {"module_args": {"_raw_params": "scripts/test.ps1"}, "module_name": "script"}, "rc": 0, "stderr": "", "stdout": "Test\n", "stdout_lines": ["Test"]}

PLAY RECAP *********************************************************************
te-h-amers1-20160120-161614-app_instance-ibrsao5jzsvm : ok=1    changed=1    unreachable=0    failed=0
```

**Comment by jhawkesworth** [comment] 2016-01-26 10:33
I was going to ask, and this may be a red herring but, if you run the same
command as a raw ansible module call do you get the same folder?

i.e.

```
ansible windowshost -i /your/inventory -m raw -a 'gci -path $env:temp'
```

Having seen your update, would it be possible to try your test against the
different branches again in a different order?  The reason I ask, and this
is pure speculation at the moment, is I wonder if a logout or timeout is
removing the temp dir for the session you are getting.  I'm not fully aware
of code changes but I don't think there has been much recently regarding
the winrm connection - if something has changed twice between 1.9.stable
and latest dev.. well I'd be surprised.

If it is something that's changed between stable-2.0 and stable-2.0.0.1 it
might be possible to determine what using git bisect, but that's not
something I've tried before myself.

**Comment by stu-smith** [comment] 2016-01-26 11:30
I ran a modified version of the command you suggested as ad-hoc:

```
an-ers2-20160123-103606-ansible-instance-yiwsqccpgwls:/home/cloud/test-deploy # ANSIBLE_CLOUDS_DIR=/home/cloud/clouds ANSIBLE_ENVIRONMENT=ci-orch  ansible "windows:&test-authentication:&ci-orch" -i inventory/ci-orch -m raw -a 'Write-Host $env:temp' -vvvvv
Using /home/cloud/test-deploy/ansible.cfg as config file
Loaded callback minimal of type stdout, v2.0
<10.206.148.110> ESTABLISH WINRM CONNECTION FOR USER: cloud on PORT 5986 TO 10.206.148.110
<10.206.148.110> WINRM CONNECT: transport=ssl endpoint=https://10.206.148.110:5986/wsman
<10.206.148.110> EXEC Write-Host $env:temp
<10.206.148.110> WINRM OPEN SHELL: 7CF2FE91-111F-47EB-97C2-C276DB50F7C6
<10.206.148.110> WINRM EXEC 'PowerShell' ['-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Unrestricted', '-EncodedCommand', 'VwByAGkAdABlAC0ASABvAHMAdAAgACQAZQBuAHYAOgB0AGUAbQBwAA==']
<10.206.148.110> WINRM RESULT u'<Response code 0, out "C:\\Users\\cloud\\AppDa", err "">'
<10.206.148.110> WINRM CLOSE SHELL: 7CF2FE91-111F-47EB-97C2-C276DB50F7C6
te-h-amers1-20160120-161614-app_instance-ibrsao5jzsvm | SUCCESS | rc=0 >>
C:\Users\cloud\AppData\Local\Temp
```

I guess that's what you'd expect: RDP sessions use numbered sub-folders within Temp, but a direct WinRM connection doesn't.

Regarding something that changed, and then changed back:

| Branch | Link |
| --- | --- |
| Latest | https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/basic.py#L1813 |
| stable-2.0.0.1 | https://github.com/ansible/ansible/blob/stable-2.0.0.1/lib/ansible/module_utils/basic.py#L1766 |
| stable-2.0 | https://github.com/ansible/ansible/blob/stable-2.0/lib/ansible/module_utils/basic.py#L1770 |
| stable-1.9 | https://github.com/ansible/ansible/blob/stable-1.9/lib/ansible/module_utils/basic.py#L1465 |

**Comment by nitzmahone** [comment] 2016-02-02 18:52
fixed by https://github.com/ansible/ansible/pull/14272

**Closed as completed by nitzmahone** 2016-02-02 18:52 UTC
Labels: windows, bug
