### ISSUE TITLE
Problem with {{ item }} concatenation in use with with_items directive

### ISSUE THREAD

**Issue by decayofmind** [ansible/ansible#9552] opened 2014-11-13 15:32 UTC
Hi! Let's have a playbook like these:

``` yaml
- hosts: all
  sudo: yes
  tasks:
    - name: Reproduce items bug
      yum: name=nagios-plugins-{{ item }} state=present
      with_items:
        - dhcp
        - disc
        - dummy
```

and if you run this playbook, you can see an error:

> failed: [mylovelyhost] => (item=dhcp,disc,dummy) => {"changed": false, "failed": true, "item":  "dhcp,disc,dummy", "rc": 0, "results": ["nagios-plugins-dhcp-1.4.16-10.fc20.x86_64 providing nagios-plugins-dhcp is already installed"]}
> msg: No Package matching 'disc' found available, installed or updated

So, string concatenation with {{ item }} variable in with_items cycle will only work for the first step. For next steps only pure {{ item }} will sended.

**Comment by bcoca** [comment] 2014-11-13 15:54
try:

 yum: name={{'nagios-plugins-' +  item }}

On Thu, Nov 13, 2014 at 10:32 AM, decayofmind notifications@github.com
wrote:

> Hi! Let's have a playbook like these:
> - hosts: all
>   sudo: yes
>   tasks:
>   - name: Reproduce items bug
>     yum: name=nagios-plugins-{{ item }} state=present
>     with_items:
>     - dhcp
>     - disc
>     - dummy
> 
> and if you run this playbook, you can see an error:
> 
> failed: [mylovelyhost] => (item=dhcp,disc,dummy) => {"changed": false,
> "failed": true, "item": "dhcp,disc,dummy", "rc": 0, "results":
> ["nagios-plugins-dhcp-1.4.16-10.fc20.x86_64 providing nagios-plugins-dhcp
> is already installed"]}
> msg: No Package matching 'disc' found available, installed or updated
> 
> So, string concatenation with {{ item }} variable in with_items cycle will
> only work for the first step. For next steps only pure {{ item }} will
> sended.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ansible/ansible/issues/9552.

## 

Brian Coca

**Comment by bcoca** [comment] 2014-11-13 15:56
actually scratch that, yum modules is 'smart' with_items and it is taking
the whole list in an optimization, most other modules do not work this way,
but it improves performance of apt and yum modules.

On Thu, Nov 13, 2014 at 10:54 AM, Brian Coca bcoca@ansible.com wrote:

> try:
> 
>  yum: name={{'nagios-plugins-' +  item }}
> 
> On Thu, Nov 13, 2014 at 10:32 AM, decayofmind notifications@github.com
> wrote:
> 
> > Hi! Let's have a playbook like these:
> > - hosts: all
> >   sudo: yes
> >   tasks:
> >   - name: Reproduce items bug
> >     yum: name=nagios-plugins-{{ item }} state=present
> >     with_items:
> >     - dhcp
> >     - disc
> >     - dummy
> > 
> > and if you run this playbook, you can see an error:
> > 
> > failed: [mylovelyhost] => (item=dhcp,disc,dummy) => {"changed": false,
> > "failed": true, "item": "dhcp,disc,dummy", "rc": 0, "results":
> > ["nagios-plugins-dhcp-1.4.16-10.fc20.x86_64 providing nagios-plugins-dhcp
> > is already installed"]}
> > msg: No Package matching 'disc' found available, installed or updated
> > 
> > So, string concatenation with {{ item }} variable in with_items cycle
> > will only work for the first step. For next steps only pure {{ item }} will
> > sended.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ansible/ansible/issues/9552.
> 
> ## 
> 
> Brian Coca

## 

Brian Coca

**Comment by mpdehaan** [comment] 2014-11-17 22:02
Yeah this is a duplicate of some previous questions.

I would suggest this:

 with_items:
        - nagios-plugins-dhcp
        - nagios-plugins-disc
        - nagios-plugins-dummy

And then just name={{ item }}

That will sort things out.

Sorry for the confusion!

**Closed as completed by mpdehaan** 2014-11-17 22:02 UTC
