### ISSUE TITLE
feature request: option vault-password-file in ansible.cfg

### ISSUE THREAD

**Issue by resmo** [ansible/ansible#6980] opened 2014-04-14 11:03 UTC
Instead of given the argument `--vault-password-file <file>` by cli. I would like to have an option in ansible.cfg to set it in defaults:

```
[defaults]
vault-password-file = <file>
```

**Comment by gildegoma** [comment] 2014-04-14 11:17
It seems to be a duplicate of #6947 ;)

**Closed as completed** 2014-04-14 11:26 UTC
