### ISSUE TITLE
Cannot inline array in when statement

### ISSUE THREAD

**Issue by artur-fijalkowski** [ansible/ansible#16272] opened 2016-06-14 13:04 UTC
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible-playbook --version
ansible-playbook 2.0.0.2
  config file = /var/lib/jenkins/jobs/XXX/workspace/ansible.cfg
  configured module search path = modules/ansible
```
##### CONFIGURATION

Nothing special
##### OS / ENVIRONMENT

Linux

Replicable on Ubuntu and CentOS
##### SUMMARY

Following line works as expected

```
when: job_status.json.status == 'FAILED' or job_status.json.status == 'PASSED'
```

Wrapping same code with inline array:

```
when: job_status.json.status in ['FAILED','PASSED']
```

Triggers error:
[\"FAILED\"' failed. The error was: template error while templating string: unexpected '}', expected ']'. String: {% if job_status.json.status in [\"FAILED\" %} True {% else %} False {% endif %}
##### STEPS TO REPRODUCE

```

```

##### EXPECTED RESULTS

Syntax for 'in' operator should work in when statement with inline array definition.
Most probably inline array is interpreted differently, most probably can be fixed by enforcing interpretation of [] when preceded by in operator.
##### ACTUAL RESULTS

```

```

**Comment by sivel** [comment] 2016-06-14 13:16
This is a duplicate of the already resolved https://github.com/ansible/ansible/issues/15291

The fix was included in the 2.1 release.

**Closed as completed by sivel** 2016-06-14 13:16 UTC
