### ISSUE TITLE
V2 bug: Can't pickle <type 'module'>

### ISSUE THREAD

**Issue by dougluce** [ansible/ansible#10923] opened 2015-05-05 21:24 UTC
It hangs before the ^C:

```
% ansible-playbook -i inventory site_degenerate.yml

PLAY: <no name specified> *******************************************************

TASK [setup] ********************************************************************
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 266, in _feed
    send(obj)
PicklingError: Can't pickle <type 'module'>: attribute lookup __builtin__.module failed
^C
PLAY RECAP **********************************************************************
```

ansible 2.0 (detached HEAD f310d13280) on Ubuntu 12.04.5 LTS

I've confirmed that 0b83626 doesn't give this error.

site_degenerate.yml:

```

---
- hosts:
  - toolboxes
  vars:
  - some_var: "{{ data_host }}"
```

inventory:

```
[toolboxes]
toolbox.prod.toyokeizai.net

[toolboxes:vars]
data_host=some_host
```

**Comment by bcoca** [comment] 2015-05-05 22:04
~~soo it looks like you are trying to use an early version of the v2 tree, which is what both of those commits affect, this is not an issue in current devel.~~ play has single task (implied gather facts)

i get rid of the error by setting gather_facts: False, bring it back by adding a debug task, so it seems to be something task related

**Comment by dougluce** [comment] 2015-05-05 22:08
This is an issue in current devel.  Sorry for not being explicit about that, I filed this after a bisect.

Just confirmed the failure again in ansible 2.0 (devel 9b95c22dc0) last updated 2015/05/05 22:06:12 (GMT +000)

**Comment by bcoca** [comment] 2015-05-05 22:11
this is a v2 issue I'm guessing and only with an playbook without tasks.

**Comment by dougluce** [comment] 2015-05-05 22:12
That's just the smallest playbook I could easily get to fail.  Also fails with tasks.

**Comment by jimi-c** [comment] 2015-05-06 01:35
I've isolated this down to the variable within the variable - commenting that out clears up the issue. Continuing to investigate why now.

**Comment by jimi-c** [comment] 2015-05-06 01:43
And confirmed this bisects to f310d132806dd6870a92cd93b2a8983c24ff548d

**Comment by jimi-c** [comment] 2015-05-06 06:32
I've pushed the above commit to the v2_final branch, which corrects this bug in my testing.

**Comment by dougluce** [comment] 2015-05-06 18:54
The example I gave earlier now runs for me without errors on 4f28a814.

However, something else pops up:

```
ERROR! The module setup was not found in configured module paths. Additionally, core modules are missing. If this is a checkout, run 'git submodule update --init --recursive' to correct this problem.
```

Looks like `self._searched_paths` is getting out of sync with `self._plugin_path_cache` -- maybe one isn't getting serialized (in `lib/plugins/__init__.py`)?

Please let me know if you'd like me to open another issue w/full example etc.

**Comment by jimi-c** [comment] 2015-05-06 20:52
Yes, I've just fixed that as well on v2_final.

**Comment by dougluce** [comment] 2015-05-06 22:13
Cool!  Just re-ran on 1152c73 -- everything works!

**Comment by dougluce** [comment] 2015-05-06 23:49
I spoke too soon.  With a different playbook (on the same system and sha):

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 266, in _feed
    send(obj)
PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed
```

Let me know if I should dig a bit more and get you a proper repro.

**Comment by jimi-c** [comment] 2015-05-07 18:01
Yes, please do.

**Comment by dougluce** [comment] 2015-05-07 19:33
Okay, it's https://github.com/ansible/ansible/issues/10945 -- let me know if I can do something more.

**Comment by jimi-c** [comment] 2015-05-08 02:17
Since the original error was fixed, as well as the follow-up, I'm going to go ahead and close this. If you see any further issues along these lines, let us know and/or open another issue. Thanks!

**Closed as completed by jimi-c** 2015-05-08 02:17 UTC
Labels: bug
