### ISSUE TITLE
Variable referencing in playbook vars section

### ISSUE THREAD

**Issue by drybjed** [ansible/ansible#4616] opened 2013-10-21 11:21 UTC
I have two hosts: `small.aiua` and `philote.aiua`. I want to run a set of tasks on both hosts, but activate some of them only on one of them (`philote.aiua`). To test this ability I created this playbook:

```

---

- hosts: all
  sudo: yes

  vars:
    test_derived: 'philote.{{ ansible_domain }}'
    test_literal: 'philote.aiua'
    test_addition: "{{ 'philote.' + ansible_domain }}"

  tasks:

    - debug: msg='test_derived - {{ test_derived }}'

    - debug: msg='test_derived == ansible_fqdn - {{ test_derived }} == {{ ansible_fqdn }}'
      when: test_derived == ansible_fqdn

    - debug: msg='test_derived != ansible_fqdn - {{ test_derived }} != {{ ansible_fqdn }}'
      when: test_derived != ansible_fqdn

    - debug: msg='test_literal - {{ test_literal }}'

    - debug: msg='test_literal == ansible_fqdn - {{ test_literal }} == {{ ansible_fqdn }}'
      when: test_literal == ansible_fqdn

   - debug: msg='test_literal != ansible_fqdn - {{ test_literal }} != {{ ansible_fqdn }}'
      when: test_literal != ansible_fqdn

    - debug: msg='test_addition - {{ test_addition }}'

    - debug: msg='test_addition == ansible_fqdn - {{ test_addition }} == {{ ansible_fqdn }}'
      when: test_addition == ansible_fqdn

    - debug: msg='test_addition != ansible_fqdn - {{ test_addition }} != {{ ansible_fqdn }}'
      when: test_addition != ansible_fqdn
```

Output of this playbook when run:

```
PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [philote.aiua]
ok: [small.aiua]

TASK: [debug msg='test_derived - philote.{{ansible_domain}}'] ***************** 
ok: [philote.aiua] => {
    "msg": "test_derived - philote.aiua"
}
ok: [small.aiua] => {
    "msg": "test_derived - philote.aiua"
}

TASK: [debug msg='test_derived == ansible_fqdn - {{test_derived}} == {{ansible_fqdn}}'] *** 
skipping: [small.aiua]
skipping: [philote.aiua]

TASK: [debug msg='test_derived != ansible_fqdn - {{test_derived}} != {{ansible_fqdn}}'] *** 
ok: [philote.aiua] => {
    "msg": "test_derived != ansible_fqdn - philote.aiua != philote.aiua"
}
ok: [small.aiua] => {
    "msg": "test_derived != ansible_fqdn - philote.aiua != small.aiua"
}

TASK: [debug msg='test_literal - philote.aiua'] ******************************* 
ok: [small.aiua] => {
    "msg": "test_literal - philote.aiua"
}
ok: [philote.aiua] => {
    "msg": "test_literal - philote.aiua"
}

TASK: [debug msg='test_literal == ansible_fqdn - {{test_literal}} == {{ansible_fqdn}}'] *** 
skipping: [small.aiua]
ok: [philote.aiua] => {
    "msg": "test_literal == ansible_fqdn - philote.aiua == philote.aiua"
}

TASK: [debug msg='test_literal != ansible_fqdn - {{test_literal}} != {{ansible_fqdn}}'] *** 
skipping: [philote.aiua]
ok: [small.aiua] => {
    "msg": "test_literal != ansible_fqdn - philote.aiua != small.aiua"
}

TASK: [debug msg='test_addition - {{'philote.' + ansible_domain}}'] *********** 
ok: [small.aiua] => {
    "msg": "test_addition - philote.aiua"
}
ok: [philote.aiua] => {
    "msg": "test_addition - philote.aiua"
}

TASK: [debug msg='test_addition == ansible_fqdn - {{test_addition}} == {{ansible_fqdn}}'] *** 
skipping: [philote.aiua]
skipping: [small.aiua]

TASK: [debug msg='test_addition != ansible_fqdn - {{test_addition}} != {{ansible_fqdn}}'] *** 
ok: [small.aiua] => {
    "msg": "test_addition != ansible_fqdn - philote.aiua != small.aiua"
}
ok: [philote.aiua] => {
    "msg": "test_addition != ansible_fqdn - philote.aiua != philote.aiua"
}

PLAY RECAP ******************************************************************** 
philote.aiua               : ok=7    changed=0    unreachable=0    failed=0   
small.aiua                 : ok=7    changed=0    unreachable=0    failed=0   
```

It seems that I cannot use `run_on_host: 'philote.{{ ansible_domain }}'` as a variable definition, which would make playbook more portable.

**Comment by onnos** [comment] 2013-10-21 21:03
This appears to be the same problem as discussed in #4579. It was not fixed in the latest dev changes.

**Comment by jctanner** [comment] 2013-10-22 20:35
@drybjed Just to clarify ... this is a request to allow for variable substitution in the vars: section of a playbook?

It seems as though booleans are working fine for other types of vars such as ...

<pre>
    - debug: msg="ansible_os_family == RedHat"
      when: ansible_os_family == "RedHat"
</pre>

**Comment by drybjed** [comment] 2013-10-22 20:39
@jctanner Yes, that's correct. That would let me set a variable for a FQDN name like, for example: cache_server: 'cache.{{ ansible_domain }}'. By using that, I can create a host called 'cache.some.domain.com' and let ansible automatically recognize it and run tasks against it (or not) using when: contitions.

The problem is not that variables like this are not subsituted, but when: does not correctly evaluate conditions using these kinds of variables. In short, all three examples provided above should produce the same output when using when: tests, but they don't.

**Comment by jctanner** [comment] 2013-10-22 20:45
Testcase:

<pre>
- hosts: el6.lab.net
  gather_facts: True
  vars:
    test_var: '{{ ansible_domain }}'
  tasks:
    - debug: msg="test == test"
      when: test_var == ansible_domain
</pre>

Current behavior: debug task is skipped
Expected behavior: debug task is run

**Comment by drybjed** [comment] 2013-10-22 20:47
@jctanner Yes, exactly as you described.

**Comment by darkone23** [comment] 2013-10-28 22:31
I believe the regression was introduced here: https://github.com/ansible/ansible/compare/0568ab...503110
(at least the issue in #4662, a git bisect and test-case could prove if this one was also introduced by the same commits)

Is the simplest fix just to revert those commits until we can get them working with the previous behavior?

**Comment by mpdehaan** [comment] 2013-10-29 13:56
We're going to move forward because this is the development branch rather than simply revert, there are some upgrades to variable handling that are worth working on.

Sorry for the delay in response we have chased some related issues and this _LOOKS_ resolved, though because this got tagged feature accidentally it slipped off my radar.   Apologies.

**Comment by jctanner** [comment] 2013-10-29 15:35
Testing with latest devel seems to show this issue is fixed:

```
jtanner@u1304:~/issues/4616-when_vars$ cat simple.yml 
- hosts: el6.lab.net
  #connection: local
  gather_facts: True

  vars:
    test_var: '{{ ansible_domain }}'
    test_var2: "el6.{{ ansible_domain }}"
    test_var3: "{{ 'el6.' + ansible_domain }}"

  tasks:

    - debug: msg="{{ test_var }}"
    - debug: msg="{{ test_var2 }}"
    - debug: msg="{{ test_var3 }}"

    - debug: msg="test == test"
      when: test_var == ansible_domain
```

Result ...

```
jtanner@u1304:~/issues/4616-when_vars$ ansible-playbook -i inventory simple.yml 

PLAY [el6.lab.net] ************************************************************ 

GATHERING FACTS *************************************************************** 
ok: [el6.lab.net]

TASK: [debug msg="{{ansible_domain}}"] **************************************** 
ok: [el6.lab.net] => {
    "msg": "lab.net"
}

TASK: [debug msg="el6.{{ansible_domain}}"] ************************************ 
ok: [el6.lab.net] => {
    "msg": "el6.lab.net"
}

TASK: [debug msg="{{'el6.' + ansible_domain}}"] ******************************* 
ok: [el6.lab.net] => {
    "msg": "el6.lab.net"
}

TASK: [debug msg="test == test"] ********************************************** 
ok: [el6.lab.net] => {
    "msg": "test == test"
}

PLAY RECAP ******************************************************************** 
el6.lab.net                : ok=5    changed=0    unreachable=0    failed=0  
```

**Closed as completed** 2013-10-29 15:36 UTC
Labels: bug
