### ISSUE TITLE
Ansible 2.0 fails parsing dynamic inventory result

### ISSUE THREAD

**Issue by fbarriere** [ansible/ansible#14259] opened 2016-02-02 12:39 UTC
Hi,

   I have an inventory script that works fine with Ansible 1.9.4 but makes Ansible 2.0 fail with the trace:

Traceback (most recent call last):
  File "/opt/ansible-python/2016-01-26/Linux-x86_64/ansible-2.0.0.2/bin/ansible-playbook", line 85, in <module>
    sys.exit(cli.run())
  File "/opt/ansible-python/2016-01-26/Linux-x86_64/ansible-2.0.0.2/lib/python2.7/site-packages/ansible/cli/playbook.py", line 128, in run
    inventory = Inventory(loader=loader, variable_manager=variable_manager, host_list=self.options.inventory)
  File "/opt/ansible-python/2016-01-26/Linux-x86_64/ansible-2.0.0.2/lib/python2.7/site-packages/ansible/inventory/**init**.py", line 81, in **init**
    self.parse_inventory(host_list)
  File "/opt/ansible-python/2016-01-26/Linux-x86_64/ansible-2.0.0.2/lib/python2.7/site-packages/ansible/inventory/**init**.py", line 124, in parse_inventory
    self.parser = InventoryDirectory(loader=self._loader, groups=self.groups, filename=host_list)
  File "/opt/ansible-python/2016-01-26/Linux-x86_64/ansible-2.0.0.2/lib/python2.7/site-packages/ansible/inventory/dir.py", line 164, in __init__
    host.groups.remove(ungrouped)
ValueError: list.remove(x): x not in list

[inventory.json.txt](https://github.com/ansible/ansible/files/113907/inventory.json.txt)

**Comment by abadger** [comment] 2016-02-05 17:33
How are you specifying your inventory?  Are you specifying a directory as your inventory and the script lives inside of that?

I downloaded inventory.json.txt but it was malformed... I think I corrected it by just closing the list for the LON entry.  (Line 20 or so).

**Comment by fbarriere** [comment] 2016-02-25 12:43
Hi,

   Yes, I specify the directory and use a mix of dynamic and static files. The part I attached was a stripped down version of the complete inventory (large and contains too much information about our infrastructure to be posted), I'm sorry it was malformed.

**Comment by fbarriere** [comment] 2016-03-23 13:32
Hi,

   found the minimum testcase to trigger the problem. See the attached zip file. It contains three inventory files (to put in the same folder to be used as inventory). It contains a dynamic inventory file and two static files. I don't understand if there is something forbidden, and the error is not very explicit...

François.

[testcase.zip](https://github.com/ansible/ansible/files/186063/testcase.zip)

**Closed as completed** 2016-03-24 23:46 UTC
Labels: bug

**Comment by abadger** [comment] 2016-03-24 23:59
Thanks!  I was able to reproduce with that test case and fixed it.  It looks like the problem was that the same inventory host was listed in two places in inventory.  So when we went to take them out of the ungrouped list we got this error.  The commit listed above fixes the issue with the test case so I think we're good to go now.
