### ISSUE TITLE
Running ansible-playbook for tag which doesn't exist retuns OK

### ISSUE THREAD

**Issue by marcinkubica** [ansible/ansible#16098] opened 2016-06-02 11:35 UTC
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

CentOS Linux release 7.2.1511 (Core)
##### SUMMARY

When you execute ansible-playbook and use `-t` against a tag which has not been specified ansible connects to the hosts and does nothing, returning OK
##### STEPS TO REPRODUCE

```
ansible-playbook {{ your playbokname }}  -t i_dont_exist
```

##### EXPECTED RESULTS

```
fatal: tag "i_dont_exist" not found in your playbook"
 ok=0    changed=0    unreachable=0    failed=1 
```
##### ACTUAL RESULTS

```
$  ansible-playbook -i 10.72.59.125, opsview-agent.yaml -t i_dont_exist -vvvv
Using /etc/ansible/ansible.cfg as config file
Loaded callback default of type stdout, v2.0

PLAYBOOK: opsview-agent.yaml ***************************************************
1 plays in opsview-agent.yaml

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
<10.72.59.125> ESTABLISH SSH CONNECTION FOR USER: centos
<10.72.59.125> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=centos -o ConnectTimeout=10 -o ControlPath=/var/go/.ansible/cp/ansible-ssh-%h-%p-%r 10.72.59.125 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1464867279.35-177515427009047 `" && echo ansible-tmp-1464867279.35-177515427009047="` echo $HOME/.ansible/tmp/ansible-tmp-1464867279.35-177515427009047 `" ) && sleep 0'"'"''
<10.72.59.125> PUT /tmp/tmp9vA75H TO /home/centos/.ansible/tmp/ansible-tmp-1464867279.35-177515427009047/setup
<10.72.59.125> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=centos -o ConnectTimeout=10 -o ControlPath=/var/go/.ansible/cp/ansible-ssh-%h-%p-%r '[10.72.59.125]'
<10.72.59.125> ESTABLISH SSH CONNECTION FOR USER: centos
<10.72.59.125> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=centos -o ConnectTimeout=10 -o ControlPath=/var/go/.ansible/cp/ansible-ssh-%h-%p-%r -tt 10.72.59.125 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-rlxpmwntrjabpxtgmajshgdpwocitngs; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/centos/.ansible/tmp/ansible-tmp-1464867279.35-177515427009047/setup; rm -rf "/home/centos/.ansible/tmp/ansible-tmp-1464867279.35-177515427009047/" > /dev/null 2>&1'"'"'"'"'"'"'"'"' && sleep 0'"'"''
ok: [10.72.59.125]

PLAY RECAP *********************************************************************
10.72.59.125               : ok=1    changed=0    unreachable=0    failed=0

```

**Comment by sdarwin** [comment] 2016-06-02 12:13
It sort of seems like that isn't an error. A tag will trigger tasks to run, even if only 1% of the tasks have that particular tag.  So why not 0% of tasks?
It's like a while loop or a for loop that is never iterated through even once.  is such a loop an error?

**Comment by marcinkubica** [comment] 2016-06-02 13:16
Well this is an automation tool - If you run automation against anything - here:tags, and in your code tags (or anything) will be gone/replaced, your playbook should return error (because it won't - in fact - execute the code). 

It's just a logical consequence of calling something which doesn't exists - should return error `i'm not here!` :)

**Comment by bcoca** [comment] 2016-06-02 13:57
dupe of #13292

**Closed as completed by bcoca** 2016-06-02 13:57 UTC
