### ISSUE TITLE
CentOS upstart override file

### ISSUE THREAD

**Issue by ebastos** [ansible/ansible#7757] opened 2014-06-13 18:05 UTC
While working on issue #7715 I noticed that CentOS 6.5 was not happy with the "manual" stanza added to override files used by initctl:

10.0.2.16 | FAILED >> {
    "failed": true, 
    "msg": "stop: Method \"Get\" with signature \"ss\" on interface \"org.freedesktop.DBus.Properties\" doesn't exist\n\n"
}

The problem is that the "manual" stanza was added on upstart 0.6.7, while the latest version on CentOS is 0.6.5

A fix for that is to add "start on manual"  to the override file, which works fine on 0.6.5 up to the latest Ubuntu version - upstart 1.12

**Comment by ebastos** [comment] 2014-06-13 18:06
Here is an idea

https://github.com/ebastos/ansible/commit/ad8f317c786ff1dd50fabe9d23dc9434451da885

**Comment by mpdehaan** [comment] 2014-06-15 20:18
Can you please provide steps to reproduce this problem?

Thanks!

**Comment by mpdehaan** [comment] 2014-06-15 20:19
nevermind see mention to #7757

**Comment by mpdehaan** [comment] 2014-06-15 20:20
Sorry, I'm correct.

It seems yo have a commit above that is referrenced in this ticket, rather than this being a pull request.  Can you please submit a pull request and provide more context?

**Comment by ebastos** [comment] 2014-06-16 11:49
Sure, sorry about that.

## Environment:

CentOS 6.5:

[root@localhost ~]# lsb_release -a
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch
Distributor ID: CentOS
Description:    CentOS release 6.5 (Final)
Release:        6.5
Codename:       Final

Upstart version that comes with it:

[root@localhost ~]# rpm -q upstart
upstart-0.6.5-13.el6_5.3.x86_64

## Problem:

Ansible will create an override file and populate it with "manual" as per Upstart Cookbook configuration here.:

Stanzas per category:
http://upstart.ubuntu.com/cookbook/#stanzas-by-category
*\* Note stanza "manual" was introduced on Upstart 0.6.7

However CentOS' upstart cannot understand that stanza, effectively breaking the configuration altogether.

## Expected Results:

[root@localhost init]# initctl status test
test start/running, process 1140
[root@localhost init]# echo "start on manual" > test.override
[root@localhost init]# initctl status test
test start/running, process 1140
[root@localhost init]# initctl stop test
test stop/waiting
[root@localhost init]# initctl status test
test stop/waiting

## Actual Results:

[root@localhost init]# initctl status test
test start/running, process 603
[root@localhost init]# echo manual > test.override
[root@localhost init]# initctl status test
test start/running, process 603
[root@localhost init]# initctl stop test
initctl: Method "Get" with signature "ss" on interface "org.freedesktop.DBus.Properties" doesn't exist
[root@localhost init]# initctl status test
initctl: Unknown job: test

## Steps to reproduce:

ansible -v all -u root -k -m service -a 'name=test state=stopped enabled=no'

Please, let me know if you need more information

**Comment by jimi-c** [comment] 2014-08-25 19:00
# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2014-08-25 19:00 UTC
Labels: bug
