### ISSUE TITLE
RDS snapshot and restore broken

### ISSUE THREAD

**Issue by m-barthelemy** [ansible/ansible#10627] opened 2015-04-06 19:23 UTC
Using Ansible 1.9.0.1, we're unable to snapshot an RDS instance or to restore a snapshot.
Tried with boto 2.32 and 2.37

We use the following task:

```
- rds: >
    command=restore
    instance_name="{{newinstance_name}}"
    snapshot="{{snap_name}}"
    size=150
    instance_type=db.m3.medium
    subnet="{{vpc_db_subnet}}"
    wait=yes
    wait_timeout=1200
  when: env != "production" and newinstance_name != "xxxx" 
  register: newrds
```

Ansible throws the following error:

```
TASK: [rds-clone | rds command=restore instance_name="{{newinstance_name}}" snapshot="{{snap_name}}" size=150 instance_type=db.m3.medium subnet="{{vpc_db_subnet}}" wait=yes wait_timeout=1200
] *** 
failed: [localhost] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1428346104.18-118692723765023/rds", line 2807, in <module>
    main()
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1428346104.18-118692723765023/rds", line 1008, in main
    invocations[module.params.get('command')](module, conn)
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1428346104.18-118692723765023/rds", line 864, in restore_db_instance
    resource = await_resource(conn, result, 'available', module)
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1428346104.18-118692723765023/rds", line 614, in await_resource
    module.fail_json(msg="Timeout waiting for resource %s" % resource.id)
AttributeError: RDS2DBInstance instance has no attribute 'id'
```

**Comment by Reregistered** [comment] 2015-04-15 03:12
I have the same issue. It looks like the issue is related to enabling "wait" on this command. Irrespective of the time limit, my command always times out. Without the "wait" everything works as expected.

**Comment by rahulmehrotra1** [comment] 2015-04-15 17:16
I second that... I am also facing the timeout issue when using wait

**Comment by ryanwalls** [comment] 2015-04-17 22:43
+1

**Comment by ryanwalls** [comment] 2015-04-17 22:57
FYI... I am working around this for now by creating my own "wait" where I keep trying the operation until the status changes to what I want.  Obviously this won't work if you can't retry the operation multiple times.  Hope it helps someone.

```
  - name: Create database
    rds:
      backup_retention: 7
      command: create
      db_engine: sqlserver-ex
      instance_name: "{{ env }}"
      instance_type: db.t2.micro
      license_model: license-included
      multi_zone: no
      password: "{{databasePassword}}"
      port: "{{databasePort}}"
      publicly_accessible: yes
      region: "{{region}}"
      size: 20
      subnet: default
      tags:
        env: "{{env}}"
      upgrade: yes
      username: "{{databaseUsername}}"
      vpc_security_groups:  "{{sg.group_id}}"
    register: database
    until: database.instance.status == "available"
    retries: 30
    delay: 60 
```

**Comment by m-barthelemy** [comment] 2015-04-29 16:06
Seems to have been fixed in Ansible 1.9.1

**Comment by LewisW** [comment] 2015-05-01 12:03
We get a similar error, has anyone else experienced this?

```
boto.exception.JSONResponseError: JSONResponseError: 400 Bad Request
{u'RequestId': u'requestidhere', u'Error': {u'Message': u'The parameter Filter: db-snapshot-id is not a valid identifier. Identifiers must begin with a letter; must contain only ASCII letters, digits, and hyphens; and must not end with a hyphen or contain two consecutive hyphens.', u'Code': u'InvalidParameterValue', u'Type': u'Sender'}}
```

**Comment by ghost** [comment] 2015-05-11 20:45
Encountering this issue when using the replica command... 

```
BECOME-SUCCESS-voxqublxksfyukgvssnooghacwvejbmf
Traceback (most recent call last):
  File "/Users/ryanvangundy/.ansible/tmp/ansible-tmp-1431376318.13-180101363664316/rds", line 2816, in <module>
    main()
  File "/Users/ryanvangundy/.ansible/tmp/ansible-tmp-1431376318.13-180101363664316/rds", line 1012, in main
    invocations[module.params.get('command')](module, conn)
  File "/Users/ryanvangundy/.ansible/tmp/ansible-tmp-1431376318.13-180101363664316/rds", line 685, in replicate_db_instance
    resource = await_resource(conn, result, 'available', module)
  File "/Users/ryanvangundy/.ansible/tmp/ansible-tmp-1431376318.13-180101363664316/rds", line 614, in await_resource
    module.fail_json(msg="Timeout waiting for resource %s" % resource.id)
AttributeError: RDS2DBInstance instance has no attribute 'id'
```

**Comment by amoghe** [comment] 2015-06-09 18:04
I'm running `1.9.1` and seeing this as well (same backtrace as @rvangundy ). As mentioned before, it only seems to break when using `wait: yes`

**Comment by bennojoy** [comment] 2015-06-09 18:19
@amoghe  it shoudl be fixed via #1333 can yu check against the latest devel branch. https://github.com/ansible/ansible-modules-core/blob/devel/cloud/amazon/rds.py

**Comment by gacyun** [comment] 2015-07-02 05:14
+1

**Comment by shay-li** [comment] 2015-09-08 07:36
+1
ansible 1.9.3
only when using `wait: yes` timeout if waiting long time

**Comment by dgabriele** [comment] 2015-10-23 16:12
+1
ansible 1.9.4
`wait: yes`

**Comment by sanear** [comment] 2015-12-04 21:46
+1 ansible 1.9.4
`wait: yes`

**Comment by b-b3rn4rd** [comment] 2016-01-04 00:09
Meanwhile, as a workaround I'm using `facts` command to check if RDS is ready:

```
- name: Wait until RDS is available
  rds:
    aws_region: "{{ region }}"
    command: facts
    instance_name: "{{ rds_name }}"
  when: new_rds is defined
  ignore_errors: True
  register: rds
  ignore_errors: True
  until: rds.instance.status == "available"
  retries: 15
  delay: 60
```

**Comment by jctanner** [comment] 2016-07-01 20:54
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!

**Closed as completed by jctanner** 2016-07-01 20:54 UTC
Labels: cloud, bug
