### ISSUE TITLE
ansible_ssh_user not used in task when delegate_to set

### ISSUE THREAD

**Issue by ephess** [ansible/ansible#8979] opened 2014-09-12 00:46 UTC
##### Summary:

The ansible_ssh_user setting does not appear to be applied to a host when using the delegate_to feature.
##### Steps To Reproduce:

test inventory:

```
[lb]
lb ansible_ssh_user=ubuntu

[web]
web ansible_ssh_user=ubuntu
```

test.yml playbook:

``` yml

---

- hosts: web
  serial: 1
  sudo: yes

  tasks:
    - name: this is a test
      shell: echo test
      delegate_to: lb
```

run ansible:
`ansible-playbook -i test test.yml -vvvv`
##### Expected Results:

I expect that it would use the ssh user defined by the ansible_ssh_user setting when attempting to log into the lb node.
##### Actual Results:

```
TASK: [this is a test] ******************************************************** 
<lb> ESTABLISH CONNECTION FOR USER: user
<lb> REMOTE_MODULE command echo test #USE_SHELL
<lb> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/user/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', 'lb', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1410482613.68-50435724199494 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1410482613.68-50435724199494 && echo $HOME/.ansible/tmp/ansible-tmp-1410482613.68-50435724199494'"]
```

Comparing this to the ssh command used on tasks that aren't delegated, it's missing the `-o User=ubuntu` section of the command.

**Comment by jsmartin** [comment] 2014-09-18 22:24
This is duplicate of #8224

**Comment by sivel** [comment] 2014-09-23 20:39
It looks like this may already be resolved in devel.  It may have been fixed as part of the fact caching stuff, but did not actually appear to be fixed until 2629cd3fce4a6a2740093387fca75df38d38e4f9

**Comment by abadger** [comment] 2014-10-01 00:09
@sivel, doesn't appear to be fixed... Perhaps you have some other local changes?  if not we can compare playbooks and see if there's something silly that I'm doing.

**Comment by jimi-c** [comment] 2014-10-02 02:36
Since this is a duplicate, I've promoted #8224 to a P2, and we'll go ahead and close this one.

If you have any further questions, please leave them on that issue, or let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2014-10-02 02:36 UTC
Labels: P2, bug
