### ISSUE TITLE
[2.0-rc2] ansible-playbook: role with relative path don't work

### ISSUE THREAD

**Issue by HanXHX** [ansible/ansible#13472] opened 2015-12-08 16:02 UTC
Hi,

**Type**: Bug Report
**Ansible Version**: 2.0-rc2
**Environment**: Xubuntu 14.04 LTS

**Summary**:

With Ansible 1.*, we can use relative path for roles in a playbook. I use it for testing my roles with Vagrant. 

My playbook looks like

```
- hosts: all
  roles:
    - ../../
```

**Expected Results**: Run my role (like ansible 1.*)

**Steps To Reproduce**: You can test with one of my roles (vagrant up): https://github.com/HanXHX/ansible-nginx

**Actual Results**:

```
$ ansible-playbook --private-key=/home/xxxxxx/.vagrant.d/insecure_private_key --user=vagrant --limit='debian-jessie' --inventory-file=/home/xxxxxxx/xxxxxxxxx/.vagrant/provisioners/ansible/inventory --sudo -vv tests/test.yml
Using /etc/ansible/ansible.cfg as config file
1 plays in tests/test.yml

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [debian-jessie]

PLAY RECAP *********************************************************************
debian-jessie              : ok=1    changed=0    unreachable=0    failed=0 
```

Cheers,

Emilien

**Comment by jimi-c** [comment] 2015-12-08 18:30
That's odd, this just came up the other day and it was shown to still work when it was simply the cwd (`.`).

**Comment by chrrrles** [comment] 2015-12-08 19:20
I was unable to reproduce this bug using the latest devel and this playbook:

foo/playbook.yml

```
- hosts: all
  roles:
  - ../common
```

common/tasks/main.yml

```
- debug: msg="hello"
```

**Comment by HanXHX** [comment] 2015-12-08 19:24
hi @chrrrles, can you try with https://github.com/HanXHX/ansible-nginx please? just git clone && vagrant up debian-wheezy

**Comment by chrrrles** [comment] 2015-12-08 20:00
@HanXHX Thanks - but I tried to do vagrant up debian-wheezy with your Vagrantfile but it fails in provisioning with:

```
│fatal: [debian-wheezy]: FAILED! => {"failed": true, "msg": "ERROR! 'nginx_root' is undefined"}   
```

Do you have another suggestion for testing?

**Comment by chrrrles** [comment] 2015-12-08 20:10
I also tried with this playbook, foo/playbook.yml:

```
- hosts: all
  roles:
  - ../
```

and tasks/main.yml:

```
- debug: msg="hello"
```

With the same results

**Comment by jimi-c** [comment] 2015-12-08 20:27
HI @HanXHX, is it possible that this relative path would put the role outside of the path which is mounted as `/vagrant`? Beyond that, this seems to be working as expected outside of Vagrant itself.

**Comment by HanXHX** [comment] 2015-12-09 10:32
Hi @jimi-c, i don't use ansible on vagrant mounted drive.

I also try with latest git version (ansible 2.1.0 (devel c1cec64aa8)). I have same problem :(

And still no problem with ansible 1.9.4

**Comment by HanXHX** [comment] 2015-12-09 10:46
Oh I just found something. If I run ansible-playbook as root (sudo). It works...

Do you need some environment vars or something else?

**Comment by jimi-c** [comment] 2015-12-09 16:39
@HanXHX could you include the full output using `-vvv` when you run it and it fails as well as when it succeeds?

**Comment by HanXHX** [comment] 2015-12-09 16:54
With my nginx role (https://github.com/HanXHX/ansible-nginx/blob/master/tests/test.yml).

As normal user, in this case it fails:

```
$ ANSIBLE_FORCE_COLOR=true ANSIBLE_HOST_KEY_CHECKING=false PYTHONUNBUFFERED=1 ansible-playbook --private-key=/home/hanx/.vagrant.d/insecure_private_key --user=vagrant --limit='debian-wheezy' --inventory-file=/home/hanx/Documents/Perso/_github/ansible-nginx/.vagrant/provisioners/ansible/inventory --sudo -vvv tests/test.yml
Using /etc/ansible/ansible.cfg as config file
1 plays in tests/test.yml

PLAY ***************************************************************************

TASK [setup] *******************************************************************
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
<127.0.0.1> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2201 -o 'IdentityFile="/home/hanx/.vagrant.d/insecure_private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 -o ControlPath=/home/hanx/.ansible/cp/ansible-ssh-%h-%p-%r 127.0.0.1 /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-ukmovgrgyzkiolpsignhapvwmhaowtpt; LANG=fr_FR.UTF-8 LC_ALL=fr_FR.UTF-8 LC_MESSAGES=fr_FR.UTF-8 /usr/bin/python'"'"''
ok: [debian-wheezy]

TASK [apt state=present update_cache=yes pkg={{ item }} cache_valid_time=3600] *
task path: /home/hanx/Documents/Perso/_github/ansible-nginx/tests/test.yml:5
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
<127.0.0.1> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2201 -o 'IdentityFile="/home/hanx/.vagrant.d/insecure_private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 -o ControlPath=/home/hanx/.ansible/cp/ansible-ssh-%h-%p-%r 127.0.0.1 /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-djsjwmelgpwqvxzlabdgshqxxnwvywiq; LANG=fr_FR.UTF-8 LC_ALL=fr_FR.UTF-8 LC_MESSAGES=fr_FR.UTF-8 /usr/bin/python'"'"''
ok: [debian-wheezy] => (item=[u'php5-fpm', u'curl']) => {"cache_update_time": 1449679771, "cache_updated": false, "changed": false, "invocation": {"module_args": {"cache_valid_time": "3600", "name": ["php5-fpm", "curl"], "state": "present", "update_cache": "yes"}, "module_name": "apt"}, "item": ["php5-fpm", "curl"]}

TASK [-- Add PHP file --] ******************************************************
task path: /home/hanx/Documents/Perso/_github/ansible-nginx/tests/test.yml:83
fatal: [debian-wheezy]: FAILED! => {"failed": true, "msg": "ERROR! 'nginx_root' is undefined"}
```

As root

```
# ANSIBLE_FORCE_COLOR=true ANSIBLE_HOST_KEY_CHECKING=false PYTHONUNBUFFERED=1 ansible-playbook --private-key=/home/hanx/.vagrant.d/insecure_private_key --user=vagrant --limit='debian-wheezy' --inventory-file=/home/hanx/Documents/Perso/_github/ansible-nginx/.vagrant/provisioners/ansible/inventory --sudo -vvv tests/test.yml

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
<127.0.0.1> ESTABLISH CONNECTION FOR USER: vagrant
<127.0.0.1> REMOTE_MODULE setup
<127.0.0.1> EXEC ssh -C -v -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/hanx/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=2201 -o IdentityFile="/home/hanx/.vagrant.d/insecure_private_key" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 127.0.0.1 /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=atyqcbzcjrtpncauizxdrfrykecdqmne] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-atyqcbzcjrtpncauizxdrfrykecdqmne; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python'"'"''
ok: [debian-wheezy]

TASK: [apt pkg={{ item }} update_cache=yes cache_valid_time=3600 state=present] *** 
<127.0.0.1> ESTABLISH CONNECTION FOR USER: vagrant
<127.0.0.1> REMOTE_MODULE apt pkg=php5-fpm,curl update_cache=yes cache_valid_time=3600 state=present
<127.0.0.1> EXEC ssh -C -v -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/hanx/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=2201 -o IdentityFile="/home/hanx/.vagrant.d/insecure_private_key" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 127.0.0.1 /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=jhqnzhcuzfnrpwirfjufvvpyahcgwdxl] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-jhqnzhcuzfnrpwirfjufvvpyahcgwdxl; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python'"'"''
ok: [debian-wheezy] => (item=php5-fpm,curl) => {"changed": false, "item": "php5-fpm,curl"}

TASK: [../../ | APT | Install nginx and dependencies] ************************* 
<127.0.0.1> ESTABLISH CONNECTION FOR USER: vagrant
<127.0.0.1> REMOTE_MODULE apt pkg=nginx-full,python-passlib state=latest update_cache=yes cache_valid_time=3600
<127.0.0.1> EXEC ssh -C -v -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/hanx/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=2201 -o IdentityFile="/home/hanx/.vagrant.d/insecure_private_key" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 127.0.0.1 /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=oezajrvluzbhafyaiuoujxdkkzwweqow] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-oezajrvluzbhafyaiuoujxdkkzwweqow; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python'"'"''
ok: [debian-wheezy] => (item=nginx-full,python-passlib) => {"changed": false, "item": "nginx-full,python-passlib"}

TASK: [../../ | SHELL | Get Nginx version] ************************************ 
<127.0.0.1> ESTABLISH CONNECTION FOR USER: vagrant
<127.0.0.1> REMOTE_MODULE command nginx -v 2>&1 | sed -r 's#.*/##;' | cut -d ' ' -f 1 #USE_SHELL
<127.0.0.1> EXEC ssh -C -v -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/hanx/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=2201 -o IdentityFile="/home/hanx/.vagrant.d/insecure_private_key" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 127.0.0.1 /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=qerojkbatcbxhmcntpmgqaqbaifehxvj] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-qerojkbatcbxhmcntpmgqaqbaifehxvj; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python'"'"''
ok: [debian-wheezy] => {"changed": false, "cmd": "nginx -v 2>&1 | sed -r 's#.*/##;' | cut -d ' ' -f 1", "delta": "0:00:00.004329", "end": "2015-12-09 16:51:08.367594", "rc": 0, "start": "2015-12-09 16:51:08.363265", "stderr": "", "stdout": "1.2.1", "stdout_lines": ["1.2.1"], "warnings": []}
...
```

In case as normal user, my role seems partially loaded. But `nginx_root` is defined in defaults/main.yml!

**Comment by HanXHX** [comment] 2015-12-09 17:00
With ansible 1.9.4 (as normal user):

```
$ ANSIBLE_FORCE_COLOR=true ANSIBLE_HOST_KEY_CHECKING=false PYTHONUNBUFFERED=1 ansible-playbook --private-key=/home/hanx/.vagrant.d/insecure_private_key --user=vagrant --limit='debian-wheezy' --inventory-file=/home/hanx/Documents/Perso/_github/ansible-nginx/.vagrant/provisioners/ansible/inventory --sudo -vvv tests/test.yml

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
<127.0.0.1> ESTABLISH CONNECTION FOR USER: vagrant
<127.0.0.1> REMOTE_MODULE setup
<127.0.0.1> EXEC ssh -C -v -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/hanx/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=2201 -o IdentityFile="/home/hanx/.vagrant.d/insecure_private_key" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 127.0.0.1 /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=ggcfpntgugrooffibumtsicemvjuvlvw] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-ggcfpntgugrooffibumtsicemvjuvlvw; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python'"'"''
ok: [debian-wheezy]

TASK: [apt pkg={{ item }} update_cache=yes cache_valid_time=3600 state=present] *** 
<127.0.0.1> ESTABLISH CONNECTION FOR USER: vagrant
<127.0.0.1> REMOTE_MODULE apt pkg=php5-fpm,curl update_cache=yes cache_valid_time=3600 state=present
<127.0.0.1> EXEC ssh -C -v -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/hanx/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=2201 -o IdentityFile="/home/hanx/.vagrant.d/insecure_private_key" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 127.0.0.1 /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=ioowervzplvowhxjwmlwtshwmwsefjjr] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-ioowervzplvowhxjwmlwtshwmwsefjjr; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python'"'"''
ok: [debian-wheezy] => (item=php5-fpm,curl) => {"changed": false, "item": "php5-fpm,curl"}

TASK: [../../ | APT | Install nginx and dependencies] ************************* 
<127.0.0.1> ESTABLISH CONNECTION FOR USER: vagrant
<127.0.0.1> REMOTE_MODULE apt pkg=nginx-full,python-passlib state=latest update_cache=yes cache_valid_time=3600
<127.0.0.1> EXEC ssh -C -v -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/hanx/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=2201 -o IdentityFile="/home/hanx/.vagrant.d/insecure_private_key" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 127.0.0.1 /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=kqjncwspsuatnqlqfhdgffvpdiaoggwe] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-kqjncwspsuatnqlqfhdgffvpdiaoggwe; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python'"'"''
ok: [debian-wheezy] => (item=nginx-full,python-passlib) => {"changed": false, "item": "nginx-full,python-passlib"}

TASK: [../../ | SHELL | Get Nginx version] ************************************ 
<127.0.0.1> ESTABLISH CONNECTION FOR USER: vagrant
<127.0.0.1> REMOTE_MODULE command nginx -v 2>&1 | sed -r 's#.*/##;' | cut -d ' ' -f 1 #USE_SHELL
<127.0.0.1> EXEC ssh -C -v -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/hanx/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=2201 -o IdentityFile="/home/hanx/.vagrant.d/insecure_private_key" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 127.0.0.1 /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=dnjvqpxxqnigjtywmrkhtehmbmxfmzcv] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-dnjvqpxxqnigjtywmrkhtehmbmxfmzcv; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python'"'"''
ok: [debian-wheezy] => {"changed": false, "cmd": "nginx -v 2>&1 | sed -r 's#.*/##;' | cut -d ' ' -f 1", "delta": "0:00:00.004770", "end": "2015-12-09 16:59:27.254107", "rc": 0, "start": "2015-12-09 16:59:27.249337", "stderr": "", "stdout": "1.2.1", "stdout_lines": ["1.2.1"], "warnings": []}
.........
```

**Comment by HanXHX** [comment] 2015-12-09 17:06
oooooops... as root = ansible 1.9.4... sudo don't copy my env vars (hacking-env in git repo)...

**Comment by jimi-c** [comment] 2015-12-09 18:58
Yes, it seems like your role is not being loaded properly. Can you check the permissions on the files for that role?

**Comment by HanXHX** [comment] 2015-12-10 08:30
No problem with file permissions.

**Comment by HanXHX** [comment] 2015-12-10 10:35
I found the cause.

When you launch a playbook, the main difference is about the current working dir :
- 1.*: use playbook working dir
- 2.*: use shell working dir

Playbook:

```
$ cat tmp/try.yml 
---

- hosts: localhost
  connection: local
  become: no
  tasks:
    - debug: var=ansible_env.PWD
```

Ansible 1.9.4:

```
$ ansible --version
ansible 1.9.4
  configured module search path = None
$ ansible-playbook -i localhost, tmp/try.yml

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [debug var=ansible_env.PWD] ********************************************* 
ok: [localhost] => {
    "var": {
        "ansible_env.PWD": "/home/hanx/tmp"
    }
}

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=0    unreachable=0    failed=0   

$ pwd
/home/hanx
```

On ansible 2.*:

```
$ ansible --version
ansible 2.0.0 (stable-2.0 3fafc6d655) last updated 2015/12/10 11:20:13 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 62ef8cd36b) last updated 2015/12/10 11:20:58 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD c8c321b56c) last updated 2015/12/10 11:20:58 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
$ ansible-playbook -i localhost, tmp/try.yml

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [debug var=ansible_env.PWD] ***********************************************
ok: [localhost] => {
    "ansible_env.PWD": "/home/hanx", 
    "changed": false
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   

$ pwd
/home/hanx
```

**Comment by HanXHX** [comment] 2015-12-11 15:00
Another example: 

```
$ cat tmp/try.yml
---

- hosts: localhost
  connection: local
  become: no
  tasks:
    - copy: src=/etc/lsb-release dest=./lsb-release 
    - command: readlink -f ./lsb-release
      changed_when: false
      register: p
    - debug: var=p.stdout
```

```
$ ansible-playbook --version
ansible-playbook 1.9.4
  configured module search path = None
$ ansible-playbook -i localhost, tmp/try.yml

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [copy src=/etc/lsb-release dest=./lsb-release] ************************** 
ok: [localhost]

TASK: [command readlink -f ./lsb-release] ************************************* 
ok: [localhost]

TASK: [debug var=p.stdout] **************************************************** 
ok: [localhost] => {
    "var": {
        "p.stdout": "/home/hanx/tmp/lsb-release"
    }
}

PLAY RECAP ******************************************************************** 
localhost                  : ok=4    changed=0    unreachable=0    failed=0   
```

```
$ ansible-playbook --version
ansible-playbook 2.0.0 (stable-2.0 b0e5556d9a) last updated 2015/12/11 11:31:32 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 8feda1472b) last updated 2015/12/11 11:31:49 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD c8c321b56c) last updated 2015/12/10 11:20:58 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
$ ansible-playbook -i localhost, tmp/try.yml

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [copy dest=./lsb-release src=/etc/lsb-release] ****************************
ok: [localhost]

TASK [command] *****************************************************************
ok: [localhost]

TASK [debug var=p.stdout] ******************************************************
ok: [localhost] => {
    "changed": false, 
    "p.stdout": "/home/hanx/lsb-release"
}

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0  
```

p.stdout whould be the same...

**Comment by jimi-c** [comment] 2015-12-16 16:23
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed** 2015-12-16 16:23 UTC
Labels: bug
