### ISSUE TITLE
service module fails to start postgresql service

### ISSUE THREAD

**Issue by lorin** [ansible/ansible#7695] opened 2014-06-08 03:14 UTC
**Issue type:**

Bug report.

**Ansible Version:**

1.6.2

**Environment:**
- Host: Ubuntu 12.04 running PostgreSQL 9.1.3
- Machine running Ansible: Mac OS X 10.9.3

**Summary:**

Ansible service module fails to start the postgresql service.

**Steps to Reproduce:**

Here's a playbook that will reproduce the issue:

```
- hosts: all
  sudo: yes
  tasks:
    - apt: name=postgresql update_cache=yes
    - service: name=postgresql state=stopped
    - service: name=postgresql state=started
```

**Expected Results:**

The PostgreSQL service is running on the host:

```
$ sudo -u postgres psql
psql (9.1.13)
Type "help" for help.

postgres=#
```

**Actual Results:**

The PostgreSQL service is not running on the host:

```
$ sudo -u postgres psql
psql: could not connect to server: No such file or directory
    Is the server running locally and accepting
    connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```

The service module claims that there has been no change when the final: `service: name=postgresql state=started` task executes.

Admittedly, even for a human being, it's a little confusing to parse the output of `service postgresql status` when the service isn't running.

Here's what the output looks like when PostgreSQL isn't running:

```
$ sudo service postgresql status
Running clusters:
$ echo $?
0
```

Here's what it looks like when PostgreSQL is running:

```
$ sudo service postgresql status
Running clusters: 9.1/main
$ echo $?
0
```

**Comment by jimi-c** [comment] 2014-06-09 18:23
Yes, this appears to be caused by the fact that the status check as executed by the init script is losing the return code set by the code in `/usr/share/postgresql-common/init.d-functions`. This can be resolved with the following patch for now:

<pre>
--- /etc/init.d/postgresql.bak  2014-06-09 14:15:52.396934331 -0400
+++ /etc/init.d/postgresql  2014-06-09 14:16:44.304968735 -0400
@@ -34,9 +34,12 @@ case "$1" in
         ;;
     status)
    set +e
+   rc=0
    for v in $versions; do
        ($1 $v)
+       rc=$(($rc|$?))
    done
+   exit $rc
         ;;
     force-reload)
    for v in $versions; do
</pre>

Beyond that, we may have to add in some sort of special handling for this, though that could get tricky, considering the way this init script works.

**Comment by jimi-c** [comment] 2014-06-09 18:35
Also, using `- service: name=postgresql state=restarted` works for the specific use-case above.

**Comment by jimi-c** [comment] 2014-06-09 18:49
Finally, the option `pattern='/usr/lib/postgresql/9.1/bin/postgres -D '` can be added to your `state=started` line, which allows the service module to check the ps output for the command. Beyond that, since this is an init script issue, I'm going to go ahead and close this issue. Please let us know if you have any further questions regarding this. Thanks!

**Closed as completed by jimi-c** 2014-06-09 18:49 UTC
Labels: P1, bug, postgresql
