### ISSUE TITLE
Rescue task not execute with any_errors_fatal enable

### ISSUE THREAD

**Issue by Ehekatl** [ansible/ansible#17174] opened 2016-08-22 03:05 UTC
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME
- Block
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### CONFIGURATION

```
[defaults]
inventory = local
host_key_checking = False
retry_files_enabled = False
pipelining = True

cow_selection = random
cow_whitelist=cow,cower,default,happy-whale,head-in,homer,moofasa,moose,mutilated,nyan,strikingly,supermilker,telebears,udder,whale

[ssh_connection]
sudo_flags=-HE
scp_if_ssh = True
control_path = ~/.ssh/mux-%%r@%%h:%%p
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

When enable any_errors_fatal in play, the rescue task in block will not be executed, I understand this maybe intentionally behavior, but, from real world case, I need rescue for error handling and I also need the play abort when the task failed and not continuing run on other hosts. This is extremely useful when rolling out updates to production.
##### STEPS TO REPRODUCE

Have `any_errors_fatal: true` in playbook and the rescue task won't run

```
- name: Test
  hosts: localhost
  gather_facts: no
  any_errors_fatal: true
  tasks:
    - block:
      - debug: msg="balabala"
      - debug: msg="{{ abc }}"
      rescue:
        - debug: msg="test"
```

**Comment by jimi-c** [comment] 2016-08-31 14:46
This is fixed in devel, however due to the fact that the patch does not apply cleanly to stable-2.1 this will not be included in 2.1.2.  This will be included in 2.2.0.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2016-08-31 14:46 UTC
Labels: bug

**Comment by cebotareanu** [comment] 2016-11-25 16:09
Hello,
Can you please confirm if the issue was fixed?
I am using ansible --version
ansible 2.2.1.0 (stable-2.2 8dee7f3138) last updated 2016/11/25 14:22:25 (GMT +200)

And seen same issue.

BR,
Andrei Cebotareanu

**Comment by jimi-c** [comment] 2016-11-26 22:23
@cebotareanu yes this should have been fixed. Can you please open a new issue in which you share an example playbook which reproduces the issue you're seeing?
