### ISSUE TITLE
ansible_fqdn

### ISSUE THREAD

**Issue by chris-bragg-bsh-ke** [ansible/ansible#10072] opened 2015-01-23 10:39 UTC
Shouldn't this variable be the full hostname of the target host. Not what is found in /etc/hosts.
facter_fqdn is correct.

version 1.8.2

example
machine name is host.domain.com

/etc/hosts
172.17.20.20 pp.host.domain.com

facter_fqdn = host.domain.com
ansible_fqdn = pp.host.domain.com

**Comment by sysadmin75** [comment] 2015-01-25 17:49
I am unable to reproduce this in the latest devel branch.
ansible_fqdn is set to the remote server hostname.

My example:
local
cat /etc/hosts
192.168.1.12 apache.home

ansible hosts:
apache ansible_ssh_host=192.168.1.12

remote
[root@apache-server ~]# hostname
apache-server.localhost.com

$ ansible apache -m setup | grep fqdn
        "ansible_fqdn": "apache-server.localhost.com",

**Comment by sysadmin75** [comment] 2015-02-01 17:34
@bcoca Were you able to reproduce?

**Comment by chris-bragg-bsh-ke** [comment] 2015-02-02 10:31
Hey,

I havent tried this out again against devel - I am now using the
{{ ansible_nodename }} variable - which seems to be consistent.

Thanks

_Christopher Bragg_Technical Operations Manager

Bridge House, 48-52 Baldwin Street, Bristol, BS1 1QB
mob: +44 (0)7790 580754 | direct:+44 (0)117 9159600 | fax: +44 (0)117
91559630

www.sift.com

Sift Ltd is registered in England and Wales no. 3230061

**Comment by bcoca** [comment] 2015-02-11 19:02
I cannot reproduce either

**Comment by bcoca** [comment] 2015-02-11 19:03
closing as 'solved in current development'

**Closed as completed by bcoca** 2015-02-11 19:03 UTC
Labels: P2, bug

**Comment by anguo-wenz** [comment] 2016-02-23 09:28
in chris-bragg-sift example, if the 172.17.20.20 is the same with current host ip, then ansible_fqdn will return pp.host.domain.com
in this situation, it is not a bug of ansible, because command "hostname -A" also will return pp.host.domain.com and same with "socket.getfqdn()". 
but "hostname -f" will return host.domain.com

in sysadmin75 reproducing environment, if you edit hosts file of machine 192.168.1.12, I think you will reproduce the issue
