### ISSUE TITLE
[Performance] git module is slow

### ISSUE THREAD

**Issue by 0xABAB** [ansible/ansible#14501] opened 2016-02-16 11:34 UTC
Using the git module with a specific changeset (which already exists) is a slow operation and it appears that it is not being cached. If the files are already there, it should take not more than 10ms to determine that nothing needs to be done. In Ansible it currently takes on the order of seconds on top of the line hardware (SSD, fast CPU, etc.).  

If modules are this bad, I can better just write all the shell code myself.

**Comment by mscherer** [comment] 2016-02-17 11:25
Hi, can you provide a playbook to reproduce the exact case you are seeing ?

**Comment by 0xABAB** [comment] 2016-02-17 21:29
If you want to fix it, you write a couple of tests, which connect to e.g. github and you time it. You can use e.g. the Ansible project itself to show absence of performance issues (but you will find there are performance issues). 

For my use case I already worked around it with extra logic. My code now runs in 200ms or so, but I suspect Ansible is just extremely slow. I would have to reimplement Ansible to get it down to 10ms (which should be the reasonable performance target for this operation).

**Comment by sivel** [comment] 2016-02-19 12:34
With the overhead of building Python files, establishing temp directories via ssh, copying the module to the target, executing it, processing results and cleaning up, I'm not sure that 10ms is anywhere near a reasonable expectation.

How much time are you seeing specifically without your extra logic?

Please do not try to pass the responsibility of providing proper actionable information that can assist in resolving your problem.

Something taking too long is subjective, and what you might find unacceptable, another may find perfectly reasonable.

**Comment by caspark** [comment] 2016-02-29 11:25
@sivel , @mscherer , while I think 10ms is a bit of a.. high bar, the git module's performance is definitely slower than I would expect:
1. run `hacking/test-module -m lib/ansible/modules/core/source_control/git.py -a 'repo=git@github.com:BurntSushi/quickcheck.git dest=/tmp/rs-quickcheck recursive=no'` to do an initial clone
2. run `time hacking/test-module -m lib/ansible/modules/core/source_control/git.py -a 'repo=git@github.com:BurntSushi/quickcheck.git dest=/tmp/rs-quickcheck recursive=no'` again, and notice how long it takes
3. compare with the time taken to do `time (cd /tmp/rs-quickcheck && git fetch && git reset --hard origin/HEAD)`

For me, step 2 takes anywhere from 13 to 20 seconds, and step 3 takes about 3-4 seconds. These numbers are higher for bigger repos; rust's quickcheck repo is a fairly small one.

If you apply the patch at https://gist.github.com/caspark/3b5c7232746b00ed1b13 you'll see that the slowness comes from doing several git operations as separate commands:
1. Remote head is fetched (~4 secs)
2. Remote tags are fetched (~4 secs)
3. Finally an actual git fetch is done (in what looks like 2 `git fetches` and ~6 secs)

I realise that the two commands are not quite equivalent, and the git module has the disadvantage of having to handle different use cases (including "check out a version which is already locally" as described in the original bug report), and so I assume that those early fetches are done as optmisations.

Nonetheless, I would suggest that "pull the latest changes from an unchanged remote and update a branch locally" is at least in the top 3 use cases (if not the top one, given that it's what happens when all arguments are left at default), and so it should be a fair bit faster than it is currently, even if it means making other cases slower.

I haven't read all the code, but perhaps a way to fix this is to adjust the definition of what constitutes a change for a non-bare repos from "any files in the git repo are changed" to "a non-bare repo is changed only when the checked out files are changed". That small breaking change would significantly simplify the code too, and could be hidden behind a flag. Alternatively, make a temporary local clone from the local repo that already exists, update its remote to the provided repo, fetch there, and use that to inspect whether any changes need to occur in the real clone; if they do, grab them from the temp local clone. (Though I'm not sure whether that'd take advantage of hard links on Windows..)

**Comment by jan-warchol** [comment] 2016-03-24 15:28
@sivel I am seeing similarly bad performance.  Here's a test playbook:

```
- hosts: localhost
  tasks:
    - name: ensure target is empty
      file: name=/tmp/ansible.git state=absent

    - name: clone ansible repository
      git:
        repo=https://github.com/ansible/ansible
        dest=/tmp/ansible.git
        version=devel

    - name: pull ansible repository using ansible's git module
      git:
        repo=https://github.com/ansible/ansible
        dest=/tmp/ansible.git
        version=devel

    - name: pull ansible repo using git directly
      shell: git pull chdir=/tmp/ansible.git
```

And here's the output, timed using ansible-profile plugin:

```
PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [ensure target is empty] ************************************************ 
changed: [localhost]

TASK: [clone ansible repository] ********************************************** 
changed: [localhost]

TASK: [pull ansible repository using ansible's git module] ******************** 
ok: [localhost]

TASK: [pull ansible repo using git directly] ********************************** 
changed: [localhost]

PLAY RECAP ******************************************************************** 
clone ansible repository --------------------------------------------- 56.36s
pull ansible repository using ansible's git module ------------------- 21.62s
pull ansible repo using git directly ---------------------------------- 3.22s
ensure target is empty ------------------------------------------------ 0.12s

```

As you can see, "recloning" (i.e. pulling) an existing repo using git module takes **over 6 times longer** than it should.

And in my real-life use-case I'm cloning not 1, not 2, but _13_ repositories to deploy a big system.  When I re-run the playbook to update the system, it's really annoying that I have to wait 4 minutes instead of 40 seconds just to get over pulling repositories...

**Comment by jminardi** [comment] 2016-04-28 20:23
I am also deploying a large number of git repos using ansible. If it is not possible to speed them up is it possible run them all in parallel?

**Comment by robinro** [comment] 2016-04-29 08:16
@jminardi parallel runs are something that one might be able to do in ansible in general (as a strategy?), but this is unrelated to the git module and should not be discussed/implemented here.
If we fix the problem @janek-warchol presented in the git module this would already help a lot.

**Comment by jctanner** [comment] 2016-07-11 02:55
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!

**Closed as completed by jctanner** 2016-07-11 02:55 UTC
Labels: bug

**Comment by fubarhouse** [comment] 2016-07-17 00:25
Subscribing, I've been bothered by completion times of the git module ever since.... ever - by comparison to running it through additional shell tasks with additional logic.
