### ISSUE TITLE
win_domain_membership - "System cannot find the file specified"

### ISSUE THREAD

**Issue by abottomsHarris** [ansible/ansible#57313] opened 2019-06-03 15:02 UTC
I searched 13 existing issues of this module and this seems to have same error output as mine:
https://github.com/ansible/ansible/issues/31218

##### SUMMARY
While attempting to join new PC to domain, instead receive cryptic error message. I have joined/unjoined domain manually via powershell without issue. Module correctly identifies (via green "ok") when it is joined to domain. Problem persists after domain has been unjoined.

Powershell used:
```
add-computer -domainname andrews.net -Credential ANDREWS\Administrator
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_domain_membership 

##### ANSIBLE VERSION

```$ ansible --version
ansible 2.7.10
  config file = None
  configured module search path = ['/home/abottoms/.ansible/plugins/modules', '/usr/share/ansible/plug                                                                                                         ins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.3 (default, Jan  4 2018, 16:40:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION

```$ ansible-config dump --only-changed
[abottoms@hostname ansible]$
```

##### OS / ENVIRONMENT

**Ansible master:** CentOS 7
**Domain Controller:** Windows Server 2016 -- vanilla, is independent of other DCs, is a one-man show. No other computers/hosts have been joined to this domain. I am not a windows admin, I followed a basic guide, could be a misconfigured here but seems unlikely as powershell works.
**Domain Joiner:** Windows 10 mostly up to date

##### STEPS TO REPRODUCE

```---
- name: demo
  hosts: win10vle #this specifies the domain-joiner host
  gather_facts: no #yes
  tasks:
    - name: set DNS # without setting DNS, domain-joiner will not see DC
      win_dns_client:
        adapter_names: '*'
        ipv4_addresses: <direct IP of DC Host>
    - name: Join test domain
      win_domain_membership:
        dns_domain_name: andrews.net
        hostname: <domain-joiner, have also tried explicit hostname of DC>
        domain_admin_user: Administrator@andrews.net
        domain_admin_password: <Redacted>
        domain_ou_path: "OU=Computers,DC=andrews,DC=net" #have also tried adding CN= common name of domain-joiner and DC Host
        state: domain
        register: domain_state
```

##### EXPECTED RESULTS

Expected result should show 'changed' and after reboot domain-joiner should be visible in OU "Computers" in admin console of DC Host

##### ACTUAL RESULTS

Fatal failure with cryptic error message below.

```$ ansible-playbook -vvvv debug2.yml
ansible-playbook 2.7.10
  config file = None
  configured module search path = ['/home/abottoms/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.6.3 (default, Jan  4 2018, 16:40:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
No config file found; using defaults
setting up inventory plugins
/etc/ansible/hosts did not meet host_list requirements, check plugin documentation if this is unexpected
/etc/ansible/hosts did not meet script requirements, check plugin documentation if this is unexpected
Parsed /etc/ansible/hosts inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python3.6/site-packages/ansible/plugins/callback/default.py

PLAYBOOK: debug2.yml ******************************************************************************************************************************************************************************************
1 plays in debug2.yml

PLAY [demo] ***************************************************************************************************************************************************************************************************
META: ran handlers

TASK [set DNS] ************************************************************************************************************************************************************************************************
task path: /etc/ansible/debug2.yml:18
Using module file /usr/lib/python3.6/site-packages/ansible/modules/windows/win_dns_client.ps1
<domain-joiner> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5986 TO domain-joiner
checking if winrm_host domain-joiner is an IPv6 address
EXEC (via pipeline wrapper)
ok: [domain-joiner] => {
    "changed": false
}

TASK [Join test domain] ***************************************************************************************************************************************************************************************
task path: /etc/ansible/debug2.yml:22
Using module file /usr/lib/python3.6/site-packages/ansible/modules/windows/win_domain_membership.ps1
<domain-joiner> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5986 TO domain-joiner
checking if winrm_host domain-joiner is an IPv6 address
EXEC (via pipeline wrapper)
fatal: [domain-joiner]: FAILED! => {
    "changed": true,
    "msg": "failed to join domain: Computer 'domain-joiner' failed to join domain 'andrews.net' from its current workgroup 'WORKGROUP' with following error message: The system cannot find the file specified.",
    "reboot_required": false
}
        to retry, use: --limit @/etc/ansible/debug2.retry

PLAY RECAP ****************************************************************************************************************************************************************************************************
domain-joiner                  : ok=1    changed=0    unreachable=0    failed=1
```

**Comment by ShachafGoldstein** [comment] 2019-06-04 06:26
Are you renaming the machine while joining?
I see this error online when people rename and join at the same time without a reboot and I'm pretty sure there is a similier issue still open regarding the issue of rename and join together

**Comment by abottomsHarris** [comment] 2019-06-04 13:08
Hello Shacha,

No, I have re-labelled the "domain-joiner" host instead of the actual hostname. It's a short and simple alphanumeric string with no special characters or spaces or anything of the like.

**Comment by ShachafGoldstein** [comment] 2019-06-04 13:36
I meant that if you change the hostname while also joining to the domain,
could be the cause.
can you try without the rename?

**Comment by abottomsHarris** [comment] 2019-06-04 14:28
The hostname is not changing. I'm unclear on why you think it is?

**Comment by ShachafGoldstein** [comment] 2019-06-04 14:38
that is what I asked, so the hostname you send to the parameter is the same as the current hostname of the machine and you simply want it to join the ad?

can you remove the hostname parameter and use only the required?

**Comment by abottomsHarris** [comment] 2019-06-04 15:58
Edited above comment with re-run with hostname excluded as requested. Yes, I only want to join the host to AD. Is there anything else you'd like me to remove?

**Comment by ShachafGoldstein** [comment] 2019-06-05 20:50
Can you check against another OU?
and/or try without OU?

**Comment by abottomsHarris** [comment] 2019-06-06 14:52
No luck.

'''
      win_domain_membership:
        dns_domain_name: andrews.net
#        hostname: ##########
        domain_admin_user: Administrator@andrews.net
        domain_admin_password: <redacted>
        domain_ou_path: "DC=andrews,DC=net,OU=testing"    # tried with no OU as well as this manually-created new OU
        state: domain
        register: domain_state
'''

'''TASK [Join test domain] *********************************************************************************************************************************************************************
task path: /etc/ansible/debug2.yml:25
Using module file /usr/lib/python3.6/site-packages/ansible/modules/windows/win_domain_membership.ps1
<#######> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5986 TO #######
checking if winrm_host ##### is an IPv6 address
EXEC (via pipeline wrapper)
fatal: [######]: FAILED! => {
    "changed": true,
    "msg": "failed to join domain: Computer '######' failed to join domain 'andrews.net' from its current workgroup 'WORKGROUP' with following error message: The system cannot open the device or file specified.",
    "reboot_required": false
}
'''

**Comment by tbennett6421** [comment] 2019-06-10 22:18
I'm experiencing the same issue, what worked in the end for you @abottomsHarris ? For me it appears to be simply commenting out the `domain_ou_path`. I'm not sure what's causing the ou string to have problems as mine is pretty ~boring~ standard without spaces or special characters.

It expands to: `OU=Workstations,OU=Machines,DC=ansible,DC=lab`

relevant task
```
- name: Join the lab domain
  win_domain_membership:
    dns_domain_name: "{{ domain }}"
    hostname: "{{ inventory_hostname }}"
    domain_admin_user: Administrator@{{domain}}
    domain_admin_password: "{{ default_password }}"
    #domain_ou_path: "OU=Workstations,OU=Machines,{{ldap_root}}"
    state: domain
  register: domain_state
  notify: reboot windows
```
In my case the hostname doesn't appear to have any affect on the module. Earlier in my playbook there is a task to set the hostname on a freshly provisioned box to the exact same name used in the inventory and `win_domain_membership` module. Immediately after that task I force a reboot (this same role is used to promote DC's and the machine must be rebooted prior to install and configuring AD-DS)
```
- name: Set a hostname on the target
  win_hostname:
    name: "{{ inventory_hostname }}"
  register: hostname_result
  notify: reboot windows

- name: force reboot on name changes
  meta: flush_handlers
```

**Comment by ShachafGoldstein** [comment] 2019-06-16 00:11
@abottomsHarris - Can you explain again what solved it for you, maybe we can see if the docs should mention it.

**Comment by abottomsHarris** [comment] 2019-06-17 13:21
@ShachafGoldstein  @tbennett6421 
My solution: 
1. Commenting out the hostname line entirely
2. Ensuring the OU path was the following:
```
domain_ou_path: "OU=testing,DC=andrews,DC=net"
```

From some minimal reading, it appears using the hostname line attempts to change the hostname of the machine that you're joining to the domain (e.g., if it was 'hostnameA' off-domain but my hostname line said 'hostnameB' then it would become "ANDREWS\hostnameB") . I could be wrong on this point but that was my understanding.

**Comment by ShachafGoldstein** [comment] 2019-06-17 13:25
I think we should add something to the docs about this issue and I'll look into it in the next few days

**Comment by abottomsHarris** [comment] 2019-06-17 13:52
For reference, the 'testing' ou didn't exist before and Computers that I was attempting to use before was a built-in but was not under the groups/users tab on the DC. I manually created 'testing' ou and then was able to join successfully. 

Given the simplicity of the powershell command as my workaround, maybe I have confused the issue by specifying a 'domain_ou_path' at all. I get a successful join of the domain by leaving it out entirely:

```    - name: Join test domain
      win_domain_membership:
        dns_domain_name: andrews.net
        domain_admin_user: Administrator@andrews.net
        domain_admin_password: <redacted>
        state: domain
        register: domain_state
```

```
TASK [Join test domain] ***************************************************************************************************************************************************************************************
task path: /etc/ansible/debug2.yml:19
Using module file /usr/lib/python3.6/site-packages/ansible/modules/windows/win_domain_membership.ps1
<######> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5986 TO ######
checking if winrm_host ######is an IPv6 address
EXEC (via pipeline wrapper)
changed: [######] => {
    "changed": true,
    "reboot_required": true
}
```

As stated in the first post, I'm no Windows admin so I can't speak to the proper sequencing/logic of the OU/DC/CN path. Leaving it blank, the joiner-host winds up in the 'Computers' folder of the AD Users and Computers and will not be part of any groups.

Unrelated, here's a useful powershell command for checking your hosts domain status before/after as the module in maximum verbosity returns zero data:
```
    - name: Check domain status before
      win_shell: '(Get-WmiObject Win32_ComputerSystem).Domain'
      register: before
    - name: debug before
      debug:
        var: before
```

**Comment by ShachafGoldstein** [comment] 2019-06-17 14:04
I see, no doc fix is needed. just close the issue then

**Closed as completed** 2019-06-18 12:15 UTC
Labels: windows, python3, module, support:core, bug, affects_2.7
