### ISSUE TITLE
Number casting incoherence (floats not automatically cast to strings)

### ISSUE THREAD

**Issue by exclor** [ansible/ansible#20629] opened 2017-01-25 10:04 UTC
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
2.2.1
```

##### CONFIGURATION
Python 2.6.6
Red Hat Enterprise Linux Server release 6.3 (Santiago)

##### SUMMARY

Variable casting to numeric is incoherent when concatenating string with standard floating point numbers and scientific notation numbers
It would be nice to have the default casting set to strings to maintain backward compatibility.

##### STEPS TO REPRODUCE
Playbook:
```
---
- name: Testing numbers
  hosts: local
  remote_user: "{{remote_host_user}}"
  become: no
  gather_facts: no

  tasks:
    - name: Case1
      debug:
         msg: "{{ number }}"
    - name: Case2
      debug:
         msg: "a{{ number }}"

    - name: Case3
      debug:
         msg: "{{ scientific_number }}"

    - name: Case4
      debug:
         msg: "a{{ scientific_number }}"
```
Inventory:
```
[local]
localhost ansible_connection=local remote_host_user=ci

[local:vars]
number=1.1
scientific_number=1.1e-2
```

##### EXPECTED RESULTS

The expected result, is the one obtained launching the playbook with Ansible 1.9.4.
Both values "number" and "scientific_number" are considered strings and printed accordingly
```
PLAY [Testing numbers] ********************************************************

TASK: [Case1] **********************************************************
ok: [localhost] => {
    "msg": "1.1"
}

TASK: [Case2] **********************************************
ok: [localhost] => {
    "msg": "a1.1"
}

TASK: [Case3] **********************************************
ok: [localhost] => {
    "msg": "1.1e-2"
}

TASK: [Case4] **********************************************
ok: [localhost] => {
    "msg": "a1.1e-2"
}

PLAY RECAP ********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0

```

##### ACTUAL RESULTS

> 
The actual result obtained launching the playbook with ansible 2.2.1 does not guarantee backward compatibility (values are now AUTOMATICALLY casted into numeric) while with ansible 1.9 everything was treated as a string.

Moreover "Case2" and "Case4" show incoherence when concatenating values with strings, in particular:
- when a floating number is concatenated with a string the whole result is casted to string
- when a scientific number is concatenated with a string the result is NOT casted to string, the expected result in "Case4" is "a1.1e-2"

```
PLAY [Testing numbers] *********************************************************

TASK [Case1] ************************************************************
ok: [localhost] => {
    "msg": 1.1000000000000001
}

TASK [Case2] ************************************************
ok: [localhost] => {
    "msg": "a1.1"
}

TASK [Case3] ************************************************
ok: [localhost] => {
    "msg": 0.010999999999999999
}

TASK [Case4] ************************************************
ok: [localhost] => {
    "msg": "a0.011"
}

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0

**Comment by alikins** [comment] 2017-01-30 15:51
I can reproduce the results with devel branch  (8b14935521cbbb86784ffcafbd99a9faae85149a):

```
[fedora-25:float_string_cat_coherence_20629 (master %)]$ cat orig_test.yml 
---
- name: Testing numbers
  hosts: local
  remote_user: "{{remote_host_user}}"
  become: no
  gather_facts: no

  tasks:
    - name: Case1
      debug:
         msg: "{{ number }}"
    - name: Case2
      debug:
         msg: "a{{ number }}"

    - name: Case3
      debug:
         msg: "{{ scientific_number }}"

    - name: Case4
      debug:
         msg: "a{{ scientific_number }}"
[fedora-25:float_string_cat_coherence_20629 (master %)]$ cat hosts 
[local]
localhost ansible_connection=local remote_host_user=ci

[local:vars]
number=1.1
scientific_number=1.1e-2
[fedora-25:float_string_cat_coherence_20629 (master %)]$ ansible-playbook -vvv -i hosts orig_test.yml
Using /home/adrian/ansible/ansible.cfg as config file

PLAYBOOK: orig_test.yml ********************************************************************************************************************************************************************************************
1 plays in orig_test.yml

PLAY [Testing numbers] *********************************************************************************************************************************************************************************************
META: ran handlers

TASK [Case1] *******************************************************************************************************************************************************************************************************
task path: /home/adrian/src/ansible-bug-repro/float_string_cat_coherence_20629/orig_test.yml:9
ok: [localhost] => {
    "msg": 1.1
}

TASK [Case2] *******************************************************************************************************************************************************************************************************
task path: /home/adrian/src/ansible-bug-repro/float_string_cat_coherence_20629/orig_test.yml:12
ok: [localhost] => {
    "msg": "a1.1"
}

TASK [Case3] *******************************************************************************************************************************************************************************************************
task path: /home/adrian/src/ansible-bug-repro/float_string_cat_coherence_20629/orig_test.yml:16
ok: [localhost] => {
    "msg": 0.011
}

TASK [Case4] *******************************************************************************************************************************************************************************************************
task path: /home/adrian/src/ansible-bug-repro/float_string_cat_coherence_20629/orig_test.yml:20
ok: [localhost] => {
    "msg": "a0.011"
}
META: ran handlers
META: ran handlers

PLAY RECAP *********************************************************************************************************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0   
```

**Comment by alikins** [comment] 2017-01-30 16:25
I think the behavior is the intended behavior.

**Comment by samdoran** [comment] 2019-04-12 15:16
Closing as this is intended behavior.

**Closed as completed by samdoran** 2019-04-12 15:16 UTC
Labels: affects_2.2, support:core, bug
