### ISSUE TITLE
After configure my ansible.cfg with ssh_args="-C -o ControlMaster=auto -o ControlPersist=20m", ansible-core 2.16.2 can't run playbook.

### ISSUE THREAD

**Issue by yangboroy** [ansible/ansible#82640] opened 2024-02-02 16:23 UTC
### Summary

In my rhel-8, i use ansible core 2.16.2, and config `ssh_args="-C -o ControlMaster=auto -o ControlPersist=20m"` in my `ansible.cfg`. Now, i plan to run a very simple playbook, but it fails as
```
[root@bootp-73-199-153 pbench_setup]# ansible-playbook -i inventory simple.yml 
PLAY [all] ***********************************************************************************************************************************************************************************************************
TASK [Gathering Facts] ***********************************************************************************************************************************************************************************************
fatal: [bootp-73-199-54.lab.eng.pek2.redhat.com]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: unknown option --  \r\nusage: ssh [-46AaCfGgKkMNnqsTtVvXxYy] [-B bind_interface]\n           [-b bind_address] [-c cipher_spec] [-D [bind_address:]port]\n           [-E log_file] [-e escape_char] [-F configfile] [-I pkcs11]\n           [-i identity_file] [-J [user@]host[:port]] [-L address]\n           [-l login_name] [-m mac_spec] [-O ctl_cmd] [-o option] [-p port]\n           [-Q query_option] [-R address] [-S ctl_path] [-W host:port]\n           [-w local_tun[:remote_tun]] destination [command]", "unreachable": true}
PLAY RECAP ***********************************************************************************************************************************************************************************************************
bootp-73-199-54.lab.eng.pek2.redhat.com : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0  
```

Downgrade ansible core to 2.14.2. It works.

Rerun `ansible-playbook -i inventory simple.yml -vvv` with ansible core 2.16.2:
```
...
<bootp-73-199-54.lab.eng.pek2.redhat.com> SSH: EXEC ssh '-C -o ControlMaster=auto -o ControlPersist=20m' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o 'ControlPath="/root/.ansible/cp/6f37923ad0"' bootp-73-199-54.lab.eng.pek2.redhat.com '/bin/sh -c '"'"'echo ~root && sleep 0'"'"''
...
```

Rerun `ansible-playbook -i inventory simple.yml -vvv` with ansible core 2.14.2:
```
...
<bootp-73-199-54.lab.eng.pek2.redhat.com> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=20m -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o 'ControlPath="/root/.ansible/cp/6f37923ad0"' bootp-73-199-54.lab.eng.pek2.redhat.com '/bin/sh -c '"'"'echo ~root && sleep 0'"'"''
...
```

So, i see 
With ansible core 2.16.2,  '-C -o ControlMaster=auto -o ControlPersist=20m'
With ansible core 2.14.2,  -C -o ControlMaster=auto -o ControlPersist=20m

Run `ansible-config dump --only-changed -t all` with Ansible core 2.16.2.
```
CONFIG_FILE() = /root/perf-agent/pbench_setup/ansible.cfg
DEFAULT_LOG_PATH(/root/perf-agent/pbench_setup/ansible.cfg) = /root/perf-agent/pbench_setup/ansible.log
DEFAULT_REMOTE_USER(/root/perf-agent/pbench_setup/ansible.cfg) = root

CONNECTION:
==========

paramiko_ssh:
____________
remote_user(/root/perf-agent/pbench_setup/ansible.cfg) = root
ssh_args(/root/perf-agent/pbench_setup/ansible.cfg) = "-C -o ControlMaster=auto -o ControlPersist=20m"

ssh:
___
remote_user(/root/perf-agent/pbench_setup/ansible.cfg) = root
ssh_args(/root/perf-agent/pbench_setup/ansible.cfg) = "-C -o ControlMaster=auto -o ControlPersist=20m"
```

Run `ansible-config dump --only-changed -t all` with Ansible core 2.14.2.
```
CONFIG_FILE() = /root/perf-agent/pbench_setup/ansible.cfg
DEFAULT_LOG_PATH(/root/perf-agent/pbench_setup/ansible.cfg) = /root/perf-agent/pbench_setup/ansible.log
DEFAULT_REMOTE_USER(/root/perf-agent/pbench_setup/ansible.cfg) = root

CONNECTION:
==========

paramiko_ssh:
____________
remote_user(/root/perf-agent/pbench_setup/ansible.cfg) = root
ssh_args(/root/perf-agent/pbench_setup/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=20m

ssh:
___
remote_user(/root/perf-agent/pbench_setup/ansible.cfg) = root
ssh_args(/root/perf-agent/pbench_setup/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=20m
```

Seems when ansible 2.16.2 and 2.14.2 handle my ansible.cfg, they have the different behaviors on quotes.

 
### Issue Type

Bug Report

### Component Name

ssh

### Ansible Version

```console
$ ansible --version
[root@bootp-73-199-153 pbench_setup]# ansible --version
ansible [core 2.16.2]
  config file = /root/perf-agent/pbench_setup/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.7 (main, Jan 26 2024, 15:26:41) [GCC 8.5.0 20210514 (Red Hat 8.5.0-21)] (/usr/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
[root@bootp-73-199-153 pbench_setup]# ansible-config dump --only-changed -t all
CONFIG_FILE() = /root/perf-agent/pbench_setup/ansible.cfg
DEFAULT_LOG_PATH(/root/perf-agent/pbench_setup/ansible.cfg) = /root/perf-agent/pbench_setup/ansible.log
DEFAULT_REMOTE_USER(/root/perf-agent/pbench_setup/ansible.cfg) = root

CONNECTION:
==========

paramiko_ssh:
____________
remote_user(/root/perf-agent/pbench_setup/ansible.cfg) = root
ssh_args(/root/perf-agent/pbench_setup/ansible.cfg) = "-C -o ControlMaster=auto -o ControlPersist=20m"

ssh:
___
remote_user(/root/perf-agent/pbench_setup/ansible.cfg) = root
ssh_args(/root/perf-agent/pbench_setup/ansible.cfg) = "-C -o ControlMaster=auto -o ControlPersist=20m"
```

### OS / Environment

RHEL 8

### Steps to Reproduce

```yaml (paste below)
---
- hosts: all
  become: true
  become_user: root
  become_method: sudo

  gather_facts: yes
  tasks:
    - name: Shell CMD
      shell: echo abc
```
cat inventory 
bootp-73-199-54.lab.eng.pek2.redhat.com

### Expected Results

It works to run a simple playbook.

### Actual Results

```console
"Failed to connect to the host via ssh: unknown option --"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by s-hertel** [comment] 2024-02-02 17:19
This looks like a duplicate of https://github.com/ansible/ansible/issues/82387. You can work around the issue by removing the quotation marks from the ini value:
```
[ssh_connection]
ssh_args=-C -o ControlMaster=auto -o ControlPersist=20m
```
rather than
```
[ssh_connection]
ssh_args="-C -o ControlMaster=auto -o ControlPersist=20m"
```

**Comment by mkrizek** [comment] 2024-02-06 15:09
Closing as per above.

If you have further questions please stop by IRC or the mailing list:
* IRC: #ansible on irc.libera.chat
* mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Closed as completed by mkrizek** 2024-02-06 15:09 UTC
Labels: bug, affects_2.16
