### ISSUE TITLE
lineinfile should detect missing EOF newline

### ISSUE THREAD

**Issue by FiloSottile** [ansible/ansible#6881] opened 2014-04-07 14:15 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

`ansible 1.5.3`
##### Environment:

Linux
##### Summary:

When lineinfile adds a line at the end of a file, it should detect if the last character of the file is not a `\n`, and add it in case.
##### Steps To Reproduce:

```
- name: add ClientAliveInterval to sshd_config
  lineinfile: dest=/etc/ssh/sshd_config regexp="^ClientAliveInterval "
    line="ClientAliveInterval 15"
  sudo_user: root
```
##### Expected Results:

```
[...]
UsePAM yes
UseDNS no
ClientAliveInterval 15
ClientAliveCountMax 4
```
##### Actual Results:

```
UsePAM yes
UseDNS noClientAliveInterval 15
ClientAliveCountMax 4
```

**Comment by mpdehaan** [comment] 2014-04-07 17:42
This ticket seems to be rather that it didn't add the line, not that it had left off a \n.

Can you confirm the intent of this bug report?  Thanks!

**Comment by FiloSottile** [comment] 2014-04-07 18:28
Please focus on the `ClientAliveInterval 15` line, the rest is for context.

As you can see it's there in both Expected and Actual, but in Expected it's concatenated to the last line.

**Comment by jabclab** [comment] 2014-04-11 13:02
I've come across this bug too, e.g. default `/etc/ssh/sshd_config` on vanilla Centos 6.5. I want to disable root login via SSH so have this in a playbook:

```
- name: disable root login over SSH
  lineinfile: line='PermitRootLogin no'
              regexp='^PermitRootLogin'
              dest='/etc/ssh/sshd_config'
              insertafter='EOF'
              validate='sshd -T -f %s'
  sudo: yes
```

The issue is that the config file has no trailing `\n` at `EOF` so we see this:

#### before

```
# Example of overriding settings on a per-user basis
#Match User anoncvs
#   X11Forwarding no
#   AllowTcpForwarding no
#   ForceCommand cvs server
```

#### after

```
# Example of overriding settings on a per-user basis
#Match User anoncvs
#   X11Forwarding no
#   AllowTcpForwarding no
#   ForceCommand cvs serverPermitRootLogin no
```

**Comment by akkie** [comment] 2014-04-16 13:59
I have the same problem with the same file on Amazon Linux. Is there a workaround for this issue?

**Comment by rafaltrojniak** [comment] 2014-04-22 09:46
Hello, 
We also were hit by this bug.
I have tried to manually add newline at beginning or end of the line parameter, but this results in adding extra newlines every time play was run (even after it consists of such line).

We had opportunity to use "insertbefore: BOF" so we did that, and it works.

**Comment by chriszarate** [comment] 2014-05-28 22:23
@rafaltrojniak, Thanks for the workaround.

+1 on running into this problem when the `dest` file doesn't include a trailing newline.

**Comment by jimi-c** [comment] 2014-06-12 14:31
The above pull request has been merged in, which should correct this issue. Thanks!

**Closed as completed by jimi-c** 2014-06-12 14:31 UTC
Labels: bug
