### ISSUE TITLE
--limit restricts visibility to hostvars not in the catalogue for the current run

### ISSUE THREAD

**Issue by coxley** [ansible/ansible#14141] opened 2016-01-26 23:56 UTC
##### Issue Type:
- Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 1.9.4
```

Upgraded to v2.0.0.2 with some outcome.
##### Ansible Configuration:

``` ini
[defaults]
ansible_managed = This section managed by Ansible
fact_caching = jsonfile
fact_caching_connection = fact_cache
fact_caching_timeout = 86400
filter_plugins = ./plugins/filter_plugins
inventory = ./scripts/inventory.py
nocows = 1
```
##### Environment:

Doesn't really apply, but:

Ubuntu 10.04, Python 2.7, connection=local to generate fragments and assemble.
##### Summary:

From my research, `hostvars` should contain all YAML defined vars for all hosts even for `ansible-playbook` runs which specify `--limit` - It is what I'd expect also.

This is **not** concerning gathered facts and caching which a different issue (though those don't show either)

I'm trying to access defined variables in templates on other hosts while running `--limit` for faster debugging and targeted executions. 

If we have `host_vars/{hostA,hostB,hostC}.yml` and a template task running on hostA doing `{{ hostvars['hostB'] }}`, it will not contain host-specific YAML vars.

Removing the limit, it acts as you'd expect
##### Steps To Reproduce:

**Command**: `ansible-playbook -v -e set_some_vars=1 playbooks/play.yml --skip-tags=remote --ask-vault-pass --limit=hostname`

**Template** - The rest of the content isn't really relevant, this is what I'm using to test.

``` jinja2
HOSTA
-----
{{ hostvars[inventory_hostname] | to_nice_json }}

HOSTB
-----

{{ hostname['hostB'] | to_nice_json }}


```

**Role Task**:

``` yaml

---
- name: BGP | Configuring BGP
  template: src=bgp.j2 dest={{ fragments_dir }}/{{ inventory_hostname }}/bgp.conf
```

**Playbook**

``` yaml

---
- name: Build BGP Config
  hosts: all
  gather_facts: no
  connection: local
  roles:
  - bgp

```
##### Expected Results:

I would expect to see both group 'all' vars and host specific vars under both returned host dicts
##### Actual Results:

Actual results show all host vars for the --limit host (hostA), but hostB only has the group-level vars and is missing the host-specific (host_vars/hostB.yml) ones.

**Comment by sivel** [comment] 2016-01-27 00:04
I feel we could use some examples showing the issue.  Without this I'm not fully sure I understand the problem based on the given description.

Filling out the this issue using the issue template would be a good start:  

https://raw.githubusercontent.com/ansible/ansible/devel/ISSUE_TEMPLATE.md

**Comment by coxley** [comment] 2016-01-27 00:39
Will fill out and update the summary. I wish Github let repo owners enforce an issue template. :)

**Comment by coxley** [comment] 2016-01-27 01:34
Updated!

**Comment by inconshreveable** [comment] 2016-08-05 21:56
This is an important issue and remains open in ansible 2.1.1.0. @coxley how did/are you working around this?

**Comment by coxley** [comment] 2016-08-08 06:27
I've since moved on from my previous workplace where I was using Ansible in prod. IIRC, I had to do what I was doing differently hoping it would be fixed soon. :)

**Comment by jonaz** [comment] 2016-10-13 11:58
We have this issue aswell. Resulting in alot of ugly workarrounds... Would really like this solved!

**Comment by bcoca** [comment] 2016-10-13 21:41
with a simple example, i cannot reproduce this:

```
- hosts: all
  gather_facts: false
  tasks:
    - debug: var=hostvars['localhost2']['ansible_ssh_host']
```

inventory has both localhost and localhost2, when i run normally allhosts show the var, when i run with limit I also get var:
`ansible-playbook play.yml --limit localhost`
results in:

```
PLAY [all] *********************************************************************

TASK [debug] *******************************************************************
ok: [localhost] => {
    "hostvars['localhost2']['ansible_ssh_host']": "127.0.0.2"
}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```

it does not matter if the var is set in the inventory file or as a host_var/

**Comment by inconshreveable** [comment] 2016-10-13 22:24
@bcoca 

Thanks so much for looking into this! I've actually been able to track this down a minimal test case. The bug manifests itself _when the inventory file is in a subdirectory_:

```
inconshreveable ♡ : tree
.
├── env
│   └── prod
├── host_vars
│   └── localhost2
└── play.yml

2 directories, 3 files
```

```
inconshreveable ♡ : cat env/prod 
localhost ansible_ssh_host=127.0.0.1
localhost2 ansible_ssh_host=127.0.0.2

[all]
localhost
localhost2
```

```
inconshreveable ♡ : cat host_vars/localhost2 
foo: "bar"
```

```
inconshreveable ♡ : cat play.yml 
- hosts: all
  gather_facts: false
  tasks:
  - debug: var=hostvars['localhost2']['ansible_ssh_host']
  - debug: var=hostvars['localhost2']['foo']
```

```
inconshreveable ♡ : ansible-playbook -i env/prod --limit localhost play.yml 

PLAY [all] *********************************************************************

TASK [debug] *******************************************************************
ok: [localhost] => {
    "hostvars['localhost2']['ansible_ssh_host']": "127.0.0.2"
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "hostvars['localhost2']['foo']": "VARIABLE IS NOT DEFINED!"
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

If you move the inventory file into the current working directory it works as expected:

```
inconshreveable ♡ : cp env/prod .
inconshreveable ♡ : ansible-playbook -i prod --limit localhost play.yml 

PLAY [all] *********************************************************************

TASK [debug] *******************************************************************
ok: [localhost] => {
    "hostvars['localhost2']['ansible_ssh_host']": "127.0.0.2"
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "hostvars['localhost2']['foo']": "bar"
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

**Comment by bcoca** [comment] 2016-10-14 00:04
Well, that is not a bug, host/group_vars MUST be adjacent to inventory file, not in a directory above. 

This might have worked temporarily if host/group-vars were in your 'current working directory' AND you executed from that directory, but that was a bug we fixed a while back. Since the issue has to do with the directories not being where they were expected, I'm going to close this ticket.

**Closed as completed by bcoca** 2016-10-14 00:04 UTC
Labels: affects_1.9, bug

**Comment by inconshreveable** [comment] 2016-10-14 00:17
Very helpful thank you!

**Comment by jpgimenez** [comment] 2016-11-01 19:43
I can reproduce this, but is maybe a limitation more than a bug...
On a playbook that configure a load balancer we need to know the ipv4 address of internal interface, so we iterate over a group and access hostvars like this:

```
  {% for host in groups['webservers'] %}
      {% set srv_ip = hostvars[host]['ansible_eth2']['ipv4']['address'] %}
```

That works if not --limit is set, but as soon as we limit to only one host it fails because 'ansible_eth2' is only defined for the host passed on the limit param. I say limitation because the variable is a fact from a not accessed host, so I undestand that no facts are gathered, but is an annoying issue.

# Simple example:

## inventory file:

```
# Generated by Vagrant

vagrant2 ansible_ssh_host=192.168.121.152
default ansible_ssh_host=192.168.121.46

[webservers]
default
vagrant2
```

## playbook:

```
---
- hosts: all
  become: yes

  tasks:

    - name: Display eth2 address for hosts in a group
      debug: var=hostvars['{{ item }}']['ansible_eth2']['ipv4']['address']
      with_items:
        - "{{ groups['webservers'] }}"
```

## run & results:

```
$ ansible-playbook -i hosts.vagrant --vault-password-file .vault test2-jpg.yml

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [default]
ok: [vagrant2]

TASK [Display eth2 address for hosts in a group] *******************************
ok: [vagrant2] => (item=default) => {
    "hostvars['default']['ansible_eth2']['ipv4']['address']": "192.168.4.2", 
    "item": "default"
}
ok: [default] => (item=default) => {
    "hostvars['default']['ansible_eth2']['ipv4']['address']": "192.168.4.2", 
    "item": "default"
}
ok: [default] => (item=vagrant2) => {
    "hostvars['vagrant2']['ansible_eth2']['ipv4']['address']": "192.168.4.52", 
    "item": "vagrant2"
}
ok: [vagrant2] => (item=vagrant2) => {
    "hostvars['vagrant2']['ansible_eth2']['ipv4']['address']": "192.168.4.52", 
    "item": "vagrant2"
}

PLAY RECAP *********************************************************************
default                    : ok=2    changed=0    unreachable=0    failed=0   
vagrant2                   : ok=2    changed=0    unreachable=0    failed=0   
```

```
$ ansible-playbook -i hosts.vagrant --vault-password-file .vault test2-jpg.yml --limit default

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [default]

TASK [Display eth2 address for hosts in a group] *******************************
ok: [default] => (item=default) => {
    "hostvars['default']['ansible_eth2']['ipv4']['address']": "192.168.4.2", 
    "item": "default"
}
ok: [default] => (item=vagrant2) => {
    "hostvars['vagrant2']['ansible_eth2']['ipv4']['address']": "VARIABLE IS NOT DEFINED!", 
    "item": "vagrant2"
}

PLAY RECAP *********************************************************************
default                    : ok=2    changed=0    unreachable=0    failed=0   
```

**Comment by bcoca** [comment] 2016-11-01 19:55
@jpgimenez that is different issue, facts are not collected for that host, the original ticket is about group vars. You might want to look into fact caching and/or a task that runs over all hosts with `delegate_facts: True`

**Comment by jpgimenez** [comment] 2016-11-01 20:56
Thank you @bcoca, delegate facts solved my issue.
