### ISSUE TITLE
synchronize module breaks when ansible_shell_type=fish

### ISSUE THREAD

**Issue by bonds** [ansible/ansible#13490] opened 2015-12-09 18:29 UTC
Using ansible@devel https://github.com/ansible/ansible/commit/04d74fd6804b5a851cc8762cecf07b100e4dcc6f, using an account with Fish as its shell, I can successfully use the synchronize module:

```
~/s/config (master|✚26…) ❯❯❯ 
ansible -i hosts -m synchronize -a "src=/home/scott/.config/fish/ dest=/home/scott/.config/fish delete=yes" localhost -vvvv
No config file found; using defaults
Loaded callback minimal of type stdout, v2.0
ESTABLISH LOCAL CONNECTION FOR USER: scott
127.0.0.1 EXEC ( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1449685345.99-147311751194700 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1449685345.99-147311751194700 )" )
127.0.0.1 PUT /tmp/tmporuqsm TO /home/scott/.ansible/tmp/ansible-tmp-1449685345.99-147311751194700/synchronize
127.0.0.1 EXEC LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /home/scott/.pyenv/versions/2.7.10/bin/python2.7 /home/scott/.ansible/tmp/ansible-tmp-1449685345.99-147311751194700/synchronize; rm -rf "/home/scott/.ansible/tmp/ansible-tmp-1449685345.99-147311751194700/" > /dev/null 2>&1
localhost | SUCCESS => {
    "changed": false, 
    "cmd": "rsync --delay-updates -F --compress --delete-after --archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no' --out-format='<<CHANGED>>%i %n%L' \"/home/scott/.config/fish/\" \"/home/scott/.config/fish\"", 
    "invocation": {
        "module_args": {
            "_local_rsync_path": "rsync", 
            "delete": "yes", 
            "dest": "/home/scott/.config/fish", 
            "src": "/home/scott/.config/fish/"
        }, 
        "module_name": "synchronize"
    }, 
    "msg": "", 
    "rc": 0, 
    "stdout_lines": []
}
```

But if ansible_shell_type=fish is set, it breaks:

```
~/s/config (master|✚26…) ❯❯❯ 
ansible -i hosts -m synchronize -a "src=/home/scott/.config/fish/ dest=/home/scott/.config/fish delete=yes" -e "ansible_shell_type=fish" localhost -vvvv
No config file found; using defaults
Loaded callback minimal of type stdout, v2.0
ESTABLISH LOCAL CONNECTION FOR USER: scott
127.0.0.1 EXEC  umask 22 ; and mkdir -p ( echo $HOME/.ansible/tmp/ansible-tmp-1449685279.64-250696661210290 ) ; and echo ( echo $HOME/.ansible/tmp/ansible-tmp-1449685279.64-250696661210290 ) 
localhost | UNREACHABLE! => {
    "changed": false, 
    "msg": "ERROR! Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was:  umask 22 ; and mkdir -p ( echo $HOME/.ansible/tmp/ansible-tmp-1449685279.64-250696661210290 ) ; and echo ( echo $HOME/.ansible/tmp/ansible-tmp-1449685279.64-250696661210290 ) , exited with result 1", 
    "unreachable": true
}
```

I tried setting remote_temp=/tmp in ~/.ansible.cfg as the error message suggested, but that made no difference.

**Comment by bcoca** [comment] 2015-12-09 23:06
`ansible_shell_type=fish` is for when you have fish as the shell on the target machine, it does not matter on the 'controller' except for when you `delegate_to: localhost` or use `local_action`

**Comment by bonds** [comment] 2015-12-10 00:43
Understood. I used these snippets to illustrate the bug I've encountered , the practical effect is that when I'm using the synchronize module to rsync between the controller and the target, if I've set ansible_shell_type=fish on the target, I get this error. I can work around it by setting ansible_shell_type=csh on the task or by using the shell module and writing the rsync command line myself, but neither seems ideal.

In my illustration I'm rsyncing to and from the same machine, a machine which uses Fish as the shell, so both the controller and the target are running Fish as the shell.

**Comment by ksmets** [comment] 2016-01-12 21:41
I have a similar issue, when using `local_action` when using the git module. (I'm also using fish shell running on both remote and local machine).

**Comment by abadger** [comment] 2016-01-26 04:23
a change that might have fixed this was merged to devel here: https://github.com/ansible/ansible/pull/14006  and into stable-2.0 here: https://github.com/ansible/ansible/commit/8647fdc7f25ba1c707c5333ca1581a1fa0ffe566

Could someone check whether that fixed this issue?  If so the fix will be in the 2.0.1 release.

**Comment by bonds** [comment] 2016-01-26 21:25
I installed 8647fdc7f25ba1c707c5333ca1581a1fa0ffe566 with:

```
~/s/config (master|✚8…) ❯❯❯ pip2 uninstall ansible
~/s/config (master|✚8…) ❯❯❯ pip2 install git+https://github.com/ansible/ansible.git@8647fdc7f25ba1c707c5333ca1581a1fa0ffe566
```

and ran the same command and got the same error:

```
~/s/config (master|✚8…) ❯❯❯ 
ansible -i hosts -m synchronize -a "src=/home/scott/.config/fish/ dest=/home/scott/.config/fish delete=yes" -e "ansible_shell_type=fish" localhost -vvvv
No config file found; using defaults
Loaded callback minimal of type stdout, v2.0
ESTABLISH LOCAL CONNECTION FOR USER: scott
127.0.0.1 EXEC /bin/sh -c ' umask 22 ; and mkdir -p ( echo $HOME/.ansible/tmp/ansible-tmp-1453842977.55-256037622019004 ) ; and echo ( echo $HOME/.ansible/tmp/ansible-tmp-1453842977.55-256037622019004 ) '
localhost | UNREACHABLE! => {
    "changed": false, 
    "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was:  umask 22 ; and mkdir -p ( echo $HOME/.ansible/tmp/ansible-tmp-1453842977.55-256037622019004 ) ; and echo ( echo $HOME/.ansible/tmp/ansible-tmp-1453842977.55-256037622019004 ) , exited with result 1", 
    "unreachable": true
}
```

**Comment by ksmets** [comment] 2016-01-27 08:52
Could it be that you need to specify `executable` to `/usr/bin/fish` in `ansible.cfg`. The problem is that `and` and `or` are used and that doesn't work with `/bin/sh`.

**Comment by abadger** [comment] 2016-01-29 00:06
Okay, I've got a pull request that I think fixes this.  Could you give #14196 a try?

It is a candidate to go to the stable-2.0 branch but it may not make it into 2.0.1 (it will make it into 2.0.2 if it doesn't).

**Comment by bonds** [comment] 2016-01-29 17:01
sorry, still doesn't work

**Comment by bonds** [comment] 2016-01-29 17:08
I tested 76c941305b5a388141a6316083092d1a5096f93b and, unfortunately, I still get the same error. I also tested the hash from the PR (2c825539ffb737051add23dbb9f16a5fef24e469), same result.

**Comment by bonds** [comment] 2016-01-29 17:10
Please reopen, or let me know and I'll create a new ticket.

**Comment by abadger** [comment] 2016-01-30 07:13
@bonds could you tell us what the host machine's shell is, what the remote machine's shell is, what you have in inventory for the two machines and your playbook to reproduce?

**Comment by bonds** [comment] 2016-02-01 17:21
@abadger in this ticket's description you can see the relevant repro steps. Both the host and remote machine are running Fish shell, since, in the case of the examples, both the host and remote are the same machine and that machine is running Fish shell.

**Comment by abadger** [comment] 2016-02-02 17:13
Okay, I talked with @bcoca about this and he clarified that `ansible_shell_type` should not be used here.  In fact, it should almost never be used.  I'll attempt to summarize what he told me.

There's a bug in 2.0.0.{0,1,2} which makes it so `ansible_shell_type` needs to be used in circumstances where it shouldn't.  Namely, if the remote machine is using a non bourne compatible shell, the shell_type needs to be set to the remote shell type.  (In previous versions of ansible, one could set this but the information wasn't used to set quoting style.)  This behaviour was a bug in 2.0.0.x rather than a feature because ansible should be invoking /bin/sh directly and passing the command invocation to that shell.  So the quoting style should always be /bin/sh style, not /bin/fish style.  If you encounter a place where you need to add ansible_shell_type and /bin/sh is present on the remote system, then that would be a bug we need to address.

So what is the use of ansible_shell_type?  The answer is that it is used in conjunction with the ansible.cfg executable option: http://docs.ansible.com/ansible/intro_configuration.html#executable  If the remote machine doesn't have a /bin/sh then you can set executable to an alternate shell like /bin/fish.  When you do so you need to also set ansible_shell_type=fish so that ansible knows to quote appropriately for that shell.

There's a bit of a mismatch having one of these be set globally in the ansible.cfg and the other be set per-host in inventory.  In some future version of ansible we'll probably add a config option for shell_type and/or a per-host variable for executable to remedy that.

I just checked and everything does work when ansible_shell_type is unset (using the default sh) so I'll close this now.

**Closed as completed by abadger** 2016-02-02 17:13 UTC
Labels: bug
