### ISSUE TITLE
with_nested should also handle lists of hashes

### ISSUE THREAD

**Issue by akkie** [ansible/ansible#6916] opened 2014-04-09 13:04 UTC
##### Issue Type:

“Feature Idea”
##### Ansible Version:

ansible 1.5.4
##### Environment:

Ubuntu 14.04
##### Summary:

Currently `with_nested` does only handle lists with scalar values. But it should also handle lists of hashes.
##### Steps To Reproduce:

Consider the following use case:

``` yaml
- name: Provision instance
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    - volumes: [{dev: /dev/hda1, size: 10}]
  tasks:
    # previous tasks

    - name: Attach volumes to previously created instances
      local_action:
        module: ec2_vol
        instance: "{{ item[0].id }}"
        device_name: "{{ item[1].dev }}"
        volume_size: "{{ item[1].size }}"
        region: $aws_region
      with_nested:
        ec2.instances
        volumes
      register: ec2_volumes
      when: volumes is defined
```
##### Expected Results:

The module should create multiple devices for every instance.
##### Actual Results:

Ansible fails with the message:

```
fatal: [localhost] => One or more undefined variables: 'str object' has no attribute 'id'
```

**Comment by mpdehaan** [comment] 2014-04-14 15:50
PSA:  There are $foo variables here which are removed in 1.6, use the following instead:

```
region: "{{ aws_region }}"
```

You might have deprecation warnings off as you might have had warnings about these.

I would have thought this should be handled, so I'll classify this a bug and we can test to reproduce.

**Comment by jctanner** [comment] 2014-04-14 18:09
1.6 does produce errors in the ec2 module when region is in the form of an old style var:

```
$ ansible --version
ansible 1.6 (devel db36c41c3b) last updated 2014/04/14 13:18:21 (GMT -400)

TASK: [make one instance] *****************************************************
failed: [localhost] => {"failed": true}
msg: value of region must be one of: ap-northeast-1,ap-southeast-1,ap-southeast-2,eu-west-1,sa-east-1,us-east-1,us-west-1,us-west-2, got: $region
```

**Comment by Beneter** [comment] 2016-01-07 01:22
This is still a problem for me.

**Comment by jimi-c** [comment] 2016-07-09 07:52
Hi, I just tested this with the following playbook, and it appears to have been fixed at some point in the past (though this issue was not update or unknown to the person who fixed it):

<pre>
- hosts: localhost
  gather_facts: no
  tasks:
  - debug:
      msg: "{{item[0]}} {{item[1].foo}}"
    with_nested:
    - [ 'alice', 'bob' ]
    - [ {foo: "bar"}, {foo: "bam"} ]
</pre>

Which results in the following output:

<pre>
# ansible-playbook -v test.yml 
Using /etc/ansible/ansible.cfg as config file
PLAY [localhost] ***************************************************************
TASK [debug] *******************************************************************
ok: [localhost] => (item=[u'alice', {u'foo': u'bar'}]) => {
    "item": [
        "alice", 
        {
            "foo": "bar"
        }
    ], 
    "msg": "alice bar"
}
ok: [localhost] => (item=[u'alice', {u'foo': u'bam'}]) => {
    "item": [
        "alice", 
        {
            "foo": "bam"
        }
    ], 
    "msg": "alice bam"
}
ok: [localhost] => (item=[u'bob', {u'foo': u'bar'}]) => {
    "item": [
        "bob", 
        {
            "foo": "bar"
        }
    ], 
    "msg": "bob bar"
}
ok: [localhost] => (item=[u'bob', {u'foo': u'bam'}]) => {
    "item": [
        "bob", 
        {
            "foo": "bam"
        }
    ], 
    "msg": "bob bam"
}
PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
</pre>

As such, we will close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by jimi-c** [comment] 2016-07-09 07:53
This was tested with devel, by the way:

<pre>
# ansible-playbook --version
ansible-playbook 2.2.0 (devel 46cdb27376) last updated 2016/07/08 16:20:25 (GMT -500)
  lib/ansible/modules/core: (detached HEAD 799159b8ee) last updated 2016/07/07 15:19:27 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD 8502d2595a) last updated 2016/07/07 15:19:28 (GMT -500)
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible']
</pre>

**Closed as completed by jimi-c** 2016-07-09 07:52 UTC
Labels: feature
