### ISSUE TITLE
Allowed formatting has changed in 2.o

### ISSUE THREAD

**Issue by smiller171** [ansible/ansible#13913] opened 2016-01-15 16:36 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

2.0
##### Ansible Configuration:

N/A
##### Environment:

Ubuntu 14.04
##### Summary:

Previously allowed formatting is no longer accepted
##### Steps To Reproduce:

Put `---` as the top line in tasks/main.yml
##### Expected Results:

Playbook works as expected
##### Actual Results:

Playbook fails

**Comment by bcoca** [comment] 2016-01-15 16:41
Yes, the YAML parser is much better at reporting invalid formatting which previously was silently ignored or caused subtle bugs.

**Comment by smiller171** [comment] 2016-01-15 16:44
@bcoca wasn't `---` at the top of a yaml file the proper formatting that was advised in the getting started guide?

**Comment by smiller171** [comment] 2016-01-15 16:45
sorry, I accidentally submitted before I had the full comment details in.

**Comment by bcoca** [comment] 2016-01-15 16:51
i responded on title alone, with an actual issue now ...:

This should not break the parser. 
In fact i just tested and this works for me.

without an actual error message there is not much more i can do.

**Comment by bcoca** [comment] 2016-01-15 16:51
test1/tasks/main.yml 

```
---
# tasks file for test1
- debug: msg=RIGHT
```

running play with test1 role:

```
 ______ 
< PLAY >
 ------ 
  \
   \ ,   _ ___.--'''`--''//-,-_--_.
      \`"' ` || \\ \ \\/ / // / ,-\\`,_
     /'`  \ \ || Y  | \|/ / // / - |__ `-,
    /@"\  ` \ `\ |  | ||/ // | \/  \  `-._`-,_.,
   /  _.-. `.-\,___/\ _/|_/_\_\/|_/ |     `-._._)
   `-'``/  /  |  // \__/\__  /  \__/ \
        `-'  /-\/  | -|   \__ \   |-' |
          __/\ / _/ \/ __,-'   ) ,' _|'
         (((__/(((_.' ((___..-'((__,'

 ______________________ 
< TASK [test1 : debug] >
 ---------------------- 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

ok: [localhost] => {
    "msg": "RIGHT"
}
 ____________ 
< PLAY RECAP >
 ------------ 
     \
      \
       ("`-'  '-/") .___..--' ' "`-._
         ` *_ *  )    `-.   (      ) .`-.__. `)
         (_Y_.) ' ._   )   `._` ;  `` -. .-'
      _.. `--'_..-_/   /--' _ .' ,4
   ( i l ),-''  ( l i),'  ( ( ! .-'    

localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```

**Comment by jimi-c** [comment] 2016-01-15 17:01
The only time I've seen this fail is when there are multiple `---` lines in the file, which is in fact an invalid yaml file.

**Comment by bcoca** [comment] 2016-01-15 17:02
well, not invalid, its a 'multidocument' file, which we don't support

**Comment by smiller171** [comment] 2016-01-15 17:04
I'll work on putting together a minimal failure case.

**Comment by nomaster** [comment] 2016-01-17 17:27
Apparently, I'm running into the same issue.

[Update: trunk version works fine, though.]

Ansible version: 2.0.0.2-1

The task file of my 'common' role includes a number of others:

``` YAML
# roles/common/tasks/main.yml
---

- include: hostname.yml
- include: snmpd.yml
- include: syslog.yml
- include: gretun.yml
- include: loopback.yml
```

This always worked for me, but since the upgrade, Ansible throws an error.

``` shell
% ansible-playbook site.yml --diff --check                         
Vault password: 
ERROR! The handlers/main.yml file for role 'common' must contain a list of tasks

The error appears to have been in '/home/nomaster/src/ffddorf/config/roles/common/tasks/main.yml': line 3, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- include: hostname.yml
^ here
```

Note that this is not a syntax error, so the YAML checks out fine, but Ansible gets confused about it.

**Comment by jimi-c** [comment] 2016-01-18 03:34
@nomaster in your case, it appears to be complaining about an error in the handlers file, but it's showing the error line in the tasks file (which is very odd in itself):

<pre>
ERROR! The handlers/main.yml file for role 'common' must contain a list of tasks
</pre>

Can you share your handlers file?

**Comment by nomaster** [comment] 2016-01-18 08:43
Right. Missed that spot.

``` YAML
# roles/common/handlers/main.yml
---

- name: restart snmpd
  service: name=snmpd state=restarted

- name: restart syslog
  service: name=syslog-ng state=restarted

- name: restart journald
  service: name=systemd-journald state=restarted
```

**Comment by smiller171** [comment] 2016-01-18 14:57
I'm having trouble recreating my issue. We had an issue with a deployment and I failed to capture the logs. Can't seem to recreate in a VM

**Comment by bcoca** [comment] 2017-03-11 05:20
So since this is not reproducible, I'm going to close this ticket. If you can generate a reproducible case, please open a new one and reference this one.

**Closed as completed by bcoca** 2017-03-11 05:20 UTC
Labels: affects_2.0, bug
