### ISSUE TITLE
force_handlers does not work with inline handler using roles

### ISSUE THREAD

**Issue by l0neranger** [ansible/ansible#13940] opened 2016-01-17 22:39 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

Default configuration.
##### Environment:

Control Machine: OS X v10.11.2
Managed Node: Debian Jessie 8.2
##### Summary:

site.yml:

```

---
- hosts: '{{ hosts }}'
  become: yes
  become_user: root
  force_handlers: yes

  roles:
    - test-role

# Ansible 2.0 known issue
# - include doesn't work with runtime execution for handlers.
  handlers:
    - name: restart-nginx
      service:
        name: nginx
        state: restarted
```

roles/test-role/tasks/main.yml:

```

---
- block:
    - name: Install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes
      notify:
      - restart-nginx
  when: ansible_os_family == "Debian"
```
##### Steps To Reproduce:

```
ansible-playbook -i hosts site.yml -e "hosts=test"
```
##### Expected Results:

The handler restarts nginx on every execution when force_handlers is set to yes.
##### Actual Results:

The handler runs the only once during installation. The force_handlers directive which is meant to run handlers regardless of the task status, does not trigger handler on further executions after installation.

**Comment by jimi-c** [comment] 2016-01-22 20:39
I am unable to reproduce this. Using a slightly modified version of your example, here's what I get:

<pre>
TASK [setup] *******************************************************************
ok: [localhost]
TASK [test-role : Install nginx] ***********************************************
NOTIFIED HANDLER restart-nginx
ok: [localhost] => {
    "msg": "here i am"
}
TASK [test-role : fail] ********************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed as requested from task"}
NO MORE HOSTS LEFT *************************************************************
RUNNING HANDLER [restart-nginx] ************************************************
ok: [localhost] => {
    "msg": "ok restarted nginx"
}
PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=1   
</pre>

The modified role is as follows:

<pre>
---
- block:
    - name: Install nginx
      debug: msg="here i am"
      changed_when: true
      notify:
      - restart-nginx
    - fail:
  #when: ansible_os_family == "Debian"
</pre>

And the main playbook is identical (except I use a debug for the handler rather than the actual service module).

@l0neranger Is there any additional information you can provide regarding this?

**Comment by l0neranger** [comment] 2016-01-23 10:42
@jimi-c 
On first run the force_handlers executes just fine:

```
SHELL $ ansible-playbook -i hosts/hosts site.yml -e "hosts=test"

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [test]

TASK [test-role : Install nginx] ***********************************************
changed: [test]

RUNNING HANDLER [restart-nginx] ************************************************
changed: [test]

PLAY RECAP *********************************************************************
test                       : ok=3    changed=2    unreachable=0    failed=0
```

But on a subsequent run...

```
SHELL $ ansible-playbook -i hosts/hosts site.yml -e "hosts=test"

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [test]

TASK [test-role : Install nginx] ***********************************************
ok: [test]

PLAY RECAP *********************************************************************
test                       : ok=2    changed=0    unreachable=0    failed=0

```

My expectation with force_handlers is that the handler is run every single time according to http://docs.ansible.com/ansible/playbooks_error_handling.html -

> When handlers are forced, they will run when notified even if a task fails on that host

LMK if I'm missing something very obvious.

**Comment by jimi-c** [comment] 2016-01-23 14:05
Correct, the handlers will run when forced even if there's a failure. However in this case, there is no failure, what's happening is there is no notification to that handler. Without a notification, handlers won't run even if force_handlers is set.

If you want the handler to run regardless, you can create a notification task with `changed_when: True` (as I did above), which will always send a notification to the handler.

Hope that helps.

**Comment by bcoca** [comment] 2016-01-23 14:09
"meant to run handlers regardless of the task status" <= wrong assumption

http://docs.ansible.com/ansible/playbooks_error_handling.html#handlers-and-failure

^ as the docs explain, if forces handlers to run when notified and after a task failure for that host. Closing this ticket as this is a misunderstanding of how the feature works.

**Closed as completed by bcoca** 2016-01-23 14:09 UTC
Labels: needs_info, P2, bug
