### ISSUE TITLE
yum update fail

### ISSUE THREAD

**Issue by urajio** [ansible/ansible#12659] opened 2015-10-07 08:17 UTC
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible 1.9.3
##### Ansible Configuration:

nothing special
##### Environment:

run from: OS X 10.11
managing: OracleLinux 7.1
##### Summary:

Playbook with this task fail:

```
- name: Upgrade
  yum: name=* state=latest update_cache=yes
```
##### Actual Results:

```
TASK: [packages-yum | Upgrade] ************************************************ 
<192.168.x.x> ESTABLISH CONNECTION FOR USER: root
<192.168.x.x> REMOTE_MODULE yum name=* state=latest update_cache=yes
<192.168.x.x> EXEC ssh -C -tt -v -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/wicommander/.ansible/cp/ansible-ssh-%h-%p-%r" -o IdentityFile="/Users/wicommander/.ssh/id_rsa_java" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 192.168.x.x /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1444204659.82-210310868168839 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1444204659.82-210310868168839 && echo $HOME/.ansible/tmp/ansible-tmp-1444204659.82-210310868168839'
<192.168.x.x> PUT /tmp/tmpiCqSFi TO /root/.ansible/tmp/ansible-tmp-1444204659.82-210310868168839/yum
<192.168.x.x> EXEC ssh -C -tt -v -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/wicommander/.ansible/cp/ansible-ssh-%h-%p-%r" -o IdentityFile="/Users/wicommander/.ssh/id_rsa_java" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 192.168.x.x /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python -tt /root/.ansible/tmp/ansible-tmp-1444204659.82-210310868168839/yum; rm -rf /root/.ansible/tmp/ansible-tmp-1444204659.82-210310868168839/ >/dev/null 2>&1'
failed: [ns2] => {"changed": false, "errors": "unexpected state", "failed": true, "results": ""}
msg: we should never get here unless this all failed

FATAL: all hosts have already failed -- aborting
```

**Comment by abadger** [comment] 2015-10-08 16:21
This is a duplicate of https://github.com/ansible/ansible-modules-core/issues/2013 which is fixed in the devel branch and in 1.9.4.  We're currently on rc3 for 1.9.4.

**Closed as completed by abadger** 2015-10-08 16:21 UTC
Labels: P2, packaging
