### ISSUE TITLE
Ansible 1.6.8 does not like single quotes (needs repro)

### ISSUE THREAD

**Issue by aabdnn** [ansible/ansible#8255] opened 2014-07-23 01:56 UTC
##### Summary:

Ansible insists on using double quotes around variable module parameters, and does not permit single quotes.
##### Steps To Reproduce:

Create a task like this:
- name: add rsync server key to known_hosts
  lineinfile: dest=/home/ansible/.ssh/known_hosts create=yes
              owner=ansible group=ansible mode=600
              regexp='^{{item.host}}' line='{{item.host}},{{item.addresses}} {{item.key}}'
  with_items: known_hosts
##### Expected Results:

The task should run just fine under 1.6.6.
##### Actual Results:

Under 1.6.6, the above task runs just fine. Under 1.6.8, it gives the error:

TASK: [local_ansible | add rsync server key to known_hosts] ******************\* 
fatal: [vicuna.ripe.net] => A variable inserted a new parameter into the module args. Be sure to quote variables if they contain equal signs (for example: "{{var}}").

**Comment by mpdehaan** [comment] 2014-07-23 23:57
I agree this shouldn't need to be a thing for the (non-command based) modules and we can see about fixing this.

Until then, the workaround should be to just use the double quotes.

cc @jimi-c

**Comment by jimi-c** [comment] 2014-07-24 00:25
@arhbkb can you share a full playbook that reproduces this for you? I'm unable to reproduce it with the following playbook on either devel or 1.6.8:

<pre>
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    foo: "foo=foo"
    bar: "bar"
  tasks:
  - copy: dest=/tmp/8255.txt content='{{foo}} {{bar}}'
</pre>

Which results in the following:

<pre>
TASK: [copy dest=/tmp/8255.txt content='foo=foo bar'] ************************* 
changed: [127.0.0.1] => {"changed": true, "dest": "/tmp/8255.txt", "gid": 0, "group": "root", "md5sum": "3f886d22ac1eb21c50d925f11f3610e0", "mode": "0644", "owner": "root", "secontext": "unconfined_u:object_r:user_tmp_t:s0", "size": 11, "src": "/root/.ansible/tmp/ansible-tmp-1406161405.45-151907408050054/source", "state": "file", "uid": 0}
</pre>

**Comment by mpdehaan** [comment] 2014-07-24 04:20
Also we've pushed some parsing improvements and additional integration tests to the development branch now.    These shouldn't affect the above if we are still having trouble repro'ing but should be relevant for similar quoting questions.

**Comment by jaspernbrouwer** [comment] 2014-07-25 10:43
I have the same problem after upgrading to 1.6.8

Going over _all_ playbooks and galaxy roles to change single quotes to double quotes isn't really an option at the moment, that would probably take at least a full day's work.

I've downgraded to 1.6.7 as a workaround.

PS: I'm using [host] Python 2.7.8 on OS X 10.9.4 (build 13E28), [guest] Python 2.7.3 on Debian wheezy 7.6

**Comment by jimi-c** [comment] 2014-07-25 14:40
We've also just released 1.6.9, which addresses some quoting issues as well. Could you please try with that version to see if your issue is resolved? If not, could you please include an example from your playbook that reproduces the issue?

**Comment by aabdnn** [comment] 2014-07-25 15:32
Thanks @jimi-c. My colleague @ioc32 has just tested 1.6.9 against the playbook, and it is now working fine. The issue I reported has been resolved.

**Comment by jimi-c** [comment] 2014-07-25 15:44
@arhbkb excellent. I'll go ahead and close this then. Thanks!

**Closed as completed by jimi-c** 2014-07-25 15:44 UTC
Labels: P2, bug
