### ISSUE TITLE
global name 'os' is not defined

### ISSUE THREAD

**Issue by volkhin** [ansible/ansible#12759] opened 2015-10-15 10:07 UTC
Unexpected Exception: global name 'os' is not defined
the full traceback was:

Traceback (most recent call last):
  File "/tmp/ansible/bin/ansible-playbook", line 80, in <module>
    sys.exit(cli.run())
  File "/tmp/ansible/lib/ansible/cli/playbook.py", line 138, in run
    results = pbex.run()
  File "/tmp/ansible/lib/ansible/executor/playbook_executor.py", line 77, in run
    self._inventory.set_playbook_basedir(os.path.dirname(playbook_path))
NameError: global name 'os' is not defined

**Comment by quinot** [comment] 2015-10-15 10:16
This is collateral damage from ca826508d992f99ab6cba75d03a34b804448dfef.

**Comment by mgedmin** [comment] 2015-10-15 11:02
#12758 fixes this.

**Comment by chrrrles** [comment] 2015-10-15 13:17
Unable to reproduce, so probably fixed by #12758  - adding to pending closure

**Comment by quinot** [comment] 2015-10-15 13:21
Indeed, in principle this should be fixed by fed7cea7958ea8db686eaa7cfa1631dfc88acfda.

**Comment by jimi-c** [comment] 2015-10-15 13:36
Closed as fixed, thanks!

**Closed as completed** 2015-10-15 13:35 UTC
Labels: pending_action
