### ISSUE TITLE
meta reset_connection doesn't appear to work on windows

### ISSUE THREAD

**Issue by paylocity-sflanders** [ansible/ansible#62077] opened 2019-09-10 15:50 UTC
##### SUMMARY
Trying to utilize the meta reset_connection on a windows machine documented here: https://docs.ansible.com/ansible/2.8/modules/meta_module.html  However anyway i format it, it complains with error:

ERROR! Unexpected Exception, this is probably a bug: 'Requested entry (plugin_type: connection plugin: winrm setting: _extras ) was not defined in configuration.'

I've tried variations where i sets vars for winrm to try to get around it but can't find any documentation on how to fix it.  It appears to produce same result for any of the other meta.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
reset_connection

##### ANSIBLE VERSION

```paste below
ansible 2.8.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/code/Corp/ENV/domain-cluster-teamcity/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 20 2019, 20:27:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION
```paste below
DEFAULT_MODULE_PATH(env: ANSIBLE_LIBRARY) = [u'/home/code/Corp/ENV/domain-cluster-teamcity/library']
DEFAULT_MODULE_UTILS_PATH(env: ANSIBLE_MODULE_UTILS) = [u'/home/code/Corp/ENV/domain-cluster-teamcity/module_utils']
DEFAULT_ROLES_PATH(env: ANSIBLE_ROLES_PATH) = [u'/home/code/Corp/ENV/domain-cluster-teamcity/roles']
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = //root/.vault_pass
```

##### OS / ENVIRONMENT
windows

##### STEPS TO REPRODUCE
Create a playbook with a line like:

```yaml
- name: reset connection
  meta: reset_connection
```
or

```yaml
- name: reset connection
  meta: reset_connection
  vars:
    _extras:
    ansible_connection: winrm
    ansible_winrm_scheme: http
    ansible_port: 5985
    ansible_winrm_transport: kerberos
    ansible_winrm_server_cert_validation: ignore
```

##### EXPECTED RESULTS
doesn't error

##### ACTUAL RESULTS

```paste below
ERROR! Unexpected Exception, this is probably a bug: 'Requested entry (plugin_type: connection plugin: winrm setting: _extras ) was not defined in configuration.'
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 110, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 123, in run
    results = pbex.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 169, in run
    result = self._tqm.run(play=play)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 249, in run
    play_return = strategy.run(iterator, play_context)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/linear.py", line 263, in run
    results.extend(self._execute_meta(task, play_context, iterator, host))
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 1075, in _execute_meta
    connection.reset()
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/winrm.py", line 515, in reset
    self._connect()
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/winrm.py", line 507, in _connect
    self._build_winrm_kwargs()  # build the kwargs from the options set
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/winrm.py", line 263, in _build_winrm_kwargs
    passed_winrm_args = set([v.replace('ansible_winrm_', '') for v in self.get_option('_extras')])
  File "/usr/lib/python2.7/site-packages/ansible/plugins/__init__.py", line 60, in get_option
    raise KeyError(to_native(e))
KeyError: 'Requested entry (plugin_type: connection plugin: winrm setting: _extras ) was not defined in configuration.'
```

**Comment by sivel** [comment] 2019-09-10 15:52
This is likely a duplicate of https://github.com/ansible/ansible/issues/58184

**Comment by sivel** [comment] 2019-09-17 15:30
Closing per above.

**Closed as completed by sivel** 2019-09-17 15:30 UTC
Labels: support:core, bug, traceback, affects_2.8
