### ISSUE TITLE
Broken 'Edit on GitHub' link at http://docs.ansible.com/ansible/intro_adhoc.html

### ISSUE THREAD

**Issue by webarchitect609** [ansible/ansible#20547] opened 2017-01-22 10:15 UTC
##### ISSUE TYPE
 - Documentation Report

##### SUMMARY
'Edit on GitHub' http://joxi.ru/l2Z6VxFwlbVL2J?d=1 link leads to 404 error page http://joxi.ru/eAO14Wfxv1Gdmo?d=1

##### STEPS TO REPRODUCE
1 Go to http://docs.ansible.com/ansible/intro_adhoc.html
2 Press 'Edit on GitHub' at top right corner. 
3 See 404 error page. 

##### EXPECTED RESULTS
Some kind of valid git hub page for editing related page. 

##### ACTUAL RESULTS
404 error page

**Comment by sivel** [comment] 2017-01-22 17:48
This is a duplicate of https://github.com/ansible/ansible/issues/20474

**Closed as completed by sivel** 2017-01-22 17:48 UTC
Labels: affects_2.3, docs
