### ISSUE TITLE
include_role: handlers issue

### ISSUE THREAD

**Issue by hryamzik** [ansible/ansible#26718] opened 2017-07-12 19:03 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

include_role

##### ANSIBLE VERSION

```
2.3.0.0
```

##### SUMMARY

Handlers are not found in `include_role`.

##### STEPS TO REPRODUCE

```
roles/test/
├── included
│   └── handlers
│       └── main.yml
└── main
    └── tasks
        └── main.yml
```

roles/test/main/tasks/main.yml
```yml
- debug: msg="ping"
  changed_when: yes
  notify: pong

- include_role:
    name: test/included

```

roles/test/included/handlers/main.yml
```yml
- name: pong
  debug: msg="pong"
```

playbook
```yml
- hosts: all
  roles:
    - role: test/main

  handlers:
    - name: other
      debug: msg="other"

```

Note `handlers` section, works fine without it!

##### ACTUAL RESULTS

```
PLAY [all] *************************************************************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [setup] **********************************************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [all]

TASK [test/main : debug] **********************************************************************************************************************************************************************************************************************************************************************************************************************************************
ERROR! The requested handler 'pong' was not found in either the main handlers list nor in the listening handlers list

```

Clone of #26698 that was closed instead of waiting for an update, good job @abadger.

**Comment by dmizelle** [comment] 2017-07-13 01:18
I don't think handlers included via `include_role` work like that.

At the time that your debug task is running in `roles/test/main/tasks/main.yml`, there is no defined handler named `pong`.

Ansible doesn't work like other CM systems (Puppet, etc) where the entire DSL is compiled and ran as a catalog. It is more of a procedural, declarative one. You need need to define the handler before the task that notifies said handler, either by adding it to the current role or including the handler file before then.

Additionally, in my memory, I don't think that you can call handlers cross-role. I.e., you can only call handler `pong` from inside role `test/included`. I may be wrong though.

**Comment by hryamzik** [comment] 2017-07-13 09:21
@dmizelle you are wrong. It even works fine if you remove `handlers` section from this playbook.

**Comment by willthames** [comment] 2017-07-17 02:57
This might be fixed with #26335 - can you check?

**Comment by dmizelle** [comment] 2017-07-17 14:12
@hryamzik 

Sorry, in retrospect after reading my comment, I seem to have completely missed the point you were trying to make. Have you tried #26335 ?

**Comment by sivel** [comment] 2018-05-01 15:57
Duplicate of https://github.com/ansible/ansible/issues/18140

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Closed as completed by sivel** 2018-05-01 15:57 UTC
Labels: affects_2.3, support:core, include_role, bug
