### ISSUE TITLE
ansible_os_family value lost when using -include

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible#18486] opened 2016-11-14 21:05 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Core

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.3.0 (devel 11465134fa) last updated 2016/11/14 14:28:27 (GMT -500)
  lib/ansible/modules/core: (devel d21ac8a5da) last updated 2016/11/14 14:28:28 (GMT -500)
  lib/ansible/modules/extras: (devel 19c7d5b31b) last updated 2016/11/14 14:28:30 (GMT -500)
  config file = /Users/tanner/projects/ansible.git/playbooks.git/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
Unchanged from git pull from devel branch

##### OS / ENVIRONMENT

Running Ansible from macOS
Managing OpenSolaris, OpenIndiana, Linux

##### SUMMARY
ansible_os_family value is lost when using "- include" of another yaml file and from what I can tell the 
"- debug" command doesn't function properly either.

##### STEPS TO REPRODUCE
```
---
# file: updates/main.yml
- debug: msg="main.yml {{ ansible_os_family }}"
- include: debian.yml
  when: ansible_os_family == 'Debian'
- include: solaris.yml
  when: ansible_os_family == 'Solaris'
```
```
---
# tasks file for updates/debian.yml
- debug: msg="inside debian.yml"
- debug: msg="{{ ansible_os_family }}"
```
```
---
# tasks file for updates/solaris.yml
- debug: msg="inside solaris.yml"
- debug: msg="{{ ansible_os_family }}"
```

##### EXPECTED RESULTS
On a Debian based Linux installation, debug would output "main.yml Debian", "inside debian.yml", "Debian"

On a Solaris based installation, debug would output "main.yml Solaris", "inside solaris.yml", "Solaris"

##### ACTUAL RESULTS
On Solaris installations
```
TASK [Gathering Facts] *********************************************************
ok: [test-oi1.local]
ok: [test-o2.local]

TASK [updates : debug] *********************************************************
ok: [test-oi1] => {
    "msg": "main.yml Solaris"
}
ok: [test-oi2 => {
    "msg": "main.yml Solaris"
}

TASK [updates : debug] *********************************************************

TASK [updates : debug] *********************************************************

(processes the debian.yml tasks)
```

**Comment by dagwieers** [comment] 2019-01-23 17:51
This works fine for me on the devel branch. Since this one is pretty old, I am going to close it.

If you can still reproduce this on a more recent Ansible version (one that is supported), feel free to leave a comment, or contact me on IRC.

**Closed as completed by dagwieers** 2019-01-23 17:51 UTC
Labels: affects_2.3, support:core, bug
