### ISSUE TITLE
White list action plugin overrides for network modules

### ISSUE THREAD

**Issue by Qalthos** [ansible/ansible#22166] opened 2017-03-01 21:03 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
executor/task_executor.py

##### ANSIBLE VERSION

```
2.3
```

##### SUMMARY

Action plugins overriding introduced in 2.3 are overly broad and can lead to issues when custom modules with the same prefix are used.

See #22121

**Comment by bcoca** [comment] 2017-03-01 22:56
actually, that is how they always worked, for networking there was a change introduced that allowed connection plugin to override the action plugin, but @privateip recently removed that.

**Comment by gundalow** [comment] 2017-03-07 17:35
So, assuming I've understood the discussion correctly this issue is not a bug, and in fact is very much by design.

The case outlined in https://github.com/ansible/ansible/issues/22121 is regarding someone created a new module called `junos_*`. We are post new module freeze for 2.3, so this will not be an issue. Therefore moving to 2.4

@privateip and @Qalthos Need to review this, though based on my understanding this can be closed WONTFIX/BYDESIGN

**Comment by stacywsmith** [comment] 2017-03-07 17:58
@privateip @Qalthos @gundalow This is new behavior introduced in 2.3 and really needs to be fixed for 2.3. It breaks existing Junos Galaxy modules provided by Juniper which are named junos_*.

**Comment by gundalow** [comment] 2017-03-07 17:59
@stacywsmith Ah, that was some detail I missed, moved back to `2.3`

**Closed as completed** 2017-03-11 16:28 UTC
Labels: networking, affects_2.3, bug

**Comment by gundalow** [comment] 2017-03-13 17:23
@stacywsmith A fix has been pushed into `devel`, Could you please retest, and add a comment 

Thanks in advance.

**Comment by stacywsmith** [comment] 2017-03-14 15:45
@gundalow #22423 generally looks good to me, but it tickled a latent bug in the junos galaxy modules. I filed #22589 for that issue, and I have a suggested fix in #22590. I also have Juniper/ansible-junos-stdlib#215 to address the underlying issue in the junos galaxy modules.
