### ISSUE TITLE
Private property for vars_prompt hangs

### ISSUE THREAD

**Issue by AlexanderAllen-zz** [ansible/ansible#10517] opened 2015-03-22 10:10 UTC
Whenever I specify the private property on my vars_prompt Ansible takes my input, but after pressing enter it "hangs". If I take the "private" property out, vars_prompt works.

Reference: https://github.com/ansible/ansible/blob/507a1ef0934b9a03c9c76c4faa84b89731f22748/docsite/rst/playbooks_prompts.rst

Hangs:

```
# playbook.yml

hosts: foobar
vars_prompt:

    - name: "release_version"
      prompt: "Product release version"
      private: no
```

Works:

```
    - name: "release_version"
      prompt: "Product release version"
```

Ansible version: ansible 1.8.4

**Comment by bcoca** [comment] 2015-03-22 21:00
can you fill in the template? I cannot reproduce on my machines and more information would be helpful.

**Comment by TimPerry** [comment] 2015-04-02 12:32
Any update on this? I am also experiencing this. If you point me towards the template you mentioned I can fill it out for my setup.

**Comment by jder** [comment] 2015-04-04 13:19
@TimPerry The issue template is here if you want to fill it out: https://github.com/ansible/ansible/blob/devel/ISSUE_TEMPLATE.md

**Comment by bcoca** [comment] 2015-04-04 16:40
I cannot reproduce this issue, since you don't provide additional information I don't know I'll ever be able to.

**Comment by TimPerry** [comment] 2015-04-08 07:56
Issue Type: Bug
Ansible Version:  1.9.0.1
Environment: Running from OS X 10.9.5 on a virtualbox (vagrant) the host is CentOS release 5.11 (Final) which is Python 2.4.3
Summary:
var_prompts hangs when setting the private property

e.g. this works:

```
- name: "install_configurator"
  prompt: "Do you want to install the Configurator?"
  default: "N"
```

but this hangs:

```
- name: "install_configurator"
  prompt: "Do you want to install the Configurator?"
  default: "N"
  private: no
```

As does this:

```
- name: "install_configurator"
  prompt: "Do you want to install the Configurator?"
  default: "N"
  private: yes
```

Steps To Reproduce:
Add a var_prompts section that has the private property then when prompted attempt to enter some input and press enter and it will hang.

Expected Results:
Input should be accepted and ansible should continue.

Actual Results:
Ansible prompts for input, input is entered but when you press enter it hangs.

If you need any more detail let me know!

**Comment by bcoca** [comment] 2015-04-08 14:00
so I asked people with OS X to test and they cannot reproduce, the only thing i can think of is that you don't have sshpass installed.

**Comment by sivel** [comment] 2015-04-08 14:21
The only thing that I can imagine is the potential for there being no tty. Without a tty, I don't believe getpass would be able to read the input.

**Comment by bcoca** [comment] 2015-04-08 14:25
Matt brings up a good point, are you running this from cron?

On Wed, Apr 8, 2015 at 10:21 AM, Matt Martz notifications@github.com
wrote:

> The only thing that I can imagine is the potential for there being no tty.
> Without a tty, I don't believe getpass would be able to read the input.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ansible/ansible/issues/10517#issuecomment-90930793.

## 

Brian Coca

**Comment by TimPerry** [comment] 2015-04-09 07:21
All of this would make sense if I was trying to make it private but we actually want it visible i.e. none private so surely I shouldn't need sshpass installed? I might be missing the point entirely but all we want is the input to be visible on screen. When setting the private property to yes or no it hangs, I could understand your points if it only hanged for private: yes but for private: no I am confused to why it would need any additional libraries to just show input on screen.

**Comment by jder** [comment] 2015-04-09 13:17
This sounds very similar to this issue when running under `vagrant provision`; is that what you're doing? https://github.com/mitchellh/vagrant/issues/2924

In that case, though, `private: yes` did _not_ hang, because `getpass` works fine. Looking at the code it is hard to see how passing `private: yes` would be any different than not specifying `private`.

**Comment by bcoca** [comment] 2015-04-09 13:20
@TimPerry I'm just trying to find out why it works for others but not for you. You are not really giving us any info to go on. Please answer the questions posed.

**Comment by TimPerry** [comment] 2015-04-10 10:01
@jder I am using vagrant provision and I have checked and I was mistaken having private: yes does work, I think I might have been doing private: Y or something before...

Are we to presume that vagrant + ansible + public var_prompts is a no go due to vagrant?

**Comment by bcoca** [comment] 2015-04-10 17:18
yes, this is a known issue with vagrant, closing this ticket then

**Closed as completed by bcoca** 2015-04-10 17:18 UTC
Labels: P2, bug
