### ISSUE TITLE
request to follow symlinks in group and host_var directories

### ISSUE THREAD

**Issue by zitterbacke** [ansible/ansible#5280] opened 2013-12-13 10:29 UTC
Hi,

when upgrading from 1.3.4 to 1.4.1 I noticed that symlinks in group_vars/ are no longer read. Following play works with 1.3.4, but not with 1.4.1:

```
- hosts: all
  sudo: False
  tasks:
    - group_by: key=extra_{{ ansible_default_ipv4.network }}
    - name: debugging dynmaic group variables
      debug: msg="var test has value {{ test }}"
```

with following content in group_vars:

``` bash
$ ls -al group_vars/*
lrwxrwxrwx group_vars/extra_X.X.X.X -> myfile
-rw-r--r-- group_vars/myfile
```

and the content of group_vars/myfile

``` bash
$ cat group_vars/myfile 
test: bla
```

Thanks, AlfZi.

**Comment by byronmccollum** [comment] 2013-12-13 17:24
I'm having the same issue with 1.4.1.

https://gist.github.com/byronmccollum/7946964

**Comment by mpdehaan** [comment] 2013-12-14 16:57
In queue to be reproduced.

Possibly just a thing because of the new support for intermediate directories, i.e. it's legal to organize as

host_vars/some_folder/groupname.yml now

and probably an explicit os.path.isfile check

**Comment by zitterbacke** [comment] 2014-01-21 08:39
Hi,

Pull Request #5580: "Symlinking rel path in group_vars.py bug fix" fixes this issue.

+1 for merging it.

Thanks, AlfZi

**Comment by mpdehaan** [comment] 2014-03-16 17:57
This is merged, so closing this one, thanks!

**Closed as completed by mpdehaan** 2014-03-16 17:57 UTC
Labels: bug
