### ISSUE TITLE
Ansible does not look for ansible.cfg in parent directories

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible#15473] opened 2016-04-19 11:19 UTC
It seems that at this moment ansible is not able to look for `ansible.cfg` file in parent directories and this make quite difficult to manage bigger layouts where you end-up having lots of playbooks.

If you want to start storing playbooks in subdirectories you will not able able to load the configuration file from the repository root. 

Yes, it is possible to point the default ansible configuration from system or user directory to the repository one that this does not make much sense in practice. 

We want to be able to use ansible just by checking out the repository and without having to mangle the user configuration in order to be able to use it.

Please make it work like `setup.cfg` or `.gitignore` where you do not need to create config files at each level.

**Comment by tyleha** [comment] 2017-01-18 03:17
Same as #17115 ? (great idea though)

**Comment by bcoca** [comment] 2017-01-18 19:08
closing as dupe of #17115

**Closed as completed by bcoca** 2017-01-18 19:08 UTC
Labels: affects_2.2, affects_2.3, feature
