### ISSUE TITLE
[USER module] cant create a home folder if path doesnt end with /

### ISSUE THREAD

**Issue by kiranos** [ansible/ansible#6897] opened 2014-04-08 17:03 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.4
##### Environment:

Debian 7
##### Summary:

the user module cant create a home folder if path doesnt end with /

```
 ansible test -m user -a "name=johnd home=/home/test1/test2/test"
192.168.0.3 | FAILED >> {
    "failed": true,
    "msg": "useradd: cannot create directory /home/test1/test2/test\n",
    "name": "johnd",
    "rc": 12
}
```

and tried locally with useradd:

```
ssh 192.168.0.3
labb:~# useradd -d /home/test1/test2/test johnd
labb:~#

```
##### Steps To Reproduce:

Check that parent folder is missing and run:

ansible test -m user -a "name=johnd home=/home/test1/test2/test"
##### Expected Results:

work like:

```
ansible test -m user -a "name=johnd home=/home/test5/test6/test/"
192.168.0.3 | success >> {
    "append": false,
    "changed": true,
    "comment": "",
    "group": 2002,
    "home": "/home/test5/test6/test/",
    "move_home": false,
    "name": "johnd",
    "shell": "/bin/sh",
    "state": "present",
    "uid": 2002
}
```
##### Actual Results:

```
FAILED >> {
    "failed": true,
    "msg": "useradd: cannot create directory /home/test1/test2/test\n",
    "name": "johnd",
    "rc": 12
}
```

**Comment by jimi-c** [comment] 2014-04-21 19:53
@kiranos This seems to be more of a limitation of the useradd command on debian, where it will not create the full directory tree if the parent doesn't exist. Even using the createhome=yes option (so that -m is used with the command does not appear to help).

**Comment by kiranos** [comment] 2014-04-21 20:35
hm I'm not following, it does work if I have / at the end like:

ansible test -m user -a "name=johnd home=/home/test5/test6/test/"

even if /home/test5/ doesnt exist previously. Or do I miss something?

**Comment by jimi-c** [comment] 2014-04-21 21:33
@kiranos I wasn't able to reproduce that, it returned an error for me in both cases. I'll try it again later and see if I can reproduce it again.

**Comment by kiranos** [comment] 2014-04-22 06:46
you are correct I tried again with

"useradd -d /home/testing/test4/test32 johntest -m"

and it didnt let me create it, I tried ubuntu aswell and no go. I can create the subfolder before with command module.

**Comment by jimi-c** [comment] 2014-04-22 13:42
@kiranos ok to close this then? Perhaps adding a note to the createhome option regarding the parent directory existing on certain platforms might be useful.

**Comment by kiranos** [comment] 2014-04-22 14:00
I created a test centos server and its the same there:

[root@centos6test ~]# cat /etc/issue
CentOS Linux release 6.0 (Final)  
Kernel \r on an \m

[root@centos6test ~]# useradd -m -d /home/test1/test2/test johnd
useradd: cannot create directory /home/test1/test2/test 

So its probably how useradd works? cant find a definit answer on that though.

**Comment by jimi-c** [comment] 2014-04-22 14:23
Yes, that does appear to be the case. So yes, I'm going to close this, with the note that the file module should be used to create the parent directory for the user's home if it does not already exist. If you have any further questions regarding this, please let us know. Thanks!

**Closed as completed by jimi-c** 2014-04-22 14:23 UTC
Labels: needs_info, P2, bug
