### ISSUE TITLE
ansible-pull later than 1..6.5 throws "ERROR: A vault password must be specified to decrypt [encrypted file]"

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#11748] opened 2015-07-27 01:30 UTC
### Issue Type:

Bug report
### Ansible Version:

Currently experiencing this on 1.9.2 but the issue appears to be present in every version I tested since 1.6.5.
### Ansible Configuration:

N/A
### Environment:

Issue is present in Ubuntu 12.04 and 14.04, I have not tested any other platforms.
### Summary:

ansible-pull throws an error suggesting no vault password is provided to decrypt vault-encrypted files. However, I provide the --vault-password-file flag as part of the command.
### Steps To Reproduce:

Run ansible-pull as follows:

```
ssh-keyscan github.com > ~/.ssh/known_hosts && ansible-pull -o -d /home/ansible/Systems -U [repository] --vault-password-file=[vault_pw_file] -i /home/ansible/Systems/hosts
```

I have also tried specifying the vault password in the following ways:
- specifying ANSIBLE_VAULT_PASS 
- setting vault_password_file = in my ansible.cfg, then setting ANSIBLE_CONFIG prior to running ansible-pull. 

Both environment variables yield the same error below.
### Expected Results:

ansible-pull should run to completion (or report other issues with the playbook).
### Actual Results:

This command works as expected with ansible 1.6.5, but in every later version that I have tested, I get this:

```
Starting ansible-pull at 2015-07-27 01:08:42
ERROR: A vault password must be specified to decrypt /home/ansible/Systems/[an_encrypted_file]
```

I have also tried running ansible-playbook in local connection mode, similar to what ansible-pull should be doing:

```
ansible-playbook Systems/local.yml -c local -i Systems/hosts --vault-password-file=[vault_pw_file] --limit=`hostname`
```

The above command (with ansible-playbook) works fine.

**Comment by akatch** [comment] 2016-01-15 05:18
I'm not sure if this was meant to make it into 2.0 but I am seeing similar behavior in 2.0.0.2:

```
ansible@box:~$ ansible-pull -o -d /home/ansible/Systems -U [repository] -i /home/ansible/Systems/hosts --vault-password-file=/home/ansible/.vault
Starting Ansible Pull at 2016-01-15 05:13:04
/usr/local/bin/ansible-pull -o -d /home/ansible/Systems -U [repository] -i /home/ansible/Systems/hosts --vault-password-file=[vault_pw_file]
ERROR! Decryption failed
ansible@box:~$ ansible --version
ansible 2.0.0.2
  config file = 
  configured module search path = Default w/o overrides
```

I was able to successfully run a very simple test playbook using ansible-playbook with similar parameters:

```
ansible@box:~$ ansible-playbook Systems/local.yml -c local -i Systems/hosts --vault-password-file=[vault_pw_file] --check --limit=`hostname`

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [box.example.com]

TASK [ping] ********************************************************************
ok: [box.example.com]

PLAY RECAP *********************************************************************
box.example.com           : ok=2    changed=0    unreachable=0    failed=0 
```

**Comment by bcoca** [comment] 2016-01-30 00:02
hmm, this seems to work fine for me, used http://github.com/bcoca/configme as pull object (vault password is 'test')

i am using current devel and stable-2.0, have not tested 2.0.0.2, but if you can confirm it works for you in those, i can just close this as it will be fixed on next release.

**Comment by akatch** [comment] 2016-01-30 00:29
This is getting weirder and weirder. Testing against your repository works, but testing again against my own repository does not. I've double, triple, and quadruple checked the vault password and it is definitely correct (it wouldn't have changed between versions anyway)... and it works correctly in 1.6.5.

One thing that's very strange is that if I try to run the ansible-pull command with --ask-vault-pass instead of --vault-password-file, it still fails with "Decryption failed" (and I never get prompted for the password). I should add that in the middle of troubleshooting this I noticed that running `ansible-pull --help` suggests that the -U argument must come before all other options, which I seem to have missed previously. I have changed up my command so that the -U argument comes first, but I still see this behavior. Here's the command I'm currently using:

```
ansible-pull -U [repo] --directory=/home/ansible/Systems --vault-password-file=[pw_file] --inventory-file=/home/ansible/Systems/hosts --checkout=master
```

**Comment by akatch** [comment] 2016-01-30 00:31
Just for funsies, I also just tried using my repository over https (previously we were using a ssh://git@github.com/Organization/repo.git style repository URL) and the behavior persists.

**Comment by bcoca** [comment] 2016-01-30 00:34
i really can't do much w/o a way to reproduce the issue, any clues on how your repo is diff?

**Comment by akatch** [comment] 2016-01-30 01:27
I think I've figured out where this originates. I don't know if it's actually a bug or desired behavior, but if I supply the relative path to the inventory file as --inventory-file, it works (in my example, the functional parameter is `--inventory-file=hosts`). It does not work if I supply the absolute path (as in all of the examples above). My guess as to why this is happening in my repo and not yours is that when I tested against your repo, your local.yml uses localhost (and thus requires no inventory file) and mine doesn't.

The documentation suggests that `--inventory-file` should accept an absolute path, so I don't _think_ this is desired behavior.

**Comment by muff1nman** [comment] 2016-03-13 23:28
Not sure if you need a new ticket opened, but I encountered this same issue. I have been able to reproduce it using the following repository:

https://github.com/muff1nman/ansible-simple-vault-repo.git

The command used to run this was `ansible-playbook -i inventory --ask-vault-pass local.yml`

```
ansible 1.9.4
  configured module search path = None
```

**Comment by muff1nman** [comment] 2016-03-13 23:49
Scratch, that. I cannot reproduce with that repo with:

```
$ ansible --version
ansible 2.1.0 (devel d211b4c962) last updated 2016/03/13 17:48:06 (GMT -600)
  lib/ansible/modules/core: (detached HEAD c86a0ef84a) last updated 2016/03/13 17:48:13 (GMT -600)
  lib/ansible/modules/extras: (detached HEAD 33a557cc59) last updated 2016/03/13 17:48:13 (GMT -600)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

**Comment by jimi-c** [comment] 2016-06-27 21:38
# Closing This Ticket

Hi!

As this issue appears to be resolved in the most recent release branch, we are going to close this at this time.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2016-06-27 21:38 UTC
Labels: bug
