### ISSUE TITLE
role defaults' vars not visible when using import_role in playbook.

### ISSUE THREAD

**Issue by Jean-Daniel** [ansible/ansible#33768] opened 2017-12-11 12:28 UTC
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

```
ansible 2.5.0
  config file = /home/conductor/playbooks/ansible.cfg
  configured module search path = ['/home/conductor/playbooks/plugins/modules']
  ansible python module location = /home/conductor/env/lib/python3.5/site-packages/ansible
  executable location = /home/conductor/env/bin/ansible
  python version = 3.5.2 (default, Nov 17 2016, 17:05:23) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```
CACHE_PLUGIN(/home/conductor/playbooks/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/conductor/playbooks/ansible.cfg) = ~/.ansible/facts
CACHE_PLUGIN_TIMEOUT(/home/conductor/playbooks/ansible.cfg) = 86400
DEFAULT_DEBUG(/home/conductor/playbooks/ansible.cfg) = False
DEFAULT_GATHERING(/home/conductor/playbooks/ansible.cfg) = smart
DEFAULT_JINJA2_EXTENSIONS(/home/conductor/playbooks/ansible.cfg) = jinja2.ext.do,jinja2.ext.i18n
INJECT_FACTS_AS_VARS(/home/conductor/playbooks/ansible.cfg) = False
MERGE_MULTIPLE_CLI_TAGS(/home/conductor/playbooks/ansible.cfg) = True
RETRY_FILES_ENABLED(/home/conductor/playbooks/ansible.cfg) = False
```
##### OS / ENVIRONMENT

N/A

##### SUMMARY

I'm trying to use the modern role include syntax to mix tasks and roles import in a playbook but switching to "classic manner" to the "import_include" syntax cause undefined variables issues.

When using the classic syntax, the role's defaults are visible inside the playbook file and other roles. When using import_roles, the role's defaults are visible only inside the role that declare them.

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  tasks:
    - import_role: { name: myrole }
    - debug:
        msg: "myrole default: {{ myrole_default }}"
```

file: roles/myrole/defaults/main.yaml
```yaml
myrole_default: "hello"
```

##### EXPECTED RESULTS

```
TASK [debug] *****************************************************************************************
ok: [localhost] => {
    "msg": "myrole default: hello"
}
```

##### ACTUAL RESULTS

```
TASK [debug] *****************************************************************************************
task path: /Users/jddupas/Projects/python/playbooks/playbook.yaml:4
fatal: [localhost]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'myrole_default' is undefined\n\nThe error appears to have been in '/Users/jddupas/Projects/python/playbooks/playbook.yaml': line 4, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n    - import_role: { name: myrole }\n    - debug:\n      ^ here\n"
}
```

Note:  When using the classic syntax, it works fine (but I can't mix tasks and roles as I need):

```yaml
- hosts: localhost
  roles:
    - myrole
  tasks:
    - debug:
        msg: "myrole default: {{ myrole_default }}"
```

**Comment by alikins** [comment] 2017-12-11 19:00
(reformatted error output for easier reading here)
```
The task includes an option with an undefined variable. The error was: 
'myrole_default' is undefined

The error appears to have been in '/Users/jddupas/Projects/python/playbooks/playbook.yaml': line 4, column 7,
but may be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  - import_role: { name: myrole }
    - debug:
      ^ here
```

**Comment by alikins** [comment] 2017-12-11 19:08
I can reproduce with devel c2b4fd7f1e

```
[newswoop:F27:ansible (devel % u=)]$ cat ping_import_role_33768.yml 
- hosts: localhost
  gather_facts: false
  tasks:
    - import_role: { name: myrole }
    - debug:
        msg: "myrole default: {{ myrole_default }}"

[newswoop:F27:ansible (devel % u=)]$ cat roles/myrole/defaults/main.yml 
myrole_default: "hello"


[newswoop:F27:ansible (devel % u=)]$ ansible-playbook -vvv ping_import_role_33768.yml 
ansible-playbook 2.5.0 (devel c2b4fd7f1e) last updated 2017/12/11 11:52:13 (GMT -400)
  config file = /home/adrian/src/ansible/ansible.cfg
  configured module search path = [u'/home/adrian/ansible/my-modules']
  ansible python module location = /home/adrian/src/ansible/lib/ansible
  executable location = /home/adrian/src/ansible/bin/ansible-playbook
  python version = 2.7.14 (default, Nov  3 2017, 10:55:25) [GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]
Using /home/adrian/src/ansible/ansible.cfg as config file
 
PLAYBOOK: ping_import_role_33768.yml **********************************************************************
1 plays in ping_import_role_33768.yml

PLAY [localhost] ******************************************************************************************
META: ran handlers

TASK [debug] **********************************************************************************************
task path: /home/adrian/src/ansible/ping_import_role_33768.yml:5
fatal: [localhost]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'myrole_default' is undefined\n\nThe error appears to have been in '/home/adrian/src/ansible/ping_import_role_33768.yml': line 5, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n    - import_role: { name: myrole }\n    - debug:\n      ^ here\n"
}

PLAY RECAP ************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   
```

**Comment by sivel** [comment] 2018-05-08 19:39
This is by design, and no functionality has been added to support exposing these vars outside of the role at this time.

I've updated this to a feature idea.

**Comment by sivel** [comment] 2018-05-08 19:41
Duplicate of https://github.com/ansible/ansible/issues/21890

**Closed as completed by sivel** 2018-05-08 19:41 UTC
Labels: support:core, affects_2.5, feature
