### ISSUE TITLE
include statement does not respect --tag in Ansible 2.0

### ISSUE THREAD

**Issue by tetherit** [ansible/ansible#12809] opened 2015-10-18 02:07 UTC
I have this in my task file:

```
- name: Check if we already have an openvpn key file
  stat: "path='/etc/openvpn/{{ vpn_domain }}.conf'"
  register: openvpn_config

- include: "openvpn-genkey.yml"
  when: openvpn_config.stat.exists == False
```

However, I see this output:

```
time ansible-playbook --forks=20 timeboxes.yml --limit guardhome1 --tag timeagent

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [guardhome1 -> localhost]

TASK [common : include] ********************************************************
included: user.yml for guardhome1

TASK [common : include] ********************************************************
included: apt.yml for guardhome1

... MORE OUTPUT HERE ...

TASK [timebox : include] *******************************************************
fatal: [guardhome1]: FAILED! => {"failed": true, "msg": "ERROR! The conditional check 'openvpn_config.stat.exists == False' failed. The error was: ERROR! error while evaluating conditional: openvpn_config.stat.exists == False ({% if openvpn_config.stat.exists == False %} True {% else %} False {% endif %})"}

PLAY RECAP *********************************************************************
guardhome1                 : ok=19   changed=0    unreachable=0    failed=1   
```

I'm using latest Ansible from git.

**Comment by tetherit** [comment] 2015-10-18 02:22
Ah, it seems this happens because includes do not take --tag into account. So if you have an include, in a task file that should be skipped, it will run the include statement anyway.

**Comment by adragomir** [comment] 2015-10-19 10:38
@jimi-c @hackeron seems related to / duplicate of this, I think: https://github.com/ansible/ansible/issues/12793

**Comment by jimi-c** [comment] 2015-10-19 13:40
Yes, this is "as expected", and not an issue in 2.0. As @adragomir, this is also the underlying cause of #12793, which I'm looking at now.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-10-19 13:40 UTC
