### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by randyqx** [ansible/ansible#11889] opened 2015-08-07 13:31 UTC
Issue Type:

```
Bug Report
```

Ansible Version:

% ansible --version
ansible 2.0.0
  config file = 
  configured module search path = None

Fully patched Mac OSX 10.10.4 on a maxed out late 2013 MBP retina

Summary:

```
- hosts: localhost
  tasks:
    - name: run a command
      command: date
      register: ver_out
      changed_when: false
```

Expected Results:

Successful setting of {{ver}}

Actual Results:

```
fatal: [frobnitz.edu]: FAILED! => {"msg": "Traceback (most recent call last):
  File \"/root/.ansible/tmp/ansible-tmp-1438822667.55-270531375236680/command\", line 2106, in <module>
    main()
  File \"/root/.ansible/tmp/ansible-tmp-1438822667.55-270531375236680/command\", line 158, in main
    module = CommandModule(argument_spec=dict())
  File \"/root/.ansible/tmp/ansible-tmp-1438822667.55-270531375236680/command\", line 607, in __init__
    self._check_for_check_mode()
  File \"/root/.ansible/tmp/ansible-tmp-1438822667.55-270531375236680/command\", line 1133, in _check_for_check_mode
    for (k,v) in self.params.iteritems():
AttributeError: 'tuple' object has no attribute 'iteritems'
", "failed": true, "changed": false, "parsed": false, "invocation": {"module_name": "command", "module_args": {"_raw_params": "syslog-ng --version"}}}
```

**Comment by bcoca** [comment] 2015-08-07 14:26
so I ran your test and it works,  also your error output does not match the play.

**Comment by bcoca** [comment] 2015-08-07 14:28
output I get:

```
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [run a command] ***********************************************************
ok: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
```

**Comment by sivel** [comment] 2015-08-07 14:29
This is likely related to running mismatched versions of ansible and the core modules.  The command module required an update to work with recent updates to ansible itself.

**Comment by candlerb** [comment] 2015-08-07 18:10
I can replicate this under ubuntu 12.04.  Fresh checkout of ansible from git, and
- `git submodule init`
- `git submodule update`
- `. hacking/env-setup`

```
brian@wrn-mon1:~/ansible-git$ cat ~/test.yml
- hosts: localhost
  tasks:
    - command: date
      register: ver_out
brian@wrn-mon1:~/ansible-git$ ansible-playbook ~/test.yml

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [command] *****************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'tuple' object has no attribute 'iteritems'
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "parsed": false}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1

brian@wrn-mon1:~/ansible-git$ ansible-playbook --version
ansible-playbook 2.0.0 (devel 8f106c9a58) last updated 2015/08/07 19:06:53 (GMT +100)
  lib/ansible/modules/core: (detached HEAD 8412adc4f9) last updated 2015/08/07 08:18:17 (GMT +100)
  lib/ansible/modules/extras: (detached HEAD 210ee3febc) last updated 2015/08/07 08:18:33 (GMT +100)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/08/07 08:18:51 (GMT +100)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/08/07 08:19:06 (GMT +100)
  config file = /etc/ansible/ansible.cfg
  configured module search path = /usr/share/ansible
```

**Comment by fiunchinho** [comment] 2015-08-24 17:17
Same here. Fresh git clone on osx, following installation instructions.

**Comment by coledarr** [comment] 2015-08-30 07:56
Ubuntu 14.04 git ansible pull 8/29/2015 around midnight. Took the test.yml above from candlerb. Same problem described above. Tried using shell instead of command, still same issue.

**Comment by faxe78** [comment] 2015-09-16 11:11
tried today because i have some issue around service state detection and read that it would be better in 2.0 devel, can't run man playbooks because of the errors mentioned above centos 6.

**Comment by kleptog** [comment] 2016-01-29 13:13
FWIW, I was getting this error running the version on pypi, not any git version. The cause was apparently a conflict with the installed debian package version. Uninstalling the package fixed it.

**Comment by acsrujan** [comment] 2016-03-18 08:25
I had this issue. I had debian package installed as well as pypi. I removed debian package `sudo apt-get purge ansible` and it worked well.

**Comment by bcoca** [comment] 2016-03-18 13:50
So i'm going to close this as it does not seem like an Ansible bug but the result of installing conflicting versions.

**Closed as completed by bcoca** 2016-03-18 13:50 UTC
Labels: bug
