### ISSUE TITLE
[WARNING]: sftp transfer mechanism failed

### ISSUE THREAD

**Issue by jesusch** [ansible/ansible#22127] opened 2017-03-01 10:33 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ping

##### ANSIBLE VERSION

ansible 2.2.1.0

##### CONFIGURATION
[defaults]
inventory       = $HOME/ansible/hosts
host_key_checking = False
log_path = $HOME/ansible/ansible.log
[privilege_escalation]
become=True

##### OS / ENVIRONMENT
Debian8
ansible installed via pip

##### SUMMARY
[WARNING]: sftp transfer mechanism failed occured during ping

##### STEPS TO REPRODUCE
jesusch@myhost:~$ ansible all -m ping
 [WARNING]: sftp transfer mechanism failed on [myhost]. Use ANSIBLE_DEBUG=1 to see detailed information

myhost | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
ANSIBLE_DEBUG=1 ansible all -m ping -vvvvv
can be found at https://www.boschman.de/~jesusch/tmp/sftp.log

##### EXPECTED RESULTS
no warning?

**Comment by jctanner** [comment] 2017-03-03 14:35
@jesusch please use ANSIBLE_DEBUG=1 and -vvvv to give us better information.

needs_info

**Comment by jesusch** [comment] 2017-03-04 07:58
The requested Output already hast been supplied?

**Comment by ceving** [comment] 2017-03-31 12:07
I have the problem with the `copy` module. But only if the copy module does a transfer. But the transfer succeeds. A second run does not transfer anything. Same Ansible version.

**Comment by profhase** [comment] 2017-08-31 15:19
I have the same problem when I do the copy of a large file and there is not enough space on the partition the ansible temp folder is in (even if i copy the file to another partition), e.g.:

    File Size 6G

    /home/myuser  -> /dev/sda1 (3G free)
    /var/opt/           -> /dev/sdb1 (100G free)

copy file to `/var/opt` throws same warning and the transfer fails

**Comment by mftovey** [comment] 2017-09-08 14:40
I am experiencing this too, but on AIX systems, so it appears to be OS agnostic.  I do not see this on any of my Linux or Solaris systems.  I am running this across several systems simultaneously, and it occurs only on some of them.  I also see the warning when I use the file module to remove the transferred files.

**Comment by mftovey** [comment] 2017-09-08 18:22
I found it, at least in my case.  sftp-server was failing on the affected servers, and so Ansible switched to just using scp instead, which explains why the files were being delivered in spite of the warning.  As to why sftp-server was failing took me a while to track down, but I did solve it.  On the servers that worked, the sshd_config file was world readable, so sftp-server, which is running in the calling user environment was able to read it.  On the servers where SFTP was not working, the sshd_config file was not world readable, and so sftp-server could not read its configuration and so failed.  The preference is to keep sshd_config secure, so I switched to using internal-sftp in the sshd_config file.  That stopped sshd from starting a separate process for SFTP instead of just handling it itself, and so the sshd_config file can remain secure while allowing SFTP transfers to function properly.
This may not be the solution for everyone, but it worked for me.

**Comment by bcoca** [comment] 2017-09-08 18:44
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

This is not a bug, Ansible just warned you it was unable to use sftp for some reason but still succeeded by falling back to scp.

As for the reason why, it will probably require debugging on the ssh server side as the message `Received exit status from master 127` normally indicates that the 'command was not found', which suggests that the sftp subsystem configured is not accessible.

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Closed as completed by bcoca** 2017-09-08 18:44 UTC
Labels: affects_2.2, module, support:core, bug

**Comment by jmarcos-cano** [comment] 2018-02-07 10:06
For me (Centos 7) I needed to change /etc/ssh/sshd_config 

from this: 
`Subsystem    sftp    /usr/libexec/openssh/sftp-server`

to this:
`Subsystem sftp internal-sftp`

restart sshd (`systemctl restart sshd`) 

hope it helps

**Comment by tomtastic** [comment] 2018-08-08 10:43
I'm having this problem also, I can test scp and sftp manually and they work fine, but Ansibles fetch module reports that they both fail : `"msg": "Failed to connect to the host via ssh: ", "unreachable": true`.

```yaml
- name: Fetch to storage
  fetch:
    src: '{{ item.path }}'
    dest: '/development/ansible/output/{{ inventory_hostname }}/'
    flat: yes
  with_items: '{{ agent_log.files }}
```

Despite the fetch module task failing, the file is actually fetched!

```# ansible --version
ansible 2.4.2.0
  config file = /development/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

Attached is an ANSIBLE_DEBUG log :  
[ansible_fetch_problem.txt](https://github.com/ansible/ansible/files/2269951/ansible_fetch_problem.txt)

**Comment by tomtastic** [comment] 2018-08-08 11:06
Fails only when `pipelining = True` is set.

**Comment by jctanner** [comment] 2018-08-08 14:50
@tomtastic can you file that in a new bug please?

**Comment by tomtastic** [comment] 2018-08-09 11:03
@jctanner [43880](https://github.com/ansible/ansible/issues/43880) done.

**Comment by atul-ram** [comment] 2018-08-30 08:40
This worked for me.

# if True, make ansible use scp if the connection type is ssh
scp_if_ssh = True

**Comment by masseybradley** [comment] 2018-11-08 12:20
FWIW I encountered the error on AIX 7.2 TL2. The SFTP log contained errors "ssh_packet_send: invalid format" suspected to be related to the known error with OpenSSH 7.5 (http://www-01.ibm.com/support/docview.wss?crawler=1&uid=isg1IJ03680) when using compression (default ansible.cfg ssh_args option using  2.5.10) - anyhow, patching OpenSSL 1.0.2.1500 and OpenSSH 7.5.102.1500 worked for me (http://www-01.ibm.com/support/docview.wss?uid=isg3T1025737).

**Comment by C0rn3j** [comment] 2018-12-17 20:36
in my case my VPS (Scaleway) somehow had the wrong line in sshd_config.

I had 
```
Subsystem sftp /usr/lib/openssh/sftp-server
```
where I needed
```
Subsystem sftp /usr/lib/ssh/sftp-server
```

I guess you can see if your config is pointing at the right file by using something like `locate` to look for it.

```
[0] # locate sftp-server
/usr/lib/ssh/sftp-server
```

Surprisingly just restarting the openssh service didn't work, but it did work after a full reboot.

**Comment by ssbarnea** [comment] 2018-12-17 21:12
Something that hit me recently and I think it would be useful to know: the host ended up with some files inside /etc/profile.d/foo.sh which were not really behaving correctly with non interactive terminals (throwing errors).

This didn't impact establishing a ssh sessions but they did broke both **sftp** and **scp**.  What happens with ansible is quite ugly because ansible will try both scp and sftp on each task and throw a warning, slowing down the process a lot and also creating a lot of spam.

I would find much better if ansible would:
- have an option to treat these warnings as errors
- have an option to remember that scp or sftp is broken on that host, and avoid retrying them on each additional task.
- display the error received when attempting scp or sftp because this could have saved me a LOT of time wondering why these were broken. GIving a generic warning message is less useful and easy to be ignored. If the message would also contain the output from the failed command, it would be more useful.
