### ISSUE TITLE
ansible-pull 2.0 lists multiple hosts

### ISSUE THREAD

**Issue by opoplawski** [ansible/ansible#13925] opened 2016-01-15 21:59 UTC
With ansible 1.9.4 my ansible-pull invocation:

```
 /usr/bin/ansible-pull --url ssh://URL.git --key-file /root/.ssh/id_rsa_ansible -i inventory
```

Only outputs local hostname info as expected:

```
 TASK: [common | Configure root] ***********************************************
 ok: [vulcan7.cora.nwra.com]
```

But with 2.0.0.0.2:

```
TASK [setup] *******************************************************************
ok: [lroot.cora.nwra.com]
ok: [barry.cora.nwra.com]
ok: [ibis.cora.nwra.com]
ok: [moa.cora.nwra.com]
.....
```

It doesn't appear to be trying to connect to these hosts, but the output is problematic, and perhaps more is going wrong.

**Comment by sivel** [comment] 2016-01-15 22:08
I just looked over this again, I think the problem, is that although we are building a `limit_opts`, we are not using it in building the `ansible-playbook` command.

In 1.9 we added `limit_opts` to `base_opts`.  Seems we are no longer doing that, which then doesn't apply any limit, unless `-l` is supplied to the `ansible-pull` command.

**Comment by sivel** [comment] 2016-01-15 22:10
Something like this change may resolve the problem:

``` diff
diff --git a/lib/ansible/cli/pull.py b/lib/ansible/cli/pull.py
index 2571717..900e47a 100644
--- a/lib/ansible/cli/pull.py
+++ b/lib/ansible/cli/pull.py
@@ -210,6 +210,8 @@ class PullCLI(CLI):
             cmd += ' -t "%s"' % self.options.tags
         if self.options.subset:
             cmd += ' -l "%s"' % self.options.subset
+        else:
+            cmd += ' -l "%s"' % limit_opts

         os.chdir(self.options.dest)


```

**Comment by bcoca** [comment] 2016-01-18 22:27
looks like dupe of #13681

**Closed as completed by bcoca** 2016-01-18 22:27 UTC
Labels: bug

**Comment by robinro** [comment] 2016-01-19 21:18
It's not a direct dupe of #13681 as in the case here there are even more hosts shown. Nevertheless #13682 would also fix it.
