### ISSUE TITLE
Role without a main tasks file causes an error.

### ISSUE THREAD

**Issue by axos88** [ansible/ansible#8438] opened 2014-08-04 20:08 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.10
##### Environment:

N/A
##### Summary:

I would expect to be able to make empty, meta-roles, which do not have any tasks, only dependencies.
For example, I would expect to be able to make a webserver role, which would depend on the roles apache and ntp, but would not have any tasks of its own. (Another role could then tell what kind of webserver this would be)
This could also serve a grouping role (pun not intended), since ansible displays all run tasks by prefixing the inclusion path, so tasks that are executed in order to make a node into a webserver would be kept together.

This is currently not possible, because an error is returned for the missing / empty task file.
##### Steps To Reproduce:

Create a role without a tasks/main.yml file
##### Expected Results:

To include the dependencies of this playbook, and ignore the missing tasks/main.yml file silently.
##### Actual Results:

An error is returned.

**Comment by mpdehaan** [comment] 2014-08-04 20:33
I'm being somewhat pedantic here, but I want to be through.

Can you please paste the error you are receiving and the command you are running to generate the error?

I agree roles without tasks should be valid, especially if they exist to package modules.

**Comment by jimi-c** [comment] 2014-08-05 20:47
I cannot reproduce this, either on devel or 1.6.10. I've created a role as specified, however no error is generated. If there are no main.yml files present, the following expected error message is shown:

<pre>
ERROR: found role at /root/testing/roles/8438, but cannot find /root/testing/roles/8438/tasks/main or /root/testing/roles/8438/handlers/main or /root/testing/roles/8438/vars/main or /root/testing/roles/8438/defaults/main or /root/testing/roles/8438/meta/main or /root/testing/roles/8438/library
</pre>

If that is the error you're seeing, this is expected, as we require there to be at least one main.yml file for tasks, vars, or meta (or for there to be a library/ directory in the role for custom modules).

**Comment by mpdehaan** [comment] 2014-08-11 12:44
Hi,

I'm closing this one as we haven't seen any activity in some time.

If you have continued problems with this one on a recent version of Ansible (i.e. 1.7), please feel free to open a new ticket.   Thank you!

**Closed as completed by mpdehaan** 2014-08-11 12:44 UTC
Labels: needs_info, P2, bug

**Comment by axos88** [comment] 2014-08-14 17:21
@jimi-c yes, that is the error.

That error is a bug, it is impossible to make a role without a task list (what should I put in the tasks/main.yml, if I do not have any tasks for this role?)

**Comment by axos88** [comment] 2014-08-14 17:21
@mpdehaan  Sorry for the late response, I was a bit overwhelmed.

**Comment by axos88** [comment] 2014-08-14 17:22
I will paste a gist with all the necessary commands shortly

**Comment by jimi-c** [comment] 2014-08-15 02:13
@axos88 a role must have at least one file in tasks/, handlers/, vars/, defaults/ or library/. If you don't have any of those, what files do you have?

**Comment by axos88** [comment] 2014-08-15 05:32
@jimi-c  I have a meta/main.yml, which contains dependencies

```
dependencies:
  - carbon
  - thin
```

**Comment by jimi-c** [comment] 2014-08-15 14:45
This is my setup, which does not reproduce this error:

<pre>
# cat 8438.yml 
- hosts: localhost
  connection: local
  gather_facts: no
  roles:
  - "8438"
  tasks:
  - debug: msg="here we are"
# find roles/8438/ -type f
roles/8438/meta/main.yml
# cat roles/8438/meta/main.yml 
---
dependencies: []
</pre>

This runs as expected, with the only file present being the `meta/main.yml`:

<pre>
# ansible-playbook -vv 8438.yml 
PLAY [localhost] ************************************************************** 
TASK: [debug msg="here we are"] *********************************************** 
ok: [127.0.0.1] => {
    "msg": "here we are"
}
PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=0   
</pre>

**Comment by axos88** [comment] 2014-08-16 12:23
@jimi-c , @mpdehaan I can also not reproduce it any more. Probably it was just a typo.

**Comment by jimi-c** [comment] 2014-08-17 02:11
Great, thanks for following up with us! If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you!
