### ISSUE TITLE
inconsistency with passing vars into roles

### ISSUE THREAD

**Issue by jmurphyau** [ansible/ansible#56760] opened 2019-05-22 04:27 UTC
##### SUMMARY

When passing vars into a role that will be run multiple times (allow_duplicates=true) the results are inconsistent.. The differences is when using "vars" keyword and when not using "vars" keyword.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below    
ansible 2.8.0
  config file = None
  configured module search path = [u'/Users/jamesmurphy/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Feb 22 2019, 21:17:52) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Mac OSX 10.14.4 (18E226)

##### STEPS TO REPRODUCE

```yaml
# roles/test/tasks/main.yml

---
- assert:
    that: test_name is defined

- debug:
    msg: 'test_name={{ test_name }}'

# roles/test/meta/main.yml

---
allow_duplicates: true

# play1.yml

---
  - hosts: localhost

    roles:
      - { role: test, test_name: 'test-1' }
      - { role: test, test_name: 'test-2' }
      - { role: test }

# play2.yml

---
  - hosts: localhost

    roles:
      - { role: test, vars: { test_name: 'test-1' } }
      - { role: test, vars: { test_name: 'test-2' } }
      - { role: test }
```

##### EXPECTED RESULTS

```paste below
> ansible-playbook play1.yml                                                                          
 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [localhost] *********************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [test : assert] *****************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [test : debug] ******************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "test_name=test-1"
}

TASK [test : assert] *****************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [test : debug] ******************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "test_name=test-2"
}

TASK [test : assert] *****************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {
    "assertion": "test_name is defined", 
    "changed": false, 
    "evaluated_to": false, 
    "msg": "Assertion failed"
}

PLAY RECAP ***************************************************************************************************************************************************************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

> ansible-playbook play2.yml                                                                          
 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [localhost] *********************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [test : assert] *****************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [test : debug] ******************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "test_name=test-1"
}

TASK [test : assert] *****************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [test : debug] ******************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "test_name=test-2"
}

TASK [test : assert] *****************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {
    "assertion": "test_name is defined", 
    "changed": false, 
    "evaluated_to": false, 
    "msg": "Assertion failed"
}

PLAY RECAP ***************************************************************************************************************************************************************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

##### ACTUAL RESULTS

```paste below
> ansible-playbook play1.yml                                                                          
 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [localhost] *********************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [test : assert] *****************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [test : debug] ******************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "test_name=test-1"
}

TASK [test : assert] *****************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [test : debug] ******************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "test_name=test-2"
}

TASK [test : assert] *****************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {
    "assertion": "test_name is defined", 
    "changed": false, 
    "evaluated_to": false, 
    "msg": "Assertion failed"
}

PLAY RECAP ***************************************************************************************************************************************************************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

> ansible-playbook play2.yml                                                                          
 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [localhost] *********************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [test : assert] *****************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [test : debug] ******************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "test_name=test-1"
}

TASK [test : assert] *****************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [test : debug] ******************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "test_name=test-2"
}

TASK [test : assert] *****************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [test : debug] ******************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "test_name=test-2"
}

PLAY RECAP ***************************************************************************************************************************************************************************************************************
localhost                  : ok=7    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0  
```

**Comment by sivel** [comment] 2019-05-22 18:40
Duplicate of https://github.com/ansible/ansible/issues/56349

**Closed as completed by sivel** 2019-05-22 18:40 UTC
Labels: support:core, bug, affects_2.8

**Comment by jmurphyau** [comment] 2019-05-23 01:04
I think this is slightly different to that ticket. 

This is about inconsistency between the two methods of including vars.

* Running play1.yml (not using vars key) throws an exception on the third role (test_name not defined)
* Running play2.yml (using vars key) runs the third role but with vars from the second role 

#56349 relates to play2 (using vars key), this ticket is about the inconsistency between the two methods.

**Comment by sivel** [comment] 2019-05-23 13:58
role params and role vars are different things, and are expected to work different.  They are scoped completely different, and as such, that scope causes the difference you are seeing.

**Comment by jmurphyau** [comment] 2019-05-24 01:36
There are so many different ways to pass data into [things] in ansible, I was unaware that these two are meant to be different - so thank you for this clarification :)
