### ISSUE TITLE
bug in unarchive module

### ISSUE THREAD

**Issue by pescobar** [ansible/ansible#11348] opened 2015-06-22 18:45 UTC
Hi

I have found a problem with the unarchive module when the file to uncompress contains "weird" characters. With this playbook the problem can be reproduced:

```

---

- name: reproduce the unarchive bug
  hosts: 127.0.0.1
  connection: local

  tasks:
  - name: Download LMOD
    get_url:
      url=https://github.com/TACC/Lmod/archive/6.0.4.tar.gz
      dest=/tmp/
      mode=0644
      validate_certs=no

  - name: Uncompress LMOD
    unarchive: src=/tmp/Lmod-6.0.4.tar.gz dest=/tmp copy=no mode=0644
```

And this is the output when executing it:

```
root@mgmt05 /tmp # ansible-playbook unarchive-bug.yml

PLAY [reproduce the unarchive bug] ********************************************

GATHERING FACTS ***************************************************************
ok: [127.0.0.1]

TASK: [Download LMOD] *********************************************************
ok: [127.0.0.1]

TASK: [Uncompress LMOD] *******************************************************
failed: [127.0.0.1] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1434998674.55-80965098747038/unarchive", line 1895, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1434998674.55-80965098747038/unarchive", line 289, in main
    res_args['changed'] = module.set_fs_attributes_if_different(file_args, res_args['changed'])
  File "/root/.ansible/tmp/ansible-tmp-1434998674.55-80965098747038/unarchive", line 1090, in set_fs_attributes_if_different
    file_args['path'], file_args['mode'], changed
  File "/root/.ansible/tmp/ansible-tmp-1434998674.55-80965098747038/unarchive", line 928, in set_mode_if_different
    path_stat = os.lstat(path)
OSError: [Errno 2] No such file or directory: '/tmp/Lmod-6.0.4/contrib/Presentations/Keynote_Lmod_SC14-Calcul_Que\\314\\201bec_experience.pdf'


FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/unarchive-bug.retry

127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=1
```

the file can be uncompressed without issues using "tar" directly in the command line or using the ansible shell module to call "tar". This is the file name which triggers the error:

```
Keynote_Lmod_SC14-Calcul_Québec_experience.pdf
```

I have found this issue with ansible 1.9.1

**Comment by mikeputnam** [comment] 2015-07-07 13:18
This same test performed on v1.9.2 works without error.

**Comment by pescobar** [comment] 2015-07-07 13:43
I have just updated my ansible install to 1.9.2 in a ubuntu14.04 machine and I still get the same error (btw, the first report I did was running ansible in a centos7 machine)

```
$ ansible-playbook -c local ansible-test.yml 

PLAY [reproduce the unarchive bug] ******************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [Download LMOD] ********************************************************* 
changed: [127.0.0.1]

TASK: [Uncompress LMOD] ******************************************************* 
failed: [127.0.0.1] => {"failed": true}
msg: Unexpected error when accessing exploded file: [Errno 2] No such file or directory: '/tmp/Lmod-6.0.4/contrib/Presentations/Keynote_Lmod_SC14-Calcul_Que\\314\\201bec_experience.pdf'

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/escobar/ansible-test.retry

127.0.0.1                  : ok=2    changed=1    unreachable=0    failed=1   
```

```
$ ansible-playbook --version
ansible-playbook 1.9.2
  configured module search path = None
```

any clue why it could be that it's working for you but not for me?

**Comment by mikeputnam** [comment] 2015-07-07 13:51
Is it possible that we have differing "locale" and therefore character set handling?

Here is mine:

```
mikeputnam@host ~$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by bcoca** [comment] 2015-07-07 14:12
is it possible you have OS X fork resource files?

**Comment by pescobar** [comment] 2015-07-07 14:14
I think locale is not the issue. These are my locales and I still get the error

```
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=
```

The only difference I noticed was LANGUAGE so I tried to do "export LANGUAGE=en_US" but still no luck, same error....

@bcoca what do you mean by OS X fork resource files? I did the test in a ubuntu14.04 and a centos7

**Comment by bcoca** [comment] 2015-07-07 14:15
in the tarball, was it created on an OS X machine?

**Comment by pescobar** [comment] 2015-07-07 14:28
I know the developer has a OS X machine but I am not sure where he created the file. In case it's helpful, this is the output of "tar -tf Lmod-6.0.4.tar.gz"

https://gist.github.com/anonymous/c7317f23a15a03ed31f5

edit: I just realized that the file which causes problem appears two times when listing the files in the tarball

```
Lmod-6.0.4/contrib/Presentations/Keynote_Lmod_SC14-Calcul_Québec_experience.pdf
Lmod-6.0.4/contrib/Presentations/Keynote_Lmod_SC14-Calcul_Québec_experience.pdf
```

maybe related?   :?

**Comment by bcoca** [comment] 2015-07-07 14:39
no resource forks there, need new theory

**Comment by pescobar** [comment] 2015-07-07 14:58
when uncompressing the tarball the same file appears two times :?

```
root@kb-raphael /tmp/Lmod-6.0.4/contrib/Presentations # md5sum Keynote_Lmod_SC14-Calcul_Qu*
6387aac8f59162df95d2d38273cb3ec5  Keynote_Lmod_SC14-Calcul_Québec_experience.pdf
6387aac8f59162df95d2d38273cb3ec5  Keynote_Lmod_SC14-Calcul_Québec_experience.pdf
```

**Comment by bcoca** [comment] 2015-07-07 15:23
hidden char?

**Comment by pescobar** [comment] 2015-07-07 15:33
```
escobar@kb-raphael /tmp/Lmod-6.0.4/contrib/Presentations $ ls Keynote_Lmod_SC14-Calcul_Qu*|cat -v
Keynote_Lmod_SC14-Calcul_QueM-LM-^Abec_experience.pdf
Keynote_Lmod_SC14-Calcul_QuM-CM-)bec_experience.pdf
```

does it gives any clue?

**Comment by jimi-c** [comment] 2015-07-21 02:47
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
# ansible-playbook -vv 11348.yml 
Using /etc/ansible/ansible.cfg as config file
1 plays in 11348.yml
PLAY [reproduce the unarchive bug] **********************************************
TASK [Download LMOD] ************************************************************
changed: [localhost] => {"changed": true, "checksum": "5f4783a177f1a35d399b007e13c94a4a3b4bab8f", "dest": "/tmp/11348/Lmod-6.0.4.tar.gz", "gid": 0, "group": "root", "md5sum": "bb716eb842f68e548f99b1d3295aa286", "mode": "0644", "msg": "OK (unknown bytes)", "owner": "root", "secontext": "unconfined_u:object_r:user_tmp_t:s0", "sha256sum": "", "size": 7904217, "src": "/tmp/tmpkPw3__", "state": "file", "uid": 0, "url": "https://github.com/TACC/Lmod/archive/6.0.4.tar.gz"}
TASK [Uncompress LMOD] **********************************************************
...
PLAY RECAP **********************************************************************
localhost                  : ok=2    changed=2    unreachable=0    failed=0   
# ll /tmp/11348/Lmod-6.0.4/contrib/Presentations/
total 6164
-rw-r--r--. 1 root root 4275316 Jun 19 09:28 2011-10-27-Modules_PBS_Intro.pdf
-rw-r--r--. 1 root root  919469 Jun 19 09:28 Keynote_Lmod_SC14-Calcul_Québec_experience.pdf
-rw-r--r--. 1 root root  919469 Jun 19 09:28 Keynote_Lmod_SC14-Calcul_Québec_experience.pdf
-rw-r--r--. 1 root root  191678 Jun 19 09:28 Muthing_IWR_lmod.pdf
</pre>

Per our normal policy, we close bug report issues when we see the issue has been corrected in the devel branch, so we will close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-07-21 02:47 UTC
Labels: P2, m:unarchive, bug

**Comment by odyssey4me** [comment] 2016-03-04 21:02
We recently encountered this with Ansible 1.9.4-1 and discovered that the issue came down to the archive containing file/folder names with unicode characters, and the host doing the unarchive couldn't deal with them. The host was Ubuntu 14.04 and the issue was resolved by installing the package 'language-pack-en' on the host.

**Comment by ghost** [comment] 2016-04-29 01:42
Are we sure this is really fixed? I get the same error here on a fresh Raspbian on a raspberry pi. This is my playbook (I use the same test archive):

```
---
- name: break unarchive
  hosts: all
  tasks:
    - unarchive: src=https://github.com/TACC/Lmod/archive/6.0.4.tar.gz copy=no dest=/tmp mode=0644
```

And the run:

```
$ ansible-playbook -i local_inventory test.yml

PLAY [break unarchive] *********************************************************

TASK [setup] *******************************************************************
ok: [stb.local]

TASK [unarchive] ***************************************************************
fatal: [stb.local]: FAILED! => {"changed": false, "failed": true, "msg": "Unexpected error when accessing exploded file: [Errno 2] No such file or directory: '/tmp/Lmod-6.0.4/contrib/Presentations/Keynote_Lmod_SC14-Calcul_Que\\\\314\\\\201bec_experience.pdf'"}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @test.retry

PLAY RECAP *********************************************************************
stb.local                  : ok=1    changed=0    unreachable=0    failed=1
```

```
$ ansible-playbook --version
ansible-playbook 2.0.2.0
  config file =
  configured module search path = Default w/o overrides
```

I'm suspecting that this has something to do with the locale, but should ansible really be locale-sensible? If I ssh on the rpi and do `tar -zxf`, it works fine.

I've tried with Raspbian's default locale (`en_GB.UTF-8`) and with a `C` default locale (using `update-locale LANG=C`). Same result.

I've also disabled `AcceptEnv` in my sshd_config. Same result.

**Comment by ghost** [comment] 2016-04-29 20:35
In fact, I think I have a very simple way to always reproduce the issue:

```
$ cat foo.yml
- hosts: localhost
  tasks:
    - unarchive: src=foo.tar copy=no dest=/tmp

$ cd /tmp
$ mkdir foo
$ touch foo/é.txt
$ tar -cf foo.tar foo
$ LANG=C ansible-playbook -c local foo.yml
[WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [unarchive] ***************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Unexpected error when accessing exploded file: [Errno 2] No such file or directory: '/tmp/foo/\\\\303\\\\251.txt'"}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @foo.retry

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1
```

Can anyone confirm?

**Comment by ghost** [comment] 2016-04-29 20:57
Also, for the record, I've just tried on a fresh `devel` checkout, with the same results.

**Comment by pescobar** [comment] 2016-05-11 09:59
I can confirm I hit the same issue in a centos7 machine running ansible `1.9.1` using the test playbook in previous comment https://github.com/ansible/ansible/issues/11348#issuecomment-215874147

```
TASK: [unarchive src=foo.tar copy=no dest=/tmp] ******************************* 
failed: [localhost] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1462960662.75-43340223611111/unarchive", line 1895, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1462960662.75-43340223611111/unarchive", line 289, in main
    res_args['changed'] = module.set_fs_attributes_if_different(file_args, res_args['changed'])
  File "/root/.ansible/tmp/ansible-tmp-1462960662.75-43340223611111/unarchive", line 1090, in set_fs_attributes_if_different
    file_args['path'], file_args['mode'], changed
  File "/root/.ansible/tmp/ansible-tmp-1462960662.75-43340223611111/unarchive", line 928, in set_mode_if_different
    path_stat = os.lstat(path)
OSError: [Errno 2] No such file or directory: '/tmp/foo/\\303\\251.txt'


FATAL: all hosts have already failed -- aborting
```

**Comment by Oliboy50** [comment] 2016-07-27 14:27
could we reopen this until it's really fixed?

**Comment by abadger** [comment] 2016-08-04 23:35
just confirmed that the test that was proposed in comment https://github.com/ansible/ansible/issues/11348#issuecomment-215874147 is currently passing in devel and stable-2.1

```
$ LANG=C ansible-playbook -c local foo.yml                                              (16:30:43)
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [unarchive] ***************************************************************
ok: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0

$ ansible --version                                                                     (16:33:58)
ansible 2.1.1.0 (stable-2.1 baaa1d3013) last updated 2016/08/04 16:32:51 (GMT -700)

$ ansible --version                                             (16:33:25)
ansible 2.2.0 (devel bced8715cd) last updated 2016/08/04 16:18:19 (GMT -700)
```

Please open a new bug report with a reproducer and we'll be happy to look into what could be happening.

**Comment by AndydeCleyre** [comment] 2016-10-26 19:42
I'm still experiencing this bug, and I don't even see any fancy characters. Here's an easy way to reproduce with docker:

``` bash
$ docker run -it alpine:3.4 sh
/ # apk update
/ # apk add ansible
/ # cd /etc
/etc # mkdir outdir
/etc # tar -cf fstab.tar fstab
/etc # ansible localhost -m unarchive -a "src=fstab.tar dest=outdir"
```

This yields:

```
localhost | FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "Unexpected error when accessing exploded file: [Errno 2] No such file or directory: 'outdir/fstab'"
}
```

**Comment by AndydeCleyre** [comment] 2016-10-26 19:46
Prepending the ansible command with `LANG=C` does not change the results.

**Comment by AndydeCleyre** [comment] 2016-10-26 20:02
I see the comments in here about not reading comments on closed tickets, so I've created a new one, as requested, in ansible-modules-core: [5394](https://github.com/ansible/ansible-modules-core/issues/5394)
