### ISSUE TITLE
When statement errors when variable is used alone

### ISSUE THREAD

**Issue by josephtate** [ansible/ansible#4104] opened 2013-09-13 15:12 UTC
Given the variable
central_log_server set to either "some-host-name-10" or "off". I believe the dashes in the hostname are important because of the error message.

And the task:
- Central logging
  copy: ...
  when: central_log_server
- Turn off central logging
  file: state=absent...
  when: not central_log_server

I get a traceback:
TASK: [Central logging] ********************************
fatal: [test01.crunch.io] => Traceback (most recent call last):
  File "/home/jtate/.virtualenvs/pow/local/lib/python2.7/site-packages/ansible/runner/**init**.py", line 382, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/home/jtate/.virtualenvs/pow/local/lib/python2.7/site-packages/ansible/runner/__init__.py", line 471, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/home/jtate/.virtualenvs/pow/local/lib/python2.7/site-packages/ansible/runner/__init__.py", line 555, in _executor_internal_inner
    if not utils.check_conditional(cond, self.basedir, inject, fail_on_undefined=self.error_on_undefined_vars):
  File "/home/jtate/.virtualenvs/pow/local/lib/python2.7/site-packages/ansible/utils/__init__.py", line 172, in check_conditional
    conditional = template.template(basedir, presented, inject)
  File "/home/jtate/.virtualenvs/pow/local/lib/python2.7/site-packages/ansible/utils/template.py", line 310, in template
    varname = template_from_string(basedir, varname, vars, fail_on_undefined)
  File "/home/jtate/.virtualenvs/pow/local/lib/python2.7/site-packages/ansible/utils/template.py", line 512, in template_from_string
    res = jinja2.utils.concat(t.root_render_func(t.new_context(_jinja2_vars(basedir, vars, t.globals, fail_on_undefined), shared=True)))
  File "<template>", line 9, in root
TypeError: unsupported operand type(s) for -: 'StrictUndefined' and 'int'

If I change the when: block to "not not central_log_server" or "central_log_server is defined and central_log_server" it works.

Is the variable name being replaced with the value before being fed to jinja2 so that it interprets "some" "host" and 10 as tokens with minus operators between them?

**Comment by jimi-c** [comment] 2013-09-13 16:09
What version of ansible are you running?

**Comment by josephtate** [comment] 2013-09-13 16:14
I just pulled HEAD on the devel branch.

**Comment by jimi-c** [comment] 2013-09-13 16:37
Ok, I can reproduce this and will look into it.

**Comment by jimi-c** [comment] 2013-09-13 18:43
So this appears to have been caused by 62b39d3d. I'm testing a work-around right now.

**Comment by jimi-c** [comment] 2013-09-13 18:54
The above patch has been merged into devel, if you could re-pull and test to confirm it fixes your issue I'd appreciate it.

**Closed as completed** 2013-09-13 18:54 UTC
Labels: bug

**Comment by josephtate** [comment] 2013-09-13 19:53
Yes, seems to have fixed it.
