### ISSUE TITLE
ansible ERROR when following "Introduction to ad-hoc commands" in User Guide

### ISSUE THREAD

**Issue by clashleyca** [ansible/ansible#72724] opened 2020-11-24 19:43 UTC
##### SUMMARY
When following the Users Guide for "Introduction to ad-hoc commands, the following command produces an error message
https://docs.ansible.com/ansible/latest/user_guide/intro_adhoc.html
```
ansible raleigh -m ansible.builtin.shell -a 'echo $TERM'
# ERROR! this task 'ansible.builtin.shell' has extra params, which is only allowed in the following modules: shell, win_shell, include_vars, add_host, raw, include_role, meta, set_fact, include, import_tasks, script, import_role, include_tasks, group_by, command, win_command
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible.builtin.shell

##### ANSIBLE VERSION

```paste below
ansible 2.9.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ssgroot/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

```

##### CONFIGURATION

```paste below
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False

```

##### OS / ENVIRONMENT

Target #1 
#157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Target #2 
#124-Ubuntu SMP Thu Oct 15 13:03:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE

Add two targets to /etc/ansible/hosts
[raleigh]
FQDN#1
FQDN#2
run ansible command

```yaml
ansible raleigh -m ansible.builtin.shell -a 'echo $TERM'
```

##### EXPECTED RESULTS

Display of TERM information for each host

##### ACTUAL RESULTS

Got error message

```ansible 2.9.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ssgroot/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Parsed /etc/ansible/hosts inventory source with ini plugin
ERROR! this task 'ansible.builtin.shell' has extra params, which is only allowed in the following modules: shell, win_shell, include_vars, add_host, raw, include_role, meta, set_fact, include, import_tasks, script, import_role, include_tasks, group_by, 

```

**Comment by clashleyca** [comment] 2020-11-24 19:44
May relate to https://github.com/ansible/ansible/issues/71817
If so, the documentation should be updated

**Comment by mkrizek** [comment] 2020-11-27 08:11
Duplicate of #71817.
Fixed in https://github.com/ansible/ansible/pull/71824 and https://github.com/ansible/ansible/pull/72471.
Backport for 2.10 https://github.com/ansible/ansible/pull/72457.
Backport for 2.9 https://github.com/ansible/ansible/pull/72458.

If you have further questions please stop by IRC or the mailing list:
* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Closed as completed by mkrizek** 2020-11-27 08:11 UTC
Labels: support:core, bug, affects_2.9
