### ISSUE TITLE
sudo command results in query hanging over SSH

### ISSUE THREAD

**Issue by bala-v** [ansible/ansible#12386] opened 2015-09-15 22:51 UTC
On some machines, the ansible shell command hangs if sudo privilege is necessary to execute the commands, e.g.

test-mac:playbooks $ ansible all -s -m shell -a 'tail /var/log/secure'
SSH password: 
....
....

Nothing, it hangs till Ctrl-Z is pressed. Any ideas to debug?.

**Comment by jimi-c** [comment] 2015-09-16 14:39
Hi @bala-v , can you provide more information about your setup, such as the version of ansible, example playbooks to reproduce the issue, and any relevant sudoers configuration?

Thanks!

**Comment by bala-v** [comment] 2015-09-16 20:53
Hi James, 

The machine doesn't have /etc/sudoers file because sudoers is centrally managed across the corporate machines. There is a default /etc/sudo.conf that looks like below:-

<pre>
*******
#
# Default /etc/sudo.conf file
#
# Format:
#   Plugin plugin_name plugin_path plugin_options ...
#   Path askpass /path/to/askpass
#   Path noexec /path/to/sudo_noexec.so
#   Debug sudo /var/log/sudo_debug all@warn
#   Set disable_coredump true
#
# Sudo plugins:
#
# The plugin_path is relative to ${prefix}/libexec unless fully qualified.
# The plugin_name corresponds to a global symbol in the plugin
#   that contains the plugin interface structure.
# The plugin_options are optional.
#
# The sudoers plugin is used by default if no Plugin lines are present.
Plugin sudoers_policy sudoers.so
Plugin sudoers_io sudoers.so
#
# Sudo askpass:
#
# An askpass helper program may be specified to provide a graphical
# password prompt for "sudo -A" support.  Sudo does not ship with its
# own passpass program but can use the OpenSSH askpass.
#
# Use the OpenSSH askpass
#Path askpass /usr/X11R6/bin/ssh-askpass
#
# Use the Gnome OpenSSH askpass
#Path askpass /usr/libexec/openssh/gnome-ssh-askpass
#
# Sudo noexec:
#
# Path to a shared library containing dummy versions of the execv(),
# execve() and fexecve() library functions that just return an error.
# This is used to implement the "noexec" functionality on systems that
# support C<LD_PRELOAD> or its equivalent.
# The compiled-in value is usually sufficient and should only be changed
# if you rename or move the sudo_noexec.so file.
#
#Path noexec /usr/libexec/sudo_noexec.so
#
# Core dumps:
#
# By default, sudo disables core dumps while it is executing (they
# are re-enabled for the command that is run).
# To aid in debugging sudo problems, you may wish to enable core
# dumps by setting "disable_coredump" to false.
#
# Set to false here so as not to interfere with /proc/sys/fs/suid_dumpable
#
*******
</pre>

The command that works in vanilla ssh is below

$ssh -t <user>@<hostname> 'sudo cat /var/log/secure'

The same from ansible hangs

$ansible <hostname> -s -m shell -a 'cat /var/log/secure'

hangs and has to be exited using Ctrl-Z. 

the ansible version is 

ansible 1.9.2
  configured module search path = None

**Comment by jimi-c** [comment] 2015-09-17 14:55
So does your sudo command require a password?

**Comment by bala-v** [comment] 2015-09-17 16:38
Yes, sudo command requires password

**Comment by bala-v** [comment] 2015-09-17 16:39
basically, the same works in plain ssh mode - $ssh -t @ 'sudo cat /var/log/secure' but doesn't when using -s option in ansible.

**Comment by jimi-c** [comment] 2015-09-17 16:57
Ok, what happens if you also specify the `--ask-sudo-pass`  (or newer, the `--ask-become-pass`) option?

**Comment by bala-v** [comment] 2015-09-17 21:52
Thanks. The below works
1. test-mac:books $ ansible all -m shell -s --ask-sudo-pass -a 'tail /var/log/secure'
   SSH password: 
   SUDO password[defaults to SSH password]: 
   <host> | success | rc=0 >>

and
1. test-mac:books $ ansible all -m shell --ask-become-pass -a 'sudo tail /var/log/secure'
   SSH password: 
   SUDO password[defaults to SSH password]: 
   <host> | success | rc=0 >>

but the below does not work:-
1. test-mac:books $ ansible all -m shell --ask-become-pass -a 'tail /var/log/secure'
   SSH password: 
   SUDO password[defaults to SSH password]: 
   <host> | FAILED | rc=1 >>
   tail: cannot open `/var/log/secure' for reading: Permission denied

**Comment by jimi-c** [comment] 2015-09-18 00:42
That is because you've removed the `-s` option on the last one, so you're rightly getting a permission denied error. Since all of these behaviors look normal and what I'd expect, I'm going to go ahead and close this issue.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-09-18 00:42 UTC
Labels: needs_info, bug
