### ISSUE TITLE
Handler skipped when same role is called multiple times using "when"

### ISSUE THREAD

**Issue by lberruti** [ansible/ansible#20978] opened 2017-02-02 16:10 UTC
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
ansible

##### ANSIBLE VERSION
```
ansible-playbook 2.3.0 (detached HEAD ba39d1158c) last updated 2017/02/01 12:45:19 (GMT +200)
  config file =
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Handler skipped when same role is called multiple times using "when"

##### STEPS TO REPRODUCE
```
ansible-playbook test.yml -e run_first=false -e run_second=true
```

```yaml
---
- hosts: localhost
  connection: local
  roles:
    - { role: a, params: aaa, when: run_first }
    - { role: a, params: bbb, when: run_second }
```

##### EXPECTED RESULTS
```
PLAY [localhost] *********************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************
ok: [localhost]

TASK [a : command] *******************************************************************************************************************************
skipping: [localhost]

TASK [a : command] *******************************************************************************************************************************
changed: [localhost]

RUNNING HANDLER [a : exec_me] ********************************************************************************************************************
ok: [localhost] => {
    "msg": "exec_me!"
}

PLAY RECAP ***************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0
```

##### ACTUAL RESULTS
```
PLAY [localhost] *********************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************
ok: [localhost]

TASK [a : command] *******************************************************************************************************************************
skipping: [localhost]

TASK [a : command] *******************************************************************************************************************************
changed: [localhost]

RUNNING HANDLER [a : exec_me] ********************************************************************************************************************
skipping: [localhost]

PLAY RECAP ***************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0
```

**Comment by lberruti** [comment] 2017-02-02 23:30
I forgot to describe the "a" role:
```yaml
---
# roles/a/tasks/main.yml
- command: echo
  notify: exec_me
```
```yaml
---
# roles/a/handlers/main.yml
- name: exec_me
  debug: msg='exec_me!'
```

**Comment by imjoshholloway** [comment] 2017-02-08 16:15
This also happens on version 2.2.x (I've tested 2.2.1 and 2.2.0).

What's interesting is that this issue also occurs if you have a role as a dependency of multiple roles and then use `when:` to optionally include those roles. 

Below, both role b & c include role a as a dependency:

`ansible-playbook test.yml -e run_first=true run_second=false`

Playbook:
```
---
- hosts: all
  roles:
    - { role: b, when: run_first }
    - { role: c, when: run_second }
```

```
PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [a : command] *************************************************************
changed: [localhost]

TASK [b : command] *************************************************************
changed: [localhost]

TASK [c : command] *************************************************************
skipping: [localhost]

RUNNING HANDLER [a : exec_me] **************************************************
ok: [localhost] => {
    "msg": "exec_me!"
}

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=2    unreachable=0    failed=0
```

This works as expected.

However, when the conditional forces the skipping of the first role:

`ansible-playbook test.yml -e 'run_first=false run_second=true'`

```
PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [a : command] *************************************************************
skipping: [localhost]

TASK [b : command] *************************************************************
skipping: [localhost]

TASK [c : command] *************************************************************
changed: [localhost]

RUNNING HANDLER [a : exec_me] **************************************************
skipping: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0
```


I've created the following repo to demonstrate this: https://github.com/imjoshholloway/ansible-handlers-issue-20978

**Comment by andrianaivo** [comment] 2017-06-19 15:15
+1
I have the same problem/behaviour  (also with older ansible versions: 2.0, 2.1, 2.2). It would be really great if that can be fixed! 

I have many use cases of "Multi-Steps" roles that I must call multiple times within a single playbook, but only executes the steps corresponding to the current conditions.

**Comment by guzzijason** [comment] 2018-03-05 21:39
Appears to affect 2.4 as well.

**Comment by guzzijason** [comment] 2018-03-05 21:50
BTW, I've worked around this for now doing something like this (based on the original example here):
```
---
- hosts: localhost
  connection: local
  vars:
    myparam: "{{ 'aaa' if run_first else 'bbb' }}"
  roles:
    - { role: a, params: "{{ myparam }}" }
```
This moves the conditional into the definition of the var, and then the role only gets called once. Not ideal, but it may work fine for some situations.

**Comment by daMupfel** [comment] 2018-05-28 12:40
Any feedback about this? I also seem to be affected by the same issue (ansible 2.5).

**Comment by bottlelee** [comment] 2018-06-29 05:31
Still the same on ansible 2.5.5

**Comment by mkrizek** [comment] 2018-06-29 10:06
Duplicate of https://github.com/ansible/ansible/issues/37512

**Closed as completed** 2018-06-29 10:06 UTC
Labels: affects_2.3, c:playbook/handler*, c:playbook/role/*, support:core, bug
