### ISSUE TITLE
Async docs example incorrect on 2.5 and 2.6

### ISSUE THREAD

**Issue by acozine** [ansible/ansible#50262] opened 2018-12-21 21:33 UTC
##### SUMMARY
Toure Dunnon reported that the example code in the docs for running multiple asynchronous tasks while limiting the amount of tasks running concurrently does not work on Ansible 2.5 or Ansible 2.6. 

Current:
```
#####################
# main.yml
#####################
- name: Run items asynchronously in batch of two items
  vars:
    sleep_durations:
      - 1
      - 2
      - 3
      - 4
      - 5
    durations: "{{ item }}"
  include_tasks: execute_batch.yml
  loop:
    - "{{ sleep_durations | batch(2) | list }}"
```

Correction/Replacement for last 3 lines of above example:

```
tasks:
    - include_tasks: execute_batch.yml
      with_items:
      - "{{ sleep_durations | batch(2) | list }}"
```

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
https://docs.ansible.com/ansible/2.6/user_guide/playbooks_async.html

##### ANSIBLE VERSION
2.5
2.6

##### CONFIGURATION
Unknown or N/A

##### OS / ENVIRONMENT
Unknown or N/A

**Comment by acozine** [comment] 2018-12-21 21:34
See https://docs.google.com/document/d/15TzLG-gnYU7hRMjmbk5GloPiCjKFRpIjqzEel-Mqlso/edit.

**Comment by sivel** [comment] 2019-01-02 16:11
The problem is that someone mis-converted `with_items` to `loop`.

Because `with_items` does implicit flattening it worked as `with_items`.

Using `loop`, it should instead be:

```
  loop: "{{ sleep_durations | batch(2) | list }}"
```

**Comment by anis016** [comment] 2019-02-03 19:17
@acozine, I created a pull request for this task: https://github.com/ansible/ansible/pull/51672

**Comment by gundalow** [comment] 2019-02-11 15:49
Fix is to backport https://github.com/ansible/ansible/pull/46178/files

**Comment by Akasurde** [comment] 2020-08-13 07:35
resolved via https://github.com/ansible/ansible/pull/46178

**Closed as completed by Akasurde** 2020-08-13 07:35 UTC
Labels: support:core, affects_2.5, has_pr, docs
