### ISSUE TITLE
setup module gets json parse errors some of the time w/ 1.4

### ISSUE THREAD

**Issue by omgjlk** [ansible/ansible#5082] opened 2013-11-27 17:28 UTC
I'm seeing this hit random hosts at random times, but with 1.4 it will almost always happen if I have more than a hand full of hosts trying to run setup (never an issue with 1.3.x)

Happens with ssh and ssh with ControlPersist. Does not occur with paramiko

```
10.13.135.91 | FAILED => Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 394, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 485, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 678, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/action_plugins/normal.py", line 54, in run
    return self.runner._execute_module(conn, tmp, module_name, module_args, inject=inject, complex_args=complex_args)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 369, in _execute_module
    data = utils.parse_json(res['stdout'])
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/__init__.py", line 306, in parse_json
    tokens = shlex.split(data)
  File "/usr/lib/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "/usr/lib/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/usr/lib/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/usr/lib/python2.7/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation
```

When this happens, the output appears to /always/ be cut off in the same spot, in the middle of facter_sshdsakey, even if the key is different on different hosts. I really don't know what's going on here.

**Comment by jctanner** [comment] 2013-11-27 18:29
@j2sol what is the value of facter_sshdsakey in the "facter --json" output for the problematic host(s) ?

Also, how many is a "handful"? I'm unable to reproduce 21 hosts and 10 forks.

**Comment by omgjlk** [comment] 2013-11-27 18:51
```
    "facter_sshrsakey": "AAAAB3NzaC1yc2EAAAADAQABAAABAQCz/WxLJJY/tZk4Q28+MxkKmmhjbLuLW+ptzoslv/U0flzbqsmCKC5GGJLrERp3vAHAkUdKPBdjaNagH4pT61yxsS6UIycMDUA0FIpb5uSaAPCdoAymtkgRnKm2GMn+kp3HM7CqRbpg7Vn1ONg2ckoGM1rlsH6WZsgE+6rjEAPloYYr03IX9fYV2VcJPvdUKl6uLB7tLQPtqJhiZ+L1uRR8Yj4BJog0WD5iuWrqyrFO2S0573vzEkPDY4JloRCTw2l4ZTJSeRqx/+zCCMNav/kvP6raaXpZnoND1/Lwhsme45aBH5k6u8Rji5UCinaqtYLAsC+lKJPc8G5S1v2s1Juh",  
```

in one example.

I was seeing it when using as few as 2 nodes and 1 fork, but as I play around I might be discovering that it may be environmental, networking issues between my test host and the remote hosts, that the ssh connection mode is less tolerant of.

**Comment by jctanner** [comment] 2013-11-27 18:54
@j2sol are you able to trace down the environment issues with ssh or do you need some help debugging what [partial] data is returned to ansible from the setup module on the remote hosts?

**Comment by omgjlk** [comment] 2013-11-27 18:57
I may have misspoke. I do have network issues preventing accelerated mode from working against some of my fleet from my test host, but even hosts where accelerated mode is functional, the setup module is still having issues over ssh. Not as easily pinpointed as environmental :/

**Comment by jctanner** [comment] 2013-11-27 19:08
@j2sol Let's check the outut from the setup module directly ...

Call ansible or ansible-playbook with -vvvv:

```
ANSIBLE_KEEP_REMOTE_FILES=1 ansible -vvvv -c ssh -i inventory <HOSTNAME> -m setup
```

Find the remote path of the temporary script:

```
<localhost> PUT /tmp/tmpbTlg9f TO /root/.ansible/tmp/ansible-1385579234.17-201621510532988/setup
```

Run the script by hand:

```
python /root/.ansible/tmp/ansible-1385579234.17-201621510532988/setup
```

Does that show any errors?

**Comment by omgjlk** [comment] 2013-11-27 19:15
No errors. I don't think it's anything specific to the output, as in my set of 18~ hosts it's not the same ones that fail. Different ones fail in different runs.

**Comment by jctanner** [comment] 2013-11-27 22:28
@j2sol can you try adding some extra debugging?

```
diff --git a/lib/ansible/runner/__init__.py b/lib/ansible/runner/__init__.py
index 75866fa..1ec79c7 100644
--- a/lib/ansible/runner/__init__.py
+++ b/lib/ansible/runner/__init__.py
@@ -366,6 +366,7 @@ class Runner(object):
                 cmd2 = "rm -rf %s >/dev/null 2>&1" % tmp
                 self._low_level_exec_command(conn, cmd2, tmp, sudoable=False)

+        open("/tmp/awx.log", "a").write("%s\n" % res)
         data = utils.parse_json(res['stdout'])
         if 'parsed' in data and data['parsed'] == False:
             data['msg'] += res['stderr']
```

Once the error occurs, it would be interesting to see what was written to /tmp/awx.log for the job.

**Comment by jctanner** [comment] 2013-11-28 00:19
@j2sol I was able to inject your raw text data from pastebing into runner and reproduce the traceback ....

```
localhost | FAILED => Traceback (most recent call last):
  File "/home/jtanner/ansible/lib/ansible/runner/__init__.py", line 400, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/home/jtanner/ansible/lib/ansible/runner/__init__.py", line 491, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/home/jtanner/ansible/lib/ansible/runner/__init__.py", line 691, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/home/jtanner/ansible/lib/ansible/runner/action_plugins/normal.py", line 54, in run
    return self.runner._execute_module(conn, tmp, module_name, module_args, inject=inject, complex_args=complex_args)
  File "/home/jtanner/ansible/lib/ansible/runner/__init__.py", line 372, in _execute_module
    data = utils.parse_json(tmpdata['stdout'])
  File "/home/jtanner/ansible/lib/ansible/utils/__init__.py", line 306, in parse_json
    tokens = shlex.split(data)
  File "/usr/lib/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "/usr/lib/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/usr/lib/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/usr/lib/python2.7/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation
```

So I went back to the raw data and noticed this ...

```
(Epdb) print tmpdata['stderr']
OpenSSH_6.0p1 Debian-4, OpenSSL 1.0.1e 11 Feb 2013
debug1: Reading configuration data /root/.ssh/config
debug1: /root/.ssh/config line 1: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug2: fd 3 setting O_NONBLOCK
debug2: mux_client_hello_exchange: master version 4
debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
debug3: mux_client_request_session: entering
debug3: mux_client_request_alive: entering
debug3: mux_client_request_alive: done pid = 20034
debug3: mux_client_request_session: session request sent
debug1: mux_client_request_session: master session id: 2
debug3: mux_client_read_packet: read header failed: Broken pipe
debug2: Received exit status from master 0
Shared connection to X.X.X.X closed.
```

The stdout ends with this ...

```
"facter_sshrsakey": "AAAAB3NzaC1yc2E.....iZ+L1uRR8Yj'
```

There is definitely no closing quotation and there appears to be some sort of ssh connection/timeout problem.

**Comment by mpdehaan** [comment] 2013-11-30 13:06
If it's a ssh timeout, it's probably not something under our control then?  (Which explains why we probably haven't gotten more error reports about this).

Regardless, it would be nice if we caught this error though, explicitly the "No closing quotation" one and put out a more human readable error message.

**Comment by omgjlk** [comment] 2013-12-02 22:07
I'm having a hard time accepting that it would be an ssh timeout issue, as the same scenario, same hosts, same control host on version 1.3.4 does not exhibit this problem. It only seems to happen once upgraded to 1.4. I suppose some effort could be put in to git bisect this to identify when the problem started. Not sure when I can get to that, but I'll try.

**Comment by sivel** [comment] 2013-12-02 22:20
Another idea is stracing or using pdb.  This would give insight to what is happening on the connection side of things.

Something like `strace -f -s1024 ansible foo -m setup`

**Comment by jctanner** [comment] 2013-12-03 13:32
@j2sol what is the operating system version for your client machine and for the nodes?

**Comment by jctanner** [comment] 2013-12-03 13:38
Debian 6.0.3 on the clients per the facter outputs.

**Comment by jctanner** [comment] 2013-12-03 21:11
@j2sol I spent a while this morning trying every possible way I could think of to reproduce the issue, including testing against debian wheezy (older than 6.0.3). The only problem I hit was exceeding MaxSessions on one server. 

If you could run bisect and figure out which commit changed the behavior, I'll have to try again to reproduce with that knowledge.

**Comment by omgjlk** [comment] 2013-12-03 21:28
c2d1607490f381e189ba05b9bcde5d8d2e48b7a8 is when the bisect shows problems starting. Could just be a side effect of adding more data to the return, but maybe not.

**Comment by jctanner** [comment] 2013-12-03 23:07
@j2sol if you comment out line 149 in library/system/setup do the errors go away?

**Comment by jctanner** [comment] 2013-12-03 23:16
I also created a debug branch with this code to test the theory that lots of facts and large amount of data might force the behavior ...

```
diff --git a/lib/ansible/runner/connection_plugins/ssh.py b/lib/ansible/runner/connection_plugins/ssh.py
index 68c6f17..8f5c468 100644
--- a/lib/ansible/runner/connection_plugins/ssh.py
+++ b/lib/ansible/runner/connection_plugins/ssh.py
@@ -251,6 +251,14 @@ class Connection(object):
         if p.returncode != 0 and controlpersisterror:
             raise errors.AnsibleError('using -c ssh on certain older ssh versions may not support ControlPersist, s

+
+        #if stderr is not None and stderr is not "":
+        if len(stderr) > 0:
+            open("/tmp/awx-error.log", "a").write("stdout=%s stderr=%s\n" % (len(stdout), stderr))
+        else:
+            open("/tmp/awx-error.log", "a").write("stdout=%s\n" % len(stdout))
+
+
         return (p.returncode, '', stdout, stderr)

     def put_file(self, in_path, out_path):
diff --git a/library/system/setup b/library/system/setup
index 7d69d22..454258a 100755
--- a/library/system/setup
+++ b/library/system/setup
@@ -149,6 +149,29 @@ class Facts(object):
         self.get_user_facts()
         self.get_local_facts()
         self.get_env_facts()
+        self.get_random_facts()
+
+    def get_random_facts(self):
+
+        """
+        ascii_letters
+        ascii_uppercase
+        ascii_lowercase
+        whitespace
+        punctuation
+        octdigits
+        letters
+        digits
+        """
+
+        import string
+        import random
+        for x in range(0, 1000):
+            thisname = "random_"
+            thisname += ''.join(random.choice(string.ascii_lowercase) for x in range(10))
+            thisval = ''.join(random.choice(string.ascii_lowercase) for x in range(100))
+            self.facts[thisname] = thisval + string.whitespace
+

     def populate(self):
         return self.facts
```

No errors occurred.

**Comment by jctanner** [comment] 2013-12-04 03:12
@j2sol two tests ...

1) if you comment out line 149 in library/system/setup do the errors go away?

2) If you change 9000 to 999999 on lines 231 and 236 in ssh.py, does the error go away?

https://github.com/ansible/ansible/blob/devel/lib/ansible/runner/connection_plugins/ssh.py#L231-L236

**Comment by omgjlk** [comment] 2013-12-04 19:56
I've attempted a few things today.

1) I commented out self.get_env_facts() in library/system/setup
  This caused the problem to go away.

2) I uncommented self.get_env_facts() and instead commented out a number of OTHER lines (in an effort to reduce the size of the response)
  This also caused the problem to go away, confirming my hunch that it has to do with the size of the response rather than the content of the response.

3) I changed the two 9000 values to 999999 (after reverting the other file to unmodified)
  This had no impact upon the problem.

**Comment by jctanner** [comment] 2013-12-04 19:58
@j2sol for #2 you commented out lines inside the get_env_facts function?

**Comment by omgjlk** [comment] 2013-12-04 21:26
No, sorry, still in library/system/setup I commented out other fact types, but allowed ansible to run self.get_env_facts(). So the content of get_env_facts would be in the response and the contents of others would not. This reduced the size of the response while still having env_facts() in the response.

**Comment by jctanner** [comment] 2013-12-04 21:27
@j2sol ah, ok. I'll keep looking for other possible tests.

**Comment by blandonnimrat** [comment] 2013-12-05 07:42
I am not sure it helps, but I can (somewhat) reliably reproduce this error.  I have a standard set of post-boot playbooks that are run and I see this failure at the exact same place about on 1 out of a set of four or five instances.

Using Centos 6.4 with a custom compiled openssh 6.3.  Let me know if I can assist in troubleshooting.

**Comment by jimi-c** [comment] 2013-12-05 14:04
@blandonnimrat could you also share your playbook and any other details about the system? Does it occur when using the stock openssh shipped with centos 6.4?

**Comment by jctanner** [comment] 2013-12-05 14:39
@blandonnimrat what changes did you make to openssh 6.3 ?

**Comment by blandonnimrat** [comment] 2013-12-05 19:42
@jimi-c @jctanner 

no changes to openssh 6.3 (6.3p1 to be exact) - totally standard compile options.  Just using this version for outbound ssh to get ControlPersist because CentOS/RHEL have some fail in not having this in their standard package.

I unfortunatly can't share the specifics on the playbooks.  I have about eight playbooks executed in a row (one big meta playbook with a series of includes), the playbook above where I see the consistent failure is doing some of our secret sauce.

confirmed that I don't see the issue using paramiko.  I am going to work on reproducing now with:
- stock centos ssh (and no control persist)
- new ssh w/o control persist
- compile ssh 6.4 and run w/ control persist

more info when I have it.  Thanks everyone for being so awesome!  I lub me some ansible.

**Comment by omgjlk** [comment] 2013-12-05 19:45
@blandonnimrat Can you reproduce it with just calling the setup module across the host set? I'm able to repro that which makes sharing details a lot easier.

**Comment by blandonnimrat** [comment] 2013-12-05 21:56
@j2sol so far I can't seem to reproduce outside of my complicated/proprietary workflow.  I've tried taking the playbook that ends up with the error, and the playbook before it and executing that in a short sequence

so it looks like this
- hosts: all
  gather_facts: no
  tasks:
  - name: setup
    action: setup
- include: $ENV(ANSIBLE_HOME)/playbooks/clients.yml
- include: $ENV(ANSIBLE_HOME)/playbooks/postfix.yml

I can't reproduce with 
- openssh 6.3p1 w/ controlpersist
- openssh 6.3p1 w/o controlpersist
- openssh 6.4p1 w/ controlpersist
- openssh 6.4p1 w/o controlpersist

To be clear my partial reproduction is also only effective about 20 to 25% of the time (when the playbooks are executed right after an instance boots), and even on those instances where I see the failure if I rerun the failed playbook it works the second time.  So while I can reproduce it over and over, I can't get a clean test case of it (yet)

**Comment by blandonnimrat** [comment] 2013-12-06 01:53
@jimi-c @jctanner @j2sol 

Hi everyone, so now I can't reproduce the issue.  Not very useful I know, but I thought I would report back.

Currently running a fresh compile of openssh 6.4p1 with control persist enabled.  No reproductions in around 30 instance launches this afternoon.

This sequence of playbooks gets exercised a lot around here, so I'll report back if I see something again.

sorry.

**Comment by omgjlk** [comment] 2013-12-09 19:53
My bisect attempts were bad as ansible was using the system python libraries not the one from the checkout. I've re-ran my bisect, while always adding a large amount of filler data to the facts. The new culprit appears to be:
389602b8dda3f9bb8cf189745041e69c77a0fa29

**Comment by jctanner** [comment] 2013-12-09 21:45
@j2sol does this also mean that this wasn't actually tested?

2) If you change 9000 to 999999 on lines 231 and 236 in ssh.py, does the error go away?

**Comment by omgjlk** [comment] 2013-12-09 21:56
That is correct @jctanner , that wasn't tested.

I just completed that test and that does appear to make the problem go away.

**Comment by jctanner** [comment] 2013-12-10 04:49
@j2sol I've gotten fairly good at reproducing it on my side with forks > 1 and the random facts set to a stringsize of 10000. I have to adjust the stdout read size up to 9999999 bytes to stop the errors from occuring. 

All in all, it really seems like we aren't reading enough data from the stdout filehandle before we drop the handle from observation. 

If you don't mind, validate if this patch corrects the error on your side:

```
diff --git a/lib/ansible/runner/connection_plugins/ssh.py b/lib/ansible/runner/connection_plugins/ssh.py
index 68c6f17..8d7005a 100644
--- a/lib/ansible/runner/connection_plugins/ssh.py
+++ b/lib/ansible/runner/connection_plugins/ssh.py
@@ -232,6 +232,11 @@ class Connection(object):
                 stdout += dat
                 if dat == '':
                     rpipes.remove(p.stdout)
+                elif p.poll() == None:
+                    while dat != '':
+                        dat = os.read(p.stdout.fileno(), 9000)
+                        stdout += dat
+                    rpipes.remove(p.stdout)
             if p.stderr in rfd:
                 dat = os.read(p.stderr.fileno(), 9000)
                 stderr += dat
```

The initial read size should be 9000, so you should "git reset --hard" before applying the patch.

FYI this is not a final patch even if it works. I want to understand the issue and the code better before I push in a final fix.

Let me know the results.

**Comment by jctanner** [comment] 2013-12-10 19:15
"no go for your latest patch it's executing but getting no closing quotation"

**Comment by omgjlk** [comment] 2013-12-10 19:42
So an interesting data point I've discovered:
Use of -vvvv can change the profile of the issue.

-vvvv will tell ssh to be in very verbose mode, which will cause lots of data to go to stderr -- before stdout is ready for reading. This causes select.select() to return almost immediately, with just p.stderr in the list as it's the only FD ready for reading. This means we'll attempt to drain p.stderr but never check on p.stdout because it wasn't in the select list.

Worse, if we attempt to fully drain stderr we can reach a lock state. stderr will have the initial debug output. stdout will have the actual command output -- and until it's read from the fd the process locks. Once stdout has been read there is more stderr to read -- at which point both fds are fully drained and the process can continue.

https://gist.github.com/j2sol/7896349 was an attempt at draining the FD that led to the discovery of the lock condition. If I remove -vvvv things get a lot less locky, but I think for better results testing should be done with -vvvv to ensure the code properly handles intermixed stderr and out.

I do believe that a crux of this problem is how select.select() works, in that it'll return as soon as /any/ of the fd's in the list are available for reading. stderr is immediately available.

**Comment by jctanner** [comment] 2013-12-11 01:20
[11:28:57] <jlk>         so...
[11:29:04] <jlk>         select.select() is only returning stderr
[11:29:15] <jlk>         code attempts to read stderr to the end
[11:29:17] <jlk>         but hangs.
[11:29:24] <jlk>         this is because there is stuff on stdout to read
[11:29:30] <jlk>         once it's read from stdout, there is more on stderr to read
[11:29:41] <jlk>         after which it can be read() continuously and returns ''
[11:33:23] <jlk>         I think it's is because select.select() will return as soon as one object in the list is ready to read from -- stderr is ready immediately, stdout is not ready at first, so only one gets into the return of select.select()
[11:33:30] <jlk>         so the block never knows to read from stdout
[11:33:41] <jlk>         this may have something to do with running with -vvvv -- extra ssh verbosity
[11:37:14] <jlk>         Yeah, taking out -vvvv definitely changes the profile of the issue.
[12:59:40] <jlk>         jtanner|food: I have more data -- ControlPersist is screwing things up. Attempts to read on p.stdout or p.stderr will often fail -- even though those should be unique FDs per connection because they're just pipes.

[13:18:44] <jlk>         I think I'm getting hit by https://bugzilla.mindrot.org/show_bug.cgi?id=1988
[13:23:30] <jlk>         I can't think of a way around this. It appears that if the foreground ssh process doesn't have anything for stderr, read() reverts to reading the master's stderr which is locked until the timeout.

**Comment by blandonnimrat** [comment] 2013-12-11 05:44
@jctanner  @j2sol 

my quick chime in is the above bugzilla.mindrot.org link would match my experience that I stopped being able to reproduce the issue with a move from openssh 6.3 to 6.4

**Comment by omgjlk** [comment] 2013-12-11 17:25
Testing with openssh 6.4 has been better, and I think I have a solution here -- or at least something that appears to work consistently in my environment:

https://gist.github.com/j2sol/7916239

The main take away here is to not break when p.poll() is not None because of the way that select.select works. 

The first run through select.select() may only return stderr ready for reading. If we were to read it and then do a check for empty rpipes (which would not be empty) OR p.poll() being non-none (which it could be by then) the break would happen and stdout would be left on the fd.

The other scenario -- the one that causes the unclosed quote, is if we go through select.select() and we do get stdout in the ready for reading -- we read from it (9000 bytes), but that's not all that is there. Again we'd get to the p.poll() check and it would be indeed not none, but we would have left some of stdout on the FD and thus the json blob would be malformed.

My patch adjusts the logic so that rpipes has to be empty and p.poll() has to indicate a finished process before the loop is exited.

(updated comment to have a public gist)

**Comment by jctanner** [comment] 2013-12-11 18:28
https://gist.github.com/sivel/435d1f678cbb119fc4ea

**Comment by zsolt-erl** [comment] 2013-12-11 22:29
For what it's worth:

I ran into this today and was able to reproduce it regularly.
I made the changes in ssh.py per the above gist and it seems like it resolved the problem.

**Comment by jctanner** [comment] 2013-12-12 00:37
```
<jlk> jtanner: yeah so fun times. My stuff is still broken if the task is causing the ControlPersist socket to be created, rather than re-used.
<jlk> when re-used, it works. when created, no go, lock on stderr.read()
<jlk> so it's back to the drawing board for a bit.
```

**Comment by omgjlk** [comment] 2013-12-12 01:14
New gist that appears to work the following scenarios:

-vv with the ControlPersist being created for the first time
-vv with ControlPersist socket already created
-vvvv with the ControlPersist being created for the first time
-vvvv with ControlPersist already created
-vv with ControlPersist already created by a -vvvv run
-vvvv with ControlPersist already created by a -vv run.

https://gist.github.com/j2sol/7921645

**Comment by jctanner** [comment] 2013-12-12 02:11
An easier way to reproduce:

```
# on a remote host
mkdir -p /etc/ansible/facts.d
echo "[foo]" >> /etc/ansible/facts.d/bigone.fact
echo -n "a=" >> /etc/ansible/facts.d/bigone.fact
for i in $(seq 100000); do echo -n "x" >> bigone.fact ; done;
```

**Comment by jctanner** [comment] 2013-12-12 15:02
Resolved by https://github.com/ansible/ansible/pull/5254

**Closed as completed by jctanner** 2013-12-12 15:02 UTC
Labels: needs_info, bug
