### ISSUE TITLE
Bug: --limit=all excludes localhost

### ISSUE THREAD

**Issue by dlamotte** [ansible/ansible#14194] opened 2016-01-28 22:15 UTC
##### Ansible Version: 2.0.0.2

```
ansible 2.0.0.2
  config file = /Users/dlamotte/sandbox/repo/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

```
[defaults]
inventory = hosts
remote_tmp = /tmp/.ansible
timeout = 120

[privilege_escalation]
become_ask_pass = True

[ssh_connection]
control_path = %(directory)s/%%h-%%r
```
##### Steps To Reproduce:

When using vagrant, I was surprised that a play that works fine not under vagrant.

```

---
- hosts: localhost
  ...
```

By not working, I mean:

```
PLAY ***************************************************************************
skipping: no hosts matched
```

Turns out `--limit=all` excludes localhost!  A workaround is either `--limit=` or `--limit=all,localhost`.  The only reason the former is interesting is in the case of vagrant (`ansible.limit = ""` amounts to `--limit=`).

The caveat with vagrant is that vagrant always uses `--limit=hostname` until you configure it.
##### Expected Results:

I expect `localhost` to at least be available with `--limit=all`.
##### Actual Results:

`--limit=all` does not include plays for `localhost`

**Update: the inventory does NOT contain `localhost`**

**Comment by bcoca** [comment] 2016-01-28 23:10
is it in your inventory?
all hosts in the inventory are included in the 'all' group and i cannot reproduce this using ansible directly.

**Comment by dlamotte** [comment] 2016-01-28 23:35
@bcoca Good point.  Sorry.  You are correct that `localhost` is not in the inventory (I'll update the issue).  However, that doesn't seem to stop ansible when there is no `--limit` being used.

**Comment by bcoca** [comment] 2016-01-28 23:39
It does not, if ansible detects an empty inventory or a missing localhost it tries to provide it's own, so this should still work. I can now reproduce with inventory w/o localhost.

**Comment by bcoca** [comment] 2016-01-30 00:08
so we went over it and realized that if you do not define localhost in your inventory, we SHOULD NOT add it to the 'all' group as it would 'surprise' people targeting 'all' when they did not define a localhost.

I'm going to close this as it works as expected.

**Closed as completed by bcoca** 2016-01-30 00:08 UTC
Labels: bug

**Comment by dlamotte** [comment] 2016-01-30 23:27
Great!  Thanks for the confirmation and clarification!

**Comment by jesselang** [comment] 2016-02-01 14:45
@bcoca Would you accept a PR to clarify this in the documentation?

**Comment by bcoca** [comment] 2016-02-01 14:48
yes
