### ISSUE TITLE
FATAL: no hosts matched or all hosts have already failed -- aborting

### ISSUE THREAD

**Issue by beafuture** [ansible/ansible#11987] opened 2015-08-18 02:25 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

1.9.2
##### Ansible Configuration:

force_handlers = True
##### Environment:

All my server is Centos 5
##### Summary:

Hi all,
I have enabled “force_handlers = True” in  ansible.cfg file,but when my playbook has failed to perform a task, handler task will all fail.
##### Expected Results:

After playbook task fails, the task before the fails can be performed notified tasks properly 
##### Actual Results:

TASK: [init | add monitor] **********************************\* 
fatal: [10.11.9.146] => One or more undefined variables: 'sid' is undefined
fatal: [10.11.9.134] => One or more undefined variables: 'sid' is undefined

NOTIFIED: [init | restart iptables] ******************************************\* 
FATAL: no hosts matched or all hosts have already failed -- aborting

NOTIFIED: [init | apply sysctl] **********************************************\* 
FATAL: no hosts matched or all hosts have already failed -- aborting

NOTIFIED: [init | restart crond] *********************************************\* 
FATAL: no hosts matched or all hosts have already failed -- aborting

NOTIFIED: [init | restart nrpe] *************************************\* 
FATAL: no hosts matched or all hosts have already failed -- aborting

**Comment by bcoca** [comment] 2015-08-18 02:32
# Can You Help Us Out?

Thanks for filing a ticket! I am the friendly GitHub Ansibot.

It looks like you might not have filled out the issue description based on our standard issue template.  You might not have known about that, and that's ok too, we'll tell you how to do it.

We have a standard template because Ansible is a really busy project and it helps to have some standard information in each ticket, and GitHub doesn't yet provide a standard facility to do this like some other bug trackers.  We hope you understand as this is really valuable to us!.

Solving this is simple: please copy the contents of this [template](https://raw.githubusercontent.com/ansible/ansible/devel/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket.  That's it!

# If You Had A Question To Ask Instead

If you happened to have a "how do I do this in Ansible" type of question, that's probably more of a user-list question than a bug report, and you should probably ask this question on the project mailing list instead.

However, if you think you have a bug, the report is the way to go!  We definitely want all the bugs filed :)  Just trying to help!

# About Priority Tags

Since you're here, we'll also share some useful information at this time.

In general tickets will be assigned a priority between P1 (highest) and P5, and then worked in priority order. We may also have some follow up questions along the way, so keeping up with follow up comments via GitHub notifications is a good idea.

Due to large interest in Ansible, humans may not comment on your ticket immediately.

# Mailing Lists

If you have concerns or questions, you're welcome to stop by the ansible-project or ansible-development mailing lists, as appropriate.  Here are the links:
- https://groups.google.com/forum/#!forum/ansible-project - for discussion of bugs and how-to type questions
- https://groups.google.com/forum/#!forum/ansible-devel - for discussion on how to implement a code change, or feature brainstorming among developers

Thanks again for the interest in Ansible!

**Comment by mscherer** [comment] 2015-08-18 20:14
We need the playbook to be able to reproduce ( or rather, at least, fail in the same way ). And the doc (http://docs.ansible.com/ansible/playbooks_error_handling.html ) point that some failure may prevent the handlers from being run, so I suspect this would be one of those case ( but given your description, it doesn't look like, so maybe doc should be clarified, if that's not of course a bug to be fixed in ansible).

**Comment by beafuture** [comment] 2015-08-19 02:21
The following playbook can reproduce this problem, I put all the tasks in the same playbook：

```
- name: test
  hosts: test
  user: root
  tasks:
    - name: task1
      shell: echo ok
      notify: handler task
    - name: error task
      shell: echo {{sid}}
  handlers:
    - name: handler task
      debug: msg="this is a debug task"
```

The ‘error task’ is used an undefined variable, so failed, the ‘handler task’ task failed due to its failure.The reason why sid no default value, because practically impossible to have a default value. If I just specify a value, when the user forgets to set the variable values in he's playbook , will lead to hidden error.

In fact, the task in above playbook is in a role,when I prepare for the new situation a new playbook, it will miss out this variable.After an error occurred during the execution, I must manually perform all the handler task.

**Comment by bcoca** [comment] 2015-08-20 03:20
so the 'recoverable' errors would be the task failing on execution, here it fails on definition which is not a recoverable error. If I change the task to actually fail on execution all works:

```
    - name: error task
      shell: /bin/false
```

**Comment by bcoca** [comment] 2015-08-20 03:22
the output

```
PLAY [test] ********************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [task1] *******************************************************************
changed: [localhost]

TASK [error task] **************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/bin/false", "delta": "0:00:00.003243", "end": "2015-08-19 23:22:58.183886", "failed": true, "rc": 1, "start": "2015-08-19 23:22:58.180643", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}

RUNNING HANDLER [handler task] *************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "this is a debug task"
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=1   
```

closing this ticket as it seems it was a misunderstanding of the feature.

**Closed as completed by bcoca** 2015-08-20 03:22 UTC
Labels: needs_info
