### ISSUE TITLE
vmware_guest broke in 2.4.0.0

### ISSUE THREAD

**Issue by jffz** [ansible/ansible#32042] opened 2017-10-23 14:54 UTC
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_PIPELINING(/etc/ansible/ansible.cfg) = True
CACHE_PLUGIN(/etc/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/etc/ansible/ansible.cfg) = /etc/ansible/facts
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 5
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = implicit
DEFAULT_GATHER_SUBSET(/etc/ansible/ansible.cfg) = all
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/hosts']
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_MANAGED_STR(/etc/ansible/ansible.cfg) = Ansible managed: {file} on {host}
DEFAULT_REMOTE_PORT(/etc/ansible/ansible.cfg) = 22
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles']
DEFAULT_SQUASH_ACTIONS(/etc/ansible/ansible.cfg) = ['apk', 'apt', 'dnf', 'package', 'pacman', 'pkgng', 'yum', 'zypper']
DEFAULT_SUDO_USER(/etc/ansible/ansible.cfg) = root
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 15
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = True
RETRY_FILES_SAVE_PATH(/etc/ansible/ansible.cfg) = /root/.ansible-retry

##### OS / ENVIRONMENT
CentOs 7.4

##### SUMMARY
Using vmware_guests on ansible 2.4.0.0 seems to be broken, fixed by downgrading to 2.3.0.0

##### STEPS TO REPRODUCE
Use vmware_guest with ansible 2.4.0.0

```yaml
- name: "Create VM"
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        datacenter: "{{ datacenter }}"
        cluster: "{{ cluster }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: present
        guest_id: centos64Guest
        name: "{{ item }}"
        networks:
        - name: "{{ network }}"
          vlan: "{{ vlan }}"
          type: static
          ip: "{{ ip }}"
          netmask: "255.255.255.0"
          gateway: "{{ ip.split('.')[0:3] | join('.') }}.1"
          dns_servers: "172.20.11.100"
          device_type: vmxnet3
        disk:
        - size_gb: "{{ disk }}"
          type: thin
          autoselect_datastore: True
          #datastore: "{{ datastore }}"
        hardware:
          memory_mb: "{{ memory }}"
          num_cpus: "{{ cpucount }}"
          scsi: paravirtual
        validate_certs: False
      delegate_to: localhost
      with_items: "{{ inventory_hostname }}"
	  
```

##### EXPECTED RESULTS
Make the module works

##### ACTUAL RESULTS
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'name'
failed: [testvm -> localhost] (item=testvm) => {"changed": false, "failed": true, "item": "testvm", "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_WVZUZg/ansible_module_vmware_guest.py\", line 1503, in <module>\n    main()\n  File \"/tmp/ansible_WVZUZg/ansible_module_vmware_guest.py\", line 1494, in main\n    result = pyv.deploy_vm()\n  File \"/tmp/ansible_WVZUZg/ansible_module_vmware_guest.py\", line 1189, in deploy_vm\n    dcpath = compile_folder_path_for_object(datacenter)\n  File \"/tmp/ansible_WVZUZg/ansible_modlib.zip/ansible/module_utils/vmware.py\", line 237, in compile_folder_path_for_object\nAttributeError: 'NoneType' object has no attribute 'name'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}

```

**Comment by aaronk1** [comment] 2017-10-23 15:50
> The error was: AttributeError: 'NoneType' object has no attribute 'name'

If you do a debug on the variable called "name", what do you see?

Example:  http://docs.ansible.com/ansible/latest/debug_module.html#examples

**Comment by jffz** [comment] 2017-10-23 16:05
@aaronk1 I don't have a "{{ name }}" var anywhere in my playboooks / tasks / hosts, i will debug it tomorrow anyway but i would have the same issue using ansible 2.3.0.0 if it would be related to one of my var, i guess

**Comment by alikins** [comment] 2017-10-23 16:54
(reformatted error pasted here for easier reference)

```
An exception occurred during task execution.
To see the full traceback, use -vvv. 
The error was:
   AttributeError: 'NoneType' object has no attribute 'name'
```
``` python
Traceback (most recent call last):
  File "/tmp/ansible_WVZUZg/ansible_module_vmware_guest.py", line 1503, in <module>
    main()
  File "/tmp/ansible_WVZUZg/ansible_module_vmware_guest.py", line 1494, in main
    result = pyv.deploy_vm()
  File "/tmp/ansible_WVZUZg/ansible_module_vmware_guest.py", line 1189, in deploy_vm
    dcpath = compile_folder_path_for_object(datacenter)
  File "/tmp/ansible_WVZUZg/ansible_modlib.zip/ansible/module_utils/vmware.py", line 237, in compile_folder_path_for_object
AttributeError: 'NoneType' object has no attribute 'name'

```

**Comment by jffz** [comment] 2017-10-24 10:42
Just double checked and as expected, there is no var under the name "{{ name }}".
The value of the 'name:' attribute is well set and is "{{ inventory_hostname }}".

**Comment by Akasurde** [comment] 2017-10-24 14:41
@jffz Could you please try above PR and let me know if it works for you?

**Comment by jffz** [comment] 2017-10-25 10:29
@Akasurde Seems better but now complain that resource_pool is not referenced (not mandatory).

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: UnboundLocalError: local variable 'resource_pool' referenced before assignment
fatal: [testvm -> localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_bC7ROc/ansible_module_vmware_guest.py\", line 1507, in <module>\n    main()\n  File \"/tmp/ansible_bC7ROc/ansible_module_vmware_guest.py\", line 1498, in main\n    result = pyv.deploy_vm()\n  File \"/tmp/ansible_bC7ROc/ansible_module_vmware_guest.py\", line 1296, in deploy_vm\n    task = destfolder.CreateVM_Task(config=self.configspec, pool=resource_pool)\nUnboundLocalError: local variable 'resource_pool' referenced before assignment\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
```

**Comment by Akasurde** [comment] 2017-10-25 11:14
@jffz Sorry but there is [another PR](https://github.com/ansible/ansible/pull/32026) open for that as well.

**Comment by jffz** [comment] 2017-10-25 12:27
Just triied the new PR, seems to fix the issue but leads to #30818

**Comment by Akasurde** [comment] 2017-10-25 17:48
@jffz Funny thing, there is [another PR](https://github.com/ansible/ansible/pull/31542) open. :)

**Comment by Akasurde** [comment] 2017-11-13 11:53
@jffz Could you please try with latest 2.4 or 2.5 branch? The issue is resolved.

**Comment by Akasurde** [comment] 2017-11-13 11:53
needs_info

**Comment by Akasurde** [comment] 2017-11-21 10:49
Closing this issue as PR #32671 is merged. If issue persists, please feel free to re-open.

**Closed as completed by Akasurde** 2017-11-21 10:49 UTC
Labels: needs_info, vmware, affects_2.4, support:core, bug
