### ISSUE TITLE
ansible-vault does not accept stdin as promised with single vaulted variables

### ISSUE THREAD

**Issue by gregmark** [ansible/ansible#24700] opened 2017-05-16 21:41 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible-vault, single vaulted variable

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.6.9 (unknown, Sep  1 2016, 23:34:39) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
```

##### CONFIGURATION
- ANSIBLE_VAULT_PASSWORD_FILE=<location>
- ansible.cfg
```
[defaults]
inventory      = ./ec2.py
library        = ~/git/ansible-run/lib/
forks          = 50
sudo_user      = root
transport      = smart
gathering = smart
roles_path    = ~/git/ansible-run/roles:~/git/ansible-run/roles_galaxy:./roles:./roles_galaxy
host_key_checking = False
hash_behaviour = replace
ansible_managed = Ansible managed: {file} on {host}
system_warnings = False
deprecation_warnings = False
command_warnings = True
nocows = 1
retry_files_enabled = False
[ssh_connection]
ssh_args = -o ForwardAgent=yes
pipelining = False
```

##### OS / ENVIRONMENT
control box
- Amazon Linux AMI release 2014.03

##### SUMMARY
Being able to encrypt passwords and the like on the command line by echoing to ansible-vault's stdin and receiving the encrypted data to stdout. Doesn't work, although this feature is documented here: http://docs.ansible.com/ansible/playbooks_vault.html#single-encrypted-variable

##### STEPS TO REPRODUCE

```yaml
echo flibbityFloo | ansible-vault encrypt
```

##### EXPECTED RESULTS
```
$ANSIBLE_VAULT;1.1;AES256
soOnsoON....
```
to stdout.

##### ACTUAL RESULTS
```
ERROR! [Errno 2] No such file or directory: '/home/gchavez/git/ansible-run/-'
```
Ah, dash. Frequently used to direct a command to use standard input. Here however, the dash means a file named "-" or the dash character.

**Comment by sivel** [comment] 2017-05-16 21:49
Closing as a duplicate of the already resolved https://github.com/ansible/ansible/pull/23583

This fix will be included in a future 2.3.1 release

**Closed as completed by sivel** 2017-05-16 21:49 UTC
Labels: affects_2.3, c:cli/vault, bug
