### ISSUE TITLE
to_bool filter functionality extension

### ISSUE THREAD

**Issue by anryko** [ansible/ansible#21914] opened 2017-02-24 18:51 UTC
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

plugins/filter/core.py

##### ANSIBLE VERSION

```
ansible 2.3.0 (main 3b1500d033) last updated 2017/02/23 09:41:19 (GMT +000)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/opt/ansible/ansible/library']
```

##### SUMMARY

Ansible bool filter behavior was surprising to me. After investigating YAML standard I understand the motivation behind this implementation. However, IMHO it would be useful to step over YAML limitations and extend ```|bool``` functionality.

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  tasks:
    - set_fact:
        z_dict_empty: "{{ {}|bool }}"
        z_dict_not_empty: "{{ {'key': 1}|bool }}"
        z_str_empty: "{{ ''|bool }}"
        z_str_not_empty: "{{ 'aaa'|bool }}"
        z_str_eq_yes: "{{ 'yes'|bool }}"
        z_int_0: "{{ 0|bool }}"
        z_int_1: "{{ 1|bool }}"
        z_int_negative: "{{ -7|bool }}"
    - debug:
        var: hostvars[inventory_hostname]
```

##### EXPECTED RESULTS

```bash
$ ansible-playbook plays/bool-test.yml | grep "\"z_"
        "z_dict_empty": false,
        "z_dict_not_empty": true,
        "z_int_0": false,
        "z_int_1": true,
        "z_int_negative": true,
        "z_str_empty": false,
        "z_str_eq_yes": true,
        "z_str_not_empty": false
```

##### ACTUAL RESULTS

```bash
$ ansible-playbook plays/bool-test.yml | grep "\"z_"
        "z_dict_empty": false,
        "z_dict_not_empty": false,
        "z_int_0": false,
        "z_int_1": true,
        "z_int_negative": false,
        "z_str_empty": false,
        "z_str_eq_yes": true,
        "z_str_not_empty": false
```
I acknowledge that this is a strange mix between Python variable truthiness and YAML... but I think this is better then what we have now.

**Comment by bcoca** [comment] 2017-02-24 22:18
something like `|to_bool('python')` to force 'python truthiness' ?

**Comment by anryko** [comment] 2017-02-26 01:36
Theoretically this is a breaking change. However, I really doubt that somebody is checking ```|bool``` of not empty dict and relies ```false``` :).
Custom filter is an option too, but ```|to_bool('python')``` looks too verbose for my taste. In case of custom filter I would prefer ```|pybool``` or ```|boolpy``` or ```|boolean```.

**Comment by sivel** [comment] 2017-02-26 03:22
I prefer the arg to the existing `bool` filter.  It could be either `bool('python')` or my preference would be `bool(python=True|False)` with the default being False

**Comment by anryko** [comment] 2017-02-27 11:37
```bool(python=True|False)``` looks good. I can prepare a PR some evening this week if that's OK with you.

**Comment by bcoca** [comment] 2017-02-27 14:00
just to expand it in case 'other rules' want to be applied `bool(as='python')`

**Comment by anryko** [comment] 2017-02-27 20:08
Other rules could be applied by ```bool(other=True|False)```. I'm really not sure about this one... I myself would prefer ```bool(python=True|False)``` to ```bool(as='python')```. However, looking at other filters in this "family", like ```get_hash```, ```get_encrypted_password``` or ```comment```,  their style is closer to ```bool(as='python')``` (or to keep it even more consistent with ```comment``` - ```bool(style='python')```). I think it is important to preserve consistency in details. For this reason  ```bool(style='python')``` I would consider a better choice. Ideas?

**Comment by sivel** [comment] 2017-02-27 20:13
I suppose, I can see it both ways.  jinja2 typically is more explicit, and I prefer more explicit rules where something is true/false.  Our filters seems to be less explicit, and match the value of an argument.  But to support a wider variety, without having to make it complicated and ensure that only 1 truthiness selection is made, using `as` or `style` seems like a good option.

**Comment by bcoca** [comment] 2017-02-27 21:36
im ok with name change, i just don't want `style='alternative_facts'`

**Comment by anryko** [comment] 2017-02-27 22:37
Prepared PR, please review.

**Comment by catalyst-joe-guo** [comment] 2018-08-21 02:56
Get the same trouble with `bool` filter,  after looking at the implement code, I would say, it's too far away from what I expected.

**Comment by rolandjohann** [comment] 2018-11-30 20:37
Same here. Discovered a horible bug caused by strange behavior of jinja filter operator precedence. Till today I had the dangerous assumption that the filters gets applied the bash pipe style.
Already filled out an issue and discovered this one.






##### SUMMARY
Expression evaluation of string comparison and passing to `bool` filter results in negation of bool value and therefore wrong result.
This comes from jinja2 itself, caused by operator precedence. https://github.com/pallets/jinja/issues/882

I suggest that we slightly change the bool filter at ansible to also check for valid 'False' values and either crash on invalid or at least print warnings.

##### ISSUE TYPE
- (Usability) enhancement

##### COMPONENT NAME

bool filter:
https://github.com/ansible/ansible/blob/4096d74245bae5f0828b4129c8a44154235195bf/lib/ansible/plugins/filter/core.py#L89-L97

##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0
  config file = None
  configured module search path = [u'/Users/xxxxxx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Jul 23 2018, 21:27:06) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]

```

##### CONFIGURATION

no ansible.cfg

##### STEPS TO REPRODUCE



```yaml
---
- hosts: localhost
  vars:
    foo: "foo"
    bar: "{{ foo == 'foo' }}"
  tasks:
    - debug: var=foo

    - debug:
        msg:
          expression: "foo != 'foo' | bool"
          result: "{{ foo != 'foo' | bool }}"
          expected: False
    - debug:
        msg:
          expression: "foo == 'foo' | bool"
          result: "{{ foo == 'foo' | bool }}"
          expected: True
```



##### EXPECTED RESULTS

```
TASK [debug] ***********************************************************************************************************************************************************************************************
ok: [localhost] => {
    "foo": "foo"
}

TASK [debug] ***********************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": {
        "expected": false,
        "expression": "foo != 'foo' | bool",
        "result": false
    }
}

TASK [debug] ***********************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": {
        "expected": true,
        "expression": "foo == 'foo' | bool",
        "result": true
    }
}

PLAY RECAP *************************************************************************************************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0    skipped=0
```

##### ACTUAL RESULTS

```
TASK [debug] ***********************************************************************************************************************************************************************************************
ok: [localhost] => {
    "foo": "foo"
}

TASK [debug] ***********************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": {
        "expected": false,
        "expression": "foo != 'foo' | bool",
        "result": true
    }
}

TASK [debug] ***********************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": {
        "expected": true,
        "expression": "foo == 'foo' | bool",
        "result": false
    }
}

PLAY RECAP *************************************************************************************************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0    skipped=0
```

**Comment by Yajo** [comment] 2019-06-19 12:02
Since Ansible 2.8, it started telling:

<pre><font color="#75507B">[DEPRECATION WARNING]: evaluating variable_name as a bare variable, this behaviour will go away and you might need to add |bool to the expression in the </font>
<font color="#75507B">future. Also see CONDITIONAL_BARE_VARS configuration toggle.. This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting </font>
<font color="#75507B">deprecation_warnings=False in ansible.cfg.</font>
</pre>

So I started adding `|bool` everywhere, thinking that it was the same as before, but it wasn't. If the variable is a dict, the old behavior would mean "continue if the dict isn't empty"; but now with `|bool` means "continue if it contains a truthy English-readable string". Quite different!

Maybe you could add a test instead of a filter. It would be quite readable to write:

```yaml
- name: whatever task
  when: some_variable is truthy and some_other_variable is falsy
```

**Comment by sivel** [comment] 2020-08-31 15:51
This issue has been resolved by https://github.com/ansible/ansible/pull/62602

**Closed as completed by sivel** 2020-08-31 15:51 UTC
Labels: affects_2.3, c:plugins/filter, support:core, has_pr, feature
