### ISSUE TITLE
Template creation failing when using sudo_user

### ISSUE THREAD

**Issue by genofedanzo** [ansible/ansible#12509] opened 2015-09-24 15:35 UTC
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible 2.0.0 (devel 5d3d9cfe0d9dd3943245c65b92fd91d33e446f2b)
##### Summary:

We have a task that writes a template file to a remote server as a sudo_user and it has broken in 2.0 because of permission problems.
##### Steps To Reproduce:

```
- name: Test Template
  tasks:
    - name: Test Template | Write File
      template: src=test.txt.j2 dest=/tmp/test.txt force=yes
      sudo_user: "testuser"
```
##### Expected Results:

File will be written to /tmp/ directory.
##### Actual Results:

`fatal: [123.123.123]: FAILED! => {"changed": false, "failed": true, "msg": "Source /tmp/ansible-tmp-1443108503.34-115637427635543/source not readable"}`

The source file was created as the initial ansible user with only read permissions for the user.  The error kicks out after it sudos to the sudo_user and tries to copy the staged file to the final destination.

**Comment by jimi-c** [comment] 2015-09-30 18:34
Hi @genofedanzo, I just tried reproducing this and was not able to (tried both non-root to non-root and root to non-root sudo's). Can you provide anymore context on your setup or further steps to reproduce including any relevant sudoers configuration or user setup?

Thanks!

**Comment by jimi-c** [comment] 2015-10-12 15:47
Hi @genofedanzo, since there has been no follow-up on this, we're going to go ahead and close it as we were not able to reproduce it.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-10-12 15:47 UTC
Labels: needs_info, P2, bug
