### ISSUE TITLE
Setup module doesn't work properly with YAML output

### ISSUE THREAD

**Issue by den-is** [ansible/ansible#50500] opened 2019-01-03 15:57 UTC
##### SUMMARY
Setup module returns "nothing" when setting is `stdout_callback = yaml`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

setup

##### ANSIBLE VERSION

```
ansible 2.6.11
  config file = /Users/den/.ansible.cfg
  configured module search path = [u'/Users/den/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Jun 17 2018, 12:46:58) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

##### CONFIGURATION

```
[defaults]
# Use the YAML callback plugin.
stdout_callback = yaml
# Use the stdout_callback when running ad-hoc commands.
bin_ansible_callbacks = True
```

##### OS / ENVIRONMENT

macos, fedora29, ...
##### STEPS TO REPRODUCE

```yaml
enable yaml output in ansible
[defaults]
# Use the YAML callback plugin.
stdout_callback = yaml
# Use the stdout_callback when running ad-hoc commands.
bin_ansible_callbacks = True

next try to "call setup module" "get facts" from whatever node you have handy

ansible -i 'your.node.ip.addr,' all -m setup
```

##### EXPECTED RESULTS

something like that:
```yaml
---
ansible_facts:
  ansible_all_ipv4_addresses:
  - 10.1.1.40
  - 172.17.0.1
  - 10.96.0.10
  - 10.96.0.1
  ansible_all_ipv6_addresses:
  - fe80::a00:27ff:fe6f:ec5
  ansible_apparmor:
    status: disabled
  ansible_architecture: x86_64
  ansible_bios_date: 12/01/2006
  ansible_bios_version: VirtualBox
  ansible_cmdline:
    BOOT_IMAGE: "/vmlinuz-3.10.0-957.1.3.el7.x86_64"
    LANG: en_US.UTF-8
    crashkernel: auto
    quiet: true
    rd.lvm.lv: centos_vg/root
    rhgb: true
    ro: true
    root: "/dev/mapper/centos_vg-root"
...
```

##### ACTUAL RESULTS

```paste below
ansible -i '10.1.1.40,' all -m setup

PLAY [Ansible Ad-Hoc] ******************************************************************************************************************************************************************************************

TASK [setup] ***************************************************************************************************************************************************************************************************
ok: [10.1.1.40]

PLAY RECAP *****************************************************************************************************************************************************************************************************
10.1.1.40                  : ok=1    changed=0    unreachable=0    failed=0
```

**Comment by sivel** [comment] 2019-01-03 16:02
The `yaml` stdout callback wasn't designed to work with adhoc, and as such, it will only print values based on `ansible-playbook` behavior, which only happens when running with a verbosity (`-v`) of 1 or higher.

In the end, this is a duplicate of https://github.com/ansible/ansible/issues/39122

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Closed as completed by sivel** 2019-01-03 16:02 UTC

**Comment by den-is** [comment] 2019-01-03 16:06
sad.

but sounds more like some religion prohibits that "design" enhancement.

**Comment by bcoca** [comment] 2019-01-03 16:52
no, its a bug of the yaml callback plugin, which is why the ticket referenced above is still open.
