### ISSUE TITLE
async mode with connection local and Ruby modules

### ISSUE THREAD

**Issue by jeremyschulman** [ansible/ansible#3287] opened 2013-06-20 19:25 UTC
I have experienced an issue (python error) when attempting "async" and "poll" on a playbook with connection: local, and module written in Ruby.  Could you please investigate and provide guidance on how to make this work properly?

Thank you!
-- Jeremy

**Comment by mpdehaan** [comment] 2013-06-20 21:27
So there's not much to go on here and I need some more info.

In writing better bug reports.

(A)  paste as much detail as you can, here, this would definitely include the part of playbook you were using

(B)  when you say "encountered an issue", explain what the issue was.  If there was a traceback or some unexpected behavior, showing the output or behavior would be useful.  What do you expect and what did you get?

I can obviously try to replicate with a "sleep 50" kind of ruby module, but I'd have to write one, and I'm not sure I'll be reproducing the issue without knowing what the issue was, so can you build a simple module that doesn't require talking to JunOS to replicate this so we can see if it is fixed?  Sharing it on gist would be fine.

**Comment by jeremyschulman** [comment] 2013-06-20 22:46
Ok, that's fair - so every time I don't do a good job opening an issue report I own you one bourbon based drink.

I'll setup a reproducible rig and send you the details.  Unfortunately I am going to travel again all next week.  At least I've got this issue report now to remind me :-)

**Comment by mpdehaan** [comment] 2013-07-20 19:28
closing due to insufficient info

**Closed as completed** 2013-07-20 19:28 UTC
