### ISSUE TITLE
Dropbear MOTD causing parse error

### ISSUE THREAD

**Issue by jribenfors** [ansible/ansible#6309] opened 2014-03-06 12:59 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6 (devel 40ee030790) last updated 2014/03/05 11:33:53 (GMT +100)
##### Environment:

Running ansible on Ubuntu 12.4
Host OS is: Linux mini2440 3.1.1-ptx-2011.11.0dtl #2 PREEMPT Wed Jun 12 14:56:20 UTC 2013 armv4tl GNU/Linux running on a mini2004

The host uses Dropbear sshd v0.53.1
##### Summary:

When dropbear doesn't display a MOTD on login, ansible works. If there is a MOTD, ansible gives a parse error.

The MOTD is:

```
===================== 8816 ====================

SITEID=8816
SERVER=UK

SMBD=n
HTTPD=n
FPDPORT=8800
NMDPORT=8801
HTTPPOST=80

#NMD_SPEED=
#NTP_SERVER=

ARCH=mini
SSH_PORTPREFIX=2149
SSH_FPDPORT=21490
SSH_NMDPORT=21491
SSH_SSHPORT=21492
SMSD=y

===============================================
```
##### Steps To Reproduce:

Have MOTD on host system, run ansible.
##### Expected Results:

Ansible should be able to ssh in and start running the play.

Without MOTD:

```
[johan@mars ansible] [devel]$ ansible-playbook ~/netmon-upload.yml -kvvvv
SSH password: 

PLAY [dgw] ******************************************************************** 

GATHERING FACTS *************************************************************** 
<192.168.0.46> ESTABLISH CONNECTION FOR USER: root
<192.168.0.46> REMOTE_MODULE setup
<192.168.0.46> EXEC ['sshpass', '-d4', 'ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/johan/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'GSSAPIAuthentication=no', '-o', 'PubkeyAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', '192.168.0.46', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1394111954.88-174410978718250 && echo $HOME/.ansible/tmp/ansible-tmp-1394111954.88-174410978718250'"]
<192.168.0.46> PUT /tmp/tmpDjKHxb TO /home/.ansible/tmp/ansible-tmp-1394111954.88-174410978718250/setup
<192.168.0.46> EXEC ['sshpass', '-d4', 'ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/johan/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'GSSAPIAuthentication=no', '-o', 'PubkeyAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', '192.168.0.46', "/bin/sh -c '/usr/bin/python /home/.ansible/tmp/ansible-tmp-1394111954.88-174410978718250/setup; rm -rf /home/.ansible/tmp/ansible-tmp-1394111954.88-174410978718250/ >/dev/null 2>&1'"]
ok: [192.168.0.46]

TASK: [Backup netmon-upload] ************************************************** 
<192.168.0.46> ESTABLISH CONNECTION FOR USER: root
<192.168.0.46> REMOTE_MODULE command cp /home/dtl/netmon-upload.elf /home/dtl/netmon-upload.elf.old #USE_SHELL
<192.168.0.46> EXEC ['sshpass', '-d7', 'ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/johan/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'GSSAPIAuthentication=no', '-o', 'PubkeyAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', '192.168.0.46', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1394111959.11-211847776526081 && echo $HOME/.ansible/tmp/ansible-tmp-1394111959.11-211847776526081'"]
<192.168.0.46> PUT /tmp/tmpsXYwXb TO /home/.ansible/tmp/ansible-tmp-1394111959.11-211847776526081/command
<192.168.0.46> EXEC ['sshpass', '-d7', 'ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/johan/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'GSSAPIAuthentication=no', '-o', 'PubkeyAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', '192.168.0.46', "/bin/sh -c '/usr/bin/python /home/.ansible/tmp/ansible-tmp-1394111959.11-211847776526081/command; rm -rf /home/.ansible/tmp/ansible-tmp-1394111959.11-211847776526081/ >/dev/null 2>&1'"]
changed: [192.168.0.46] => {"changed": true, "cmd": "cp /home/dtl/netmon-upload.elf /home/dtl/netmon-upload.elf.old ", "delta": "0:00:00.088391", "end": "2014-03-06 13:19:21.287605", "rc": 0, "start": "2014-03-06 13:19:21.199214", "stderr": "", "stdout": ""}

...snip
```
##### Actual Results:

Ansible gives a parse error on login:

With MOTD:

```
[johan@mars ansible] [devel]$ ansible-playbook ~/netmon-upload.yml -kvvvv
SSH password:

PLAY [dgw] ********************************************************************

GATHERING FACTS ***************************************************************
<192.168.0.46> ESTABLISH CONNECTION FOR USER: root
<192.168.0.46> REMOTE_MODULE setup
<192.168.0.46> EXEC ['sshpass', '-d4', 'ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/johan/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'GSSAPIAuthentication=no', '-o', 'PubkeyAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', '192.168.0.46', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1394108624.95-55184614825348 && echo $HOME/.ansible/tmp/ansible-tmp-1394108624.95-55184614825348'"]
<192.168.0.46> PUT /tmp/tmpgafZ_C TO /home/.ansible/tmp/ansible-tmp-1394108624.95-55184614825348/setup
<192.168.0.46> EXEC ['sshpass', '-d4', 'ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/johan/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'GSSAPIAuthentication=no', '-o', 'PubkeyAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', '192.168.0.46', "/bin/sh -c '/usr/bin/python /home/.ansible/tmp/ansible-tmp-1394108624.95-55184614825348/setup; rm -rf /home/.ansible/tmp/ansible-tmp-1394108624.95-55184614825348/ >/dev/null 2>&1'"]
fatal: [192.168.0.46] => failed to parse:
===================== 8816 ====================

SITEID=8816
SERVER=UK

SMBD=n
HTTPD=n
FPDPORT=8800
NMDPORT=8801
HTTPPOST=80

#NMD_SPEED=
#NTP_SERVER=

ARCH=mini
SSH_PORTPREFIX=2149
SSH_FPDPORT=21490
SSH_NMDPORT=21491
SSH_SSHPORT=21492
SMSD=y

===============================================
{"verbose_override": true, "changed": false, "ansible_facts": {"ansible_product_serial": "NA", "ansible_form_factor": "NA", "ansible_product_version": "NA", "ansible_swaptotal_mb": 0, "ansible_user_id": "root", "ansible_memtotal_mb": 60, "ansible_distribution_version": "NA", "ansible_domain": "", "ansible_date_time": {"tz": "UTC", "hour": "12", "time": "12:23:52", "epoch": "1394108632", "month": "03", "tz_offset": "+0000", "second": "52", "iso8601_micro": "2014-03-06T12:23:52.533376Z", "year": "2014", "date": "2014-03-06", "iso8601": "2014-03-06T12:23:52Z", "day": "06", "minute": "23"}, "ansible_processor_cores": 1, "ansible_env": {"LANG": "C", "TERM": "xterm", "SHELL": "/bin/sh", "SSH_TTY": "/dev/pts/0", "PWD": "/home", "LOGNAME": "root", "USER": "root", "PATH": "/usr/bin:/bin", "HOME": "/home", "SSH_CONNECTION": "192.168.0.20 44062 192.168.0.46 22"}, "ansible_processor_vcpus": 1, "ansible_bios_version": "NA", "ansible_processor": ["ARM920T rev 0 (v4l)"], "ansible_lo": {"mtu": 16436, "active": true, "promisc": false, "ipv4": {"netmask": "255.0.0.0", "network": "127.0.0.0", "address": "127.0.0.1"}, "device": "lo", "type": "loopback"}, "ansible_userspace_bits": "32", "ansible_architecture": "armv4tl", "ansible_default_ipv4": {"macaddress": "44:54:4c:ab:ed:1c", "network": "192.168.0.0", "mtu": 1500, "alias": "eth0", "netmask": "255.255.255.0", "address": "192.168.0.46", "interface": "eth0", "type": "ether", "gateway": "192.168.0.1"}, "ansible_swapfree_mb": 0, "ansible_default_ipv6": {}, "ansible_distribution_release": "NA", "ansible_system_vendor": "NA", "ansible_os_family": "NA", "ansible_cmdline": {"mtdparts": "nand:512k(barebox),384k(bareboxenv),4096k(kernel),-(root)", "console": "ttySAC2,115200", "ip": "none", "mini2440": "0tbc", "rootfstype": "jffs2", "root": "/dev/mtdblock3", "noinitrd": true}, "ansible_selinux": false, "ansible_product_uuid": "NA", "ansible_system": "Linux", "ansible_pkg_mgr": "unknown", "ansible_memfree_mb": 33, "ansible_devices": {}, "ansible_distribution": "NA", "ansible_processor_count": 1, "ansible_hostname": "mini2440", "ansible_bios_date": "NA", "ansible_all_ipv6_addresses": [], "ansible_interfaces": ["lo", "eth0"], "ansible_machine": "armv4tl", "ansible_kernel": "3.1.1-ptx-2011.11.0dtl", "ansible_processor_threads_per_core": 1, "ansible_fqdn": "mini2440", "ansible_mounts": [{"size_total": 263323648, "mount": "/", "size_available": 232529920, "fstype": "jffs2", "device": "/dev/root", "options": "rw,relatime"}], "ansible_eth0": {"macaddress": "44:54:4c:ab:ed:1c", "mtu": 1500, "active": true, "promisc": false, "ipv4": {"netmask": "255.255.255.0", "network": "192.168.0.0", "address": "192.168.0.46"}, "device": "eth0", "type": "ether"}, "ansible_product_name": "NA", "ansible_all_ipv4_addresses": ["192.168.0.46"], "ansible_python_version": "2.6.6"}}


TASK: [Backup netmon-upload] **************************************************
FATAL: no hosts matched or all hosts have already failed -- aborting


PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/johan/netmon-upload.retry
```

**Comment by mpdehaan** [comment] 2014-03-06 17:04
It's been a while since I remember a report about dropbear.

You may wish to try "-c paramiko" instead of "-c ssh" to see if this helps?

The parser logic should look for a "{" to start parsing though, so it seems like this can be patched to be made to work.

Is this something you might like to help work on since you have a system that can reproduce this?

If so, can provide some pointers.

Thanks!

**Comment by jribenfors** [comment] 2014-03-06 17:45
I don't have a lot of python experience, but am willing to try.  Where do I start looking?

"-c paramiko" attempts to use sftp which we don't have installed on the embedded boards.  I'm using 'scp_if_ssh = True' in /etc/ansible/ansible.cfg

Paramiko error:

```
[johan@mars ansible] [devel]$ ansible-playbook ~/netmon-upload.yml -kvvvv -c paramiko
SSH password: 

PLAY [dgw] ******************************************************************** 

GATHERING FACTS *************************************************************** 
<192.168.0.46> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO 192.168.0.46
<192.168.0.46> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1394127099.02-16822126901457 && echo $HOME/.ansible/tmp/ansible-1394127099.02-16822126901457'
<192.168.0.46> REMOTE_MODULE setup 
<192.168.0.46> PUT /tmp/tmp57PWot TO /home/.ansible/tmp/ansible-1394127099.02-16822126901457/setup
fatal: [192.168.0.46] => failed to open a SFTP connection (EOF during negotiation)

TASK: [Backup netmon-upload] ************************************************** 
FATAL: no hosts matched or all hosts have already failed -- aborting


PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/johan/netmon-upload.retry

192.168.0.46               : ok=0    changed=0    unreachable=1    failed=0   
```

**Comment by mpdehaan** [comment] 2014-03-16 15:56
Sorry for the late response, github comment notifications are easy to miss.

I'm wondering if it's not perhaps the MOTD, but instead you are getting some output in ~/.bashrc or  ~/.bash_profile -- that's caused a problem or two in the past.

In any event, I'd start by printing out things coming back from paramiko_ssh.py, possibly.

**Comment by mpdehaan** [comment] 2014-03-16 18:06
Also I noticed there's some detection code in the utils.parse_json() methods that we may need to screw with.

Historical notes show that the problem is dropbear outputs the MOTD on every single command and we have to detect when it stops and good things begin.

We did this previously by looking for a line that starts with "=" but the problem here I think is that's not the end of it.

The problem is complicated because Ansible allows bash modules to return "key=value" output, as is done here in the MOTD, which means we thought the output was key=value and not JSON, which is what happened in this case.

Discovered this while reading through the parser code as the result of another ticket.

This may be a little "fun" to solve.

**Comment by jimi-c** [comment] 2015-06-18 16:38
Spoke too soon, oddly this works with ping but when I ran a different module I got the failed to decode JSON error, so we'll leave this open for now.

**Comment by jimi-c** [comment] 2016-09-08 19:03
# Update Required

Hi, our apologies on taking so long to follow-up on this issue.

This bug was reported on a version of Ansible that is very out of date, and we're not sure if it's valid anymore. As such, could you please let us know if this issue still applies to the devel branch, or the most recent version of Ansible (currently 2.1.x or the latest commit from the stable-2.1 branch)?

If we do not see any follow-up on this issue, we will close and lock this issue and any further reports should be done in a new issue.

Thanks!

**Comment by AdamBark** [comment] 2016-09-14 19:32
I am running ansible 2.1.1.0 as available on debian testing (stretch) and I can't ping or run a command as explained in the "Getting Started" section when trying to contact a router running openwrt which uses dropbear as the sshd. Here's the motd:

> BusyBox v1.23.2 (2016-01-02 18:01:44 CET) built-in shell (ash)
> 
> ---
> 
>  |       |.-----.-----.-----.|  |  |  |.----.|  |_
>  |   -   ||  _  |  -**|     ||  |  |  ||   _||   _|
>  |_____**||   **|___**|**|**||________||**|  |__**|
>           |__| W I R E L E S S   F R E E D O M
> 
> ---
> 
>  CHAOS CALMER (15.05.1, r48532)
> 
> ---
> - 1 1/2 oz Gin            Shake with a glassful
> - 1/4 oz Triple Sec       of broken ice and pour
> - 3/4 oz Lime Juice       unstrained into a goblet.
> - 1 1/2 oz Orange Juice
> - 1 tsp. Grenadine Syrup
>   -----------------------------------------------------

**Comment by AdamBark** [comment] 2016-09-14 19:41
Ah actually I found that the problem is attempting to use sftp. Setting scp_if_ssh = True gets further along but it fails because I don't have python installed on the router.

> openwrt | FAILED! => {
>     "changed": false, 
>     "failed": true, 
>     "module_stderr": "", 
>     "module_stdout": "/bin/sh: /usr/bin/python: not found\r\n", 
>     "msg": "MODULE FAILURE", 
>     "parsed": false
> }

using the raw module works on this system. If there's anything else you'd like me to test I am willing otherwise I think you can close this issue. Would adding a feature that tries scp as a fallback if sftp fails be worth writing?

**Comment by jimi-c** [comment] 2016-10-06 14:09
@AdamBark that's interesting, that indicates the problem is more with the `put` call in the connection plugin rather than the `execute` call. So for those using pipelining mode, there generally won't be a `put` call done (which is probably why we haven't heard many reports of this).

**Comment by bcoca** [comment] 2017-01-23 18:47
We've updated latest devel to try several ways of pushing files, @AdamBark  can  you test making sure you have:
```
scp_if_ssh = smart
transfer_method = smart
```

**Comment by AdamBark** [comment] 2017-01-26 04:17
Success! That works for me, thanks @bcoca and anyone else involved.

**Comment by bcoca** [comment] 2017-01-26 14:35
nice, i'm going to close this as 'fixed' then.

**Closed as completed by bcoca** 2017-01-26 14:35 UTC
Labels: affects_2.1, affects_2.2, c:plugins/connection, bug
