### ISSUE TITLE
Ansible-Timed out waiting for scheduled task to start

### ISSUE THREAD

**Issue by lakki4444** [ansible/ansible#26244] opened 2017-06-29 13:48 UTC
FAILED! => {"changed": false, "error_record": {"CategoryInfo": {"Activity": "", "Category": 14, "Reason": "RuntimeException", "TargetName": "Timed out waiting for scheduled task to start", "TargetType": "String"}, "ErrorDetails": null, "Exception": {"Data": {}, "ErrorRecord": {"CategoryInfo": "NotSpecified: (:) [], ParentContainsErrorRecordException", "ErrorDetails": null, "Exception": "System.Management.Automation.ParentContainsErrorRecordException: Timed out waiting for scheduled task to start", "FullyQualifiedErrorId": "RuntimeException", "InvocationInfo": null, "PipelineIterationInfo": "", "ScriptStackTrace": null, "TargetObject": null}, "HResult": -2146233087, "HelpLink": null, "InnerException": null, "Message": "Timed out waiting for scheduled task to start", "Source": null, "StackTrace": null, "TargetSite": null, "WasThrownFromThrowStatement": true}, "FullyQualifiedErrorId": "Timed out waiting for scheduled task to start", "InvocationInfo": {"BoundParameters": {}, "CommandOrigin": 1, "DisplayScriptPosition": null, "ExpectingInput": false, "HistoryId": -1, "InvocationName": "", "Line": "        Throw \"Timed out waiting for scheduled task to start\"\n", "MyCommand": null, "OffsetInLine": 9, "PSCommandPath": "C:\\Users\\Administrator\\AppData\\Local\\Temp\\ansible-tmp-1498743415.94-145663458112566\\win_updates.ps1", "PSScriptRoot": "C:\\Users\\Administrator\\AppData\\Local\\Temp\\ansible-tmp-1498743415.94-145663458112566", "PipelineLength": 0, "PipelinePosition": 0, "PositionMessage": "At C:\\Users\\Administrator\\AppData\\Local\\Temp\\ansible-tmp-1498743415.94-145663458112566\\win_updates.ps1:560 char:9\r\n+         Throw \"Timed out waiting for scheduled task to start\"\r\n+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~", "ScriptLineNumber": 560, "ScriptName": "C:\\Users\\Administrator\\AppData\\Local\\Temp\\ansible-tmp-1498743415.94-145663458112566\\win_updates.ps1", "UnboundArguments": []}, "PSMessageDetails": null, "PipelineIterationInfo": [], "ScriptStackTrace": "at RunAsScheduledJob, C:\\Users\\Administrator\\AppData\\Local\\Temp\\ansible-tmp-1498743415.94-145663458112566\\win_updates.ps1: line 560\r\nat <ScriptBlock>, C:\\Users\\Administrator\\AppData\\Local\\Temp\\ansible-tmp-1498743415.94-145663458112566\\win_updates.ps1: line 646\r\nat <ScriptBlock>, <No file>: line 4", "TargetObject": "Timed out waiting for scheduled task to start"}, "failed": true, "msg": "Timed out waiting for scheduled task to start"}

##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### ANSIBLE VERSION

```

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by jhawkesworth** [comment] 2017-06-29 14:15
Please can you fill out the issue template, without this it is very hard for others to reproduce and investigate your issues.

**Comment by nitzmahone** [comment] 2017-06-30 00:45
looks like duplicate of #25298

**Closed as completed by nitzmahone** 2017-06-30 00:45 UTC
Labels: affects_2.4, support:core, bug
