### ISSUE TITLE
In Rocky 9 gather_facts does not include facts from facter.

### ISSUE THREAD

**Issue by thanos-k** [ansible/ansible#80496] opened 2023-04-12 16:17 UTC
### Summary

In Rocky 9 gather facts does not include facter derived facts even though facter is installed in the target system

### Issue Type

Bug Report

### Component Name

pip

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.4]
  config file = ./ansible.cfg
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = ./ansible7.venv/lib64/python3.11/site-packages/ansible
  ansible collection location = ./collections
  executable location = ./ansible7.venv/bin/ansible
  python version = 3.11.2 (main, Feb  8 2023, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] (./ansible7.venv/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed -t all
ANSIBLE_FORCE_COLOR(./ansible.cfg) = True
ANSIBLE_PIPELINING(./ansible.cfg) = True
COLLECTIONS_PATHS(./ansible.cfg) = ['./collections']
CONFIG_FILE() = ./ansible.cfg
DEFAULT_FORKS(./ansible.cfg) = 20
DEFAULT_HOST_LIST(./ansible.cfg) = ['./inventory']
DEFAULT_JINJA2_EXTENSIONS(./ansible.cfg) = jinja2.ext.do
DEFAULT_LOOKUP_PLUGIN_PATH(./ansible.cfg) = ['./scripts/plugins/lookup']
DEFAULT_REMOTE_USER(./ansible.cfg) = ansible
DEFAULT_ROLES_PATH(./ansible.cfg) = ['./galaxy_roles']
DEFAULT_VAULT_PASSWORD_FILE(./ansible.cfg) = ./.vault
HOST_KEY_CHECKING(./ansible.cfg) = False

CONNECTION:
==========

local:
_____
pipelining(./ansible.cfg) = True

paramiko_ssh:
____________
host_key_checking(./ansible.cfg) = False
remote_user(./ansible.cfg) = ansible
ssh_args(./ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s

psrp:
____
pipelining(./ansible.cfg) = True

ssh:
___
host_key_checking(./ansible.cfg) = False
pipelining(./ansible.cfg) = True
remote_user(./ansible.cfg) = ansible
ssh_args(./ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s

winrm:
_____
pipelining(./ansible.cfg) = True
```

### OS / Environment

Target OS :  Rocky Linux release 9.1 (Blue Onyx)

Installed facter from rpm in target OS

$ rpm -qi facter
Name        : facter
Version     : 4.3.0
Release     : 2.el9

### Steps to Reproduce

```yaml (paste below)
$ ansible rocky9 -b -m ansible.builtin.setup -a 'gather_subset="!all,!min,facter"'

```

### Expected Results

Expected to get facter facts

### Actual Results

```console
$ ansible rocky9 -b -m ansible.builtin.setup -a 'gather_subset="!all,!min,facter"'

rocky9 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3",
        "gather_subset": [
            "!all",
            "!min",
            "facter"
        ],
        "module_setup": true
    },
    "changed": false
}

Keep in mind that executing

 ansible rocky9 -b -m ansible.builtin.facter

returns full facter facs
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by sivel** [comment] 2023-04-12 16:21
Duplicate of https://github.com/ansible/ansible/issues/78724

**Comment by bcoca** [comment] 2023-04-12 19:36
never got around to testing/finishing it but here you have a 'just facter facts' module https://github.com/bcoca/misc-collection/blob/devel/plugins/modules/facter_facts.py

**Comment by thanos-k** [comment] 2023-04-12 19:53
@bcoca I think what needs to be fixed is 
https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/facts/other/facter.py#L51

not to include the --puppet flag.

It is only natural that it fails since most systems don't install puppet. 
I am just extremely surprised that this has become a problem just with the latest versions of facter and in the past the use of the --puppet flag actually had a 0 exit code.

**Comment by bcoca** [comment] 2023-04-12 19:55
i know, but until this gets fixed, the module above has that as an OPTION

**Comment by cschug** [comment] 2023-04-26 10:40
> I am just extremely surprised that this has become a problem just with the latest versions of facter and in the past the use of the --puppet flag actually had a 0 exit code.

It might be newsworthy that the behavior might be highly related to the version of Facter in use. With Facter 3 there shouldn't be any issue but in Facter 4 it was originally planned to remove the support for Puppet fact reporting (`-p`/`--puppet`).

Later with Facter 4.0.51 the Puppet fact reporting was restored again, see ...
- https://tickets.puppetlabs.com/browse/FACT-2939
- https://github.com/puppetlabs/facter/pull/2278/files

**Comment by bcoca** [comment] 2023-04-26 15:12
why a switch seems to be the best solution (see module i posted above) .. the hard part is adding this to the base 'setup.py' fact gathering as there is no good way to add a 'sub filter swtich' for fact gathering (probably adding a retry w/o --puppet).

**Comment by bcoca** [comment] 2023-04-26 15:25
pleas confirm that the PR above fixes the issue for you

**Closed as completed** 2023-05-08 20:53 UTC
Labels: module, bug, has_pr, affects_2.14
