### ISSUE TITLE
Variables not interpolated in environment when using block

### ISSUE THREAD

**Issue by aocole** [ansible/ansible#13123] opened 2015-11-10 23:53 UTC
##### Ansible Version:

```
ansible 2.0.0 (detached HEAD 76ae577519) last updated 2015/11/10 23:38:28 (GMT +000)
  lib/ansible/modules/core: (detached HEAD fde6ee15d6) last updated 2015/11/10 20:05:36 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 6cc43bbd56) last updated 2015/11/10 20:06:02 (GMT +000)
  config file = 
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

No changes
##### Environment:

Ubuntu 14.04.3
##### Summary:

When using an `environment:` section in a block, variables are not interpolated. This broke with commit 76ae5775192b03f390df0fd04b14b9d79324a9c5
##### Steps To Reproduce:

``` yaml

---
- name: Demonstrate variable interpolation in environment
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    foo: bar

  tasks:
  - block:
    - name: Print variable
      shell: "echo $baz"
      register: result
    - debug: var=result.stdout
    environment:
      baz: "{{ foo }}"
```
##### Expected Results:

```
ok: [localhost] => {
    "changed": false,
    "result.stdout": "bar"
}
```
##### Actual Results:

```
ok: [localhost] => {
    "changed": false,
    "result.stdout": "{# foo #}"
}
```

**Comment by aocole** [comment] 2015-11-11 00:00
@jimi-c ^

**Comment by chrrrles** [comment] 2015-11-11 11:37
Hi aocole -- I ran this playbook on devel and got the expected output:

```

ok: [localhost] => {
    "changed": false, 
    "result.stdout": "bar"
}
 _____________________________ 
```

May you retry this using the latest devel?

**Comment by aocole** [comment] 2015-11-11 17:55
I have verified that the problem still exists on latest devel (see version below). Please note that it only occurs when using a block, as in my example playbook above. 

```
ansible 2.0.0 (devel 1b7d3f2898) last updated 2015/11/11 17:50:21 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 6e37f1dcef) last updated 2015/11/11 17:50:54 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 7d8dd6e210) last updated 2015/11/11 17:51:04 (GMT +000)
  config file = 
  configured module search path = Default w/o overrides

 [WARNING]: provided hosts list is empty, only localhost is available

 __________________________________________________________
< PLAY [Demonstrate variable interpolation in environment] >
 ----------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

 _______________________
< TASK [Print variable] >
 -----------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

changed: [localhost]
 ________________________________
< TASK [debug var=result.stdout] >
 --------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

ok: [localhost] => {
    "changed": false,
    "result.stdout": "{# foo #}"
}
 ____________
< PLAY RECAP >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

localhost                  : ok=2    changed=1    unreachable=0    failed=0
```

**Comment by jimi-c** [comment] 2015-11-12 02:57
I'm able to reproduce this and am looking into it.

**Comment by wrouesnel** [comment] 2015-11-17 03:40
+1 - I've run into this with ansible devel head just today. Going back to commit 2e05304f668e447bbbe1696d014d0a24d45ceb92 fixes the problem.

**Comment by jimi-c** [comment] 2015-11-17 20:39
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed** 2015-11-17 20:39 UTC
Labels: bug
