### ISSUE TITLE
copy module says 'state' is an unsupported parameter

### ISSUE THREAD

**Issue by danvaida** [ansible/ansible#8454] opened 2014-08-05 14:43 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7 (devel 4e6685d772) last updated 2014/08/05 16:23:01 (GMT +200)
##### Environment:

Ansible host: FC19
Target host: Wheezy
##### Summary:

Trying to use 'state=directory' with the copy module.
##### Steps To Reproduce:

```
[...]
- name: copying the SSL certs
  copy: src=ssl dest=/etc/nginx/ssl mode=0755 directory_mode=yes state=directory recurse=yes
  sudo: yes
[...]
```
##### Expected Results:

All the 'ssl' directory gets copied across to the target machines.
##### Actual Results:

```
TASK: [nginx | copying the SSL certs] ***************************************** 
failed: [54.72.72.93] => {"failed": true, "md5sum": "d95f9724af4b31ef90098ef8c8ef587f"}
msg: unsupported parameter for module: state

FATAL: all hosts have already failed -- aborting
```

I know this is more like a job for the synchronize module, but it seems the copy module has this parameters incompatibility that I wanted to report.

**Comment by Jmainguy** [comment] 2014-08-05 16:33
Yup I can confirm it is not working. I looked at the code and could not understand how it is supposed to read the same arguments from the file: module. the only thing I see is add_file_common_args=True and directory_args = module.load_file_common_arguments. Also the documentation inside the file does not match what is on the website, the website seems much newer with expanded features then what the file actually shows.

**Comment by mpdehaan** [comment] 2014-08-06 00:52
State isn't a supported parameter.

The problem was that the docs generator code was wrong, which I've just now fixed up.   You won't need to pass state=directory here and should be fine to leave if off.   Doc chnages should reflect very very very soon.

I'm going to close this one, but feel free to stop by ansible-project to discuss if you are still having problems.  

Thanks!

**Closed as completed by mpdehaan** 2014-08-06 00:52 UTC
