### ISSUE TITLE
Shell type issues w/ FreeBSD + tcsh

### ISSUE THREAD

**Issue by 2bithacker** [ansible/ansible#13942] opened 2016-01-18 02:09 UTC
Upon upgrading to Ansible 2.0 I started having issues with running my playbooks.

Remote system is FreeBSD 10.2-RELEASE, using the default `freebsd` user that DigitalOcean creates on it's droplets, which is given `/bin/tcsh` as a shell.

With no modifications from 1.9, I received the following error:

```
$ ansible-playbook -l tor1.2bit.co common.yml
Vault password:

PLAY ***************************************************************************

TASK [setup] *******************************************************************
fatal: [tor1.2bit.co]: UNREACHABLE! => {"changed": false, "msg": "ERROR! Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 22 && mkdir -p \"$( echo $HOME/.ansible/tmp/ansible-tmp-1453082623.05-21600946241638 )\" && echo \"$( echo $HOME/.ansible/tmp/ansible-tmp-1453082623.05-21600946241638 )\" ), exited with result 1: Illegal variable name.\r\n", "unreachable": true}

PLAY RECAP *********************************************************************
tor1.2bit.co               : ok=0    changed=0    unreachable=1    failed=0
```

I did some quick searching, and this appears to be due to some assumptions about the remote shell being bash. I set `ansible_shell_type = csh` but this leads to another error:

```
$ ansible-playbook -l tor1.2bit.co common.yml
Vault password:

PLAY ***************************************************************************

TASK [setup] *******************************************************************
fatal: [tor1.2bit.co]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "{\"invocation\": {\"module_args\": {\"filter\": \"*\", \"fact_path\": \"/etc/ansible/facts.d\"}}, \"changed\": false, \"_ansible_verbose_override\": true, \"ansible_facts\": {\"ansible_product_serial\": \"NA\", \"ansible_form_factor\": \"NA\", \"ansible_product_version\": \"NA\", \"ansible_fips\": false, \"ansible_service_mgr\": \"init\\n\", \"ansible_user_id\": \"root\", \"module_setup\": true, \"ansible_memtotal_mb\": 485, \"ansible_vtnet0\": {\"status\": \"active\", \"macaddress\": \"04:01:92:09:d0:01\", \"media\": \"Ethernet\", \"metric\": \"0\", \"mtu\": \"1500\", \"flags\": [\"UP\", \"BROADCAST\", \"RUNNING\", \"SIMPLEX\", \"MULTICAST\"], \"ipv4\": [{\"broadcast\": \"159.203.47.255\", \"netmask\": \"255.255.240.0\", \"network\": \"159.203.32.0\", \"address\": \"159.203.33.150\"}, {\"broadcast\": \"10.20.255.255\", \"netmask\": \"255.255.0.0\", \"network\": \"10.20.0.0\", \"address\": \"10.20.0.7\"}], \"ipv6\": [{\"scope\": \"0x1\", \"prefix\": \"64\", \"address\": \"fe80::601:92ff:fe09:d001%vtnet0\"}, {\"prefix\": \"64\", \"address\": \"2604:a880:cad:d0::6001\"}], \"device\": \"vtnet0\", \"media_type\": \"full-duplex>\", \"media_select\": \"10Gbase-T\", \"type\": \"unknown\", \"options\": [\"PERFORMNUD\", \"AUTO_LINKLOCAL\"]}, \"ansible_vtnet1\": {\"status\": \"active\", \"macaddress\": \"04:01:92:09:d0:02\", \"media\": \"Ethernet\", \"metric\": \"0\", \"mtu\": \"1500\", \"flags\": [\"BROADCAST\", \"SIMPLEX\", \"MULTICAST\"], \"ipv4\": [], \"ipv6\": [], \"device\": \"vtnet1\", \"media_type\": \"full-duplex>\", \"media_select\": \"10Gbase-T\", \"type\": \"unknown\", \"options\": [\"PERFORMNUD\", \"AUTO_LINKLOCAL\"]}, \"ansible_product_uuid\": \"NA\", \"ansible_ssh_host_key_ecdsa_public\": \"AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBBcNXvFwVbWHpLf3h2Iyjg+o9e8LzIfWsT7rwXwi7seE2hOx8IixNi+DhT6DBTtCSzxLC5gJ1g3RfQiUpHBj5Rw=\", \"ansible_distribution_version\": \"FreeBSD 10.2-RELEASE-p8 #1 r292422: Fri Dec 18 03:11:54 UTC 2015     root@shark.2bithacker.net:/usr/obj/usr/src/sys/TWOBIT\", \"ansible_domain\": \"2bit.co\", \"ansible_virtualization_type\": \"\", \"ansible_ssh_host_key_ed25519_public\": \"AAAAC3NzaC1lZDI1NTE5AAAAICza3xiXTa3PPxx23LArZL5rWHRQK1BJX8n6JT3nDzrm\", \"ansible_virtualization_role\": \"\", \"ansible_dns\": {\"nameservers\": [\"127.0.0.1\"], \"options\": {\"edns0\": true}}, \"ansible_bios_version\": \"NA\", \"ansible_processor\": [\"Intel(R) Xeon(R) CPU E5-2650L v3 @ 1.80GHz (1797.96-MHz K8-class CPU)\"], \"ansible_date_time\": {\"weekday_number\": \"1\", \"iso8601_basic_short\": \"20160118T020556\", \"tz\": \"UTC\", \"weeknumber\": \"03\", \"hour\": \"02\", \"year\": \"2016\", \"minute\": \"05\", \"tz_offset\": \"+0000\", \"month\": \"01\", \"epoch\": \"1453082756\", \"iso8601_micro\": \"2016-01-18T02:05:56.968116Z\", \"weekday\": \"Monday\", \"time\": \"02:05:56\", \"date\": \"2016-01-18\", \"iso8601\": \"2016-01-18T02:05:56Z\", \"day\": \"18\", \"iso8601_basic\": \"20160118T020556967961\", \"second\": \"56\"}, \"ansible_userspace_bits\": \"64\", \"ansible_architecture\": \"amd64\", \"ansible_default_ipv4\": {\"status\": \"active\", \"macaddress\": \"04:01:92:09:d0:01\", \"network\": \"159.203.32.0\", \"media\": \"Ethernet\", \"metric\": \"0\", \"mtu\": \"1500\", \"broadcast\": \"159.203.47.255\", \"interface\": \"vtnet0\", \"netmask\": \"255.255.240.0\", \"flags\": [\"UP\", \"BROADCAST\", \"RUNNING\", \"SIMPLEX\", \"MULTICAST\"], \"gateway\": \"159.203.32.1\", \"address\": \"159.203.33.150\", \"device\": \"vtnet0\", \"media_type\": \"full-duplex>\", \"media_select\": \"10Gbase-T\", \"type\": \"unknown\", \"options\": [\"PERFORMNUD\", \"AUTO_LINKLOCAL\"]}, \"ansible_swapfree_mb\": 1024, \"ansible_default_ipv6\": {\"status\": \"active\", \"macaddress\": \"04:01:92:09:d0:01\", \"media\": \"Ethernet\", \"metric\": \"0\", \"media_type\": \"full-duplex>\", \"mtu\": \"1500\", \"interface\": \"vtnet0\", \"prefix\": \"64\", \"flags\": [\"UP\", \"BROADCAST\", \"RUNNING\", \"SIMPLEX\", \"MULTICAST\"], \"gateway\": \"2604:a880:cad:d0::1\", \"address\": \"fe80::601:92ff:fe09:d001%vtnet0\", \"device\": \"vtnet0\", \"scope\": \"0x1\", \"media_select\": \"10Gbase-T\", \"type\": \"unknown\", \"options\": [\"PERFORMNUD\", \"AUTO_LINKLOCAL\"]}, \"ansible_distribution_release\": \"10.2-RELEASE-p8\", \"ansible_system_vendor\": \"NA\", \"ansible_os_family\": \"FreeBSD\", \"ansible_mounts\": [{\"device\": \"/dev/gpt/rootfs\", \"mount\": \"/\", \"options\": \"rw\", \"fstype\": \"ufs\"}, {\"device\": \"/dev/gpt/swapfs\", \"mount\": \"none\", \"options\": \"sw\", \"fstype\": \"swap\"}], \"ansible_gre1\": {\"macaddress\": \"unknown\", \"metric\": \"0\", \"mtu\": \"1476\", \"flags\": [\"UP\", \"POINTOPOINT\", \"RUNNING\", \"MULTICAST\"], \"ipv4\": [{\"broadcast\": \"0xfffffffe\", \"netmask\": \"192.168.100.9\", \"network\": \"192.168.100.8\", \"address\": \"192.168.100.8\"}], \"ipv6\": [{\"scope\": \"0x5\", \"prefix\": \"64\", \"address\": \"fe80::601:92ff:fe09:d001%gre1\"}, {\"prefix\": \"127\", \"address\": \"fd9e:925c:5f72:5::\"}], \"device\": \"gre1\", \"type\": \"unknown\", \"options\": [\"PERFORMNUD\", \"AUTO_LINKLOCAL\"]}, \"ansible_gre0\": {\"macaddress\": \"unknown\", \"metric\": \"0\", \"mtu\": \"1476\", \"flags\": [\"UP\", \"POINTOPOINT\", \"RUNNING\", \"MULTICAST\"], \"ipv4\": [{\"broadcast\": \"0xfffffffe\", \"netmask\": \"192.168.100.2\", \"network\": \"192.168.100.2\", \"address\": \"192.168.100.3\"}], \"ipv6\": [{\"scope\": \"0x4\", \"prefix\": \"64\", \"address\": \"fe80::601:92ff:fe09:d001%gre0\"}, {\"prefix\": \"127\", \"address\": \"fd9e:925c:5f72:2::1\"}], \"device\": \"gre0\", \"type\": \"unknown\", \"options\": [\"PERFORMNUD\", \"AUTO_LINKLOCAL\"]}, \"ansible_selinux\": false, \"ansible_swaptotal_mb\": 1024, \"ansible_product_name\": \"NA\", \"ansible_pkg_mgr\": \"pkgng\", \"ansible_memfree_mb\": 52, \"ansible_devices\": {}, \"ansible_user_uid\": 0, \"ansible_distribution\": \"FreeBSD\", \"ansible_env\": {\"LANG\": \"en_US.UTF-8\", \"SUDO_COMMAND\": \"/bin/sh -c echo BECOME-SUCCESS-iosffazhbemrmlnzbhqmkyzzgwoyjlwl; env LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/env python2.7 /home/freebsd/.ansible/tmp/ansible-tmp-1453082754.39-250526063712173/setup; rm -rf \\\"/home/freebsd/.ansible/tmp/ansible-tmp-1453082754.39-250526063712173/\\\" >& /dev/null\", \"SUDO_GID\": \"1001\", \"SHELL\": \"/bin/csh\", \"LC_MESSAGES\": \"en_US.UTF-8\", \"SUDO_UID\": \"1001\", \"TERM\": \"xterm-256color\", \"USERNAME\": \"root\", \"PWD\": \"/usr/home/freebsd\", \"LOGNAME\": \"root\", \"USER\": \"root\", \"PATH\": \"/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/home/freebsd/bin\", \"MAIL\": \"/var/mail/root\", \"SUDO_USER\": \"freebsd\", \"HOME\": \"/root\", \"LC_ALL\": \"en_US.UTF-8\"}, \"ansible_ssh_host_key_dsa_public\": \"AAAAB3NzaC1kc3MAAACBAIQEBe+cq5gZcWGHASKeI5P7m0G8ZtTs99Xd9HXfherDpF1r4dYfNXhMCXA8zWiz2ICHCaKUR5pI0NcrO197piAFLiqYASlqIisg1eN1EutRolV1GClQVFO33UmuK2JWL8UFl1+EyEK0LBC4X8U7kAmBU1A86chDO6kDe9dw8PVjAAAAFQDRVUgUIJ1Bklrdp83ILR3JAj/gDQAAAIAhIc/VJ2UXr2oHjAwrKmZ5EA9fhpjoO65ZPQxsLg+qZeXSknwB+ZwvFrgD9G8/qZwALZ6plfsvdgE2Q1LI59t3tE4V8JfavkEPsWbdpRxx+ineLB4+4maereQSZPw65ESMm02/eImm1fLofJ1qYUUzAN+pb03NqWri7gP0XlTWNAAAAIACMDhKcDh1d4WNAiHNJ6uagXxXue0BpcPfS0oaMDoJCjHHnNMWsDf+0ZC3Dx8hENRS8NOPf2RT/kbAwsGRq6TZW/FQSvMKtupNXoK15UnsygcWb04hWWa1um1UxnkBWr+h35lUrhLgSokY20fjt1/17xakbNlyS4TytJ03uyb+Kw==\", \"ansible_user_dir\": \"/root\", \"ansible_processor_count\": \"1\", \"ansible_hostname\": \"tor1\", \"ansible_lo0\": {\"macaddress\": \"unknown\", \"metric\": \"0\", \"mtu\": \"16384\", \"flags\": [\"UP\", \"LOOPBACK\", \"RUNNING\", \"MULTICAST\"], \"ipv4\": [{\"broadcast\": \"127.255.255.255\", \"netmask\": \"255.0.0.0\", \"network\": \"127.0.0.0\", \"address\": \"127.0.0.1\"}], \"ipv6\": [{\"prefix\": \"128\", \"address\": \"::1\"}, {\"scope\": \"0x3\", \"prefix\": \"64\", \"address\": \"fe80::1%lo0\"}], \"device\": \"lo0\", \"type\": \"unknown\", \"options\": [\"PERFORMNUD\", \"AUTO_LINKLOCAL\"]}, \"ansible_bios_date\": \"NA\", \"ansible_all_ipv6_addresses\": [\"fe80::601:92ff:fe09:d001%vtnet0\", \"2604:a880:cad:d0::6001\", \"fe80::601:92ff:fe09:d001%gre0\", \"fd9e:925c:5f72:2::1\", \"fe80::601:92ff:fe09:d001%gre1\", \"fd9e:925c:5f72:5::\"], \"ansible_interfaces\": [\"vtnet1\", \"vtnet0\", \"gre0\", \"lo0\", \"gre1\"], \"ansible_machine\": \"amd64\", \"ansible_ssh_host_key_rsa_public\": \"AAAAB3NzaC1yc2EAAAADAQABAAABAQDByNzw1Idz6DzoG3RKv1YoCGtIPsfxajR7njx+WRQfd9JJs00bav1ZKeDY9m7M3SkM+pn+VqEWVJdFNtkeqvkyNDy6u+riRlWs4Ftrhb5Zz9iX8w6m9p1ytycch97pA9+duxXGZZ3DZWRTpbdmolZf1u5CPrs4lZ+tzDIcaMPSD2k63RhOAokdcWzFdMLiXX38V/c/qecRXCQT8J5YhGjdZVtZGNFMpvL9sK4kvffCvKraNc4Z8Qx5SUeRmf0OHGhdH8wn/eMJLuknMJNr0TgEVc8kbOmUeaKNLsl6Zb49t3qan+c3M99PQQyp8IbSjQ09JbH1uEVMhUPcmaOOo4Dt\", \"ansible_user_gecos\": \"Charlie &\", \"ansible_all_ipv4_addresses\": [\"159.203.33.150\", \"10.20.0.7\", \"192.168.100.3\", \"192.168.100.8\"], \"ansible_fqdn\": \"tor1.2bit.co\", \"ansible_user_gid\": 0, \"ansible_nodename\": \"tor1.2bit.co\", \"ansible_system\": \"FreeBSD\", \"ansible_user_shell\": \"/bin/csh\", \"ansible_kernel\": \"10.2-RELEASE-p8\", \"ansible_python_version\": \"2.7.11\"}}\r\nSyntax error: Bad fd number\r\n", "msg": "MODULE FAILURE", "parsed": false}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
tor1.2bit.co               : ok=0    changed=0    unreachable=0    failed=1
```

I'd really like to figure out how to get this working with tcsh, so that I don't have to manually change anything when deploying new droplets before being able to use Ansible with them. This was working perfectly in 1.9.

**Comment by bcoca** [comment] 2016-01-18 13:46
dupe of #13882

**Closed as completed by bcoca** 2016-01-18 13:46 UTC
Labels: bsd
