### ISSUE TITLE
with_fileglob requires full path

### ISSUE THREAD

**Issue by robinrocky** [ansible/ansible#12172] opened 2015-08-31 20:11 UTC
I am using ansible --version 2.0.0

The issue is when I use variables in the path of withfile_glob, Ansible play is skipping this step and continuing.

 with_fileglob:
    - ../roles/files/{{ vob_name }}/{{app_name}}/{{version_number}}/config/*.j2

sample out from the play:
TASK [Getting the list of .j2 config files to be copied for bridge] *************
skipping: [ld-chctf-appl03.cttest.local]

but when I use values for those variables and run it then the play is able to find the files.

sample output below
TASK [Getting the list of .j2 config files to be copied for bridge] *************
changed: [ld-chctf-appl03.cttest.local] => (item=/somepath/esomename.cfg.j2)
changed: [ld-chctf-appl03.cttest.local] => (item=/somepath/esomename.xml.j2)

Is this a known bug or am I doing something wrong.

Thanks
Robin

**Comment by jimi-c** [comment] 2015-09-01 19:47
Hi @robinrocky, if you're executing this from within a role, you don't need to make the path relative to the playbook, the files will be found automatically in the `files/` directory (or `templates/`, if you're using the template module). Beyond that, with this simple reproduce (not using roles), I don't see any problems:

<pre>
- hosts: localhost
  gather_facts: no
  vars:
    my_path: "./files"
  tasks:
  - debug: msg="file is {{item}}"
    with_fileglob:
    - "{{my_path}}/*"
# ansible-playbook -vv test.yml 
Using /etc/ansible/ansible.cfg as config file
1 plays in test.yml
PLAY ***************************************************************************
TASK [debug msg=file is {{item}}] **********************************************
ok: [localhost] => (item=/testing/12172/files/b) => {
    "item": "/testing/12172/files/b", 
    "msg": "file is /testing/12172/files/b"
}
ok: [localhost] => (item=/testing/12172/files/d) => {
    "item": "/testing/12172/files/d", 
    "msg": "file is /testing/12172/files/d"
}
ok: [localhost] => (item=/testing/12172/files/a) => {
    "item": "/testing/12172/files/a", 
    "msg": "file is /testing/12172/files/a"
}
ok: [localhost] => (item=/testing/12172/files/c) => {
    "item": "/testing/12172/files/c", 
    "msg": "file is /testing/12172/files/c"
}
PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
</pre>

**Comment by robinrocky** [comment] 2015-09-04 19:06
Thanks for the info jimi,

I figured out the solution.

when I use as below the path with the variables are not getting resolved.
with_fileglob:
- ../roles/files/{{ vob_name }}/{{app_name}}/{{version_number}}/config/*.j2

so I changed it to as below
with_fileglob: ../roles/files/{{ vob_name }}/{{app_name}}/{{version_number}}/config/*.j2

it started working.

**Comment by jimi-c** [comment] 2015-09-05 12:04
@robinrocky ahh ok, so it appears that we may not be flattening the list in the action plugin correctly there. I'll look into that and see if I can reproduce it now.

**Comment by chrrrles** [comment] 2015-10-05 14:05
I am unable to reproduce the issue with variables not getting resolved in `with_fileglob` using this playbook:

```
- hosts: localhost
  gather_facts: no
  vars:
    my_path: "./0"
    sub_path: "1"
  tasks:
  - debug: msg="file is {{item}}"
    with_fileglob:  "{{ my_path }}/{{ sub_path }}/*"
  - debug: msg="file is {{item}}"
    with_fileglob:  
      - "{{ my_path }}/{{ sub_path }}/*"
```

Both of the debug tasks here produce the expected results.   Going to mark this as pending closure for now.

**Comment by jimi-c** [comment] 2015-10-12 15:47
Hi @robinrocky, as there has not been any follow-up in a week, we're going to go ahead and close this now, as we were not able to reproduce the issue.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-10-12 15:47 UTC
Labels: pending_action, bug
