### ISSUE TITLE
Feature: Collections search path in playbook for lookups, filters and tests (like for modules/roles)

### ISSUE THREAD

**Issue by cognifloyd** [ansible/ansible#61871] opened 2019-09-05 17:07 UTC
##### SUMMARY
Please extend the collections search path so that lookups, filters, and tests can also be referenced without a namespace in a playbook.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
collections search path in playbook for lookups, filters and tests

##### ADDITIONAL INFORMATION
Collections allow for bundling/distributing many different kinds of plugins.
To simplify using collections, the `collections` key allows play-level definition of a "search path/order" for which collections can provide un-namespaced actions, modules, and roles during the play.

Please also provide the same collections-searching behavior for lookups, filters, and tests (ie plugin types that are directly referenced within a playbook).

```yaml
- hosts: all
  collections:
   - my_namespace.my_collection
  tasks:
    - import_role:
        name: role1

    - mymodule:
        option1: value

    - debug:
        msg: '{{ lookup("lookup1", 'param1')| filter1 }}'
```
(example based on the example from https://docs.ansible.com/ansible/devel/dev_guide/collections_tech_preview.html#using-collections )

**Comment by cognifloyd** [comment] 2019-09-05 17:11
For lookups, I think only `lookup()` and `q()` need to support collections, and therefore, only those need the collections search path support for lookups. `with_*` is legacy (superseded by `loop`) and should only work with the lookups provided directly by ansible.

**Comment by sivel** [comment] 2019-09-09 14:54
!component =lib/ansible/utils/collection_loader.py

**Comment by nitzmahone** [comment] 2019-09-13 18:35
This was originally my plan when building namespacing and collections support- I played with a few different implementations though, and it turns out that for most real-world content, at best, it would be confusing, and at worst, a total disaster that regresses several of the plugin loading issues collections want to solve. Basically, I can't come up with a sane way to do it without completely overhauling the way Ansible does templating (including the way templates/vars defined, so likely semantic changes, not just an implementation change).

Remember that Ansible templates are evaluated as late as possible (and multiple times), not when the containing var/value is defined. As such, we don't preserve the "context" in which they were set. With that in mind, consider the following:

inventory
```
myhost whatsmylookup={{ lookup('mylookup') }}
```

playbook1.yml
```
- hosts: myhost
  collections:
  - myns.mycoll
  tasks:
  - debug:
      msg: '{{ whatsmylookup }}'
  - include_role:
      name: somerole
```

roles/somerole/tasks/main.yml
```
- debug:
    msg: '{{ whatsmylookup }}'
```

The problem I'm trying to illustrate here is that the collections resolution context for an unqualified Jinja2 plugin referenced in a template would "float" throughout the execution of the playbook. The plugin that gets resolved (or not) would depend on the `collections` value that was set (or lack thereof) in the containing context (ie task, potentially affected by role/play/block/task `collections` keyword usage) where we actually render the template. This would totally fall apart on roles, for instance, since roles (by design) use the collections search list specified by the role author in the role metadata- they don't inherit the playbook's collections search list (can you imagine what a nightmare it'd be for role portability if they did?).

In this case, `whatsmylookup` will not be renderable by the inventory itself, since there's no collections search defined there to resolve `mylookup` from (nor any way to define one today). In `playbook1.yml`, it would resolve properly (assuming `myns.mycoll` contains a `mylookup` lookup plugin). In the role, it'll again fail to resolve/render, unless the role metadata `collections` keyword contained `myns.mycoll`, or if the role somehow inherited the parent context's collection search list. We didn't want to do it that way, because it makes it less predictable where a given role might resolve its plugins from, where right now, unresolved references are simply searched for in the role's defined list. It also doesn't make sense that you should have to alter a role/play collection search path to render arbitrary vars it might use from other sources.

We could've done it with something like a global config list of "default collections to search", but again, that's a big impediment for content portability. Instead of just "grab the content and make sure you have collections X Y and Z installed", now you'd have to also alter your config to put those collections on the list before that content would work properly. Not good...

So, sadly, for the foreseeable future, you'll likely have to fully-qualify Jinja2 plugin refs. I'm tempted to close this, just because we're trying to avoid keeping feature request "tracking issues" open for things that are unlikely to be implemented. If we end up doing something in the future where we revisit the way vars are implemented, it's something we'd want to look at again, but dunno if/when that's going to happen.

**Comment by s-hertel** [comment] 2020-12-11 15:54
Closing as per above

**Closed as completed by s-hertel** 2020-12-11 15:54 UTC
Labels: support:core, feature, collection, affects_2.10
