### ISSUE TITLE
redhat_subscription.py

### ISSUE THREAD

**Issue by eduardocalfaia** [ansible/ansible#25965] opened 2017-06-21 13:55 UTC
##### ISSUE TYPE

 - Feature Idea

##### ANSIBLE VERSION

```
ansible 2.4.0
  config file = None
  configured module search path = ['/Users/ecosta/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible-2.4.0-py3.6.egg/ansible
  executable location = build/scripts-3.6/ansible
  python version = 3.6.0 (default, Dec 24 2016, 08:01:42) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]

```

##### OS / ENVIRONMENT

running on Mac
managing Redhat
##### SUMMARY

Does it possible add the option --auto-attach?
##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by Akasurde** [comment] 2017-06-21 14:51
@eduardocalfaia Thanks for reporting this issue. There is already one issue filed before - #23014

**Comment by eduardocalfaia** [comment] 2017-06-21 15:54
Thanks @Akasurde.

**Comment by eduardocalfaia** [comment] 2017-06-21 16:16
Was it implemented @Akasurde ? I didn't find out.

**Comment by Akasurde** [comment] 2017-06-21 16:49
@eduardocalfaia The PR #23034 is under review process, you can try this patch and provide feedback on PR.

**Comment by s-hertel** [comment] 2017-06-21 20:07
Closing since this is a duplicate of #23014.

**Closed as completed by s-hertel** 2017-06-21 20:07 UTC
Labels: affects_2.4, feature
