### ISSUE TITLE
ignore_errors is using the wrong context for its j2 expansions

### ISSUE THREAD

**Issue by jan-grant** [ansible/ansible#12306] opened 2015-09-10 12:15 UTC
##### Summary:

defaults are not being evaluated by tasks in ignore_errors. Those defaults appear to be more-or-less pulled in correctly.

Variable behaviour for this is very broken.
##### Steps To Reproduce:

Run `ansible-playbook broken-default.yml` with this:

```
# broken-default.yml

---
- hosts: localhost
  connection: local
  roles:
    - broken-defaults
  tasks:
    - name: display default value of x
      debug:
        var: x
    - name: this one should work
      include: roles/broken-defaults/tasks/test.yml
      vars:
        x: yes
    - name: display default value of x again
      debug:
        var: x
    - name: this one breaks!
      include: roles/broken-defaults/tasks/test.yml
```

```
# roles/broken-defaults/defaults/main.yml
x: no
```

```
# roles/broken-defaults/tasks/test.yml
- include: _test.yml
```

```
# roles/broken-defaults/tasks/_test.yml
- name: value of x within _test (works)
  debug:
    var: x

- command: /bin/echo {{ x }}
  register: result
   # works

- name: value of x as expanded by 'command' (works)
  debug:
    var: result.stdout

- command: /bin/false
  ignore_errors: x
  # also breaks:
  # ignore_errors: "{{ x }}"
```
##### Expected Results:

I'd expect the error to be ignored (or not) appropriately.
##### Actual Results:

With an explicit value of 'x' passed in, the playbook works. When it tries to use the default value, however, the expression is incorrectly evaluated:

```
% ansible-playbook broken-default.yml
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [display default value of x] ******************************************** 
ok: [localhost] => {
    "var": {                                                                                                                                                                
        "x": "x"                                                                                                                                                            
    }                                                                                                                                                                       
}                                                                                                                                                                           

TASK: [value of x within _test] *********************************************** 
ok: [localhost] => {
    "var": {                                                                                                                                                                
        "x": "True"                                                                                                                                                         
    }                                                                                                                                                                       
}                                                                                                                                                                           

TASK: [command /bin/echo True] ************************************************ 
changed: [localhost]

TASK: [value of x as expanded by 'command'] *********************************** 
ok: [localhost] => {
    "var": {
        "result.stdout": "True"
    }
}

TASK: [command /bin/false] **************************************************** 
failed: [localhost] => {"changed": true, "cmd": ["/bin/false"], "delta": "0:00:00.001708", "end": "2015-09-10 13:08:26.668993", "rc": 1, "start": "2015-09-10 13:08:26.667285", "warnings": []}
...ignoring

TASK: [display default value of x again] ************************************** 
ok: [localhost] => {
    "var": {
        "x": "False"
    }
}

TASK: [value of x within _test] *********************************************** 
ok: [localhost] => {
    "var": {
        "x": "False"
    }
}

TASK: [command /bin/echo {{ x }}] ********************************************* 
changed: [localhost]

TASK: [value of x as expanded by 'command'] *********************************** 
ok: [localhost] => {
    "var": {
        "result.stdout": "False"
    }
}

TASK: [command /bin/false] **************************************************** 
ERROR: error while evaluating conditional: x
```

Replacing the bare "x" with "{{ x }}" in the ignore_errors line also produces a similar error - this one with a traceback:

```
% ansible-playbook broken-default.yml
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [display default value of x] ******************************************** 
ok: [localhost] => {
    "var": {
        "x": "x"
    }
}

TASK: [value of x within _test] *********************************************** 
ok: [localhost] => {
    "var": {
        "x": "True"
    }
}

TASK: [command /bin/echo True] ************************************************ 
changed: [localhost]

TASK: [value of x as expanded by 'command'] *********************************** 
ok: [localhost] => {
    "var": {
        "result.stdout": "True"
    }
}

TASK: [command /bin/false] **************************************************** 
failed: [localhost] => {"changed": true, "cmd": ["/bin/false"], "delta": "0:00:00.001142", "end": "2015-09-10 13:13:02.228363", "rc": 1, "start": "2015-09-10 13:13:02.227221", "warnings": []}
...ignoring

TASK: [display default value of x again] ************************************** 
ok: [localhost] => {
    "var": {
        "x": "False"
    }
}

TASK: [value of x within _test] *********************************************** 
ok: [localhost] => {
    "var": {
        "x": "False"
    }
}

TASK: [command /bin/echo {{ x }}] ********************************************* 
changed: [localhost]

TASK: [value of x as expanded by 'command'] *********************************** 
ok: [localhost] => {
    "var": {
        "result.stdout": "False"
    }
}

TASK: [command /bin/false] **************************************************** 
Traceback (most recent call last):
  File "/tmp/foo/bin/ansible-playbook", line 324, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/tmp/foo/bin/ansible-playbook", line 264, in main
    pb.run()
  File "/tmp/foo/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 348, in run
    if not self._run_play(play):
  File "/tmp/foo/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 789, in _run_play
    if not self._run_task(play, task, False):
  File "/tmp/foo/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 493, in _run_task
    task.ignore_errors =  utils.check_conditional(cond, play.basedir, task.module_vars, fail_on_undefined=C.DEFAULT_UNDEFINED_VAR_BEHAVIOR)
  File "/tmp/foo/lib/python2.7/site-packages/ansible/utils/__init__.py", line 265, in check_conditional
    conditional = template.template(basedir, conditional, inject, fail_on_undefined=fail_on_undefined)
  File "/tmp/foo/lib/python2.7/site-packages/ansible/utils/template.py", line 122, in template
    varname = template_from_string(basedir, varname, templatevars, fail_on_undefined)
  File "/tmp/foo/lib/python2.7/site-packages/ansible/utils/template.py", line 371, in template_from_string
    res = jinja2.utils.concat(rf)
  File "<template>", line 8, in root
  File "/tmp/foo/lib/python2.7/site-packages/jinja2/runtime.py", line 489, in _fail_with_undefined_error
    raise self._undefined_exception(hint)
jinja2.exceptions.UndefinedError: 'x' is undefined
```

(I note that the default appears to be initially invisible in the top-level playbook, too, but that's less of an issue as long as it's available deeper in playbook evaluation.)

Most calls to check_conditional appear idiomatially to use "inject" rather than "task.module_vars" directly.

**Comment by bcoca** [comment] 2015-09-10 13:20
are you trying to apply a role defaults/main.yml during an include?

**Comment by jan-grant** [comment] 2015-09-10 15:12
In this example, yes, but I think that's irrelevant. (FWIW the same behaviour fails with a vars/main.yml)

**Comment by bcoca** [comment] 2015-09-10 15:24
closing as dupe of  #12303, this bug was just recently introduced.

**Closed as completed by bcoca** 2015-09-10 15:24 UTC
