### ISSUE TITLE
Setting dynamic 'become' doesn't work

### ISSUE THREAD

**Issue by Tahvok** [ansible/ansible#11381] opened 2015-06-25 08:49 UTC
I have some systems that I need to run some tasks with an escalated privileges, and on some of the systems not:
So I did the following:

An example:

``` yaml
- name: create directory
  file:
    path: "/path/test"
    state: directory
  become: "{{ app_become }}"
  become_user: my_user
```

I run it with --extra_vars "app_become=yes"
It will fail with this error:

> failed: [hostname] => {"failed": true, "parsed": false}
>  Traceback (most recent call last):
>   File "/root/.ansible/tmp/ansible-tmp-1435221345.83-73209898619316/file", > line 2000, in <module>
>     main()
>   File "/root/.ansible/tmp/ansible-tmp-1435221345.83-73209898619316/file", line 279, in main
>     os.mkdir(curpath)
> OSError: [Errno 13] Permission denied: '/path/test'
> OpenSSH_6.8p1, OpenSSL 1.0.2c 12 Jun 2015
> debug1: Reading configuration data /home/albert/.ssh/config
> debug1: /home/albert/.ssh/config line 232: Applying options for hostname
> debug1: Reading configuration data /etc/ssh/ssh_config
> debug1: auto-mux: Trying existing master
> debug2: fd 3 setting O_NONBLOCK
> debug2: mux_client_hello_exchange: master version 4
> debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
> debug3: mux_client_request_session: entering
> debug3: mux_client_request_alive: entering
> debug3: mux_client_request_alive: done pid = 5042
> debug3: mux_client_request_session: session request sent
> debug1: mux_client_request_session: master session id: 2
> debug3: mux_client_read_packet: read header failed: Broken pipe
> debug2: Received exit status from master 0
> Shared connection to x.x.x.x closed.
> 
> FATAL: all hosts have already failed -- aborting

However if I explicitly set become like so:

``` yaml
- name: create directory
  file:
    path: "/path/test"
    state: directory
  become: yes
  become_user: my_user
```

It will run successfuly

**Comment by bcoca** [comment] 2015-06-25 13:55
what version of ansible?

**Comment by Tahvok** [comment] 2015-06-28 07:21
1.9.1

I have spoken a couple of days ago on IRC, with two guys. I don't have the history, but the problem was on this row:
https://github.com/ansible/ansible/blob/stable-1.9/lib/ansible/playbook/task.py#L166

The second guy made more tests, including latest devel:
https://gist.github.com/halberom/2ce3ef64dc1a5a3a5550

As I understand the problem in latest devel is partially fixed. If you set your variable to 'False' it will work, but if you set it to 'no' or 'false' it will treat it as 'true' instead.

**Comment by jimi-c** [comment] 2015-07-21 06:19
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a simple reproducer:

<pre>
# cat 11381.yml 
- hosts: awxlocal
  gather_facts: no
  tasks:
  - command: whoami
    become: yes
    become_user: "{{become_user}}"
# ansible-playbook -vv 11381.yml -e become_user=testing
Using /etc/ansible/ansible.cfg as config file
1 plays in 11381.yml
PLAY ****************************************************************************
TASK [command] ******************************************************************
changed: [awxlocal] => {"changed": true, "cmd": ["whoami"], "delta": "0:00:00.003209", "end": "2015-07-21 02:18:44.524430", "rc": 0, "start": "2015-07-21 02:18:44.521221", "stderr": "", "stdout": "testing", "stdout_lines": ["testing"], "warnings": []}
PLAY RECAP **********************************************************************
awxlocal                   : ok=1    changed=1    unreachable=0    failed=0   
</pre>

Per our normal policy, we close bug report issues when we see the issue has been corrected in the devel branch, so we will close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by serverhorror** [comment] 2015-07-21 09:24
@jimi-c You reproduced the wrong thing:

Original piece of yaml:

```
- name: create directory
  file:
    path: "/path/test"
    state: directory
  become: "{{ app_become }}" ## <<< here's a dynamic 'become'
  become_user: my_user
```

Your piece of yaml:

```
- hosts: awxlocal
  gather_facts: no
  tasks:
  - command: whoami
    become: yes
    become_user: "{{become_user}}"  ## <<< here's a dynamic 'become_user'
```

**Comment by Tahvok** [comment] 2015-07-21 10:56
I have posted on mailing list: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/ansible-project/8t4dgRjE9p8/sveuCQc0ECYJ

**Comment by jimi-c** [comment] 2015-07-21 12:24
@serverhorror my apologies, however that works as well:

<pre>
- hosts: awxlocal
  gather_facts: no
  remote_user: testing
  tasks:
  - command: whoami
  - command: whoami
    become: "{{become}}"
    #become_user: "{{become_user}}"
changed: [awxlocal] => {"changed": true, "cmd": ["whoami"], "delta": "0:00:00.001495", "end": "2015-07-21 08:24:01.973195", "rc": 0, "start": "2015-07-21 08:24:01.971700", "stderr": "", "stdout": "testing", "stdout_lines": ["testing"], "warnings": []}
changed: [awxlocal] => {"changed": true, "cmd": ["whoami"], "delta": "0:00:00.002126", "end": "2015-07-21 08:22:26.374697", "rc": 0, "start": "2015-07-21 08:22:26.372571", "stderr": "", "stdout": "root", "stdout_lines": ["root"], "warnings": []}
</pre>

As you can see in the first output, the user remains the remote_user, but for the second the user has switched to root.

**Comment by jimi-c** [comment] 2015-07-21 12:31
Reopening based on the example shown in the ML thread.

**Comment by serverhorror** [comment] 2015-07-21 13:03
I think the issue is that `-e become=no` evaluates to `True`. This is confusing to users althou from a language perspective correct that is not what users are expecting

**Comment by Tahvok** [comment] 2015-07-21 13:29
Only setting it to 'False' works (upper 'F'):
$ ansible-playbook 11381.yml  -vv -e app_become=false

```
Using /home/albert/ansible/ansible.cfg as config file
1 plays in 11381.yml

PLAY ****************************************************************************

TASK [command] ******************************************************************
changed: [antest] => {"changed": true, "cmd": ["whoami"], "delta": "0:00:00.002938", "end": "2015-07-21 16:22:01.738630", "rc": 0, "start": "2015-07-21 16:22:01.735692", "stderr": "", "stdout": "my_user", "stdout_lines": ["my_user"], "warnings": []}

PLAY RECAP **********************************************************************
antest                     : ok=1    changed=1    unreachable=0    failed=0
```

$ ansible-playbook 11381.yml  -vv -e app_become=False

```
Using /home/albert/ansible/ansible.cfg as config file
1 plays in 11381.yml

PLAY ****************************************************************************

TASK [command] ******************************************************************
changed: [antest] => {"changed": true, "cmd": ["whoami"], "delta": "0:00:00.002432", "end": "2015-07-21 16:22:05.866374", "rc": 0, "start": "2015-07-21 16:22:05.863942", "stderr": "", "stdout": "root", "stdout_lines": ["root"], "warnings": []}

PLAY RECAP **********************************************************************
antest                     : ok=1    changed=1    unreachable=0    failed=0
```

**Comment by bcoca** [comment] 2015-07-21 14:14
you should really not use variables that are the same as directives

**Closed as completed** 2015-07-21 16:15 UTC
Labels: P2, bug

**Comment by jimi-c** [comment] 2015-07-21 16:20
Ok, the above commit should resolve this now. In my testing using the above:

<pre>
# ansible-playbook -vv 11381.yml -e "become=no"
Using /etc/ansible/ansible.cfg as config file
1 plays in 11381.yml
PLAY ****************************************************************************
TASK [command] ******************************************************************
changed: [awxlocal] => {"changed": true, "cmd": ["whoami"], "delta": "0:00:00.001425", "end": "2015-07-21 12:20:12.406425", "rc": 0, "start": "2015-07-21 12:20:12.405000", "stderr": "", "stdout": "testing", "stdout_lines": ["testing"], "warnings": []}
TASK [command] ******************************************************************
changed: [awxlocal] => {"changed": true, "cmd": ["whoami"], "delta": "0:00:00.001428", "end": "2015-07-21 12:20:13.659379", "rc": 0, "start": "2015-07-21 12:20:13.657951", "stderr": "", "stdout": "testing", "stdout_lines": ["testing"], "warnings": []}
PLAY RECAP **********************************************************************
awxlocal                   : ok=2    changed=2    unreachable=0    failed=0   
</pre>

Note both outputs show the user is `testing`.
