### ISSUE TITLE
Memory allocation error while using include_task

### ISSUE THREAD

**Issue by cesarfn4** [ansible/ansible#36050] opened 2018-02-12 17:26 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
include and include_tasks

##### ANSIBLE VERSION
```
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION
No change

##### SUMMARY
If I run a playbook importing many tasks with "include_tasks" (ansible-loop_include_tasks.tar.gz), it hangs with the error:
```
OSError: [Errno 12] Cannot allocate memory
```
However, if I run the same playbook with "include" (ansible-loop_include.tar.gz) instead of "include_tasks", it finishes successfully.

##### STEPS TO REPRODUCE
Attached the following playbooks to replicate this:

- Using "include_tasks":
[ansible-loop_include_tasks.tar.gz](https://github.com/ansible/ansible/files/1717114/ansible-loop_include_tasks.tar.gz)

- Using "include":
[ansible-loop_include.tar.gz](https://github.com/ansible/ansible/files/1717113/ansible-loop_include.tar.gz)

##### EXPECTED RESULTS
Both of playbooks finishes correctly.

##### ACTUAL RESULTS
When I ran the playbook with "include_tasks" (ansible-loop_include_tasks.tar.gz), I am getting the following error:
```
TASK [loop : Hello Message] ******************************************************************************************************************************************************************
task path: /home/vagrant/ansible-projects/ansible-loop/loop/tasks/hello-world-32.yml:2
ERROR! Unexpected Exception, this is probably a bug: [Errno 12] Cannot allocate memory
the full traceback was:

Traceback (most recent call last):
  File "/bin/ansible-playbook", line 106, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 122, in run
    results = pbex.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 154, in run
    result = self._tqm.run(play=play)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 290, in run
    play_return = strategy.run(iterator, play_context)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/linear.py", line 277, in run
    self._queue_task(host, task, task_vars, play_context)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 254, in _queue_task
    worker_prc.start()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/usr/lib64/python2.7/multiprocessing/forking.py", line 121, in __init__
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

**Comment by sivel** [comment] 2018-02-12 17:28
This is a duplicate of the already resolved https://github.com/ansible/ansible/issues/35796

**Closed as completed by sivel** 2018-02-12 17:28 UTC
