### ISSUE TITLE
win_template has copy issues when templated file has #!powershell in it

### ISSUE THREAD

**Issue by thegatsbylofiexperience** [ansible/ansible#13368] opened 2015-12-01 04:21 UTC
Issue Type: Bug Report
Ansible Version: ansible 1.9.4
Ansible Configuration: No changes from original

Environment: Ubuntu 14.04 and CentOS 6.6 (Hosts) Win 7 (managed computer)

Summary:
Including a powershell shebang (#!powershell) in a template causes ansible to give the source filename in the temp directory (in C:/Users/<username>/AppData/Local/temp/<ansible task temporary dir>) a .ps1 extension (source.ps1 instead of source), and thus the file cannot be copied to its intended destination as win_copy.ps1 cannot find it.

Expected Results:
Temporary file called "source".
File copied to its destination.

Actual Results:
Temporary file called "source.ps1"
File not copied to its destination.

Thanks!

**Comment by jhawkesworth** [comment] 2015-12-01 08:46
A workaround would be to use the script module and pass the parameters you need as arguments to the script.

There are examples of how to pass arguments to the script module in the integration tests here:  https://github.com/ansible/ansible/blob/devel/test/integration/roles/test_win_script/tasks/main.yml

**Comment by jimi-c** [comment] 2015-12-01 15:47
There were quite a few improvements to win_template in devel/stable-2.0 as well, is this still an issue there @jhawkesworth ?

**Comment by cchurch** [comment] 2015-12-01 19:38
Caused by https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/connection/winrm.py#L304 (thanks @nitzmahone for the comment).  PowerShell will only run a file with the `.ps1` extension, but we load the module without any extension.

We might be able to fix it by adding the `.ps1` extension to the module name before we try to find/load it (https://github.com/ansible/ansible/blob/devel/lib%2Fansible%2Fplugins%2Faction%2F__init__.py#L106).

**Comment by nitzmahone** [comment] 2015-12-01 22:05
# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Closed as completed by nitzmahone** 2015-12-01 22:05 UTC
Labels: windows, bug
