### ISSUE TITLE
async task with poll set to 0 fails when it is skipped

### ISSUE THREAD

**Issue by jasonarewhy** [ansible/ansible#7432] opened 2014-05-16 18:15 UTC
##### Ansible Version:

1.6.1, devel
##### Environment:

Centos 6.5, OS X 10.9.2
##### Summary:

An async task with 'poll: 0' fails only when the 'when' condition causes it to be skipped. If I remove the poll option or set it to a number higher than 0, the task is successfully skipped. If I remove the 'when' condition, the async task is successful with 'poll' set to 0.
##### Steps To Reproduce:

Create an async task with 'poll: 0' and a when condition that causes it to be skipped.

```
- name: test
  hosts: localhost

  tasks:
    - name: a local task
      shell: echo hello
      async: 30
      poll: 0
      when: a_variable is defined
```
##### Expected Results:

The async task should be skipped.
##### Actual Results:

```
TASK: [a local task] **********************************************************
skipping: [localhost]
Traceback (most recent call last):
  File "/Users/jyoung/lib/ansible-main/bin/ansible-playbook", line 317, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/Users/jyoung/lib/ansible-main/bin/ansible-playbook", line 257, in main
    pb.run()
  File "/Users/jyoung/lib/ansible-main/lib/ansible/playbook/__init__.py", line 319, in run
    if not self._run_play(play):
  File "/Users/jyoung/lib/ansible-main/lib/ansible/playbook/__init__.py", line 673, in _run_play
    if not self._run_task(play, task, False):
  File "/Users/jyoung/lib/ansible-main/lib/ansible/playbook/__init__.py", line 449, in _run_task
    results = self._run_task_internal(task)
  File "/Users/jyoung/lib/ansible-main/lib/ansible/playbook/__init__.py", line 413, in _run_task_internal
    self.runner_callbacks.on_async_ok(host, res, poller.runner.vars_cache[host]['ansible_job_id'])
KeyError: 'ansible_job_id'
```

**Comment by mpdehaan** [comment] 2014-06-01 15:32
"An async task with 'poll: 0' fails only when the 'when' condition causes it to be skipped"

I think you mean something totally different here, that it fails with a traceback and the when condition isn't evaluated.

**Comment by jasonarewhy** [comment] 2014-06-01 15:40
You are correct in that by 'fail' I meant ansible exits with a traceback. However, it does appear the when condition is being evaluated (at least partially) since I am seeing 'skipping: [localhost]' just before the traceback.

The traceback only occurs when poll is 0 and the when condition would cause the task to be skipped.

**Comment by hfinucane** [comment] 2014-06-03 21:18
Indeed. Here is a minimal test case:

```
---
- hosts: localhost
  tasks:
  - action: shell /bin/true 
    async: 15
    poll: 0
    when: False
```

**Comment by adamhadani** [comment] 2014-06-17 20:35
Question - removing the poll option altogether circumvents this bug, but will it achieve the same behaviour as if 'poll: 0' was specified (in the scenario described by this bug, e.g having a when clause with a condition that would cause task to be skipped).
If so it's an easy way to avoid this bug until is fixed, trying to figure out best solution for now, thanks!

**Comment by hfinucane** [comment] 2014-06-17 21:22
It will not. `poll: 0` means that the task is run in the background with no particular timeout, it will finish when it finishes. Occasionally this is important.

Another possible substitute is running the async task as a handler, which means you can keep the conditional elsewhere so ansible doesn't break. This brings other complications- do you flush your handlers now? How expensive will that be time wise? Is it OK if your task gets started at the end?

**Comment by gplasky** [comment] 2014-07-14 17:36
Ran into this same bug in 1.6.6. My situation is slightly different (I am using a non-zero `poll`) but I think the root cause is the same (I saw an identical traceback to the above).

```
    - name: Restart Tomcat
      service: name=tomcat state=restarted
      # This comes from a previous task, was == 2 in my problem run (Tomcat was restarted)
      when: result.rc == 2 or force
      register: tomcat

    - name: Waiting for Tomcat to start
      wait_for: port=8080 delay=10 timeout=60
      when: tomcat.changed

    - name: Verify proper operation of webapp
      local_action: uri url="http://{{ inventory_hostname }}:1234/somepage" status_code=200
        timeout=30 return_content=yes
      when: tomcat.changed
      async: 30
      poll: 5
      register: status_page
      failed_when: "'some_string' not in status_page.content"
      changed_when: False
```

FWIW I was running this task across three hosts and only one of the three triggered the bug.

**Comment by jasiedu** [comment] 2014-07-23 17:09
Anyone, knows the work around for this issue?

**Comment by tom--** [comment] 2014-07-26 17:41
`poll:` can be a string so a workaround:

```
poll: "{( 0 if <condition> else 10 }}"
```

**Comment by jasiedu** [comment] 2014-07-26 21:00
I don't see how this is a workaround. I don't want the process to run at all if the condition is True.
In your workaround it will run regardless of the condition. In one case it will be fire-and-forget. In the other case it will poll every x seconds.

**Comment by tom--** [comment] 2014-07-27 00:21
@jasiedu I didn't suggest removing the `when` property.

**Comment by jimi-c** [comment] 2014-09-11 17:54
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed** 2014-09-11 17:54 UTC
Labels: bug
