### ISSUE TITLE
Powershell scripts that use Start-Job fail on Ansible 2.0+

### ISSUE THREAD

**Issue by ZahiCahana** [ansible/ansible#15770] opened 2016-05-08 15:17 UTC
##### ISSUE TYPE

- Bug Report

[dacpac.txt](https://github.com/ansible/ansible/files/253976/dacpac.txt)
##### ANSIBLE VERSION

```
<!--- Paste verbatim output from “ansible --version” between quotes -->
ansible 2.0.1.0
```
##### SUMMARY

task that work in ansible 1.9.4 not working in 2.0  
(TASK [dbonline : Run dacpac on Infra_Telephony, JajahCore, jajah, jajahccsc, jajahbilling, JajahSupportTool DBs] ***)

failed with error below 
failed: [rndv-ci1-con02] => (item=default) => {"failed": true, "invocation": {"module_name": "dacpac"}, "item": "default", "msg": "*****_Action=Publish DacPackPackage=E:\temp\workarea\rndv-ci1-con02\dbonline-10.18.0-SNAPSHOT\dbonline\schemas\Jajah.dacpac,E:\temp\workarea\rndv-ci1-con02\dbonline-10.18.0-SNAPSHOT\dbonline\schemas\JajahCore.dacpac,E:\temp\workarea\rndv-ci1-con02\dbonline-10.18.0-SNAPSHOT\dbonline\schemas\Infra_Telephony.dacpac,E:\temp\workarea\rndv-ci1-con02\dbonline-10.18.0-SNAPSHOT\dbonline\schemas\JajahCcsc.dacpac,E:\temp\workarea\rndv-ci1-con02\dbonline-10.18.0-SNAPSHOT\dbonline\schemas\jajahbilling.dacpac,E:\temp\workarea\rndv-ci1-con02\dbonline-10.18.0-SNAPSHOT\dbonline\schemas\JajahSupportTool.dacpac SqlServer=rndv-ci1-con02 DBInstancePort=1500**_*****_**Job has failed: The background process reported an error with the following message: Cannot process an element with node type \"Text\". Only Element and EndElement node types are supported.   at System.Management.Automation.Remoting.OutOfProcessUtils.ProcessData(String data, DataProcessingDelegates callbacks). [localhost] The background process reported an error with the following message: Cannot process an element with node type \"Text\". Only Element and EndElement node types are supported.   at System.Management.Automation.Remoting.OutOfProcessUtils.ProcessData(String data, DataProcessingDelegates callbacks). ScriptHalted ScriptHalted ScriptHalted ScriptHalted ScriptHalted dacpak failed with exitcode  *__"}_*
### STEPS TO REPRODUCE

```
<!--- Paste example playbooks or commands between quotes -->
```

##### ACTUAL RESULTS

```
<!--- Paste verbatim command output between quotes -->
```

**Comment by jhawkesworth** [comment] 2016-05-08 16:43
Ansible 2.0 enforces powershell strict mode for windows modules, this is the most likely cause of your failures.  See https://technet.microsoft.com/en-us/library/hh849692.aspx?f=255&MSPPError=-2147217396

Once you have modified your code for compliance with strict mode, if you still having problems, please ask on the ansible-project google group or #ansible irc channel.

Closing this so we can keep the github issue tracker for ansible defects.

**Comment by ZahiCahana** [comment] 2016-05-09 08:13
thanks
i forgot to tell that i set in all relevant places (powershell.ps1
,powershell.oy) , winrm.py - Set-StrictMode -Off  and it still happens.

Best regards
zahi

**Comment by ZahiCahana** [comment] 2016-05-09 08:38
hi,
i also saw the in your modules (win_get_url.ps1 ,win_acl.ps1
 ,win_environment.ps1 ,win_iis_webbinding.ps1
,win_scheduled_task.ps1,win_unzip.ps1) you set it to off so why we can't do
it to our code?

thanks
zahi

**Comment by jhawkesworth** [comment] 2016-05-09 19:48
You can turn of strict mode in your modules.  But since ansible 2.0 expects
that modules will comply with strict mode, it is most likely the cause of
why your module is not working after upgrading from 1.9.4.

**Comment by nitzmahone** [comment] 2016-06-22 22:37
We've had other reports of this problem as well- I narrowed it down to a change that occurred with 2.0 where we're setting the WinRM codepage to UTF-8 (65001) in 2.x so we can properly handle any non-ASCII input, where in 1.x it was hardcoded to Western European (437). It appears that Powershell's background job API is busted under the UTF-8 codepage. You can reproduce this outside of Ansible by opening cmd.exe and running the following:

```
chcp 65001
powershell
(run your script here)
```

We're going to look into options here, but it appears to be a Microsoft bug, and a lot more things are broken for international text by having a non-UTF-8 codepage (thus we're probably not going to switch back to the pre-2.0 behavior), so I'm not really optimistic at this point.

**Comment by nitzmahone** [comment] 2016-06-23 00:10
I've created a Uservoice issue for this, feel free to upvote at: https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/14915283-job-cmdlets-fail-with-utf-8-codepage

**Comment by nitzmahone** [comment] 2016-06-24 00:33
Someone's already posted a workaround on the Uservoice page that switches the InputEncoding to not expect a BOM; that fixes the standalone case, I just need to try plugging that into our shell setup, but hopefully should work great!

**Closed as completed** 2017-03-24 07:02 UTC
Labels: windows, affects_2.0, affects_2.1, affects_2.2, bug
