### ISSUE TITLE
Revisiting realtime stdout/stderr

### ISSUE THREAD

**Issue by PeterMartini** [ansible/ansible#17350] opened 2016-09-01 15:18 UTC
##### ISSUE TYPE

- Feature Idea
##### COMPONENT NAME

Realtime stdout/stderr capture
##### ANSIBLE VERSION

devel
##### OS / ENVIRONMENT

Various *nix
##### SUMMARY

I'd like to revisit #3887, collecting realtime stdout/stderr.  The last comment there pointed out the difficulties of feeding the output back to the ansible command layer, which I fully understand, so I have a counterproposal (and a prototype at https://github.com/PeterMartini/ansible/tree/ansible-tmp) - if stdout/stderr are buffered to disk alongside a copy of the python wrapper script ansible uses to actually execute its tasks (on *nix), then that data becomes available for an out-of-band process to pull back and examine the data.

With the branch referenced, a trivial callback plugin can be created to capture the task UUID for each host at the time the task is started, and use that UUID to derive the path where stdout/stderr will be buffered on the remote system.  With that information, stdout and stderr can be checked in realtime either manually or via a separate set of scripts.

If this makes sense, I'd like to work with whoever's interested to get that branch sufficiently polished to create a PR, review, and merge.

**Comment by ChristianTacke** [comment] 2016-09-01 17:28
2.1 added this: "Added facility for modules to send back 'diff' for display when ansible is called with --diff, updated several modules to return this info"
So returning some data seems to be possible.

**Comment by PeterMartini** [comment] 2016-09-01 20:21
If I run ansible with -vvv (offhand, I don't know which verbosity level is needed, I just like that one) its clear stdout/stderr are returned, they're just returned too late (meaning only after the process has finished).  The diff flag similarly only returns when the process is finished, which doesn't help where I need it (checking whether a long running process is stuck).

When I get back to a computer, I'll post more details of where/how this is useful (including a sample callback)

**Comment by PeterMartini** [comment] 2016-09-02 12:22
Bah, I did some more testing, and discovered there are at least two issues:
1. The callback is only called once at the start of each task, not once per (task, host)
2. The uuid similarly is for the task, so any kind of `local_action`would end up sharing the same directory

**Comment by bcoca** [comment] 2016-09-02 13:57
The issue is much deeper than that, the task ONLY returns info to the Ansible controller AFTER it has ended. 

I have a `update_json` proposal that would allow for tasks to return data DURING execution but it has many hurdles to get through before being viable.  

https://github.com/bcoca/ansible/tree/update_json

Once this facility exists, then we can have each module implement it.

**Comment by PeterMartini** [comment] 2016-09-02 14:32
@bcoca But that's the point - I'm not looking to return the data to Ansible before it's done, I just want it to be available on the remote host.  If stdout/stderr are available on disk on the host in realtime, then the challenges involved in returning it can be side-stepped by using an out-of-band mechanism to return output.

**Comment by bcoca** [comment] 2016-09-02 14:34
they aren't unless you are doing some custom redirection

**Comment by PeterMartini** [comment] 2016-09-02 14:44
Having a common facility for that redirection is the request here :-)

**Comment by dagwieers** [comment] 2016-09-05 16:19
Look at shmux for ideas on how to have an interactive/real-time interface to parallel background jobs.
shmux lets you list jobs, and kill them all while they are being processed. At least if something hangs you can relate it immediately to a specific host.

**Comment by samdoran** [comment] 2019-06-21 15:31
Closing since this is resolved by #13620.

**Comment by dagwieers** [comment] 2019-06-23 21:39
@samdoran It is not resolved by #13620 as that PR has not been merged yet.

**Comment by dagwieers** [comment] 2019-06-23 21:40
resolved_by #13620

**Comment by bcoca** [comment] 2019-06-24 14:19
actually even if merged it does not resolve it, it creates the foundation to be able to resolve it But still closing as the following proposal supersedes this https://github.com/ansible/proposals/issues/92

**Closed as completed by bcoca** 2019-06-24 14:19 UTC
Labels: affects_2.2, affects_2.3, support:core, feature
