### ISSUE TITLE
notify: with_items

### ISSUE THREAD

**Issue by hryamzik** [ansible/ansible#14918] opened 2016-03-11 12:09 UTC
##### Issue Type:
- Bug Report
##### Ansible Version:

```
2.0.1.0
```
##### Ansible Configuration:

default
##### Summary:

`notify` and `with_items` do not work as expected
##### Steps To Reproduce:

Run any task with a list of items with notify, in my case I had only the last file changed

```
- name: put runit services files
  template: src={{ item.f }} dest=/etc/sv/{{ runit_service_name }}/{{ item.f }} owner=root group=root mode=0755
  with_items:
    - { f: run        , h: restart, s: "{{ runit_service_name }}" }
    - { f: log/run    , h: restart, s: "{{ runit_service_name }}/log" }
    - { f: log/config , h: hup    , s: "{{ runit_service_name }}/log" }
  notify: runit {{ item.h }} {{ item.s }} 
```
##### Expected Results:

For the last file changed I would expect to see handler `runit hup {{ runit_service_name }}/log` to be notified.
##### Actual Results:

`runit restart {{ runit_service_name }}` is triggered

**Comment by jimi-c** [comment] 2016-04-20 14:12
Hi @hryamzik, I have confirmed this issue is resolved in both devel and 2.0.2.0-1 (released yesterday), so I will close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2016-04-20 14:12 UTC
Labels: P2, bug
