### ISSUE TITLE
ansible_user does not resolve in with_items loops

### ISSUE THREAD

**Issue by momoneko** [ansible/ansible#17722] opened 2016-09-23 09:00 UTC
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

Playbook variables
##### ANSIBLE VERSION

```
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Ubuntu 16.04.1
##### SUMMARY

The `with_items` feature resolves `ansible_user` to none if `remote_user` is
not defined inside the playbook. It does resolve it correctly when
`remote_user` is defined.
##### STEPS TO REPRODUCE

Have a variable in the playbook that uses `ansible_user` and use it in a with_items context:

Note: `local_file` is set to /etc/hosts for ease of reproducibility. I'm trying to
copy a different file.

Hosts file:

```
192.168.33.11 ansible_user=vagrant
```

Playbook:

```
- hosts: all
  become: yes
  become_user: root
  # remote_user: vagrant
  vars:
      - project_root: /home/{{ ansible_user }}/project
      - remote_file: "{{ project_root }}/remote_file.crt"
      - local_file: /etc/hosts

  tasks:

    - name: check for ansible_user and file
      debug: msg="{{ ansible_user }} {{ remote_file }}"
    - name: check with_items debug
      debug: msg="{{ item.message }}"
      with_items:
          - { message: "{{ local_file }}" }
          - { message: "{{ remote_file }}" }

    - name: Copy files no with
      copy: src={{ local_file }} dest={{ remote_file }} mode=600

    - name: Copy files
      copy: src={{ item.src }} dest={{ item.dest }} mode=600
      with_items:
          - { src: "{{ local_file }}", dest: "{{ remote_file }}" }

```

##### EXPECTED RESULTS

Expected `remote_file` to resolve to `/home/vagrant/project/remote_file.crt`
when used inside `with_items`
##### ACTUAL RESULTS

`remote_file` resolves to `/home//project/remote_file.crt`

```
Using /etc/ansible/ansible.cfg as config file
Loaded callback default of type stdout, v2.0
1 plays in bug-setup.yml

PLAY ***************************************************************************

TASK [setup] *******************************************************************
<192.168.33.11> ESTABLISH SSH CONNECTION FOR USER: vagrant
<192.168.33.11> SSH: EXEC ssh -C -vvv -o ForwardAgent=yes -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 -tt 192.168.33.11 '( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1474621135.69-246203852514424 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1474621135.69-246203852514424 )" )'
<192.168.33.11> PUT /tmp/tmpjQnfoS TO /home/vagrant/.ansible/tmp/ansible-tmp-1474621135.69-246203852514424/setup
<192.168.33.11> SSH: EXEC sftp -b - -C -vvv -o ForwardAgent=yes -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 '[192.168.33.11]'
<192.168.33.11> ESTABLISH SSH CONNECTION FOR USER: vagrant
<192.168.33.11> SSH: EXEC ssh -C -vvv -o ForwardAgent=yes -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 -tt 192.168.33.11 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-prizlttckchfpzwoubucdhdepjxnstuw; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1474621135.69-246203852514424/setup; rm -rf "/home/vagrant/.ansible/tmp/ansible-tmp-1474621135.69-246203852514424/" > /dev/null 2>&1'"'"'"'"'"'"'"'"''"'"''
ok: [192.168.33.11]

TASK [check for ansible_user and file] *****************************************
task path: /home/dumitru/Public/ansible/ansible-tuto/step-00/bug-setup.yml:14
ok: [192.168.33.11] => {
    "msg": "vagrant /home/vagrant/project/remote_file.crt"
}

TASK [check with_items debug] **************************************************
task path: /home/dumitru/Public/ansible/ansible-tuto/step-00/bug-setup.yml:16
ok: [192.168.33.11] => (item={u'message': u'/etc/hosts'}) => {
    "invocation": {
        "module_args": {
            "msg": "/etc/hosts"
        }, 
        "module_name": "debug"
    }, 
    "item": {
        "message": "/etc/hosts"
    }, 
    "msg": "/etc/hosts"
}
ok: [192.168.33.11] => (item={u'message': u'/home//project/remote_file.crt'}) => {
    "invocation": {
        "module_args": {
            "msg": "/home//project/remote_file.crt"
        }, 
        "module_name": "debug"
    }, 
    "item": {
        "message": "/home//project/remote_file.crt"
    }, 
    "msg": "/home//project/remote_file.crt"
}

TASK [Copy files no with] ******************************************************
task path: /home/dumitru/Public/ansible/ansible-tuto/step-00/bug-setup.yml:22
<192.168.33.11> ESTABLISH SSH CONNECTION FOR USER: vagrant
<192.168.33.11> SSH: EXEC ssh -C -vvv -o ForwardAgent=yes -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 -tt 192.168.33.11 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-omjxcudbyjocbsvrxerksqbicjzxhmzv; rc=flag; [ -r /home/vagrant/project/remote_file.crt ] || rc=2; [ -f /home/vagrant/project/remote_file.crt ] || rc=1; [ -d /home/vagrant/project/remote_file.crt ] && rc=3; python -V 2>/dev/null || rc=4; [ x"$rc" != "xflag" ] && echo "${rc}  "/home/vagrant/project/remote_file.crt && exit 0; (python -c '"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'import hashlib; BLOCKSIZE = 65536; hasher = hashlib.sha1();
afile = open("'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'/home/vagrant/project/remote_file.crt'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'", "rb")
buf = afile.read(BLOCKSIZE)
while len(buf) > 0:
    hasher.update(buf)
    buf = afile.read(BLOCKSIZE)
afile.close()
print(hasher.hexdigest())'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"' 2>/dev/null) || (python -c '"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'import sha; BLOCKSIZE = 65536; hasher = sha.sha();
afile = open("'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'/home/vagrant/project/remote_file.crt'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'", "rb")
buf = afile.read(BLOCKSIZE)
while len(buf) > 0:
    hasher.update(buf)
    buf = afile.read(BLOCKSIZE)
afile.close()
print(hasher.hexdigest())'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"' 2>/dev/null) || (echo '"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'0  '"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'/home/vagrant/project/remote_file.crt)'"'"'"'"'"'"'"'"''"'"''
<192.168.33.11> ESTABLISH SSH CONNECTION FOR USER: vagrant
<192.168.33.11> SSH: EXEC ssh -C -vvv -o ForwardAgent=yes -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 -tt 192.168.33.11 '( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1474621139.62-98652362244447 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1474621139.62-98652362244447 )" )'
<192.168.33.11> PUT /tmp/tmpEX3_nF TO /home/vagrant/.ansible/tmp/ansible-tmp-1474621139.62-98652362244447/file
<192.168.33.11> SSH: EXEC sftp -b - -C -vvv -o ForwardAgent=yes -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 '[192.168.33.11]'
<192.168.33.11> ESTABLISH SSH CONNECTION FOR USER: vagrant
<192.168.33.11> SSH: EXEC ssh -C -vvv -o ForwardAgent=yes -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 -tt 192.168.33.11 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-jrhlokwxkhnhzckjssgcebtscqkxarsn; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1474621139.62-98652362244447/file; rm -rf "/home/vagrant/.ansible/tmp/ansible-tmp-1474621139.62-98652362244447/" > /dev/null 2>&1'"'"'"'"'"'"'"'"''"'"''
ok: [192.168.33.11] => {"changed": false, "checksum": "e9fa884818fbbd9a5af322e9e412e1856d2af8a1", "dest": "/home/vagrant/project/remote_file.crt", "gid": 0, "group": "root", "invocation": {"module_args": {"backup": null, "content": null, "delimiter": null, "dest": "/home/vagrant/project/remote_file.crt", "diff_peek": null, "directory_mode": null, "follow": false, "force": false, "group": null, "mode": "600", "original_basename": "hosts", "owner": null, "path": "/home/vagrant/project/remote_file.crt", "recurse": false, "regexp": null, "remote_src": null, "selevel": null, "serole": null, "setype": null, "seuser": null, "src": "hosts", "state": null, "validate": null}}, "mode": "0600", "owner": "root", "path": "/home/vagrant/project/remote_file.crt", "size": 221, "state": "file", "uid": 0}

TASK [Copy files] **************************************************************
task path: /home/dumitru/Public/ansible/ansible-tuto/step-00/bug-setup.yml:25
<192.168.33.11> ESTABLISH SSH CONNECTION FOR USER: vagrant
<192.168.33.11> SSH: EXEC ssh -C -vvv -o ForwardAgent=yes -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 -tt 192.168.33.11 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-gvrzxuyjbvchlmohjcfizlsrbqydeluk; rc=flag; [ -r /home//project/remote_file.crt ] || rc=2; [ -f /home//project/remote_file.crt ] || rc=1; [ -d /home//project/remote_file.crt ] && rc=3; python -V 2>/dev/null || rc=4; [ x"$rc" != "xflag" ] && echo "${rc}  "/home//project/remote_file.crt && exit 0; (python -c '"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'import hashlib; BLOCKSIZE = 65536; hasher = hashlib.sha1();
afile = open("'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'/home//project/remote_file.crt'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'", "rb")
buf = afile.read(BLOCKSIZE)
while len(buf) > 0:
    hasher.update(buf)
    buf = afile.read(BLOCKSIZE)
afile.close()
print(hasher.hexdigest())'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"' 2>/dev/null) || (python -c '"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'import sha; BLOCKSIZE = 65536; hasher = sha.sha();
afile = open("'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'/home//project/remote_file.crt'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'", "rb")
buf = afile.read(BLOCKSIZE)
while len(buf) > 0:
    hasher.update(buf)
    buf = afile.read(BLOCKSIZE)
afile.close()
print(hasher.hexdigest())'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"' 2>/dev/null) || (echo '"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'0  '"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'/home//project/remote_file.crt)'"'"'"'"'"'"'"'"''"'"''
<192.168.33.11> ESTABLISH SSH CONNECTION FOR USER: vagrant
<192.168.33.11> SSH: EXEC ssh -C -vvv -o ForwardAgent=yes -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 -tt 192.168.33.11 '( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1474621141.76-274485147185946 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1474621141.76-274485147185946 )" )'
<192.168.33.11> PUT /etc/hosts TO /home/vagrant/.ansible/tmp/ansible-tmp-1474621141.76-274485147185946/source
<192.168.33.11> SSH: EXEC sftp -b - -C -vvv -o ForwardAgent=yes -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 '[192.168.33.11]'
<192.168.33.11> ESTABLISH SSH CONNECTION FOR USER: vagrant
<192.168.33.11> SSH: EXEC ssh -C -vvv -o ForwardAgent=yes -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 -tt 192.168.33.11 '( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1474621142.72-11109269940732 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1474621142.72-11109269940732 )" )'
<192.168.33.11> PUT /tmp/tmpbAq5U6 TO /home/vagrant/.ansible/tmp/ansible-tmp-1474621142.72-11109269940732/copy
<192.168.33.11> SSH: EXEC sftp -b - -C -vvv -o ForwardAgent=yes -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 '[192.168.33.11]'
<192.168.33.11> ESTABLISH SSH CONNECTION FOR USER: vagrant
<192.168.33.11> SSH: EXEC ssh -C -vvv -o ForwardAgent=yes -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 -tt 192.168.33.11 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-uljoopfthxuqncjyihxmyposrqouyogv; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1474621142.72-11109269940732/copy; rm -rf "/home/vagrant/.ansible/tmp/ansible-tmp-1474621142.72-11109269940732/" > /dev/null 2>&1'"'"'"'"'"'"'"'"''"'"''
failed: [192.168.33.11] => (item={u'dest': u'/home//project/remote_file.crt', u'src': u'/etc/hosts'}) => {"checksum": "e9fa884818fbbd9a5af322e9e412e1856d2af8a1", "failed": true, "invocation": {"module_args": {"backup": false, "content": null, "delimiter": null, "dest": "/home//project/remote_file.crt", "directory_mode": null, "follow": false, "force": true, "group": null, "mode": "600", "original_basename": "hosts", "owner": null, "regexp": null, "remote_src": null, "selevel": null, "serole": null, "setype": null, "seuser": null, "src": "/home/vagrant/.ansible/tmp/ansible-tmp-1474621141.76-274485147185946/source", "validate": null}}, "item": {"dest": "/home//project/remote_file.crt", "src": "/etc/hosts"}, "msg": "Destination directory /home//project does not exist"}

PLAY RECAP *********************************************************************
192.168.33.11              : ok=4    changed=0    unreachable=0    failed=1   

```

**Comment by bcoca** [comment] 2016-09-23 14:53
dupe of #16776

**Closed as completed by bcoca** 2016-09-23 14:53 UTC
Labels: affects_2.0, bug
