### ISSUE TITLE
Module authorized_key fails on LDAP user

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#1099] opened 2012-09-26 12:33 UTC
I noticed that when using the authorized_key module on an LDAP user, the module bails out with:

```
KeyError: 'getpwnam(): name not found: user'
```

I guess the same is true when the user does not exist. This could be implemented better.

**Comment by mpdehaan** [comment] 2012-09-26 12:38
You mean a better error message when the user does not exist or something else?

**Comment by dagwieers** [comment] 2012-09-26 13:46
Yes, I need to look into why getpwnam() fails when on LDAP (and the user exists). But also fix the backtrace. I guess the expected behavior is to fail with a proper error message.

PS I would assign the issue to myself if I had the rights :-)

**Comment by mpdehaan** [comment] 2012-09-26 13:49
I can add you to the project and then I think I can at least assign it to
you.

Not sure I can grant the other...

**Comment by jpmens** [comment] 2012-09-26 14:36
+1 for the error message

Regarding getpwnam() not returning users from LDAP via NSS, it's driving me a little crazy...

I have some boxes where it works, and others where it doesn't. `nsswitch.conf` on all is identical. Python build options are probably not... 

This is an example where it does work, and obviously doesn't differ from a simple `/etc/passwd` user:

``` python
>>> import pwd
>>> u = pwd.getpwnam('f2')
>>> u
pwd.struct_passwd(pw_name='f2', pw_passwd='*', pw_uid=902, pw_gid=4, pw_gecos='Joe Guest', pw_dir='/home/f2', pw_shell='/bin/bash')
>>>
```

**Comment by dagwieers** [comment] 2012-09-26 15:14
@mpdehaan It would be nice if we could start managing issues/features through Github's issue-tracker and be able to assign issues/features to people. That way it's transparant who's working on what, and discussions can form around specific feature-sets.

**Comment by mpdehaan** [comment] 2012-09-26 15:40
yeah I unfortunately can't delegate that ability to you easily.  I can
however add you to the project and assign tickets to you on request.  We do
that some already.

**Comment by dhozac** [comment] 2012-09-27 19:28
Are you using sssd for users, or nss_ldap? Does getent passwd <user> work?

**Comment by jpmens** [comment] 2012-09-27 19:40
NSS LDAP. Yes: getent passwd works (I have quite a bit of experience w/
that :) Can only reproduce on a single box though, so no worries. Sorry:
forgot to say that here. All forms of getpwnam(3), etc. work, but on
that one box, not from Python. I'm no longer interested in investigating
though...

**Comment by dagwieers** [comment] 2012-09-27 22:36
We use nss-pal-ldapd and nslcd. Of course `getent passwd` does work.

I will get back to you next week on this with more information when I have a chance to troubleshoot.

**Comment by mpdehaan** [comment] 2012-09-27 22:53
@dagwieers assigned to you as you requested, thanks!

**Comment by sfromm** [comment] 2012-10-20 06:22
@dagwieers Are you still working on this?  I can at least submit a fix that wraps getpwnam in try/except.

I did test pwd.getpwnam() with ldap users on a couple systems and it worked for me.  One used sssd and one used nss_ldap.

**Comment by dagwieers** [comment] 2012-10-24 17:27
@sfromm: I'd rather not catch the exception if it should be fixed. I don't know when I will have time for this though. With things as they are going now, I may not be around for this to fix.

**Comment by sfromm** [comment] 2012-10-24 23:58
@dagwieers or @jpmens  Are you able to consistently replicate the problem with a ldap user on the affected systems?  

I'd like to catch the exception so that the user doesn't get a traceback.  I'd also like to fix the problem.  

@dagwieers Hopefully you'll stick around. :-)

**Comment by jpmens** [comment] 2012-10-25 05:41
Testing this now, @sfromm with Ansible 0.8.tar. I note the following:
1. No issue with setting auth key for a user in LDAP, at least not on a SLES10 box.
2. If user specified in authorized_key action doesn't exist, a traceback is issued: `getpwnam(): name not found`. That ought to be caught and handled.

Hope that helps.

**Comment by mpdehaan** [comment] 2012-11-09 00:50
so there's the above, which covers some of it, and there's some not covered.

Since there's been no traction on this otherwise I'm going to close it, I figure if someone wants to add further fixes they can.

**Closed as completed by mpdehaan** 2012-11-09 00:50 UTC
