### ISSUE TITLE
vars/main.yml variables content overwritten by later roles in playbook

### ISSUE THREAD

**Issue by rdolejsi** [ansible/ansible#9168] opened 2014-09-26 09:23 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

1.8 (devel) - works in 1.7
##### Environment:

running on: Linux Ubuntu
managing: Linux Ubuntu
##### Summary:

`vars/main.yml` gets loaded from all roles at the beginning of playbook (expected). In case one variable is in multiple roles, it **gets overwritten** and receives the content from the last role in playbook, not the current role (unexpected, regression).

In Ansible versions prior 1.8 (devel) any such variable got the current role's `vars/main.yml` content. The current behavior breaks our infrastructure and effectively eliminates our variable and task reuse.
##### Steps To Reproduce:

playbook-role-example.yml:

```
- hosts: server
  roles:
    - role-1
    - role-2
```

roles/role-1/vars/main.yml:

```
current_role: role-1
```

roles/role-1/tasks/main.yml:

```
- name:         print current_role variable
  debug:        msg="Variable current_role is {{ current_role }}"
```

roles/role-2/vars/main.yml:

```
current_role: role-2
```

roles/role-2/tasks/main.yml:

```
- name:         print current_role variable
  debug:        msg="Variable current_role is {{ current_role }}"
```
##### Expected Results:

Output until (and including) 1.7.2:

```
TASK: [role-1 | print current_role variable] ********************************** 
ok: [192.168.56.101] => {
    "msg": "Variable current_role is role-1"
}

TASK: [role-2 | print current_role variable] ********************************** 
ok: [192.168.56.101] => {
    "msg": "Variable current_role is role-2"
}
```
##### Actual Results:

Output in 1.8 (devel):

```
TASK: [role-1 | print current_role variable] ********************************** 
ok: [192.168.56.101] => {
    "msg": "Variable current_role is role-2"
}

TASK: [role-2 | print current_role variable] ********************************** 
ok: [192.168.56.101] => {
    "msg": "Variable current_role is role-2"
}
```

**Comment by jimi-c** [comment] 2014-10-03 17:59
Hi @rdolejsi, I believe this is a duplicate of #9219, which has been corrected in devel, so I'm going to go ahead and close this issue.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2014-10-03 17:59 UTC
Labels: P1, bug

**Comment by rdolejsi** [comment] 2014-10-07 15:34
Thank you, James. I'll give it a try ASAP to confirm the fix for the issue you mentioned is indeed the correct one for this one as well..
