### ISSUE TITLE
mysql module: Syntax error: EOF in backquote substitution

### ISSUE THREAD

**Issue by LeonB** [ansible/ansible#5190] opened 2013-12-05 20:11 UTC
When I try to import a sql file into a mysql database via ansible I get this error:

```
NOTIFIED: [tt-rss | import tt-rss sql] **************************************** 
failed: [mediahub.vanutsteen.nl] => {"failed": true, "item": ""}
msg: Syntax error: EOF in backquote substitution
Syntax error: Error in command substitution
```

I'm provisioning a FreeBSD host. This is the task:

``` yml
- name: import tt-rss sql
  mysql_db: name="{{ ttrss_mysql_database }}"
    login_host="{{ ttrss_mysql_host }}"
    login_user="{{ ttrss_mysql_user }}"
    login_password="{{ ttrss_mysql_password }}"
    state=import
    target="/usr/local/www/tt-rss/schema/ttrss_schema_mysql.sql"
```

The error message with `-vvvv`:

```
NOTIFIED: [tt-rss | import tt-rss sql] **************************************** 
<mediahub.vanutsteen.nl> ESTABLISH CONNECTION FOR USER: leon
<mediahub.vanutsteen.nl> EXEC ['ssh', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/leon/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', 'mediahub.vanutsteen.nl', "/bin/sh -c 'mkdir -p /tmp/ansible-1386274190.6-35323313635181 && chmod a+rx /tmp/ansible-1386274190.6-35323313635181 && echo /tmp/ansible-1386274190.6-35323313635181'"]
<mediahub.vanutsteen.nl> REMOTE_MODULE mysql_db name="ttrss" login_host="mysql.vanutsteen.nl" login_user="ttrss" login_password=">0`;JU$DhQ-u0z%P_t;TSQhOC" state=import target="/usr/local/www/tt-rss/schema/ttrss_schema_mysql.sql"
<mediahub.vanutsteen.nl> PUT /tmp/tmpaVkVEi TO /tmp/ansible-1386274190.6-35323313635181/mysql_db
<mediahub.vanutsteen.nl> EXEC ['ssh', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/leon/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', 'mediahub.vanutsteen.nl', '/bin/sh -c \'sudo -k && sudo -H -S -p "[sudo via ansible, key=jkjxzagyumcvdswoewonbiwwuedlagaf] password: " -u root /bin/sh -c \'"\'"\'echo SUDO-SUCCESS-jkjxzagyumcvdswoewonbiwwuedlagaf; /usr/local/bin/python /tmp/ansible-1386274190.6-35323313635181/mysql_db; rm -rf /tmp/ansible-1386274190.6-35323313635181/ >/dev/null 2>&1\'"\'"\'\'']
failed: [mediahub.vanutsteen.nl] => {"failed": true, "item": ""}
msg: Syntax error: EOF in backquote substitution
Syntax error: Error in command substitution
```

I've installed ansible on an Ubuntu laptop from the ppa:

``` bash
$ ansible --version
ansible 1.4
```

**Comment by jctanner** [comment] 2013-12-05 20:41
@LeonB I have a simple playbook for testing mysql export/import and I'm not seeing your error ...

```
  vars:
     DB_DNS : el5.lab.net
     DB_USER : "root"
     DB_USER_PASSWORD : "redhat"

  tasks:
    - shell: /usr/bin/mysql -u root --password=redhat -e "drop database test"
      ignore_errors: True

    - shell: /usr/bin/mysql -u root --password=redhat -e "create database test"
      ignore_errors: True

    - shell: /usr/bin/mysql  -u root --password=redhat -D test -e "create table foo (name varchar(20))"
      ignore_errors: True

    # backup schema
    - name: dump test database
      mysql_db:   login_host={{ DB_DNS }}
                  login_user={{ DB_USER }}
                  login_password={{ DB_USER_PASSWORD }}
                  name=test
                  state=dump
                  target=/tmp/testdump1.sql

    # mess up the schema
    - shell: /usr/bin/mysql -u root --password=redhat -D test -e "drop table foo"
      ignore_errors: True

    - shell: /usr/bin/mysql  -u root --password=redhat -D test -e 'show tables'
      register: show_result1
    - debug: var=show_result1

    # restore the schema
    - name: import test database
      mysql_db:   login_host={{ DB_DNS }}
                  login_user={{ DB_USER }}
                  login_password={{ DB_USER_PASSWORD }}
                  name=test
                  state=import
                  target=/tmp/testdump1.sql
```

Do you see the same error if you run mysql by hand on the host?

```
mysql --user=<USER> --password=<PASS> --host=<HOST> -D <DBNAME> < /tmp/testdump1.sql
```

**Comment by LeonB** [comment] 2013-12-05 20:44
Running it by hand works fine. Could it maybe has to do something with the default shell on FreeBSD (/bin/tcsh)?

**Comment by jctanner** [comment] 2013-12-05 20:52
@LeonB ansible runs the remote python scripts with /bin/sh so I don't think that tcsh should impact it. However, I set the root user's shell to /bin/tcsh on my el5 machine just to test and there were no errors.

**Comment by jctanner** [comment] 2013-12-05 20:55
@LeonB One thing to check is the MODULE_ARGS line in the remote script ...

```
ANSIBLE_KEEP_REMOTE_FILES=1 ansible-playbook -vvvv
```

You should see a filepath simliar to "/root/.ansible/tmp/ansible-1386276673.34-215563927014188/mysql_db" in the output. In that file on the remote host, grep for the MODULE_ARGS line ...

```
[root@el5 ~]# fgrep MODULE_ARGS /root/.ansible/tmp/ansible-1386276878.53-177612314048373/mysql_db
MODULE_ARGS = 'login_host=el5.lab.net login_user=root login_password=redhat name=test state=import target=/tmp/testdump1.sql'
        args = MODULE_ARGS
```

Verify that your credentials/parameters were passed in correctly.

**Comment by LeonB** [comment] 2013-12-05 21:12
The penny dropped... My password contains a '`'...

**Comment by jctanner** [comment] 2013-12-05 21:14
Hrm, maybe we should safely quote passwords inside the module.

**Comment by LeonB** [comment] 2013-12-05 21:18
Would be awesome! For now I'll generate a new password. Using `ANSIBLE_KEEP_REMOTE_FILES=1` was an awesome tip. Thanks!

I also tried using a single quote, a '>' and a ';' but all caused an error.

**Comment by mpdehaan** [comment] 2013-12-05 22:49
Added "mysql module" to the ticket caption so we can tell what this is about from the issue list.

**Comment by Jmainguy** [comment] 2014-07-18 14:50
Not sure which pull request fixed this, however I am unable to reproduce the issue. I gave my user a password with a ` in it, and it connects just fine now. I suggest closing this one out.

**Comment by mpdehaan** [comment] 2014-09-29 20:46
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Closed as completed by mpdehaan** 2014-09-29 20:46 UTC
Labels: bug, mysql
