### ISSUE TITLE
Unicode bug when using copy module

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#11978] opened 2015-08-17 08:44 UTC
ansible 1.9.2

I’m having an issue with the following Jinja2 template:

<pre>
# playbook.yml

---
- name: testing
  hosts: dev
  vars:
   you_say: "hi, 申申的无赖！\n"
  tasks:
   - name: copy
     copy:
      dest: /home/jefurry/tmp/test.txt
      content: "{{ you_say }} - 指南针\n"
...

</pre>

it works fine. but hosting dev's /home/jefurry/tmp/test.txt file's contents is messy code. like this:

<pre>
hi, ç³ç³çæ èµï¼
 - æåé
</pre>

thanks!

**Comment by abadger** [comment] 2015-08-17 09:09
Confirmed on 1.9.2.  Seems to be fixed on 2.0 branch:

```
]$ cat /var/tmp/test.txt                                                             (02:01:21)
hi, 申申的无赖！
 - 指南针%    
https://github.com/ansible/ansible/issues/11978#fullscreen
```

**Comment by ghost** [comment] 2015-08-17 09:22
thanks

**Comment by bcoca** [comment] 2015-08-18 00:07
closing as this is fixed in devel

**Closed as completed by bcoca** 2015-08-18 00:07 UTC
Labels: bug
