### ISSUE TITLE
Default to sane egress policy in ec2_group (change since 1.5.3->1.6)

### ISSUE THREAD

**Issue by evanccnyc** [ansible/ansible#7027] opened 2014-04-16 19:59 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6
##### Environment:

Mac OS X 10.7
##### Summary:

rules_egress was added to ec2_group in 1.6 (previous there was no rules_egress).  Unfortunately it defaults to nothing in it, meaning that previous ansible scripts will not allow anything out of a security group.  This breaks many security groups.
##### Steps To Reproduce:

Create a ec2_group (security group) with no rules_egress.  Watch everything get blocked going outbound.
##### Expected Results:

Should default to allowing everything outbound since thats what ansible did previously.
##### Actual Results:

Unable to access going outbound.

**Comment by jimi-c** [comment] 2014-04-17 19:02
Unfortunately I cannot reproduce this issue. I just created a new security group and added an instance to it, where the only rule specified was an ingress rule for port 22 inbound from any. I hopped on the instance and was able to successfully do things like ping out and fetch web pages from public servers.

Could you attach an example playbook for an ec2_group setup that shows the reported behavior?

**Comment by evanccnyc** [comment] 2014-04-17 19:04
It was a vpc security group (no idea if that changes what happened):

```
- name: Provision frontend security group
  local_action:
        module: ec2_group
        state: present
        name: ansibleDeployedFrontend
        description: "Frontend ansible security group - ssh,http"
        vpc_id: "{{ vpc.vpc_id }}"
        region: "{{ aws_region }}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 2049
            to_port: 2049
            cidr_ip: 10.0.0.0/8
          - proto: tcp
            from_port: 111
            to_port: 111
            cidr_ip: 10.0.0.0/8
          - proto: udp
            from_port: 111
            to_port: 111
            cidr_ip: 10.0.0.0/8
          - proto: udp
            from_port: 32806
            to_port: 32806
            cidr_ip: 10.0.0.0/8

```

**Comment by jimi-c** [comment] 2014-04-17 19:52
It does, when a VPC is specified I see an empty "Outbound" tab appear for the security group. The odd thing is, if I tell it to then add the rule for any outbound to any with the boto `ec2.authorize_security_group_egress()` call, I get this error:

<pre>
&lt;Code&gt;InvalidPermission.Duplicate&lt;/Code&gt;
&lt;Message&gt;the specified rule "peer: 0.0.0.0/0, ALL, ALLOW" already exists&lt;/Message&gt;
</pre>

But then the rule shows up in the outbound tab. Still trying to get that figured out.

**Comment by jimi-c** [comment] 2014-04-17 20:23
Here's my patch:

<pre>
diff --git a/library/cloud/ec2_group b/library/cloud/ec2_group
index 56581ec..ac0389a 100644
--- a/library/cloud/ec2_group
+++ b/library/cloud/ec2_group
@@ -313,6 +313,20 @@ def main():
                                 src_group_id=grantGroup,
                                 cidr_ip=ip)
                     changed = True
+        elif vpc_id and not module.check_mode:
+            # when using a vpc, but no egress rules are specified, 
+            # we add in a default allow all out rule, which was the
+            # default behavior before egress rules were added
+            if 'out--1-None-None-None-0.0.0.0/0' not in groupRules:
+                ec2.authorize_security_group_egress(
+                    group_id=group.id,
+                    ip_protocol=-1,
+                    from_port=None,
+                    to_port=None,
+                    src_group_id=None,
+                    cidr_ip='0.0.0.0/0'
+                )
+                changed = True
 
         # Finally, remove anything left in the groupRules -- these will be defunct rules
         for rule in groupRules.itervalues():
</pre>

It does not actually run the above because that rule is found in the groupRoles list, so it does appear that by default even for VPC groups there is a default allow all outbound group if/when no other egress rules are specified.

**Comment by jimi-c** [comment] 2014-04-17 20:25
I've also pushed that up to my copy of the ansible repo.

**Comment by jimi-c** [comment] 2014-04-22 14:36
@evanccopengeo any chance to test my above patch?

**Comment by evanccnyc** [comment] 2014-04-22 15:04
I got sucked into meetings this morning. I am hoping this afternoon.

**Comment by jimi-c** [comment] 2014-04-29 14:35
@evanccopengeo just following up on this again. Thanks!

**Comment by jimi-c** [comment] 2014-04-29 15:40
I went ahead and merged in my above fix, which should address this issue. If you continue having any issues with this, let us know. Thanks!

**Closed as completed** 2014-04-29 15:39 UTC
Labels: needs_info, cloud, P2, bug

**Comment by mmoya** [comment] 2014-04-29 17:13
If you look in [line 272](https://github.com/mmoya/ansible/commit/f97243d6ed7dc7bb23c9cf675ae84c116beae457#diff-317f4cc0ba915fbd7bd5ac28fdadc031R272) of the PR implementing support for egress rules you can see that `rules_egress` are only processed if they are given in the task. That is backward-compatible because that option didn't exists before.

With my approach, if you specified a `rule_egress` without the 0/0 rule, the 0/0 wouldn't be included. I think this is the correct way to do it, otherwise you are getting behaviour not explicitedly expressed in your playbooks.

**I strongly disagree with this commit**. Documentation can be improved to include a warning regarding this detail though. 

Would appreciate your feedback @jimi-c and @evanccopengeo.

**Comment by mmoya** [comment] 2014-05-06 09:25
I didn't put enough attention when reviewing. This is a clear regression introduced by #6602.
