### ISSUE TITLE
Template module changes permissions on containing directory if dest is a directory

### ISSUE THREAD

**Issue by spakka** [ansible/ansible#9818] opened 2014-12-15 14:56 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

1.8.2
##### Environment:

From: Mac OS X 10.9.5
(Python 2.7.5)
To: CentOS 6.5
##### Summary:

Permissions on a templated file are applied to the containing directory if mode= is specified and file already exists
##### Steps To Reproduce:

Example case:

user@source:/tmp$ cat test.j2
this is a test template

```
user@source:/tmp$ cat test.yml

---
- name: test template
  hosts: all
  tasks:
    - template: src=test.j2 dest=/tmp/ mode=444
```

[root@target ~]# ls -ald /tmp
drwxrwxrwt. 7 root root 4096 Dec 15 14:39 /tmp
[root@target ~]# ls -al /tmp/test.j2
ls: cannot access /tmp/test.j2: No such file or directory

user@source:/tmp$ ansible-playbook -Ks -l target test.yml
sudo password:

PLAY [test template] **********************************************************

GATHERING FACTS ***************************************************************
ok: [target]

TASK: [template src=test.j2 dest=/tmp/ mode=444] ******************************
changed: [target]

PLAY RECAP ********************************************************************
target : ok=2    changed=1    unreachable=0    failed=0

[root@target ~]# ls -ald /tmp
drwxrwxrwt. 7 root root 4096 Dec 15 14:42 /tmp
[root@target ~]# ls -al /tmp/test.j2
-r--r--r--. 1 root root 24 Dec 15 14:42 /tmp/test.j2

user@source:/tmp$ ansible-playbook -Ks -l target test.yml
sudo password:

PLAY [test template] **********************************************************

GATHERING FACTS ***************************************************************
ok: [target]

TASK: [template src=test.j2 dest=/tmp/ mode=444] ******************************
changed: [target]

PLAY RECAP ********************************************************************
target : ok=2    changed=1    unreachable=0    failed=0

[root@target ~]# ls -ald /tmp
dr--r--r--. 8 root root 4096 Dec 15 14:44 /tmp
[root@target ~]# ls -al /tmp/test.j2
-r--r--r--. 1 root root 24 Dec 15 14:42 /tmp/test.j2
##### Expected Results:

The second playbook run should not have resulted in any changes (the template was copied correctly in the first run, and had the correct permissions set on it)
##### Actual Results:

The second playbook run alters the permissions on the containing directory instead of verifying them on the templated file
This has stopped working since Ansible 1.7.x

**Comment by mscherer** [comment] 2014-12-17 09:29
I cannot reproduce it, but I am trying on a RHEL 7 host, and using the local connexion. ( I tried with and without sudo as well ). So that's either platform specific, or connexion specific. Does it work if you run it as a user with local for you as well ?

**Comment by spakka** [comment] 2014-12-17 09:40
Hi, It doesn't seem to affect local connection, only on remote SSH push.

**Comment by sysadmin75** [comment] 2014-12-27 17:45
I was not able to reproduce this issue either.
My test cases:
From: Centos 6.6 (python 2.6.6)
To: Centos 6.6
To: Fedora 20 (python 2.7.5)

From: OSX 10.9.5 (python 2.7.5)
To: Fedora 20 (python 2.7.5)

**Comment by abadger** [comment] 2015-01-09 17:22
@spakka if there's anything else that you can think of to reproduce this please let us know.  Otherwise I'll close this in a few days since we're unable to reproduce the issue.

**Closed as completed** 2015-01-13 15:44 UTC
Labels: needs_info, P2, bug
