### ISSUE TITLE
--docker-privileged isn't in ansible-test

### ISSUE THREAD

**Issue by kbreit** [ansible/ansible#61714] opened 2019-09-03 14:39 UTC
##### SUMMARY
https://docs.ansible.com/ansible/latest/dev_guide/testing_integration.html#tests-in-docker-containers

The note here says:

> Using Docker Engine to run Docker on a non-Linux host (such as macOS) is not recommended. Some tests may fail, depending on the image used for testing. Using the `--docker-privileged` option may resolve the issue.

I tried to run with `--docker-privileged` but the option isn't there. Either the option has been removed or the documentation should be improved to show how to access it properly.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
https://docs.ansible.com/ansible/latest/dev_guide/testing_integration.html#tests-in-docker-containers

##### ANSIBLE VERSION
```paste below
2.10
```

**Comment by kbreit** [comment] 2019-09-03 14:39
CC @mattclay

**Comment by sivel** [comment] 2019-09-03 15:12
I'm not sure what issue you are running into, but that CLI argument does exist:

Example:

```
ansible-test integration --docker centos7 --docker-privileged -v connection_ssh
```

I cannot remember which tests fail without `--docker-privileged`, but running with that arg causes docker to execute with:

```
Run command: docker run --detach --volume /sys/fs/cgroup:/sys/fs/cgroup:ro --privileged=true --security-opt seccomp=unconfined --volume /var/run/docker.sock:/var/run/docker.sock quay.io/ansible/centos7-test-container:1.8.0
```

As opposed to:

```
Run command: docker run --detach --volume /sys/fs/cgroup:/sys/fs/cgroup:ro --privileged=false --security-opt seccomp=unconfined --volume /var/run/docker.sock:/var/run/docker.sock quay.io/ansible/centos7-test-container:1.8.0
```

Notice `--privileged=true` vs `--privileged=false`

**Comment by kbreit** [comment] 2019-09-04 01:07
I am running this against `network-integration` which is what's causing the error.

```(venv) ansible [meraki/meraki_mx_uplink●●] % ansible-test network-integration --allow-unsupported --docker fedora29 --docker-privileged --python 3.7 meraki_mx_uplink
usage: ansible-test [-h] COMMAND ...
ansible-test: error: unrecognized arguments: --docker-privileged```

**Comment by sivel** [comment] 2019-09-04 13:13
Ok, so that argument isn't exposed, due to this line:

https://github.com/ansible/ansible/blob/830f995ed4374a0c75b41837186e719b5c43f845/test/lib/ansible_test/_internal/cli.py#L362

After thinking about this, I'm going to take a step back for a moment.

What is not working for you, that this option is needed?

Typically, we use it for situations where you are needing to use some service that couples tightly with cgroups on a linux device. I'm unsure what would require this from a network integration side.

**Comment by kbreit** [comment] 2019-09-04 16:38
I do my development on a Mac (latest version) and trying to run `network-integration` tests. It used to work just fine. I know there were some changes around ignored files not being copied into the container so it's possible that's getting in my way. Here is output I'm seeing.

```
(venv) ansible [devel●] % git check-ignore -v test/integration/inventory.networking
.gitignore:84:/test/integration/inventory.networking	test/integration/inventory.networking
(venv) ansible [devel●] % ansible-test network-integration --allow-unsupported --docker --python 3.7 meraki_syslog
ERROR: Inventory not found: /root/ansible/test/integration/inventory.networking
Use --inventory to specify the inventory path.
Use --platform to provision resources and generate an inventory file.
See also inventory template: /root/ansible/test/lib/ansible_test/config/inventory.networking.template
```

Does it make sense to note in documentation this option is only valid for `integration` and not network?

**Comment by mattclay** [comment] 2019-09-10 01:16
@kbreit The `Inventory not found: /root/ansible/test/integration/inventory.networking` error is unrelated to the `--docker-privileged` option. Can you open a separate issue for that error, and include additional details on how to reproduce the issue?

I agree that the docs could be more clear that the option is only available for the `integration` command.

I'm going to close this issue since the `--docker-privileged` option has only ever been available for the `integration` command, not `network-integration` or `windows-integration`.

**Closed as completed by mattclay** 2019-09-10 01:16 UTC
Labels: support:core, docs, affects_2.10
