### ISSUE TITLE
cron module is not idempotent with Ansible 2.9.12

### ISSUE THREAD

**Issue by vguillard** [ansible/ansible#71536] opened 2020-08-31 14:10 UTC
##### SUMMARY
When running this task a second time, ansible 2.9.12 marked this as a change, but there are any changes.
```yaml
- name: Add a job
  cron:
    name: myjob
    cron_file: myjob
    user: root
    job: "touch /tmp/myjob"
```

Ansible mark this "changed" but when I check on the target (md5sum /etc/cron.d/myjob ; ls -l /etc/cron.d/myjob), there are no changes.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cron

##### ANSIBLE VERSION

```
ansible 2.9.12
python version = 3.6.9 
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

First, add my task, described at the top, in a role tested with molecule
```yaml
pip3 install ansible==2.9.11 && molecule test
pip3 install ansible==2.9.12 && molecule test
```

##### EXPECTED RESULTS

```
    ok: [instance] => {
        "changed": false,
        "cron_file": "myjob",
        "envs": [],
        "invocation": {
            "module_args": {
                "backup": false,
                "cron_file": "myjob",
                "day": "*",
                "disabled": false,
                "env": null,
                "hour": "*",
                "insertafter": null,
                "insertbefore": null,
                "job": "touch /tmp/myjob",
                "minute": "*",
                "month": "*",
                "name": "myjob",
                "reboot": false,
                "special_time": null,
                "state": "present",
                "user": "root",
                "weekday": "*"
            }
        },
        "jobs": [
            "myjob"
        ]
    }

```

##### ACTUAL RESULTS

```
    changed: [instance] => {
        "changed": true,
        "cron_file": "myjob",
        "diff": {
            "after": "#Ansible: myjob\n* * * * * root touch /tmp/myjob\n",
            "after_header": "/etc/cron.d/myjob",
            "before": "#Ansible: myjob\n* * * * * root touch /tmp/myjob\n",
            "before_header": "/etc/cron.d/myjob"
        },
        "envs": [],
        "invocation": {
            "module_args": {
                "backup": false,
                "cron_file": "myjob",
                "day": "*",
                "disabled": false,
                "env": null,
                "hour": "*",
                "insertafter": null,
                "insertbefore": null,
                "job": "touch /tmp/myjob",
                "minute": "*",
                "month": "*",
                "name": "myjob",
                "reboot": false,
                "special_time": null,
                "state": "present",
                "user": "root",
                "weekday": "*"
            }
        },
        "jobs": [
            "myjob"
        ]
    }

```

**Comment by sivel** [comment] 2020-08-31 14:13
Duplicate of https://github.com/ansible/ansible/issues/71213

**Closed as completed by sivel** 2020-08-31 14:13 UTC
Labels: module, support:core, bug, system, affects_2.9
