### ISSUE TITLE
Variable merging fails to occur even if "hash_behavior" is set to merge.

### ISSUE THREAD

**Issue by danieljaouen** [ansible/ansible#7091] opened 2014-04-21 12:56 UTC
##### Issue Type:

Bug report.
##### Ansible Version:

```
± ansible --version
ansible 1.6 (brew 9338e2726f) last updated 2014/04/20 16:23:05 (GMT -400)
```
##### Environment:

OS X 
##### Summary:

Dictionary variables are not merged correctly even if the `hash_behavior` option is set to `merge`.
##### Steps To Reproduce:
1. Modify `~/.ansible.cfg` to look like this:

``` ini
[defaults]
hash_behavior = merge
```
1. Create a new role with the following tasks:

``` yaml
# file: roles/debug/tasks/main.yml

---
- name: main | debug
  debug: "msg='{{ test.three }} and {{ test.two }} and {{ test.one }}'"
```

And the following defaults:

``` yaml
# file: roles/debug/defaults/main.yml

---
test:
  one: 'This is the first variable.'
```

And the following vars:

``` yaml
# file: roles/debug/vars/main.yml

---
test:
  two: 'This is the second variable.'

test:
  three: 'This is the third variable.'
```
##### Expected Results:

The debug modules prints out:

```
 This is the third variable. and This is the second variable. and This is the first variable.
```
##### Actual Results:

I receive the following error:

```
TASK: [debug | main | debug] **************************************************
fatal: [127.0.0.1] => One or more undefined variables: 'dict object' has no attribute 'two'

FATAL: all hosts have already failed -- aborting
```

**Comment by jimi-c** [comment] 2014-04-21 16:44
Dictionaries contained within the same file as you have in vars/main.yml are not merged, you're essentially overwriting the variable there with the second declaration. The vars file should be written as:

<pre>
---
test:
  two: ...
  three: ...
</pre>

 If you have any further questions regarding this issue, please let us know. Thanks!

**Closed as completed by jimi-c** 2014-04-21 16:44 UTC

**Comment by danieljaouen** [comment] 2014-04-21 16:52
The issue remains even if I remove the second definition in the `vars` file.  In other words, it seems like merging doesn't work if you define dicts across `defaults` and `vars` files.

**Comment by jimi-c** [comment] 2014-04-21 17:06
@danieljaouen I was unable to reproduce that, and in fact tested it merging across vars, defaults and a 'vars:' definition in the YAML file including the role:

<pre>
- hosts: localhost
  gather_facts: no
  vars:
    test:
      two: 'two from the main yaml'
  roles:
  - debug
</pre>

^ this worked fine and replaced the test.two output with the above.

**Comment by danieljaouen** [comment] 2014-04-21 17:13
This is still not working for me.  The only thing I can think of here is that Ansible isn't seeing my `~/.ansible.cfg` file for some reason.

Is there a command line flag to force this behavior?

**Comment by danieljaouen** [comment] 2014-04-21 17:20
Nevermind -- looks like the correct option is `hash_behaviour` and not `hash_behavior`.  Might be worthwhile to add an alias here.

**Comment by jimi-c** [comment] 2014-04-21 17:28
Oh yes, I did notice that during my testing and forgot to mention it, sorry about that.
