### ISSUE TITLE
feature-request/Add 'remote_src' option to 'template' module

### ISSUE THREAD

**Issue by qnick** [ansible/ansible#26797] opened 2017-07-14 11:17 UTC
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
Files/Template

##### ANSIBLE VERSION

```
ansible 2.3.2.0 (stable-2.3 10aa164166) last updated 2017/06/29 18:32:01 (GMT +300)
  config file = /home/user/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION
none
##### OS / ENVIRONMENT
N/A

##### SUMMARY
Lots of application, I install with ansible, are tar archives downloaded with 'maven_artifact' or 'unarchive' modules.
Some of these archives contains templates of configuration files in jinja2 format. I want to be able copy those files to application config directory with replacing jinja2 placeholders and without copying them to my local machine.
Now I have to use module 'replace', but I think it may be more native to use 'template' module with option 'remote_src=yes'

##### STEPS TO REPRODUCE

```yaml
- name: Get Snapshot app
  maven_artifact:
    group_id: "{{ component_group_id }}"
    artifact_id: "{{ component_artifact_id }}"
    repository_url: "{{ snapshot_repository }}"
    version: "{{ component_version }}"
    extension: 'tar.gz'
    dest: "{{ some_path }}.tgz"

- name: Extract tarball
  unarchive:
    remote_src: yes
    src: "{{ some_path }}.tgz"
    dest: "{{ app_directory }}"

- name: Copy configuration files
  template:
    remote_src: yes  # <- this is what I want
    src: "{{ app_directory }}/conf_templates/{{ item }}.j2"
    dest: "{{ app_directory }}/conf/{{ item }}"
  with_items: "{{ conf_files }}"
```

##### EXPECTED RESULTS

Files from directory 'conf_templates' should be copied to directory 'conf' with jinja2 filters applied

##### ACTUAL RESULTS
Now I can fetch those files to my local machine into temporary directory and then copy them back as templates, or use 'replace' module to replace jinja2 placeholders.

**Comment by bcoca** [comment] 2017-07-14 18:52
Aside from many other things, that would require that the remote machines have Jinja2 installed

**Comment by artjomaverin** [comment] 2018-12-13 04:34
> Aside from many other things, that would require that the remote machines have Jinja2 installed

Why not copy it to the tmp on ansible server in case of remote_src - as part of the task? 
Currently we have to do it manually by first fetching the template to ansible server, then provisioning it to the server.

**Comment by rashminair90** [comment] 2019-04-25 20:33
@qnick, Is this working for you. I am also implementing similar thing for my project where I am writing a playbook to execute the templates on remote server. So for that, I install my ansible rpm on remote server, then create a symlink to templates as templates are not in my ansible repo but installed as rpm on target servers. For example --> if /opt/ansible is my ansible dir then /opt/ansible/templates will point to /opt/app/config which will have templates in the subfolders . I have written below task for that    ###
 - name: Ensure files are populated from templates
      template:
        src: "{{ item.src }}"
        dest: "{{ templates_destination }}/{{ item.path | regex_replace('.template$','') }}"
        force: yes
      with_filetree: "{{ templates_source }}"
      when: item.state == 'file'
      delegate_to: server1


But this task execution shows no logs , verbose output looks something like this -###
TASK [Ensure files are populated from templates] ****************************************
task path: /delegate.yml:37
META: ran handlers
META: ran handlers




Any idea what the issue could be?﻿

**Comment by mkrizek** [comment] 2020-08-18 11:28
Duplicate of https://github.com/ansible/ansible/issues/65778

**Closed as completed by mkrizek** 2020-08-18 11:28 UTC
Labels: affects_2.3, module, support:core, feature, files

**Comment by JensTimmerman** [comment] 2020-09-10 23:58
Is this working now or not? I ran into an issue that the template can not be found on the controller, and ansible tells me to look at the 'remote_src' option, but this option doesn't seem to exist yet?

`{"changed": false, "msg": "Could not find or access '/home/im/settings.py.j2' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}`

**Comment by lucasbasquerotto** [comment] 2020-09-11 14:12
@JensTimmerman Are you use the `template` module **and not some other module** (like `copy`)? The last time I saw, `template` didn't have a `remote_src` option and the ansible team didn't intend to make it have this option (https://github.com/ansible/ansible/issues/65778#issuecomment-566656262). 

If you have that error using the `template` module, it might be that the **error message** is wrong (because it doesn't seem that `template` supports `remote_src`).

**Comment by JensTimmerman** [comment] 2020-09-11 14:42
Yes indeed, it seems to me that the error message is wrong.
