### ISSUE TITLE
add_host seems to lose variables defined on host

### ISSUE THREAD

**Issue by suppandi** [ansible/ansible#13896] opened 2016-01-14 18:29 UTC
_inventory file_

```
[allnodes]
10.1.1.1 incluster1=True myvar=foo
10.1.1.2 incluster2=True myvar=bar
```

_playbook_
splits nodes into groups and prints variables

```

---
# This playbook deploys the whole application stack in this site.

- name: dump vars1
  hosts: all
  tasks:
    - name: dump1
      debug: msg={{ myvar }}

- name: split
  hosts: 127.0.0.1
  connection: local
  tasks:
    - add_host: hostname={{ item }} groups={{ "cluster1" }}
      with_items: groups['all']
      when: hostvars[item].incluster1 is defined
    - add_host: hostname={{ item }} groups={{ "cluster2" }}
      with_items: groups['all']
      when: hostvars[item].incluster2 is defined

- name: dump vars2
  hosts: all
  tasks:
    - name: dump2
      debug: msg={{ myvar }}

```

*expected output \* 
this is what ansible 1.9.x returns

```
TASK: [dump1] ***************************************************************** 
ok: [10.1.1.1] => {
    "msg": "foo"
}
ok: [10.1.1.2] => {
    "msg": "bar"
}
...
TASK: [dump2] ***************************************************************** 
fatal: [127.0.0.1] => One or more undefined variables: 'myvar' is undefined
ok: [10.1.1.1] => {
    "msg": "foo"
}
ok: [10.1.12] => {
    "msg": "bar"
}
```

_actual output(from ansible 2.X.X)_

```
TASK [dump1] *******************************************************************
ok: [10.1.1.1] => {
    "msg": "foo"
}
ok: [10.1.1.2] => {
    "msg": "bar"
}
...
TASK [dump2] *******************************************************************
fatal: [127.0.0.1]: FAILED! => {"failed": true, "msg": "ERROR! 'myvar' is undefined"}
fatal: [10.1.1.1]: FAILED! => {"failed": true, "msg": "ERROR! 'myvar' is undefined"}
fatal: [10.1.1.2]: FAILED! => {"failed": true, "msg": "ERROR! 'myvar' is undefined"}
```

**Comment by bcoca** [comment] 2016-01-14 18:54
dupe of #13841

**Closed as completed by bcoca** 2016-01-14 18:54 UTC
