### ISSUE TITLE
Copy and template modules always run task and mark it changed if content is single line without ending '\n' 

### ISSUE THREAD

**Issue by selivan** [ansible/ansible#13476] opened 2015-12-08 17:39 UTC
Ansible: 1.9.4

Task is always changed:

```
- name: install /etc/timezone
  copy: content="{{ timezone }}" dest=/etc/timezone mode=0644 owner=root group=root
  notify: update tzdata
  tags: timezone
```

Works as intended:

```
- name: install /etc/timezone
  copy: content="{{ timezone }}\n" dest=/etc/timezone mode=0644 owner=root group=root
  notify: update tzdata
  tags: timezone
```

Same problem occurs if I use template module with template `{{ timezone }}` (no new line symbol).

Problem seems to exist since 2013: https://gist.github.com/garethrees/5591027

**Comment by bcoca** [comment] 2015-12-08 17:44
closing as duplicate of #8443

**Closed as completed by bcoca** 2015-12-08 17:44 UTC
