### ISSUE TITLE
Crash on 2.2.2 when inventory has host inside and outside group

### ISSUE THREAD

**Issue by grandchild** [ansible/ansible#23219] opened 2017-04-03 13:17 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
ansible / inventory

##### ANSIBLE VERSION

```
ansible 2.2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
None.

##### OS / ENVIRONMENT

ArchLinux 64

##### SUMMARY
In an inventory file, when mentioning a host twice, once outside and once inside a group, ansible crashes.

##### STEPS TO REPRODUCE
Create an inventory like this:

```ini
somehost

[group]
somehost
```
And an empty playbook (just so there is one, can be any existing file)
```yaml
---
lorem ipsum
```
Run as usual:
```
ansible-playbook -i inventory.ini test.yml
```
##### EXPECTED RESULTS
Playbook runs.

##### ACTUAL RESULTS
Ansible crashes and says the following.

```
ERROR! Unexpected Exception: 'Host' object has no attribute 'remove_group'
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 103, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 132, in run
    inventory = Inventory(loader=loader, variable_manager=variable_manager, host_list=self.options.inventory)
  File "/usr/lib/python2.7/site-packages/ansible/inventory/__init__.py", line 97, in __init__
    self.parse_inventory(host_list)
  File "/usr/lib/python2.7/site-packages/ansible/inventory/__init__.py", line 181, in parse_inventory
    host.remove_group(ungrouped)
AttributeError: 'Host' object has no attribute 'remove_group'
```

##### Reasons
36b462b -- This commit seems to be the culprit, probably incompletely cherry-picked from the 2.3 branch. It should include
```python
def remove_group():
     ...
```
but it doesn't.

**Comment by bcoca** [comment] 2017-04-03 15:48
dupe of #23016

**Closed as completed by bcoca** 2017-04-03 15:48 UTC
Labels: affects_2.2, bug
