### ISSUE TITLE
ansible fails with UnicodeDecodeError on disk full

### ISSUE THREAD

**Issue by dmokin** [ansible/ansible#12870] opened 2015-10-22 14:12 UTC
When ansible tries to create temporary directory in
    mkdir -p $HOME/.ansible/tmp/ansible-tmp-....
on full disk I got unhandled exception UnicodeDecodeError

```
# ansible server1-testt11.cur.local -o -i hosts.rb -M /etc/ansible/modules -s -u ansible -m user -a "name=lbuild shell=/bin/bash group=users" -vvv
<server1-testt11.cur.local> ESTABLISH CONNECTION FOR USER: ansible
<server1-testt11.cur.local> REMOTE_MODULE user name=lbuild shell=/bin/bash group=users
<server1-testt11.cur.local> EXEC ssh -C -tt -v -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/ansible/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 server1-testt11.cur.local /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1445521612.21-234730712043546 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1445521612.21-234730712043546 && echo $HOME/.ansible/tmp/ansible-tmp-1445521612.21-234730712043546'
Traceback (most recent call last):
  File "/usr/bin/ansible", line 197, in <module>
    (runner, results) = cli.run(options, args)
  File "/usr/bin/ansible", line 171, in run
    results = runner.run()
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 1498, in run
    results = [ self._executor(h, None) for h in hosts ]
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 595, in _executor
    self.callbacks.on_unreachable(host, msg)
  File "/usr/lib/pymodules/python2.7/ansible/callbacks.py", line 396, in on_unreachable
    display("%s | FAILED => %s" % (host, res), stderr=True, color='red', runner=self.runner)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 517: ordinal not in range(128)
```

**Comment by jimi-c** [comment] 2015-10-22 15:00
This is a duplicate of https://github.com/ansible/ansible/issues/11210, which has been marked as resolved as fixed in the 1.9.4 release. Please upgrade, and retest.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-10-22 15:00 UTC
