### ISSUE TITLE
Ansible mangles integers in lists

### ISSUE THREAD

**Issue by fgimian** [ansible/ansible#19851] opened 2017-01-04 04:23 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible core

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
None

##### OS / ENVIRONMENT
macOS Sierra 10.11.6
Python 2.7.13

##### SUMMARY
Lists containing integers are casted to strings when using `set_fact`

##### STEPS TO REPRODUCE
```yaml
- hosts: localhost
  vars:
    numbers:
      - 123
      - 234

  tasks:
    - name: show numbers[0]
      debug: msg="{{ numbers[0] | to_json }}"

    - name: set fact_number = numbers[0]
      set_fact: fact_number="{{ numbers[0] }}"

    - name: show fact_number
      debug: msg="{{ fact_number | to_json }}"

    - name: set fact_number = numbers[0] and expilicitly cast to int
      set_fact: fact_number="{{ numbers[0] | int }}"

    - name: show fact_number
      debug: msg="{{ fact_number | to_json }}"
```

##### EXPECTED RESULTS

```
PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [show numbers[0]] *********************************************************
ok: [localhost] => {
    "msg": "123"
}

TASK [set fact_number = numbers[0]] ********************************************
ok: [localhost]

TASK [show fact_number] ********************************************************
ok: [localhost] => {
    "msg": "123"
}

TASK [set fact_number = numbers[0] and expilicitly cast to int] ****************
ok: [localhost]

TASK [show fact_number] ********************************************************
ok: [localhost] => {
    "msg": "123"
}
```

##### ACTUAL RESULTS

```
PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [show numbers[0]] *********************************************************
ok: [localhost] => {
    "msg": "123"
}

TASK [set fact_number = numbers[0]] ********************************************
ok: [localhost]

TASK [show fact_number] ********************************************************
ok: [localhost] => {
    "msg": "\"123\""
}

TASK [set fact_number = numbers[0] and expilicitly cast to int] ****************
ok: [localhost]

TASK [show fact_number] ********************************************************
ok: [localhost] => {
    "msg": "\"123\""
}
```

**Comment by alikins** [comment] 2017-01-05 18:37
This sounds like a dupe of https://github.com/ansible/ansible/issues/17992

**Comment by dagwieers** [comment] 2017-09-21 10:12
There is a light at the end of the tunnel. We made a change to Jinja2 so we don't see all variable types changed into strings. See: https://github.com/pallets/jinja/pull/708

**Comment by dagwieers** [comment] 2017-11-01 01:27
Duplicate of #17992

**Closed as completed by dagwieers** 2017-11-01 01:27 UTC
Labels: affects_2.2, support:core, bug
