### ISSUE TITLE
GLPI support

### ISSUE THREAD

**Issue by camlafit** [ansible/ansible#12466] opened 2015-09-22 07:48 UTC
Hi

I've developed an inventory script to get data from [glpi](http://www.glpi-project.org/). 
It's published here : https://github.com/Webelys/glpi_ansible

Maybe can be usefull to others.

**Comment by jimi-c** [comment] 2015-09-22 12:06
Hi @camlafit, could you please instead submit this as a PR? I'll close this otherwise, as it is not a bug report. Thanks!

**Closed as completed by jimi-c** 2015-09-22 12:06 UTC

**Comment by camlafit** [comment] 2015-09-22 12:14
Hi

Ok I'll prepare a PR.

Thanks
