### ISSUE TITLE
Variable inventory_dir does not (alway) provide an absolute path

### ISSUE THREAD

**Issue by jurgenhaas** [ansible/ansible#4291] opened 2013-09-29 09:25 UTC
When calling a playbook with "ansible-playbook -i ../inventories/something/hosts book.yml" and then using the variable inventory_dir, the result is "../inventories/something" where the expected result would be /path/to/ansible/inventories/something"

This is being tested with the dev release of Ansible as of 29th Sep 2013.

**Comment by mpdehaan** [comment] 2013-09-29 18:35
Thanks for the heads up.

Looks like we just need to add an os.path.abspath in the code.

**Comment by mpdehaan** [comment] 2013-10-07 21:34
I tried this on the development branch and could not produce this problem

vi /tmp/test.yml
mkdir /tmp/subdirectory
cd /tmp/subdirectory
ansible-playbook ../tmp/test.yml

Looks like this is already fixed on the development branch.

**Closed as completed by mpdehaan** 2013-10-07 21:34 UTC
Labels: needs_info, bug

**Comment by jurgenhaas** [comment] 2013-10-14 06:35
Unfortunately, it's not. I guess the problem comes from the "-i ../inventories/company1/hosts" parameter and not from the ../tmp/test.yml playbook parameter.

Can I upload an archive? Then I could provide you with a very basic example demonstrating the effect.

**Comment by mpdehaan** [comment] 2013-10-14 12:30
We don't take tarball uploads, but you can provide steps to reproduce the problem, or a minimal example that reproduces the problem as a github repo.

**Comment by jurgenhaas** [comment] 2013-10-14 13:45
The structure is described here: https://groups.google.com/d/msg/ansible-project/BPnZPe_Ixhg/6rI0PSByj0cJ

Main parts are:

Inventory:
/path/to/workingdir/inventories/company1/hosts

Script:
/path/to/workingdir/scripts/test4291.sh

Playbook:
/path/to/workingdir/playbooks/test4291.yml

In the test-script there is this 1 line: ansible-playbook -i ../inventories/company1/hosts ../playbooks/test4291.yml

In the playbook there is this:
- name: 'Test for issue 4291'
  hosts: all
  connection: local
  tasks:
  - name: 'Output message'
    debug: msg="hello, your dir is {{ inventory_dir }} - are you OK with that?"

The output is:

PLAY [Test for issue 4291] ***************************************************\* 

GATHERING FACTS **************************************************************\* 
ok: [localhost]

TASK: [Output message] *******************************************************\* 
ok: [localhost] => {"msg": "hello, your dir is ../inventories/company1 - are you OK with that?"}

PLAY RECAP *******************************************************************\* 
localhost                  : ok=2    changed=0    unreachable=0    failed=0   

Conclusion: {{ inventory_dir }} provides "../inventories/company1" as the value but "/path/to/workingdir/inventories/company1" is expected.

**Comment by mpdehaan** [comment] 2013-10-16 01:33
Can you upload this as gist or repo so it's not mangled by the github formatter?

**Comment by jurgenhaas** [comment] 2013-10-16 06:45
Here (https://gist.github.com/jurgenhaas/7003535) is the gist and attached is a screenshot with the directory structure for those 3 files.
![auswahl_001](https://f.cloud.github.com/assets/1475675/1340393/8427d92c-362e-11e3-8faf-5b769a736f48.jpg)
