### ISSUE TITLE
Lots of stuff still using /usr/bin/python instead of /usr/bin/env python

### ISSUE THREAD

**Issue by edrozenberg** [ansible/ansible#10986] opened 2015-05-12 02:59 UTC
I'm far from a Python expert but shouldn't everything use /usr/bin/env python instead of /usr/bin/python?

For ex. cloud modules like 
https://github.com/ansible/ansible-modules-core/blob/devel/cloud/amazon/ec2.py

Since many folks are using homebrew python, this can cause issues with running local tasks that involve python site-packages modules. My ec2 tasks couldn't find boto because my boto is installed in /usr/local/lib/python2.7/site-packages and the ansible ec2 module was calling /usr/bin/python.

In the end the only solution was something like:

```
[localhost]
127.0.0.1 ansible_python_interpreter=/usr/local/bin/python
```

**Comment by bcoca** [comment] 2015-05-12 03:08
This is on purpose to allow for this:
http://docs.ansible.com/faq.html#how-do-i-handle-python-pathing-not-having-a-python-2-x-in-usr-bin-python-on-a-remote-machine

We've had a lot of problems with homebrew and it's paths so we do not recommend using it to install ansible. Closing this ticket at this is not a bug.

**Closed as completed by bcoca** 2015-05-12 03:08 UTC

**Comment by edrozenberg** [comment] 2015-05-12 03:27
By the way I was referring only to Homebrew Python2 in this issue. I'd learned my lesson and have been running pip2 ansible for some days now.  Regards, --Ed
