### ISSUE TITLE
Task names do not render correctly when they contain a variable with filters

### ISSUE THREAD

**Issue by organman91** [ansible/ansible#10386] opened 2015-03-05 00:17 UTC
For instance, in a role's vars/main.yml, I have the following:

``` YAML
luks_dev: "{{ luks_device | mandatory }}"
```

I then have a task that uses this variable in its name:

``` YAML
- name: initialize luks in "{{ luks_dev }}"
```

This produces the following output:

``` BASH
TASK: [luks | initialize luks in "{{ luks_device | mandatory }}"] *************
```

**Comment by autotune** [comment] 2015-03-16 03:12
I'm actually not seeing task showing ANY variables displayed for TASK name, let alone for filters, on Ansible 1.9 devel using CentOS 6.5:

[brian@controller issues]$ ansible-playbook 10386.yml

```
PLAY [localhost] **************************************************************
GATHERING FACTS ***************************************************************
ok: [localhost]
TASK: [{{ cent  }}] ***********************************************************
ok: [localhost]
TASK: [debug msg="{{ cent }}"] ************************************************
 ok: [localhost] => {
        "msg": "CentOS 6.5"
 }

PLAY RECAP ********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0
```

**Comment by abadger** [comment] 2015-03-16 15:33
Duplicate of this bug: https://github.com/ansible/ansible/issues/10347  Feel free to add any details that aren't present there.

**Closed as completed by abadger** 2015-03-16 15:33 UTC
Labels: bug
