### ISSUE TITLE
allow for nonexistent src when creating symlinks

### ISSUE THREAD

**Issue by ccxcz** [ansible/ansible#2964] opened 2013-05-21 17:11 UTC
Currently when creating symlink using file command I get:
msg: src file does not exist
There are rare instances where it is desirable to have ability to create such symlinks, so I'd like to see at least a flag to disable this check.

**Comment by bcoca** [comment] 2013-05-21 18:27
Not all systems allow you to create a dangling symlink, but it should def
be an option.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by srgvg** [comment] 2013-05-21 19:15
+1 for the option

**Comment by mpdehaan** [comment] 2013-07-20 19:10
This is a duplicate of another ticket about symlink validation so I am closing this one.

In other words, more people agree :)

**Closed as completed by mpdehaan** 2013-07-20 19:10 UTC

**Comment by mmoya** [comment] 2013-10-15 12:09
FTR this got fixed by PR #3116 (I was unable to find the previous ticket @mpdehaan was referring to).
