### ISSUE TITLE
run_once with delegate_to not working as documented

### ISSUE THREAD

**Issue by paulrowlands** [ansible/ansible#38226] opened 2018-04-03 15:10 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

run_once with delegate_to

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/wsl-reveal-01/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### OS / ENVIRONMENT

DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']

##### SUMMARY

The Ansible documentation (http://ansible-docs.readthedocs.io/zh/stable-2.0/rst/playbooks_delegation.html) gives an example of using run_once with delegate_to to make a task only execute on a designated host:

- command: /opt/application/upgrade_db.py
  run_once: true
  delegate_to: web01.example.org

But it is not working for me.

My scenario is that I wish to automatically generate groups of servers in freeIPA from the groups in my Ansible inventory.

However, instead of using the server I specify in the delegate_to (in my case, the 1st server in my "freeipa-master-servers" group), Ansible is simply trying to use whatever happens to be the 1st server in my inventory (in this case, one called "wsl-mon-01").

##### STEPS TO REPRODUCE

Inventory (partial).
```
[freeipa-master-servers]
wsl-freeipa-01

[freeipa-replica-servers]
wsl-freeipa-02

[freeipa-misc-servers]
wsl-freeipa-03
wsl-freeipa-04
wsl-freeipa-05

[monitoring-servers]
wsl-mon-01
```
S516-freeipa-group-hosts.yaml
```yaml
---
- hosts: all
  name: Visit all hosts
  vars_files:
    - passwd.yml
  tasks:

  - name: S516-freeipa-group-hosts - freeIPA hosts groups membership
    ipa_hostgroup:
      name: "{{item}}"
      description: "Host Group {{item}}"
      host: "hosts={{'['}}{% for h in groups[item] %}{{h}}{{','}}{% endfor %}{{']'}}"
      ipa_host: "{{ansible_fqdn}}"
      ipa_user: admin
      ipa_pass: "{{ADMIN_PASSWD}}"
    run_once: True
    delegate_to: wsl-freeipa-01
    delegate_facts: True
    with_items: "{{group_names}}"
```

##### EXPECTED RESULTS

I expect the task to run on the server "wsl-freeipa-01" (and thereby add a number of host groups in the freeIPA application).

##### ACTUAL RESULTS

The task tries to run on another server "wsl-mon-01", which fails (because it's not running the freeIPA application).

```
ansible-playbook --ask-vault-pass -v playbooks/S516-freeipa-group-hosts.yaml
Using /home/wsl-reveal-01/ansible/wsl-reveal-01/freeipa/ansible.cfg as config file
Vault password: 

PLAY [Visit all hosts] *****************************************************************************

TASK [Gathering Facts] *****************************************************************************
ok: [wsl-bak-01]
ok: [wsl-ansible-01]
ok: [wsl-repo-01]
ok: [wsl-freeipa-01]
ok: [wsl-mon-01]
ok: [wsl-freeipa-03]
ok: [wsl-freeipa-02]
ok: [wsl-freeipa-05]
ok: [wsl-freeipa-04]
ok: [wsl-testbox-01]
ok: [wsl-testbox-02]
ok: [wsl-inbound-01]
ok: [wsl-jenkins-01]
ok: [wsl-logtest-01]
ok: [wsl-logtest-02]
ok: [wsl-teleport-01]
ok: [wsl-outbound-01]

TASK [S516-freeipa-group-hosts - freeIPA hosts groups membership] **********************************
failed: [wsl-mon-01 -> wsl-freeipa-01] (item=freeipa-client-servers) => {"changed": false, "item": "freeipa-client-servers", "msg": "Failed to connect to wsl-mon-01.wanless.example at port 443: [Errno 111] Connection refused"}
failed: [wsl-mon-01 -> wsl-freeipa-01] (item=freeipa-servers) => {"changed": false, "item": "freeipa-servers", "msg": "Failed to connect to wsl-mon-01.wanless.example at port 443: [Errno 111] Connection refused"}
failed: [wsl-mon-01 -> wsl-freeipa-01] (item=linux-servers) => {"changed": false, "item": "linux-servers", "msg": "Failed to connect to wsl-mon-01.wanless.example at port 443: [Errno 111] Connection refused"}
failed: [wsl-mon-01 -> wsl-freeipa-01] (item=monitoring-servers) => {"changed": false, "item": "monitoring-servers", "msg": "Failed to connect to wsl-mon-01.wanless.example at port 443: [Errno 111] Connection refused"}
failed: [wsl-mon-01 -> wsl-freeipa-01] (item=snmp-clients) => {"changed": false, "item": "snmp-clients", "msg": "Failed to connect to wsl-mon-01.wanless.example at port 443: [Errno 111] Connection refused"}
failed: [wsl-mon-01 -> wsl-freeipa-01] (item=teleport-clients) => {"changed": false, "item": "teleport-clients", "msg": "Failed to connect to wsl-mon-01.wanless.example at port 443: [Errno 111] Connection refused"}

NO MORE HOSTS LEFT *********************************************************************************
	to retry, use: --limit @/home/wsl-reveal-01/ansible/wsl-reveal-01/freeipa/playbooks/S516-freeipa-group-hosts.retry

PLAY RECAP *****************************************************************************************
wsl-ansible-01             : ok=1    changed=0    unreachable=0    failed=0   
wsl-bak-01                 : ok=1    changed=0    unreachable=0    failed=0   
wsl-freeipa-01             : ok=1    changed=0    unreachable=0    failed=0   
wsl-freeipa-02             : ok=1    changed=0    unreachable=0    failed=0   
wsl-freeipa-03             : ok=1    changed=0    unreachable=0    failed=0   
wsl-freeipa-04             : ok=1    changed=0    unreachable=0    failed=0   
wsl-freeipa-05             : ok=1    changed=0    unreachable=0    failed=0   
wsl-inbound-01             : ok=1    changed=0    unreachable=0    failed=0   
wsl-jenkins-01             : ok=1    changed=0    unreachable=0    failed=0   
wsl-logtest-01             : ok=1    changed=0    unreachable=0    failed=0   
wsl-logtest-02             : ok=1    changed=0    unreachable=0    failed=0   
wsl-mon-01                 : ok=1    changed=0    unreachable=0    failed=1   
wsl-outbound-01            : ok=1    changed=0    unreachable=0    failed=0   
wsl-repo-01                : ok=1    changed=0    unreachable=0    failed=0   
wsl-teleport-01            : ok=1    changed=0    unreachable=0    failed=0   
wsl-testbox-01             : ok=1    changed=0    unreachable=0    failed=0   
wsl-testbox-02             : ok=1    changed=0    unreachable=0    failed=0   
```
##### NOTES
If I comment out the run_once and delegate_to items in the above playbook and run it, it successfully performs the action for the groups of which "wsl-freeipa-01" is a member (and "wsl-freeipa-02" as well), but then attempts and fails to execute to execute tasks against random (or all) hosts.

**Comment by sivel** [comment] 2018-04-03 15:12
Please provide additional actionable information about what you are doing, what you expect and what exactly is happening currently.

needs_info

**Comment by paulrowlands** [comment] 2018-04-03 15:40
Sorry - I was saving between completing the form - is there enough info there now?

**Comment by sivel** [comment] 2018-04-03 15:48
The problem is with how you are setting `ipa_host`:

```
ipa_host: "{{ansible_fqdn}}"
```

That `ansible_fqdn` will still be the value of the targeted host, and not the delegated host.

You likely instead want:

```
ipa_host: "{{ hostvars['wsl-freeipa-01'].ansible_fqdn }}"
```

needs_info

**Comment by paulrowlands** [comment] 2018-04-03 15:54
Aha - I think you are right - the error was between the chair and the keyboard!

I've made that change and now it's talking to the right server.

Many thanks for your help!

**Comment by paulrowlands** [comment] 2018-04-03 15:58
I've now noticed that the runbook messages & play recap still mention the "wsl-mon-01" server, even though the tasks do get performed on the correct one.

TASK [S516-freeipa-group-hosts - freeIPA hosts groups membership] **********************************
changed: [wsl-mon-01 -> wsl-freeipa-01] => (item=freeipa-client-servers)
changed: [wsl-mon-01 -> wsl-freeipa-01] => (item=freeipa-servers)
changed: [wsl-mon-01 -> wsl-freeipa-01] => (item=linux-servers)
changed: [wsl-mon-01 -> wsl-freeipa-01] => (item=monitoring-servers)
changed: [wsl-mon-01 -> wsl-freeipa-01] => (item=snmp-clients)
changed: [wsl-mon-01 -> wsl-freeipa-01] => (item=teleport-clients)

PLAY RECAP *****************************************************************************************
wsl-ansible-01             : ok=1    changed=0    unreachable=0    failed=0   
wsl-bak-01                 : ok=1    changed=0    unreachable=0    failed=0   
wsl-freeipa-01             : ok=1    changed=0    unreachable=0    failed=0   
wsl-freeipa-02             : ok=1    changed=0    unreachable=0    failed=0   
wsl-freeipa-03             : ok=1    changed=0    unreachable=0    failed=0   
wsl-freeipa-04             : ok=1    changed=0    unreachable=0    failed=0   
wsl-freeipa-05             : ok=1    changed=0    unreachable=0    failed=0   
wsl-inbound-01             : ok=1    changed=0    unreachable=0    failed=0   
wsl-jenkins-01             : ok=1    changed=0    unreachable=0    failed=0   
wsl-logtest-01             : ok=1    changed=0    unreachable=0    failed=0   
wsl-logtest-02             : ok=1    changed=0    unreachable=0    failed=0   
wsl-mon-01                 : ok=2    changed=1    unreachable=0    failed=0   
wsl-outbound-01            : ok=1    changed=0    unreachable=0    failed=0   
wsl-repo-01                : ok=1    changed=0    unreachable=0    failed=0   
wsl-teleport-01            : ok=1    changed=0    unreachable=0    failed=0   
wsl-testbox-01             : ok=1    changed=0    unreachable=0    failed=0   
wsl-testbox-02             : ok=1    changed=0    unreachable=0    failed=0

**Comment by sivel** [comment] 2018-06-25 20:44
Closing as this was resolved.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Closed as completed by sivel** 2018-06-25 20:44 UTC
Labels: affects_2.4, support:core, bug
