### ISSUE TITLE
Second play of a role doesn't evaluate dependencies

### ISSUE THREAD

**Issue by rncry** [ansible/ansible#11367] opened 2015-06-24 13:22 UTC
I'm trying to deploy the same role to different sets of machines spun up in ec2, a playbook contains 2 different plays to apply this role to different machines. The first play works and the role is applied along with its dependencies. The next play fails however as ansible attempts to apply the role without dependencies. Example playbook is below:

```

---

- name: Consul bootstrap server
  hosts: localhost
  gather_facts: False
  vars:
    launch_group: consul_bootstrap
    count: 1
    image: ami-e4ff5c93
    tags:
      Name: Ansible consul bootstrap
      consul: bootstrap
  roles:
    - ec2_start

- name: Consul servers
  hosts: localhost
  gather_facts: False
  vars:
    launch_group: consul_server
    count: 2
    image: ami-e4ff5c93
    tags:
      Name: Ansible consul server
      consul: server
  roles:
    - ec2_start

- name: setup fs and users
  gather_facts: True
  hosts: launched_ec2
  sudo: True
  user: centos
  roles:
    - cloud_base

- name: Bootstrap consul server
  gather_facts: True
  hosts: consul_bootstrap
  sudo: True
  user: username
  roles:
    - consul_server

- name: Add other consul servers
  gather_facts: True
  hosts: consul_server
  sudo: True
  user: username
  vars:
    consul_command: -join {{ hostvars[groups['consul_bootstrap'][0]]['ansible_eth0']['ipv4']['address'] }}
  roles:
    - consul_server
```

**Comment by rncry** [comment] 2015-06-24 13:23
The 'Add other consul servers' play fails.

**Comment by bcoca** [comment] 2015-06-27 05:01
with what error? verbose if possible, also what version of ansible, python, OS? or just fill in the template: https://github.com/ansible/ansible/blob/devel/ISSUE_TEMPLATE.md

**Comment by rncry** [comment] 2015-06-29 07:59
@bcoca I'm not sure the error message will be very productive, in this particular playbook it complains about docker not being present on the host when it tries to run a docker command, but this is just because the dependencies for 'consul_server' (one of which installs docker) have not been applied.

The 'bootstrap consul server' play works fine and applies the dependencies for 'consul_server' before it is applied. However the second time the role 'consul_server' is applied (in 'Add other consul servers') to different hosts, the dependent roles for 'consul_server' are not executed and so it fails. The problem is that the dependent roles are not being applied, not the actual error that we're getting (the error itself makes perfect sense).

This was from latest devel build of ansible, python 2.7, centos 7 on the host.

I've reverted to Ansible 1.9 and this all works fine.

**Comment by jimi-c** [comment] 2015-07-21 04:51
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a simple reproducer:

<pre>
# cat test.yml 
- hosts: host1
  gather_facts: no
  vars:
    foo: bar
  roles:
  - child
- hosts: host2
  gather_facts: no
  vars:
    foo: bam
  roles:
  - child
# cat inv 
host1 ansible_connection=local
host2 ansible_connection=local
# ansible-playbook -vv test.yml -i inv 
Using /etc/ansible/ansible.cfg as config file
2 plays in test.yml
PLAY ****************************************************************************
TASK [parent : parent : debug msg=foo in the parent is bar] *********************
ok: [host1] => {
    "changed": false, 
    "msg": "foo in the parent is bar"
}
TASK [child : child : debug msg=this is the child role] *************************
ok: [host1] => {
    "changed": false, 
    "msg": "this is the child role"
}
PLAY ****************************************************************************
TASK [parent : parent : debug msg=foo in the parent is bam] *********************
ok: [host2] => {
    "changed": false, 
    "msg": "foo in the parent is bam"
}
TASK [child : child : debug msg=this is the child role] *************************
ok: [host2] => {
    "changed": false, 
    "msg": "this is the child role"
}
PLAY RECAP **********************************************************************
host1                      : ok=2    changed=0    unreachable=0    failed=0   
host2                      : ok=2    changed=0    unreachable=0    failed=0   
</pre>

The meta/main.yml for the child simply lists the parent role as a dependency, and each role has a single debug statement (for which you see the output above).

Per our normal policy, we close bug report issues when we see the issue has been corrected in the devel branch, so we will close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-07-21 04:51 UTC
Labels: P2, bug
