### ISSUE TITLE
Cannot connect to hosts with long hostsnames (needs info)

### ISSUE THREAD

**Issue by mr-gadget** [ansible/ansible#8859] opened 2014-09-02 20:33 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.1
##### Environment:

Ubuntu 12.04.5
##### Summary:

I have problems connecting to a host with a lengthy hostname that go away if I use a slightly shorter CNAME or IP pointing to the same host.
##### Steps To Reproduce:

If I run the command 

```
 ansible <long hostname> -m ping
```

I get an error. If I run the command 

```
 ansible <slightly shorter cname pointing to the same host> -m ping
```

 it works. The hostname with a problem is 37 characters long. The CNAME (that works) that points to the same host is 32 characters long. 
##### Expected Results:

I expected to be able to run the command with the FQDN successfully without having to use the CNAME.
##### Actual Results:

The error I get is: 

```
 FAILED => SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh
```

I have turned up the debugging on SSH on the server and can tell that ansible is not even trying to connect when I get the error. I _do_ see the expected log entries showing a connection when using the shorter CNAME. I can also successfully connect as the user I am running ansible as via

```
ssh ansible_user@<long hostname>
```

 and it works.

I am wondering if there is something significant to the fact that 32 characters work, but not more.

**Comment by mscherer** [comment] 2014-09-02 21:57
Can you run it with ansible -vvvv and paste the result ? What connexion are you using, paramiko, ssh ?

**Comment by mpdehaan** [comment] 2014-09-03 00:20
If control persist sockets are too long this usually manifests with a more specific error and then that's tunable in ansible.cfg.

But yes, I'd very much like to see the -vvvv SSH debug output.

You should be running the -c ssh (OpenSSH) configuration type by default unless you are running from RHEL/CentOS 6.X or before. which it seems you are.

**Comment by mr-gadget** [comment] 2014-09-03 13:42
Ok, the output from

```
ansible -vvvv <long hostname> -m ping is
<long hostname> ESTABLISH CONNECTION FOR USER: supertcat
<long hostname> REMOTE_MODULE ping
<long hostname> EXEC ['ssh', '-C', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/likewise-open/CITD/supertcat/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=30', 'long hostname', u"/bin/sh -c 'LANG=C LC_CTYPE=C /usr/bin/python'"]
long hostname | FAILED => SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh
```

with hostname redacted

Output from 

```
ansible -vvvv <shorter CNAME> -m ping
<shorter CNAME> ESTABLISH CONNECTION FOR USER: supertcat
<shorter CNAME> REMOTE_MODULE ping
<shorter CNAME> EXEC ['ssh', '-C', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/likewise-open/CITD/supertcat/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=30', 'shorter CNAME', u"/bin/sh -c 'LANG=C LC_CTYPE=C /usr/bin/python'"]
shorter CNAME | success >> {
    "changed": false,
    "ping": "pong"
}
```

The ansible host and the target machine are both running Ubuntu 12.04.5, kernel 3.13.0-34
I have transport = smart and pipelining = True in my ansible.cfg

Let me know if you need more information on any of this.

**Comment by mpdehaan** [comment] 2014-09-03 16:24
Looks like this may not be a hostname length issue from the above seeing I don't see an error about control paths.

**Comment by mr-gadget** [comment] 2014-09-03 18:33
If you can tell me what, if any, additional info you need from me, I'd be glad to try to get it for you.

**Comment by mscherer** [comment] 2014-09-03 18:36
Can you try without transport = smart ( ie, transport = paramiko ) ? I can reproduce, but in my case, that's indeed ControlPath being too long and it show properly. I suspect that the lenghty homedir part may trigger some corner case.

**Comment by mscherer** [comment] 2014-09-03 18:52
Also, it may help if you could directly use the command that ansible use. Too bad that's not easy to cut and paste from the output log :/

**Comment by mr-gadget** [comment] 2014-09-03 19:39
With transport = paramiko, it works with the long hostname.

```
<long hostname> ESTABLISH CONNECTION FOR USER: supertcat on PORT 22 TO long hostname
<long hostname> REMOTE_MODULE ping
<long hostname> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1409772716.67-32152145151173 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1409772716.67-32152145151173 && echo $HOME/.ansible/tmp/ansible-tmp-1409772716.67-32152145151173'
<long hostname> PUT /tmp/tmpJgcAmZ TO /home/likewise-open/CITD/supertcat/.ansible/tmp/ansible-tmp-1409772716.67-32152145151173/ping
<long hostname> EXEC /bin/sh -c 'LANG=C LC_CTYPE=C /usr/bin/python /home/likewise-open/CITD/supertcat/.ansible/tmp/ansible-tmp-1409772716.67-32152145151173/ping; rm -rf /home/likewise-open/CITD/supertcat/.ansible/tmp/ansible-tmp-1409772716.67-32152145151173/ >/dev/null 2>&1'
long hostname | success >> {
    "changed": false,
    "ping": "pong"
}
```

Not sure what you mean by "directly use the command that ansible uses". Does the above help, though?

**Comment by mscherer** [comment] 2014-09-04 13:18
In the debug log, there is the command used by ansible: 

```
EXEC ['ssh', '-C', '-vvv', '-o', 'ControlMaster=auto', ..... 
```

Can you try to use the exact same ssh command and see the error message ?

**Comment by mr-gadget** [comment] 2014-09-04 16:11
Ok, still not entirely sure what you are asking me to do. I tried this:

```
ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath=/home/likewise-open/CITD/supertcat/.ansible/cp/ansible-ssh-1 -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=30 long-hostname "/bin/sh -c 'LANG=C LC_CTYPE=C /usr/bin/python'"
```

This appeared to connect and be waiting for more commands. See output snippet below:

```
debug3: start over, passed a different list publickey,gssapi-keyex,gssapi-with-mic,password,keyboard-interactive
debug3: preferred gssapi-with-mic,gssapi-keyex,hostbased,publickey
debug3: authmethod_lookup gssapi-with-mic
debug3: remaining preferred: gssapi-keyex,hostbased,publickey
debug3: authmethod_is_enabled gssapi-with-mic
debug1: Next authentication method: gssapi-with-mic
debug1: Unspecified GSS failure.  Minor code may provide more information
Credentials cache file '/tmp/krb5cc_757085574' not found

debug1: Unspecified GSS failure.  Minor code may provide more information
Credentials cache file '/tmp/krb5cc_757085574' not found

debug1: Unspecified GSS failure.  Minor code may provide more information


debug1: Unspecified GSS failure.  Minor code may provide more information
Credentials cache file '/tmp/krb5cc_757085574' not found

debug2: we did not send a packet, disable method
debug3: authmethod_lookup gssapi-keyex
debug3: remaining preferred: hostbased,publickey
debug3: authmethod_is_enabled gssapi-keyex
debug1: Next authentication method: gssapi-keyex
debug1: No valid Key exchange context
debug2: we did not send a packet, disable method
debug3: authmethod_lookup publickey
debug3: remaining preferred: ,publickey
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /home/likewise-open/CITD/supertcat/.ssh/id_rsa_ansible
debug3: send_pubkey_test
debug2: we sent a publickey packet, wait for reply
debug1: Server accepts key: pkalg ssh-rsa blen 279
debug2: input_userauth_pk_ok: fp redacted
debug3: sign_and_send_pubkey: RSA redacted
debug1: Enabling compression at level 6.
debug1: Authentication succeeded (publickey).
Authenticated to long-hostname ([x.x.x.x]:22).
debug1: setting up multiplex master socket
debug3: muxserver_listen: temporary control path /home/likewise-open/CITD/supertcat/.ansible/cp/ansible-ssh-1.r6RtZjrVPClNY6lY
debug2: fd 5 setting O_NONBLOCK
debug3: fd 5 is O_NONBLOCK
debug3: fd 5 is O_NONBLOCK
debug1: channel 0: new [/home/likewise-open/CITD/supertcat/.ansible/cp/ansible-ssh-1]
debug3: muxserver_listen: mux listener channel 0 fd 5
debug1: control_persist_detach: backgrounding master process
debug2: control_persist_detach: background process is 13238
debug2: fd 5 setting O_NONBLOCK
debug1: forking to background
debug1: Entering interactive session.
debug2: set_control_persist_exit_time: schedule exit in 60 seconds
debug1: multiplexing control connection
debug2: fd 6 setting O_NONBLOCK
debug3: fd 6 is O_NONBLOCK
debug1: channel 1: new [mux-control]
debug3: channel_post_mux_listener: new mux channel 1 fd 6
debug3: mux_master_read_cb: channel 1: hello sent
debug2: set_control_persist_exit_time: cancel scheduled exit
debug3: mux_master_read_cb: channel 1 packet type 0x00000001 len 4
debug2: process_mux_master_hello: channel 1 slave version 4
debug2: mux_client_hello_exchange: master version 4
debug3: mux_client_request_forwards: requesting forwardings: 0 local, 0 remote
debug3: mux_client_request_session: entering
debug3: mux_client_request_alive: entering
debug3: mux_master_read_cb: channel 1 packet type 0x10000004 len 4
debug2: process_mux_alive_check: channel 1: alive check
debug3: mux_client_request_alive: done pid = 13239
debug3: mux_master_read_cb: channel 1 packet type 0x10000002 len 107
debug2: process_mux_new_session: channel 1: request tty 0, X 0, agent 0, subsys 0, term "xterm", cmd "/bin/sh -c 'LANG=C LC_CTYPE=C /usr/bin/python'", env 1
debug3: mm_receive_fd: recvmsg: Resource temporarily unavailable
debug3: mm_receive_fd: recvmsg: Resource temporarily unavailable
debug3: mm_receive_fd: recvmsg: Resource temporarily unavailable
debug3: process_mux_new_session: got fds stdin 7, stdout 8, stderr 9
debug1: channel 2: new [client-session]
debug2: process_mux_new_session: channel_new: 2 linked to control channel 1
debug2: channel 2: send open
debug3: mux_client_request_session: session request sent
debug2: callback start
debug2: client_session2_setup: id 2
debug2: fd 4 setting TCP_NODELAY
debug1: Sending environment.
debug1: Sending env LANG = en_US.UTF-8
debug2: channel 2: request env confirm 0
debug1: Sending command: /bin/sh -c 'LANG=C LC_CTYPE=C /usr/bin/python'
debug2: channel 2: request exec confirm 1
debug3: mux_session_confirm: sending success reply
debug2: callback done
debug2: channel 2: open confirm rwindow 0 rmax 32768
debug1: mux_client_request_session: master session id: 2
debug2: channel 2: rcvd adjust 2097152
debug2: channel_input_status_confirm: type 99 id 2
debug2: exec request accepted on channel 2

debug3: start over, passed a different list publickey,gssapi-keyex,gssapi-with-mic,password,keyboard-interactive
debug3: preferred gssapi-with-mic,gssapi-keyex,hostbased,publickey
debug3: authmethod_lookup gssapi-with-mic
debug3: remaining preferred: gssapi-keyex,hostbased,publickey
debug3: authmethod_is_enabled gssapi-with-mic
debug1: Next authentication method: gssapi-with-mic
debug1: Unspecified GSS failure.  Minor code may provide more information
Credentials cache file '/tmp/krb5cc_757085574' not found

debug1: Unspecified GSS failure.  Minor code may provide more information
Credentials cache file '/tmp/krb5cc_757085574' not found

debug1: Unspecified GSS failure.  Minor code may provide more information


debug1: Unspecified GSS failure.  Minor code may provide more information
Credentials cache file '/tmp/krb5cc_757085574' not found

debug2: we did not send a packet, disable method
debug3: authmethod_lookup gssapi-keyex
debug3: remaining preferred: hostbased,publickey
debug3: authmethod_is_enabled gssapi-keyex
debug1: Next authentication method: gssapi-keyex
debug1: No valid Key exchange context
debug2: we did not send a packet, disable method
debug3: authmethod_lookup publickey
debug3: remaining preferred: ,publickey
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /home/likewise-open/CITD/supertcat/.ssh/id_rsa_ansible
debug3: send_pubkey_test
debug2: we sent a publickey packet, wait for reply
debug1: Server accepts key: pkalg ssh-rsa blen 279
debug2: input_userauth_pk_ok: fp redacted
debug3: sign_and_send_pubkey: RSA redacted
debug1: Enabling compression at level 6.
debug1: Authentication succeeded (publickey).
Authenticated to long-hostname ([x.x.x.x]:22).
debug1: setting up multiplex master socket
debug3: muxserver_listen: temporary control path /home/likewise-open/CITD/supertcat/.ansible/cp/ansible-ssh-1.r6RtZjrVPClNY6lY
debug2: fd 5 setting O_NONBLOCK
debug3: fd 5 is O_NONBLOCK
debug3: fd 5 is O_NONBLOCK
debug1: channel 0: new [/home/likewise-open/CITD/supertcat/.ansible/cp/ansible-ssh-1]
debug3: muxserver_listen: mux listener channel 0 fd 5
debug1: control_persist_detach: backgrounding master process
debug2: control_persist_detach: background process is 13238
debug2: fd 5 setting O_NONBLOCK
debug1: forking to background
debug1: Entering interactive session.
debug2: set_control_persist_exit_time: schedule exit in 60 seconds
debug1: multiplexing control connection
debug2: fd 6 setting O_NONBLOCK
debug3: fd 6 is O_NONBLOCK
debug1: channel 1: new [mux-control]
debug3: channel_post_mux_listener: new mux channel 1 fd 6
debug3: mux_master_read_cb: channel 1: hello sent
debug2: set_control_persist_exit_time: cancel scheduled exit
debug3: mux_master_read_cb: channel 1 packet type 0x00000001 len 4
debug2: process_mux_master_hello: channel 1 slave version 4
debug2: mux_client_hello_exchange: master version 4
debug3: mux_client_request_forwards: requesting forwardings: 0 local, 0 remote
debug3: mux_client_request_session: entering
debug3: mux_client_request_alive: entering
debug3: mux_master_read_cb: channel 1 packet type 0x10000004 len 4
debug2: process_mux_alive_check: channel 1: alive check
debug3: mux_client_request_alive: done pid = 13239
debug3: mux_master_read_cb: channel 1 packet type 0x10000002 len 107
debug2: process_mux_new_session: channel 1: request tty 0, X 0, agent 0, subsys 0, term "xterm", cmd "/bin/sh -c 'LANG=C LC_CTYPE=C /usr/bin/python'", env 1
debug3: mm_receive_fd: recvmsg: Resource temporarily unavailable
debug3: mm_receive_fd: recvmsg: Resource temporarily unavailable
debug3: mm_receive_fd: recvmsg: Resource temporarily unavailable
debug3: process_mux_new_session: got fds stdin 7, stdout 8, stderr 9
debug1: channel 2: new [client-session]
debug2: process_mux_new_session: channel_new: 2 linked to control channel 1
debug2: channel 2: send open
debug3: mux_client_request_session: session request sent
debug2: callback start
debug2: client_session2_setup: id 2
debug2: fd 4 setting TCP_NODELAY
debug1: Sending environment.
debug1: Sending env LANG = en_US.UTF-8
debug2: channel 2: request env confirm 0
debug1: Sending command: /bin/sh -c 'LANG=C LC_CTYPE=C /usr/bin/python'
debug2: channel 2: request exec confirm 1
debug3: mux_session_confirm: sending success reply
debug2: callback done
debug2: channel 2: open confirm rwindow 0 rmax 32768
debug1: mux_client_request_session: master session id: 2
debug2: channel 2: rcvd adjust 2097152
debug2: channel_input_status_confirm: type 99 id 2
debug2: exec request accepted on channel 2
```

Hope that helps. Let me know if there is anything else I can do.

**Comment by mscherer** [comment] 2014-09-04 17:08
yeah, it help, but still do not really show what is wrong :/

**Comment by jimi-c** [comment] 2014-09-17 20:55
@mr-gadget, could you prepend your ansible command with `ANSIBLE_SSH_CONTROL_PATH=/tmp/ansible_cp_test`? (NOTE: Do not do this in production, as it leaves your ssh control socket in a wide open and easily found place, which is not safe). 

Typically there is an error message related to ControlPersist having issues with long paths, however in this case there isn't. If ansible works when using the above with the long hostname, we can pretty conclusively say that that is the issue, otherwise we can eliminate it and look elsewhere.

**Comment by mpdehaan** [comment] 2014-09-29 21:25
Hi, I'm going to close this one due to lack of info with the above request.   If there are any updates on this one feel free to reopen a new ticket.

Thanks!

**Closed as completed by mpdehaan** 2014-09-29 21:25 UTC
Labels: needs_info, P2, bug
