### ISSUE TITLE
Strategy free exits with code 1

### ISSUE THREAD

**Issue by kamsz** [ansible/ansible#18023] opened 2016-10-14 08:43 UTC
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

free strategy
##### ANSIBLE VERSION

```
root@mbn:~/nimis/ansible# ansible --version
ansible 2.2.0.0
  config file = /root/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
[defaults]
#callback_plugins=callback_plugins
#callback_whitelist=timer,profile_tasks
fact_caching_connection=ansible_facts.json
fact_caching_timeout=600
fact_caching=jsonfile
forks=100
gathering=smart
host_key_checking=False
remote_user=root
retry_files_enabled=False

[ssh_connection]
retries=5
ssh_args=-o ControlMaster=auto -o ControlPersist=300s -o UserKnownHostsFile=/dev/null
pipelining=True
```
##### OS / ENVIRONMENT

Ubuntu 16.04
##### SUMMARY

When using strategy: free all playbooks exit with code 1. After changing the strategy to default, a proper exit code (0) is returned.
##### STEPS TO REPRODUCE

```

---
- hosts: localhost
  strategy: free
  tasks:
    - debug: msg='test'
```

root@mbn:~/ansible# echo $?
1

```

---
- hosts: localhost
  #strategy: free
  tasks:
    - debug: msg='test'
```

root@mbn:~/ansible# echo $?
0
##### EXPECTED RESULTS

Running playbook with strategy free should exit with 0 when playbook has executed successfully.
##### ACTUAL RESULTS

Running playbook with strategy free exists with exit code 1.

**Comment by jctanner** [comment] 2016-10-14 14:01
I was able to reproduce with devel -and- 2.2rc1

```
v2.0.1.0-0.1.rc1 ; 0
v2.0.1.0-0.2.rc2 ; 0
v2.0.1.0-1 ; 0
v2.0.2.0-0.1.rc1 ; 0
v2.0.2.0-0.2.rc2 ; 0
v2.0.2.0-0.3.rc3 ; 0
v2.0.2.0-0.4.rc4 ; 0
v2.0.2.0-1 ; 0
v2.1.0.0-0.1.rc1 ; 0
v2.1.0.0-0.2.rc2 ; 0
v2.1.0.0-0.3.rc3 ; 0
v2.1.0.0-0.4.rc4 ; 0
v2.1.0.0-1 ; 0
v2.1.1.0-0.1.rc1 ; 0
v2.1.1.0-0.2.rc2 ; 0
v2.1.1.0-0.3.rc3 ; 0
v2.1.1.0-0.4.rc4 ; 0
v2.1.1.0-0.5.rc5 ; 0
v2.1.1.0-1 ; 0
v2.1.2.0-0.1.rc1 ; 0
v2.1.2.0-0.2.rc2 ; 0
v2.1.2.0-0.3.rc3 ; 0
v2.1.2.0-0.4.rc4 ; 0
v2.1.2.0-0.5.rc5 ; 0
v2.1.2.0-1 ; 0
v2.2.0.0-0.1.rc1; 1
devel-8095c39 ; 1
```

**Comment by jimi-c** [comment] 2016-10-14 14:24
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2016-10-14 14:24 UTC
Labels: P2, affects_2.2, bug
