### ISSUE TITLE
When --ask-sudo-pass is not provided on CentOS and it's required, there is no error message that it is asking for a password.

### ISSUE THREAD

**Issue by jacobweber** [ansible/ansible#7165] opened 2014-04-26 18:30 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.5
##### Environment:

Centos 6.4 server and client.
##### Summary:

Ansible hangs when trying to run a command via sudo, and can't be stopped without killing the process.
##### Steps To Reproduce:

When I run `ansible hostname --sudo -m service -a 'name=httpd state=restarted'`, it hangs. Pressing control-C does nothing. I have to kill the process. I'm assuming this is because it's asking for a password.
##### Expected Results:

Ansible can be stopped with control-C. Of course, it would be better if it showed some output, but that's another issue...
##### Actual Results:

See above.

**Comment by mpdehaan** [comment] 2014-04-26 19:55
Generically speaking, ansible does not hang with sudo.

You can supply --ask-sudo-pass to supply a sudo password.   

If this works and you get the hang scenario without --ask-sudo-pass, please let us know, as we need to look into why the sudo prompt detection is not giving you an error. (I suspect this part is paramiko specific).

In any event, supply --ask-sudo-pass and let us know more information.

(edited ticket title)

**Comment by jacobweber** [comment] 2014-04-26 19:59
--ask-sudo-pass does prompt me for a password, before it runs ssh. But if I get it wrong, or if that user doesn't have sudo permission to run ansible's script, it still hangs when running ssh.

(BTW, the edited title refers to the lack of a prompt, which is an issue, but I just meant to report the fact that you can't interrupt Ansible in this state.)

**Comment by jctanner** [comment] 2016-05-27 12:10
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us. 

Testing this on the version you have specified, we cannot reproduce this problem.

Our reasons and evidence for this are:
- ansible 2.1 gives proper error messages in various sudo failure scenarios ...

Password not provided but is required ...

```
fatal: [u1404]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "command"}, "module_stderr": "OpenSSH_7.2p2, OpenSSL 1.0.2h-fips  3 May 2016\r\ndebug1: Reading configurat
ion data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 58: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello
_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\nde
bug3: mux_client_request_alive: done pid = 17768\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_pa
cket: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\nShared connection to u1404 closed.\r\n", "module_stdout": "sudo: a password is required\r\n", "msg": "MODULE FA
ILURE", "parsed": false}
```

Incorrect password given ...

```
fatal: [u1404]: FAILED! => {"failed": true, "msg": "Incorrect sudo password"}
```

And we suggest that:
- Update to a newer version of ansible.

As such, we are most likely going to close this ticket.  Should you disagree with this conclusion, you may also wish to join our mailing lists, which are very active:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Closed as completed by jctanner** 2016-05-27 12:10 UTC
Labels: bug
