### ISSUE TITLE
"when statements should not include jinja2 templating" when using variable reference

### ISSUE THREAD

**Issue by Jean-Daniel** [ansible/ansible#22690] opened 2017-03-16 13:09 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION
ansible 2.4.0
  config file = /home/conductor/playbooks/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Jul  1 2016, 15:12:24) [GCC 5.4.0 20160609]

##### CONFIGURATION
Not relevant

##### OS / ENVIRONMENT
Ubuntu 16.04 / Python 2.7

##### SUMMARY
Ansible display "when statements should not include jinja2 templating" warning while I'm not using jinja2 templating in the when statement.

The problem come from the face the variable passed in the when statement references an other variable:

in defaults/main.yml
```yaml

my_role_var: "{{ my_host_var }}"

```

in tasks/main.yml

```yaml

- copy: …
  when:  my_role_var

```
 [WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: {{ my_host_var }}

[test.zip](https://github.com/ansible/ansible/files/847733/test.zip)

##### STEPS TO REPRODUCE

Uncompress the attached project.
Update hosts file and playbook to specify a reachable host.

run it using "ansible-playbook -i hosts  playbook.yml"

##### EXPECTED RESULTS
No warning, or an explanation about what to do about it.

##### ACTUAL RESULTS
> ansible-playbook -i hosts  playbook.yml

> 
> PLAY [*] 
>********************************************************************************************
> 
> TASK [Gathering Facts] 
>*********************************************************************************************
> ok: [test]
> 
> TASK [simple : debug] 
>*********************************************************************************************
>  **[WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: {{ hello }}**
> 
> ok: [test] => {
>     "changed": false, 
>     "msg": "Hello"
> }
> 
> PLAY RECAP 
>*********************************************************************************************
> test                       : ok=2    changed=0    unreachable=0    failed=0

**Comment by nitzmahone** [comment] 2017-03-16 18:49
@jimi-c Interesting corner case around spurious template warning via passthru of templated play var to a `when` inside a role. Not sure what to do about this one...

**Comment by fanatid** [comment] 2017-04-02 08:09
Same issue, my when statement: `when: runningvms.stdout.find('{{ vm }}') != -1`

**Comment by Jean-Daniel** [comment] 2017-04-03 14:12
@fanatid . This is not the same issue. In your case the warning is legit as your when statement did contains a jinja2 templating token.

You should fix it as follow:

`when: runningvms.stdout.find(vm) != -1`

**Comment by fanatid** [comment] 2017-04-03 14:14
@Jean-Daniel did not notice that there only `vm`, funny.
should note that ansible 2.2 did not show warnings

**Comment by dieswaytoofast** [comment] 2017-04-13 14:40
Just upgraded to 2.3, and now see this all over the place. 
Easiest reproduction is this play (note that adding the `==` test seems to deal with the issue...)
```
- hosts: localhost
  vars:
    foo: true
    bar: "{{ foo }}"

  tasks:
    - debug: msg="This complains"
      when: bar

    - debug: msg="This doesn't complain"
      when: bar == true
```

**Comment by anastazya** [comment] 2017-04-13 16:04
The question remains, how do we fix our playbooks so they don't generate warnings ? 

ex :  [WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: {{ ansible_distribution == 'Ubuntu' }}

**Comment by dieswaytoofast** [comment] 2017-04-13 16:11
I (temporarily) dealt with the issue by adding `== true` to the booleans
(or `== false`. depends)

**Comment by nitzmahone** [comment] 2017-04-13 21:26
The `when: bar` pattern is rather dangerous anyway- I've gotten nailed by it before when the var isn't a boolean, either by user error, or because it was set from a context that doesn't undergo YAML type inference (eg, `-e bar=False`), which can cause the boolean conversion to be incorrect. The truly safe way to do this is `when: bar | bool`, which has the bonus side-effect of zapping the template warning.

**Comment by jimi-c** [comment] 2017-06-09 18:01
Using @dieswaytoofast's example above, I'm no longer seeing this on the `devel` branch, though I am still seeing it on `stable-2.3`:
```TASK [debug] *********************************************************************************************************************************************************************************
task path: /home/jamesc/testing/22690/test.yml:8
ok: [localhost] => {
    "failed": false, 
    "msg": "This complains"
}

TASK [debug] *********************************************************************************************************************************************************************************
task path: /home/jamesc/testing/22690/test.yml:11
ok: [localhost] => {
    "failed": false, 
    "msg": "This doesn't complain"
}
```
So it appears this has been resolved, if anyone else can confirm?

**Comment by sivel** [comment] 2017-06-09 18:09
Yes, this was resolved in https://github.com/ansible/ansible/pull/25092 for devel

**Comment by sivel** [comment] 2017-08-25 16:47
duplicate_of 25092

**Closed as completed** 2017-08-25 16:51 UTC
Labels: needs_info, pending_action, c:template/templar, affects_2.4, support:core, bug

**Comment by vinidba** [comment] 2019-04-18 19:49
Hi guys,

I have a file:

when: "( grid_home_installed.stdout == 'skipped, since /oracle/app/oraInventory/ContentsXML/inventory.xml does not exist' or grid_home_installed.stdout == '' ) and asm_version != ''" )

This works, but the path is hard-coded and I don't wan't this.



Then, in my group_vars I created this variable:

oraInventory: /oracle/app/oraInventory

Then I create in another file:

- name: set message for oraInventory
  set_fact:
     message_oraInventory: "'skipped, since {{ oraInventory }}/ContentsXML/inventory.xml does not exist'"


So, in my original file:

  when: "(( grid_home_installed.stdout == {{ message_oraInventory }} or grid_home_installed.stdout == '' ) and asm_version != '' )"

This works, but I got jinja2 delimiters warning, which is expected.

So, I replace:

  when: "(( grid_home_installed.stdout == message_oraInventory or grid_home_installed.stdout == '' ) and asm_version != '' )"

I don't get any error, but the playbook doesn't run as expected: the evaluation is not working...
