### ISSUE TITLE
fatal errors are sent to stdout instead of stderr

### ISSUE THREAD

**Issue by fredericve** [ansible/ansible#17958] opened 2016-10-10 08:32 UTC
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Ansible reporting output sends fatal errors to stdout instead of stderr.
##### STEPS TO REPRODUCE

Just run a playbook or a command for which you expect a fatal error (e.g. host is down) and redirect stderr to a file. The error output will be visible on the console, but the file will be empty.

```
~# ansible unreachablehost.example.com -m command -a 'uptime' 2>errout
unreachablehost.example.com | UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh.", 
    "unreachable": true
}
~# cat errout
~#
```

##### EXPECTED RESULTS

I expected no output on the console and the file `errout` to contain the output instead.
##### ACTUAL RESULTS

Errors were output to the console and the `errout` file was empty

```

```

**Comment by Quimstr** [comment] 2016-10-13 22:09
That's because whole class is missing.
fatal errors are redirected to stderr with class CallbackModule.
connection errors are handled by class ConnectionError.
which is mentioned only once and has 2 lines ( one of wich is 'pass' ).
I'd gladly help you if I knew how ansible coders want this class writen.

**Comment by bcoca** [comment] 2016-10-14 00:08
As discussed in the linked PR, this is not a mistake, ansible-playbook did not get an error, it is reporting the status of tasks on hosts (all to stdout). 

If ansible-playbook itself suffers an error it will output to stderr, but it will not do so for reporting the steps of a playbook. This is the expected default behavior, the callback plugin system allows you to modify this behavior if you are so inclined, that is what I asked the submitter to do.

As such,I'm closing this issue as it is not a bug.

**Closed as completed by bcoca** 2016-10-14 00:08 UTC
Labels: affects_2.0, bug
