### ISSUE TITLE
Documentation difficult to identify changes across version

### ISSUE THREAD

**Issue by pfremm** [ansible/ansible#15792] opened 2016-05-09 19:39 UTC
- Feature Idea

It would be nice to have some consistency across documentation when changes to modules were done across ansible versions.  For example with the URI modules minor changes to behavior occurred in 2.0 with the body_format, but unless you read in detail about this option when troubleshooting impact analysis for ansible version upgrades is very difficult.  No references to this change are even found in the chnagelog markdown if I search for body_format.  If new options were added it would be helpful to have a page representing each major and minor release where I could see what modules had changes or additions.    At a minimum clearly showing which ansible versions had changes to a module at the top of the page like is done for some of the ec2 cloud modules would be extremely helpful as we migrate from 1.9.x to 2.x.

**Comment by bcoca** [comment] 2017-02-13 17:29
closing as dupe of #13858

**Closed as completed by bcoca** 2017-02-13 17:29 UTC
Labels: affects_2.2, affects_2.3, docs, feature
