### ISSUE TITLE
SyntaxError on Python 3 remote hosts in module wrappers

### ISSUE THREAD

**Issue by dedfriedly** [ansible/ansible#18629] opened 2016-11-25 21:50 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

executor/module_common.py
module_utils/base.py
module_utils/_text.py

##### ANSIBLE VERSION

```
2.2.0.0
```

##### OS / ENVIRONMENT

local OS = CentOS 7, Python 2.7.5
remote OS = FreeBSD 8.2, Python 3

##### SUMMARY

Trying to run ansible on the remote host fails with syntax errors, I'm able to get modules to run after editting the three files above.  Most of the issues where statically defining a string as unicode (u'test' will fail).  Also had to statically define ZIPDATA a binary (in Python 3, ZIPDATE = b"""(blah)""")

##### STEPS TO REPRODUCE

Just run ansible on a py2 local OS on a py3 remote OS (and only py3)

ansible host -m ping

```

```

##### ACTUAL RESULTS

```

```

**Comment by sivel** [comment] 2016-11-25 23:28
Can you confirm which python version specifically?  Is it less than 3.3?  Python 3.3 added support for unicode literals as proposed in PEP 414.

Per our documentation (http://docs.ansible.com/ansible/dev_guide/developing_modules_python3.html#minimum-version-of-python-3-x-and-python-2-x) the minimum required version of Python3 is python3.5.  Earlier versions are not supported:

> For modules (and by extension, module_utils) we support Python-3.5 and Python-2.4

**Comment by alikins** [comment] 2016-11-28 15:01
If possible, include a cut&paste of the error messages.

**Comment by abadger** [comment] 2017-01-04 06:07
@dedfriedly Since this looks like it's being caused by using Ansible with Python-3 that's older than 3.3 I'll close this in a few days unless you report back that this is occurring with Python-3.5.  Thanks for understanding.

**Comment by dedfriedly** [comment] 2017-01-04 06:09
Hi sorry thought I replied, yes confirmed this is older python

 

I have a hack in place that does what I need it to for pre-3.3 support.  I won’t share that as it’s likely not good :)

 

Thanks

**Closed as completed** 2017-02-03 18:26 UTC
Labels: python3, affects_2.2, bug
