### ISSUE TITLE
String with backslash at the end

### ISSUE THREAD

**Issue by michel-kraemer** [ansible/ansible#10464] opened 2015-03-14 15:17 UTC
I have a file with the following content:

```
exec "$JAVACMD" \
    "${JVM_OPTS[@]}" \
    -Djava.util.logging.config.file=${VERTX_JUL_CONFIG:-${VERTX_HOME}/conf/logging.properties} \
    -Dvertx.home=$VERTX_HOME\
    -Dvertx.clusterManagerFactory=org.vertx.java.spi.cluster.impl.hazelcast.HazelcastClusterManagerFactory\
    -classpath "$CLASSPATH" \
    org.vertx.java.platform.impl.cli.Starter "$@"
```

In my playbook I have the following task:

```
- name: enable log4j
  sudo: yes
  lineinfile: dest={{ vertx_home }}/bin/vertx
    line="    -Dlog4j.configuration=file:$VERTX_HOME/conf/log4j.properties -Dorg.vertx.logger-delegate-factory-class-name=org.vertx.java.core.logging.impl.Log4jLogDelegateFactory \"
    regexp="-Djava\.util\.logging\.config\.file"
```

When I execute Ansible it says `ERROR: There was an error while parsing the task`. I figured the problem is the backslash at the end of the `line` string. However, I need this backslash because in the final file it escapes the line break.

I tried two backslashes `\\` but got the same error.

I tried to insert a space between the backslash and the quotation mark, but then the final shell file is invalid (because the backslash escapes the space character and not the line break).

Is this a bug or am I doing something wrong?

Thanks,
Michel

**Comment by jimi-c** [comment] 2015-07-23 20:05
Hi @michel-kraemer, I've been looking into this and there is a way to get around the parsing error, which involves using the dictionary syntax for arguments:

<pre>
  - lineinfile:
      dest: "/tmp/test_10464.txt"
      line: "    -Dlog4j.configuration=file:$VERTX_HOME/conf/log4j.properties -Dorg.vertx.logger-delegate-factory-class-name=org.vertx.java.core.logging.impl.Log4jLogDelegateFactory \\"
      regexp: "-Djava\\.util\\.logging\\.config\\.file"
</pre>

Note the double `\\` there, which is required to prevent the YAML parser from thinking you're escaping the quote.

The original issue arises from our key="value" parser thinking that you're escaping that quote, since we do not ourselves check for a double `\` to mean use a literal backslash there. I'll continue working on that, to see if I can get it to parse that without error.

**Comment by jimi-c** [comment] 2015-07-23 20:38
Since this has a workaround and would otherwise be a VERY involved changed to the parser, I'm moving this to post-2.0 release milestone.

**Comment by albertux** [comment] 2015-08-20 18:48
My workaround solution is using hexadecimal code:
`
line="  ...../bin/cassandra.in.sh \x5C"
`
this will add: ( with not spaces or anything ) 
`
..../bin/cassandra.in.sh \
`

**Comment by albertux** [comment] 2015-09-26 03:39
@jimi-c  @michel-kraemer  ^

**Comment by michel-kraemer** [comment] 2015-10-04 09:33
Awesome idea, @albertux ! I haven't tried it out yet, but it surely looks promising.

**Comment by seeker89** [comment] 2016-04-28 10:38
Just as a heads up - since I upgraded from `1.9.4` to `2.0.1`, the workaround suggested above https://github.com/ansible/ansible/issues/10464#issuecomment-133116051 by @albertux is showing a weird behavior - it seems to be inserting the entire block, including the surrounding quotes (both single and double quotes). Not sure where it might be coming from.

**Comment by albertux** [comment] 2016-05-02 18:27
@seeker89 I forgot to mention this was using ansible `1.9.3`I will try to find a workaround for other versions

**Comment by seeker89** [comment] 2016-05-02 20:38
@albertux the dictionary syntax works - I'm currently using that everywhere now.

**Comment by jimi-c** [comment] 2016-06-18 12:00
@seeker89 yes the dictionary syntax is still the suggested workaround for this. I have confirmed that works on devel/stable-2.1.

**Comment by simonpie** [comment] 2016-08-22 19:31
@albertux's solution is still works very well (and is still necessary) in ansible 2.1.1.0

**Comment by abadger** [comment] 2017-01-23 19:23
There's a variety of workarounds for this including the ones posted in comments above and using the extra space at the end but running it through jinja2's trim filter:
```
  - lineinfile: 'dest=/var/tmp/dest line="{{ \"conti nued\\ \" |trim }}" create=True'
```

However, the supported way to do this in Ansible-2.x is to use yaml dicts:
```
  - lineinfile:
      dest: /var/tmp/dest
     # Single quotes in yaml do not need to escape the backslash
      line: 'an other\'
      create: True
  - lineinfile:
      dest: /var/tmp/dest
     # double quotes in yaml do need to escape the backslash
      line: "final ly\\"
      create: True
```

k=v parsing has cornercases like this that will always make it inferior to yaml dicts when there is a need for escaping or complex quoting.

Since yaml dict format works and there are several workarounds if someone feels they must use k=v I'll close this ticket.

**Closed as completed by abadger** 2017-01-23 19:23 UTC
Labels: affects_2.2, affects_2.3, c:parsing/splitter, bug
