### ISSUE TITLE
scp_if_ssh parameter ignored in ansible 2.0.1.0

### ISSUE THREAD

**Issue by Brian-Williams** [ansible/ansible#14668] opened 2016-02-25 21:03 UTC
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = /home/share/library
##### Ansible Configuration:

$ cat /etc/ansible/ansible.cfg | grep scp
# if True, make ansible use scp if the connection type is ssh
scp_if_ssh = True
##### Environment:

N/A
##### Summary:

Parameter scp_if_ssh is set to True in ansible.cfg. It fails to connect to host with error message "unable to open an sftp connection". It shouldn't be attempting an sftp connection.
##### Steps To Reproduce:

Run the following on a system that rejects sftp connections:
ansible <hostname> -m setup

```

$ ansible-playbook service-pack-6.2.x.yml 

PLAY ***************************************************************************

TASK [setup] *******************************************************************
fatal: [GoldenBoy]: FAILED! => {"failed": true, "msg": "failed to open a SFTP connection (Channel closed.)"}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @service-pack-6.2.x.retry

PLAY RECAP *********************************************************************
GoldenBoy                  : ok=0    changed=0    unreachable=0    failed=1
$ ansible-playbook service-pack-6.2.x.yml 

PLAY ***************************************************************************

TASK [setup] *******************************************************************
fatal: [GoldenBoy]: FAILED! => {"failed": true, "msg": "failed to open a SFTP connection (Channel closed.)"}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @service-pack-6.2.x.retry

PLAY RECAP *********************************************************************
GoldenBoy                  : ok=0    changed=0    unreachable=0    failed=1

```
##### When I uninstall ansible and reinstall 1.9.4 with no configuration changes setup works.

```
**$ pip uninstall ansible
<< ommitted >>
$ pip install ansible==1.9.4
<<ommitted>>
$ ansible --version
ansible 1.9.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = /home/share/library
$ ansible tigh -m setup
tigh | success >> {
    "ansible_facts": {
        "ansible_all_ipv4_addresses": [
...
}, 
    "changed": false
}

Playbook works as well

$ ansible-playbook service-pack-6.2.x.yml 

PLAY [GoldenBoy] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [GoldenBoy]

TASK: [debug var=inventory_hostname] ****************************************** 
ok: [GoldenBoy] => {
    "var": {
        "inventory_hostname": "GoldenBoy"
    }
}

TASK: [debug var=ansible_host] ************************************************ 
ok: [GoldenBoy] => {
    "var": {
        "ansible_host": "ansible_host"
    }
}

TASK: [revert to snapshot] **************************************************** 
changed: [GoldenBoy -> 127.0.0.1]
...

```
##### Expected Results:

It uses scp to succeed.
##### Actual Results:

It attempts to connect with SFTP.

```
$ ansible GoldenBoy -m setup
GoldenBoy | FAILED! => {
    "failed": true, 
    "msg": "failed to open a SFTP connection (Channel closed.)"
}
```

**Comment by bcoca** [comment] 2016-02-29 22:07
that message is emitted by the paramiko plugin, so you do not seem to be using the ssh one.

**Comment by Brian-Williams** [comment] 2016-03-02 07:52
Any suggestion on where I look first? Does this seem like a ansible.cfg problem where it isn't being read or a module.

I stripped non-default parameters from ansible.cfg. Tried in 1.9.4 again it succeeded. Then upgraded to stable-2.0 and it failed. I have also tried dev branch below.

> $ ansible --version
> ansible 2.1.0 (devel 201bd8c) last updated 2016/02/29 23:43:49 (GMT -400)
> lib/ansible/modules/core: (detached HEAD 0bbb7ba38d) last updated 2016/02/29 23:43:52 (GMT -400)
> lib/ansible/modules/extras: (detached HEAD 39e4040685) last updated 2016/02/29 23:43:54 (GMT -400)
> config file = /etc/ansible/ansible.cfg
> configured module search path = Default w/o overrides

The following is the uncommented lines from the ansible.cfg used in my most recent attempt. The only non-default is scp_if_ssh.

> $ grep "^[^#]" /etc/ansible/ansible.cfg 
> [defaults]
> [privilege_escalation]
> [paramiko_connection]
> [ssh_connection]
> scp_if_ssh = True
> [accelerate]
> [selinux]
> [colors]

The only other param I'm that isn't stock ansible is specifying python interpreter in hosts file.
[local]
localhost ansible_connection=local ansible_python_interpreter=/usr/local/bin/python

**Comment by bcoca** [comment] 2016-03-08 01:31
Can you fill in the environment info? what OS/python/etc  is this running from and the same for target.

Also, are you using ssh keys or passwords?

**Comment by Brian-Williams** [comment] 2016-03-09 07:00
I apologize I thought the environment wasn't relevant because I was getting the same failure on my macbook and a linux vm. However, I just successfully connected on another co-workers vm. I uninstalled ansible 1.9. Installed the same version of ansible 2.0.0.2 as the vm that succeeded and copied his ansible.cfg. Then made a new folder and pointed to an arbitrary hosts file so it had no connection to my previous install and it still attempts to use sftp. I have attempted using rsa keys and passwords.

It seemed like it might be a python module problem. I uninstalled and reinstalled paramiko (paramiko-1.16.0).

Still the same result of failed to open a SFTP connection (Channel closed.).

```
$ ansible 172.27.4.80 -m setup
172.27.4.80 | FAILED! => {
    "failed": true, 
    "msg": "failed to open a SFTP connection (Channel closed.)"
}
```

Environment ansible controller:
Python 2.7.10
OSX Yosemite
Darwin Brians-MacBook-Pro-2.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64

Environment ansible target:
- shouldn't be relevant; other macbook connected to this same host
- including for completeness
  CentOS release 6.7
  Linux Sky622_Sky1 2.6.32-573.12.1.el6.x86_64 #1 SMP Tue Dec 15 21:19:08 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

I copied the ansible.cfg from my co-workers it follows:
- note scp_if_ssh = True is set
- The only thing I changed was I commented out "private_key_file = ~/.ssh/ansible.priv" as I define key to use in group_vars
- config file for ansible -- http://ansible.com/
  
  nearly all parameters can be overridden in ansible-playbook
  or with command line flags. ansible will read ANSIBLE_CONFIG,
  ansible.cfg in the current working directory, .ansible.cfg in
  the home directory or /etc/ansible/ansible.cfg, whichever it
  finds first

```
[defaults]

# some basic default values...

inventory      = /etc/ansible/hosts
#library        = /usr/share/my_modules/
remote_tmp     = $HOME/.ansible/tmp
pattern        = *
forks          = 25
poll_interval  = 15
sudo_user      = root
#ask_sudo_pass = True
#ask_pass      = True
transport      = smart
#remote_port    = 22
module_lang    = C

# plays will gather facts by default, which contain information about
# the remote system.
#
# smart - gather by default, but don't regather if already gathered
# implicit - gather by default, turn off with gather_facts: False
# explicit - do not gather by default, must say gather_facts: True
gathering = implicit

# additional paths to search for roles in, colon separated
#roles_path    = /etc/ansible/roles

# uncomment this to disable SSH key host checking
host_key_checking = False

# change this for alternative sudo implementations
sudo_exe = sudo


# SSH timeout
timeout = 10

# if set, always use this private key file for authentication, same as
# if passing --private-key to ansible or ansible-playbook
#private_key_file = /path/to/file
private_key_file = ~/.ssh/ansible.priv

# format of string {{ ansible_managed }} available within Jinja2
# templates indicates to users editing templates files will be replaced.
# replacing {file}, {host} and {uid} and strftime codes with proper values.
ansible_managed = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}

# set plugin path directories here, separate with colons
action_plugins     = /usr/share/ansible_plugins/action_plugins
callback_plugins   = /usr/share/ansible_plugins/callback_plugins
connection_plugins = /usr/share/ansible_plugins/connection_plugins
lookup_plugins     = /usr/share/ansible_plugins/lookup_plugins
vars_plugins       = /usr/share/ansible_plugins/vars_plugins
filter_plugins     = /usr/share/ansible_plugins/filter_plugins

# if set to a persistent type (not 'memory', for example 'redis') fact values
# from previous runs in Ansible will be stored.  This may be useful when
# wanting to use, for example, IP information from one group of servers
# without having to talk to them in the same playbook run to get their
# current IP information.
fact_caching = memory


[privilege_escalation]

[paramiko_connection]


[ssh_connection]

# if True, make ansible use scp if the connection type is ssh
# (default is sftp)
scp_if_ssh = True

[accelerate]
accelerate_port = 5099
accelerate_timeout = 30
accelerate_connect_timeout = 5.0
```

**Comment by stephanarts** [comment] 2016-03-28 09:09
I had the same problem on OS-X.

There you need to specify  ansible_connection=ssh in your inventory for it to force it to use openssh. If it is set to smart, it appears to default to paramiko.

Next, it complains that you need the sshpass package, I've followed the procedures on this page:

http://www.hashbangcode.com/blog/installing-sshpass-osx-mavericks

After sshpass was installed, everything works perfectly.

**Comment by bcoca** [comment] 2016-03-28 15:16
So the issue is not the parameter being ignored but that you are using OS X with the default `smart` transport, which defaults to paramiko, as sshpass can cause a kernel panic. 

The setting is not being ignored, the wrong protocol is being assumed, I'm closing this as it is not a bug but confusion on the protocol actually used.

**Closed as completed by bcoca** 2016-03-28 15:16 UTC
Labels: bug

**Comment by allo-** [comment] 2016-05-15 11:03
I can still reproduce the issue (ansible 2.0.2.0):

inventory:

```
myhost ansible_ssh_user=root ansible_connection=ssh scp_if_ssh=True
```

and commandline

```
$ ansible -vvvv myhost -i hosts -a ls
...
<myhost> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/data/home/allo/.ansible/cp/ansible-ssh-%h-%p-%r '[myhost]'
```

**Comment by Brian-Williams** [comment] 2016-05-15 18:52
Hey allo-,

The default behavior of parameter "ansible_connection" changed from pre 2.0 to post 2.0. On some systems it will now default to paramiko. Paramiko doesn't support scp, it uses sftp. If you are connecting to systems like I am where sftp is refused you must set BOTH of these:

ansible_connection=ssh
scp_if_ssh=True

It's slightly confusing in my mind because any time I would need scp_if_ssh I would also be requiring the connection to be ssh. Maybe there are other use cases I can't think of. Either way the above would be helpful to be documented alongside the scp parameter as a note in the ansible docs.

**Comment by allo-** [comment] 2016-05-15 19:22
Hi. I read this in this bug, but shouldn't this work with the options set per host in the inventory (see my post above)?
I only have a few hosts without sftp, so i would prefer to use it only for those hosts.

**Comment by Brian-Williams** [comment] 2016-05-15 20:21
Scp_if_ssh doesn't appear to be an [inventory parameter](http://docs.ansible.com/ansible/intro_inventory.html#list-of-behavioral-inventory-parameters).

You need to put scp_if_ssh=True in your ansible.cfg. You could put ansible_connection=ssh only on your non-sftp hosts and it should use sftp on your other hosts.

**Comment by allo-** [comment] 2016-05-15 20:39
Hmm okay. Maybe it should be?
Do i see it correct, that sftp is a lot more performant (when copying multiple files) than scp?

**Comment by Brian-Williams** [comment] 2016-05-15 20:52
Scp is faster. Sftp has to wait for packet confirmations.

**Comment by ViViDboarder** [comment] 2016-08-07 20:03
I've read over this issue and I'm having trouble determining if there is something else I need to set. In my hostvars I have ansible_connection=ssh for the desired host. I also put scp_if_ssh in just about everywhere I could. In hostvars and in my ansible.cfg. When I try to run the ping module I see it make an ssh connection and then attempt an sftp connection still. No scp.

```
laptop playbooks (master)$ ansible router -m ping -vvv                                                  [venv]
Using /Users/vividboarder/workspace/ansible-settings/playbooks/ansible.cfg as config file
<192.168.2.1> ESTABLISH SSH CONNECTION FOR USER: vividboarder
<192.168.2.1> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o Port=3945 -o 'IdentityFile="../ansible-private/id_rsa_ansible"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vividboarder -o ConnectTimeout=10 -o ControlPath=/Users/vividboarder/.ansible/cp/ansible-ssh-%h-%p-%r 192.168.2.1 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1470598174.21-242749632706722 `" && echo ansible-tmp-1470598174.21-242749632706722="` echo $HOME/.ansible/tmp/ansible-tmp-1470598174.21-242749632706722 `" ) && sleep 0'"'"''
<192.168.2.1> PUT /var/folders/10/m0s9wd2d4jdgh2hfnmcn7b7c42h357/T/tmp6Utf1n TO /root/.ansible/tmp/ansible-tmp-1470598174.21-242749632706722/ping
<192.168.2.1> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o Port=3945 -o 'IdentityFile="../ansible-private/id_rsa_ansible"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vividboarder -o ConnectTimeout=10 -o ControlPath=/Users/vividboarder/.ansible/cp/ansible-ssh-%h-%p-%r '[192.168.2.1]'
```

Is there something else I could be missing?

Ansible version: ansible 2.1.1.0
Operating System: OSX

EDIT: Aaaand figured it out right after posting this. After spending so much time debugging I finally posted and then realized I had scp_if_ssh in my ansible.cfg, but in the wrong section... Putting it under [ssh_connection] resolved it. Sorry!
