### ISSUE TITLE
'utf8' codec can't decode byte 0xff in position 0: invalid start byte"

### ISSUE THREAD

**Issue by windowsansiblernew** [ansible/ansible#23903] opened 2017-04-24 09:04 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

lookup
##### ANSIBLE VERSION

```
2.3.0.0
```

##### SUMMARY

Getting the error "'utf8' codec can't decode byte 0xff in position 0: invalid start byte" when a compressed json is being called by lookup plugin
##### STEPS TO REPRODUCE

```yaml
    - name: read local file
      set_fact:
       reg_changes: "{{ lookup('file', '/home/tess/xl.json') | from_json }}"                    
      delegate_to: localhost
```

##### EXPECTED RESULTS

Json file should be parsed

##### ACTUAL RESULTS

```
'utf8' codec can't decode byte 0xff in position 0: invalid start byte"
```

**Comment by jhawkesworth** [comment] 2017-04-24 10:07
I'm guessing you have a Byte Order Mark at the start of your compressed JSON file.   Can you run 'od -cx xl.json' to see whether there is a Byte Order Mark present?

needs_info

**Comment by windowsansiblernew** [comment] 2017-04-24 10:16
how can i see it? i ran it and it gave me bunch of numbers

**Comment by jhawkesworth** [comment] 2017-04-24 11:30
Look at the first line of the od -cx output.  If there are invisible characters present before the start of your file contents, then you have a BOM which you need to get rid of.

Some examples:
```
$ od -cx bomExample.ps1 | more
0000000 357 273 277   #       B   O   M       e   x   a   m   p   l   e
           bbef    23bf    4220    4d4f    6520    6178    706d    656c
0000020
$ echo "# No BOM example" > noBomExample.txt
$ od -cx noBomExample.txt | more
0000000   #       N   o       B   O   M       e   x   a   m   p   l   e
           2023    6f4e    4220    4d4f    6520    6178    706d    656c
0000020  \n
           000a
0000021
```

needs_info

**Comment by windowsansiblernew** [comment] 2017-04-24 11:49
compressed json output
first line
```
0000000 377 376   [  \0   {  \0   "  \0   n  \0   a  \0   m  \0   e  \0
           feff    005b    007b    0022    006e    0061    006d    0065
```

non compressed json output first line
```
0000000   [   {  \r  \n  \t   "   n   a   m   e   "   :       "   A   c
           7b5b    0a0d    2209    616e    656d    3a22    2220    6341
```

**Comment by alikins** [comment] 2017-04-24 14:57
I can reproduce this with devel/. The error seems to happen on the file load, so the '|from_json' isnt needed to reproduce the error.

```
[fedora-25:compressed_json_utf8_23903 (master %)]$ ansible-playbook -vvv test.yml 
Using /etc/ansible/ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available


PLAYBOOK: test.yml ********************************************************************************************************************************************************************************
1 plays in test.yml

PLAY [localhost] **********************************************************************************************************************************************************************************
META: ran handlers

TASK [read local file] ****************************************************************************************************************************************************************************
task path: /home/adrian/src/ansible-bug-repro/compressed_json_utf8_23903/test.yml:6
fatal: [localhost]: FAILED! => {
    "failed": true, 
    "msg": "An unhandled exception occurred while running the lookup plugin 'file'. Error was a <type 'exceptions.UnicodeDecodeError'>, original message: 'utf8' codec can't decode byte 0x8b in position 1: invalid start byte"
}
	to retry, use: --limit @/home/adrian/src/ansible-bug-repro/compressed_json_utf8_23903/test.retry

PLAY RECAP ****************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   

[fedora-25:compressed_json_utf8_23903 (master %)]$ file compressed.json.gz 
compressed.json.gz: gzip compressed data, was "compressed.json", last modified: Mon Apr 24 14:46:32 2017, from Unix
[fedora-25:compressed_json_utf8_23903 (master %)]$ cat test.yml 
---
- hosts: localhost
  gather_facts: false

  tasks:
      - name: read local file
        set_fact:
            #          reg_changes: "{{ lookup('file', '/home/adrian/src/ansible/repro/compressed_json_utf8_23903/compressed.json') | from_json }}"
          reg_changes: "{{ lookup('file', '/home/adrian/src/ansible/repro/compressed_json_utf8_23903/compressed.json.gz') }}"

# delegate_to: localhost
[fedora-25:compressed_json_utf8_23903 (master %)]$ ansible --version
ansible 2.4.0 (devel e0a7105c2d) last updated 2017/04/24 10:09:13 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/adrian/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/adrian/src/ansible/lib/ansible
  executable location = /home/adrian/src/ansible/bin/ansible
  python version = 2.7.13 (default, Jan 12 2017, 17:59:37) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
[fedora-25:compressed_json_utf8_23903 (master %)]$ cat test.yml 
---
- hosts: localhost
  gather_facts: false

  tasks:
      - name: read local file
        set_fact:
            #          reg_changes: "{{ lookup('file', '/home/adrian/src/ansible/repro/compressed_json_utf8_23903/compressed.json') | from_json }}"
          reg_changes: "{{ lookup('file', '/home/adrian/src/ansible/repro/compressed_json_utf8_23903/compressed.json.gz') }}"
```

**Comment by sivel** [comment] 2017-04-24 15:03
BTW, I am not sure that "compressed json" means a "gzipped" JSON file.  It looks like from what I can tell, the OP means that it is all one line, and not pretty formatted with indentation.

Although the OP hasn't express explicitly how the "compressed json" is being created.

But from the output mentioned in https://github.com/ansible/ansible/issues/23903#issuecomment-296634616 it appears it is still plain text, and does appear to have characters before the initial `[` identified by `feff` which is a BOM, that needs to be removed.

**Comment by alikins** [comment] 2017-04-24 15:09
@sivel good point about 'compressed json'. I tested with just a gzipped json file and got similar error (file lookup expects to be able to to_text() the file contents and that failed on the gzip bytes content). But the file shown in https://github.com/ansible/ansible/issues/23903#issuecomment-296634616 is something else...

@windowsansiblernew what do you mean by 'compressed json'?  Can you provide a sample file?

**Comment by windowsansiblernew** [comment] 2017-04-24 16:27
i have resolved it myself by changing the encoding to ascii and ansible nailed it :1st_place_medal:

**Comment by jhawkesworth** [comment] 2017-04-24 16:36
ok, glad you are working, lets close this issue then as its not really an ansible issue.

**Closed as completed by jhawkesworth** 2017-04-24 16:36 UTC
Labels: needs_info, affects_2.3, c:plugins/lookup, bug
