### ISSUE TITLE
{{ 2 | bool }} returns False not True

### ISSUE THREAD

**Issue by mdavis-xyz** [ansible/ansible#71410] opened 2020-08-22 02:08 UTC
##### SUMMARY

The `bool` filter should convert all non-zero integers to True.
It does not do that.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
bool

##### ANSIBLE VERSION

```
ansible 2.9.0
  config file = /home/ec2-user/.ansible.cfg
  configured module search path = ['/home/ec2-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ec2-user/.local/lib/python3.6/site-packages/ansible
  executable location = /home/ec2-user/.local/bin/ansible
  python version = 3.6.10 (default, Feb 10 2020, 19:55:14) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/home/ec2-user/.ansible.cfg) = True
DEFAULT_LOCAL_TMP(/home/ec2-user/.ansible.cfg) = /dev/shm/ansible/tmp_local/ansible-local-300093uiay0wv
```

##### OS / ENVIRONMENT

Amazon Linux

##### STEPS TO REPRODUCE

```
---
- hosts: localhost
  connection: local
  tasks:
  - assert:
      that: 
      - "{{ 2 | bool }}"
```

##### EXPECTED RESULTS

The only documentation I can find says:

> To cast values as certain types, such as when you input a string as “True” from a vars_prompt and the system doesn’t know it is a boolean value:

I want to cast from int to bool. So I expect that this playbook passes.

##### ACTUAL RESULTS

The assertion fails.
`1 | bool` returns True.
So this filter is not 'is this variable already a boolean type'.

**Comment by mkrizek** [comment] 2020-08-24 06:01
Duplicate of #21914

**Closed as completed by mkrizek** 2020-08-24 06:01 UTC
Labels: python3, support:core, bug, affects_2.9

**Comment by mkrizek** [comment] 2020-08-24 06:05
Also see https://docs.ansible.com/ansible/devel/user_guide/playbooks_tests.html#testing-truthiness
