### ISSUE TITLE
s3 module doesn't follow "region" setting?

### ISSUE THREAD

**Issue by mathieumd** [ansible/ansible#8783] opened 2014-08-27 19:14 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8 (devel f8a30faeee) last updated 2014/08/27 20:31:45 (GMT +200)
##### Environment:

Ubuntu 14.04
##### Summary:

I can't create a S3 Bucket in a specified region, as Ansible's s3 module seems to always create them in the US Standard region.

Or maybe shall I use s3_url=s3-eu-west-1.amazonaws.com argument?
##### Steps To Reproduce:

```
- s3: bucket=test mode=create region=eu-west-1 aws_access_key=<...> aws_secret_key=<...>
```
##### Expected Results:

S3 Bucket created in the EU (Ireland) region.
##### Actual Results:

S3 Bucket created in the US Standard region.

**Comment by abadger** [comment] 2014-09-08 16:10
Confirmed.

I've taken a look at the code and the boto docs for the s3 API.  We're not passing the region information into boto for the s3 module at the moment.  There's a different s3.connect_to_region() method that looks like a drop in replacement for the connection method we're currently using.  That may work.  However, the boto API docs imply that we actually need to set the Location attribute at bucket creation time.  And additionally, the Location names are not all the same as the region names.  If we have to do that, it won't be as simple.

**Comment by lwade** [comment] 2014-09-08 16:12
S3_URL should work without problem here, just use the regions S3 endpoint.

**Comment by abadger** [comment] 2014-09-08 16:32
Hm... my testing is showing that S3_URL doesn't work either.  That would coincide with what the boto docs seem to be saying:  there are per-region endpoints for S3 but they only control where you talk to the service, not where new buckets are created.

@lwade, has S3_URL worked for you to create a new bucket?

**Comment by lwade** [comment] 2014-09-08 16:44
Sorry, you are correct.  So I believe the fix for this would instead be to modify the create_bucket call with a location (i.e. s3.create_bucket(bucket, location=Location.APNortheast))component and import the location object.

**Comment by lwade** [comment] 2014-09-08 16:46
Here: http://boto.readthedocs.org/en/latest/s3_tut.html

It shouldn't be mandatory though and the default should be DEFAULT.

**Comment by abadger** [comment] 2014-09-09 16:14
Thanks for the pointers lwade! 

@mathieumd, this commit should fix your issue:
https://github.com/ansible/ansible/commit/a56767c49c741d56399f9cd29f7e673f785b056e

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Closed as completed by abadger** 2014-09-09 16:14 UTC
Labels: cloud, P1, bug

**Comment by mathieumd** [comment] 2014-09-11 17:41
I confirm that the problem is fixed. Thanks!

**Comment by jalbstmeijer** [comment] 2014-10-30 21:24
Hi,

I'm running Ansible 1.7.2 and for me;

## \- s3: bucket=random mode=create region=eu-west-1 aws_access_key={{aws_access_key}} aws_secret_key={{aws_secret_key}}

PLAY [Create S3 bucket] ******************************************************\* 

TASK: [s3 bucket=random mode=create region=eu-west-1 aws_access_key=xxx aws_secret_key=xxx] **\* 
changed: [localhost] => {"changed": true, "msg": "Bucket created succesfully"}

PLAY RECAP *******************************************************************\* 

## localhost                  : ok=1    changed=1    unreachable=0    failed=0   

still ends up creating a 'random' bucket in 'us-east-1' instead of 'eu-west-1'

Gr, Justin

**Comment by lwade** [comment] 2014-10-30 22:02
Hi @jalbstmeijer, this is probably because this fix is going into Ansible 1.8 / devel :)

**Comment by jalbstmeijer** [comment] 2014-10-30 22:47
aah, ok thanks.. i'll check the devel tree then :)

**Comment by mlaccetti** [comment] 2015-02-24 21:16
I don't think this has been fixed; specifically in the case where a bucket already exists, but is in a different region.  This is especially broken when using GovCloud, since the AWS creds for GovCloud are totally separate from the regular AWS and need to be provided via the the s3.connect_to_region call.

**Comment by mlaccetti** [comment] 2015-02-25 13:47
I created a PR to address this: https://github.com/ansible/ansible-modules-core/pull/846
