### ISSUE TITLE
Ansible shell command does not display output when output contains ANSI colors

### ISSUE THREAD

**Issue by hozn** [ansible/ansible#7522] opened 2014-05-23 17:43 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

1.5.5
##### Environment:

CentOS 5.9
##### Summary:

We are using Ansible to run puppet agent, which by default (and very helpfully) uses colors to indicate severity of logs.  When puppet is run with default (color=on) settings, there is no output from Ansible; when it is run with ("--color=false") then ansible displays the output.  We would like to have puppet colors preserved since they are of value to spotting issues.
##### Steps To Reproduce:

Run the "puppet agent -t" (or other puppet apply command) on a system using Ansible.

```
[root@localhost ~]# ansible server.example.com -m shell -a 'puppet agent -t --noop' -v
```
##### Expected Results:

Expected to see something like below (but with ANSI colors):

```
[root@localhost ~]# ansible  server.example.com -m shell -a 'puppet agent -t --noop' -v
server.example.com | success | rc=0 >>
info: Retrieving plugin
info: Loading facts in /var/lib/puppet/lib/facter/facter_dot_d.rb
info: Loading facts in /var/lib/puppet/lib/facter/puppet_vardir.rb
info: Caching catalog for server.example.com
info: Applying configuration version '1400866037'
notice: Finished catalog run in 8.13 seconds

[root@localhost ~]#
```
##### Actual Results:

E.g.

```
[root@localhost ~]# ansible server.example.com -m shell -a 'puppet agent -t --noop' -v
server.example.com | success | rc=0 >>

[root@localhost ~]#
```

**Comment by jimi-c** [comment] 2014-05-23 19:29
This is just a quick and dirty patch, but you can try this:

<pre>
diff --git a/lib/ansible/utils/string_functions.py b/lib/ansible/utils/string_functions.py
index 3b45271..c808330 100644
--- a/lib/ansible/utils/string_functions.py
+++ b/lib/ansible/utils/string_functions.py
@@ -1,12 +1,5 @@
 def isprintable(instring):
-    if isinstance(instring, str):
-        #http://stackoverflow.com/a/3637294
-        import string
-        printset = set(string.printable)
-        isprintable = set(instring).issubset(printset)
-        return isprintable
-    else:
-        return True
+    return True
 
 def count_newlines_from_end(str):
     i = len(str)
</pre>

We previously had some discussion about whether we need to filter out control characters this way, so it might be better to have a function that strips certain bad things out while keeping things like ANSII colors intact.

**Comment by hozn** [comment] 2014-05-23 19:37
Ah, very nice -- thank you; I will try that out & report back on whether
that fixes the issue.

**Comment by mpdehaan** [comment] 2014-05-25 21:50
Quick workaround here BTW is to feed puppet the nocolor option.  Can't remember whether that requires using the "environment:" keyword in ansible or if it's a CLI option.

**Comment by hozn** [comment] 2014-05-25 23:08
Yes, I mentioned in the ticket that --color=false works, but we want
[puppet] colors! :)  I applied the mentioned patch to our ansible (rpm)
build process and kicked off the build before leaving on Friday.  I'll play
with that on Tuesday; I'm guessing it'll fix the problem for us.

**Comment by hozn** [comment] 2014-05-27 15:47
Yes, that proposed short-circuit of isprintable did indeed solve the problem with missing colors.

**Comment by mpdehaan** [comment] 2014-06-01 17:04
duplicate of #7487

**Closed as completed by mpdehaan** 2014-06-01 17:04 UTC
Labels: bug
