### ISSUE TITLE
Unexpected behaviour when using delegate_to with ansible_host and ansible_fqdn

### ISSUE THREAD

**Issue by thmshmm** [ansible/ansible#16157] opened 2016-06-06 14:23 UTC
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.1.0
```
##### OS / ENVIRONMENT

RHEL 6
##### SUMMARY

When creating a file from a template and delegating the execution to a different host, the variables ansible_host and ansible_fqdn point to different hosts.
##### STEPS TO REPRODUCE

```
playbook.yml:
- name: create conf
  become: yes
  become_method: sudo
  become_user: root
  template:
    src: mytemplate.j2
    dest: myconf.conf
  delegate_to: "{{ groups['web_server'][0] }}"

mytemplate.j2:
{{ ansible_fqdn }}
{{ ansible_host }}
```
##### EXPECTED RESULTS

The destination file contains either two times the delegated hostname or the source host.
##### ACTUAL RESULTS

The ansible_host variable contains the host from delegate_to whereas the ansible_fqdn variable points to the source host.

**Comment by alikins** [comment] 2016-06-06 17:24
(note: I edited the initial response to fix up some formatting)

**Comment by bcoca** [comment] 2016-06-06 17:30
ansible_host reflects the connect_to/connected_to host, ansible_fqdn is a fact collected from the `inventory_hostname`, when delegation is in play you should not expect them to always match as they are different variables, set in different ways and for different reasons.

As such, closing this issue as it is not a bug.

**Closed as completed by bcoca** 2016-06-06 17:30 UTC
Labels: bug
