### ISSUE TITLE
roles not working with spaces in path on mac

### ISSUE THREAD

**Issue by binduwavell** [ansible/ansible#3521] opened 2013-07-13 21:22 UTC
Attempt to use roles from folder that has space in ancestor path results in the following relatively impossible to debug error message

```
> ansible-playbook linode.yml -k -vvv
SSH password:
Traceback (most recent call last):
  File "/Volumes/Macintosh HD/UsersHD/binduwavell/projects/ansible/bin/ansible-playbook", line 235, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/Volumes/Macintosh HD/UsersHD/binduwavell/projects/ansible/bin/ansible-playbook", line 181, in main
    pb.run()
  File "/Volumes/Macintosh HD/UsersHD/binduwavell/projects/ansible/lib/ansible/playbook/__init__.py", line 217, in run
    play = Play(self, play_ds, play_basedir)
  File "/Volumes/Macintosh HD/UsersHD/binduwavell/projects/ansible/lib/ansible/playbook/play.py", line 111, in __init__
    self._tasks      = self._load_tasks(self._ds.get('tasks', []), load_vars)
  File "/Volumes/Macintosh HD/UsersHD/binduwavell/projects/ansible/lib/ansible/playbook/play.py", line 301, in _load_tasks
    (k,v) = t.split("=", 1)
ValueError: need more than 1 value to unpack
```

**Comment by mpdehaan** [comment] 2013-07-14 00:38
Thanks for the heads up.   Can you share the include line from your
playbook (or what part has spaces in it?) so I can make sure I have a way
to reproduce this?

Thanks!

**Comment by binduwavell** [comment] 2013-07-14 14:38
In my home directory /Users/me I have a folder called projects that is symlinked to /Volumes/Macintosh HD/UsersHD/me/projects. I put my project in a subfolder of projects called ansible-project. I switched from one uber playbook to using roles so. With even one role: common in my site.yml I see this error.

**Comment by stoned** [comment] 2013-07-15 18:55
Issue #2752 is related to this.

**Comment by mpdehaan** [comment] 2013-07-15 19:01
The fix is probably a little different :)

**Comment by stoned** [comment] 2013-07-15 19:28
Well in fact I can't see something fixing #2752 but proper and careful quoting in the playbook. More on this there.

**Comment by stoned** [comment] 2013-07-15 19:47
I have a proposal to fix this issue, see stoned/ansible@5dfa0043463cfd54db73916ea508ffe229371f97

**Comment by AlejandroTrev** [comment] 2013-07-18 23:33
Not sure if @stoned's proposal is what you guys are planning to settle on, but if it helps, I cloned & tested it and can confirm that it fixed the problem in my environment!  (I wrote more about my specific problem on #2752).

**Comment by mpdehaan** [comment] 2013-07-20 18:36
@stoned -- that's fine, please send me a pull request and I'll merge it.  Thanks!

**Comment by stoned** [comment] 2013-07-20 21:35
@mpdehaan pull request #3606 done, with the help of  AlejandroTrev, Thanks !

**Comment by mpdehaan** [comment] 2013-07-20 22:11
closing per above, thank you!

**Closed as completed by mpdehaan** 2013-07-20 22:11 UTC
Labels: bug

**Comment by domdom82** [comment] 2016-06-13 11:15
Got a regression of this problem in ansible 2.0.2.0 over at Openwhisk https://github.com/openwhisk/openwhisk/issues/632

I can reproduce this problem with the following setup:

```
/path with spaces/ansible/roles/couchdb
/path with spaces/ansible/roles/couchdb/tasks/main.yml

/path with spaces/ansible/couchdb.yml
```

where the playbook `couchdb.yml`looks like this:

```
- hosts: db
  roles:
  - couchdb
```

This leads to the following error message:

```
TASK [couchdb : CouchDB] *******************************************************
task path: /path with spaces/ansible/roles/couchdb/tasks/main.yml:6
Monday 13 June 2016  13:12:24 +0200 (0:00:00.268)       0:00:00.292 ***********
fatal: [192.168.99.102]: FAILED! => {"failed": true, "msg": "need more than 1 value to unpack"}
```
