### ISSUE TITLE
vsphere_guest module and variables

### ISSUE THREAD

**Issue by Govinda-Fichtner** [ansible/ansible#7181] opened 2014-04-28 12:36 UTC
##### Environment:

What OS are you running Ansible from:  Mac OS X 10.9.2
and what OS are you managing: Ubuntu 10.04, 12.04, 14.04
##### Summary:

While trying the vsphere_guest module from the devel branch I had problems to get the module working with the following parameters:

https://gist.github.com/Govinda-Fichtner/11370085

Basically it is about lines like the following

``` yaml
vm_hardware:
          memory_mb: "{{ vm_memory }}"
```

vm_memory is defined in a host var like this

```
vm_memory: 512
```

It seems as if the quoting around the variable makes it a unicode string.
I get the following error:

https://gist.github.com/Govinda-Fichtner/b700c4cd78cdb078a61f

The solution for me was just to cast the value to int in the vsphere_guest module like this:

``` python
config.set_element_memoryMB(int(vm_hardware['memory_mb']))
```

I guess it would make sense to ensure the datatype for every numeric value in vsphere_guest.

If you are interested I can provide a pull request for this.
##### Steps To Reproduce:

create a vsphere_guest task and use a variable for the memory value
##### Expected Results:

that it runs without error and uses the provided memory value
##### Actual Results:

error - https://gist.github.com/Govinda-Fichtner/b700c4cd78cdb078a61f

**Comment by mpdehaan** [comment] 2014-04-28 13:35
This ticket is a duplicate of the one previously opened

**Closed as completed by mpdehaan** 2014-04-28 13:35 UTC

**Comment by Govinda-Fichtner** [comment] 2014-04-29 07:03
Sorry for the duplicate... do not know exactly how it happened.
