### ISSUE TITLE
docker module not idempotent

### ISSUE THREAD

**Issue by discordianfish** [ansible/ansible#6395] opened 2014-03-11 14:19 UTC
##### Issue Type:

Feature Request
##### Ansible Version:

ansible 1.6 (devel c7d1c1a306) last updated 2014/03/07 16:45:29 (GMT +200)
##### Environment:

Ubuntu saucy & precise
##### Summary:

I expected the docker module to run a new container only if the container doesn't exist yet.
##### Steps To Reproduce:

Given this task:

```
- name: run some container
  docker:
    image: fish/some-container
    name: some-containers-name
```
##### Expected Results:

I expected the docker module to run a new container only if the container doesn't exist yet.
##### Actual Results:

It's starting a new container each time. 
##### Notes:

That should be easy to implement if the name attribute is provided:

If there is no container with that name: run (docker run) a new one
If there is one with that name, and it's stopped: start it (docker start)
If there is one with that name and it's running: noop
Please summarize your request in this space.  You will earn bonus points for being succinct, but please add enough detail so we can understand the request.

**Comment by softzilla** [comment] 2014-03-11 15:57
Can't reproduce. 

New container created only on first run:

```
    - name: Start 1
      docker:
        image: ubuntu
        name: c1
        state: present
        command: sleep 1000
      tags: ['dev']


    - name: Start 2
      docker:
        image: ubuntu
        name: c1
        state: present
        command: sleep 1000
      tags: ['dev']
```

Output: 

```
GATHERING FACTS ***************************************************************
ok: [server]

TASK: [Start 1] ***************************************************************
changed: [server]

TASK: [Start 2] ***************************************************************
ok: [server]

PLAY RECAP ********************************************************************
server             : ok=3    changed=1    unreachable=0    failed=0
```

"ok" (not "changed") - Second task run without new container

Also, "docker ps -a" on host gives only one container with name "c1" and command "sleep 1000".

**Comment by mpdehaan** [comment] 2014-03-11 16:39
I'm going to close this per the above.    If we think there are still issues let's discuss implementation on ansible-devel (as notifications on this closed ticket are not easily read by everyone, and tickets in general are not read by everyone).

Thanks!

**Closed as completed by mpdehaan** 2014-03-11 16:39 UTC
Labels: docker

**Comment by jpetazzo** [comment] 2014-03-12 18:45
Try with "sleep 1" instead of "sleep 1000".

There are (at least) two use-cases for this feature:
- make sure that something is running (if it has been stopped for some reason, restart it!)
- make sure that a container exists (e.g. for data containers).

I will also ping ansible-devel.

Thank you!
