### ISSUE TITLE
SSL verification fails

### ISSUE THREAD

**Issue by kodieg** [ansible/ansible#6474] opened 2014-03-13 16:30 UTC
##### Issue Type:

Problem with SSL verification 
##### Ansible Version:

`ansible 1.5.2`
installed via pip
##### Environment:

Ubuntu 12.04
##### Summary:

When I try to fetch any URL via https I get SSL verification error
##### Steps To Reproduce:

```
ansible -i 127.0.0.1, "*" -m 'get_url'  -a'url="https://www.postgresql.org" dest=/tmp/x'
```

```

##### Expected Results:

Downloaded file.

##### Actual Results:

127.0.0.1 | FAILED >> {
    "failed": true, 
    "msg": "failed to validate the SSL certificate for www.postgresql.org:443. You can use validate_certs=no, however this is unsafe and not recommended '/usr/share/ca-certificates/cacert.org/cacert.org.crt'"
}
```

I am on ubuntu 12.04. Script found some certs here /usr/share/ca-certificates/cacert.org/cacert.org.crt and failed to verify postgresql certificate. Any ideas why?

**Comment by stanhu** [comment] 2014-03-13 17:33
I suspect this is a duplicate of #6412.

**Comment by mpdehaan** [comment] 2014-03-13 22:56
A user on twitter had this same problem because their ca-certs were old and we are now validating certs, which is to say, this is kind of a feature.

This was fixed for them by running update-ca-certs on their system.

Let us know per what ansibot is asking what version of ansible you are using and whether this works for you.

**Comment by kodieg** [comment] 2014-03-14 07:28
update-ca-certificates make no difference. Isn't that a problem that get_ca_cert in module_utils/urts.py returns "/usr/share/ca-certificates/cacert.org/cacert.org.crt" and not "/etc/ssl/certs/ca-certificates.crt"?

When I changed this function to return ca-certificates.crt, everything works fine

**Comment by mpdehaan** [comment] 2014-03-16 16:08
1.5.3 and later should look for all .crt files in the search directories.

Let us know if you are still seeing problems.

**Comment by marmot21** [comment] 2014-03-17 00:28
1.5.3 Fixed this issue for me

**Comment by ramondelafuente** [comment] 2014-03-17 23:44
I ran into this on OSX 10.9.2 with Ansible 1.5.3.

While executing a "local_action" (for notification). The paths searched are _/etc/ssl/certs_ and _/etc/ansible_ but I think OSX uses the keychain to store certificates...

[ Workaround: I use macports and have **curl-ca-bundle** installed; I have symlinked _/opt/local/share/curl/_ to _/etc/ssl/certs_ to make it work for now ]

**Comment by FiloSottile** [comment] 2014-03-19 16:51
1.5.3 fixed this for me.

Control machine: OS X
Remote: Debian Wheezy

Old version: 1.5.2

**Comment by mpdehaan** [comment] 2014-03-29 19:17
There's a fix applied on devel that enables the OS X keychain (due to some crazy aspects of needing to feed at least one dummy cert to the library to get this far).   

So this should be pretty good to go on 1.5.3 and even better on 1.6, as a result, I think we can close this one.

**Closed as completed by mpdehaan** 2014-03-29 19:17 UTC
Labels: needs_info, P2, net_tools, bug

**Comment by lpaulmp** [comment] 2016-04-14 14:37
I have the same problem on ansible 2.0.1.0, tested on ubuntu 14.04
`{"changed": false, "failed": true, "invocation": {"module_args": {"data": null, "file": null, "id": "ACCC4CF8", "key": null, "keyring": null, "keyserver": null, "state": "present", "url": "https://www.postgresql.org/media/keys/ACCC4CF8.asc", "validate_certs": true}, "module_name": "apt_key"}, "msg": "Failed to validate the SSL certificate for www.postgresql.org:443. Make sure your managed systems have a valid CA certificate installed.  If the website serving the url uses SNI you need python >= 2.7.9 on your managed machine.  You can use validate_certs=False if you do not need to confirm the server\\s identity but this is unsafe and not recommended Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible"}`

**Comment by wuz** [comment] 2016-04-15 15:41
I am having a similar problem as @lpaulmp, 

```
TASK: [apt_key url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present] *** 
failed: [localhost] => {"failed": true}
msg: Failed to validate the SSL certificate for www.postgresql.org:443. Use validate_certs=no or make sure your managed systems have a valid CA certificate installed. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible 
```

Any thoughts?

**Comment by lpaulmp** [comment] 2016-04-15 15:44
@ohmfox are you deploying some ssl certs before deploy postgres??

**Comment by wuz** [comment] 2016-04-15 16:16
No, just trying to install Postgres on a Docker machine using Ansible.

**Comment by lpaulmp** [comment] 2016-04-15 16:20
I had this issue because I used wrong ssl certs on my /etc/ssl/ folder on ubuntu. Also you could being  MITMed

**Comment by wuz** [comment] 2016-04-15 16:25
How do you mean?

**Comment by lpaulmp** [comment] 2016-04-15 16:31
@ohmfox Check your ssl folder, looks that is correct in my case some ssl cert was wrong.

**Comment by lpaulmp** [comment] 2016-04-15 17:29
@ohmfox please let us if you find some solution :)

**Comment by zerotao** [comment] 2016-04-15 18:26
@ohmfox check that you can resolve www.postgresql.org from your container.  I just ran into the same issue and when I did the following:

  openssl s_client -showcerts -connect www.postgresql.org:443

it gave a could not resolve error.

restarted docker and everything started working.
