### ISSUE TITLE
Incorrect evaluation of conditions with externally changed boolean variables and `and`

### ISSUE THREAD

**Issue by skazi0** [ansible/ansible#28874] opened 2017-08-31 11:25 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible-playbook, when

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /home/skazi/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
```
[defaults]
inventory = $HOME/ansible/hosts

gathering = smart
fact_caching = jsonfile
fact_caching_connection = $HOME/.ansible/facts_cache
fact_caching_timeout = 86400

[privilege_escalation]
become=True
become_method=sudo
become_user=root
#become_ask_pass=True
```
##### OS / ENVIRONMENT
Debian Jessie

##### SUMMARY
Conditions using boolean variables and `and` are not evaluated correctly when variable values are changed from outside the playbook.

The `when: ansible_distribution == "Debian" and bool_test` expression is correctly evaluated when `bool_test` is changed inside the playbook but not if it's changed when including playbook in another one or with `--extra-vars` CLI parameter. The list version of `and` works correctly.
##### STEPS TO REPRODUCE
test.yaml
```yaml
---
- hosts: all
  vars:
    bool_test: True
  tasks:
    - debug: "msg={{ bool_test }}"

    - name: Run when distro and test list
      debug: "msg='true so running'"
      when:
        - ansible_distribution == "Debian"
        - bool_test

    - name: Run when distro and test
      debug: "msg='true so running'"
      when: ansible_distribution == "Debian" and bool_test

    - name: Run when distro
      debug: "msg='true so running'"
      when: ansible_distribution == "Debian"

    - name: Run when test
      debug: "msg='true so running'"
      when: bool_test
```
test2.yml
```yaml
---
- include: test.yml bool_test=False
- include: test.yml bool_test=True
```
shell
```
$ ansible-playbook test.yml --limit localhost
$ ansible-playbook test.yml --limit localhost --extra-vars bool_test=False
$ ansible-playbook test2.yml --limit localhost
```

##### EXPECTED RESULTS
```
$ ansible-playbook test.yml --limit localhost

PLAY [all] *********************************************************************

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": true
}

TASK [Run when distro and test list] *******************************************
ok: [localhost] => {
    "msg": "true so running"
}

TASK [Run when distro and test] ************************************************
ok: [localhost] => {
    "msg": "true so running"
}

TASK [Run when distro] *********************************************************
ok: [localhost] => {
    "msg": "true so running"
}

TASK [Run when test] ***********************************************************
ok: [localhost] => {
    "msg": "true so running"
}

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=0   
```
```
$ ansible-playbook test.yml --limit localhost --extra-vars bool_test=False

PLAY [all] *********************************************************************

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": false
}

TASK [Run when distro and test list] *******************************************
skipping: [localhost]

TASK [Run when distro and test] ************************************************
skipping: [localhost]

TASK [Run when distro] *********************************************************
ok: [localhost] => {
    "msg": "true so running"
}

TASK [Run when test] ***********************************************************
skipping: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0   
```
```
$ ansible-playbook test2.yml  --limit localhost

PLAY [all] *********************************************************************

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": false
}

TASK [Run when distro and test list] *******************************************
skipping: [localhost]

TASK [Run when distro and test] ************************************************
skipping: [localhost]

TASK [Run when distro] *********************************************************
ok: [localhost] => {
    "msg": "true so running"
}

TASK [Run when test] ***********************************************************
skipping: [localhost]

PLAY [all] *********************************************************************

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": true
}

TASK [Run when distro and test list] *******************************************
ok: [localhost] => {
    "msg": "true so running"
}

TASK [Run when distro and test] ************************************************
ok: [localhost] => {
    "msg": "true so running"
}

TASK [Run when distro] *********************************************************
ok: [localhost] => {
    "msg": "true so running"
}

TASK [Run when test] ***********************************************************
ok: [localhost] => {
    "msg": "true so running"
}

PLAY RECAP *********************************************************************
localhost                  : ok=8    changed=0    unreachable=0    failed=0   
```

##### ACTUAL RESULTS
```
$ ansible-playbook test.yml --limit localhost

PLAY [all] *********************************************************************

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": true
}

TASK [Run when distro and test list] *******************************************
ok: [localhost] => {
    "msg": "true so running"
}

TASK [Run when distro and test] ************************************************
ok: [localhost] => {
    "msg": "true so running"
}

TASK [Run when distro] *********************************************************
ok: [localhost] => {
    "msg": "true so running"
}

TASK [Run when test] ***********************************************************
ok: [localhost] => {
    "msg": "true so running"
}

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=0   
```
```
$ ansible-playbook test.yml --limit localhost --extra-vars bool_test=False

PLAY [all] *********************************************************************

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": false
}

TASK [Run when distro and test list] *******************************************
skipping: [localhost]

TASK [Run when distro and test] ************************************************
ok: [localhost] => {
    "msg": "true so running"
}

TASK [Run when distro] *********************************************************
ok: [localhost] => {
    "msg": "true so running"
}

TASK [Run when test] ***********************************************************
skipping: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0   
```
```
$ ansible-playbook test2.yml  --limit localhost

PLAY [all] *********************************************************************

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": false
}

TASK [Run when distro and test list] *******************************************
skipping: [localhost]

TASK [Run when distro and test] ************************************************
ok: [localhost] => {
    "msg": "true so running"
}

TASK [Run when distro] *********************************************************
ok: [localhost] => {
    "msg": "true so running"
}

TASK [Run when test] ***********************************************************
skipping: [localhost]

PLAY [all] *********************************************************************

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": true
}

TASK [Run when distro and test list] *******************************************
ok: [localhost] => {
    "msg": "true so running"
}

TASK [Run when distro and test] ************************************************
ok: [localhost] => {
    "msg": "true so running"
}

TASK [Run when distro] *********************************************************
ok: [localhost] => {
    "msg": "true so running"
}

TASK [Run when test] ***********************************************************
ok: [localhost] => {
    "msg": "true so running"
}

PLAY RECAP *********************************************************************
localhost                  : ok=8    changed=0    unreachable=0    failed=0   
```

**Comment by giovannisciortino** [comment] 2017-08-31 18:31
Reproduced this behavior also in 2.4. 
But I think it's a duplicate of this issue https://github.com/ansible/ansible/issues/17193 that was closed as not bug and contain further detail about passing False boolean value with --extra-vars

**Comment by sivel** [comment] 2017-08-31 18:35
passing vars from `--extra-vars` using the `key=value` syntax always assumes that the value is a string.  You can pass JSON via extra-vars, which cause it to use the right variable type, such as:

```
--extra-vars '{"bool_test": False}'
```

It is recommended that when you are evaluating a boolean in a when statement to use the `|bool` filter, to ensure that string values that look like booleans are properly evaluated as a real boolean, such as:

`when: bool_test|bool`

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Closed as completed by sivel** 2017-08-31 18:35 UTC
Labels: affects_2.2, c:cli/playbook, support:core, bug

**Comment by skazi0** [comment] 2017-09-01 07:46
@giovannisciortino I don't think this is a duplicate of #17193. The case from that bug actually works fine in my scenario (probably because of newer version). My problem is only with composite conditions with `and` (maybe others as well). IMO this is a bug as we have inconsistent behavior of condition depending on it's complexity, i.e. `when: bool_test` works fine but `when: something='the value' and bool_test` does not even if first part is true.
@sivel thanks for the `|bool` hint. This solves the problem but note that the problem is not only with `--extra-vars`. Included playbooks also don't handle the conditions properly. In the end even if `|bool` would be the solution (not just a workaround), it should at least be clearly documented (e.g. http://docs.ansible.com/ansible/latest/playbooks_conditionals.html#the-when-statement has example with direct use of booleans and doesn't mention `bool` filter).

**Comment by sivel** [comment] 2017-09-01 14:05
Playbook includes, due to use `key=value` style variable definitions also suffer from the same problem as `--extra-vars` when using `key=value`

Using the `|bool` filter is safest.

To use full YAML to get variable types to stick with playbook includes use:

```
- include: something.yml
  vars:
    bool_test: True
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by skazi0** [comment] 2017-09-05 09:00
@sivel thx
