### ISSUE TITLE
JSON not returned as raw string in long-form actions with variable substitutions

### ISSUE THREAD

**Issue by scottanderson42** [ansible/ansible#7005] opened 2014-04-15 22:59 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6 (devel 53a511275c) last updated 2014/04/08 10:58:23 (GMT -400)
##### Environment:

OSX 10.9.2 
##### Summary:

The problem is only displayed in actions (or local_actions, not shown below but I did test it) with JSON in parameters that have variable substitutions in them. There’s definitely a different path being followed given the REMOTE_MODULE lines are different.
##### Steps To Reproduce:

ansible-playbook -vvv -i inventory/local pb_test.yml

https://gist.github.com/scottanderson42/10786990
##### Expected Results:

All 4 tasks should return exactly the same results.
##### Actual Results:

(sp_devops)GoatRodeo:devops anderson$ ansible-playbook -vvv -i inventory/local pb_test.yml

```
PLAY [127.0.0.1] ************************************************************** 

TASK: [test_params] *********************************************************** 
<127.0.0.1> REMOTE_MODULE test_params
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1397601415.78-239255619138400 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1397601415.78-239255619138400 && echo $HOME/.ansible/tmp/ansible-tmp-1397601415.78-239255619138400']
<127.0.0.1> PUT /var/folders/m4/mk3x6q_50dj_50jpx0763lm80000gn/T/tmpxbRBxm TO /Users/anderson/.ansible/tmp/ansible-tmp-1397601415.78-239255619138400/test_params
<127.0.0.1> EXEC ['/bin/sh', '-c', '/usr/bin/python /Users/anderson/.ansible/tmp/ansible-tmp-1397601415.78-239255619138400/test_params; rm -rf /Users/anderson/.ansible/tmp/ansible-tmp-1397601415.78-239255619138400/ >/dev/null 2>&1']
ok: [127.0.0.1] => {"changed": false, "thing": "{u'test': u'harbles'}"}

TASK: [test_params] *********************************************************** 
<127.0.0.1> REMOTE_MODULE test_params thing='{"test":"harbles"}'
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1397601415.84-272058890961595 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1397601415.84-272058890961595 && echo $HOME/.ansible/tmp/ansible-tmp-1397601415.84-272058890961595']
<127.0.0.1> PUT /var/folders/m4/mk3x6q_50dj_50jpx0763lm80000gn/T/tmpb9C64f TO /Users/anderson/.ansible/tmp/ansible-tmp-1397601415.84-272058890961595/test_params
<127.0.0.1> EXEC ['/bin/sh', '-c', '/usr/bin/python /Users/anderson/.ansible/tmp/ansible-tmp-1397601415.84-272058890961595/test_params; rm -rf /Users/anderson/.ansible/tmp/ansible-tmp-1397601415.84-272058890961595/ >/dev/null 2>&1']
ok: [127.0.0.1] => {"changed": false, "thing": "{\"test\":\"harbles\"}"}

TASK: [test_params thing='{"test":"harbles"}'] ******************************** 
<127.0.0.1> REMOTE_MODULE test_params thing='{"test":"harbles"}'
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1397601415.9-58380721107891 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1397601415.9-58380721107891 && echo $HOME/.ansible/tmp/ansible-tmp-1397601415.9-58380721107891']
<127.0.0.1> PUT /var/folders/m4/mk3x6q_50dj_50jpx0763lm80000gn/T/tmpXAVoIC TO /Users/anderson/.ansible/tmp/ansible-tmp-1397601415.9-58380721107891/test_params
<127.0.0.1> EXEC ['/bin/sh', '-c', '/usr/bin/python /Users/anderson/.ansible/tmp/ansible-tmp-1397601415.9-58380721107891/test_params; rm -rf /Users/anderson/.ansible/tmp/ansible-tmp-1397601415.9-58380721107891/ >/dev/null 2>&1']
ok: [127.0.0.1] => {"changed": false, "thing": "{\"test\":\"harbles\"}"}

TASK: [test_params thing='{"test":"harbles"}'] ******************************** 
<127.0.0.1> REMOTE_MODULE test_params thing='{"test":"harbles"}'
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1397601415.96-101768747887534 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1397601415.96-101768747887534 && echo $HOME/.ansible/tmp/ansible-tmp-1397601415.96-101768747887534']
<127.0.0.1> PUT /var/folders/m4/mk3x6q_50dj_50jpx0763lm80000gn/T/tmpBYgVAP TO /Users/anderson/.ansible/tmp/ansible-tmp-1397601415.96-101768747887534/test_params
<127.0.0.1> EXEC ['/bin/sh', '-c', '/usr/bin/python /Users/anderson/.ansible/tmp/ansible-tmp-1397601415.96-101768747887534/test_params; rm -rf /Users/anderson/.ansible/tmp/ansible-tmp-1397601415.96-101768747887534/ >/dev/null 2>&1']
ok: [127.0.0.1] => {"changed": false, "thing": "{\"test\":\"harbles\"}"}

TASK: [fail msg='These should be equal...'] *********************************** 
failed: [127.0.0.1] => {"failed": true}
msg: These should be equal...

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/anderson/pb_test.retry

127.0.0.1                  : ok=5    changed=0    unreachable=0    failed=1  
```

**Comment by jimi-c** [comment] 2014-04-22 15:16
Hrm, if I define a var as follows:

<pre>
  vars:
    moo: harbles
    bar:
      test: harbles
</pre>

The test also fails (for both result1 and result2), despite the fact that `debug: var=` says that all  three appear to be the same:

<pre>
    - debug: var=results1.thing
    - debug: var=results2.thing
    - debug: var=bar
 
    - fail: msg='These should be equal...'
      when: results1.thing != bar
      ignore_errors: yes
 
    - fail: msg='These should be equal...'
      when: results2.thing != bar
      ignore_errors: yes
 
    - fail: msg='These should be equal...'
      when: results1.thing != results2.thing
      ignore_errors: yes
TASK: [debug var=results1.thing] ********************************************** 
ok: [127.0.0.1] => {
    "results1.thing": {
        "test": "harbles"
    }
}
TASK: [debug var=results2.thing] ********************************************** 
ok: [127.0.0.1] => {
    "results2.thing": {
        "test": "harbles"
    }
}
TASK: [debug var=bar] ********************************************************* 
ok: [127.0.0.1] => {
    "bar": {
        "test": "harbles"
    }
}
TASK: [fail msg='These should be equal...'] *********************************** 
failed: [127.0.0.1] => {"failed": true}
msg: These should be equal...
...ignoring
TASK: [fail msg='These should be equal...'] *********************************** 
failed: [127.0.0.1] => {"failed": true}
msg: These should be equal...
...ignoring
TASK: [fail msg='These should be equal...'] *********************************** 
failed: [127.0.0.1] => {"failed": true}
msg: These should be equal...
...ignoring
</pre>

So I'm not sure if this is because of the JSON, or if it's something odd going on with jinja2 when comparing dictionaries.

**Comment by scottanderson42** [comment] 2014-04-22 15:33
Note that the JSON was being explicitly parsed and then converted to a string when I debugged this directly within the module. The playbook fail tasks are just a convenient means of demonstrating the behavior.

If you print out the value of 'thing' on line 11 of the module (after this line: thing = module.params.get('thing')), the JSON text from the file has already been inappropriately converted.

**Comment by jimi-c** [comment] 2014-04-22 15:39
Looking at the python representations of each of the results, I believe the issue is that sometimes the keys and/or values of the dictionaries may or may not be unicode objects vs. regular strings:

<pre>
results1: u'thing': u"{u'test': u'harbles'}"
results2: u'thing': u'{"test":"harbles"}'
results3: u'thing': u'{"test":"harbles"}'
results4: u'thing': u'{"test":"harbles"}'
bar: {'test': 'harbles'}
</pre>

**Comment by scottanderson42** [comment] 2014-04-22 15:43
The u'' only indicates that the raw JSON has been parsed here:

"{u'test': u'harbles'}"

In other words, the value starts out as:

{"test":"harbles"}

It's read in and parsed instead of being treated as a raw value, resulting in a Python dict. This dict is then coerced to be a string, which results in this:

"{u'test': u'harbles'}"

I don't believe this has anything to do with the original state of the values. The problem is that it's being parsed in the first place.

**Comment by jimi-c** [comment] 2014-04-22 16:24
Ahh, ok, I see what's going on here. The way you have things specified above, you are using the 'complex variable' syntax, in which the variables are not passed in as strings but rather as data structures. If you change the first task to:

<pre>
    - test_params: thing='{"test":"{{ moo }}"}'
      register: results1
</pre>

the play works as expected. The reason is that when the complex args are templated, they are run through the utils.safe_eval() function which turns the thing value into a data structure before templating it (recursively).

Make sense?

**Comment by scottanderson42** [comment] 2014-04-22 16:29
Huh... I guess so. It's completely unexpected though, from my perspective. 

I was just trying to read in a file that happened to have JSON in it -- the original task was using lookup('file', 'somefile.json') instead of '{"test":"{{ moo }}"}' -- and I prefer to use (what I think of as) the long form of module parameter specification as it's much easier to read when there are more than a few parameters. I had no idea it changed the semantics of the data, particularly since it does it transparently by detecting a { or [ at the start of the file.

Is there a way to have a parameter per line but without the JSON parsing semantics?

**Comment by jimi-c** [comment] 2014-04-22 16:33
Yes, you can use the line continuation character:

<pre>
    - test_params: >
        thing='{"test":"{{ moo }}"}'
      register: results1
</pre>

Any lines with the same indent after the first indented line (if you had other parameters besides thing) do not need the continuation character. For example:

<pre>
    - test_params: >
        thing1=...
        thing2=...
        thing3=...
      register: results1
</pre>

**Comment by jimi-c** [comment] 2014-04-22 18:07
@scottanderson42 if the above syntax works for you, any object to closing this issue?

**Comment by scottanderson42** [comment] 2014-04-22 22:15
Just for clarification, is this behavior documented anywhere? I haven't been able to find it.

**Comment by jimi-c** [comment] 2014-04-23 04:12
@scottanderson42 not really, it's more of an internal thing that doesn't come up very often.

**Comment by jimi-c** [comment] 2014-04-23 20:57
I'm going to go ahead and close this, if you have any further questions please let us know. Thanks!

**Closed as completed by jimi-c** 2014-04-23 20:57 UTC
Labels: P2, bug

**Comment by scottanderson42** [comment] 2014-05-12 16:22
@jimi-c This is continuing to cause me pain, unfortunately.

Here's an example:

```
    - name: Create an instance
      local_action:
        module: ec2
        state: present
        image: "{{ ami_base_image_id }}"
        instance_type: t1.micro
        group: "{{ instance_security_groups }}"
        key_name: "{{ environment_public_ssh_key_name }}"
        vpc_subnet_id: "{{ environment_vpc_public_subnet_az1_id }}"
        user_data: "{{ lookup('template', '../templates/user_data.json') }}"
        assign_public_ip: yes
        wait: yes
        wait_timeout: 600
        region: "{{ vpc_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: new_instance
      when: environment_instance is not defined
```

user_data needs a raw string. group needs complex data (instance_security_groups is a list of strings). If I use the complex arg version as above, user_data fails because it's a dict. If I use this:

```
    - name: Create an instance
      ec2: >
        state=present
        image="{{ ami_base_image_id }}"
        instance_type=t1.micro
        group="{{ instance_security_groups }}"
        key_name="{{ environment_public_ssh_key_name }}"
        vpc_subnet_id="{{ environment_vpc_public_subnet_az1_id }}"
        user_data="{{ lookup('template', '../templates/user_data.json') }}"
        assign_public_ip=yes
        wait=yes
        wait_timeout=600
        region="{{ vpc_region }}"
        aws_access_key="{{ aws_access_key }}"
        aws_secret_key="{{ aws_secret_key }}"
      register: new_instance
      when: environment_instance is not defined
```

Then the user_data works, but the groups fail (silently, as it happens... I only noticed because the instance was unreachable) because they're passed in as a string.

**Comment by sayap** [comment] 2014-05-12 22:07
One trick you may try is to wrap user_data with empty space, assuming the tool that reads it later can deal with that (I use http://stedolan.github.io/jq/ and it has no problem with the extra spaces). Then, it shall remain as raw string.

**Comment by jkamenik** [comment] 2016-08-19 18:24
A year late, but here is the trick I do that I don't think sucks too bad.

``` yml
- name: set user_data
  set_fact:
    user_data: "{{ lookup('template', '../templates/user_data.json') | string }}"

 - name: Create an instance
      ec2: >
        state=present
        image="{{ ami_base_image_id }}"
        instance_type=t1.micro
        group="{{ instance_security_groups }}"
        key_name="{{ environment_public_ssh_key_name }}"
        vpc_subnet_id="{{ environment_vpc_public_subnet_az1_id }}"
        user_data="{{ user_data }}"
        assign_public_ip=yes
        wait=yes
        wait_timeout=600
        region="{{ vpc_region }}"
        aws_access_key="{{ aws_access_key }}"
        aws_secret_key="{{ aws_secret_key }}"
      register: new_instance
      when: environment_instance is not defined
```

By putting it in a variable it becomes a string which is what EC2 wants.  For some reason if I do the `lookup(...) | string` within the EC2 block then `| string` appears to be ignored.

**Comment by brendanlong** [comment] 2019-03-08 18:13
Just ran into this too, spending over an hour trying to figure out how to keep a JSON dict as a literal string so I can pass it as part of a list of Docker labels. Automatically evaling anything that starts with `[` or `{` is *really* confusing and should at least be documented with a workaround. I ended up having to write:

```
default_docker_labels:
  # https://github.com/ansible/ansible/issues/7005
  "com.datadoghq.ad.logs": >-
    {{ [{"source": app_name, "service": app_name}] | to_json }}
```

Because that somehow happens to avoid all of the automatic evaling, but neither of these worked as expected:

```
  "com.datadoghq.ad.logs": '[{"source": "{{ app_name }}", "service": "{{ app_name}}"}]'
  "com.datadoghq.ad.logs": >-
    [{"source": "{{ app_name }}", "service": "{{ app_name}}"}]
```
