### ISSUE TITLE
/tmp/ansible/ not world-writable

### ISSUE THREAD

**Issue by chrisblossom** [ansible/ansible#5725] opened 2014-01-22 18:20 UTC
When initially setting "user: root" in a playbook, /tmp/ansible is created with directory permissions 0755 when it should be 0777 (recurse=no) because when falling back to a non-root user the following error occurs:

Should be noted I'm not specifying "-u root" in the ansible-playbook command.

```
fatal: [dev] => Authentication or permission failure.  In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in "/tmp". Failed command was: mkdir -p /tmp/ansible/$USER/ansible-tmp-1390414200.76-192986604554742 && chmod a+rx /tmp/ansible/$USER/ansible-tmp-1390414200.76-192986604554742 && echo /tmp/ansible/$USER/ansible-tmp-1390414200.76-192986604554742, exited with result 1: mkdir: cannot create directory `/tmp/ansible/chris': Permission denied
```

Example playbook:

```
-   name: initial setup
    hosts: all
    user: root
    roles:
        - system
        - packages
        - users

-   name: common setup
    hosts: all
    tasks:
        - include: roles/users/tasks/freshshell.yml

-   hosts: webservers
    gather_facts: false
    roles:
        - php
        - nginx
        - web_deploy
```

The solution I have done is to first setup the /tmp/ansible directory with the correct permissions:

```
-   name: /tmp/ansible/ directory exists with 0777 permission
    file: path=/tmp/ansible/ owner=root group=root mode=0777 recurse=no state=directory
    sudo: yes

```

**Comment by mpdehaan** [comment] 2014-01-23 15:51
So the default temp location is handled here:

DEFAULT_REMOTE_TMP        = shell_expand_path(get_config(p, DEFAULTS, 'remote_tmp',       'ANSIBLE_REMOTE_TEMP',      '$HOME/.ansible/tmp'))

Which uses the user's home directory

The default ansible.cfg also sets this this way:

remote_tmp     = $HOME/.ansible/tmp

Did you perhaps change this?

Also please share what version of Ansible you are using.

Thank you!

**Comment by chrisblossom** [comment] 2014-01-23 16:01
```
chris@chris-rmbp  ~/Dropbox/GitHub/ansible  ± master ●  ansible-playbook --version
ansible-playbook 1.5 (devel 61d283e2ad) last updated 2014/01/21 19:14:16 (GMT -700)
```

I'm using a mostly-default ansible config located in the base of my Ansible directory (although I am not sure the last time the ansible.cfg file has been updated):

```
# config file for ansible -- http://ansibleworks.com/
# ==================================================

# nearly all parameters can be overridden in ansible-playbook
# or with command line flags. ansible will read ~/.ansible.cfg,
# ansible.cfg in the current working directory or
# /etc/ansible/ansible.cfg, whichever it finds first

[defaults]

# some basic default values...

hostfile       = local
library        = /usr/share/ansible
remote_tmp     = /tmp/ansible/$USER
pattern        = *
forks          = 5
poll_interval  = 15
sudo_user      = root
#ask_sudo_pass = True
#ask_pass      = True
transport      = smart
remote_port    = 22

```

Looks like remote_tmp was changed somehow. Was this default at one point? Because there is no reason I would have changed it. I'm going to update the ansible.cfg file from the example directory in the meantime.

**Comment by chrisblossom** [comment] 2014-01-24 16:28
I think I made a mistake, sorry. I need better commenting...I think I moved the remote_tmp to /tmp because there is an issue if the user does not have a home directory, such as www-data, Ansible will fail without this change. Another option is for me to change to /tmp/$USER/ansible so I won't need to specifically change /tmp/ansible to world-writable won't be an issue anymore.

Maybe a better fallback should be inplace if a user's home directory doesn't exist? Just an idea.

**Comment by mpdehaan** [comment] 2014-03-19 15:58
Falling back to temp seems a little sketchy as a default, but leaving this open for now.

**Comment by edrozenberg** [comment] 2014-06-05 13:16
I've run into a somewhat related 'head-banging' :) issue which I finally resolved. Somehow the local controller machine ~HOME/.ansible/tmp path got chowned root, unbeknownst to me at the time. I run ansible as a regular user so eventually I ran across this error doing a synchronize:

```
fatal: [slacky] => Authentication or permission failure.  In some cases, you 
may have been able to authenticate and did not have permissions on the remote 
directory. Consider changing the remote temp path in ansible.cfg to a path 
rooted in "/tmp". Failed command was: mkdir -p 
$HOME/.ansible/tmp/ansible-tmp-1401973086.25-185293296215162 && echo 
$HOME/.ansible/tmp/ansible-tmp-1401973086.25-185293296215162, exited with 
result 1
```

The error clearly implied that the problem is on the remote host so I kept running the failed command and it was working on the remote host just fine. It was only after doing a verbose run that I saw in addition the following error:

```
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p 
$HOME/.ansible/tmp/ansible-tmp-1401973086.25-185293296215162 && echo 
$HOME/.ansible/tmp/ansible-tmp-1401973086.25-185293296215162']
```

Which meant the failure was actually on the local controller machine. After deleting my local .ansible directory everything worked fine again. Ansible will hopefully improve the cleanup and sanity checking of potential issues on the local and remote .ansible directories which can cause this tricky and hard to debug class of issues. Also the error messages will need to be improved because in this case the initial error message was extremely misleading. I'll plan to submit some ideas on this as a Feature Request.

**Comment by ttousai** [comment] 2014-08-06 11:34
I also encountered this problem on Mac OS X Mavericks running ansible 1.7 (devel c93b89fa63). The solution for me was to run ansible with the '-c paramiko' connection parameter.

**Comment by edrozenberg** [comment] 2014-08-06 18:46
@ttousai note that running with Paramiko means slower performance than the default ssh connection mode. You might want to check whether deleting your local ~/.ansible directory or making sure it is chowned as your normal user fixes the problem in case it is a permissions issue.

**Comment by ttousai** [comment] 2014-08-07 09:37
@edrozenberg deleting the ~/.ansible directory had no effect at all. Note that the version of SSH on the Mavericks is OpenSSH_6.2p2 dated 8th December 2011. Will try installing a more recent of openssh and update.

**Comment by theshapguy** [comment] 2015-04-06 12:12
It may be because your Linux $HOME is encrypted. Try to decrypt and run it.

**Comment by jimi-c** [comment] 2015-06-18 14:30
Hi all, we're going back through some of the older issues, and I see this seems to revolve more around system configuration rather than anything Ansible is doing. Can anyone confirm whether or not this is still an issue for them? In regards to the permissions error, that is due to the fact that Ansible creates the directory with restrictive permissions to prevent other users from having access to those temporary files created during execution, and will not be changed.

**Comment by hybby** [comment] 2015-07-03 16:02
the problem i was having was running playbooks as my own user (`drew`) but with `sudo: yes` enabled.  this works fine for me, as a temporary directory is created, belonging to me.

however then when my colleague comes along (`dave`) and runs the same playbook, he'd have problems writing to the temporary directory, as it was owned by `drew` with restrictive permissions.

i've had more success setting `remote_tmp` as so:

```
remote_tmp     = /tmp/${USER}/ansible
```

this means that when both `drew` and `dave` run the same playbook, two temporary directories are created, one for each user.  

```
# ls -ld /tmp/drew
drwxr-x---. 2 drew users 4096 Jul  3 16:43 ansible

# ls -ld /tmp/dave
drwxr-x---. 2 dave users 4096 Jul  3 16:43 ansible
```

so, neither user then experiences permissions issues writing to the temporary directory.  nor do any further new users!

**Comment by jimi-c** [comment] 2015-07-04 03:49
Thanks for the follow-up, I'll go ahead and close this issue.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-07-04 03:49 UTC
Labels: needs_info, bug

**Comment by mondherGL** [comment] 2016-04-29 12:50
Hi there, 

i want to use variables from the remote host i tried to save for example the variable JAVA_HOME existing in the remote host in a file , but the file is empty .
ansible can't find this variable .
is there any configuration , module ... to use to manipulate the environments variables of the remote host ?

---
- name: java home
  shell: chdir=/home  echo $JAVA_HOME > TEST.txt

the value of $JAVA_HOME is /usr/jdk1.8.0_65 when i execute "echo $JAVA_HOME" directly in the remote host but when i use ansible i can't catch any thing .

thank you in advance .

**Comment by abadger** [comment] 2016-04-29 14:08
Hi, that's a usage question rather than a bug report.  Please use the
mailing list mentioned above or  irc, #ansible  on irc.freenode.net, to get
help for your question.   Thanks.

**Comment by gajowi** [comment] 2017-05-03 10:56
For reference, this also seems to be a problem with template and sudo on a system with nfs mounted home directories and root squash.  The same workaround applies.

**Comment by meenaven** [comment] 2018-04-08 02:06
excellent, it worked for me, i was struggling with this for last one week

**Comment by humpalum** [comment] 2018-04-23 11:16
Just an quick Heads-Up for anyone who may encounter this problem:
I just had the same Error, but the Solution was as simple as stupid: The harddisk was full so Ansible obviously couldn't write anything.

**Comment by mohi048** [comment] 2018-06-14 05:43
Folks, i had the same issue which turns out to be linux user password expiration issue , on logging onto the remote vm mannually, got the msg "You are required to change your password immediately (password aged)", Ansible was giving out the error message as "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory."

**Comment by collins-b** [comment] 2018-06-27 22:28
I agree with @mohi048. Changing the root password fixed this issue.
