### ISSUE TITLE
ansible: ansible 2.0.0.2: "ERROR! Missing required action" even if i want to see help

### ISSUE THREAD

**Issue by shamimgeek** [ansible/ansible#13969] opened 2016-01-18 21:21 UTC
Hi developer,

If i want to see help with ansible-galaxy without specifying any option it is throwing error "ERROR! Missing required action" . 

`ansible-galaxy --help`
or 
`ansible-galaxy  -h`

is it expected behavior or bug ? below are the details:

OS: Ubuntu 15.04 LTS
ansible version: 2.0.0.2

```
shamim@shamim-ThinkPad-Edge:~/Desktop/ansible$ ansible-galaxy -h
Usage: ansible-galaxy [delete|import|info|init|install|list|login|remove|search|setup] [--help] [options] ...

Options:
  -h, --help     show this help message and exit
  -v, --verbose  verbose mode (-vvv for more, -vvvv to enable connection
                 debugging)
  --version      show program's version number and exit
ERROR! Missing required action

shamim@shamim-ThinkPad-Edge:~/Desktop/ansible$ ansible-galaxy --help
Usage: ansible-galaxy [delete|import|info|init|install|list|login|remove|search|setup] [--help] [options] ...

Options:
  -h, --help     show this help message and exit
  -v, --verbose  verbose mode (-vvv for more, -vvvv to enable connection
                 debugging)
  --version      show program's version number and exit
ERROR! Missing required action
```

**Comment by bcoca** [comment] 2016-01-18 21:28
closing as dupe of #12004

**Closed as completed by bcoca** 2016-01-18 21:28 UTC
