### ISSUE TITLE
Ansible Galaxy won't install 'geerlingguy.ansible' role from Galaxy

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible#11556] opened 2015-07-10 23:16 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

1.9.2
##### Ansible Configuration:

Defaults.
##### Environment:

Mac OS X (10.10)
##### Summary:

Ansible Galaxy will not download my `geerlingguy.ansible` role from a requirements file, but instead returns the error:

```
$ ansible-galaxy install -r requirements.txt
- downloading role 'ansible', owned by geerlingguy
- sorry, geerlingguy.ansible was not found on galaxy.ansible.com.
```

Requirements file in question:

```
geerlingguy.firewall
geerlingguy.ansible
geerlingguy.java
geerlingguy.jenkins
```

(This was reported to me by @erimar77, taken from this example playbook: https://github.com/geerlingguy/ansible-for-devops/tree/master/jenkins).

The role exists in Galaxy, here: https://galaxy.ansible.com/list#/roles/1007 (though the title is missing), and is on GitHub, here: https://github.com/geerlingguy/ansible-role-ansible
##### Steps To Reproduce:

Attempt to install `geerlingguy.ansible` role from Ansible Galaxy via requirements file.
##### Expected Results:

`geerlingguy.ansible` role is downloaded and installed correctly.
##### Actual Results:

Ansible Galaxy returns an error saying that the role cannot be found.

**Comment by bcoca** [comment] 2015-07-11 00:01
I can confirm that even manually this does not work:

```
ansible-galaxy install geerlingguy.ansible -p roles/
- downloading role 'ansible', owned by geerlingguy
- sorry, geerlingguy.ansible was not found on galaxy.ansible.com.
- you can use --ignore-errors to skip failed roles.
```

**Comment by willthames** [comment] 2015-07-23 04:11
#11485 fixes this one. (in fact geerlinguy.mysql was my test case :) )

**Comment by geerlingguy** [comment] 2015-07-23 04:15
@willthames - More specifically, though, have you tested #11485 with the role `geerlingguy.ansible`? It seemed that that specific role was causing issues, maybe since the role name was `ansible` in Galaxy itself... it displays funny on Galaxy :-/

**Comment by willthames** [comment] 2015-07-23 04:34
@geerlingguy, I hadn't. I can still reproduce even with my fix.

It doesn't seem to be a bug in the ansible-galaxy tool though.

Basically, https://galaxy.ansible.com/api/v1/roles/?owner__username=geerlingguy&name=ansible isn't returning any results. (Compare the result with using name=mysql, which does have results)

So this might be a galaxy.ansible.com bug rather than an ansible-galaxy bug.

**Comment by gregdek** [comment] 2015-10-22 18:46
So we're going through our Galaxy issues, and we've found a lot of pointers to this one. :)

Here's the argument:

We generally strip away the namespace in list views on Galaxy, and we don't want a ton of roles named "Ansible" to show up and confuse people.

@geerlingguy in this case, it appears that we hit a corner case where deleting ansible-role from the beginning left us with just "ansible", and because that's basically reserved, your role can't actually be downloaded. Is that right?

Is there a compelling reason why you guys need to have roles named "ansible"?

(Actually, we're digging in to figure out exactly what's gone on. This is a weird corner case.)

**Comment by gregdek** [comment] 2015-10-22 18:53
OK, so this is the very specific case where we want a role to be called "ansible" because it actually installs ansible. We will figure out how to handle this case correctly.

**Comment by gregdek** [comment] 2015-10-22 18:54
Also confirming that this is a Galaxy upload issue, so we'll close this one and handle in the appropriate Galaxy issues.

**Closed as completed by gregdek** 2015-10-22 18:54 UTC
Labels: P2, bug
