### ISSUE TITLE
Windows path mangled on v2.0.0-0.6.rc1

### ISSUE THREAD

**Issue by juju4** [ansible/ansible#13311] opened 2015-11-26 02:39 UTC
Hello,

testing ansible v2, host is lubuntu trusty (fr UTF8). guest is win10 virtualbox (FR too, Installlanguage    REG_SZ    040C)

```
- name: Do FastIR check (64bits)
  raw: "{{ bin_path }}\\Fastir_Collector-master\\build\\FastIR_x64.exe"
```

```
TASK [xxx : Do FastIR check (64bits)] *****************************
fatal: [192.168.2.109]: FAILED! => {"changed": false, "failed": true, "rc": 1, "stderr": "#< CLIXML\r\n<Objs Version=\"1.1.0.1\" xmlns=\"http://schemas.microsoft.com/powershell/2004/04\"><S S=\"Error\">c:\\temp\\irbin\\Fastir_Collector-master_x0008_uild\\FastIR_x005F_x64.exe : Le terme ?_x000D__x000A_</S><S S=\"Error\">c:\\temp\\irbin\\Fastir_Collector-master_x0008_uild\\FastIR_x005F_x64.exe? n'est pas reconnu comme nom d'applet de commande, fonction, _x000D__x000A_</S><S S=\"Error\">fichier de script ou programme ex?cutable. V?rifiez l'orthographe du nom, ou si un chemin d'acc?s existe, v?rifiez que _x000D__x000A_</S><S S=\"Error\">le chemin d'acc?s est correct et r?essayez._x000D__x000A_</S><S S=\"Error\">Au caract?re Ligne:1 : 1_x000D__x000A_</S><S S=\"Error\">+ c:\\temp\\irbin\\Fastir_Collector-master_x0008_uild\\FastIR_x005F_x64.exe_x000D__x000A_</S><S S=\"Error\">+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~_x000D__x000A_</S><S S=\"Error\">    + CategoryInfo          : ObjectNotFound: (c:\\temp\\irbin\\F...\\FastIR_x005F_x64.exe:String) [], CommandNotFoundException_x000D__x000A_</S><S S=\"Error\">    + FullyQualifiedErrorId : CommandNotFoundException_x000D__x000A_</S><S S=\"Error\"> _x000D__x000A_</S></Objs>", "stdout": "", "stdout_lines": []}
```

Please note executable path is not the same as in yml file.
I check with vim 'set invlist' and don't see anomaly in source.
I have other commands which works fine.

**Comment by nitzmahone** [comment] 2015-12-01 22:22
@juju4: There have been some changes to the escaping code for 2.0. I've not been able to replicate this locally yet, but can you try changing to single-quotes and getting rid of the double backslashes to see if it makes a difference? eg:

```
raw: '{{ bin_path }}\Fastir_Collector-master\build\FastIR_x64.exe'
```

**Comment by juju4** [comment] 2015-12-01 23:20
nope

```
- name: Do FastIR check (64bits)
  raw: '{{ bin_path }}\Fastir_Collector-master\build\FastIR_x64.exe'
  when: not fastirout.stat.exists and ansible_architecture == '64 bits'
```

got

```
TASK [xxx : Do FastIR check (64bits)] *****************************
fatal: [192.168.2.109]: FAILED! => {"changed": false, "failed": true, "rc": 1, "stderr": "#< CLIXML\r\n<Objs Version=\"1.1.0.1\" xmlns=\"http://schemas.microsoft.com/powershell/2004/04\"><S S=\"Error\">c:\\temp\\irbin\\Fastir_Collector-master_x0008_uild\\FastIR_x005F_x64.exe : Le terme «_x000D__x000A_</S><S S=\"Error\">c:\\temp\\irbin\\Fastir_Collector-master_x0008_uild\\FastIR_x005F_x64.exe» n'est pas reconnu comme nom d'applet de commande, fonction, _x000D__x000A_</S><S S=\"Error\">fichier de script ou programme exécutable. Vérifiez l'orthographe du nom, ou si un chemin d'accès existe, vérifiez que _x000D__x000A_</S><S S=\"Error\">le chemin d'accès est correct et réessayez._x000D__x000A_</S><S S=\"Error\">Au caractère Ligne:1 : 1_x000D__x000A_</S><S S=\"Error\">+ c:\\temp\\irbin\\Fastir_Collector-master_x0008_uild\\FastIR_x005F_x64.exe_x000D__x000A_</S><S S=\"Error\">+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~_x000D__x000A_</S><S S=\"Error\">    + CategoryInfo          : ObjectNotFound: (c:\\temp\\irbin\\F...\\FastIR_x005F_x64.exe:String) [], CommandNotFoundException_x000D__x000A_</S><S S=\"Error\">    + FullyQualifiedErrorId : CommandNotFoundException_x000D__x000A_</S><S S=\"Error\"> _x000D__x000A_</S></Objs>", "stdout": "", "stdout_lines": []}

```

I really think it's encoding related as path {{ bin_path }}\Fastir_Collector-master\build\FastIR_x64.exe transforms into c:\temp\irbin\Fastir_Collector-master_x0008_uild\FastIR_x005F_x64.exe_x000D__x000A_
again, no invisible character seen with vim inside the role

**Comment by nitzmahone** [comment] 2015-12-01 23:24
Wouldn't surprise me. Thanks for trying the other way, that's a helpful data point. I'll get the alternate locales set up and see if I can reproduce that way.

**Comment by jimi-c** [comment] 2015-12-08 20:07
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-12-08 20:07 UTC
Labels: windows, bug

**Comment by abadger** [comment] 2015-12-08 20:11
Note we discovered this wasn't related to either windows or encodings.  It was a backslash escaping issue.  raw_params were having backslash_decoding run over them once too often.
