### ISSUE TITLE
Decrypt a file with a multiple vault id file fail when file was encrypted with a single vault id first

### ISSUE THREAD

**Issue by deepbluemussel** [ansible/ansible#72881] opened 2020-12-07 18:01 UTC
##### SUMMARY

After encrypting a file with a vault-id file, trying to decrypt it with a multiple vault id file that contains the id the encrypted the file fail.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible-vault --vault-id
##### ANSIBLE VERSION

```paste below
ansible 2.10.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ubuntu/.local/lib/python3.8/site-packages/ansible
  executable location = /home/ubuntu/.local/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

```

##### STEPS TO REPRODUCE

```bash
echo "db_pass: thepass" > creds_prod

echo "\
prod prodpass
dev devpass" > vault_multi

echo "prod prodpass" > vault_prod

ansible-vault encrypt --vault-id prod@vault_prod creds_prod
ansible-vault edit --vault-id prod@vault_multi creds_prod
```

##### EXPECTED RESULTS

As mentionned in [documentation](https://docs.ansible.com/ansible/latest/user_guide/vault.html#storing-passwords-in-files), I should be able to decrypt the file with the multiple vault id file that contains the id that encrypted the file first.

##### ACTUAL RESULTS

Error below. Ansible doesn't the file.

```paste below
ERROR! Decryption failed (no vault secrets were found that could decrypt) for /home/ubuntu/tests/playbooks/creds_prod
```

**Comment by sivel** [comment] 2020-12-07 18:08
Duplicate of https://github.com/ansible/ansible/issues/72230

That documentation is completely bogus, and doesn't actually represent any functionality in Ansible.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Closed as completed by sivel** 2020-12-07 18:08 UTC

**Comment by goldpanic** [comment] 2020-12-07 18:34
Should I look for an other way to work with multiple vault id file or just give up?

**Comment by sivel** [comment] 2020-12-07 18:37
You cannot put multiple vault IDs in a single file. You can only specify exactly 1 password per file, however you can provide multiple files via config or on the CLI.

See https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-vault-identity-list and the `--vault-id` CLI flag (which can be supplied multiple times).
