### ISSUE TITLE
python3.7 : RuntimeError: cannot release un-acquired lock

### ISSUE THREAD

**Issue by pgauret** [ansible/ansible#55729] opened 2019-04-24 19:08 UTC
##### SUMMARY
Running ansible 2.7 with python 3.7 repeatedly produces the following error for each task:
```
Exception ignored in: <function _releaseLock at 0x7f0141ec97b8>
Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/__init__.py", line 226, in _releaseLock
RuntimeError: cannot release un-acquired lock
Ignoring exception from logging atfork <_StderrHandler <stderr> (WARNING)> release method: cannot release un-acquired lock
```
Note: playbook execution continues successfully despite the error messages

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible

##### ANSIBLE VERSION

```
ansible 2.7.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3 (default, Apr 17 2019, 11:48:37) [GCC 8.3.0]
```

##### CONFIGURATION

```
ansible-config dump --only-changed returned empty content
```

##### OS / ENVIRONMENT

Alpine Linux Edge
Recently upgraded from python 3.6 to 3.7 which is when the error messages started appearing

##### STEPS TO REPRODUCE

Running any playbook repeatedly produces the error message. Execution continues and is successful.

##### EXPECTED RESULTS

Playbook should run as usual without python error messages

##### ACTUAL RESULTS

```
TASK [Gathering Facts] *************************************************************************************************************************************************************************************
task path: /etc/ansible/playbook.yml:42
<hass> THIS IS A LOCAL LXC DIR
<hass> EXEC ['/bin/sh', '-c', "/bin/sh -c 'echo ~root && sleep 0'"]
<hass> EXEC ['/bin/sh', '-c', '/bin/sh -c \'( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1556132749.736614-105305599181482 `" && echo ansible-tmp-1556132749.736614-105305599181482="` echo /root/.ansible/tmp/ansible-tmp-1556132749.736614-105305599181482 `" ) && sleep 0\'']
Using module file /usr/lib/python3.7/site-packages/ansible/modules/system/setup.py
<hass> PUT /root/.ansible/tmp/ansible-local-291838ok3cs9c/tmphb1g9s8t TO /root/.ansible/tmp/ansible-tmp-1556132749.736614-105305599181482/AnsiballZ_setup.py
Exception ignored in: <function _releaseLock at 0x7fd6c97dc7b8>
Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/__init__.py", line 226, in _releaseLock
RuntimeError: cannot release un-acquired lock
Ignoring exception from logging atfork <_StderrHandler <stderr> (WARNING)> release method: cannot release un-acquired lock
<hass> EXEC ['/bin/sh', '-c', "/bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1556132749.736614-105305599181482/ /root/.ansible/tmp/ansible-tmp-1556132749.736614-105305599181482/AnsiballZ_setup.py && sleep 0'"]
<hass> EXEC ['/bin/sh', '-c', "/bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1556132749.736614-105305599181482/AnsiballZ_setup.py && sleep 0'"]
<hass> EXEC ['/bin/sh', '-c', "/bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1556132749.736614-105305599181482/ > /dev/null 2>&1 && sleep 0'"]
ok: [hass]
META: ran handlers
```

**Comment by sivel** [comment] 2019-04-29 15:17
I've done a small amount of research, and this might be caused by a 3rd party dependency.

When researching the error I cam across https://github.com/unbit/uwsgi/issues/1978#issuecomment-471768261

It indicates C extensions not implementing the correct calls is misbehaving.

I notice from the output the string `THIS IS A LOCAL LXC DIR`, which indicates you are using the `lxc` connection plugin, which has a dependency on `python2-lxc`/`python3-lxc`.

Both of those bindings use a compile C extension, that may be misbehaving with Python3.7.

Can you confirm whether you are indeed using the `lxc` connection plugin, and whether or not this happens when connecting to a host via any other connection plugins?

needs_info

**Comment by pgauret** [comment] 2019-04-29 20:36
Indeed I am using the `lxc` connection plugin through `py3-lxc`. The issue does **not** happen when connecting to localhost.

On a somewhat related note, I was already having issues with Ansible when using `lxc`. 
https://github.com/ansible/ansible/issues/54659

I'll log an issue with https://github.com/lxc/python3-lxc , guess there's not much more to do on the Ansible side.

**Comment by sivel** [comment] 2019-07-25 18:41
Closing per above.

**Closed as completed by sivel** 2019-07-25 18:41 UTC
Labels: python3, support:core, bug, traceback, affects_2.7
