### ISSUE TITLE
Galaxy failing to download certain requirements despite being found on galaxy site

### ISSUE THREAD

**Issue by CafeLungo** [ansible/ansible#42212] opened 2018-07-02 20:23 UTC
##### SUMMARY
When running `ansible-galaxy install -r requirements.yml` from my main ansible project (been using without problem for several years), suddenly we are unable to download certain requirements. Upon searching on the galaxy site, though, the requirements are indeed present.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
todd-7signal-mbp:Deployment todd$ ansible-galaxy --version
ansible-galaxy 2.5.0
  config file = /Users/todd/Documents/workspace/github/Deployment/ansible.cfg
  configured module search path = [u'/Users/todd/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.5.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-galaxy
  python version = 2.7.14 (default, Mar 22 2018, 15:04:47) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION

```
todd-7signal-mbp:Deployment todd$ ansible-config dump --only-changed
ANSIBLE_PIPELINING(/Users/todd/Documents/workspace/github/Deployment/ansible.cfg) = True
ANSIBLE_SSH_RETRIES(/Users/todd/Documents/workspace/github/Deployment/ansible.cfg) = 3
DEFAULT_ROLES_PATH(/Users/todd/Documents/workspace/github/Deployment/ansible.cfg) = [u'/Users/todd/Documents/workspace/github/Deployment/.imported_roles', u'/Users/todd/Documents/wor
HOST_KEY_CHECKING(/Users/todd/Documents/workspace/github/Deployment/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Mac OS X And Ubuntu

##### STEPS TO REPRODUCE

The following requirements are currently giving me issues, but searching them on the galaxy site locates them, and shows they are current.
```yaml
# requirements.yml
- src: dev-sec.nginx-hardening
  version: 1.0.2

- src: andrewrothstein.java-oracle-jre
  version: v2.0.6
```
These requirements are unmodified and worked prior to today. I found that the `dev-sec` requirement will work if I rename it to `dev_sec`. It may have been renamed. But the andrewrothstein requirement fails no matter what I do. Seems like a strange coincidence that both are failing all of a sudden.

##### EXPECTED RESULTS

I expect them to download to my `.imported_roles` directory without error.

##### ACTUAL RESULTS

The two mentioned roles fail to download, where they previously did not.

```
# dev-sec.nginx-hardening role failure:
- downloading role 'nginx-hardening', owned by dev-sec
 [WARNING]: - dev-sec.nginx-hardening was NOT installed successfully: - sorry, dev-sec.nginx-hardening was not found on https://galaxy.ansible.com.
```
```
# andrewrothstein.java-oracle-jre role failure:
- downloading role 'java-oracle-jre', owned by andrewrothstein
- downloading role from https://github.com/andrewrothstein/ansible-java-oracle-jre/archive/v2.0.6.tar.gz
- extracting andrewrothstein.java-oracle-jre to /Users/todd/Documents/workspace/github/Deployment/.imported_roles/andrewrothstein.java-oracle-jre
- andrewrothstein.java-oracle-jre (v2.0.6) was installed successfully
- adding dependency: andrewrothstein.java-oracle (v1.0.7)
- downloading role 'java-oracle', owned by andrewrothstein
 [WARNING]: - andrewrothstein.java-oracle was NOT installed successfully: - sorry, andrewrothstein.java-oracle was not found on https://galaxy.ansible.com.
```

**Comment by CafeLungo** [comment] 2018-07-05 14:45
The `dev-sec` requirement seems to have "flipped" again, so now it needs to be defined as `dev-sec` instead of `dev_sec` now. The andrewrothstein role definition is still not working correctly, though.

**Comment by Akasurde** [comment] 2019-02-12 10:46
@CafeLungo I am not able to reproduce this - 
```
ansible-galaxy install -r requirements.yml
- downloading role 'nginx-hardening', owned by dev-sec
- downloading role from https://github.com/dev-sec/ansible-nginx-hardening/archive/1.0.2.tar.gz
- extracting dev-sec.nginx-hardening to /Users/akasurde/.ansible/roles/dev-sec.nginx-hardening
- dev-sec.nginx-hardening (1.0.2) was installed successfully
- downloading role 'java-oracle-jre', owned by andrewrothstein
- downloading role from https://github.com/andrewrothstein/ansible-java-oracle-jre/archive/v2.0.6.tar.gz
- extracting andrewrothstein.java-oracle-jre to /Users/akasurde/.ansible/roles/andrewrothstein.java-oracle-jre
- andrewrothstein.java-oracle-jre (v2.0.6) was installed successfully
- adding dependency: andrewrothstein.java-oracle (v1.0.7)
- downloading role 'java-oracle', owned by andrewrothstein
- downloading role from https://github.com/andrewrothstein/ansible-java-oracle/archive/v1.0.7.tar.gz
- extracting andrewrothstein.java-oracle to /Users/akasurde/.ansible/roles/andrewrothstein.java-oracle
- andrewrothstein.java-oracle (v1.0.7) was installed successfully
- adding dependency: andrewrothstein.unarchive-deps (v1.0.9)
- adding dependency: andrewrothstein.alpine-glibc-shim (v2.0.5)
- downloading role 'unarchive-deps', owned by andrewrothstein
- downloading role from https://github.com/andrewrothstein/ansible-unarchive-deps/archive/v1.0.9.tar.gz
- extracting andrewrothstein.unarchive-deps to /Users/akasurde/.ansible/roles/andrewrothstein.unarchive-deps
- andrewrothstein.unarchive-deps (v1.0.9) was installed successfully
- downloading role 'alpine-glibc-shim', owned by andrewrothstein
- downloading role from https://github.com/andrewrothstein/ansible-alpine-glibc-shim/archive/v2.0.5.tar.gz
- extracting andrewrothstein.alpine-glibc-shim to /Users/akasurde/.ansible/roles/andrewrothstein.alpine-glibc-shim
- andrewrothstein.alpine-glibc-shim (v2.0.5) was installed successfully
```

**Comment by samdoran** [comment] 2020-07-10 15:53
Closing per above. The name changed to use an underscore rather than a dash.

**Closed as completed by samdoran** 2020-07-10 15:53 UTC
Labels: support:core, affects_2.5, bug
