### ISSUE TITLE
task not considered changed with changed_when set to rc != 0 and ignore_errors: true

### ISSUE THREAD

**Issue by ari-s** [ansible/ansible#14877] opened 2016-03-09 08:13 UTC
##### Issue Type:

- Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### Summary:

for a task that has changed_when set to program failure ansible does not consider the task changed. As a consequence handlers are not being run.
this bug is introduced somewhere between 1.7.2 and 2.0.1.0, but most probably with ansible 2
##### Steps To Reproduce:

Consider this playbook

```

---
- name: test
  hosts: playground.ccczh.ch
  tasks:
  - name: test
    shell: "false"
    notify: barbaz
    register: test
    changed_when: "test.rc == 1"
    # failed_when: "test.rc == 0"
    ignore_errors: true
  handlers:
  - name: barbaz
    shell: echo foo
<!--- Paste example playbooks or commands here -->
```

ansible 1.7.4. notifies the barbaz-handler:

```
TASK: [test] ****************************************************************** 
failed: [playground.ccczh.ch] => {"changed": true, "cmd": "false", "delta": "0:00:00.003002", "end": "2016-03-09 08:41:22.027993", "rc": 1, "start": "2016-03-09 08:41:22.024991", "stdout_lines": []}
...ignoring

NOTIFIED: [barbaz] ************************************************************ 
changed: [playground.ccczh.ch]

PLAY RECAP ******************************************************************** 
playground.ccczh.ch        : ok=3    changed=2    unreachable=0    failed=0   
```

while ansible 2.0.1.0 does not, does not count the task as changed, but also not as failed: 

```
TASK [test] ********************************************************************
fatal: [playground.ccczh.ch]: FAILED! => {"changed": true, "cmd": "false", "delta": "0:00:00.002459", "end": "2016-03-09 08:41:56.485175", "failed": true, "rc": 1, "start": "2016-03-09 08:41:56.482716", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}
...ignoring

PLAY RECAP *********************************************************************
playground.ccczh.ch        : ok=2    changed=0    unreachable=0    failed=0   
```

with the commented failed_when key ansible 2 considers this task changed.

from the yml I really expect this to be what 1.7.4 does, I mean, the command returns the value that is specified in changed_when and ignore_errors makes it not count as failed.

**Comment by dagwieers** [comment] 2016-03-09 16:56
Summary: task handler does not run when task fails when ignore_errors: true

| Version | v1.9.4 | v2.0.1.0 |
| --- | --- | --- |
| changed | true | true |
| failed | N/A | true |
| notification? | yes | no |
| failure count | 0 | 0 |

The fact that on v2.0.1.0 failed tasks (with ignore_errors) return as failed is actually a bugfix. The task did fail, and the wish to ignore it doesn't change the fact that it did fail.

The fact that the failure doesn't count in the summary, is because we explicitly asked it to be ignored. So ignoring an error (ie. failure) does not increase the failure-count. This is intentional (and has not changed between v1.9.4 and v2.0.1.0).

The fact that the handler was run in v1.9.4, and not in v2.0.1.0 might be a regression. I don't know if there was a deliberate change to the behaviour in this. It is likely that this is the result of leaving the task flagged as failed.

**Comment by jimi-c** [comment] 2016-03-17 20:00
As the task is marked as failed (but ignored), we don't fire the notify. I'd almost say this was a bug in 1.x instead.

**Comment by jimi-c** [comment] 2016-03-17 20:05
After a quick internal discussion, we agree that the behavior in 1.x was a bad side-effect, as the task is marked as failed (even if it was also marked as changed), so no notification should have been triggered. Per your own discovery, the correct syntax for this is to use the combination of changed_when/failed_when you have.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed** 2016-03-17 20:06 UTC
Labels: bug
