### ISSUE TITLE
Creating a templated file on vagrant shared folders fails

### ISSUE THREAD

**Issue by timbuchwaldt** [ansible/ansible#10297] opened 2015-02-19 19:53 UTC
### Issue Type:

Bug Report
### Ansible Version:

ansible 1.8.2
### Environment:
- OS X 10.10.2
- VMWare Fusion Professional 7.1.1
- Vagrant 1.7.2
- vagrant-vmware-fusion (3.2.3)
### Summary:

When running a template-task on a vagrant shared folder, the playbook-run is stopped with the error 

```
failed: [default] => {"failed": true, "parsed": false}
SUDO-SUCCESS-fkqfzpqnukvypcybwjzcuueirjhhaorz
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1424374956.05-84759286783521/copy", line 1824, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1424374956.05-84759286783521/copy", line 238, in main
    module.atomic_move(src, dest)
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1424374956.05-84759286783521/copy", line 1624, in atomic_move
    os.chown(dest, os.getuid(), os.getgid())
OSError: [Errno 1] Operation not permitted: '/vagrant/test.conf'
Exception OSError: (2, 'No such file or directory', '/vagrant/.ansible_tmpPHJWkgtest.conf') in <bound method _TemporaryFileWrapper.__del__ of <closed file '<fdopen>', mode 'w+b' at 0x7fc206235270>> ignored
```

The file is generated and on subsequent runs (also when changing it) no error occurs. I created a sample repository that showcases the error by erasing the file after creating it, so every `vagrant provision` run leads to the error.
### Steps To Reproduce:
1. Clone my sample repo https://github.com/timbuchwaldt/vagrant-ansible-bug
2. Run `vagrant up`
### Expected Results:

The file is created without an error
### Actual Results:

```
failed: [default] => {"failed": true, "parsed": false}
SUDO-SUCCESS-fkqfzpqnukvypcybwjzcuueirjhhaorz
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1424374956.05-84759286783521/copy", line 1824, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1424374956.05-84759286783521/copy", line 238, in main
    module.atomic_move(src, dest)
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1424374956.05-84759286783521/copy", line 1624, in atomic_move
    os.chown(dest, os.getuid(), os.getgid())
OSError: [Errno 1] Operation not permitted: '/vagrant/test.conf'
Exception OSError: (2, 'No such file or directory', '/vagrant/.ansible_tmpPHJWkgtest.conf') in <bound method _TemporaryFileWrapper.__del__ of <closed file '<fdopen>', mode 'w+b' at 0x7fc206235270>> ignored
```

**Comment by bcoca** [comment] 2015-02-19 19:56
this is duplicate of issue #9526, this is caused by the VM underlying vagrant's shared folders not implementing correct file system semantics, we are looking at ways around this

**Closed as completed by bcoca** 2015-02-19 19:56 UTC
Labels: bug
