### ISSUE TITLE
pkg_resources.DistributionNotFound

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#10038] opened 2015-01-18 16:08 UTC
Related to: #8575 and #7219 

Issue Type:
Bug Report

Ansible Version:

```
root@localhost:/sovereign# dpkg -l ansible
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-=============================================
ii  ansible        1.7.2+dfsg-1 all          Configuration management, deploym
```

Environment:

```
Linux localhost.localdomain 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

it's on a kvm vps

Summary:
Ansible does not load dependencies properly?

Steps To Reproduce:
Run ansible-playbook

Expected Results:
Ansible works.

Actual Results:

root@localhost:/sovereign# ansible-playbook -i ./hosts site.yml 
Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 4, in <module>
    import pkg_resources
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: ecdsa>=0.11

**Comment by sivel** [comment] 2015-01-18 16:28
I believe, based on a comment in another ticket, that you haven't provided full reproduction steps.

```
similar error here, installed from ubuntu
apt-get after failing with source code
installation at the pip stage
```

If you install via pip/source first, and then apt-get, I would likely expect this to happen.

You should likely pip uninstall first, before installing via apt-get, as some files may be placed in different locations between the 2 installation methods.

**Comment by ghost** [comment] 2015-01-18 17:24
@sivel didn't install from pip/source, followed source instructions on ansible website(encountered an error at the pip step). How would I uninstall via pip then?
Full reproduction steps(ansible-playbook -i ./hosts site.yml) were in the actual results section.

**Comment by ghost** [comment] 2015-01-18 17:24
@sivel do you think a make uninstall would work? If it makes a difference, I was following https://github.com/al3x/sovereign

**Comment by abadger** [comment] 2015-01-19 19:49
Which version of ubuntu?  Which version of python-ecdsa is installed (or none?)

**Comment by abadger** [comment] 2015-01-19 20:04
Ah another thought -- are you sure that paramiko and ecdsa are installed from your OS?  Someone earlier was having an issue where paramiko had been installed via pip for an unrelated package.  paramiko added the requirement for ecdsa which was not satisfied by the OS packaging.  This lead to the error when invoking ansible.  Things to check:
- is the Ubuntu python-paramiko package installed?
- is the Ubuntu python-ecdsa package installed?
- Do all of the files of the python-paramiko package match what came from the package?
- Do all of the files of the python-ecdsa package match what came from the pacakge?
- Do the *egg-info files for python-paramiko specify the dependency on ecdsa?  What version?
- Does the *egg-info files for python-ecdsa exist and match the version needed for python-paramiko?
- Are there any other egg-info files for python-ecdsa or python-paramiko?  Like under /usr/local/ or ~/.local/lib ?
  (The egg-info probably lives somewhere like /usr/lib/python2.7/dist-packages/paramiko-_egg_/ and similar for the other directory structures.  If the egg-info is a directory the requirements are in a requires.txt file.  If it's a file then there will be a field in the file that specifies the requirements.  The version of the package itself (as the egg metadata reports it) is part of the egginfo filename.)

**Comment by abadger** [comment] 2015-01-26 17:19
Without more information I'll be unable to diagnose this further.  When I've seen this in the past, it was due to having mismatched versions of paramiko and ecdsa installed on the system (so that when ansible loads it finds the requirement for paramiko, then the requirement for paramiko finds the wrong version of ecdsa and causes everything to fail).  That or something similar is likely what's going on here as well.

# Cannot Reproduce

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us. 

Testing this on the version you have specified, we cannot reproduce this problem.

Our reasons and evidence for this are:
- ansible runs fine locally on Ubuntu14.04 and 12.04

And we suggest that:
- Look into whether you have ecdsa_egg_ files or directories that are for a version < 0.11 on your system.  Chances are good that setuptools is finding that metadata instead of metadata for the needed version of ecdsa ( ecdsa >= 0.11)

As such, we are most likely going to close this ticket.  Should you disagree with this conclusion, you may also wish to join our mailing lists, which are very active:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Closed as completed by abadger** 2015-01-26 17:19 UTC
Labels: needs_info, P2, bug
