### ISSUE TITLE
support multiple hosts on different ports

### ISSUE THREAD

**Issue by lcosmin** [ansible/ansible#399] opened 2012-05-16 12:51 UTC
As requested [here](https://groups.google.com/forum/#!topic/ansible-project/fDMQhGuSt9A) I'm filing a bug report for the following test case:

```
$ cat hosts

---
- group: all
  hosts:
  - host: 10.120.137.188:23000
  - host: 10.120.137.188:23001
$ ansible all -i ./hosts -m shell -a uptime
10.120.137.188:23000 | FAILED => FAILED: [Errno -2] Name or service not known
10.120.137.188:23001 | FAILED => FAILED: [Errno -2] Name or service not known
```

**Comment by mpdehaan** [comment] 2012-05-16 12:53
YAML inventory needs to recognize the colon in the hostname and assume is a port like the INI format one does

**Comment by mpdehaan** [comment] 2012-05-16 12:53
lcosmin -- try the INI format

**Comment by lcosmin** [comment] 2012-05-16 20:25
```
$ cat hosts
[all]
10.120.137.188:23000
10.120.137.188:23001
$ ansible all -i ./hosts -m shell -a uptime
10.120.137.188 | success | rc=0 >>
22:23:26 up 1 day, 12:46,  1 user,  load average: 0.05, 0.05, 0.05
$
```

As you can see, only 1 answer instead of 2.

**Comment by mpdehaan** [comment] 2012-05-16 21:48
duplicate of #395

**Comment by mpdehaan** [comment] 2012-05-16 21:49
actually I take that back, but it's because the hosts are keyed by name, true, it's valid regardless

**Comment by mpdehaan** [comment] 2012-05-27 17:55
It seems the proper fix for this is "if the host name is referenced with port notation, the name of the host object should include the part with the colon in it".

Seems like an easy patch to either the yaml/ini parser code or hosts.py.

**Comment by lcosmin** [comment] 2012-05-28 06:34
I tried to fix this in 0.3 by handling hosts using a (host, port) tuple instead of a string, but the changes were too big. If I have enough time I'll look at 0.5, maybe I can fix something there.

**Comment by lcosmin** [comment] 2012-07-10 06:36
Wrote an email about this, here:

https://groups.google.com/forum/#!topic/ansible-project/vfNqyuiLvQg

**Comment by mpdehaan** [comment] 2012-07-12 00:46
Isn't this resolveable now by putting the actual hostnames in there and configuring SSH such that it knows which jumphosts to use?

I think it may be.

**Closed as completed by mpdehaan** 2012-07-12 00:46 UTC

**Comment by wricardo** [comment] 2015-02-12 22:50
I'm having this same issue. I have the same ip with different ports on the same group and it runs on only one of them.
