### ISSUE TITLE
hostvars[inventory_name] no longer displays variables from group_vars

### ISSUE THREAD

**Issue by slmingol** [ansible/ansible#16721] opened 2016-07-15 15:44 UTC
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 8a55a446bf) last updated 2016/06/22 22:59:59 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 4fe583e29b) last updated 2016/06/22 23:00:06 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 709114d55f) last updated 2016/06/22 23:00:06 (GMT -400)
  config file =
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

OSX 10.11.5
##### SUMMARY

In previous versions of ansible I could get a list of all the variables set in the group_var using `hostvars[inventory_hostname]`, this no longer works.
##### STEPS TO REPRODUCE

```
$ ansible -i inv/hosts host1 -m debug -a "var=hostvars[inventory_hostname]"
```

##### EXPECTED RESULTS

...
      "clustertype": "cdh",
        "crt_file": "/etc/haproxy/haproxy.crt",
        "csr_file": "/etc/haproxy/haproxy.csr",
        "dns_forwarder_ip1": "153.65.2.111",
        "dns_forwarder_ip2": "153.65.2.12",
        "ds_lb_server_port": 80,
...
##### ACTUAL RESULTS

```
    "hostvars[inventory_hostname]": {
        "ansible_check_mode": false,
        "ansible_version": {
            "full": "2.2.0",
            "major": 2,
            "minor": 2,
            "revision": 0,
            "string": "2.2.0"
        },
        "group_names": [
            "app-servers",
            "as-servers",
            "bamboo-targets",
            "elasticsearch-nfs",
            "elasticsearch-servers",
            "krb5-clients",
...
...
        "omit": "__omit_place_holder__f43ed14a91ac616c5b88da8bbed37fc5a1d7a6bd",
        "playbook_dir": "."
    }
}
```

**Comment by bcoca** [comment] 2016-07-15 15:47
I just tested and I DO get group_vars, can you give more details?

**Comment by slmingol** [comment] 2016-07-15 15:49
@bcoca - I don't get any of my custom variables that I set in either all.yml or a group file in group_vars. When I reverted to ansible stable 2.0 I got the expected output.

```
"clustertype": "cdh",
"crt_file": "/etc/haproxy/haproxy.crt",
"csr_file": "/etc/haproxy/haproxy.csr",
"dns_forwarder_ip1": "153.65.2.111",
"dns_forwarder_ip2": "153.65.2.12",
"ds_lb_server_port": 80,
```

The above are set in a group file in group_vars and I don't see them since upgrading to 2.2.0 when I run the ansible ... hostvars[inventory_name] command.

**Comment by bcoca** [comment] 2016-07-15 15:52
i have these set in group_vars/all:

```
        "test2": {
            "key1": "valueall1",
            "key3": "valueall3"
        },
```

and they show in all versions.

**Comment by slmingol** [comment] 2016-07-15 17:37
Here's an isolated example that shows the same problem.

```
$ ansible -i inv/host dev01-ost-env-h-app01 -m debug -a "var=hostvars[inventory_hostname]"
dev01-ost-env-h-app01 | SUCCESS => {
    "hostvars[inventory_hostname]": {
        "ansible_check_mode": false,
        "ansible_version": {
            "full": "2.2.0",
            "major": 2,
            "minor": 2,
            "revision": 0,
            "string": "2.2.0"
        },
        "group_names": [
            "app-servers",
            "as-servers",
            "bamboo-targets",
            "dev01-ost-env-h",
            "ds-lb-server",
            "ds-servers",
            "elasticsearch-nfs",
            "elasticsearch-servers",
            "krb5-clients",
            "lb-servers",
            "ls-servers",
            "ns-servers",
            "redis-servers",
            "rtim-cluster",
            "rtim-nfs",
            "ss-servers",
            "tomcat-servers",
            "was-servers"
        ],
        "groups": {
            "all": [
                "dev01-ost-env-h-app01",
                "dev01-ost-env-h-hb01"
            ],
            "app-servers": [
                "dev01-ost-env-h-app01"
            ],
            "as-servers": [
                "dev01-ost-env-h-app01"
            ],
            "bamboo-targets": [
                "dev01-ost-env-h-app01"
            ],
            "dev01-ost-env-h": [
                "dev01-ost-env-h-app01",
                "dev01-ost-env-h-hb01"
            ],
            "ds-lb-server": [
                "dev01-ost-env-h-app01"
            ],
            "ds-servers": [
                "dev01-ost-env-h-app01"
            ],
            "elasticsearch-nfs": [
                "dev01-ost-env-h-app01"
            ],
            "elasticsearch-servers": [
                "dev01-ost-env-h-app01"
            ],
            "hbase-clients": [
                "dev01-ost-env-h-hb01"
            ],
            "hbase-master": [
                "dev01-ost-env-h-hb01"
            ],
            "hbase-nodes": [
                "dev01-ost-env-h-hb01"
            ],
            "ipaservers": [],
            "krb5-clients": [
                "dev01-ost-env-h-app01"
            ],
            "lb-servers": [
                "dev01-ost-env-h-app01"
            ],
            "ls-servers": [
                "dev01-ost-env-h-app01"
            ],
            "ns-servers": [
                "dev01-ost-env-h-app01"
            ],
            "redis-servers": [
                "dev01-ost-env-h-app01"
            ],
            "rtim-cluster": [
                "dev01-ost-env-h-app01",
                "dev01-ost-env-h-hb01"
            ],
            "rtim-nfs": [
                "dev01-ost-env-h-app01"
            ],
            "ss-servers": [
                "dev01-ost-env-h-app01"
            ],
            "tomcat-servers": [
                "dev01-ost-env-h-app01"
            ],
            "ungrouped": [
                "localhost"
            ],
            "was-servers": [
                "dev01-ost-env-h-app01"
            ]
        },
        "inventory_dir": "/Users/sammingolelli/ans-tst/inv",
        "inventory_file": "inv/hosts_dev01-ost-env-h",
        "inventory_hostname": "dev01-ost-env-h-app01",
        "inventory_hostname_short": "dev01-ost-env-h-app01",
        "omit": "__omit_place_holder__336cc808b2959ba3468f17e4a3b70a5419b1e9a3",
        "playbook_dir": "."
    }
}
```

Contents of my group_var/all file:

```
$ more group_vars/all
testvar1: value1
testvar2: value2
testvar3: value3
testvar4: value4
```

**Comment by bcoca** [comment] 2016-07-23 21:28
where is group_vars/ located? by inventory or by play?

**Comment by slmingol** [comment] 2016-07-23 22:26
My directory tree is as follows:

```
$ tree -d -L 1
.
├── ansible
├── bb
├── cfg_reports
├── group_vars
├── inv
├── modules
├── notes
├── roles
├── scripts
└── templates

10 directories
```

I always run my playbooks from this top level directory like so:

```
ansible-playbook -i inv/<some hosts file> <playbook.yml>
```

**Comment by resmo** [comment] 2016-07-24 06:59
I could not reproduce with v2.1 and devel.

**Comment by slmingol** [comment] 2016-07-24 12:01
My issue shows up on v2.1 & devel, if I drop back to v2.0 hostvars[inventory_name] works as expected.

**Comment by slmingol** [comment] 2016-07-24 12:07
If I create a actual playbook like this:

```
- name: Display ansible variables
  hosts: all
  become: yes

  tasks:
    - name: debug test - hostvars
      debug: var=hostvars[inventory_hostname]
```

And run it like so I see hostvars[inventory_name]:

```
$ ansible-playbook -i inv/hosts ansible_debug_vars.yml -l some_server
```

**Comment by bcoca** [comment] 2016-07-24 23:58
So i don't see group_vars adjacent to inventories or plays, if i read your tree correctly these are all on a 'upper' directory. 

You might have been relying on a bug in 2.0 that loaded group_vars from cwd (current working directory), this was never intended and not good to depend on (run ansible from /tmp?).

**Comment by slmingol** [comment] 2016-07-25 03:23
I have my inventories in `inv/` which is at  the same level as `roles/` and `group_vars/`. I keep all the .yml playbooks at this level as well. Here's a more detailed example of what I have:

```
$ tree ...
.
├── common.yml
├── create_admin_accounts.yml
├── data_hosts.yml
├── datadog.yml
├── dc-apache.yml
├── dc-haproxies.yml
├── dc-ntp.yml
├── group_vars
├── inv
├── modules
├── roles
└── templates
```

My directory structure is consistent with the best practices here: http://docs.ansible.com/ansible/playbooks_best_practices.html#directory-layout.

**Comment by jinnko** [comment] 2016-08-06 09:47
I think this is the same problem as in #16956

**Comment by caseylucas** [comment] 2016-08-08 13:59
@bcoca Can you provide any more information (bug num perhaps) about the `bug in 2.0 that loaded group_vars from cwd`?

**Comment by zigarn** [comment] 2016-08-11 16:13
A very simple reproduction of the problem:

``` yaml
# playbook.yml
- hosts: all
  tasks:
    - debug: var=key
    - debug: var=hostvars[inventory_hostname].key|default('NOT FOUND')
```

``` ini
# hosts
[test]
localhost ansible_connection=local
```

``` yaml
# group_vars/test.yml
key: test
```

Actual result (2.1.1.0):

``` bash
$ ansible --version
ansible 2.1.1.0
  config file =
  configured module search path = Default w/o overrides

$ ansible-playbook -i hosts playbook.yml

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "key": "test"
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "hostvars[inventory_hostname].key|default('NOT FOUND')": "NOT FOUND"
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0
```

Expected result (2.1.0.0):

``` bash
$ ansible --version
ansible 2.1.0.0
  config file =
  configured module search path = Default w/o overrides

$ ansible-playbook -i hosts playbook.yml

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "key": "test"
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "hostvars[inventory_hostname].key|default('NOT FOUND')": "test"
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0
```

Even weirder if you set a `all.yml`:

``` yaml
# group_vars/all.yml
key: value
```

``` bash
$ ansible --version
ansible 2.1.1.0
  config file =
  configured module search path = Default w/o overrides

$ ansible-playbook -i hosts playbook.yml

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "key": "test"
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "hostvars[inventory_hostname].key|default('NOT FOUND')": "value"
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0
```

``` bash
$ ansible --version
ansible 2.1.0.0
  config file =
  configured module search path = Default w/o overrides

$ ansible-playbook -i hosts playbook.yml

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "key": "test"
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "hostvars[inventory_hostname].key|default('NOT FOUND')": "test"
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0
```

**Comment by zigarn** [comment] 2016-08-17 09:33
Looks like the problem I present was introduced by commit c9b125d2.
This commit c9b125d2 is a cherry-pick of b51d0dd6 which also introduced the problem but was fixed by commit f7570f1d (PR #16900 fixing #16886, #16882 and #16898). This commit is only in devel for now.

The problem only applies to hosts named `localhost`, if I change the `hosts` file to:

``` ini
# hosts
[test]
localhost ansible_connection=local
not_localhost ansible_ssh_host=localhost ansible_connection=local
```

The result is:

``` bash
$ ansible-playbook -i hosts playbook.yml

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [localhost]
ok: [not_localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "inventory_hostname|type": "<type 'unicode'>"
}
ok: [not_localhost] => {
    "inventory_hostname|type": "<type 'unicode'>"
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "inventory_hostname": "localhost"
}
ok: [not_localhost] => {
    "inventory_hostname": "not_localhost"
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "key": "test"
}
ok: [not_localhost] => {
    "key": "test"
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "hostvars[inventory_hostname].key|default('NOT FOUND')": "NOT FOUND"
}
ok: [not_localhost] => {
    "hostvars[inventory_hostname].key|default('NOT FOUND')": "test"
}

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=0
not_localhost              : ok=5    changed=0    unreachable=0    failed=0
```

**Comment by bcoca** [comment] 2016-08-17 14:03
OK, that narrows it down, this is 'localhost' related, my tests were using other hosts as this problem was described as more generic so I missed the reproduction. 

Since this is already fixed in devel and pushed to stable-2.1 for a possible 2.1.2 release I'm going to close this ticket at this point.

**Closed as completed by bcoca** 2016-08-17 14:03 UTC
Labels: bug

**Comment by slmingol** [comment] 2016-08-17 16:53
@bcoca - my testing was not using localhost, I was running my playbooks against actual hosts.

**Comment by zigarn** [comment] 2016-08-18 07:39
@bcoca: I may have think too quickly that my problem was like this one as the description was the same but the context wasn't (localhost vs other host).
@slmingol: I think @bcoca is right about your layout, in the best practices inventory files are directly at the top level directory but yours are in the 'inv' subfolder. So it looks like issue #16956 about cwd and group_vars (@caseylucas)

**Comment by slmingol** [comment] 2016-08-19 01:37
@zigarn: Makes no difference if I have my inventories in a subdirectory or at the top level, in either case the behavior I'm seeing is consistent. I tried that early on when @bcoca mentioned it and saw no difference in behavior.

**Comment by qubusp** [comment] 2017-06-12 09:44
Same issue here:
`- name: get ip address node1
  debug: var=hostvars[LOG1]['ansible_default_ipv4']['address']
  register: es_node1`

The result being: 

`{
    "hostvars[LOG1]['ansible_default_ipv4']['address']": "VARIABLE IS NOT DEFINED!"
}`
