### ISSUE TITLE
delegate_to not working correctly in 2.0.0 devel - HAProxy tasks fail

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible#12527] opened 2015-09-26 02:45 UTC
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible 2.0.0 (devel b757798f3e) last updated 2015/09/25 21:12:40 (GMT -500)
##### Ansible Configuration:

Defaults.
##### Environment:

Mac OS X 10.10.4
##### Summary:

This might be related to https://github.com/ansible/ansible/issues/12499, but basically, if I run a particular task with delegate_to and Ansible 2.0.0 devel, the task fails.

If I run the same task standalone in its own playbook, directly on the host (just removing `delegate_to`), it succeeds. If I run the same playbook with the failing task in Ansible <= 1.9.3, it succeeds. Only Ansible 2.0.0 devel is failing.

You can quickly emulate the entire environment and see the problem using the [deployments-balancer](https://github.com/geerlingguy/ansible-for-devops/tree/master/deployments-balancer) example (it's the exact playbook I'm running, using a set of three VirtualBox VMs configured via the Vagrantfile).
##### Steps To Reproduce:

Set up an HAProxy server and at least one server managed by HAProxy as a load balancer (note: this seems like it may be an issue that would affect other delegated tasks, but I've only done testing with HAProxy sockets so far).

Set up a playbook to run on an app server (that's _not_ the HAProxy host), with a task using the `haproxy` module to manage HAProxy on a delegated host:

``` yaml

---
- hosts: app
  sudo: yes

  tasks:
    - name: Disable the backend server in HAProxy.
      haproxy:
        state: disabled
        host: 192.168.4.3
        socket: /var/lib/haproxy/stats
        backend: habackend
      delegate_to: 192.168.4.2
```

Run this playbook.
##### Expected Results:

The playbook should indicate a change occurred, delegated to the HAProxy balancer:

```
TASK: [Disable the backend server in HAProxy.] ******************************** 
changed: [192.168.4.3 -> 192.168.4.2]
```

(This is the output from Ansible 1.9.3).
##### Actual Results:

The playbook errors out, with:

```
TASK [Disable the backend server in HAProxy.] **********************************
fatal: [192.168.4.3 -> 192.168.4.2]: FAILED! => {"changed": false, "failed": true, "msg": "Traceback (most recent call last):\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1443233601.59-214579071947909/haproxy\", line 2074, in <module>\r\n    main()\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1443233601.59-214579071947909/haproxy\", line 316, in main\r\n    ansible_haproxy.act()\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1443233601.59-214579071947909/haproxy\", line 287, in act\r\n    self.disabled(self.host, self.backend, self.shutdown_sessions)\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1443233601.59-214579071947909/haproxy\", line 273, in disabled\r\n    self.execute(cmd)\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1443233601.59-214579071947909/haproxy\", line 172, in execute\r\n    self.client.connect(self.socket)\r\n  File \"/usr/lib/python2.7/socket.py\", line 224, in meth\r\n    return getattr(self._sock,name)(*args)\r\nsocket.error: [Errno 2] No such file or directory\r\n", "parsed": false}
```

If I take the exact same task, and put it in a playbook on its own, and run that playbook directly on the balancer HAProxy server in Ansible 2.0.0 devel (without using delgate_to, basically), everything works fine:

``` yaml

---
- hosts: balancer
  sudo: yes

  tasks:
    - name: Disable the backend server in HAProxy.
      haproxy:
        state: enabled
        host: '192.168.4.3'
        socket: /var/lib/haproxy/stats
        backend: habackend
```

**Comment by jimi-c** [comment] 2015-09-26 12:36
@geerlingguy does this work before the commit that fixed #12499?

**Comment by geerlingguy** [comment] 2015-09-26 13:39
@jimi-c - it didn't work before then, either, AFAICT. Before that commit I was only getting the warning mentioned in #12499 — the fix might not be related to this bug, I was just adding context. Probably could've been more clear in my wording.

**Comment by jimi-c** [comment] 2015-09-26 15:32
@geerlingguy no problem, just wanted to make sure that that commit didn't break something else.

**Comment by jimi-c** [comment] 2015-09-30 13:29
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-09-30 13:29 UTC
Labels: P2, bug

**Comment by geerlingguy** [comment] 2015-09-30 14:46
Looks good; everything works fine, and I get the warning (which makes sense):

```
[WARNING]: no remote address found for delegated host 192.168.4.2, using its name by default
```

**Comment by jimi-c** [comment] 2015-09-30 15:21
Yeah, I threw that in there as a "just in case". Normally it will be caused by what you have in your inventory (people using IP's as inventory names), though the JIK was for those times when it might need to fallback to DNS.
