### ISSUE TITLE
Role dependencies don't maintain execution order specified

### ISSUE THREAD

**Issue by ivanshaovchev** [ansible/ansible#9294] opened 2014-10-08 16:03 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.2
##### Environment:

Centos 6
##### Summary:

Role dependencies don't maintain execution order specified and execute alphabetically. 
##### Steps To Reproduce:

```
playbook.yml 
roles:
  - {role: myrole, tags: ["mytag"]}

roles/myrole/tasks/main.yml
- name: Install Stuff
  ...
roles/myrole/meta/main.yml
dependencies:
  - {role: b}
  - {role: a}
```

Role `a` will be executed before role `b` in the above example. 
##### Expected Results:

Role dependencies to maintain the order specified.
##### Actual Results:

Executed alphabetically.

**Comment by jimi-c** [comment] 2014-10-08 18:28
Hi @ivanshaovchev, using your example I am unable to reproduce this in either v1.7.2 or devel. Here is my output from the `version1.7.2` branch:

<pre>
# ansible --version
ansible 1.7.2
# ansible-playbook -vv playbook.yml 
PLAY [localhost] ************************************************************** 
TASK: [dep_b | debug msg="in deb_b"] ****************************************** 
ok: [127.0.0.1] => {
    "msg": "in deb_b"
}
TASK: [dep_a | debug msg="in dep_a"] ****************************************** 
ok: [127.0.0.1] => {
    "msg": "in dep_a"
}
TASK: [parent | debug msg="in parent role"] *********************************** 
ok: [127.0.0.1] => {
    "msg": "in parent role"
}
PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=3    changed=0    unreachable=0    failed=0   
</pre>

Could you please include a gist of a more complete playbook that replicates this issue for you?

**Comment by ivanshaovchev** [comment] 2014-10-09 14:32
I think this problem is the same or stems from the one I reported here https://github.com/ansible/ansible/issues/9292 Depending on the order I list roles with tags and then depending on which tag is matched down the list and which dependency is in which role some messy unpredictable behaviour is triggered. I get all sorts of execution order combinations depending on how I list the roles in the playbook.yml file.

**Comment by jimi-c** [comment] 2014-10-22 16:58
@ivanshaovchev I believe this would be expected, if you're limiting the execution to tags. If a role was previously run, it won't be run again unless you specifically allow it to be via the `meta/main.yml` configuration file (`allow_duplicates: yes`). Regardless, the execution is still linear through the list of roles (where dependencies are run first).

We will hold the other issue open, but we are going to go ahead and close this. If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2014-10-22 16:58 UTC
Labels: needs_info, P1, bug
