### ISSUE TITLE
Incomplete deprecation warning: The comma separated role spec format, use the yaml/explicit format instead.

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible#14663] opened 2016-02-25 16:24 UTC
It seems that the deprecation warning `The comma separated role spec format, use the yaml/explicit format instead.` does not provide any information regarding how the new-desired format is supposed to look.  It does not include any link or example of correct usage, causing big confusions.

Also, it seems that the entire documentation regarding roles does not contain any example of the new format either. 

http://docs.ansible.com/ansible/playbooks_roles.html#role-dependencies

**Comment by dagwieers** [comment] 2016-02-26 15:37
Can you please share the play that gives you this error ?

**Comment by dixhuit** [comment] 2016-02-28 14:28
I'm also pretty confused about this warning. You can see it in context [here (line 46 of build log)](https://travis-ci.org/danbohea/mac-playbook/builds/112403217).

**Comment by sivel** [comment] 2016-02-28 16:05
This is likely the same as https://github.com/ansible/ansible/pull/14612

**Comment by sivel** [comment] 2016-02-28 16:07
Closing as a dupe of https://github.com/ansible/ansible/pull/14612

**Closed as completed by sivel** 2016-02-28 16:07 UTC
