### ISSUE TITLE
--skip-tags option demands tags to be present in playbook

### ISSUE THREAD

**Issue by cloudscriptguy** [ansible/ansible#15038] opened 2016-03-18 17:18 UTC
##### Issue Type:

- Bug Report
##### Ansible Version:

```
1.9.4
```
##### Environment:

CentOS 7 
##### Summary:

--skip-tags option to exclude tasks with specified tags, cannot be run against playbook that do not have those tags
##### Steps To Reproduce:
- Create a simple playbook with a debug task without any tags
- Run this playbook with --skip-tags 'foo_bar'

```
ansible-playbook -i my_inventory --skip-tags "foo_bar" simple_playbook.yml
```
##### Expected Results:

All tasks in the playbook should run
##### Actual Results:

Nothing executed and following error is shown

```
ERROR: tag(s) not found in playbook: foo_bar.  possible values:
```

**Comment by bcoca** [comment] 2016-03-18 17:26
not a bug, it is done on purpose, either the wrong plays or tags were specified.

**Comment by cloudscriptguy** [comment] 2016-03-18 18:51
Thanks!
Does it make sense to add another option like `--skip-tags-no-check` that will not perform this check?

This will greatly help with automation where we need to run bunch of playbooks and specifically exclude only tasks that have the specified tags and run everything else.

**Comment by bcoca** [comment] 2016-03-18 19:19
Well, this check is currently broken in 2.x (due to dynamic includes) but you can submit a `feature idea` ticket (if one does not already exist).

closing this ticket in any case as per above

**Closed as completed by bcoca** 2016-03-18 19:19 UTC
