### ISSUE TITLE
vars_prompt with private:no setting never continues

### ISSUE THREAD

**Issue by stefanvangastel** [ansible/ansible#8680] opened 2014-08-19 11:10 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.1
##### Environment:

Ubuntu 14.04 LTS 
Vagrant 1.6.3
Python 2.7.6
##### Summary:

Error is generated using Ansible 1.7 and the vars_prompt feature. 

I did not have the issue using Ansible 1.3 but upgraded tot the latest version because I needed the debconf feature.

The raw_input call in the on_vars_prompt function in /usr/lib/pymodules/python2.7/ansible/callbacks.py seems to 'freeze' when the private: no is set and the question is answered followed by a enter key.

If private is set to yes (or using the default) and thus the getpass.getpass is used, the prompt progresses after the enter key is pressed.
##### Steps To Reproduce:

Create a playbook using vars_prompt like this:

```

---
- name: Deploys the whole software stack for a CakePHP application
  hosts: development
  user: vagrant
  sudo: yes

  vars_prompt:
  - name: "cakephp_version"
    prompt: "\n\nWhat version of CakePHP do you want to deploy? (2 or 3)?"
    default: "2"
    private: no

  roles:
    - system
```
##### Expected Results:

```
What version of CakePHP do you want to deploy? (2 or 3)? [2]: 3
```

![works](https://cloud.githubusercontent.com/assets/2473490/3965007/faab2708-2790-11e4-8aff-0fdc34dbc7fc.png)
##### Actual Results:

```
What version of CakePHP do you want to deploy? (2 or 3)? [2]: 3

asfasfasf
asf
asf

```

![fail](https://cloud.githubusercontent.com/assets/2473490/3965032/5b9a18c6-2791-11e4-941b-1f0cf17a776e.png)

**Comment by astorije** [comment] 2014-12-21 19:39
@stefanvangastel, I am experiencing the same issue here. Did you find a workaround to make this work (like you found one for #8644), apart from keeping the prompt private?

**Comment by astorije** [comment] 2014-12-21 19:41
I just realized this issue is 4 month old. I am using Ansible 1.7.1 on Ubuntu 14.04 LTS as well (through apt-get). Was this fixed later on, by chance?

**Comment by stefanvangastel** [comment] 2014-12-23 08:45
No idea. Havent tried it since and found no other workaround.

**Comment by bcoca** [comment] 2014-12-23 18:45
I cannot reproduce in 1.8 or current devel, please try there and confirm.

**Comment by jrgns** [comment] 2015-01-20 20:21
I'm seeing this in 1.8.2.

**Comment by bcoca** [comment] 2015-01-20 20:25
so tested again on 1.7.6, 1.8.2 and current devel, I cannot reproduce the issue, I've used debian, centos and gentoo machines as ansible masters. 

Is everyone with the issue using vagrant?

**Comment by jrgns** [comment] 2015-01-20 20:27
+1 for vagrant.

**Comment by bcoca** [comment] 2015-01-20 20:35
# Is This A Bug?

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We're not sure this is a bug, and we don't mean for this to be confrontational.  Let's explain what we're thinking:
- Non private variables use a normal prompt, which vagrant does not work with, expected of most batch systems. Private prompts work through getpass and tty redirection magic,  Ansible is behaving properly here so I'm not considering this a bug anymore.

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists 
to talk about this and we might be persuaded otherwise.
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!

**Closed as completed by bcoca** 2015-01-20 20:35 UTC
Labels: bug
