### ISSUE TITLE
Premature "all hosts have already failed" on localhost plays when using a limit and not including localhost

### ISSUE THREAD

**Issue by omgjlk** [ansible/ansible#7247] opened 2014-05-01 18:46 UTC
##### Summary:

Imagine a playbook, with a play that has a hosts: line of localhost

Imagine running this playbook, with a --limit derp, which does not include localhost.

You'd expect this to skip the play with no matching hosts, but instead the play will get executed, and then the playbook will immediately fail with FATAL: all hosts have already failed.
##### Steps To Reproduce:

test.yaml

```

---
- name: Test play 1
  hosts: localhost
  gather_facts: no

  tasks:
    - name: derp
      debug: msg="herp"
```

```
$ ansible-playbook -i derp, test.yaml -vv --limit derp
```
##### Expected Results:

```
PLAY [Test play 1] ************************************************************
skipping: no hosts matched
```

or

```
TASK: [derp] ******************************************************************
ok: [localhost] => {
    "msg": "herp"
}
```
##### Actual Results:

```
TASK: [derp] ******************************************************************
ok: [localhost] => {
    "msg": "herp"
}

FATAL: all hosts have already failed -- aborting
```

Through some bisecting, I think the offending commit is
ae9843fccdac1bc5da95f2c9d274e927f4a43962
but I'm not positive. I believe it's a combination of this commit, along with the introduction of the implicit localhost inventory entry. More testing to continue, but I wanted to get this filed for tracking.

**Comment by mpdehaan** [comment] 2014-05-01 19:46
Looks like this could be argued that this is "not a bug" as the limit criteria should have been --limit "derp:localhost" ?

Though still need to think it over.

**Comment by omgjlk** [comment] 2014-05-01 19:56
Well, it's a bit disturbing that it would execute the task on localhost, then decide that there are no hosts in the play, thus indicating a failure based on max failure percentage (100%). If localhost really needed to be in the limit, I would expect the play to be skipped with "no hosts matched".

If I replace "localhost" with some other fictional host in the hosts: line, things work as expected. Either no hosts matched if not in the inventory, no hosts matched if in the inventory and limited out, and ran if in inventory and in limit.

The situation of localhost both being there and not there is a source of confusion.

**Comment by mpdehaan** [comment] 2014-05-01 22:21
So, that's exactly the same as what happens for any other group of host though.

Localhost having special handling on whether it should have a failure seems like a slippery slope.

(If a playbook group targets less than 1 host, ansible will abort because the available pool of hosts to talk to is 0)

**Comment by omgjlk** [comment] 2014-05-01 23:07
"(If a playbook group targets less than 1 host, ansible will abort because the available pool of hosts to talk to is 0)" 

That is not what I see in practice. What I see is that the play will be skipped, but the playbook will not abort.

What I see in practice is special handling with localhost, in that the task will always execute, and then the playbook will abort.

```
---
- name: Test play 1
  hosts: hurp
  gather_facts: no

  tasks:
    - name: derp
      debug: msg="herp"
```

Usage:

```
$ ansible-playbook -i derp, test.yaml -vvvv

PLAY [Test play 1] ************************************************************
skipping: no hosts matched

PLAY RECAP ********************************************************************

$ echo $?
0
```

**Comment by jasonarewhy** [comment] 2014-05-19 22:18
Seeing this same issue. Rather than skipping a localhost task when --limit is used, the localhost task is executed successfully and then the "FATAL: all hosts have already failed -- aborting" appears. I would assume it should instead show "skipping: no hosts matched" and then continue (assuming there are other plays that match hosts in the --limit).

**Comment by gildegoma** [comment] 2014-05-23 09:27
I confirm that the introduction of the implicit localhost in Ansible 1.5 caused that `localhost` is badly handled by `--limit` option, as already reported in #6449.

**Comment by mpdehaan** [comment] 2014-06-01 18:52
Closing as a duplicate

**Closed as completed by mpdehaan** 2014-06-01 18:52 UTC
Labels: needs_info, bug

**Comment by trinitronx** [comment] 2014-12-05 00:30
Saw this same issue when I used `127.0.0.1` instead of `localhost` in my hosts inventory file.  Changing to `localhost` fixed it
