### ISSUE TITLE
Installation documentation of version 4 incorrect for Debian

### ISSUE THREAD

**Issue by abraxxa** [ansible/ansible#75146] opened 2021-06-30 11:18 UTC
### Summary

The documentation for installing Ansible 4 on Debian at https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#installing-ansible-on-debian is incorrect as no trusty packages exist for it.

### Issue Type

Documentation Report

### Component Name

docs/docsite/rst/installation_guide/intro_installation.rst

### Ansible Version

```console
does not apply because ansible couldn't be installed
```

### Configuration

```console
does not apply because ansible couldn't be installed
```

### OS / Environment

Debian 10

### Additional Information

none

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by aminvakil** [comment] 2021-06-30 11:22
I've just tested doc on a clean debian 10 buster and it works fine.
```
debian@ansibletest:~$ sudo apt purge ansible*
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'ansible-tower-cli' for glob 'ansible*'
Note, selecting 'ansible-tower-cli-doc' for glob 'ansible*'
Note, selecting 'ansible-doc' for glob 'ansible*'
Note, selecting 'ansible' for glob 'ansible*'
Note, selecting 'ansible-lint' for glob 'ansible*'
Package 'ansible' is not installed, so not removed
Package 'ansible-doc' is not installed, so not removed
Package 'ansible-lint' is not installed, so not removed
Package 'ansible-tower-cli' is not installed, so not removed
Package 'ansible-tower-cli-doc' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
debian@ansibletest:~$ sudo sh -c "echo deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main > /etc/apt/sources.list.d/ansible.list"
debian@ansibletest:~$ sudo apt update
Hit:1 http://deb.debian.org/debian buster InRelease
Hit:2 http://security.debian.org/debian-security buster/updates InRelease
Get:3 http://ppa.launchpad.net/ansible/ansible/ubuntu trusty InRelease [16.0 kB]
Hit:4 http://deb.debian.org/debian buster-updates InRelease
Get:5 http://ppa.launchpad.net/ansible/ansible/ubuntu trusty/main amd64 Packages [697 B]
Get:6 http://ppa.launchpad.net/ansible/ansible/ubuntu trusty/main Translation-en [492 B]
Fetched 17.1 kB in 1s (12.4 kB/s)                   
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
debian@ansibletest:~$ sudo apt install ansible -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libsodium23 python-bcrypt python-crypto python-httplib2 python-jinja2 python-markupsafe python-nacl python-paramiko python-pyasn1 sshpass
Suggested packages:
  python-crypto-doc python-jinja2-doc python-nacl-doc python-gssapi
The following NEW packages will be installed:
  ansible libsodium23 python-bcrypt python-crypto python-httplib2 python-jinja2 python-markupsafe python-nacl python-paramiko python-pyasn1 sshpass
0 upgraded, 11 newly installed, 0 to remove and 0 not upgraded.
Need to get 6,637 kB of archives.
After this operation, 61.3 MB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/ansible/ansible/ubuntu trusty/main amd64 ansible all 2.9.23-1ppa~trusty [5,799 kB]
Get:2 http://deb.debian.org/debian buster/main amd64 python-markupsafe amd64 1.1.0-1 [14.0 kB]
Get:3 http://deb.debian.org/debian buster/main amd64 python-jinja2 all 2.10-2 [106 kB]
Get:4 http://deb.debian.org/debian buster/main amd64 python-bcrypt amd64 3.1.6-1 [31.5 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 libsodium23 amd64 1.0.17-1 [158 kB]
Get:6 http://deb.debian.org/debian buster/main amd64 python-nacl amd64 1.3.0-2 [49.5 kB]
Get:7 http://deb.debian.org/debian buster/main amd64 python-pyasn1 all 0.4.2-3 [57.6 kB]
Get:8 http://deb.debian.org/debian buster/main amd64 python-paramiko all 2.4.2-0.1 [120 kB]
Get:9 http://deb.debian.org/debian buster/main amd64 python-httplib2 all 0.11.3-2 [30.4 kB]
Get:10 http://deb.debian.org/debian buster/main amd64 python-crypto amd64 2.6.1-9+b1 [259 kB]
Get:11 http://deb.debian.org/debian buster/main amd64 sshpass amd64 1.06-1 [11.3 kB]
Fetched 6,637 kB in 1s (5,565 kB/s)                           
Selecting previously unselected package python-markupsafe.
(Reading database ... 28824 files and directories currently installed.)
Preparing to unpack .../00-python-markupsafe_1.1.0-1_amd64.deb ...
Unpacking python-markupsafe (1.1.0-1) ...
Selecting previously unselected package python-jinja2.
Preparing to unpack .../01-python-jinja2_2.10-2_all.deb ...
Unpacking python-jinja2 (2.10-2) ...
Selecting previously unselected package python-bcrypt.
Preparing to unpack .../02-python-bcrypt_3.1.6-1_amd64.deb ...
Unpacking python-bcrypt (3.1.6-1) ...
Selecting previously unselected package libsodium23:amd64.
Preparing to unpack .../03-libsodium23_1.0.17-1_amd64.deb ...
Unpacking libsodium23:amd64 (1.0.17-1) ...
Selecting previously unselected package python-nacl.
Preparing to unpack .../04-python-nacl_1.3.0-2_amd64.deb ...
Unpacking python-nacl (1.3.0-2) ...
Selecting previously unselected package python-pyasn1.
Preparing to unpack .../05-python-pyasn1_0.4.2-3_all.deb ...
Unpacking python-pyasn1 (0.4.2-3) ...
Selecting previously unselected package python-paramiko.
Preparing to unpack .../06-python-paramiko_2.4.2-0.1_all.deb ...
Unpacking python-paramiko (2.4.2-0.1) ...
Selecting previously unselected package python-httplib2.
Preparing to unpack .../07-python-httplib2_0.11.3-2_all.deb ...
Unpacking python-httplib2 (0.11.3-2) ...
Selecting previously unselected package python-crypto.
Preparing to unpack .../08-python-crypto_2.6.1-9+b1_amd64.deb ...
Unpacking python-crypto (2.6.1-9+b1) ...
Selecting previously unselected package sshpass.
Preparing to unpack .../09-sshpass_1.06-1_amd64.deb ...
Unpacking sshpass (1.06-1) ...
Selecting previously unselected package ansible.
Preparing to unpack .../10-ansible_2.9.23-1ppa~trusty_all.deb ...
Unpacking ansible (2.9.23-1ppa~trusty) ...
Setting up python-crypto (2.6.1-9+b1) ...
Setting up libsodium23:amd64 (1.0.17-1) ...
Setting up python-httplib2 (0.11.3-2) ...
Setting up python-bcrypt (3.1.6-1) ...
Setting up sshpass (1.06-1) ...
Setting up python-pyasn1 (0.4.2-3) ...
Setting up python-nacl (1.3.0-2) ...
Setting up python-paramiko (2.4.2-0.1) ...
Setting up python-markupsafe (1.1.0-1) ...
Setting up python-jinja2 (2.10-2) ...
Setting up ansible (2.9.23-1ppa~trusty) ...
Processing triggers for libc-bin (2.28-10) ...
debian@ansibletest:~$ ansible --version
ansible 2.9.23
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/debian/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]
debian@ansibletest:~$ ansible localhost -m ping
localhost | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
```

**Comment by abraxxa** [comment] 2021-06-30 12:14
Yes, ansible 2.9 but not 4.x.

**Comment by sivel** [comment] 2021-06-30 13:57
Duplicate of https://github.com/ansible-community/antsibull/issues/202

**Comment by samccann** [comment] 2021-11-16 21:31
Fixed by https://github.com/ansible/ansible/pull/75567

**Closed as completed by samccann** 2021-11-16 21:31 UTC
Labels: support:core, docs, affects_2.12
