### ISSUE TITLE
npm module won't install a package if it is installed as another package's dependency

### ISSUE THREAD

**Issue by davidminor** [ansible/ansible#6399] opened 2014-03-11 17:01 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5
##### Environment:

N/A
##### Summary:

npm module won't install a package if it is installed as another package's dependency
##### Steps To Reproduce:

``` yml
- name: Install less compiler, css minifier
  npm: name={{ item }}
  with_items:
    - less
    - clean-css
```
##### Expected Results:

clean-css should be installed, as it will be if you run:

``` shell
# npm install less clean-css
```
##### Actual Results:

clean-css is not installed.

This is because the npm module is misinterpreting the results of npm list. If the less package is installed, `npm list --json clean-css` returns:

``` json
{
  "dependencies": {
    "less": {
      "version": "1.7.0",
      "from": "less@",
      "dependencies": {
        "clean-css": {
          "version": "2.1.6",
          "from": "clean-css@2.1.x"
        }
      }
    }
  }
}
```

The npm module interprets this to mean that clean-css is installed.

**Comment by bartdag** [comment] 2014-06-27 09:54
Looks like a duplicate of #4659

**Comment by jimi-c** [comment] 2014-08-07 16:51
Hi!

The above change has been applied for this ticket, which should resolve this item for you.

If you believe this ticket is not resolved, or have further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments on closed tickets, though the mailing list is a great way to get involved or discuss this one further.

Thanks!

**Closed as completed by jimi-c** 2014-08-07 16:51 UTC
Labels: bug
