### ISSUE TITLE
v2 failed_when does not allow lists or tuples

### ISSUE THREAD

**Issue by drfickle** [ansible/ansible#15291] opened 2016-04-05 21:44 UTC
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = /home/sfox/.ansible.cfg
  configured module search path = /home/sfox/src/sysops/ops/branches/ansible-2.0/ansible/library
```
##### CONFIGURATION

```
library = /home/sfox/src/sysops/ops/branches/ansible-2.0/ansible/library
forks          = 20
sudo_flags = -H -i
jinja2_extensions = jinja2.ext.do,jinja2.ext.i18n,jinja2.ext.loopcontrols,jinja2.ext.with_
ansible_managed = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
action_plugins     = /usr/share/ansible_plugins/action_plugins:/home/sfox/src/sysops/ops/branches/ansible-2.0/ansible/plugins/action
callback_plugins   = /usr/share/ansible_plugins/callback_plugins:/home/sfox/src/sysops/ops/branches/ansible-2.0/ansible/plugins/callback
connection_plugins = /usr/share/ansible_plugins/connection_plugins:/home/sfox/src/sysops/ops/branches/ansible-2.0/ansible/plugins/connection
lookup_plugins     = /usr/share/ansible_plugins/lookup_plugins:/home/sfox/src/sysops/ops/branches/ansible-2.0/ansible/plugins/lookup
vars_plugins       = /usr/share/ansible_plugins/vars_plugins:/home/sfox/src/sysops/ops/branches/ansible-2.0/ansible/plugins/vars
filter_plugins     = /usr/share/ansible_plugins/filter_plugins:/home/sfox/src/sysops/ops/branches/ansible-2.0/ansible/plugins/filter
nocows = 1
```
##### OS / ENVIRONMENT

From: Fedora 23
Managing: Ubuntu Trusty (14.04)
##### SUMMARY

I can no longer specify lists or tuples in a failed_when statement like I could with 1.9.x
##### STEPS TO REPRODUCE

Using this inventory file

```
test_host ansible_host=10.0.0.208
```

and this playbook

```
- name: My Playbook
  hosts: test_host
  gather_facts: no

  tasks:  
    - shell: ls pants                         
      register: result
      failed_when: result.rc not in [0, 1]
      #failed_when: "result.rc not in [0, 1]"           
      #failed_when: result.rc not in (0, 1)
```

I cannot get Ansible to execute this with or without quotes. Both lists and tuples worked previously.
##### EXPECTED RESULTS

```
PLAY [My Playbook] ************************************************************ 

TASK: [shell ls pants] ******************************************************** 
failed: [test_host] => {"changed": true, "cmd": "ls pants", "delta": "0:00:00.003004", "end": "2016-04-05 16:29:21.478688", "failed": true, "failed_when_result": true, "rc": 2, "start": "2016-04-05 16:29:21.475684", "stdout_lines": [], "warnings": []}
stderr: ls: cannot access pants: No such file or directory

FATAL: all hosts have already failed -- aborting
```
##### ACTUAL RESULTS

```
PLAY [My Playbook] *************************************************************

TASK [command] *****************************************************************
fatal: [test_host]: FAILED! => {"failed": true, "msg": "The conditional check 'result.rc not in [0' failed. The error was: template error while templating string: unexpected '}', expected ']'. String: {% if result.rc not in [0 %} True {% else %} False {% endif %}"}

NO MORE HOSTS LEFT *************************************************************
```

**Comment by nitzmahone** [comment] 2016-04-21 15:28
Yep, this was working in 2.0.1, so it's a recent regression. I'm seeing this on both 2.0.2 and devel. @abadger - git bisect says this broke with 61afb71

**Comment by bcoca** [comment] 2016-04-21 21:05
^ why did we allow that? it shoudl be either yaml lists - (or [ , ]) or use |list filter on string

**Comment by abadger** [comment] 2016-04-22 01:05
Yeah, we talked about this in irc when I merged it because I was unsure whether it was a good idea or not.  Here's the PR and the three comments that lead to it:

https://github.com/ansible/ansible/pull/13443#discussion_r55925772

And here's our IRC discussion.

> 14/03/16 12:06:54,#ansible-devel,<abadger1999>,"bcoca, jimi|ansible : Did you see my note about FieldAttributes in https://github.com/ansible/ansible/pull/13443 ?"
> 14/03/16 12:07:44,#ansible-devel,<abadger1999>,"for type, if it's a list then if someone specifies a comma separated string it looks like it would get turned into ['comma,separated,string']"
> 14/03/16 12:08:20,#ansible-devel,<abadger1999>,"is that something we want individual FieldAttributes to handle or do we want separation to be part of the general FieldAttribute handling?"
> 14/03/16 12:14:29,#ansible-devel,<abadger1999>,"(also -- I want to make FieldAttribute sets have more of FieldAttributes lists options. let me know if you don't htink that's a good idea.)"
> 14/03/16 12:15:08,#ansible-devel,<privateip>,#ansible-devel
> 14/03/16 12:17:13,#ansible-devel,<jimi|ansible>,"ok, email sent to ML's regarding static_includes"
> 14/03/16 12:17:29,#ansible-devel,<jimi|ansible>,"abadger1999: did not see that, looking now"
> 14/03/16 12:18:12,#ansible-devel,<bcoca>,"abadger1999: agree, should split , if only a string is passed"
> 14/03/16 12:18:29,#ansible-devel,<jimi|ansible>,"yes, it should live in the FieldAttribute class"
> 14/03/16 12:18:38,#ansible-devel,<abadger1999>,"Cool.  I'll make that change."

We can definitely revisit this -- it was something I was unsure of at the time as well.

**Closed as completed** 2016-04-22 18:21 UTC
Labels: P2, bug

**Comment by jimi-c** [comment] 2016-04-22 18:23
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by drfickle** [comment] 2016-04-22 19:03
Fantastic! Confirmed the bug is fixed in my original playbook too. Thank you.
