### ISSUE TITLE
Run task depending on host has changed

### ISSUE THREAD

**Issue by garyrutland** [ansible/ansible#13151] opened 2015-11-13 12:02 UTC
Hi,

Sorry if this is the wrong place to ask this but I'm not sure where else and this seems like the most likely place that someone might be able to answer my question.

Using AWS to update our Bamboo box if and when a new capability is needed for whatever reason, need to then create an AMI based on these changes so that they aren't lost.
I can create an AMI without issue, but only really want it to be created if something is actually changed on any of the hosts.

This is an example of what I would like to achieve:

```

---

- name: update bamboo nodes
  hosts: security_group_bamboo
  roles:
    - common
    ...

- name: create ami
  connection: local
  hosts: local
  gather_facts: false
  tasks:
    - ec2_ami:
        ...
      when: "something has changed in above roles"
```

Is this even possible?

Thanks,
Gary

**Comment by jimi-c** [comment] 2015-11-13 13:43
Hi @garyrutland, unfortunately not directly like this. Typically you would register the result from a single task and then check `result.changed`, however doing so for task within a role would be tricky. To do so, you'd have to have a task using `set_fact` after every other task to test if things had changed at all, which is doable but not ideal.

As this is a general use question and not a bug, I'm going to go ahead and close this. If you would like to continue the discussion, we ask that normal use questions be sent to one of the mailing lists or our IRC channel:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code
- #ansible or #ansible-devel on FreeNode IRC

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-11-13 13:43 UTC
