### ISSUE TITLE
ansible-galaxy install doesn't install collections, only roles from requirements.yml

### ISSUE THREAD

**Issue by szigya** [ansible/ansible#71913] opened 2020-09-24 13:55 UTC
##### SUMMARY

According to documentation 

> To install both roles and collections at the same time with one command, run the following:
> `$ ansible-galaxy install -r requirements.yml`

**but it only installs roles, collections not**.

it works however with the following combination of commands:

  ansible-galaxy install -r requirements.yml
  ansible-galaxy collection install -r requirements.yml

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```paste below
2.9.6
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

OS: Ubuntu 20.04 Desktop

##### STEPS TO REPRODUCE

Create requirements.yml and call
`ansible-galaxy install -r requirements.yml`

```yaml
---
roles:
  - gantsign.oh-my-zsh
  - honatas.openjdk_ppa
  - akkerman.docker

collections:
  - name: community.general
```

##### EXPECTED RESULTS

Collections should have been installed.
Both the actual result plus:
```
Found installed collection ansible.posix:1.1.1 at '/home/mike/.ansible/collections/ansible_collections/ansible/posix'
Found installed collection ansible.netcommon:1.2.1 at '/home/mike/.ansible/collections/ansible_collections/ansible/netcommon'
Found installed collection community.general:1.1.0 at '/home/mike/.ansible/collections/ansible_collections/community/general'
Found installed collection google.cloud:1.0.0 at '/home/mike/.ansible/collections/ansible_collections/google/cloud'
Process install dependency map
Initial connection to galaxy_server: https://galaxy.ansible.com
Opened /home/mike/.ansible/galaxy_token
Calling Galaxy at https://galaxy.ansible.com/api/
Processing requirement collection 'community.general'
Collection requirement 'community.general' is the name of a collection
Found API version 'v1, v2' with Galaxy server default (https://galaxy.ansible.com/api/)
Calling Galaxy at https://galaxy.ansible.com/api/v2/collections/community/general/versions/
Collection 'community.general' obtained from server default https://galaxy.ansible.com/api/
Starting collection install process
Skipping 'community.general' as it is already installed
```

##### ACTUAL RESULTS

Only roles are installed

```paste below
 ansible_dev_env ansible-galaxy install -r requirements.yml -vvvv
ansible-galaxy 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/mike/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible-galaxy
  python version = 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]
Using /etc/ansible/ansible.cfg as config file
Reading requirement file at 'requirements.yml'
found role {'name': 'gantsign.oh-my-zsh', 'src': 'gantsign.oh-my-zsh', 'scm': None, 'version': None} in yaml file
found role {'name': 'honatas.openjdk_ppa', 'src': 'honatas.openjdk_ppa', 'scm': None, 'version': None} in yaml file
found role {'name': 'akkerman.docker', 'src': 'akkerman.docker', 'scm': None, 'version': None} in yaml file
Processing role gantsign.oh-my-zsh 
[WARNING]: - gantsign.oh-my-zsh (2.3.0) is already installed - use --force to change version to unspecified
Processing role honatas.openjdk_ppa 
[WARNING]: - honatas.openjdk_ppa (master) is already installed - use --force to change version to unspecified
Processing role akkerman.docker 
[WARNING]: - akkerman.docker (v1.1.0) is already installed - use --force to change version to unspecified
```

**Comment by sivel** [comment] 2020-09-24 13:57
This is the expected behavior.  However we are looking into improving the `ansible-galaxy` installation UX for the 2.11 release, and it is possible that we may be able to combine these in a future release.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by szigya** [comment] 2020-09-24 14:01
@sivel 
Sorry, but if that's the expected behaviour, then the documentation is wrong. Like I quoted:

> To install both roles and collections at the same time with one command, run the following:
> `$ ansible-galaxy install -r requirements.yml`

Source: https://docs.ansible.com/ansible/latest/user_guide/collections_using.html

**Comment by sivel** [comment] 2020-09-24 14:05
I missed that, we'll make sure to get the docs addressed.

**Comment by szigya** [comment] 2020-09-24 14:14
Thank you. Also, I would be for the documentation way, it's nicer. However, I just created a bash script to include both, so it's not a huge headache.

**Comment by jborean93** [comment] 2020-09-24 19:16
It is the expected behaviour but only when you are using Ansible 2.10+ This wasn't backported because it's technically a feature. You won't find the same information for the 2.9 specific docs https://docs.ansible.com/ansible/2.9/user_guide/collections_using.html.

**Comment by samdoran** [comment] 2020-09-24 19:50
Closing per above.

**Closed as completed** 2020-09-24 20:03 UTC
Labels: python3, support:core, docs, affects_2.9

**Comment by szigya** [comment] 2020-09-25 04:07
I see, thank you for the clarification, I thought that is the newest version as I installed from apt, but I see now that version 10 has only packages named ansible-base.

**Comment by jborean93** [comment] 2020-09-25 04:11
Version 2.10 was only just release on pypi so it will take time before it is available through system package managers. As soon as we create the release we update the docs to point to that version which is why people would typically only just see this feature.
