### ISSUE TITLE
wall messages can leak into ansible return data

### ISSUE THREAD

**Issue by omgjlk** [ansible/ansible#3909] opened 2013-08-21 19:39 UTC
I have on occasion seen ansible tasks fail due to inability to parse the output, and the output happens to have wall message content in it. It seems something isn't protecting ansible from getting wall messages mixed in.

I don't have any handy examples right now, but I witnessed a wall message while logged into a system and put 2 and 2 together.

**Comment by bcoca** [comment] 2013-08-21 19:50
You can disable with mesg, but root can override that.

**Comment by jimi-c** [comment] 2013-08-21 20:22
Can you make your sysadmins format their wall messages as JSON? :)

**Comment by omgjlk** [comment] 2013-08-21 21:20
Hah. In this case it made me notice a bad configuration state on our servers, that I'm about to clean up. So the bug will trigger for me far far less often.

**Comment by jimi-c** [comment] 2013-08-22 02:00
Kidding aside, I'm not sure if there's something we can fix here. Since we do open a tty with SSH it may never be possible to ensure that broadcast messages like wall never bleed into the output.

**Comment by mpdehaan** [comment] 2013-08-22 02:05
Yeah I believe I'd concur with James here, unless there is some way to initiate a terminal that doesn't get Wall.

**Comment by omgjlk** [comment] 2013-08-22 04:19
I only know of mesg n to disable, but root overrides that, so not much that can be done. Might be worth a warning somewhere in the docs about the potential for wall messages to interrupt ansible.

**Comment by mpdehaan** [comment] 2013-08-23 23:43
Yep, that seems reasonable.   I couldn't dig up anything else either.

Maybe rm -rf wall :)

**Comment by bcoca** [comment] 2013-08-23 23:58
We need to create Wall, which is a wall against wall.

Brian Coca

**Comment by jimi-c** [comment] 2013-09-03 15:51
Testing this out on my system, and it seems like "mesg n" (even as root) isn't preventing wall messages from showing up (even from non-privileged users). So I'm not sure if there's a good solution here, short of `shell: rm -f $(which wall)`

**Comment by bcoca** [comment] 2013-09-03 18:43
wall was designed as an interrupt to all live sessions for administrative
purposes (i.e. shutdown or 'can I run a forkbomb test?') . I would be
surprised if there was a way for apps to cancel this on a live tty.

Brian Coca

**Comment by jimi-c** [comment] 2013-09-10 20:28
Ok, going to close this as there is no good resolution here. If it comes up again in the future we can revisit it.

Thanks!

**Closed as completed by jimi-c** 2013-09-10 20:28 UTC
Labels: bug
