### ISSUE TITLE
WinRM: Certification error when using "delegate_to" in playbook

### ISSUE THREAD

**Issue by naphta** [ansible/ansible#18082] opened 2016-10-18 14:30 UTC
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

`WinRM -- pywinrm`
##### ANSIBLE VERSION

`ansible 2.1.0.0`
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

`Ubuntu 14.04 w/ Python 2.7.10`
##### SUMMARY

When using `pywinrm==2.0` or higher I recieve a certification error despite `ansible_winrm_server_cert_validation=ignore` being set.

Appears to not be respecting that specific setting. This only occurs when using the "delegate_to".
##### STEPS TO REPRODUCE

```
- hosts:  localhost
  tasks:

    - set_fact:
         primary_web2: 10.0.0.2

    - name: Ensure NTFS permissions
       delegate_to: "{{ primary_web2 }}"
       win_acl:
         path: d:/websites
         user: 'Everyone'
         rights: 'FullControl'
         type: 'allow'
         state: 'present'
         inherit: 'ContainerInherit, ObjectInherit'
```
##### EXPECTED RESULTS

To set the permissions on the remote host as per the module (this applies to all windows modules, not just the one in the example)
##### ACTUAL RESULTS

```
<10.0.0.2> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5986 TO 10.0.0.2
fatal: [localhost]: UNREACHABLE! =>
{
    "changed": false,
    "msg": "ssl: (\"bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)\",)",
    "unreachable": true
}
```
##### WORK AROUND

Downgrading to pywinrm==0.1.1 works absolutely fine.

**Comment by alikins** [comment] 2016-10-19 19:34
This does seem to be a bug.

 As a potential workaround, try setting 'ansible_winrm_server_cert_validation' on the original host/group  as well as the Windows host/group.

**Comment by bcoca** [comment] 2016-10-20 03:52
The issue is known, on delegation we copy a set of variables, which does not include 'connection plugin custom ones', the workaround is just setting these vars in the 'all' group or for the servers you delegate for .

We have a permanent fix in the works, but it will take some time as it reverses how we currently select and pass variables to our connection plugins.

**Comment by naphta** [comment] 2016-10-20 15:15
Workaround mentioned above works just fine and perfectly OK from my point of view. Cheers both.

**Comment by nitzmahone** [comment] 2016-10-20 17:42
Since the workaround is good and it's a known issue that we're already planning to fix, I'm going to close this. Thanks all!

**Closed as completed by nitzmahone** 2016-10-20 17:42 UTC
Labels: windows, affects_2.1, bug
