### ISSUE TITLE
ansible-galaxy outputs stderr onto multiple lines when redirecting or using pipe

### ISSUE THREAD

**Issue by otteydw** [ansible/ansible#73417] opened 2021-01-29 15:11 UTC
##### SUMMARY

When running the ansible-galaxy command through a pipe, some output is split onto multiple lines.  But when not run through a pipe, it stays on a single line.  Splitting the output onto multiple lines when run through a pipe makes parsing the output difficult / unreliable.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible-galaxy

##### ANSIBLE VERSION

```paste below
ansible-galaxy 2.10.5
  config file = /home/dottey/git/ansible-playbook-boomi-platform/ansible.cfg
  configured module search path = [u'/home/dottey/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/dottey/git/ansible-playbook-boomi-platform/.venv/lib/python2.7/site-packages/ansible
  executable location = /home/dottey/git/ansible-playbook-boomi-platform/.venv/bin/ansible-galaxy
  python version = 2.7.15 (default, Aug 12 2020, 13:29:00) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/home/dottey/git/ansible-playbook-boomi-platform/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/dottey/git/ansible-playbook-boomi-platform/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s
ANSIBLE_SSH_CONTROL_PATH(/home/dottey/git/ansible-playbook-boomi-platform/ansible.cfg) = ******************************************************************************** Intentionally will fail - make sure the ANSIBLE_SSH_CONTROL_PATH env var is set!!! ****************************>
ANY_ERRORS_FATAL(/home/dottey/git/ansible-playbook-boomi-platform/ansible.cfg) = True
DEFAULT_CALLBACK_WHITELIST(/home/dottey/git/ansible-playbook-boomi-platform/ansible.cfg) = [u'profile_tasks']
DEFAULT_GATHER_TIMEOUT(/home/dottey/git/ansible-playbook-boomi-platform/ansible.cfg) = 90
DEFAULT_TIMEOUT(/home/dottey/git/ansible-playbook-boomi-platform/ansible.cfg) = 90

```

##### OS / ENVIRONMENT

Ubuntu 20.04.1 LTS

##### STEPS TO REPRODUCE

Run ansible-galaxy to install a role that already exists.  The error message (in stderr) telling you to use --force gets split onto multiple lines when stdout is redirected to /dev/null or the command is sent through a pipe.

```bash
$ .venv/bin/ansible-galaxy install --role-file=galaxy/ansible-role-vpc-peering.yml --roles-path=roles/
Starting galaxy role install process
[WARNING]: - galaxy-ansible-role-vpc-peering (release20.1.1) is already installed - use --force to change version to release20.1.2

$ .venv/bin/ansible-galaxy install --role-file=galaxy/ansible-role-vpc-peering.yml --roles-path=roles/ > /dev/null
[WARNING]: - galaxy-ansible-role-vpc-peering (release20.1.1) is already
installed - use --force to change version to release20.1.2

$ .venv/bin/ansible-galaxy install --role-file=galaxy/ansible-role-vpc-peering.yml --roles-path=roles/ | cat -vet
Starting galaxy role install process$
[WARNING]: - galaxy-ansible-role-vpc-peering (release20.1.1) is already
installed - use --force to change version to release20.1.2

```

##### EXPECTED RESULTS

The output should be on a single line. Ansible version 2.9.17, for example, has the output on a single line.
```
[WARNING]: - galaxy-ansible-role-vpc-peering (release20.1.1) is already installed - use --force to change version to release20.1.2
```

##### ACTUAL RESULTS

stderr is split onto multiple lines making parsing the output with grep unreliable

```
$ .venv/bin/ansible-galaxy install --role-file=galaxy/ansible-role-vpc-peering.yml --roles-path=roles/ > /dev/null
[WARNING]: - galaxy-ansible-role-vpc-peering (release20.1.1) is already
installed - use --force to change version to release20.1.2
```

**Comment by sivel** [comment] 2021-01-29 15:14
Duplicate of https://github.com/ansible/ansible/issues/71461

**Closed as completed by sivel** 2021-01-29 15:14 UTC
