### ISSUE TITLE
with_items needs {{ }} if the first word is not a variable

### ISSUE THREAD

**Issue by ktosiek** [ansible/ansible#9434] opened 2014-10-28 09:30 UTC
##### Ansible Version:

ansible 1.8 (devel 58defa5cce) last updated 2014/10/28 10:25:01 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 7f611468a8) last updated 2014/10/27 16:48:25 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD a0df36c6ab) last updated 2014/10/27 16:48:29 (GMT +200)
  v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/10/27 16:48:33 (GMT +200)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/10/27 16:48:37 (GMT +200)
  configured module search path = /usr/share/ansible
##### Summary:

with_items breaks if the first word is an undefined variable, which makes it unusable with |default
##### Steps To Reproduce:

```
- shell: echo {{ item }}
  with_items: dummy | default([])
```
##### Expected Results:

```
TASK: [shell echo {{ item }}] ************************************************* 
skipping: [localhost]
```
##### Actual Results:

```
TASK: [shell echo {{ item }}] ************************************************* 
fatal: [localhost] => with_items expects a list or a set

FATAL: all hosts have already failed -- aborting
```

**Comment by garlandkr** [comment] 2014-10-29 17:23
This is a dupe of #9335

**Closed as completed** 2014-10-29 23:46 UTC
