### ISSUE TITLE
When a host is added via add_host, group_vars are not loaded

### ISSUE THREAD

**Issue by dekked** [ansible/ansible#3566] opened 2013-07-17 17:25 UTC
According to @mpdehaan this might not happen if the group is defined on the inventory. Haven't tried though.

Investigate.

**Comment by dekked** [comment] 2013-07-18 21:33
Same thing when running a playbook with --limit "127.0.0.1,", the variables from "all" are not loaded.

**Comment by bcoca** [comment] 2013-07-19 01:13
Can you add test case? This works for me. Fyi, your 2nd example is using
inventory shorthand on --limit that is intended for -i.

Brian Coca

**Comment by mpdehaan** [comment] 2013-07-19 01:17
Yeah if you did "-i hostname," it would not load the file, --limit will/should

Test case would be very very good, can you share something on gist?

**Comment by dekked** [comment] 2013-07-19 02:30
Sorry, I intended to say **-i** and not --limit, my bad.

I have shared minimal playbooks to reproduce the issue I am having here: https://github.com/dekked/ansible-issue-3566

Running:

```
ansible-playbook -c local -i hosts site.yml
```

the variables get resolved every time. Here, the host is on the inventory file on the correct group. If we run:

```
ansible-playbook -c local -i hosts2 site.yml
```

the "all" variables get resolved correctly, but not the group1 var.
Finally, running:

```
ansible-playbook -c local -i "127.0.0.1," site.yml
```

the variables are never resolved.

**Comment by bcoca** [comment] 2013-07-19 02:33
3rd case, yes, expected as you are passing the inventory in list.

On Thu, Jul 18, 2013 at 10:30 PM, Alan Descoins notifications@github.comwrote:

> ansible-playbook -c local -i "127.0.0.1," site.yml
> 
> the variables are never resolved.

group and host vars get loaded from inventory (dir/file) and sub
directories, when passing a list inline you aren't specifying a root for

## ansible to look for these.

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by bcoca** [comment] 2013-07-19 02:34
for case #2, there is no group1 in your inventory so even though ansible
finds the group1 files it doesn't add it, you might want to change the -i
to the directory in which case it will pick up both files.

On Thu, Jul 18, 2013 at 10:33 PM, Brian Coca briancoca@gmail.com wrote:

> 3rd case, yes, expected as you are passing the inventory in list.
> 
> On Thu, Jul 18, 2013 at 10:30 PM, Alan Descoins notifications@github.comwrote:
> 
> > ansible-playbook -c local -i "127.0.0.1," site.yml
> > 
> > the variables are never resolved.
> 
> group and host vars get loaded from inventory (dir/file) and sub
> directories, when passing a list inline you aren't specifying a root for
> 
> ## ansible to look for these.
> 
> Brian Coca
> Stultorum infinitus est numerus
> 
> 0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
> Pedo mellon a minno

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by bcoca** [comment] 2013-07-21 16:13
debugged on IRC, this was mostly a misunderstanding on how hosts and groups were defined and used by ansible.

**Comment by tszming** [comment] 2013-07-28 13:43
I also come across this issue today, the `group_vars` folder only get included when your inventory file is under the playbook directory, e.g.

```
cd myplaybook
ansible-playbook -i hosts site.yml
```

But not

```
cd myplaybook
ansible-playbook -i /other/dir/hosts site.yml
```

Sound like this behaviors is a little bit different from I receive from  [1]

> Tip: In Ansible 1.2 or later the group_vars/ and host_vars/ directories can exist in either the playbook directory OR the inventory directory. If both paths exist, variables in the playbook directory will be loaded second.

[1] http://www.ansibleworks.com/docs/patterns.html

**Comment by mpdehaan** [comment] 2013-07-28 15:41
I need to test to explore.

What you are seeing in (A) is it finding it parallel to inventory so both
don't have to be true (it doesn't have to be alongside playbook +
inventory).

I do need to investigate whether group_vars/host_vars directly in playbook
directories are happy or not, and if not, why and under what conditions.

**Comment by mpdehaan** [comment] 2013-10-07 19:28
Sorry for not attending to this ticket closure earlier.

I just did a quick check of the above and playbook directory group_vars are loading in fine, so I'm closing this, which confirms what @bcoca said above.

Tested on 1.4 (devel) though should be equally applicable on 1.3.X.

**Closed as completed by mpdehaan** 2013-10-07 19:28 UTC
Labels: bug

**Comment by AdmiralNemo** [comment] 2014-06-11 18:38
This issue definitely exists; I can reproduce it with these 3 files:

test.yml:

```
- hosts: all
  gather_facts: False
  tasks:
    - add_host: name={{ inventory_hostname }}
                group=test
- hosts: test
  gather_facts: False
  tasks:
    - debug: "msg='{{ myvar }}'"
```

group_vars/test:

```
myvar: foo
```

hosts:

```
dhatch-l    ansible_connection=local ansible_python_interpreter=/usr/bin/python2
[test]
```

Run the playbook with

```
ansible-playbook -i hosts test.yml
```

And you get this output:

```
PLAY [all] ******************************************************************** 

TASK: [add_host name={{inventory_hostname}} group=test] *********************** 
ok: [dhatch-l]

PLAY [test] ******************************************************************* 

TASK: [debug msg='{{myvar}}'] ************************************************* 
fatal: [dhatch-l] => One or more undefined variables: 'myvar' is undefined

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/dhatch/test.retry

dhatch-l                   : ok=1    changed=0    unreachable=1    failed=0   
```

Even if you add a host to the `[test]` group in the inventory file, the host added to it dynamically does not get the definition for `myvar`.

Tested with Ansible 1.5.5 on Gentoo and Ansible 1.6.3 on RHEL 7.
