### ISSUE TITLE
'command' module expands environment variables, whereas 'shell' does not

### ISSUE THREAD

**Issue by w-miller** [ansible/ansible#16394] opened 2016-06-22 09:14 UTC
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 1.9.4
  configured module search path = None
```

Also tested with current Ansible dev branch.
##### CONFIGURATION

No changes to stock Ansible configuration.
##### OS / ENVIRONMENT

Centos 7.2, running on localhost.
##### SUMMARY

The [documentation for the 'command' module](https://github.com/ansible/ansible-modules-core/blob/stable-1.9/commands/command.py#L37) states that variables will _not_ be expanded in commands passed to the 'command' module, and that you should instead use the 'shell' module for shell expansion. In actual fact, the behaviour is the opposite of this: variables _are_ expanded using the 'command' module, but _not_ using the 'shell' module. [This line of code appears to be the culprit](https://github.com/ansible/ansible/blob/stable-1.9/lib/ansible/module_utils/basic.py#L1467).
##### STEPS TO REPRODUCE

play.yaml:

```

---
- hosts: all
  tasks:
    - command: echo '$HOME'
      register: command_result

    - shell: echo '$HOME'
      register: shell_result

    - debug:
        msg: command_result is {{ command_result.stdout }}

    - debug:
        msg: shell_result is {{ shell_result.stdout }}
```

Execute the playbook.

##### EXPECTED RESULTS

```
PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [kolla]

TASK: [command echo '$HOME'] **************************************************
changed: [kolla]

TASK: [shell echo '$HOME'] ****************************************************
changed: [kolla]

TASK: [debug ] ****************************************************************
ok: [kolla] => {
    "msg": "command_result is $HOME"
}

TASK: [debug ] ****************************************************************
ok: [kolla] => {
    "msg": "shell_result is /root"
}

PLAY RECAP ********************************************************************
kolla                      : ok=5    changed=2    unreachable=0    failed=0
```
##### ACTUAL RESULTS

```
PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [kolla]

TASK: [command echo '$HOME'] **************************************************
changed: [kolla]

TASK: [shell echo '$HOME'] ****************************************************
changed: [kolla]

TASK: [debug ] ****************************************************************
ok: [kolla] => {
    "msg": "command_result is /root"
}

TASK: [debug ] ****************************************************************
ok: [kolla] => {
    "msg": "shell_result is $HOME"
}

PLAY RECAP ********************************************************************
kolla                      : ok=5    changed=2    unreachable=0    failed=0
```

**Comment by westsouthnight** [comment] 2016-06-22 09:58
I Thinks its not only in one space where we get the issue with remove environment variables, - what i know, imho, something we get in consul_kv module if try to set ANSIBLE_CONSUL_URL. That Environment variable not readed from Environment variables, and module everytime try connect to localhost.

http://stackoverflow.com/questions/36043393/set-environment-in-ansible-doesnt-seem-to-work/37950548#37950548

**Comment by jctanner** [comment] 2016-06-22 17:57
@w-miller have you tested with a more recent version of ansible?

**Comment by w-miller** [comment] 2016-06-24 11:45
Yes, the issue is present in the current dev branch.

**Comment by krzysztof-magosa** [comment] 2016-12-08 22:03
Bash does not interpolate variables in ''.

```
$ echo '$HOME'
$HOME
```

```
$ echo "$HOME"
/Users/km
```

**Comment by sivel** [comment] 2016-12-08 22:57
@krzysztof-magosa is correct.  The problem is that you have used single quotes instead of double.

The reason it is being expanded in command, is due to some functionality to attempt resolving vars in the args, when not running through a shell as can be seen here:

https://github.com/ansible/ansible/blob/f1812b0f1591e6f3f1d599738ec30b3d5c0f60ae/lib/ansible/module_utils/basic.py#L2212-L2214

If you are using `shell`, we let the shell handle that expansion.  If using command, you will not get that expansion, so we do it before the command is actually executed.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Closed as completed by sivel** 2016-12-08 22:57 UTC
Labels: affects_1.9, bug
