### ISSUE TITLE
apt package with non-ascii filename fails

### ISSUE THREAD

**Issue by langemeijer** [ansible/ansible#4891] opened 2013-11-13 13:54 UTC
Running this playbook:

```

---
- hosts: all
  user: root
  tasks:

  - name: Make sure aspell-es package is installed
    apt: pkg=aspell-es state=latest
```

Will install the aspell-es package on the first run, but when ran a second time the apt module crashes with the following output:

```
TASK: [Make sure aspell-es package is installed] ****************************** 
failed to parse json:     force=force_yes)
  File "/root/.ansible/tmp/ansible-1384349137.11-11362832900179/apt", line 202, in install
    installed, upgradable, has_files = package_status(m, name, version, cache, state='install')
  File "/root/.ansible/tmp/ansible-1384349137.11-11362832900179/apt", line 155, in package_status
    has_files = len(pkg.installed_files) > 0
  File "/usr/lib/python2.7/dist-packages/apt/package.py", line 1052, in installed_files
    return file_list.read().decode("utf-8").split(u"\n")
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf1 in position 667: invalid continuation byte

fatal: [www4.procurios.net] => Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 382, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 471, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 659, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/usr/lib/pymodules/python2.7/ansible/runner/action_plugins/normal.py", line 54, in run
    return self.runner._execute_module(conn, tmp, module_name, module_args, inject=inject, complex_args=complex_args)
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 357, in _execute_module
    data = utils.parse_json(res['stdout'])
  File "/usr/lib/pymodules/python2.7/ansible/utils/__init__.py", line 288, in parse_json
    tokens = shlex.split(data)
  File "/usr/lib/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "/usr/lib/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/usr/lib/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/usr/lib/python2.7/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation


FATAL: all hosts have already failed -- aborting

```

in apt main() the output from apt.Cache() is stored into the cache variable this variable is used in package_status()
 has_files = len(pkg.installed_files) > 0

aspell-es is failing because it contains the file '/usr/lib/aspell/español.alias'
http://packages.debian.org/wheezy/all/aspell-es/filelist

**Comment by jctanner** [comment] 2013-11-13 14:00
@langemeijer what version of ansible playbook?

I'm not able to reproduce with current devel ...

```
jtanner@u1304:~/issues/4891-apt-non-ascii-package$ ansible-playbook -i inventory site.yml 

PLAY [localhost] ************************************************************** 

TASK: [apt pkg=aspell-es state=latest] **************************************** 
changed: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=1    changed=1    unreachable=0    failed=0   

```

**Comment by langemeijer** [comment] 2013-11-13 14:07
1.3.1, 1.3.2, 1.3.3 1.3.4 and current devel tested. 1.2.3 was fine. 

Did you run it twice? The first run will be ok, only when the installed_files is present in the cache when the package is already installed the problem occurs.

**Comment by jctanner** [comment] 2013-11-13 14:08
@langemeijer Yep, I'm seeing the traceback on the second run now. I'll debug/fix.

**Comment by langemeijer** [comment] 2013-11-13 14:10
Impressed with the speed you are responding. fwiw: We tried fixing the code ourselves, but failed.

**Comment by jctanner** [comment] 2013-11-13 14:49
@langemeijer the patch I just committed will catch the error and proceed as if there were files installed. Maybe not the most accurate behavior, but it does fix the traceback.

**Closed as completed** 2013-11-13 14:49 UTC
Labels: bug

**Comment by langemeijer** [comment] 2013-11-14 20:17
Excellent solution. If there are no files this error could never occur. I'm assuming this issue was caused by a problem in the python-apt library. Do we need to get this issue fixed upstream?

**Comment by jctanner** [comment] 2013-11-14 20:24
@langemeijer yeah, it's python-apt at fault. I can't really spend the time to research it upstream, but i did find some related bugs for ubuntu, so I'm guessing someone knows about it.
