### ISSUE TITLE
In a with_ loop, the "command" module doesn't fail when script exit status != 0, always returns changed

### ISSUE THREAD

**Issue by sacrelege** [ansible/ansible#11769] opened 2015-07-28 13:03 UTC
Issue Type: Bug Report

Ansible Version: 
ansible 2.0.0 (devel aa5bd8c2b5) last updated 2015/07/28 14:27:18 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 291fef3b34) last updated 2015/07/20 16:27:51 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD ff2386faf4) last updated 2015/07/20 16:27:51 (GMT +200)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/07/01 10:23:05 (GMT +200)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/07/01 10:23:08 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = /usr/share/ansible

Ansible Configuration:
No change in default configuration

Environment:
Ubuntu 15.04

Summary:
The "command" module doesn't fail when script exit status != 0

Steps To Reproduce:
It seems to work fine in 1.9.2 but not in ansible 2.0.0 (devel aa5bd8c2b5).

The easiest example to reproduce is running the following script:

```
#!bin/bash
exit 4
```

with the following play

```
name: doesnt fail in ansible 2.x.x 
command: testscript.sh
```

**Comment by bcoca** [comment] 2015-07-28 13:09
so i tested directly

```
ansible -a '/bin/false' testhost
nyx | FAILED | rc=1 >>
```

and with a copy of your script

```
ansible -a '/home/bcoca/badscript.sh' localhost
localhost | FAILED | rc=2 >>
[Errno 2] No such file or directory
```

and with a corrected copy of your script (shebang)

```
ansible -a '/home/bcoca/badscript.sh' localhost
localhost | FAILED | rc=4 >>
```

in a play

```
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "cmd": "/home/bcoca/badscript.sh", 
    "failed": true, 
    "msg": "[Errno 2] No such file or directory", 
    "rc": 2
}
```

in a play corrected

```

fatal: [localhost]: FAILED! => {
    "changed": true, 
    "cmd": [
        "/home/bcoca/badscript.sh"
    ], 
    "delta": "0:00:00.003200", 
    "end": "2015-07-28 09:09:35.482134", 
    "rc": 4, 
    "start": "2015-07-28 09:09:35.478934", 
    "stderr": "", 
    "stdout": "", 
    "stdout_lines": [], 
    "warnings": []
}
```

**Comment by bcoca** [comment] 2015-07-28 13:34
from IRC was able to reproduce in a with_ loop

```
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - command: "{{item}}"
      with_items:
        - /bin/false
        - /home/bcoca/badscript.sh

```

output

```
changed: [localhost] => {
    "changed": true,                                                                                                                                                                                     
    "msg": "All items completed",                                                                                                                                                                        
    "results": [                                                                                                                                                                                         
        {                                                                                                                                                                                                
            "changed": true, 
            "cmd": [
                "/bin/false"
            ], 
            "delta": "0:00:00.004091", 
            "end": "2015-07-28 09:34:25.037168", 
            "item": "/bin/false", 
            "rc": 1, 
            "start": "2015-07-28 09:34:25.033077", 
            "stderr": "", 
            "stdout": "", 
            "stdout_lines": [], 
            "warnings": []
        }, 
        {
            "changed": true, 
            "cmd": [
                "/home/bcoca/badscript.sh"
            ], 
            "delta": "0:00:00.003150", 
            "end": "2015-07-28 09:34:25.154616", 
            "item": "/home/bcoca/badscript.sh", 
            "rc": 4, 
            "start": "2015-07-28 09:34:25.151466", 
            "stderr": "", 
            "stdout": "", 
            "stdout_lines": [], 
            "warnings": []
        }
    ]
}
```

**Comment by bcoca** [comment] 2015-07-28 13:36
output in 1.9:

```
failed: [localhost] => (item=/bin/false) => {"changed": true, "cmd": ["/bin/false"], "delta": "0:00:00.002939", "end": "2015-07-28 09:37:06.062142", "item": "/bin/false", "rc": 1, "start": "2015-07-28 09:37:06.059203", "warnings": []}
failed: [localhost] => (item=/home/bcoca/badscript.sh) => {"changed": true, "cmd": ["/home/bcoca/badscript.sh"], "delta": "0:00:00.004518", "end": "2015-07-28 09:37:06.198623", "item": "/home/bcoca/badscript.sh", "rc": 4, "start": "2015-07-28 09:37:06.194105", "warnings": []}

FATAL: all hosts have already failed -- aborting
```

**Comment by jimi-c** [comment] 2015-07-28 14:15
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by jimi-c** [comment] 2015-07-28 14:16
Note that we're still sorting out a display issue with the above, so the output from 2.0 does not yet match that from 1.9.

Thanks!

**Closed as completed by jimi-c** 2015-07-28 14:15 UTC
Labels: P2, bug

**Comment by sacrelege** [comment] 2015-07-28 14:23
Thanks you very much. I can confirm it behaves now as expected.
