### ISSUE TITLE
Only first include of role is executed! 

### ISSUE THREAD

**Issue by deviscalio** [ansible/ansible#12035] opened 2015-08-21 08:26 UTC
Issue Type:
Bug Report

Ansible Version:
ansible --version
ansible 2.0.0

Environment:
Ubuntu 15.04

Summary:
I have a role with tasks/main.yml like this:
- include: packages.yml
- include: config-cluster.yml
- include: config.yml
- include: service.yml
- include: cluster.yml
- include: rabbitmq.yml
- include: queues.yml
  tags: queues
- meta: flush_handlers

When I use this role from my playbook only first include is executed.
- hosts: serverdev
  user: root
  roles:
  - role.rabbitmq

Expected Results:

Run all includes

Actual Results:
This is the output of command "ansible-playbook serverdev.yml":
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [trr-rabbit-dev2]
ok: [trr-rabbit-dev1]

TASK [tierra.rabbitmq : include] ***********************************************
included: packages.yml for trr-rabbit-dev1
included: packages.yml for trr-rabbit-dev2

TASK [tierra.rabbitmq : Ensure Epel is installed] ******************************
ok: [trr-rabbit-dev2]
ok: [trr-rabbit-dev1]

TASK [tierra.rabbitmq : Ensure Erlang repo is installed] ***********************
ok: [trr-rabbit-dev2]
ok: [trr-rabbit-dev1]

TASK [tierra.rabbitmq : Ensure RabbitMQ RPM key is present] ********************
ok: [trr-rabbit-dev2]
ok: [trr-rabbit-dev1]

TASK [tierra.rabbitmq : Ensure RabbitMQ is installed] **************************
ok: [trr-rabbit-dev2]
ok: [trr-rabbit-dev1]

PLAY RECAP *********************************************************************
trr-rabbit-dev1            : ok=6    changed=0    unreachable=0    failed=0  
trr-rabbit-dev2            : ok=6    changed=0    unreachable=0    failed=0

**Comment by alfetopito** [comment] 2015-08-21 20:44
Is duplicated by https://github.com/ansible/ansible/issues/12039

I managed to get the include working by resetting back to a week old commit: 4068598c159214ba47392cfb1fc2410847d7529d

**Comment by bcoca** [comment] 2015-08-21 22:03
closing as dupe of #12039

**Closed as completed** 2015-08-24 23:13 UTC
Labels: P1, bug
