### ISSUE TITLE
Importing e.g. ansible.inventory has strange terminal side effects

### ISSUE THREAD

**Issue by Julian** [ansible/ansible#16384] opened 2016-06-21 17:42 UTC
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = /Users/Julian/.config/ansible/config.ini
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

`ansible.utils.color` has side effects on import.

This can make things as simple as wanting to `import ansible.inventory` throw a traceback:

```
  File "floodgate/inventory/ansible.py", line 3, in <module>
    from ansible.inventory.ini import InventoryParser
  File "/Users/Julian/.local/share/virtualenvs/ansible/lib/python2.7/site-packages/ansible/inventory/__init__.py", line 36, in <module>
    from ansible.plugins import vars_loader
  File "/Users/Julian/.local/share/virtualenvs/ansible/lib/python2.7/site-packages/ansible/plugins/__init__.py", line 38, in <module>
    from ansible.utils.display import Display
  File "/Users/Julian/.local/share/virtualenvs/ansible/lib/python2.7/site-packages/ansible/utils/display.py", line 37, in <module>
    from ansible.utils.color import stringc
  File "/Users/Julian/.local/share/virtualenvs/ansible/lib/python2.7/site-packages/ansible/utils/color.py", line 32, in <module>
    curses.setupterm()
TypeError: argument must be an int, or have a fileno() method.
```

if `sys.stdout` (which is the default for `setupterm`) is not backed by a real file.
##### EXPECTED RESULTS

No side effects unless some sort of initialization is run. Just handling the possible exception in that block of `ansible.utils.color` would be an alternate smaller change which would help at least for not crashing.

**Comment by bcoca** [comment] 2016-06-21 17:47
can you show a simple playbook that reproduces this issue?

**Comment by Julian** [comment] 2016-06-21 17:51
@bcoca 

```
⊙ python -c 'import sys; import StringIO; sys.stdout = StringIO.StringIO(); sys.stdout.isatty = lambda : True; import ansible.inventory.ini'                                                                                                                                                                        Julian@Macnetic
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/Julian/.local/share/virtualenvs/ansible/lib/python2.7/site-packages/ansible/inventory/__init__.py", line 36, in <module>
    from ansible.plugins import vars_loader
  File "/Users/Julian/.local/share/virtualenvs/ansible/lib/python2.7/site-packages/ansible/plugins/__init__.py", line 38, in <module>
    from ansible.utils.display import Display
  File "/Users/Julian/.local/share/virtualenvs/ansible/lib/python2.7/site-packages/ansible/utils/display.py", line 37, in <module>
    from ansible.utils.color import stringc
  File "/Users/Julian/.local/share/virtualenvs/ansible/lib/python2.7/site-packages/ansible/utils/color.py", line 32, in <module>
    curses.setupterm()
TypeError: argument must be an int, or have a fileno() method.
```

**Comment by bcoca** [comment] 2016-06-21 18:09
we do not support arbitrary python imports of the API, since this is not a bug in the existing ansible CLI tools I"m going to close this ticket.

**Closed as completed by bcoca** 2016-06-21 18:09 UTC

**Comment by Julian** [comment] 2016-06-21 18:14
Oh. That's interesting. Got it. Ansible's code isn't public API? Are any
parts of it public?

**Comment by Julian** [comment] 2016-06-21 19:26
Or more specifically, what public API exists currently for just parsing an inventory file? `ansible --list-hosts` produces not very machine readable output.

**Comment by sivel** [comment] 2016-06-21 19:32
@Julian technically speaking, there are no public programatic APIs.  The only public "APIs" are the command line utilities (ansible/ansible-playbook/etc...)

If you are interested in sample code for parsing an inventory file, and processing it have a look at the following unsupported example at https://gist.github.com/sivel/3c0745243787b9899486

If you have further questions, please move your discussion to the mailing list.  We won't be actively monitoring comments on closed issues.

**Comment by Julian** [comment] 2016-06-21 19:43
Right I'm including the CLIs I guess -- there doesn't seem to be one to just print a list of hosts, and the example code you linked won't work because of the issue in this ticket, but I'll move to the ML. Thanks.
