### ISSUE TITLE
wait_for sporadically fails on random hosts with `ValueError: cannot mmap an empty file`

### ISSUE THREAD

**Issue by tannerjfco** [ansible/ansible#80711] opened 2023-05-03 17:14 UTC
### Summary

_Note:_  This issue is being reported for ansible v.2.14.5 on python 3.10.6, however we started encountering this issue on ansible 2.13.4 on python 3.8.10

We have a number of `wait_for` tasks that detect events in log files to determine whether the rest of the ansible play can proceed. Generally these tasks work as expected, but we encounter errors such as the one below sporadically.

```
fatal: [node11]: FAILED! => {"changed": false, "module_stderr": "Shared connection to <ip> closed.\r\n", "module_stdout": "/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (C.UTF-8)\r\nTraceback (most recent call last):\r\n  File \"/home/****/.ansible/tmp/ansible-tmp-1683073045.9051418-3490-160423116003082/AnsiballZ_wait_for.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/****/.ansible/tmp/ansible-tmp-1683073045.9051418-3490-160423116003082/AnsiballZ_wait_for.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/****/.ansible/tmp/ansible-tmp-1683073045.9051418-3490-160423116003082/AnsiballZ_wait_for.py\", line 48, in invoke_module\r\n    run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\r\n    fname, loader, pkg_name)\r\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\r\n    mod_name, mod_fname, mod_loader, pkg_name)\r\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\r\n    exec code in run_globals\r\n  File \"/tmp/ansible_wait_for_payload_9lqbgz/ansible_wait_for_payload.zip/ansible/modules/wait_for.py\", line 689, in <module>\r\n  File \"/tmp/ansible_wait_for_payload_9lqbgz/ansible_wait_for_payload.zip/ansible/modules/wait_for.py\", line 589, in main\r\nValueError: cannot mmap an empty file\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

There doesn't seem to be a rhyme or reason to when we encounter the issue. We can go days to weeks without seeing it in any of our pipelines or target environments, or we can have days where we see the issue on almost every play. The target environments have 7-28 hosts, and we'll typically see the failure affect 1-4 hosts. The specific hosts the task fails on are different almost every time. In all cases, it is ensured and confirmed that the file being watched exists and readable on all hosts. In all cases, the event string we want to detect in this task is present on the target hosts within the task's configured timeout

Checking existing issues, we see #79683 reported that suggests `wait_for` was changed from using `read()` to `mmap()` in https://github.com/ansible/ansible/commit/9d4ced1237380051334b54379ff64e45c0341a6d. While that issue is different from the one we see, 

### Issue Type

Bug Report

### Component Name

wait_for

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.5]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
[DEPRECATION WARNING]: DEFAULT_GATHER_TIMEOUT option, the module_defaults keyword is a more generic version and can apply to all calls to the M(ansible.builtin.gather_facts) or M(ansible.builtin.setup) actions, use module_defaults instead.
This feature will be removed from ansible-core in version 2.18. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
CONFIG_FILE() = /etc/ansible/ansible.cfg
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 40
DEFAULT_GATHER_TIMEOUT(/etc/ansible/ansible.cfg) = 60
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 60
INVENTORY_UNPARSED_IS_FAILED(/etc/ansible/ansible.cfg) = True

CONNECTION:
==========

paramiko_ssh:
____________
ssh_args(/etc/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=7200s

ssh:
___
reconnection_retries(/etc/ansible/ansible.cfg) = 3
ssh_args(/etc/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=7200s
timeout(/etc/ansible/ansible.cfg) = 60
```

### OS / Environment

Ansible controller running on Ubuntu 22.04, with the issue also previously observed when the controller was running on Ubuntu 20.04

The target hosts of the plays have a spread of currently supported major LTS-equivalent distributions - ubuntu 18/20/22, RHEL 7/8, Centos7

### Steps to Reproduce

```yaml (paste below)
- name: detect now frozen marker
  wait_for:
    path: "/path/to/logfile"
    search_regex: "Dispatch: Preparing to Handle Request \\[ eventName = \\'(IN_CLOSE_WRITE|CREATE)\\', triggerFile = \\'now_frozen\\.mf\\' \\]"
    timeout: 900
  register: yahcli_freeze_upgrade_frozen_post_0_3_0
```

### Expected Results

I expect all hosts to return result `ok: [<host>]` 

### Actual Results

```console
TASK [yahcli : detect now frozen marker] ***
fatal: [node11]: FAILED! => {"changed": false, "module_stderr": "Shared connection to <ip> closed.\r\n", "module_stdout": "/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (C.UTF-8)\r\nTraceback (most recent call last):\r\n  File \"/home/****/.ansible/tmp/ansible-tmp-1683073045.9051418-3490-160423116003082/AnsiballZ_wait_for.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/****/.ansible/tmp/ansible-tmp-1683073045.9051418-3490-160423116003082/AnsiballZ_wait_for.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/****/.ansible/tmp/ansible-tmp-1683073045.9051418-3490-160423116003082/AnsiballZ_wait_for.py\", line 48, in invoke_module\r\n    run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\r\n    fname, loader, pkg_name)\r\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\r\n    mod_name, mod_fname, mod_loader, pkg_name)\r\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\r\n    exec code in run_globals\r\n  File \"/tmp/ansible_wait_for_payload_9lqbgz/ansible_wait_for_payload.zip/ansible/modules/wait_for.py\", line 689, in <module>\r\n  File \"/tmp/ansible_wait_for_payload_9lqbgz/ansible_wait_for_payload.zip/ansible/modules/wait_for.py\", line 589, in main\r\nValueError: cannot mmap an empty file\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
ok: [node02]
ok: [node13]
ok: [node18]
ok: [node00]
ok: [node06]
ok: [node27]
ok: [node15]
ok: [node14]
ok: [node25]
ok: [node04]
ok: [node17]
ok: [node19]
ok: [node16]
ok: [node12]
ok: [node03]
ok: [node08]
ok: [node05]
ok: [node22]
ok: [node10]
ok: [node01]
ok: [node07]
ok: [node24]
ok: [node26]
ok: [node09]
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by nitzmahone** [comment] 2023-05-04 19:21
closing as duplicate of #79683 (same underlying cause)

**Closed as not planned by nitzmahone** 2023-05-04 19:21 UTC
Labels: module, bug, traceback, P3, affects_2.14
