### ISSUE TITLE
Use custom known_hosts file with ansible-pull 

### ISSUE THREAD

**Issue by aschwanb** [ansible/ansible#18201] opened 2016-10-26 13:22 UTC
# ISSUE TYPE
- Bug Report
##### COMPONENT NAME

ansible-pull
##### ANSIBLE VERSION

```
ansible 2.1.2.0
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Not sure if this is a problem or just me doing it wrong, but I can not add a custom path for the known_hosts file for ansible-pull.
##### STEPS TO REPRODUCE

By default, ansible-pull uses the known_hosts file located at `~/.ssh/known_hosts` but I should be able to add a custom one with `--ssh-common-args=UserKnownHostsFile=~/my_temporary_known_host`
Unfortunately, this setting is ignored by ansible-pull and the git checkout fails.

```
Starting Ansible Pull at 2016-10-26 15:06:29
/usr/local/mydir/bin/ansible-pull -i myinventory -U ssh://git@mygit -C master --private-key=mykey --ssh-common-args=UserKnownHostsFile=~/my_temporary_known_host
localhost | FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "mygit has an unknown hostkey. Set accept_hostkey to True or manually add the hostkey prior to running the git module"
}
```

**Comment by mscherer** [comment] 2016-10-27 22:59
I do not think that would work, because ssh-common-args is used by the connexion plugin, not by the git module. However, I guess we would look at doing something on the git side.

**Comment by aschwanb** [comment] 2016-10-28 07:05
The ssh-common-args show up under the connection options in `ansible-pull -h`. Maybe the man page entry should be changed?

It would be fine to just pass that option to the git module. Is there a way to do that with ansible-pull?

**Comment by mscherer** [comment] 2016-10-28 07:39
So we have 2 issues:
- the command-line options doc is likely incorrect. I checked the code, the option is not here
- we need to add options.

Another solution would be to modify /etc/ssh/config before running ansible-pull, what is the workflow you try to achieve ?

**Comment by aschwanb** [comment] 2016-10-28 08:47
Thanks for the fast reply.

I would like to run ansible-pull on my client machines (not servers). Because I don't want users messing with the configuration, I'm trying to have it self-contained in a separate directory.

It's working great so far. The only thing missing is a separate `known_hosts` file, but because I want it self-contained, modifying `/etc/ssh/config` is likely not an option.

**Comment by sivel** [comment] 2019-03-01 16:29
Ultimately this will become a duplicate of https://github.com/ansible/ansible/issues/48678 which aims to expose passing arbitrary arguments to the underlying version control module used by ansible-pull

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Closed as completed by sivel** 2019-03-01 16:29 UTC
Labels: affects_2.1, c:cli/pull, support:core, bug
