### ISSUE TITLE
Ansible 2.4 : all BigIP modules are not working

### ISSUE THREAD

**Issue by broferek** [ansible/ansible#31341] opened 2017-10-05 08:16 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

BigIP modules

##### ANSIBLE VERSION

```
ansible 2.4.0.0
```

##### CONFIGURATION

DEFAULT_ACTION_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible/plugins/action', u'/opt/kookel/kelkoo_ansible/plugins/action']
DEFAULT_CALLBACK_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible/plugins/callback', u'/opt/kookel/kelkoo_ansible/plugins/callback']
DEFAULT_FILTER_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible/plugins/filter', u'/opt/kookel/kelkoo_ansible/plugins/filter']
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 50
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = explicit
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/inventories']
DEFAULT_MANAGED_STR(/etc/ansible/ansible.cfg) = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}. Do not modify it manually
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/opt/kookel/kelkoo_ansible/modules']
DEFAULT_PRIVATE_KEY_FILE(/etc/ansible/ansible.cfg) = /opt/kookel/.ssh/kookel_ansible_rsa
DEFAULT_REMOTE_TMP(/etc/ansible/ansible.cfg) = /tmp
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = root
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/opt/kookel/ansible/common/playbooks/roles']
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = debug
DEFAULT_TRANSPORT(/etc/ansible/ansible.cfg) = ssh
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
SYSTEM_WARNINGS(/etc/ansible/ansible.cfg) = True

##### OS / ENVIRONMENT

Centos 6.9

##### SUMMARY

All BigIP modules fails with an exception of a class in the new f5-sdk library

##### STEPS TO REPRODUCE

```yaml
- hosts: "localhost"
  tasks:
    - name: Create the node in BigIP
      bigip_node:
        server: "{{ bigip_dc.server }}"
        user: "{{ credential.bigip.user }}"
        password: "{{ credential.bigip.password }}"
        state: "present"
        name: "{{ inventory_hostname_short }}"
        host: "{{ server_ip }}"
        description: "{{ inventory_hostname_short }}"
        validate_certs: false
```

##### EXPECTED RESULTS

I expect the node to be created in our F5 BigIP

##### ACTUAL RESULTS

We have a Python syntax issue

```
Traceback (most recent call last):
File "/tmp/ansible_YPCTIj/ansible_module_bigip_pool.py", line 237, in 
from ansible.module_utils.f5_utils import (
File "/tmp/ansible_YPCTIj/ansible_modlib.zip/ansible/module_utils/f5_utils.py", line 143, in 
File "/usr/lib/python2.6/site-packages/f5/bigip/__init__.py", line 26, in 
from f5.bigip.cm import Cm
File "/usr/lib/python2.6/site-packages/f5/bigip/cm/__init__.py", line 19, in 
from f5.bigip.cm.autodeploy import Autodeploy
File "/usr/lib/python2.6/site-packages/f5/bigip/cm/autodeploy/__init__.py", line 20, in 
from f5.bigip.cm.autodeploy.software_images import Software_Image_Downloads
File "/usr/lib/python2.6/site-packages/f5/bigip/cm/autodeploy/software_images.py", line 23, in 
from f5.bigip.resource import PathElement
File "/usr/lib/python2.6/site-packages/f5/bigip/resource.py", line 724
no_meta_dict = {k: v for k, v in iteritems(self.__dict__)
^
SyntaxError: invalid syntax
```

**Comment by samdoran** [comment] 2017-10-05 17:57
My guess is this is a Python 2.6 issue. Can you provide details on your Python version and try running with Python 2.7 to see if the issue still exists?

needs_info

**Comment by broferek** [comment] 2017-10-06 05:19
Hi,

here is my Python version : Python 2.6.6

I'll let you know what I find out if I can test with 2.7

Thanks,

Ludo

**Comment by bcoca** [comment] 2017-10-06 05:21
dict comprehensions are not available until 2.7, code needs to be updated

**Comment by broferek** [comment] 2017-10-06 05:28
Thanks Brian,

This is bad as Python 2.6.6 is delivered with Centos 6.9 and it really prevents us from upgrading to 2.4.

Shall we open an issue on f5-sdk github with a reference to this one?

Thanks,

Ludo

**Comment by bcoca** [comment] 2017-10-06 12:49
@broferek yes, closing this as the issue is not with the module in the ansible repo but with the library imported. 

If they decline to fix this in the library, we should update the requirements in the bigip modules to reflect they only work with py2.7 and above.

**Closed as completed by bcoca** 2017-10-06 12:49 UTC
Labels: affects_2.4, support:core, bug

**Comment by broferek** [comment] 2017-10-11 14:51
@bcoca the issue has been closed on f5-sdk side.
I think the documentation has to be updated to reflect that the modules can no longer work with Python 2.6

Thanks,

Ludo
