### ISSUE TITLE
stat, command etc module error when using "name" in tasks

### ISSUE THREAD

**Issue by shrikeh** [ansible/ansible#11466] opened 2015-07-02 09:34 UTC
Using: devel version of ansible

steps to reproduce:
Create a task as:

```
- name: Check if JumpCloud is already installed
  stat: 
   path: /opt/jc
  register: jc_installed
```

Expected result: information on directory, whether or not the directory actually exists, populated to the variable jc_installed.

Actual result: playbook refuses to run, with the following message:

```

ERROR! this task 'stat' has extra params, which is only allowed in the following modules: command, shell, script, include, include_vars, add_host, group_by, set_fact, raw, meta

The error appears to have been in '[playbook-dir]/roles/jumpcloud/tasks/main.yml': line 2, column 3, but may be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- name: Check if JumpCloud is already installed
  ^ here
```

**Comment by jhawkesworth** [comment] 2015-07-02 10:42
I think you just have a syntax error
from http://docs.ansible.com/stat_module.html I can see path is mandatory
parameter to stat,

I think the following is likely to fix:
- name: Check if JumpCloud is already installed
  stat: path=/opt/jc
  register: jc_installed

or
- name: Check if JumpCloud is already installed
  stat:
    path: /opt/jc
  register: jc_installed

Hope this helps,

Jon

**Comment by jimi-c** [comment] 2015-07-21 20:36
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using your simple reproducer (path changed, to reflect a directory which exists on my test system):

<pre>
# cat 11466.yml 
- hosts: localhost
  gather_facts: no
  tasks:
  - name: Check if JumpCloud is already installed
    stat: 
     path: /opt
    register: jc_installed
TASK [Check if JumpCloud is already installed] **********************************
ok: [localhost] => {"changed": false, "stat": {"atime": 1408195884.0, "ctime": 1432922701.591172, "dev": 64769, "exists": true, "gid": 0, "gr_name": "root", "inode": 2883585, "isblk": false, "ischr": false, "isdir": true, "isfifo": false, "isgid": false, "islnk": false, "isreg": false, "issock": false, "isuid": false, "mode": "0755", "mtime": 1408195884.0, "nlink": 5, "path": "/opt", "pw_name": "root", "rgrp": true, "roth": true, "rusr": true, "size": 4096, "uid": 0, "wgrp": false, "woth": false, "wusr": true, "xgrp": true, "xoth": true, "xusr": true}}
</pre>

Per our normal policy, we close bug report issues when we see the issue has been corrected in the devel branch, so we will close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-07-21 20:36 UTC
Labels: bug
