### ISSUE TITLE
empty notify produces exception

### ISSUE THREAD

**Issue by gtirloni** [ansible/ansible#10873] opened 2015-04-29 14:22 UTC
Issue Type: Bug Report
Ansible Version: 1.9.0.1
Environment: CentOS 7.1.1503 x86_64
Summary: Invalid YAML is accepted and causes Runner exception
Steps to Reproduce:

```
$ cat broken.yml 

---
- name: invalid notify syntax
  hosts: localhost
  tasks:

    - debug:
        msg: "testing notify"
      notify:

$ ansible-playbook --syntax-check -i "localhost," broken.yml 

playbook: broken.yml

$ ansible-lint broken.yml 
$ echo $?
0

$ ansible-playbook -i "localhost," broken.yml 

PLAY [invalid notify syntax] ************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [debug ] **************************************************************** 
ok: [localhost] => {
    "msg": "testing notify"
}
Traceback (most recent call last):
  File "/home/gtirloni/virtualenv/dev/bin/ansible-playbook", line 323, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/gtirloni/virtualenv/dev/bin/ansible-playbook", line 263, in main
    pb.run()
  File "/home/gtirloni/virtualenv/dev/lib/python2.7/site-packages/ansible/playbook/__init__.py", line     348, in run
    if not self._run_play(play):
  File "/home/gtirloni/virtualenv/dev/lib/python2.7/site-packages/ansible/playbook/__init__.py", line     788, in _run_play
    if not self._run_task(play, task, False):
  File "/home/gtirloni/virtualenv/dev/lib/python2.7/site-packages/ansible/playbook/__init__.py", line     548, in _run_task
    if len(task.notify) > 0:
TypeError: object of type 'NoneType' has no len()
```

**Comment by jimi-c** [comment] 2015-07-13 14:22
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0). Here is the output using a version of your example above:

<pre>
# ansible-playbook -vv 10873.yml 
Using /etc/ansible/ansible.cfg as config file
1 plays in 10873.yml
PLAY: invalid notify syntax *****************************************************
TASK [setup] ********************************************************************
ok: [localhost]
TASK [debug msg=testing notify] *************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "testing notify"
}
PLAY RECAP **********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
</pre>

The cause for this working in devel is that empty entries like that are treated as `None` internally, which is the default value now for notify, meaning the field is ignored.

Per our normal policy, we close bug report issues when we see the issue has been corrected in the devel branch, so we will close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-07-13 14:22 UTC
Labels: bug
