### ISSUE TITLE
Using ansible 2.1.x breaks old playbooks (specifically "current working directory" reference changes)

### ISSUE THREAD

**Issue by gsharma-va** [ansible/ansible#16585] opened 2016-07-05 20:56 UTC
- Old Issue (Use as a reference)
  https://github.com/ansible/ansible/issues/13592
  Compared both results using the same playbook on ansible 1.9.4 and ansible 2.1.0.0
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
(1) ansible --version
ansible 1.9.4
  configured module search path = externals/libraries:/usr/share/ansible:/usr/local/share/ansible

(2) ansible --version
ansible 2.1.0.0
  config file = /home/deploy/GIT/ansible-jenkins-test-swarm-slaves/ansible.cfg
  configured module search path = ['externals/libraries', '/usr/share/ansible', '/usr/local/share/ansible']
```
##### CONFIGURATION

ansible.cfg

```
[ssh_connection]
timeout = 20
ssh_args =

[defaults]
roles_path = externals/roles
library = externals/libraries:/usr/share/ansible:/usr/local/share/ansible
forks = 20
transport = ssh
host_key_checking = false
jinja2_extensions = jinja2.ext.do
filter_plugins = externals/filter_plugins
```
##### OS / ENVIRONMENT

```
(a) cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.4 (Santiago)

(b) cat /etc/redhat-release
CentOS Linux release 7.1.1503 (Core)
```
##### SUMMARY

Current working directory points to where the playbook is being executed from instead of where it "actually" is stored. This has caused a lot of backward compatibility issues.
##### STEPS TO REPRODUCE

**WITH ANSIBLE 1.9.4**

```
(a) create "test.yml" 

---
- hosts: localhost
  become: no
  gather_facts: yes
  connection: local
  tasks:
    - debug: var=ansible_env.PWD
    - debug: var=ansible_version

(b) put this playbook under "/home/deploy/GIT/ansible-jenkins-test"

(c) Execute the playbook

[deploy@gs-rhel6u4-brn1-adt ansible-jenkins]$ ansible-playbook -i local, test.yml

PLAY [localhost] **************************************************************

GATHERING FACTS ***************************************************************
ok: [localhost]

TASK: [debug var=ansible_env.PWD] *********************************************
ok: [localhost] => {
    "var": {
         **"ansible_env.PWD": "/home/deploy/GIT/ansible-jenkins-test"**
    }
}

TASK: [debug var=ansible_version] *********************************************
ok: [localhost] => {
    "var": {
        "ansible_version": {
            "full": "1.9.4",
            "major": 1,
            "minor": 9,
            "revision": 4,
            "string": "1.9.4\n  configured module search path = externals/libraries:/usr/share/ansible:/usr/local/share/ansible"
        }
    }
}

PLAY RECAP ********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0

(d) Copy this playbook to a different location and execute it again from "/home/deploy/GIT/ansible-jenkins-test"

cp test.yml /tmp

[deploy@gs-rhel6u4-brn1-adt ansible-jenkins-test]$ ansible-playbook -i local, /tmp/test.yml

PLAY [localhost] **************************************************************

GATHERING FACTS ***************************************************************
ok: [localhost]

TASK: [debug var=ansible_env.PWD] *********************************************
ok: [localhost] => {
    "var": {
         **"ansible_env.PWD": "/tmp"**
    }
}

TASK: [debug var=ansible_version] *********************************************
ok: [localhost] => {
    "var": {
        "ansible_version": {
            "full": "1.9.4",
            "major": 1,
            "minor": 9,
            "revision": 4,
            "string": "1.9.4\n  configured module search path = externals/libraries:/usr/share/ansible:/usr/local/share/ansible"
        }
    }
}

PLAY RECAP ********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0

```

**WITH ANSIBLE 2.1.0.0**

```
(a) Use the same playbook (as above) test.yml and execute it.

[deploy@gs-centos7u1-brn1-adt ansible-jenkins-test]$ ansible-playbook -i local, test.yml

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "ansible_env.PWD": "/home/deploy/GIT/ansible-jenkins-test-swarm-slaves"
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "ansible_version": {
        "full": "2.1.0.0",
        "major": 2,
        "minor": 1,
        "revision": 0,
        "string": "2.1.0.0"
    }
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0

(b) Copy this playbook to /tmp and execute from the same location:

[deploy@gs-centos7u1-brn1-adt ansible-jenkins-test]$ ansible-playbook -i local, /tmp/test.yml

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
   "ansible_env.PWD": "/home/deploy/GIT/ansible-jenkins-test-swarm-slaves"
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "ansible_version": {
        "full": "2.1.0.0",
        "major": 2,
        "minor": 1,
        "revision": 0,
        "string": "2.1.0.0"
    }
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0

```
##### EXPECTED RESULTS

Why has the behavior changed ? This is causing many backward compatibility issues with old playbooks. 

Please verify if there are some configuration parameters that I'm not setting correctly.

**Comment by jctanner** [comment] 2016-07-08 14:06
@gsharma-va this behavior changed with 2.0, so it's not a regression in 2.1.

**Comment by jctanner** [comment] 2016-07-08 14:16
@gsharma-va the ansible_env.PWD variable is taken directly from os.environ['PATH'], so if the ansible command is being run from "/home/deploy/GIT/ansible-jenkins-test-swarm-slaves", then that is the directory that should be set for $PWD. The 2.0 behavior is correct and the 1.9 behavior was wrong because it was setting the underlying CWD. 

Are you running into a problem other than the ansible_env.PWD not being what you expected?

**Comment by JohnPeacockMessageSystems** [comment] 2016-07-13 16:47
Ah, so it was "fixed" so now we need to rewrite all of our playbooks?  This bit me as well because I was relying on the role search path being relative to the playbook itself NOT the execution directory.  I wonder what else will break because of this behavior change. @jctanner

**Comment by JohnPeacockMessageSystems** [comment] 2016-07-18 15:37
FWIW, my problem may be something slightly different, so I've opened #16747 with full example code.

**Comment by bcoca** [comment] 2016-07-23 00:38
dupe of #14489

**Closed as completed by bcoca** 2016-07-23 00:38 UTC
Labels: bug
