### ISSUE TITLE
git module reports change on update with nothing to update

### ISSUE THREAD

**Issue by profhase** [ansible/ansible#8096] opened 2014-07-11 08:07 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.6
##### Environment:

Ubuntu 12.04
##### Summary:

Using the git module and pulling from a branch (or HEAD, i.e. not defining a version) causes ansible notify that there is a change, even if there is none. (The verbose says: local modifications exist, though there are no local modifications)
##### Steps To Reproduce:
- hosts: myhosts
  tasks:
  - name: Update git repo
    git:
      dest=/my/webapp
      repo=repo@host:repos/my-webapp
      recursive=no
      update=yes
      accept_hostkey=yes
    sudo: yes
##### Expected Results:

ok [ myhost ] : Update git repo
##### Actual Results:

changed: [myhost] => {"after": "61b54a57dca2bb263a795541fd3cd9a8090aac45", "before": "61b54a57dca2bb263a795541fd3cd9a8090aac45", "changed": true, "msg": "Local modifications exist"}

**Comment by jimi-c** [comment] 2014-07-11 16:13
I believe this may be caused by the fact that there are local modifications. Could you stash those in that directory to see if the changed status goes back to false?

**Comment by profhase** [comment] 2014-07-12 10:25
There are definetely no lodal modifications. The issue is also reproduced by a user:
https://groups.google.com/forum/#!msg/ansible-project/xyBewW5AP4s/B5e_cloqK44J

**Comment by jimi-c** [comment] 2014-07-13 04:40
That's odd, the output from the module says there are: `"msg": "Local modifications exist"`

**Comment by josef-spak** [comment] 2014-09-02 07:06
This may be a wild guess, but do you use submodules? I think it's possible that the git module ignores the recursive=no argument under some conditions.

Edit: Also I think this could have been fixed in a later version (https://github.com/ansible/ansible/issues/7927). Could you try 1.7 or the devel branch?

**Comment by mpdehaan** [comment] 2014-09-29 20:23
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Closed as completed by mpdehaan** 2014-09-29 20:23 UTC
Labels: bug
