### ISSUE TITLE
Provide ansible_interfaces Details in setup

### ISSUE THREAD

**Issue by LukeShortCloud** [ansible/ansible#19527] opened 2016-12-19 18:27 UTC
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
setup (Core module)

##### ANSIBLE VERSION

```
ansible 2.2.0.0 (detached HEAD ba8e1f88a9) last updated 2016/10/20 13:40:25 (GMT -400)
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY

The "setup" module provides `ansible_interfaces` which is a list of network interfaces. It does not provide any information about them other than their name. Elsewhere in the setup output, a dictionary called `ansible_<INTERFACE>` (`ansible_eth0`, for example) has all of the details about the device including IP addressing, MAC addresses, and feature support.

There is no easy/clean way to reference an interface from `ansible_interfaces` to it's corresponding `ansible_<INTERFACE>` dictionary.

Here is my exact use case of generating all of getting all of the IP addresses and related subnet masks from each interface.

Current Implementation
```
{% for interface in ansible_interfaces %}
IPADDR{{ loop.index }}={{ hostvars[inventory_hostname]['ansible_%s' | format(interface)]['ipv4']['address'] }}
NETMASK{{ loop.index }}={{ hostvars[inventory_hostname]['ansible_%s' | format(interface)]['ipv4']['netmask'] }}
{% endfor %}
```

Ideal Implementation
```
{% for interface in ansible_interfaces %}
IPADDR{{ loop.index }}={{ ansible_interfaces[interface]['ipv4']['address'] }}
NETMASK{{ loop.index }}={{ ansible_interfaces[interface]['ipv4']['netmask'] }}
{% endfor %}
```

It would be nice to have either:

(1) Update "ansible_interfaces" to provide dictionaries of the interface information instead of just a list of their names.
```
        "ansible_interfaces": [
            "eth0": {
                "active": true,
                "device": "eth0",
                "features": {
<OMMITTED>    
                },
                "ipv4": {
                    "address": "192.168.0.44",
                    "broadcast": "192.168.0.255",
                    "netmask": "255.255.255.0",
                    "network": "192.168.0.0"
                },
                "ipv6": [
                    {
                        "address": "fe80::f816:3eff:feb0:3bcb",
                        "prefix": "64",
                        "scope": "link"
                    }
                ],
                "macaddress": "fa:16:3e:b0:3b:cb",
                "module": "virtio_net",
                "mtu": 1450,
                "pciid": "virtio0",
                "promisc": false,
                "type": "ether"
            },
        ],
```
OR
(2) A new top-level "ansible_interfaces_details" dictionary that contains the interface names (no "ansible_" prefix) as the dictionary of details.
```
        "ansible_interfaces_details": [
            "eth0": {
                "active": true,
                "device": "eth0",
                "features": {
<OMMITTED>    
                },
                "ipv4": {
                    "address": "192.168.0.44",
                    "broadcast": "192.168.0.255",
                    "netmask": "255.255.255.0",
                    "network": "192.168.0.0"
                },
                "ipv6": [
                    {
                        "address": "fe80::f816:3eff:feb0:3bcb",
                        "prefix": "64",
                        "scope": "link"
                    }
                ],
                "macaddress": "fa:16:3e:b0:3b:cb",
                "module": "virtio_net",
                "mtu": 1450,
                "pciid": "virtio0",
                "promisc": false,
                "type": "ether"
            },
        ],
```

##### STEPS TO REPRODUCE

```
$ ansible <ANSIBLE_HOST> -m setup
```

##### EXPECTED RESULTS

See suggested options (1) and (2) in the Summary section.

##### ACTUAL RESULTS

```
        "ansible_interfaces": [
            "lo",
            "bond0",
            "eth2",
            "eth1",
            "eth0"
        ],
```

**Comment by bcoca** [comment] 2016-12-19 20:06
dupe of #17953 #12731

**Closed as completed by bcoca** 2016-12-19 20:06 UTC
Labels: windows, affects_2.2, module, feature
