### ISSUE TITLE
Ansible installation failing

### ISSUE THREAD

**Issue by electricmind007** [ansible/ansible#76458] opened 2021-12-03 16:56 UTC
### Summary

I could not able to install ansible which is failing. Please check and help me on the steps how to install it successfully using pip3 install ansible command. I believe it worked fine before some days. Was there any new issue happened?

Logs: sudo pip3 install ansible
The directory '/home/murugesan/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/murugesan/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting ansible
  Downloading https://files.pythonhosted.org/packages/51/d6/2fe0f449844d489fe1a915d2c8da5a115e0d001889f31e6d2f6786e00d74/ansible-5.0.0.tar.gz (38.4MB)
    100% |████████████████████████████████| 38.5MB 25kB/s 
Collecting ansible-core<2.13,>=2.12.0 (from ansible)
  Could not find a version that satisfies the requirement ansible-core<2.13,>=2.12.0 (from ansible) (from versions: 0.0.1a1, 2.11.0b1, 2.11.0b2, 2.11.0b3, 2.11.0b4, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.11.1rc1, 2.11.1, 2.11.2rc1, 2.11.2, 2.11.3rc1, 2.11.3, 2.11.4rc1, 2.11.4, 2.11.5rc1, 2.11.5, 2.11.6rc1, 2.11.6, 2.11.7rc1)
No matching distribution found for ansible-core<2.13,>=2.12.0 (from ansible)

Environment details:
murugesan@murugesan-VirtualBox:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

### Issue Type

Bug Report

### Component Name

pip

### Ansible Version

```console
$ ansible --version
ansible 5.0.0
```

### Configuration

```console
$ ansible-config dump --only-changed
NA
```

### OS / Environment

Ubuntu 18.04

murugesan@murugesan-VirtualBox:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

### Steps to Reproduce

```yaml (paste below)

```
sudo pip3 install ansible

### Expected Results

Successful installation

### Actual Results

```console
I could not able to install ansible which is failing. Please check and help me on the steps how to install it successfully using pip3 install ansible command. I believe it worked fine before some days. Was there any new issue happened?

Logs: sudo pip3 install ansible
The directory '/home/murugesan/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/murugesan/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting ansible
  Downloading https://files.pythonhosted.org/packages/51/d6/2fe0f449844d489fe1a915d2c8da5a115e0d001889f31e6d2f6786e00d74/ansible-5.0.0.tar.gz (38.4MB)
    100% |████████████████████████████████| 38.5MB 25kB/s 
Collecting ansible-core<2.13,>=2.12.0 (from ansible)
  Could not find a version that satisfies the requirement ansible-core<2.13,>=2.12.0 (from ansible) (from versions: 0.0.1a1, 2.11.0b1, 2.11.0b2, 2.11.0b3, 2.11.0b4, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.11.1rc1, 2.11.1, 2.11.2rc1, 2.11.2, 2.11.3rc1, 2.11.3, 2.11.4rc1, 2.11.4, 2.11.5rc1, 2.11.5, 2.11.6rc1, 2.11.6, 2.11.7rc1)
No matching distribution found for ansible-core<2.13,>=2.12.0 (from ansible)

Environment details:
murugesan@murugesan-VirtualBox:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by electricmind007** [comment] 2021-12-03 17:18
I could not able to install ansible itself. So could not able to help with component name and lib/ansible/modules/pip.py

**Comment by dmsimard** [comment] 2021-12-05 02:27
Hi @electricmind007, this issue was also reported here: https://github.com/ansible/ansible/issues/76414 and it should have been resolved when 5.0.1 was released.

ansible-core 2.12 (installed by ansible 5) now requires python >=3.8 and the ansible 5.0.0 package was incorrectly declaring a requirement on python >=2.7.

When using a lower python version, pip should now correctly fall back to ansible 4.x which provides ansible-core 2.11.

**Comment by electricmind007** [comment] 2021-12-06 04:22
Hi @dmsimard, Please let me know if you know the release date for ansible 5.0.1.

**Comment by mkrizek** [comment] 2021-12-06 07:45
Duplicate of #76414.

**Closed as completed by mkrizek** 2021-12-06 07:45 UTC
Labels: module, support:core, bug, affects_2.13
