### ISSUE TITLE
Regression: facts not gathered when using --tags

### ISSUE THREAD

**Issue by kustodian** [ansible/ansible#14278] opened 2016-02-02 20:38 UTC
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible 2.1.0 (devel c5b4e194fa) last updated 2016/02/02 20:48:56 (GMT +200)
##### Environment:

Ubuntu 15.10
##### Summary:

When running a playbook by specifying tags, fact gathering is skipped.
##### Steps To Reproduce:

Run any playbook with `--tags tagname`.
##### Expected Results:

Facts should be gathered like in version before 2.0 when specifying tags.
##### Actual Results:

Facts are not gathered when any tag is specified.

**Comment by sivel** [comment] 2016-02-02 20:42
I believed this was recently addressed in https://github.com/ansible/ansible/commit/5587b08335f223fff64f54ced6f2790b3d6ee6f0 which was linked to https://github.com/ansible/ansible/issues/13602

Are you sure this is happening in the current HEAD of devel as per your version output?

cc @jimi-c

**Comment by kustodian** [comment] 2016-02-02 20:45
I just pulled again from the devel branch and tested again, the same thing happens. Here is the output of the `ansible --version` command:

```
ansible 2.1.0 (devel 42e312d3bd) last updated 2016/02/02 21:43:33 (GMT +200)
```

**Comment by bcoca** [comment] 2016-02-02 20:53
duplicate of #14228

**Closed as completed by bcoca** 2016-02-02 20:53 UTC
