### ISSUE TITLE
[WARNING]: Removed restricted key from module data: ansible_*

### ISSUE THREAD

**Issue by Torrent007** [ansible/ansible#38667] opened 2018-04-12 13:17 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

set_fact

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/mnt/data/ansible/my_modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION

```
COMMAND_WARNINGS(/etc/ansible/ansible.cfg) = False
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/mnt/data/ansible/my_modules']
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = True
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
SYSTEM_WARNINGS(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

CentOS 7 with Ansible Tower installed

##### SUMMARY

A Warning appears each time I changed during playbook vars like ansible_user or ansible_winrm_transport

##### STEPS TO REPRODUCE

Create ´user.yml´:

```yaml
- name: Test playbook
  hosts: all
  connection: local
  gather_facts: no

  tasks:
    - set_fact:
        ansible_user: toto
```
Run this command with any single host inventory (same issue when multiples hosts of course): 
```
ansible-playbook -i inventory user.yml -vvvvv
```

##### EXPECTED RESULTS

See comments at the end of 'Actual Results'

##### ACTUAL RESULTS

A warning line appears as you can see below when I change ansible_* vars:
```
[...]
TASK [set_fact] ***********************************************************************************************************************************************************************************************
task path: /mnt/data/test/ansible/user.yml:13
 [WARNING]: Removed restricted key from module data: ansible_user = toto

ok: [vm0050568e0362.RES.ROOT.CORP] => {
    "ansible_facts": {
        "ansible_user": "toto"
    },
    "changed": false
}
META: ran handlers
META: ran handlers
[...]
```
I just upgraded from 2.4.2 to 2.5 and I haven't this issue before.

For information, I changed during a specific role these vars:
- ´ansible_user´
- ´ansible_password´
- ´ansible_winrm_transport´
- ´ansible_winrm_kinit_mode´
And I have this warning appears for each of them.

The main problem is that it clearly displays the new values of variables, including the password:
 ![Ansible Tower output screenshot](https://user-images.githubusercontent.com/1904945/38679481-251c1a54-3e64-11e8-970c-0f23626c53a2.jpg)

**Comment by bcoca** [comment] 2018-04-12 13:25
dupe of #37535

**Closed as completed by bcoca** 2018-04-12 13:25 UTC

**Comment by Torrent007** [comment] 2018-04-12 13:29
Thanks for quick support and sorry for dupe ;)
