### ISSUE TITLE
setup command does not include all groups for host

### ISSUE THREAD

**Issue by atomatt** [ansible/ansible#394] opened 2012-05-15 13:28 UTC
Ansible: devel, r404c3acbbf5ed3f2f6a5a2f64cc230cd22317e15
OS: Ubuntu 12.04
Python: 2.7.3

Given the following .ini inventory file:

```
[example:vars]
domain_name=example.com

[example]
example-web
example-db

[example-web]
10.0.3.82

[example-db]
10.0.3.82
```

The 'setup' command does not emit the correct list of groups (example-db is missing):

```
"group_names": [
    "example",
    "example-web"
]
```

Note: reversing the order of the example-db and example-web group definitions in the inventory just means the last defined group is ignored:

```
"group_names": [
    "example",
    "example-db"
]
```

**Comment by mpdehaan** [comment] 2012-05-15 17:05
there is nothing about the setup command relevant to this, dupe of #395, will add some comments there

**Closed as completed by mpdehaan** 2012-05-15 17:05 UTC
