### ISSUE TITLE
include_vars ignores hash_behaviour setting

### ISSUE THREAD

**Issue by flare-ws** [ansible/ansible#17486] opened 2016-09-09 16:11 UTC
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

core 
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible']
```
##### CONFIGURATION

this key is commented

```
#hash_behaviour = replace
```
##### SUMMARY

According to ansible docs (http://docs.ansible.com/ansible/intro_configuration.html#hash-behaviour) default hash behaviour is "REPLACE". But dict "megavar" has been merged during play.

Actually, hash_behaviour in ansible.cfg means nothing, I've tried to manually set this to "replace"
##### STEPS TO REPRODUCE

```
# vars1.yml

megavar:
  var1: "abra"
  var2: "kadabra"

# vars2.yml

megavar:
  var1: "new abra"
  var3: "-_-"

# site.yml

---
- hosts: host.yandex.ru

  tasks:
    - name: load vars1
      include_vars: ./vars1.yml
    - name: load vars2
      include_vars: ./vars2.yml
    - debug:
        msg: "{{ megavar }}"

```

##### EXPECTED RESULTS

```
ok: [host.yandex.ru] => {
    "msg": {
        "var1": "new abra",
        "var3": "-_-"
    }
}
```
##### ACTUAL RESULTS

```
ok: [host.yandex.ru] => {
    "msg": {
        "var1": "new abra",
        "var2": "kadabra",
        "var3": "-_-"
    }
}
```

**Comment by flare-ws** [comment] 2016-09-09 16:27
Actually, hash_behaviour in ansible.cfg means nothing, I've tried to manually set this to "replace"

**Comment by bcoca** [comment] 2016-09-09 16:30
so tested this several ways and it seem to only be an issue with include_vars, when using vars/vars_files and other methods the behavior is as configured.

**Comment by bcoca** [comment] 2016-09-16 19:39
dupe of #15517

**Closed as completed by bcoca** 2016-09-16 19:39 UTC
Labels: affects_2.1, affects_2.2, bug
