### ISSUE TITLE
include_role and import_role undefines vars of third level parent role

### ISSUE THREAD

**Issue by pmfoss** [ansible/ansible#68006] opened 2020-03-04 15:21 UTC
##### SUMMARY
The variables defined in a role's vars/main.yml are available up to the second level child role. However, if the second level child role includes or imports another role, the variables are suddenly 
not defined.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- import_role
- include_role

##### ANSIBLE VERSION

```
ansible 2.9.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/mpietsch/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.1 (default, Jan 22 2020, 06:38:00) [GCC 9.2.0]
```
This bug has occurred since at least 2.2.

##### CONFIGURATION

```
none
```

##### OS / ENVIRONMENT

Occurs in Linux (ArchLinux) and FreeBSD (tested)

##### STEPS TO REPRODUCE

1 create four roles with `ansible-galaxy`

	ansible-galaxy init roles/a
	ansible-galaxy init roles/a.b
	ansible-galaxy init roles/a.b.c
	ansible-galaxy init roles/a.b.c.d

2 define a variable in `roles/a.b.c.d/vars/main.yml`

	myvar: "myvar"

3 create `tasks/main.yml` of roles

3.1 `roles/a.b.c.d/tasks/main.yml`

	- debug:
	    var: myvar

	- include_role:
	     name: a.b.c

3.2 `roles/a.b.c/tasks/main.yml`

	- debug:
	    var: myvar

	- include_role:
	     name: a.b

3.3 `roles/a.b/tasks/main.yml`

	- debug:
	    var: myvar

	- include_role:
	     name: a

3.4 `roles/a/tasks/main.yml`

	- debug:
	    var: myvar

4 create playbook `test.yml`

	- hosts: localhost
	  tasks:
	     - include_role:
	          name: a.b.c.d

5 run the playbook `ansible-playbook test.yml`

Note: The module `import_role` has the same behaviour.

##### EXPECTED RESULTS

	[user@myhost tmp]$ ansible-playbook test.yml 

	PLAY [localhost] ********************************************************************************************************************************************

	TASK [Gathering Facts] **************************************************************************************************************************************
	ok: [localhost]

	TASK [include_role : a.b.c.d] *******************************************************************************************************************************

	TASK [a.b.c.d : debug] **************************************************************************************************************************************
	ok: [localhost] => {
	    "myvar": "myvar"
	}

	TASK [include_role : a.b.c] *********************************************************************************************************************************

	TASK [a.b.c : debug] ****************************************************************************************************************************************
	ok: [localhost] => {
	    "myvar": "myvar"
	}

	TASK [include_role : a.b] ***********************************************************************************************************************************

	TASK [a.b : debug] ******************************************************************************************************************************************
	ok: [localhost] => {
	    "myvar": "myvar"
	}

	TASK [include_role : a] *************************************************************************************************************************************

	TASK [a : debug] ********************************************************************************************************************************************
	ok: [localhost] => {
	    "myvar": "myvar"
	}

	PLAY RECAP **************************************************************************************************************************************************
	localhost                  : ok=5    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

##### ACTUAL RESULTS

	[user@myhost tmp]$ ansible-playbook test.yml 

	PLAY [localhost] ********************************************************************************************************************************************

	TASK [Gathering Facts] **************************************************************************************************************************************
	ok: [localhost]

	TASK [include_role : a.b.c.d] *******************************************************************************************************************************

	TASK [a.b.c.d : debug] **************************************************************************************************************************************
	ok: [localhost] => {
	    "myvar": "myvar"
	}

	TASK [include_role : a.b.c] *********************************************************************************************************************************

	TASK [a.b.c : debug] ****************************************************************************************************************************************
	ok: [localhost] => {
	    "myvar": "myvar"
	}

	TASK [include_role : a.b] ***********************************************************************************************************************************

	TASK [a.b : debug] ******************************************************************************************************************************************
	ok: [localhost] => {
	    "myvar": "myvar"
	}

	TASK [include_role : a] *************************************************************************************************************************************

	TASK [a : debug] ********************************************************************************************************************************************
	ok: [localhost] => {
	    "myvar": "VARIABLE IS NOT DEFINED!"
	}

	PLAY RECAP **************************************************************************************************************************************************
	localhost                  : ok=5    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

**Comment by sivel** [comment] 2020-03-04 15:28
Duplicate of https://github.com/ansible/ansible/issues/47023

**Closed as completed by sivel** 2020-03-04 15:29 UTC
