### ISSUE TITLE
Variables passed to the script command aren't evaluated

### ISSUE THREAD

**Issue by cbertoldi** [ansible/ansible#3467] opened 2013-07-08 07:28 UTC
I have defined an handler like the following:

``` yaml
- name: do something
  script: ../scripts/do_something.sh {{ foo }} {{ bar }}
  sudo: no
```

When ansible executes this handler, the variables aren't evaluated, and it fails with the following error:

> fatal: [roger] => Traceback (most recent call last):
>   File "/usr/local/lib/python2.6/dist-packages/ansible/runner/**init**.py", line 344, in _executor
>     exec_rc = self._executor_internal(host)
>   File "/usr/local/lib/python2.6/dist-packages/ansible/runner/__init__.py", line 423, in _executor_internal
>     return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
>   File "/usr/local/lib/python2.6/dist-packages/ansible/runner/__init__.py", line 577, in _executor_internal_inner
>     result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
>   File "/usr/local/lib/python2.6/dist-packages/ansible/runner/action_plugins/script.py", line 45, in run
>     source = utils.path_dwim_relative(inject['_original_file'], 'files', source, self.runner.basedir)
>   File "/usr/local/lib/python2.6/dist-packages/ansible/utils/__init__.py", line 211, in path_dwim_relative
>     if os.path.exists(source2):
>   File "/usr/lib/python2.6/genericpath.py", line 18, in exists
>     st = os.stat(path)
> TypeError: stat() argument 1 must be encoded string without NULL bytes, not str

I know that the variables contain something, because if I change the script line with this `command: /bin/echo {{ foo }} {{ bar }}` I see the correct values.
Also, I know that the problems has to do something with script plus variables, because if I hardcode values in the script command, the script it is actually executed on the remote host.

Ansible version is 1.2.

**Comment by cllunsford** [comment] 2013-07-17 16:30
I ran into the same issue.  I believe this is due to the fact that the script module (like the raw module) doesn't use the module subsystem.  This must be where the variables are sub'd in.

As a workaround, I copied the script "manually" and then used the shell module to execute:

``` yml
- name: copy the script first
  copy: src=../scripts/do_something.sh dest=/tmp/do_something.sh mode=0744
- name: now do something
  shell: ./do_something.sh {{ foo }} {{ bar }} chdir=/tmp/
```

**Comment by mpdehaan** [comment] 2013-07-17 16:42
It's not really a lack of using a module, but rather not calling the
template engine on the options line.

This is pretty easy to address, just need to get to it.

**Comment by srgvg** [comment] 2013-07-18 19:08
Can't reproduce this? 

Tested with play.yml:

``` yaml
- hosts: localhost
  gather_facts: False
  vars:
    foo: oof
    bar: rab
  tasks:
  - command: echo
    notify: script
  handlers:
  - name: script
    script: do_echo {{foo}} {{bar}}
```

and `do_echo` script contains just `echo $*`

Tested with ansible 1.2, 1.2.2 and latest 1.3, all gives this same output:

``` bash
PLAY [localhost] ************************************************************** 

TASK: [command echo] ********************************************************** 
changed: [localhost] => {"changed": true, "cmd": ["echo"], "delta": "0:00:00.001272", "end": "2013-07-18 21:05:46.552985", "rc": 0, "start": "2013-07-18 21:05:46.551713", "stderr": "", "stdout": ""}

NOTIFIED: [script] ************************************************************ 
ok: [localhost] => {"rc": 0, "stderr": "", "stdout": "oof rab\n"}

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=1    unreachable=0    failed=0   
```

**Comment by mpdehaan** [comment] 2013-07-20 22:31
I can't reproduce this in 1.3 (devel) either, this was my test.

```
- name: test
  hosts: all
  connection: local
  gather_facts: False
  vars:
    hi: hello there
  tasks:
    - script: /tmp/test.sh {{ hi }}
```

Might just be an issue on 1.2, so I am closing this ticket.

**Closed as completed by mpdehaan** 2013-07-20 22:31 UTC
Labels: bug

**Comment by cllunsford** [comment] 2013-07-25 20:50
Did some more testing.  The issue only happens when configured under a role, not with a normal playbook.  Also, I see this in 1.2.2 and 1.3 (devel).

Here's a minimal setup to reproduce:

test.yml:

```
- hosts: localhost
  gather_facts: False
  vars:
    foo: oof
    bar: rab
  roles:
  - test
```

roles/test/tasks/main.yml:

```
---
- command: echo {{foo}} {{bar}}
- script: do_echo {{foo}} {{bar}}
```

roles/test/files/do_echo:

```
echo $*
```

results in:

```
PLAY [localhost] ************************************************************** 

TASK: [command echo oof rab] ************************************************** 
changed: [localhost] => {"changed": true, "cmd": ["echo", "oof", "rab"], "delta": "0:00:00.002334", "end": "2013-07-25 16:49:13.069864", "item": "", "rc": 0, "start": "2013-07-25 16:49:13.067530", "stderr": "", "stdout": "oof rab"}

TASK: [script do_echo oof rab] ************************************************ 
fatal: [localhost] => Traceback (most recent call last):
  File "/usr/local/lib64/python2.6/site-packages/ansible/runner/__init__.py", line 364, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/lib64/python2.6/site-packages/ansible/runner/__init__.py", line 443, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/local/lib64/python2.6/site-packages/ansible/runner/__init__.py", line 597, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/usr/local/lib64/python2.6/site-packages/ansible/runner/action_plugins/script.py", line 45, in run
    source = utils.path_dwim_relative(inject['_original_file'], 'files', source, self.runner.basedir)
  File "/usr/local/lib64/python2.6/site-packages/ansible/utils/__init__.py", line 211, in path_dwim_relative
    if os.path.exists(source2):
  File "/usr/lib64/python2.6/genericpath.py", line 18, in exists
    st = os.stat(path)
TypeError: stat() argument 1 must be (encoded string without NULL bytes), not str


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
localhost                  : ok=1    changed=1    unreachable=1    failed=0   
```

**Comment by vcastellm** [comment] 2013-08-19 19:29
Failing for me too in a role

**Comment by WramblinWreck** [comment] 2013-08-22 22:06
I'm getting the same failure in a role when run from a CentOS 5.8 box running python 2.6.8, but works when run locally on Mac OS X running python 2.6.1 and from Ubuntu boxes running Python 2.7

**Comment by jabclab** [comment] 2013-09-23 09:07
I'm seeing this same issue using:
- Ansible **1.3.1**
- Python **2.7.5** 
- OS X **10.8.2**

My task is also within a role (`roles/xxx/tasks/main.yml`). This is my task:

``` yaml
- name: Add known clients
  script: add_clients.sh
          -u "{{ users.admin.username }}:{{ users.admin.password }}"
          {% for client in groups['clients'] %}
            -c "{{ hostvars[client].name }}:{{ hostvars[client].server.http.auth }}"
          {% endfor %}
```

The `hostvars` here are defined in files within a `host_vars` directory.

Stack trace:

```
fatal: [vagrant.xxx] => Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/ansible/runner/__init__.py", line 382, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/Library/Python/2.7/site-packages/ansible/runner/__init__.py", line 471, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/Library/Python/2.7/site-packages/ansible/runner/__init__.py", line 654, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/Library/Python/2.7/site-packages/ansible/runner/action_plugins/script.py", line 45, in run
    source = utils.path_dwim_relative(inject['_original_file'], 'files', source, self.runner.basedir)
  File "/Library/Python/2.7/site-packages/ansible/utils/__init__.py", line 259, in path_dwim_relative
    if os.path.exists(source2):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
TypeError: must be encoded string without NULL bytes, not str
```

**Comment by lisaglendenning** [comment] 2013-09-24 21:29
I'm also experiencing this problem on OS X 10.8. The script task is now under an Ansible 1.3.1 role but used to work as a non-role task with Ansible 1.0.

<pre>
- name: mount ZK data log device
  script: zk_mount_log_device.py -v {{ zk_tree.vlb }}/datalog
  when: zk_datalog_device is defined
</pre>

**Comment by deefour** [comment] 2013-10-04 01:51
I'm having the same problem _(variables defined in a role)_ with `script` module. OS X 10.8 and ansible 1.3.2.

**Comment by guillaumevincent** [comment] 2014-08-08 09:40
Still having the problem in a role, do we need to open a new ticket ?

**Comment by srgvg** [comment] 2014-08-08 09:44
Yes, please open a new ticket, comments on closed tickets are not being monitored.

**Comment by KuiKui** [comment] 2014-09-02 12:26
[New issue](https://github.com/ansible/ansible/issues/8514)
