### ISSUE TITLE
Included role does not propagate changed to the task.

### ISSUE THREAD

**Issue by steve-todorov** [ansible/ansible#70468] opened 2020-07-05 19:37 UTC
##### SUMMARY

Included role does not propagate `changed` to the task.

##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

lib/ansible/modules/include_role.py

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/steve/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.2 (default, Apr 27 2020, 15:53:34) [GCC 9.3.0]

```

##### CONFIGURATION
```paste below
empty
```

##### OS / ENVIRONMENT

OS: Ubuntu 20.04 LTS
Python: 3.8.2

##### STEPS TO REPRODUCE

An oversimplified reproducible version:

```
--- roles/server/dhcpd/tasks/main.yaml
- name: Always simulate changed.
  command: "echo 'hello world'"

--- playbook.yaml
- name: Example
  hosts: localhost
  tasks:
  - name: DHCP configuration
    include_role:
      name: server/dhcpd
    register: dhcpdConfig
  - debug:
      msg: "{{ dhcpd|default('undefined') }}"
  - name: Restarting DHCP server
    service:
      name: isc-dhcp-server
      enabled: yes
      state: restarted
    when: dhcpdConfig.changed
```

Then simply `ansible-playbook playbook.yaml`

##### EXPECTED RESULTS

`dhcpdConfig.changed` should be true and the `Restarting DHCP server` task should run.

##### ACTUAL RESULTS

The `Restarting DHCP server` task is always skipped because `dhcpdConfig.changed` is always `false`.

**Comment by Akasurde** [comment] 2020-07-06 07:44
Duplicate of https://github.com/ansible/ansible/issues/26537. Please see https://github.com/ansible/ansible/issues/26537#issuecomment-333640123 and https://github.com/ansible/ansible/issues/26537#issuecomment-338167934

Thanks.

**Closed as completed by Akasurde** 2020-07-06 07:44 UTC
