### ISSUE TITLE
any_errors_fatal doesn't work when using includes in roles

### ISSUE THREAD

**Issue by malpaniravikant** [ansible/ansible#14424] opened 2016-02-10 22:51 UTC
Issue Type:
Bug Report

Ansible Version:
commit 64c976a6c395967f5d5dd29c00d53ca71c14f5c7
Merge: 371c731 3079a03
Author: Brian Coca bcoca@ansible.com
Date:   Wed Feb 10 15:42:29 2016 -0500

```
Merge pull request #14416 from bcoca/diff_size_fix

read full file when doing diff
```

Default configuration

Environment:
Ubuntu 14.04

Summary:
any_errors_fatal doesn't stop task execution if failed in includes

Steps To Reproduce:
Playbook:

```
- name: Test an_errors_fatal with includes
  hosts: all
  any_errors_fatal: True

  roles:
    - { role: test1 }
    - { role: test2 }

$ cat test1/tasks/main.yml 
- include: helper.yml

$ cat test1/tasks/helper.yml 
- fail: msg="failed in include of test1"

$ cat test2/tasks/main.yml 
- include: helper.yml

$ cat test2/tasks/helper.yml 
- fail: msg="failed in include of test2"
```

```
PLAY [Test an_errors_fatal with includes] **************************************

TASK [setup] *******************************************************************
ok: [192.168.208.104]
ok: [192.168.208.85]

TASK [test1 : include] *********************************************************
included: /home/zerostack/ansible/roles/test1/tasks/helper.yml for 192.168.208.85, 192.168.208.104

TASK [test1 : fail] ************************************************************
fatal: [192.168.208.85]: FAILED! => {"changed": false, "failed": true, "msg": "failed in include of test1"}
fatal: [192.168.208.104]: FAILED! => {"changed": false, "failed": true, "msg": "failed in include of test1"}

TASK [test2 : include] *********************************************************
included: /home/zerostack/ansible/roles/test2/tasks/helper.yml for 192.168.208.85, 192.168.208.104

TASK [test2 : fail] ************************************************************
fatal: [192.168.208.85]: FAILED! => {"changed": false, "failed": true, "msg": "failed in include of test2"}
fatal: [192.168.208.104]: FAILED! => {"changed": false, "failed": true, "msg": "failed in include of test2"}
    to retry, use: --limit @/home/zerostack/ansible/include_any_errors_fatal.retry

PLAY RECAP *********************************************************************
192.168.208.104            : ok=3    changed=0    unreachable=0    failed=2   
192.168.208.85             : ok=3    changed=0    unreachable=0    failed=2   
```

**Comment by rudimeyer** [comment] 2016-04-27 08:22
I see the same issue, also on Ubuntu 14.04, with Ansible version 2.0.2.0

**Comment by jctanner** [comment] 2016-06-07 13:12
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us. 

Testing this on the version you have specified, we cannot reproduce this problem.

Our reasons and evidence for this are:
- Unable to reproduce with ansible 1.9, 2.0 or 2.1. The play stops after the first role calls the fail module.

And we suggest that:
- Check in with the mailing list or IRC and look for help with debugging your environment to further isolate the problem.

As such, we are most likely going to close this ticket.  Should you disagree with this conclusion, you may also wish to join our mailing lists, which are very active:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Closed as completed by jctanner** 2016-06-07 13:12 UTC
Labels: P2, bug

**Comment by iredmail** [comment] 2017-04-30 02:20
Got same issue with Ansible 2.3.0.0.

**Comment by prit342** [comment] 2017-05-30 11:12
I am having similar issues with 2.3.0.0. Right now I am adding "any_errors_fatal: true" to all the tasks as workaround.  If there is a better workaround, please let me know.

**Comment by elouanKeryell-Even** [comment] 2017-06-13 11:18
Working for me in version 2.3.

```
[root@localhost 2]# ansible --version
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
[root@localhost 2]# ansible-playbook playbook.yaml -i inventory.txt -v
```

---

```
[root@localhost 2]# ansible-playbook playbook.yaml -i inventory.txt -v
Using /etc/ansible/ansible.cfg as config file

PLAY [Test an_errors_fatal with includes] ***************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************
ok: [192.168.1.92]
ok: [192.168.1.89]

TASK [test1 : fail] *************************************************************************************************************************************************
fatal: [192.168.1.92]: FAILED! => {"changed": false, "failed": true, "msg": "failed in include of test1"}
fatal: [192.168.1.89]: FAILED! => {"changed": false, "failed": true, "msg": "failed in include of test1"}
        to retry, use: --limit @/root/ekeryell/test_ansible_any_errors_fatal/2/playbook.retry

PLAY RECAP **********************************************************************************************************************************************************
192.168.1.89               : ok=1    changed=0    unreachable=0    failed=1
192.168.1.92               : ok=1    changed=0    unreachable=0    failed=1
```
