### ISSUE TITLE
Ansible 2.5.3 doesn't create the correct remote_tmp directory when the remote user isn't specified

### ISSUE THREAD

**Issue by plumbeo** [ansible/ansible#40625] opened 2018-05-23 17:00 UTC
##### SUMMARY
Ansible 2.5.3 creates a `~None` directory inside the remote user's home directory when `remote_tmp` is set to the default value of `~/.ansible/tmp` and the remote user isn't specified on the command line or in the config file but defaults to the name of the current user.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible

##### ANSIBLE VERSION
```
ansible 2.5.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/my_modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

```

##### CONFIGURATION
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_CONTROL_PATH_DIR(/etc/ansible/ansible.cfg) = /home/ansible/.ansible/cp
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/home/ansible/inventory/hosts']
DEFAULT_LOCAL_TMP(/etc/ansible/ansible.cfg) = /home/ansible/.ansible/tmp/ansible-local-1948US5bRX
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/home/ansible/roles']

##### OS / ENVIRONMENT
Ubuntu 16.04 LTS on both the server that runs ansible and the remote hosts.

##### STEPS TO REPRODUCE
Launch any playbook.

##### EXPECTED RESULTS
Ansible should create a `.ansible/tmp/` directory inside the remote user's home directory.

##### ACTUAL RESULTS
Ansible creates a `~None/tmp` directory inside the remote user's home directory

The only significant difference I found in the logs is that if the remote user is specified the verbose log says:

ESTABLISH SSH CONNECTION FOR USER: ansible

otherwise it says:

ESTABLISH SSH CONNECTION FOR USER: None

even though ansible is connecting to the remote server using the correct user.

**Comment by sivel** [comment] 2018-05-23 17:36
Duplicate of https://github.com/ansible/ansible/issues/40483

**Closed as completed by sivel** 2018-05-23 17:36 UTC
Labels: support:core, affects_2.5, bug
