### ISSUE TITLE
Parsing traceback in 1.7.2

### ISSUE THREAD

**Issue by jnojr** [ansible/ansible#9580] opened 2014-11-19 16:33 UTC
Issue Type:

Bug Report

Ansible Version:

1.7.2

Environment:

Mac OS X 10.10.1 "Yosemite"

Summary:

YAML traceback when hosts in playbook is a number

Steps To Reproduce:

Create a simple playbook and set hosts: to a number

Expected Results:

Playbook should run, or if that's not possible for some reason, output should be more friendly and informative.

Actual Results:

flamingo:RDTE joliver$ ansible-playbook java.yml

PLAY [111] *******************************************************************\* 
Traceback (most recent call last):
  File "/opt/local/bin/ansible-playbook", line 309, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/opt/local/bin/ansible-playbook", line 249, in main
    pb.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/playbook/**init**.py", line 339, in run
    if not self._run_play(play):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 635, in _run_play
    play._play_hosts = self.inventory.list_hosts(play.hosts)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/inventory/__init__.py", line 494, in list_hosts
    result = [ h.name for h in self.get_hosts(pattern) ]
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/inventory/**init**.py", line 185, in get_hosts
    patterns = pattern.replace(";",":").split(":")
AttributeError: 'int' object has no attribute 'replace'

**Comment by bcoca** [comment] 2014-11-19 16:56
confirmed bug, as a workaround you can quote the number and it will see it as a string.

**Comment by jimi-c** [comment] 2015-06-28 05:02
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-06-28 05:01 UTC
Labels: bug
