### ISSUE TITLE
yaml inventory support in 2.3

### ISSUE THREAD

**Issue by dano0b** [ansible/ansible#23556] opened 2017-04-13 08:25 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

core inventory

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /root/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### CONFIGURATION

...
[defaults]
inventory = ./inventories/hosts.yml
....
##### OS / ENVIRONMENT

rhel 7
##### SUMMARY

play can't access host_vars for hosts/groups defined in a yaml inventory

##### STEPS TO REPRODUCE

define host/group using a yaml inventory
define host var this host in host_vars
define play:

```yaml
- hosts: yourGroup / yourHost
  become: false
  tasks:
  - name: debug var
    debug:
      var: yourHostVar
```

more info: https://gist.github.com/dano0b/72a067f162dadbe5bf5c482b0d67e9f0

##### EXPECTED RESULTS

host_var will be printed using the debug module

##### ACTUAL RESULTS

```
[WARNING]: provided hosts list is empty, only localhost is available

TASK [debug var] **************************************************************************************************************************************************************************************************
Thursday 13 April 2017  09:02:45 +0200 (0:00:00.036)       0:00:00.036 ********
ok: [host1] => {
    "changed": false,
    "yourHostVar": "VARIABLE IS NOT DEFINED!"
```

**Comment by bcoca** [comment] 2017-04-13 16:41
I just tested locally and get:
```
ok: [host1] => {
    "hostHttpProxy": "http://ProxyIP:8080"
}
```

**Comment by bcoca** [comment] 2017-04-13 16:42
from the warning you get in the gist I think you are not pointing at the inventory file correctly, use -i and full path

**Comment by dano0b** [comment] 2017-04-13 17:13
@bcoca tried with an absolute path in the ansible.cfg and using -i before, too.
could be a file structure issue? my structure:
```
inventories/hosts.yml (configured by ansible.cfg or -i)
host_vars/host1 (yaml format)
group_vars/group/vars (yaml format)
playbook.yml 
```
now at home I can reproduce this behavior with the following playbook:
```
### inventories/hosts.yml:
---
group:
  hosts:
    host1:
  vars:
    ansible_port: myPort
    ansible_host: myHost
    ansible_connection: ssh
    ansible_user: myUser

### playbook.yml
---
- hosts: host1
  become: false
  tasks:
  - name: debug var
    debug:
      var: hostHttpProxy

### host_vars/host1:
---
hostHttpProxy: http://ProxyIP:8080

### output:
# ansible-playbook -i inventories/hosts.yml playbook.yml
[WARNING]: provided hosts list is empty, only localhost is available


PLAY [host1] ******************************************************************************

TASK [debug var] **************************************************************************
Thursday 13 April 2017  19:12:26 +0200 (0:00:00.398)       0:00:00.398 ******** 
ok: [host1] => {
    "changed": false, 
    "hostHttpProxy": "VARIABLE IS NOT DEFINED!"
}

PLAY RECAP ********************************************************************************
host1                      : ok=1    changed=0    unreachable=0    failed=0   

Thursday 13 April 2017  19:12:27 +0200 (0:00:00.564)       0:00:00.962 ******** 
=============================================================================== 
debug var --------------------------------------------------------------- 0.56s
Playbook run took 0 days, 0 hours, 0 minutes, 0 seconds
```
If I put my hostHttpProxy-Variable to the group_vars/group/vars yaml file, I get my desired value. In both cases I get the Warning.

**Comment by bcoca** [comment] 2017-04-13 17:21
To be picked up host_vars need to be adjacent to the inventory file or playbook, it will not be picked up from 'upper directories'. I had host_vars adjacent to inventory, moved it to play as in your example .. still works for me.

**Comment by dano0b** [comment] 2017-04-13 17:55
@bcoca 

just used a clean system with a fresh install, same problem:

```
[root@6pat413 tmp] # find -print -type f -exec cat {} \; 
.
./hosts.yml
---
group:
  vars:
    ansible_connection: local
  hosts:
    host1:
./host_vars
./host_vars/host1
---
hostHttpProxy: http://ProxyIP:8080
./playbook.yml
---
- hosts: host1
  become: false
  tasks:
  - name: debug var
    debug:
      var: hostHttpProxy
[root@6pat413 tmp] # ansible --version
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```
output:
```
[root@6pat413 tmp] # ansible-playbook -i hosts.yml playbook.yml 
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [host1] ******************************************************************************

TASK [Gathering Facts] ********************************************************************
ok: [host1]

TASK [debug var] **************************************************************************
ok: [host1] => {
    "changed": false, 
    "hostHttpProxy": "VARIABLE IS NOT DEFINED!"
}

PLAY RECAP ********************************************************************************
host1                      : ok=2    changed=0    unreachable=0    failed=0   
```

using group_var:
```
[root@6pat413 tmp] # mkdir group_vars
[root@6pat413 tmp] # mkdir group_vars/group
[root@6pat413 tmp] # cp host_vars/host1 group_vars/group/vars
[root@6pat413 tmp] # ansible-playbook -i hosts.yml playbook.yml 
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [host1] ******************************************************************************

TASK [Gathering Facts] ********************************************************************
ok: [host1]

TASK [debug var] **************************************************************************
ok: [host1] => {
    "changed": false, 
    "hostHttpProxy": "http://ProxyIP:8080"
}

PLAY RECAP ********************************************************************************
host1                      : ok=2    changed=0    unreachable=0    failed=0   
```

**Comment by bcoca** [comment] 2017-04-13 18:45
I still cannot reproduce ... i get the value of the variable. The strange thing is you keep getting the warning of an empty inventory, I don't.

**Comment by dano0b** [comment] 2017-04-13 19:34
thanks to @bcoca I've found some workaround for us, just have to put all my groups in an all: group . At the moment I don't have an explaination and this couldn't be reproduced(see previous comment). From my side this issue could be closed, just letting you decide if there is some more investigation required.

newest test results:

```
### configuration
find -print -type f -exec cat {} \; 
.
./hosts.yml
---
all:
  children:
    group1:
      vars:
        ansible_connection: local
      hosts:
        host1:

group2:
  hosts:
    host2:
  vars:
    ansible_connection: local
./host_vars
./host_vars/host2
---
hostHttpProxy: http://ProxyIP:8080
./host_vars/host1
---
hostHttpProxy: http://ProxyIP:8080
./playbook.yml
---
- hosts: host1
  become: false
  tasks:
  - name: debug var
    debug:
      var: hostHttpProxy

- hosts: host2
  become: false
  tasks:
  - name: debug var
    debug:
      var: hostHttpProxy


###result:
ansible-playbook -i hosts.yml playbook.yml 

PLAY [host1] ******************************************************************************

TASK [Gathering Facts] ********************************************************************
ok: [host1]

TASK [debug var] **************************************************************************
ok: [host1] => {
    "changed": false, 
    "hostHttpProxy": "http://ProxyIP:8080"
}

PLAY [host2] ******************************************************************************

TASK [Gathering Facts] ********************************************************************
ok: [host2]

TASK [debug var] **************************************************************************
ok: [host2] => {
    "changed": false, 
    "hostHttpProxy": "VARIABLE IS NOT DEFINED!"
}

PLAY RECAP ********************************************************************************
host1                      : ok=2    changed=0    unreachable=0    failed=0   
host2                      : ok=2    changed=0    unreachable=0    failed=0   
```

**Comment by bcoca** [comment] 2017-04-21 03:10
closing as i was never able to reproduce, user has workaround and no one else has had similar complaint.

**Closed as completed by bcoca** 2017-04-21 03:10 UTC
Labels: affects_2.3, bug
