### ISSUE TITLE
Handlers do not get executed if 'run_once: True' and execution fails (even with force_handlers: True)

### ISSUE THREAD

**Issue by hdimitriou** [ansible/ansible#22408] opened 2017-03-08 14:26 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - Handlers

##### ANSIBLE VERSION

```
From ansible 2.2.0
up to ansible 2.3.0
```

##### SUMMARY

Handlers do not get executed if 'run_once: True' and execution fails (even with force_handlers: True).

##### STEPS TO REPRODUCE

Execute the example playbook. Basically setup a task that notifies a handler followed by a task that fails. Handler does not get executed if run_once: True is set

```yaml
- name: Test
  hosts: 127.0.0.1
  connection: local
  run_once: True
  force_handlers: True
  tasks:
    - name: touch a file
      file:
        path: /tmp/test
        state: touch
      notify: cleanup
    - name: test fail
      fail:
        msg: Test-Fail
  handlers:
    - name: cleanup
      file:
        path: /tmp/test
        state: absent
```

##### EXPECTED RESULTS

Handler should run and /tmp/test should not exist post run

The output if 'run_once: True' is not there
```
PLAY [Test5] *******************************************************************

TASK [setup] *******************************************************************
Wednesday 08 March 2017  16:14:30 +0200 (0:00:00.050)       0:00:00.050 *******
ok: [127.0.0.1]

TASK [touch a file] ************************************************************
Wednesday 08 March 2017  16:14:31 +0200 (0:00:00.668)       0:00:00.718 *******
changed: [127.0.0.1] => {"changed": true, "dest": "/tmp/test", "gid": 0, "group": "wheel", "mode": "0644", "owner": "hdimitriou", "size": 0, "state": "file", "uid": 501}

RUNNING HANDLER [cleanup] ******************************************************
Wednesday 08 March 2017  16:14:32 +0200 (0:00:00.413)       0:00:01.132 *******
changed: [127.0.0.1] => {"changed": true, "path": "/tmp/test", "state": "absent"}

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=3    changed=2    unreachable=0    failed=0
```

##### ACTUAL RESULTS

Handler never run, /tmp/test file exists post run

```
PLAY [Test5] ***************************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************************************************************************************************************************
Wednesday 08 March 2017  16:16:37 +0200 (0:00:00.135)       0:00:00.135 *******
ok: [127.0.0.1]

TASK [touch a file] ********************************************************************************************************************************************************************************************************************************************************************
Wednesday 08 March 2017  16:16:38 +0200 (0:00:00.868)       0:00:01.004 *******
changed: [127.0.0.1] => {"changed": true, "dest": "/tmp/test", "gid": 0, "group": "wheel", "mode": "0644", "owner": "hdimitriou", "size": 0, "state": "file", "uid": 501}

TASK [test fail] ***********************************************************************************************************************************************************************************************************************************************************************
Wednesday 08 March 2017  16:16:39 +0200 (0:00:00.481)       0:00:01.485 *******
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "Test-Fail"}

NO MORE HOSTS LEFT *********************************************************************************************************************************************************************************************************************************************************************
	to retry, use: --limit @/Users/hdimitriou/Virtualenvs/ansible/vars_test/test17.retry

PLAY RECAP *****************************************************************************************************************************************************************************************************************************************************************************
127.0.0.1                  : ok=2    changed=1    unreachable=0    failed=1
```

**Comment by jctanner** [comment] 2017-03-13 20:36
Related:
https://github.com/ansible/ansible/commit/5be2a3a9e03afa9734fb41c1f47a9f639c440120
https://github.com/ansible/ansible/issues/18021
https://github.com/ansible/ansible/commit/c669a381d117ccd96d4d59ab9191a107d08dfdb4
https://github.com/ansible/ansible/issues/16937

**Comment by jctanner** [comment] 2017-03-13 20:41
@hdimitriou This appears to be the expected behavior, according to https://github.com/ansible/ansible/commit/5be2a3a9e03afa9734fb41c1f47a9f639c440120

Once all of the hosts in the play have failed, the play returns early. Expecting a handler to fire in that situation is a little questionable because you are now in a "rescue" type situation which is what blocks were designed for.

http://docs.ansible.com/ansible/playbooks_blocks.html#error-handling

I'm going to close this as not a bug, but if you disagree with the conclusion, please feel free to reach out on the mailing list, irc or via the proposal process.

**Closed as completed by jctanner** 2017-03-13 20:41 UTC
Labels: affects_2.2, c:playbook/handler*, bug
