### ISSUE TITLE
Please provide deb package for Ubuntu Xenial (16.04 LTS)

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible#15524] opened 2016-04-21 15:56 UTC
##### ISSUE TYPE
- Feature Idea
##### ANSIBLE VERSION

N/A
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Ubuntu 16.04 Xenial was just released today, and it's the new LTS version, supported for many years. Please consider adding a xenial release of the official Ansible deb packages for Ubuntu to the Ansible PPA: https://launchpad.net/~ansible/+archive/ubuntu/ansible
##### STEPS TO REPRODUCE

Try installing Ansible with Ansible's Ubuntu PPA.
##### EXPECTED RESULTS

Installation works.
##### ACTUAL RESULTS

```
W: The repository 'http://ppa.launchpad.net/ansible/ansible/ubuntu xenial Release' does not have a Release file.
E: Failed to fetch http://ppa.launchpad.net/ansible/ansible/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Failed to fetch http://ppa.launchpad.net/ansible/ansible/ubuntu/dists/xenial/main/binary-i386/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by CorbanR** [comment] 2016-04-27 06:59
+1

**Comment by okelet** [comment] 2016-04-27 10:28
+1

**Comment by jcode** [comment] 2016-04-28 09:59
+1

**Comment by jlumme** [comment] 2016-04-28 12:30
+1

**Comment by bilkoua** [comment] 2016-04-28 14:13
+1

**Comment by filsh** [comment] 2016-04-28 20:21
+1

**Comment by ChesterFie1d** [comment] 2016-04-29 11:20
+1

**Comment by klauern** [comment] 2016-04-29 17:48
I don't want to derail this issue, but there are ways to +1 something without sending a notification to everybody who is subscribed to it:

https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments

**Comment by Jalle19** [comment] 2016-05-23 11:17
Any progress on this? We can't even begin to use Ubuntu 16.04 until Ansible is easily available through the PPA.

**Comment by bilkoua** [comment] 2016-05-23 11:35
> Any progress on this?

https://launchpad.net/~ansible/+archive/ubuntu/ansible
added from 2016-05-19

**Comment by Jalle19** [comment] 2016-05-23 15:36
Great stuff, I guess this issue can be closed then!

**Comment by bcoca** [comment] 2016-05-23 15:45
closing as per above

**Closed as completed by bcoca** 2016-05-23 15:45 UTC
Labels: feature

**Comment by porbas** [comment] 2016-05-23 16:17
There were build failure for ubuntu 16.04 and package is not available for install
https://launchpad.net/~ansible/+archive/ubuntu/ansible/+packages

**Comment by WolverineFan** [comment] 2016-05-24 16:08
Can this be reopened?  The package build failed due to a missing dependency on the python-support package, which isn't available in Xenial.  https://launchpad.net/ubuntu/+source/python-support/

**Comment by hswong3i** [comment] 2016-05-25 02:23
Please kindly reopen this issue since it didn't get fixed yet :-(

**Comment by geerlingguy** [comment] 2016-05-27 01:20
It looks like there was a successful build yesterday:

https://launchpad.net/~ansible/+archive/ubuntu/ansible/+build/9805053

(And I can confirm it installs and works correctly on 16.04).

**Comment by hswong3i** [comment] 2016-05-27 04:18
(which means that they just left the ansible-2.0.2 build fail... since ansible-2.1.0 going to be released and it also get the build fixed...)

**Comment by Jalle19** [comment] 2016-05-30 09:30
It seems the repository isn't signed, I get this when trying to build a box with Packer:

```
==> virtualbox-iso: Provisioning with shell script: scripts/ansible.sh
    virtualbox-iso: Ansible is a radically simple IT automation platform that makes your applications and systems easier to deploy. Avoid writing scripts or custom code to deploy and update your applications— automate in a language that approaches plain English, using SSH, with no agents to install on remote systems.
    virtualbox-iso:
    virtualbox-iso: http://ansible.com/
    virtualbox-iso: More info: https://launchpad.net/~ansible/+archive/ubuntu/ansible
    virtualbox-iso: Error reading https://launchpad.net/api/1.0/~ansible/ppas: Service Temporarily Unavailable
    virtualbox-iso: Hit:1 http://security.ubuntu.com/ubuntu xenial-security InRelease
    virtualbox-iso: Get:2 http://ppa.launchpad.net/ansible/ansible/ubuntu xenial InRelease [18.1 kB]
    virtualbox-iso: Ign:2 http://ppa.launchpad.net/ansible/ansible/ubuntu xenial InRelease
    virtualbox-iso: Hit:3 http://us.archive.ubuntu.com/ubuntu xenial InRelease
    virtualbox-iso: Get:4 http://ppa.launchpad.net/ansible/ansible/ubuntu xenial/main amd64 Packages [552 B]
    virtualbox-iso: Hit:5 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease
    virtualbox-iso: Get:6 http://ppa.launchpad.net/ansible/ansible/ubuntu xenial/main i386 Packages [552 B]
    virtualbox-iso: Get:7 http://ppa.launchpad.net/ansible/ansible/ubuntu xenial/main Translation-en [340 B]
    virtualbox-iso: Hit:8 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease
    virtualbox-iso: Fetched 19.5 kB in 0s (34.2 kB/s)
    virtualbox-iso: Reading package lists...
    virtualbox-iso: [sudo] password for vagrant: W: GPG error: http://ppa.launchpad.net/ansible/ansible/ubuntu xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 93C4A3FD7BB9C367
    virtualbox-iso: W: The repository 'http://ppa.launchpad.net/ansible/ansible/ubuntu xenial InRelease' is not signed.
    virtualbox-iso: W: There is no public key available for the following key IDs:
    virtualbox-iso: 93C4A3FD7BB9C367
    virtualbox-iso: Reading package lists...
    virtualbox-iso: Building dependency tree...
    virtualbox-iso: Reading state information...
    virtualbox-iso: The following additional packages will be installed:
    virtualbox-iso: libyaml-0-2 python-crypto python-ecdsa python-httplib2 python-jinja2
    virtualbox-iso: python-markupsafe python-paramiko python-pkg-resources python-setuptools
    virtualbox-iso: python-six python-yaml sshpass
    virtualbox-iso: Suggested packages:
    virtualbox-iso: python-crypto-dbg python-crypto-doc python-jinja2-doc python-setuptools-doc
    virtualbox-iso: The following NEW packages will be installed:
    virtualbox-iso: ansible libyaml-0-2 python-crypto python-ecdsa python-httplib2 python-jinja2
    virtualbox-iso: python-markupsafe python-paramiko python-pkg-resources python-setuptools
    virtualbox-iso: python-six python-yaml sshpass
    virtualbox-iso: 0 upgraded, 13 newly installed, 0 to remove and 0 not upgraded.
    virtualbox-iso: Need to get 2,229 kB of archives.
    virtualbox-iso: After this operation, 14.0 MB of additional disk space will be used.
    virtualbox-iso: WARNING: The following packages cannot be authenticated!
    virtualbox-iso: ansible
    virtualbox-iso: E: There were unauthenticated packages and -y was used without --allow-unauthenticated
```

The script used `ansible.sh` is very simple:

```
#!/bin/bash -eux
# install ansible
add-apt-repository ppa:ansible/ansible
/usr/bin/apt-get update
/usr/bin/apt-get -y install ansible
```

**Comment by geerlingguy** [comment] 2016-05-30 12:15
Line 6 in your log seems to state that the server was unreachable at the time. Can you try again? I had a successful packer build with exactly the same script.

**Comment by Jalle19** [comment] 2016-05-30 12:35
Funny, I totally missed that myself. Will give it a try.

**Comment by ryanmaclean** [comment] 2016-06-18 23:20
Came here with a similar problem to what @Jalle19 reported, and can also report that this should remain closed as he didn't report back :)

**Comment by Spurlos** [comment] 2016-10-20 07:47
Same bug arouse for 16.10 release.

```
E: The repository 'http://ppa.launchpad.net/ansible/ansible/ubuntu yakkety Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

```

**Comment by g000444555** [comment] 2016-12-30 18:41
Not sure this is related to the issue but I have the following problem.
The target host is localhost running ubuntu 16.04 LTS with `uname -a` reporting `Linux red-lion 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`. Also, `ansible --version` reports
```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

When I run the command:

`ansible test -C -m apt -a "name=openssl state=latest" --sudo --ask-sudo-pass`

I get the error:

```
localhost | FAILED! => {
    "changed": false,
    "cmd": "apt-get update '&&' apt-get install python-apt -y -q --force-yes",
    "failed": true,
    "msg": "W: The repository 'http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial Release' does not have a Release file.\nE: Failed to fetch http://ppa.launchpad.net/tualatrix/ppa/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found\nE: Some index files failed to download. They have been ignored, or old ones used instead.",
    "rc": 100,
    "stderr": "W: The repository 'http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial Release' does not have a Release file.\nE: Failed to fetch http://ppa.launchpad.net/tualatrix/ppa/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found\nE: Some index files failed to download. They have been ignored, or old ones used instead.\n",
    "stdout": "Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]\nGet:2 http://ppa.launchpad.net/ansible/ansible/ubuntu xenial InRelease [18.1 kB]\nHit:3 http://gr.archive.ubuntu.com/ubuntu xenial InRelease\nHit:4 http://gr.archive.ubuntu.com/ubuntu xenial-updates InRelease\nIgn:5 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial InRelease\nHit:6 http://gr.archive.ubuntu.com/ubuntu xenial-backports InRelease\nHit:7 http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease\nIgn:8 https://dl.bintray.com/sbt/debian  InRelease\nGet:9 http://ppa.launchpad.net/ansible/ansible/ubuntu xenial/main amd64 Packages [548 B]\nGet:10 http://ppa.launchpad.net/ansible/ansible/ubuntu xenial/main i386 Packages [548 B]\nGet:11 http://ppa.launchpad.net/ansible/ansible/ubuntu xenial/main Translation-en [340 B]\nGet:12 https://dl.bintray.com/sbt/debian  Release [814 B]\nHit:12 https://dl.bintray.com/sbt/debian  Release\nIgn:14 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial Release\nIgn:15 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main amd64 Packages\nIgn:16 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main i386 Packages\nIgn:17 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main all Packages\nIgn:18 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main Translation-en_US\nIgn:19 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main Translation-en\nIgn:20 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main amd64 DEP-11 Metadata\nIgn:21 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main DEP-11 64x64 Icons\nIgn:15 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main amd64 Packages\nIgn:16 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main i386 Packages\nIgn:17 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main all Packages\nIgn:18 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main Translation-en_US\nIgn:19 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main Translation-en\nIgn:20 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main amd64 DEP-11 Metadata\nIgn:21 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main DEP-11 64x64 Icons\nIgn:15 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main amd64 Packages\nIgn:16 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main i386 Packages\nIgn:17 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main all Packages\nIgn:18 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main Translation-en_US\nIgn:19 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main Translation-en\nIgn:20 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main amd64 DEP-11 Metadata\nIgn:21 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main DEP-11 64x64 Icons\nIgn:15 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main amd64 Packages\nIgn:16 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main i386 Packages\nIgn:17 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main all Packages\nIgn:18 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main Translation-en_US\nIgn:19 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main Translation-en\nIgn:20 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main amd64 DEP-11 Metadata\nIgn:21 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main DEP-11 64x64 Icons\nIgn:15 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main amd64 Packages\nIgn:16 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main i386 Packages\nIgn:17 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main all Packages\nIgn:18 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main Translation-en_US\nIgn:19 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main Translation-en\nIgn:20 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main amd64 DEP-11 Metadata\nIgn:21 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main DEP-11 64x64 Icons\nErr:15 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main amd64 Packages\n  404  Not Found\nIgn:16 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main i386 Packages\nIgn:17 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main all Packages\nIgn:18 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main Translation-en_US\nIgn:19 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main Translation-en\nIgn:20 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main amd64 DEP-11 Metadata\nIgn:21 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main DEP-11 64x64 Icons\nFetched 122 kB in 8s (14.6 kB/s)\nReading package lists...\n",
    "stdout_lines": [
        "Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]",
        "Get:2 http://ppa.launchpad.net/ansible/ansible/ubuntu xenial InRelease [18.1 kB]",
        "Hit:3 http://gr.archive.ubuntu.com/ubuntu xenial InRelease",
        "Hit:4 http://gr.archive.ubuntu.com/ubuntu xenial-updates InRelease",
        "Ign:5 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial InRelease",
        "Hit:6 http://gr.archive.ubuntu.com/ubuntu xenial-backports InRelease",
        "Hit:7 http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease",
        "Ign:8 https://dl.bintray.com/sbt/debian  InRelease",
        "Get:9 http://ppa.launchpad.net/ansible/ansible/ubuntu xenial/main amd64 Packages [548 B]",
        "Get:10 http://ppa.launchpad.net/ansible/ansible/ubuntu xenial/main i386 Packages [548 B]",
        "Get:11 http://ppa.launchpad.net/ansible/ansible/ubuntu xenial/main Translation-en [340 B]",
        "Get:12 https://dl.bintray.com/sbt/debian  Release [814 B]",
        "Hit:12 https://dl.bintray.com/sbt/debian  Release",
        "Ign:14 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial Release",
        "Ign:15 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main amd64 Packages",
        "Ign:16 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main i386 Packages",
        "Ign:17 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main all Packages",
        "Ign:18 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main Translation-en_US",
        "Ign:19 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main Translation-en",
        "Ign:20 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main amd64 DEP-11 Metadata",
        "Ign:21 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main DEP-11 64x64 Icons",
        "Ign:15 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main amd64 Packages",
        "Ign:16 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main i386 Packages",
        "Ign:17 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main all Packages",
        "Ign:18 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main Translation-en_US",
        "Ign:19 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main Translation-en",
        "Ign:20 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main amd64 DEP-11 Metadata",
        "Ign:21 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main DEP-11 64x64 Icons",
        "Ign:15 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main amd64 Packages",
        "Ign:16 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main i386 Packages",
        "Ign:17 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main all Packages",
        "Ign:18 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main Translation-en_US",
        "Ign:19 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main Translation-en",
        "Ign:20 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main amd64 DEP-11 Metadata",
        "Ign:21 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main DEP-11 64x64 Icons",
        "Ign:15 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main amd64 Packages",
        "Ign:16 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main i386 Packages",
        "Ign:17 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main all Packages",
        "Ign:18 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main Translation-en_US",
        "Ign:19 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main Translation-en",
        "Ign:20 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main amd64 DEP-11 Metadata",
        "Ign:21 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main DEP-11 64x64 Icons",
        "Ign:15 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main amd64 Packages",
        "Ign:16 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main i386 Packages",
        "Ign:17 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main all Packages",
        "Ign:18 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main Translation-en_US",
        "Ign:19 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main Translation-en",
        "Ign:20 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main amd64 DEP-11 Metadata",
        "Ign:21 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main DEP-11 64x64 Icons",
        "Err:15 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main amd64 Packages",
        "  404  Not Found",
        "Ign:16 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main i386 Packages",
        "Ign:17 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main all Packages",
        "Ign:18 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main Translation-en_US",
        "Ign:19 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main Translation-en",
        "Ign:20 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main amd64 DEP-11 Metadata",
        "Ign:21 http://ppa.launchpad.net/tualatrix/ppa/ubuntu xenial/main DEP-11 64x64 Icons",
        "Fetched 122 kB in 8s (14.6 kB/s)",
        "Reading package lists..."
    ]
}
```

**Comment by g000444555** [comment] 2016-12-30 19:11
I can confirm that the problem has been resolved after installing the `python-apt` package:

`sudo apt-get install python-apt`

Now when I run the command:

`ansible test -C -m apt -a "name=openssl state=latest" --sudo --ask-sudo-pass`

I get:

```
localhost | SUCCESS => {
    "cache_update_time": 1483124517,
    "cache_updated": false,
    "changed": false
}
```
