### ISSUE TITLE
'list' object has no attribute 'startswith'\r\n", "msg": "MODULE FAILURE"

### ISSUE THREAD

**Issue by oussemos** [ansible/ansible#16369] opened 2016-06-20 14:22 UTC
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

ansible 2.1.0.0
##### CONFIGURATION

Using https://github.com/openstack-ansible-galaxy/vagrant-ansible-openstack
##### OS / ENVIRONMENT

Centos 7
##### SUMMARY & STEPS TO REPRODUCE

I'm testing with this repo https://github.com/openstack-ansible-galaxy/vagrant-ansible-openstack
##### EXPECTED RESULTS

Deployment of Openstack
##### ACTUAL RESULTS

```
failed: [controller] (item={u'vhost': u'/', u'password': u'Uawaiyiz6tee7chietoC', u'user': u'openstack-glance'}) => 
{"failed": true, "item": {"password": "Uawaiyiz6tee7chietoC", "user": "openstack-glance", "vhost": "/"}, 
"module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  
File \"/tmp/ansible_otGN8Y/ansible_module_rabbitmq_user.py\", line 302, in <module>\r\n    main()\r\n  
File \"/tmp/ansible_otGN8Y/ansible_module_rabbitmq_user.py\", line 274, in main\r\n    if rabbitmq_user.get():\r\n  
File \"/tmp/ansible_otGN8Y/ansible_module_rabbitmq_user.py\", line 155, in get\r\n    users = self._exec(['list_users'], True)\r\n  
File \"/tmp/ansible_otGN8Y/ansible_module_rabbitmq_user.py\", line 150, in _exec\r\n    rc, out, err = self.module.run_command(cmd + args, check_rc=True)\r\n  
File \"/tmp/ansible_otGN8Y/ansible_modlib.zip/ansible/module_utils/basic.py\", line 1993, in run_command\r\n  
File \"/usr/lib/python2.7/posixpath.py\", line 261, in expanduser\r\n    if not path.startswith('~'):\r\nAttributeError: 'list' object has no attribute 'startswith'\r\n", "msg": "MODULE FAILURE", "parsed": false}
```

```
failed: [controller] (item={u'vhost': u'/', u'password': u'Zuu1aabaewoh5tei2agh', u'user': u'openstack-nova'}) => {"failed": true, "item": {"password": "Zuu1aabaewoh5tei2agh", "user": "openstack-nova", "vhost": "/"}, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  
File \"/tmp/ansible_tpcgZ7/ansible_module_rabbitmq_user.py\", line 302, in <module>\r\n    main()\r\n  
File \"/tmp/ansible_tpcgZ7/ansible_module_rabbitmq_user.py\", line 274, in main\r\n    if rabbitmq_user.get():\r\n  
File \"/tmp/ansible_tpcgZ7/ansible_module_rabbitmq_user.py\", line 155, in get\r\n    users = self._exec(['list_users'], True)\r\n  
File \"/tmp/ansible_tpcgZ7/ansible_module_rabbitmq_user.py\", line 150, in _exec\r\n    rc, out, err = self.module.run_command(cmd + args, check_rc=True)\r\n  
File \"/tmp/ansible_tpcgZ7/ansible_modlib.zip/ansible/module_utils/basic.py\", line 1993, in run_command\r\n  
File \"/usr/lib/python2.7/posixpath.py\", line 261, in expanduser\r\n    if not path.startswith('~'):\r\nAttributeError: 'list' object has no attribute 'startswith'\r\n", "msg": "MODULE FAILURE", "parsed": false}
```

```
failed: [controller] (item={u'vhost': u'/', u'password': u'seiye6Ekah1hoxeshook', u'user': u'openstack-neutron'}) => {"failed": true, "item": {"password": "seiye6Ekah1hoxeshook", "user": "openstack-neutron", "vhost": "/"}, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  
File \"/tmp/ansible_8isjDu/ansible_module_rabbitmq_user.py\", line 302, in <module>\r\n    main()\r\n  
File \"/tmp/ansible_8isjDu/ansible_module_rabbitmq_user.py\", line 274, in main\r\n    if rabbitmq_user.get():\r\n  
File \"/tmp/ansible_8isjDu/ansible_module_rabbitmq_user.py\", line 155, in get\r\n    users = self._exec(['list_users'], True)\r\n  
File \"/tmp/ansible_8isjDu/ansible_module_rabbitmq_user.py\", line 150, in _exec\r\n    rc, out, err = self.module.run_command(cmd + args, check_rc=True)\r\n  File \"/tmp/ansible_8isjDu/ansible_modlib.zip/ansible/module_utils/basic.py\", line 1993, in run_command\r\n  File \"/usr/lib/python2.7/posixpath.py\", line 261, in expanduser\r\n    if not path.startswith('~'):\r\nAttributeError: 'list' object has no attribute 'startswith'\r\n", "msg": "MODULE FAILURE", "parsed": false}
```

**Comment by sivel** [comment] 2016-06-20 14:39
This is a duplicate of the already resolved https://github.com/ansible/ansible-modules-extras/pull/2310 and will be included in the 2.1.1 release which is currently in RC1.

**Closed as completed by sivel** 2016-06-20 14:39 UTC
