### ISSUE TITLE
fetch_url is missing imports

### ISSUE THREAD

**Issue by rbak** [ansible/ansible#11167] opened 2015-06-04 16:27 UTC
Calling fetch_url from module_utils/urls.py results in the error "NameError: global name 'get_distribution' is not defined" and if this is worked around results in the error "NameError: global name 'sys' is not defined".  I didn't test any further than this but it seems like this file is missing import statements.

**Comment by sivel** [comment] 2015-06-04 16:54
Can you provide an example of the module you were using and how you are calling this?

`ansible.module_utils.urls` has a dependency on `ansible.module_utils.basic`, but due to those being fake imports and how the ansible module building works, both of those have to be imported in the module, such as:

```
from ansible.module_utils.basic import *
from ansible.module_utils.urls import *
```

The `sys` module, also comes from basic.py, as well as numerous other modules.

**Comment by rbak** [comment] 2015-06-04 17:13
We were trying to use the a10 module here:
https://github.com/ansible/ansible-modules-extras/tree/devel/network/a10

We ran into an an issue where the a10 utils couldn't find fetch_url, and so we added the module_utils.urls import to compensate, but then ran into the error above.  Adding the basic import did fix this, it just wasn't clear there was a dependency there.

**Comment by sivel** [comment] 2015-06-04 17:52
Those a10 modules appear to already have the proper imports, so they should be working as is. Are you saying they are not working?  They all import the module_utils in the correct order and should not suffer from any import issues, and should not require any modification.

**Comment by bcoca** [comment] 2015-06-05 14:09
I cannot reproduce the error, get_distribution loads for me as the import of basic.py adds it to the final rewritten module

**Comment by jimi-c** [comment] 2015-07-15 17:07
Per the above, we're going to go ahead and close this.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-07-15 17:07 UTC
Labels: needs_info, P2, bug
