### ISSUE TITLE
Allow playbook "serial:" to accept a var and not just an int

### ISSUE THREAD

**Issue by rafecolton** [ansible/ansible#8133] opened 2014-07-14 19:53 UTC
##### Issue Type:

Feature Idea
##### Ansible Version:

`ansible 1.6.6`
##### Environment:

Mac OS 10.9.4 managing Ubuntu 14.04 (also "N/A")
##### Summary:

Allow playbook `serial:` function to accept a variable argument instead of just a raw int
##### Steps To Reproduce:

At the top of a playbook, include something like this:

``` yaml
serial: "{{ (groups[server] | length / 2) | round(0, 'ceil') | int }}"
```
##### Expected Results:

Dynamically determine the parallelization of a playbook run
##### Actual Results:

An error:

```
Traceback (most recent call last):
  File "<path-to-ansible-playbook-cmd>", line 317, in <module>
    sys.exit(main(sys.argv[1:]))
  File "<path-to-ansible-playbook-cmd>", line 257, in main
    pb.run()
  File "<path-to-ansible-package>/ansible/playbook/__init__.py", line 289, in run
    play = Play(self, play_ds, play_basedir, vault_password=self.vault_password)
  File "<path-to-ansible-package>/ansible/playbook/play.py", line 115, in __init__
    self.serial           = int(ds.get('serial', 0))
ValueError: invalid literal for int() with base 10: "{{(groups[server] | length / 2) | round(0, 'ceil') | int}}"
```

**Comment by bcoca** [comment] 2014-07-14 20:00
serial already accepts a var, your construct might be the issue. This for
example works for me:
- hosts: all
  serial: "{{ howmany|default(1)|int}}"
  gather_facts: False
  tasks:
  - debug: var=inventory_hostname
  - ping:

both w/o options and with -e "howmany=10" passed in the command line

​

**Comment by rafecolton** [comment] 2014-07-14 20:02
@bcoca was this introduced in a later version of ansible?  I tried the exact same `"{{ ... }}"` part elsewhere in the playbook to just have it echo the result and it worked just fine...

**Comment by rafecolton** [comment] 2014-07-14 20:04
Updated to `ansible 1.6.6`, same issue

**Comment by bcoca** [comment] 2014-07-14 20:05
probably, I run from current dev,  I get all the goodies and sometimes a
stack trace.​

**Comment by rafecolton** [comment] 2014-07-14 20:20
@bcoca looks like you're right about it accepting variables.  Is there something about `groups[server]` (`server` being a variable that produces an array) that makes it unavailable at that point in the playbook?

**edit:** Wow, that sentence wasn't clear at all.  The `server` variable refers to a parent host group.  What I'm wondering is if the magic `groups` variable is unavailable at that point in the playbook

**Comment by bcoca** [comment] 2014-07-14 20:42
'server' should be a string, groups[] produces the list/array.​

**Comment by rafecolton** [comment] 2014-07-14 21:38
Yes, `server` is indeed a string.  I looks like `groups[server]` resolves just fine during the playbook run but not during the evaluation of `serial:`

**Comment by srgvg** [comment] 2014-07-15 05:43
This doesn't work because serial: is not evaluated in the scope of the inventory. (It's evaluated before spawning Runner() objects, hence not per host) You can template this, but it must have a single value for the whole play, not something dependent on inventory values.

**Comment by rafecolton** [comment] 2014-07-15 23:17
@sergevanginderachter is it plausible to evaluate `serial:` in the scope of the inventory?

**Comment by srgvg** [comment] 2014-07-16 08:17
@rafecolton not currently, and also, it is not really possible: how do you want to have different serial values depending on hosts (groups) within the same play?

**Comment by jimi-c** [comment] 2014-07-16 18:55
Based on the above discussion, I'm going to close this as not a bug. If you would like to continue the discussion, please move it the ansible-project mailing list. Thanks!

**Closed as completed by jimi-c** 2014-07-16 18:55 UTC
