### ISSUE TITLE
Dynamically loading vars from vars files based on ec2 variables broken by 313f26f

### ISSUE THREAD

**Issue by flibby-jibbit** [ansible/ansible#9411] opened 2014-10-24 03:42 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

``` bash
ansible 1.8 (devel c86851be2c) last updated 2014/10/23 22:35:42 (GMT -500)
  lib/ansible/modules/core: (detached HEAD 7f611468a8) last updated 2014/10/23 22:36:35 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD a0df36c6ab) last updated 2014/10/23 22:36:35 (GMT -500)
  v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/10/23 22:36:38 (GMT -500)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/10/23 22:36:42 (GMT -500)
  configured module search path = None
```
##### Environment:

Management computer is OS X 10.9. Managing Ubuntu 12.04. Not sure it matters, though.
##### Summary:

Commit 313f26f866cec92e4dbe0e1d713a0ab0da647c98 fixed #9219, but causes a failure to properly merge variables dynamically loaded using ec2 variables.
##### Steps To Reproduce:

myplay.yml

``` yaml

---
- name: illustrate hash merge bug using module vars
  hosts: all

  vars_files:
    - myvars.yml
    - "{{ ec2_tag_Environment }}.yml"

  tasks:
    - name: inspect some_string
      debug: var=some_string
```

myvars.yml

``` yaml

---
some_string: 'this is the base value from myvars.yml'
```

myenv.yml

``` yaml

---
some_string: 'this is override value from myenv.yml'
```

and the command (1)

``` bash
$ ansible-playbook myplay.yml -i ec2.py -l 'tag_Environment_myenv'
```

(1) The command is purposefully abridged here for brevity.
##### Expected Results:

``` bash
TASK: [inspect some_string] ***************************************************
ok: [xxx.xxx.xxx.xxx] => {
    "some_string": "this is override value from myenv.yml"
}
```
##### Actual Results:

``` bash
TASK: [inspect some_string] ***************************************************
ok: [xxx.xxx.xxx.xxx] => {
    "some_string": "this is the base value from myvars.yml"
}
```

**Comment by dstillman** [comment] 2014-11-07 09:15
See also https://github.com/ansible/ansible/issues/9498, which I'm guessing is the same issue (or at least probably needs to be fixed at the same time).

**Comment by jimi-c** [comment] 2014-11-18 03:05
@dstillman I created a patch for #9498 today, could you test that out and see if you're seeing the issue still?

**Comment by dstillman** [comment] 2014-11-18 03:54
#9498 was fixed by 9a0f8f0, but now I'm seeing #9497 again.

**Comment by jimi-c** [comment] 2014-11-18 14:40
@dstillman and this issue?

**Comment by dstillman** [comment] 2014-11-18 17:32
Using `"{{ ansible_system }}.yml"` for the second vars file, this does appear to have been fixed in 9a0f8f0. (I didn't test with EC2 tag variables, but I doubt that's relevant.) Here's the test I used:

main.yml:

```
- hosts: 127.0.0.1

  vars_files:
    - myvars.yml
    - "{{ ansible_system }}.yml"

  tasks:
    - debug: var=foo

    - assert: { that: "foo == 'GOOD'" }
```

myvars.yml:

```
foo: BAD
```

Linux.yml:

```
foo: GOOD
```

**Comment by jimi-c** [comment] 2014-11-18 18:25
Ok great, I'll work on #9497 then, and leave this open until all 3 issues are confirmed fixed.

**Comment by flibby-jibbit** [comment] 2014-11-19 20:27
I just confirmed, with my original test case, that 9a0f8f015877e8f1ae3c728a035120a25d4e7fa9 did correct the issue. I ran devel HEAD (a897a5ea89dffc343087215b3f3bdc811986a623 as of 2014-11-19), and it ran correctly also.

Thanks!

**Comment by jimi-c** [comment] 2014-11-20 18:55
# Closing This Ticket

Hi!

We believe the above commits should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2014-11-20 18:55 UTC
Labels: P1, bug
