### ISSUE TITLE
local_action fails with sudo

### ISSUE THREAD

**Issue by erikm-nxp** [ansible/ansible#11148] opened 2015-06-03 15:13 UTC
##### Issue Type:

Bug report.
##### Ansible Version:

ansible 1.9.1 from MacPorts, ansible 1.9.1 from EPEL (ansible-1.9.1-1.el6.noarch)
##### Ansible Configuration:

Default.
##### Environment:

Management host: RHEL 6u5, Mac OS/X 10.10.3 (Yosemite)
Target machines: RHEL 6, CentOS 6
##### Summary:

A `local_action` for a host fails when the inventory entry for that host uses sudo.

This used to work fine in Ansible 1.7.2 through 1.8.4, but it started failing in 1.9.0.1.

It looks like Ansible tries to apply the  `ansible_sudo` for a host onto the localhost, which is obviously incorrect: a `local_action` should work on localhost with local connection (just like it did before 1.9.0.1).
##### Steps To Reproduce:

Create two VMs with Centos 6.

Inventory file:

```
centos6vm1 ansible_ssh_host=192.168.239.129 ansible_ssh_user=erik ansible_sudo=yes ansible_sudo_pass=test1234
centos6vm2 ansible_ssh_host=192.168.239.132

[vm]
centos6vm1
centos6vm2
```

Example playbook:

```

---
- hosts: vm

  tasks:
  - name: test shell
    local_action: shell "touch" "ansible-test-{{inventory_hostname}}"
            creates="ansible-test-{{inventory_hostname}}"
```
##### Expected Results:

```
$ ansible-playbook filetest.yml --limit centos6vm2

PLAY [vm] *********************************************************************

GATHERING FACTS ***************************************************************
ok: [centos6vm2]

TASK: [test shell] ************************************************************
changed: [centos6vm2 -> 127.0.0.1]

PLAY RECAP ********************************************************************
centos6vm2                 : ok=1    changed=1    unreachable=0    failed=0
```
##### Actual Results:

```
$ ansible-playbook filetest.yml --limit centos6vm1

PLAY [vm] *********************************************************************

GATHERING FACTS ***************************************************************
ok: [centos6vm1]

TASK: [test shell] ************************************************************
failed: [centos6vm1 -> 127.0.0.1] => {"failed": true, "parsed": false}
Sorry, try again.
[sudo via ansible, key=lgxsqaofduqkpnkskndzomckmkrxfddh] password:
sudo: 1 incorrect password attempt


FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/erik/filetest.retry

centos6vm1                 : ok=0    changed=0    unreachable=0    failed=1
```

**Comment by bcoca** [comment] 2015-06-03 16:11
closing as dupe of #10906

**Closed as completed by bcoca** 2015-06-03 16:11 UTC
Labels: P2, bug
