### ISSUE TITLE
Ansible group_vars from inventory don't support repeated hosts

### ISSUE THREAD

**Issue by mping** [ansible/ansible#17243] opened 2016-08-25 13:36 UTC
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

Inventory Group Vars
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = /Users/mpi10/Devel/Workspace/hapi/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Ansible group vars are being determined by host looking, and don't take account that a host may be in two different groups and have different vars per group.
##### STEPS TO REPRODUCE

Using the following inventory:

```
[app1]
host1

[app1:vars]
ports_spec=1

[app2]
host1

[app2:vars]
ports_spec=2
```

and running the command:

```
ansible -m debug -a "var=hostvars[inventory_hostname]" -i myInventory app2 | grep spec
        "ports_spec": 1
```
##### EXPECTED RESULTS

It should report `port_spec: 2`
##### ACTUAL RESULTS

It reports `port_spec: 1`. I believe the lookup for the vars is by host, but I should be able to have the same host in different groups.

**Comment by nitzmahone** [comment] 2016-08-25 17:43
Normally group vars are applied alphabetically (last writer wins), and if I change the group names in your sample to "a" and "b", I get the expected behavior. However, using "app1" and "app2" reproduces the behavior you describe, which is ... weird.

**Comment by mping** [comment] 2016-08-26 09:33
That is weirder than I thought :)

**Comment by svsool** [comment] 2016-09-02 18:28
same

**Comment by svsool** [comment] 2016-09-04 20:26
simple workaround, create host alias in inventory, and use group_vars as usual, this working as expected, because variables not shared and overridden between different host aliases

my-host-1 ansible_host=example.com
my-host-2 ansible_host=example.com

[my-host-1]
my-host-1

[my-host-2]
my-host-2

**Comment by jimi-c** [comment] 2016-11-19 04:59
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed** 2016-11-19 04:58 UTC
Labels: affects_2.0, affects_2.1, affects_2.2, affects_2.3, bug
