### ISSUE TITLE
Error validating launchpad.net SSL certificate

### ISSUE THREAD

**Issue by jcassee** [ansible/ansible#7218] opened 2014-04-29 20:14 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6
(commit 71a870a6be16c7d94debd114f60804ea2ba9ca15)
##### Environment:

Running Ansible from Ubuntu 12.04. Managed system is Ubuntu 14.04.
##### Summary:

Module `apt_repository` fails to validate launchpad.net SSL certificate.

(See also: https://groups.google.com/forum/#!topic/ansible-project/lmAp8ui0JEc)
##### Steps To Reproduce:

Run this playbook with any inventory:

```

---
- hosts: all
  gather_facts: no
  tasks:
  - apt_repository: repo='ppa:webupd8team/java'
```
##### Expected Results:

The Apt repository should have been added to `/etc/apt/sources.list.d`.
##### Actual Results:

Running the playbook gives the following error:

```
PLAY [all] ******************************************************************** 

TASK: [apt_repository repo='ppa:webupd8team/java'] **************************** 
failed: [XXX] => {"failed": true}
msg: Failed to validate the SSL certificate for launchpad.net:443. Use validate_certs=no or make sure your managed systems have a valid CA certificate installed. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/joost/test.retry

XXX        : ok=0    changed=0    unreachable=0    failed=1
```
##### Extra Information:

I extracted the temporary ca_certs file that `urls.py` feeds to `ssl.wrap_socket` and used `gnutls-cli` to check whether it contains the root certificate for launchpad.net. It verified correctly:

```
$ gnutls-cli --x509cafile tmp_ca_certs.pem launchpad.net
Processed 332 CA certificate(s).
[...]
 - Certificate[0] info:
  - subject `OU=Domain Control Validated,CN=launchpad.net', issuer `C=US,ST=Arizona,L=Scottsdale,O=GoDaddy.com\, Inc.,OU=http://cer
ts.godaddy.com/repository/,CN=Go Daddy Secure Certificate Authority - G2', RSA key 2048 bits, signed using RSA-SHA256, activated `2
014-04-08 05:33:03 UTC', expires `2014-07-25 18:24:13 UTC', SHA-1 fingerprint `3e6aa453dcc8f9888e7ee368b374d9e2b21917c5'
 - Certificate[1] info:
  - subject `C=US,ST=Arizona,L=Scottsdale,O=GoDaddy.com\, Inc.,OU=http://certs.godaddy.com/repository/,CN=Go Daddy Secure Certifica
te Authority - G2', issuer `C=US,ST=Arizona,L=Scottsdale,O=GoDaddy.com\, Inc.,CN=Go Daddy Root Certificate Authority - G2', RSA key
 2048 bits, signed using RSA-SHA256, activated `2011-05-03 07:00:00 UTC', expires `2031-05-03 07:00:00 UTC', SHA-1 fingerprint `27a
c9369faf25207bb2627cefaccbe4ef9c319b8'
 - Certificate[2] info:
  - subject `C=US,ST=Arizona,L=Scottsdale,O=GoDaddy.com\, Inc.,CN=Go Daddy Root Certificate Authority - G2', issuer `C=US,O=The Go 
Daddy Group\, Inc.,OU=Go Daddy Class 2 Certification Authority', RSA key 2048 bits, signed using RSA-SHA256, activated `2014-01-01 
07:00:00 UTC', expires `2031-05-30 07:00:00 UTC', SHA-1 fingerprint `340b2880f446fcc04e59ed33f52b3d08d6242964'
- The hostname in the certificate matches 'launchpad.net'.
- Peer's certificate is trusted
[...]
```

**Comment by jimi-c** [comment] 2014-04-29 21:26
Thanks, I'll get working on this ASAP.

**Comment by jimi-c** [comment] 2014-04-30 15:01
@jcassee I'm having trouble reproducing this one. I used the sample playbook you gave above and got this:

<pre>
# ansible-playbook 7218.yml 
PLAY [ubuntu1404] ************************************************************* 
TASK: [apt_repository repo='ppa:webupd8team/java'] **************************** 
changed: [192.168.122.113]
PLAY RECAP ******************************************************************** 
192.168.122.113            : ok=1    changed=1    unreachable=0    failed=0   
</pre>

And on the system I see the file created correctly:

<pre>
root@ubuntu1404:~# cat /etc/apt/sources.list.d/ppa_webupd8team_java_trusty.list
deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main
</pre>

As you can see, the system is 14.04 as well. I did notice the above output was `http://` so I tried this url: `https://ppa.launchpad.net/webupd8team/java/ubuntu/dists/trusty/Release`, which gives me a 404 error. Maybe this is something messed up on Ubuntu's side?

**Comment by jimi-c** [comment] 2014-04-30 15:02
Forgot to mention, `http://ppa.launchpad.net/webupd8team/java/ubuntu/dists/trusty/Release` works fine and shows the Release file as expected.

**Comment by jcassee** [comment] 2014-04-30 19:07
@jimi-c That is so strange! I think the problem is caused by something installed on my system. I installed a fresh Ubuntu 12.04 and fresh Ubuntu 14.04 Digital Ocean droplet. I then ran the following commands:

```
apt-get install -y git python-yaml python-jinja2
git clone https://github.com/ansible/ansible.git
source ansible/hacking/env-setup
echo localhost > hosts
cat > test.yml <<EOM
---
- hosts: all
  gather_facts: no
  tasks:
  - apt_repository: repo='ppa:webupd8team/java'
EOM
ansible-playbook test.yml -i hosts -c local
```

On both machines the repository was added correctly!

However, another fresh 12.04 machine I tried yesterday did have the problem. I am now trying to work out what the differences are...

**Comment by jimi-c** [comment] 2014-04-30 19:33
@jcassee sounds good. Definitely let us know, if it's something we can account for in the SSL validation code we can make sure it doesn't perform randomly like this. Thanks!

**Comment by jcassee** [comment] 2014-04-30 19:36
Alright, I found the problem. On my system, and on the system I tested yesterday, some certificates in `/etc/ssl/certs` did not end with a newline. The naive concatenation used in `urls.py` causes the start of the next certificate to appear on the same line.

Simply writing a newline after each certificate fixes the problem:
(`urls.py`, around line 156)

```
cert_file = open(full_path, 'r')
os.write(tmp_fd, cert_file.read())
os.write(tmp_fd, '\n')
cert_file.close()
```

**Comment by jimi-c** [comment] 2014-04-30 19:39
Ahh, yes. I can fix that quickly or if you'd like send a PR for it.

**Comment by jcassee** [comment] 2014-04-30 19:41
Is a PR useful? No problem creating one.

**Comment by jimi-c** [comment] 2014-04-30 19:45
It's mainly to give you credit for the fix.

**Comment by jcassee** [comment] 2014-04-30 19:46
Okay :-) that's nice. I'll create one.

**Comment by jimi-c** [comment] 2014-04-30 20:48
Merged the above, so closing this. Thanks!

**Closed as completed by jimi-c** 2014-04-30 20:48 UTC
Labels: P2, bug

**Comment by jcassee** [comment] 2014-05-01 21:26
(A bit late, but) thank you for taking the time to look into this. I would not have pursued the problem if you had not tried to reproduce the problem.

**Comment by jimi-c** [comment] 2014-05-01 21:37
No problem at all, it's what I'm here for :)

**Comment by mark-casey** [comment] 2014-05-09 20:15
To keep things working in the meantime, when the error suggets "Use validate_certs=no", to where is it referring? I don't see it as an option for apt_repository

**Comment by jimi-c** [comment] 2014-05-09 21:16
@mark-casey unfortunately that option isn't exposed for all modules that use the shared code. I'd recommend using a task to cat an empty line into each cert file, or you can manually apply the patch above to fix the issue (or just download the urls.py file from the upstream github and replace the one on your system).

**Comment by dan-v** [comment] 2014-05-12 22:52
I still have this issue with version 1.6.1 (installed through pip) which appears to have this fix in it. Running Ansible from Ubuntu 12.04. Managed system is also Ubuntu 12.04.

```
failed: [host] => {"failed": true, "item": ""}
msg: Failed to validate the SSL certificate for launchpad.net:443. Use validate_certs=no or make sure your managed systems have a valid CA certificate installed. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible

FATAL: all hosts have already failed -- aborting
```

Don't have time to debug right now, but downgrading to 1.5 solves issue for me.

**Comment by jimi-c** [comment] 2014-05-13 12:15
@dan-v that's odd, 1.6.x definitely has that fix included so definitely let us know if/when you do follow-up on it. The downside to downgrading is you will no longer be validating SSL certificates at all.

**Comment by dan-v** [comment] 2014-05-14 22:52
I tracked down the issue to a corporate http proxy that is required to get to the outside network. The python socket used to validate the certificate does not take system proxy settings into account. If I print out the actual error message I see: "[Errno 113] No route to host.".

**Comment by jimi-c** [comment] 2014-05-15 01:39
@dan-v please open up a new issue for this, thanks!

**Comment by HeisenbergTT** [comment] 2014-05-19 04:46
Did anyone actually open an issue on this? We are located in china and we get this same error. Tried this with VPN on and VPN off, both give the same error. We are basically using the "the-ansibles" projects as a base for our work and this apt repository always fails.

If no one has opened an issue I can do this.

Thanks

**Comment by jimi-c** [comment] 2014-05-19 13:21
@HeisenbergTT yes, the original has been fixed and should be included in 1.6.1. The second issue (SSL cert validation not using proxy settings) is still being worked on but should be merged in soon.

**Comment by geerlingguy** [comment] 2014-05-28 17:32
Just wanted to add another note that inside a network with a proxy (but on a part of the network that's outside the proxy, oddly enough), I got the same error with 1.6.2. When I was at home (no proxy at all), I had no issues. This was on Ubuntu 12.04 in a VirtualBox VM.

**Comment by nguyenchiencong** [comment] 2014-06-23 07:08
+1

**Comment by jefferai** [comment] 2014-08-28 22:48
I just ran into this problem, and I fixed it by rebooting the target host. I honestly couldn't tell you why it worked, but literally it wasn't working, I rebooted the target host, re-ran the playbook and it worked.

**Comment by komuw** [comment] 2014-11-25 11:12
I had the same issue and I fixed it by making sure that all my certificates in /etc/ssl/certs and /usr/local/share/ca-certificates end with a new line. Thanks to @jcassee 's comment above

**Comment by pfloride** [comment] 2014-12-17 01:36
Just had the same problem with a vagrant ubuntu box - rebooting the VM and rerunning the playbook fixed it.

**Comment by soupdiver** [comment] 2015-01-23 01:54
I'm running 1.8.2 from OSX 10.10.1 against Ubuntu 14.04 and get the same error.
I already tried to reboot the target machine without any effect

**Comment by ei-grad** [comment] 2016-09-19 15:06
Getting this on IPv6-only server.

**Comment by ei-grad** [comment] 2016-09-19 16:10
It is raised after "gaierror: (-2, 'Name or service not known')" in https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/urls.py#L689.

**Comment by ei-grad** [comment] 2016-09-19 16:12
Which is because the socket `s` is created with AF_INET.
