### ISSUE TITLE
apt_repository fails to validate SSL cert for launchpad.net

### ISSUE THREAD

**Issue by sw00** [ansible/ansible#8221] opened 2014-07-21 14:16 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.6
##### Environment:

Ubuntu 14.04 on hosts to be provisioned.
OSX with boot2docker-vm on master host.
##### Summary:

apt_repository fails to add repo, fails to validate SSL cert for launchpad.net
##### Steps To Reproduce:

Run this command to use apt_repository to add any launchpad repo.

`ansible all -i devops/docker.inventory -m apt_repository -a "repo=ppa:juju/pkgs" -vvvv`
##### Expected Results:

apt_repository should add the repository.
##### Actual Results:

```
$ ansible all -i devops/docker.inventory -m apt_repository -a "repo=ppa:chris-lea/node.js" -vvvv
<192.168.59.103> ESTABLISH CONNECTION FOR USER: root
<192.168.59.103> REMOTE_MODULE apt_repository repo=ppa:chris-lea/node.js
<192.168.59.103> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/sett/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=50061', '-o', 'IdentityFile=devops/docker/common/docker_rsa', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', '192.168.59.103', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1405949653.07-188801175664130 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1405949653.07-188801175664130 && echo $HOME/.ansible/tmp/ansible-tmp-1405949653.07-188801175664130'"]
<192.168.59.103> PUT /var/folders/y7/zy_gg2bx2_d5lx_wyl5wm7lc0000gn/T/tmpLCs86T TO /root/.ansible/tmp/ansible-tmp-1405949653.07-188801175664130/apt_repository
<192.168.59.103> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/sett/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=50061', '-o', 'IdentityFile=devops/docker/common/docker_rsa', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', '192.168.59.103', u"/bin/sh -c 'LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1405949653.07-188801175664130/apt_repository; rm -rf /root/.ansible/tmp/ansible-tmp-1405949653.07-188801175664130/ >/dev/null 2>&1'"]
192.168.59.103 | FAILED >> {
    "failed": true,
    "msg": "Failed to validate the SSL certificate for launchpad.net:443. Use validate_certs=no or make sure your managed systems have a valid CA certificate installed. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible"
}
```

**Comment by jimi-c** [comment] 2014-07-21 18:21
I am unable to reproduce this right now on devel. Is it possible it was a transient certificate error?

**Comment by mpdehaan** [comment] 2014-08-11 12:41
Hi,

I'm closing this one as we haven't seen any activity in some time.

If you have continued problems with this one on a recent version of Ansible (i.e. 1.7), please feel free to open a new ticket.   Thank you!

**Closed as completed by mpdehaan** 2014-08-11 12:41 UTC
Labels: needs_info, bug

**Comment by sw00** [comment] 2014-08-11 20:35
Hi,

It resolved itself after a day. It was particularly odd since it occurred on more than one machine. Thank you.
