### ISSUE TITLE
ansible-inventory breaks group names by replacing `-` in region names when requested as groups from aws_ec2

### ISSUE THREAD

**Issue by kdelee** [ansible/ansible#51844] opened 2019-02-06 21:11 UTC
##### SUMMARY

Groups based off of region names used to come through with dashes `-`, but now the plugin replaces them with `_`.

This munging of my group names is not helpful and breaks my ability to get groups based off of the data that is there in ec2. If I want to name something with dashes, or it has dashes in the name, let it be please.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

inventory

##### ANSIBLE VERSION

```paste below
 ansible --version
ansible 2.8.0.dev0
  config file = /home/elijah/demo_region_name_change/ansible.cfg
  configured module search path = ['/home/elijah/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']                                                                                                 
  ansible python module location = /home/elijah/env/site-packages/ansible
  executable location = /home/elijah/env/bin/ansible
  python version = 3.6.7 (default, Nov 27 2018, 20:59:50) [GCC 8.2.1 20181105 (Red Hat 8.2.1-5)]
```

##### CONFIGURATION

```paste below
INVENTORY_ENABLED(/home/elijah/demo_region_name_change/ansible.cfg) = ['aws_ec2', 'script', 'auto']   
```

##### STEPS TO REPRODUCE

`aws_ec2.yml` for the plugin to get regions as groups
```yaml
---
plugin: aws_ec2
regions:
  - us-west-1
groups:
  ec2: true
keyed_groups:
  - prefix: ""
    separator: ""
    key: placement.region
  - prefix: ""
    separator: ""
    key: placement.availability_zone
  - prefix: type  # may need to replace . with _
    key: instance_type
  - prefix: instance_state
    key: state.name
```

Call ` ansible-inventory -i aws_ec2.yml --list --export > plugin.output`, file looks like:
```
{
    "_meta": {
        "hostvars": { // redacted // },
    "all": {
        "children": [
            "instance_state_running",
            "instance_state_stopped",
            "type_m3_medium",
            "type_t2_medium",
            "type_t2_xlarge",
            "ungrouped",
            "us_west_1",
            "us_west_1a",
            "us_west_1b"
        ]
    },
    "instance_state_running": {
        "hosts": [
            "secret.example.com"
        ]
    },
    "instance_state_stopped": {
        "hosts": [
            "secret.example.com"
        ]
    },
    "type_m3_medium": {
        "hosts": [
            "secret.example.com"
        ]
    },
    "type_t2_medium": {
        "hosts": [
            "secret.example.com"
        ]
    },
    "type_t2_xlarge": {
        "hosts": [
            "secret.example.com"
        ]
    },
    "us_west_1": {
        "hosts": [
            "secret.example.com"
        ]
    },
    "us_west_1a": {
        "hosts": [
            "secret.example.com"
        ]
    },
    "us_west_1b": {
        "hosts": [
            "secret.example.com"
        ]
    }
}
``` 

Then use old script to see what used to happen with the region names:
`ansible-inventory -i ~/path/to/repos/ansible/ansible/contrib/inventory/ec2.py --list --export > script.output`
```
{
    "_meta": {
        "hostvars": { //redacted// }
    "all": {
        "children": [
            "instance_state_running",
            "instance_state_stopped",
            "type_m3_medium",
            "type_t2_medium",
            "type_t2_xlarge",
            "ungrouped",
            "us-west-1",
            "us-west-1a",
            "us-west-1b",
        ]
    },
    "instance_state_running": {
        "hosts": [
            "XX.XXX.XXX.XX"
        ]
    },
    "instance_state_stopped": {
        "hosts": [
            "secret.example.com"
        ]
    },
    "type_m3_medium": {
        "hosts": [
            "XX.XXX.XXX.XX"
        ]
    },
    "type_t2_medium": {
        "hosts": [
            "secret.example.com"
        ]
    },
    "type_t2_xlarge": {
        "hosts": [
            "secret.example.com"
        ]
    },
    "us-west-1": {
        "hosts": [
            "secret.example.com"
        ]
    },
    "us-west-1a": {
        "hosts": [
            "secret.example.com"
        ]
    },
    "us-west-1b": {
        "hosts": [
            "secret.example.com"
        ]
    },
}
```

##### EXPECTED RESULTS

Region names are what they are

##### ACTUAL RESULTS

Region names are munged and `-` replaced with `_`

**Comment by kdelee** [comment] 2019-02-06 21:13
This hurts awx ability to adopt the `aws_ec2` inventory plugin (see https://github.com/ansible/awx/issues/171 ) @AlanCoding can provide more details if needed.

**Comment by AlanCoding** [comment] 2019-02-06 21:21
Yes, users already have content that was imported by the script. If we move to plugins without this resolved, then the old groups will remain, and new groups will be imported with the difference name. Memberships with the old group won't be updated, and this will result in very hard to debug behavior changes in playbooks.

**Comment by sivel** [comment] 2019-02-06 22:14
I don't think this is anything that the `aws_ec2` inventory plugin is doing.  It may be a difference between boto2 vs boto3.

We cannot however change the default at this point. There might be the opportunity to add some form of configuration.

On another note, I would not make the assumption that the transition from the old community supported inventory scripts to the new inventory plugins is a direct transition. There was no intention that they would produce the same output.

**Comment by AlanCoding** [comment] 2019-02-07 14:15
We know what the root cause is. @s-hertel has been extremely helpful to use getting these issues fully triaged, and found the cause in this case.

https://github.com/ansible/ansible/pull/28578/files#diff-0b5241ab9313f5d4f783ad8dd8ee8524R163

The dashes were considered unsafe.

This rule is totally unique and novel with `keyed_groups` (may be called something different in different plugins), using the Constructable plugin base class.

A patch on the Ansible core side to resolve this would be very easy in terms of the code. Implementing a migration strategy on the side consuming the inventory content is nigh-impossible. The priority of this specific issue still hasn't been fully vetted, we're still triaging the list, but filing issues to catalog them all.

**Comment by wenottingham** [comment] 2019-02-07 19:43
@sivel my concern is this:
```
regions:
  - us-west-1
groups:
  ec2: true
keyed_groups:
  - prefix: ""
    separator: ""
    key: placement.region
```

Essentially, if the translation is "a group name = a parameter passed in", output should match input.

**Comment by bcoca** [comment] 2019-02-21 20:27
closing as dupe of #40581

**Closed as completed by bcoca** 2019-02-21 20:27 UTC
Labels: inventory, support:core, bug, affects_2.8
