### ISSUE TITLE
Do not fail when a skip_tag matches nothing

### ISSUE THREAD

**Issue by warrenseine** [ansible/ansible#11597] opened 2015-07-15 10:08 UTC
Hi,

It often happens, in my case, that Ansible throws telling me that a "tag" I'm willing to skip doesn't exist. Through I totally understand that it's made in order to prevent typos in the tags, it's quite frustrating.

Since I'm skipping it, could we just ignore the invalid tag?

Usually, it's only invalid because I commented out some roles in order to speed up the provisioning during development.

Regards,
Warren.

**Comment by bcoca** [comment] 2016-06-06 23:59
dupe of #10510

**Closed as completed by bcoca** 2016-06-06 23:59 UTC
Labels: feature
