### ISSUE TITLE
Ansible 2 : ERROR! 'vars_files' is not a valid attribute for a PlaybookInclude

### ISSUE THREAD

**Issue by jfcoz** [ansible/ansible#14987] opened 2016-03-16 08:09 UTC
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible --version
ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

N/A
##### Environment:

N/A
##### Summary:

With openshift ansible playbook, and ansible 2 on  : https://github.com/openshift/openshift-ansible/blob/master/playbooks/byo/openshift-cluster/config.yml : 

```
ERROR! 'vars_files' is not a valid attribute for a PlaybookInclude
```

**Comment by amenonsen** [comment] 2016-03-16 08:21
Did this _ever_ work?

**Comment by jfcoz** [comment] 2016-03-16 09:28
This works with 1.9.4, but not in 2.0.1

**Comment by bcoca** [comment] 2016-03-17 00:15
no, 1.9.4 just ignored the invalid entry.

**Comment by bcoca** [comment] 2016-03-21 15:32
closing as this is just 2.0 not ignoring invalid syntax

**Closed as completed by bcoca** 2016-03-21 15:32 UTC
Labels: bug

**Comment by ibotty** [comment] 2016-04-06 10:11
Please reopen. It seems not true, that it did not work before. Before ansible-2, the vars-file was evaluated and the playbook was included. It could not have worked otherwise.

What's the recommended way to set a vars_file and include a different playbook?

**Comment by rushabh268** [comment] 2016-04-18 19:24
Seeing this issue with ansible 2.0.1.0. Worked with 1.9.4

**Comment by detiber** [comment] 2016-04-25 20:43
@amenonsen @bcoca just wanted to follow up here. This actually did work with 1.9.4, the vars_files entries were evaluated based on the path of the included playbook.

That said, we are working on fixing it, since the fact that it even did work was a bug.

**Comment by sameetn** [comment] 2016-10-27 13:48
Any update on this issue? It looks closed but does not work in ansible 2.1

**Comment by flare-ws** [comment] 2016-11-24 12:36
+1 it does not work since ansible 2.1

**Comment by akamac** [comment] 2016-11-25 19:17
Workaround can be (but all variables will be inside 'wrapped'):
```
- include: playbook.yml
  vars:
    wrapped: "{{ lookup('file', 'variables.yml') | from_yaml }}"
```

**Comment by roderickrandolph** [comment] 2017-06-09 10:41
@bcoca if the error is caused by invalid syntax, the doc example should be updated since it's misleading: http://docs.ansible.com/ansible/playbooks_variables.html#variable-file-separation

**Comment by ahharu** [comment] 2017-10-06 13:19
this is still a bug , not fixed :(

**Comment by ahharu** [comment] 2017-10-06 15:47
Any update?

**Comment by flare-ws** [comment] 2017-10-06 16:18
Can someone check if error is still present in 2.4?

**Comment by ahharu** [comment] 2017-10-06 16:35
@flare-ws yes it is, I stumbled across this today in 2.4.0 ( latest version available on pip )

This can be solved by passing every single variable on vars, using the "wrapped" workaround or including it inside the playbooks, in all "hosts" statements. 

This adds a considerable bloat of variables in the code, and in case #3 ( including inside playbooks ) breaks the ability to override variables from higher level in hierarchy

**Comment by peterducai** [comment] 2017-11-20 16:01
for me it worked in 2.4.0 but today i'm under Fedora27 with 2.4.1 and got issue again..

```
ERROR! 'include_vars' is not a valid attribute for a Play
```

**Comment by bcoca** [comment] 2017-11-20 16:24
@peterducai that error is correct, `include_vars` is an action, so it belongs in a task.
FYI, i only saw this post cause someone commented in IRC, normally we dont see updates to closed issues.
