### ISSUE TITLE
git clone hanging with v1.8.1

### ISSUE THREAD

**Issue by mgcrea** [ansible/ansible#9710] opened 2014-12-04 09:17 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 1.8.1
```
##### Environment:

```
$ uname -a
Darwin 0x6D67 14.0.0 Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64 x86_64 i386 MacBookPro11,3 Darwin
```
##### Summary:

Since 1.8.1 update, one of my git commands hangs forever.
##### Steps To Reproduce:

```
- name: bar | Checkout project
  sudo: yes
  git: repo=git@github.com:foo/bar.git accept_hostkey=True
       force=yes remote=origin version=master
       dest=/srv/www/foo/bar
```
##### Expected Results:

It's working with ansible `v1.7.2`
##### Actual Results:

The task hangs, if I ssh and check the folder, it looks like it crashes on a submodule:

```
Submodule 'webroot/modules/col-stats' () registered for path 'webroot/modules/col-stats'
fatal: Needed a single revision
Unable to find current revision in submodule path 'webroot/modules/col-broadcast-viewer'
```

Can't reproduce it with the CLI:

```
git clone -o github git@github.com:foo/bar.git --recursive
```

**Comment by abadger** [comment] 2014-12-04 17:52
Are the submodules coming from github or from a different repository?

**Comment by abadger** [comment] 2014-12-04 17:53
If they are a different repository, this may be a duplicate of https://github.com/ansible/ansible/issues/9655

**Comment by abadger** [comment] 2014-12-04 18:18
I was able to replicate this with two repositories on github.  So it isn't host key checking.

**Comment by abadger** [comment] 2014-12-04 18:26
Sorry -- the repository I was checking against didn't have a master branch.  Once I changed your playbook to use a different branch name, the two github repo check worked.  So back to wondering if this is the host key checking issue.

**Comment by mgcrea** [comment] 2014-12-04 18:45
@abadger it hangs on a bitbucket.org submodule. might be related indeed.

**Comment by juliedavila** [comment] 2014-12-08 16:25
So this is somewhat related to something I brought up here https://groups.google.com/forum/#!topic/ansible-devel/hp5636_AAcw

Sounds like the way to go according to @mpdehaan is to use lineinfile to ensure the hostkey(s) are present in known_hosts.

**Comment by abadger** [comment] 2014-12-11 21:03
Okay, I think I've fixed this in: https://github.com/ansible/ansible-modules-core/commit/2493dda4e519b3845f5a4926a4368d65829413c2

I've tested with a github main repo and bitbucket submodule and everything appeared to work.

Thanks for the report!

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Closed as completed by abadger** 2014-12-11 21:03 UTC
Labels: P2, bug
