### ISSUE TITLE
Package install with_item list fails on EL7 client with 2.0.0 beta5

### ISSUE THREAD

**Issue by opoplawski** [ansible/ansible#12976] opened 2015-10-30 14:17 UTC
Connecting with ansible 2.0.0-beta5 from Fedora 21 host to EL7 client the following task:

```
- name: Install common packages
  action: "{{ ansible_pkg_mgr }}"
  with_items:
    - { name: bash-completion, state: present }
    - { name: libselinux-python, state: present }
    - { name: logwatch, state: present }
    - { name: sssd, state: present }
```

fails with:

```
failed: [vulcan7.cora.nwra.com] => (item={u'state': u'present', u'name': u'bash-completion'}) => {"failed": true, "item": {"name": "bash-completion", "state": "present"}, "msg": "one of the following is required: name,list"}
failed: [vulcan7.cora.nwra.com] => (item={u'state': u'present', u'name': u'libselinux-python'}) => {"failed": true, "item": {"name": "libselinux-python", "state": "present"}, "msg": "one of the following is required: name,list"}
failed: [vulcan7.cora.nwra.com] => (item={u'state': u'present', u'name': u'logwatch'}) => {"failed": true, "item": {"name": "logwatch", "state": "present"}, "msg": "one of the following is required: name,list"}
failed: [vulcan7.cora.nwra.com] => (item={u'state': u'present', u'name': u'sssd'}) => {"failed": true, "item": {"name": "sssd", "state": "present"}, "msg": "one of the following is required: name,list"}
```

It works with a Fedora 22 client (and with ansible 1.9.3).

**Comment by larsks** [comment] 2015-10-30 16:08
On my system, running the above with ansible 1.9.3 results in:

```
TASK: [Install common packages] *********************************************** 
failed: [localhost] => (item={'state': 'present', 'name': 'bash-completion'}) => {"failed": true, "item": {"name": "bash-completion", "state": "present"}}
msg: one of the following is required: name,list
failed: [localhost] => (item={'state': 'present', 'name': 'sssd'}) => {"failed": true, "item": {"name": "sssd", "state": "present"}}
msg: one of the following is required: name,list
```

But I think this may be due to a typo on your part.  The following
works correctly for me on 1.9.4:

```
- hosts: localhost
  vars:
    ansible_pkg_mgr: dnf
  tasks:
    - name: Install common packages
      action: "{{ ansible_pkg_mgr }}"
      args: "{{item}}"
      with_items:
        - { name: bash-completion, state: present }
        - { name: sssd, state: present }
```

Resulting in:

```
TASK: [Install common packages] *********************************************** 
ok: [localhost] => (item={'state': 'present', 'name': 'bash-completion'})
ok: [localhost] => (item={'state': 'present', 'name': 'sssd'})
```

But fails in 2.0.0:

```
Unexpected Exception: dictionary update sequence element #0 has length 1; 2 is required
```

The full traceback for the above is:

```
Traceback (most recent call last):
  File "/home/lars/src/ansible/bin/ansible-playbook", line 80, in <module>
    sys.exit(cli.run())
  File "/home/lars/src/ansible/lib/ansible/cli/playbook.py", line 142, in run
    results = pbex.run()
  File "/home/lars/src/ansible/lib/ansible/executor/playbook_executor.py", line 75, in run
    pb = Playbook.load(playbook_path, variable_manager=self._variable_manager, loader=self._loader)
  File "/home/lars/src/ansible/lib/ansible/playbook/__init__.py", line 51, in load
    pb._load_playbook_data(file_name=file_name, variable_manager=variable_manager)
  File "/home/lars/src/ansible/lib/ansible/playbook/__init__.py", line 89, in _load_playbook_data
    entry_obj = Play.load(entry, variable_manager=variable_manager, loader=self._loader)
  File "/home/lars/src/ansible/lib/ansible/playbook/play.py", line 111, in load
    return p.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/home/lars/src/ansible/lib/ansible/playbook/base.py", line 192, in load_data
    self._attributes[name] = method(name, ds[name])
  File "/home/lars/src/ansible/lib/ansible/playbook/play.py", line 162, in _load_tasks
    return load_list_of_blocks(ds=ds, play=self, variable_manager=self._variable_manager, loader=self._loader)
  File "/home/lars/src/ansible/lib/ansible/playbook/helpers.py", line 50, in load_list_of_blocks
    loader=loader
  File "/home/lars/src/ansible/lib/ansible/playbook/block.py", line 74, in load
    return b.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/home/lars/src/ansible/lib/ansible/playbook/base.py", line 192, in load_data
    self._attributes[name] = method(name, ds[name])
  File "/home/lars/src/ansible/lib/ansible/playbook/block.py", line 110, in _load_block
    use_handlers=self._use_handlers,
  File "/home/lars/src/ansible/lib/ansible/playbook/helpers.py", line 97, in load_list_of_tasks
    t = Task.load(task, block=block, role=role, task_include=task_include, variable_manager=variable_manager, loader=loader)
  File "/home/lars/src/ansible/lib/ansible/playbook/task.py", line 133, in load
    return t.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/home/lars/src/ansible/lib/ansible/playbook/base.py", line 181, in load_data
    ds = self.preprocess_data(ds)
  File "/home/lars/src/ansible/lib/ansible/playbook/task.py", line 169, in preprocess_data
    (action, args, delegate_to) = args_parser.parse()
  File "/home/lars/src/ansible/lib/ansible/parsing/mod_args.py", line 253, in parse
    action, args = self._normalize_parameters(thing, additional_args=additional_args)
  File "/home/lars/src/ansible/lib/ansible/parsing/mod_args.py", line 140, in _normalize_parameters
    final_args.update(additional_args)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

At the time the above `final_args.update(additional_args)` is called,
`additional_args` still contains `{{item}}` and has not yet been
templated.

**Comment by larsks** [comment] 2015-10-30 17:32
Adding to the excitement, this "works":

```
- hosts: localhost
  vars:
    ansible_pkg_manager: dnf
    packages:
      - name: bash
        state: present
      - name: git
        state: latest
    testvar:
      var: item
  tasks:
    - action: "{{ansible_pkg_manager}}"
      args:
        name: "{{item.name}}"
        state: "{{item.state}}"
      with_items: packages
```

But at the time the decision is made re: whether or not to squash the
items, `action` is `{{ ansible_pkg_mgr }}`, so even though this is
using the `dnf` module, it is being run multiple times, rather than
getting batched.

If we modify the task to explicitly use `dnf`...

```
- name: Install common packages                                             
  dnf:                                                                      
    name: "{{item.name}}"                                                   
    state: "{{item.state}}"                                                 
  with_items:                                                               
    - { name: bash-completion, state: present }                             
    - { name: sssd, state: present }                                        
```

...it fails differently:

```
TASK [Install common packages] *************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "ERROR! 'unicode object' has no attribute 'state'"} 
```

This is a result of the `_squash_items` method in `lib/ansible/executor/task_executor.py` ([here](https://github.com/ansible/ansible/blob/devel/lib/ansible/executor/task_executor.py#L227)), which transforms our item list from this:

```
[
{u'state': u'present', u'name': u'bash-completion'},
{u'state': u'present', u'name': u'sssd'}
]
```

To this:

```
[u'bash-completion,sssd']
```

Of course, the task in this example works fine under 1.9.3, but without the batching behavior.

**Comment by opoplawski** [comment] 2015-10-30 18:06
Ah, sorry I missed that this was failing with F22 as well.  But it does seem that there are some issues surrounding this in any case.

**Comment by bcoca** [comment] 2015-11-01 22:28
in 2.0 you have the generic package manager:

```
- name: Install common packages                                             
  package:                                                                      
    name: "{{item.name}}"                                                   
    state: "{{item.state}}"                                                 
  with_items:                                                               
    - { name: bash-completion, state: present }                             
    - { name: sssd, state: present }                                        
```

**Comment by abadger** [comment] 2015-11-01 22:29
Still won't work because of bugs in how we handle with_items, though.

**Comment by abadger** [comment] 2015-11-05 02:39
Thanks @larska, you seem to have uncovered three errors:
- _squash_items() is unable to handle non-string items.  I looked at the 1.9.4 behaviour and in that version we skip optimizing in this case.
- Using `action: {{ ansible_pkg_mgr }}` doesn't trigger the optimization because the module's name has not been templated yet.  This works in 1.9.x
- Specifying args: "{{ items }}" does not work because the value of args has not been templated by the time we get ready to use it.  This works in 1.9.x

**Comment by abadger** [comment] 2015-11-05 19:00
Okay, so the first two problems should be fixed now.  @jimi-c, @bcoca, and I have been talking about whether to fix, deprecate, or disallow the last issue in 2.0 (using `args: "{{item}}"`).  We've pretty much settled on one of the latter two but aren't sure which yet.

The better syntax for that portion of the issue is:

```
  action: "{{ ansible_pkg_mgr }}"
    name: "{{item.name}}"                                                   
    state: "{{item.state}}"                                                 
  with_items:                                                               
    - { name: bash-completion, state: present }                             
    - { name: sssd, state: present }
```

or:

```
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: "{{item.name}}"                                                   
    state: "{{item.state}}"                                                 
  with_items:                                                               
    - { name: bash-completion, state: present }                             
    - { name: sssd, state: present }
```

Both of those should now work with the current devel.

**Comment by jimi-c** [comment] 2016-06-27 21:56
Closing, as this was resolved a while back and just cleaning up old issues.

**Closed as completed by jimi-c** 2016-06-27 21:56 UTC
Labels: bug
