### ISSUE TITLE
label not displayed for included files when looping over include_tasks

### ISSUE THREAD

**Issue by dnmvisser** [ansible/ansible#68820] opened 2020-04-09 16:32 UTC
##### SUMMARY
When looping over include_tasks, ansible correctly prints out labels for skipped files, but not for included files.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
unsure

##### ANSIBLE VERSION

```
ansible 2.9.6
  config file = /Users/dnmvisser/.ansible.cfg
  configured module search path = ['/Users/dnmvisser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/dnmvisser/.ansible_virtualenvs/ansible-2.9.6/lib/python3.7/site-packages/ansible
  executable location = /Users/dnmvisser/.ansible_virtualenvs/ansible-2.9.6/bin/ansible
  python version = 3.7.7 (default, Mar 10 2020, 15:43:33) [Clang 11.0.0 (clang-1100.0.33.17)]
```

##### CONFIGURATION

```
ALLOW_WORLD_READABLE_TMPFILES(/Users/dnmvisser/.ansible.cfg) = True
DEFAULT_LOAD_CALLBACK_PLUGINS(/Users/dnmvisser/.ansible.cfg) = False
DEFAULT_NO_TARGET_SYSLOG(/Users/dnmvisser/.ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/Users/dnmvisser/.ansible.cfg) = yaml
INTERPRETER_PYTHON(/Users/dnmvisser/.ansible.cfg) = python3
LOCALHOST_WARNING(/Users/dnmvisser/.ansible.cfg) = False
RETRY_FILES_ENABLED(/Users/dnmvisser/.ansible.cfg) = False
USE_PERSISTENT_CONNECTIONS(/Users/dnmvisser/.ansible.cfg) = True
```

##### OS / ENVIRONMENT

```Darwin NUC8i5BEK.local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64```

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - include_tasks: task.yml
    with_items:
      - 1
      - 2
      - 3
      - 4
    loop_control:
      label: "{{ item }}"
    when: item > 2

```

##### EXPECTED RESULTS

```TASK [include_tasks] *********************************************************************************************************************************************************************
skipping: [localhost] => (item=1) 
skipping: [localhost] => (item=2) 
included: /ansible/task.yml for localhost => (item=3)
included: /ansible/task.yml for localhost => (item=4)
```
##### ACTUAL RESULTS

```
TASK [include_tasks] **********************************************************************************************************************************************
skipping: [localhost] => (item=1) 
skipping: [localhost] => (item=2) 
included: /ansible/task.yml for localhost
included: /ansible/task.yml for localhost
```

This very feature appears to have been requested a while ago: https://github.com/ansible/ansible/issues/42301, and implemented in https://github.com/ansible/ansible/pull/42478, but that either never, or broke somewhere along the line.

**Comment by sivel** [comment] 2020-04-09 16:41
Duplicate of https://github.com/ansible/ansible/issues/65904

**Closed as completed by sivel** 2020-04-09 16:41 UTC
