### ISSUE TITLE
ansible.cfg - ansible-vault does not recognize 'vault_password_file' setting

### ISSUE THREAD

**Issue by klauern** [ansible/ansible#28786] opened 2017-08-29 16:58 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible-vault, ansible

##### ANSIBLE VERSION

```
$ ansible --version                           
ansible 2.3.1.0
  config file = /home/rundeck/ESBAnsible/ansible.cfg
  configured module search path = [u'./library']
  python version = 2.7.5 (default, Sep  5 2016, 02:30:38) [GCC 4.8.5 20150623 (Red Hat 4.8.5-9)]
```

##### CONFIGURATION
No `ANSIBLE_*` env settings

##### OS / ENVIRONMENT
OL7

##### SUMMARY
When trying to script out using a per-project `ansible.cfg`, I found that the `vault_password_file` field doesn't seem to be used when running playbooks or ansible, or even `ansible-vault view` itself.

##### STEPS TO REPRODUCE

Given an Ansible config file like so:

```ini
[defaults]
remote_user             = user
inventory               = inventory/hosts.ini
roles_path              = roles
library                 = library
forks                   = 20
transport               = smart
callback_whitelist      = timer
callback_plugins        = callback_plugins
vault_password_file = /home/user/ansible-test/.vault-pass.txt
```

When I run the command-line to pass in the `ANSIBLE_CONFIG`, it prompts me for a password that is already present:

```sh
$ ANSIBLE_CONFIG=ansible.cfg ansible-vault view inventory/group_vars/all/all-secrets.yml                                                                                        
Vault password:
```

But, when I run it with an additional ENV var for `ANSIBLE_VAULT_PASSWORD_FILE`, it works:
```sh
$ ANSIBLE_VAULT_PASSWORD_FILE=.vault-pass.txt ANSIBLE_CONFIG=ansible.cfg ansible-vault view inventory/group_vars/all/all-secrets.yml                                            
sudo_password: *******                       
ldap_password: *****
...
```

**Comment by nrwahl2** [comment] 2017-09-02 08:49
@klauern Can you please test with the current devel branch? I'm not able to reproduce:

```
[reid@laptop ~/git]$ grep vault_password_file /etc/ansible/ansible.cfg 
vault_password_file = /home/reid/.vault_passwords
[reid@laptop ~/git]$ cat /home/reid/.vault_passwords 
password
[reid@laptop ~/git]$ ansible-vault create test_vault.yml
[reid@laptop ~/git]$ ansible-vault view test_vault.yml
asfd
```

**Comment by mkrizek** [comment] 2018-05-11 13:02
Closing, could not reproduce the issue with the current version. Feel free to re-open if you're still seeing the problem.

**Closed as completed by mkrizek** 2018-05-11 13:02 UTC
Labels: affects_2.3, c:cli/vault, support:core, bug
