### ISSUE TITLE
with_sequence - count=1 won't run

### ISSUE THREAD

**Issue by mlaccetti** [ansible/ansible#11480] opened 2015-07-03 15:46 UTC
`ansible/lib/ansible/runner/lookup_plugins/sequence.py`

Specifically, in `run`:

```
                if self.start != self.end:
                    results.extend(self.generate_sequence())
```

This ensures that ansible cannot run with a sequence of 1, which is a common use case.  The `self.start != self.end` check can be removed, since the call to `sanity_check()` will ensure that everything is correct.

**Comment by bcoca** [comment] 2015-07-03 17:16
closing as dupe of #11422, thanks for pinpointing the issue.

**Closed as completed by bcoca** 2015-07-03 17:16 UTC
