### ISSUE TITLE
ImportError: No module named ansible.module_utils.basic in Ansible 2.1.0.0 using ansible_python_interpreter 

### ISSUE THREAD

**Issue by kodstark** [ansible/ansible#16435] opened 2016-06-24 14:27 UTC
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### CONFIGURATION

[defaults]
executable = /bin/bash
module_lang = C
callback_plugins = ./src/callback_plugins
##### OS / ENVIRONMENT

CentOS 7.1
##### SUMMARY

I'm connecting with ansible to CentOS having Python 2.6 and Solaris having Python 2.4. I'm getting import error from only Solaris target machine: "No module named ansible.module_utils.basic". CentOS machine runs same basic playbook without problem. Problem is that Solaris machine has ansible_python_interpreter:

Error happens in Ansible 2.1.0.0 which I just migrated too. 

Ansible 2.0.2, 2.0.1, 1.9.4 doesn't have this problem
##### STEPS TO REPRODUCE

Inventory

```
[group1]
centos ansible_shell_type=csh 

[group2]
solaris ansible_shell_type=csh  ansible_python_interpreter=/home/user/.python-ansible/bin/python
```

Playbook:

```
- hosts: group1
  remote_user: user
  tasks:
    - command: echo Hello1

- hosts: group2
  remote_user: user
  tasks:
    - command: echo Hello2
```

I'm using ansible_python_interpreter with simple script having modified PYTHONPATH as I can't / don't want to install json module there for Python 2.4

`/home/user/.python-ansible/bin/python`:

```
#!/bin/bash

export PYTHONPATH="/home/user/.python-ansible/site-packages"

/usr/bin/python "$@"
```

`ls /home/user/.python-ansible/site-packages`

```
simplejson
```

When I add ansible_python_interpreter to centos item in inventory then it fails also with same error "No module named ansible.module_utils.basic". (even centos machine has Python 2.6)

Is it related to setting PYTHONPATH by my ansible_python_interpreter script ? If so how can I make this working?

##### EXPECTED RESULTS

Ansible 2.1.0 working with ansible_python_interpreter.
##### ACTUAL RESULTS

Ansible failed with error "No module named ansible.module_utils.basic" on target machine.

```

```

**Comment by bcoca** [comment] 2016-06-24 14:57
you should NOT be using ansible_shell_type w/o ansible_executable being set, unless you are restricted to csh as the only shell, the setting should not be used.

The ansible_python_interpreter should not be an issue, it is designed to allow setups as the one you have.

can you try the following and past the output?:

```
ansible -m ping group2 -vvvv
```

**Comment by kodstark** [comment] 2016-06-24 15:21
[Documentation](http://docs.ansible.com/ansible/intro_configuration.html#executable) mentions executable - not ansible_executable and I do have it in above example - I have included it in report in configuration section having /bin/bash. It was only solution which I found while ago to make our servers working with Ansible 1.9.x when server have csh as default shell - otherwise it was error with setting variables before calling /bin/bash - Sure - let me include ping in next comment.

**Comment by kodstark** [comment] 2016-06-24 15:36
I don't know why ping is failing with auth error as playbook is passing auth step.

I'm adding output with  `vvvv` from playbook run - is it OK?

```
[vagrant@localhost ansible]$ ./ansible.sh -i environments/int/inventory.ini -m ping group2 --ask-pass
SSH password:
solaris.domain | UNREACHABLE! => {
    "changed": false,
    "msg": "Authentication failure.",
    "unreachable": true
}

vagrant@localhost ansible]$ ./ansible-playbook.sh -i environments/int/inventory.ini testSolaris.yml --ask-pass -vvvv
Using /vagrant/setup/ansible/ansible.cfg as config file
SSH password:
Loaded callback default of type stdout, v2.0
Loaded callback log_plays of type notification, v2.0

PLAYBOOK: testSolaris.yml ******************************************************
2 plays in testSolaris.yml

PLAY [jboss] *******************************************************************

TASK [command] *****************************************************************
task path: /vagrant/setup/ansible/testSolaris.yml:7
<solaris.domain> ESTABLISH SSH CONNECTION FOR USER: user
<solaris.domain> SSH: EXEC sshpass -d12 ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o User=user -o ConnectTimeout=10 -o ControlPath=/home/vagrant/.ansible/cp/ansible-ssh-%h-%p-%r solaris.domain '/bin/bash -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1466782089.78-160744409965522 `" && echo ansible-tmp-1466782089.78-160744409965522="` echo $HOME/.ansible/tmp/ansible-tmp-1466782089.78-160744409965522 `" ) && sleep 0'"'"''
<solaris.domain> PUT /tmp/tmplvOB5b TO /home/user/.ansible/tmp/ansible-tmp-1466782089.78-160744409965522/command
<solaris.domain> SSH: EXEC sshpass -d12 sftp -o BatchMode=no -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o User=user -o ConnectTimeout=10 -o ControlPath=/home/vagrant/.ansible/cp/ansible-ssh-%h-%p-%r '[solaris.domain]'
<solaris.domain> ESTABLISH SSH CONNECTION FOR USER: user
<solaris.domain> SSH: EXEC sshpass -d12 ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o User=user -o ConnectTimeout=10 -o ControlPath=/home/vagrant/.ansible/cp/ansible-ssh-%h-%p-%r -tt solaris.domain '/bin/bash -c '"'"'env LANG=C LC_ALL=C LC_MESSAGES=C /home/user/.python-ansible/bin/python /home/user/.ansible/tmp/ansible-tmp-1466782089.78-160744409965522/command; rm -rf "/home/user/.ansible/tmp/ansible-tmp-1466782089.78-160744409965522/" >& /dev/null && sleep 0'"'"''
fatal: [solaris.domain]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "command"}, "module_stderr": "OpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 9915\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\nShared connection to solaris.domain closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_Nf4M2o/ansible_module_command.py\", line 247, in <module>\r\n    from ansible.module_utils.basic import *\r\nImportError: No module named ansible.module_utils.basic\r\n", "msg": "MODULE FAILURE", "parsed": false}

INVOCATION:
{'module_name': u'command'}

MSG:
MODULE FAILURE

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @testSolaris.retry

PLAY RECAP *********************************************************************
solaris.domain : ok=0    changed=0    unreachable=0    failed=1
```

**Comment by kodstark** [comment] 2016-06-24 15:54
ansible_python_interpreter  looks like culprit because when I add it centos host then it fails with same error and without ansible_python_interpreter centos testcase is passing (both hosts uses csh).

**Comment by abadger** [comment] 2016-06-25 00:43
@kodstark regarding: ansible_shell_type, we fixed some problems with ansible_shell_type between 1.x and 2.1.x.  So you should check and see if you can remove that now.  I don't believe that's the problem here, though.  Looking into this now.

**Comment by abadger** [comment] 2016-06-25 01:27
Ooooohhhhh.... The answer was staring me right in the face all along.  The Ansiballz wrapper sets PYTHONPATH so that the module knows where to find the boilerplate that it needs.  Then it invokes your shell script which sets PYTHONPATH, overriding any previous PYTHONPATH.  This is why the module then can't find the ansible library code.

The right answer is probably to modify your shell script like this:

``` bash
#!/bin/sh
if [ x"$PYTHONPATH" = x ] ; then
    export PYTHONPATH="/home/user/.python-ansible/site-packages"
else
    export PYTHONPATH="/home/user/.python-ansible/site-packages:$PYTHONPATH"
fi

/usr/bin/python "$@"
```

Give that a try and see if it works.

If there's some documentation you know of that talks about modifying PYTHONPATH let me know and I'll see about changing it.

**Comment by abadger** [comment] 2016-06-30 15:26
@kodstark Did that change to your script work for you?

**Comment by abadger** [comment] 2016-07-06 21:26
The workaround mentioned in https://github.com/ansible/ansible/issues/16435#issuecomment-228499523 should address this so I'm going to close this issue now.

**Closed as completed by abadger** 2016-07-06 21:26 UTC
Labels: bug

**Comment by kodstark** [comment] 2017-02-15 17:56
Confirmed above workaround is working.

**Comment by ChillarAnand** [comment] 2017-06-20 10:57
On android, python is installed somewhere else. I am trying to run 
```
ansible all -m ping -vvvv --user root -i 192.168.0.126, -e 'ansible_python_interpreter=/data/data/org.qpython.qpy/files/bin/qpython-android5.sh'
```

It fails with 

```
Using /etc/ansible/ansible.cfg as config file
Loading callback plugin minimal of type stdout, v2.0 from /usr/local/lib/python2.7/dist-packages/ansible/plugins/callback/__init__.pyc
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/core/system/ping.py
<192.168.0.126> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.0.126> SSH: EXEC ssh -vvv -o ControlMaster=auto -o ControlPersist=60s -o ForwardAgent=yes -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=30 -o ControlPath=/home/chillaranand/.ansible/cp/ansible-ssh-%h-%p-%r 192.168.0.126 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /data/media/0/Temp/ansible-tmp-1497955944.15-134733980389027 `" && echo ansible-tmp-1497955944.15-134733980389027="` echo /data/media/0/Temp/ansible-tmp-1497955944.15-134733980389027 `" ) && sleep 0'"'"''
<192.168.0.126> PUT /tmp/tmpBtwuvY TO /data/media/0/Temp/ansible-tmp-1497955944.15-134733980389027/ping.py
<192.168.0.126> SSH: EXEC sftp -b - -vvv -o ControlMaster=auto -o ControlPersist=60s -o ForwardAgent=yes -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=30 -o ControlPath=/home/chillaranand/.ansible/cp/ansible-ssh-%h-%p-%r '[192.168.0.126]'
<192.168.0.126> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.0.126> SSH: EXEC ssh -vvv -o ControlMaster=auto -o ControlPersist=60s -o ForwardAgent=yes -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=30 -o ControlPath=/home/chillaranand/.ansible/cp/ansible-ssh-%h-%p-%r 192.168.0.126 '/bin/sh -c '"'"'chmod u+x /data/media/0/Temp/ansible-tmp-1497955944.15-134733980389027/ /data/media/0/Temp/ansible-tmp-1497955944.15-134733980389027/ping.py && sleep 0'"'"''
<192.168.0.126> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.0.126> SSH: EXEC ssh -vvv -o ControlMaster=auto -o ControlPersist=60s -o ForwardAgent=yes -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=30 -o ControlPath=/home/chillaranand/.ansible/cp/ansible-ssh-%h-%p-%r -tt 192.168.0.126 '/bin/sh -c '"'"'/data/data/org.qpython.qpy/files/bin/qpython-android5.sh /data/media/0/Temp/ansible-tmp-1497955944.15-134733980389027/ping.py; rm -rf "/data/media/0/Temp/ansible-tmp-1497955944.15-134733980389027/" > /dev/null 2>&1 && sleep 0'"'"''
192.168.0.126 | FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "ping"
    }, 
    "module_stderr": "OpenSSH_7.2p2 Ubuntu-4ubuntu2.1, OpenSSL 1.0.2g  1 Mar 2016\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 15103\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\nShared connection to 192.168.0.126 closed.\r\n", 
    "module_stdout": "TRACE (9630): enter sign_key_free\r\nTRACE (9630): enter dsa_key_free\r\nTRACE (9630): leave dsa_key_free\r\nTRACE (9630): enter rsa_key_free\r\nTRACE (9630): leave rsa_key_free\r\nTRACE (9630): leave sign_key_free\r\nTraceback (most recent call last):\r\n  File \"/storage/emulated/0/qpython/cache/ansible_W4g6t3/ansible_module_ping.py\", line 44, in <module>\r\n    from ansible.module_utils.basic import AnsibleModule\r\nImportError: No module named ansible.module_utils.basic\r\n", 
    "msg": "MODULE FAILURE"
}
```

**Comment by abadger** [comment] 2017-06-20 23:46
Please open a new bug report with a complete set of information for
reproducing (filling out the issue template and giving any additional,
relevant information)..  We don't have anyone checking closed bug reports
so were unlikely to track any continuation of a problem here.  Since this
was confirmed working after the PR was merged, this also seems like it is a
new problem, not the same one as before.
