### ISSUE TITLE
symlinked ansible path could not resolve if containing space

### ISSUE THREAD

**Issue by loranger** [ansible/ansible#32166] opened 2017-10-25 20:27 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Core

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /Users/loranger/.ansible.cfg
  configured module search path = [u'/Users/loranger/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.0.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:54:19) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

##### CONFIGURATION
DEFAULT_HOST_LIST(/Users/loranger/.ansible.cfg) = [u'/Users/loranger/.ansible/hosts']
DEFAULT_REMOTE_TMP(/Users/loranger/.ansible.cfg) = $HOME/.ansible/tmp
DEFAULT_ROLES_PATH(/Users/loranger/.ansible.cfg) = [u'/Users/loranger/.ansible/roles']
HOST_KEY_CHECKING(/Users/loranger/.ansible.cfg) = False

##### OS / ENVIRONMENT
Using Ansible on macOS 10.13 to various debians

##### SUMMARY
Since I enabled a _Business Dropbox_ account, Dropbox app renamed the default `Dropbox` folder to `Dropbox (Personnelle)` and my sync-ed ansible folder (`~/.ansible -> ~/Dropbox (Personnelle)/OSX/mackup/.ansible`) now contains a space which ansible cannot deal with.
As discussed on the mailinglist, I cannot rename the Dropbox folder because the app detect the change and rollback my modifications.
It seems my bug could be fixed if ansible would surround the inventory folder by quotes, or escape pathes.

##### STEPS TO REPRODUCE
```shell
❯ ansible chaos -m ping
```

##### EXPECTED RESULTS
```shell
chaos | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
```

##### ACTUAL RESULTS
```
ansible 2.4.0.0
  config file = /Users/loranger/.ansible.cfg
  configured module search path = [u'/Users/loranger/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.0.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:54:19) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
Using /Users/loranger/.ansible.cfg as config file
setting up inventory plugins
Parsed /Users/loranger/.ansible/hosts/composer inventory source with ini plugin
Parsed /Users/loranger/.ansible/hosts/dujour.conf inventory source with ini plugin
Parsed /Users/loranger/.ansible/hosts/hosts inventory source with ini plugin
Parsed /Users/loranger/.ansible/hosts/northern.conf inventory source with ini plugin
Parsed /Users/loranger/.ansible/hosts/perso.conf inventory source with ini plugin
Parsed /Users/loranger/.ansible/hosts/phoenix.disable inventory source with ini plugin
Parsed /Users/loranger/.ansible/hosts/puccia.conf inventory source with ini plugin
Parsed /Users/loranger/.ansible/hosts/raspberry.conf inventory source with ini plugin
Loading callback plugin minimal of type stdout, v2.0 from /usr/local/Cellar/ansible/2.4.0.0/libexec/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc
META: ran handlers
Using module file /usr/local/Cellar/ansible/2.4.0.0/libexec/lib/python2.7/site-packages/ansible/modules/system/ping.py
<chaos> ESTABLISH SSH CONNECTION FOR USER: None
<chaos> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o 'ControlPath=/Users/loranger/Dropbox (Personnelle)/OSX/mackup/.ansible/cp/eead3d7599' chaos '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1508359150.0-45696358822537 `" && echo ansible-tmp-1508359150.0-45696358822537="` echo $HOME/.ansible/tmp/ansible-tmp-1508359150.0-45696358822537 `" ) && sleep 0'"'"''
<chaos> (255, '', 'command-line line 0: garbage at end of line; "(Personnelle)/OSX/mackup/.ansible/cp/eead3d7599".\r\n')
chaos | UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh: command-line line 0: garbage at end of line; \"(Personnelle)/OSX/mackup/.ansible/cp/eead3d7599\".\r\n", 
    "unreachable": true
}
```

(Sorry to re-open my [previous issue](issues/31916), but it seems it's a real bug)

**Comment by speshuric** [comment] 2019-04-04 18:58
I've faced the same problem.
It seems that path quotation should be reviewed deeply, but the particular case can be patched "ad hoc".

In the file [ssh.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/connection/ssh.py) I've just changed the line 

```python
b_args = (b"-o", b"ControlPath=" + to_bytes(self.control_path % dict(directory=cpdir), errors='surrogate_or_strict'))
```
to
```python
b_args = (b"-o", b"ControlPath=" + to_bytes("\"" + (self.control_path % dict(directory=cpdir)) + "\"", errors='surrogate_or_strict'))
```

**NOTE:** this is not right solution in common, but there is fix for those who need fast hack
PS: this issue is still actual for ansible 2.7.9

**Comment by sivel** [comment] 2019-09-06 16:15
This should probably be closed as a duplicate of https://github.com/ansible/ansible/issues/59206 since #59206 also has a linked PR

**Closed as completed** 2019-09-07 08:02 UTC
Labels: affects_2.4, support:core, bug
