### ISSUE TITLE
pip module argument chdir cannot be used without virtualenv argument

### ISSUE THREAD

**Issue by kahowell** [ansible/ansible#41338] opened 2018-06-08 20:02 UTC
##### SUMMARY

The pip module fails when run with `chdir` argument but without `virtualenv` argument.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

pip
##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/khowell/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, May  9 2018, 11:18:37) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
```

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

Create playbook per below:

```yaml
- hosts: localhost
  tasks:
    - name: install non-existent requirements.txt
      pip:
        chdir: /tmp
        requirements: 'testalsdjfkljkl.txt
```

Note that our actual use case is here: https://github.com/candlepin/subscription-manager/blob/afdae4ce73833d3fa38128c367c20482a34fc562/vagrant/roles/subman-devel/tasks/main.yml#L140
Can `vagrant up` from the project and reproduce also... but that'll take longer

##### EXPECTED RESULTS

```
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [localhost] *************************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [install non-existent requirements.txt] **************************************************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/usr/bin/pip2 install -r test.txt", "msg": "\n:stderr: Could not open requirements file: [Errno 2] No such file or directory: 'test.txt'\n"}
	to retry, use: --limit @/home/khowell/github.com/candlepin/subscription-manager/test.retry

PLAY RECAP *******************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1
```
##### ACTUAL RESULTS

 

```
PLAY [localhost] *************************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [install non-existent requirements.txt] *********************************************************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'startswith'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_eb2w1S/ansible_module_pip.py\", line 562, in <module>\n    main()\n  File \"/tmp/ansible_eb2w1S/ansible_module_pip.py\", line 387, in main\n    env = os.path.join(chdir, env)\n  File \"/usr/lib64/python2.7/posixpath.py\", line 68, in join\n    if b.startswith('/'):\nAttributeError: 'NoneType' object has no attribute 'startswith'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
	to retry, use: --limit @/home/khowell/github.com/candlepin/subscription-manager/test.retry

PLAY RECAP *******************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1  
```

**Comment by sivel** [comment] 2018-06-08 20:08
Duplicate of https://github.com/ansible/ansible/issues/37912

**Closed as completed by sivel** 2018-06-08 20:08 UTC
