### ISSUE TITLE
Minimum privaleges required for use of Amazon cloud modules

### ISSUE THREAD

**Issue by russormes** [ansible/ansible#23704] opened 2017-04-18 14:56 UTC
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
ansible/lib/ansible/modules/cloud/amazon/*

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```
##### SUMMARY
Working with three modules from the cloud/amazon library 
- iam
- iam_policy
- s3_bucket

I had to experiment with the ansible user I created on amazon to get the user privileges correct for each module. This was because I want to allow the anisble user the MINIMUM required to perform the actions in my role and no more. Finally I created the following two policies:

```js
//Create a user
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowUsersToPerformUserActions",
            "Effect": "Allow",
            "Action": [
                "iam:GetUser",
                "iam:UpdateUser",
                "iam:CreateUser",
                "iam:CreateAccessKey",
                "iam:PutUserPolicy",
                "iam:ListUsers",
                "iam:ListAccessKeys",
                "iam:ListGroups",
                "iam:ListRoles",
                "iam:ListInstanceProfiles",
                "iam:ListGroupsForUser",
                "iam:ListUserPolicies",
                "iam:ListAttachedUserPolicies"
            ],
            "Resource": "*"
        }
    ]
}

//Create a bucket
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "DBCreateVersionedBucketWithTags",
            "Effect": "Allow",
            "Action": [
                "s3:CreateBucket",
                "s3:ListBucket",
                "s3:GetBucketPolicy",
                "s3:GetBucketVersioning",
                "s3:GetBucketRequestPayment",
                "s3:GetBucketTagging",
                "s3:PutBucketPolicy",
                "s3:PutBucketTagging",
                "s3:PutBucketVersioning"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```
However, I am still not completely sure these are the MINIMUM required by the modules. 

Can I request that the module documentation include a set of minimal permissions for performing each module operation? Or is that beyond the scope of the docs? 

Many thanks

**Comment by s-hertel** [comment] 2017-04-19 19:56
@russormes Hi, this looks like a duplicate of #22552 so I'm going to close this, but please add to the conversation on that PR if you would like to. This is a daunting task (that would then need maintenance after completion as well) although PRs to enhance the documentation are very welcome.

**Closed as completed by s-hertel** 2017-04-19 19:56 UTC
Labels: cloud, aws, affects_2.3, module, docs

**Comment by russormes** [comment] 2017-04-19 20:12
Ahh, I didn't find that when I was looking. Thanks, I will join the discussion there.

Regards
