### ISSUE TITLE
extra-vars parsing fails in 1.8.2

### ISSUE THREAD

**Issue by mgcleveland** [ansible/ansible#9729] opened 2014-12-05 17:57 UTC
##### Issue Type:

Bug report
##### Ansible Version:

1.8.2
##### Environment:

Ubuntu 14.04
##### Summary:

When using a JSON string as the argument to an ansible playbook in 1.8.2, I get the folowing error:

ERROR: failed to combine variables, expected dicts but got a 'dict' and a 'list'
##### Steps To Reproduce:

```
The format of this JSON string has not changed and has been parsed and used successfully since 1.4.  The JSON is as follows:

{
    "info": {
        "user": "ubuntu",
        "realm": "dev",
        "uuid": "194f800e27304a779d2e6137e89678f6",
        "name": "xxxxxxxxxxxxxxxxxxxxxxxxx",
        "image_type": "ebs",
        "zk_namespace": "xxxxxxxxxxxx",
        "fullname": "xxxxxxxxxxxx",
        "email": "zzzzzzzzzz@xxxxxxxxxxx.net",
        "description": "TEST"
    },
    "aws": {
        "iam": {
            "instance_profile": "",
            "aws_account_id": "xxxxxxxxxxxxxxxxxx"
        },
        "vpc": {
            "ami": "ami-xxxxxxx",
            "subnet": "subnet-xxxxxxx",
            "region": "us-west-2",
            "instance_type": "c3.large",
            "keypair": "key",
            "id": "vpc-XXXXX",
            "security_groups": [
                "sg-XXXXXXX"
            ]
        },
        "s3": {
            "ami_bucket": "bucket/name"
        },
        "region": "us-west-2",
        "volumes": [
            {
                "volume_size": "8",
                "device_name": "/dev/sda1"
            }
        ],
        "route53": {
            "record": "XXXXX",
            "type": "A",
            "overwrite": "true",
            "zone": "XXX",
            "ttl": 300
        }
    },
    "hosts": "launched",
    "user": "ubuntu",
    "tags": {
        "exclude": []
    }
}

To recreate, use the above JSON as a string argument to a playbook, similar to the following command:

ansible-playbook -vvvv playbook.yml --extra-vars "$json"
```
##### Expected Results:

Playebook is executed successfully.
##### Actual Results:

ERROR: failed to combine variables, expected dicts but got a 'dict' and a 'list'

**Comment by mgcleveland** [comment] 2014-12-05 17:59
The problem occurs in the "_validate_both_dicts(a, b)" in ansible/utils/__init__.py.  The parsing fails when validating the '"tags": {"exclude": []}' section of the JSON.

**Comment by mpdehaan** [comment] 2014-12-08 21:44
Can you provide a minimal playbook that helps reproduce this issue?  Thanks!

**Comment by mgcleveland** [comment] 2014-12-10 15:10
```
---
- hosts: localhost
  connection: local
  tasks:
   - name: echo all variables
     shell: echo {{user}} {{aws.route53.overwrite}} {{aws.route53.record}} {{aws.route53.ttl}} {{aws.route53.zone}} {{aws.route53.type}} {{aws.iam.aws_account_id}} {{aws.iam.instance_profile}} {{aws.s3.ami_bucket}} {{aws.vpc.security_groups}} {{aws.vpc.id}} {{aws.vpc.region}} {{aws.vpc.ami}} {{aws.vpc.keypair}} {{aws.vpc.subnet}} {{aws.vpc.instance_type}} {{aws.region}} {{hosts}} {{tags}} {{info.uuid}} {{info.zk_namespace}} {{info.user}} {{info.name}} {{info.description}} {{info.email}} {{info.image_type}} {{info.realm}} {{info.fullname}} {{aws.volumes}}
```

**Comment by aminjam** [comment] 2015-01-03 16:24
+1 I am getting the same error after upgrading to `v1.8.2`

**Comment by bluskool** [comment] 2015-01-20 16:26
Same error. Downgrading to 1.8.1 fixes it.

**Comment by mordi34** [comment] 2015-01-22 09:42
Same issue here too

**Comment by calmera** [comment] 2015-02-20 00:25
+1 same issue on v1.8.2

**Comment by bcoca** [comment] 2015-02-20 15:15
so, i saved the original json as test.json and used the following play:

```
- hosts: localhost
  gather_facts: false
  tasks:
    - debug: msg="{{user}} {{aws.route53.overwrite}} {{aws.route53.record}} {{aws.route53.ttl}} {{aws.route53.zone}} {{aws.route53.type}} {{aws.iam.aws_account_id}} {{aws.iam.instance_profile}} {{aws.s3.ami_bucket}} {{aws.vpc.security_groups}} {{aws.vpc.id}} {{aws.vpc.region}} {{aws.vpc.ami}} {{aws.vpc.keypair}} {{aws.vpc.subnet}} {{aws.vpc.instance_type}} {{aws.region}} {{hosts}} {{tags}} {{info.uuid}} {{info.zk_namespace}} {{info.user}} {{info.name}} {{info.description}} {{info.email}} {{info.image_type}} {{info.realm}} {{info.fullname}} {{aws.volumes}}"
```

and ran:

```
#>ansible-playbook play.yml -e @test.json
ok: [localhost] => {
    "msg": "ubuntu true XXXXX 300 XXX A xxxxxxxxxxxxxxxxxx  bucket/name ['sg-XXXXXXX'] vpc-XXXXX us-west-2 ami-xxxxxxx key subnet-xxxxxxx c3.large us-west-2 launched {'exclude': []} 194f800e27304a779d2e6137e89678f6 xxxxxxxxxxxx ubuntu xxxxxxxxxxxxxxxxxxxxxxxxx TEST zzzzzzzzzz@xxxxxxxxxxx.net ebs dev xxxxxxxxxxxx [{'volume_size': '8', 'device_name': '/dev/sda1'}]"
}
```

It seems to work fine in current 1.8.2, devel and last stable (1.8.4), the only thing is that it is not -e $test.json but -e '@test.json' (the $ notation will call for shell substitution).

are there any other special conditions to reproduce this?

**Comment by calmera** [comment] 2015-02-20 21:04
I got the issue trying to pass the actual json along, not a file holding the json content, but let me test if I got the same issue as the OP, just to be sure.

**Comment by calmera** [comment] 2015-02-20 22:18
Sorry guys, seems like my problem is related to something else.

**Comment by sumdog** [comment] 2015-02-25 22:29
I have the same issue:

My base playbook includes some roles:

```
---
- name: BigSense Database
  hosts: database
  sudo: true
  vars_files:
    - ../environment.yml
  roles:
   - security
   - database
```

and that environment.yml looks like this:

```
---
name: ubuntu-nightly-postgres
type: run
domain: internal
```

and in my security role I have:
vars/main.yml

```
---
pgp_password_path: "{{ lookup('env','HOME') }}/.password-store/vsense/{{ name }}"
pgp_password_file: "{{ pgp_password_path }}/{{ inventory_hostname }}.gpg"
```

tasks/main.yml:

```
- local_action: file path={{ pgp_password_path }} state=directory
  when: local_pgp_password_file.stat.exists == False
  sudo: False
```

This worked until I went up to ansible 1.8.4. Now I get:

```
TASK: [security | file path={{ lookup('env','HOME') }}/.password-store/vsense/{{ name }} state=directory] *** 
fatal: [database] => failed to combine variables, expected dicts but got a 'dict' and a 'str'
```

What I find really interesting is that if I try to add a `debug var=name` I get the same error message about combing dict/str. I can't even debug the variable to see what's going on. 

Gentoo only has Ansible 1.6.8 and 1.8.4. Dropping back to 1.6.8 fixed the issue.

**Comment by romainrichard** [comment] 2015-02-26 23:07
Also have an issue related to the introduction of the function "validate_both_dicts(a, b)" in ansible/utils/__init_.py.
The issue occurs when a dict variable contains another dict and when hash_behaviour=merge, here's the minimal example to reproduce it.

```
$ tree
.
├── ansible.cfg
├── group_vars
│   └── all
├── playbook.yml
└── roles
    └── my_role
        └── tasks
            └── main.yml

4 directories, 4 files

$ cat ansible.cfg 
[defaults] 
hash_behaviour=merge

$ cat group_vars/all 
---
my_var:
  a:

$ cat playbook.yml 
---
- name: my playbook
  hosts: all
  roles:
    - { role: my_role, a_var: "{{ my_var }}" }

$ cat roles/my_role/tasks/main.yml 
---
- debug: var=a_var
```

This is what happens when I run ansible on it:

```
$ ansible --version
ansible 1.8.2
  configured module search path = None

$ ansible-playbook playbook.yml -i localhost,

PLAY [my playbook] ************************************************************ 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [my_role | debug var=a_var] ********************************************* 
fatal: [localhost] => failed to combine variables, expected dicts but got a 'dict' and a 'unicode'

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/romain/playbook.retry

localhost                  : ok=1    changed=0    unreachable=1    failed=0
```

I modified the validate_both_dicts(a, b) function to look like this:

```
def _validate_both_dicts(a, b):

    if not (isinstance(a, dict) and isinstance(b, dict)):
        raise errors.AnsibleError(
            "failed to combine variables, expected dicts but got a '%s' (%s) and a '%s' (%s)" % (type(a).__name__, repr(a), type(b).__name__, repr(b))
        )
```

Now when I run ansible, it gives me more insight:

```
$ ansible-playbook playbook.yml -i localhost,

PLAY [my playbook] ************************************************************ 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [my_role | debug var=a_var] ********************************************* 
fatal: [localhost] => failed to combine variables, expected dicts but got a 'dict' ({'a': None}) and a 'unicode' (u'{{ my_var }}')

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/romain/playbook.retry

localhost                  : ok=1    changed=0    unreachable=1    failed=0
```

Note that it would work fine if I were to modify group_vars/all to this (without the nested dicts):

```
$ cat group_vars/all 
---
my_var:
  a

$ ansible-playbook playbook.yml -i localhost,

PLAY [my playbook] ************************************************************ 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [my_role | debug var=a_var] ********************************************* 
ok: [localhost] => {
    "a_var": "a"
}

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

**Comment by sumdog** [comment] 2015-04-28 09:27
I just upgraded to 1.9.0.1 and this problem seems to be resolved, at least for my particular use case I mentioned above.

**Comment by jimi-c** [comment] 2015-06-29 03:33
As the above comment indicates this issue has been resolved in the latest stable branch, we're going to go ahead and close this issue.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-06-29 03:33 UTC
Labels: needs_info, bug
