### ISSUE TITLE
--syntax-check should really check your hosts file and *_vars folders?

### ISSUE THREAD

**Issue by AntelopeSalad** [ansible/ansible#7837] opened 2014-06-19 14:09 UTC
##### Issue Type:

Bug Report / Feature Request
##### Ansible Version:

Ansible 1.6.2
##### Environment:

Xubuntu 14.04
##### Summary:

`--syntax-check` does not check the hosts file and does not check `group_vars/all.yml` or any other yaml files in your inventory folder.

Since these are required to be valid syntax for the playbook to run they should be validated by `--syntax-check`.
##### Steps To Reproduce:

`ansible-playbook site.yml -i /some/path/to/inventory/group_vars/all.yml --syntax-check`

```
# Contents of all.yml:

hello {{{{ }}: {{{}}
```
##### Expected Results:

Syntax error
##### Actual Results:

A legit playbook with no errors reported

**Comment by ssbarnea** [comment] 2016-03-24 09:10
This the clearly not a "feature idea", is just an plain old bug. Let me explain it this way: a perfect valid playbook will trigger syntax error if checked but will run fine. If that's not a bug I am in the wrong industry ;)

Reproduce it with:

```
---
- hosts:
  - "{{ some_var_from_vars_all }}"
  roles:
    - name: node
```

**Comment by jimi-c** [comment] 2016-07-09 20:32
# Switch to Proposal

Hi!

As of April of 2016, we have started using the Ansible Proposal process for large feature ideas or changes in current functionality, such as this. Because this issue has been open for so long without any action, we are going to go ahead and close it at this time. If you are still interested in seeing this new feature get into Ansible, please submit a proposal for it using this process.

https://github.com/ansible/proposals/blob/master/proposals_process_proposal.md

If you have any further questions, please let us know by stopping by our devel mailing list, or our devel IRC channel:
- #ansible-devel on Freenode
- https://groups.google.com/forum/#!forum/ansible-devel

Thank you!

**Closed as completed by jimi-c** 2016-07-09 20:32 UTC
Labels: feature
