### ISSUE TITLE
delegate_to is not propagated properly

### ISSUE THREAD

**Issue by kirtixs** [ansible/ansible#17878] opened 2016-10-03 16:21 UTC
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

delegate_to
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 4643bb4c6a) last updated 2016/10/03 16:16:10 (GMT +200)
  lib/ansible/modules/core: (detached HEAD e4c5a13a7a) last updated 2016/10/03 17:27:38 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD df35d324d6) last updated 2016/10/03 17:27:38 (GMT +200)
  configured module search path = Default w/o overrides

```
##### SUMMARY

When using `include` with `delegate_to`, `ansible_host` is set for the first level include, consecutive includes are ignored.
##### STEPS TO REPRODUCE

``` yaml
#main.yml
- hosts: localhost
  become: false

  tasks:
    - include: include_1.yml
      delegate_to: "not_localhost"

#include_1.yml
- debug: var=ansible_host

- include: include_2.yml

#include_2.yml
- debug: var=ansible_host
```
##### EXPECTED RESULTS

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
ok: [localhost -> not_localhost] => {
    "ansible_host": "not_localhost"
}

TASK [debug] *******************************************************************
ok: [localhost -> not_localhost] => {
    "ansible_host": "not_localhost"
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0   
##### ACTUAL RESULTS

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
ok: [localhost -> not_localhost] => {
    "ansible_host": "not_localhost"
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "ansible_host": "127.0.0.1"
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0   

This bug was introduced in cddf1cf98ec3fa31 in file https://github.com/ansible/ansible/blob/cddf1cf98ec3fa3150738b5f3d8edd594c464152/lib/ansible/playbook/base.py#L110  
The getter for `delegate_to` is set to `partial(_generic_g, attr_name)` but it should be `getter = partial(_generic_g_parent, attr_name)`.  
After adding this dirty workaound after the automatic getter detection the example above works:

``` python
    if attr_name == "delegate_to":
        getter = partial(_generic_g_parent, attr_name)
```

I'm not that fluent in python, otherwise I would have opened a pr.

The best,
redshark1802

**Comment by fabala** [comment] 2016-11-04 11:30
Hello,

Will this bug be fixed soon?
Thanks!

For information, I encounter the same issue with new Ansible 2.2 "include_role" task.
The fix provided by redshark1802 works also in this case.

**Comment by bcoca** [comment] 2016-11-04 15:41
dupe of #18315

**Closed as completed by bcoca** 2016-11-04 15:41 UTC
Labels: affects_2.2, bug
