### ISSUE TITLE
Junos commands and XML format issues related with Python 2.7

### ISSUE THREAD

**Issue by garfieldairlines** [ansible/ansible#26236] opened 2017-06-29 12:20 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

junos_command (but not only !)

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

##### OS / ENVIRONMENT

Linux 4.4.0-21-generic
##### SUMMARY

By using the junos services by using "commands" or "rpcs" I have issues with XML and python, even with a empty "commands". I tried the commands directly on my Juniper switch where it works, but ansible just rejects it.

For your information a connexion issue can be excluded because a junos_netconf stating "present" for the netconf port 22 has worked just before a junos_command request on the same playbook.
##### STEPS TO REPRODUCE

```yaml
  - name: run commands
    junos_command:
      rpcs: get-software-information
      port: 22
      host: testswitch
      username: netscreen
      password: netscreen
      transport: cli
```

##### ACTUAL RESULTS

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_iupXjm/ansible_module_junos_command.py", line 388, in <module>
    main()
  File "/tmp/ansible_iupXjm/ansible_module_junos_command.py", line 338, in main
    responses = rpc(module, items)
  File "/tmp/ansible_iupXjm/ansible_module_junos_command.py", line 225, in rpc
    reply = send_request(module, element)
  File "/tmp/ansible_iupXjm/ansible_modlib.zip/ansible/module_utils/netconf.py", line 59, in send_request
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1311, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0

fatal: [testswitch]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_iupXjm/ansible_module_junos_command.py\", line 388, in <module>\n    main()\n  File \"/tmp/ansible_iupXjm/ansible_module_junos_command.py\", line 338, in main\n    responses = rpc(module, items)\n  File \"/tmp/ansible_iupXjm/ansible_module_junos_command.py\", line 225, in rpc\n    reply = send_request(module, element)\n  File \"/tmp/ansible_iupXjm/ansible_modlib.zip/ansible/module_utils/netconf.py\", line 59, in send_request\n  File \"/usr/lib/python2.7/xml/etree/ElementTree.py\", line 1311, in XML\n    parser.feed(text)\n  File \"/usr/lib/python2.7/xml/etree/ElementTree.py\", line 1653, in feed\n    self._raiseerror(v)\n  File \"/usr/lib/python2.7/xml/etree/ElementTree.py\", line 1517, in _raiseerror\n    raise err\nxml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
```

**Comment by ganeshrn** [comment] 2017-06-29 12:46
@garfieldairlines Are you seeing this issue only for `get-software-information` or for other rpc's as well?

**Comment by garfieldairlines** [comment] 2017-06-29 12:48
I didn't tried any other RPC, but any commands (even a empty "" field) will result in the same error.

**Comment by ganeshrn** [comment] 2017-06-30 06:43
@garfieldairlines The issue seems to be caused while parsing `xml rpc` response received from the remote device.

Can you please share more details of your environment so that I can try to reproduce it in my setup.

FYI: `junos_netconf` is using `cli` as underlying transport which does does not involve `xml rpc` response parsing that's why it is working for you.

For remaining `junos` modules transport defaults to `netconf`.

**Comment by garfieldairlines** [comment] 2017-06-30 08:59
It's a SSG 140 on default configuration (therefore "netscreen").

**Comment by ganeshrn** [comment] 2017-06-30 09:37
What is the os and its version running on device?

**Comment by garfieldairlines** [comment] 2017-06-30 10:30
Hardware Version: 1010(0)-(00), FPGA checksum: 00000000, VLAN1 IP (0.0.0.0)
Software Version: 6.3.0r2.0, Type: Firewall+VPN
File Name: screenos_image, Checksum: 7f28a9c1

I hope it's what you wanted to know.

**Comment by ganeshrn** [comment] 2017-06-30 14:54
Thank you the information. I am not sure if `junos` modules work with `screenos`.
 As I don't have access to `screenos` I won't be able to reproduce the issue.

It fails at this [line](https://github.com/ansible/ansible/blob/stable-2.3/lib/ansible/module_utils/netconf.py#L59)

You can add some debug logs in `module_utils/netconf.py` to print `out` in a file and check what is wrong with response. 
For eg.
```
    import logging
    logging.basicConfig(filename='<log-file-path>', level=logging.DEBUG)
    logging.debug("Type %s" % type(out))
    logging.debug("Out %s" % out)
    return fromstring(out)
```

**Comment by garfieldairlines** [comment] 2017-06-30 14:57
Will do, but you will have to wait 10 days for an answer on my side I'm afraid… But I won't forget it !

**Comment by garfieldairlines** [comment] 2017-07-10 08:13
@ganeshrn ah I'm sorry just looked the code and your logging snippet, I'm sorry but I'm not really a developer, and quite frankly I feel quite dumb about how I'm supposed to do it.
How am I supposed to add the debug function ? ( sorry :cry: )

**Comment by ganeshrn** [comment] 2017-07-10 09:38
@garfieldairlines 
No worries.

You can follow the steps given [here](https://gist.github.com/ganeshrn/f638141b7bf03992770f68ab33a0b803) to get started
and here is the Ansible [developer guide](https://docs.ansible.com/ansible/dev_guide/) for more details

If you are stuck you can ping me on irc (nick: ganeshrn)
I am also available in Ansible channels
`#ansible-devel`
`#ansible-network`

Also, we don't have any immediate plans to support `screenos` in Ansible, unless someone raises a pull request to add support for it.

**Comment by garfieldairlines** [comment] 2017-07-11 11:46
Sadly I don't have the time, nor the skills to write such a thing for screenos. However, is it possible to write in the Ansible documentation that screenos isn't supported to avoid other admins to fall in the same trap than me ?

Thank you.

**Comment by calfonso** [comment] 2017-08-18 15:27
As screenos isn't supported, I'm closing this issue.

**Closed as completed by calfonso** 2017-08-18 15:27 UTC
Labels: networking, affects_2.3, support:core, bug
