### ISSUE TITLE
Regression: Ansible 1.9.5-1 does not load group or host variables

### ISSUE THREAD

**Issue by nikut** [ansible/ansible#15093] opened 2016-03-22 15:41 UTC
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 1.9.5 (detached HEAD cdfbc4243a) last updated 2016/03/22 13:00:45 (GMT +300)
  lib/ansible/modules/core: (detached HEAD 44f55986d8) last updated 2016/03/22 13:03:25 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD 114b70dba0) last updated 2016/03/22 13:03:28 (GMT +300)
```
##### Ansible Configuration:

Default
##### Environment:

Control host CentOS 5.11 or OS X 10.11.3, managed host is not relevant
##### Summary:

Ansible 1.9.5-1 does not load group or host variables from the inventory at all. This is a regression from 1.9.4-1.
##### Steps To Reproduce:

This is a synthetic test case but the same occurs in our production environment with normal playbooks and with all hosts causing massive breakage.

inventory/hosts:

```
[test]
localhost
```

inventory/group_vars/all:

```

---
test_var_all: "This is defined in inventory/group_vars/all"
```

inventory/group_vars/test:

```

---
test_var_test: "This is defined in inventory/group_vars/test"
```

inventory/host_vars/localhost:

```

---
test_var_localhost: "This is defined in inventory/host_vars/localhost"
```
##### Expected Results:

On 1.9.4-1:

```
nikut@s1977:~/ansible$ ansible -i inventory test -m debug -a var="hostvars['localhost']"
localhost | success >> {
    "var": {
        "hostvars['localhost']": {
            "group_names": [
                "test"
            ],
            "inventory_hostname": "localhost",
            "inventory_hostname_short": "localhost",
            "test_var_all": "This is defined in inventory/group_vars/all",
            "test_var_localhost": "This is defined in inventory/host_vars/localhost",
            "test_var_test": "This is defined in inventory/group_vars/test"
        }
    }
}
```
##### Actual Results:

On 1.9.5-1:

```
nikut@s1977:~/ansible$ ansible -i inventory test -m debug -a var="hostvars['localhost']"
localhost | success >> {
    "var": {
        "hostvars['localhost']": {
            "group_names": [
                "test"
            ],
            "inventory_hostname": "localhost",
            "inventory_hostname_short": "localhost"
        }
    }
}

```

**Comment by jpalomaki** [comment] 2016-03-23 08:35
We also ran into this (ansible not loading variables in `/path/to/inventory/group_vars/foo/main.yml`) and had to revert to 1.9.4. This sort of thing should really be part of ansible's release testing.

**Comment by nikut** [comment] 2016-03-23 09:08
Agreed, this is an absolute showstopper. Frankly I'm a little shocked that this kind of thing can get through unnoticed, it does not say good things about the release testing process. Also disappointing to see no activity on an issue like this for 17 hours.

**Comment by jbouzekri** [comment] 2016-03-23 17:04
Same on 2.0.1.0 : #14945.

@nikut : you say 17h. Try more than 10 days ... 

Sad. It has blocked the development of my team deployment tasks.

**Comment by abadger** [comment] 2016-03-23 17:48
As a temporary workaround, if you are able to reference the hosts file directly instead of referencing the directory that it is inside of, then it will work.  Figuring out what the difference between those two cases is now.

```
$ ansible-playbook 15093.yml -i inventory/hosts       (10:45:34)

PLAY [localhost] ************************************************************** 

TASK: [debug ] **************************************************************** 
ok: [localhost] => {
    "var": {
        "hostvars['localhost']": {
            "group_names": [
                "test"
            ],
            "inventory_hostname": "localhost",
            "inventory_hostname_short": "localhost",
            "test_var_all": "This is defined in inventory/group_vars/all",
            "test_var_in_hosts_file": "defined in hosts file",
            "test_var_localhost": "This is defined in inventory/host_vars/localhost",
            "test_var_test": "This is defined in inventory/group_vars/test"
        }
    }
}

PLAY RECAP ******************************************************************** 
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```

**Comment by abadger** [comment] 2016-03-23 17:52
git bisected to this commit:  ab18fd2171482859bebc84072471fa086ea3489c

_EDIT_: pasted the wrong hash.  This is the problem commit: e856ac2320d4bd2e8559d7e214241ec55f29325f

**Comment by abadger** [comment] 2016-03-23 18:24
@jbouzekri I just checked and this bug is not present on 2.0.1.0 or devel.  So looks like these are separate bugs.

**Comment by jbouzekri** [comment] 2016-03-23 18:25
@abadger : but look at the referenced bug report #14945. It seems it is almost the same issue no ?

**Comment by abadger** [comment] 2016-03-23 19:36
After comparing current code in stable-1.9 to code in devel I think that commit e856ac2 is wrong.  The limit bug that was intended to fix is because something is not looking at runner.basedir (the equivalent of 2.x's vars['playbook_dir']).   e856ac2 is modifying the basedir found for inventory rather than the one found for playbooks so it is doing the wrong thing.  I'm going to revert that now in stable-1.9 and then look for where the runner.basedir is being omitted when limit is given.

**Comment by abadger** [comment] 2016-03-23 22:58
Okay, this should be fixed by the revert    in 81c4817  and that problem with the --limit should be fixed by #13556.   So I'm closing this bug as fixed.

**Closed as completed by abadger** 2016-03-23 22:58 UTC
Labels: P2, bug

**Comment by nikut** [comment] 2016-03-24 09:12
@abadger Confirmed that it works now in stable-1.9, both with my test case and with our production inventory. Thank you!

Hope there will be a test case for the "inventory is directory" case from now on. Will you be making a bugfix release considering the showstopper nature of this bug?

**Comment by abadger** [comment] 2016-04-04 01:51
@nikut yes, there will be a 1.9.6... We're looking at one more bug on the 1.9 release and then we'll be putting out a release candidate.

If you'd like to make a pull request for an integration test of inventory is directory, that would be a great way for us to expand test coverage of this.   Integration tests are ansible playbooks that use the assert module to show that the test conditions are met. They live here: https://github.com/ansible/ansible/tree/devel/test/integration
