### ISSUE TITLE
[v2] failing apt task with_items in a include with_items

### ISSUE THREAD

**Issue by basz** [ansible/ansible#12736] opened 2015-10-13 19:16 UTC
Hi,

running the devel branch (@7dfce28) I found that following inconsistency

I have a playbook with an apt install task with a with_items property. That works fine. Followed by that I have an include task, again with_items (feature is now back in v2 and the reason i running level as beta1 had a bug with include and with_items)

In the included task I have an apt [task](https://gist.github.com/basz/c74dff4fb6a333433ec6#file-import_s3_backup-yml-L7) (the exact same as in the playbook) where the item property isn't populated correctly and the task is marked as [skipped](https://gist.github.com/basz/c74dff4fb6a333433ec6#file-sndout-L26).

perhaps I am doing something wrong; but when i modify the include task such that it operates without the with_items the apt task in the included file runs fine. I think {{ item }} from the with_items is somehow scoped into the apt task.

https://gist.github.com/basz/c74dff4fb6a333433ec6

**Comment by basz** [comment] 2015-10-13 19:29
ps. credentials in output are voided

**Comment by jimi-c** [comment] 2015-10-13 20:37
@basz can you run it with ANSIBLE_KEEP_REMOTE_FILES=1 (and -vvv) and gist the contents of the module as it is run on a remote target? Really, I only need the MODULE_ARGS/MODULE_COMPLEX_ARGS (be sure to censor any relevant data there).

**Comment by lufik** [comment] 2015-10-15 08:58
I hit the same bug (I'm in beta1 tag). I prepared the smallest reproducible playbook.
https://gist.github.com/lufik/a1d3d4f3395ff8124c8e

You can run it:
ansible-playbook include.yml --limit <some_host>

Output I get:
$ ansible-playbook include.yml --limit localhost -vvv
Using /etc/ansible/ansible.cfg as config file
1 plays in include.yml

PLAY ***************************************************************************

TASK [setup] *******************************************************************
<localhost> ESTABLISH SSH CONNECTION FOR USER: user
<localhost> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/user/.ansible/cp/ansible-ssh-%h-%p-%r localhost /bin/sh -c 'sudo -H -n -S -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-ogivipbmqaoxcderjdzmqsehcfmtjwzp; LANG=C LC_MESSAGES=C LC_CTYPE=C /usr/bin/python'"'"''
ok: [localhost]

TASK [include] *****************************************************************
included: debug.yml for localhost => (item=text 1)
included: debug.yml for localhost => (item=text 2)

TASK [include] *****************************************************************
included: debug.yml for localhost

TASK [Debug variable text] *****************************************************
ok: [localhost] => {
    "changed": false, 
    "text": "static"
}

PLAY RECAP *********************************************************************
localhost : ok=4    changed=0    unreachable=0    failed=0

**Comment by jimi-c** [comment] 2015-10-20 19:42
@basz / @lufik I've merged in a PR that mentioned the small reproducer above was no longer showing up as a problem, so could you please reverify against the latest version of devel to see if this is still a problem? Thanks!

**Comment by basz** [comment] 2015-10-20 21:11
I have confirmed that the playbook from @lufik now works. My playbook did not however, but I found something interesting.

As soon as i comment out my 'when' option of the include task the (included) apt and pip tasks run fine. They now both aren't marked as skipped. 
When i use the 'when' option both are marked as skipped. Thought the output of both tasks is different. 'item=boto' for the pip task vs 'item=' for the apt task.
Switched the order of the apt and pip task and/or adding more items to both lists didn't matter.

concluding: The _when_ option of an _include_ somehow interferes with the execution of other tasks that use with_items.

Would this make sense to you?

simple play here : https://gist.github.com/basz/1144e2acfa84560d2def#file-playbook-yml-L13

**Comment by jimi-c** [comment] 2015-10-21 14:36
@basz thanks, I'll continue looking into this.

**Comment by jimi-c** [comment] 2015-10-23 03:48
@basz I think I see what's going on here. The include is happening in a with loop, and you have a with loop inside the include as well. This causes the second loop to overwrite the `{{item}}` variable, which can be seen in this simple reproducer:

<pre>
# cat test.yml 
- hosts: localhost
  gather_facts: no
  tasks:
  - include: foo.yml x="{{item}}"
    with_items:
    - a
    - b
    - c
# cat foo.yml 
- command: echo "x is {{x}}, y is {{item}}"
  with_items:
  - a
  - b
  - c
TASK [include x={{item}}] ******************************************************
included: /root/testing/12876/foo.yml for localhost
included: /root/testing/12876/foo.yml for localhost
included: /root/testing/12876/foo.yml for localhost
TASK [command] *****************************************************************
changed: [localhost] => (item=a) => {"changed": true, "cmd": ["echo", "x is a, y is a"], "delta": "0:00:00.003132", "end": "2015-10-22 23:45:15.957233", "item": "a", "rc": 0, "start": "2015-10-22 23:45:15.954101", "stderr": "", "stdout": "x is a, y is a", "stdout_lines": ["x is a, y is a"], "warnings": []}
changed: [localhost] => (item=b) => {"changed": true, "cmd": ["echo", "x is b, y is b"], "delta": "0:00:01.003637", "end": "2015-10-22 23:45:17.033430", "item": "b", "rc": 0, "start": "2015-10-22 23:45:16.029793", "stderr": "", "stdout": "x is b, y is b", "stdout_lines": ["x is b, y is b"], "warnings": []}
changed: [localhost] => (item=c) => {"changed": true, "cmd": ["echo", "x is c, y is c"], "delta": "0:00:00.002598", "end": "2015-10-22 23:45:17.106864", "item": "c", "rc": 0, "start": "2015-10-22 23:45:17.104266", "stderr": "", "stdout": "x is c, y is c", "stdout_lines": ["x is c, y is c"], "warnings": []}
TASK [command] *****************************************************************
changed: [localhost] => (item=a) => {"changed": true, "cmd": ["echo", "x is a, y is a"], "delta": "0:00:00.002612", "end": "2015-10-22 23:45:17.267495", "item": "a", "rc": 0, "start": "2015-10-22 23:45:17.264883", "stderr": "", "stdout": "x is a, y is a", "stdout_lines": ["x is a, y is a"], "warnings": []}
changed: [localhost] => (item=b) => {"changed": true, "cmd": ["echo", "x is b, y is b"], "delta": "0:00:00.002633", "end": "2015-10-22 23:45:17.341061", "item": "b", "rc": 0, "start": "2015-10-22 23:45:17.338428", "stderr": "", "stdout": "x is b, y is b", "stdout_lines": ["x is b, y is b"], "warnings": []}
changed: [localhost] => (item=c) => {"changed": true, "cmd": ["echo", "x is c, y is c"], "delta": "0:00:00.002675", "end": "2015-10-22 23:45:17.418910", "item": "c", "rc": 0, "start": "2015-10-22 23:45:17.416235", "stderr": "", "stdout": "x is c, y is c", "stdout_lines": ["x is c, y is c"], "warnings": []}
TASK [command] *****************************************************************
changed: [localhost] => (item=a) => {"changed": true, "cmd": ["echo", "x is a, y is a"], "delta": "0:00:00.002546", "end": "2015-10-22 23:45:17.571484", "item": "a", "rc": 0, "start": "2015-10-22 23:45:17.568938", "stderr": "", "stdout": "x is a, y is a", "stdout_lines": ["x is a, y is a"], "warnings": []}
changed: [localhost] => (item=b) => {"changed": true, "cmd": ["echo", "x is b, y is b"], "delta": "0:00:00.002609", "end": "2015-10-22 23:45:17.646796", "item": "b", "rc": 0, "start": "2015-10-22 23:45:17.644187", "stderr": "", "stdout": "x is b, y is b", "stdout_lines": ["x is b, y is b"], "warnings": []}
changed: [localhost] => (item=c) => {"changed": true, "cmd": ["echo", "x is c, y is c"], "delta": "0:00:00.002702", "end": "2015-10-22 23:45:17.722527", "item": "c", "rc": 0, "start": "2015-10-22 23:45:17.719825", "stderr": "", "stdout": "x is c, y is c", "stdout_lines": ["x is c, y is c"], "warnings": []}
</pre>

So, the short answer for now is "don't do this" :) We currently have no mechanism for specifying the loop variable, so this will have to be something we fix down the road I think.

**Comment by jimi-c** [comment] 2015-10-23 07:29
@basz I've taken an alternate route in trying to solve this, which is to make the variable used within the loop settable per-task. This feature branch has not been merged in yet, but if you'd like to test it out and see how it works for you I'd be interested in hearing if it does resolve your issue.

Frankly, I'm a little unsure about this as a language feature, so I'm waiting to hear from some others as to what they think.

**Comment by bcoca** [comment] 2015-10-23 11:23
as a workaround in the included file do this (as first task):

```
- set_fact: mysql_databases="{{item}}"
```

**Comment by jimi-c** [comment] 2015-10-23 12:19
@basz as @bcoca notes above, best to use the above work-around for this right now, as we most likely won't include the above loop_var feature until 2.1 (if we decide to add it at all).

If you can confirm his workaround above gets you past this error, we'll go ahead and close this.

**Comment by jimi-c** [comment] 2015-10-27 18:45
Seeing no further discussion here, we're going to go ahead and close this now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-10-27 18:45 UTC
Labels: pending_action, bug

**Comment by windowsrefund** [comment] 2016-04-19 16:40
The commit does not appear to be working when using with_dict: See my comments in the commit.
