### ISSUE TITLE
module_common.py causes ImportError: No module named base64

### ISSUE THREAD

**Issue by mdfck** [ansible/ansible#24482] opened 2017-05-11 04:02 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
module_common.py

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/srv/ansible/library/']
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### OS / ENVIRONMENT

Master: RHEL 7.2. 
Managed node: OSNEXUS QuantaStor / Ubuntu 12.04.2 LTS

##### SUMMARY
ansible-playbook hangs when running authorized_keys module against on my OSNEXUS nodes. Apparently, this is caused because python's sys.path is being changed within module_common.py. I kept the remote file and added a couple of prints to show the sys.path variable before and after it is changed. The value referenced by scriptdir is being deleted from sys.path and all modules imports after that will fail with an "ImportError: no module named XXXXX" message

##### STEPS TO REPRODUCE
- Run a playbook with authorized_keys

##### EXPECTED RESULTS
Remote scripts should complete without errors and the playbook should continue

##### ACTUAL RESULTS
Playbook hangs when running authorized_key module

TASK [quantastor/setup-accounts : Installing SSH public-keys] ***************************************************************************************************************************************
task path: /srv/ansible/roles/quantastor/setup-accounts/tasks/main.yml:15
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/authorized_key.py
<fsnqnt310liv> ESTABLISH SSH CONNECTION FOR USER: root
<fsnqnt310liv> SSH: EXEC sshpass -d13 ssh -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ansible/.ansible/cp/ansible-ssh-%h-%p-%r qsnode '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<qsnode> (0, '/root\n', 'OpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 14501\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<qsnode> ESTABLISH SSH CONNECTION FOR USER: root
<qsnode> SSH: EXEC sshpass -d13 ssh -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ansible/.ansible/cp/ansible-ssh-%h-%p-%r qsnode '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1494474978.1-106591971739520 `" && echo ansible-tmp-1494474978.1-106591971739520="` echo /root/.ansible/tmp/ansible-tmp-1494474978.1-106591971739520 `" ) && sleep 0'"'"''
<qsnode> (0, 'ansible-tmp-1494474978.1-106591971739520=/root/.ansible/tmp/ansible-tmp-1494474978.1-106591971739520\n', 'OpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 14501\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<qsnode> PUT /tmp/tmpfzpQ8m TO /root/.ansible/tmp/ansible-tmp-1494474978.1-106591971739520/authorized_key.py
<qsnode> SSH: EXEC sshpass -d13 sftp -o BatchMode=no -b - -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ansible/.ansible/cp/ansible-ssh-%h-%p-%r '[qsnode]'
<qsnode> (0, 'sftp> put /tmp/tmpfzpQ8m /root/.ansible/tmp/ansible-tmp-1494474978.1-106591971739520/authorized_key.py\n', 'OpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 14501\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug2: Remote version: 3\r\ndebug2: Server supports extension "posix-rename@openssh.com" revision 1\r\ndebug2: Server supports extension "statvfs@openssh.com" revision 2\r\ndebug2: Server supports extension "fstatvfs@openssh.com" revision 2\r\ndebug2: Server supports extension "hardlink@openssh.com" revision 1\r\ndebug3: Sent message fd 6 T:16 I:1\r\ndebug3: SSH_FXP_REALPATH . -> /root size 0\r\ndebug3: Looking up /tmp/tmpfzpQ8m\r\ndebug3: Sent message fd 6 T:17 I:2\r\ndebug3: Received stat reply T:101 I:2\r\ndebug1: Couldn\'t stat remote file: No such file or directory\r\ndebug3: Sent message SSH2_FXP_OPEN I:3 P:/root/.ansible/tmp/ansible-tmp-1494474978.1-106591971739520/authorized_key.py\r\ndebug3: Sent message SSH2_FXP_WRITE I:4 O:0 S:32768\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 4 32768 bytes at 0\r\ndebug3: Sent message SSH2_FXP_WRITE I:5 O:32768 S:32768\r\ndebug3: Sent message SSH2_FXP_WRITE I:6 O:65536 S:23921\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 5 32768 bytes at 32768\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 6 23921 bytes at 65536\r\ndebug3: Sent message SSH2_FXP_CLOSE I:4\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<qsnode> ESTABLISH SSH CONNECTION FOR USER: root
<qsnode> SSH: EXEC sshpass -d13 ssh -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ansible/.ansible/cp/ansible-ssh-%h-%p-%r qsnode '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1494474978.1-106591971739520/ /root/.ansible/tmp/ansible-tmp-1494474978.1-106591971739520/authorized_key.py && sleep 0'"'"''
<qsnode> (0, '', 'OpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 14501\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<qsnode> ESTABLISH SSH CONNECTION FOR USER: root
<qsnode> SSH: EXEC sshpass -d13 ssh -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/ansible/.ansible/cp/ansible-ssh-%h-%p-%r -tt qsnode '/bin/sh -c '"'"'/usr/bin/python /root/.ansible/tmp/ansible-tmp-1494474978.1-106591971739520/authorized_key.py && sleep 0'"'"''

```
# python -m trace --trace /root/.ansible/tmp/ansible-tmp-1494451618.1-15014298871827/authorized_key.py 2>&1 
 --- modulename: authorized_key, funcname: <module>
authorized_key.py(3): ANSIBALLZ_WRAPPER = True # For test-module script to tell this is a ANSIBALLZ_WRAPPER
authorized_key.py(31): import os
authorized_key.py(32): import os.path
authorized_key.py(33): import sys
authorized_key.py(34): import __main__
authorized_key.py(54): print sys.path
['/root/.ansible/tmp/ansible-tmp-1494451618.1-15014298871827', '/usr/local/lib/python2.7/dist-packages/softlayer_object_storage-0.5.4-py2.7.egg', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-linux2', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/pymodules/python2.7']
authorized_key.py(55): scriptdir = None
authorized_key.py(56): try:
authorized_key.py(57):     scriptdir = os.path.dirname(os.path.abspath(__main__.__file__))
 --- modulename: posixpath, funcname: abspath
posixpath.py(343):     if not isabs(path):
 --- modulename: posixpath, funcname: isabs
posixpath.py(53):     return s.startswith('/')
posixpath.py(349):     return normpath(path)
 --- modulename: posixpath, funcname: normpath
posixpath.py(315):     slash, dot = (u'/', u'.') if isinstance(path, unicode) else ('/', '.')
posixpath.py(316):     if path == '':
posixpath.py(318):     initial_slashes = path.startswith('/')
posixpath.py(321):     if (initial_slashes and
posixpath.py(322):         path.startswith('//') and not path.startswith('///')):
posixpath.py(324):     comps = path.split('/')
posixpath.py(325):     new_comps = []
posixpath.py(326):     for comp in comps:
posixpath.py(327):         if comp in ('', '.'):
posixpath.py(328):             continue
posixpath.py(326):     for comp in comps:
posixpath.py(327):         if comp in ('', '.'):
posixpath.py(329):         if (comp != '..' or (not initial_slashes and not new_comps) or
posixpath.py(331):             new_comps.append(comp)
posixpath.py(326):     for comp in comps:
posixpath.py(327):         if comp in ('', '.'):
posixpath.py(329):         if (comp != '..' or (not initial_slashes and not new_comps) or
posixpath.py(331):             new_comps.append(comp)
posixpath.py(326):     for comp in comps:
posixpath.py(327):         if comp in ('', '.'):
posixpath.py(329):         if (comp != '..' or (not initial_slashes and not new_comps) or
posixpath.py(331):             new_comps.append(comp)
posixpath.py(326):     for comp in comps:
posixpath.py(327):         if comp in ('', '.'):
posixpath.py(329):         if (comp != '..' or (not initial_slashes and not new_comps) or
posixpath.py(331):             new_comps.append(comp)
posixpath.py(326):     for comp in comps:
posixpath.py(334):     comps = new_comps
posixpath.py(335):     path = slash.join(comps)
posixpath.py(336):     if initial_slashes:
posixpath.py(337):         path = slash*initial_slashes + path
posixpath.py(338):     return path or dot
 --- modulename: posixpath, funcname: dirname
posixpath.py(120):     i = p.rfind('/') + 1
posixpath.py(121):     head = p[:i]
posixpath.py(122):     if head and head != '/'*len(head):
posixpath.py(123):         head = head.rstrip('/')
posixpath.py(124):     return head
authorized_key.py(63): if scriptdir is not None:
authorized_key.py(64):     sys.path = [p for p in sys.path if p != scriptdir]
authorized_key.py(64):     sys.path = [p for p in sys.path if p != scriptdir]
authorized_key.py(64):     sys.path = [p for p in sys.path if p != scriptdir]
authorized_key.py(64):     sys.path = [p for p in sys.path if p != scriptdir]
authorized_key.py(64):     sys.path = [p for p in sys.path if p != scriptdir]
authorized_key.py(64):     sys.path = [p for p in sys.path if p != scriptdir]
authorized_key.py(64):     sys.path = [p for p in sys.path if p != scriptdir]
authorized_key.py(64):     sys.path = [p for p in sys.path if p != scriptdir]
authorized_key.py(64):     sys.path = [p for p in sys.path if p != scriptdir]
authorized_key.py(64):     sys.path = [p for p in sys.path if p != scriptdir]
authorized_key.py(64):     sys.path = [p for p in sys.path if p != scriptdir]
authorized_key.py(66): print scriptdir
/usr/lib/python2.7
authorized_key.py(67): print sys.path
['/root/.ansible/tmp/ansible-tmp-1494451618.1-15014298871827', '/usr/local/lib/python2.7/dist-packages/softlayer_object_storage-0.5.4-py2.7.egg', '/usr/lib/python2.7/plat-linux2', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/pymodules/python2.7']
authorized_key.py(69): import base64
 --- modulename: trace, funcname: _unsettrace
trace.py(80):         sys.settrace(None)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/trace.py", line 819, in <module>
    main()
  File "/usr/lib/python2.7/trace.py", line 807, in main
    t.runctx(code, globs, globs)
  File "/usr/lib/python2.7/trace.py", line 513, in runctx
    exec cmd in globals, locals
  File "/root/.ansible/tmp/ansible-tmp-1494451618.1-15014298871827/authorized_key.py", line 69, in <module>
    import base64
ImportError: No module named base64
```

**Comment by abadger** [comment] 2017-05-11 04:22
I'm afraid that running this via trace is throwing the results off because then __main__ refers to the trace module (which then ends up with scriptdir pointing to /usr/lib/python2.7).  Can you run it via 
```
python /root/.ansible/tmp/ansible-tmp-1494451618.1-15014298871827/authorized_key.py 2>&1 
```
instead and tell us what your instrumented print statements say then?

needs_info

**Comment by abadger** [comment] 2017-08-08 06:18
Closing this for lack of information.  As far as I can tell the symptoms shows are because of running under the trace module, not because of a bug in ansible.  If someone is experiencing similar errors, please open a new bug report with complete information on how to reproduce that error and we'll see what we can find.  Thanks!

**Closed as completed by abadger** 2017-08-08 06:18 UTC
Labels: needs_info, affects_2.3, c:executor/module_common, support:core, bug
