### ISSUE TITLE
Sudo fails on check_password_prompt

### ISSUE THREAD

**Issue by fvant** [ansible/ansible#11308] opened 2015-06-18 09:58 UTC
This worked fine up to 3 days ago; this commit still works:  5ed2e440260e2d06d234634305f4d61e82413f6c 

Now every SSH gets this error:

fatal: [10.22.26.38]: FAILED! => {"failed": true, "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python2.7/dist-packages/ansible-2.0.0-py2.7.egg/ansible/executor/process/worker.py\", line 118, in run\n    executor_result = TaskExecutor(host, task, job_vars, new_connection_info, self._new_stdin, self._loader, shared_loader_obj).run()\n  File \"/usr/local/lib/python2.7/dist-packages/ansible-2.0.0-py2.7.egg/ansible/executor/task_executor.py\", line 111, in run\n    res = self._execute()\n  File \"/usr/local/lib/python2.7/dist-packages/ansible-2.0.0-py2.7.egg/ansible/executor/task_executor.py\", line 266, in _execute\n    result = self._handler.run(task_vars=variables)\n  File \"/usr/local/lib/python2.7/dist-packages/ansible-2.0.0-py2.7.egg/ansible/plugins/action/normal.py\", line 27, in run\n    return self._execute_module(tmp, task_vars=task_vars)\n  File \"/usr/local/lib/python2.7/dist-packages/ansible-2.0.0-py2.7.egg/ansible/plugins/action/__init__.py\", line 355, in _execute_module\n    self._transfer_data(remote_module_path, module_data)\n  File \"/usr/local/lib/python2.7/dist-packages/ansible-2.0.0-py2.7.egg/ansible/plugins/action/__init__.py\", line 221, in _transfer_data\n    self._connection.put_file(afile, remote_path)\n  File \"/usr/local/lib/python2.7/dist-packages/ansible-2.0.0-py2.7.egg/ansible/plugins/connections/ssh.py\", line 418, in put_file\n    (returncode, stdout, stderr) = self._communicate(p, stdin, indata)\n  File \"/usr/local/lib/python2.7/dist-packages/ansible-2.0.0-py2.7.egg/ansible/plugins/connections/ssh.py\", line 181, in _communicate\n    elif self.check_password_prompt(stdout):\n  File \"/usr/local/lib/python2.7/dist-packages/ansible-2.0.0-py2.7.egg/ansible/plugins/connections/__init__.py\", line 136, in check_password_prompt\n    return self.prompt(output)\nTypeError: 'NoneType' object is not callable\n", "stdout": ""}

**Comment by bennojoy** [comment] 2015-06-18 12:34
@fvant i am not able to reproduce this, are you on the latest checkout ?

**Comment by bcoca** [comment] 2015-06-18 14:27
I broke sudo w NOPASSWORD while fixing the diff password options, should be fixed in latest commit.

**Closed as completed by bcoca** 2015-06-18 14:27 UTC
Labels: P2, bug
