### ISSUE TITLE
Playbook doesn't load vars_files correctly with variable in path name

### ISSUE THREAD

**Issue by RXminuS** [ansible/ansible#11382] opened 2015-06-25 09:58 UTC
According to the documentation variable precedence has extra variables at the top. However in `/lib/ansible/vars/__init__.py` the function `get_vars` (line 127-145) has the order inverted with extra variables as the lowest priority. This prevents me from dynamically loading vars_files based on what I specify in the extra variable. I use this so that I can load the "staging" and "production" var files based upon what variable I set.

**Comment by RXminuS** [comment] 2015-06-25 10:05
Can confirm that moving line 215 to line 145 is the only fix needed...at least for my issue! Should I make pull request or do you guys just copy it in if deemed worthy. Also, this might be related to #9723 ?

**Comment by bcoca** [comment] 2015-06-30 00:08
yes, if that fixes it please submit a PR

**Comment by anthcourtney** [comment] 2015-07-05 04:14
+1

**Comment by jimi-c** [comment] 2015-07-21 06:20
Dupe of #11377, which has been fixed. Closing this now.

Thanks!

**Closed as completed by jimi-c** 2015-07-21 06:20 UTC
Labels: P1, bug
