### ISSUE TITLE
Dynamic inventory host precedence changed

### ISSUE THREAD

**Issue by hyperized** [ansible/ansible#20383] opened 2017-01-18 09:41 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Dynamic inventory (ec2.py)

##### ANSIBLE VERSION
```
ansible 2.2.1.0
```

##### CONFIGURATION
Using ec2.py to gather dynamic inventory from Ansible

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Previously variables were resolved in such a matter:

```
group_vars/tag_group_somegroup -> myvar: default
group_vars/tag_Name_someserver -> myvar: override
```

Resulting in: `myvar: override`

However this behaviour has somehow changed in 2.2.1.
It now results in  `myvar: default`

##### STEPS TO REPRODUCE
test.yml:

```
---
- hosts: tag_type_ansible
  tasks:
    - debug:
        var: myvar
```

group_vars/tag_group_ansible:

```
myvar: incorrect
```

group_vars/tag_Name_ansible(rest of fqdn here with underscores):
```
myvar: correct
```

##### EXPECTED RESULTS
Expected:
```
TASK [debug] *******************************************************************
ok: [*.*.*.*] => {
    "myvar": "correct"
}
```

##### ACTUAL RESULTS
```
hyperized@:~/testcase$ ansible-playbook -i inventory/ec2.py test.yml

PLAY [tag_type_ansible] ********************************************************

TASK [setup] *******************************************************************
ok: [*.*.*.*]

TASK [debug] *******************************************************************
ok: [*.*.*.*] => {
    "myvar": "incorrect"
}

PLAY RECAP *********************************************************************
*.*.*.*                : ok=2    changed=0    unreachable=0    failed=0
```

**Comment by hyperized** [comment] 2017-01-18 10:14
It seems this issue is also present in 2.2.0, trying to find the last version in which this worked or which other factor (perhaps inventory gathering) plays a role in this issue.

**Comment by hyperized** [comment] 2017-01-18 10:45
When executing: `./inventory/ec2.py` I notice the following behavior in order listing:

`tag_Name_something` is listed before:
`tag_group_something`.

Now at some time in the past this ordering was alphabetical with the capitalisation ordered like such: `abCcdeFf`etc, now it returns `CFabcdef`. So `group`, which alphabetically is _before_ `Name` is actually listed after, and naturally the variable precedence would follow the order `group` -> `Name`. Currently however it prefers capitalised listings over the alphabetical order.

I'm unable to determine whether this is something that ec2.py causes, boto causes or even AWS(s search index?) causes when querying for inventory based on tags.

**Comment by hyperized** [comment] 2017-01-18 11:54
Our fix for this situation is to add a `name` tag, along with the (required) `Name` tag to our EC2 instances, but I would love for someone to have a look at this to see if sorting is part of ec2.py, boto or simply AWS.

**Comment by gundalow** [comment] 2017-01-18 15:19
I was recenty directed at https://github.com/jctanner/ansible-tools/blob/master/ansible-var-precedence-check

**Comment by gundalow** [comment] 2017-01-18 15:20
@hyperized I wonder if the title for this issue needs updating

**Comment by hyperized** [comment] 2017-01-18 15:31
A short update to narrow this down, if I use the AWS CLI to poll the AWS API directly (`aws ec2 describe-instances`) I find that the Tags are returned in a completely random order, so either boto or ec2.py sorts them.

**Comment by hyperized** [comment] 2017-01-18 15:34
Boto does not seem to sort (at all): https://github.com/boto/boto/blob/master/boto/ec2/tag.py

**Comment by bcoca** [comment] 2019-10-18 15:51
This might have changed in the past due to lack of order in groups when processing host_vars/group_vars, but the current behavior is the intended one, closing this as not a bug.

**Closed as completed by bcoca** 2019-10-18 15:51 UTC
Labels: affects_2.2, inventory, support:core, bug
