### ISSUE TITLE
First level of nested `include` inside looped `include` makes loop variable go out of scope in most cases

### ISSUE THREAD

**Issue by mentalisttraceur** [ansible/ansible#17606] opened 2016-09-16 00:41 UTC
##### ISSUE TYPE

Bug Report
##### COMPONENT NAME

`include`, looping
##### ANSIBLE VERSION

```
/tmp/foo $ ansible --version
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Default (config file only has commented out and blank lines; no ANSIBLE_\* variables set)
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Inside an `include` with a loop (such as `with_items` or `with_lines`), the next level of nested `include` without a loop does not seem to have the loop variable in its included tasks' scope, unless that nested `include` is the very first task in the included YML, in which case the variable is inherited as expected.

Deeper levels of nested `include` without a loop seem to not be affected by this bug, they just inherit the state of the loop variable from the first nested include.

Bug #17148 is probably the same bug, but that bug seems to be only a partial description, and the wording on that bug implies that it effects only loops explicitly using `loop_control` and `loop_var`: however, this issue seems to effect all loops, not just ones explicitly using `loop_control`.
##### STEPS TO REPRODUCE

This simple setup shows the basic behavior of the bug (I will include two additional more complex setups that are more complex but paint a clearer picture of how the bug manifests as comments).

Create these files, and run the `main.yml` with the `ansible-playbook` command:

```

---
# main.yml
- hosts: localhost
  tasks:
  - include: other.yml
    with_items: [ foo ]
```

```

---
# other.yml
# `item` stays in scope under the first include
# unless there's other tasks before it in this YML
- include: deeper.yml
# `item` is undefined under all later includes in this YML
- include: deeper.yml
```

```

---
# deeper.yml
- debug: var=item
```
##### EXPECTED RESULTS

Generally, I expect the loop variable to be in scope for all nested includes unless there's another loop using the same loop variable name. For the files above, I expect two runs of the debug task, each printing `foo`.
##### ACTUAL RESULTS

Instead, the first debug task print `foo`, the other print `VARIABLE IS NOT DEFINED!` instead:

```
/tmp/foo $ ansible-playbook main.yml
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************


TASK [setup] *******************************************************************

ok: [localhost]

TASK [include] *****************************************************************

included: /tmp/foo/other.yml for localhost

TASK [debug] *******************************************************************

ok: [localhost] => {
    "item": "foo"
}

TASK [debug] *******************************************************************

ok: [localhost] => {
    "item": "VARIABLE IS NOT DEFINED!"
}

PLAY RECAP *********************************************************************

localhost                  : ok=4   changed=0    unreachable=0    failed=0

```

**Comment by mentalisttraceur** [comment] 2016-09-16 00:46
##### STEPS TO REPRODUCE (Deeper nested case)

This variant shows that `include`s without a loop nested below the first nested `include` that exhibits the bug don't exhibit the bug themselves - they just properly inherit the state of the loop variable from the statement that included them.

Create these files, and run the `main.yml` with the `ansible-playbook` command:

```
---
# main.yml
- hosts: localhost
  tasks:
  - include: other.yml
    with_items: [ foo ]
```

```
---
# other.yml
- include: deeper.yml
- include: deeper.yml
```

```
---
# deeper.yml
- include: even_deeper.yml
- include: even_deeper.yml
```

```
---
# even_deeper.yml
- include: real_deep.yml
- include: real_deep.yml
```

```
---
# real_deep.yml
- debug: var=item
```

##### EXPECTED RESULTS

For the files above, I expect eight runs of the debug task, each printing `foo`.

##### ACTUAL RESULTS

Instead, the first four debug tasks print `foo`, the other four print `VARIABLE IS NOT DEFINED!` instead:

```
/tmp/foo $ ansible-playbook main.yml
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************


TASK [setup] *******************************************************************

ok: [localhost]

TASK [include] *****************************************************************

included: /tmp/foo/other.yml for localhost

TASK [debug] *******************************************************************

ok: [localhost] => {
    "item": "foo"
}

TASK [debug] *******************************************************************

ok: [localhost] => {
    "item": "foo"
}

TASK [debug] *******************************************************************

ok: [localhost] => {
    "item": "foo"
}

TASK [debug] *******************************************************************

ok: [localhost] => {
    "item": "foo"
}

TASK [debug] *******************************************************************

ok: [localhost] => {
    "item": "VARIABLE IS NOT DEFINED!"
}

TASK [debug] *******************************************************************

ok: [localhost] => {
    "item": "VARIABLE IS NOT DEFINED!"
}

TASK [debug] *******************************************************************

ok: [localhost] => {
    "item": "VARIABLE IS NOT DEFINED!"
}

TASK [debug] *******************************************************************

ok: [localhost] => {
    "item": "VARIABLE IS NOT DEFINED!"
}

PLAY RECAP *********************************************************************

localhost                  : ok=10   changed=0    unreachable=0    failed=0

```

**Comment by mentalisttraceur** [comment] 2016-09-16 01:03
##### STEPS TO REPRODUCE (Complex case: nesting and "scope" details)

This case demonstrates that further nested looped-includes also exhibit the bug. Also, this setup abuses using variables with the same name in order to demonstrate how the bug takes the loop's instance of the variable name out of the set of variables that a task sees, but still allows the task to see other variables defined with the same name. I include it in case it helps one of the developers understand what exactly the issue is.

Create these files, and run the `main.yml` with the `ansible-playbook` command:

```
---
# main.yml
- hosts: localhost
  tasks:
  - include: other.yml
    with_items: [ foo ]
  vars:
    item: bar # Note the addition of a variable with the same name
```

```
---
# other.yml
# `item` stays in scope under the first include
# unless there's other tasks before it in this YML
- include: deeper.yml
# `item` is undefined under all later includes in this YML
- include: deeper.yml
```

```
---
# deeper.yml
- include: even_deeper.yml
- include: even_deeper.yml # Note the addition of a loop
  with_items: [ qux ]
```

```
---
# even_deeper.yml
- include: real_deep.yml
- include: real_deep.yml
```

```
---
# real_deep.yml
- debug: var=item
```

##### EXPECTED RESULTS

I don't formally expect any specific results in this case, because I'm abusing variables of the same name. Given my limited understanding of how Ansible handles such cases, in this case I'd presume the eight runs of the debug task would each print `foo`.

##### ACTUAL RESULTS

Instead, the tasks print `foo`, `foo`, `foo`, `foo`, `bar`, `bar`, `qux`, `bar`:

```
/tmp/foo $ ansible-playbook main.yml
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************


TASK [setup] *******************************************************************

ok: [localhost]

TASK [include] *****************************************************************

 [WARNING]: The loop variable 'item' is already in use. You should set the
`loop_var` value in the `loop_control` option for the task to something else to avoid variable collisions and unexpected behavior.

included: /tmp/foo/other.yml for localhost

TASK [debug] *******************************************************************

ok: [localhost] => {
    "item": "foo"
}

TASK [debug] *******************************************************************

ok: [localhost] => {
    "item": "foo"
}

TASK [include] *****************************************************************

 [WARNING]: The loop variable 'item' is already in use. You should set the
`loop_var` value in the `loop_control` option for the task to something else to avoid variable collisions and unexpected behavior.

included: /tmp/foo/even_deeper.yml for localhost

TASK [debug] *******************************************************************

ok: [localhost] => {
    "item": "foo"
}

TASK [debug] *******************************************************************

ok: [localhost] => {
    "item": "foo"
}

TASK [debug] *******************************************************************

ok: [localhost] => {
    "item": "bar"
}

TASK [debug] *******************************************************************

ok: [localhost] => {
    "item": "bar"
}

TASK [include] *****************************************************************

 [WARNING]: The loop variable 'item' is already in use. You should set the
`loop_var` value in the `loop_control` option for the task to something else to avoid variable collisions and unexpected behavior.

included: /tmp/foo/even_deeper.yml for localhost

TASK [debug] *******************************************************************

ok: [localhost] => {
    "item": "qux"
}

TASK [debug] *******************************************************************

ok: [localhost] => {
    "item": "bar"
}

PLAY RECAP *********************************************************************

localhost                  : ok=12   changed=0    unreachable=0    failed=0

```

**Comment by mentalisttraceur** [comment] 2016-09-16 01:17
#### Workarounds

For those who are interested in workarounds, until this bug is fixed, there seem to be two options:

##### Indirect Include

Given an `a.yml` that does a looped include of `b.yml` which has additional `include` statements that break due to this bug, create an `indirect.yml` which just contains the line `- include: b.yml`, and include that `indirect.yml` in `a.yml`. Then all includes in `b.yml` will work fine.

##### Loop-abusing Include

Given an `a.yml` that does a looped include of `b.yml` which has additional `include` statements that break due to this bug, add the following lines to each `include` statement that breaks:

```
with_items: [ unused_loop_item ]
loop_control:
  loop_var=unused_loop_var
```

..for some reason, turning your nested non-looping include into a one-iteration-looped include successfully avoids the bug, and the loop variables you actually care about are correctly inherited by the included tasks.

**Comment by mentalisttraceur** [comment] 2016-09-16 02:41
Note: My initial bug report port contained a couple of errors because when copy-pasting my notes into the report I mixed up some notes for a slightly different reproduction setup than the one I was ultimately reporting. I have now edited it and it should be correct.

**Comment by jimi-c** [comment] 2016-11-18 19:35
Hi @mentalisttraceur, I can no longer reproduce this on devel/stable-2.2/stable-2.1, so I'll go ahead and close this. If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by jimi-c** [comment] 2016-11-18 19:36
I did go back to confirm, and at least 2.1.3.0 works as expected, so there is a known-good version.

**Closed as completed by jimi-c** 2016-11-18 19:35 UTC
Labels: affects_2.1, bug
