### ISSUE TITLE
ansible 2 shell-module pipe problem?

### ISSUE THREAD

**Issue by snsb-seifert** [ansible/ansible#14145] opened 2016-01-27 07:39 UTC
in ansible 1.9 
shell: "fdisk -l  {{ systemcontainer | quote }} | grep Disklabel | wc -m" 
returns in stdout "20" but in ansible 2.0
stdout is record as "0".
running the generated ansible 2.0 command manually ("python command" from .ansible/tmp)  the recorded stdout is "20"

**Comment by jimi-c** [comment] 2016-01-27 17:37
Hi @snsb-seifert, can you share the output when running the command without the `| wc -m`?

**Comment by bcoca** [comment] 2016-01-27 19:33
I was able to reproduce but only when not running as root:

```
  fdisk -l /dev/sda | grep Disklabel | wc -m
-bash: fdisk: command not found
0
```

when running as root:

```
 sudo /sbin/fdisk -l /dev/sda | grep Disklabel | wc -m                                                                                                                                                  
Password: 
20
```

i get 0 and 20 respectively when adding sudo to my play:

```
- shell: fdisk -l /dev/sda | grep Disklabel | wc -m
```

**Comment by snsb-seifert** [comment] 2016-01-28 07:45
Both times I ran the play as root.

_testplay:_
`---`
`- hosts: myhost`
`tasks:`
`- shell: "fdisk -l /dev/sda | grep Disklabel"`

_always the same call:_
`ansible-playbook -vv -u root -i production_inventory  ansible_shell.yml`

**Ansible 1.9:**
`PLAY [myhost] *************************************************`
`GATHERING FACTS ***************************************************************`
`<myhost> REMOTE_MODULE setup`
`ok: [myhost]`
`TASK: [shell fdisk -l /dev/sda | grep Disklabel] ******************************`
`<myhost> REMOTE_MODULE command fdisk -l /dev/sda | grep Disklabel #USE_SHELL`
`changed: [myhost] => {"changed": true, "cmd": "fdisk -l /dev/sda | grep Disklabel", "delta":` 
`"0:00:00.529142", "end": "2016-01-28 08:24:38.433455", "rc": 0, "start": "2016-01-28`
`08:24:37.904313", "stderr": "", "stdout": "Disklabel type: gpt", "warnings": []}'`
`PLAY RECAP ********************************************************************`
`myhost     : ok=2    changed=1    unreachable=0    failed=0`

**Ansible 2.0:**
...
`TASK [command] *****************************************************************`
`fatal: [myhost]: FAILED! => {"changed": true, "cmd": "fdisk -l /dev/sda | grep Disklabel",`
`"delta": "0:00:00.012556", "end": "2016-01-28 08:26:54.869994", "failed": true,`
`"rc": 1, "start": "2016-01-2808:26:54.857438", "stderr": "", "stdout": "",`
`"stdout_lines": [], "warnings": []}`

Ok, Reducing the command to 
  `fdisk -l /dev/sda`
then it is working in Ansible 2.0. 
`TASK [command] *****************************************************************`
`changed: [myhost] => {"changed": true, "cmd": "fdisk -l /dev/sda",`
`"delta": "0:00:00.011503", "end": "2016-01-28 08:35:46.070486",`
`"rc": 0, "start": "2016-01-28 08:35:46.058983", "stderr": "",`
`"stdout": "Festplatte /dev/sda: 837,8 GiB, 899527213056 Bytes,`
...
`"], "warnings": []}`

Seems there is a problem with the pipe?

I use bash-4.3 and python 2.7.10 on the host.

**Comment by davidmnoriega** [comment] 2016-09-19 04:25
I think I'm seeing this too, ansible 2.1.1.0 here with this task

``` YAML
    - name: Check current resource location
      shell: crm status | grep {{ resource }}
      register: resource_loc
```

With this output

```
TASK [Check current resource location] *****************************************
fatal: [pacemaker-ha1]: FAILED! => {"changed": true, "cmd": "crm status | grep dummy1", "delta": "0:00:00.077562", "end": "2016-09-18 21:20:18.303292", "failed": true, "rc": 1, "start": "2016-09-18 21:20:18.225730", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}
```

Running the task without `| grep...` does not give an error.

**Comment by jimi-c** [comment] 2016-10-06 14:19
@davidmnoriega that's because the output doesn't contain the string you're looking for, so the rc is being set to 1 by grep (and thus the failure).

**Comment by jimi-c** [comment] 2016-10-06 14:21
@bcoca, can you check if this does in fact still affect 2.2?

**Comment by bcoca** [comment] 2016-10-06 15:29
Yes, but I do not think this is a bug, its a issue with what is being executed, as per original ticket:
As me

```
ansible -m shell -a 'fdisk -l /dev/sda | grep Disklabel | wc -m' localhost
localhost | SUCCESS | rc=0 >>
0/bin/sh: fdisk: command not found
```

as root

```
bcoca@erebos:~/work/ansible(devel) $ ansible -m shell -a 'fdisk -l /dev/sda | grep Disklabel | wc -m' localhost -K -b
SUDO password:
localhost | SUCCESS | rc=0 >>
20
```

So it looks like a PATH issue, root has /sbin, I do not. Many things can trigger a failure here, the shell used, having PIPEFAIL set on bash, the user used, all can change the resulting RC. 

Ansible just looks at that to determine the success/failure of a shell command, you just need to make sure it runs successfully in the same environment Ansible runs, which is not normally the same as when you login interactively. The other examples are probably hitting an environmental difference (we are much more strict in newer versions) vs actual bug in shell module.

**Comment by jimi-c** [comment] 2016-10-06 16:04
I agree this seems to be environmental and not a bug. The fact that it's `20` vs. `0` is coincidental and I don't believe it's truncating the output.

**Comment by snsb-seifert** [comment] 2016-10-06 16:49
When I wrote the ticket, I did not change anything in the environment. I just installed the 1.9 or 2.0 packet. (Gentoo, emerge). And the play was on the same remote machine without any changes on that environment. So if it is an environment issue, there must be a difference in how Ansible is interpreting the environments. I just switched yesterday from 1.9 to 2.2 but have not run my tests, yet.

**Comment by snsb-seifert** [comment] 2016-11-02 16:15
I had time to check this issue again. Ansible actively send the environment variable LC_ALL to the host in each task. Setting the LC_ALL variable to '' for the whole playbook, it works for me. LC_ALL is nowhere set on my machines for good reasons.
I tested with version 2.1.2.0. Can it be that the environment processing changed between 1.9 and 2.x?
Is there a ansible-global setting for this?

The playbook section:

``` yml
---
- hosts: xyz
  environment:
       LC_MESSAGES: C
       LC_ALL: ''
  tasks:
       - name: first task
```

**Comment by bcoca** [comment] 2017-02-07 18:01
Yes, environment saw many changes, mostly because we need to have a predictable one for matching output.

There are settings in ansible.cfg (module_lang, module_set_locale) that let you control the defaults, but you can also do this at play level as your workaround above shows.

Since I don't see many hitting this issue and it can be controlled via configuration or plays, I'm going to close this issue.

**Closed as completed by bcoca** 2017-02-07 18:01 UTC
Labels: affects_2.2, affects_2.3, bug
