### ISSUE TITLE
Rich Rule FirewallD fails when already enabled

### ISSUE THREAD

**Issue by ahharu** [ansible/ansible#14610] opened 2016-02-22 17:40 UTC
##### Issue Type:

Please pick one and delete the rest:
- Bug Report
##### Ansible Version:

2.0.0.2
##### Environment:

Ubuntu 14.04 LTS
##### Summary:

When trying to add a rich rule, if its already enabled , ansible will fail 

```
`fatal: [54.246.134.217]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout":
 "Traceback (most recent call last):\r\n 

 File \"/home/centos/.ansible/tmp/ansible-tmp-1456162642.23-104681647474789/firewalld\", line 2386, in <module>\r\n    main()\r\n 

 File \"/home/centos/.ansible/tmp/ansible-tmp-1456162642.23-104681647474789/firewalld\", line 434, in main\r\n    set_rich_rule_enabled(zone, rich_rule, timeout)\r\n

  File \"/home/centos/.ansible/tmp/ansible-tmp-1456162642.23-104681647474789/firewalld\", line 209, in set_rich_rule_enabled\r\n    fw.addRichRule(zone, rule, timeout)\r\n 

 File \"<string>\", line 2, in addRichRule\r\n  File \"/usr/lib/python2.7/site-packages/slip/dbus/polkit.py\", line 103, in _enable_proxy\r\n    return func(*p, **k)\r\n  

File \"<string>\", line 2, in addRichRule\r\n  File \"/usr/lib/python2.7/site-packages/firewall/client.py\", line 52, in handle_exceptions\r\n    return func(*args, **kwargs)\r\n  

File \"/usr/lib/python2.7/site-packages/firewall/client.py\", line 2016, in addRichRule\r\n    return dbus_to_python(self.fw_zone.addRichRule(zone, rule, timeout))\r\n 

 File \"/usr/lib/python2.7/site-packages/slip/dbus/proxies.py\", line 50, in __call__\r\n    return dbus.proxies._ProxyMethod.__call__(self, *args, **kwargs)\r\n  File \"/usr/lib64/python2.7/site-packages/dbus/proxies.py\", line 145, in __call__\r\n    **keywords)\r\n 
```

 File \"/usr/lib64/python2.7/site-packages/dbus/connection.py\", line 651, in call_blocking\r\n    message, timeout)\r\ndbus.exceptions.DBusException: 
org.freedesktop.DBus.Python.dbus.exceptions.DBusException: ALREADY_ENABLED\r\n", "msg": "MODULE FAILURE", "parsed": false}`
##### Steps To Reproduce:
- name: Open ports
  firewalld:
    rich_rule: "rule family='ipv4' source address='127.0.0.1' port port='2222' protocol='tcp' accept"
    permanent: true
    immediate: true
    state: enabled
  tags: ports

and rerun this task. it will fail
##### Expected Results:

Ansible to mark this task as GREEN ( OK )
##### Actual Results:

Ansible task execution failed

**Comment by mscherer** [comment] 2016-02-22 22:42
So I faced the same issue, and the problem is triggered from immediate=True. I am trying to put a better backtrace, since both ansible and github have mangled the output.

**Comment by mscherer** [comment] 2016-02-22 22:49
```
Traceback (most recent call last):
  File \"/tmp/ansible-tmp-1456181103.11-10597087219040/firewalld\", line 2386, in <module>
    main()
  File \"/tmp/ansible-tmp-1456181103.11-10597087219040/firewalld\", line 434, in main
    set_rich_rule_enabled(zone, rich_rule, timeout)
  File \"/tmp/ansible-tmp-1456181103.11-10597087219040/firewalld\", line 209, in set_rich_rule_enabled
    fw.addRichRule(zone, rule, timeout)
  File \"<string>\", line 2, in addRichRule
  File \"/usr/lib/python2.7/site-packages/slip/dbus/polkit.py\", line 103, in _enable_proxy
    return func(*p, **k)
  File \"<string>\", line 2, in addRichRule
  File \"/usr/lib/python2.7/site-packages/firewall/client.py\", line 52, in handle_exceptions
    return func(*args, **kwargs)
  File \"/usr/lib/python2.7/site-packages/firewall/client.py\", line 2016, in addRichRule
    return dbus_to_python(self.fw_zone.addRichRule(zone, rule, timeout))
  File \"/usr/lib/python2.7/site-packages/slip/dbus/proxies.py\", line 50, in __call__
    return dbus.proxies._ProxyMethod.__call__(self, *args, **kwargs)
  File \"/usr/lib64/python2.7/site-packages/dbus/proxies.py\", line 145, in __call__
    **keywords)
  File \"/usr/lib64/python2.7/site-packages/dbus/connection.py\", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.dbus.exceptions.DBusException: ALREADY_ENABLED
```

**Comment by mscherer** [comment] 2016-02-22 23:38
So I can't reproduce on latest devel checkout, for a reason i can't explain.

**Comment by mscherer** [comment] 2016-02-22 23:44
It was fixed on https://github.com/ansible/ansible-modules-extras/pull/1081

**Comment by sivel** [comment] 2016-02-22 23:59
Since this appears to have been fixed in the above referenced pull request im going to go ahead and close this issue.

**Closed as completed by sivel** 2016-02-22 23:59 UTC
