### ISSUE TITLE
Multiple limit should either be prohibited or produce a warning message

### ISSUE THREAD

**Issue by cmorent** [ansible/ansible#24054] opened 2017-04-27 11:18 UTC
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
The --limit option

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel ba3295dd3f) last updated 2017/04/12 11:26:36 (GMT +200)
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

One of our developer tried to use one of our playbooks using multiple limits, thinking it will behave like a `:&` pattern. Having something like:

`ansible-playbook deploy.yml --limit foo --limit bar`

The limit on `foo` was omitted without any warning/error message prompted.

##### STEPS TO REPRODUCE

```yaml
$ ansible-playbook deploy.yml --limit foo --limit bar --list-hosts
# The output will only contain hosts from *bar* group
$ ansible-playbook deploy.yml --limit "foo:&bar" --list-hosts
# The output will contain hosts contained in both foo and bar groups
```

##### EXPECTED RESULTS

I think that ansible should, at least, print a warning to mention that one of the *--limit* will be omitted

##### ACTUAL RESULTS

The playbook was run on hosts from the group mentioned in the second *limit*.

**Comment by bcoca** [comment] 2017-04-27 14:15
We are using optparse as argument passing library, I haven't been able to figure out how to error/warn when having duplicate entries. 

The normal behaviour for optparse is 'last one wins' unless it is an 'append' option in which case they get added to a list.

**Comment by bcoca** [comment] 2017-04-27 19:20
dupe of #22396

**Closed as completed by bcoca** 2017-04-27 19:20 UTC
Labels: affects_2.4, feature
