### ISSUE TITLE
Ansible group variables being merged for distinct hosts

### ISSUE THREAD

**Issue by EddyP23** [ansible/ansible#32353] opened 2017-10-30 15:42 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Ansible inventory variable parsing

##### ANSIBLE VERSION

```ansible 2.4.0.0```

##### CONFIGURATION

None

##### OS / ENVIRONMENT

Ubuntu 16.04 LTS

##### SUMMARY AND STEPS TO REPRODUCE

`inventory.yml`:
```
all:
  children:
    westeu:
      vars:
        location: 'westeu'
      children:
        esNodes:
          hosts:
            host1:
    southcentralus:
      vars:
        location: 'southus'
      children:
        esNodes:
          hosts:
            host2:
```

When I run `ansible -i inventory.yml -m debug -a 'var=location' all` I get `location: westeu` for both hosts! *Please note*, that the main part here is that both location groups (`southcentralus` and `westeu`) share the same subgroup called `esNodes`. If I change `esNodes` to `esNodesEU` and `esNodesUS` everything works as expected. But then I can never just select `esNodes`.

I am aware of this issue [variable issue](https://github.com/ansible/ansible/issues/9065) and there is an explanation there that variables are resolved at the host level, but it seems that they are resolved at a group level as well and then only later pushed down to a host. It clearly sounds like a bug to me.

**Comment by bcoca** [comment] 2017-10-30 15:48
this is supposed to fix that display issue #32276

**Comment by sivel** [comment] 2017-10-30 15:51
I'm not sure it is a bug.  I believe what is happening is the correct behavior.  You have applied vars to a group, and that group contains children.  In resolving variables, the parent groups vars will apply to the children groups as well.  Meaning that the last processed will overwrite.  Because you specified the same child groups for both parents, this is the result.

I think the YAML plugin is making it seem as though this won't happen due to structure, but that assumption is incorrect.

@bcoca that PR doesn't affect the results of how inventory is parsed for this report.

**Comment by EddyP23** [comment] 2017-10-30 16:06
@sivel, I think I am starting to understand the idea of inventory variable with Ansible.

But then would it be possible for ansible to issue a warning when assigning the same variable twice? It would solve my problem and the problems people are having in the issue I linked to.

And thanks for a quick reply.

**Comment by sivel** [comment] 2017-10-30 16:12
Technically the overwriting is a "feature" of ansible, so issuing a warning would probably be counterintuitive and noise to most.  Since people will often add a variable at the `all` level, and expect it to be overwritten for groups or hosts with a more specific value.

**Comment by bcoca** [comment] 2017-10-30 17:04
@sivel, it is a bug for the intended representation, its supposed to reflect how Ansible sees the inventory once resolved. 
I do plan to add a couple of options: 
- An optimized version with vars in groups (mainly for import/migrations)
- A option to show everywhere in inventory in which a var is defined

**Comment by sivel** [comment] 2017-10-30 17:05
@bcoca I'm slightly confused.  This isn't about how ansible-inventory displays an inventory, this is literally about how ansible inventory works.

**Comment by bcoca** [comment] 2017-10-30 17:06
ah .. sorry, mixed tickets in my head ... sorry for the noise.

**Comment by EddyP23** [comment] 2017-10-31 08:12
@sivel, I potentially see a few options here. The warning could be shown using higher verbosity level (and so, not being noise to most). Also, at higher verbosity, it could display all the variable values and those that won, some sort of a tree, wouldn't that be very useful for debugging?

Also, what about overriding variables at the same level? You can argue this is also a feature, isn't it most of the time just a bug? And if so, doesn't it deserve at least a warning?

**Comment by bcoca** [comment] 2017-10-31 14:44
@EddyP23 the merging is by design as plays only deal with hosts and tasks, variables are flattened to the host (this is clearly stated in docs as well as the precedence and order of merges) and groups are just a 'host property'. 

That said, my comment above is about a feature that will allow more introspection to the setup, this is not something we can easily do during runtime as we do not examine the vars one by one (this would be very expensive), we just merge the sources.

**Comment by bcoca** [comment] 2017-11-23 00:08
As @sivel  points out, the original issue outlined here is not a bug, but works as designed, group names are unique so it does not matter where you declare it, they always get merged.

**Closed as completed by bcoca** 2017-11-23 00:08 UTC
Labels: affects_2.4, support:core, bug
