### ISSUE TITLE
macOS 10.12

### ISSUE THREAD

**Issue by aarongo** [ansible/ansible#22631] opened 2017-03-15 03:18 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

yum

##### ANSIBLE VERSION

```
ansible 2.2.1.0
```

##### CONFIGURATION

hostfile = /Users/lonny/Documents/Ansible_Book/playbooks/inventory
roles_path = /Users/lonny/Documents/Ansible_Book/playbooks/roles
##### OS / ENVIRONMENT

macOS 10.12
##### STEPS TO REPRODUCE

failed: [172.31.10.100] (item=[u'Dependent']) => {"failed": true, "item": ["Dependent"], "module_stderr": "Shared connection to 172.31.10.100 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_CL3d4K/ansible_module_yum.py\", line 25, in <module>\r\n    import yum\r\nImportError: No module named yum\r\n", "msg": "MODULE FAILURE"}

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by dagwieers** [comment] 2017-03-15 10:23
You will have to share a lot more of what you are doing if you expect anyone to be able to help you.

My first guess is that you are running the yum-module on a target node that does not have yum installed (or does not even use yum for package management).

**Comment by gundalow** [comment] 2017-03-15 17:31
I'm going to close this, please fill edit the issue and fill in the template so we know what the issue is.

**Closed as completed by gundalow** 2017-03-15 17:31 UTC
Labels: affects_2.2, module, bug
