### ISSUE TITLE
task entry environment: is not autotemplated

### ISSUE THREAD

**Issue by nikulk** [ansible/ansible#13514] opened 2015-12-11 08:33 UTC
The issue remarked here: https://github.com/ansible/ansible/issues/11912 seems to be back. I'm trying to use a variable in environment: field as follows:

```
- name: Run Django database migrations
  django_manage:
    command: migrate
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: django_environment
  when: run_django_db_migrations is defined and run_django_db_migrations
  tags: django.migrate
```

The variable is defined in vars/main.yml as follows:

```
django_environment:
  DJANGO_SETTINGS_MODULE: "{{ django_settings_file }}"
  DJANGO_SECRET_KEY: "{{ django_secret_key }}"
  STATIC_ROOT: "{{ nginx_static_dir }}"
  DATABASE_USER: "{{ db_user }}"
  DATABASE_PASSWORD: "{{ db_password }}"
  EMAIL_HOST: "{{ email_host|default(omit) }}"
  EMAIL_HOST_USER: "{{ email_host_user|default(omit) }}"
  EMAIL_HOST_PASSWORD: "{{ email_host_password|default(omit) }}"
  BROKER_URL: "{{ broker_url|default(omit) }}"
```

On reaching this task, I get the following error:

```
fatal: [52.27.20.139]: FAILED! => {"failed": true, "msg": "ERROR! environment must be a dictionary, received django_environment (<class 'ansible.parsing.yaml.objects.AnsibleUnicode'>)"}
```

Even the documentation says this should work: http://docs.ansible.com/ansible/playbooks_environment.html
Look at the code titled "The environment can also be stored in a variable, and accessed like so:"

My ansible version is as follows: (I just did an install from the git repo)

```
ansible 2.1.0 (devel bd0f9a4afc) last updated 2015/12/11 05:46:08 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 0d23b3df52) last updated 2015/12/11 05:46:21 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 51813e0033) last updated 2015/12/11 05:46:30 (GMT +000)
  config file = /vagrant/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

Could you please suggest me a workaround for the time being? Thank you! It's great to use Ansible, has saved me so much time I can't imagine. A few hours for a repeatable stack configuration is just beautiful!.

**Comment by nikulk** [comment] 2015-12-12 07:56
Hi @bcoca I tried using `${django_environment}`, but it's not working. Writing `"{{django_environment}}"` doesn't work either as it becomes a string. Using `{{django_environment}}` doesn't work either because it is interpreted as a dictionary. 

Is there any manual way to use this dictionary variable? If not, this seems to be a big limitation of using Jinja with YAML, because this functionality shouldn't be so hard to implement...

Thanks!

**Comment by bcoca** [comment] 2015-12-12 17:33
Use this:

`environment: "{{django_environment}}"` < it needs to be quoted

`${django_environment}` is invalid in Ansible, `$django_environment` might have worked in older versions but they did not have the `environment` directive.

`{django_environment}` is not an Ansible variable

I've updated the docs to use the proper form, the bare variable should still work so I'm keeping the ticket open to figure out exactly what the issue is.

**Comment by nikulk** [comment] 2015-12-12 19:22
@bcoca Sorry, that's what I meant - I did try the double curly brackets in the quotes. It didn't work either. I've updated the comment above. I believe it got interpreted as a string rather than as a dictionary. Are you sure it should work? Why will it get interpreted as a dictionary rather than as a string if it is inside quotes?

**Comment by bcoca** [comment] 2015-12-12 21:24
The templating looks at the result and sets the type, if its a dict, it will return a dict. 

It needs to be quoted or YAML will see the initial `{` as the start of a YAML dictionary, which it is not, its a variable reference, which jinja2 templating will substitute and then Ansible converts into an actual dictionary.

**Comment by nikulk** [comment] 2015-12-13 10:11
A simple question - wouldn't processing Jinja tags first always, before YAML, solve all these problems? Because I haven't seen any YAML syntax that would confuse Jinja, the way Jinja's templates confuse YAML due to the presence of curly brackets; particularly because most of Jinja's templating uses double characters like {{ and {%.

**Comment by bcoca** [comment] 2015-12-13 14:45
since plays are yaml files .... not sure how that would be possible.

**Comment by jimi-c** [comment] 2015-12-17 18:18
This should be fixed now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-12-17 18:18 UTC
Labels: bug
