### ISSUE TITLE
async_status default messaging is misleading

### ISSUE THREAD

**Issue by mwhahaha** [ansible/ansible#67755] opened 2020-02-25 22:46 UTC
##### SUMMARY
When using async_status to wait for jobs to finish with retries, the default messaging by ansible is misleading because it says "FAILED - RETRYING: [task name] (#### retries left)"

See also https://bugzilla.redhat.com/show_bug.cgi?id=1801470

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
default callback

##### ANSIBLE VERSION

```paste below
ansible-2.8.8-1.el8ae.noarch
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

RHEL8.1

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: wait a while
      async: 3600
      poll: 0
      shell: sleep 30
      register: wait_async_result

    - name: wait for wait to finish
      async_status:
        jid: "{{ wait_async_result.ansible_job_id }}"
      register: wait_outputs
      until: wait_outputs.finished
      retries: 60
      delay: 1
```

##### EXPECTED RESULTS

A different message than "FAILED" is used when waiting for a job to complete.

##### ACTUAL RESULTS

```paste below
$ ansible-playbook wait.yaml 
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [localhost] ****************************************************************************************************************************************************************************************

TASK [wait a while] *************************************************************************************************************************************************************************************
changed: [localhost]

TASK [wait for wait to finish] **************************************************************************************************************************************************************************
FAILED - RETRYING: wait for wait to finish (60 retries left).
FAILED - RETRYING: wait for wait to finish (59 retries left).
FAILED - RETRYING: wait for wait to finish (58 retries left).
FAILED - RETRYING: wait for wait to finish (57 retries left).
FAILED - RETRYING: wait for wait to finish (56 retries left).
FAILED - RETRYING: wait for wait to finish (55 retries left).
FAILED - RETRYING: wait for wait to finish (54 retries left).
FAILED - RETRYING: wait for wait to finish (53 retries left).
FAILED - RETRYING: wait for wait to finish (52 retries left).
FAILED - RETRYING: wait for wait to finish (51 retries left).
FAILED - RETRYING: wait for wait to finish (50 retries left).
FAILED - RETRYING: wait for wait to finish (49 retries left).
FAILED - RETRYING: wait for wait to finish (48 retries left).
FAILED - RETRYING: wait for wait to finish (47 retries left).
FAILED - RETRYING: wait for wait to finish (46 retries left).
FAILED - RETRYING: wait for wait to finish (45 retries left).
FAILED - RETRYING: wait for wait to finish (44 retries left).
FAILED - RETRYING: wait for wait to finish (43 retries left).
FAILED - RETRYING: wait for wait to finish (42 retries left).
FAILED - RETRYING: wait for wait to finish (41 retries left).
FAILED - RETRYING: wait for wait to finish (40 retries left).
FAILED - RETRYING: wait for wait to finish (39 retries left).
FAILED - RETRYING: wait for wait to finish (38 retries left).
FAILED - RETRYING: wait for wait to finish (37 retries left).
FAILED - RETRYING: wait for wait to finish (36 retries left).
changed: [localhost]

PLAY RECAP **********************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

**Comment by mwhahaha** [comment] 2020-02-25 22:50
Just dropping "FAILED - " is an improvement

**Comment by sivel** [comment] 2020-02-25 22:55
This is not the async_status messaging.

This is the result of the `until` statement.  `until` works very much like a `when` statement, and when the `until` statement evaluates to `False`, this is considered a failure, and as such, it is retried. 

Duplicate of https://github.com/ansible/ansible/issues/63926

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Closed as completed by sivel** 2020-02-25 22:55 UTC

**Comment by mwhahaha** [comment] 2020-02-25 22:59
Which is closed as WONTFIX. It is a terrible UX and is confusing. ‾\_(ツ)_/‾
