### ISSUE TITLE
with_sequence doesn't evaluate when count=1

### ISSUE THREAD

**Issue by rncry** [ansible/ansible#11504] opened 2015-07-06 15:34 UTC
Issue Type:

Bug Report
Ansible Version:
ansible 1.9.2
  configured module search path = None

Ansible Configuration:

No changes to .cfg, using vanilla installed package version installed with pip

Environment:

Ubuntu 14.04

Summary:

using with_sequence will skip the play when the sequence is only a single item long.

Steps To Reproduce:

```
  tasks:
    - name: print thing
      debug: var={{ item }}
      with_sequence: count=1
```

Expected Results:

```
ok: [localhost] => (item=1) => {
    "item": "1", 
    "var": {
        "1": "1"
    }
}
```

Actual Results:

```
skipping: [localhost]
```

**Comment by bcoca** [comment] 2015-07-06 15:37
closing as duplicate of #11422 and #11480

**Closed as completed by bcoca** 2015-07-06 15:37 UTC
