### ISSUE TITLE
Conditional role inclusion+run_once may skip tasks unexpectedly

### ISSUE THREAD

**Issue by amenonsen** [ansible/ansible#18821] opened 2016-12-07 08:53 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION
```
devel
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
If a role is included conditionally, then any ``run_once`` task in it may be skipped if the first host that is running the play doesn't meet the condition.

##### STEPS TO REPRODUCE
foo.yml
```
---
- hosts: all
  gather_facts: no
  roles:
    - role: p
      when: inventory_hostname == 'c'
```
roles/p/tasks/main.yml:
```
- command: cat /proc/uptime
  run_once: true
```

I did this:
```
ansible-playbook -v -i a,b,c,d, -e ansible_connection=local i.yml
```
##### EXPECTED RESULTS
I expected the task to be executed on 'c'.

##### ACTUAL RESULTS
```
PLAY [all] ************************************************************************************************************************************************************************************

TASK [p : command] ****************************************************************************************************************************************************************************
skipping: [a] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

PLAY RECAP ************************************************************************************************************************************************************************************
a                          : ok=0    changed=0    unreachable=0    failed=0   
```

**Comment by krzysztof-magosa** [comment] 2016-12-07 11:52
Related to #13226

**Comment by bcoca** [comment] 2016-12-20 16:59
closing as dupe of #13226, this is a consequence of run_once running on the first active host in the run, so the when condition evaluates relative to that host.

**Closed as completed by bcoca** 2016-12-20 16:59 UTC
Labels: affects_2.3, bug
