### ISSUE TITLE
Ansible unexpectedly sets new variable values in sub-sub-roles

### ISSUE THREAD

**Issue by PascalReintjens** [ansible/ansible#78608] opened 2022-08-21 15:47 UTC
### Summary

When you define a role twice in a playbook which includes a subrole that includes another subrole and you provide a parameter in the first playbook definition but omit it in the second definition, the old value of the first definition will suddenly appear in the sub-sub-role of the second definition, but will disappear one sub-role deeper

This (test includes test2, test2 includes test3, test3 includes test4 - all four roles have a debug message which outputs the content of testvar):
![grafik](https://user-images.githubusercontent.com/8560378/185795434-ff74c4ed-62f6-4ee4-85e8-1ea3eea57d37.png)

Results in this:
![grafik](https://user-images.githubusercontent.com/8560378/185795487-ec6f93dd-7d7e-474e-9573-d1b211847130.png)

### Issue Type

Bug Report

### Component Name

include_role

### Ansible Version

```console
ansible [core 2.12.7]
  config file = /mnt/c/Users/Pascal/Pascal - Cloud/Privat/Resourcen/Ansible/REI/Ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /mnt/c/Users/Pascal/Pascal - Cloud/Privat/Resourcen/Ansible/REI/Ansible/.galaxy/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True
```

### Configuration

```console
COLLECTIONS_PATHS(/mnt/c/Users/Pascal/Pascal - Cloud/Privat/Resourcen/Ansible/REI/Ansible/ansible.cfg) = ['/mnt/c/Users/Pascal/Pascal - Cloud/Privat/Resourcen/Ansible/REI/Ansible/.galaxy/collections']
DEFAULT_HOST_LIST(/mnt/c/Users/Pascal/Pascal - Cloud/Privat/Resourcen/Ansible/REI/Ansible/ansible.cfg) = ['/mnt/c/Users/Pascal/Pascal - Cloud/Privat/Resourcen/Ansible/REI/Ansible/inventory/hosts.ini']
DEFAULT_ROLES_PATH(/mnt/c/Users/Pascal/Pascal - Cloud/Privat/Resourcen/Ansible/REI/Ansible/ansible.cfg) = ['/mnt/c/Users/Pascal/Pascal - Cloud/Privat/Resourcen/Ansible/REI/Ansible/.galaxy/roles', '/mnt/c/User>

BECOME:
======

CACHE:
=====

CALLBACK:
========

CLICONF:
=======

CONNECTION:
==========

HTTPAPI:
=======

INVENTORY:
=========

LOOKUP:
======

NETCONF:
=======

SHELL:
=====

VARS:
====
```

### OS / Environment

Ubuntu 20.04.4 LTS (WSL 2)

### Steps to Reproduce

Implement a playbook:
```
- name: Test
  hosts: rei-test1
  roles:

    - role: test1
      info: First definition
      testvar: abc

    - role: test1
      info: Second definition
```

Task file for the role test1:
```
- name: "{{ info }} - test1-role: testvar content"
  debug:
    msg: '{{ testvar | default("Not specified") }}'

- name: 'Test deeper'
  include_role: 
    name: test2

```
Task file for the role test2:
```
- name: "{{ info }} - subrole of test1-role (test2): testvar content"
  debug:
    msg: '{{ testvar | default("Not specified") }}'

- name: 'Test even deeper'
  include_role: 
    name: test3
```

Task file for the role test3:
```
- name: "{{ info }} - subrole of subrole of test1-role (test3): testvar content"
  debug:
    msg: '{{ testvar | default("Not specified") }}'

- name: 'Test even deeper'
  include_role: 
    name: test4
```

Task file for the role test4:
```
- name: "{{ info }} - subrole of subrole of subrole of test1-role (test4): testvar content"
  debug:
    msg: '{{ testvar | default("Not specified") }}'
```

### Expected Results

I expected that testvar is still undefined in test3 of the second role declaration of the playbook

### Actual Results

```console
testvar is suddenly defined in test3 of the second role declaration of the playbook
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by PascalReintjens** [comment] 2022-08-21 15:48
Sorry for reopening this Issue, but #78384 was already locked and after taking some time I’m still at the conclusion there must be a bug. 

In #78384 @bcoca said that the problem is that the variables are loaded before execution and therefore both declarations get executed with the same var values, the top level roles are deduped by the vars signature therefore the second role-declaration and sub-role don’t have the wrong content, but that does not translate to dependent roles. 
But after the case got closed I found out, that testvar only is defined for one layer and the next sub-role it is missing again (See screenshot in the first post). So if the -not translating to dependent roles- would be the problem, the testvar should be set on all sub-roles of the sub-role where testvar appears.
But I tried lots of other things. @bcoca said that using include_role to get dynamic versions of the role would solve the problem, but including it like the following, results in exactly the same behavior: 
```
- name: Test
  hosts: rei-test1
  tasks:
    - name: Test1
      include_role: 
        name: test1
      vars: 
        info: first definition
        testvar: abc

    - name: Test2
      include_role: 
        name: test1
      vars: 
        info: second definition
```
![grafik](https://user-images.githubusercontent.com/8560378/185799414-75e16e23-cb3f-477d-9f47-28f6c93415c5.png)


If I instead move the testvar declaration around and define testvar in the second role, if testvar would be populated like described by @bcoca in advance, this should still result in testvar being defined in the sub-sub-sub-role of the first declaration
```
- name: setup server
  hosts: rei-test1
  roles:

    - role: test1
      info: first definition

    - role: test1
      info: second definition
      testvar: abc
```

Instead, the value is then not set there:
![grafik](https://user-images.githubusercontent.com/8560378/185799423-932fc5fa-8025-45f4-9ce3-ef127f66b303.png)


Because of all those reasons, I think this is a bug. If I can test anything more, please let me know. I tried my best and hope everything is understandable, since English isn’t my native language. Thank you very much for taking the time to look at my bug report.

**Comment by sivel** [comment] 2022-08-30 17:45
As an update here, the issue is due to how role deduplicate is handled.

Long story short, for any set of params/tags/when statements for a single role, we only create 1 instance of that role.  The parent chain is not considered in this deduplication.  So `role3` is only instantiated 1 time, and the means in which we do so, basically makes the 2nd `role3` have a parent of the first `role2` which has a parent of the first `role1`.  Ignoring `role4` for now, that is kind of a different problem where we lose variable scope at a certain depth.

The only way to fix this is to rewrite how we handle tracking role duplicates for `allow_duplicates`.

I'm working on that in https://github.com/ansible/ansible/pull/78661 currently, but there is more work to be done.  Seeing as though this has the potential to break other things, and with 2.14 nearing the freeze date, we're likely planning to include it in 2.15 if all things go to plan, and will likely not backport the fix.

As such, there is no short term fix for this.

As a workaround, on the 2nd invocation of `test1` you can set:

```
testvar: "{{ undef() }}"
```

**Closed as completed** 2022-11-29 21:56 UTC
Labels: support:core, bug, has_pr, P3, affects_2.12
