### ISSUE TITLE
A weird win order for variables of the same name if multiple external variables files are used

### ISSUE THREAD

**Issue by hostmaster** [ansible/ansible#8697] opened 2014-08-20 14:33 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

Ansible 1.8 (devel a1f09bd89f) last updated 2014/08/20 17:28:56 (GMT +400)
##### Environment:

Linux Ubuntu 12.04, Mac OS X
##### Summary:

There is an `app_user` variable which is defined in `group_vars/all` as `all_user` and in external variables file `vars/staging.yml` as `staging_user`.  I've got weird win order for the variable when the second external variables file is used and it is not empty. 
##### Steps To Reproduce:

I made a public repository with files for convenience https://github.com/hostmaster/ansible-bugreport

```
# group_vars/all
app_user: all_user
```

```
# inventory/staging
localhost ansible_connection=local

[all:vars]
deploy_env=staging
```

```
# vars/secrets/staging.yml
test_url: 'google.com'
```

```
# vars/staging.yml
app_user: staging_user
```

```

---
# test.yml
- hosts: localhost
  gather_facts: no
  vars_files:
    - 'vars/{{ deploy_env }}.yml'
    - 'vars/secrets/{{ deploy_env }}.yml'

  tasks:
    - local_action: debug var=deploy_env
    - local_action: debug var=app_user
```

I have expected to get `staging_user` here but I've got `all_user` instead. 

```
$ ansible-playbook -i inventory/staging test.yml

PLAY [localhost] **************************************************************
localhost: importing /Users/igor/Temp/ansible/test_run/vars/staging.yml
localhost: importing /Users/igor/Temp/ansible/test_run/vars/secrets/staging.yml

TASK: [debug var=deploy_env] **************************************************
ok: [localhost -> 127.0.0.1] => {
    "deploy_env": "staging"
}

TASK: [debug var=app_user] ****************************************************
ok: [localhost -> 127.0.0.1] => {
    "app_user": "all_user"
}

PLAY RECAP ********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

Now comment out the line in `vars/secrets/staging.yml`

```
# vars/secrets/staging.yml
# test_url: 'google.com'
```

```
$ ansible-playbook -i inventory/staging test.yml

PLAY [localhost] **************************************************************
localhost: importing /Users/igor/Temp/ansible/test_run/vars/staging.yml

TASK: [debug var=deploy_env] **************************************************
ok: [localhost -> 127.0.0.1] => {
    "deploy_env": "staging"
}

TASK: [debug var=app_user] ****************************************************
ok: [localhost -> 127.0.0.1] => {
    "app_user": "staging_user"
}

PLAY RECAP ********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```
##### Expected Results:

ok: [localhost -> 127.0.0.1] => {
    "app_user": "staging_user"
}
##### Actual Results:

ok: [localhost -> 127.0.0.1] => {
    "app_user": "all_user"
}

**Comment by jimi-c** [comment] 2014-08-20 16:13
# Duplicate Issue

Hi!

This issue appears to be a duplicate of #8638. I have tested your example playbook above, and with the patch on that issue it works as expected:

<pre>
# ansible-playbook -vv -i inventory/staging site.yml 
PLAY [localhost] ************************************************************** 
localhost: importing vars/staging.yml
localhost: importing vars/secrets/staging.yml
TASK: [debug var=deploy_env] ************************************************** 
ok: [localhost -> 127.0.0.1] => {
    "deploy_env": "staging"
}
TASK: [debug var=app_user] **************************************************** 
ok: [localhost -> 127.0.0.1] => {
    "app_user": "staging_user"
}
PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
</pre>

Because of this, we will close this issue.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2014-08-20 16:13 UTC

**Comment by hostmaster** [comment] 2014-08-21 08:25
It works as expected. Thank you.
