### ISSUE TITLE
'file' lookup broken in devel branch

### ISSUE THREAD

**Issue by candlerb** [ansible/ansible#4637] opened 2013-10-22 15:57 UTC
Task:

```
- name: install authorized keys
  action: authorized_key user={{item}} key="{{ lookup('file', 'authorized_keys') }}"
  with_items: ssh_key_users
```

This worked under ansible 1.3.3. With devel branch I get:

```
TASK: [ssh_key | install authorized keys] *************************************
fatal: [ubutest] => One or more undefined variables: 'lookup' is undefined

FATAL: all hosts have already failed -- aborting
```

**Comment by jctanner** [comment] 2013-10-22 15:58
duplicate of #4608

**Closed as completed by jctanner** 2013-10-22 15:58 UTC
