### ISSUE TITLE
Restrict task execution by tag intersection

### ISSUE THREAD

**Issue by fvilpoix** [ansible/ansible#31971] opened 2017-10-20 09:18 UTC
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
Tags

##### SUMMARY

hi, it would be very usefull if we could combine tags to restrict the execution on some task which have all the tags, instead of the union.

That could be done with this kind of arguments:

```
ansible-playbook -i "localhost," -c local playbook.yml --tags=tag1 --tags=tag2 --tag-strategy=intersection
```

And it would execute only the task with both tags.

The same could be done with the skip-tags property.

Thanks for your feedback.

**Comment by alikins** [comment] 2017-10-23 16:01
Related to:
https://github.com/ansible/ansible/issues/11185
https://github.com/ansible/ansible/issues/18401 
https://github.com/ansible/ansible/issues/16273

**Comment by sivel** [comment] 2018-09-24 15:39
Duplicate of https://github.com/ansible/ansible/issues/11396

**Closed as completed by sivel** 2018-09-24 15:39 UTC
Labels: test, c:playbook/taggable, support:community, affects_2.5, feature
