### ISSUE TITLE
Ansible Connect windows : WINRM CONNECTION ERROR: 500 WinRMTransport. [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

### ISSUE THREAD

**Issue by fsteinel** [ansible/ansible#10294] opened 2015-02-19 15:26 UTC
Accessing a Win7 machine using the windows automatic default self signed cert requires [opting-out](https://www.python.org/dev/peps/pep-0476/#opting-out).

Error Message from pywinrm:
- `WINRM CONNECTION ERROR: 500 WinRMTransport. [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)`

The quick and really dirty (see link) test was that I added (and removed) the line to urllib2.py.

The [pywinrm](https://github.com/diyan/pywinrm/pull/43) pull request might help to make that happen.

env:
 Ansible control: 
- Gentoo x64 Ansible1.8.2
- pywinrm 0.0.3
  client: windows 7 Service Pack 1

My Steps:
1. control
cat /etc/ansible/hosts
 [win]
 192.168.0.8
 cat /etc/ansible/group_vars/win2.yml 
 ansible_ssh_user: Administrator
 ansible_ssh_pass: 3KRxuSezVdx5
 ansible_ssh_port: 5986
 ansible_connection: winrm

2.then I run the scripts on windows server 2012 R2:
 upgrade_to_ps3.ps1
 ConfigureRemotingForAnsible.ps1
https://github.com/ansible/ansible/blob/devel/examples/scripts/ConfigureRemotingForAnsible.ps1 
read http://damonoverboe.org/post/ansible-and-windows-basic-set-up

3.the question:

```
fsteinel@host:~# ansible win2 -m win_ping
<192.168.0.8> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5986 TO  192.168.0.8
<192.168.0.8> WINRM CONNECT: transport=plaintext endpoint=https://192.168.0.8:5986/wsman
<192.168.0.8> WINRM CONNECTION ERROR: 500 WinRMTransport. [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
<192.168.0.8> WINRM CONNECT: transport=plaintext endpoint=http://192.168.0.8:5986/wsman
192.168.0.8 | FAILED => Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/ansible/runner/__init__.py", line 590, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib64/python2.7/site-packages/ansible/runner/__init__.py", line 792, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib64/python2.7/site-packages/ansible/runner/__init__.py", line 955, in _executor_internal_inner
    conn = self.connector.connect(actual_host, actual_port, actual_user, actual_pass, actual_transport, actual_private_key_file)
  File "/usr/lib64/python2.7/site-packages/ansible/runner/connection.py", line 51, in connect
    self.active = conn.connect()
  File "/usr/lib64/python2.7/site-packages/ansible/runner/connection_plugins/winrm.py", line 132, in connect
    self.protocol = self._winrm_connect()
  File "/usr/lib64/python2.7/site-packages/ansible/runner/connection_plugins/winrm.py", line 86, in _winrm_connect
    protocol.send_message('')
  File "/usr/lib64/python2.7/site-packages/winrm/protocol.py", line 173, in send_message
    return self.transport.send_message(message)
  File "/usr/lib64/python2.7/site-packages/winrm/transport.py", line 76, in send_message
    response = urlopen(request, timeout=self.timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib64/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib64/python2.7/httplib.py", line 1073, in getresponse
    response.begin()
  File "/usr/lib64/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python2.7/httplib.py", line 371, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib64/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
```

**Comment by cchurch** [comment] 2015-04-15 17:31
A quick workaround is to create a [callback plugin](http://docs.ansible.com/developing_plugins.html#callbacks) with the following content:

```
import ssl
if hasattr(ssl, '_create_default_https_context') and hasattr(ssl, '_create_unverified_context'):
    ssl._create_default_https_context = ssl._create_unverified_context

class CallbackModule(object):
    pass
```

The plugin will [opt out](https://www.python.org/dev/peps/pep-0476/#opting-out) of certificate verification before any WinRM connections are attempted.

**Comment by ryanwalls** [comment] 2015-04-16 03:34
@cchurch I'm having this issue as well.  Do we anticipate a longer term fix?  Seems like opting out of cert validation is a bad thing.  

And fyi, registering a callback in my project fixed the issue.  

For those who read this and aren't familiar with callbacks, let me save you 30 mins of your life...the easiest solution was to create a directory called `callback_plugins` in the same directory as my playbook.  Inside the `callback_plugins` directory I created a `fix-ssl.py` file with the contents that @cchurch had above:

```
import ssl
if hasattr(ssl, '_create_default_https_context') and hasattr(ssl, '_create_unverified_context'):
    ssl._create_default_https_context = ssl._create_unverified_context

class CallbackModule(object):
    pass
```

As long as you execute your playbook from that playbook's directory, the `callback_plugins` directory will be found and loaded automatically.  You'll know the plugin was loaded successfully if a `fix-ssl.pyc` file is created.

**Comment by cchurch** [comment] 2015-04-16 03:56
@ryanwalls Thanks for the feedback and more detailed explanation.

I have a more complete fix in the works.

**Comment by klj613** [comment] 2015-05-10 22:46
I just came across this. The callback_plugins workaround worked for ansible-playbook but not ansible. Any ideas how to get `ansible` to work?

**Comment by cchurch** [comment] 2015-05-11 00:38
Set the `ANSIBLE_LOAD_CALLBACK_PLUGINS` environment variable:

```
`ANSIBLE_LOAD_CALLBACK_PLUGINS=1 ansible ...`
```

**Comment by balajicbabu** [comment] 2015-05-12 10:24
Even after creating fix-ssl.py file and adding env variable: ANSIBLE_LOAD_CALLBACK_PLUGINS=1 ansible windows -i win_wrkstns -m win_ping, I still get the same error message:
[ansible@mgmt001 ansible]$ ANSIBLE_LOAD_CALLBACK_PLUGINS=1 ansible windows -i win_wrkstns -m win_ping
uk-lon01-rt02 | FAILED => Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/runner/**init**.py", line 590, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 792, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 957, in _executor_internal_inner
    conn = self.connector.connect(actual_host, actual_port, actual_user, actual_pass, actual_transport, actual_private_key_file)
  File "/usr/lib/python2.7/site-packages/ansible/runner/connection.py", line 51, in connect
    self.active = conn.connect()
  File "/usr/lib/python2.7/site-packages/ansible/runner/connection_plugins/winrm.py", line 132, in connect
    self.protocol = self._winrm_connect()
  File "/usr/lib/python2.7/site-packages/ansible/runner/connection_plugins/winrm.py", line 86, in _winrm_connect
    protocol.send_message('')
  File "/usr/lib/python2.7/site-packages/winrm/protocol.py", line 190, in send_message
    return self.transport.send_message(message)
  File "/usr/lib/python2.7/site-packages/winrm/transport.py", line 82, in send_message
    response = urlopen(request, timeout=self.timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1216, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib64/python2.7/urllib2.py", line 1189, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib64/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/usr/lib64/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib64/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
. 
Not sure what I'm doing wrong. @cchurch can you please help me on this ?

**Comment by phwelo** [comment] 2015-05-13 14:26
@balajicbabu i think you need to add "env" to the beginning there like <pre>env ANSIBLE_LOAD_CALLBACK_PLUGINS=1 ansible windows -i win_wrkstns -m win_ping</pre>

**Comment by berdario** [comment] 2015-06-15 18:05
The proper solution would be to check the selfsigned/root certificate.

Adding one `ansible_winrm_ca` to every windows host (if each of them is using a selfsigned certificate) in the inventory file (or in a dictionary defined in a `group_var` file, accessed by hostname) would suffice.

Then, if the winrm connection would be as simple as making an http request, the code should be equivalent to:

``` python
import ssl as tls
from urllib.request import urlopen

ctx = tls.create_default_context(cadata='{{ansible_winrm_ca}}')
urlopen(url, context=ctx)
```

(I haven't had a look at the winrm code, and I've no time to prepare a patch for this... but at least I wanted to mention briefly how this could be tackled, at a very high level, without sacrificing security by forgoing checks)

**Comment by GuillaumeQuerso** [comment] 2015-06-17 16:07
i have this error message:

fatal: [192.168.79.128] => SSH Error: Permission denied (publickey,password,keyboard-interactive).

i did the setup of WinRM with the script provided by the Ansible documentation and i created the callback plugin as suggested by @cchurch. The inventory variables are correctly defined. 
Can you please help me on this?

**Comment by berdario** [comment] 2015-06-17 21:30
@GuillaumeQuerso the mailing list might be a better venue for it, your error seems to be completely unrelated.

`SSH Error` means that it's actually using SSH to connect, not WinRM

remember to specify `ansible_connection: winrm`... when I tried the windows support out I had to try adding it in group_vars and/or in the inventory before it was picked up (I don't know why it was flaky... but maybe it was just a mistake on my side, since I haven't been able to reproduce it)

**Comment by GuillaumeQuerso** [comment] 2015-06-17 22:26
i have already set the ansible_connection: winrm and it is not working..

**Comment by jhawkesworth** [comment] 2015-06-19 17:34
@GuillaumeQuerso -  

what exact error message do you get?
 which ansible version are you using?  
can you share your inventory and playbook.

As suggested above it would be better to ansible on ansible-project mailing list as many more people will see your questions there.

**Comment by GuillaumeQuerso** [comment] 2015-06-22 09:49
i am running ansible 1.9.1 on a Ubuntu server 14.04.2, my remote machine is a windows 7 sp1. 

/etc/ansible/group_vars/windows.yml

ansible_ssh_user: AnsibleUser
ansible_ssh_pass: ansiblepass
ansible_ssh_port: 5986
ansible_connection: winrm

/etc/ansible/winplaybook.yml
- hosts: WIN-F6531IBP8HG
  tasks:
  - name: unarchive
    unarchive: src=/tmp/hello.txt.zip dest=C:\Users\Querso\Desktop

/etc/ansible/hosts 

WIN-F6531IBP8HG

i have python 2.7.6 and i have the following error message:
ansible-playbook /etc/ansible/winplaybook.yml -i WIN-F6531IBP8HG,

PLAY [WIN-F6531IBP8HG] *******************************************************\* 

GATHERING FACTS **************************************************************\* 
fatal: [WIN-F6531IBP8HG] => SSH Error: Permission denied (publickey,password,keyboard-interactive).
    while connecting to 192.168.79.133:22
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help diagnose the issue.

TASK: [unarchive] ************************************************************\* 
FATAL: no hosts matched or all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/home/guillaume/winplaybook.retry

WIN-F6531IBP8HG            : ok=0    changed=0    unreachable=1    failed=0   

if i try to ping windows:
ansible WIN-F6531IBP8HG -m win_ping
WIN-F6531IBP8HG | FAILED => SSH Error: Permission denied (publickey,password,keyboard-interactive).
    while connecting to 192.168.79.133:22
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help diagnose the issue.

thanks for your help

**Comment by berdario** [comment] 2015-06-22 11:43
@GuillaumeQuerso You keep hijacking this issue... PLEASE use the mailing list

The problem is that `ansible_connection: winrm` (together with all the others windows group_vars) isn't being picked up, because there's no such group as the windows one in your inventory file.

In fact, you're not even using an inventory file at all.

If you want to keep doing `-i WIN-F6531IBP8HG,` you can probably set these options directly inside the playbook, otherwise switch to using an inventory file

(btw, you can also set variables inside the inventory files.... I put there stuff that doesn't need to be encrypted by ansible-vault, e.g.:

```
[windows]
win7vm

[windows:vars]
ansible_connection=winrm

```

)

**Comment by jhawkesworth** [comment] 2015-06-22 12:07
You need to add your
WIN-F6531IBP8HG to a group called 'windows' so that the group vars you have
defined take effect:

So in your inventory file you should have

[windows]
WIN-F6531IBP8HG

Also, best to ask questions like this on the ansible-project google group
rather than on the github issue tracker - a lot more people will be able to
help you on the google group.

Hope this helps,

Jon

**Comment by GuillaumeQuerso** [comment] 2015-06-22 12:43
just to keep you informed, i created a topic on the google group (https://groups.google.com/forum/#!topic/ansible-project/YeGT-1Ux1yA). i changed my files: 
/etc/ansible/group_vars/windows/windows.yml 
ansible_ssh_user: AnsibleUser
ansible_ssh_pass: ansiblepass
ansible_ssh_port: 5986
ansible_connection: winrm

/etc/ansible/hosts 
[windows]
WIN-F6531IBP8NG

the ping is working but sometimes it fails with this message:
WIN-F6531IBP8HG | FAILED >> {
    "failed": true, 
    "msg": "\nProcess is terminated due to StackOverflowException.\n", 
    "parsed": false
} 
or this one:
WIN-F6531IBP8HG | FAILED >> {
    "failed": true, 
    "msg": "", 
    "parsed": false
}

but when i run the playbook, it still tries to connect via ssh and not winrm so it doesn't seem to see my windows.yml file but i don't know how to deal with this issue....

**Comment by klj613** [comment] 2015-09-07 21:43
I've used this workaround before however now it has stopped working. The latest commit (found with lg --grep=winrm so there might be newer commits which work) I can get to work with the callback workaround on v2 is e36b713 and anything newer won't work.

Anyone else having this issue with latest v2 code?

**Comment by klj613** [comment] 2015-09-07 22:17
Just used bisect and found that ce3ef7f4c16e47d5a0b5600e1c56c177b7c93f0d introduces the issue I am experiencing mentioned above.

**Comment by basictheprogram** [comment] 2015-09-11 22:00
Broken as @klj613  states.

```
$ ansible --version
ansible 2.0.0 (devel 9d4d7bd74d) last updated 2015/09/11 16:12:34 (GMT -500)
  lib/ansible/modules/core: (detached HEAD 4de4bd0be6) last updated 2015/09/11 16:12:35 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD ea1bd0b078) last updated 2015/09/11 16:12:35 (GMT -500)
  config file = /Users/tanner/projects/ansible.git/playbooks.git/ansible.cfg
  configured module search path = None
```

Even the callback_plugins isn't working for me now.

My work-around was to drop 

```
import ssl

try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    # Legacy Python that doesn't verify HTTPS certificates by default
    pass
else:
    # Handle target environment that doesn't support HTTPS verification
    ssl._create_default_https_context = _create_unverified_https_context
```

into my sitecustomize.py as _highly discouraged_ by [PEP0476](https://www.python.org/dev/peps/pep-0476/#opting-out).

**Comment by davidobrien1985** [comment] 2015-09-29 02:13
I'm experiencing this issue when running Ansible from my Mac (installed with pip) against a Vagrant Windows Box.
This setup works against an Ubuntu server just fine.

I suspect the issue is because Vagrant boxes are exposed only via host port forwarding. To access the Windows guest via winrm from my Ansible Host I need to specify the following command:
ansible all -i 127.0.0.1:55986, -m setup -vvvv -u vagrant -k -c winrm

I reckon this trips up winrm or Ansible or something else, just doesn't work.

For now my workaround will be to have Ansible also installed in a Vagrant guest, that way I can add the actual hostname / IP address of the windows node to the inventory file.

**Comment by basictheprogram** [comment] 2015-10-02 05:41
:poke: 20 days ago did the horrible no good very bad thing of changing my sitecustomize.py. Did a pristine pull and seems this is still broken in 

```
$ ansible --version
ansible 2.0.0 (devel 0a21e2ab4d) last updated 2015/10/01 15:56:42 (GMT -500)
  lib/ansible/modules/core: (detached HEAD b9090a8146) last updated 2015/10/01 15:56:42 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD 962afeed54) last updated 2015/10/01 15:56:43 (GMT -500)
  config file =
  configured module search path = None
```

Any progress on a better solution?

**Comment by jvervlied** [comment] 2015-10-13 18:59
I've been fighting this all day. The underlying issue has to do with they way python handles ssl validation going forward from v2.7.9. There is more in depth here
https://github.com/diyan/pywinrm/issues/46

For now I just built a Ubuntu 12.04 VM with python 2.7.6 for use as my control station until we can resolve this. I'm not sure if it should be fixed in ansible's winrm module or if it first needs to be fixed upstream with pywinrm. 

I tried fixing it myself, but just kept breaking things, here is hoping I can spur the conversation to help drive a resolution.

**Comment by dreamcat4** [comment] 2015-10-13 19:56
Hello.
I have python v2.7.9 installed here on ubuntu currently. The thing is I have 2 versions of ansible. One from APT (1.9.3), and then also the one from git...
- The v1.9.3 installed from APT will load up the file `callback_plugins/fix_ssl.py`. And that circumvents the certificate checking successfully. I would be able to use this version, except it's lacking many recent windows modules.
- The version from git is 2.x + and has all the latest windows modules. However for the life of me (I don't know why). But it also loads the same callback plugin. I can see the `.pyc` file afterward. Yet the circumvention file does not work anymore. It looks like this:

``` python
import ssl
if hasattr(ssl, '_create_default_https_context') and hasattr(ssl, '_create_unverified_context'):
    ssl._create_default_https_context = ssl._create_unverified_context

class CallbackModule(object):
    pass
```

...The version of python (and other python libs) seems to be 2.7.9 in both cases.

Also need the following `ansible.cfg` in your local folder to get the file `callback_plugin/fix-ssl.py` to be executed:

``` ini
[defaults]
bin_ansible_callbacks=True
callback_plugins = ./callback_plugins
library = ./library
```

Anyway my point is that we can't keep going on like this for very much longer. So @berdario can you please elaborate on this solution for us?

https://github.com/ansible/ansible/issues/10294#issuecomment-112156407

Or anybody else can come up with yet another workaround? (shudder)

**Comment by dreamcat4** [comment] 2015-10-13 19:57
You may also need the following `ansible.cfg` in your local folder to get the file `callback_plugin/fix-ssl.py` to be executed:

```ini
[defaults]
bin_ansible_callbacks=True
callback_plugins = ./callback_plugins
library = ./library
```

**Comment by jvervlied** [comment] 2015-10-13 20:52
@dreamcat4 That solution doesn't work for ansible 2 (from git). Though as I said, it's working when using python-2.7.6.

Edit: I see that's what you said, just re-iterating it here. We need a real solution here, but I don't know what the proper answer for this one is.

**Comment by basictheprogram** [comment] 2015-10-14 15:46
> On Oct 13, 2015, at 2:59 PM, Dreamcat4 notifications@github.com wrote:
> 
> You may also need the following ansible.cfg in your local folder to get the file callback_plugin/fix-ssl.py to be executed:
> 
> [defaults]
> bin_ansible_callbacks=True
> callback_plugins = ./callback_plugins
> library = ./library
> I use virtualenv for my git cloned ansible stuff. Inside the virtualenv I added the below to my sitecustomize.py (as posted on Sep 11 http://git.io/vCocB)

$ cat  ./lib/python2.7/site-packages/sitecustomize.py
import ssl

try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    # Legacy Python that doesn't verify HTTPS certificates by default
    pass
else:
    # Handle target environment that doesn't support HTTPS verification
    ssl._create_default_https_context = _create_unverified_https_context

**Comment by TvL2386** [comment] 2015-10-23 12:22
I'm having the same issue here.
It would be great if we could disable certificate verfication with an ansible(-playbook) command line option

**Comment by dreamcat4** [comment] 2015-10-23 15:13
@TvL2386 It seems there's a more recent PR come out 2 weeks ago which is related to this matter. Looks like relevant people have been looking into it... sorry just doesn't seem to be linked to this issue yet.

https://github.com/ansible/ansible/pull/12687

Also someone else recent. Not as certain if it's actually related to our winrm ssl verification problems or not:

https://github.com/ansible/ansible/issues/12884

**Comment by azenakhi** [comment] 2015-10-23 15:40
Thank you for this response, but I think he doesn't my problem. I wanted redefine the variable ca_file_path inside ansible.cfg for tacking my own certification location. Ansible takes always the default path /etc/ssl/certs.

Thank you to go here in order to understand this problem :
https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/urls.py
method : def get_ca_certs(self).

The all path in that method are hard-coded

Thank you for your help.

**Comment by nik-shornikov** [comment] 2015-11-24 23:45
Would someone be kind enough to tell me if self-signed certs installed per this http://unix.stackexchange.com/questions/90450/adding-a-self-signed-certificate-to-the-trusted-list will still encounter the issue?

If this helps anyone, Python is set up to look at `/etc/ssl/certs/ca-certificates.crt` (per http://stackoverflow.com/questions/30577392/python-using-system-ssl-certificates).

On CentOS, that does link into a bundled managed by the `ca-certificates` yum package (http://kb.kerio.com/product/kerio-connect/server-configuration/ssl-certificates/adding-trusted-root-certificates-to-the-server-1605.html).

**Comment by jhawkesworth** [comment] 2015-11-26 18:27
@nik-shornikov - I think your question is best asked on ansible project
mailing list.

If I've understood its a question of where python looks for certificates in
this case.

**Comment by soniah** [comment] 2015-11-27 07:48
Ubuntu machines after about the Trusty release (eg Wily) can add the previously mentioned Python to `/usr/lib/python2.7/sitecustomize.py`. The Python code is (in case you missed it):

```
import ssl

try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    # Legacy Python that doesn't verify HTTPS certificates by default
    pass
else:
    # Handle target environment that doesn't support HTTPS verification
    ssl._create_default_https_context = _create_unverified_https_context
```

As @basictheprogram mentioned, [pep-0746](https://www.python.org/dev/peps/pep-0476/#opting-out) strongly discourages this.

I'd be interested in finding out where to get the **Windows SSL certificate**, so I could add it the keystore. I think that would be the correct way of solving this, until a patch to Ansible is accepted.

**Comment by dreamcat4** [comment] 2015-11-27 10:37
Yeah that's one of the old workarounds. But recently they've merged the new one. So that should be available on master now:

https://github.com/ansible/ansible/pull/12687

**Comment by soniah** [comment] 2015-11-27 20:17
:+1:

I'd still be interested in where to get the **Windows SSL Certificate**, as that would be the correct solution :-)

**Comment by nitzmahone** [comment] 2015-12-10 21:21
This has been fixed in 2.0 + pywinrm-0.1.1. Leaving open for 1.9.x backport (see #13508)

**Comment by nitzmahone** [comment] 2015-12-15 01:13
Closing- backported for 1.9.5 (see #13508).

**Closed as completed by nitzmahone** 2015-12-15 01:13 UTC
Labels: P2, windows, bug

**Comment by sumanthreddybolledla** [comment] 2017-03-13 19:26
Hi,
I'm getting the below issue,  Can someone please help me? 
**ansible version: 1.9.4
python: 2.6
pyopenssl: 0.10**

FAILED => Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 586, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 789, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 968, in _executor_internal_inner
    conn = self.connector.connect(actual_host, actual_port, actual_user, actual_pass, actual_transport, actual_private_key_file, delegate_host)
  File "/usr/lib/python2.6/site-packages/ansible/runner/connection.py", line 35, in connect
    conn = utils.plugins.connection_loader.get(transport, self.runner, host, port, user=user, password=password, private_key_file=private_key_file)
  File "/usr/lib/python2.6/site-packages/ansible/utils/plugins.py", line 218, in get
    self._module_cache[path] = imp.load_source('.'.join([self.package, name]), path)
  File "/usr/lib/python2.6/site-packages/ansible/runner/connection_plugins/winrm.py", line 32, in <module>
    from winrm import Response
  File "/usr/lib/python2.6/site-packages/winrm/__init__.py", line 6, in <module>
    from winrm.protocol import Protocol
  File "/usr/lib/python2.6/site-packages/winrm/protocol.py", line 11, in <module>
    from winrm.transport import Transport
  File "/usr/lib/python2.6/site-packages/winrm/transport.py", line 42, in <module>
    from requests_credssp import HttpCredSSPAuth
  File "/usr/lib/python2.6/site-packages/requests_credssp/__init__.py", line 1, in <module>
    from .credssp import HttpCredSSPAuth
  File "/usr/lib/python2.6/site-packages/requests_credssp/credssp.py", line 8, in <module>
    raise Exception("Cannot import pyOpenSSL")
Exception: Cannot import pyOpenSSL

**Comment by sakhamuri4545** [comment] 2018-12-12 21:16
Hi,

I am getting following error when i am trying to run a playbook in ansible,

Fatal: [server] :  UNREACHABLE! =>
{
 "Changed" : false, "msg": "Basic: Bad HTTP Response FRom Server.  code 404",
"Unreachable": True
}

And this is my host file
[webserver]
sskwin.eastus.cloudapp.azure.com

[webserver:vars]
ansible_user=windows
ansible_password=Sakhamur@
ansible_connection=winrm
ansible_winrm_transport=basic
ansible_winrm_scheme=http
ansible_port=5985
#ansible_winrm_operation_timeout_sec=60
#ansible_winrm_read_timeout_sec=70
ansible_winrm_server_cert_validation=ignore

My main file is

---
- hosts: webserver
  gather_facts: true
  tasks:
    - name: create a file on windows server
      win_file:
        path: C:/temp/hello
        state: touch

did any one face this problem
