### ISSUE TITLE
ansible 2.x regression: retry file feature gone ?

### ISSUE THREAD

**Issue by jcst** [ansible/ansible#13944] opened 2016-01-18 03:32 UTC
Is that feature gone ?

still documented in the ansible.cfg 

```
#retry_files_enabled = False
#retry_files_save_path = ~/.ansible-retry
```

but generate_retry_inventory() has gone from ansible-playbook ?

**Comment by sivel** [comment] 2016-01-18 20:56
Based on a quick search, it does appear to have been overlooked. The only place `RETRY_FILES_ENABLED` is used currently is in `constants.py`, and I don't see any additional retry code laying around.

```
$ ack RETRY_FILES_ENABLED
lib/ansible/constants.py
237:RETRY_FILES_ENABLED            = get_config(p, DEFAULTS, 'retry_files_enabled', 'ANSIBLE_RETRY_FILES_ENABLED', True, boolean=True)
```

**Comment by larsks** [comment] 2016-01-19 00:10
If someone decides to put that feature back, please (oh, pretty please) don't go dropping them into `$HOME` by default.  Surely either "the playbook directory" or "a temporary directory" would be better.

**Comment by elasticdog** [comment] 2016-01-19 00:15
> If someone decides to put that feature back, please (oh, pretty please) don't go dropping them into $HOME by default.

Agree...this was [discussed on the list](https://groups.google.com/d/topic/ansible-devel/iOtlm1YbWZ0/discussion) about 2 years ago, and I tend to think `~/.ansible/retry` makes a much better default directory. Either way, I look forward to having the retry files back, and have missed them with v2.0.

**Comment by jimi-c** [comment] 2016-01-26 18:16
Whoopsie... not sure how we missed this one. We'll get this in 2.0.1.

**Comment by jimi-c** [comment] 2016-01-26 19:14
^ reimplemented. I've also added the ability to now leave the retry directory unset (with a default value of `None`), in which case the retry file will be written to the playbook directory. Otherwise, if the retry path is set, it will use that.

Sorry for missing this!

**Comment by conorsch** [comment] 2016-01-29 22:00
As always, thanks for a quick response, @jimi-c!

**Comment by solomongifford** [comment] 2016-03-08 02:05
The retry feature appears to only be capturing the unreachable and not the failed.

**Comment by elasticdog** [comment] 2016-03-14 19:00
Can confirm that this is not capturing the failed hosts (only the unreachable ones), so this issue should be re-opened.

**Comment by jimi-c** [comment] 2016-04-19 15:33
I was unable to reproduce the above reported problem with the following setup:

<pre>
# cat inv
localhost ansible_connection=local
192.168.1.255
# cat test.yml
- hosts:
  - localhost
  - 192.168.1.255
  gather_facts: no
  tasks:
  - ping:
  - fail:
# ANSIBLE_RETRY_FILES_ENABLED=1 ansible-playbook -vv test.yml -i inv
Using /etc/ansible/ansible.cfg as config file
PLAYBOOK: test.yml *************************************************************
1 plays in test.yml
PLAY [localhost,192.168.1.255] *************************************************
TASK [ping] ********************************************************************
task path: /root/testing/test_retry/test.yml:6
fatal: [192.168.1.255]: UNREACHABLE! => {"changed": false, "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", "unreachable": true}
ok: [localhost] => {"changed": false, "ping": "pong"}
TASK [fail] ********************************************************************
task path: /root/testing/test_retry/test.yml:7
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed as requested from task"}
NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @test.retry
PLAY RECAP *********************************************************************
192.168.1.255              : ok=0    changed=0    unreachable=1    failed=0   
localhost                  : ok=1    changed=0    unreachable=0    failed=1   
# cat test.retry
192.168.1.255
localhost
</pre>

Could someone please confirm whether or not they're still seeing this on the devel branch, and if so could they please share an example which reproduces the problem?

**Comment by i5513** [comment] 2016-05-09 15:29
I had to use your workaround env var: ANSIBLE_RETRY_FILES_ENABLED=1, without it , it didn't work.

But I have

```
retry_files_enabled = True
retry_files_save_path = ~/.ansible-retry
```

On ansible.cfg

I have ansible-2.0.2.0-1.el6.noarch

Thank you

**Comment by jimi-c** [comment] 2016-05-17 01:50
Seeing as this has been fixed for a while, I'll go ahead and close this now.

Thanks!

**Closed as completed by jimi-c** 2016-05-17 01:50 UTC
Labels: bug

**Comment by elasticdog** [comment] 2016-05-17 22:43
Note that I still (as of today) get runs using my work Ansible setup where the failed hosts do not trigger the retry file to be generated, but the unreachable hosts do. This is with Ansible v2.0.10...unfortunately, I cannot reproduce this behavior with your [minimal test example](https://github.com/ansible/ansible/issues/13944#issuecomment-211980843) from above (everything works as expected there). I still hope to try and find out what the key difference is, and will report back.
