### ISSUE TITLE
Template module failing when using su (edit: request for help with filesystem permissions error)

### ISSUE THREAD

**Issue by stdacl** [ansible/ansible#8594] opened 2014-08-13 08:37 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8 (devel 9edf3a7) last updated Tue Aug 12 18:25:52 2014 -0400
##### Environment:

Running from: Ubuntu 12.04
Managing: Oracle Solaris 10
##### Summary:

Template module fail when using su with the message:

{msg: Source /tmp/ansible-tmp-1407917907.05-71556896811980/source not readable}
##### Steps To Reproduce:

Run playbook using the template module as an su user.

ansible-playbook site.yml -i inventory -vvv

```
- name: Template fails as su
  hosts: all
  vars:
    ansible_ssh_port: 2200
    user_name: appadm

  tasks:
    - name: Create some configuration file
      su: yes
      su_user: "{{ user_name }}"
      template: src=config dest=/tmp/config
```
##### Expected Results:

Requested files created
##### Actual Results:

```
PLAY [Template fails as su] *************************************************** 

TASK: [Create some configuration file] **************************************** 
<127.0.0.1> ESTABLISH CONNECTION FOR USER: johndoe
<127.0.0.1> EXEC ['ssh', '-C', '-tt', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/johndoe/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=2200', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', '127.0.0.1', "/bin/sh -c 'mkdir -p /tmp/ansible-tmp-1407917907.05-71556896811980 && chmod a+rx /tmp/ansible-tmp-1407917907.05-71556896811980 && echo /tmp/ansible-tmp-1407917907.05-71556896811980'"]
<127.0.0.1> EXEC ['ssh', '-C', '-tt', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/johndoe/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=2200', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', '127.0.0.1', u'/bin/sh -c \'rc=0; [ -r "/tmp/config" ] || rc=2; [ -f "/tmp/config" ] || rc=1; [ -d "/tmp/config" ] && echo 3 && exit 0; (/usr/bin/md5sum /tmp/config 2>/dev/null) || (/sbin/md5sum -q /tmp/config 2>/dev/null) || (/usr/bin/digest -a md5 /tmp/config 2>/dev/null) || (/sbin/md5 -q /tmp/config 2>/dev/null) || (/usr/bin/md5 -n /tmp/config 2>/dev/null) || (/bin/md5 -q /tmp/config 2>/dev/null) || (/usr/bin/csum -h MD5 /tmp/config 2>/dev/null) || (/bin/csum -h MD5 /tmp/config 2>/dev/null) || (echo "${rc} /tmp/config")\'']
<127.0.0.1> PUT /tmp/tmpNRENwN TO /tmp/ansible-tmp-1407917907.05-71556896811980/source
<127.0.0.1> PUT /tmp/tmpVJhLMO TO /tmp/ansible-tmp-1407917907.05-71556896811980/copy
<127.0.0.1> EXEC ['ssh', '-C', '-tt', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/johndoe/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=2200', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', '127.0.0.1', "/bin/sh -c 'chmod a+r /tmp/ansible-tmp-1407917907.05-71556896811980/copy'"]
<127.0.0.1> EXEC ['ssh', '-C', '-tt', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/johndoe/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=2200', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', '127.0.0.1', u'/bin/sh -c \'su appadm -c "/bin/sh -c \'"\'"\'echo SUDO-SUCCESS-mjzpfzevqpohuqkfptbhjtrtzasuztzn; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /tmp/ansible-tmp-1407917907.05-71556896811980/copy\'"\'"\'"\'']
failed: [127.0.0.1] => {"failed": true}
msg: Source /tmp/ansible-tmp-1407917907.05-71556896811980/source not readable

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/johndoe/playbook.retry

127.0.0.1                  : ok=0    changed=0    unreachable=0    failed=1   
```

**Comment by mpdehaan** [comment] 2014-08-13 13:31
Sounds like a valid permissions error, but it might be nice if we could share a different exception.

You mentioned the managed OS is Solaris 10, which is probably why we don't see this more often.  What's the destination filesystem and what do permissions look like? 

You may be able to export ANSIBLE_KEEP_REMOTE_FILES=1 on the control machine to run this and learn more, as ansible will keep the temp dir around.

(The default su user is root, I'm assuming you are not passing --su-user and it remains root.)

Thanks!

**Comment by stdacl** [comment] 2014-08-14 02:39
Well, it definitely permission error. So, as you can see from the trace log  below, the source file was created with permission 600 by user johndoe and that's why su user (appadm) can't read it.
The question is why it's happenning? Because all other modules for instance "copy" are working well.

The destination filesystem is ZFS which is quite often used with Oracle Solaris.

Here is another one test with "ANSIBLE_KEEP_REMOTE_FILES" flag is set:

```
johndoe@desk:/pub/site/ansible/bug_report$ ANSIBLE_KEEP_REMOTE_FILES=1 ansible-playbook -i inventory playbook.yml -u johndoe -vvv

PLAY [Template fails as su] *************************************************** 

TASK: [Create some configuration file] **************************************** 
<127.0.0.1> ESTABLISH CONNECTION FOR USER: johndoe
<127.0.0.1> EXEC ['ssh', '-C', '-tt', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/johndoe/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=2200', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', '127.0.0.1', "/bin/sh -c 'mkdir -p /tmp/ansible-tmp-1407982491.27-242988883727372 && chmod a+rx /tmp/ansible-tmp-1407982491.27-242988883727372 && echo /tmp/ansible-tmp-1407982491.27-242988883727372'"]
<127.0.0.1> EXEC ['ssh', '-C', '-tt', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/johndoe/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=2200', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', '127.0.0.1', u'/bin/sh -c \'rc=0; [ -r "/tmp/config" ] || rc=2; [ -f "/tmp/config" ] || rc=1; [ -d "/tmp/config" ] && echo 3 && exit 0; (/usr/bin/md5sum /tmp/config 2>/dev/null) || (/sbin/md5sum -q /tmp/config 2>/dev/null) || (/usr/bin/digest -a md5 /tmp/config 2>/dev/null) || (/sbin/md5 -q /tmp/config 2>/dev/null) || (/usr/bin/md5 -n /tmp/config 2>/dev/null) || (/bin/md5 -q /tmp/config 2>/dev/null) || (/usr/bin/csum -h MD5 /tmp/config 2>/dev/null) || (/bin/csum -h MD5 /tmp/config 2>/dev/null) || (echo "${rc} /tmp/config")\'']
<127.0.0.1> PUT /tmp/tmpCResfU TO /tmp/ansible-tmp-1407982491.27-242988883727372/source
<127.0.0.1> PUT /tmp/tmp21GyXI TO /tmp/ansible-tmp-1407982491.27-242988883727372/copy
<127.0.0.1> EXEC ['ssh', '-C', '-tt', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/johndoe/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=2200', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', '127.0.0.1', "/bin/sh -c 'chmod a+r /tmp/ansible-tmp-1407982491.27-242988883727372/copy'"]
<127.0.0.1> EXEC ['ssh', '-C', '-tt', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/johndoe/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=2200', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', '127.0.0.1', u'/bin/sh -c \'su appadm -c "/bin/sh -c \'"\'"\'echo SUDO-SUCCESS-nymvborbgbhoxowkjtcamfjfqahpektl; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /tmp/ansible-tmp-1407982491.27-242988883727372/copy\'"\'"\'"\'']
failed: [127.0.0.1] => {"failed": true}
msg: Source /tmp/ansible-tmp-1407982491.27-242988883727372/source not readable

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/johndoe/playbook.retry

127.0.0.1                  : ok=0    changed=0    unreachable=0    failed=1 



-bash-3.2$ uname -a
SunOS unknown 5.10 Generic_147148-26 i86pc i386 i86pc
-bash-3.2$ who am i
johndoe      pts/2        Aug 14 09:07    (10.0.2.2)
-bash-3.2$ ls -lR ansible* 
ansible-tmp-1407982491.27-242988883727372:
total 128
-rw-r--r--   1 johndoe    other      61318 Aug 14 09:14 copy
-rw-------   1 johndoe    other        220 Aug 14 09:14 source
-bash-3.2$ 
```

**Comment by mpdehaan** [comment] 2014-08-14 15:14
Can you stop by the ansible-project list and share a link to this one?   

While this is definitey an error and something we have to figure out, it's not related to the template module and that's a bit better of a support forum than the bug tracker.   Others may also be able to help with suggestions.

Thanks!

**Comment by stdacl** [comment] 2014-08-15 05:54
New information: I replayed the scenario with Solaris11, Centos 6.5 as managed hosts, and I've got the same error. So I suppose this bug is platform-independent.

**Comment by jimi-c** [comment] 2014-09-15 17:25
@stdacl confirmed, I am seeing this when going from a Fedora 20 system to both Centos 6.5 and Ubuntu 14.04 systems, so it's definitely not platform dependent. Looking into this now.

**Comment by jimi-c** [comment] 2014-09-15 18:24
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2014-09-15 18:24 UTC
Labels: P2, bug, solaris
