### ISSUE TITLE
CRITICAL BUG REPORT: using the user module on Mac OS X will kill your groups

### ISSUE THREAD

**Issue by domibarton** [ansible/ansible#13266] opened 2015-11-23 22:47 UTC
## Description

I think I found a really (**REALLY!**) critical bug... at least if I'm not completely wrong.

When you use the [user module](http://docs.ansible.com/ansible/user_module.html) to run a task on Linux and you don't specify the `group` or `groups` parameters, then the group membership isn't touched. If you do the same on Mac OS X then your user's groups will be wiped!
## Steps to reproduce

Create a new task which changes the user's info but not the group(s).
For example change the shell:

``` yaml

---
- name: configure zsh shell for user foobar
  user:
    name: foobar
    shell: /usr/bin/zsh
```

Run the task on Linux and on Mac OS X.

**WARNING: Make sure you add your user with the username to the sudoers file, because you might end up without any groups and/or admin access! Again, don't rely on sudo access via group permissions, because you probably won't have any groups after you've executed the step above.**
## Actual result

On Linux only the shell is changed to `/usr/bin/zsh`, while the group(s) aren't touched!

On Mac OS X the primary group and all additional groups will be wiped. The primary group is set to `nogroup` while all required additional groups are removed (e.g. `staff`, `wheel`, `admin`). You end up with a non-privileged user and you can't run `sudo` to get it fixed!
## Expected result

As long as you don't specify the `group` or `groups` parameter, the groups shouldn't be touched at all!
## Platform
- Ansible 1.9.3
- Mac OS X 10.11.1
- Python 2.7.10
## Temporary fix

I messed up my whole system when I tried to change the shell. As I wrote above, make sure you've a sudo rule for your user in place before testing the task above.

If you've messed up your system reboot into single user mode (hold `command+s` while booting).

Mount the filesystem for write-access:

``` bash
mount -uw /
```

Add your user to the `/etc/sudoers` file:

``` bash
vim /etc/sudoers
```

Hit `ctrl-d` or enter `exit` to continue booting your system and after your system has booted, run sudo to add your user back into the right groups:

``` bash
USERNAME=dbarton
dseditgroup -o edit -a $USERNAME -t user admin
dseditgroup -o edit -a $USERNAME -t user staff
dseditgroup -o edit -a $USERNAME -t user com.apple.sharepoint.group.1
dseditgroup -o edit -a $USERNAME -t user everyone
dseditgroup -o edit -a $USERNAME -t user localaccounts
dseditgroup -o edit -a $USERNAME -t user _appserverusr
dseditgroup -o edit -a $USERNAME -t user _appserveradm
dseditgroup -o edit -a $USERNAME -t user _lpadmin
dseditgroup -o edit -a $USERNAME -t user _appstore
dseditgroup -o edit -a $USERNAME -t user _lpoperator
dseditgroup -o edit -a $USERNAME -t user _developer
dseditgroup -o edit -a $USERNAME -t user com.apple.access_ftp
dseditgroup -o edit -a $USERNAME -t user com.apple.access_screensharing
dseditgroup -o edit -a $USERNAME -t user com.apple.access_ssh
```

I'm not sure if these are the right groups because I don't have any backup of my group setup before Ansible screwed me!

**Comment by domibarton** [comment] 2015-11-23 22:52
Oh and I tried to changed the shell of my `root` user... this is what my `root` user looks now:

``` bash
# id
uid=0(root) gid=4294967295(nogroup) groups=12(everyone),61(localaccounts),100(_lpoperator),701(com.apple.sharepoint.group.1)
```

OMFG... anyone an idea how to fully restore group privileges on Mac OS X? :/

**Comment by bcoca** [comment] 2015-11-23 23:22
tested this and I cannot reproduce, when I check id i get the following:

```
#> id foobar
uid=504(foobar) gid=4294967295(nogroup) groups=12(everyone),61(localaccounts),701(com.apple.sharepoint.group.2),702(com.apple.sharepoint.group.3),100(_lpoperator),401(com.apple.sharepoint.group.1)
```

**Comment by domibarton** [comment] 2015-11-23 23:52
Now check your groups ;)  
your `gid` is set to `nogroup` and you no longer have `admin` access...

I think there is no user in OS X which has `gid` set to `nogroup`...

**Comment by bcoca** [comment] 2015-11-23 23:53
nope, i have 3 full lines worth of groups on my user

**Comment by domibarton** [comment] 2015-11-23 23:56
but what's with your output above?

```
uid=504(foobar) gid=4294967295(nogroup) groups=12(everyone),61(localaccounts),701(com.apple.sharepoint.group.2),702(com.apple.sharepoint.group.3),100(_lpoperator),401(com.apple.sharepoint.group.1)
```

see `gid=4294967295(nogroup)`?

Check it against a "proper user":

```
uid=501(foobar) gid=20(staff) groups=20(staff),12(everyone),33(_appstore),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),100(_lpoperator),204(_developer),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh),701(com.apple.sharepoint.group.1)
```

Or try sudo...

**Comment by bcoca** [comment] 2015-11-24 00:00
i created the user w/o specifying any groups, that is what OS X assigns by default

**Comment by bcoca** [comment] 2015-11-24 00:03
hmm, i get nogroup even when i specify a group

**Comment by domibarton** [comment] 2015-11-24 00:03
No it isn't!

http://cloud.confirm.ch/dtH6

OS X defines a group or a series of groups... but Ansible will destroy them!

**Comment by bcoca** [comment] 2015-11-24 00:03
i created from the command line, not using settings

**Comment by domibarton** [comment] 2015-11-24 00:04
OK I see, because you didn't define any groups on the CLI. 
But most of the users have groups defined and you don't want them to be vanished after Ansible run over it...

**Comment by bcoca** [comment] 2015-11-24 00:06
i added staff, still adds 'nogroup' and running your tests does nothing to modify the groups

I don't have access to the mac in question directly (i was given ssh) so I cannot test with a user created through the interface

**Comment by bcoca** [comment] 2015-11-24 00:07
from the code being executed I cannot see any way for what you describe to happen unless you set groups=""

**Comment by domibarton** [comment] 2015-11-24 00:10
Just see yourself...

http://cloud.confirm.ch/dtL6

**Comment by domibarton** [comment] 2015-11-24 00:17
Mhm weird, isn't it? That should only happen when `groups` is set to an empty string, but even then it should only "clean up" the additional groups and not the primary group. I've also tried to set the `append=yes` parameter (without any `group` or `groups` parameter), but that didn't help either.

Something's really wrong here!

Sorry I'm really tired now (it's late night in Switzerland ^^) from fixing my Mac ;)
But I'll have a look at the user module by Wednesday and I hope I find something by debugging it.

Thanks anyway for your support mate!

**Comment by tima** [comment] 2015-11-24 00:49
I was able to reproduce @domibarton's problem if I follow his steps of creating the user there the Apple System Preferences. Same version of Ansible and Python, but on Yosemite.

**Comment by bcoca** [comment] 2015-11-24 00:53
I got 3 diff people reproducing the issue now, seems that the user needs to be created a certain way.

**Comment by domibarton** [comment] 2015-11-24 09:43
I started to debug the user module and the following command is definitely run:

``` bash
/usr/bin/dscl . -create /Users/foobar PrimaryGroupID 4294967295
```

This happens in the [modify_user method](https://github.com/ansible/ansible-modules-core/blob/devel/system/user.py#L1682) of the [DarwinUser class](https://github.com/ansible/ansible-modules-core/blob/devel/system/user.py#L1389) on [line 1689-1703](https://github.com/ansible/ansible-modules-core/blob/devel/system/user.py#L1689-L1703):

``` python
        for field in self.fields:
            if self.__dict__.has_key(field[0]) and self.__dict__[field[0]]:
                current = self._get_user_property(field[1])
                if current is None or current != self.__dict__[field[0]]:
                    cmd = self._get_dscl()
                    cmd += [ '-create', '/Users/%s' % self.name,
                             field[1], self.__dict__[field[0]]]
                    (rc, _err, _out) = self.execute_command(cmd)
                    if rc != 0:
                        self.module.fail_json(
                            msg='Cannot update property "%s" for user "%s".'
                            % (field[0], self.name), err=err, out=out, rc=rc)
                    changed = rc
                    out += _out
                    err += _err
```

The following condition matches for the keys `shell` and `group`:

``` python
            if self.__dict__.has_key(field[0]) and self.__dict__[field[0]]:
```

Apparently the `self.__dict__[field[0]]` contains the value `4294967295`, even if we don't specify anything in the task!

**Comment by domibarton** [comment] 2015-11-24 09:46
And [there's the error](https://github.com/ansible/ansible-modules-core/blob/devel/system/user.py#L1498-L1507):

``` python
    def _make_group_numerical(self):
        '''Convert SELF.GROUP to is stringed numerical value suitable for dscl.'''
        if self.group is None:
            self.group = 'nogroup'
        try:
            self.group = grp.getgrnam(self.group).gr_gid
        except KeyError:
            self.module.fail_json(msg='Group "%s" not found. Try to create it first using "group" module.' % self.group)
        # We need to pass a string to dscl
        self.group = str(self.group)
```

The `_make_group_numerical()` method is [called right before](https://github.com/ansible/ansible-modules-core/blob/devel/system/user.py#L1687) the loop is started in `modify_user`, which will set then the group to `nogroup`:

``` python
        if self.group is None:
            self.group = 'nogroup'
```

**Comment by domibarton** [comment] 2015-11-24 10:48
I've fixed the problem and created a [pull request](https://github.com/ansible/ansible-modules-core/issues/2538). I know it isn't perfect, but I didn't want to refactor more of the code. 

Unfortunately I don't know why the additional groups were wiped, so I think there's one more thing we've to fix.

**Comment by jctanner** [comment] 2016-09-28 14:35
Resolved by https://github.com/ansible/ansible-modules-core/pull/2538

**Closed as completed by jctanner** 2016-09-28 14:35 UTC
Labels: affects_2.2, bug
