### ISSUE TITLE
ansible-pull does not recognize git updated branches

### ISSUE THREAD

**Issue by go2sh** [ansible/ansible#604] opened 2012-07-17 13:02 UTC
I'm using ansible-pull as cron.daily job for syncing new packages to my clients.
But right now it fails to pull updates from the remote host. 
I run ansible-pull like this:

``` bash
#!/bin/bash
# Cron job to git clone/pull a repo and then run locally
echo "127.0.0.1" > /tmp/ansible_hosts
su root -c 'env ANSIBLE_HOSTS="/tmp/ansible_hosts" ansible-pull -d /var/lib/ansible/local -U ansible-git:ansible -C ansible-update >/var/log/ansible-pull.log 2>&1'
```

ansible-git is defind in my ssh_config. The Output from ansible-pull is:

```
127.0.0.1 | success >> {
    "after": "971fe17", 
    "before": "971fe17", 
    "changed": false
}
```

But git status shows:

```
~# git status
# On branch ansible-update
# Your branch is behind 'origin/ansible-update' by 3 commits, and can be fast-forwarded.
#
nothing to commit (working directory clean)
```

**Comment by mpdehaan** [comment] 2012-07-17 14:48
Assigning to sfromm, though if you'd like to help figure it out that would be welcome.

**Comment by go2sh** [comment] 2012-07-17 15:58
I will try to debug the code. But my python skills are very poor.

**Comment by mpdehaan** [comment] 2012-07-17 18:27
was this repo originally copied instead of cloned?   Currently the git module expects a repo that was cloned with the "git clone" command.

**Comment by mpdehaan** [comment] 2012-07-17 18:27
see https://github.com/ansible/ansible/issues/601

**Comment by goozbach** [comment] 2012-07-17 18:28
Could be related to #601

**Comment by sfromm** [comment] 2012-07-17 18:42
Not necessarily related to this issue, but -U means --url with ansible-pull.  Not --sudo-user as it does with ansible-playbook.

**Comment by mpdehaan** [comment] 2012-07-17 20:53
closing as duplicate of #601 since I haven't heard anything, let me know if you disagree at this repo was originated in some way other than a git clone (in which case it's not a dup)

**Comment by go2sh** [comment] 2012-07-18 09:53
It was cloned by ansible-pull script, because the local dir was empty before the first run.

**Comment by mpdehaan** [comment] 2012-07-18 11:41
ok, reopening, git module has additional things to fix probably

**Comment by sfromm** [comment] 2012-07-18 15:51
@go2sh, please provide the output of _git branch -a_.  Thanks.

**Comment by sfromm** [comment] 2012-07-18 16:03
@go2sh: One more question:  what version of ansible are you using?

**Comment by sfromm** [comment] 2012-07-18 17:34
I can replicate the problem by if I update the local repository with git (_git pull_) and then try to update it with ansible's git module.  The latter step fails.

It appears the git module is basically doing the following:

```
git checkout master
git pull -u origin
git checkout <branchname> --force
```

The first step, _git checkout master_, is called by switchLocalBranch() from inside pull(), line 154 in my ansible repo.  My repo is at 13abe50, a little bit behind.  If the module doesn't check out master, the pull step will work as expected and the repo will go to HEAD for the desired branch.

One other thing I would add:  when creating the local branch at line 151 (git checkout -b %s origin/%s), I think it should also use the option _--track_ since it is meant to track the upstream branch.

**Comment by go2sh** [comment] 2012-07-18 23:25
```
/var/lib/ansible/local# git branch -a
* ansible-update
  master
  remotes/origin/HEAD -> origin/master
  remotes/origin/ansible-update
  remotes/origin/master
```

I use ansible 0.6 .

**Comment by sfromm** [comment] 2012-07-20 17:49
The git module probably needs some deeper work, but I opted to fix this specific issue instead.  I'd appreciate comments on skipping the step switchLocalBranch( branch ) in pull().

**Closed as completed** 2012-07-20 23:57 UTC
