### ISSUE TITLE
document the 'vars' magic dict

### ISSUE THREAD

**Issue by halberom** [ansible/ansible#16395] opened 2016-06-22 10:08 UTC
##### ISSUE TYPE
- Documentation Report
##### ANSIBLE VERSION

Any, but currently

```
$ ansible --version
ansible 2.1.0.0
  config file =
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Unlike the magic `hostvars` dict/function, there's no mention anywhere in the documentation of the `vars` one.
##### STEPS TO REPRODUCE

N/A
##### EXPECTED RESULTS

Browsing to the playbook variables document page (or using ansible docs) and doing a search would give information on the usage of `vars`.

Currently I 'think' that it is all local variables for the immediate host.  Useful for variable interpolation such as `{{ vars[inventory_hostname + '_foo'] }}`
##### ACTUAL RESULTS

I only found out about it from an IRC comment, and I'm still a little unclear on how it differs from the `hostvars` dict.

**Comment by halberom** [comment] 2017-02-16 14:26
Is this still a valid request? the `vars` dict is extremely useful but I just found https://github.com/ansible/ansible/issues/10506 which is related (and was closed as won't do), so I'm a bit concerned a) whether i should use it and b) whether i should tell others - as i have done from time to time in irc.

**Comment by bcoca** [comment] 2017-02-16 17:47
closing as dupe of #10506

**Closed as completed by bcoca** 2017-02-16 17:47 UTC
Labels: affects_2.1, docs
