### ISSUE TITLE
unable to set an alias in the hosts file (unicode problem in line?)

### ISSUE THREAD

**Issue by davidfischer-ch** [ansible/ansible#6684] opened 2014-03-25 16:59 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6
##### Environment:

Ubuntu 13.10 amd64
##### Summary:

Ansible is unable to handle aliases that are not "real" hostnames:

```
cloudncode-ansible-0 ansible_ssh_host=10.0.3.204 ansible_ssh_user=ubuntu
```
##### Steps To Reproduce:
- Install Ansible from GitHub devel branch.
- Update hosts file with content in summary.
- Create a dummy playbook.
- Run it.
##### Expected Results:

Expected to not fail.
##### Actual Results:

```
fatal: [cloudncode-ansible-0 ansible_ssh_host=10.0.3.204 ansible_ssh_user=ubuntu] => {'msg': 'FAILED: [Errno -2] Name or service not known', 'failed': True}
```

**Comment by mpdehaan** [comment] 2014-03-25 17:31
Can you please paste your Ansible hosts file and your dummy playbook?

This should be splitting out variables on the same line without problems here, but for some reason it's not.

Seeing the whole hosts file would be helpful.

**Comment by davidfischer-ch** [comment] 2014-03-25 17:34
```
cloudncode-ansible-0 ansible_ssh_host=10.0.3.204 ansible_ssh_user=ubuntu
```

Playbook:

```
---
- hosts: all
  gather_facts: False
  sudo: True

  tasks:

    - name: Install pycurl for APT Ansible module
      pip: name=pycurl

    - name: Add FFMpeg repository to install the real FFMpeg
      apt_repository: repo=ppa:jon-severinsson/ffmpeg state=present update_cache=yes

    - name: Install the real FFMpeg
      apt: name=ffmpeg state=latest
```

**Comment by davidfischer-ch** [comment] 2014-03-25 17:40
This is the complete file :-)

**Comment by mpdehaan** [comment] 2014-03-25 17:42
Hmm, this is very odd... I'm not able to reproduce this using the latest devel branch.

We are doing a split on whitespace, is there a chance someone very sneaky stuck a unicode invisible character in there instead?

**Comment by davidfischer-ch** [comment] 2014-03-25 17:49
Unicode is not the evil, ideally unicode should be used everywhere and some unit-tests should include special characters. A lot of trouble with some Python projects only because of this. Thanks.

```
$ cat juju_local_hosts 
cloudncode-ansible-0 ansible_ssh_host=10.0.3.52 ansible_ssh_user=ubuntu
$ md5sum juju_local_hosts 
65a1a5d15c6d1caafde0973de4566280  juju_local_hosts
```

**Comment by jctanner** [comment] 2014-03-25 18:05
@davidfischer-ch what is the "od -c" output for the inventory file?

**Comment by davidfischer-ch** [comment] 2014-03-25 18:07
```
0000000   c   l   o   u   d   n   c   o   d   e   -   a   n   s   i   b
0000020   l   e   -   0       a   n   s   i   b   l   e   _   s   s   h
0000040   _   h   o   s   t   =   1   0   .   0   .   3   .   5   2    
0000060   a   n   s   i   b   l   e   _   s   s   h   _   u   s   e   r
0000100   =   u   b   u   n   t   u  \n
0000110
```

**Comment by davidfischer-ch** [comment] 2014-03-25 18:08
Please add my case to your unit-tests :-)

**Comment by mpdehaan** [comment] 2014-03-25 18:19
"Unicode is not the evil, "

Never said it was, the default split splits on whitespace, so the question was about the possibility of what the split might not be splitting on.

**Comment by davidfischer-ch** [comment] 2014-03-25 18:23
Excuse me.

**Comment by mpdehaan** [comment] 2014-03-25 19:06
Hmmm -- Unclear how to create that file using keyboard.

If you can email me your host file to michael@ansible.com we can take a look and at least understand what it's doing or not doing.

**Comment by davidfischer-ch** [comment] 2014-03-27 09:44
Hello,

Good news : I am not able to reproduce the bug with the file (I just restarted my computer this morning, ... Maybe it is time for me to cleanup it a little bit). So I wanted to go ahead and bypass the creation of a file and put the content in a variable.

I put the line (without the \n) in a variable:

```
hosts = ['cloudncode-ansible-0 ansible_ssh_host=10.0.3.52 ansible_ssh_user=ubuntu']
```

And used this variable:

```
stats = AggregateStats()
inventory = Inventory(host_list=hosts)
playbook = PlayBook(playbook='ffmpeg.yml', inventory=inventory, remote_user='ubuntu',
                    callbacks=PlaybookCallbacks(verbose=VERBOSITY), stats=stats,
                    runner_callbacks=PlaybookRunnerCallbacks(stats=stats, verbose=VERBOSITY))
playbook.run()
```

But it fails:

```
GATHERING FACTS *************************************************************** 
fatal: [cloudncode-ansible-0 ansible_ssh_host=10.0.3.158 ansible_ssh_user=ubuntu] => {'msg': 'FAILED: [Errno -2] Name or service not known', 'failed': True}
```

Am I wrong with my hosts variable ?

Thanks for your patience.

**Comment by abadger** [comment] 2015-07-07 19:43
Cleaning up old bugs as we move towards v2.  Since this isn't happening with an inventory file I'm going to close this.

The host_list parameter to Inventory can either take a filename/directoryname or a string/list of strings.  If it's strings, then the present inventory parser does not process any inventory variables.  It takes each string as a hostname.  There's this comment in the inventory/**init**.py that explains that:

``` python
        # the host file file, or script path, or list of hosts
        # if a list, inventory data will NOT be loaded
        self.host_list = host_list
```

For your use case (with the v1 tree) you'd need to utilize a temporary file.  In the v2 tree we've talked about reworking inventory.  It's not going to hit in time for 2.0, though, so the temporary file is probably the only workaround that would work there as well.

**Closed as completed by abadger** 2015-07-07 19:43 UTC
Labels: bug
