### ISSUE TITLE
Jinja2 doesn't allow to use template includes outside playbook dir

### ISSUE THREAD

**Issue by pfalcon** [ansible/ansible#7106] opened 2014-04-21 19:33 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6 (devel f1ce9abe0d) last updated 2014/04/21 21:05:18 (GMT +300)
##### Environment:

Ubuntu 12.04
##### Summary:

We have our playbook's data (group/host vars, templates, etc.) split in 2 parts: public, which goes alongside playbook, and private, which is held in completely different repo. Both repos are checkout out into a common parent dir, so from public dir, private can be accessed as ../ansible-secrets-jenkins/ . That works for accessing most data, except for templates - Jinja2 by default doesn't want to access templates with ".." in path.
##### Steps To Reproduce:

In this specific case, we have:

```
secret_dir: ../ansible-secrets-jenkins/
jenkins_ssh_publishers_file: "{{secrets_dir}}/jenkins_ssh_publishers.xml.tcwg-ci"
```

and within a template:

```
{% if jenkins_ssh_publishers_file is defined %}
{% include jenkins_ssh_publishers_file %}
{% endif %}
```
##### Expected Results:

I'd expect to be able to use template located outside playbook dir,
just as possible for var files, copy file, etc.
##### Actual Results:

With #7105 applied:

```
fatal: [tcwg.ci.linaro.org] => {'msg': 'TemplateNotFound: ../../ansible-secrets-jenkins/jenkins_ssh_publishers.xml.tcwg-ci', 'failed': True}
```

That's because:

jinja2/loaders.py:

```
def split_template_path(template):
    """Split a path into segments and perform a sanity check.  If it detects
    '..' in the path it will raise a `TemplateNotFound` error.
    """
```

**Comment by mpdehaan** [comment] 2014-04-22 02:36
Note this is just about template includes, not templates in general - I've edited the description to reflect this.

As I've mentioned before, template includes in Ansible aren't really a thing presently and need some hammering to be made to work.   (I agree it would be nice -- but not too many people use them).

**Comment by pfalcon** [comment] 2014-04-24 19:55
Ah, thanks for correction - indeed, I didn't try to reference direct template form outside a playbook dir, that indeed works. Well, per our usecase, really need to keep parts of template separate, and including subparts seems like most straightforward way. Currently working the issue around by having a symlink within playbook dir pointing to outside dir.

**Comment by rsyring** [comment] 2015-01-03 18:50
I could really use them.  There is a discussion about this here:

https://groups.google.com/forum/#!msg/ansible-project/hLBux9z4JbI/BE2lgJWNtHYJ

Since I maintain my roles separately from my playbooks too, this is a frustrating problem for me.

You wouldn't even need to undo Jinja's security settings.  All you would have to do is add a few more directory lookups to the FileSystemLoader:

https://github.com/ansible/ansible/blob/d3c9eda15b0028b4a0621f313c6ee53eef439d43/lib/ansible/utils/template.py#L215

Current code is:

``` python
loader=jinja2.FileSystemLoader([basedir,os.path.dirname(realpath)])
```

Adjusted pseudo code would be:

``` python
loader=jinja2.FileSystemLoader([
    os.path.dirname(realpath),   # directory of currently parsed template gets priority
    ansible_role_for_template(realpath),  # if the current template is in a role, return role's base path
    ansible_roles_path(),  # the root "roles" folder
    basedir,  # the playbook directory
])
```

The code may have to be a little more intelligent to determine if the template belongs to a role.

**Comment by rsyring** [comment] 2015-01-03 18:51
And, on second thought, if `ansible_role_for_template(realpath),` is holding things up, then just add the ansible_roles_path()...that would still allow the flexibility to include templates from other roles, which is probably the biggest need for this issue.

**Comment by rsyring** [comment] 2015-01-03 19:55
I have confirmed the patch in #9933 works as desired.   I can now do a jinja template include with a path like `php/templates/apache-php.j2` and all is well.

where "php" is a role.

**Comment by rsyring** [comment] 2015-01-05 23:39
Michael DeHaan said my PR is not likely to get accepted due to a preference for changes to be against the v2 codebase.  For future reference:

> v2 is not open for submissions just yet, plugins are in progress -- we anticipate this should be ready in about a month or so for helping testing and development.   There will be an analogous file in the action_plugins tree, called template.py, and be pretty similar, just a bit nicer.

**Comment by jimi-c** [comment] 2015-08-05 02:51
As this is specifically forbidden by jinja2, I'm not sure that there's much we can do about it. Users will simply need to make sure that any relative paths are below the current directory and don't use `..` in the path (as that triggers the immediate exception in the jinja2 code).

As for #9933, I've merged in a comparable fix to that PR, so paths relative to the role path should work (again, as long as they don't contain `..`, as above).

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-08-05 02:51 UTC
Labels: bug
