### ISSUE TITLE
> yaml syntax does not strip newlines

### ISSUE THREAD

**Issue by xiongchiamiov** [ansible/ansible#20993] opened 2017-02-02 22:50 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

`shell` module

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

Vanilla.

##### OS / ENVIRONMENT

N/A

##### SUMMARY

According to [the YAML syntax documentation](https://docs.ansible.com/ansible/YAMLSyntax.html), `>` can be used to input a long series of text, but won't have newlines in the result.

However, the `shell` module somehow ends up with newlines anyways, which causes syntax errors.

##### STEPS TO REPRODUCE

According to the documentation, I should be able to break up long `shell` commands onto multiple lines like this:
```yaml
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - shell: >
        false
          || true
```

However, this produces a syntax error:
```
[$]> ansible-playbook shell.yaml 
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [command] *****************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "false\n || true", "delta": "0:00:00.003198", "end": "2017-02-02 14:42:50.566188", "failed": true, "rc": 2, "start": "2017-02-02 14:42:50.562990", "stderr": "/bin/sh: 2: Syntax error: \"||\" unexpected", "stdout": "", "stdout_lines": [], "warnings": []}
        to retry, use: --limit @/home/james/temp/ansible-bugs/shell.retry

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   
```
You can see in the debug output that the command has a newline embedded in it, contrary to what the Ansible YAML syntax docs say.

If we change it to use the command module instead, we see that we no longer get a syntax error:
```yaml
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - command: >
        false
          || true
```
```
[$]> ansible-playbook shell.yaml
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [command] *****************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["false", "||", "true"], "delta": "0:00:00.003857", "end": "2017-02-02 14:45:47.881270", "failed": true, "rc": 1, "start": "2017-02-02 14:45:47.877413", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}
        to retry, use: --limit @/home/james/temp/ansible-bugs/shell.retry

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   
```
(I'm not sure why it marks it as failed, but that's a separate issue.)

We can also verify that merging the lines onto one works as expected, so it's not an issue with using the `||` construct:
```yaml
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - shell: false || true
```
```
[$]> ansible-playbook shell.yaml
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [command] *****************************************************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0   
```

##### EXPECTED RESULTS

Commands split onto multiple lines with `>` should be executed in the `shell` module without newlines.

**Comment by bcoca** [comment] 2017-02-02 22:54
command does not invoke a shell, `||` is ignored so it returns false. Use shell instead

**Comment by xiongchiamiov** [comment] 2017-02-02 22:59
> command does not invoke a shell, || is ignored so it returns false.

Ah, right, of course.  I guess the thing then is just that `>` doesn't appear to be stripping newlines.  Here's with `debug`:

```yaml
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - debug:
        msg: >
          false
            || true
```
```
[$]> ansible-playbook shell.yaml 
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "false\n  || true\n"
}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```

It's producing exactly the same thing as using `|`, even though they're supposed to be different:
```yaml
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - debug:
        msg: |
          false
            || true
```
```
[$]> ansible-playbook shell.yaml
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "false\n  || true\n"
}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```

**Comment by xiongchiamiov** [comment] 2017-02-03 00:07
> Use shell instead

Using `shell` *also* doesn't work, which is what the issue is about.  See: the first example.

**Comment by dagwieers** [comment] 2017-02-03 13:27
@xiongchiamiov You have syntax-errors, all lines have to be indented identically IMO
```yaml
- hosts: localhost
  gather_facts: no
  tasks:
  - debug:
      msg: >
        true
          || false

  - debug:
      msg: >                                                                              
        true
        || false
```
gives:
```
[dag@moria ansible.testing]$ ansible-playbook test143.yml

PLAY [localhost] *************************************************************************

TASK [debug] *****************************************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "true\n  || false\n"
}

TASK [debug] *****************************************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "true || false"
}

PLAY RECAP *******************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
```
This is IMO unrelated to Ansible. This is purely related to YAML syntax and parsing.

**Comment by bcoca** [comment] 2017-02-03 14:51
since both issues have been addressed, I'm going to close this issue as it is not a bug

**Closed as completed by bcoca** 2017-02-03 14:51 UTC
Labels: affects_2.2, module

**Comment by xiongchiamiov** [comment] 2017-02-03 18:47
Well that's pretty dumb.  Can we update https://docs.ansible.com/ansible/YAMLSyntax.html to mention that?

**Comment by dagwieers** [comment] 2017-02-04 20:36
Sure, feel free to make a PR with the changes you think would help people in this respect.
I agree that it may be confusing and may look like a genuine error to the user.

(PS You don't need to know Git to create a PR, simple browse to the file you want to modify on the GitHub website, and edit the file the way you like. Anyone can make changes that way without learning low-level Git)

Thanks in advance BTW !
