### ISSUE TITLE
Installing ansible into virtualenv fails because it wants to write to /usr/share/ansible

### ISSUE THREAD

**Issue by todd-a-jacobs** [ansible/ansible#7557] opened 2014-05-27 05:56 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

N/A. Attempting to install Ansible v1.6.2, but the point of the ticket is that the installation fails.
##### Environment:

Ubuntu Linux 14.04, with the goal of managing various Debian and Ubuntu distros...and possibly MacPorts if it's currently supported in the recent versions.
##### Summary:

This seems like a bug in the package installer, which isn't respecting the boundaries of the virtual environment. Ansible appears to insist on writing outside the virtualenv to /usr/share/ansible.
##### Steps To Reproduce:

```
$ mkvirtualenv ansible; pip install ansible
```
##### Expected Results:

I expect ansible to install within the confines of ~/.virtualenvs/ansible/ and to do so successfully.
##### Actual Results:

Ansible appears to fail when writing to /usr/share/ansible. The command listed above results in the following (trimmed) output:

```
running install_data
creating /usr/share/ansible
error: could not create '/usr/share/ansible': Permission denied
----------------------------------------
Cleaning up...
```

> Command /home/codegnome/.virtualenvs/ansible/bin/python -c "import setuptools, tokenize;**file**='/home/codegnome/.virtualenvs/ansible/build/ansible/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-zphvWt-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/codegnome/.virtualenvs/ansible/include/site/python2.7 failed with error code 1 in /home/codegnome/.virtualenvs/ansible/build/ansible
> Storing debug log for failure in /home/codegnome/.pip/pip.log

**Comment by jimi-c** [comment] 2014-05-27 14:57
This is a dupe of an issue we closed previously. The issue is that Ansible is a system tool, there are things that must be installed in /usr/bin as well as the other bits that are installed in /usr/share. At AnsibleFest, the Twitter presenter had patches for this, so we'll review those when we receive them, however we will be closing this issue for now. Please let us know if you have any further questions. Thanks!

**Closed as completed by jimi-c** 2014-05-27 14:57 UTC

**Comment by jsheffie** [comment] 2014-11-11 14:46
please link to previous issue, or list the 'other bits' that need to be in /usr/share... as google told me this is the place that holds the answer to this issue. ..Thanks...

https://github.com/ansible/ansible/issues/1410

**Comment by jimi-c** [comment] 2014-11-11 15:53
@jsheffie this should no longer be an issue, as per the module reorganization we now store the modules in the python library path and not /usr/share/ansible. This means virtualenv installs as of 1.8 should have no problems.

Thanks!
