### ISSUE TITLE
Service module not safe for chroot connections.

### ISSUE THREAD

**Issue by jhohertz** [ansible/ansible#8987] opened 2014-09-12 15:51 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

1.6.10
##### Environment:

Ubuntu 14.04 for both target and host running Ansible
##### Summary:

Using the chroot connection to use Ansible to manage images, I have discovered that the service module does not account for a chroot environment and will perform actions on the host environment.

Most notable, is when using state=stopped, as we often try to do in order to ensure the chroot is "quiet" before imaging it, it will cause the hosts daemon to be stopped.
##### Steps To Reproduce:

Have a service running on the host, and attempt to use service module to set state=stopped for a service in the context of a chroot "connection".
##### Expected Results:

That the operation will be executed with in the context of the chroot target host.
##### Actual Results:

The operation executes outside of the chroot, killing the service on the host system running Ansible.

**Comment by mscherer** [comment] 2014-09-12 17:58
Can you give a example, like the type of service that would be stopped ?

**Comment by jhohertz** [comment] 2014-09-12 20:42
Well the one that we noticed, and caused us to investigate it, was the ssh server daemon, IE:

```
- name: Stop sshd
  service: name=ssh state=stopped
```

But I have no reason to believe that it would not also affect any other service provided it was one in common to both the host and the client.

**Comment by mscherer** [comment] 2014-09-12 21:18
Can you post the complete playbook ? I am trying to reproduce but I would prefer to make sure I do not miss something.

**Comment by mscherer** [comment] 2014-09-12 21:23
Ok, i can reproduce, I will try to see why it does this.

**Comment by jhohertz** [comment] 2014-09-12 21:23
Have a look at this: https://github.com/viafoura/buri in the playbooks folder, all but the most recent commit which removes all the ssh related are affected.

It's a big hairy set of plays. I am invoking through the resnap-from-buri or resnap-from-aminator plays that this comes into play. In the former, the play goes through one section to setup the chroot, another that actually runs the main role we care about in the chroot, and then another images the chroot.

The role in question is the base_buri one here.

And I see I am a bit late to this, you've reproduced. Thanks for looking into it.

**Comment by mscherer** [comment] 2014-09-12 21:41
So, after testing on a different distribution, ie testing on Debian, I suspect strongly that's a problem with the service module and upstart who somehow leak the outside world inside the chroot. I tested with nginx, atd and acpid, and it only do that on Ubuntu.

**Comment by mscherer** [comment] 2014-09-12 22:06
Ok so yeah, the root cause is upstart. initctl inside the chroot will operate on the main upstart socket, so outside of the chroot. There isn't much we can do, and while I am not fan of saying "issue is on your side", I think the chroot module cannot offer the proper isolation, because of upstart design.

**Comment by mscherer** [comment] 2014-09-12 22:08
And upstart seems to suggest to disable initctl with a symlink https://bugs.launchpad.net/ubuntu/+source/upstart/+bug/430224

**Comment by jhohertz** [comment] 2014-09-15 12:19
Thanks for looking into this and confirming the issue. It does seem it is not a simple one to address, and just another of the things that make upstart _fun_ to work with. :frowning:

For my purposes, I will just avoid using the service module as I can call the init scripts (which exist, and upstart is just wrapping) directly where needed.

I'll let you close the item, as you'll probably want to flag it as wontfix or the like.

**Comment by jimi-c** [comment] 2014-09-15 14:47
@mscherer thanks for looking into this and tracking it down! 

Since this does seem to be an upstart issue and not directly related to Ansible, I am going to close this issue for now.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2014-09-15 14:47 UTC
