### ISSUE TITLE
--start-at-task skips tasks

### ISSUE THREAD

**Issue by darKoram** [ansible/ansible#4447] opened 2013-10-11 05:03 UTC
I found --start-at-task one of the most useful features for debugging late-in-playbook tasks.  

ansible-playbook -i hosts site.yml --start-at-task="Name of a task"

Previously this worked (though you had to take care you used the full phrase with no spelling errors").
Now, it always just skips over all tasks starting at the named task.

Has there been a change in how this feature works?

I just pulled the latest from github (oct 10th), and see the same behavior.

I can reproduce this on any task in my playbook.

kesten

**Comment by jimi-c** [comment] 2013-10-11 14:48
To be clear, this is still working for you, the only issue is that it no longer shows the skipped tasks? Otherwise, I am unable to reproduce this.

**Comment by darKoram** [comment] 2013-10-11 18:05
Prior to perhaps 2 weeks ago, the behaviour was as I wished.

ansible-playbook -i hosts site.yml --start-at-task="4th to last task of
very long playbook"

this would start at the 4th to last task (accessed by name) and then
continue chugging along to the end, executing 4 tasks.
If i mis-spelled the name, then it would fire up, but just state some tasks
and exit without executing any tasks.

Now the behavior is more like the latter.  Never executing any tasks if i
ask it to start at any task.
There was a bug closed 5 months ago regarding --start-at-task requiring
--step for --start.. to work correctly.
Doubt if there is any connection.

kesten

On Fri, Oct 11, 2013 at 9:48 AM, James Cammarata
notifications@github.comwrote:

> To be clear, this is still working for you, the only issue is that it no
> longer shows the skipped tasks? Otherwise, I am unable to reproduce this.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/issues/4447#issuecomment-26142974
> .

## 

Kesten Broughton
512 701 4209

**Comment by jimi-c** [comment] 2013-10-11 18:21
Could you please include a sample playbook that reproduces the issue? A gist or some other paste service is preferred to pasting it here.

**Comment by mpdehaan** [comment] 2013-10-19 18:35
I think this is a duplicate of #4561

Comment there if you disagree.  Thanks!

**Closed as completed by mpdehaan** 2013-10-19 18:35 UTC
Labels: needs_info, bug
