### ISSUE TITLE
with_fileglob not working with glob in path / absolute path

### ISSUE THREAD

**Issue by h0nIg** [ansible/ansible#17907] opened 2016-10-05 11:38 UTC
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

with_fileglob lookup
##### ANSIBLE VERSION

2.2.0 rc1
on 2.0 / 2.1 it works
##### CONFIGURATION

nothing changed
##### OS / ENVIRONMENT

ubuntu 14.04
##### SUMMARY

with_fileglob lookup does not work with glob in path / absolute path
##### STEPS TO REPRODUCE

```
  tasks:
    - debug: msg="{{ item }}"
      with_fileglob:
        - /tmp/testglob/UnlimitedJCEPolicy*/US_export_policy.jar
        - /tmp/testglob/UnlimitedJCEPolicy*/local_policy.jar
```
##### EXPECTED RESULTS

with_fileglob should respect glob in path / absolute path
##### ACTUAL RESULTS

`[WARNING]: Unable to find '/tmp/testglob/UnlimitedJCEPolicy*' in expected paths.`

**Comment by h0nIg** [comment] 2016-10-14 12:05
ping @bcoca since you changed this with 3c39bb5633d0cbfa9cf22f9a4038296caef9c622

**Comment by h0nIg** [comment] 2016-10-14 12:07
may be related:
https://github.com/ansible/ansible/issues/17269
https://github.com/ansible/ansible/issues/17136

**Comment by bcoca** [comment] 2016-10-14 13:23
closing as dupe of #17136

**Closed as completed by bcoca** 2016-10-14 13:23 UTC
Labels: affects_2.2, bug
