### ISSUE TITLE
Create a filter_plugins library path

### ISSUE THREAD

**Issue by bcavns01** [ansible/ansible#45865] opened 2018-09-19 19:25 UTC
##### SUMMARY

The ability to load custom python libraries for use in filters by placing them into some local ansible path, preferably `filter_plugins/library`.

##### ISSUE TYPE
- Feature Idea
The `filter_plugins` path could have a subdirectory called `library` where you could put your custom libraries.

##### COMPONENT NAME

filter_plugins_library

##### ADDITIONAL INFORMATION

This would allow ansible users to import custom python libraries without having to install them into their python path.  The functionality would be similar to that of the `module_utils` directory.

This would see to also take care of https://github.com/ansible/ansible/issues/27748 because you'd have the option of symlinking things in from module_utils if you needed/wanted to.

**Comment by sivel** [comment] 2018-09-19 19:51
Duplicate of https://github.com/ansible/ansible/issues/28770

**Closed as completed by sivel** 2018-09-19 19:51 UTC
