### ISSUE TITLE
group_vars and host_vars undefined after upgrade from 2.1.0 to 2.1.1

### ISSUE THREAD

**Issue by maximsnezhkov** [ansible/ansible#16927] opened 2016-08-03 02:44 UTC
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
##### CONFIGURATION

custom role_path
##### OS / ENVIRONMENT

Ubuntu 12.04
##### SUMMARY

After upgrade from 2.1.0 to 2.1.1 cannot use group_vars and host_vars in role's defined playbook
##### STEPS TO REPRODUCE

$ ansible-playbook -i hosts playbooks/playbook.yml 
Enter hosts for playbook run: test_group

PLAY [Test playbook] ***********************************************************

TASK [setup] *******************************************************************
ok: [10.10.10.5]
ok: [10.10.10.6]

TASK [common-aliases : set alias] **********************************************
fatal: [10.10.10.5]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'root_mail_aliase' is undefined\n\nThe error appears to have been in '/home/snow/Documents/scripts/ansible/roles/common-aliases/tasks/main.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: set alias\n  ^ here\n"}
fatal: [10.10.10.6]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'root_mail_aliase' is undefined\n\nThe error appears to have been in '/home/snow/Documents/scripts/ansible/roles/common-aliases/tasks/main.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: set alias\n  ^ here\n"}

```
$ cat playbook.yml

---
- name: Test playbook
  hosts: "{{ hosts }}"
  user: root
  gather_facts: True
  vars_prompt:
    - name: hosts
      prompt: "Enter hosts for playbook run"
      private: no


  roles:
#check host_vars/ before run
#check group_vars/ before run
      - common-aliases

$ cat group_vars/test_group
root_mail_aliase: "admins@example.com"

$ cat /home/snow/Documents/scripts/ansible/roles/common-aliases/tasks/main.yml

---
- name: set alias
  lineinfile: "dest=/etc/aliases insertafter='^#root:' line='root:       {{ root_mail_aliase }}'"
```
##### EXPECTED RESULTS

Variable root_mail_aliase can be accessible from task
##### ACTUAL RESULTS

Running the playbook leads to the error above

**Comment by kuboj** [comment] 2016-08-03 08:04
As this affects me too, I just want to mention that this happens when the playbook is executed from subdirectory - e.g. `ansible-playbook playbook.yml` resolves group and host vars without problems, but something like `ansible-playbook subdir/playbook.yml` causes problems with undefined variables.

**Comment by maximsnezhkov** [comment] 2016-08-03 08:21
```
$ ansible-playbook -i ../../hosts/nginx playbook.yml
Enter hosts for playbook run: test_group

PLAY [Test playbook] ***********************************************************

TASK [setup] *******************************************************************
ok: [10.10.10.5]
ok: [10.10.10.6]
TASK [common-aliases : set alias] **********************************************
fatal: [172.20.16.194]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'root_mail_aliase' is undefined\n\nThe error appears to have been in '/home/snow/Documents/scripts/ansible/roles/common-aliases/tasks/main.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: set alias\n  ^ here\n"}
fatal: [172.20.16.197]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'root_mail_aliase' is undefined\n\nThe error appears to have been in '/home/snow/Documents/scripts/ansible/roles/common-aliases/tasks/main.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: set alias\n  ^ here\n"}


```

**Comment by bcoca** [comment] 2016-08-03 14:11
duplicate of #16878

**Closed as completed by bcoca** 2016-08-03 14:11 UTC

**Comment by caDevOps** [comment] 2016-08-26 15:43
Ditto for me.  :/
