### ISSUE TITLE
pre_tasks not working while gathering=smart in ansible.cfg

### ISSUE THREAD

**Issue by marcinhlybin** [ansible/ansible#14243] opened 2016-02-01 15:55 UTC
**Issue Type:**
Bug report

**Ansible Version:**

```
ansible 2.1.0 (devel 45e05ec072) last updated 2016/02/01 14:17:33 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 88e0bfd75d) last updated 2015/11/20 12:34:36 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 7da1f8d4ca) last updated 2015/11/20 12:34:44 (GMT +200)
  config file = ansible.cfg
  configured module search path = Default w/o overrides
```

**Ansible Configuration:**

```
[defaults]
gathering = smart
```

**Environment:**
Mac OS X

**Summary:**
When `gathering=smart` used in ansible.cfg pre_tasks are not running.

**Steps To Reproduce:**

ansible.cfg:

```
[defaults]
gathering = smart
```

play.yml:

```

---
- hosts: localhost

  pre_tasks:
    - name: pre_task
      shell: echo 'hello'

  tasks:
    - name: task
      shell: echo 'still busy'

  post_tasks:
    - name: post_task
      shell: echo 'goodbye'
```

**Expected Results:**

```
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [pre_task] ****************************************************************
changed: [localhost]

TASK [task] ********************************************************************
changed: [localhost]

TASK [post_task] ***************************************************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=3    unreachable=0    failed=0
```

**Actual Results:**

```
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [task] ********************************************************************
changed: [localhost]

TASK [post_task] ***************************************************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=0
```

**Comment by bcoca** [comment] 2016-02-01 16:01
checked, it only removes the 1st pre task and only if gather_facts is true for that play.
play.yml

```
---
- hosts: localhost
  #gather_facts: False
  pre_tasks:
    - debug: msg='i AM PRE'
    - debug: msg='i AM PRE2'
  tasks:
    - debug: msg='main task'
```

**Comment by jimi-c** [comment] 2016-02-02 13:07
This appears to be a bug in the linear strategy caused by the smart gathering mode only (explicit/implicit are unaffected). Looking into it further.

**Comment by jimi-c** [comment] 2016-02-02 15:23
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2016-02-02 15:23 UTC
Labels: P2, bug
