### ISSUE TITLE
being able to do includes in templates

### ISSUE THREAD

**Issue by kleinth328** [ansible/ansible#7015] opened 2014-04-16 08:57 UTC
##### Steps To Reproduce:

In one template file i have this code snippet:
{% for group in group_names %}
    {% include "debug_include.j2" with context %}
{% endfor %}

In the included template 'debug_include.j2' i have this code:
This is the included Template. The current group is {{group}}

The documentation claims that included templates have the same variable context as the main file.
So i would expect to see something like:
This is the included Template. The current group is mailserver
##### Expected Results:

I would expect to see something like:
This is the included Template. The current group is mailserver
##### Actual Results:

Instead i get an error on the commandline when executing this play:
TASK: [common-linux | dump all variables] *************************************
fatal: [ltesthost] => {'msg': "One or more undefined variables: 'group' is undefined", 'failed': True}
fatal: [testhost] => {'msg': "One or more undefined variables: 'group' is undefined", 'failed': True}

FATAL: all hosts have already failed -- aborting

**Comment by jimi-c** [comment] 2014-04-16 14:48
This appears to be a duplicate of #6653, so we'll close this and track the issue there. Thanks!

**Closed as completed by jimi-c** 2014-04-16 14:48 UTC
Labels: P2, bug
