### ISSUE TITLE
ansible-galaxy should not remove galaxy.yml from installed collections

### ISSUE THREAD

**Issue by eengstrom** [ansible/ansible#74771] opened 2021-05-19 20:11 UTC
### Summary

When installing collections via `ansbile-galaxy`, it appears as if the `galaxy.yml` is removed or otherwise not kept during the build/install process.  Having that file remain in the directory seems useful, and I don't see a downside to leaving it in place.  

### Issue Type

Bug Report

### Component Name

ansible-galaxy

### Ansible Version

```console
$ ansible --version
ansible 2.10.9
  config file = None
  configured module search path = ['/PATH/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /PATH/ansible/.venv/lib/python3.9/site-packages/ansible
  executable location = /PATH/ansible/.venv/bin/ansible
  python version = 3.9.5 (default, May  4 2021, 03:33:11) [Clang 12.0.0 (clang-1200.0.32.29)]
```

### Configuration

```console
$ ansible-config dump --only-changed
ANSIBLE_PIPELINING(PATH/ansible/ansible.cfg) = True
CACHE_PLUGIN(PATH/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(PATH/ansible/ansible.cfg) = ./facts
CACHE_PLUGIN_TIMEOUT(PATH/ansible/ansible.cfg) = 7200
COLLECTIONS_PATHS(PATH/ansible/ansible.cfg) = ['PATH/ansible/dev/collections', 'PATH/ansible/collections']
CONDITIONAL_BARE_VARS(PATH/ansible/ansible.cfg) = False
DEFAULT_FORKS(PATH/ansible/ansible.cfg) = 50
DEFAULT_GATHERING(PATH/ansible/ansible.cfg) = smart
DEFAULT_HOST_LIST(PATH/ansible/ansible.cfg) = ['PATH/ansible/inventory', 'PATH/ansible/config/constructed-inventory.yml']
DEFAULT_ROLES_PATH(PATH/ansible/ansible.cfg) = ['PATH/ansible/dev/roles', 'PATH/ansible/roles']
DEFAULT_VAULT_PASSWORD_FILE(PATH/ansible/ansible.cfg) = PATH/ansible/scripts/vault-keyring.py
INTERPRETER_PYTHON(PATH/ansible/ansible.cfg) = auto
INVENTORY_ENABLED(PATH/ansible/ansible.cfg) = ['ini', 'yaml', 'constructed', 'auto']
RETRY_FILES_ENABLED(PATH/ansible/ansible.cfg) = False
TRANSFORM_INVALID_GROUP_CHARS(PATH/ansible/ansible.cfg) = ignore
USE_PERSISTENT_CONNECTIONS(PATH/ansible/ansible.cfg) = True
```

### OS / Environment

% uname -a 
Darwin HOST 19.6.0 Darwin Kernel Version 19.6.0: Mon Apr 12 20:57:45 PDT 2021; root:xnu-6153.141.28.1~1/RELEASE_X86_64 x86_64 i386 MacBookPro16,1 Darwin

### Steps to Reproduce

```bash
% ansible-galaxy collection install  amazon.aws  
Starting galaxy collection install process
Process install dependency map
Starting collection install process
Installing 'amazon.aws:1.5.0' to '/PATH/ansible/dev/collections/ansible_collections/amazon/aws'
Downloading https://galaxy.ansible.com/download/amazon-aws-1.5.0.tar.gz to /PATH/.ansible/tmp/ansible-local-3885383h4cl9o/tmphx62usq_
amazon.aws (1.5.0) was installed successfully
% ls dev/collections/ansible_collections/amazon/aws/galaxy.yml 
ls: cannot access 'dev/collections/ansible_collections/amazon/aws/galaxy.yml': No such file or directory
```

### Expected Results

I would expect to be able to find the `galaxy.yml` file

### Actual Results

```console
no such file
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by sivel** [comment] 2021-05-19 20:16
`galaxy.yml` doesn't actually exist in the collection artifact.  It's only used at build time to create the `MANIFEST.json` file, and is not included, and thus not installed.

Duplicate of https://github.com/ansible/ansible/issues/68383

**Closed as completed by sivel** 2021-05-19 20:16 UTC
