### ISSUE TITLE
Yum module and with_items

### ISSUE THREAD

**Issue by linuskendall** [ansible/ansible#10276] opened 2015-02-18 12:18 UTC
_Issue Type:_

Bug Report

_Ansible Version:_

Tested on both latest Git version as well as Ansible 1.8.3

_Environment:_

Deploying from Mac OS X (Python 2.7.6)
Deploying to CentOS 6.5 (Python 2.6.6)

_Summary:_

When using the yum module with with_items in the latest version, state="present" seems to be included as part of the package name list. 

_Steps To Reproduce:_

Run the following task

``` yaml
- name: ensure postfix is installed
  yum: name={{ item }} state=present
  with_items:
    - postfix
    - cyrus-sasl
    - cyrus-sasl-lib
    - cyrus-sasl-plain
  when: ansible_os_family == "RedHat"
```

Have tested surrounding {{ item }} with single and double quotes.  The only work around which I've found to work is using the alternative syntax:

``` yaml
   yum: 
     name: "{{ item }}"
     state: present
```

_Expected Results:_

The four packages should be installed without the need for using alternate syntax. 

_Actual Results:_

```
failed: [107.170.116.184] => (item=postfix,cyrus-sasl,cyrus-sasl-lib,cyrus-sasl-plain) => {"changed": false, "failed": true, "item": "postfix,cyrus-sasl,cyrus-sasl-lib,cyrus-sasl-plain", "rc": 0, "results": ["postfix-2.6.6-6.el6_5.x86_64 providing postfix is already installed", "cyrus-sasl-2.1.23-15.el6_6.1.x86_64 providing cyrus-sasl is already installed", "cyrus-sasl-lib-2.1.23-15.el6_6.1.x86_64 providing cyrus-sasl-lib is already installed"]}
msg: No Package matching 'cyrus-sasl-plain state=present' found available, installed or updated
```

**Comment by Jmainguy** [comment] 2015-02-21 19:12
Unable to reproduce.

Using latest copy from git
Deploying from Centos7
Deploying to Centos6

```
---

- name: Install stuff with yum
  yum: name={{ item }} state=present
  with_items:
    - httpd
    - mysql-server
    - ruby


[root@phy01 tmp]# ansible-playbook -i hosts test.yml 

PLAY [Install stuff] ********************************************************** 

GATHERING FACTS *************************************************************** 
ok: [ca.soh.re]

TASK: [test | Install stuff with yum] ***************************************** 
changed: [ca.soh.re] => (item=httpd,mysql-server,ruby)

PLAY RECAP ******************************************************************** 
ca.soh.re                  : ok=2    changed=1    unreachable=0    failed=0   

[root@phy01 tmp]# ansible-playbook -i hosts test.yml 

PLAY [Install stuff] ********************************************************** 

GATHERING FACTS *************************************************************** 
ok: [ca.soh.re]

TASK: [test | Install stuff with yum] ***************************************** 
ok: [ca.soh.re] => (item=httpd,mysql-server,ruby)

PLAY RECAP ******************************************************************** 
ca.soh.re                  : ok=2    changed=0    unreachable=0    failed=0   
```

**Comment by sysadmin75** [comment] 2015-02-21 22:15
I'm not able to reproduce either.

ansible 1.8.2 and 1.8.3

Deploying from Mac OSX 10.9.5 (python 2.7.5)
Deploying to Centos 6.6 (python 2.6.6)

**Comment by bcoca** [comment] 2015-02-23 15:31
I'm also not able to reproduce, @linuskendall I'm closing this for now, if you have more information on how to reproduce this please let us know and we will reopen the issue.

**Closed as completed by bcoca** 2015-02-23 15:31 UTC
Labels: P2, bug, packaging

**Comment by linuskendall** [comment] 2015-02-23 16:10
Thanks for looking into it. I wonder if there might have been a file encoding issue in the playbook file, as I recreated it and now I am not able to reproduce it any more.
