### ISSUE TITLE
docker: image parameter does not support images from a local registry

### ISSUE THREAD

**Issue by ludovicc** [ansible/ansible#8000] opened 2014-07-01 10:28 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.5
##### Environment:

Ubuntu 14.04
Docker 1.0.1
##### Summary:

I'm trying to launch a Docker container from a playbook. The container name uses a URL pointing to a local registry.
##### Steps To Reproduce:

I'm using this command:

```
local_action:
  module: docker
  name: ks-archiver-store
  image: "internal_registry.localdomain:5000/store"
  ports: "29200:9200,29300:9300"
  volumes: "/var/logs/store:/data/store/logs"
```
##### Expected Results:

Container internal_registry.localdomain:5000/store should be up and running, with its ports and volumes mapped
##### Actual Results:

Ansible fails with this stack trace:

failed: [localhost] => {"failed": true, "parsed": false}
invalid output was: SUDO-SUCCESS-ooibeoxgrrqtxfypdgvqnrzdftzyssvc
Traceback (most recent call last):
  File "/home/ludo/.ansible/tmp/ansible-tmp-1404209494.7-244300550568170/docker", line 1971, in <module>
    main()
  File "/home/ludo/.ansible/tmp/ansible-tmp-1404209494.7-244300550568170/docker", line 680, in main
    running_containers = manager.get_running_containers()
  File "/home/ludo/.ansible/tmp/ansible-tmp-1404209494.7-244300550568170/docker", line 528, in get_running_containers
    for i in self.get_deployed_containers():
  File "/home/ludo/.ansible/tmp/ansible-tmp-1404209494.7-244300550568170/docker", line 507, in get_deployed_containers
    running_image, running_tag = self.get_split_image_tag(i['Image'])
  File "/home/ludo/.ansible/tmp/ansible-tmp-1404209494.7-244300550568170/docker", line 457, in get_split_image_tag
    if '/' in image:
TypeError: argument of type 'int' is not iterable

**Comment by rubycut** [comment] 2014-07-19 21:10
+1 I get same error on latest ansible 1.6.6 and latest docker 1.1.1

**Comment by rubycut** [comment] 2014-07-19 22:23
This is nasty one, container ids are usually mixtures of letters and numbers, for example: 963c78ea4ea8

But in rare cases, image id is all numbers, and it that case python doesn't recognize it as string, rather as int and this message pops up, so it has really nothing to do with local repositories, they work fine.

**Comment by arruda** [comment] 2014-07-21 04:37
@rubycut  not sure that the image id is the problem... I'm having the same problem here and the local image Id is 114144d3c2d2

**Comment by rubycut** [comment] 2014-07-21 05:06
Any container can be problem you can find it with

```
docker ps -a
```

**Comment by arruda** [comment] 2014-07-21 21:12
Hummm.. I see, thanks @rubycut =)

**Comment by jimi-c** [comment] 2014-08-12 18:08
# Closing This Ticket

Hi!

We believe recent commits to he devel branch have resolved this problem for you. Testing with the following playbook does not reproduce the issue above:

<pre>
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - docker:
      state: present
      name: test_8000
      image: "localhost:5000/ubuntu"
      ports: "29200:9200,29300:9300"
      command: "/bin/bash"
      detach: yes
</pre>

This will be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2014-08-12 18:08 UTC
Labels: cloud, P2, docker, bug
