### ISSUE TITLE
Templating error in registered stdout

### ISSUE THREAD

**Issue by keithbentrup** [ansible/ansible#10396] opened 2015-03-06 00:33 UTC
I believe there's an ansible parsing error in this shell task that then leads to a template error. 

Here's a sample playbook, test.yml, that I ran against a host with docker installed. `ansible-playbook test.yml -e hosts=dockerhost -v`

```

---
# test.yml
- name: Simple test  
  hosts: "{{ hosts }}"
  gather_facts: no
  sudo: true
  tasks:
    - name: remove previous container if it exists
      command: docker rm -f busybox-container
      ignore_errors: yes
    - name: run simple docker container
      command: docker run -di --name=busybox-container busybox:latest
    - name: get image name
      shell: docker inspect --format="{{'{{.Config.Image}}'}}" busybox-container
      #shell:  docker ps -a | grep busybox | awk '{print $2}'
      register: image_name
    - name: print debug
      debug: msg={{ image_name.stdout }}
```

Compare the output of the shell task "get image name" using `docker inspect` (which uses a go template similar to jinja2 syntax and therefore must be escaped) to the shell task that parses the same value through a series of shell commands. The stdout value is the same for each shell, but the debug task fails for `docker inpect` but not the other.
![tmp](https://cloud.githubusercontent.com/assets/253579/6517942/5edd8b70-c36e-11e4-89e6-0e06a90d3458.png)

**Comment by jimi-c** [comment] 2015-07-05 03:41
Hi @keithbentrup, I believe this is a duplicate of #10156, which has since been resolved and no longer appears to be an issue in the current devel branch, so I'm going to go ahead and close this issue as well.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-07-05 03:41 UTC
Labels: bug
