### ISSUE TITLE
azure_rm_cdnprofile CdnClientManagement is not defined when auth_source: msi

### ISSUE THREAD

**Issue by JohnnyRacket** [ansible/ansible#51751] opened 2019-02-05 16:20 UTC
##### SUMMARY
When creating a cdn profile using azure_rm_cdnprofile and using an azure vm with a managed service identity, the azure_rm_cdnprofile fails with `NameError: name 'CdnManagementClient' is not defined`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_cdnprofile

##### ANSIBLE VERSION
```paste below
devel
```

##### CONFIGURATION

```paste below
no output
```

##### OS / ENVIRONMENT
Red Hat Enterprise Linux Server release 7.5 (Maipo)

##### STEPS TO REPRODUCE
1. Create an azure linux vm
2. Give it an MSI
3. Run a playbook on in with the azure_rm_cdnprofile module

```yaml
---
- hosts: localhost

  tasks:
    - name: Create resource group for the 
      azure_rm_resourcegroup:
        auth_source: msi
        name: "{{ app_name + '-storage-rg' }}"
        location: "{{ location }}"

    - name: create an account
      azure_rm_storageaccount:
        auth_source: msi
        resource_group: "{{ app_name + '-storage-rg' }}"
        name: "{{ app_name + 'storage' }}"
        type: Standard_LRS
        kind: StorageV2

    - name: Create a CDN profile to host our static site
      azure_rm_cdnprofile:
        auth_source: msi
        resource_group: "{{ app_name + '-storage-rg' }}"
        name: "{{ app_name + '-cdn-profile' }}"
        sku: standard_microsoft
          
    - name: Create a Azure CDN endpoint
      azure_rm_cdnendpoint:
        auth_source: msi
        resource_group: "{{ app_name + '-storage-rg' }}"
        name: "{{ app_name + '-cdn-endpoint' }}"
        profile_name: "{{ app_name + '-cdn-profile' }}"
        origins:
          - name: "{{ app_name + '-storage-origin' }}"
            host_name: "{{'https://' + app_name + 'storage.z21.web.core.windows.net/' }}"
```

##### EXPECTED RESULTS

A CDN profile to be created in azure

##### ACTUAL RESULTS

```paste below
The full traceback is:
2019-02-05T15:02:25.2872123Z Traceback (most recent call last):
2019-02-05T15:02:25.2872633Z   File "/home/***/.ansible/tmp/ansible-tmp-1549378944.0326262-266537741592028/AnsiballZ_azure_rm_cdnprofile.py", line 113, in <module>
2019-02-05T15:02:25.2873066Z     _ansiballz_main()
2019-02-05T15:02:25.2873485Z   File "/home/***/.ansible/tmp/ansible-tmp-1549378944.0326262-266537741592028/AnsiballZ_azure_rm_cdnprofile.py", line 105, in _ansiballz_main
2019-02-05T15:02:25.2873913Z     invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
2019-02-05T15:02:25.2874361Z   File "/home/***/.ansible/tmp/ansible-tmp-1549378944.0326262-266537741592028/AnsiballZ_azure_rm_cdnprofile.py", line 48, in invoke_module
2019-02-05T15:02:25.2874804Z     imp.load_module('__main__', mod, module, MOD_DESC)
2019-02-05T15:02:25.2875195Z   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/imp.py", line 235, in load_module
2019-02-05T15:02:25.2875612Z     return load_source(name, filename, file)
2019-02-05T15:02:25.2876016Z   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/imp.py", line 170, in load_source
2019-02-05T15:02:25.2876640Z     module = _exec(spec, sys.modules[name])
2019-02-05T15:02:25.2877098Z   File "<frozen importlib._bootstrap>", line 618, in _exec
2019-02-05T15:02:25.2877646Z   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
2019-02-05T15:02:25.2878534Z   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2019-02-05T15:02:25.2879000Z   File "/tmp/ansible_azure_rm_cdnprofile_payload_qvoc32i8/__main__.py", line 304, in <module>
2019-02-05T15:02:25.2879440Z   File "/tmp/ansible_azure_rm_cdnprofile_payload_qvoc32i8/__main__.py", line 300, in main
2019-02-05T15:02:25.2879913Z   File "/tmp/ansible_azure_rm_cdnprofile_payload_qvoc32i8/__main__.py", line 152, in __init__
2019-02-05T15:02:25.2880389Z   File "/tmp/ansible_azure_rm_cdnprofile_payload_qvoc32i8/ansible_azure_rm_cdnprofile_payload.zip/ansible/module_utils/azure_rm_common.py", line 310, in __init__
2019-02-05T15:02:25.2881222Z   File "/tmp/ansible_azure_rm_cdnprofile_payload_qvoc32i8/__main__.py", line 160, in exec_module
2019-02-05T15:02:25.2881863Z   File "/tmp/ansible_azure_rm_cdnprofile_payload_qvoc32i8/__main__.py", line 292, in get_cdn_client
2019-02-05T15:02:25.2882297Z NameError: name 'CdnManagementClient' is not defined
2019-02-05T15:02:25.2882674Z fatal: [localhost]: FAILED! => {
2019-02-05T15:02:25.2883095Z     "changed": false,
2019-02-05T15:02:25.2884277Z     "module_stderr": "Traceback (most recent call last):\n  File \"/home/***/.ansible/tmp/ansible-tmp-1549378944.0326262-266537741592028/AnsiballZ_azure_rm_cdnprofile.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/home/***/.ansible/tmp/ansible-tmp-1549378944.0326262-266537741592028/AnsiballZ_azure_rm_cdnprofile.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/***/.ansible/tmp/ansible-tmp-1549378944.0326262-266537741592028/AnsiballZ_azure_rm_cdnprofile.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/imp.py\", line 235, in load_module\n    return load_source(name, filename, file)\n  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/imp.py\", line 170, in load_source\n    module = _exec(spec, sys.modules[name])\n  File \"<frozen importlib._bootstrap>\", line 618, in _exec\n  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/tmp/ansible_azure_rm_cdnprofile_payload_qvoc32i8/__main__.py\", line 304, in <module>\n  File \"/tmp/ansible_azure_rm_cdnprofile_payload_qvoc32i8/__main__.py\", line 300, in main\n  File \"/tmp/ansible_azure_rm_cdnprofile_payload_qvoc32i8/__main__.py\", line 152, in __init__\n  File \"/tmp/ansible_azure_rm_cdnprofile_payload_qvoc32i8/ansible_azure_rm_cdnprofile_payload.zip/ansible/module_utils/azure_rm_common.py\", line 310, in __init__\n  File \"/tmp/ansible_azure_rm_cdnprofile_payload_qvoc32i8/__main__.py\", line 160, in exec_module\n  File \"/tmp/ansible_azure_rm_cdnprofile_payload_qvoc32i8/__main__.py\", line 292, in get_cdn_client\nNameError: name 'CdnManagementClient' is not defined\n",
2019-02-05T15:02:25.2886364Z     "module_stdout": "",
2019-02-05T15:02:25.2886814Z     "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
2019-02-05T15:02:25.2887231Z     "rc": 1
2019-02-05T15:02:25.2887601Z }
2019-02-05T15:02:25.2888556Z 
2019-02-05T15:02:25.2889044Z 	to retry, use: --limit @/tmp/drop/ansible.retry
```

**Comment by Fred-sun** [comment] 2019-02-12 13:34
@JohnnyRacket Thanks for your reproting this issue! I will try to copy and find the cause of the problem. Thanks!

**Comment by Fred-sun** [comment] 2019-02-14 05:49
@zikalino  Could you help take a look this when you're available? Thanks!

**Comment by Fred-sun** [comment] 2019-02-26 07:24
@yungezz

**Comment by yungezz** [comment] 2019-02-27 08:17
Hi @JohnnyRacket do you have dependency package `azure-mgmt-cdn==3.0.0` in `requirements-azure` installed? could you pls give it a try?

**Comment by yungezz** [comment] 2019-03-11 07:52
hello @JohnnyRacket  could you pls try above suggestion https://github.com/ansible/ansible/issues/51751#issuecomment-467766586 to see if your issue resolved?

**Comment by yungezz** [comment] 2019-03-21 06:54
ping for update

**Comment by Fred-sun** [comment] 2019-03-25 10:04
@JohnnyRacket Are you still here? could you can give a try according by above comments? Thanks!

**Comment by yuwzho** [comment] 2019-03-26 03:07
@JohnnyRacket This error message shows the required CDN SDK library is missing. When installing the devel branch, [this requirement.txt](https://github.com/ansible/ansible/blob/devel/packaging/requirements/requirements-azure.txt) is also required. Please download this file and run `pip install -r requirements-azure.txt` to install required Azure libraries if there is any library missing.

**Comment by Fred-sun** [comment] 2019-04-02 02:57
kindly ping

**Comment by JohnnyRacket** [comment] 2019-04-09 14:14
Sorry for delay, let me try this and get back to you

**Comment by Fred-sun** [comment] 2019-04-16 06:19
@JohnnyRacket Thanks for your try, Could you help share your test result? Thanks!

**Comment by Fred-sun** [comment] 2019-04-22 06:01
kindly ping

**Comment by Fred-sun** [comment] 2019-05-06 02:59
@JohnnyRacket Are you still here? Could you help share your test result? Thanks a lot!

**Comment by yuwzho** [comment] 2019-05-16 05:25
close_me

Close this, feel free to reopen it if still have problem

**Closed as completed** 2019-05-16 05:38 UTC
Labels: cloud, azure, python3, module, support:community, bug, traceback, affects_2.8
