### ISSUE TITLE
Add option to automatically redact Vault-sourced variables from logging output

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#41613] opened 2018-06-15 23:07 UTC
##### SUMMARY
Add an option to automatically redact from Ansible playbook output the values of variables that originate from a Vault-encrypted file

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
core

##### ANSIBLE VERSION
```
ansible 2.5.4
  config file = None
  configured module search path = [u'/home/jollis/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION
Stock

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
This change will allow control of logging at the variable level without relying exclusively on `no_log`, and promote better security by moving the protection of the value closer to the source, rather than requiring setting at every instance of a use of the value.

**Comment by sivel** [comment] 2018-06-18 18:38
Duplicate of https://github.com/ansible/ansible/issues/41371

**Closed as completed by sivel** 2018-06-18 18:38 UTC
Labels: support:core, affects_2.5, feature
