### ISSUE TITLE
Subversion module doesn't properly handle file names with accentuated / non-ascii characters

### ISSUE THREAD

**Issue by siboulet** [ansible/ansible#6737] opened 2014-03-27 21:48 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6
##### Environment:

CentOS 5.8
##### Summary:

The subversion module doesn't properly handle file names with accentuated / non-ascii characters.

This bug appears to have been introduced by the use of LANG=C in #5626.

Maybe we should be using LANG=en_US.UTF-8 (or any UTF-8 encoding) instead.

I can confirm using LANG=en_US.UTF-8 here does appear to fix the issue.
##### Steps To Reproduce:
- Add file with accentuated characters to SVN
- Try to run subversion task
##### Expected Results:

Should work.
##### Actual Results:

```
failed: [***] => {"cmd": "/usr/bin/svn --non-interactive --trust-server-cert --no-auth-cache --username *** --password ******** status ***", "failed": true, "rc": 1}
stderr: svn: Error converting entry in directory '***/Images' to UTF-8
svn: Can't convert string from native encoding to 'UTF-8':
svn: TERRASSE SOIR?\195?\137E 2.jpg
```

**Comment by mpdehaan** [comment] 2014-03-27 22:22
Yay, conflicting fixes :)

**Comment by siboulet** [comment] 2014-03-27 22:26
How about getting rid of the need for specifying the locale and using the system default instead? The initial problem in #5626 was the regexp that matches the "svn info" output to parse the Revision. I was thinking of using "svn info --xml" which output the information in computer readable locale-independent format.

**Comment by mpdehaan** [comment] 2014-03-27 22:41
Using that sounds reasonable.  Does it have a JSON option?

**Comment by siboulet** [comment] 2014-03-28 00:23
Please review and let me know what you think.

**Comment by siboulet** [comment] 2014-03-28 01:47
Oh, hold on here.

Ansible is overriding the default locale to be "C" (at lib/ansible/module_utils/basic.py:191). It appears there is an "hidden" module_lang config parameters to place in ansible.cfg.

So, the above patch is needed + setting module_lang=en_US.UTF-8 in ansible.cfg.

**Comment by jimi-c** [comment] 2014-04-22 05:49
The above patch should resolve this issue for you, and will be included in the next major release. If you continue to see any further problems related to this issue, or if you have any further questions, please let us know. Thanks!

**Closed as completed** 2014-04-22 05:48 UTC
Labels: needs_info, P2, bug

**Comment by wangdepeng** [comment] 2016-07-07 03:27
Hi @siboulet, I am trying to pull some code from svn. But the svn path contains chinese characters. 
The error message looks like this:
svn: E000022: Can't convert string from native encoding to 'UTF-8':\n

ansible --version
ansible 2.1.0.0

Tried to set LANG and LC_CTYPE, but still did not work.

**Comment by chui101** [comment] 2016-07-20 13:20
@wangdepeng this seems to be a new bug in the subversion module: https://github.com/ansible/ansible-modules-core/issues/4178

**Comment by jimi-c** [comment] 2016-07-20 14:17
Yes, if this is a new issue please open a new bug report for it on ansible/ansible-modules-core

Thanks!

**Comment by jimi-c** [comment] 2016-07-20 14:17
Disregard my previous (deleted) comment, I see the issue is already linked from the comment above.

Thanks!

**Comment by tearsakura** [comment] 2016-09-23 08:05
Hi, I have this error on this system

```
FROM alpine:3.4

RUN echo "===> Installing sudo to emulate normal OS behavior..."  && \
    apk --update add sudo                                         && \
    \
    \
    echo "===> Adding Python runtime..."  && \
    apk --update add python py-pip openssl ca-certificates    && \
    apk --update add --virtual build-dependencies \
                python-dev libffi-dev openssl-dev build-base  && \
    pip install --upgrade pip cffi                            && \
    \
    \
    echo "===> Installing Ansible..."  && \
    pip install ansible==2.1.1               && \
    \
    \
    echo "===> Removing package list..."  && \
    apk del build-dependencies            && \
    rm -rf /var/cache/apk/*

RUN apk --update add sshpass openssh

```

With ansible 2.1.1

I tried this:

```
- name: SVN checkout
  environment:
    LC_ALL: en_US.UTF-8
    LC_CTYPE: en_US.UTF-8
  subversion: repo="{{ svn_base }}/{{ item }}"
         username="{{ svn_user }}"
         password="{{ svn_pass }}"
         dest="/tmp/kkk/{{ item }}"
  with_items: '{{ svn }}'
  tags: [innova_base]

```

but nothing..
