### ISSUE TITLE
BUG: vars not merged for included playbooks (1.9.1)

### ISSUE THREAD

**Issue by wojtek-oledzki** [ansible/ansible#10992] opened 2015-05-12 13:55 UTC
Ansible version: 1.9.1
OS: osx 10.10

extra vars are not merged with vars defined in playbooks included from the main playbook. Instead the extra_vars replaces entire dict :(

Expected

```
ansible-playbook ... -e '{ "test": { "a": "A" } }' test.yml

TASK: [debug] *****************************************************************
ok: [default] => {
    "test": {
        "a": "A",
        "b": "B"
    }
}
TASK: [sub-include debug] *****************************************************
ok: [default] => {
    "test": {
        "a": "A",
        "b": "C"
    }
}
```

Actual

```
ansible-playbook ... -e '{ "test": { "a": "A" } }' test.yml

TASK: [debug] *****************************************************************
ok: [default] => {
    "test": {
        "a": "A",
        "b": "B"
    }
}
TASK: [sub-include debug] *****************************************************
ok: [default] => {
    "test": {
        "a": "A",   <== Just "A" - merged behaviour is not used for playbook includes ?
    }
}
```

test.yml

``` YML
- name: test
  hosts: all
  vars:
    test:
      b: B
  tasks:
    - name: debug
      debug: var=test

- name: another include
  include: test_include.yml
```

test_include.yml

``` YML
- name: test
  hosts: all
  vars:
    test:
      b: C
  tasks:
    - name: sub-include debug
      debug: var=test
```

**Comment by abadger** [comment] 2015-05-14 17:20
This is expected behaviour.  A variable is a name bound to a piece of information.  When you think in that way, what you're really doing is reassigning the name to a different piece of information, not assigning additional values to it.  So there's no expectation of merging here.  That said, there are ways to do what you want.

http://docs.ansible.com/intro_configuration.html#hash-behaviour

You can change ansible's behaviour when it encounters two dictionaries with the same name.  The above config file option will change this behaviour to "merge" fields for all such collisions.  It's not recommended because it can have unwanted effects if you have other collisions elsewhere where you are counting on (perhaps unknown to you thus far) the dict to be replaced rather than merged.

There's also a pull request to add support in jinja filters for merging specific dicts but there's a bunch of issues to resolve (bcoca and I have been talking about the issues today... not sure if that will lead immediately to some ideas on fixing them or not, though...)  https://github.com/ansible/ansible/pull/10489

# Is This A Bug?

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We're not sure this is a bug, and we don't mean for this to be confrontational.  Let's explain what we're thinking:
- variables are intended to overwrite previously defined variables.  This holds true even for dicts. There is a config setting you can toggle to make dicts merge instead of overwrite but it can lead to unintended consequences.  You can turn it on but do be careful of side effects for other dicts.

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists 
to talk about this and we might be persuaded otherwise.
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!

**Closed as completed by abadger** 2015-05-14 17:20 UTC

**Comment by wojtek-oledzki** [comment] 2015-05-14 19:05
@abadger - this is with merge behaviour turn on.

The bug here is it works in main playbook (merge), but does not work in playbook that are included from the main.
