### ISSUE TITLE
DWIM search path needs documenting to avoid errors such as ' module error in 2.2.0.0 (Unable to find '%s' in expected paths.)'

### ISSUE THREAD

**Issue by Hayorti** [ansible/ansible#19104] opened 2016-12-09 19:54 UTC
_From @Hayorti on November 14, 2016 19:49_

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
- (role file resolution)

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /home/ansible/cloudops/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
- No setting changes.

##### OS / ENVIRONMENT
- Host: CentOS 7
- Client: Windows Server 2012 R2

##### SUMMARY
The win_copy module was functioning correctly in Ansible 2.1.3.0, but the same module task now fails in Ansible 2.2.0.0 with the following message:
```
fatal: [172.31.14.229]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to find 'script/CurrentLicenses.ps1' in expected paths."}
```

##### STEPS TO REPRODUCE
Run a win_copy module task with a relative path.

Directory Structure:
```
ansible
├── check-licenses.yml
└── roles
    └── check-licenses
        ├── script
        │   └── CurrentLicenses.ps1
        └── tasks
            └── main.yml
```

Playbook (check-licenses.yml):
```
- name: Checks the licenses currently present on the server
  hosts: webservers
  strategy: free
  gather_facts: false
  vars_files:
    - host_vars/{{ env }}-vars
  roles:
    - check-licenses
```

Role (check-licenses):
```
---
- name: Delete existing CheckLicenses directory
  win_file:
    path="C:\BP_Tools\Licensing"
    state=absent

- name: Create BP_Tools directory
  win_file:
    path="C:\BP_Tools"
    state=directory

- name: Create script directory
  win_file:
    path="C:\BP_Tools\Licensing"
    state=directory

- name: Copy script to remote system
  win_copy:
    src=script/CurrentLicenses.ps1
    dest=C:/BP_Tools/Licensing/CurrentLicenses.ps1

- name: Run script
  raw: Invoke-Expression C:/BP_Tools/Licensing/CurrentLicenses.ps1
...
```

##### EXPECTED RESULTS
This result is from Ansible 2.1.3.0, limited to a single host.

```
TASK [check-licenses : Delete existing CheckLicenses directory] ****************
changed: [172.31.14.229]

TASK [check-licenses : Create BP_Tools directory] ******************************
ok: [172.31.14.229]

TASK [check-licenses : Create script directory] ********************************
changed: [172.31.14.229]

TASK [check-licenses : Copy script to remote system] ***************************
changed: [172.31.14.229]

TASK [check-licenses : Run script] *********************************************
ok: [172.31.14.229]

PLAY RECAP *********************************************************************
172.31.14.229              : ok=5    changed=3    unreachable=0    failed=0
```

##### ACTUAL RESULTS
This result is from Ansible 2.2.0.0, limited to a single host.

Non-Verbose Output
```
PLAY [Checks the licenses currently present on the server] *********************

TASK [check-licenses : Delete existing CheckLicenses directory] ****************
changed: [172.31.14.229]

TASK [check-licenses : Create BP_Tools directory] ******************************
ok: [172.31.14.229]
 [WARNING]: Module invocation had junk after the JSON data:


TASK [check-licenses : Create script directory] ********************************
changed: [172.31.14.229]

TASK [check-licenses : Copy script to remote system] ***************************
fatal: [172.31.14.229]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to find 'script/CurrentLicenses.ps1' in expected paths."}

PLAY RECAP *********************************************************************
172.31.14.229              : ok=3    changed=2    unreachable=0    failed=1
```

Verbose Output (-vvv)
```
PLAYBOOK: check-licenses.yml ***************************************************
1 plays in check-licenses.yml

PLAY [Checks the licenses currently present on the server] *********************
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/windows/win_file.ps1
<172.31.14.229> ESTABLISH WINRM CONNECTION FOR USER: ansible on PORT 5986 TO 172.31.14.229
<172.31.14.229> EXEC Set-StrictMode -Version Latest
(New-Item -Type Directory -Path $env:temp -Name "ansible-tmp-1479152898.25-122543529253760").FullName | Write-Host -Separator '';
<172.31.14.229> PUT "/tmp/tmp_mDunx" TO "C:\Users\ansible\AppData\Local\Temp\ansible-tmp-1479152898.25-122543529253760\win_file.ps1"
<172.31.14.229> EXEC Set-StrictMode -Version Latest
Try
{
& 'C:\Users\ansible\AppData\Local\Temp\ansible-tmp-1479152898.25-122543529253760\win_file.ps1'
}
Catch
{
$_obj = @{ failed = $true }
If ($_.Exception.GetType)
{
$_obj.Add('msg', $_.Exception.Message)
}
Else
{
$_obj.Add('msg', $_.ToString())
}
If ($_.InvocationInfo.PositionMessage)
{
$_obj.Add('exception', $_.InvocationInfo.PositionMessage)
}
ElseIf ($_.ScriptStackTrace)
{
$_obj.Add('exception', $_.ScriptStackTrace)
}
Try
{
$_obj.Add('error_record', ($_ | ConvertTo-Json | ConvertFrom-Json))
}
Catch
{
}
Echo $_obj | ConvertTo-Json -Compress -Depth 99
Exit 1
}
Finally { Remove-Item "C:\Users\ansible\AppData\Local\Temp\ansible-tmp-1479152898.25-122543529253760" -Force -Recurse -ErrorAction SilentlyContinue }

TASK [check-licenses : Delete existing CheckLicenses directory] ****************
task path: /home/ansible/cloudops/ansible/roles/check-licenses/tasks/main.yml:7
ok: [172.31.14.229] => {
    "changed": false,
    "invocation": {
        "module_name": "win_file"
    }
}
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/windows/win_file.ps1
<172.31.14.229> ESTABLISH WINRM CONNECTION FOR USER: ansible on PORT 5986 TO 172.31.14.229
<172.31.14.229> EXEC Set-StrictMode -Version Latest
(New-Item -Type Directory -Path $env:temp -Name "ansible-tmp-1479152899.19-48551702457764").FullName | Write-Host -Separator '';
<172.31.14.229> PUT "/tmp/tmpD9Qs_g" TO "C:\Users\ansible\AppData\Local\Temp\ansible-tmp-1479152899.19-48551702457764\win_file.ps1"
<172.31.14.229> EXEC Set-StrictMode -Version Latest
Try
{
& 'C:\Users\ansible\AppData\Local\Temp\ansible-tmp-1479152899.19-48551702457764\win_file.ps1'
}
Catch
{
$_obj = @{ failed = $true }
If ($_.Exception.GetType)
{
$_obj.Add('msg', $_.Exception.Message)
}
Else
{
$_obj.Add('msg', $_.ToString())
}
If ($_.InvocationInfo.PositionMessage)
{
$_obj.Add('exception', $_.InvocationInfo.PositionMessage)
}
ElseIf ($_.ScriptStackTrace)
{
$_obj.Add('exception', $_.ScriptStackTrace)
}
Try
{
$_obj.Add('error_record', ($_ | ConvertTo-Json | ConvertFrom-Json))
}
Catch
{
}
Echo $_obj | ConvertTo-Json -Compress -Depth 99
Exit 1
}
Finally { Remove-Item "C:\Users\ansible\AppData\Local\Temp\ansible-tmp-1479152899.19-48551702457764" -Force -Recurse -ErrorAction SilentlyContinue }

TASK [check-licenses : Create BP_Tools directory] ******************************
task path: /home/ansible/cloudops/ansible/roles/check-licenses/tasks/main.yml:14
ok: [172.31.14.229] => {
    "changed": false,
    "invocation": {
        "module_name": "win_file"
    }
}
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/windows/win_file.ps1
<172.31.14.229> ESTABLISH WINRM CONNECTION FOR USER: ansible on PORT 5986 TO 172.31.14.229
<172.31.14.229> EXEC Set-StrictMode -Version Latest
(New-Item -Type Directory -Path $env:temp -Name "ansible-tmp-1479152900.1-75553227803084").FullName | Write-Host -Separator '';
<172.31.14.229> PUT "/tmp/tmpy_GdMz" TO "C:\Users\ansible\AppData\Local\Temp\ansible-tmp-1479152900.1-75553227803084\win_file.ps1"
<172.31.14.229> EXEC Set-StrictMode -Version Latest
Try
{
& 'C:\Users\ansible\AppData\Local\Temp\ansible-tmp-1479152900.1-75553227803084\win_file.ps1'
}
Catch
{
$_obj = @{ failed = $true }
If ($_.Exception.GetType)
{
$_obj.Add('msg', $_.Exception.Message)
}
Else
{
$_obj.Add('msg', $_.ToString())
}
If ($_.InvocationInfo.PositionMessage)
{
$_obj.Add('exception', $_.InvocationInfo.PositionMessage)
}
ElseIf ($_.ScriptStackTrace)
{
$_obj.Add('exception', $_.ScriptStackTrace)
}
Try
{
$_obj.Add('error_record', ($_ | ConvertTo-Json | ConvertFrom-Json))
}
Catch
{
}
Echo $_obj | ConvertTo-Json -Compress -Depth 99
Exit 1
}
Finally { Remove-Item "C:\Users\ansible\AppData\Local\Temp\ansible-tmp-1479152900.1-75553227803084" -Force -Recurse -ErrorAction SilentlyContinue }
 [WARNING]: Module invocation had junk after the JSON data:


TASK [check-licenses : Create script directory] ********************************
task path: /home/ansible/cloudops/ansible/roles/check-licenses/tasks/main.yml:19
changed: [172.31.14.229] => {
    "changed": true,
    "invocation": {
        "module_name": "win_file"
    }
}

TASK [check-licenses : Copy script to remote system] ***************************
task path: /home/ansible/cloudops/ansible/roles/check-licenses/tasks/main.yml:26
fatal: [172.31.14.229]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "dest": "C:/BP_Tools/Licensing/CurrentLicenses.ps1",
            "src": "script/CurrentLicenses.ps1"
        },
        "module_name": "win_copy"
    },
    "msg": "Unable to find 'script/CurrentLicenses.ps1' in expected paths."
}

PLAY RECAP *********************************************************************
172.31.14.229              : ok=3    changed=1    unreachable=0    failed=1
```

_Copied from original issue: ansible/ansible-modules-core#5606_

**Comment by Hayorti** [comment] 2016-12-09 19:54
_From @ansibot on November 14, 2016 20:16_



@jhawkesworth ping, this issue is waiting for your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Hayorti** [comment] 2016-12-09 19:54
_From @jhawkesworth on November 14, 2016 21:17_

Hello.

The win_copy code itself has not changed between 2.1.3 and 2.2.0 so I think the problem is perhaps not with the win_copy code, but another part of the system.

Can you check that you are running from the same directory that you were when you were running 2.1.3?  Since 2.x, I have noticed that ansible is sensitive to the cwd that it is run from, especially when referencing relative paths such as script/CurrentLicenses.ps1 in your example.

It might also be worthwhile following the convention for sub directories of your roles - see http://docs.ansible.com/ansible/playbooks_roles.html#roles

I would suggest moving your script/CurrentLicenses.ps1 into roles/check_licenses/files/CurrentLicenses.ps1
then you can take advantage of role 'magic' and make use of the 'script' module which will both copy and run the .ps1 (and remove it when complete) in a single module call like this:
- name: run CurrentLicenses.ps1
  script: CurrentLicenses.ps1

If it is important that the file is in C:/BP_Tools/Licensing/ you would obviously need to change the script a little to make it cd to that directory.

needs_info

**Comment by Hayorti** [comment] 2016-12-09 19:54
@jhawkesworth Thanks for the response.

All of my playbooks are run from the "ansible" directory, and a large portion of the modules I'm using still work after the update. It's only win_copy that was causing some grief.

**Example 1**
I created a "files" directory as recommended, moved the script, and re-ran my playbook. It executed correctly, which is great.

Directory structure:

```
ansible
├── check-licenses.yml
└── roles
    └── check-licenses
        ├── files
        │   └── CurrentLicenses.ps1
        └── tasks
            └── main.yml
```

Task:

```
- name: Copy script to remote system
  win_copy:
    src=CurrentLicenses.ps1
    dest=C:/BP_Tools/Licensing/CurrentLicenses.ps1
```

---

**Example 2**
Just to play around a bit, I created a "script" directory inside of the "files" directory, moved the script into it, and re-ran my playbook. That worked as well.

Directory Structure:

```
ansible
├── check-licenses.yml
└── roles
    └── check-licenses
        ├── files
        │   └── script
        │       └── CurrentLicenses.ps1
        └── tasks
            └── main.yml
```

Task:

```
- name: Copy script to remote system
  win_copy:
    src=script/CurrentLicenses.ps1
    dest=C:/BP_Tools/Licensing/CurrentLicenses.ps1
```

---

**Example 3**
But, what I found most interesting is that this works as well:

Directory structure:

```
ansible
├── check-licenses.yml
└── roles
    └── check-licenses
        ├── files
        │   └── CurrentLicenses.ps1
        └── tasks
            └── main.yml
```

Task:

```
- name: Copy script to remote system
  win_copy:
    src=files/CurrentLicenses.ps1
    dest=C:/BP_Tools/Licensing/CurrentLicenses.ps1
```

In this scenario, my directory structure is identical to **Example 1**, and the only modification to the task is the addition of "files/" to the beginning of my "src" path. In **Example 1**, execution was successful without this prefix. In this example, it's successful with the prefix. So, it seems to me like Ansible is correctly ingesting the prefix, but dropping it if it finds that it's value is "files" and included redundantly. I feel this complicates things because Ansible is ingesting the prefix without complaining, sometimes unnecessarily (in the case of a redundant "files/" prefix), and only complains when the prefix is not "files".

Correct me if I'm wrong, but this doesn't seem very intuitive. If the default location is always "roles/_role_/files", then shouldn't **Example 3** fail because the directory "roles/check-licenses/files/files" doesn't exist? The "src" syntax in **Example 2** and **Example 3** is the same in that the path is a directory prefix followed by a file name, but in the case of **Example 2** there actually is a directory called "script" within the root "files" directory, but in **Example 3** there is no "files" directory nested within the root "files" directory.

---

In response to your recommendation to use the script module instead of win_copy, I need to use win_copy because this script is periodically run manually and needs to remain on the system.

**Comment by Hayorti** [comment] 2016-12-09 19:54
_From @Chris-YBS on November 16, 2016 11:47_

I have discovered that when copying from local:

prior to 2.2 you had:

win_copy: src="**files/**log4j.xml" dest= ...

2.2 it is 

win_copy: src="log4j.xml" dest=...

**Comment by Hayorti** [comment] 2016-12-09 19:54
_From @nitzmahone on November 16, 2016 18:8_

@Chris-YBS is correct- this doesn't actually have anything to do with the win_copy module itself. You're running afoul of Ansible's "DWIM" (Do What I Mean) stuff- when you're inside a role, the documented behavior of copy modules is to automatically look first in files/ in the role (and script pulls from scripts/, template pulls from templates/, etc). However, I think this was an unintended breakage due to some changes made to DWIM in 2.2- we're discussing internally, but I suspect we'll be restoring the pre-2.2 behavior.

**Comment by Hayorti** [comment] 2016-12-09 19:54
@nitzmahone

Thanks for the response. And apologies for all the reading I'm making you guys do for this.

I do have to disagree with you in regards to the documented behaviour of these modules. I can't see any documentation that dictates that these modules look for contents in specific directories. If there is documentation, it definitely isn't within the module docs themselves, which is probably where it should be.

In the case of the Unix variants of these modules (copy, template), they don't even have examples that use relative paths. They're all absolute paths to directories on the target servers themselves.

In the case of the script module, which is used for any target system, the previous observation can be made again.

In the case of the win_copy, the examples have both relative and absolute paths, which is great. But, the relative paths contain the "files/" path prefix, which makes it seem as though it can be specified to be something different. This creates confusion between the following directory structures, which both work when the "src" for the module is "files/script.ps1"

```
ansible
├── playbook.yml
└── roles
    └── roles
        ├── files
        │   └── script.ps1
        └── tasks
            └── main.yml
```

```
ansible
├── playbook.yml
└── roles
    └── role
        ├── files
        │   └── files
        │       └── script.ps1
        └── tasks
            └── main.yml
```

In the case of win_template, it has an example of an absolute path, which I'm not even sure resolves considering that it doesn't have a drive letter. Only the destination path has a drive letter. Maybe I'm just not understanding how Ansible handles Unix-style absolute paths in Windows.

I personally don't have a preference for how Ansible should work in terms of default paths/directories and such, but I do believe that direction needs to be given for how these modules are meant to be used. For example, the Directory Layout[](http://docs.ansible.com/ansible/playbooks_best_practices.html#directory-layout) in "Playbooks Best Practices" shouldn't be called a "best practice" if that's a prescriptive layout as opposed to a proposed one. My understanding of those best practices is the Ansible team saying "This is how we would do it," as opposed to "This is how you should do it." Some of those directories are definitely necessary and it is documented that, for example, role dependencies must be located in the "meta" folder. It isn't, however, documented that files must be in the files folder, even though that might be intuitive for some. There are use cases where someone might want to part out their files in folders like _scripts_ and _installers_, but might not know that there directory structure should look like this:

```
ansible
├── playbook.yml
└── roles
    └── role
        ├── files
        │   ├── scripts
        │   │   └── script.ps1
        │   └── installers
        │       └── installer.exe
        └── tasks
            └── main.yml
```

As opposed to this:

```
ansible
├── playbook.yml
└── roles
    └── role
        ├── scripts
        │   └── script.ps1
        ├── installers
        │   └── installer.exe
        └── tasks
            └── main.yml
```

This would probably be worthwhile to include in the documentation revamp that you guys have in mind for 2.3, but these minor things would probably help between now and then.

**Comment by Hayorti** [comment] 2016-12-09 19:54
_From @ansibot on December 7, 2016 20:5_

This repository has been locked. All new issues and pull requests should be filed in https://github.com/ansible/ansible

Please read through the <a href="http://docs.ansible.com/ansible/dev_guide/repomerge.html#move-issues-and-prs-to-new-repo">repomerge</a> page in the dev guide. The guide contains links to tools which automatically move your issue or pull request to the ansible/ansible repo.

**Comment by jhawkesworth** [comment] 2017-01-12 17:34
@nitzmahone - any update on changing the DWIM logic?  I had a look but couldn't find any issues regarding 'role path' or 'role file locations' so I don't know if there's a github issue for the underlying problem which I could link to or close this in favour of another issue.

Since the problem isn't specific to win_copy I'm going to edit the component_name in the description so that the bot can unassign it from me, so I can tackle issues I'm more likely to be able to resolve.

**Comment by Chris-YBS** [comment] 2017-01-13 08:35
Actually I find the "new" behaviour more logical, and once I realised what the issue was a global search/replace through my playbooks was enough to update it. 

I think we are now in a situation where the new behaviour should be preserved, any fix should look at both the new and old paths rather than just going back to the old

**Comment by jhawkesworth** [comment] 2017-02-20 08:06
@Hayorti The paths that apply to files within roles are documented here: 
http://docs.ansible.com/ansible/playbooks_roles.html#roles
I've unassigned this one from myself as it does not seem to be to do with win_copy, but rather the core DWIM logic.  I have flagged for triage so it can be reviewed by the core team in due course.

**Comment by alikins** [comment] 2017-02-20 14:43
ping @bcoca based on https://github.com/ansible/ansible/issues/19104#issuecomment-281012239 this sound like it is related to dataloader and path DWIM issues. 

ping @dharmabumstead @docschick It sounds like it may also boil down to making in sure the docs and behavior agree completely.

I haven't tried to reproduce this with devel/ yet, so heads up that it could be resolved already.

**Comment by bcoca** [comment] 2017-02-20 16:43
The current behaviour is well defined, in the past this has varied a lot and been very inconsistent. It is on my list to clearly document DWIM search path, sorry i have not gotten around to it yet.

**Comment by jhawkesworth** [comment] 2017-03-23 17:25
I edited the issue name so the bot removes this from the windows queue and hopefully is easier to locate once DWIM logic has been documented.

**Comment by jhawkesworth** [comment] 2017-03-30 08:42
Manually removed windows label as the bot doesn't seem to want to remove component labeling.

**Comment by bcoca** [comment] 2017-07-11 17:15
dupe of #17960

**Closed as completed by bcoca** 2017-07-11 17:15 UTC
Labels: affects_2.2, module, c:parsing/data_loader, c:plugins/lookup, support:core, bug, docs
