### ISSUE TITLE
Docker AttributeError: 'module object has no attribute 'Client'

### ISSUE THREAD

**Issue by benairs3** [ansible/ansible#20449] opened 2017-01-19 10:55 UTC
When i'm executing vagrant up, appears this error.
My Ansible version is: ansible_1.9.4-1

> TASK: [bootstrap_containers | start database container] *********************** 
> failed: [localhost] => {"failed": true, "parsed": false}
> BECOME-SUCCESS-vaydnjxmsrquhcgfpksenczprilvozqn
> Traceback (most recent call last):
>   File "/home/vagrant/.ansible/tmp/ansible-tmp-1484822873.61-187869719276661/docker", line 3185, in <module>
>     main()
>   File "/home/vagrant/.ansible/tmp/ansible-tmp-1484822873.61-187869719276661/docker", line 1513, in main
>     manager = DockerManager(module)
>   File "/home/vagrant/.ansible/tmp/ansible-tmp-1484822873.61-187869719276661/docker", line 635, in __init__
>     self.client = docker.Client(base_url=docker_url,
> AttributeError: 'module' object has no attribute 'Client'
> 
> 
> FATAL: all hosts have already failed -- aborting
> 
> PLAY RECAP ******************************************************************** 
>            to retry, use: --limit @/home/vagrant/bootstrap.retry
> 
> localhost                  : ok=1    changed=0    unreachable=0    failed=1   
> 
> Ansible failed to complete successfully. Any error output should be
> visible above. Please fix these errors and try again.
> 

I tried everything, but nothing appears to solve the problem

**Comment by berlic** [comment] 2017-01-19 13:14
Duplicate of https://github.com/ansible/ansible/issues/20380

**Closed as completed** 2017-01-20 00:07 UTC
Labels: affects_1.9, docker
