### ISSUE TITLE
Diff doesn't produce any output for template when using with_items, with_subelements, with_fileglob

### ISSUE THREAD

**Issue by manuel-sousa** [ansible/ansible#15776] opened 2016-05-09 12:16 UTC
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

ansible 2.0.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
##### CONFIGURATION

Default package configuration (no settings)
##### OS / ENVIRONMENT

Ubuntu 15.10
##### SUMMARY

Diff doesn't produce any output for template when using with_items, with_subelements, with_fileglob

That information is present when doing -vvvv but still doesn't show the diff output.
##### STEPS TO REPRODUCE
1. Create a file example.j2 in templates;
2. Create following playbook

```
# Example.yml
- hosts: localhost

  vars:
    example:
    - name: item0
      values:
      - name: item1

  tasks:
    - name: Normal example
      template:
        src: example.j2
        dest: "/tmp/example"

    - name: Fileglob example
      template:
        src: "{{ item }}"
        dest: "/tmp/{{ item | basename }}"
      with_fileglob:
        - ../templates/*

    - name: Subelements example
      template:
        src: example.j2
        dest: "/tmp/{{ item.0.name }}-{{ item.1.name}}"
      with_subelements:
        - "{{ example }}"
        - values

    - name: With items example
      template:
        src: example.j2
        dest: "/tmp/{{ item }}"
      with_items:
        - file1
        - file2
```
1. (Optional) create files in /tmp with different contents; For report purposes created /tmp/file1 so that all were absent besides this one;
2. Execute playbook `ansible-playbook example.yml -C -D`
##### EXPECTED RESULTS

When applying a template with items expected each item to produce it's own diff
##### ACTUAL RESULTS

The actual diff of the files isn't present except for the first example which doesn't use items.

```
mjs@mjs-G10AC:~/tmp/ansible$ ansible-playbook example.yml -C -D  -vvvv
Using /etc/ansible/ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available

Loaded callback default of type stdout, v2.0

PLAYBOOK: example.yml **********************************************************
1 plays in example.yml

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ESTABLISH LOCAL CONNECTION FOR USER: mjs
127.0.0.1 EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1462795902.63-279613495423138 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1462795902.63-279613495423138 `" )'
127.0.0.1 PUT /tmp/tmpstQDtn TO /home/mjs/.ansible/tmp/ansible-tmp-1462795902.63-279613495423138/setup
127.0.0.1 EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/mjs/.ansible/tmp/ansible-tmp-1462795902.63-279613495423138/setup; rm -rf "/home/mjs/.ansible/tmp/ansible-tmp-1462795902.63-279613495423138/" > /dev/null 2>&1'
ok: [localhost]

TASK [Normal example] **********************************************************
task path: /home/mjs/tmp/ansible/example.yml:11
ESTABLISH LOCAL CONNECTION FOR USER: mjs
127.0.0.1 EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1462795903.01-243037132411814 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1462795903.01-243037132411814 `" )'
127.0.0.1 PUT /tmp/tmp_uXVaQ TO /home/mjs/.ansible/tmp/ansible-tmp-1462795903.01-243037132411814/stat
127.0.0.1 EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/mjs/.ansible/tmp/ansible-tmp-1462795903.01-243037132411814/stat'
127.0.0.1 EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1462795903.05-277527102318693 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1462795903.05-277527102318693 `" )'
127.0.0.1 PUT /tmp/tmpXMj2ws TO /home/mjs/.ansible/tmp/ansible-tmp-1462795903.05-277527102318693/file
127.0.0.1 EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/mjs/.ansible/tmp/ansible-tmp-1462795903.05-277527102318693/file'
127.0.0.1 EXEC /bin/sh -c 'rm -f -r /home/mjs/.ansible/tmp/ansible-tmp-1462795903.01-243037132411814/ > /dev/null 2>&1'
changed: [localhost] => {"changed": true, "diff": {"after": "# Test\n", "after_header": "dynamically generated", "before": ""}, "invocation": {"module_args": {"dest": "/tmp/example", "src": "example.j2"}, "module_name": "template"}}
--- before
+++ after: dynamically generated
@@ -0,0 +1 @@
+# Test


TASK [Fileglob example] ********************************************************
task path: /home/mjs/tmp/ansible/example.yml:16
ESTABLISH LOCAL CONNECTION FOR USER: mjs
127.0.0.1 EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1462795903.11-6200349910493 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1462795903.11-6200349910493 `" )'
127.0.0.1 PUT /tmp/tmp7194Bn TO /home/mjs/.ansible/tmp/ansible-tmp-1462795903.11-6200349910493/stat
127.0.0.1 EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/mjs/.ansible/tmp/ansible-tmp-1462795903.11-6200349910493/stat'
127.0.0.1 EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1462795903.15-29023807356899 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1462795903.15-29023807356899 `" )'
127.0.0.1 PUT /tmp/tmpmyijtN TO /home/mjs/.ansible/tmp/ansible-tmp-1462795903.15-29023807356899/file
127.0.0.1 EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/mjs/.ansible/tmp/ansible-tmp-1462795903.15-29023807356899/file'
127.0.0.1 EXEC /bin/sh -c 'rm -f -r /home/mjs/.ansible/tmp/ansible-tmp-1462795903.11-6200349910493/ > /dev/null 2>&1'
changed: [localhost] => (item=/home/mjs/tmp/ansible/templates/example.j2) => {"changed": true, "diff": {"after": "# Test\n", "after_header": "dynamically generated", "before": ""}, "invocation": {"module_args": {"dest": "/tmp/example.j2", "src": "/home/mjs/tmp/ansible/templates/example.j2"}, "module_name": "template"}, "item": "/home/mjs/tmp/ansible/templates/example.j2"}

TASK [Subelements example] *****************************************************
task path: /home/mjs/tmp/ansible/example.yml:23
ESTABLISH LOCAL CONNECTION FOR USER: mjs
127.0.0.1 EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1462795903.21-219983279367155 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1462795903.21-219983279367155 `" )'
127.0.0.1 PUT /tmp/tmpkDZYpo TO /home/mjs/.ansible/tmp/ansible-tmp-1462795903.21-219983279367155/stat
127.0.0.1 EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/mjs/.ansible/tmp/ansible-tmp-1462795903.21-219983279367155/stat'
127.0.0.1 EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1462795903.24-140102414221580 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1462795903.24-140102414221580 `" )'
127.0.0.1 PUT /tmp/tmpaHW_V6 TO /home/mjs/.ansible/tmp/ansible-tmp-1462795903.24-140102414221580/file
127.0.0.1 EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/mjs/.ansible/tmp/ansible-tmp-1462795903.24-140102414221580/file'
127.0.0.1 EXEC /bin/sh -c 'rm -f -r /home/mjs/.ansible/tmp/ansible-tmp-1462795903.21-219983279367155/ > /dev/null 2>&1'
changed: [localhost] => (item=({u'name': u'item0'}, {u'name': u'item1'})) => {"changed": true, "diff": {"after": "# Test\n", "after_header": "dynamically generated", "before": ""}, "invocation": {"module_args": {"dest": "/tmp/item0-item1", "src": "example.j2"}, "module_name": "template"}, "item": [{"name": "item0"}, {"name": "item1"}]}

TASK [With items example] ******************************************************
task path: /home/mjs/tmp/ansible/example.yml:31
ESTABLISH LOCAL CONNECTION FOR USER: mjs
127.0.0.1 EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1462795903.3-195998129463053 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1462795903.3-195998129463053 `" )'
127.0.0.1 PUT /tmp/tmpEV5rie TO /home/mjs/.ansible/tmp/ansible-tmp-1462795903.3-195998129463053/stat
127.0.0.1 EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/mjs/.ansible/tmp/ansible-tmp-1462795903.3-195998129463053/stat'
127.0.0.1 EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1462795903.34-178217666635827 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1462795903.34-178217666635827 `" )'
127.0.0.1 PUT /tmp/tmpGkq0Ie TO /home/mjs/.ansible/tmp/ansible-tmp-1462795903.34-178217666635827/file
127.0.0.1 EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/mjs/.ansible/tmp/ansible-tmp-1462795903.34-178217666635827/file'
127.0.0.1 EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1462795903.39-124397021626891 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1462795903.39-124397021626891 `" )'
127.0.0.1 PUT /tmp/tmpVR90W1 TO /home/mjs/.ansible/tmp/ansible-tmp-1462795903.39-124397021626891/slurp
127.0.0.1 EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/mjs/.ansible/tmp/ansible-tmp-1462795903.39-124397021626891/slurp'
127.0.0.1 EXEC /bin/sh -c 'rm -f -r /home/mjs/.ansible/tmp/ansible-tmp-1462795903.3-195998129463053/ > /dev/null 2>&1'
changed: [localhost] => (item=file1) => {"changed": true, "diff": {"after": "# Test\n", "after_header": "dynamically generated", "before": "xpto\n", "before_header": "/tmp/file1"}, "invocation": {"module_args": {"dest": "/tmp/file1", "src": "example.j2"}, "module_name": "template"}, "item": "file1"}
127.0.0.1 EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1462795903.43-231114333874843 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1462795903.43-231114333874843 `" )'
127.0.0.1 PUT /tmp/tmpB9VRHn TO /home/mjs/.ansible/tmp/ansible-tmp-1462795903.43-231114333874843/stat
127.0.0.1 EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/mjs/.ansible/tmp/ansible-tmp-1462795903.43-231114333874843/stat'
127.0.0.1 EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1462795903.47-203177154167636 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1462795903.47-203177154167636 `" )'
127.0.0.1 PUT /tmp/tmplmZQ_X TO /home/mjs/.ansible/tmp/ansible-tmp-1462795903.47-203177154167636/file
127.0.0.1 EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/mjs/.ansible/tmp/ansible-tmp-1462795903.47-203177154167636/file'
127.0.0.1 EXEC /bin/sh -c 'rm -f -r /home/mjs/.ansible/tmp/ansible-tmp-1462795903.43-231114333874843/ > /dev/null 2>&1'
changed: [localhost] => (item=file2) => {"changed": true, "diff": {"after": "# Test\n", "after_header": "dynamically generated", "before": ""}, "invocation": {"module_args": {"dest": "/tmp/file2", "src": "example.j2"}, "module_name": "template"}, "item": "file2"}

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=4    unreachable=0    failed=0   

```

**Comment by manuel-sousa** [comment] 2016-05-09 12:17
This might be related to #15492

**Comment by bcoca** [comment] 2016-05-09 18:07
dupe of #15492

**Closed as completed by bcoca** 2016-05-09 18:07 UTC
Labels: bug

**Comment by manuel-sousa** [comment] 2016-05-09 18:14
@bcoca - don't know if this is the same issue, probably it's the same base issue but it doesn't  require the delegate_to and affects other with_*.

I've run into this issue on regular playbooks (remote hosts) after I upgraded to ansible 2.0. 

I've reproduced it on a fresh install with the example playbook. Do you want me to add any information on the other bug report since it's flagged as needing info?

**Comment by manuel-sousa** [comment] 2016-05-30 08:53
Today i tested it on 2.1.0 and it worked
