### ISSUE TITLE
Ansible won't work when VagrantFile file is at the same level as ansible dir

### ISSUE THREAD

**Issue by alfetopito** [ansible/ansible#11806] opened 2015-07-30 19:05 UTC
##### Issue Type:
- Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 2.0.0 (devel efcad3aa6d) last updated 2015/07/30 15:16:07 (GMT -200)
  lib/ansible/modules/core: (detached HEAD ff69ce7912) last updated 2015/07/07 11:42:48 (GMT -200)
  lib/ansible/modules/extras: (detached HEAD 4e48ef9eca) last updated 2015/07/07 11:43:20 (GMT -200)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/07/07 11:43:45 (GMT -200)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/07/07 11:44:04 (GMT -200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = None
```
##### Ansible Configuration:

The /etc/ansible/ansible.cfg is exactly the same as the version on github.
##### Environment:

Ubuntu 14.04 LTS
##### Summary:

Ansible won't work when VagrantFile is at the same level as ansible dir.
The base ansible path is duplicated.
It works though if the Vagrant file is inside a folder, and this folder in turn is at the same level as ansible dir.
##### Steps To Reproduce:

Create a structure like this:

```
.
├── ansible
│   ├── group_vars
│   │   └── all
│   └── site.yml
├── directory
│   └── Vagrantfile
└── Vagrantfile
```

Where `ansible/group_vars/all` is empty; `ansible/site.yml` is:

```

---
- hosts: all
  tasks:
      - name: Test
          assert:
              that:
                  - 1 == 1
```

`VagrantFile` is:

```
Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/site.yml"
    ansible.host_key_checking = false
    ansible.verbose = "v"
  end
end
```

And `directory/VagrantFile` is:

```
Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../ansible/site.yml"
    ansible.host_key_checking = false
    ansible.verbose = "v"
  end
end
```
1. Run `vagrant up` from the base dir.
2. Run from the same dir: `ansible-playbook --private-key=.vagrant/machines/default/virtualbox/private_key --inventory-file=.vagrant/provisioners/ansible/inventory ansible/site.yml`
##### Expected Results:

The playbook to run sucessfully.
##### Actual Results:

```
$ ansible-playbook --private-key=.vagrant/machines/default/virtualbox/private_key --inventory-file=.vagrant/provisioners/ansible/inventory ansible/site.yml
ERROR! the file_name '/home/alfeto/work/ansible_bug/ansible/ansible/group_vars/all' does not exist, or is not readable
```

Notice how `ansible` appears twice: `/home/alfeto/work/ansible_bug/ansible/ansible/group_vars/all`
##### Extra info:

If `ansible-playbook` is run instead from `directory/`, the playbook runs successfully:

```
/directory$ ansible-playbook --private-key=.vagrant/machines/default/virtualbox/private_key --inventory-file=.vagrant/provisioners/ansible/inventory ../ansible/site.yml

PLAY ****************************************************************************

...
```

**Comment by bcoca** [comment] 2015-07-30 19:16
Ansible has no knowledge of vagrant in this context, its just a command line tool being executed and using the parameters passed to it.

**Comment by alfetopito** [comment] 2015-07-30 19:26
@bcoca Updated the steps to not use `vagrant provision` directly.
Now invoking it using `ansible-playbook`

**Comment by abadger** [comment] 2015-08-03 20:02
Looks like a vagrant problem of some sort.  If I recreate that directory structure and run ansible-playbook no error occurs:

```
$ find .                                                                       (13:05:46)
.
./ansible
./ansible/group_vars
./ansible/group_vars/all
./ansible/site.yml
./.vagrant
./.vagrant/provisioners
./.vagrant/provisioners/ansible
./.vagrant/provisioners/ansible/inventory
$ ansible-playbook --private-key=/home/badger/.ssh/id_rsa --inventory-file=.vagrant/provisioners/ansible/inventory ansible/site.yml

PLAY ****************************************************************************

TASK [setup] ********************************************************************
ok: [localhost]

TASK [Test] *********************************************************************
ok: [localhost]

PLAY RECAP **********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

Perhaps you could post what's in the .vagrant directory and if any of those files end up being symlinks.

**Comment by alfetopito** [comment] 2015-08-03 21:11
This is what I got:

```
$ find .
.
./Vagrantfile
./ansible
./ansible/site.yml
./ansible/group_vars
./ansible/group_vars/all
./directory
./directory/Vagrantfile
./directory/.vagrant
./directory/.vagrant/provisioners
./directory/.vagrant/provisioners/ansible
./directory/.vagrant/provisioners/ansible/inventory
./directory/.vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory
./directory/.vagrant/machines
./directory/.vagrant/machines/default
./directory/.vagrant/machines/default/virtualbox
./.vagrant
./.vagrant/provisioners
./.vagrant/provisioners/ansible
./.vagrant/provisioners/ansible/inventory
./.vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory
./.vagrant/machines
./.vagrant/machines/default
./.vagrant/machines/default/virtualbox
```

**Comment by abadger** [comment] 2015-08-05 20:56
Reproduced... tracking down what specifically is causing this behaviour now.

**Comment by bcoca** [comment] 2015-08-05 21:23
dupe of #11789

**Closed as completed by bcoca** 2015-08-05 21:23 UTC
