### ISSUE TITLE
DNF GPG signature validation fails

### ISSUE THREAD

**Issue by kassner** [ansible/ansible#76240] opened 2021-11-08 11:10 UTC
### Summary

I am trying to use the DNF plugin to install packages, but they usually fail with GPG signature validation. I've seen this happen a few times already with my machine, so this isn't specific to `dbeaver-ce` here. If I just download the file and install, it works fine (dnf doesn't ask for any validation key), but installing via Ansible fails.

Downloading the RPM says it's not even signed:

```$ rpm -qpi dbeaver-ce-21.2.4-stable.x86_64.rpm 
Name        : dbeaver-ce
Epoch       : 0
Version     : 21.2.4
Release     : stable
Architecture: x86_64
Install Date: (not installed)
Group       : Applications/Databases
Size        : 138512192
License     : ASL2
Signature   : (none)
Source RPM  : (none)
Build Date  : Mon 01 Nov 2021 03:23:31 PM CET
Build Host  : https://dbeaver.io/
Packager    : dbeaver@jkiss.org
Vendor      : DBeaver Corp
URL         : https://dbeaver.io/
Summary     : Universal Database Manager and SQL Client
Description :
Universal Database Manager and SQL Client
```

### Issue Type

Bug Report

### Component Name

dnf

### Ansible Version

```console
$ ansible --version
ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/rafael/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.7 (default, Aug 30 2021, 00:00:00) [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)]
```

### Configuration

```console
$ ansible-config dump --only-changed
$
```

### OS / Environment

Fedora 34

### Steps to Reproduce

```yaml (paste below)
- name: setup machine
  hosts: 127.0.0.1
  connection: local
  become: no

  tasks:
  - name: install dbeaver
    become: yes
    dnf:
      name: https://github.com/dbeaver/dbeaver/releases/download/21.2.4/dbeaver-ce-21.2.4-stable.x86_64.rpm
      state: latest
```

### Expected Results

dbeaver-ce installed via DNF.

### Actual Results

```console
`Failed to validate GPG signature`:


$ ansible-playbook -K main.yaml
BECOME password: 
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [setup machine] *********************************************************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [install dbeaver] *******************************************************************************************************************************************************************************************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Failed to validate GPG signature for dbeaver-ce-21.2.4-stable.x86_64"}

PLAY RECAP *******************************************************************************************************************************************************************************************************************************************************************************************************************
127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by mkrizek** [comment] 2021-11-08 11:14
Duplicate of https://github.com/ansible/ansible/issues/76192

**Closed as completed by mkrizek** 2021-11-08 11:14 UTC
