### ISSUE TITLE
git module does not allow override of local tmp directory

### ISSUE THREAD

**Issue by hyweldt** [ansible/ansible#38218] opened 2018-04-03 14:31 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
git

##### ANSIBLE VERSION
```
ansible 2.4.2.0
```

##### CONFIGURATION
[default]
local_tmp=~/ansible-tmp/
remote_tmp=~/ansible-tmp/

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When attempting to clone with a non-executable /tmp directory, the git module fails with a permissions error.  From local hacking on the git module I've found that write_ssh_wrapper doesn't respect the user's local_tmp or remote_tmp options.
I discovered this in my attempts to use ansible-pull, which uses the git module to perform clones, so this should also improve ansible-pull in constrained environments.

##### STEPS TO REPRODUCE
In the user's home directory, create an .ansible.cfg file with contents:
```
[default]
local_tmp=~/ansible-tmp/
```
With a non-executable tmp directory, run:
ansible -i inventory -m git -a "name=git@github.com:ansible/ansible.git dest=~/ansible"

##### EXPECTED RESULTS
The local_tmp value is respected and the git module clones the repository, depositing and running the ssh wrapper script in ~/ansible-tmp/

##### ACTUAL RESULTS
ansible fails with message "fatal: cannot exec '/tmp/tmp6uQ6wH': Permission denied\nfatal: unable to fork"

**Comment by sivel** [comment] 2018-04-03 14:35
Duplicate of https://github.com/ansible/ansible/issues/33947

**Closed as completed by sivel** 2018-04-03 14:35 UTC
