### ISSUE TITLE
argument_spec: default value for dict entries do not work

### ISSUE THREAD

**Issue by oetiker** [ansible/ansible#83287] opened 2024-05-21 12:28 UTC
### Summary

In `argument_spec` configuring a `dict` key and inside that key  `options` with `default` values. The `default` value will not be supplied.

### Issue Type

Bug Report

### Component Name

bin/ansible
validate_argument_spec.py

### Ansible Version

```console
$ ansible --version
ansible [core 2.16.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/oetiker/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/oetiker/.local/share/mise/installs/python/3.12/lib/python3.12/site-packages/ansible
  ansible collection location = /home/oetiker/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/oetiker/.local/share/mise/installs/python/3.12/bin/ansible
  python version = 3.12.3 (main, Apr 15 2024, 18:25:56) [Clang 17.0.6 ] (/home/oetiker/.local/share/mise/installs/python/3.12/bin/python3.12)
  jinja version = 3.1.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /etc/ansible/ansible.cfg
EDITOR(env: EDITOR) = jmacs
```

### OS / Environment

Ubuntu 20.04.6 LTS

### Steps to Reproduce

from `meta.yaml` for the `oposs.aa_hello` role

```yaml
argument_specs:
  main:
    short_description: "add the hello.sh script to /usr/bin"
    author: "Tobi Oetiker <tobi@oetiker.ch>"
    description:
      - This is the main entry point for the `{{ role_name }}` role.
      - It creates a hello.sh shellscript.
    options:
      # we can use the role name as a prefix for the options
      oposs_aa_hello:
        description: the role namespace
        type: dict
        required: true
        options:
          first_name:
            description: "Your name"
            type: str
            required: true
          choice:
            description: "Pick a type of greating (formal, informal)"
            type: str
            choices: ["formal", "informal"]
            default: "formal"
```

`playbook.yaml`

```yaml
- name: Run the Role oposs.aa_hello
  hosts: all
  gather_facts: true
  tags:
    - molecule-idempotence-notest
  roles:
    - role: oposs.aa_hello
      vars:
        oposs_aa_hello:
          first_name: Tobi
```

### Expected Results

anisible should be happy :)

### Actual Results

```console
FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'choice'. 'dict object' has no attribute 'choice'"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by sivel** [comment] 2024-05-21 13:52
Duplicate of https://github.com/ansible/ansible/issues/83268 https://github.com/ansible/ansible/issues/78889

**Comment by oetiker** [comment] 2024-05-21 13:59
> Duplicate of #83268 #78889

hmmm not sure, this is about default values for keys of dicts ... looking at the issues you cited they seem to have different datastructures ...

**Comment by sivel** [comment] 2024-05-21 14:09
> `default` is just for documentation and the existing type validators only guarantee that it can be converted to the type, not that it is actually that type.

> ... because of complexities with variable precedence. At the moment, we could return the validated and coerced variables in an ansible_facts key from the validate_argument_spec action plugin, but this would break the assumptions of variable precedence. At this time we do not have plans on implementing a feature that would allow re-injecting the validated and coerced variables.

**Comment by flowerysong** [comment] 2024-05-21 14:18
Duplicate of #80298 #80604

**Comment by oetiker** [comment] 2024-05-21 15:03
What seems odd, is that when you are setting `required: true` and `default: xxx` then ansible will complain, that a default value and required would not go together. If default is for documentation only, then this error makes little sense.

**Comment by bcoca** [comment] 2024-05-21 15:25
closing as per above

**Closed as completed by bcoca** 2024-05-21 15:25 UTC
Labels: module, bug, affects_2.16

**Comment by bcoca** [comment] 2024-05-21 15:34
the error is correct, the documentation should not specify a default if the argument is required, it is not only code consistency we check for.
