### ISSUE TITLE
Ansible template sometimes created directory instead file

### ISSUE THREAD

**Issue by PlugIN73** [ansible/ansible#10244] opened 2015-02-15 09:16 UTC
##### Issue Type:

Bug
##### Ansible Version:

ansible 1.8.2
##### Environment:

My home system is:
Linux 3.13.0-39-generic #66-Ubuntu SMP Tue Oct 28 13:30:27 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
And host system: 
Linux 3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
##### Summary:

I have this task:

```
- template: src=supervisord.hexlet-ide.conf.j2 dest={{ ide_release_root }}/supervisord.hexlet-ide.conf
  sudo: yes
  tags: ide
```

And sometimes, when i running this tack, I see that in destination directory supervisord.hexlet-ide.conf is not a file! It's directory with file supervisord.hexlet-ide.conf. When I remove this directory and try run this task again - supervisord.hexlet-ide.conf becomes file.
##### Steps To Reproduce:

I do not know the right steps to reproduce this problem. But sometimes I saw this problem since ansible 1.5 (when i started using them)

**Comment by abadger** [comment] 2015-02-16 06:00
It sounds like your setup is running the ansible task you listed periodically.  the actual file should almost never be updated by the task since the file should already exist with the correct contents.  Is that correct?

It also sounds like you don't find that you run ansible and right after the task completes successfully you see that the file is now a directory.  It sounds more like you run ansible and it fails.  When you investigate you find that the conf file has become a directory at some point in the past?

If so, I don't think this is ansible (or at least, not this task) making the change.  For the same playbook, ansible is going to repeatably make the same change.  So something else (or some other ansible task) is likely the culprit for the file turning into a directory.

I've run the task you gave in a loop for 10000 repetitions just in case there was something I'm not seeing and was unable to reproduce.  If you still think the problem is this ansible task I'm afraid we'll need a reproducer in order to diagnose further.

**Comment by abadger** [comment] 2015-02-17 21:56
# Cannot Reproduce

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us. 

Testing this on the version you have specified, we cannot reproduce this problem.

We suggest that:
- you attempt to find either a reproducer or something else (another program or another ansible task) that might be creating the listed file as a directory.  Since we're unable to reproduce the issue with the task you mentioned we highly suspect that something else is what's causing the problem and you only notice it when this task runs. 

As such, we are going to close this ticket.  Should you disagree with this conclusion, you may also wish to join our mailing lists, which are very active:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Closed as completed by abadger** 2015-02-17 21:56 UTC
Labels: bug

**Comment by aavkvard** [comment] 2016-12-14 08:25
Can you please reopen as I'm hitting this one as well on both 2.2.0.0 on Arch Linux and 2.1.2.0 and 2.2.1.0 on Debian Jessie.

My tasks are:
```
- name: create Django environment
  template: src=settings.py.j2  dest="{{ conf_root }}/django/{{ app_name }}/settings_ansible.py" mode=0640 owner=root group=docker

- name: create gunicorn configuration
  template: src="{{ app_name }}.conf.j2" dest="{{ conf_root}}/django/{{ app_name }}.conf"
```
With my vars resolving as
```
conf_root:  /etc
app_name: selfservice
```
the first task creates /etc/django/selfservice/setings_ansible.py/settings.py.j2, which is incorrect, while the second creates /etc/django/selfservice.conf, which is correct.

**Comment by ph448** [comment] 2016-12-14 11:06
Scratch that, it was found to be a local problem caused by incorrect ordering of tasks.

**Comment by kralikba** [comment] 2017-10-02 13:06
@aavkvard @ph448 I'm also hitting this problem. What was your issue exactly?

**Comment by ph448** [comment] 2017-10-02 13:35
@kralikba I was trying to mount config files in a Docker container but had a stray task that started the container before the play got to create the files. If you start the container without the files being there, Docker will fake them as directories and Ansible will produce the described behaviour.

**Comment by kralikba** [comment] 2017-10-02 13:42
@ph448 Thanks. Docker turned out to be my problem as well!
