### ISSUE TITLE
Data from multiple ansible.cfg should be partially merged instead of a full replacement

### ISSUE THREAD

**Issue by flare-ws** [ansible/ansible#25707] opened 2017-06-14 16:47 UTC
##### ISSUE TYPE

 - Bug Report
 - Feature Idea

##### COMPONENT NAME
ansible.config.manager.ConfigManager

##### ANSIBLE VERSION

```
2.3.1.0
```

##### CONFIGURATION

multiple ansible.cfg files
~/.ansible.cfg
{{ playbook_dir }}/ansible.cfg

##### OS / ENVIRONMENT
N/A

##### SUMMARY
For some reasons I want to override a single value from ansible.cfg, for example, "hash_behaviour", for a single playbook. But there are no override mechanism available so first found file wins.

##### STEPS TO REPRODUCE

```
Ansible.cfg lookup priority (from docs):

* ANSIBLE_CONFIG (an environment variable)
* ansible.cfg (in the current directory)
* .ansible.cfg (in the home directory)
* /etc/ansible/ansible.cfg
```

```~/.ansible.cfg
[defaults]
stdout_callback = mycallback
callback_plugins  = ./callback_plugins/
hash_behaviour=replace
```

```{{ playbook_dir }}/ansible.cfg
[defaults]
hash_behaviour=merge
```

##### EXPECTED RESULTS
ansible-playbook should combine two files according to priority list (like in group_vars) and load this env:
```
[defaults]
stdout_callback = mycallback
callback_plugins  = ./callback_plugins/
hash_behaviour=merge
```
##### ACTUAL RESULTS

but actually it loads
```
[defaults]
hash_behaviour=merge
```
so other variables from ~/.ansible.cfg are lost

**Comment by bcoca** [comment] 2017-06-14 17:24
dupe of #17914

**Closed as completed by bcoca** 2017-06-14 17:24 UTC
Labels: affects_2.3, bug
