### ISSUE TITLE
[WARNING]: Could not match supplied host pattern, ignoring: empty-group

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible#36306] opened 2018-02-16 15:08 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION

```
2.4.3.0
```

##### OS / ENVIRONMENT
N/A
##### SUMMARY
It seems that ansible will always throw an warning if a host group is empty and there is no way to avoid getting this warning if the group is empty.

This goes even more verbose when list of groups is specified.

##### STEPS TO REPRODUCE

```yaml
#!/usr/bin/env ansible-playbook -i hosts
---
- hosts: empty-group
  tasks:
    - debug: msg="foo"
```

With hosts:
```
localhost

[empty-group]
```

##### EXPECTED RESULTS
No warning.

##### ACTUAL RESULTS

```
 [WARNING]: Could not match supplied host pattern, ignoring: empty-group


PLAY [empty-group] *******************************************************************************************************************************************************************************************************************************************
skipping: no hosts matched

PLAY RECAP ***************************************************************************************************************************************************************************************************************************************************
```

**Comment by bcoca** [comment] 2018-02-16 15:23
Duplicate of #35255

**Closed as completed by bcoca** 2018-02-16 15:23 UTC
Labels: affects_2.4, support:core, bug
