### ISSUE TITLE
'ansible_os_family' is undefined

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible#14231] opened 2016-01-31 20:20 UTC
All playbooks with ansible_os_family used for conditional roll includes now fail. Using git bisect shows things "break" in 5587b08335f223fff64f54ced6f2790b3d6ee6f0.

I don't see anything regarding the renaming of the ansible_os_family variable so I assume this is a bug?

```
$ ansible --version
ansible 2.1.0 (detached HEAD 5587b08335) last updated 2016/01/31 14:13:01 (GMT -500)
  lib/ansible/modules/core: (detached HEAD 93d02189f6) last updated 2016/01/29 12:10:41 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD fff5ae6994) last updated 2016/01/29 12:10:41 (GMT -500)
  config file =
  configured module search path = Default w/o overrides
```

```
5587b08335f223fff64f54ced6f2790b3d6ee6f0 is the first bad commit
commit 5587b08335f223fff64f54ced6f2790b3d6ee6f0
Author: James Cammarata <jimi@sngx.net>
Date:   Fri Jan 29 15:32:35 2016 -0500

    Make sure setup tasks inherit properly from their parent play

    Fixes #13602
```

```
fatal: [testing]: FAILED! => {"failed": true, "msg": "The conditional check 'ansible_os_family == 'Debian'' failed. The error was: error while evaluating conditional (ansible_os_family == 'Debian'): 'ansible_os_family' is undefined\n\nThe error appears to have been in '/Users/tanner/projects/ansible.git/playbooks.git/roles/updates/tasks/main.yml': line 4, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- include: debian.yml\n  ^ here\n"}
```

**Comment by basictheprogram** [comment] 2016-01-31 22:51
Simple task that is failing.

```
---
# file: roles/updates

- include: debian.yml
  when: ansible_os_family == 'Debian'
```

debian.yml

```
---
# tasks file for roles/updates

- name: package update (apt)
  apt: update_cache=yes cache_valid_time=3600
  always_run: yes
  tags: apt
```

**Comment by mattclay** [comment] 2016-02-01 07:57
This appears to be the same as issue #14228.

**Comment by mattclay** [comment] 2016-02-01 08:46
I can reproduce this, but only when specifying a tag.

**Comment by bcoca** [comment] 2016-02-01 13:57
asnible_os_family depends on fact gathering, the commit you reference makes the fact gathering task obey tags, if your tagging prevents fact gathering ... it is expected that it is undefined.

But this is not clear, please post a fully functional minimal test case.

**Comment by basictheprogram** [comment] 2016-02-01 17:40
To be clear the behavior of 2.0 (and 1.9) has changed? 

All the tasks, plays, and playbooks I have work as I would expect until commit 5587b08335f223fff64f54ced6f2790b3d6ee6f0.

The fully functional minimal test cast below. This code is used in our production environment (2.0) and works.

```
$ ansible --version
ansible 2.1.0 (devel 25f403d36d) last updated 2016/02/01 11:31:25 (GMT -500)
  lib/ansible/modules/core: (detached HEAD 93d02189f6) last updated 2016/01/29 12:10:41 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD fff5ae6994) last updated 2016/01/29 12:10:41 (GMT -500)
  config file = /Users/tanner/projects/ansible.git/playbooks.git/ansible.cfg
  configured module search path = Default w/o overrides
```

```
---
# file: linux-servers.yml

- hosts: linux-servers
  roles:
    - { role: updates, become: yes }
  tasks:
```

```
---
# file: updates/main.yml

- include: debian.yml
  when: ansible_os_family == 'Debian'
```

```
---
# tasks file for updates/debian.yml

- name: package update (apt)
  apt: update_cache=yes cache_valid_time=3600
  always_run: yes
  tags: apt

- name: package upgrade (apt)
  apt: upgrade=dist
  always_run: yes
  tags: apt
```

```
$ ansible-playbook -i lab/testing-servers  --ask-vault-pass --user= labansible linux-servers.yml --tags=apt
<snip>
fatal: [linux-1.lab.real-time.com]: FAILED! => {"failed": true, "msg": "The conditional check 'ansible_os_family == 'Debian'' failed. The error was: error while evaluating conditional (ansible_os_family == 'Debian'): 'ansible_os_family' is undefined\n\nThe error appears to have been in '/Users/tanner/projects/ansible.git/playbooks.git/roles/updates/tasks/main.yml': line 4, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- include: debian.yml\n  ^ here\n"}
```

**Comment by bcoca** [comment] 2016-02-02 20:53
closing as dupe  of #14228

**Closed as completed by bcoca** 2016-02-02 20:53 UTC
Labels: bug
