### ISSUE TITLE
delegate_to is broken if ansible_host relies on inventory_hostname

### ISSUE THREAD

**Issue by plastikat** [ansible/ansible#71198] opened 2020-08-11 09:58 UTC
##### SUMMARY

When `ansible_host` is customized (i.e. overridden/redefined) for all hosts (e.g. in 'group_vars/all'), the task with a `delegate_to` tries to connect to localhost over SSH (thus ignoring the implicit `ansible_connection: local`) *prior* to establishing an SSH connection to a delegation target host.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.9.11
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Jul 20 2020, 15:37:01) [GCC 7.5.0]
```

##### CONFIGURATION

```paste below
Default
```

##### OS / ENVIRONMENT

Description:    Ubuntu 18.04.4 LTS

##### STEPS TO REPRODUCE

The prerequisites to reproduce the issue are the following:
* The 'localhost' entry is *not* defined in inventory.
* The 'delegation_target' entry *is* defined in inventory (and is expected to be reached over SSH, as per default).
* The following is defined in 'group_vars/all' of a given inventory:
```yaml
ansible_host: "{{ inventory_hostname }}.example.org"
```
* The following is a test playbook:
```yaml
- name: Test
  hosts: localhost
  gather_facts: no
  become: no

  vars:
    my_delegation_host: delegation_target.example.org

  tasks:

    - debug:
        var: ansible_host
    - debug:
        var: ansible_connection

    - shell: hostname
      register: hostname_data
      delegate_to: "{{ my_delegation_host }}"

    - debug:
        var: hostname_data
```

```yaml

```

##### EXPECTED RESULTS

With the following Ansible version:
```paste below
ansible 2.8.13
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Jul 20 2020, 15:37:01) [GCC 7.5.0]
```
the result is the following:
```

PLAY [Test] *********************************************************************************************************************

TASK [debug] ********************************************************************************************************************
ok: [localhost] => {
    "ansible_host": "localhost.example.org"
}

TASK [debug] ********************************************************************************************************************
ok: [localhost] => {
    "ansible_connection": "local"
}

TASK [shell] ********************************************************************************************************************
changed: [localhost -> delegation_target.example.org]

TASK [debug] ********************************************************************************************************************
ok: [localhost] => {
    "hostname_data": {
        "ansible_facts": {
            "discovered_interpreter_python": "/usr/bin/python"
        }, 
        "changed": true, 
        "cmd": "hostname", 
        "delta": "0:00:00.001931", 
        "deprecations": [
            {
                "msg": "Distribution Ubuntu 18.04 on host localhost should use /usr/bin/python3, but is using /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using the discovered platform python for this host. See https://docs.ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html for more information", 
                "version": "2.12"
            }
        ], 
        "end": "2020-08-11 08:54:44.884152", 
        "failed": false, 
        "rc": 0, 
        "start": "2020-08-11 08:54:44.882221", 
        "stderr": "", 
        "stderr_lines": [], 
        "stdout": "delegation_target", 
        "stdout_lines": [
            "delegation_target"
        ]
    }
}

PLAY RECAP **********************************************************************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

##### ACTUAL RESULTS

But with the topic Ansible version, the result is:

```paste below

PLAY [Test] *********************************************************************************************************************

TASK [debug] ********************************************************************************************************************
ok: [localhost] => {
    "ansible_host": "localhost.example.org"
}

TASK [debug] ********************************************************************************************************************
ok: [localhost] => {
    "ansible_connection": "local"
}

TASK [shell] ********************************************************************************************************************
fatal: [localhost]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname localhost.example.org: Name or service not known", "unreachable": true}

PLAY RECAP **********************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
```

**Comment by plastikat** [comment] 2020-08-11 09:59
This might be related to https://github.com/ansible/ansible/issues/70495, however, explicitly defining localhost does not help in this case.

In case I define localhost in inventory with:
```
localhost ansible_connection=local ansible_host=127.0.0.1
```
then its own `ansible_host` is in effect for the `debug` task of the test playbook (it's printed as 127.0.0.1), *but* the `shell` delegated task still tries to connect to 'localhost.example.org', which puzzles me.

**Comment by bcoca** [comment] 2020-08-11 13:02
`localhost` is not the host you are delegating to, `delegation_target.example.org`, set the `ansible_connection` on THAT host.

fyi, hosts that were not in inventory will not be added to any groups if `delegate_to` is the first place they are defined in.

**Comment by plastikat** [comment] 2020-08-12 03:20
The `delegation_target` *was* defined in inventory (I forgot to clarify this and now have updated the "STEPS TO REPRODUCE" section), so it is *expected* to be reached over SSH. This is exactly what is done by Ansible 2.8:

> TASK [shell] ********************************************
> changed: [localhost -> delegation_target.example.org]

though, I agree, it is not clear it was SSH here, since the example logs are not debug logs.

As to the `localhost` host, it implicitly has `ansible_connection: local` when not defined in inventory, and all I tried to do [here](https://github.com/ansible/ansible/issues/71198#issuecomment-671851947) is just to set implicit values explicitly.

The main problem is that the topic version of Ansible 2.9, when running the `shell` delegated task, tries to connect to *localhost over SSH* (as I explain in the "SUMMARY" section), in spite of having `ansible_connection: local` for localhost. Here is the key log excerpt:
> "Failed to connect to the host via ssh: ssh: Could not resolve hostname localhost.example.org: Name or service not known"

When I remove `ansible_host` from my inventory, the result is identical to that of Ansible 2.8 (hence the issue title contains "when `ansible_host` is defined").

**Comment by plastikat** [comment] 2020-08-12 03:58
FYI, to expand on the issue further, should I replace `localhost` with some other host `X` from inventory (which has `ansible_connection: ssh`), the `delegate_to` (while already running at `X` over SSH) seems to make *a second SSH connection* to `X` (which succeeds), but *never reaches* `delegation_target` at all (i.e. the `shell` gets executed at `X`, via this second SSH connection).

I believe the root cause to be the same, but let us see if this second use case worth a dedicated issue. I reported the `localhost` case first because I think it is easier to debug (as only two hosts are required for testing, instead of three for this second use case).

**Comment by plastikat** [comment] 2020-08-12 04:08
As a side note, considering all the recent efforts being done to refine connection type handling (and to make a strict distinction between them), would it not be a good idea to add `ansible_connection` to the list of [Return Values](https://docs.ansible.com/ansible/latest/reference_appendices/common_return_values.html#return-values)? We would then be able to easily see what connection type each task used (without having to resort to an overwhelming `-vvvv` mode).

**Comment by plastikat** [comment] 2020-08-12 05:23
Some more details. When I enable pipelining by putting the following in ansible.cfg:
```ini
[ssh_connection]
pipelining = True
```
I get the following additional warning in the log:
> TASK [shell] ********************************************
> [WARNING]: Unhandled error in Python interpreter discovery for host delegation_target.example.org: Failed to connect to the host via ssh: ssh: Could not resolve hostname localhost.example.org: Name or service not known

As you can see, two different host names are reported (while I would expect only one name).

**Comment by rodneyvdw** [comment] 2020-08-12 07:45
I can confirm this behavior of delegating to localhost suddenly wanting to setup a local ssh connection.

"delegate_to: localhost " - used to merely run commands locally on the ansible host (no ssh to localhost). We use this a lot for jobs that run under tower/awx to connect to APIs of other servers.. This morning i upgraded ansible from 2.9.9 to 2.9.12 and every playbook using using the delegate_to: localhost statement has broken. I have now rolled back to 2.9.9 and all is well.

From the OS log we see the beviour
Aug 12 07:33:33 myserver unix_chkpwd[52491]: password check failed for user (awx)
Aug 12 07:33:33 myserver sshd[52490]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=localhost  user=awx
Aug 12 07:33:33 myserver sshd[52490]: pam_succeed_if(sshd:auth): requirement "uid >= 1000" not met by user "awx"
Aug 12 07:33:35 myserver sshd[52486]: error: PAM: Authentication failure for awx from localhost
Aug 12 07:33:35 myserver sshd[52486]: Postponed keyboard-interactive for awx from ::1 port 51858 ssh2 [preauth]

**Comment by bcoca** [comment] 2020-08-12 15:15
` localhost.example.org`  won't match 'implicit localhost' so it won't default to local connection, I'm not sure what is going on, but I think it has to do with you setting `ansible_host` for localhost to a different value than what you state.

Try using `ansbile-invenotry --list ` to ensure the vars are what you think they are.

**Comment by bcoca** [comment] 2020-08-12 15:16
@rodneyvdw your case seems different, he is delegating FROM localhost, not TO localhost, i would also run `ansible-inventory` in your case to check proper values are not overriding the connection info for localhost.

**Comment by plastikat** [comment] 2020-08-12 16:27
@bcoca, my ultimate goal is to make my code work again. If there is anything wrong on my side, I would appreciate if someone could help me figure what exactly is wrong.

I have created a repository with the test case: [ansible3](https://github.com/plastikat/ansible3).

To reproduce the issue I use the following command:
```
ansible-playbook -i inventories/an7 test.yml
```

The output of `ansible-inventory --list -i inventories/an7` is in the same repository: [an7.inventory.json](https://github.com/plastikat/ansible3/blob/master/an7.inventory.json).

Please let me know if I can provide any additional information.

**Comment by bcoca** [comment] 2020-08-12 17:25
`    "ansible_host": "{{ inventory_hostname }}.{{ dns_domain }}", ` <= this won't work as you think it does, `inventory_hostname` ALWAYS refers to the host you delegate FOR, not the host you delegate TO.

**Comment by plastikat** [comment] 2020-08-13 10:36
Within our code base, we had `ansible_host: "{{ inventory_hostname }}.{{ dns_domain }}"` *for years*, this definition has been there long before I myself have joined the project. So, from our side, I can assure it *had* worked as expected, like a charm, since at least version 2.4. This is the reason it had not even occurred to me that `inventory_hostname` might be the culprit here...

And by "as expected" I mean that `inventory_hostname` *always* contained the name of the host where code currently ran, including a host where code was delegated to. And it seemed logical and easy to follow.

Now that you have explained what causes our code to fail (thank you for that), I wonder how can the previous behavior be achieved? Are there any "special variables" that can be used to figure that "currently code runs on a delegated host"? Also, is there any chance that a separate variable that would mimic "the old behavior" be introduced?

**Comment by plastikat** [comment] 2020-08-14 06:57
Within our code base, we had `ansible_host: "{{ inventory_hostname }}.{{ dns_domain }}"` *for years*, this definition has been there long before I myself have joined the project. So, from our side, I can assure it *had* worked as expected, like a charm, since at least version 2.4. This is the reason it had not even occurred to me that `inventory_hostname` might be the culprit here...

@bcoca, thank you for helping to track the underlying reason down. After doing further testing and analysis, it looks like `inventory_hostname` is used to be *temporarily* set by Ansible to a delegation host name, but *only while* establishing a delegating connection, because for the tasks running *at a delegation host* `inventory_hostname` had its usual value of (quoting the docs):

> the ‘current’ host being iterated over in the play

I am not really sure which behavior is more correct, but the `ansible_host` definition (as given at the top of this message) allows us to gracefully abstract DNS domains (which differ between our environments) and keep environment inventories much more similar to each other.

To overcome this `inventory_hostname` "fix", for our code base I have implemented the following [workaround](https://github.com/plastikat/ansible3/commit/72d724b9b41477b29afce5f10ad5715d8f705316). It is far from being elegant (and requires to add an additional variable to all delegation calls), but it makes our code work again.

**Comment by bcoca** [comment] 2020-08-17 15:55
not sure your 'workaround' would work since variable evaluation is 'lazy' and `inventory_hostname` should still refer to the original task host. You would need `set_fact` to 'freeze' the value for the delegated host.

In any case, closing as this is how it is supposed to work.

**Closed as completed by bcoca** 2020-08-17 15:55 UTC
Labels: python3, support:core, bug, affects_2.9

**Comment by plastikat** [comment] 2020-08-18 01:52
Just for the sake of clarity, I want to say that my workaround works. No doubt `inventory_hostname` would still refer to the original task host, but I have hidden `inventory_hostname` behind `ansible_hostname`, then I *override* `ansible_hostname` for a delegated task, so for that task it no longer refers to `inventory_hostname`. This is very tedious (because I need to do it for *every* delegated task), but I have found no better solution so far.

**Comment by bcoca** [comment] 2020-08-18 14:16
might be simpler to just have a set_fact at start of play that does this, overriding inventory_hostname can cause issues.
