### ISSUE TITLE
clear_host_errors does not work with gather_facts

### ISSUE THREAD

**Issue by mrcamp** [ansible/ansible#32394] opened 2017-10-31 15:49 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

clear_host_errors

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

CentOS 7

##### SUMMARY

clear_host_errors does not seem to clear host errors from gather_facts.

##### STEPS TO REPRODUCE

```yaml
---
- name: foo
  hosts: blah
  gather_facts: yes
  roles:
    - do_this
    - do_that
  tasks:
    - meta: clear_host_errors
```

Hosts consist of A and B. A is fine, but B is unreachable.

##### EXPECTED RESULTS

I would expect Ansible to note that B was unreachable while gathering facts. The roles would then only run on A. Then `clear_host_errors` would remove the alert of B being unreachable so that the job can then complete successfully.

##### ACTUAL RESULTS

Ansible notes that B is unreachable while gathering facts. The roles then only run on A.

`clear_host_errors never appears in the output, and and the job exits as a failure.

```
PLAY [foo] *********************************************************************

TASK [setup] *******************************************************************
ok: [A]
fatal: [B]

TASK [do_this : fizz] ************************************************************
changed: [A]

TASK [do_that: fizz] *************************************************************
changed: [A]

PLAY RECAP *********************************************************************
A                                                       : ok=1   changed=2    unreachable=0    failed=0
B                                                       : ok=0   changed=0    unreachable=1    failed=0
```

**Comment by bcoca** [comment] 2017-10-31 17:00
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

The issue is not with `meta: clear_host_errors` but in the execution order, `tasks:` runs AFTER `roles:` you want `pre_tasks:`.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by mrcamp** [comment] 2017-10-31 17:27
I understand that `tasks` runs AFTER `roles`, that's why I used it. 

I may not have explained my `EXPECTED RESULTS` in the report well enough: I expect A to be reachable during gathering_facts and the defined roles (this works). I expect B to be unreachable during gathering_facts, and then not tried against for the defined roles (this works). I then expect clear_host_errors to run (this does not appear to happen in the output) and clear the unreachable error for B before exiting. With the error cleared, I expect the process to exit successfully (it instead exits as a failure).

My point is: I'm trying to use `clear_host_errors` to clear `unreachable` errors in the setup so that the command won't exit as a failure. By the output of the run (I've tried both `tasks` and `pre_tasks`), it doesn't appear to even be running `clear_host_errors` and continues to exit as a failure.

**Comment by bcoca** [comment] 2017-10-31 18:44
@mrcamp sorry for misunderstanding, but i'm not sure your expectation matches the function.
The 'clear host errors' means that the host is now available to proceed in play, not that the error status of all tasks associated with that host get changed.

in any case, for the `meta` task to execute at least one host still needs to be active in the play, is this the case?

**Comment by mrcamp** [comment] 2017-10-31 18:47
No worries! I was probably too vague to begin with. There is at least one host still active in the play.

**Comment by mrcamp** [comment] 2017-10-31 19:13
Ok so `clear_host_errors` clears it to retry again, but doesn't technically clear the error from Ansible. 

Is there a different meta tag to use or a different strategy to accomplish this? `clear_host_errors` sounded like the correct path, hence my bug report.

**Comment by bcoca** [comment] 2017-10-31 19:18
@mrcamp ah, so you wan to clear the 'TASK' errors, not the HOST .. those are 2 dif things. 

Host are marked as 'failed' or 'unreachable' and that affects subsequent task execution, this is what 'clear_host_errors' affects.

Task status is not the same, a failed task can mark a host as failed (unless you use ignore_errors), the state of the task can be controlled via `failed_when:` on the task itself.

Since this is not a bug, but mostly a misunderstanding on the feature, I'm going to close this ticket, as stated above, please use the mailing list or IRC when you have questions  of this nature as the ticketing system is for reporting bugs or requesting features.

**Closed as completed by bcoca** 2017-10-31 19:18 UTC
Labels: affects_2.2, support:core, bug

**Comment by mrcamp** [comment] 2017-10-31 19:37
I have not said anything about tasks failing. I fully understand `ignore_errors` and `failed_when` and know that these are not applicable to this scenario.

I am referring to a HOST unreachable error and not a TASK error. You said that `clear_host_errors` affects `unreachable` hosts. That is exactly what my descriptions are about.

1. I run a playbook.
2. A is reachable. B is unreachable. This is discovered during the `gather_facts` stage.
3. All tasks then run on A only.
4. All the tasks are done. There are no task failures.
5. I then try to use `clear_host_errors` to affect the `unreachable` host B, but `clear_host_errors` doesn't appear to get run at all.
6. The ansible playbook finishes and exits. The playbook (but no tasks) exits with a failed status.

`clear_host_errors` may add unreachable hosts back into the inventory for subsequent tasks, but it certainly does not actually clear any host unreachable errors.

**Comment by bcoca** [comment] 2017-10-31 21:28
the fail status is not only due to host state, but also due to task failures
