### ISSUE TITLE
ec2_group not idempotent (always changed)

### ISSUE THREAD

**Issue by aioue** [ansible/ansible#26286] opened 2017-06-30 13:15 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ec2_group

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /Users/tom/repos/aws-codecommit/ansible-tower/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY
Multiple identical `ec2_group` calls are always `state: changed` when `rules_egress` is not provided.

##### STEPS TO REPRODUCE

If you just this play, state is always changed:

```yaml
- name: create security group
  ec2_group:
    description: foo
    name: bar
    region: eu-central-1
    vpc_id: vpc-123456a
```

Running this play (with `rules_egress`) populated but empty, task is idempotent (OK).

```yaml
- name: create security group
  ec2_group:
    description: foo
    name: bar
    region: eu-central-1
    vpc_id: vpc-123456a
    rules_egress: []
```

##### EXPECTED RESULTS

`State: OK` on second run

##### ACTUAL RESULTS

```
changed: [localhost] => {
    "changed": true,
    "group_id": "sg-01e8c969",
    "invocation": {
        "module_args": {
            "aws_access_key": null,
            "aws_secret_key": null,
            "description": "foo",
            "ec2_url": null,
            "group_id": null,
            "name": "bar",
            "profile": null,
            "purge_rules": true,
            "purge_rules_egress": true,
            "region": "eu-central-1",
            "rules": null,
            "rules_egress": null,
            "security_token": null,
            "state": "present",
            "validate_certs": true,
            "vpc_id": "vpc-123456a"
        }
    }
}
```

**Comment by aioue** [comment] 2017-06-30 13:19
Related: https://github.com/ansible/ansible/issues/7309

**Comment by aioue** [comment] 2017-06-30 15:01
Module is also `changed` when `cidr_ip:` is an empty value inside a `rule`.

**Comment by s-hertel** [comment] 2017-07-10 14:04
I'm able to reproduce that specifying a null value for cidr_ip results in changed == True when it should be False. The same issue exists for specifying group_id as a null value.

But I cannot reproduce the error at all with:
```
- name: create security group
  ec2_group:
    description: foo
    name: bar
    region: us-east-1
    vpc_id: vpc-XXXXXXXX
```
The reason the above may appear changed is if rules/egress rules are added at some point. purge_rules defaults to True, as does purge_rules_egress. I suspect if you specify False for both of those then changed will display as False as you expect. Please let me know if that works as expected.
My output from running that task a second time:
```
ok: [localhost] => {
    "changed": false,
    "failed": false,
    "group_id": "sg-a2d1bfd3",
    "invocation": {
        "module_args": {
            "aws_access_key": null,
            "aws_secret_key": null,
            "description": "foo",
            "ec2_url": null,
            "group_id": null,
            "name": "bar",
            "profile": null,
            "purge_rules": true,
            "purge_rules_egress": true,
            "region": "us-east-1",
            "rules": null,
            "rules_egress": null,
            "security_token": null,
            "state": "present",
            "validate_certs": true,
            "vpc_id": "vpc-XXXXXXXX"
        }
    }
}
META: ran handlers
META: ran handlers

PLAY RECAP ************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```

needs_info

**Comment by aioue** [comment] 2017-07-12 11:25
@s-hertel yes you're right. The module adds in an unspecified outbound rule.

This doesn't seem like good default behaviour, especially as in both cases - the `rules` section of the output is always 'null' (when actually it has added a rule).

- The module shouldn't add unspecified rules to existing groups (it's bad security at the very least)
- When the module does make changes to rules, they should be visible in the debug JSON

### Steps to reproduce

- take this latest commit of `ec2_group.py`

https://github.com/ansible/ansible/blob/e9447e9481c6a1677f7276ccdeed986f47b588aa/lib/ansible/modules/cloud/amazon/ec2_group.py

- write a task that ensures and existing security group already exists

The existing security group has *0* inbound and *0* outbound rules.

```yaml
- name: ensure security group sg-123456
  ec2_group:
    description: Ansible Masters
    name: ansible_master_servers
    region: us-west-1
    vpc_id: vpc-123456
```

#### Output

The task adds in an outbound ALL:ALL rule that was not previously present.

```
Wednesday 12 July 2017  12:13:42 +0100 (0:00:01.040)       0:00:01.115 ********
Using module file /Users/tom/repos/aws-codecommit/ansible-tower/library/ec2_group.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: tom
<127.0.0.1> EXEC /bin/sh -c '/usr/local/opt/python/bin/python2.7 && sleep 0'
changed: [localhost] => {
    "changed": true,
    "group_id": "sg-123456",
    "invocation": {
        "module_args": {
            "aws_access_key": null,
            "aws_secret_key": null,
            "description": "Ansible Masters",
            "ec2_url": null,
            "group_id": null,
            "name": "ansible_master_servers",
            "profile": null,
            "purge_rules": true,
            "purge_rules_egress": true,
            "region": "us-west-1",
            "rules": null,
            "rules_egress": null,
            "security_token": null,
            "state": "present",
            "validate_certs": true,
            "vpc_id": "vpc-0123456"
        }
    }
}
META: ran handlers
META: ran handlers
```

#### Expected behaviour

The task does not modify the existing rules.


#### Second run
The JSON output is _identical_ to the 'changed' result above. Neither mention it has added an unspecified outgoing rule.

```
Wednesday 12 July 2017  12:15:28 +0100 (0:00:00.730)       0:00:00.802 ********
Using module file /Users/tom/repos/aws-codecommit/ansible-tower/library/ec2_group.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: tom
<127.0.0.1> EXEC /bin/sh -c '/usr/local/opt/python/bin/python2.7 && sleep 0'
ok: [localhost] => {
    "changed": false,
    "group_id": "sg-123456",
    "invocation": {
        "module_args": {
            "aws_access_key": null,
            "aws_secret_key": null,
            "description": "Ansible Masters",
            "ec2_url": null,
            "group_id": null,
            "name": "ansible_master_servers",
            "profile": null,
            "purge_rules": true,
            "purge_rules_egress": true,
            "region": "us-west-1",
            "rules": null,
            "rules_egress": null,
            "security_token": null,
            "state": "present",
            "validate_certs": true,
            "vpc_id": "vpc-123456"
        }
    }
}
META: ran handlers
META: ran handlers
```

**Comment by s-hertel** [comment] 2017-07-12 13:41
@aioue Thanks for the extra feedback. I think a solution for this may be to add more helpful output from this module.

Since this module is marked as stableinterface we can't change fundamental behavior. No unspecified inbound rules are ever created, but if no outbound rules are specified then a default all-out outbound rule is created. Docs on this behavior: https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ec2_group.py#L62-L63
To ensure a security group has no outbound rules, I would recommend specifying rules_egress: []

I'm going to label this as not a bug, but will look at adding more helpful output so this kind of thing doesn't catch people by surprise if they haven't read the docs.

notabug

**Closed as completed** 2017-07-12 13:49 UTC
Labels: cloud, aws, affects_2.3, module, bug

**Comment by aioue** [comment] 2017-07-12 13:52
That's unusual behaviour for Ansible (and any declarative config management system).

It makes sense when _creating_ a group, but creation of unspecified rules, when run against an existing group, is a stretch.

Can you vote for interfaces to change? (+1)

There's certainly a bug in the JSON response. `rules` is 'null' both times, yet on the first run, rules are changed, so you can't see what changed, even on maximum verbosity. There's no way of knowing what just happened!

**Comment by s-hertel** [comment] 2017-07-12 14:02
@aioue A community meeting would be a good place to start if you want more opinions on this. Here's the schedule: https://github.com/ansible/community/tree/master/meetings
and the June/July agenda: https://github.com/ansible/community/issues/162
Feel free to link this on the agenda (or you can talk about it during open floor). Since this is an aws topic you could also join the #ansible-aws IRC channel to discuss it.

**Comment by s-hertel** [comment] 2017-07-12 14:07
Also, rules are shown as null because it's the invocation. And no rules are being added anyway, the `egress_rules` are the outbound rules. The invocation output are just the parameters that you've given the module. There is currently no helpful output provided besides changed and the group id. I'm making a pull request to also provide rules/rules_egress data.
