### ISSUE TITLE
Documentation: mixed content warning on docs.ansible.com

### ISSUE THREAD

**Issue by rfc1459** [ansible/ansible#13295] opened 2015-11-25 13:19 UTC
##### Issue Type:

Documentation Report
##### Ansible Version:

N/A
##### Ansible Configuration:

N/A
##### Environment:

N/A
##### Summary:

Visiting any page on https://docs.ansible.com/ which embeds the Google Custom Search box causes a mixed content warning. This is caused by the hardcoded `http` scheme for the GCS script URL.

Also, the GCS script won't load until the user forces the browser to accept mixed content.
##### Steps To Reproduce:

Open a browser and navigate to https://docs.ansible.com/ansible/intro.html
##### Expected Results:

The browser should show the secure connection badge and the search form should show the "Google Custom Search" watermark.
##### Actual Results:

The "mixed content" warning is displayed by the browser and the GCS script is not loaded correctly.

**Comment by bcoca** [comment] 2015-11-26 06:06
I don't get this warning and I've tried with several browsers (on linux), can you give exact method to reproduce this?

**Comment by rfc1459** [comment] 2015-11-26 10:56
On Firefox 42.0 (new profile, no extensions), navigating to https://docs.ansible.com/ansible/intro.html gives a "Parts of this page are not secure" warning on the left of the URL (and the search box won't show the Google watermark).

Chrome 46.0.2490.86 shows on the right of the omnibox the "Load unsafe scripts" grey shield (the Google watermark in the search box doesn't show up as well).

**Comment by bcoca** [comment] 2015-11-27 18:12
grey shield? are you using a script blocker? They normally default to not allow javascript from external sites (which is what the google searchbox is), you might need to allow google.com javascript being loaded on the page.

I'm using the same versions of chrome and firefox and I cannot reproduce the issues

**Comment by rfc1459** [comment] 2015-11-28 00:34
As I said, I reproduced the issue on Chrome 46.0.2490.86 for Linux with a clean profile without any extension or non-default settings.
The "shield" is the standard [mixed content blocked](https://support.google.com/chrome/answer/1342714) error from Chrome.

Looking at the page source, there is indeed a hardcoded `http` script URI for GCS (which also has a naked `&` instead of an `&amp;`:

``` html
<script type="text/javascript" src="http://www.google.com/cse/brand?form=search-form-id&inputbox=search-box-id"></script>
```

Also, the console reports the expected mixed content error:

> Mixed Content: The page at 'https://docs.ansible.com/ansible/intro.html' was loaded over HTTPS, but
> requested an insecure script 'http://www.google.com/cse/brand?form=search-form-id&inputbox=search-box-id'.
> This request has been blocked; the content must be served over HTTPS.

**Comment by dharmabumstead** [comment] 2017-02-13 18:39
Unable to reproduce. I think this one is obsolete. Closing.

**Closed as completed by dharmabumstead** 2017-02-13 18:39 UTC
Labels: affects_2.2, affects_2.3, docs
