### ISSUE TITLE
False positive warning when variable is used in playbook hosts field.

### ISSUE THREAD

**Issue by anryko** [ansible/ansible#23462] opened 2017-04-10 15:07 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

inventory

##### ANSIBLE VERSION

```
ansible 2.4.0 devel
```

##### SUMMARY

Waring is displayed "Could not match supplied host pattern, ignoring: group-{{" when ansible variables are used in playbook hosts.

##### STEPS TO REPRODUCE

```yaml
- name: setup icinga
  hosts: "security_group_{{ env }}-icinga"
```

##### EXPECTED RESULTS

Playbook executed without warnings.

##### ACTUAL RESULTS

Playbook is executed correctly but warning is displayed:

```
 [WARNING]: Could not match supplied host pattern, ignoring: security_group_{{

 [WARNING]: Could not match supplied host pattern, ignoring: }}-icinga
```

**Comment by bcoca** [comment] 2017-04-10 16:09
dupe of #23057

**Closed as completed by bcoca** 2017-04-10 16:09 UTC
Labels: affects_2.4, bug
