### ISSUE TITLE
 Ansible : Windows SSL certification installation.

### ISSUE THREAD

**Issue by deepalikinikar** [ansible/ansible#14387] opened 2016-02-09 13:20 UTC
Hi Guys, 

I have recently started using Ansible for automating. I am trying to automate ssl certificate installation for windows 2008 R2 machines through Ansible. I have created simple power-shell script, my script is perfectly working locally on windows machine. But when I am trying to run same scripts through Ansible it is not working. Although through ansible I can able to install .p7b certificates but facing issues while installing .pfx and .p12 certificates.

Any guidance is highly appreciate.

Here is my sample power-shell script . 

$CertificateName = "certname.pfx"
$CertificatePassword = "XXXXXX"
$ComponentFolder = "c:\Temp"
$CertificatePath = "$ComponentFolder\$CertificateName"
$pfxcert = New-Object system.security.cryptography.x509certificates.x509certificate2
$pfxcert.Import($CertificatePath,$CertificatePassword,"Exportable,PersistKeySet")
## Found above import is not able to write anything to pfxcert object.

echo $pfxcert | Out-File $ComponentFolder\cert_output_pfx_after.txt
$store = Get-Item cert:\LocalMachine\My
$store.Open([System.Security.Cryptography.X509Certificates.OpenFlags]"ReadWrite")
$store.add($pfxcert)
$store.Close()

**Comment by jhawkesworth** [comment] 2016-02-09 16:15
Hi @deepalikinikar 

You don't say what actual error message you get, if any, when you try this.

There is a module for managing windows certificates which is not yet merged here: 

https://github.com/ansible/ansible-modules-extras/pull/1374

Would it be possible for you to to test the above module?  You can copy the files from the PR into your ansible installation temporarily so that you can try the new module out.

It is certainly possible to automate installation of .pfx certificates as I have done it using certutil.exe rather than in powershell code, but I recommend you try the module.

**Comment by deepalikinikar** [comment] 2016-02-09 17:35
As suggested, I tried to use win_certificate module but getting below error .. 
tasks :
- name : install ssl certificate to windows
  win_certificate:
    pfx_file: 'c:\Temp\certname.pfx'
    password: 'XXXXX'
    state: present
    location: LocalMachine
     store_name: 'My'

Error details : 
PLAY [windows] ****************************************************************

GATHERING FACTS ***************************************************************
ok: [winhost]

TASK: [install ssl certificate to windows] ************************************
failed: [winhost] => {"changed": false, "failed": true}
msg: Exception calling "Import" with "3" argument(s): "Array may not be empty or null.
Parameter name:   rawData"

**Comment by deepalikinikar** [comment] 2016-02-09 17:45
As I suspected in my first notes and looking at above error message from your module, looks like 
below $pfxcert.Import object is not populating, though I am passing the correct certificate path and password.
$pfx.import($pfx_file,$password,"Exportable,PersistKeySet")

**Comment by jhawkesworth** [comment] 2016-02-10 21:00
Hi,
What version of powershell and windows management framework do you have running on the Windows machine you are trying to run this on?

It is probably worth reporting that the win_certificate module is not working for you on  https://github.com/ansible/ansible-modules-extras/pull/1374 as the person who wrote the module may have encountered the same problem you are having, or understand where it might be going wrong.

Jon

**Comment by deepalikinikar** [comment] 2016-02-11 10:42
I am using Powershell 3.0 version and Windows Management Framework 3.0 (KB2506143).

**Comment by jhawkesworth** [comment] 2016-02-11 12:15
Ok,
It might be worth trying WMF 4.0 if that is an option for you.
Going back to the original problem as described, I think it is possible that the user that you are running as doesn't have correct rights / permissions / group membership in order to make the change that you want to make.
It is worth checking the windows event log.
Also ensure the user that you are running ansible as is an Administrator or member of WinRMRemoteUsers__ group on the remote windows machine.

Hope this helps.

Jon

**Comment by deepalikinikar** [comment] 2016-02-11 13:06
I am using local admin user and using that User I can able to install some .exe,  Enabled IIS features and also able to install .p7b certificate through Ansible. So definitely user I am using certainly have correct permissions. As suggested I was checking windows event log, I can't see anything there with respect to Ansible. Does Ansible server generate any logs which I can refer?

**Comment by jhawkesworth** [comment] 2016-02-11 15:28
Perhaps then you have a policy in place that stops this modification.

I got .pfx installed using certutil.exe.  If you don't have a copy of certutil.exe already it is available by installing AD-Certificates role.

Looking at my playbook though I realize that I also had to grant access to some users so they could access the certs in 'My computer' store, so I wonder if the problem is not that the cert isn't stored, but that it isn't readable by the user who is trying to access it.

**Comment by deepalikinikar** [comment] 2016-02-17 09:28
After debugging I found below errors. Any suggestion how can I fix this?
Exception calling \"Import\" with \"3\" argument(s): \"Access denied._x000D__x000A_

changed: [winhost] => {"changed": true, "rc": 0, "stderr": "#< CLIXML\r\n<Objs Version=\"1.1.0.1\" xmlns=\"http://schemas.microsoft.com/powershell/2004/04\"><S S=\"Error\">Exception calling \"Import\" with \"3\" argument(s): \"Access denied._x000D__x000A_</S><S S=\"Error\">\"_x000D__x000A_</S><S S=\"Error\">At C:\Users\Ansible\AppData\Local\Temp\ansible-tmp-1455701150.88-91453269349144_x000D__x000A_</S><S S=\"Error\">\import_cert.ps1:48 char:9_x000D__x000A_</S><S S=\"Error\">\+         $pfx.import(\"$location\$name\",\"$password\",\"Exportable,PersistKeySet\")_x000D__x000A_</S><S S=\"Error\">\+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~_x000D__x000A_</S><S S=\"Error\">    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException_x000D__x000A_</S><S S=\"Error\">    + FullyQualifiedErrorId : CryptographicException_x000D__x000A_</S><S S=\"Error\"> _x000D__x000A_</S></Objs>", "stdout": ""}

**Comment by jhawkesworth** [comment] 2016-02-17 16:40
Typically Access Denied means your user doesn't have rights to access something.  Its a rather vague error message and doesn't really give a clue to what you are missing unfortunately.

Looks like others have hit this when attempting to import certificates - see https://social.technet.microsoft.com/Forums/en-US/925a0280-381f-4998-8139-12461d4d7fae/import-certificate-access-is-denied-error-code-80070005?forum=systemcenteressentials

http://stackoverflow.com/questions/18637238/certificate-installation-access-denied-error

Hope the above links are of use to you.

**Comment by jhawkesworth** [comment] 2016-06-23 12:37
For info I had to use win_acl to ensure the user that an app was running as had access to the store (as below).

However as mentioned I was using certutil.exe to install, rather than powershell.

I imagine it might be possible to find out what exactly is causing access denied to be returned using sysinternals' Process Monitor - there's an introduction to Process Monitor here: http://www.howtogeek.com/school/sysinternals-pro/lesson5/all/

```
- name: grant user access to the certs 
  win_acl:
     src: 'C:\ProgramData\Microsoft\Crypto\RSA\MachineKeys'
     user: "{{domain}}\\{{app_user}}"
     rights: 'Read'
     type: 'allow'
     state: present
     inherit: 'ContainerInherit, ObjectInherit'
     propagation: 'None'
```

**Comment by andmos** [comment] 2016-11-22 20:02
I am sorry if I ask this question in the wrong issue, but here goes. While waiting on [the new certificate module](https://github.com/ansible/ansible-modules-extras/pull/1374) we are installing certificates in the following way: 
```
win_shell: Import-PfxCertificate -filepath "{{ certificatePath }}" -certStorelocation cert:\\localmachine\\My -password $(ConvertTo-SecureString -AsPlainText -Force -String "{{ organization_key }}")
```
This works fine, but I have not found any good way to skip the task if the certificate is already installed. I know that you can run `SET-LOCATION CERT:\LOCALMACHINE` in Powershell, which provides access to the certificate store as a filesystem, but it is possible to do something like `creates=cert:\localmachine\path\to\my\cert` ? What is the best strategy here?

**Comment by jhawkesworth** [comment] 2017-01-09 14:54
@andmos - maybe best to ask such questions on ansible-project google group as more people read that than the git issues.

You could probably do it in two steps.  The first step would need to use win_shell to register a var to see whether the certificate exists

Not tested but you could probably find the cert by thumbprint like this

Get-ChildItem CERT:\LocalMachine\My |where {$_.Thumbprint -match $ucthumb} | sort $_.NotAfter -Descending | select -first 1 -erroraction STOP

then in the second step use a when: condition so that the win_shell: Import-PfxCertificate ... is only run when the certificate thumbprint doesn't match

**Comment by andmos** [comment] 2017-01-09 18:36
@jhawkesworth I found a way to do this using the `creates=` option in the `win_shell` module: 

```
win_shell: Import-PfxCertificate -filepath C:\\WildcardCert.pfx -certStorelocation cert:\\localmachine\\My -password $(ConvertTo-SecureString -AsPlainText -Force -String "{{ wildcard_certificate_key }}")
     args:
       creates: "{{ Wildcard_certificate_creates }}"
```
Where the `"{{ Wildcard_certificate_creates }}"` is on the form 
`Cert:\\LOCALMACHINE\\My\\[thumbprint]`.

Leaving this here in case someone else googles across the issue 👍

**Comment by jhawkesworth** [comment] 2017-01-09 20:08
@andmos nice workaround!
@deepalikinikar - can you use the above suggestion?  If so let's close this issue?

**Comment by jhawkesworth** [comment] 2017-02-13 08:15
Since this is more of a 'how to' question than an actual bug in Ansible, and @deepalikinikar has not responded for over 1 month I am going to close this issue.

**Closed as completed by jhawkesworth** 2017-02-13 08:15 UTC
Labels: windows, affects_2.2, affects_2.3, bug

**Comment by dagwieers** [comment] 2017-07-08 13:26
So there is a new module win_certificate in PR #25837 that is ready to be merged.
Feedback from users is very much appreciated.
