### ISSUE TITLE
locale_gen module fails if a certain file does not exist beforehand

### ISSUE THREAD

**Issue by nickjj** [ansible/ansible#7965] opened 2014-06-27 21:11 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

1.6.2
##### Environment:

Ubuntu 12.04 LTS (running on travis ci)
##### Summary:

The `locale_gen` module fails with `msg: /etc/locale.gen and /var/lib/locales/supported.d/local are missing. Is the package “locales” installed?` when that file does not exist on the system before hand even when the `locales` package is installed.

The work around is to conditionally touch this file if it does not exist which seems a bit user unfriendly. Maybe this logic could be encapsulated in the module itself?

Here's a travis build failing:
https://travis-ci.org/nickjj/ansible-locale/builds/28623557

Here's a travis build working:
https://travis-ci.org/nickjj/ansible-locale/builds/28626066

Without this snippet running before `locale_gen` then it fails:
https://github.com/nickjj/ansible-locale/blob/v0.1.1/tasks/main.yml#L14=L20
##### Steps To Reproduce:

```
- name: ensure the system locale is configured
  locale_gen: name=en_US.UTF-8 state=present
```
##### Expected Results:

The locale to be written out to a config file and then enabled.
##### Actual Results:

It failed with the error posted in the summary.

**Comment by Lekensteyn** [comment] 2014-07-18 10:27
Duplicate of #7289

**Comment by mpdehaan** [comment] 2014-09-29 20:27
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Closed as completed by mpdehaan** 2014-09-29 20:27 UTC
Labels: bug
