### ISSUE TITLE
yum/apt with_items ignores filters, prefixes

### ISSUE THREAD

**Issue by Habbie** [ansible/ansible#6592] opened 2014-03-20 10:02 UTC
##### Issue Type:

Bug report
##### Ansible Version:

ansible 1.4.3
##### Environment:

RHEL 6.5 from RHEL 6.5; bug appears to be generic though.
##### Summary:

The hack at https://github.com/ansible/ansible/blob/devel/lib/ansible/runner/__init__.py#L586 appears to break filter usage (name={{item | basename }}).
##### Steps To Reproduce:

This code:

```
  - name: install RPMs
    yum: name=/root/{{ item }}
    notify: restart recursor
    with_items:
    - '{{ recursor_rpm_url | basename }}'
    - '{{ pdnsmgrd_rpm_url | basename }}'
```

Should behave identically to:

```
  - name: install RPMs
    yum: name=/root/{{ item | basename }}
    notify: restart recursor
    with_items:
    - '{{ recursor_rpm_url }}'
    - '{{ pdnsmgrd_rpm_url }}'
```

However, the second version feeds the full URLs (that I have in those vars) to yum.

In both cases /root/ is dropped as well, but the first version accepts this because ansible is running from /root anyway.
##### Expected Results:

Both versions do the same, honoring /root and | basename.
##### Actual Results:

One version works, mostly by accident. The other does not work at all.

**Comment by Habbie** [comment] 2014-03-20 10:14
I should clarify that "does not work at all" means "it feeds the URLs to the yum module which then proceeds to do nothing at all, instead of upgrading the package". This might be an unrelated bug in the yum module.

**Comment by mpdehaan** [comment] 2014-03-20 12:05
yum when used with "with_items" will join the arguments with commas.  This is more or less a duplicate of #5166 which says to not engage this behavior in the same amount of places, so I'm going to close this and merge these two tickets together, the other will contain a reference to this and this can be solved jointly.  Thanks!

**Closed as completed by mpdehaan** 2014-03-20 12:05 UTC
Labels: packaging

**Comment by Habbie** [comment] 2014-03-20 12:06
Thanks, missed that ticket!
