### ISSUE TITLE
Included tasks use different variable definitions in roles activated by the role dependency mechanism

### ISSUE THREAD

**Issue by briceburg** [ansible/ansible#4642] opened 2013-10-22 17:06 UTC
Included tasks use different variable definitions in roles activated by the role dependency mechanism.
- ansible 1.4 -devel 214b0b052c3d54b58a531b0f7fb401ec3c0229f5
# Description

The alpha->beta scope, `port` when called from roles/beta/`tasks/main.yml` acts like a `var`, whereas when called from roles/beta/`tasks/include.yml` port acts like a `default`.
# Demonstration

`main.yml` :

```

---
# beta role tasks

- debug: msg="beta role (tasks/main.yml) - port - expected beta-port, got {{ port }}"
  failed_when: "port != 'beta-port'"
  ignore_errors: True

- { include: "include.yml"}
```

`include.yml` :

```

---
# beta role included task(s)

- debug: msg="beta role (tasks/include.yml) - port - expected beta-port, got {{ port }}"
  failed_when: "port != 'beta-port'"
  ignore_errors: True
```

exhibit#2, 

functional demo:
 https://github.com/briceburg/ansible-variable-scoping/tree/master/simple_include

Edit: Improved description to include @aboyett synopsis https://github.com/ansible/ansible/issues/4642#issuecomment-31992722

**Comment by mpdehaan** [comment] 2013-10-23 18:03
This is a duplicate of the other Brice ticket so I'm closing this one.

**Comment by jctanner** [comment] 2013-11-01 19:17
@briceburg This is not quite a duplicate of #4641 so I'm going to reopen. Here's the output from your example git repo:

```
jtanner@u1304:~/issues/4641-role_dep_var_precedence/ansible-variable-scoping/simple_include$ ansible-playbook -i hosts playbook.yml

PLAY [test variable scoping] **************************************************

GATHERING FACTS ***************************************************************
ok: [localhost]

TASK: [beta | debug msg="beta role (tasks/main.yml) - port - expected beta-port, got {{port}}"] ***
ok: [localhost] => {
    "failed": false,
    "failed_when_result": false,
    "item": "",
    "msg": "beta role (tasks/main.yml) - port - expected beta-port, got beta-port"
}

TASK: [beta | debug msg="beta role (tasks/include.yml) - port - expected beta-port, got {{port}}"] ***
failed: [localhost] => {"failed": true, "failed_when_result": true, "item": "", "verbose_always": true}
msg: beta role (tasks/include.yml) - port - expected beta-port, got alpha-port
...ignoring

TASK: [alpha | debug msg="alpha role (tasks/main.yml) - port - expected alpha-port, got {{port}}"] ***
ok: [localhost] => {
    "failed": false,
    "failed_when_result": false,
    "item": "",
    "msg": "alpha role (tasks/main.yml) - port - expected alpha-port, got alpha-port"
}

PLAY RECAP ********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0
```

So we know from #4641 that a role dependency will execute with vars being passed from the parent (alpha vars --> beta). In this case we are seeing beta run main.yml with alphas vars, but then beta runs an included playbook 'include.yml' with beta's vars. This does seem inconsistent, so I will investigate and talk to @jimi-c about what we expect here.

**Comment by jctanner** [comment] 2013-11-01 19:23
@briceburg This is also expected behavior.

**Closed as completed by jctanner** 2013-11-01 19:23 UTC

**Comment by briceburg** [comment] 2013-11-01 19:30
Hah... pretty ridiculous. They should all work one way. 

I've spent a lot of time compiling these issues && given up on our refactor because of this weirdness. Hopefully it'll be addressed as weird in the future; until then I hope the new include_vars ( https://github.com/ansible/ansible/blob/devel/library/utilities/include_vars )  can bail us out.

**Comment by aboyett** [comment] 2014-01-10 00:36
> So we know from #4641 that a role dependency will execute with vars being passed from the parent (alpha vars --> beta). In this case we are seeing beta run main.yml with alphas vars, but then beta runs an included playbook 'include.yml' with beta's vars. This does seem inconsistent, so I will investigate and talk to @jimi-c about what we expect here.

@jctanner, that description of what is going on isn't quite correct. The beta role isn't including a playbook, it is including tasks.

from docsite/rst/playbook_roles.rst:

> At a basic level, including task files allows you to break up bits of configuration policy into smaller files.  Task includes pull in tasks from other files.

I would expect this to mean that I can take a series of tasks that would have been in roles/xyz/tasks/main.yml and split them up into roles/xyz/tasks/{foo,bar}.yml without any functionality change assuming the contents of roles/xyz/tasks/main.yml are

```
---
- include: foo.yml
- include: bar.yml
```

This bug appears to demonstrate the opposite. When the alpha role calls the beta role as a dependency it exhibits dissimilar behaviors:
- when a task is defined in roles/beta/tasks/main.yml: `port` evaluates to 'beta_port' -- despite this being defined in roles/beta/defaults/main.yml so the alpha definition of the var should override
- when a task is defined in roles/beta/tasks/include.yml and included via roles/beta/tasks/main.yml: `port` evaluates to 'alpha_port' -- this is what I would expect given that beta defines `port` as a default, but contradicts the behavior exhibited by the preceding task in main.yml

To reiterate, in the alpha->beta scope, `port` when called from roles/beta/tasks/main.yml acts like a var, whereas when called from roles/beta/tasks/include.yml `port` acts like a default. Odd considering it is defined as a default.

Some more clarification as to why this is expected behavior would be appreciated.

Edit: I flipped default and var in the initial post.

**Comment by briceburg** [comment] 2014-01-25 03:58
@aboyett have you made sense of this? believe it allows a logical approach to abstracted playbook organization (that I wasn't able to accomplish partly due to bugs/workarounds).
