### ISSUE TITLE
add support for group roles to postgresql_user

### ISSUE THREAD

**Issue by tom-clx** [ansible/ansible#11035] opened 2015-05-19 21:09 UTC
Issue Type: Feature Idea
Ansible Version: 1.9.0.1
Ansible Configuration: Nothing unusual
Environment: N/A
Summary:

The postgresql_user module doesn't have any provision to manage role membership within other roles (groups). This makes it impossible to manage complex role structures using postgresql_user.

This is typically handled with a grant, or create/alter role syntax:

GRANT role_name [, ...] TO role_name [, ...] 

-or-

CREATE ROLE name [ [ WITH ] option [ ... ] ]
...snip...
IN ROLE role_name [, ...]

Relevant documentation links:
http://www.postgresql.org/docs/9.2/static/sql-createrole.html
http://www.postgresql.org/docs/9.2/static/sql-grant.html

Steps To Reproduce:
Here is the expected playbook, with 'in_roles' parameter added to the last play.

```
- hosts: dev_database

  vars_prompt:
  - name: pg_user
    prompt: "PostgreSQL username"
    private: no

  - name: pg_pass
    prompt: "PostgreSQL password"
    private: yes

  vars:
    myuserprivs: LOGIN,NOREPLICATION
    pggroups:
      - {name: 'mygroup'}
    pgusers:
      - {name: 'myuser', pass: 'apassword', privs: "{{ myuserprivs }}" }

  - name: create postgres group roles.
    with_items: pggroups
    postgresql_user: >
      login_user={{ pg_user }}
      login_password={{ pg_pass }}
      name={{ item.name }}
      db=postgres

  - name: create postgres pgusers.
    with_items: pgusers
    postgresql_user: >
      login_user={{ pg_user }}
      login_password={{ pg_pass }}
      name={{ item.name }}
      db=postgres
      password={{ item.pass }}
      role_attr_flags={{ item.privs }}
      in_roles=mygroup
```

Expected Results:

I would expect that ansible generate SQL equivalent to the following:

```
CREATE ROLE mygroup;
CREATE ROLE myuser WITH LOGIN NOREPLICATION PASSWORD 'apassword' IN ROLE mygroup;
```

Actual Results:

**Comment by kamikaze** [comment] 2016-07-18 23:25
Yeah, please do this

**Comment by MannerMan** [comment] 2016-09-07 09:30
It's already possible to create/manage group roles with postgresql_user and postgresql_privs, although it's not too intuitive.

```
#Create postgres role "role1"
  - name: Create postgres role
    postgresql_user: >-
      name=role1
      role_attr_flags="NOLOGIN,NOSUPERUSER,INHERIT,NOCREATEDB,NOCREATEROLE,NOREPLICATION"
      state=present
    become: yes
    become_user: "{{ postgresql_admin_user }}"

#Create postgres user "user1"
  - name: Create postgres user
    postgresql_user: >-
      name=user1
      password=user1
      encrypted=True
      state=present
    become: yes
    become_user: "{{ postgresql_admin_user }}"

#Make "user1" member of "role1"
  - name: Setup user memberships
    postgresql_privs: >
        database=postgres
        roles=user1
        objs=role1
        type=group
    become: yes
    become_user: "{{ postgresql_admin_user }}"

#revoke access to public group from "database1"
  - name: Revoke public access to database
    postgresql_privs: >
      db=postgres
      state=absent
      priv=CONNECT,TEMPORARY
      obj=database1
      role=public
      type=database
    become: yes
    become_user: "{{ postgresql_admin_user }}"

#Grant "role1" (and thereby "user1") full access to "database1"
  - name: Setup group privileges
    postgresql_privs: >
        db=postgres
        role=role1
        objs=database1
        privs=ALL
        type=database
    become: yes
    become_user: "{{ postgresql_admin_user }}"
```

**Comment by jimi-c** [comment] 2017-01-06 21:10
Per the above, it seems the postgresql modules writers have made the design decision to separate priv creation from user creation, so I'm going to close this at this time.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2017-01-06 21:10 UTC
Labels: affects_1.9, feature, postgresql

**Comment by elgow** [comment] 2017-02-15 23:11
Since I'm on github but not the ansible mailing list I'll comment here in spite of the advice above. 

I think it is a mistake to close this issue as a valid design choice on the part of the module authors. The authors of the postgresql database clearly made the opposite choice. They provide the feature of group roles with inheritance for a purpose, and it is widely used for that purpose. It is an extremely unwise design choice to make this feature inaccessible from the ansible module.

**Comment by kamikaze** [comment] 2017-02-15 23:18
this is stupid

**Comment by elgow** [comment] 2017-02-15 23:48
The third example in the comment by MannerMan was just pointed out to me. This does support the use of the postgresql feature, so that solves the main problem. The remaining problem, which should be regarded as a documentation bug, is that the ansible documents do not describe the usage shown in the example. The use of the objs parameter to hold a group role name is not mentioned in the documents. Assuming it works, which I've not yet tried, this important case should be documented.

**Comment by 3manuek** [comment] 2017-12-05 17:43
The problem is how the module implements groups as a privilege, not as an object by itself. It will be  more intuitive to count with a `postgresql_group`, which can  internally inherit the `postgresql_user` implementation but using the corresponding defaults on the database. 

Although, it must be mentioned that the current implementation actually relies more on the concept of `role` over `user` as stated in the [postgresql docs](https://www.postgresql.org/docs/10/static/user-manag.html):

```
The concept of roles subsumes the concepts of “users” and “groups”. In PostgreSQL versions
 before 8.1, users and groups were distinct kinds of entities, but now there are only roles. 
Any role can act as a user, a group, or both.
```
