### ISSUE TITLE
ERROR! need more than 2 values to unpack while using ansible commands, caused by group names with spaces in ini inventory

### ISSUE THREAD

**Issue by engbalaji** [ansible/ansible#13917] opened 2016-01-15 18:34 UTC
I'm using ansible 2.0.0.1 and while excuting any command on the remote server or local server, I'm getting following error

[root@wautomation-tst01 ansible]# ansible werindbalajil01 -l ping
ERROR! need more than 2 values to unpack

I trying reinstalling, but still getting the same issue 

anybody help?
##### Issue Type:

Can you help us out in labelling this by telling us what kind of ticket this this?  You can say:
- Bug Report
##### Ansible Version:

Ansible 2.0.0.1
##### Ansible Configuration:

Nothing, i just finished installing the ansible in Oracle Linuc 6.4 (same kernal as RHEL 6), after the installation when i try to execute any ansible core commands (such as Ping, file or Setup) are showing following error
##### Environment:

OEL 6.3
[root@wautomation-tst01 ansible]# uname -a
Linux wautomation-tst01.us.int.rci.com 2.6.39-400.109.4.el6uek.x86_64 #1 SMP Mon Jul 22 11:44:00 PDT 2013 x86_64 x86_64 x86_64 GNU/Linux

Python version 
[root@wautomation-tst01 ansible]# python --version
Python 2.6.6
##### Summary:

When i try to use the basic ansible command it coming with following error 
ERROR! need more than 2 values to unpack
##### Steps To Reproduce:

running any ansuble core commands. E.g

[root@wautomation-tst01 ansible]# ansible 127.0.0.1 -m ping
ERROR! need more than 2 values to unpack
[root@wautomation-tst01 ansible]# ansible -vvv 127.0.0.1 -m ping
Using /etc/ansible/ansible.cfg as config file
ERROR! need more than 2 values to unpack
##### Expected Results:

ping command output
##### Actual Results:

[root@wautomation-tst01 ansible]# ansible -vvv 127.0.0.1 -m ping
Using /etc/ansible/ansible.cfg as config file
ERROR! need more than 2 values to unpack

**Comment by bcoca** [comment] 2016-01-15 19:03
Can You Help Us Out?
====================

Thanks for filing a ticket! I am the friendly GitHub Ansibot.

It looks like you might not have filled out the issue description based on our standard issue template.  You might not have known about that, and that's ok too, we'll tell you how to do it.

We have a standard template because Ansible is a really busy project and it helps to have some standard information in each ticket, and GitHub doesn't yet provide a standard facility to do this like some other bug trackers.  We hope you understand as this is really valuable to us!.

Solving this is simple: please copy the contents of this [template](https://raw.githubusercontent.com/ansible/ansible/devel/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket.  That's it!

If You Had A Question To Ask Instead
====================================

If you happened to have a "how do I do this in Ansible" type of question, that's probably more of a user-list question than a bug report, and you should probably ask this question on the project mailing list instead.

However, if you think you have a bug, the report is the way to go!  We definitely want all the bugs filed :)  Just trying to help!

About Priority Tags
===================

Since you're here, we'll also share some useful information at this time.

In general tickets will be assigned a priority between P1 (highest) and P5, and then worked in priority order. We may also have some follow up questions along the way, so keeping up with follow up comments via GitHub notifications is a good idea.

Due to large interest in Ansible, humans may not comment on your ticket immediately.

Mailing Lists
=============

If you have concerns or questions, you're welcome to stop by the ansible-project or ansible-development mailing lists, as appropriate.  Here are the links:

  * https://groups.google.com/forum/#!forum/ansible-project - for discussion of bugs and how-to type questions
  * https://groups.google.com/forum/#!forum/ansible-devel - for discussion on how to implement a code change, or feature brainstorming among developers

Thanks again for the interest in Ansible!

**Comment by engbalaji** [comment] 2016-01-15 20:06
updated as suggested

**Comment by bcoca** [comment] 2016-01-15 20:09
can you run the command with -vvvv? and post the output

**Comment by engbalaji** [comment] 2016-01-15 20:24
[root@wautomation-tst01 ansible2]# ansible -vvvv werindbalajil01 -m ping
Using /etc/ansible/ansible.cfg as config file
ERROR! need more than 2 values to unpack

**Comment by sivel** [comment] 2016-01-15 20:51
It sounds to me like this is failing at a point before the playbook is even read.  Some place where the error is being caught in a way that the traceback wouldn't be displayed.

If you run with `ANSIBLE_DEBUG` such as the following example, what do you get?

```
ANSIBLE_DEBUG=1 ansible -vvvv werindbalajil01 -m ping
```

**Comment by engbalaji** [comment] 2016-01-15 20:55
[root@wautomation-tst01 ansible2]# ANSIBLE_DEBUG=1 ansible -vvvv werindbalajil01 -m ping
 23062 1452015876.19391: starting run
Using /etc/ansible/ansible.cfg as config file
ERROR! need more than 2 values to unpack

**Comment by sivel** [comment] 2016-01-15 21:30
This is rather strange.  In order for the message to be prefixed with `ERROR!` the real exception would have to be caught, and re-raised as an `AnsibleError`, that only is passed `e` or `str(e)`, and there just aren't many of those that I can see in the execution path of an adhoc command, especially prior to loading callbacks.

With `-vvvv` we should see something like the following if callbacks had been loaded yet:

```
Loaded callback minimal of type stdout, v2.0
```

So this happens before `tqm.run()` is called.

Just documenting some things so others have insight, and I know where I was :)

**Comment by sivel** [comment] 2016-01-15 21:32
@engbalaji what is in your `/etc/ansible/ansible.cfg` file?

**Comment by sivel** [comment] 2016-01-15 21:32
Also, can we see what is in your inventory file?

**Comment by engbalaji** [comment] 2016-01-15 21:33
using a default one, copied from example dir, do you need a copy?

**Comment by dropqa** [comment] 2016-01-18 02:14
I'm in the exactly same situation as @engbalaji . But I am using 
uname -a
Linux ansible224 3.13.0-32-generic # 57-Ubuntu SMP Tue Jul 15 03:51:12 UTC 2014 i686 i686 i686 GNU/Linux
python --version
Python 2.7.6

**Comment by ktaragorn** [comment] 2016-01-19 03:35
If either of @dropqa or @engbalaji 's Inventories have group names with spaces, this is a duplicate of #13960. I was able to reproduce it.

**Comment by dropqa** [comment] 2016-01-19 06:54
Thanks a lot. I replaced group names with spaces in my inventory file, then the problem solved. Thanks again. :)

**Comment by ktaragorn** [comment] 2016-01-19 06:56
Glad I could help, can the ticket be closed as a duplicate of the other one?

**Comment by bcoca** [comment] 2016-01-19 14:25
so we 'broke' the names with spaces on purpose as this creates many problems down the line, but keeping this open to make sure we give a proper error as the 'unpacking' is not clear and hard to trace.

**Comment by engbalaji** [comment] 2016-01-19 16:06
@ktaragorn - thanks it worked. Much appreciate it.

**Comment by jimi-c** [comment] 2016-01-19 17:11
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2016-01-19 17:11 UTC
Labels: P2, bug

**Comment by Excedrin** [comment] 2016-04-07 21:16
This fix breaks having hosts that start with a range. In inventory:

[section]
[01:50]whatever.foo.bar

fails now and used to work. http://docs.ansible.com/ansible/intro_inventory.html doesn't mention removal of this functionality or this new limitation that a range can't start a hostname.

**Comment by paruff** [comment] 2017-12-08 22:33
same error with duplicate group names :-(
