### ISSUE TITLE
copy module adds extra newlines

### ISSUE THREAD

**Issue by sruon** [ansible/ansible#9367] opened 2014-10-17 15:23 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.2
##### Environment:

Management: Mac OS X
Target: Debian stable
##### Summary:

I have a SSL certificate stored in a vault file, one of my task copies it to a file (using the copy module) on the remote server. 
This worked perfectly on 1.7.1, on 1.7.2 it adds an extra newline after every line which causes my webserver to fail.

Summary: copy module using content from ansible-vault variable -> extra newlines in target file. Bug is not present in 1.7.1. Possibly unrelated to ansible-vault.
##### Steps To Reproduce:
1. Create a vault file

```
ssl_crt: |
  -----BEGIN CERTIFICATE-----
  Content goes here
  -----END CERTIFICATE-----
```
1. Have a task using vault (include the vault vars file)

```
- name: Copy the SSL certificate to the remote server
  copy: content="{{ ssl_crt }}" dest=/etc/ssl/mycert.crt
```
##### Expected Results:

```
/etc/ssl# cat -e mycert.crt
-----BEGIN CERTIFICATE-----$
Content goes here$
-----END CERTIFICATE-----$
```
##### Actual Results:

```
/etc/ssl# cat -e mycert.crt
-----BEGIN CERTIFICATE-----$
$
Content goes here$
$
-----END CERTIFICATE-----$
```

**Comment by mpdehaan** [comment] 2014-10-19 22:54
As this is a module related ticket, please file these at https://github.com/ansible/ansible-modules-core ... though I think we may already have a duplicate of this.

Thanks!

**Closed as completed by mpdehaan** 2014-10-19 22:54 UTC
