### ISSUE TITLE
Using local_action: in a playbook prevents completion with a Python error

### ISSUE THREAD

**Issue by keltia** [ansible/ansible#14744] opened 2016-03-02 10:26 UTC
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.0.2
  config file = /usr/local/etc/ansible/ansible.cfg
  configured module search path = /opt/local/share/ansible
```
##### Ansible Configuration:

Nothing changed from default ansible.cfg.
##### Environment:

Host: OS X 10.11.3, Ansible installed with Homebrew, Python 2.7.10
Target: same
##### Summary:

My long-time running playbooks are generating a Python error every time I use local_action:. It started around 2.0-ish.
##### Steps To Reproduce:

I use a playbook to update various parts of my system, namely:
- Homebrew data in /usr/local
- MacPorts
- Ruby rbenv data
- my own git/Hg repositories

The playbook itself is very simple:

```

---
# Main driver

- hosts: localhost
  gather_facts: no
  vars:
  roles:
  - brew
  - macports
  - rbenv
  - mine
```

The first role itself:
`roles/tasks/main.yml`

```

---
# Update Homebrew

- name: Update homebrew
  local_action: shell {{ tsocks }} brew update
                chdir="/usr/local"
  tags: [ doit, brew ]
```
##### Expected Results:

It should just run the command.
##### Actual Results:

Trying to keep the generated script and more verbose

```
env ANSIBLE_KEEP_REMOTE_FILES=1 ansible-playbook -vvv -i push-blog/hosts -e "home=$HOME tsocks=''" update-software/main.yml
Using /usr/local/etc/ansible/ansible.cfg as config file
1 plays in update-software/main.yml

PLAY ***************************************************************************

TASK [brew : Update homebrew] **************************************************
task path: /Users/roberto/Src/Perso/HG/ansible-playbooks/update-software/roles/brew/tasks/main.yml:4
ESTABLISH LOCAL CONNECTION FOR USER: roberto
localhost EXEC ( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1456914018.76-101146047866084 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1456914018.76-101146047866084 )" )
localhost PUT /var/folders/57/rgkx46jn3x944g_9l5tw13m0000159/T/tmpRslVIn TO /Users/roberto/.ansible/tmp/ansible-tmp-1456914018.76-101146047866084/command
localhost EXEC LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /Users/roberto/.ansible/tmp/ansible-tmp-1456914018.76-101146047866084/command
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/Users/roberto/.ansible/tmp/ansible-tmp-1456914018.76-101146047866084/command", line 2377, in <module>
    main()
  File "/Users/roberto/.ansible/tmp/ansible-tmp-1456914018.76-101146047866084/command", line 118, in main
    module = CommandModule(argument_spec=dict())
  File "/Users/roberto/.ansible/tmp/ansible-tmp-1456914018.76-101146047866084/command", line 740, in __init__
    self._check_arguments(check_invalid_arguments)
  File "/Users/roberto/.ansible/tmp/ansible-tmp-1456914018.76-101146047866084/command", line 1284, in _check_arguments
    for (k,v) in self.params.items():
AttributeError: 'tuple' object has no attribute 'items'

fatal: [localhost -> localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "command"}, "parsed": false}

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1
```

this function in the generated script is exploding, as if params was no dict but an array or something.

```
    def _check_arguments(self, check_invalid_arguments):
        for (k,v) in self.params.items():                                 <<<<<<<<<<<< HERE

            if k == '_ansible_check_mode' and v:
                if not self.supports_check_mode:
                    self.exit_json(skipped=True, msg="remote module does not support check mode")
                self.check_mode = True

            elif k == '_ansible_no_log':
                self.no_log = self.boolean(v)

            elif k == '_ansible_debug':
                self._debug = self.boolean(v)

            elif check_invalid_arguments and k not in self._legal_inputs:
                self.fail_json(msg="unsupported parameter for module: %s" % k)
```

**Comment by keltia** [comment] 2016-03-02 16:11
2.0.1.0 does not solve that.  Why params could be anything else than a dict?

**Comment by bcoca** [comment] 2016-03-02 23:19
I cannot reproduce, even though the formatting looks wrong, as you are using k=v pairs but also multiline

**Comment by keltia** [comment] 2016-03-03 00:08
This playbook has been working for more than one year, only broke recently.  What can I do to debug this?  It may be something local but what?

**Comment by sivel** [comment] 2016-03-03 00:17
This looks like the problem people experienced when they were running the v1.9 command module with v2 Ansible.

Due to a difference in how arguments are passed between v1 and v2, this error would occur.

**Comment by keltia** [comment] 2016-03-27 13:15
I have tried removing all traces of Ansible and then reinstall it from Homebrew. Same error.  Removed it again and installed the macports version and it works.  Something might be broken in Homebrew python and/or ansible.

**Comment by bcoca** [comment] 2016-03-27 20:44
closing then, but keeping as "yet another reason we don't recommend installing Ansible via homebrew"

**Closed as completed by bcoca** 2016-03-27 20:44 UTC
