### ISSUE TITLE
[ansible-galaxy] `--help` and `--version` throw an error

### ISSUE THREAD

**Issue by paulmenzel** [ansible/ansible#14856] opened 2016-03-08 07:58 UTC
Debian 8.3 (jessie) with Ansible 2.0.1.0-1~bpo8+1 from Debian Backports is used.

```
$ ansible-galaxy --help
Usage: ansible-galaxy [delete|import|info|init|install|list|login|remove|search|setup] [--help] [options] ...

Options:
  -h, --help     show this help message and exit
  -v, --verbose  verbose mode (-vvv for more, -vvvv to enable connection
                 debugging)
  --version      show program's version number and exit
ERROR! Missing required action
$ echo $?
5
$ ansible-galaxy --version
Usage: ansible-galaxy [delete|import|info|init|install|list|login|remove|search|setup] [--help] [options] ...

Options:
  -h, --help     show this help message and exit
  -v, --verbose  verbose mode (-vvv for more, -vvvv to enable connection
                 debugging)
  --version      show program's version number and exit
ERROR! Missing required action
```

**Comment by bcoca** [comment] 2016-03-08 14:28
dupe of #12004

**Closed as completed by bcoca** 2016-03-08 14:28 UTC
