### ISSUE TITLE
unarchive just one file

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#12292] opened 2015-09-09 14:24 UTC
**issue type**  : Feature Idea
**ansible version**  : 1.9.3

it will be cool if we could extract only one file like this : 

```
unarchive: src={{ item.value.url }} dest={{ target_path }}{{ item.value.app_name }} path={{ item.value.path }}
```

where  `path` parm is the path of the file inside the archive 

this could give 

```
unarchive: src=http://myrepository.com/dir/foobar-1.2.3.tar.gz dest=/home/foxmask/tomcat/webapps/foobar.war path=./applications/foobar.war
```

thus this will mimic this command : 

```
cd /home/foxmask/tomcat/webapps && wget -O - http://myrepository.com/dir/foobar-1.2.3.tar.gz | tar -xvzf - ./applications/foobar.ear
```

**Comment by bcoca** [comment] 2015-09-09 15:07
duplicate of https://github.com/ansible/ansible-modules-core/issues/2037, also in the wrong repo

**Closed as completed by bcoca** 2015-09-09 15:07 UTC
Labels: m:unarchive
