### ISSUE TITLE
cron: multiple jobs in the same cron_file overwrite each other since 2.9.12

### ISSUE THREAD

**Issue by rbott** [ansible/ansible#71489] opened 2020-08-27 12:16 UTC
##### SUMMARY
If you put multiple cronjobs in a single file (using the [cron module](https://docs.ansible.com/ansible/latest/modules/cron_module.html)), each call to the module will overwrite the entire cronjob file. The result is that we only have one single (the last) cronjob in that file. This problem first appeared with 2.9.12, 2.9.11 is not affected. It might be related to #71134, but not sure.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cron

##### ANSIBLE VERSION
```
ansible 2.9.12
  config file = None
  configured module search path = ['/home/bott/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/bott/venv/ansible-python3/lib/python3.7/site-packages/ansible
  executable location = /home/bott/venv/ansible-python3/bin/ansible
  python version = 3.7.5 (default, Apr 19 2020, 20:18:17) [GCC 9.2.1 20191008]

```

##### CONFIGURATION
```
ANSIBLE_SSH_ARGS(/home/bott/deployment/ansible.cfg) = -o ControlPersist=60m -o ControlMaster=auto
ANSIBLE_SSH_CONTROL_PATH(/home/bott/deployment/ansible.cfg) = %(directory)s/REPLACEME-%%C
DEFAULT_CALLBACK_WHITELIST(/home/bott/deployment/ansible.cfg) = ['grafana_annotations', 'instana_pipeline_feedback', 'debug']
DEFAULT_GATHER_TIMEOUT(/home/bott/deployment/ansible.cfg) = 30
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/bott/deployment/ansible.cfg) = True
HOST_KEY_CHECKING(/home/bott/deployment/ansible.cfg) = False
```

##### OS / ENVIRONMENT
* target OSes: Debian 9, 10
* ansible OSes: tested with Ubuntu 19.10, 20.04, ArchLinux (Python 3.7 and 3.8, always using a virtual environment with ansible + dependencies installed through pip)

##### STEPS TO REPRODUCE
```yaml
---
- hosts: all
  tasks:
    - name: Create first cronjob
      cron:
        name: "first_cronjob"
        minute: "17"
        hour: "4"
        job: "/usr/local/bin/first.sh"
        user: root
        cron_file: cronfile

    - name: Create second cronjob
      cron:
        name: "second_cronjob"
        minute: "*/5"
        job: "/usr/local/bin/second.sh"
        user: root
        cron_file: cronfile

    - name: Create special reboot cronjob
      cron:
        name: "third_cronjob"
        special_time: reboot
        job: "/usr/local/sbin/third.sh"
        user: root
        cron_file: cronfile
```

##### EXPECTED RESULTS
With Ansible 2.9.11 the file `/etc/cron.d/cronfile` will show:
```
#Ansible: first_cronjob
17 4 * * * root /usr/local/bin/first.sh
#Ansible: second_cronjob
*/5 * * * * root /usr/local/bin/second.sh
#Ansible: third_cronjob
@reboot root /usr/local/sbin/third.sh
```

##### ACTUAL RESULTS

With Ansible 2.9.12 the file `/etc/cron.d/cronfile` will show:
```
#Ansible: third_cronjob
@reboot root /usr/local/sbin/third.sh
```

```
$ ansible-playbook -i environments/dev/inventory -l sample.server.net -u root -vvv cron-example.yml 

ansible-playbook 2.9.12
  config file = /home/bott/deployment/ansible.cfg
  configured module search path = ['/home/bott/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/bott/venv/ansible-python3/lib/python3.7/site-packages/ansible
  executable location = /home/bott/venv/ansible-python3/bin/ansible-playbook
  python version = 3.7.5 (default, Apr 19 2020, 20:18:17) [GCC 9.2.1 20191008]
Using /home/bott/deployment/ansible.cfg as config file
host_list declined parsing /home/bott/deployment/environments/dev/inventory as it did not pass its verify_file() method
script declined parsing /home/bott/deployment/environments/dev/inventory as it did not pass its verify_file() method
auto declined parsing /home/bott/deployment/environments/dev/inventory as it did not pass its verify_file() method
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details
Parsed /home/bott/deployment/environments/dev/inventory inventory source with ini plugin

PLAYBOOK: cron-example.yml *********************************************************************************************************************************************************************************
1 plays in cron-example.yml

PLAY [all] *************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************************************
task path: /home/bott/deployment/cron-example.yml:2
<sample.server.net> ESTABLISH SSH CONNECTION FOR USER: root
<sample.server.net> SSH: EXEC ssh -o ControlPersist=60m -o ControlMaster=auto -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/home/bott/.ansible/cp/REPLACEME-%C sample.server.net '/bin/sh -c '"'"'echo ~root && sleep 0'"'"''
<sample.server.net> (0, b'/root\n', b'')
<sample.server.net> ESTABLISH SSH CONNECTION FOR USER: root
<sample.server.net> SSH: EXEC ssh -o ControlPersist=60m -o ControlMaster=auto -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/home/bott/.ansible/cp/REPLACEME-%C sample.server.net '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1598529938.5360637-7922-267693323266366 `" && echo ansible-tmp-1598529938.5360637-7922-267693323266366="` echo /root/.ansible/tmp/ansible-tmp-1598529938.5360637-7922-267693323266366 `" ) && sleep 0'"'"''
<sample.server.net> (0, b'ansible-tmp-1598529938.5360637-7922-267693323266366=/root/.ansible/tmp/ansible-tmp-1598529938.5360637-7922-267693323266366\n', b'')
<sample.server.net> Attempting python interpreter discovery
<sample.server.net> ESTABLISH SSH CONNECTION FOR USER: root
<sample.server.net> SSH: EXEC ssh -o ControlPersist=60m -o ControlMaster=auto -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/home/bott/.ansible/cp/REPLACEME-%C sample.server.net '/bin/sh -c '"'"'echo PLATFORM; uname; echo FOUND; command -v '"'"'"'"'"'"'"'"'/usr/bin/python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.6'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.5'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.6'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/libexec/platform-python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/bin/python3'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python'"'"'"'"'"'"'"'"'; echo ENDFOUND && sleep 0'"'"''
<sample.server.net> (0, b'PLATFORM\nLinux\nFOUND\n/usr/bin/python\n/usr/bin/python3.7\n/usr/bin/python2.7\n/usr/bin/python3\n/usr/bin/python\nENDFOUND\n', b'')
<sample.server.net> ESTABLISH SSH CONNECTION FOR USER: root
<sample.server.net> SSH: EXEC ssh -o ControlPersist=60m -o ControlMaster=auto -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/home/bott/.ansible/cp/REPLACEME-%C sample.server.net '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
<sample.server.net> (0, b'{"osrelease_content": "PRETTY_NAME=\\"Debian GNU/Linux 10 (buster)\\"\\nNAME=\\"Debian GNU/Linux\\"\\nVERSION_ID=\\"10\\"\\nVERSION=\\"10 (buster)\\"\\nVERSION_CODENAME=buster\\nID=debian\\nHOME_URL=\\"https://www.debian.org/\\"\\nSUPPORT_URL=\\"https://www.debian.org/support\\"\\nBUG_REPORT_URL=\\"https://bugs.debian.org/\\"\\n", "platform_dist_result": ["debian", "10.5", ""]}\n', b'')
<sample.server.net> Python interpreter discovery fallback (unsupported Linux distribution: debian)
Using module file /home/bott/venv/ansible-python3/lib/python3.7/site-packages/ansible/modules/system/setup.py
<sample.server.net> PUT /home/bott/.ansible/tmp/ansible-local-7917tdc20bg3/tmp01mv87gd TO /root/.ansible/tmp/ansible-tmp-1598529938.5360637-7922-267693323266366/AnsiballZ_setup.py
<sample.server.net> SSH: EXEC sftp -b - -o ControlPersist=60m -o ControlMaster=auto -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/home/bott/.ansible/cp/REPLACEME-%C '[sample.server.net]'
<sample.server.net> (0, b'sftp> put /home/bott/.ansible/tmp/ansible-local-7917tdc20bg3/tmp01mv87gd /root/.ansible/tmp/ansible-tmp-1598529938.5360637-7922-267693323266366/AnsiballZ_setup.py\n', b'')
<sample.server.net> ESTABLISH SSH CONNECTION FOR USER: root
<sample.server.net> SSH: EXEC ssh -o ControlPersist=60m -o ControlMaster=auto -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/home/bott/.ansible/cp/REPLACEME-%C sample.server.net '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1598529938.5360637-7922-267693323266366/ /root/.ansible/tmp/ansible-tmp-1598529938.5360637-7922-267693323266366/AnsiballZ_setup.py && sleep 0'"'"''
<sample.server.net> (0, b'', b'')
<sample.server.net> ESTABLISH SSH CONNECTION FOR USER: root
<sample.server.net> SSH: EXEC ssh -o ControlPersist=60m -o ControlMaster=auto -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/home/bott/.ansible/cp/REPLACEME-%C -tt sample.server.net '/bin/sh -c '"'"'/usr/bin/python /root/.ansible/tmp/ansible-tmp-1598529938.5360637-7922-267693323266366/AnsiballZ_setup.py && sleep 0'"'"''
<sample.server.net> (0, b'\r\n{"invocation": {"module_args": {"filter": "*", "gather_subset": ["all"], "fact_path": "/etc/ansible/facts.d", "gather_timeout": 30}}, "ansible_facts": "redacted" })
<sample.server.net> ESTABLISH SSH CONNECTION FOR USER: root
<sample.server.net> SSH: EXEC ssh -o ControlPersist=60m -o ControlMaster=auto -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/home/bott/.ansible/cp/REPLACEME-%C sample.server.net '/bin/sh -c '"'"'rm -f -r /root/.ansible/tmp/ansible-tmp-1598529938.5360637-7922-267693323266366/ > /dev/null 2>&1 && sleep 0'"'"''
<sample.server.net> (0, b'', b'')
[WARNING]: Platform linux on host sample.server.net is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.
ok: [sample.server.net]
META: ran handlers

TASK [Create first cronjob] ********************************************************************************************************************************************************************************
task path: /home/bott/deployment/cron-example.yml:4
<sample.server.net> ESTABLISH SSH CONNECTION FOR USER: root
<sample.server.net> SSH: EXEC ssh -o ControlPersist=60m -o ControlMaster=auto -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/home/bott/.ansible/cp/REPLACEME-%C sample.server.net '/bin/sh -c '"'"'echo ~root && sleep 0'"'"''
<sample.server.net> (0, b'/root\n', b'')
<sample.server.net> ESTABLISH SSH CONNECTION FOR USER: root
<sample.server.net> SSH: EXEC ssh -o ControlPersist=60m -o ControlMaster=auto -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/home/bott/.ansible/cp/REPLACEME-%C sample.server.net '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1598529940.5878143-7933-221951741056305 `" && echo ansible-tmp-1598529940.5878143-7933-221951741056305="` echo /root/.ansible/tmp/ansible-tmp-1598529940.5878143-7933-221951741056305 `" ) && sleep 0'"'"''
<sample.server.net> (0, b'ansible-tmp-1598529940.5878143-7933-221951741056305=/root/.ansible/tmp/ansible-tmp-1598529940.5878143-7933-221951741056305\n', b'')
Using module file /home/bott/venv/ansible-python3/lib/python3.7/site-packages/ansible/modules/system/cron.py
<sample.server.net> PUT /home/bott/.ansible/tmp/ansible-local-7917tdc20bg3/tmpdt5mz3yj TO /root/.ansible/tmp/ansible-tmp-1598529940.5878143-7933-221951741056305/AnsiballZ_cron.py
<sample.server.net> SSH: EXEC sftp -b - -o ControlPersist=60m -o ControlMaster=auto -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/home/bott/.ansible/cp/REPLACEME-%C '[sample.server.net]'
<sample.server.net> (0, b'sftp> put /home/bott/.ansible/tmp/ansible-local-7917tdc20bg3/tmpdt5mz3yj /root/.ansible/tmp/ansible-tmp-1598529940.5878143-7933-221951741056305/AnsiballZ_cron.py\n', b'')
<sample.server.net> ESTABLISH SSH CONNECTION FOR USER: root
<sample.server.net> SSH: EXEC ssh -o ControlPersist=60m -o ControlMaster=auto -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/home/bott/.ansible/cp/REPLACEME-%C sample.server.net '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1598529940.5878143-7933-221951741056305/ /root/.ansible/tmp/ansible-tmp-1598529940.5878143-7933-221951741056305/AnsiballZ_cron.py && sleep 0'"'"''
<sample.server.net> (0, b'', b'')
<sample.server.net> ESTABLISH SSH CONNECTION FOR USER: root
<sample.server.net> SSH: EXEC ssh -o ControlPersist=60m -o ControlMaster=auto -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/home/bott/.ansible/cp/REPLACEME-%C -tt sample.server.net '/bin/sh -c '"'"'/usr/bin/python /root/.ansible/tmp/ansible-tmp-1598529940.5878143-7933-221951741056305/AnsiballZ_cron.py && sleep 0'"'"''
<sample.server.net> (0, b'\r\n{"jobs": ["first_cronjob"], "warnings": [], "envs": [], "changed": true, "cron_file": "cronfile", "invocation": {"module_args": {"name": "first_cronjob", "insertbefore": null, "state": "present", "cron_file": "cronfile", "reboot": false, "hour": "4", "month": "*", "disabled": false, "job": "/usr/local/bin/first.sh", "special_time": null, "user": "root", "env": null, "insertafter": null, "backup": false, "day": "*", "minute": "17", "weekday": "*"}}}\r\n', b'Shared connection to sample.server.net closed.\r\n')
<sample.server.net> ESTABLISH SSH CONNECTION FOR USER: root
<sample.server.net> SSH: EXEC ssh -o ControlPersist=60m -o ControlMaster=auto -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/home/bott/.ansible/cp/REPLACEME-%C sample.server.net '/bin/sh -c '"'"'rm -f -r /root/.ansible/tmp/ansible-tmp-1598529940.5878143-7933-221951741056305/ > /dev/null 2>&1 && sleep 0'"'"''
<sample.server.net> (0, b'', b'')
changed: [sample.server.net] => {
    "changed": true,
    "cron_file": "cronfile",
    "envs": [],
    "invocation": {
        "module_args": {
            "backup": false,
            "cron_file": "cronfile",
            "day": "*",
            "disabled": false,
            "env": null,
            "hour": "4",
            "insertafter": null,
            "insertbefore": null,
            "job": "/usr/local/bin/first.sh",
            "minute": "17",
            "month": "*",
            "name": "first_cronjob",
            "reboot": false,
            "special_time": null,
            "state": "present",
            "user": "root",
            "weekday": "*"
        }
    },
    "jobs": [
        "first_cronjob"
    ]
}

TASK [Create second cronjob] *******************************************************************************************************************************************************************************
task path: /home/bott/deployment/cron-example.yml:13
<sample.server.net> ESTABLISH SSH CONNECTION FOR USER: root
<sample.server.net> SSH: EXEC ssh -o ControlPersist=60m -o ControlMaster=auto -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/home/bott/.ansible/cp/REPLACEME-%C sample.server.net '/bin/sh -c '"'"'echo ~root && sleep 0'"'"''
<sample.server.net> (0, b'/root\n', b'')
<sample.server.net> ESTABLISH SSH CONNECTION FOR USER: root
<sample.server.net> SSH: EXEC ssh -o ControlPersist=60m -o ControlMaster=auto -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/home/bott/.ansible/cp/REPLACEME-%C sample.server.net '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1598529942.010977-7942-106754464667067 `" && echo ansible-tmp-1598529942.010977-7942-106754464667067="` echo /root/.ansible/tmp/ansible-tmp-1598529942.010977-7942-106754464667067 `" ) && sleep 0'"'"''
<sample.server.net> (0, b'ansible-tmp-1598529942.010977-7942-106754464667067=/root/.ansible/tmp/ansible-tmp-1598529942.010977-7942-106754464667067\n', b'')
Using module file /home/bott/venv/ansible-python3/lib/python3.7/site-packages/ansible/modules/system/cron.py
<sample.server.net> PUT /home/bott/.ansible/tmp/ansible-local-7917tdc20bg3/tmpl_jgjh53 TO /root/.ansible/tmp/ansible-tmp-1598529942.010977-7942-106754464667067/AnsiballZ_cron.py
<sample.server.net> SSH: EXEC sftp -b - -o ControlPersist=60m -o ControlMaster=auto -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/home/bott/.ansible/cp/REPLACEME-%C '[sample.server.net]'
<sample.server.net> (0, b'sftp> put /home/bott/.ansible/tmp/ansible-local-7917tdc20bg3/tmpl_jgjh53 /root/.ansible/tmp/ansible-tmp-1598529942.010977-7942-106754464667067/AnsiballZ_cron.py\n', b'')
<sample.server.net> ESTABLISH SSH CONNECTION FOR USER: root
<sample.server.net> SSH: EXEC ssh -o ControlPersist=60m -o ControlMaster=auto -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/home/bott/.ansible/cp/REPLACEME-%C sample.server.net '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1598529942.010977-7942-106754464667067/ /root/.ansible/tmp/ansible-tmp-1598529942.010977-7942-106754464667067/AnsiballZ_cron.py && sleep 0'"'"''
<sample.server.net> (0, b'', b'')
<sample.server.net> ESTABLISH SSH CONNECTION FOR USER: root
<sample.server.net> SSH: EXEC ssh -o ControlPersist=60m -o ControlMaster=auto -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/home/bott/.ansible/cp/REPLACEME-%C -tt sample.server.net '/bin/sh -c '"'"'/usr/bin/python /root/.ansible/tmp/ansible-tmp-1598529942.010977-7942-106754464667067/AnsiballZ_cron.py && sleep 0'"'"''
<sample.server.net> (0, b'\r\n{"jobs": ["second_cronjob"], "warnings": [], "envs": [], "changed": true, "cron_file": "cronfile", "invocation": {"module_args": {"name": "second_cronjob", "insertbefore": null, "state": "present", "cron_file": "cronfile", "reboot": false, "hour": "*", "month": "*", "disabled": false, "job": "/usr/local/bin/second.sh", "special_time": null, "user": "root", "env": null, "insertafter": null, "backup": false, "day": "*", "minute": "*/5", "weekday": "*"}}}\r\n', b'Shared connection to sample.server.net closed.\r\n')
<sample.server.net> ESTABLISH SSH CONNECTION FOR USER: root
<sample.server.net> SSH: EXEC ssh -o ControlPersist=60m -o ControlMaster=auto -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/home/bott/.ansible/cp/REPLACEME-%C sample.server.net '/bin/sh -c '"'"'rm -f -r /root/.ansible/tmp/ansible-tmp-1598529942.010977-7942-106754464667067/ > /dev/null 2>&1 && sleep 0'"'"''
<sample.server.net> (0, b'', b'')
changed: [sample.server.net] => {
    "changed": true,
    "cron_file": "cronfile",
    "envs": [],
    "invocation": {
        "module_args": {
            "backup": false,
            "cron_file": "cronfile",
            "day": "*",
            "disabled": false,
            "env": null,
            "hour": "*",
            "insertafter": null,
            "insertbefore": null,
            "job": "/usr/local/bin/second.sh",
            "minute": "*/5",
            "month": "*",
            "name": "second_cronjob",
            "reboot": false,
            "special_time": null,
            "state": "present",
            "user": "root",
            "weekday": "*"
        }
    },
    "jobs": [
        "second_cronjob"
    ]
}

TASK [Create special reboot cronjob] ***********************************************************************************************************************************************************************
task path: /home/bott/deployment/cron-example.yml:21
<sample.server.net> ESTABLISH SSH CONNECTION FOR USER: root
<sample.server.net> SSH: EXEC ssh -o ControlPersist=60m -o ControlMaster=auto -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/home/bott/.ansible/cp/REPLACEME-%C sample.server.net '/bin/sh -c '"'"'echo ~root && sleep 0'"'"''
<sample.server.net> (0, b'/root\n', b'')
<sample.server.net> ESTABLISH SSH CONNECTION FOR USER: root
<sample.server.net> SSH: EXEC ssh -o ControlPersist=60m -o ControlMaster=auto -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/home/bott/.ansible/cp/REPLACEME-%C sample.server.net '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1598529942.9901352-7951-138030144150757 `" && echo ansible-tmp-1598529942.9901352-7951-138030144150757="` echo /root/.ansible/tmp/ansible-tmp-1598529942.9901352-7951-138030144150757 `" ) && sleep 0'"'"''
<sample.server.net> (0, b'ansible-tmp-1598529942.9901352-7951-138030144150757=/root/.ansible/tmp/ansible-tmp-1598529942.9901352-7951-138030144150757\n', b'')
Using module file /home/bott/venv/ansible-python3/lib/python3.7/site-packages/ansible/modules/system/cron.py
<sample.server.net> PUT /home/bott/.ansible/tmp/ansible-local-7917tdc20bg3/tmpjcaogdx3 TO /root/.ansible/tmp/ansible-tmp-1598529942.9901352-7951-138030144150757/AnsiballZ_cron.py
<sample.server.net> SSH: EXEC sftp -b - -o ControlPersist=60m -o ControlMaster=auto -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/home/bott/.ansible/cp/REPLACEME-%C '[sample.server.net]'
<sample.server.net> (0, b'sftp> put /home/bott/.ansible/tmp/ansible-local-7917tdc20bg3/tmpjcaogdx3 /root/.ansible/tmp/ansible-tmp-1598529942.9901352-7951-138030144150757/AnsiballZ_cron.py\n', b'')
<sample.server.net> ESTABLISH SSH CONNECTION FOR USER: root
<sample.server.net> SSH: EXEC ssh -o ControlPersist=60m -o ControlMaster=auto -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/home/bott/.ansible/cp/REPLACEME-%C sample.server.net '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1598529942.9901352-7951-138030144150757/ /root/.ansible/tmp/ansible-tmp-1598529942.9901352-7951-138030144150757/AnsiballZ_cron.py && sleep 0'"'"''
<sample.server.net> (0, b'', b'')
<sample.server.net> ESTABLISH SSH CONNECTION FOR USER: root
<sample.server.net> SSH: EXEC ssh -o ControlPersist=60m -o ControlMaster=auto -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/home/bott/.ansible/cp/REPLACEME-%C -tt sample.server.net '/bin/sh -c '"'"'/usr/bin/python /root/.ansible/tmp/ansible-tmp-1598529942.9901352-7951-138030144150757/AnsiballZ_cron.py && sleep 0'"'"''
<sample.server.net> (0, b'\r\n{"jobs": ["third_cronjob"], "warnings": [], "envs": [], "changed": true, "cron_file": "cronfile", "invocation": {"module_args": {"name": "third_cronjob", "insertbefore": null, "state": "present", "cron_file": "cronfile", "reboot": false, "hour": "*", "month": "*", "disabled": false, "job": "/usr/local/sbin/third.sh", "special_time": "reboot", "user": "root", "env": null, "insertafter": null, "backup": false, "day": "*", "minute": "*", "weekday": "*"}}}\r\n', b'Shared connection to sample.server.net closed.\r\n')
<sample.server.net> ESTABLISH SSH CONNECTION FOR USER: root
<sample.server.net> SSH: EXEC ssh -o ControlPersist=60m -o ControlMaster=auto -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/home/bott/.ansible/cp/REPLACEME-%C sample.server.net '/bin/sh -c '"'"'rm -f -r /root/.ansible/tmp/ansible-tmp-1598529942.9901352-7951-138030144150757/ > /dev/null 2>&1 && sleep 0'"'"''
<sample.server.net> (0, b'', b'')
changed: [sample.server.net] => {
    "changed": true,
    "cron_file": "cronfile",
    "envs": [],
    "invocation": {
        "module_args": {
            "backup": false,
            "cron_file": "cronfile",
            "day": "*",
            "disabled": false,
            "env": null,
            "hour": "*",
            "insertafter": null,
            "insertbefore": null,
            "job": "/usr/local/sbin/third.sh",
            "minute": "*",
            "month": "*",
            "name": "third_cronjob",
            "reboot": false,
            "special_time": "reboot",
            "state": "present",
            "user": "root",
            "weekday": "*"
        }
    },
    "jobs": [
        "third_cronjob"
    ]
}
META: ran handlers
META: ran handlers

PLAY RECAP *************************************************************************************************************************************************************************************************
sample.server.net     : ok=4    changed=3    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

```

**Comment by mkrizek** [comment] 2020-08-27 12:21
Duplicate of https://github.com/ansible/ansible/issues/71213

**Closed as completed by mkrizek** 2020-08-27 12:21 UTC
