### ISSUE TITLE
scp_if_ssh not respected in copy and template modules if in a loop

### ISSUE THREAD

**Issue by smiller171** [ansible/ansible#15839] opened 2016-05-12 17:19 UTC
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.2.0
```
##### SUMMARY

If using the copy or template modules in a loop, `scp_if_ssh = True` is not respected.  
The setting is respected when not using a loop.
##### STEPS TO REPRODUCE
1. Disable SFTP on target host
2. set `scp_if_ssh = True` in .ansible.cfg

```
- Name: Test copy loop
  copy:
      src: "{{item}}"
      dest: "/tmp/{{item}}"
  with_items:
  - foo
  - bar
```

##### EXPECTED RESULTS

Expect Foo and Bar to be copied to remote server with scp
##### ACTUAL RESULTS

Get an error about sftp being disabled. I no longer have access to the system that this was occurring on. Will try to reproduce on a VM and update this issue.

If I create a separate task for each file this works.

**Comment by smiller171** [comment] 2016-05-12 17:20
@defionscode I know I talked to you about this a week or two ago.

**Comment by jctanner** [comment] 2016-06-09 20:30
I started the test case by doing the following on the remote host to break sftp
- mv /usr/libexec/openssh/sftp-server /usr/libexec/openssh/sftp-server.bak
- service sshd restart

Then I ran this testcase ...

```
$ cat test.sh
#!/bin/bash
rm -rf /home/jtanner/.ansible/cp/*
ssh root@el6host 'rm -rf /tmp/foo'
ssh root@el6host 'rm -rf /tmp/bar'
ansible-playbook -vvvv -i inventory site.yml
RC=$?
exit $RC

$ cat site.yml
- hosts: el6host
  user: root
  gather_facts: False
  tasks:
    - name: Test copy loop
      copy:
        src: "{{item}}"
        dest: "/tmp/{{item}}"
      with_items:
        - foo
        - bar
```

Results ...

```
$ cat returncodes.txt  | fgrep -v rc | tail -n 20
v1.8.0 ; 0
v1.8.1 ; 0
v1.8.2 ; 0
v1.8.3 ; 0
v1.8.4 ; 0
v1.9.0-1 ; 0
v1.9.0-2 ; 0
v1.9.0.1-1 ; 0
v1.9.1-1 ; 0
v1.9.2-1 ; 0
v1.9.3-1 ; 0
v1.9.4-1 ; 0
v1.9.5-1 ; 0
v1.9.6-1 ; 0
v2.0.0.0-1 ; 0
v2.0.0.1-1 ; 0
v2.0.0.2-1 ; 0
v2.0.1.0-1 ; 0
v2.0.2.0-1 ; 0
v2.1.0.0-1 ; 0
```

**Comment by jctanner** [comment] 2016-06-09 20:31
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us. 

Testing this on the version you have specified, we cannot reproduce this problem.

Our reasons and evidence for this are:
- Testcase outlined above.

And we suggest that:
- Use -vvvv with ansible-playbook to capture the connection information so that we can see the sftp/scp mode changing between items.

As such, we are most likely going to close this ticket.  Should you disagree with this conclusion, you may also wish to join our mailing lists, which are very active:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Closed as completed by jctanner** 2016-06-09 20:31 UTC
Labels: P2, bug
