### ISSUE TITLE
AnsibleUndefined exception with Jinja2 "or" template

### ISSUE THREAD

**Issue by joel-schaal** [ansible/ansible#76989] opened 2022-02-08 21:28 UTC
### Summary

I cannot use [basic Python conditional handling](https://docs.python.org/3/reference/expressions.html#boolean-operations) in my template without having an AnsibleUndefined exception. 

### Issue Type

Bug Report

### Component Name

template

### Ansible Version

```console
$ ansible --version
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/joel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
```

### Configuration

```console
$ ansible-config dump --only-changed
$
```

### OS / Environment

Ubuntu 20.04.3 LTS (through Linux Subsystem)

### Steps to Reproduce

```yaml 
- hosts: all
  tasks:
    - debug:
        msg: "{{some_undefined_var or some_defined_var}}"
```

But if I use the following in a basic Jinja2 template it works as expected:

```python
>>> from jinja2 import Template
>>> t = Template("Hello {{ something or alternative or 'nobody' }}!")
>>> t.render(something="world")
'Hello world!'
>>> t.render(alternative="universe")
'Hello universe!'
>>> t.render()
'Hello nobody!'
>>>
```

This seems quite [basic Python conditional handling](https://docs.python.org/3/reference/expressions.html#boolean-operations) so I'm surprised it is not supported by Ansible. 

### Expected Results

Assuming `some_defined_var` is a previously defined variable, I would have expected to debug task succeed, with the content of that variable displayed, even if I have no variable `some_undefined_var`.

If I use the following in a basic Jinja2 template it works as expected:

```python
>>> from jinja2 import Template
>>> t = Template("Hello {{ something or alternative or 'nobody' }}!")
>>> t.render(something="world")
'Hello world!'
>>> t.render(alternative="universe")
'Hello universe!'
>>> t.render()
'Hello nobody!'
>>>
```

### Actual Results

```console
fatal: [myhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'some_undefined_var ' is undefined\n[...]
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by sivel** [comment] 2022-02-08 21:31
Duplicate of https://github.com/ansible/ansible/issues/56017

**Closed as completed by sivel** 2022-02-08 21:31 UTC

**Comment by joel-schaal** [comment] 2022-02-08 21:36
Thank you @sivel for having found it (I was not sure how to do that search, or is pretty common 😅).
