### ISSUE TITLE
Pause with prompt in loop - not prompting

### ISSUE THREAD

**Issue by retinaburn** [ansible/ansible#11800] opened 2015-07-30 13:45 UTC
Issue Type:
Bug Report?
Ansible Version: 1.9.2

Environment: RHEL6

Summary:

What I wanted to do was compare the property files in the local source directory against the destination, and if there was a difference (by md5 comparison) prompt the user that they should manually verify and confirm. The reason for this is that different environments (lower test environments, production environments) may have had optimizations that I don't want to overwrite blindly - or skip and miss a change that should be deployed.

Even gathering the host and file info and then logging it at the end of the run would work from my perspective.

Steps To Reproduce:

For my test the remote file on server1(10.246.34.158) is the same as the local file, the remote file on server2(10.246.34.159) is different.

The following runs against a list of hosts (2 currently):

```
- hosts: webservice
  vars:
    local_path: /tmp/webservice-latest
    tomcat_dest_path: /opt/tomcat/webapps
    shared_classes_path: /opt/tomcat/shared/classes

    webservice_files: [
     {
      sample_name: wrapper.properties.sample,
      name: wrapper.properties,
      src: "{{local_path}}/conf",
      dest: "{{shared_classes_path}}"
     }
    ]

 tasks:

    - name: Get local stat of all webapp files
      become: no
      local_action: stat path="{{item.src}}/{{item.sample_name}}"
      with_items:
        - "{{webservice_files}}"
      register: local

    - name: Get remote stat of all the webapp files
      action: stat path="{{item.dest}}/{{item.name}}"
      with_items:
        - "{{webservice_files}}"
      register: remote

   - name: "Debug file stat for both local and remote - True"
      debug: msg="Stat should be True {{item.1.stat.path}}:{{item.1.stat.md5}} {{item.2.stat.path}}:{{item.2.stat.md5}}"
      when: '"{{item.2.stat.exists}}" == "True" and "{{item.1.stat.md5}}" != "{{item.2.stat.md5|default}}"'
      with_together:
        - "{{webservice_files}}"
        - "{{local.results}}"
        - "{{remote.results}}"

    # if the property files do exist, then we need to tell the user
    # and let them sort it out
    - name: Compare md5 of webservice files that do exist, prompt if different
      pause: prompt="Files are different - manually review (enter to continue)"
      when: '"{{item.2.stat.exists}}" == "True" and "{{item.1.stat.md5}}" != "{{item.2.stat.md5|default}}"'
      with_together:
        - "{{webservice_files}}"
        - "{{local.results}}"
        - "{{remote.results}}"
```

Expected Results:
 Get prompted for each file and each host where there is a difference.

Actual Results:
I can see the debug line skipped for server2, and displayed for server1 which is correct.

The issue is that I only see the action skipped for server2, for server1 I don't get a prompt or a notification that it was skipped.  It just silently skips it.

```
TASK: [Debug file stat for both local and remote - True] **********************
skipping: [10.246.34.158] => (item=[ <snip> ])
ok: [10.246.34.159] => (item=<snip>
    "item": [<snip]
    "msg": "Stat should be True /tmp/webservice-latest/conf/wrapper.properties.sample:67b3c6d486e5ee5a431e5a5f5df75045 /opt/tomcat/shared/classes/wrapper.properties:7bfe4004786dac7006355fe9b810032c"
}

TASK: [Compare md5 of webservice files that do exist, prompt if different] ****
skipping: [10.246.34.158] => (item=[ <snip> ])
```

**Comment by bcoca** [comment] 2015-08-07 03:49
so I tested a simple case:

```
    - pause: prompt="type stuff {{item}}"
      register: mypause
      when: item > 0
      with_items:
        - 1
        - 2
        - 3
```

and i get:

```
[pause prompt=type stuff 2]
type stuff 2:
[pause prompt=type stuff 3]
type stuff 3:
skipping: [localhost] => (item=1) 
ok: [localhost] => (item=2)
ok: [localhost] => (item=3)

```

Which shows there are no issues with_items in a loop. What is happening here is that pause bypasses the host loop, so it will not run per host, only once per play and it will only have data available for the server it runs for (normally play_hosts[0]).

We should probably update the module docs to make a note of this.

Closing this issue as this is not a bug, but expected behavior.

**Closed as completed by bcoca** 2015-08-07 03:49 UTC
Labels: bug
