### ISSUE TITLE
(edit: recursive copy) failing When the file name contains "="

### ISSUE THREAD

**Issue by hapming** [ansible/ansible#8774] opened 2014-08-27 13:00 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

1.7.1
##### Environment:

Fedora release 18 -> centos release 6.4
##### Summary:

copy modules failing When the file name contains "="
##### Steps To Reproduce:

Current folder "test" contains a file "a=b.txt".
Example playbook:

```

---
- name: Copy file
  hosts: hosts
  remote_user: root
  tasks:
    - name: copy test
       copy: src=./test dest=/work/
```
##### Expected Results:

No error
##### Actual Results:

TASK: [test] ******************************************************************
fatal: [192.168.8.140] => failed to parse: Exception OSError: (2, 'No such file or directory', '/work/test/.ansible_tmpKvKSfea=b.txt') in <bound method _TemporaryFileWrapper.__del__ of <closed file '<fdopen>', mode 'w+b' at 0xb24780>> ignored
{"src": "/root/.ansible/tmp/ansible-tmp-1409141808.19-6629981198454/source", "md5sum": "d41d8cd98f00b204e9800998ecf8427e", "group": "root", "uid": 0, "dest": "/work/test/a=b.txt", "changed": true, "state": "file", "gid": 0, "mode": "0644", "owner": "root", "size": 0}

FATAL: all hosts have already failed -- aborting
PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/sss/playbook2.retry

192.168.8.140 : ok=0    changed=0    unreachable=1    failed=0

**Comment by abadger** [comment] 2014-09-03 18:48
@hapming  I've setup ansible-1.7.1 on a fedora18 vm talking to a centos6.4 vm and so far have been unable to replicate this issue:

``` ShellSession
# ls -l test
total 4
-rw-rw-r--. 1 badger badger 13 Sep  3 10:22 a=b.txt
# cat test.yml 
---
- name: Copy file
  hosts: rhel6.lan
  remote_user: root
  tasks:
    - name: copy test
      copy: src=./test dest=/work/
# ansible-playbook test.yml -i inv

PLAY [Copy file] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [rhel6.lan]

TASK: [copy test] ************************************************************* 
changed: [rhel6.lan]

PLAY RECAP ******************************************************************** 
rhel6.lan                  : ok=2    changed=1    unreachable=0    failed=0 
# ssh rhel6.lan find /work -print
/work
/work/test
/work/test/a=b.txt
```

Do you see anything that might be different between our two runs?  Anything else that might help reproduce this?

**Comment by hapming** [comment] 2014-09-05 10:14
@abadger  Sorry. I can't still found anything to help reproduce this. Maybe I have made some special setting.

**Comment by abadger** [comment] 2014-09-05 16:30
Yeah, if you find a setting, or some non-standard version of something, let us know.  Without being able to reproduce this, I don't think we'll be able to track this down.

Just on an offhand thought, the "=" isn't a red herring, is it?  If you have some other files in the teste directory tree, it doesn't still fail, does it?

**Comment by mpdehaan** [comment] 2014-09-05 20:15
I'm wondering if maybe it was an older version of ansible at the path at the time of that test?

**Comment by mpdehaan** [comment] 2014-09-11 20:34
I'm going to close this one since we can't replicate this, if do find it again stop by ansible-project and we'll take a look. Thanks!

**Closed as completed by mpdehaan** 2014-09-11 20:34 UTC
Labels: needs_info, P2, bug
