### ISSUE TITLE
Pause module does not abort

### ISSUE THREAD

**Issue by binbashroot** [ansible/ansible#14252] opened 2016-02-02 08:13 UTC
Ansible 2.0.0.2 (pip installation)

When using the pause module, using control-c-a does not abort the playbook.  Hitting Control-c will bring up the option of Press C to continue or A to abort.  Pressing A just continues the playbook.  I was able to reproduce this.

Ansible Host:   RHEL6.7
Ansible Clients:  RHEL5/6

**Comment by bcoca** [comment] 2016-02-02 15:01
can you test against devel/stable-2.0 or the 2.0.1-rc1? I cannot reproduce on any of those.

**Comment by udondan** [comment] 2016-02-05 07:19
Confirming this. Tested with:
- 2.0.0.2
- devel
- 2.0.1-rc1

This is my task:

```
- name: foo
  pause: prompt='fooo. Press Ctrl+c and then "a" to abort'
```

Pressing Ctrl+c will bring up:

```
Press 'C' to continue the play or 'A' to abort
```

Pressing A will result in a failed task:

```
fatal: [some.host]: FAILED! => {"failed": true, "msg": "user requested abort!"}
```

And then it simply continues with the rest of the play.
There is no ignore_errors defined which might explain such behavior. Same task works as expected in Ansible 1.9

---

This is a mega blocker for us using Ansible 2 because we require user confirmation before running some tags against production hosts.

**Comment by udondan** [comment] 2016-02-05 07:30
Another interesting observation: Right before the pause module I have a task which makes use of `{{ ansible_distribution }}`. When running from the devel branch this task fails and claims `'ansible_distribution' is undefined`. The task indeed fails - and while there is no ignore_errors is defined the play already continues there. So my guess is this is not a problem with the pause module at all - but a general problem where the play continues after failed tasks. Though I was not yet able to reproduce the problem in a small example playbook. Maybe it's only triggered when the tasks are inside roles. I see what I can do to provide a small "working" example.

**Comment by udondan** [comment] 2016-02-05 08:15
<sub>I can not reproduce the `ansible_distribution` thingy, but it anyway seems to be unrelated. I removed that comment to stay on topic. I will open another issue for that if I need to. Back to the pause problem:</sub>

I now can perfectly reproduce it. I missed one important fact before. The playbook did not continue for all hosts! It only happens when multiple hosts are involved.

To reproduce it, use this small playbook:

```
- name: some play
  hosts: 
    - host1
    - host2
  tasks:

    - name: foo
      pause: prompt='fooo! Press return to continue. Press Ctrl+c and then "a" to abort'

    - debug: msg="what the...."
```

this will result in:

```
PLAY [some play] ***************************************************************

TASK [setup] *******************************************************************
ok: [host1]
ok: [host2]

TASK [foo] *********************************************************************
[foo]
fooo! Press return to continue. Press Ctrl+c and then "a" to abort:
Press 'C' to continue the play or 'A' to abort 
fatal: [host1]: FAILED! => {"failed": true, "msg": "user requested abort!"}

TASK [debug] *******************************************************************
ok: [host2] => {
    "msg": "what the...."
}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
host1       : ok=1    changed=0    unreachable=0    failed=1   
host2       : ok=2    changed=0    unreachable=0    failed=0   
```

This somehow makes sense, since the pause module is only executed for the first host of the inventory. The other hosts are not affected by the failed pause module.

In Ansible 1.x all hosts will fail. And this has to be the expected behavior. Otherwise the pause module does not make sense, since there is no option to actually run it for all hosts.

**Comment by bcoca** [comment] 2016-02-05 14:11
now i can reproduce, you are correct it only 'aborts' the one host.

**Comment by jimi-c** [comment] 2016-02-05 16:00
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2016-02-05 15:59 UTC
Labels: P2, bug
