### ISSUE TITLE
Playbooks with many handlers make slow task transition.

### ISSUE THREAD

**Issue by marlox-ouda** [ansible/ansible#21773] opened 2017-02-22 14:13 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
task executor

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
tryed with different option on *ssh_args* (-o ControlPersist=3600s -o ServerAliveInterval=5)
tryed with different option on "scp_on_ssh"
same issue each time
working with python3

##### OS / ENVIRONMENT
manager: fedora
managed: debian jessie

##### SUMMARY
Have a complex playbook with many dependencies and many tasks with own handlers.
On recursive *template* and *copy* tasks with 1-3 items and notified handlers, tasks with *changed=true* are very likely too hang : I need to wait Ansible go to the next step for 10-30 minutes
while modification is done on the remote system and there is no more remote Ansible process.
If I rerun the playbook, change is already done and I don't need to wait … for this task. But I lose handler execution.

##### STEPS TO REPRODUCE
Have complex playbook with 30 roles included through dependencies. Some few times.
Each one raise at least two handlers. Some handlers can raise other handlers.

##### EXPECTED RESULTS
Same with very higher speed

**Comment by marlox-ouda** [comment] 2017-02-22 14:33
Other information : during execution, I have 
```
%CPU %MEM     VSZ     RSS  STAT   COMMAND
93.3 14.4  467496  184536   Rl+   ansible-playbook […]
 0.3  0.0       0       0    Z+   [ansible-playboo] <defunct>
[…]
```

The zombie process does not block the slowly running of the playbook

**Comment by abadger** [comment] 2017-04-11 21:31
@marlox-ouda I noticed this in your issue report:
> On recursive template and copy tasks with 1-3 items and notified handlers, tasks with changed=true are very likely too hang :

Is this only happening with recursive template and copy?  If so, it may be solved by this PR: https://github.com/ansible/ansible/pull/23326

That Pr has been applied on the current devel branch and is pending for 2.3.1 (not for 2.3.0).
needs_info

**Comment by marlox-ouda** [comment] 2017-05-04 14:29
@abadger : thank you for your notice : such modification really increase playbook speed.

I have just discovered ```debug``` mode to run playbook and discover there is sometimes, many consecutive (may be 100 times), and each ones take 1 sec to execute :
```
in VariableManager get_vars()
done with get_vars()
```

For instance :
```
  3984 1493908312.73511: done running TaskExecutor() for server.tld/TASK: role : templating_task
  3984 1493908312.73626: sending task result
  3984 1493908312.73678: done sending task result
  3984 1493908312.73700: WORKER PROCESS EXITING
  2605 1493908312.74601: in VariableManager get_vars()
  2605 1493908313.56119: done with get_vars()
  2605 1493908313.56163: in VariableManager get_vars()
  2605 1493908314.38252: done with get_vars()
  2605 1493908314.38272: in VariableManager get_vars()
  2605 1493908315.19104: done with get_vars()
  2605 1493908315.19132: in VariableManager get_vars()
  2605 1493908316.00958: done with get_vars()
  2605 1493908316.00980: in VariableManager get_vars()
  2605 1493908316.81766: done with get_vars()
NOTIFIED HANDLER my_handlers
  2605 1493908316.81798: in VariableManager get_vars()
  2605 1493908317.63926: done with get_vars()
  2605 1493908317.63948: in VariableManager get_vars()
  2605 1493908318.45975: done with get_vars()
  2605 1493908318.45998: in VariableManager get_vars()
  2605 1493908319.25929: done with get_vars()
  2605 1493908319.25950: in VariableManager get_vars()
  2605 1493908320.06514: done with get_vars()
  2605 1493908320.06538: in VariableManager get_vars()
  2605 1493908320.87020: done with get_vars()
  2605 1493908320.87043: in VariableManager get_vars()
  2605 1493908321.69846: done with get_vars()
  2605 1493908321.69865: in VariableManager get_vars()
  2605 1493908322.51162: done with get_vars()
  2605 1493908322.51184: in VariableManager get_vars()
  2605 1493908323.32551: done with get_vars()
  2605 1493908323.32570: in VariableManager get_vars()
  2605 1493908324.13521: done with get_vars()
  2605 1493908324.13545: in VariableManager get_vars()
  2605 1493908324.95142: done with get_vars()
  2605 1493908324.95166: in VariableManager get_vars()
  2605 1493908325.77192: done with get_vars()
  2605 1493908325.77214: in VariableManager get_vars()
  2605 1493908326.58124: done with get_vars()
  2605 1493908326.58145: in VariableManager get_vars()
  2605 1493908327.40465: done with get_vars()
  2605 1493908327.40486: in VariableManager get_vars()
  2605 1493908328.23524: done with get_vars()
  2605 1493908328.23547: in VariableManager get_vars()
  2605 1493908329.04575: done with get_vars()
```

**Comment by marlox-ouda** [comment] 2017-05-04 15:04
Another more accurate example. There is a task in my playbook that try to templating the following file :
[etc_pam.d_su.j2.txt](https://github.com/ansible/ansible/files/976578/etc_pam.d_su.j2.txt)

There is only 3 variables on this task and i took about 8.5 minutes with such trace
[extract_running_cmd.log.txt](https://github.com/ansible/ansible/files/976577/extract_running_cmd.log.txt)

The templating is rightly done at the end.

It does not occur in this example but, usually the Handler is call in the middle of the trace and action has already been done for a while. So, what does it solving ? It is mystery.

More I go through the playbook ands tasks, more they are likely to have roles with dependencies, more they are taking long time, more they are taking time. 8.5 minutes is not the longuest.

**Comment by Dantemss** [comment] 2018-01-05 22:45
I have also noticed severe slowness when notifying handlers (running ansible 2.4.2.0). For example, we have 15 or so tasks like this in our playbook:

```
- name: notify monit handlers
  command: 'true'
  notify: monit
  when: notify_all_handlers
  tags:
    - monit
    - handler
```

We run these tasks after a deployment goes wrong (server OOMs for example) to fix the server state, since in that case the handlers did not run and service configuration may have been modified without the services being restarted. However, each of these tasks, which basically does nothing but notify a handler, takes 20 seconds to run. Other tasks that notify handlers also create similar slowdown.

We do also have a lot of roles with complex dependencies between them, like the OP.

**Comment by Dantemss** [comment] 2018-01-05 23:03
Something else I remembered... when we had even more complex role dependencies before, ALL tasks started taking an extra 3-4 seconds to run. Debug mode showed the time being spent in calls to `get_vars()` like posted above by @marlox-ouda (though less calls than that). Eventually we got rid of a bunch of roles and simplified the dependencies, causing the time spent in `get_vars()` to be not as bad. My best guess would be that `get_vars()` is re-processing role dependencies every time it is called, which takes a considerable chunk of time if they are complex enough, though I have not investigated further.

**Comment by jstoja** [comment] 2018-07-25 07:30
hey @abadger sorry to get this from the very past, but I'm having the same issue as @Dantemss.
We're just doing a `set_fact` that notifies a handler that does a `file` and the set_fact (event setting a static string) is taking +10seconds whereas all the other tasks are taking few ms.
I got the same debug messages too (many calls to `get_vars`), but cannot pin point why. Would you mind guiding me to where the issue could be? Maybe I could find a way to solve it...

**Comment by jstoja** [comment] 2018-07-25 12:37
We found a workaround, we were using the listen + notify and we switched to using the name of the task and it worked as expected. I hope this would help others.

**Comment by Vladimir-csp** [comment] 2019-07-23 10:14
#59017
`get_vars()` calls are due to re-rendering of var structure for every handler in undeduplicated playbook (with dependency repetitions).

**Comment by sivel** [comment] 2019-08-09 19:05
Closing this as a duplicate of https://github.com/ansible/ansible/issues/59017 https://github.com/ansible/ansible/issues/49022

**Closed as completed by sivel** 2019-08-09 19:05 UTC
Labels: affects_2.2, c:executor/task_executor, support:core, bug
