### ISSUE TITLE
-c ssh_alt does not work with -K, fails 100% of the time

### ISSUE THREAD

**Issue by msolo** [ansible/ansible#5372] opened 2013-12-20 18:04 UTC
I actually have password-less sudo enabled, but my bootstrap requires my sudo password so this is relevant when new devices come online.

```
> ansible-playbook ansible/prod.yml -K -c ssh_alt
sudo password: 

PLAY [prod] ******************************************************************* 

GATHERING FACTS *************************************************************** 
failed: [pa2] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'mysecretsudopasswd' is not defined
```

**Comment by mpdehaan** [comment] 2013-12-20 20:10
Thanks, we will take a look (note to others, this plugin is still experimental and not the default just yet)

cc @jeromew in case he wants to beat us to it.

**Comment by jeromew** [comment] 2013-12-20 20:41
weird ; it works for me with

playbook:

```
- hosts: worker1
  gather_facts: yes
  tasks:
  - command: echo "ping"
    sudo: yes


ansible-playbook -c ssh_alt -k -K -u fakeuser -i ansiconf/prod ansiconf/prod.yml
```

where fakeuser needs both password & sudo password.

can you share a minimal playbook that breaks in your case + explain a bit more about how your user setup is done ? which platform ?

thank you

**Comment by jeromew** [comment] 2013-12-20 21:00
I tried different things but could not reproduce it so I will need your feedback @msolo.

(important) sidenote: I am leaving for an offline xmas break in like 10 minutes so you'll probably beat me to it @mpdehaan ! If galaxy turns into a black hole I'll take a look at this issue when I get back - probably not before the end of the year though.

**Comment by msolo** [comment] 2013-12-20 23:20
Running your sample playbook I get the same failure with this version:

ansible-playbook 1.5 (devel d6ea5be20f) last updated 2013/12/20 15:18:08 (GMT -700)

As I mentioned, I actually have sudo nopass here, so I don't _need_ -K. Not sure if that is relevant.

```
ansible-playbook ansible/test.yml -c ssh_alt -K
sudo password: 

PLAY [pa2] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [pa2]

TASK: [command echo "ping"] *************************************************** 
failed: [pa2] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'failed' is not defined


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/mike/test.retry

pa2                        : ok=1    changed=0    unreachable=0    failed=1   
```

**Comment by jeromew** [comment] 2013-12-31 10:56
thanks for the feedback. I had wrongly interpreted your original post.

so you are invoking the -K option and sending the password even though the system will not ask for it (NOPASSWD is configured).

Currently i confirm that the code of the ssh_alt connection plugin :
- correcly send the passwords (-k and -K) when they are given by the user AND they are expected by the system
- wrongly tries to send the -K password to the remote when it is not expected by the system

I will take a look at this and report what I find here. It maybe related to the tty / no-tty aspect of things.

**Comment by jeromew** [comment] 2013-12-31 19:48
last PR before the new year !

@msolo the case you encountered (-K on a NOPASSWD user) should be fixed with this PR. I would appreciate if you can find some time to test it and confirm it is ok for you.

@mpdehaan, @jctanner : check the PR, 
- I had to add the handling of the detection of the password prompt for the no-tty case. I think it works in all cases
- I finally understood why the pipelining mode does not work with ssh with tty (-tt). It breaks because pipelining into python inside a tty forces the interactive-mode and the code of the modules is not compatible with this mode (indentation is broken mainly by the empty lines that are often added to beautify the code. they are more than often added without indendation).

I hope this works for you and I wish you a happy new year !

**Comment by msolo** [comment] 2014-01-01 06:28
LGTM

Thanks for the fix.

**Comment by mpdehaan** [comment] 2014-01-04 19:05
This is now merged in and I've emailed the list to get some final testing in before having this finally replace -c ssh proper.

Thanks very much!

**Closed as completed by mpdehaan** 2014-01-04 19:05 UTC
Labels: bug
