### ISSUE TITLE
su hangs when home directory does not exist for the user.

### ISSUE THREAD

**Issue by arlinton** [ansible/ansible#9847] opened 2014-12-18 01:05 UTC
Hi there,

I've encountered an infinite hang when using the following command line and this example output:
    anisble vms -u randomuser -k --su --ask-su-pass -a 'whoami'

```
su password:
<192.168.122.5> ESTABLISH CONNECTION FOR USER: randomuser on PORT 22 TO 192.168.122.5
<192.168.122.5> REMOTE_MODULE command whoami
<192.168.122.5> EXEC /bin/sh -c 'mkdir -p /tmp/.randomuser/ansible/ansible-tmp-1418850953.24-280533105060233 && chmod a+rx /tmp/.randomuser/ansible/ansible-tmp-1418850953.24-280533105060233 && echo /tmp/.randomuser/ansible/ansible-tmp-1418850953.24-280533105060233'
<192.168.122.5> PUT /tmp/tmpogJNxA TO /tmp/.randomuser/ansible/ansible-tmp-1418850953.24-280533105060233/command
<192.168.122.5> EXEC /bin/sh -c 'su root -c "/bin/sh -c '"'"'echo SUDO-SUCCESS-enoryfrfdmmjizfrplcjcbgwifwgmapg; LANG=C LC_CTYPE=C /usr/bin/python /tmp/.randomuser/ansible/ansible-tmp-1418850953.24-280533105060233/command; rm -rf /tmp/.randomuser/ansible/ansible-tmp-1418850953.24-280533105060233/ >/dev/null 2>&1'"'"'"'
```

After poke around in the source code I found that the verbose output wasn't enough to tell me what was going on. I made a minor change to determine what was the cause:

```
--- paramiko_ssh.py 2014-12-18 00:56:11.220560347 +0000
+++ paramiko_ssh_patched.py 2014-12-18 00:57:29.914347181 +0000
@@ -239,6 +239,7 @@
                 if self.runner.sudo_pass or self.runner.su_pass:

                     while True:
+                        vvv("OUTPUT %s" % sudo_output, host=self.host)

                         if success_key in sudo_output or \
                             (self.runner.sudo_pass and sudo_output.endswith(prompt)) or \
```

The output of the said command above now looked similar this:

```
su password:
<192.168.122.5> ESTABLISH CONNECTION FOR USER: randomuser on PORT 22 TO 192.168.122.5
<192.168.122.5> REMOTE_MODULE command whoami
<192.168.122.5> EXEC /bin/sh -c 'mkdir -p /tmp/.randomuser/ansible/ansible-tmp-1418850953.24-280533105060233 && chmod a+rx /tmp/.randomuser/ansible/ansible-tmp-1418850953.24-280533105060233 && echo /tmp/.randomuser/ansible/ansible-tmp-1418850953.24-280533105060233'
<192.168.122.5> PUT /tmp/tmpogJNxA TO /tmp/.randomuser/ansible/ansible-tmp-1418850953.24-280533105060233/command
<192.168.122.5> EXEC /bin/sh -c 'su root -c "/bin/sh -c '"'"'echo SUDO-SUCCESS-enoryfrfdmmjizfrplcjcbgwifwgmapg; LANG=C LC_CTYPE=C /usr/bin/python /tmp/.randomuser/ansible/ansible-tmp-1418850953.24-280533105060233/command; rm -rf /tmp/.randomuser/ansible/ansible-tmp-1418850953.24-280533105060233/ >/dev/null 2>&1'"'"'"'
<192.168.122.5> OUTPUT
<192.168.122.5> OUTPUT Could not chdir to home directory /home/randomuser: No such file or directory
<192.168.122.5> OUTPUT Could not chdir to home directory /home/randomuser: No such file or directory Password:
```

After this i saw that the 'Password:' prompt was at the end of the string and what solved the issue was the following patch:

```
--- paramiko_ssh.py 2014-12-18 00:56:11.220560347 +0000
+++ paramiko_ssh_patched.py 2014-12-18 01:03:59.250278669 +0000
@@ -239,6 +239,7 @@
                 if self.runner.sudo_pass or self.runner.su_pass:

                     while True:
+                        vvv("OUTPUT %s" % sudo_output, host=self.host)

                         if success_key in sudo_output or \
                             (self.runner.sudo_pass and sudo_output.endswith(prompt)) or \
@@ -253,7 +254,7 @@
                             else:
                                 raise errors.AnsibleError('ssh connection ' +
                                     'closed waiting for password prompt')
-                        sudo_output += chunk
+                        sudo_output = chunk

                     if success_key not in sudo_output:
```

The output of the ansible command is now:

```
su password:
<192.168.122.5> ESTABLISH CONNECTION FOR USER: randomuser on PORT 22 TO 192.168.122.5
<192.168.122.5> REMOTE_MODULE command whoami
<192.168.122.5> EXEC /bin/sh -c 'mkdir -p /tmp/.randomuser/ansible/ansible-tmp-1418851006.59-186214506171513 && chmod a+rx /tmp/.randomuser/ansible/ansible-tmp-1418851006.59-186214506171513 && echo /tmp/.randomuser/ansible/ansible-tmp-1418851006.59-186214506171513'
<192.168.122.5> PUT /tmp/tmptihHkN TO /tmp/.randomuser/ansible/ansible-tmp-1418851006.59-186214506171513/command
<192.168.122.5> EXEC /bin/sh -c 'su root -c "/bin/sh -c '"'"'echo SUDO-SUCCESS-cypdpfxjcdmrnjzgtttkxjlwmlibmjtk; LANG=C LC_CTYPE=C /usr/bin/python /tmp/.randomuser/ansible/ansible-tmp-1418851006.59-186214506171513/command; rm -rf /tmp/.randomuser/ansible/ansible-tmp-1418851006.59-186214506171513/ >/dev/null 2>&1'"'"'"'
<192.168.122.5> OUTPUT
<192.168.122.5> OUTPUT Could not chdir to home directory /home/randomuser: No such file or directory
<192.168.122.5> OUTPUT Password:
192.168.122.5 | success | rc=0 >>
root
```

Regards,
~arlinton

**Comment by jctanner** [comment] 2016-05-27 12:57
Error message in 1.6.x ...

```
SSH password: 
sudo password [defaults to SSH password]: 

PLAY [u1404] ****************************************************************** 

TASK: [shell whoami] ********************************************************** 
<u1404> ESTABLISH CONNECTION FOR USER: testuser1 on PORT 22 TO u1404
<u1404> REMOTE_MODULE command whoami #USE_SHELL
<u1404> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1464353862.42-160889733902537 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1464353862.42-160889733902537 && echo $HOME/.ansible/tmp/ansible-tmp-1464353862.42-160889733902537'
fatal: [u1404] => Authentication or permission failure.  In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in "/tmp". Failed command was: mkdir -p $HOME/.ansible/tmp/ansible-tmp-1464353862.42-160889733902537 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1464353862.42-160889733902537 && echo $HOME/.ansible/tmp/ansible-tmp-1464353862.42-160889733902537, exited with result 1

FATAL: all hosts have already failed -- aborting
```

Error message in 2.1 ..

```
No config file found; using defaults
SSH password: 
SUDO password[defaults to SSH password]: 
[DEPRECATION WARNING]: Instead of su/su_user, use become/become_user and set become_method to 'su' 
(default is sudo).
This feature will be removed in a future release. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
Loaded callback default of type stdout, v2.0

PLAYBOOK: site.yml *************************************************************
1 plays in site.yml

PLAY [u1404] *******************************************************************

TASK [command] *****************************************************************
task path: /home/jtanner/workspace/issues/AP-9847/site.yml:6
<u1404> ESTABLISH CONNECTION FOR USER: testuser1 on PORT 22 TO u1404
<u1404> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1464353688.3-192532736642615 `" && echo ansible-tmp-1464353688.3-192532736642615="` echo $HOME/.ansible/tmp/ansible-tmp-1464353688.3-192532736642615 `" ) && sleep 0'
fatal: [u1404]: UNREACHABLE! => {"changed": false, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo $HOME/.ansible/tmp/ansible-tmp-1464353688.3-192532736642615 `\" && echo ansible-tmp-1464353688.3-192532736642615=\"` echo $HOME/.ansible/tmp/ansible-tmp-1464353688.3-192532736642615 `\" ), exited with result 1", "unreachable": true}
        to retry, use: --limit @site.retry

PLAY RECAP *********************************************************************
u1404                      : ok=0    changed=0    unreachable=1    failed=0   
```

**Comment by jctanner** [comment] 2016-05-27 13:00
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us. 

Testing this on the version you have specified, we cannot reproduce this problem.

Our reasons and evidence for this are:
- We detect a failure in su and provide a relevant error to the user in 1.6.x and in 2.1.

And we suggest that:
- Check the behavior on a more recent version of ansible.

As such, we are most likely going to close this ticket.  Should you disagree with this conclusion, you may also wish to join our mailing lists, which are very active:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Thank you once again for this and your interest in Ansible!

**Closed as completed by jctanner** 2016-05-27 13:00 UTC
Labels: bug
