### ISSUE TITLE
rescue not called after fail... 

### ISSUE THREAD

**Issue by snemir2** [ansible/ansible#17912] opened 2016-10-05 18:17 UTC
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

block/rescue does not act as expected... 
##### ANSIBLE VERSION

```
 ansible --version
ansible 2.1.1.0
  config file = /ansible/conf/ansible.cfg
  configured module search path = Default w/o overrides

```
##### SUMMARY

I have the following in my tasks/main.yml
- name: FAIL IF STATE IS NOT HEALTHY
  fail: msg="{{inventory_hostname}} is not in HEALTHY state"
  when: HDP_host_state != "HEALTHY"
- debug:  msg="{{inventory_hostname}} is HEALTHY"
  - rescue:
  - debug: msg="Not all nodes in HEALTHY state"
  - always:
- debug: msg="This should run"

Rescue or Always do not executed if fail above executes. 
##### STEPS TO REPRODUCE

```

```

##### EXPECTED RESULTS

expected rescue and always debug statements to pring 
##### ACTUAL RESULTS

TASK [HDP_check_cluster_node_state : FAIL IF STATUS IS NOT HEALTHY] ************
fatal: [hqhddev90.pclc0.merkle.local]: FAILED! => {"changed": false, "failed": true, "msg": "hqhddev90.pclc0.merkle.local is not in HEALTHY status"}
fatal: [hqhddev91.pclc0.merkle.local]: FAILED! => {"changed": false, "failed": true, "msg": "hqhddev91.pclc0.merkle.local is not in HEALTHY status"}
fatal: [hqhddev92.pclc0.merkle.local]: FAILED! => {"changed": false, "failed": true, "msg": "hqhddev92.pclc0.merkle.local is not in HEALTHY status"}
fatal: [hqhddev93.pclc0.merkle.local]: FAILED! => {"changed": false, "failed": true, "msg": "hqhddev93.pclc0.merkle.local is not in HEALTHY status"}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @/home/snemirovsky/.ansible-retry/HDP_patch_MASTER_NODES_WITH_DOWNTIME.retry

```
TASK [HDP_check_cluster_node_state : FAIL IF STATUS IS NOT HEALTHY] ************
fatal: [hqhddev90.pclc0.merkle.local]: FAILED! => {"changed": false, "failed": true, "msg": "hqhddev90.pclc0.merkle.local is not in HEALTHY status"}
fatal: [hqhddev91.pclc0.merkle.local]: FAILED! => {"changed": false, "failed": true, "msg": "hqhddev91.pclc0.merkle.local is not in HEALTHY status"}
fatal: [hqhddev92.pclc0.merkle.local]: FAILED! => {"changed": false, "failed": true, "msg": "hqhddev92.pclc0.merkle.local is not in HEALTHY status"}
fatal: [hqhddev93.pclc0.merkle.local]: FAILED! => {"changed": false, "failed": true, "msg": "hqhddev93.pclc0.merkle.local is not in HEALTHY status"}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @/home/snemirovsky/.ansible-retry/HDP_patch_MASTER_NODES_WITH_DOWNTIME.retry


```

**Comment by jimi-c** [comment] 2016-10-05 19:52
@snemir2 do you have `-` in front of rescue and always in your actual main.yml? If so, that's the problem - you're essentially creating new blocks with each one of those. Your block should look like this:

<pre>
- block:
  - name: FAIL IF STATE IS NOT HEALTHY
    fail: msg="{{inventory_hostname}} is not in HEALTHY state"
    when: HDP_host_state != "HEALTHY"
  - debug:  msg="{{inventory_hostname}} is HEALTHY"
  rescue:
  - debug: msg="Not all nodes in HEALTHY state"
  always:
  - debug: msg="This should run"
</pre>

Beyond that, I cannot reproduce the issue stated, so I'll go ahead and close this now.  If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2016-10-05 19:52 UTC
Labels: affects_2.1, bug

**Comment by snemir2** [comment] 2016-10-05 20:00
thanks, will give that a try! Perhaps, docs need to be updated?   the examples shown only show within tasks block,  not within roles..

**Comment by snemir2** [comment] 2016-10-07 21:10
actually, no, this is not working.  
 main.yml for a role:
`
- block:
  - name: Task to fail
    command: /bin/false
  
  rescue:
  - name: this should print
    debug: msg="In Rescue"
  
  always:
  - name: this should always print
    debug: msg="In Always"
    '
    output:
    PLAY [hqhddev91.pclc0.merkle.local] ********************************************

TASK [test_block : Task to fail] ***********************************************
fatal: [hqhddev91.pclc0.merkle.local]: FAILED! => {"changed": true, "cmd": ["/bin/false"], "delta": "0:00:00.014387", "end": "2016-10-07 17:05:37.438613", "failed": true, "rc": 1, "start": "2016-10-07 17:05:37.424226", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************

**Comment by jimi-c** [comment] 2016-11-14 05:56
@snemir2 sorry for the late follow-up, however on `stable-2.1`, `stable-2.2` and `devel` I'm seeing the expected output from the above.

**Comment by snemir2** [comment] 2016-11-14 12:47
Yep.   Confirmed working on 2.1

Get Outlook for Android

On Mon, Nov 14, 2016 at 12:57 AM -0500, "James Cammarata" notifications@github.com wrote:

@snemir2 sorry for the late follow-up, however on stable-2.1, stable-2.2 and devel I'm seeing the expected output from the above.
