### ISSUE TITLE
Provide a way to quiet the "localhost | success >>" output at the start of setup

### ISSUE THREAD

**Issue by jefferai** [ansible/ansible#8520] opened 2014-08-08 15:15 UTC
##### Issue Type:

Feature Request
##### Ansible Version:

ansible 1.7
##### Environment:

OSX 10.9 and Ubuntu 14.04
##### Summary:

When you run the setup module from the command line, you see the following:

```
$ ansible -m setup localhost
localhost | success >> {
    "ansible_facts": {
```

Can there be a way to not show the `localhost | success >>` part of the output? If there is a way, I haven't found it by looking at the command options. Right now I need to parse that out before I can feed the output into e.g. `jq`.
##### Steps To Reproduce:

Run the setup module.
##### Expected Results:

There is a way to provide only the JSON output.
##### Actual Results:

Extra information is added prior to the JSON.

**Comment by mpdehaan** [comment] 2014-08-08 15:35
Part of the issue is that if run on multiple hosts, it would not be able to output hosts as they were coming back in realtime, but would have to wait and return JSON for all hosts.

There is "--tree" which will output JSON to the filesystem, but maybe is not what you want.

Open to ideas for sure, though I think the multiple-system output case is something we need to consider for this.

**Comment by jefferai** [comment] 2014-08-08 16:36
A couple of notes:

1) Perhaps when the only target is localhost, it can be omitted
2) Generally speaking, when run with multiple systems, each one will hopefully have a different ansible_fqdn/ansible_hostname, which dispels any ambiguity.

**Comment by bcoca** [comment] 2014-08-09 14:42
Why not just "|grep -v success" ?

Brian Coca

**Comment by jefferai** [comment] 2014-08-09 23:45
Because the opening bracket of the JSON output is on that line, so the result of that grep is invalid JSON.

**Comment by jefferai** [comment] 2014-08-09 23:49
@bcoca And to be clear, it's not that you can't work around it -- I can use `cut` to remove the first X characters, for instance -- but it'd be nice to be able to silence that output to begin with.

@mpdehaan Idea: in the JSON is the ansible_facts dictionary, which is basically all of the returned output. Why not add an additional dictionary with the result of the call, rather than printing it before the JSON? Then it's both easily parseable and completely backwards compatible for programs that aren't expecting it while providing the same information.

**Comment by bcoca** [comment] 2014-08-10 01:26
or a smaller change, add 1 newline after "success​" and before "{"

**Comment by nocive** [comment] 2014-08-11 13:33
+1

IMO, a command line flag to get the raw output from ansible commands is useful for a variety of different scenarios.

**Comment by jefferai** [comment] 2014-08-11 16:37
@bcoca I think that would be fine, but I'd still like to see the informational output be included in the JSON, just not under ansible_facts. Backwards compatibility + easy machine parsing = win.

**Comment by jimi-c** [comment] 2016-07-09 20:34
# Switch to Proposal

Hi!

As of April of 2016, we have started using the Ansible Proposal process for large feature ideas or changes in current functionality, such as this. Because this issue has been open for so long without any action, we are going to go ahead and close it at this time. If you are still interested in seeing this new feature get into Ansible, please submit a proposal for it using this process.

https://github.com/ansible/proposals/blob/master/proposals_process_proposal.md

If you have any further questions, please let us know by stopping by our devel mailing list, or our devel IRC channel:
- #ansible-devel on Freenode
- https://groups.google.com/forum/#!forum/ansible-devel

Thank you!

**Closed as completed by jimi-c** 2016-07-09 20:34 UTC
Labels: feature

**Comment by jefferai** [comment] 2016-07-09 20:38
@jimi-c It was open for so long without any action because nobody from Ansible paid any attention to it -- or even said something like "we'll accept a PR with this functionality".

It's really not very nice to close issues for non-responsiveness when the lack of response is coming from upstream, not from the reporter.

Before putting in effort in the new Proposal process, can someone comment on whether this is even functionality that would be considered?

**Comment by jimi-c** [comment] 2016-07-10 05:38
@jefferai really I would say this should be something that's done via a callback plugin.

**Comment by clintmod** [comment] 2018-02-02 16:25
This is bullshit… why would you half ass output json (by default) that has to be munged before it can be consumed by a json parser? Put this in your own proposal system.

**Comment by jefferai** [comment] 2018-02-02 17:52
@clintmod Yeah.

**Comment by skunk73** [comment] 2018-02-04 23:40
`sed '/^[ }].*/!s/^/"/;s/ =>/":/;1s/^/{\n/;$s/$/\n}/'`

**Comment by jefferai** [comment] 2018-02-05 00:07
@skunk73 ?

**Comment by skunk73** [comment] 2018-02-05 00:12
after piping ansible's output to the above command you get a valid json...

**Comment by jefferai** [comment] 2018-02-05 00:36
The problem isn't how to filter it. That's easy. The problem is that you *shouldn't have to*. Ansible is mixing machine-oriented output (JSON) with human-oriented output (text status). The result is something that takes needless work to use in a machine-based way and at the same time isn't in a human-friendly format. You lose either way.

**Comment by skunk73** [comment] 2018-02-05 00:48
my intention was to just offer a quick workaround for a problem i was facing myself and since i came here because i was googling for a solution it might save time to somebody else too imho...

**Comment by damobrisbane** [comment] 2018-02-15 22:19
Yeh, grappling with the same moronic issue and lack of action - as articulated two years ago - for broken command line output. Raise issue, do what in what new system??

**Comment by sivel** [comment] 2018-02-15 22:32
The proper way to achieve the goal of getting JSON from ansible on the CLI is to use the `json` stdout callback plugin.  The default output is not designed to be machine parsable.

#### via ansible (adhoc):

```
ANSIBLE_LOAD_CALLBACK_PLUGINS=true ANSIBLE_STDOUT_CALLBACK=json ansible ...
```

#### via ansible-playbook:

```
ANSIBLE_STDOUT_CALLBACK=json ansible-playbook ...
```

It may also be useful to set `ANSIBLE_COMMAND_WARNINGS=0` and `ANSIBLE_RETRY_FILES_ENABLED=0`

These configurations can also be set in an `ansible.cfg` file: http://docs.ansible.com/ansible/latest/config.html

For a simple adhoc ping, the output should look like:

```json
{
    "plays": [
        {
            "play": {
                "id": "784f43a0-97cc-db4e-e204-000000000007",
                "name": "Ansible Ad-Hoc"
            },
            "tasks": [
                {
                    "hosts": {
                        "localhost": {
                            "_ansible_no_log": false,
                            "_ansible_parsed": true,
                            "changed": false,
                            "failed": false,
                            "invocation": {
                                "module_args": {
                                    "data": "pong"
                                }
                            },
                            "ping": "pong"
                        }
                    },
                    "task": {
                        "id": "784f43a0-97cc-db4e-e204-000000000009",
                        "name": ""
                    }
                }
            ]
        }
    ],
    "stats": {
        "localhost": {
            "changed": 0,
            "failures": 0,
            "ok": 1,
            "skipped": 0,
            "unreachable": 0
        }
    }
}
```

**Comment by damobrisbane** [comment] 2018-02-16 02:11
Thanks for the great explanation, I jumped the gun a bit with my frustration...

**Comment by clintmod** [comment] 2018-02-16 20:42
@sivel when I run this in ansible 2.4.3.0 `ANSIBLE_LOAD_CALLBACK_PLUGINS=true ANSIBLE_STDOUT_CALLBACK=json ansible localhost -m ping` literally nothing get's output to the console.

**Comment by sivel** [comment] 2018-02-16 21:11
Apologies, I forgot to include that this will be new functionality in v2.5.  2.5.0.b2 has been released.  For the release roadmap see: http://docs.ansible.com/ansible/devel/roadmap/ROADMAP_2_5.html

**Comment by max-allan-surevine** [comment] 2018-12-06 19:43
> Apologies, I forgot to include that this will be new functionality in v2.5. 2.5.0.b2 has been released. For the release roadmap see: http://docs.ansible.com/ansible/devel/roadmap/ROADMAP_2_5.html

What is it called in the roadmap? I can't see anything in the linked page that looks like "don't pollute the JSON output with human readable stuff"
