### ISSUE TITLE
Extraneous files in release tarball

### ISSUE THREAD

**Issue by hlieberman** [ansible/ansible#11051] opened 2015-05-22 00:34 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

Ansible 1.9.1
##### Ansible Configuration:

N/A
##### Environment:

N/A
##### Summary:

The release tarball for version 1.9.1 includes .git repositories for the extras and modules repo.  These should be removed in the release tarball.

**Comment by bcoca** [comment] 2015-06-26 21:37
confirmed, found the .git file even in 1.9.2

**Comment by jimi-c** [comment] 2015-07-13 19:46
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-07-13 19:46 UTC
Labels: bug
