### ISSUE TITLE
Can not force ansible to use http with winrm: ansible_winrm_scheme=http

### ISSUE THREAD

**Issue by ruzickap** [ansible/ansible#16460] opened 2016-06-27 15:28 UTC
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
$ ansible --version | grep ^ansible
ansible 2.1.0.0
```
##### OS / ENVIRONMENT

Fedora 23
##### SUMMARY

Ansible ignores "ansible_winrm_scheme" when using non-standard ansible_ssh_port.
##### STEPS TO REPRODUCE

This usually happen when I use "-e ansible_connection=winrm -e ansible_winrm_scheme=http":

```
ansible-playbook -vvv  -e ansible_ssh_user=vagrant -e ansible_ssh_pass=vagrant -e ansible_ssh_port=3149 -e ansible_connection=winrm -e ansible_winrm_scheme=http -i "${IP}," win.yml
```

then I got:

```
PLAYBOOK: win.yml **************************************************************
1 plays in win.yml

PLAY [test raw module] *********************************************************

TASK [setup] *******************************************************************
<127.0.0.1> ESTABLISH WINRM CONNECTION FOR USER: vagrant on PORT 3149 TO 127.0.0.1
fatal: [127.0.0.1]: UNREACHABLE! => {"changed": false, "msg": "ssl: HTTPSConnectionPool(host='127.0.0.1', port=3149): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fd8f225c510>: Failed to establish a new connection: [Errno 111] Connection refused',))", "unreachable": true}
        to retry, use: --limit @win.retry
```

##### EXPECTED RESULTS

Ansible should be able to use "http" winrm scheme with non-standard ports.
##### ACTUAL RESULTS

Ansible ignores ansible_winrm_scheme=http when using it with combination of ansible_ssh_port=3149 environments.

**Comment by nitzmahone** [comment] 2016-07-05 22:27
This should be fixed as of 2.1.1 RC1 by https://github.com/ansible/ansible/commit/6b286ee0c88f3252a27ff94f39d794566c3f7d6f

Please let us know if it works for you from 2.1.1 RC1 or stable-2.1.

**Closed as completed** 2016-07-14 18:09 UTC
Labels: windows, bug

**Comment by amitangarkar** [comment] 2016-08-22 12:48
ansible 2.1.1.0

Using /etc/ansible/ansible.cfg as config file
Loaded callback minimal of type stdout, v2.0
<10.10.32.29> ESTABLISH WINRM CONNECTION FOR USER: amitagg on PORT 5985 TO 10.10.32.29
10.10.32.29 | UNREACHABLE! => {
    "changed": false,
    "msg": "plaintext: HTTPConnectionPool(host='10.10.32.29', port=5985): Max retries exceeded with url: /wsman (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x34bd790>, 'Connection to 10.10.32.29 timed out. (connect timeout=30)'))",
    "unreachable": true
}

**Comment by jhawkesworth** [comment] 2016-08-23 13:55
@amitangarkar I think your issue might be slightly different from the original poster as you are using the standard port (5985) and an http connection (as opposed to an https connection) appears to be being attempted.  You are getting a connection timeout, implying the host wasn't reachable, whereas original bug report was receiving connection refused.

I suggest you check to see if you can make a connection to port 5985 on the target windows machine and ensure there is no firewall stopping the connection between your ansible controller and windows host.  If you still have problems please either ask on ansible-project google group (which is seen by many more people than the github tracker) or #ansible irc channel.

**Comment by sohail-prodevans** [comment] 2017-07-29 16:00
HTTPConnectionPool(host='192.168.56.10', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x228c850>: Failed to establish a new connection: [Errno 111] Connection refused',))", 
    "unreachable": true

**Comment by jhawkesworth** [comment] 2017-07-29 22:05
@sohail-prodevans please check you have followed all instructions here: https://docs.ansible.com/ansible/latest/intro_windows.html

If you are still having problems, please raise a new issue and complete all items on the issue template - closed issues are not usually monitored by ansible core team and there is not enough information to help you above.

**Comment by MattJM12** [comment] 2017-08-10 13:21
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]

xx.xx.x.xx | UNREACHABLE! => {
    "changed": false,
    "msg": "plaintext: HTTPConnectionPool(host='xx.xx.x.xx', port=5986): Read timed out. (read timeout=120)",
    "unreachable": true
 
Debian host to Windows 7 and 10. 

Any ideas?

**Comment by jhawkesworth** [comment] 2017-08-15 15:38
@MattJM12  please check you have followed all instructions here: https://docs.ansible.com/ansible/latest/intro_windows.html

If you are still having problems, please raise a new issue and complete all items on the issue template - closed issues are not usually monitored by ansible core team and there is not enough information to help you above.

**Comment by AnsibleBala** [comment] 2018-03-14 17:56
HTTPConnectionPool

error states the firewall issue , need to enable the firewall and allow the port locally . (in windows -> allow or set the inbound rule for the port of the specific service.
