### ISSUE TITLE
ansible-galaxy munges installed role filenames under Ansible 2.3

### ISSUE THREAD

**Issue by command-tab** [ansible/ansible#23877] opened 2017-04-21 21:45 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible-galaxy

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /Users/callen/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 17 2016, 23:03:43) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### CONFIGURATION
Nothing special.

##### OS / ENVIRONMENT
macOS Sierra 10.12.4

##### SUMMARY
When using `ansible-galaxy` to check out a `requirements.yml` role, if a template inside the role contains the name of the role, the template file gets mangled during checkout. It should leave files named as they are in the repo.

##### STEPS TO REPRODUCE

Create a `requirements.yml` file with a single, simple role reference:

```yaml
---
- src: https://github.com/commandtab/nginx.git
  scm: git
  version: 1.0.0
```

Install the role:

`ansible-galaxy install -r requirements.yml --force`

##### EXPECTED RESULTS
I expect the role to be cloned from the git repo to disk, leaving all filenames intact.

##### ACTUAL RESULTS
If you compare the contents of the [role git repo's `templates/` directory](https://github.com/commandtab/nginx/tree/master/templates) to the checked-out role, the `templates/` directory on disk has had two of the files renamed:

* `nginx.conf.j2` became `.conf.j2`
* `nginx.repo.j2` became `.repo.j2`

Note that `mime.types.j2` was not renamed.

**Comment by sivel** [comment] 2017-04-21 21:55
Closing this as a duplicate of the already resolved https://github.com/ansible/ansible/issues/22572

**Closed as completed by sivel** 2017-04-21 21:55 UTC
Labels: affects_2.3, c:cli/galaxy, bug
