### ISSUE TITLE
Fact gathering is slow with a high open file limit

### ISSUE THREAD

**Issue by markgoddard** [ansible/ansible#24785] opened 2017-05-18 16:23 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Ansible setup module.

##### ANSIBLE VERSION
ansible 2.2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
Control: CentOS 7.3
Target: CentOS 7.3

##### SUMMARY
When gathering facts for a host with a high open file limit setting, fact gathering can take a long time. This is exacerbated on systems with many network interfaces. On a system with an open file limit of 1048576 and ~50 network interfaces (mostly virtual), fact gathering takes in excess of 20 seconds.

##### STEPS TO REPRODUCE
Set the open file limit to a high value:

```yaml
- hosts: all
  become: yes
  tasks:
  - name: increase file descriptor limit
    copy:
      dest: /etc/security/limits.d/99-nofile.conf
      content: |
        root soft nofile 1048576
        root hard nofile 1048576
```

Gather facts:

```yaml
- hosts: all
  become: yes
  gather_facts: yes
```

##### EXPECTED RESULTS
Facts are gathered in a reasonable time.

##### ACTUAL RESULTS
Facts took a long time to be gathered.

**Comment by markgoddard** [comment] 2017-05-18 16:33
After delving into the facts module and the module.run_command method, I noticed that by default, subprocess.Popen gets called with close_fds=True. This causes subprocess to close all file descriptors up to the open file limit.

Related: https://bugs.python.org/issue8052 and https://bugs.python.org/issue11284.

**Comment by sivel** [comment] 2017-05-18 16:36
Closing as a duplicate of https://github.com/ansible/ansible/issues/24228

**Closed as completed by sivel** 2017-05-18 16:36 UTC
Labels: affects_2.2, module, bug
