### ISSUE TITLE
[get_url] DNS resolution is done on the controller, not the target

### ISSUE THREAD

**Issue by xicesky** [ansible/ansible#10847] opened 2015-04-27 18:21 UTC
get_url sometimes fails, if the DNS configuration on the ansible controller is wrong. Names seems to be resolved on the controller, then sent to the client (i suspect).

Steps to reproduce:
Configure your controller to mis-resolve a hostname, e.g. by inserting into /etc/hosts:
1.2.3.4 github.com

Try to download a file on the target machine via get_url, this then fails, because the target machine cannot find github.com at the IP address 1.2.3.4.

**Comment by bcoca** [comment] 2015-04-27 19:37
soo, I'm not able to reproduce this, also to note that get_url always gets executed on the target and passed the paramaters via file, ansible should not be resolving any parameters unless you are asking it to. lookup('pipe', 'dig ' + hostname + '|grep...' )

**Comment by jimi-c** [comment] 2015-07-12 23:12
Hi @xicesky, this would only be true if there were a `get_url` action plugin, which for core there is not. So the destination hosts must be having issues resolving things for some reason, or there is some other issue going on here.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-07-12 23:12 UTC
Labels: net_tools, bug
