### ISSUE TITLE
Team where can I find script to ConfigureRemotingForAnsible?

### ISSUE THREAD

**Issue by jigyasapriyadarshini** [ansible/ansible#81255] opened 2023-07-13 18:04 UTC
### Summary

Team I was using the link https://github.com/ansible/ansible/blob/devel/examples/scripts/ConfigureRemotingForAnsible.ps1 to enable winrm ports using ansible. Can you share the updated path/ branch?

### Issue Type

Documentation Report

### Component Name

https://github.com/ansible/ansible/blob/devel/examples/scripts/ConfigureRemotingForAnsible.ps1

### Ansible Version

```console
$ ansible --version
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Ubuntu

### Additional Information

https://github.com/ansible/ansible/blob/devel/examples/scripts/ConfigureRemotingForAnsible.ps1 unavailable 

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by mattclay** [comment] 2023-07-13 18:05
Closing as a duplicate of https://github.com/ansible/ansible/issues/81240

**Closed as completed by mattclay** 2023-07-13 18:05 UTC
