### ISSUE TITLE
Service module fails on a stopped nginx service on Ubuntu 12.04

### ISSUE THREAD

**Issue by lorin** [ansible/ansible#564] opened 2012-07-10 18:19 UTC
When you ask for status of a stopped nginx service (on Ubuntu 12.04), it gives the following status message:

```
root@precise32:~# service nginx stop
Stopping nginx: nginx.
root@precise32:~# service nginx status
 * could not access PID file for nginx
```

Unfortunately, ansible doesn't like that message, and so attempts to do anything to the service fail, e.g.:

```
$ ansible all -m service -a "name=nginx state=started"
192.168.33.11 | FAILED => failed to parse: {"msg": "failed determining the current service state => state stays unchanged", "failed": true}
```

**Comment by jeremysmitherman** [comment] 2012-07-10 20:43
I have a fix for this in https://github.com/ansible/ansible/pull/566

The problem is the /usr/sbin/service nginx status is returning "\* Cannot access PID file" or similar.  I added code to check for that return.

**Comment by mpdehaan** [comment] 2012-07-10 23:05
I accepted this, but I probably shouldn't have as in general we've been pushing for people to fix their init scripts.   Be sure to file this with upstream as well.

**Closed as completed by mpdehaan** 2012-07-10 23:05 UTC

**Comment by lorin** [comment] 2012-07-11 13:04
Reported this upstream:

https://bugs.launchpad.net/ubuntu/+source/nginx/+bug/1023389

**Comment by lorin** [comment] 2012-07-11 18:20
Her's how the bug got triaged upstream:

Importance being set to: Wishlist.

Reasoning (https://wiki.ubuntu.com/Bugs/Importance):
Wishlist: Missing functionality.

I am marking this as Wishlist as the only thing that is affected by this "flaw" in the init script is the Ansible tool which you have linked us to. Secondly, since this is not technically a bug, but a request to have the init script's "status" return differently than currently is returned, I do not believe it qualifies for "Low" importance, as there is no _actual_ bug in the init script nor the Ubuntu package for nginx, but a flaw in how Ansible parses such information.

I am also marking this as "triaged" in accordance with Ubuntu Bug triaging policies, as "Wishlist" bugs should also be marked as "Triaged".

---

Thomas Ward
LPID: trekcaptainusa-tw
Ubuntu Bug Squad Member
Ubuntu Bug Control Member

**Comment by teward** [comment] 2012-07-11 18:28
Correction to https://github.com/ansible/ansible/issues/564#issuecomment-6914956:

This bug is not actually a bug in nginx.  While I may have "Wishlisted" the bug, on second review with the nginx source in hand (and with Comment 4 on the launchpad bug, https://bugs.launchpad.net/ubuntu/+source/nginx/+bug/1023389/comments/4), I did change its status to "Opinion" / "Wishlist"  (Opinion being status, Wishlist being importance).  Please note that the checks being done in the init script for Ubuntu uses the LSB (Linux Standard Base) function "status_of_proc" to report this message, which returns "Could not find the PID" if the process is not running.

I propose that this flaw is therefore part of Ansible in the sense that the check being used by the nginx init script returns a more informative message that "the PID file could not be found", but Ansible _expects_ 'stop' to be used somewhere. (for example, a service could have been started, but then been reniced or killed without changing the status with the init script).  There are programs used by some specialized-hosting companies which say "could not find PID, process could have died" when using a status command (not via init scripts, mind you).

Lorin, thanks for "upstream"ing this, but keep in mind that you should **_NEVER**_ assume that something will stay triaged.  I am but one Bug Control member, I can be wrong sometimes (its why there's collaboration on bugsquads).

---

Thomas Ward
LaunchPad ID: trekcaptainusa-tw
Ubuntu Bug Squad Member
Ubuntu Bug Control Member

**Comment by mpdehaan** [comment] 2012-07-11 18:31
I'm not really paying attention to this, but to clarify a few things.

All that string logic is there to handle init scripts that don't return error codes like we suspect, of which many distribution init scripts in various distributions are not pretty.   Return codes indiciating stopped are what we want to use, but in this case, there seems to have not been one.   I probably shouldn't have accepted a fix to handle the PID file message at all and let the init script stay broken, but I'm trying to be accomodating.

Clearly if there is a problem it's not with nginx but the init script from the packager.

**Comment by teward** [comment] 2012-07-11 18:34
@mpdehaan I understand, I was clarifying the "Bug was triaged" comment, as I have untriaged the bug, and elaborated on my reasoning/opinion.  (to correct @lorin)

**Comment by lorin** [comment] 2012-07-11 18:38
@TheLordOfTime Gotcha, no problem.

**Comment by mpdehaan** [comment] 2012-07-11 18:39
BTW, I'm more than happy to take education on the proper way to interpret running/not running on Ubuntu.   This was a user patch to bring it up to current speed, I think it's mostly reasonable, but improvements are welcome.

In general, it's good for a shell script to have a reasonably brain-dead way to interpret service status, and more so for a systems management app.

**Comment by teward** [comment] 2012-07-11 18:47
I agree.  Ubuntu though doesn't require each status to be clearly defined, which makes creating such administration and monitoring programs difficult, because you have to eventually start "guessing" as to possible status messages.

**Comment by teward** [comment] 2012-07-11 18:50
@lorin Final Update on Upstream LP Bug:

Bug marked as invalid by the Debian package maintainer for the 'nginx' package.
