### ISSUE TITLE
Dynamic include fails with KeyError: '_raw_params'

### ISSUE THREAD

**Issue by mgedmin** [ansible/ansible#17657] opened 2016-09-20 08:03 UTC
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

include
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

I'm trying to dynamically compute the include file, which fails with a KeyError.
##### STEPS TO REPRODUCE

``` yml
# test.yml

---
- hosts: localhost
  gather_facts: no
  vars:
    foo_state: present
  tasks:
    - include: "{{ dict(present='install', absent='remove')[foo_state] }}.yml"
      when: foo_state in ('present', 'absent')
```

``` yml
# install.yml

---
- debug: msg="installing foo"
```

``` yml
# remove.yml

---
- debug: msg="removing foo"
```

Now run `ansible-playbook -c local -i localhost, test.yml -vvv`
##### EXPECTED RESULTS

I expect install.yml to be included and executed.
##### ACTUAL RESULTS

```
ERROR! Unexpected Exception: '_raw_params'
the full traceback was:

Traceback (most recent call last):
  File "/home/mg/.venv/bin/ansible-playbook", line 92, in <module>
    exit_code = cli.run()
  File "/home/mg/.venv/local/lib/python2.7/site-packages/ansible/cli/playbook.py", line 154, in run
    results = pbex.run()
  File "/home/mg/.venv/local/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 73, in run
    pb = Playbook.load(playbook_path, variable_manager=self._variable_manager, loader=self._loader)
  File "/home/mg/.venv/local/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 53, in load
    pb._load_playbook_data(file_name=file_name, variable_manager=variable_manager)
  File "/home/mg/.venv/local/lib/python2.7/site-packages/ansible/playbook/__init__.py", line 98, in _load_playbook_data
    entry_obj = Play.load(entry, variable_manager=variable_manager, loader=self._loader)
  File "/home/mg/.venv/local/lib/python2.7/site-packages/ansible/playbook/play.py", line 115, in load
    return p.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/home/mg/.venv/local/lib/python2.7/site-packages/ansible/playbook/base.py", line 206, in load_data
    self._attributes[name] = method(name, ds[name])
  File "/home/mg/.venv/local/lib/python2.7/site-packages/ansible/playbook/play.py", line 167, in _load_tasks
    return load_list_of_blocks(ds=ds, play=self, variable_manager=self._variable_manager, loader=self._loader)
  File "/home/mg/.venv/local/lib/python2.7/site-packages/ansible/playbook/helpers.py", line 58, in load_list_of_blocks
    loader=loader
  File "/home/mg/.venv/local/lib/python2.7/site-packages/ansible/playbook/block.py", line 79, in load
    return b.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/home/mg/.venv/local/lib/python2.7/site-packages/ansible/playbook/base.py", line 206, in load_data
    self._attributes[name] = method(name, ds[name])
  File "/home/mg/.venv/local/lib/python2.7/site-packages/ansible/playbook/block.py", line 115, in _load_block
    use_handlers=self._use_handlers,
  File "/home/mg/.venv/local/lib/python2.7/site-packages/ansible/playbook/helpers.py", line 122, in load_list_of_tasks
    (not templar._contains_vars(t.args['_raw_params']) and not t.loop)
KeyError: '_raw_params'
```

**Comment by mgedmin** [comment] 2016-09-20 08:06
The reproducer example can be simplified by dropping the `when: ...` -- it still fails.

A workaround is to use

``` yaml
- include: "{{ {'present': 'install', 'absent': 'remove'}[foo_state] }}.yml"
```

**Comment by bcoca** [comment] 2016-09-20 14:03
dupe of #17428

**Closed as completed by bcoca** 2016-09-20 14:03 UTC
Labels: affects_2.1, bug
