### ISSUE TITLE
copy modules fails if lookup() files are reference in group_vars

### ISSUE THREAD

**Issue by tgolly** [ansible/ansible#10002] opened 2015-01-14 06:20 UTC
##### Summary:

For some reason the "copy" module bombs out if lookup('file', '...') is referenced in group_vars, even though the "copy" task itself does not reference that variable, and the file does exist relative to the role directory.
##### Steps to reproduce:

Please see this gist:  https://gist.github.com/tgolly/930dce54307139f9c758

You'll see that "authorized_key" tasks successfully references the "listofkeys" variable and deploys the file, then the "file" and "stat" tasks both work without error, then "copy" bombs out, even though it doesn't reference the "listofkeys" variable from group_vars/all.
##### Expected Results:

The file is copied without error.
##### Actual Results:

```
TASK: [myrole | copy src=/etc/hosts dest=/tmp/foo] ****************************
fatal: [localhost] => could not locate file in lookup: public_keys/somekey
```

**Comment by evoncken** [comment] 2015-01-18 18:36
Same here - could this be a regression, see https://github.com/ansible/ansible/issues/8297 ?

**Comment by bcoca** [comment] 2015-01-19 15:01
duplicate of #9944

**Closed as completed by bcoca** 2015-01-19 15:01 UTC
Labels: P2, bug

**Comment by linsomniac** [comment] 2015-04-28 04:09
This seems to still be a problem in 1.9.0 from the Ubuntu PPA.  I have a playbook that did the "lookup('file', 'path')" in the group_vars, which worked on 1.5.4 from Ubuntu Trust, and 1.7.2 back-ported fom Vivid, and it works in both of those.  But 1.9.0 reports the "could not locate file in lookup".

 I have worked around it by moving the lookup() from the group_vars into the role itself, but this seems like a regression.

**Comment by hyperfocus1338** [comment] 2015-05-06 07:04
I still have this issue on 1.9.1: https://github.com/ansible/ansible-modules-core/issues/1263

**Comment by bcoca** [comment] 2015-05-06 13:48
unrelated as this is directly in task
