### ISSUE TITLE
multiple include => conflicting action statements

### ISSUE THREAD

**Issue by hloeffler** [ansible/ansible#13324] opened 2015-11-26 13:05 UTC
in 1.9.4 this works: (in task/main.yml)

```
# user creation
#-------------------------------------------------------------------------------
- { include: create_user.yml, name: 'test1' }
- { include: create_user.yml, name: 'test2' }
- { include: create_user.yml, name: 'test3' }
```

in 2.0 => ERROR! conflicting action statements

**Comment by hloeffler** [comment] 2015-12-02 07:29
is this a bug or a feature in 2.0? @jimi-c @bcoca

**Comment by jimi-c** [comment] 2015-12-02 19:28
@hloeffler this is a bug, but based on the code this only happens when it detects two module actions in a single dictionary. Do you by chance have any custom modules, and if so would one have the file name of `name.py`?

**Comment by jimi-c** [comment] 2015-12-02 19:33
@hloeffler so this doesn't error for me, I'm thinking you may have a typo in your create_user.yml file? Also, I'm assuming `name` is not a param into  that included file, because `name` is reserved for the task and becomes the name of the include task itself.

**Comment by jimi-c** [comment] 2015-12-04 19:28
@hloeffler are you still seeing this on the latest devel?

**Comment by hloeffler** [comment] 2015-12-07 06:34
no, but i got a new error (befor the part with the multiple includes):

```
ERROR! The tasks/main.yml file for role 'packages/test1' must contain a list of tasks

The error appears to have been in '/root/ansible/roles/packages/test1/tasks/main.yml': line 7, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

#-------------------------------------------------------------------------------
- name: ensure foo is configured as desired
^ here
```

i try to create a testcase which i can to share

**Comment by hloeffler** [comment] 2015-12-07 06:48
yes, "same error" if i delete the lines with the 3 includes it runs,
if i include only one => error
if i delete the included file => same error

maybe misleading error msg?
how to get more debug msg? ( "-vvvv" wont help )

**Comment by hloeffler** [comment] 2015-12-07 07:19
okay, got "it":

this is okay:

```
- { include: /root/ansible/roles/test1/tasks/mysql_user.yml, test: 'test',test2: 'test2', mysql_user2: 'test' }
```

this not:

```
- { include: /root/ansible/roles/test1/tasks/mysql_user.yml, test: 'test',test2: 'test2', mysql_user: 'test' }
```

its not allowed to have a var with the same name as the included file

we use this in many places, what to do? (+ better error msg)

**Comment by Yannig** [comment] 2015-12-07 07:40
Well, the problem came from variable with the same content as there name. The following playbook show this:

``` yaml
---
# Vars mapper test

- name: "Test"
  hosts: "localhost"
  connection: "local"
  gather_facts: no
  vars:
    test: "test"
  tasks:
    - debug: var=test
```

Which result in the following result:

``` yaml
ansible-playbook vars-with-same-value-as-name.yml 

PLAY [Test] ********************************************************************

TASK [debug var=test] **********************************************************
ok: [localhost] => {
    "changed": false, 
    "test": "VARIABLE IS NOT DEFINED!"
}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```

**Comment by Yannig** [comment] 2015-12-07 07:44
Well, I think it's not the same problem. But anyway, this is a bug in debug code. I'll open a bug for this one.

**Comment by Yannig** [comment] 2015-12-07 07:51
The corresponding issue is opened here: https://github.com/ansible/ansible/issues/13453

**Comment by jimi-c** [comment] 2015-12-07 14:26
@hloeffler I merged the patch from @Yannig to address that bug, if you'd like to re-pull and test this?

**Comment by hloeffler** [comment] 2015-12-07 14:31
@jimi-c done, but wont help ( patch is only for task: "debug" )

**Comment by jimi-c** [comment] 2015-12-07 14:35
Ahh true, ok I'll dig into this a bit more as well.

**Comment by Yannig** [comment] 2015-12-07 14:37
@hloeffler I have tried to reproduce your problem but failed to succeed. Can you sent a find on your directories and snippets of your playbook code?

**Comment by hloeffler** [comment] 2015-12-07 14:48
ansible-playbook test-play.yml --diff --check -l $IP  -vvvv

```

ERROR! The tasks/main.yml file for role 'test1' must contain a list of tasks

The error appears to have been in '/root/ansible/roles/test1/tasks/main.yml': line 7, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

#-------------------------------------------------------------------------------
- { include: /root/ansible/roles/test1/tasks/mysql_user.yml, test: 'test',test2: 'test2', mysql_user: 'test' }
^ here
```

cat test-play.yml

```
---

- name: test
  hosts: localhost

  roles:
    - test1
```

find roles/test1/

```

roles/test1/
roles/test1/tasks
roles/test1/tasks/mysql_user.yml
roles/test1/tasks/main.yml
```

cat roles/test1/tasks/main.yml

```

---
- { include: /root/ansible/roles/test1/tasks/mysql_user.yml, test: 'test',test2: 'test2', mysql_user: 'test' }
- { include: /root/ansible/roles/test1/tasks/mysql_user.yml, test: 'test' }
```

cat roles/test1/tasks/mysql_user.yml 

```
---

- debug: msg=test
```

**Comment by jimi-c** [comment] 2015-12-07 15:44
Ok, so when I examine the error that's actually being caught in the YAML parsing portions of the role loading code, it is the same conflict message:

<pre>
Error was: ERROR! conflicting action statements
The error appears to have been in '/root/testing/13324/new/roles/test1/tasks/main.yml': line 3, column 3, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
# tasks file for roles/test1
- include: /root/ansible/roles/test1/tasks/mysql_user.yml
  ^ here
</pre>

It appears the way we're accepting params for includes doesn't quite mesh up with how they're parsed in 1.x.

**Comment by jimi-c** [comment] 2015-12-07 16:22
Technically, this syntax is not supported, and is not documented anywhere in http://docs.ansible.com/ansible/playbooks_roles.html. Instead, the includes should be structured as follows:

<pre>
- include: mysql_user.yml
  args:
    test: 'test'
    test2: 'test2'
    mysql_user: 'test'
- include: mysql_user.yml
  args:
    test: 'testing again'
</pre>

Alternatively, using `vars` instead of `args` is supported as well and is interchangeable. As-is, the new argument parsing code is seeing `mysql_user` (which is a valid module name) and believes you're specifying multiple actions in one task, thus the error.

I'll hold this open for now, to debate whether we should allow this syntax during the transition to 2.0. If we do, it would certainly be marked as a deprecated syntax, so I would recommend updating your playbooks to use the format above.

**Comment by jimi-c** [comment] 2015-12-07 16:33
So after a quick internal discussion, we've decided we're not going to add support for this format. @bcoca provided a perfect example as to why:

<pre>
- include: fool.yml
  vasr: 
     varwontappear: true
</pre>

^ In this example, in 1.9.x and prior, this would be accepted but is obviously incorrect, and would be a pain to debug. As we have never documented the bare param syntax as far as we can tell, users should move their syntax to the officially supported syntax.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-12-07 16:33 UTC
Labels: bug

**Comment by hloeffler** [comment] 2015-12-08 06:23
thanks,

```
- include: test.yml
  args:
    test: 'test'
    test2: 'test2'
    mysql_user: 'test'
```

could be written as:

```
- include: test.yml
  args: { test: 'test', test2: 'test2', mysql_user: 'test' }
```

?

**Comment by hloeffler** [comment] 2015-12-08 06:42
@jimi-c 
**args** not working in v1.9.4 - so better use **vars**?

**Comment by jimi-c** [comment] 2015-12-08 14:09
@hloeffler yes that's the old syntax, in 2.0 the syntax for regular tasks (args) and includes (vars) is interchangeable.

**Comment by hloeffler** [comment] 2015-12-08 14:39
@jimi-c thanks

add this to the docs:
http://docs.ansible.com/ansible/playbooks_roles.html

```
For instance, if deploying multiple wordpress instances, I could contain all of my wordpress tasks in a single wordpress.yml file, and use it like so:

tasks:
  - include: wordpress.yml wp_user=timmy
  - include: wordpress.yml wp_user=alice
  - include: wordpress.yml wp_user=bob
```

was the start of this error

**Comment by jimi-c** [comment] 2015-12-08 17:23
@hloeffler that syntax still works, as the key=value params are split up and assigned to the include as expected, which is the consistent with how all other tasks work. Likewise, if you do this:

<pre>
tasks:
- foo:
  param1: bar
</pre>

it would fail, and you need to use args/vars in the same way (depending on whether you're specifying params to the module, or just setting variables for the task to use):

<pre>
tasks:
- foo:
  args:
    param1: bar
</pre>

**Comment by msieurtoph** [comment] 2017-09-12 13:30
I am kind of lost ...

using ansible 2.2.1.0, I noticed this works : 

```
- include: "xxxx.yml"
  vars: 
    foo: "bar"
```
but not that : 
```
- include: "xxxx.yml"
  args: 
    foo: "bar"
```

I thought it was supposed to be the opposite : args should work with include, and vars should not.
It is not either interchangeable ...

What is the good practice for v2 ?

**Comment by bcoca** [comment] 2017-09-12 13:53
@msieurtoph `args` are for task options, not for variables, sadly `include` conflates them
