### ISSUE TITLE
to_nice_json fails with whitespace

### ISSUE THREAD

**Issue by nickjbyrne** [ansible/ansible#11223] opened 2015-06-10 14:09 UTC
Content with whitespace fails to be rendered fully when being passed through the to_json or to_nice_json filters. 

Reproduce with

```

---
- hosts: all
  vars:
    one: 
      var1: 'abc 123 def 456'
    two: 
      var2: 'abc-123%def-456'

  tasks:
  - debug: var=one
  - debug: var=two

  - name: var one
    copy: dest=/tmp/one content="{{ one }}"
  - name: var one to_nice_json
    copy: dest=/tmp/one_json content="{{ one|to_nice_json }}"

  - name: var two
    copy: dest=/tmp/two content="{{ two }}"
  - name: var two to_nice_json
    copy: dest=/tmp/two_json content="{{ two|to_nice_json }}"
```

Output:

```
[admin@localhost ~]$ more /tmp/one
{'var1': 'abc 123 def 456'}
[admin@localhost ~]$ more /tmp/one_json
"{
"var1": "abc
[admin@localhost ~]$ more /tmp/two
{'var2': 'abc-123%def-456'}
[admin@localhost ~]$ more /tmp/two_json 
{
"var2": "abc-123%def-456"
}
```

Env:
- Fedora 22
- Python 2.7.9
- Ansible 1.9.1

**Comment by bcoca** [comment] 2015-06-10 15:16
copy does not deal well with multiline content, use template instead, copy's content option was never meant as a substitute.

**Comment by sivel** [comment] 2015-06-10 15:17
I think the problem is that the JSON is breaking out of the key=value pair, because JSON uses `"` as it's quoting character, and you are using `"` as the encapsulation character for the value.  This is a downside to the key=value syntax parsing, as opposed to YAML syntax.

Something like the following would probably be most appropriate:

```
  - name: var one to_nice_json
    copy:
        dest: /tmp/one_json
        content: "{{ one|to_nice_json }}"
```

**Comment by bcoca** [comment] 2015-06-10 17:44
with the following play I get the output you expect:

```
---
- hosts: all
  vars:
    one: 
      var1: 'abc 123 def 456'
    two: 
      var2: 'abc-123%def-456'

  tasks:
  - debug: var=one
  - debug: var=two

  - name: var one
    copy: dest=/tmp/one content="{{ one }}"
  - name: var one to_nice_json
    copy:
        dest: /tmp/one_json
        content: "{{ one|to_nice_json }}"

  - name: var two
    copy: dest=/tmp/two content="{{ two }}"

  - name: var two to_nice_json
    copy:
        dest: /tmp/two_json
        content: "{{ two|to_nice_json }}"
```

**Comment by bcoca** [comment] 2015-06-10 17:44
I'm going to close this as it is a quoting issue not an issue related to the json filters

**Closed as completed by bcoca** 2015-06-10 17:44 UTC
