### ISSUE TITLE
Apt module does not work well when specifying version along with with_items loop

### ISSUE THREAD

**Issue by luiseterc** [ansible/ansible#10471] opened 2015-03-16 12:10 UTC
When trying to install several packages with this task:

```
- name: Install deb packages
  apt: name={{ item }}=1.0*
       update_cache=yes
       state=present
       force=yes
  with_items:
    - package1
    - package2
```

Only package2 (last one in the loop) is forced to install with 1.0 version. Package1 is installed with the latest version found on the repository. Running the playbook with "-vvvv" I can se how the command is eventually executed:

REMOTE_MODULE apt name=package1,package2=1.0\* update_cache=yes state=present force=yes

I got it working by rewriting the task as following:

```
- name: Install deb packages
  apt: name={{ item }}
       update_cache=yes
       state=present
       force=yes
  with_items:
    - package1=1.0*
    - package2=1.0*
```

**Comment by bcoca** [comment] 2015-03-17 17:31
actually this is how it works due to an "optimization" that affects some modules (apt, yum, zypper, ...) so you can install multiple packages with 1 call. As such the whole list of items in a with_ get concatenated with a  , and passed into the name= field.

**Comment by bcoca** [comment] 2015-03-18 00:50
closing this as it is not really a bug but works as intended, that said, we are looking at ways to improve this as this is not the first time this 'feature' has led to confusion.

**Closed as completed by bcoca** 2015-03-18 00:50 UTC
Labels: bug, packaging
