### ISSUE TITLE
Update bundled distro to 1.7.0

### ISSUE THREAD

**Issue by mattclay** [ansible/ansible#77392] opened 2022-03-29 21:31 UTC
### Summary

Update the bundled package [distro](https://pypi.org/pypi/distro) from `1.6.0` to `1.7.0`.

### Issue Type

Bug Report

### Component Name

`lib/ansible/module_utils/distro/__init__.py`

### Ansible Version

2.14

### Configuration

N/A

### OS / Environment

N/A

### Steps to Reproduce

N/A

### Expected Results

N/A

### Actual Results

N/A

**Comment by sivel** [comment] 2022-03-29 21:35
Going to close this as a duplicate of https://github.com/ansible/ansible/issues/77027

I didn't work through this because 1.7 drops Python2.7 and Python3.5 support.

**Closed as completed by sivel** 2022-03-29 21:35 UTC
Labels: support:core, bug, affects_2.14
