### ISSUE TITLE
Playbooks are runned over other group of hosts than listed by list-hosts

### ISSUE THREAD

**Issue by jkramarz** [ansible/ansible#6314] opened 2014-03-06 15:15 UTC
##### Issue Type:

Bug report
##### Ansible Version:

starting from commit ae9843fccdac1bc5da95f2c9d274e927f4a43962
ansible 1.5 is affected
##### Environment:

at last Debian 6
##### Summary:

Please summarize your request in this space.  You will earn bonus points for being succinct, but please add enough detail so we can understand the request.
##### Steps To Reproduce:

run
1. ansible-playbook -C site.yml -i hosts --list-hosts
2. ansible-playbook -C site.yml -i hosts

using files

hosts:

```
[physical]
phost1

[phost1]
vm1.phost1
```

site.yml:

```

---
- hosts: physical
  tasks:
    - ping:
```
##### Expected Results:

Groups not declared as children of group 'physical' should not be involved.

```
playbook: site.yml

  play #1 (physical): host count=1
    phost1


PLAY [physical] *************************************************************** 

TASK: [ping ] ***************************************************************** 
ok: [phost1]

PLAY RECAP ******************************************************************** 
phost1                     : ok=1    changed=0    unreachable=0    failed=0   
```
##### Actual Results:

Hosts from groups named after hosts included in group 'physical' (not declared as group's children) are involved by play.

```
playbook: site.yml

  play #1 (physical): host count=1
    phost1


PLAY [physical] *************************************************************** 

TASK: [ping ] ***************************************************************** 
ok: [vm1.phost1]
ok: [phost1]

PLAY RECAP ******************************************************************** 
phost1                     : ok=1    changed=0    unreachable=0    failed=0   
vm1.phost1                 : ok=1    changed=0    unreachable=0    failed=0   
```

**Comment by mpdehaan** [comment] 2014-03-06 16:55
So reading into your above report:

```
Groups not declared as children of group 'physical' should not be involed.
```

What I see in your inventory file is not that you don't have any child groups of "physical", but you have two top level groups.

Can you confirm that is all of the inventory file?

Thanks!

**Comment by mpdehaan** [comment] 2014-03-06 16:58
I can't reproduce the above behavior using a simple inventory file with two groups and two hosts.

Both --list-hosts and a regular run is correctly only selecting one host.

**Comment by jkramarz** [comment] 2014-03-06 17:06
@mpdehaan, I believe that configuration included in issues is the most minimalist one required to reproduce the problem.

Yes, I don't have any child groups of "physical". It works well for "ansible", "ansible-playbook --list-hosts" but for "ansible-playbook" group phost1 (named after other host) behaves like child of "physical".

**Comment by mpdehaan** [comment] 2014-03-19 15:35
Given I can't reproduce this and if this were this horribly broken I would expect screaming and pitchforks, I am at a loss to see what the problem may be.  As a result, I'm closing this one.  If you can dig and find out what is going on that would be welcome, though I suspect this might be some confusion with some particular thing.

IRC might be a good place to ask questions.

**Closed as completed by mpdehaan** 2014-03-19 15:35 UTC
Labels: needs_info, bug
