### ISSUE TITLE
synchronize module : unsupported parameter ansible_ssh_user

### ISSUE THREAD

**Issue by davidfischer-ch** [ansible/ansible#6683] opened 2014-03-25 16:56 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6
##### Environment:

Ubuntu 13.10
##### Summary:

The module does not handle hosts file like this:

```
10.0.3.204 ansible_ssh_user=ubuntu
```
##### Steps To Reproduce:
- Install Ansible from the devel branch of the repository.
- Update hosts file with content in summary.
- Create a playbook using the synchronize module.
- Run it.
##### Expected Results:

It does synchronize files.
##### Actual Results:

It does fail with the following message:

```
failed: [10.0.3.204 ansible_ssh_user=ubuntu] => {"failed": true}
msg: unsupported parameter for module: ansible_ssh_user
FATAL: all hosts have already failed -- aborting
```

**Comment by mpdehaan** [comment] 2014-03-25 17:37
So this sounds like your host file is being parsed strangely.

As I believe I commented previously, can you please paste your complete host file?   It should be possible to declare variables in it, so I'm curious what is happening here.

(This also sounds like another ticket you had opened about hostnames containing a hyphen, but I can't seem to find that one right now)

Thanks!

**Comment by mpdehaan** [comment] 2014-03-25 17:39
Duplicate of #6684 from what is showing in the "failed" line this is getting read as a hostname.  Investigating.

**Closed as completed by mpdehaan** 2014-03-25 17:39 UTC
Labels: bug

**Comment by davidfischer-ch** [comment] 2014-03-25 17:41
Thanks you really much Michael !

**Comment by targetoyes** [comment] 2015-08-18 09:27
ansible_ssh_port not work in module synchronize：
return
{
    "failed": true,
    "msg": "unsupported parameter for module: dest_port"
}
