### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by TuringZhu** [ansible/ansible#15748] opened 2016-05-06 05:57 UTC
##### ISSUE TYPE

Bug Report
##### COMPONENT NAME

action plugin
##### ANSIBLE VERSION

N/A
##### SUMMARY

---

I find that when stdout contains chinese, it throw  UnicodeDecodeError Error.
If I comments this line, it is OK.

```
 vim /root/ansible/lib/ansible/plugins/action/__init__.py +700
display.debug("_low_level_execute_command() done: rc=%d, stdout=%s, stderr=%s" % (rc, stdout, stderr))
```

---

the command line out put:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/root/ansible/lib/ansible/executor/task_executor.py", line 124, in run
    res = self._execute()
  File "/root/ansible/lib/ansible/executor/task_executor.py", line 437, in _execute
    result = self._handler.run(task_vars=variables)
  File "/root/ansible/lib/ansible/plugins/action/normal.py", line 33, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars))
  File "/root/ansible/lib/ansible/plugins/action/__init__.py", line 605, in _execute_module
    res = self._low_level_execute_command(cmd, sudoable=sudoable, in_data=in_data)
  File "/root/ansible/lib/ansible/plugins/action/__init__.py", line 700, in _low_level_execute_command
    display.debug("_low_level_execute_command() done: rc=%d, stdout=%s, stderr=%s" % (rc, stdout, stderr))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 435: ordinal not in range(128)

fatal: [192.168.100.7]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
```

**Comment by jctanner** [comment] 2016-09-16 22:13
@Turing-Chu I'm not able to reproduce this in any version of ansible with the following task ...

```
- shell: echo -e "\xe6"
```

Can you please indicatethe version of ansible you were using when this error occured and any other detail you think might be useful for tracking down the problem? It would also be helpful to know if the error still occurs in the latest devel (2.2).

needs_info

**Comment by abadger** [comment] 2016-09-16 23:28
We weren't able to reproduce this with python2.  Fixing UnicodeErrors is something that's ongoing and fairly active so if we don't know the precise version it's entirely possible that we fixed this bug but don't know about it.  I did find that this bug could resurface with the current code if python3 is used so I went ahead and applied https://github.com/ansible/ansible/commit/ce4c0fd644dab88c412dabee7a9dd5e4d539f2b3 which should work on python3 and make the code more robust besides.  Hopefully even if you were getting the issue in relatively current code, that commit will fix it for you.

**Comment by jctanner** [comment] 2016-09-18 19:13
@Turing-Chu We still need to know what version of ansible you were using to produce this error and if the latest devel code helps at all.

needs_info

**Comment by jimi-c** [comment] 2016-09-24 20:34
# Closing This Ticket

Hi!

As there has been no follow-up and we were unable to reproduce this, we're going to go ahead and close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2016-09-24 20:34 UTC
Labels: P2, affects_2.2, bug
