### ISSUE TITLE
hostvars not collected when using  inventory "script plugin"

### ISSUE THREAD

**Issue by jladdjr** [ansible/ansible#25371] opened 2017-06-05 21:22 UTC
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
New inventory plugin system (https://github.com/ansible/ansible/pull/23001)

##### ANSIBLE VERSION
```
ansible 2.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Since [inventory plugins](https://github.com/ansible/ansible/pull/23001) landed, when Tower runs against ansible `devel` seems like extravars are not being picked up. Even with [recent fix](https://github.com/ansible/ansible/commit/5d572055b3b4bc6eda783279adaa063057448265), still looks like extravars are not being collected.

Tower uses [`awxrest.py`](https://github.com/ansible/ansible-tower/blob/devel/awx/plugins/inventory/awxrest.py) for the inv. script. That generates an inventory based on a Tower inventory. When I run the script against a Tower inventory with localhost, I get:
```
{"all": {"hosts": ["localhost"]}, "_meta": {"hostvars": {"localhost": {"ansible_connection": "local"}}}}
```

Running ansible w/ that script results in `Unreachable.. Failed to connect to the host via ssh.. Permission denied (publickey,gssapi-keyex,gssapi-with-mic` which suggests that local connection is not being used.

##### STEPS TO REPRODUCE

1. Provision an instance of Tower. Instance should be running latest build of ansible `devel`.
1. In Tower, create an inventory with a single host called `localhost`. Add `ansible_connection: local` to the VARIABLES section. Get id of inventory. Can get this from URL. (Alternatively, you can just use the Demo Inventory. ID is 1.)
1. Log into tower instance and run:
```
export REST_API_URL=https://admin:PASSWORD@TOWER_FQDN
export INVENTORY_ID=INVENTORY_ID
export INVENTORY_HOSTVARS=True
cd /var/lib/awx/venv/tower/lib/python2.7/site-packages/awx/plugins/inventory
python awxrest.py --list
```

Now run: `ansible localhost -i awxrest.py -m ping`

##### EXPECTED RESULTS

Running `python awxrest.py --list` should give the json for a single host, `localhost` with `ansible_connection: local`.
```
{"all": {"hosts": ["localhost"]}, "_meta": {"hostvars": {"localhost": {"ansible_connection": "local"}}}}
```

Running `ansible localhost -i awxrest.py -m ping` should return:
```
localhost | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
```

##### ACTUAL RESULTS
Receive the expected json, but running ansible command returns:

```
localhost | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.\r\nPermission denied (publickey,gssapi-keyex,gssapi-with-mic).\r\n",
    "unreachable": true
}
```

**Comment by bcoca** [comment] 2017-06-05 21:27
@jladdjr for reproducers a simple setup w/o Tower is what we require, to show it is an Ansible and not a Tower issue, which has different support.

**Comment by jladdjr** [comment] 2017-06-05 21:51
@bcoca:

```
cat << EOF > fake_inv_script.py
#!/bin/env python

print("""{"all": {"hosts": ["localhost"]}, "_meta": {"hostvars": {"localhost": {"ansible_connection": "local"}}}}""")
EOF

ansible localhost -i fake_inv_script.py -m ping
```

*devel*:
https://gist.github.com/jladdjr/a8cd06f285f0885cd4cfa8e44737b61d

*stable-2.3*:
https://gist.github.com/jladdjr/0bd9fcfb89dc77ec43bd2633272dba09

**Comment by sivel** [comment] 2017-06-05 22:09
This change begins to fix it, but things go further awry from here:

```diff
diff --git a/lib/ansible/plugins/inventory/script.py b/lib/ansible/plugins/inventory/script.py
index b60fb29..53fbd2e 100644
--- a/lib/ansible/plugins/inventory/script.py
+++ b/lib/ansible/plugins/inventory/script.py
@@ -122,8 +122,8 @@ class InventoryModule(BaseInventoryPlugin):
             data_from_meta = None
             for (group, gdata) in processed.items():
                 if group == '_meta':
-                    if 'hostvars' in processed:
-                        data_from_meta = processed['hostvars']
+                    if 'hostvars' in gdata:
+                        data_from_meta = gdata['hostvars']
                 else:
                     self._parse_group(group, gdata)
 ```

With just that change, we seem to end up with weird parsing later.

In the above test inventory we get:

```
 [WARNING]:  * Failed to parse /Users/matt/projects/ansibledev/playbooks/fake_inv_script.py2 with script inventory plugin: Could not find group _meta in inventory

 [WARNING]:  * Failed to parse /Users/matt/projects/ansibledev/playbooks/fake_inv_script.py2 with ini inventory plugin: host range must be begin:end or begin:end:step

 [WARNING]: Unable to parse /Users/matt/projects/ansibledev/playbooks/fake_inv_script.py2 as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available
```

With a test `localhost.py` that I have, we end up with hosts called: `1`, `2`, `7`, `0`, `.` and `127.0.0.1`

Looking later in the code I see `self.populate_host_vars(host, got, group)`, but the variable `group` is "out of scope" here, as it's just the last group from looping over `processed.items()`.

Looks like this needs a larger logic cleanup.

**Comment by bcoca** [comment] 2017-06-05 22:24
@sivel, i'm already a couple of steps ahead, mismtach on 'meta' vs '_meta' .. got it working now .. just got more hosts than defined (once that is solved it should be good)

**Comment by sivel** [comment] 2017-06-05 22:24
Looks like `populate_host_vars` is also expecting to get a list of hosts.  So when we call `populate_host_vars` from `script.py` with a single host, we are iterating the characters of the hostname.

**Closed as completed** 2017-06-05 22:32 UTC
Labels: c:module_utils/facts, affects_2.4, bug

**Comment by jladdjr** [comment] 2017-06-06 15:57
@bcoca - This morning's tests confirm the fix is working - will get in touch if we see any other issues with inventories / extravars. Appreciate the help, thanks!
