### ISSUE TITLE
ansible-vault encrypt is not idempotent

### ISSUE THREAD

**Issue by ktdreyer** [ansible/ansible#10595] opened 2015-04-01 20:05 UTC
Encrypting and re-encrypting a file changes the contents of the file. 

Steps to reproduce:
-  Create a simple text file:

```
$ echo hello > hello.txt
```
- Encrypt it:

```
  $ ansible-vault encrypt hello.txt
    Vault password: hello
    Confirm Vault password: hello 
    Encryption successful
```
- Save the encrypted version:

```
   $ cp hello.txt hello.txt.firstcrypt
```
- Decrypt and Re-encrypt a second time:

```
   $ ansible-vault decrypt hello.txt
   $ ansible-vault encrypt hello.txt
```
- Compare the two versions:

```
   $ diff -u hello.txt.firstcrypt hello.txt
```

Actual results: The two files are different.

Expected results: The two encrypted files should be the same.

I'm using git's filters to encrypt my ansible-vault'd files on the fly. This issue causes Git to think that the contents of the encrypted file are changing, when my data is not actually changing.

**Comment by dipankar** [comment] 2015-04-09 09:09
Hey, its not possible for for the encrypted files to be the same using AES256 in the current scheme. The random salt changes each time you encrypt making sure the final encrypted outputs are not the same for the same content. Hope that helps!

**Comment by bcoca** [comment] 2015-04-09 13:13
keeping ticket open to see if we can try to detect changes to the file and avoid re-encrypting

**Comment by dwt** [comment] 2015-06-15 08:59
I would really like that too, as it would be much easier that way to decrypt all vault files to allow easy working with lots of vault files (finding where a specific password has been set and determining if settings are irrelevant or need moving to a vault). This is much discouraged if that always generates version management changes.

**Comment by dmick** [comment] 2015-06-26 22:56
"random salt"...that's why you save the salt value with the crypted text, right?....

**Comment by abadger** [comment] 2015-08-25 19:10
I think you might be able to leverage ansible-vault edit in some way to do this (with the version in devel.  before that, we were re-saving the file even if no changes were made).  Making this work with separate  ansible-vault decrypt and ansible-vault encrypt steps  doesn't seem very feasible.  The decrypted file should be the input file so it wouldn't contain the random salt value. So we wouldn't have any way to go from decrypted file back to the same encrypted file.

With recent changes in how ansible-vault edit is implemented ( https://github.com/ansible/ansible/blob/devel/lib/ansible/parsing/vault/__init__.py#L242 ) you might be able to work something out there (maybe setting $EDITOR to a custom script?).  This is possible as ansible-vault edit can hold onto the original information since it's running as a single process, not two separate invocations of the program.

**Comment by abadger** [comment] 2015-08-25 21:47
Using ansible-vault edit in devel:

```
$ ansible-vault encrypt testing
Vault password: 
Encryption successful
$ cp testing testing.encrypted
$ ls -al testing*
-rw-rw-r--. 1 badger badger 355 Aug 25 14:39 testing
-rw-rw-r--. 1 badger badger 355 Aug 25 14:40 testing.encrypted
$ ansible-vault edit testing
Vault password: 
$ cmp testing testing.encrypted
$
```

As explained above, there's no way for ansible-vault to have enough information to do this with separate encrypt and decrypt runs.  So closing this ticket.  Hopefully ansible-vault edit gives you the building block to make what you want possible.

**Closed as completed by abadger** 2015-08-25 21:47 UTC
Labels: bug

**Comment by glatapoui** [comment] 2017-05-26 20:34
I don't understand why this bug was closed. 
The issue is still present, and the fact that the current scheme does not allow a simple resolution only makes this bug harder to fix, but not impossible.

Can we not think of a way to adapt the current scheme in order to fix this issue ?
- use the MD5 of `ansible.cfg` as the salt ?
- keep the encrypted version as a backup when we decrypt, and use that backup when we encrypt if the content stays the same ?
- something more creative ?

**Comment by nelsg** [comment] 2018-10-22 13:06
For me this is a normal behaviour : `ansible-vault` use a salt. Use `ansible-vault view` to display file content.
From wikipedia :
`A salt is random data that is used as an additional input to a one-way function that "hashes" data, passwords, ...
Salts are used to safeguard passwords in storage.
Salts defend against dictionary attacks or against their hashed equivalent, a pre-computed rainbow table attack.
Since salts are different in each case, they also protect commonly used passwords, or those users who use the same password on several sites, by making all salted hash instances for the same password different from each other.`

**Comment by jamesdh** [comment] 2019-03-20 14:36
> Making this work with separate ansible-vault decrypt and ansible-vault encrypt steps doesn't seem very feasible. 

Agreed completely. As vault currently stands, it's not feasible. But I think there are definitely ways to make it feasible. 

@glatapoui I opened a new issue (#54112) with a suggested solution that I now see matches one of your own. Would love your input there if still interested!
