### ISSUE TITLE
Groups undefined for all templates.

### ISSUE THREAD

**Issue by Jacob-SAE** [ansible/ansible#16303] opened 2016-06-15 15:20 UTC
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

I'm unable to access the 'groups' builtin from my templates.
##### STEPS TO REPRODUCE

```
site.yml

---
- name: This role is used to place common installation files on all servers.
  hosts: all
  remote_user: root
  gather_facts: no

  roles:
    - release0

- name: This role is used to place nginx installation files on all nginx servers.
  hosts: nginx
  remote_user: root
  gather_facts: no

  roles:
    - nginx

----------------
inventory.txt
----------------
[nginx]
X.X.X.X
[php]
X.X.X.X
[mysql]
X.X.X.X

-------------------------
roles/nginx/tasks/main.yml
-------------------------

---
- name: Gather Facts
  setup:
  always_run: yes

- name: Wait | Wait for server to be accessible
  wait_for: port=22 delay=10 connect_timeout=30
  always_run: yes

- name: MKDIR | Create directory for NGINX SSL
  file: path=/etc/nginx/ssl state=directory mode=0755
  always_run: yes

- name: TEMPLATE | Use template for NGINX site conf
  template: src=roles/nginx/templates/client_url.j2 dest=/etc/nginx/sites-available/{{client_url}}


---------------
client_url.j2
---------------
{% for host in groups['php'] %}
  server {{ hostvars[host]['ansible_eth0']['ipv4']['address'] }}:9000;
{% endfor %}

####General nginx client config ####

```

##### EXPECTED RESULTS

TASK [nginx : TEMPLATE | Use template for NGINX site conf] *********************
ok: [X.X.X.X]
##### ACTUAL RESULTS

fatal: [X.X.X.X]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'groups' is undefined"}

```

```

**Comment by nitzmahone** [comment] 2016-06-16 18:22
I'm unable to reproduce this on Ansible 2.1.0.0 - you didn't specify how Ansible got installed, but perhaps you've got a mixed-version installation or cruft left over between an OS package-managed version and a pip version?

**Comment by Jacob-SAE** [comment] 2016-06-16 18:33
I installed ansible through pip. I did an pip install ansible --upgrade , would this cause a problem?

I'll attempt to uninstall and reinstall through pip to see if that helps. I will inform you here afterwards if it persists.

Thank you @nitzmahone

**Comment by nitzmahone** [comment] 2016-06-16 18:43
Yeah, that should work fine, but we've seen weird issues when people have installed via OS package manager then pip over the top. If you've got a clean VM to try the install in, might be a good thing too, because the test case works fine for me!

**Comment by Jacob-SAE** [comment] 2016-06-16 18:46
Its still happening on a newly created KVM.

Could it be that I'm misusing the CLI? I'll include the code I call playbooks with below.

```
class Scheme(object):
    """
    Interface used to run Ansible playbooks based on playbook name.
    """
    def __init__(self, role_base='/srv/auction-balancer/Auction-Balancer/sae/prov/playbooks/', timeout=90, private_key='/srv/auction-balancer/.ssh/newserveraccess', extra_vars={}):
        self.role_base = role_base
        self.timeout = timeout
        self.private_key = private_key
        self.extra_vars = extra_vars

    def configure(self, role, host_list):
        self.variable_manager = VariableManager()
        self.loader = DataLoader()

        self.inventory = Inventory(loader=self.loader, variable_manager=self.variable_manager, host_list=host_list)
        self.playbook_path = self.role_base + role

        if not os.path.exists(self.playbook_path):
            print '[INFO] The playbook does not exist'
            sys.exit()

        Options = namedtuple('Options', ['listtags', 'listtasks', 'listhosts', 'syntax', 'connection', \
                                         'module_path', 'forks', 'private_key_file', 'ssh_common_args', \
                                         'ssh_extra_args', 'sftp_extra_args', 'scp_extra_args', 'become', 'become_method', \
                                         'become_user', 'verbosity', 'check'])

        self.options = Options(listtags=False, listtasks=False, listhosts=False, syntax=False, connection='ssh', \
                          module_path=None, forks=100, private_key_file=self.private_key, ssh_common_args=None, \
                          ssh_extra_args=None, sftp_extra_args=None, scp_extra_args=None, become=False, become_method=None, \
                          become_user=None, verbosity=None, check=False)

        self.variable_manager.extra_vars = self.extra_vars
        self.passwords = {}

        self.pbex = PlaybookExecutor(playbooks=[self.playbook_path], inventory=self.inventory, variable_manager=self.variable_manager, \
                                     loader=self.loader, options=self.options, passwords=self.passwords)


    def run_pb(self):
        return self.pbex.run()
```

The inventory seems to persist for the first role and then vanish on the next one.

I realize this may not be the place for this; however, I appreciate suggestions on what I could try.

**Comment by nitzmahone** [comment] 2016-06-16 19:10
Sorry, the simple blanket answer for this one: we don't support calling the Python API externally. You are, of course, welcome to do so, but you may run into any number of issues that we're unable to directly help with. Our CLI tools (the only use case we test the Python API against) live long enough to do a single run, and we're not particularly careful about preserving state beyond that.

Others who try to do this kind of thing occasionally hang out on the ansible-project mailing list and/or #ansible IRC- if you figure out the issue and need code changes merged to make it work, we might accept them as long as they don't have detrimental effects to our supported use cases...

**Closed as completed by nitzmahone** 2016-06-16 19:10 UTC
Labels: bug

**Comment by Jacob-SAE** [comment] 2016-06-27 16:32
My namedtuple used for PlaybookExecutor(options=self.options) did not keep persistent inventory.

I resolved it with:

```
self.variable_manager.set_inventory(self.inventory)
```

Is it intended for inventory within the namedtuple to not stay persistent for all roles in a playbook?
