### ISSUE TITLE
`run_once` for single task also affect the tasks after it

### ISSUE THREAD

**Issue by ralavay** [ansible/ansible#16050] opened 2016-05-30 11:06 UTC
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Nothing special

```
[defaults]
remote_user = ubuntu
force_color = 1
forks= 10
gathering = smart
log_path = /var/log/ansible/ansible.log
nocows = 0
host_key_checking = False
retry_files_save_path = /tmp/

[ssh_connection]
pipelining = True
ssh_args = -o ControlMaster=auto -o ControlPersist=60s -o ForwardAgent=yes
control_path = /tmp/ansible/ansible-ssh-%%h-%%p-%%r
```
##### OS / ENVIRONMENT

Ubuntu 14.04
##### SUMMARY

Deploying to autoscale group by using tag Name. When I set a custom variable and use `run_once` then the block contains `register` after that will be affect too.
##### STEPS TO REPRODUCE

I have a very simple playbook to print out the location of a symlink folder in servers. Each server will have a different source of symlink based on the time the folder was created. If I don't use `run_once` then the block after that will return the correct values but on the next `register` block it only takes the value from the first server. 

```
- hosts: tag_Name_test_auto_scale
  tasks:

    - block:

      - set_fact: asg_timestamp="{{ ansible_date_time['date'] }}-{{ ansible_date_time['hour'] }}-{{ ansible_date_time['minute'] }}"
        run_once: yes

      - name: Check if it is not the first deployment | do not put the '/' at the end of current/
        stat: path=/data/code/current
        register: stat_current
        ignore_errors: yes

      - debug: msg="{{ stat_current.stat.lnk_source }}"

      become: yes
      become_user: deploy
```
##### EXPECTED RESULTS

```
TASK [debug] *******************************************************************
ok: [10.0.6.165] => {
    "msg": "/data/code/releases/2016-05-30-07-01"
}
ok: [10.0.10.4] => {
    "msg": "/data/code/releases/2016-05-30-07-03"
}
ok: [10.0.9.182] => {
    "msg": "/data/code/releases/2016-05-30-07-05"
}
ok: [10.0.8.96] => {
    "msg": "/data/code/releases/2016-05-30-07-02"
}
```
##### ACTUAL RESULTS

```
TASK [debug] *******************************************************************
ok: [10.0.6.165] => {
    "msg": "/data/code/releases/2016-05-30-07-02"
}
ok: [10.0.10.4] => {
    "msg": "/data/code/releases/2016-05-30-07-02"
}
ok: [10.0.9.182] => {
    "msg": "/data/code/releases/2016-05-30-07-02"
}
ok: [10.0.8.96] => {
    "msg": "/data/code/releases/2016-05-30-07-02"
}
```

**Comment by jimi-c** [comment] 2016-09-26 16:48
Hi @ralavay, I am unable to reproduce this, even on 2.0.1 as reported. That version's output is shown here:

<pre>
[jamesc@jimi 16050]$ ansible-playbook -vv -i inv test.yml 
Using /etc/ansible/ansible.cfg as config file
1 plays in test.yml
PLAY ***************************************************************************
TASK [setup] *******************************************************************
ok: [host2]
ok: [host1]
ok: [host3]
TASK [set_fact] ****************************************************************
task path: /home/jamesc/testing/16050/test.yml:7
ok: [host1] => {"ansible_facts": {"asg_timestamp": "2016-09-26-12-43"}, "changed": false}
TASK [Check if it is not the first deployment | do not put the '/' at the end of current/] ***
task path: /home/jamesc/testing/16050/test.yml:10
ok: [host2] => {"changed": false, "stat": {"atime": 1474005639.897703, "ctime": 1474908219.850375, "dev": 64512, "exists": true, "gid": 0, "gr_name": "root", "inode": 8205, "isblk": false, "ischr": false, "isdir": true, "isfifo": false, "isgid": false, "islnk": false, "isreg": false, "issock": false, "isuid": false, "mode": "1777", "mtime": 1474908219.850375, "nlink": 2, "path": "/tmp", "pw_name": "root", "rgrp": true, "roth": true, "rusr": true, "size": 4096, "uid": 0, "wgrp": true, "woth": true, "wusr": true, "xgrp": true, "xoth": true, "xusr": true}}
ok: [host1] => {"changed": false, "stat": {"atime": 1474005617.203987, "ctime": 1474908219.8601224, "dev": 64512, "exists": true, "gid": 0, "gr_name": "root", "inode": 131229, "isblk": false, "ischr": false, "isdir": true, "isfifo": false, "isgid": false, "islnk": false, "isreg": false, "issock": false, "isuid": false, "mode": "1777", "mtime": 1474908219.8601224, "nlink": 6, "path": "/tmp", "pw_name": "root", "rgrp": true, "roth": true, "rusr": true, "size": 4096, "uid": 0, "wgrp": true, "woth": true, "wusr": true, "xgrp": true, "xoth": true, "xusr": true}}
ok: [host3] => {"changed": false, "stat": {"atime": 1474005614.473682, "ctime": 1474908219.8534534, "dev": 64512, "exists": true, "gid": 0, "gr_name": "root", "inode": 613, "isblk": false, "ischr": false, "isdir": true, "isfifo": false, "isgid": false, "islnk": false, "isreg": false, "issock": false, "isuid": false, "mode": "1777", "mtime": 1474908219.8534534, "nlink": 4, "path": "/tmp", "pw_name": "root", "rgrp": true, "roth": true, "rusr": true, "size": 4096, "uid": 0, "wgrp": true, "woth": true, "wusr": true, "xgrp": true, "xoth": true, "xusr": true}}
TASK [debug] *******************************************************************
task path: /home/jamesc/testing/16050/test.yml:15
fatal: [host1]: FAILED! => {"failed": true, "msg": "'dict object' has no attribute 'lnk_source'"}
fatal: [host2]: FAILED! => {"failed": true, "msg": "'dict object' has no attribute 'lnk_source'"}
fatal: [host3]: FAILED! => {"failed": true, "msg": "'dict object' has no attribute 'lnk_source'"}
NO MORE HOSTS LEFT *************************************************************
PLAY RECAP *********************************************************************
host1                      : ok=3    changed=0    unreachable=0    failed=1   
host2                      : ok=2    changed=0    unreachable=0    failed=1   
host3                      : ok=2    changed=0    unreachable=0    failed=1   
</pre>

In your case you may be seeing this because of the fact that set_fact + run_once means the same fact is set for all hosts based on the result from one host. Based on this and the above, I'm going to go ahead and close this now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2016-09-26 16:48 UTC
Labels: P2, affects_2.0, bug
