### ISSUE TITLE
Lookup Passwords in Loops Should Not Generate Same Password

### ISSUE THREAD

**Issue by timfaraci** [ansible/ansible#10844] opened 2015-04-27 16:07 UTC
I believe when generating passwords they should be unique. When generating multiple passwords through a loop it results in the same password. Use cases where you want the same password across multiple entries should be toggled with a flag. 

Example:
- name: Create directories with password in the name (This is used for Crush FTP Magic Directory).
   file: path=/home/{{ item.key }}__{{ lookup('password', 'chars=digits') }} mode=0755 state=directory
   with_dict: dict

Output of Directories Created:

Dir1__qApDPxfONGEdHQ_F37UX
Dir2__qApDPxfONGEdHQ_F37UX
Dir3__qApDPxfONGEdHQ_F37UX
Dir4__qApDPxfONGEdHQ_F37UX

**Comment by bcoca** [comment] 2015-04-27 17:32
dupe of #10843

**Closed as completed by bcoca** 2015-04-27 17:32 UTC
