### ISSUE TITLE
| combine() broken in 2.5.1

### ISSUE THREAD

**Issue by dvvolodin** [ansible/ansible#39336] opened 2018-04-25 21:28 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

combine() filter

##### ANSIBLE VERSION

```
ansible 2.5.1
  config file = /home/dvvolodin/d2d/ansible/ansible.cfg
  configured module search path = [u'/home/dvvolodin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

##### CONFIGURATION

DEFAULT_ROLES_PATH(/home/dvvolodin/d2d/ansible/ansible.cfg) = [u'/home/dvvolodin/d2d/ansible/roles/internal', u'/home/dvvolodin/d2d/ansible/roles/external']
DEFAULT_TIMEOUT(/home/dvvolodin/d2d/ansible/ansible.cfg) = 60
DEFAULT_VAULT_PASSWORD_FILE(/home/dvvolodin/d2d/ansible/ansible.cfg) = /home/dvvolodin/d2d/ansible/vault_pass.txt
HOST_KEY_CHECKING(/home/dvvolodin/d2d/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 7.5 (Maipo)
x86_64

##### SUMMARY

combine() seems to reset the dictionary's contents before adding new elements.

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  gather_facts: no

  tasks:
    - set_fact:
        d: "{{ d | default({}) | combine( {('key_' + item) : 'value_' + item} ) }}"
      with_items:
        - a
        - b
        - c

    - debug: var=d

```

##### EXPECTED RESULTS

TASK [debug] *******************************************************************************************************
ok: [localhost] => {
    "d": {
        "key_a": "value_a",
        "key_b": "value_b",
        "key_c": "value_c"
    }
}

##### ACTUAL RESULTS

```
ansible-playbook 2.5.1
  config file = /home/dvvolodin/d2d/ansible/ansible.cfg
  configured module search path = [u'/home/dvvolodin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
Using /home/dvvolodin/d2d/ansible/ansible.cfg as config file
setting up inventory plugins
 [WARNING]: Unable to parse /etc/ansible/hosts as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not
match 'all'

Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: bug.yml **************************************************************************************************
1 plays in bug.yml

PLAY [localhost] ***************************************************************************************************
META: ran handlers
Trying secret FileVaultSecret(filename='/home/dvvolodin/d2d/ansible/vault_pass.txt') for vault_id=default
Trying secret FileVaultSecret(filename='/home/dvvolodin/d2d/ansible/vault_pass.txt') for vault_id=default
Trying secret FileVaultSecret(filename='/home/dvvolodin/d2d/ansible/vault_pass.txt') for vault_id=default

TASK [set_fact] ****************************************************************************************************
task path: /home/dvvolodin/d2d/ansible/bug.yml:6
ok: [localhost] => (item=a) => {
    "ansible_facts": {
        "d": {
            "key_a": "value_a"
        }
    },
    "changed": false,
    "item": "a"
}
ok: [localhost] => (item=b) => {
    "ansible_facts": {
        "d": {
            "key_b": "value_b"
        }
    },
    "changed": false,
    "item": "b"
}
ok: [localhost] => (item=c) => {
    "ansible_facts": {
        "d": {
            "key_c": "value_c"
        }
    },
    "changed": false,
    "item": "c"
}

TASK [debug] *******************************************************************************************************
task path: /home/dvvolodin/d2d/ansible/bug.yml:13
ok: [localhost] => {
    "d": {
        "key_c": "value_c"
    }
}
META: ran handlers
META: ran handlers

PLAY RECAP *********************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0

```

**Comment by bcoca** [comment] 2018-04-25 21:37
closing as dupe of  #38271, fixed in #38302

**Closed as completed by bcoca** 2018-04-25 21:37 UTC
