### ISSUE TITLE
KeyError: 'include' in v2

### ISSUE THREAD

**Issue by hryamzik** [ansible/ansible#10552] opened 2015-03-26 22:46 UTC
Ansible task fail on the `include` modules.

```
TASK [nginx : include] **********************************************************
fatal: [nginx]: FAILED! => {"msg": "ERROR! error while evaluating conditional: ansible_os_family  == \"RedHat\" ({% if ansible_os_family  == \"RedHat\" %} True {% else %} False {% endif %})", "failed": true}
Traceback (most recent call last):
  File "/mypathtotest/ansible/ansible-git/v2/bin/ansible-playbook", line 136, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/mypathtotest/ansible/ansible-git/v2/bin/ansible-playbook", line 129, in main
    return pbex.run()
  File "/mypathtotest/ansible/ansible-git/v2/ansible/executor/playbook_executor.py", line 80, in run
    result = self._tqm.run(play=play)
  File "/mypathtotest/ansible/ansible-git/v2/ansible/executor/task_queue_manager.py", line 157, in run
    return strategy.run(iterator, connection_info)
  File "/mypathtotest/ansible/ansible-git/v2/ansible/plugins/strategies/linear.py", line 239, in run
    include_file = self._loader.path_dwim_relative(original_task._role._role_path, 'tasks', include_result['include'])
KeyError: 'include'
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by jimi-c** [comment] 2015-04-20 16:46
This should be resolved now, unless you can provide a reproducer that shows it is still broken, so we will close this for now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-04-20 16:46 UTC
Labels: bug
