### ISSUE TITLE
Ansible looses role variable when include_roles nested 4 levels

### ISSUE THREAD

**Issue by jpsmeets-work** [ansible/ansible#70371] opened 2020-06-29 19:51 UTC
##### SUMMARY
Ansible looses default role variable when include_roles nested 4 levels deep.
We have a a role with a default variable. This is the role_l1.
role_l1 includes role_l2, role_l2 includes roles_l3, role_l3 include role l4
In role_l4 the variable from role_l1 becomes undefined.

In the actual production code the variable in role_l1 becomes undefined even when the lower roles role_l2 .. role_l4 are not using this variable.
so th etop level role role_l1 gets damaged by included lower level roles.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
include_role

##### ANSIBLE VERSION
ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/my_modules', '/opt/asml/ZXPFST/ansible/modules', '/opt/asml/ZXPFST/lib/python']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Dec  5 2019, 15:45:45) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

##### CONFIGURATION
DEFAULT_JINJA2_EXTENSIONS(/etc/ansible/ansible.cfg) = jinja2.ext.do,jinja2.ext.i18n,jinja2.ext.loopcontrols
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_MANAGED_STR(/etc/ansible/ansible.cfg) = This file is managed by Ansible, all changes will be lost.
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = ['/usr/share/my_modules', '/opt/asml/ZXPFST/ansible/modules', '/opt/asml/ZXPFST/lib/python']
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = ['/opt/asml/LXCF/ansible/roles', '/opt/asml/ZXPFCF/ansible/roles', '/opt/asml/ZXPFNW/ansible/>
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
RETRY_FILES_SAVE_PATH(/etc/ansible/ansible.cfg) = /tmp/.ansible-retry

##### OS / ENVIRONMENT
Redhat 8.2

##### STEPS TO REPRODUCE
[test1.zip](https://github.com/ansible/ansible/files/4847674/test1.zip)
ziparchive contains test case
run:
 ansible-playbook -i "localhost," -c local test.yml

##### EXPECTED RESULTS
The variable role_l1_dry_run should remain defined

##### ACTUAL RESULTS
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'not role_l1_dry_run' failed. The error was: error while evaluating conditional (not role_l1_dry_run): 'role_l1_dry_run' is undefined\n\nThe error appears to be in '/var/tmp/tests/test1/roles/role_l4/tasks/main.yml': line 3, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  block:\n    - name:\n      ^ here\n"}

**Comment by sivel** [comment] 2020-06-29 19:53
Duplicate of https://github.com/ansible/ansible/issues/47023

**Closed as completed by sivel** 2020-06-29 19:53 UTC
