### ISSUE TITLE
Problem using group_by with with_items and facts

### ISSUE THREAD

**Issue by jcassee** [ansible/ansible#7540] opened 2014-05-25 20:41 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7 (devel ee82681d14) last updated 2014/05/23 10:56:18 (GMT +200)
##### Environment:

Ubuntu 14.04
##### Summary:

Using `group_by` with `with_items`, host-specific variables seem to be resolved only for the first host.
##### Steps To Reproduce:

hosts:

```
[group]
host1
host2
```

playbook:

```
- hosts: all
  connection: local
  gather_facts: no
  tasks:
  - debug: var=inventory_hostname
  - group_by: key={{ item }}
    with_items:
    - "{{ inventory_hostname }}"
  - debug: var=group_names
```

Run `ansible-playbook`:

```
$ ansible-playbook -i hosts test.yml
```
##### Expected Results:

```
PLAY [all] ******************************************************************** 

TASK: [debug var=inventory_hostname] ****************************************** 
ok: [host1] => {
    "inventory_hostname": "host1"
}
ok: [host2] => {
    "inventory_hostname": "host2"
}

TASK: [group_by key={{item}}] ************************************************* 
changed: [host1] => (item=host1)
changed: [host2] => (item=host2)

TASK: [debug var=group_names] ************************************************* 
ok: [host1] => {
    "group_names": [
        "group", 
        "host1"
    ]
}
ok: [host2] => {
    "group_names": [
        "group", 
        "host2"
    ]
}

PLAY RECAP ******************************************************************** 
host1                      : ok=3    changed=1    unreachable=0    failed=0   
host2                      : ok=3    changed=1    unreachable=0    failed=0   
```
##### Actual Results:

```
PLAY [all] ******************************************************************** 

TASK: [debug var=inventory_hostname] ****************************************** 
ok: [host1] => {
    "inventory_hostname": "host1"
}
ok: [host2] => {
    "inventory_hostname": "host2"
}

TASK: [group_by key={{item}}] ************************************************* 
changed: [host1] => (item=host1)

TASK: [debug var=group_names] ************************************************* 
ok: [host1] => {
    "group_names": [
        "group", 
        "host1"
    ]
}
ok: [host2] => {
    "group_names": [
        "group", 
        "host1"
    ]
}

PLAY RECAP ******************************************************************** 
host1                      : ok=3    changed=1    unreachable=0    failed=0   
host2                      : ok=3    changed=1    unreachable=0    failed=0   
```
##### Differences:

Note two things:
1. `host2` is in group `host1` instead of `host2`.
2. (cosmetic) There is only one status line for the `group_by` task.
##### Further info:

Using `with_items` without host-specific variables does work, but still only shows status lines for the first host:

```
- hosts: all
  connection: local
  gather_facts: no
  tasks:
  - debug: var=inventory_hostname
  - group_by: key={{ item }}
    with_items:
    - test1
    - test2
    - test3
  - debug: var=group_names
```

```
PLAY [all] ******************************************************************** 

TASK: [debug var=inventory_hostname] ****************************************** 
ok: [host2] => {
    "inventory_hostname": "host2"
}
ok: [host1] => {
    "inventory_hostname": "host1"
}

TASK: [group_by key={{item}}] ************************************************* 
changed: [host1] => (item=test1)
changed: [host1] => (item=test2)
changed: [host1] => (item=test3)

TASK: [debug var=group_names] ************************************************* 
ok: [host1] => {
    "group_names": [
        "group", 
        "test1", 
        "test2", 
        "test3"
    ]
}
ok: [host2] => {
    "group_names": [
        "group", 
        "test1", 
        "test2", 
        "test3"
    ]
}

PLAY RECAP ******************************************************************** 
host1                      : ok=3    changed=1    unreachable=0    failed=0   
host2                      : ok=3    changed=1    unreachable=0    failed=0   
```

Using a host-specific variable is in itself also not a problem:

```
- hosts: all
  connection: local
  gather_facts: no
  tasks:
  - debug: var=inventory_hostname
  - group_by: key={{ inventory_hostname }}
  - debug: var=group_names
```

```
PLAY [all] ******************************************************************** 

TASK: [debug var=inventory_hostname] ****************************************** 
ok: [host1] => {
    "inventory_hostname": "host1"
}
ok: [host2] => {
    "inventory_hostname": "host2"
}

TASK: [group_by key={{inventory_hostname}}] *********************************** 
changed: [host1]

TASK: [debug var=group_names] ************************************************* 
ok: [host1] => {
    "group_names": [
        "group", 
        "host1"
    ]
}
ok: [host2] => {
    "group_names": [
        "group", 
        "host2"
    ]
}

PLAY RECAP ******************************************************************** 
host1                      : ok=3    changed=1    unreachable=0    failed=0   
host2                      : ok=3    changed=1    unreachable=0    failed=0   
```

**Comment by jimi-c** [comment] 2014-05-27 18:31
I believe this is to be expected, as the `with_items:` invocation is expanded just the once (for the first host in the list) and that key is applied to all hosts. If you modify your playbook as follows:

<pre>
- hosts: all
  connection: local
  gather_facts: no
  tasks:
  - debug: var=inventory_hostname
  - group_by: key={{ inventory_hostname }}
  - debug: var=group_names
</pre>

everything works as expected, because the magic variable `inventory_hostname` is applied to each host in the list:

<pre>
# ansible-playbook 7540.yml -i 7540_inv 
PLAY [all] ******************************************************************** 
TASK: [debug var=inventory_hostname] ****************************************** 
ok: [host1] => {
    "inventory_hostname": "host1"
}
ok: [host2] => {
    "inventory_hostname": "host2"
}
TASK: [group_by key={{inventory_hostname}}] *********************************** 
changed: [host1]
TASK: [debug var=group_names] ************************************************* 
ok: [host2] => {
    "group_names": [
        "group", 
        "host2"
    ]
}
ok: [host1] => {
    "group_names": [
        "group", 
        "host1"
    ]
}
PLAY RECAP ******************************************************************** 
host1                      : ok=4    changed=1    unreachable=0    failed=0   
host2                      : ok=4    changed=1    unreachable=0    failed=0   
</pre>

**Comment by jcassee** [comment] 2014-05-27 21:51
Hi James,

I think I already included your example in my original submission? Anyway, why would `group_by` work differently than, for example, `set_fact`:

```
- hosts: all
  connection: local
  gather_facts: no
  tasks:
  - debug: var=inventory_hostname
  - set_fact:
      somevar={{ item }}
    with_items:
    - "{{ inventory_hostname }}"
  - debug: var=somevar
```

```
PLAY [all] ******************************************************************** 

TASK: [debug var=inventory_hostname] ****************************************** 
ok: [host1] => {
    "inventory_hostname": "host1"
}
ok: [host2] => {
    "inventory_hostname": "host2"
}

TASK: [set_fact somevar={{item}}] ********************************************* 
ok: [host1] => (item=host1)
ok: [host2] => (item=host2)

TASK: [debug var=somevar] ***************************************************** 
ok: [host2] => {
    "somevar": "host2"
}
ok: [host1] => {
    "somevar": "host1"
}

PLAY RECAP ******************************************************************** 
host1                      : ok=3    changed=0    unreachable=0    failed=0   
host2                      : ok=3    changed=0    unreachable=0    failed=0   
```

Notice how the `{{ item }}` is nicely expanded correctly for each host.

**Comment by jimi-c** [comment] 2015-06-22 05:30
Going back through issues, and this is actually a duplicate of #7199. The root cause is the fact that group_by is a BYPASS_HOST_LOOP action, which means that it executes only on the first host in the list of those in the play. Thus, any variables used which are sourced from inventory (facts, group_vars, host_vars) would only come from that first host in the list.

Since this is a duplicate, we'll close this here.

**Closed as completed by jimi-c** 2015-06-22 05:30 UTC
Labels: bug
