### ISSUE TITLE
Custom filter plugin cannot load custom module_utils library

### ISSUE THREAD

**Issue by davidmnoriega** [ansible/ansible#52871] opened 2019-02-23 00:32 UTC
##### SUMMARY
Custom filter_plugins cannot load a custom module_utils library the same way custom modules can

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.7.6
  config file = /home/david.noriega/x/x/x/ansible.cfg
  configured module search path = [u'/home/david.noriega/x/x/x/library']
  ansible python module location = /home/david.noriega/.virtualenvs/xxx/lib/python2.7/site-packages/ansible
  executable location = /home/david.noriega/.virtualenvs/xxx/bin/ansible
  python version = 2.7.15 (default, Oct 15 2018, 15:26:09) [GCC 8.2.1 20180801 (Red Hat 8.2.1-2)]
```

##### CONFIGURATION

```paste below
DEFAULT_MODULE_PATH(/home/david.noriega/x/x/x/ansible.cfg) = [u'/home/david.noriega/x/x/x/library']
```

##### OS / ENVIRONMENT

Fedora 29

##### STEPS TO REPRODUCE
Write a custom module that also has a custom module_utils library, then write a filter plugin that attempts to load the library with

```python
from ansible.module_utils.XXXX import YYYY
```

##### EXPECTED RESULTS

ansible-playbook runs with no warnings or eventual playbook error due to missing filter

##### ACTUAL RESULTS

```
[WARNING]: Skipping plugin (/x/x/x/x/filter_plugins/filters.py) as it seems to be invalid: No module named XXXX
.
.
.
TASK [debug] ************************************************************************************
fatal: [x.y.example.com]: FAILED! => {"msg": "template error while templating string: no filter named 'YYYY'. String: {{item|YYYY}}"}
```

**Comment by sivel** [comment] 2019-02-25 15:37
Duplicate of https://github.com/ansible/ansible/issues/28770

**Closed as completed by sivel** 2019-02-25 15:37 UTC
Labels: support:core, bug, affects_2.7
