### ISSUE TITLE
Default CallbackModule: 'module' object has no attribute 'dumps'

### ISSUE THREAD

**Issue by naftulikay** [ansible/ansible#28963] opened 2017-09-03 03:52 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

`ansible.plugins.callback.default.CallbackModule`

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### CONFIGURATION

`ansible.cfg`

```
[defaults]
roles_path = /etc/ansible/roles
retry_files_enabled = false
```

##### OS / ENVIRONMENT

Reproducible by me on [Ubuntu 14.04](https://travis-ci.org/naftulikay/ansible-role-ruby-dev/jobs/271307367) and [Ubuntu 16.04](https://travis-ci.org/naftulikay/ansible-role-ruby-dev/jobs/271307366).

##### SUMMARY

When a task fails, I invariably get the following output:

```
TASK [ruby-dev : install the given ruby version] *******************************

PLAY RECAP *********************************************************************
localhost                  : ok=20   changed=0    unreachable=0    failed=1

 [WARNING]: Failure using method (v2_runner_item_on_failed) in callback plugin
(<ansible.plugins.callback.default.CallbackModule object at 0x7f38f2ba7c10>):
'module' object has no attribute 'dumps'
```

##### STEPS TO REPRODUCE

Please see this link to builds which reliably reproduce this issue: https://travis-ci.org/naftulikay/ansible-role-ruby-dev/builds/271307364

##### EXPECTED RESULTS

I expected to see failure output.

##### ACTUAL RESULTS

The above error is thrown.

```
TASK [ruby-dev : install the given ruby version] *******************************

PLAY RECAP *********************************************************************
localhost                  : ok=20   changed=0    unreachable=0    failed=1

 [WARNING]: Failure using method (v2_runner_item_on_failed) in callback plugin
(<ansible.plugins.callback.default.CallbackModule object at 0x7f38f2ba7c10>):
'module' object has no attribute 'dumps'
```

**Comment by bcoca** [comment] 2017-09-05 12:54
I cannot reproduce this locally? can you supply a playbook with a minimal reproducer?
It is specially telling that that first job uses `v2_runner_item_on_failed` w/o any issues.

**Comment by naftulikay** [comment] 2017-09-06 02:25
Here is my test playbook: https://github.com/naftulikay/ansible-role-ruby-dev/blob/master/tests/playbook.yml

It only throws the error if a task fails.

**Comment by naftulikay** [comment] 2017-09-10 05:24
Running a new playbook and `-vvv`:

```
TASK [java-dev : download gradle] **********************************************
task path: /etc/ansible/roles/java-dev/tasks/gradle.yml:2
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1505020739.37-69223633457760 `" && echo ansible-tmp-1505020739.37-69223633457760="` echo /root/.ansible/tmp/ansible-tmp-1505020739.37-69223633457760 `" ) && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1505020739.37-69223633457760/ > /dev/null 2>&1 && sleep 0'
 [WARNING]: Failure using method (v2_runner_on_failed) in callback plugin
(<ansible.plugins.callback.default.CallbackModule object at 0x7ff3f771b3d0>):
'module' object has no attribute 'dumps'
```

Source task:

```
- name: download gradle
  unarchive:
    src: https://services.gradle.org/distributions/gradle-{{ gradle_version }}-all.zip
    dest: /usr/local/share/
    # creates: /usr/local/share/gradle-{{ gradle_version }}/bin/gradle
  become: true
```

Still Ansible 2.3.2.0.

**Comment by naftulikay** [comment] 2017-09-10 05:27
Inspecting the source code, I find no call to `dumps` whatsoever in the default CallbackModule. However, there is a call to `json.dumps` in [my own output plugin](https://github.com/naftulikay/ansible-role-degoss/blob/master/callback_plugins/goss_format.py#L29), albeit qualified as `json.dumps`.

Is there a way to get a stacktrace here?

**Comment by naftulikay** [comment] 2017-09-10 05:29
Apparently it _is_ being caused by my own module, as when I remove the play with the `degoss` role in it, I get output again. I will triage and debug the issue.

**Comment by naftulikay** [comment] 2017-09-18 20:27
I have provided ample more details [on this StackOverflow question](https://stackoverflow.com/questions/46287669/failure-using-method-module-object-has-no-attribute-dumps).

**Comment by bcoca** [comment] 2017-09-18 20:49
if you run with 2.4 and -vvv you should see the stacktrace

**Comment by bcoca** [comment] 2017-10-28 05:27
dupe of #31527

**Closed as completed by bcoca** 2017-10-28 05:27 UTC
Labels: needs_info, affects_2.3, support:core, bug
