### ISSUE TITLE
Invalid deprecation warning message with certain types of syntax errors

### ISSUE THREAD

**Issue by JoelFeiner** [ansible/ansible#28672] opened 2017-08-25 15:24 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Seems to be a core feature.

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /<redacted>/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### CONFIGURATION

ansible.cfg
```
[defaults]
host_key_checking = false
gathering = smart
[ssh_connection]
scp_if_ssh = true
```

No environment variables changed

##### OS / ENVIRONMENT
Ubuntu 17.04 x86-64

##### SUMMARY

If you have a playbook that has a misnamed task parameter, instead of getting an appropriate message about an unknown parameter, and file/line information, you get this deprecation warning about an entirely different issue, with no file/line information.

```
[DEPRECATION WARNING]: Specifying include variables at the top-level of the task is deprecated. Please see:
http://docs.ansible.com/ansible/playbooks_roles.html#task-include-files-and-
encouraging-reuse

 for currently supported syntax regarding included files and variables.
This feature will be removed in a future release. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
```

In my case, I had mistyped "static" as "statice" in one of the include tasks in my roles. Thankfully, version control was able to allow me to isolate the problem quickly. It would have been considerably more tedious to find the issue otherwise.

##### STEPS TO REPRODUCE

In the main playbook file:
```yaml
- hosts: all
  tasks:
   - include: foo.yml
     statice: no
```

And then foo.yml can be a list of tasks (not included here as it is not relevant).

The misspelled "statice" triggers the error.

##### EXPECTED RESULTS

An error message indicating that "statice" is not a valid task argument, and information about where this invalid parameter is (file and line number), as with most other errors.

##### ACTUAL RESULTS
Error message as in the summary above.

**Comment by JoelFeiner** [comment] 2017-08-25 15:24
Relates to:
 - https://github.com/ansible/ansible/issues/12282
 - https://github.com/ansible/ansible/issues/16183

**Comment by nrwahl2** [comment] 2017-08-26 07:04
@JoelFeiner If you use `import_tasks` for static task includes and `include_tasks` for dynamic task includes, you should no longer see these warnings **on 2.4**. I was clued in because my deprecation warnings on 2.4 are more descriptive.

It looks like someone halfway updated the deprecation warnings and then stopped and committed. The formatting is a bit off, and it's not accurate. `include_tasks` and `import_tasks` are not yet available as of 2.3.2. They **are** available on 2.4. The deprecation warning should not advise you to use a feature that doesn't exist yet -_-

On 2.4 with `statice`:
```
[reid@laptop ~]$ cat dep-test.yml 
- hosts: localhost
  connection: local
  tasks:
    - include: foo.yml
      statice: no
[reid@laptop ~]$ ansible-playbook dep-test.yml -i hosts.ini 
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions.
This feature will be removed in a future release. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Specifying include variables at the top-level of the task is deprecated. Please see:
http://docs.ansible.com/ansible/playbooks_roles.html#task-include-files-and-encouraging-reuse

 for 
currently supported syntax regarding included files and variables.
This feature will be removed in version 2.7. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
...
```

On 2.4 with `static`:
```
[reid@laptop ~]$ cat dep-test.yml 
- hosts: localhost
  connection: local
  tasks:
    - include: foo.yml
      static: no
[reid@laptop ~]$ ansible-playbook dep-test.yml -i hosts.ini 
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions.
This feature will be removed in a future release. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: The use of 'static' has been deprecated. Use 'import_tasks' for static inclusion, or 'include_tasks' for dynamic inclusion.
This feature will be removed in a future release. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
...
```

On 2.4 with `include_tasks`:
```
[reid@laptop ~]$ cat dep-test.yml 
- hosts: localhost
  connection: local
  tasks:
    - include_tasks: foo.yml    # include_tasks for dynamic, import_tasks for static
[reid@laptop ~]$ ansible-playbook dep-test.yml -i hosts.ini 

PLAY [localhost] **************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
ok: [localhost]

TASK [include_tasks] **********************************************************************************************************************************************************************************************
included: /home/reid/foo.yml for localhost

TASK [touch a file] ***********************************************************************************************************************************************************************************************
 [WARNING]: Consider using file module with state=touch rather than running touch

changed: [localhost]

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0   
```

Please see the following links for more info for 2.4.
https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/playbooks_reuse.rst
https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/playbooks_reuse_includes.rst

Meanwhile we need to see if we can either get the warning removed for 2.3, or better yet, flesh out the warning and backport the two new actions.

**Comment by nrwahl2** [comment] 2017-08-26 07:08
FWIW, this is what happens when I try to run the third iteration above (the one with `include_tasks`) on Ansible 2.3.2:
```
[reid@laptop ~]$ ansible-playbook dep-test.yml -i hosts.ini 
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/home/reid/dep-test.yml': line 4, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - include_tasks: foo.yml
      ^ here


The error appears to have been in '/home/reid/dep-test.yml': line 4, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - include_tasks: foo.yml
      ^ here
```

**Comment by bcoca** [comment] 2017-08-28 14:45
@JoelFeiner  you are 1/2 right, but also 1/2 wrong. Most tasks will give you a 'invalid keyword' message, but sadly `include` was special and allowed for 'variables' to be included at the same level as keywords, which is of course confusing .. so anything NOT recognized as a keyword is assumed to be a variable .. including misspelled keywords. 

We deprecated this behaviour and plan to remove it to avoid exactly THIS problem as it causes much confusion, once the 'feature' is removed this message will properly describe an 'unsupported keyword' instead of a warning about defining variables.

As per above, I'm closing this issue as not a bug.

**Closed as completed by bcoca** 2017-08-28 14:45 UTC
Labels: affects_2.3, support:core, bug
