### ISSUE TITLE
"unquoted colon" error inside quoted string

### ISSUE THREAD

**Issue by zystem** [ansible/ansible#10140] opened 2015-01-30 17:06 UTC
Issue Type:

Bug Report
Ansible Version:

1.8.2
Environment:

RHEL 6.x
Summary:
Ansible get error then parsing quoted string with colon inside

```
  - cron: name="fiber check 2" minute="0" job="fcinfo hba-port | tr '\n' ';' | perl -pe 's/(HBA Port WWN:)/\n$1/g' | grep -v 'State: offline'"
```

Error text:

```
ERROR: Syntax Error while loading YAML script, fiber.yml
Note: The error may actually appear before this position: line 9, column 135

  - cron: name="fiber check 2" minute="0" job="fcinfo hba-port | tr '\n' ';' | perl -pe 's/(HBA Port WWN:)/\n$1/g' | grep -v 'State: offline'"
                                                                                                                                   ^
This one looks easy to fix.  There seems to be an extra unquoted colon in the line
and this is confusing the parser. It was only expecting to find one free
colon. The solution is just add some quotes around the colon, or quote the
entire line after the first colon.
```

but the next code works great

```
  vars:
    abc: "fcinfo hba-port | tr '\n' ';' | perl -pe 's/(HBA Port WWN:)/\n$1/g' | grep -v 'State: offline'"
  tasks:
  - cron: name="fiber check 2" minute="0" job="{{ abc }}"
```

**Comment by arBmind** [comment] 2015-01-30 20:16
This is not an issue with Ansible. YAML has some limitations, this is one of them.

For YAML nothing is quoted unless your values starts like that. In your case "cron" is the key and then follows an unquoted string value. Where no further colons are allowed.

use may use the hash syntax

``` yaml
- cron:
    name: fiber check 2
    minute: 0
    job: "fcinfo hba-port | tr '\n' ';' | perl -pe 's/(HBA Port WWN:)/\n$1/g' | grep -v 'State: offline'"
```

This is from the YAML perspective the same as your second try.

Or you have to quote the entire string. which is really ugly.

``` yaml
- cron: "name=\"fiber check 2\" minute=\"0\" job=\"fcinfo hba-port | tr '\n' ';' | perl -pe 's/(HBA Port WWN:)/\n$1/g' | grep -v 'State: offline'\""
```

You may also use one of the extended string syntax options built into YAML.

``` yaml
- cron: >
    name="fiber check 2" minute="0" job="fcinfo hba-port | tr '\n' ';' | perl -pe 's/(HBA Port WWN:)/\n$1/g' | grep -v 'State: offline'"
```

**Comment by bcoca** [comment] 2015-02-02 13:45
closing as per @arBmind 's answer, this is not a bug, this is a YAML requirement to quote the whole string when a colon with a trailing space is part of the string.

**Closed as completed by bcoca** 2015-02-02 13:45 UTC
