### ISSUE TITLE
with_sequence is skipped when count = 1

### ISSUE THREAD

**Issue by bandesz** [ansible/ansible#11581] opened 2015-07-14 11:25 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.9.2 (works in ansible 1.9.1)
##### Ansible Configuration:

Nothing changed, clean install
##### Environment:

N/A
##### Summary:

A task with with_sequence and count = 1 is skipped
##### Steps To Reproduce:

```
- command: echo "{{ item }}"
  with_sequence: start=1 count=1
```
##### Expected Results:

The task not to be skipped and run once.
##### Actual Results:

```
TASK: [command echo "{{ item }}"] *********************************************
skipping: [localhost]
```

**Comment by bcoca** [comment] 2015-07-14 11:30
closing as dupe of #11546, #11504, #11480 and #11422

**Closed as completed by bcoca** 2015-07-14 11:30 UTC

**Comment by bandesz** [comment] 2015-07-14 11:34
@bcoca sorry, only did a search in open tickets.
