### ISSUE TITLE
include_role with delegation - handlers does not delegate to remote host

### ISSUE THREAD

**Issue by sunshine69** [ansible/ansible#26336] opened 2017-07-03 06:59 UTC
Tested with latest ansible devl branch as well as stable 2.3.1.0

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
include_role

##### ANSIBLE VERSION
2.3.1.0
latest devel (2.4.0)
```
```

##### OS / ENVIRONMENT
OS: Linux ubuntu 16.04

##### SUMMARY
when I use include_role with delegation_to a remote hosts the handlers in the role does not get delegated.

##### STEPS TO REPRODUCE
Play the playbook 
ansible-playbook -v playbook-handler-delegation-bug.yml
Using /etc/ansible/ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available

PLAY [localhost] *******************************************************************************************************

TASK [handlertest : command] *******************************************************************************************
{'9801a79b-b2f9-559a-7a69-00000000000b': []}
9801a79b-b2f9-559a-7a69-00000000000b
changed: [localhost -> 10.13.9.216] => {"changed": true, "cmd": ["echo"], "delta": "0:00:00.001692", "end": "2017-07-03 06:58:58.486566", "rc": 0, "start": "2017-07-03 06:58:58.484874", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

RUNNING HANDLER [handlertest : Some handler] ***************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["systemctl", "daemon-reload"], "delta": "0:00:25.024095", "end": "2017-07-03 17:01:17.454599", "failed": true, "rc": 1, "start": "2017-07-03 17:00:52.430504", "stderr": "Failed to execute operation: Connection timed out", "stderr_lines": ["Failed to execute operation: Connection timed out"], "stdout": "", "stdout_lines": []}
	to retry, use: --limit @/home/stevek/tmp/test-ansible/playbook-handler-delegation-bug.retry

PLAY RECAP *************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=1 

```
cat playbook-handler-delegation-bug.yml 
---
- hosts: localhost
  gather_facts: no
  tasks:
    - include_role:
        name: handlertest
      delegate_to: 10.13.9.216

cat roles/handlertest/tasks/main.yml 
---
- command: echo
  notify: Some handler

cat roles/handlertest/handlers/main.yml 
---
- name: Some handler
  command: systemctl daemon-reload


```

##### EXPECTED RESULTS
Look at the output RUNNING HANDLER [handlertest : Some handler]
It should show the delegation to the remote hosts.

And it should run the command at remote hosts.

##### ACTUAL RESULTS

From the output it does not delegate to remote host.
Instead it runs at localhost and my desktop pop up a dialog to ask credential to run the systemd reload systemd state.

Then I click Cancel and then it failed (see the output above)
```

```

**Comment by Oloremo** [comment] 2017-09-12 14:43
Any news on this issue?..

**Comment by agnellodsouza** [comment] 2017-09-21 17:54
am facing the same issue

**Comment by agnellodsouza** [comment] 2017-09-24 15:01
Am having the same problem , below is my piece of code . 

root@ansible-control-mach1:/opt/ansible/playbooks# ansible --version
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]

I have create a playbook to do rolling updates , rollingupdates.yml 



---
 - include: deploy.yml

 - hosts: webserver
   become: true
   serial: 1


   pre_tasks:
      - include_role:
          name: nginx
        vars:
          backend_var: "{{ inventory_hostname }}"
        delegate_to: Load-bal-nginx1

   roles:
     - apache2
     - webapp


   post_tasks:
     - include_role:
         name: nginx
       vars:
         backend_var: ""
       delegate_to:  Load-bal-nginx1

This rolling update file then calls  roles/nginx/tasks/main.yml 
I am passing backend_var vairable to the template file 

---


        - name: passing vairble to handler
          set_fact:
             backend_var: "{{ backend_var | default('') }}"


        - name : install Nginx
          apt: name=nginx state=present update_cache=no
        - name: ensure nginx service is started
          service: name=nginx state=started enabled=yes

        - name: configure nginx
          template: src=templates/nginx.conf.j2 dest=/etc/nginx/sites-available/nginx.conf mode=0644
          notify: restart nginx

        - name: de-activate default nginx site
          file: path=/etc/nginx/sites-enabled/default state=absent
          notify: restart nginx

        - name: activate LB
          file: src=/etc/nginx/sites-available/nginx.conf   dest=/etc/nginx/sites-enabled/nginx.conf state=link
          notify: restart nginx


when i run the rollingupdate.yml file 

root@ansible-control-mach1:/opt/ansible/playbooks# ansible-playbook tt.yml

PLAY [webserver] *******************************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************************
ok: [Web-server1]

TASK [nginx : debug] ***************************************************************************************************************************************************************************
ok: [Web-server1 -> 192.168.48.4] => {
    "msg": " Web-server1 is thisrere "
}

TASK [nginx : passing vairble to handler] ******************************************************************************************************************************************************
ok: [Web-server1 -> 192.168.48.4]

TASK [nginx : install Nginx] *******************************************************************************************************************************************************************
ok: [Web-server1 -> 192.168.48.4]

TASK [nginx : ensure nginx service is started] *************************************************************************************************************************************************
changed: [Web-server1 -> 192.168.48.4]

TASK [nginx : configure nginx] *****************************************************************************************************************************************************************
changed: [Web-server1 -> 192.168.48.4]

TASK [nginx : de-activate default nginx site] **************************************************************************************************************************************************
ok: [Web-server1 -> 192.168.48.4]

TASK [nginx : activate LB] *********************************************************************************************************************************************************************
ok: [Web-server1 -> 192.168.48.4]

****RUNNING HANDLER [nginx : restart nginx] ********************************************************************************************************************************************************
fatal: [Web-server1]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service nginx: host"}**
        to retry, use: --limit @/opt/ansible/playbooks/tt.retry**

PLAY RECAP *************************************************************************************************************************************************************************************
Web-server1                : ok=8    changed=2    unreachable=0    failed=1
---------------------------------------------------------------------------------------

Instead of running the handler on Nginx server its runs Restart of Nginx  the apache  webserver . 

Is there a workaround for this .

**Comment by agnellodsouza** [comment] 2017-10-03 18:17
Is there any update on this !! ..

**Comment by sebastiencaty** [comment] 2017-12-01 15:10
Having the same issue here with ansible 2.4.1. Handlers are run only on the play host and not the delegated host. Tried several workaround without success. 

You cannot use handlers in this scenario. Instead, I did a register:var and added another task that run only when: var|changed.

**Comment by colemanja91** [comment] 2018-03-05 13:21
Seeing the same on Ansible 2.4.3

**Comment by aderbique** [comment] 2018-04-04 18:43
Issue is still not resolved

**Comment by sivel** [comment] 2018-04-04 19:16
As of ansible 2.5, `delegate_to` is expected to have no effect on `include_role`.

This was the intention in 2.4, but the code did not match the intention.

In 2.5, applying an attribute to `include_role` only affects the `include_role` itself, not the tasks or handlers within the role.  As such, `delegate_to` on an `include_role` makes no sense and is effectively ignored.

**Comment by mback2k** [comment] 2018-04-06 08:01
@sivel So what is the indented way to modularize ansible playbooks and have for a example a task file in a role which is able to configure a virtual host or firewall on a delegated host. We are making heavy use of something like this:

```
- name: Create apache2 vhosts configuration
  include_role:
    name: network-services-apache
    tasks_from: update-vhost
  vars:
    (variables that specify the vhost configuration)

- name: Create reverse proxy site
  delegate_to: (reverse proxy host here)
  delegate_facts: true
  include_role:
    name: network-services-nginx
    tasks_from: update-vhost
  vars:
    (variables that specify the vhost configuration)
```

The included roles trigger handlers that reload the apache2 and nginx daemons to apply the configuration.

Do you have any suggestion on how to handle something like that in the future?

**Comment by teddyphreak** [comment] 2018-04-06 16:20
Thank you for the clarification @sivel. 
Can you provide a link that confirms that documentation for delegate_to and include_role in version 2.4 were marked as preview and not guaranteed to have a stable interface? otherwise the intention of the code is irrelevant to the issue and this is indeed a regression as reported initially

**Comment by sivel** [comment] 2018-04-06 16:41
metadata for `include_role` in 2.4:

https://github.com/ansible/ansible/blob/v2.4.4.0-1/lib/ansible/modules/utilities/logic/include_role.py#L10-L14

Also, we don't guarantee from major release to major release that there will be no backwards incompatibilities.  2.4 and 2.5 being major releases.

The porting guides are updated for each release for situations such as these:

http://docs.ansible.com/ansible/latest/porting_guides/porting_guides.html

Closing this as things are working as intended.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Closed as completed by sivel** 2018-04-06 16:41 UTC
Labels: affects_2.3, c:playbook/handler*, c:playbook/role_include, support:core, include_role, bug

**Comment by mback2k** [comment] 2019-02-18 14:48
> Do you have any suggestion on how to handle something like that in the future?

BTW-- We are now using import_role instead of include_rule and handlers are now delegated as well.
