### ISSUE TITLE
"limit" does not match hosts with spaces in hostname

### ISSUE THREAD

**Issue by simfarm** [ansible/ansible#14513] opened 2016-02-16 22:17 UTC
**Issue Type:**

Bug Report

**Ansible Version:**

```
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

**Ansible Configuration:**

Using default ansible.cfg.

**Environment:**

Centos 6.7 (up to date).

**Description**

`--limit` no longer works in matching hosts with spaces in their hostname under ansible-v2. Manually tested and this worked under ansible-1.9.2.

**Steps to Reproduce**
- Create the following inventory file:

```
"foopey mackrel" ansible_host=127.0.0.1 ansible_connection=local ansible_python_interpreter='/usr/bin/env python'
```
- Create the following playbook:

```
[root@localhost ~]# cat ping.yml

---

- hosts: all
  gather_facts: false
  tasks:
    - ping:
```
- Run the following command:

```
ansible-playbook ping.yml -i inventory -l "foopey mackrel"
```

**Expected Results**
This is what we get under ansible 1.9.2:

```
PLAY [all] ******************************************************************** 

TASK: [ping ] ***************************************************************** 
ok: [foopey mackrel]

PLAY RECAP ******************************************************************** 
foopey mackrel              : ok=1    changed=0    unreachable=0    failed=0   
```

**Actual Results**

```
ERROR! Specified --limit does not match any hosts
```

**Comment by jlaska** [comment] 2016-02-17 14:59
@simfarm In your sample inventory, you used `ansible_host`.  I presume you meant to use `ansible_ssh_host`?

**Comment by jimi-c** [comment] 2016-02-17 15:08
@jlaska they are interchangeable. `ansible_host` is the more generalized version while `ansible_ssh_host` is intended to be specifically for the ssh/paramiko connection plugins.

**Comment by jladdjr** [comment] 2016-04-18 18:29
Still seeing this issue in ansible 2.0.1.0.

**Comment by jladdjr** [comment] 2016-04-18 18:33
@jimi-c - we saw this issue come in testing Tower 2.4.5 - any plans to get a fix for this?

**Comment by simfarm** [comment] 2016-04-18 20:37
Also seeing this.

**Comment by jladdjr** [comment] 2016-04-19 14:46
Followed the above steps to reproduce..
- On ansible 2.0.1.0 - still seeing `ERROR! Specified --limit does not match any hosts`
- On fresh build of ansible 2.0.2.0 - still seeing `ERROR! Specified --limit does not match any hosts`
- On ansible 1.9.6 - playbook runs successfully

Can we confirm that this fix is on the 2.x branch?

**Comment by jladdjr** [comment] 2016-04-20 14:54
Ran through steps to reproduce using `devel` branch of ansible repo. Seeing `ERROR! Specified --limit does not match any hosts` here as well:

```
Jamess-MacBook-Pro% ansible-playbook ping.yml -i inventory -l "foopey mackrel"
ERROR! Specified --limit does not match any hosts
```

Version:

```
Jamess-MacBook-Pro% ansible --version
ansible 2.1.0 (devel c600ab81ee) last updated 2016/04/20 10:49:55 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 98322a777f) last updated 2016/04/20 10:50:44 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 1aecfc1e19) last updated 2016/04/20 10:50:47 (GMT -400)
  config file = /Users/jladd/.ansible.cfg
  configured module search path = Default w/o overrides
```

**Comment by jimi-c** [comment] 2016-04-20 15:32
For the record, the use of spaces in host names is forbidden. However, we do have another issue in which the use of spaces in group names should be allowed. As such, we're going to close this issue.

Thanks!

**Closed as completed by jimi-c** 2016-04-20 15:32 UTC
Labels: bug
