### ISSUE TITLE
ansible_modeule_unarchive.py failure after update

### ISSUE THREAD

**Issue by Guyverix** [ansible/ansible#40549] opened 2018-05-22 17:31 UTC
##### SUMMARY
Ubuntu Xenial release upgrade from Ansible 2.5.2-1 to 2.5.3-1 from the PPA appears to have broken part of the deploy environment dealing with unarchiving files.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

ansible_module_unarchive.py

##### ANSIBLE VERSION

```
ansible --version
ansible 2.5.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/chubbard/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

```

##### CONFIGURATION

ansible-config dump --only-changed
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/opt/ansible-configs/base/inventory']
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT

Ubuntu 16.04.4 LTS

##### STEPS TO REPRODUCE

```yaml
- name: Extract files to the /opt/{{ application }} directory
  unarchive: 
    src=/opt/automation-build/builds/{{ build_env }}/{{ application }}/{{ version }}.tar.gz
    dest=/opt/
    owner=jetty
    group=jetty
    extra_opts="--overwrite"
  become: true
  register: result2

```

##### EXPECTED RESULTS

extract the files from the tar.gz file that was copied over.

##### ACTUAL RESULTS

It appears that something is missing when setting the /home/USER/.ansble path.  I am now seeing a /home/USER/~None/.ansible subdirectory in my home directory on the destination host that I am attempting to deploy to.  

```
TASK [/opt/ansible-configs/base/roles/mongoDbToPostgreSqlExport : Extract files to the /opt/mongoDbToPostgreSqlExport directory] ***************************************************************************************************************************
task path: /opt/ansible-configs/base/roles/mongoDbToPostgreSqlExport/tasks/main.yml:36
<prod-fups02-sea.anytime.org> ESTABLISH SSH CONNECTION FOR USER: None
<prod-fups02-sea.anytime.org> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/chubbard/.ansible/cp/3d06fc2029 prod-fups02-sea.anytime.org '/bin/sh -c '"'"'echo ~None && sleep 0'"'"''
<prod-fups02-sea.anytime.org> (0, '~None\n', '')
<prod-fups02-sea.anytime.org> ESTABLISH SSH CONNECTION FOR USER: None
<prod-fups02-sea.anytime.org> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/chubbard/.ansible/cp/3d06fc2029 prod-fups02-sea.anytime.org '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo ~None/.ansible/tmp/ansible-tmp-1527009660.7-122004306651677 `" && echo ansible-tmp-1527009660.7-122004306651677="` echo ~None/.ansible/tmp/ansible-tmp-1527009660.7-122004306651677 `" ) && sleep 0'"'"''
<prod-fups02-sea.anytime.org> (0, 'ansible-tmp-1527009660.7-122004306651677=~None/.ansible/tmp/ansible-tmp-1527009660.7-122004306651677\n', '')
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/files/stat.py
<prod-fups02-sea.anytime.org> PUT /home/chubbard/.ansible/tmp/ansible-local-26937G_fsx_/tmpthrRAT TO ~None/.ansible/tmp/ansible-tmp-1527009660.7-122004306651677/stat.py
<prod-fups02-sea.anytime.org> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/chubbard/.ansible/cp/3d06fc2029 '[prod-fups02-sea.anytime.org]'
<prod-fups02-sea.anytime.org> (0, "sftp> put /home/chubbard/.ansible/tmp/ansible-local-26937G_fsx_/tmpthrRAT '~None/.ansible/tmp/ansible-tmp-1527009660.7-122004306651677/stat.py'\n", '')
<prod-fups02-sea.anytime.org> ESTABLISH SSH CONNECTION FOR USER: None
<prod-fups02-sea.anytime.org> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/chubbard/.ansible/cp/3d06fc2029 prod-fups02-sea.anytime.org '/bin/sh -c '"'"'chmod u+x '"'"'"'"'"'"'"'"'~None/.ansible/tmp/ansible-tmp-1527009660.7-122004306651677/'"'"'"'"'"'"'"'"' '"'"'"'"'"'"'"'"'~None/.ansible/tmp/ansible-tmp-1527009660.7-122004306651677/stat.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''
<prod-fups02-sea.anytime.org> (0, '', '')
<prod-fups02-sea.anytime.org> ESTABLISH SSH CONNECTION FOR USER: None
<prod-fups02-sea.anytime.org> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/chubbard/.ansible/cp/3d06fc2029 -tt prod-fups02-sea.anytime.org '/bin/sh -c '"'"'sudo -H -S  -p "[sudo via ansible, key=rltbucwomzzibhhorzlfgtxowovxjppw] password: " -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-rltbucwomzzibhhorzlfgtxowovxjppw; /usr/bin/python '"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'~None/.ansible/tmp/ansible-tmp-1527009660.7-122004306651677/stat.py'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"''"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
<prod-fups02-sea.anytime.org> (0, '\r\n\r\n{"invocation": {"module_args": {"checksum_algorithm": "sha1", "get_checksum": true, "follow": true, "checksum_algo": "sha1", "path": "/opt/", "get_md5": null, "get_mime": true, "get_attributes": true}}, "stat": {"charset": "binary", "uid": 0, "exists": true, "attr_flags": "e", "woth": true, "isreg": false, "device_type": 0, "mtime": 1526578838.1303155, "block_size": 4096, "inode": 2621441, "isgid": false, "size": 4096, "executable": true, "isuid": false, "readable": true, "version": "781266571", "pw_name": "root", "gid": 0, "ischr": false, "wusr": true, "writeable": true, "mimetype": "inode/directory", "blocks": 8, "xoth": true, "islnk": false, "nlink": 9, "issock": false, "rgrp": true, "gr_name": "root", "path": "/opt/", "xusr": true, "atime": 1526675300.7297072, "isdir": true, "ctime": 1526578838.1303155, "isblk": false, "wgrp": false, "xgrp": true, "dev": 2056, "roth": true, "isfifo": false, "mode": "0757", "rusr": true, "attributes": ["extents"]}, "changed": false}\r\n', 'Shared connection to prod-fups02-sea.anytime.org closed.\r\n')
<prod-fups02-sea.anytime.org> PUT /opt/automation-build/builds/prod/mongoDbToPostgreSqlExport/mongoDbToPostgreSqlExport_prod_35.tar.gz TO ~None/.ansible/tmp/ansible-tmp-1527009660.7-122004306651677/source
<prod-fups02-sea.anytime.org> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/chubbard/.ansible/cp/3d06fc2029 '[prod-fups02-sea.anytime.org]'
<prod-fups02-sea.anytime.org> (0, "sftp> put /opt/automation-build/builds/prod/mongoDbToPostgreSqlExport/mongoDbToPostgreSqlExport_prod_35.tar.gz '~None/.ansible/tmp/ansible-tmp-1527009660.7-122004306651677/source'\n", '')
<prod-fups02-sea.anytime.org> ESTABLISH SSH CONNECTION FOR USER: None
<prod-fups02-sea.anytime.org> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/chubbard/.ansible/cp/3d06fc2029 prod-fups02-sea.anytime.org '/bin/sh -c '"'"'chmod u+x '"'"'"'"'"'"'"'"'~None/.ansible/tmp/ansible-tmp-1527009660.7-122004306651677/'"'"'"'"'"'"'"'"' '"'"'"'"'"'"'"'"'~None/.ansible/tmp/ansible-tmp-1527009660.7-122004306651677/source'"'"'"'"'"'"'"'"' && sleep 0'"'"''
<prod-fups02-sea.anytime.org> (0, '', '')
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/files/unarchive.py
<prod-fups02-sea.anytime.org> PUT /home/chubbard/.ansible/tmp/ansible-local-26937G_fsx_/tmpzX5f0u TO ~None/.ansible/tmp/ansible-tmp-1527009660.7-122004306651677/unarchive.py
<prod-fups02-sea.anytime.org> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/chubbard/.ansible/cp/3d06fc2029 '[prod-fups02-sea.anytime.org]'
<prod-fups02-sea.anytime.org> (0, "sftp> put /home/chubbard/.ansible/tmp/ansible-local-26937G_fsx_/tmpzX5f0u '~None/.ansible/tmp/ansible-tmp-1527009660.7-122004306651677/unarchive.py'\n", '')
<prod-fups02-sea.anytime.org> ESTABLISH SSH CONNECTION FOR USER: None
<prod-fups02-sea.anytime.org> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/chubbard/.ansible/cp/3d06fc2029 prod-fups02-sea.anytime.org '/bin/sh -c '"'"'chmod u+x '"'"'"'"'"'"'"'"'~None/.ansible/tmp/ansible-tmp-1527009660.7-122004306651677/'"'"'"'"'"'"'"'"' '"'"'"'"'"'"'"'"'~None/.ansible/tmp/ansible-tmp-1527009660.7-122004306651677/unarchive.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''
<prod-fups02-sea.anytime.org> (0, '', '')
<prod-fups02-sea.anytime.org> ESTABLISH SSH CONNECTION FOR USER: None
<prod-fups02-sea.anytime.org> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/chubbard/.ansible/cp/3d06fc2029 -tt prod-fups02-sea.anytime.org '/bin/sh -c '"'"'sudo -H -S  -p "[sudo via ansible, key=robwbdprijvhguuerlowrohuahwpfeea] password: " -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-robwbdprijvhguuerlowrohuahwpfeea; /usr/bin/python '"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'~None/.ansible/tmp/ansible-tmp-1527009660.7-122004306651677/unarchive.py'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"''"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
<prod-fups02-sea.anytime.org> (1, '\r\n\r\n{"msg": "Failed to find handler for \\"~None/.ansible/tmp/ansible-tmp-1527009660.7-122004306651677/source\\". Make sure the required command to extract the file is installed. Command \\"/bin/tar\\" could not handle archive. Command \\"/usr/bin/unzip\\" could not handle archive.", "failed": true, "exception": "  File \\"/tmp/ansible_Hxz24C/ansible_module_unarchive.py\\", line 140, in <module>\\n    from shlex import quote\\n", "invocation": {"module_args": {"directory_mode": null, "force": null, "remote_src": false, "exclude": [], "owner": "jetty", "follow": false, "group": "jetty", "unsafe_writes": null, "keep_newer": false, "setype": null, "content": null, "serole": null, "extra_opts": ["[--overwrite]"], "dest": "/opt/", "selevel": null, "original_basename": "mongoDbToPostgreSqlExport_prod_35.tar.gz", "regexp": null, "src": "~None/.ansible/tmp/ansible-tmp-1527009660.7-122004306651677/source", "validate_certs": true, "list_files": false, "seuser": null, "creates": null, "delimiter": null, "mode": null, "attributes": null, "backup": null}}}\r\n', 'Shared connection to prod-fups02-sea.anytime.org closed.\r\n')
<prod-fups02-sea.anytime.org> ESTABLISH SSH CONNECTION FOR USER: None
<prod-fups02-sea.anytime.org> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/chubbard/.ansible/cp/3d06fc2029 prod-fups02-sea.anytime.org '/bin/sh -c '"'"'rm -f -r '"'"'"'"'"'"'"'"'~None/.ansible/tmp/ansible-tmp-1527009660.7-122004306651677/'"'"'"'"'"'"'"'"' > /dev/null 2>&1 && sleep 0'"'"''
<prod-fups02-sea.anytime.org> (0, '', '')
The full traceback is:
  File "/tmp/ansible_Hxz24C/ansible_module_unarchive.py", line 140, in <module>
    from shlex import quote

fatal: [prod-fups02-sea.anytime.org]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "attributes": null, 
            "backup": null, 
            "content": null, 
            "creates": null, 
            "delimiter": null, 
            "dest": "/opt/", 
            "directory_mode": null, 
            "exclude": [], 
            "extra_opts": [
                "[--overwrite]"
            ], 
            "follow": false, 
            "force": null, 
            "group": "jetty", 
            "keep_newer": false, 
            "list_files": false, 
            "mode": null, 
            "original_basename": "mongoDbToPostgreSqlExport_prod_35.tar.gz", 
            "owner": "jetty", 
            "regexp": null, 
            "remote_src": false, 
            "selevel": null, 
            "serole": null, 
            "setype": null, 
            "seuser": null, 
            "src": "~None/.ansible/tmp/ansible-tmp-1527009660.7-122004306651677/source", 
            "unsafe_writes": null, 
            "validate_certs": true
        }
    }, 
    "msg": "Failed to find handler for \"~None/.ansible/tmp/ansible-tmp-1527009660.7-122004306651677/source\". Make sure the required command to extract the file is installed. Command \"/bin/tar\" could not handle archive. Command \"/usr/bin/unzip\" could not handle archive."
}

```

**Comment by sivel** [comment] 2018-05-22 17:43
Duplicate of https://github.com/ansible/ansible/issues/40483

**Closed as completed by sivel** 2018-05-22 17:43 UTC

**Comment by Guyverix** [comment] 2018-05-22 18:01
Sorry about the dupe.
