### ISSUE TITLE
Unexpected Exception: execv() arg 2 must contain only strings

### ISSUE THREAD

**Issue by jooadam** [ansible/ansible#13581] opened 2015-12-17 03:22 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 2.1.0
##### Ansible Configuration:

[ssh_connection]

ssh_args = ''
##### Environment:

Ubuntu 12.04 / Ubuntu 15.04
##### Summary:

Running a simple playbook with a debug task produces the error:

```
Unexpected Exception: execv() arg 2 must contain only strings
```
##### Steps To Reproduce:

```
[
    {
        "hosts": "all",
        "gather_facts": false,

        "tasks": [
            {
                "name":   "test",
                "action": "debug msg='Hello, stranger.'"
            }
        ]
    }
]

ansible-playbook playbook.json -i example.com,
```
##### Expected Results:

```
PLAY ***************************************************************************

TASK [test] ********************************************************************
ok: [example.com] => {
    "changed": false, 
    "msg": "Hello, stranger."
}

PLAY RECAP *********************************************************************
example.com              : ok=1    changed=0    unreachable=0    failed=0   
```
##### Actual Results:

```
PLAY ***************************************************************************

TASK [test] ********************************************************************
Unexpected Exception: execv() arg 2 must contain only strings
to see the full traceback, use -vvv
```

**Comment by jooadam** [comment] 2015-12-17 05:04
Note: this still works correctly in v2.0.0-0.7.rc2, must have been introduced since.

**Comment by pearofducks** [comment] 2015-12-17 09:27
+1

mine is `ansible 2.1.0 (devel d7f2f606e1) last updated 2015/12/17 10:25:14 (GMT +200)`

**Comment by Yannig** [comment] 2015-12-17 09:50
I'm enable to reproduce your issue with the following version:

```
ansible 2.1.0 (devel baece499df) last updated 2015/12/16 20:59:27 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 3c48320b29) last updated 2015/12/17 10:49:50 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 8ec4f95ffd) last updated 2015/12/17 10:49:50 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

**Comment by replicaJunction** [comment] 2015-12-17 16:30
I can also reproduce this issue, running on Mac OS X 10.11.

```
ansible 2.1.0 (devel 26bbabcfba) last updated 2015/12/17 10:21:26 (GMT -500)
  lib/ansible/modules/core: (detached HEAD 16a3bdaa7d) last updated 2015/12/17 09:51:17 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD 8ec4f95ffd) last updated 2015/12/17 09:51:23 (GMT -500)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

I receive the same error running an ad-hoc command:

```
$ ansible all -m ping
Unexpected Exception: execv() arg 2 must contain only strings
to see the full traceback, use -vvv
```

I'm pretty new to Ansible, though, so I could be doing something wrong.

**Comment by jimi-c** [comment] 2015-12-17 16:43
Could someone please provide me with an example inventory that helps reproduce this? I've tested against my inventory but do not see this error.

FWIW, this is a result of the ssh_known_hosts_redux branch I merged in last night, which pre-fetches known_hosts keys for hosts when host key checking is enabled. Disabling host key checking should be a temporary workaround for this, though I should be able to fix this quickly.

**Comment by bcoca** [comment] 2015-12-17 16:45
@jooadam  can you run with -vvv so we can see the full stacktrace?

**Comment by mscherer** [comment] 2015-12-17 16:46
Bisect say the issue is on e5c2c03dea09988 and digging a bit, the problem is on https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/connection/ssh.py#L67 where play_context.remote_addr is empty. ( ie None). 

I was able to reproduce on '-i someserver,' as well as a regular hosts file. See:

```
checkout/git/ansible $ ansible all -i hosts -m test
Unexpected Exception: execv() arg 2 must contain only strings
to see the full traceback, use -vvv
checkout/git/ansible $ cat hosts 
[foo]
www.manageiq.org
```

**Comment by mscherer** [comment] 2015-12-17 16:48
For the stacktrace:

```
$ ansible all -vvv -i hosts -m test
Using /home/misc/.ansible.cfg as config file
Unexpected Exception: execv() arg 2 must contain only strings
the full traceback was:

Traceback (most recent call last):
  File "/home/misc/checkout/git/ansible/bin/ansible", line 85, in <module>
    sys.exit(cli.run())
  File "/home/misc/checkout/git/ansible/lib/ansible/cli/adhoc.py", line 187, in run
    result = self._tqm.run(play)
  File "/home/misc/checkout/git/ansible/lib/ansible/executor/task_queue_manager.py", line 237, in run
    play_return = strategy.run(iterator, play_context)
  File "/home/misc/checkout/git/ansible/lib/ansible/plugins/strategy/linear.py", line 241, in run
    self._queue_task(host, task, task_vars, play_context)
  File "/home/misc/checkout/git/ansible/lib/ansible/plugins/strategy/__init__.py", line 156, in _queue_task
    ssh_conn.fetch_and_store_key(host, temp_pc)
  File "/home/misc/checkout/git/ansible/lib/ansible/plugins/connection/ssh.py", line 197, in fetch_and_store_key
    ssh_opts = get_ssh_opts(play_context)
  File "/home/misc/checkout/git/ansible/lib/ansible/plugins/connection/ssh.py", line 68, in get_ssh_opts
    res = subprocess.check_output(cmd)
  File "/usr/lib64/python2.7/subprocess.py", line 568, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings
```

**Comment by mscherer** [comment] 2015-12-17 16:49
And on irc, Jimmy mentionned a option, which fix things:

```
 $ cat hosts ; ansible all -vvv -i hosts -m test ; 
[foo]
www.manageiq.org ansible_ssh_host=www.manageiq.org
Using /home/misc/.ansible.cfg as config file
unknown option -- G
usage: ssh [-1246AaCfgKkMNnqsTtVvXxYy] [-b bind_address] [-c cipher_spec]
           [-D [bind_address:]port] [-E log_file] [-e escape_char]
           [-F configfile] [-I pkcs11] [-i identity_file]
           [-L [bind_address:]port:host:hostport] [-l login_name] [-m mac_spec]
           [-O ctl_cmd] [-o option] [-p port]
           [-Q cipher | cipher-auth | mac | kex | key]
           [-R [bind_address:]port:host:hostport] [-S ctl_path] [-W host:port]
           [-w local_tun[:remote_tun]] [user@]hostname [command]
www.manageiq.org | FAILED! => {
    "failed": true, 
    "msg": "ERROR! The module test was not found in configured module paths. Additionally, core modules are missing. If this is a checkout, run 'git submodule update --init --recursive' to correct this problem."
}
```

Now, the -G option is not working on RHEL 7.2, but a different problem.

**Comment by jimi-c** [comment] 2015-12-17 17:09
Ok, the above patch should fix this. Please let us know if you continue seeing problems with this.

**Closed as completed by jimi-c** 2015-12-17 17:09 UTC
Labels: P2, bug

**Comment by jimi-c** [comment] 2015-12-17 17:11
@mscherer just saw your comment above, that's a different bug :-/ We'll have to come up with another workaround for that.

**Comment by replicaJunction** [comment] 2015-12-17 17:14
The above patch works for me. Thanks very much!

**Comment by jooadam** [comment] 2015-12-17 17:34
Yeah, now I get the complaint about the G option, but otherwise it works, thanks!

**Comment by jimi-c** [comment] 2015-12-17 17:38
@jooadam is that on RHEL 7+ too?

**Comment by jooadam** [comment] 2015-12-17 17:39
Nope, it’s an Ubuntu 12.04.

**Comment by jimi-c** [comment] 2015-12-17 17:44
Ok, I have reverted the commits that led to this, and will revisit the known_host stuff later.
