### ISSUE TITLE
ansible-galaxy install should fail gracefully when a role's source changes but name stays the same

### ISSUE THREAD

**Issue by ches** [ansible/ansible#9744] opened 2014-12-08 12:03 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

1.8.2
##### Environment:

Control host: OS X, managed hosts: N/A
##### Summary:

`ansible-galaxy install` should gracefully tell a user to uninstall a role if it already exists on disk but he or she attempts to install it from a different `src`. This should return a non-zero exit code but not output a traceback.

The use case is, you have a role installed from Galaxy, and either:
- Something is fixed upstream, but the author hasn't tagged a version or refreshed Galaxy to know about the tag.
- You fork the role and fix it yourself, and want to use your fork while waiting on upstream to merge your fix.

In either case, you change the `src` of the role you had in `requirements.yml`, but leave the name the same so that you don't need to update the includes in any playbooks using it.
##### Steps To Reproduce:

This is a contrived example in that the two requirements files below actually install the same version of the role, but it does work to demonstrate the problem since the `src` changes. In reality the updated requirements file would be referring to some hotfix version or branch.

Install this `requirements.yml` with `ansible-galaxy install -r requirements.yml`

``` yaml
# Galaxy src
- src: neel.rundeck
  version: v0.0.7
```

But now you want to point to an interim fix—update the requirements as such:

``` yaml
- name: neel.rundeck
  src: https://github.com/New-Edge-Engineering/ansible-rundeck
  version: 214629ec0a94
```
##### Expected Results:

`ansible-galaxy install --ignore-errors -r requirements.yml` on the updated file above should inform the user that a role with the same name already exists and he or she should either change the name or `ansible-galaxy remove neel.rundeck` and try again.
##### Actual Results:

An ugly traceback:

```
$ ansible-galaxy install --ignore-errors -r roles/requirements.yml
- executing: git clone https://github.com/New-Edge-Engineering/ansible-rundeck neel.rundeck
- executing: git archive --prefix=neel.rundeck/ --output=/var/folders/rn/jn2hxmmx7csbzj1ft7j7f3v40000gn/T/tmptlnUri.tar 2a130cddfdf9d
Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/1.8.2/libexec/bin/ansible-galaxy", line 954, in <module>
    main()
  File "/usr/local/Cellar/ansible/1.8.2/libexec/bin/ansible-galaxy", line 948, in main
    fn(args, options, parser)
  File "/usr/local/Cellar/ansible/1.8.2/libexec/bin/ansible-galaxy", line 793, in execute_install
    tmp_file = scm_archive_role(role_scm, role_src, role.get("version"), role.get("name"))
  File "/usr/local/Cellar/ansible/1.8.2/libexec/bin/ansible-galaxy", line 383, in scm_archive_role
    shutil.rmtree(tempdir)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 66] Directory not empty: '/var/folders/rn/jn2hxmmx7csbzj1ft7j7f3v40000gn/T/tmp9ofBOz/neel.rundeck/.git'
```

**Comment by ches** [comment] 2014-12-08 12:31
`--ignore-errors` is looking overworked these days—IMO the above failed operation should return a non-zero status, but `--ignore-errors` makes it sound like that should basically never happen if it's specified.

For the use case of installing newly-added roles in a requirements file, you use:

```
$ ansible-galaxy install --ignore-errors -r requirements.yml
```

And to force some already existing roles to update to a version you've changed:

```
$ ansible-galaxy install --ignore-errors --force -r requirements.yml
```

Kind of long/ugly, not intention-revealing, and wasteful because it basically reinstalls everything whether you've changed a version or not. It'd be nice if there were an `ansible-galaxy update` subcommand:

```
# Automatically install any newly-added roles and skip existing ones. Don't require
# me to type --ignore-errors, this is a rather common procedure.
$ ansible-galaxy install -r requirements.yml

# Update roles with changed versions to the specified one, update roles with
# unspecified version to the latest, and install any newly-added roles:
$ ansible-galaxy update -r requirements.yml

# Update the named role to latest, or given version.
$ ansible-galaxy update some.role [optional version argument]
```

I have a feeling something like this has probably already been discussed or considered, but I'll file this as a separate request if desired.

**Comment by mpdehaan** [comment] 2014-12-08 21:54
I agree a traceback is almost always a bug.

I don't think the intent about --ignore-errors was ever to silence bugs in the operation, but probably just to coerce the RC on failed error paths.

We'll investigate, thanks!

**Comment by mpdehaan** [comment] 2014-12-08 21:54
I don't neccessarily agree that we should track the old source - I want to avoid writing a package manager.

An upgrade or replacement could be acceptable.

**Comment by jctanner** [comment] 2016-10-31 15:00
I am not able to reproduce the traceback with 1.8.2 ...

```
###################################
v1.8.2
###################################
- downloading role 'rundeck', owned by neel
- downloading role from https://github.com/New-Edge-Engineering/ansible-rundeck/archive/v0.0.7.tar.gz
- extracting neel.rundeck to roles/neel.rundeck
- neel.rundeck was installed successfully
- executing: git clone https://github.com/New-Edge-Engineering/ansible-rundeck neel.rundeck
- executing: git archive --prefix=neel.rundeck/ --output=/tmp/tmpEWiOLZ.tar 214629ec0a94
- extracting neel.rundeck to roles/neel.rundeck
- error: the specified role neel.rundeck appears to already exist. Use --force to replace it.
- neel.rundeck was NOT installed successfully.
## RC: 0
```

In 2.2 a slight different message appears ...

```
###################################
v2.2.0.0-0.4.rc4
###################################
- downloading role 'rundeck', owned by neel
- downloading role from https://github.com/New-Edge-Engineering/ansible-rundeck/archive/v0.0.7.tar.gz
- extracting neel.rundeck to roles/neel.rundeck
- neel.rundeck was installed successfully
- neel.rundeck is already installed, skipping.
## RC: 0
```

With the --force parameter added, the role is overwritten ...

```
###################################
v2.2.0.0-0.4.rc4
###################################
- downloading role 'rundeck', owned by neel
- downloading role from https://github.com/New-Edge-Engineering/ansible-rundeck/archive/v0.0.7.tar.gz
- extracting neel.rundeck to roles/neel.rundeck
- neel.rundeck was installed successfully
- extracting neel.rundeck to roles/neel.rundeck
- neel.rundeck was installed successfully
## RC: 0
```

Galaxy cli appears to behave as requested by this issue's description, so I'm closing it.

**Closed as completed by jctanner** 2016-10-31 15:00 UTC
Labels: affects_1.8, bug
