### ISSUE TITLE
include_tasks does not search relative to current file.

### ISSUE THREAD

**Issue by Testicule** [ansible/ansible#57107] opened 2019-05-29 07:11 UTC
##### SUMMARY

I have this:
      - include_tasks: "./by-name/snapshot-info-by-name.yml"
it fails, with this:
  reason: Could not find or access 'longpath_removed/playbooks/by-name/snapshot-info-by-name.yml' on the Ansible Controller.
It's suddenly looking relative to my playbooks directory, and can't even search the current dir?

I just give up.
Trying to develop anything in ansible is futile.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```
2.8.0
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Meh.

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by Testicule** [comment] 2019-05-29 07:48
This is just incredible.

**Comment by Akasurde** [comment] 2019-05-29 08:06
@Testicule Could you please provide playbook used with directory structure so that we can help ? Commenting randomly is not going to help.

**Comment by Testicule** [comment] 2019-05-29 08:08
I don't think i can put it any more simply than this:

I have a file"blah.yml".
it's using include_tasks to include another file, bar.yml, 
bar.yml is in a subdirectory "fu" of the dir that blah.yml is in.

so i have:
include_tasks: ./fu/bar.yml

Can't find it. 
Ansible goes off and looks in my playbooks dir.
Brilliant.

**Comment by Testicule** [comment] 2019-05-29 08:13
I could give you the directory structure which is large with a lot of files, because i am trying to reorganise a whole bunch of things that were working fine as tasks, into a role.

And suddenly the search paths of include_tasks is changing.
Now i have an include_tasks that cannot even search relative to its own file.

**Comment by Akasurde** [comment] 2019-05-29 08:16
Have you tried -

```yaml
    - include_tasks: "{{ playbook_dir }}/fu/bar.yml"
```

**Comment by Testicule** [comment] 2019-05-29 08:20
I can give it a full path relative to the tasks folder under the role, and that works.
But... why is that necessary?
The file i am trying to include is in a subdir relative to the file that is trying to include it.
So why can i not just use that relative path.

Surely include_tasks is supposed to search relative to the current file.

**Comment by Testicule** [comment] 2019-05-29 08:26
to be more specific, i have a role, "vm".
it has the usual "tasks" folder.
"tasks" has a subdir "01-vmware", which has subdir "jobs" which has subdir "by-name".
i have a file "snapshot-info.yml" in "jobs", which is trying to include a file in the subdir "by-name"

But when i do:
   include_tasks: ./by-name/somefile.yml
it fails to find it, and prints error message which makes it look as if the search path is only relative to my playbooks dir.

if I do:
  include_tasks: "01-vmware/jobs/by-name/somefile.yml"
it finds it.
But this should not be necessary. The shorter relative path "./by-name/somefile.yml" should find it.

**Comment by Testicule** [comment] 2019-05-29 08:29
BTW, i apologise to anyone who finds my bugreports offensive, but, this is just incredibly frustrating.

**Comment by Testicule** [comment] 2019-05-29 08:58
In my playbook, if i use include_tasks to directly load, with the full path to a task file "blah.yml" inside a role, and blah.yml does another include_task to bring in "./by-name/somefile.yml", it works - with the nice, short path (relative to the current file).

If, my playbook, instead of using include_tasks, uses "include_role", with the "tasks_from" clause, to load the blah.yml, then, in blah.yml the include_tasks:  "./by-name/somefile.yml" now fails.

I might expect some of the search paths to change, when used via a role or not, but, surely searching relative to the current file is the most obvious place to search, in all instances...

How can include_tasks not search relative to the current file, *at all*, when used within a role?

It's just unbelievable.

**Comment by Testicule** [comment] 2019-05-29 10:10
There should be no need to point out that using the shortest relative path possible is the most robust way to do it.

If i specify the path to file as ./blah/somefile.yml, i can move the parent dirs around, and all these relative paths are still valid.

So, why should i have to specify "01-vmware/jobs/by-name/somefile"? If i decide i want to rename 01-vmwre to just vmware, suddenly i have to fix all these includes in lower-level files, which shouldn't care that their parent dir was renamed. Its unnecessarily fragile.

So why is include_tasks not searching relative to the current file when i use it...

**Comment by Testicule** [comment] 2019-05-29 11:27
Here we go:

Playbook:
- hosts: "{{ hostgroups }}"
  tasks:
    - name: "Include_tasks ./roles/vm/tasks/jobs/jobs.yml directly. Great, super, this works."
      include_tasks: ./roles/vm/tasks/jobs/jobs.yml
    - name: "Include vm role, with tasks_from jobs/jobs.yml."
      include_role:
        name: vm
        tasks_from: jobs/jobs.yml

roles/vm/tasks/main.yml:
- name: "main.yml: include_tasks ./jobs/jobs.yml"
  include_tasks: ./jobs/jobs.yml

roles/vm/tasks/jobs/jobs.yml:
- name: "jobs.yml: include_tasks ./meh/meh.yml"
  include_tasks: ./meh/meh.yml

roles/vm/tasks/jobs/meh/meh.yml:
- name: "meh.yml: Meh"
  debug:
    msg: "Meh"

That's all it takes to replicate the error.

Running that playbook yields:

ansible-playbook -i ./inventory-vorpal.yml ./vorpal-00-role-test.yml --extra-vars='{"hostgroups":"voltaire"}'

PLAY [voltaire] *****************************************************************************************************************************************************************************

TASK [Include_tasks ./roles/vm/tasks/jobs/jobs.yml directly. Great, super, this works.] *****************************************************************************************************
included: /mnt/somehost/awx/projects/vorpal/roles/vm/tasks/jobs/jobs.yml for voltaire

TASK [jobs.yml: include_tasks ./meh/meh.yml] ************************************************************************************************************************************************
included: /mnt/somehost/awx/projects/vorpal/./roles/vm/tasks/jobs/./meh/meh.yml for voltaire

TASK [meh.yml: Meh] *************************************************************************************************************************************************************************
ok: [voltaire] =>
  msg: Meh

TASK [Include vm role, with tasks_from jobs/jobs.yml.] *********************************************************************************************************************************************************************

TASK [vm : jobs.yml: include_tasks ./meh/meh.yml] *******************************************************************************************************************************************
fatal: [voltaire]: FAILED! =>
  reason: Could not find or access '/mnt/somehost/awx/projects/vorpal/meh/meh.yml' on the Ansible Controller.

PLAY RECAP **********************************************************************************************************************************************************************************
voltaire                   : ok=3    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by Testicule** [comment] 2019-05-29 11:36
if you comment out the "tasks_from: jobs/jobs.yml", so we go into the role at main.yml, which then includes jobs.yml, we get this, which is great. It all works:

ansible-playbook -i ./inventory-vorpal.yml ./vorpal-00-role-test.yml --extra-vars='{"hostgroups":"voltaire"}'

PLAY [voltaire] *****************************************************************************************************************************************************************************

TASK [Include_tasks ./roles/vm/tasks/jobs/jobs.yml directly. Great, super, this works.] *****************************************************************************************************
included: /mnt/somehost/awx/projects/vorpal/roles/vm/tasks/jobs/jobs.yml for voltaire

TASK [jobs.yml: include_tasks ./meh/meh.yml] ************************************************************************************************************************************************
included: /mnt/somehost/awx/projects/vorpal/./roles/vm/tasks/jobs/./meh/meh.yml for voltaire

TASK [meh.yml: Meh] *************************************************************************************************************************************************************************
ok: [voltaire] =>
  msg: Meh

TASK [Include vm role, going in via main.yml.] ************************************************************************************************************************

TASK [vm : main.yml: include_tasks ./jobs/jobs.yml] *****************************************************************************************************************************************
included: /mnt/somehost/awx/projects/vorpal/roles/vm/tasks/./jobs/jobs.yml for voltaire

TASK [vm : jobs.yml: include_tasks ./meh/meh.yml] *******************************************************************************************************************************************
included: /mnt/somehost/awx/projects/vorpal/roles/vm/tasks/jobs/meh/meh.yml for voltaire

TASK [vm : meh.yml: Meh] ********************************************************************************************************************************************************************
ok: [voltaire] =>
  msg: Meh

PLAY RECAP **********************************************************************************************************************************************************************************
voltaire                   : ok=6    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

So the problem is clearly caused by using tasks_from, to jump to a file inside the role. But there is no reason why this should cause my include_tasks to fail. 

This is a bug.

**Comment by Akasurde** [comment] 2019-05-29 13:41
Reproducer - https://github.com/Akasurde/ansible-reproducers/tree/master/57107

**Comment by bcoca** [comment] 2019-05-29 13:52
closing as dupe of #57013

**Closed by bcoca** 2019-05-29 13:52 UTC
Labels: affects_2.8, bug, needs_triage, support:core

**Comment by Testicule** [comment] 2019-05-29 14:26
There are some similarities i guess but I'm not convinced this is a dupe of #57013.

Sam Doran said, of #57013:

"This is due to the same task file name being present at the role root and adjacent to the task file with the import_tasks task."

That is not the case here.
I am not seeing a file get included twice, I'm seeing a file *fail* to be included even once.

**Comment by bcoca** [comment] 2019-05-29 14:40
the issue is the same at root, you are using relative paths in a subdir and expecting a different path resolution,  his case happens to have a file with the same name doing an import which triggers the 2nd use, that is the main difference between your issues, but the cause is the same.

**Comment by Testicule** [comment] 2019-05-29 14:48
Ok, well, I'm glad someone is ontop of this.
Pls resolve asap.

And pls god just strike down upon me with great vengeance and furious anger before inflicting anymore of these ansible bugs upon me i can't take it anymore i just want to do some simple things in ansible pls, that's all have mercy upon me just let me get some work done, or end it all for me.

**Comment by Testicule** [comment] 2019-05-29 14:56
And i suppose in the meantime if i roll back to something before 2.7.10 i can hope this bug goes away.

**Comment by Testicule** [comment] 2019-05-29 15:03
Ansible 2.6.5 no good.

**Comment by Testicule** [comment] 2019-05-29 15:33
that's it.
i am done.

**Comment by Testicule** [comment] 2019-05-29 15:36
I'll be quitting my job and walking slowly into the ocean.
it's over.
