### ISSUE TITLE
Roles being ignored when executed against different hosts in different plays

### ISSUE THREAD

**Issue by jamiehannaford** [ansible/ansible#11514] opened 2015-07-07 15:07 UTC
I have a playbook with two plays in it, each addresses a different host group:

``` yaml
- name: Configure host1
  hosts: host1
  remote_user: root
  roles:
    - { role: nginx }
    - { role: php-fpm }
    - { role: magento, is_admin: True }

- name: Configure host2
  hosts: host2
  remote_user: root
  roles:
    - { role: nginx }
    - { role: php-fpm }
    - { role: magento, is_admin: False }
```

I've omitted the `vars` section, which contain different values for each play. 

I expect the `nginx` and `php-fpm` roles to be executed against the `host2` group, but right now they're being ignored. The `magento` role is run on the second host, though, which leads me to think that it does so because there's a different val passed in for `is_admin`. 

How do I get the second set of roles to run?

**Comment by jimi-c** [comment] 2015-07-08 01:03
@jamiehannaford what version of Ansible are you executing this against? This seems to be a role-deduplication issue. If you're not running against the current devel, could you?

**Comment by jimi-c** [comment] 2015-07-08 01:08
@jamiehannaford nevermind, I can reproduce this with a simple set of roles on the devel branch.

**Comment by jimi-c** [comment] 2015-07-08 01:48
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2015-07-08 01:48 UTC
Labels: P1, bug
