### ISSUE TITLE
--user command line option does not override "ansible_ssh_user" in var/playbook files

### ISSUE THREAD

**Issue by pfalcon** [ansible/ansible#7841] opened 2014-06-19 16:22 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 1.6.2
```
##### Environment:

Ubuntu 12.04
##### Summary:

It's both well documented and intuitive that vars passed on command line with --extra-vars, override any values set in playbook. It would be just as natural to expect that --user=, if given on command line, overrides `ansible_ssh_user` as set in playbook, but that's not what happens. Instead, --user= value is ignored, and `ansible_ssh_user` from playbook prevails.
##### Steps To Reproduce:

In our usecase, we want to use static user like "vagrant" or "ubuntu" for development hosts (Vagrant VMs or Ubuntu EC2) by default, but use individual user auth for production. So, someone would not pass --user= for devel hosts, and default user would be used, and pass explicit --user only if needed.
##### Actual Results:

See above.

**Comment by cashell** [comment] 2015-07-24 16:47
I just got bit by this, too, and spent an hour trying to figure out why it wasn't working.  I agree completely with the submitter.  Command line options should almost always override config file options.  This is the expected behavior across most commands.

**Comment by cashell** [comment] 2015-07-24 17:41
I found a work-around.  It appears that Ansible is just very inconsistent in deciding which command line options it will use to override file configured options.  For this particular case, using the `-u/--user` option will be ignored in favor of inventory options.  However, Passing the `ansible_ssh_user` via `-e` (`-e ansible_ssh_user=foo`) will result in the expected outcome.

This kind of inconsistency is guaranteed to trip up users.

**Comment by bcoca** [comment] 2016-09-08 19:42
Just to clarify, command line options override config file (ansible.cfg) but not inventory data (ansible_user) nor playbook directives (remote_user).

**Comment by jimi-c** [comment] 2016-09-08 19:44
Hi @pfalcon (and @cashell), sorry for the late follow-up on this. As @bcoca noted above, inventory values have always overridden connection values such as this. This has been a long-standing design choice in Ansible, so we will close this issue now.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2016-09-08 19:44 UTC
Labels: bug

**Comment by mprinc** [comment] 2018-10-15 15:16
Sorry guys, but I am really disappointed with your response on this matter :( You even locked this issue for the same user complains :( https://github.com/ansible/ansible/issues/4622

What @jimi-c and @bcoca are constantly insisting on, is rather backing up that "ansible is INNOCENT!!!" It is NOT about that!? It is about the USER-expected behavior. And users are not happy, confused, etc. You do not need to defend yourselves ... defend customer satisfaction!

Look, users are saying that it is not properly explained, there, and there, ... NO MENTION, of that normal behavior that you are insisting on. 

If what you saying is really true (and code is obviously proving that) why it is not EVER mentioned where CLI arguments are presented?! Here is the main CLI document [Working with Command Line Tools](https://docs.ansible.com/ansible/latest/user_guide/command_line_tools.html) or for the tool [ansible-playbook](https://docs.ansible.com/ansible/latest/cli/ansible-playbook.html), right? Not mentioned there :( 👎
