### ISSUE TITLE
ansible-galaxy install does not work

### ISSUE THREAD

**Issue by lowks** [ansible/ansible#17534] opened 2016-09-13 05:06 UTC
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

ansible-galaxy
##### ANSIBLE VERSION

```
master (2.2.0)
```
##### OS / ENVIRONMENT

mac, Linux
##### SUMMARY

ansible-galaxy install -r requirements.yml fails.
##### STEPS TO REPRODUCE

```
ansible-galaxy install -r requirements.yml
```

##### EXPECTED RESULTS

It will install the roles in requirements.yml file.
##### ACTUAL RESULTS

```
(ansible) ~/P/c/ansible-role-django-app ❯❯❯ ~/miniconda2/envs/ansible/bin/ansible-galaxy install -r requirements.yml             master
Usage: ansible-galaxy install [options] [-r FILE | role_name(s)[,version] | scm+role_repo_url[,version] | tar_file(s)]

Options:
  -f, --force           Force overwriting an existing role
  -h, --help            show this help message and exit
  -c, --ignore-certs    Ignore SSL certificate validation errors.
  -i, --ignore-errors   Ignore errors and continue with the next specified
                        role.
  -n, --no-deps         Don't download roles listed as dependencies
  -r ROLE_FILE, --role-file=ROLE_FILE
                        A file containing a list of roles to be imported
  -p ROLES_PATH, --roles-path=ROLES_PATH
                        The path to the directory containing your roles. The
                        default is the roles_path configured in your
                        ansible.cfg file (/etc/ansible/roles if not
                        configured)
  -s API_SERVER, --server=API_SERVER
                        The API server destination
  -v, --verbose         verbose mode (-vvv for more, -vvvv to enable
                        connection debugging)
  --version             show program's version number and exit
ERROR! - please specify a user/role name, or a roles file, but not both
```

**Comment by bitmensch** [comment] 2016-09-13 07:55
I can see the same issue, and it looks like this has been introduced in the last 24 hours. Prior to this everything worked fine.

One of my nightly builds (which also runs `ansible-galaxy` from `ansible@devel`) failed around two hours ago, showing the same error message:
https://travis-ci.org/goodplay/goodplay/jobs/159504690#L520

Not sure about the root cause yet, but it might be related to commit bf2996194.

**Comment by martbhell** [comment] 2016-09-14 06:00
My last working test used this commit: f4af154beff2b281e464b616f504293d67187da5

**Comment by jladdjr** [comment] 2016-09-14 14:09
Have a duplicate issue open against ansible-galaxy (https://github.com/ansible/galaxy-issues/issues/191). git bisect identified [this commit](https://github.com/ansible/ansible/commit/bf2996194716c7d58b9b543603c2d917e3eac060) as introducing the issue.

**Comment by abadger** [comment] 2016-09-14 18:50
Okay, fix merged to devel.

**Closed as completed** 2016-09-14 18:49 UTC
Labels: P1, affects_2.2, bug
