### ISSUE TITLE
UnboundLocalError exception in ansible/utils/template.py

### ISSUE THREAD

**Issue by obormot** [ansible/ansible#5563] opened 2014-01-09 22:26 UTC
v1.4.4

This seems like a simple coding error, the exception handler only re-raises when a certain condition is met (if 'StrictUndefined' in str(te)), but when it's not then `res` stays undefined and crashes the app. 

```
fatal: [127.0.0.1] => Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ansible/runner/__init__.py", line 394, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/lib/python2.7/site-packages/ansible/runner/__init__.py", line 485, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/local/lib/python2.7/site-packages/ansible/runner/__init__.py", line 679, in _executor_internal_inner
    module_args = template.template(self.basedir, module_args, inject, fail_on_undefined=self.error_on_undefined_vars)
  File "/usr/local/lib/python2.7/site-packages/ansible/utils/template.py", line 319, in template
    varname = template_from_string(basedir, varname, vars, fail_on_undefined)
  File "/usr/local/lib/python2.7/site-packages/ansible/utils/template.py", line 543, in template_from_string
    return res
UnboundLocalError: local variable 'res' referenced before assignment
```

**Comment by mpdehaan** [comment] 2014-01-09 22:50
Can you please include steps (such as a template or playbook) to reproduce this problem?

**Comment by lichesser** [comment] 2014-01-10 08:40
#5566 looks related to this

**Comment by obormot** [comment] 2014-01-10 22:48
Here is how you reproduce. When you remove the `| bool` part the exception doesn't happen.

```
- hosts: localhost
  tasks:
  - shell: echo 'hi there'
    register: echo_out

  - shell: echo 'foo'
    when: "{{ 'there' in echo_out.stdout | bool }}"
```

**Comment by mpdehaan** [comment] 2014-01-17 20:45
Since we have the other ticket open, I'm going to link these two tickets and close this one, we can still find this thread from the other.

Thanks!

**Closed as completed by mpdehaan** 2014-01-17 20:45 UTC
Labels: needs_info, bug
