### ISSUE TITLE
Fix installation into virtualenv

### ISSUE THREAD

**Issue by yarikoptic** [ansible/ansible#7092] opened 2014-04-21 14:14 UTC
##### Issue Type:

“Bug Report”
##### Ansible Version:

v1.5.1-1155-gf09c0c7
##### Environment:

Debian mix of unstable/testing
##### Summary:

There was https://github.com/ansible/ansible/pull/1509 some time ago which presumably resolved similar issues before. Trying in current devel (v1.5.1-1155-gf09c0c7):

```
$> mkdir venv; virtualenv venv
New python executable in venv/bin/python
Installing Setuptools..............................................................................................................................................................................................................................done.
Installing Pip.....................................................................................................................................................................................................................................................................................................................................done.
$> venv/bin/python setup.py install
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
running build_scripts
running install_lib
creating /home/yoh/proj/misc/ansible/venv/lib/python2.7/site-packages/ansible
...
running install_scripts
copying build/scripts-2.7/ansible-doc -> /home/yoh/proj/misc/ansible/venv/bin
copying build/scripts-2.7/ansible-vault -> /home/yoh/proj/misc/ansible/venv/bin
copying build/scripts-2.7/ansible -> /home/yoh/proj/misc/ansible/venv/bin
copying build/scripts-2.7/ansible-pull -> /home/yoh/proj/misc/ansible/venv/bin
copying build/scripts-2.7/ansible-playbook -> /home/yoh/proj/misc/ansible/venv/bin
copying build/scripts-2.7/ansible-galaxy -> /home/yoh/proj/misc/ansible/venv/bin
changing mode of /home/yoh/proj/misc/ansible/venv/bin/ansible-doc to 755
changing mode of /home/yoh/proj/misc/ansible/venv/bin/ansible-vault to 755
changing mode of /home/yoh/proj/misc/ansible/venv/bin/ansible to 755
changing mode of /home/yoh/proj/misc/ansible/venv/bin/ansible-pull to 755
changing mode of /home/yoh/proj/misc/ansible/venv/bin/ansible-playbook to 755
changing mode of /home/yoh/proj/misc/ansible/venv/bin/ansible-galaxy to 755
running install_data
copying ./library/utilities/accelerate -> /usr/share/ansible/utilities
error: could not delete '/usr/share/ansible/utilities/accelerate': Permission denied
```

still tries to deal with '/usr/share'
##### Steps To Reproduce:

see above

**Comment by retrogradeorbit** [comment] 2014-06-30 09:08
The problems extend deeper than this, too. Even when I removed the references to /usr/share from the installer (and changed them to a local path) and then installed into a virtualenv, it appeared to succeed, but the binaries don't work and the library can't be found from the virtual python.

```
$ vp/bin/ansible
Traceback (most recent call last):
  File "vp/bin/ansible", line 10, in <module>
    execfile(__file__)
  File ".../vp/src/ansible/bin/ansible", line 25, in <module>
    from ansible.runner import Runner
ImportError: No module named ansible.runner
```

and

```
$ vp/bin/python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ansible
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named ansible
```

**Comment by claco** [comment] 2014-11-09 03:11
Just here to add that this is still an issue for me with the latest devel on OSX.

I've tried installing ansible 3 different ways to test this:
1. Working: Clone from github. source hacking setup-env. Pip install into system python. 
2. Working: Clone from github. source hacking setup-env. Create venv. Source venv. Pip install into venv.
3. Broken: Create venv. Source venv. Pip install into venv.

The last method yields an ansible, ansible-galaxy, and ansible-vault commands that stack trace with:

```
 → ansible
Traceback (most recent call last):
  File "/Users/claco/Projects/racker.ninja/.venv/bin/ansible", line 10, in <module>
    execfile(__file__)
  File "/Users/claco/Projects/racker.ninja/.venv/src/ansible/bin/ansible", line 25, in <module>
    from ansible.runner import Runner
ImportError: No module named ansible.runner

 → ansible-galaxy
Traceback (most recent call last):
  File "/Users/claco/Projects/racker.ninja/.venv/bin/ansible-galaxy", line 10, in <module>
    execfile(__file__)
  File "/Users/claco/Projects/racker.ninja/.venv/src/ansible/bin/ansible-galaxy", line 42, in <module>
    import ansible.constants as C
ImportError: No module named ansible.constants

 → ansible-vault
Traceback (most recent call last):
  File "/Users/claco/Projects/racker.ninja/.venv/bin/ansible-vault", line 10, in <module>
    execfile(__file__)
  File "/Users/claco/Projects/racker.ninja/.venv/src/ansible/bin/ansible-vault", line 28, in <module>
    import ansible.constants as C
ImportError: No module named ansible.constants
```

Oddly, ansible-playbook works just fine, as do all of the modules I'm using from within the now external submodules for core/extras.

**Comment by rgbkrk** [comment] 2014-11-13 22:34
Yup.

**Comment by sivel** [comment] 2014-11-14 01:29
FWIW, I cannot duplicate this.  I just pip installed 1.8 via the following command inside of a venv, and everything works as expected:

```
pip install git+https://github.com/ansible/ansible.git@devel#egg=ansible
```

All commands work as expected.

**Comment by sivel** [comment] 2014-11-14 01:40
Ok, scratch that.  I can duplicate this when adding `-e` to pip.  It appears as though `ansible-playbook` works as a result of the following lines https://github.com/ansible/ansible/blob/devel/bin/ansible-playbook#L28-L34

This was only added to `ansible-playbook` and not the other bin files in https://github.com/ansible/ansible/commit/44b9f5e752b6f66a2450a5ec3c5c2625cefa6a14

**Comment by claco** [comment] 2014-11-14 01:48
Hurray! E_NOT_CRAY

**Comment by mdarby** [comment] 2015-04-03 14:47
I love running into the same bugs as coworkers.

**Comment by sivel** [comment] 2015-06-19 16:21
I have tested this with the devel branch and the current stable-1.9 branch and can no longer reproduce the issue.  This is can be closed.

**Comment by rgbkrk** [comment] 2015-06-19 16:31
I'm going to miss this watercooler if it's fixed now.

**Comment by bcoca** [comment] 2015-06-19 16:35
@rgbkrk I'll open koolaid stand instead, but closing this bug since it has been declared fixed

**Closed as completed by bcoca** 2015-06-19 16:35 UTC
Labels: bug
