### ISSUE TITLE
Copy module with recursive - empty dirs not copied over

### ISSUE THREAD

**Issue by edrozenberg** [ansible/ansible#10567] opened 2015-03-28 19:25 UTC
ansible 1.9.0.1 Mac OSX controlling Slackware Linux hosts

The copy module does not copy over empty directories. 
Directories that contain at least one file do get copied.

For ex this copy task:

```
# Copy skel files to skel
- name: aws copy skel files
  copy: >
    src=etc/skel/aws/
    dest={{ conf_skel_dir }}/.aws/
    owner=root group=root 
    mode=0600 directory_mode=0700
    force=yes
```

**Comment by abadger** [comment] 2015-03-30 17:52
Reproduced with a corrected playbook:

```
---
- hosts: localhost
  tasks:
    - copy:
        src: /var/tmp/roles
        dest: /var/tmp/mine/
```

Note: i would not expect it to work if the src has a trailing slash (as that denotes that the files inside of the directory are supposed to be copied rather than the directory itself.)

**Comment by edrozenberg** [comment] 2015-03-30 18:24
The reason I had a trailing slash on the source is I'm specifically trying to copy contents of directory aws to the directory .aws (achieving a kind of directory 'rename') - I'd expect all contents of source dir/ to be copied including any empty directories inside source dir/ - I consider the empty directories to be contents, not just the files.

**Comment by abadger** [comment] 2015-03-30 18:26
Ohhh.... I misunderstood.  /etc/skel/aws is not empty.  It just contains empty directories.  Is that correct?

**Comment by edrozenberg** [comment] 2015-03-30 18:29
That's exactly right, I wasn't clear in my original post.

```
src=etc/skel/aws/
```

Contents of src dir for example:
- myfile.txt
- mydir (empty)
- otherdir (not empty)
- other.stuff

The mydir (empty) would not get copied during the recursive copy of the source contents.
But the otherdir (notempty) DOES get copied.

**Comment by abadger** [comment] 2015-03-30 23:32
this is basically the same problem as here: https://github.com/ansible/ansible/issues/5005 mpdehaan wanted copy to be about copying files and left copying empty directories to other modules like synchronize.  I'd have to stare at the code for a while longer to know why but I suspect it has to do with an ambiguity with telling the difference between making a remote directory into a copy of the local directory and placing a copy of the local directory into the remote directory.

**Comment by edrozenberg** [comment] 2015-03-30 23:45
Thanks - that https://github.com/ansible/ansible/issues/5005 looks like the same issue.
One of the comments there:

"copy is intended to copy files only.". But it will do a recursive copy. So it is copying dirs but only when they have stuff in them. That is not really intuitive behavior. It should copy empty dirs.

I agree - if it is doing a recursive copy it should do everything, empty or not.
If it is NOT a recursive copy, then it should skip all directories empty or not.
The behavior that only empty dirs get skipped doesn't match my experience
with any other tool or command line.

**Comment by njia** [comment] 2015-04-23 02:12
@edrozenberg totally agree and what about empty files ? If it copies empty files and it should copy empty directories.

**Comment by bcoca** [comment] 2015-04-23 02:51
closing this as dupe of #5005, the syncronize module is a better choice to copy a tree structure.

**Closed as completed by bcoca** 2015-04-23 02:51 UTC
Labels: bug
