### ISSUE TITLE
multi level includes - copy/template can't find file in /files

### ISSUE THREAD

**Issue by zshamrock** [ansible/ansible#13671] opened 2015-12-25 18:39 UTC
##### Issue Type:
- Bug Report
##### Ansible Version:

1.9.4
##### Ansible Configuration:

Default
##### Environment:

Debian 8.2 (jessie)
##### Summary:

See the project structure below
##### Steps To Reproduce:

I have the following project structure:

```
roles/
  local/
    files/
      .vim/
    tasks/
      main.yml [1]
      system/
        main.yml [2]
        vim.yml
```

[1] main.yml has content:
`- include: system/main.yml tags=system`

[2] main.yml has content:
`- include: vim.yml`

vim.yml has a copy task, like this one:

```
- name: ...
  copy: src=.vim dest=...
```
##### Expected Results:

When I run: `ansible-playbook site.yml -i hosts` I expect `copy` module is able to understand that `.vim` is inside `files/` directory, and copy it into the destination, as it has worked fine before I moved `vim.yml` into `system` subdirectory.
##### Actual Results:

It fails with the following error:

```
TASK: [local | copy .vim] ***************************************************** 
fatal: [127.0.0.1] => input file not found at /home/alex/dev/automation/roles/local/tasks/files/.vim or /home/alex/dev/automation/.vim
```

As you can see ansible tries to search for `local/tasks/files` instead of `local/files`.

P.S.1: As a workaround I can use `{{ role_path }}/files/.vim` as `src` for `copy`, but this is the reason for the layout for not prefix the resources inside `files`.

P.S.2: Same is true for `template` module as well.

**Comment by bcoca** [comment] 2015-12-28 15:55
this should be already fixed in 2.0/devel, but keeping this open in case we can fix it in 1.9.5

**Comment by yew011** [comment] 2016-01-11 17:31
Do not mean to hijack this thread, but I have similar issue
with `ansible 2.0.0-0.9.rc4_1` on my mac.

Please let me know if this should be opened in a new issue.

My roles layout is:

```
├── roles
│   ├── docker-service
│   │   ├── tasks
│   │   │   └── docker-service.yml
│   │   └── templates
│   │       └── docker.service.j2
│   ├── kafka
│   │   └── tasks
│   │       └── main.yml
│   └── zookeeper
│       └── tasks
│           └── main.yml
```

The **zookeeper/kafka** playbook, all include the `docker-service.yml` via:

```
- include: ../../docker-service/tasks/docker-service.yml
  vars:
    systemd_service_name: zookeeper
```

And in the docker-service playbook, it adds the systemd service file:

```
- name: adds {{ systemd_service_name }}.service files
  template:
    src: docker.service.j2
    dest: "/etc/systemd/system/{{ systemd_service_name }}.service"
    owner: root
    group: root
    mode: 0644
```

The problem is, when running, the **docker-service** playbook cannot find the
template file from `docker-service/templates/`.  And reports this error.

```
failed: [example] => (item=zookeeper) => {"failed": true, "item": "zookeeper", "msg": "IOError: [Errno 2] No such file or directory: u'/Users/alexw/tmp/projectname/docker.service.j2'"}
```

The same playbook works on Ansible 1.9.2.

Thanks,
Alex Wang,

**Comment by gtback** [comment] 2016-01-22 17:02
I'm having the same issue as @yew011 : When a tasks file from one role includes a task file from another role, any file paths (for example, the `src` parameter in the `template` module is taken relative to the _including_ task file, not the _included_ task file).

EDIT: Nevermind, #13818 is a better explanation of my issue.

**Comment by bcoca** [comment] 2016-02-12 14:15
dupe of #13818

**Closed as completed by bcoca** 2016-02-12 14:15 UTC
Labels: bug
