### ISSUE TITLE
Ansible vault fails to write to stdout (in 2.3.0)

### ISSUE THREAD

**Issue by zellio** [ansible/ansible#24791] opened 2017-05-18 20:23 UTC
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ansible-vault

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Feb 11 2017, 12:22:40) [GCC 6.3.1 20170109]
```

##### CONFIGURATION
None

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Ansible vault no longer writes to stdout correctly.

##### STEPS TO REPRODUCE

```sh
$ echo secret | ansible-vault encrypt --vault-password-file=~/.vault_password_file --output=-
```

##### EXPECTED RESULTS
```
$ANSIBLE_VAULT;1.1;AES256
37633461343236623465393564643231623135316432653433333663653262336633356261393433
6135343866303138623931303030343635616331393664650a663233383839356430623338376332
61666238356539323562373538376133626265363234343264633565666332646331366130363766
6533353966343463340a623562366464383334663066376461366536633764393761643635656261
3736
Encryption successful
```
##### ACTUAL RESULTS
```
ERROR! [Errno 2] No such file or directory: '/home/notroot/-'
```

**Comment by sivel** [comment] 2017-05-18 20:47
Closing as a duplicate of the already resolved https://github.com/ansible/ansible/pull/23583 

The referenced fix will be included in a upcoming 2.3.1 release

**Closed as completed** 2017-05-18 20:47 UTC
