### ISSUE TITLE
Failed to resolve remote temporary directory on groups

### ISSUE THREAD

**Issue by dasJ** [ansible/ansible#14465] opened 2016-02-13 22:11 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

Using default ansible.cfg.

Inventory:

```
[all:vars]
ansible_python_interpreter=/usr/bin/python2

[kubernetes]
kubemaster1 ansible_ssh_host=192.168.0.150
kubemaster2 ansible_ssh_host=192.168.0.220
kubenode1 ansible_ssh_host=192.168.0.157
kubenode2 ansible_ssh_host=192.168.0.73
```
##### Environment:

Arch Linux (up to date) on all machines.
##### Summary:

When using any module (I'm using `ping` for testing), Ansible sometimes fails on a host. It never happens when I use one single host and it fails in about 8/10 cases. The failing hosts are differing.

I'm calling Ansible like this:

```
ansible -vvvv -e 'ansible_ssh_user=root' kubernetes -m ping
```

Full log output of a failed run:

```
Using /etc/ansible/ansible.cfg as config file
Loaded callback minimal of type stdout, v2.0
<192.168.0.220> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.0.150> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.0.220> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o
ConnectTimeout=10 -o ControlPath=/home/janne/.ansible/cp/ansible-ssh-%h-%p-%r -tt 192.168.0.220 'mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1455401136.3-129748284741880 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1455401136.3-129748284741880 )"'
<192.168.0.150> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o
ConnectTimeout=10 -o ControlPath=/home/janne/.ansible/cp/ansible-ssh-%h-%p-%r -tt 192.168.0.150 'mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1455401136.3-110669559663006 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1455401136.3-110669559663006 )"'
<192.168.0.73> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.0.157> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.0.73> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/janne/.ansible/cp/ansible-ssh-%h-%p-%r -tt 192.168.0.73 'mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1455401136.32-132910215829706 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1455401136.32-132910215829706 )"'
<192.168.0.220> PUT /tmp/janne/tmpqd8UFn TO /root/.ansible/tmp/ansible-tmp-1455401136.3-129748284741880/ping
<192.168.0.220> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/janne/.ansible/cp/ansible-ssh-%h-%p-%r '[192.168.0.220]'
<192.168.0.157> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o
ConnectTimeout=10 -o ControlPath=/home/janne/.ansible/cp/ansible-ssh-%h-%p-%r -tt 192.168.0.157 'mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1455401136.32-263198601926357 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1455401136.32-263198601926357 )"'
<192.168.0.150> PUT /tmp/janne/tmpvvf2uM TO /root/.ansible/tmp/ansible-tmp-1455401136.3-110669559663006/ping
<192.168.0.150> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/janne/.ansible/cp/ansible-ssh-%h-%p-%r '[192.168.0.150]'
kubenode2 | FAILED! => {
    "failed": true,
    "msg": "ERROR! failed to resolve remote temporary directory from ansible-tmp-1455401136.32-132910215829706: `mkdir -p \"$( echo $HOME/.ansible/tmp/ansible-tmp-1455401136.32-132910215829706 )\" && echo \"$( echo $HOME/.ansible/tmp/ansible-tmp-1455401136.32-132910215829706 )\"` returned empty string"
}
<192.168.0.220> ESTABLISH SSH CONNECTION FOR USER: root
kubenode1 | FAILED! => {
    "failed": true,
    "msg": "ERROR! failed to resolve remote temporary directory from ansible-tmp-1455401136.32-263198601926357: `mkdir -p \"$( echo $HOME/.ansible/tmp/ansible-tmp-1455401136.32-263198601926357 )\" && echo \"$( echo $HOME/.ansible/tmp/ansible-tmp-1455401136.32-263198601926357 )\"` returned empty string"
}
<192.168.0.220> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o
ConnectTimeout=10 -o ControlPath=/home/janne/.ansible/cp/ansible-ssh-%h-%p-%r -tt 192.168.0.220 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1455401136.3-129748284741880/ping; rm -rf "/root/.ansible/tmp/ansible-tmp-1455401136.3-129748284741880/" > /dev/null 2>&1'
<192.168.0.150> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.0.150> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o
ConnectTimeout=10 -o ControlPath=/home/janne/.ansible/cp/ansible-ssh-%h-%p-%r -tt 192.168.0.150 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1455401136.3-110669559663006/ping; rm -rf "/root/.ansible/tmp/ansible-tmp-1455401136.3-110669559663006/" > /dev/null 2>&1'
kubemaster2 | SUCCESS => {
    "changed": false,
    "invocation": {
        "module_args": {
            "data": null
        },
        "module_name": "ping"
    },
    "ping": "pong"
}
kubemaster1 | SUCCESS => {
    "changed": false,
    "invocation": {
        "module_args": {
            "data": null
        },
        "module_name": "ping"
    },
    "ping": "pong"
}
```

Note that different hosts fail sometimes.
##### Steps To Reproduce:

Run the command above on a small group of Arch Linux hosts. Sometimes, it fails.
##### Expected Results:

```
Using /etc/ansible/ansible.cfg as config file
Loaded callback minimal of type stdout, v2.0
<192.168.0.157> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.0.150> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.0.157> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o
ConnectTimeout=10 -o ControlPath=/home/janne/.ansible/cp/ansible-ssh-%h-%p-%r -tt 192.168.0.157 'mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1455401324.79-221794005648841 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1455401324.7
9-221794005648841 )"'
<192.168.0.150> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o
ConnectTimeout=10 -o ControlPath=/home/janne/.ansible/cp/ansible-ssh-%h-%p-%r -tt 192.168.0.150 'mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1455401324.79-182183570705768 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1455401324.7
9-182183570705768 )"'
<192.168.0.73> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.0.73> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o C
onnectTimeout=10 -o ControlPath=/home/janne/.ansible/cp/ansible-ssh-%h-%p-%r -tt 192.168.0.73 'mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1455401324.79-134588512123476 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1455401324.79-
134588512123476 )"'
<192.168.0.220> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.0.220> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o
ConnectTimeout=10 -o ControlPath=/home/janne/.ansible/cp/ansible-ssh-%h-%p-%r -tt 192.168.0.220 'mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1455401324.8-245049243481998 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1455401324.8-
245049243481998 )"'
<192.168.0.157> PUT /tmp/janne/tmpU2Q_8L TO /root/.ansible/tmp/ansible-tmp-1455401324.79-221794005648841/ping
<192.168.0.157> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ro
ot -o ConnectTimeout=10 -o ControlPath=/home/janne/.ansible/cp/ansible-ssh-%h-%p-%r '[192.168.0.157]'
<192.168.0.150> PUT /tmp/janne/tmpiBTinc TO /root/.ansible/tmp/ansible-tmp-1455401324.79-182183570705768/ping
<192.168.0.150> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ro
ot -o ConnectTimeout=10 -o ControlPath=/home/janne/.ansible/cp/ansible-ssh-%h-%p-%r '[192.168.0.150]'
<192.168.0.73> PUT /tmp/janne/tmpV_eY8S TO /root/.ansible/tmp/ansible-tmp-1455401324.79-134588512123476/ping
<192.168.0.73> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=roo
t -o ConnectTimeout=10 -o ControlPath=/home/janne/.ansible/cp/ansible-ssh-%h-%p-%r '[192.168.0.73]'
<192.168.0.220> PUT /tmp/janne/tmpbllWlE TO /root/.ansible/tmp/ansible-tmp-1455401324.8-245049243481998/ping
<192.168.0.220> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ro
ot -o ConnectTimeout=10 -o ControlPath=/home/janne/.ansible/cp/ansible-ssh-%h-%p-%r '[192.168.0.220]'
<192.168.0.150> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.0.150> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o
ConnectTimeout=10 -o ControlPath=/home/janne/.ansible/cp/ansible-ssh-%h-%p-%r -tt 192.168.0.150 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1455401324.79-182183570705768/ping
; rm -rf "/root/.ansible/tmp/ansible-tmp-1455401324.79-182183570705768/" > /dev/null 2>&1'
<192.168.0.157> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.0.157> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o
ConnectTimeout=10 -o ControlPath=/home/janne/.ansible/cp/ansible-ssh-%h-%p-%r -tt 192.168.0.157 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1455401324.79-221794005648841/ping
; rm -rf "/root/.ansible/tmp/ansible-tmp-1455401324.79-221794005648841/" > /dev/null 2>&1'
<192.168.0.220> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.0.220> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o
ConnectTimeout=10 -o ControlPath=/home/janne/.ansible/cp/ansible-ssh-%h-%p-%r -tt 192.168.0.220 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1455401324.8-245049243481998/ping;
 rm -rf "/root/.ansible/tmp/ansible-tmp-1455401324.8-245049243481998/" > /dev/null 2>&1'
<192.168.0.73> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.0.73> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o C
onnectTimeout=10 -o ControlPath=/home/janne/.ansible/cp/ansible-ssh-%h-%p-%r -tt 192.168.0.73 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1455401324.79-134588512123476/ping;
rm -rf "/root/.ansible/tmp/ansible-tmp-1455401324.79-134588512123476/" > /dev/null 2>&1'
kubemaster1 | SUCCESS => {
    "changed": false,
    "invocation": {
        "module_args": {
            "data": null
        },
        "module_name": "ping"
    },
    "ping": "pong"
}
kubenode1 | SUCCESS => {
    "changed": false,
    "invocation": {
        "module_args": {
            "data": null
        },
        "module_name": "ping"
    },
    "ping": "pong"
}
kubemaster2 | SUCCESS => {
    "changed": false,
    "invocation": {
        "module_args": {
            "data": null
        },
        "module_name": "ping"
    },
    "ping": "pong"
}
kubenode2 | SUCCESS => {
    "changed": false,
    "invocation": {
        "module_args": {
            "data": null
        },
        "module_name": "ping"
    },
    "ping": "pong"
}
```
##### Actual Results:

The error that I added above.

**Comment by kongslund** [comment] 2016-02-17 06:55
I experience the same and due to its seemingly random behavior I have come to believe that it relates to [SSH connection reuse](http://docs.ansible.com/ansible/faq.html#how-do-i-get-ansible-to-reuse-connections-enable-kerberized-ssh-or-have-ansible-pay-attention-to-my-local-ssh-config-file).

After disabling any connection reuse – at a performance cost – I no longer encounter the error:

``` bash
ansible all -i hosts -m ping --ssh-extra-args="-o ControlMaster=no -o ControlPath=none -o ControlPersist=no"
```

You can also add the extra parameters in your inventory file using [ansible_ssh_extra_args](http://docs.ansible.com/ansible/intro_inventory.html#list-of-behavioral-inventory-parameters) or [disable it entirely](http://docs.ansible.com/ansible/intro_configuration.html#ssh-args) in your configuration file.

Does this help you as well?

**Comment by jimi-c** [comment] 2016-02-24 12:57
@kongslund, are you also on Arch?

**Comment by kongslund** [comment] 2016-02-26 09:29
@jimi-c, no I'm on a custom built image based on Ubuntu 14.04.

I've tried to reproduce the issue using two Vagrant instances of Arch Linux but was unable to do so.

I also didn't manage to reproduce it on a vanilla Ubuntu 14.04, i.e. not a custom built one.

**Comment by kongslund** [comment] 2016-02-26 09:40
@jimi-c, did you try what I suggested and did it help?

**Comment by pgporada** [comment] 2016-03-01 17:08
@kongslund
I've specified those ssh args in my inventory file but still get random module failures. I'm using Ubuntu 15.10 64bit with Ansible 2.0.0.2

**Comment by one1zero1one** [comment] 2016-03-10 08:46
Had same issue (ansible 2.1.0 - ubuntu 15.10 64bit - OpenSSH_6.9p1 Ubuntu-2ubuntu0.1, OpenSSL 1.0.2d 9 Jul 2015), disabled connection reuse (in the conf file) worked.  Thx @kongslund

**Comment by jaimess** [comment] 2016-03-10 13:36
I made it work on centos 6.6 by updating openssh to 5.3p1-112.el6_7

**Comment by ulrichSchreiner** [comment] 2016-03-13 15:42
hi,

i think this is duplicate of #13876. and it happens with 2.0.1.0. if i set the `ssh_args` it still happens with ubuntu 15.10 and also with the latest beta of 16.04.

it always happens in my playbook (and always on `template`-tasks). i do not have any successful run :-(

</usc>

**Comment by jimi-c** [comment] 2016-04-20 11:49
@ulrichSchreiner yes this is a dupe of that bug, so I'm going to close this now. There is a workaround in place for 2.0.2 and 2.1, but we're going to hold that open just to be sure.

Thanks!

**Closed as completed by jimi-c** 2016-04-20 11:49 UTC
Labels: P2, bug
