### ISSUE TITLE
Location not parsing correctly when executing ansible or ansible-playbook

### ISSUE THREAD

**Issue by Comnenus** [ansible/ansible#61931] opened 2019-09-06 15:13 UTC
##### SUMMARY
When ~/.ansible is a symlink to another location, in this case, a Dropbox folder with spaces and parenthesis, ansible does not parse the path correctly.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Core

##### ANSIBLE VERSION

```
ansible 2.8.4
  config file = None
  configured module search path = ['/Users/justin.stmarie/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.8.4_1/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.4 (default, Jul  9 2019, 18:13:23) [Clang 10.0.1 (clang-1001.0.46.4)]
```

##### CONFIGURATION

```

```

##### OS / ENVIRONMENT
MacOS 10.14.6
iTerm 3.3.3
Mackup 0.8.27

##### STEPS TO REPRODUCE
1. $ brew install mackup
2. Configure a dropbox for business, which likely has spaces and parenthesis, and cannot be changed.
2. $ mackup backup
 - this will move .ansible to to the mackup dirextory in dropbox and create a symlink for ~/.ansible
3. Run any ansible playbook or ansible ad-hoc command.
4. TASK [Gathering Facts] *********************************************************
fatal: [host-1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: command-line line 0: garbage at end of line; \"(Company\".", "unreachable": true}
  - In this case the directory is ~/Dropbox (Company A)/

##### EXPECTED RESULTS
Playbooks and commands should execute correctly.

##### ACTUAL RESULTS
SSH: EXEC sshpass -d43 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o 'User="root"' -o ConnectTimeout=10 -o 'ControlPath=/Users/justin/Dropbox (Company A)/Mackup/.ansible/cp/a833c3d1b0' ws01.local '/bin/sh -c '"'"'echo ~root && sleep 0'"'"''
<ws01.local> (255, b'', b'command-line line 0: garbage at end of line; "(Company".\r\n')
fatal: [ws01.local]: UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: command-line line 0: garbage at end of line; \"(Company\".",
    "unreachable": true
}

**Comment by sivel** [comment] 2019-09-06 15:15
Duplicate of https://github.com/ansible/ansible/issues/59206

**Closed as completed by sivel** 2019-09-06 15:15 UTC
