### ISSUE TITLE
Template module broken when modifying symlinks

### ISSUE THREAD

**Issue by jsternberg** [ansible/ansible#10208] opened 2015-02-10 22:06 UTC
If you attempt to template a file that's a symlink and the file is already up to date, the code path for the template module attempts to invoke the file module. This is done right here: https://github.com/ansible/ansible/blob/devel/lib/ansible/runner/action_plugins/template.py#L158

You can see right before the module invocation it attempts to wipe the `src` parameter from the module arguments. Unfortunately, if you use complex_args, it doesn't wipe that attribute from there. So the `src` parameter continues to be passed to the file module. This then ends up hitting the following error: https://github.com/ansible/ansible-modules-core/blob/release1.8.2/files/file.py#L264

I've tested this on ansible 1.8.2 and 1.7.2 and it appears to be present in both.

**Comment by abadger** [comment] 2015-02-11 02:02
@jsternberg Are you able to test whether https://github.com/ansible/ansible/commit/8fba66b4b541007ef9805bb7254fa3433ae42f3b fixes things for you?  I didn't try to reproduce your error conditions, just took a look at the code with your analysis in mind and thought that this patch should fix it.  I'll try and work up an integration test to go along with this tonight but I'd love independent confirmation that I'm on the right track.

**Comment by jsternberg** [comment] 2015-02-11 02:21
It looks like that will fix it. Give me a bit to try it out.

**Comment by jsternberg** [comment] 2015-02-11 02:29
Looks good! The fix works with my test case.

**Comment by abadger** [comment] 2015-02-11 08:14
excellent.  Thanks for reporting and testing the fix!

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Closed as completed** 2015-02-11 08:13 UTC
Labels: P2, bug
