### ISSUE TITLE
group_by handles jinja filters non-gracefully

### ISSUE THREAD

**Issue by neshura** [ansible/ansible#6953] opened 2014-04-11 15:42 UTC
##### Issue Type:

Bug report
##### Ansible Version:

ansible 1.5.3
##### Environment:

control: OSX
management: RHEL5/6
##### Summary:

If you supply a jinja filter in a group_by key, the unexpected result is a dynamic group created with the name as a string literal up to and including the pipe (|) symbol. It would be nice if it either failed in a way that made it clear that filters are not allowed, or supported filters.
##### Steps To Reproduce:

Create a group of hosts and filter the variable used for the key. 

```

---
- hosts: somehosts
  user: deploy
  sudo: yes
  gather_facts: yes
  tasks:
    - group_by: key={{ ansible_distribution_release }}-{{ ansible_distribution_version | truncate(1, True, '') }}
```

Create a group of hosts with the group name that would be expected.

```
- hosts: RedHat-6
  user: deploy
  sudo: yes
  gather_facts: yes
  roles:
    - somerole

- hosts: RedHat-5
  user: deploy
  sudo: yes
  gather_facts: yes
  tasks:
    - fail: "RHEL5 is not currently supported for this release"
```

Create a group of hosts with the group name as a strange string literal that matches a chunk of unhandled code.

```
- hosts: '{{ansible_distribution_release}}-{{ansible_distribution_version'
  user: deploy
  sudo: yes
  gather_facts: yes
  tasks:
    - command: echo $HOSTNAME
```
##### Expected Results:

I would expect the role 'somerole' to be applied to the RedHat-6 machines in production, and not to end up deployed on any lingering RedHat-5 hosts. (Obviously I can match and handle os versions in a different way, such as any number of os-specific group vars suggested by the documentation, the scenario exists just to demonstrate the issue.)

I would definitely not expect the final group of hosts, as above, to be created and usable.
##### Actual Results:

```
TASK: [group_by key={{ansible_distribution_release}}-{{ansible_distribution_version | truncate(1, True, '')}}] ***
changed: [foohost1-somesite]

PLAY [RedHat-6] ***************************************************************
skipping: no hosts matched

PLAY [RedHat-5] ***************************************************************
skipping: no hosts matched

PLAY [{{ansible_distribution_release}}-{{ansible_distribution_version] ********

GATHERING FACTS ***************************************************************
ok: [foohost2-somesite]
ok: [foohost3-somesite]
ok: [foohost1-somesite]

TASK: [command echo $HOSTNAME] ************************************************
changed: [foohost2-somesite]
changed: [foohost3-somesite]
changed: [foohost1-somesite]
```

Working around is not difficult, but one is required to create a temporary variable or fact to hold interim filtered results.

**Comment by mpdehaan** [comment] 2014-04-14 15:32
Hi, I'm having trouble understanding this report.

The group by module groups modules based on a string value, which can of course be templated.

Can you explain what about it you think is incorrect?  I understand your playbook is going on to use this data later but I'm unclear where you think the error lies.

If it creates a group name that you don't use, there's not much we can do, though I'm perhaps not understanding the underlying question/issue.

Thanks!

**Comment by neshura** [comment] 2014-04-14 16:46
Of course! I'm sorry if it did not make sense, I'm sure I could have
written it more clearly. The short version is that I was expecting
equivalency between

```
  tasks:
    - set_fact: os_major_version={{ ansible_distribution_version |
```

truncate(1, True, '') }}
        - group_by: key={{ ansible_distribution }}-{{ os_major_version }}

and

```
  tasks:
    - group_by: key={{ ansible_distribution }}-{{
```

ansible_distribution_version | truncate(1, True, '') }}

The former divides my hosts into groups "RedHat-6" and "RedHat-5" as I
would expect, the latter doesn't, and skips every host in the group.

Does that make sense? It's entirely possible I'm misunderstanding where and
when one could expect to use a filter.

Thank you for the polite response! Please let me know if this does not
clarify the report, and/or whatever other information I can provide.

**Comment by denisphillips** [comment] 2014-05-04 12:53
The problem is that the group_by plugin in is using:

```
        args.update(parse_kv(self.runner.module_args))
```

It should be using this:

```
        args.update(parse_kv(module_args))
```

Pull Request with fix: https://github.com/ansible/ansible/pull/7273

**Comment by jimi-c** [comment] 2014-05-05 14:24
The above commit has been merged in. If you continue having problems related to this issue, or if you have any further questions, please let us know. Thanks!

**Closed as completed by jimi-c** 2014-05-05 14:24 UTC
Labels: needs_info, bug
