### ISSUE TITLE
ipaddr returns empty string

### ISSUE THREAD

**Issue by nomaster** [ansible/ansible#13716] opened 2016-01-03 11:51 UTC
Given a IPv4 network with exactly two addresses, specified in CIDR notation
When I use the ipaddr filter to extract the address (without prefix)
Then I expect to have the address returned
But an empty string is returned

Example:

``` shell
# {{ '100.64.251.2/31' | ipaddr('address') }}
""

# {{ '100.64.251.3/31' | ipaddr('address') }}
"100.64.251.3"
```

**Comment by nomaster** [comment] 2016-01-03 11:53
Point to point links, specified in [RFC 3021](https://tools.ietf.org/html/rfc3021) have no addresses for network or brodcast.

**Comment by nomaster** [comment] 2016-01-03 12:34
Upstream bug: drkjam/netaddr#96

**Comment by chrrrles** [comment] 2016-01-05 22:07
Cannot reproduce using this playbook on 2.0 or stable-1.9:

```
- hosts: all
  connection: local
  tasks:
  - debug: msg="{{ '192.168.0.1/24' | ipaddr('address') }}"
```

Output:
```
ok: [localhost] => {
    "msg": "192.168.0.1"
}
```

**Comment by chrrrles** [comment] 2016-01-06 16:34
I used the wrong address in my first test, so adding the Pending Closure label was a mistake.

**Comment by drybjed** [comment] 2016-01-07 14:09
Related issues: https://github.com/ansible/ansible/issues/12065 and https://github.com/ansible/ansible/issues/13104.

**Comment by abadger** [comment] 2017-04-11 16:41
Fixed in https://github.com/ansible/ansible/issues/13739 which is present in the stable-2.2, stbale-2.3, and devel branches.

Closing as fixed.

**Closed as completed by abadger** 2017-04-11 16:41 UTC
Labels: affects_2.2, affects_2.3, bug
