### ISSUE TITLE
ignores dry run flag (--check) for template module when setting mode

### ISSUE THREAD

**Issue by gjuric** [ansible/ansible#9370] opened 2014-10-17 18:17 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.6
ansible 1.7.2
##### Environment:

OS X 10.9.5 (installed via homebrew)
##### Summary:

Ansible changes the remote system when playbook is being run with the "--check" flag.
##### Steps To Reproduce:

This feature used to work until I started adding tags and limits to the command. The command that ignores the "--check" flag looks like this:

```
ansible-playbook -i hosts play.yml --diff --check --limit=ONE-GROUP-NAME --tags=ONE-TAG --ask-vault-pass
```
##### Expected Results:

I expected that playbook will not actually change the remote system. I have noticed this while running the task that looks something like this:

```
- name: Action name
  template:
    src: template.src.j2
    dest: /remote/path/file.src
    group: group-name
    owner: owner-name
    mode: 0640
```
##### Actual Results:

Ansible applied the settings for group and owner from the action above.

**Comment by jimi-c** [comment] 2014-10-20 16:47
Hi @gjuric, I believe we corrected this in 0c4a7492bf6a62f7d84cb52f4ce9989f928f8b6d (currently in devel only). Could you please test this against the devel branch to determine if you're stll seeing the same issue there?

**Comment by abadger** [comment] 2014-10-20 19:37
Confirming that the file mode is changed using ansible-playbook 1.7.2 with --check and that template but is unchanged with current devel branch.

**Comment by jimi-c** [comment] 2014-10-22 20:48
Hi @gjuric, since we've confirmed this is fixed in the devel branch, we're going to go ahead and close this. The patch referenced above will be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Closed as completed by jimi-c** 2014-10-22 20:48 UTC
Labels: needs_info, P1, bug
