### ISSUE TITLE
lookup_plugins appearing alongside playbook not found

### ISSUE THREAD

**Issue by quinot** [ansible/ansible#11815] opened 2015-07-31 10:20 UTC
According to the documentation, " plugins can be shipped in a subdirectory relative to a top-level playbook", and this used to work in v1.

With v2 however, this does not work (at least for lookup_plugins) unless the "lookup_plugins" subdirectory is explicitly mentioned in ansible.cfg.

```
$ mkdir lookup_plugins
$ cp $ANSIBLE_ROOT/lib/ansible/plugins/lookup/items.py lookup_plugins/myitems
$ cat test_lookup_pl.yml 

---
- hosts: localhost
  tasks:
    - name: Print items from custom lookup plugin
      debug: msg="Item= {{ item }} "
      with_myitems:
        - foo
        - bar
$ ansible-playbook test_lookup_pl.yml
PLAY ****************************************************************************

TASK [setup] ********************************************************************
ok: [localhost]

TASK [Print items from custom lookup plugin] ************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "ERROR! the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'item' is undefined"}

PLAY RECAP **********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   


Now if I create an ansible.cfg file:
$ cat ansible.cfg
[defaults]
lookup_plugins=./lookup_plugins

$ ansible-playbook test_lookup_pl.yml
PLAY ****************************************************************************

TASK [setup] ********************************************************************

ok: [localhost]

TASK [Print items from custom lookup plugin] ************************************
ok: [localhost] => (item=foo) => {
    "item": "foo", 
    "msg": "Item= foo "
}
ok: [localhost] => (item=bar) => {
    "item": "bar", 
    "msg": "Item= bar "
}
ok: [localhost]

PLAY RECAP **********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
```

**Comment by jimi-c** [comment] 2015-08-03 17:09
@quinot this is a duplicate of https://github.com/ansible/ansible/issues/11685, and is due to the fact that the API for lookup plugins changed slightly, so our code will only load those plugins that use the base class LookupBase.

We are planning on (at the very least) writing some migration docs for plugins like this, where the API has changed, though we still might try and create some kind of wrapper class to make this a bit easier for user. For now though, I'll close this as a duplicate.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by quinot** [comment] 2015-08-04 09:37
@jimi-c I am very puzzled by your answer. This issue does not look to me like #11685 at all.

As you can see from the reproducer I gave, this problem occurs with a lookup plugin that is a verbatim copy of item.py from the Ansible source tree, which does use LookupBase as its base class. Furthermore, the plugin _does_ load succsefully once the lookup_plugins directory is explicitly listed in ansible.cfg. I would therefore very much appreciate your reopening and reviewing this report.

**Comment by amenonsen** [comment] 2015-08-04 10:03
@quinot I think the idea is that, due to the intentional compatibility break, plugins in the same location as earlier are not automatically loaded on purpose. If you know for some reason that your plugins can be loaded by the current code, you can set the path and they'll be loaded.

(**Update**: The above is retained for historical accuracy, but it was based on a misunderstanding and is completely wrong. Please ignore it.)

**Comment by jimi-c** [comment] 2015-08-04 12:22
@quinot my apology, I did not see that you were using a copy of item.py. I've reopened this and will continue investigating.

**Comment by quinot** [comment] 2015-08-04 13:16
@jimi-c Thanks Jim! Do let me know if I can be of any help.

**Closed as completed** 2015-08-04 16:26 UTC
Labels: bug

**Comment by jimi-c** [comment] 2015-08-04 16:28
@quinot the above patch should fix this for you. One thing I did notice however, is that lookup plugins must end with the `.py` (only modules are allowed to have no extension). Combined with the patch above I now get this for your output:

<pre>
TASK [Print items from custom lookup plugin] ************************************
ok: [localhost] => (item=foo) => {
    "item": "foo", 
    "msg": "Item=foo"
}
ok: [localhost] => (item=bar) => {
    "item": "bar", 
    "msg": "Item=bar"
}
ok: [localhost] => {"changed": false, "msg": "All items completed"}
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by amenonsen** [comment] 2015-08-07 09:43
Note that after this change, plugins that are in e.g. `$basedir/library/filter_plugins` _don't_ get loaded, which they used to do before. Since this worked in 1.x, I think it should be supported in devel. (If I put them in `$basedir/filter_plugins`, it does work now.)

**Comment by amenonsen** [comment] 2015-08-07 10:00
(This breaks even if I set `ANSIBLE_LIBRARY=/absolute/path/to/library`, which seems especially bad.)
