### ISSUE TITLE
routeros_command - Unable to connect (expected msg: 50 got: 5)

### ISSUE THREAD

**Issue by bogd** [ansible/ansible#55042] opened 2019-04-09 14:23 UTC
##### SUMMARY
I am attempting to use the new routeros_command module to send commands to Mikrotik routers. However, all connection attempts fail with "Invalid/incorrect username/password. Authentication failed.".

Authentication is performed via username/password. I have double- and triple-checked the credentials, and they all seem ok.

The only other hint is a message logged by the router, saying "expected msg: 50 got: 5".

I have already set "look_for_keys = False" under ansible.cfg/paramiko, but the result is the same.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
routeros_command

##### ANSIBLE VERSION

```paste below
ansible 2.7.8
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```paste below
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_PRIVATE_KEY_FILE(/etc/ansible/ansible.cfg) = /root/ansible_key
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
PARAMIKO_HOST_KEY_AUTO_ADD(/etc/ansible/ansible.cfg) = True
PARAMIKO_LOOK_FOR_KEYS(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Tested on two different Mikrotik routers, both running RouterOS v6.44.2

##### STEPS TO REPRODUCE

inventory.yml:
```yaml
router:
  hosts:
    mikrotik:
      ansible_connection: network_cli
      ansible_network_os: routeros
      ansible_host: 192.168.1.1
      ansible_user: bogd
      ansible_ssh_pass: test123
```

playbook - mik-test.yml:
```yaml
---
- name: Test Mikrotik commands
  hosts: mikrotik
  gather_facts: false
  tasks: 
     
  - name: Test command 1
    routeros_command:
      commands:
      - /system identity print
      
  - name: Test command 2
    routeros_command:
      commands:
      - /system identity print
```
##### EXPECTED RESULTS

Successful connection, and commands being run on the device.

##### ACTUAL RESULTS
Connection fails. Mikrotik routers log this message:

Buffer |   | memory
Topics |   | ssh, error
Message |   | expected msg: 50 got: 5

Ansible logs:

```paste below
# ansible-playbook -i inventory.yml mik_test.yml -vvvv
ansible-playbook 2.7.8
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
/mnt/hgfs/docker/Ansible - full deployment/inventory.yml did not meet host_list requirements, check plugin documentation if this is unexpected
Parsed /mnt/hgfs/docker/Ansible - full deployment/inventory.yml inventory source with yaml plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/dist-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: mik_test.yml ********************************************************************************
1 plays in mik_test.yml

PLAY [Test Mikrotik commands] *************************************************************************
META: ran handlers

TASK [Test command 1] *********************************************************************************
task path: /mnt/hgfs/docker/Ansible - full deployment/mik_test.yml:7
<192.168.1.1> attempting to start connection
<192.168.1.1> using connection plugin network_cli
<192.168.1.1> local domain socket does not exist, starting it
<192.168.1.1> control socket path is /root/.ansible/pc/99ef10c7e3
<192.168.1.1> 
The full traceback is:
Traceback (most recent call last):
  File "/usr/bin/ansible-connection", line 106, in start
    self.connection._connect()
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/connection/network_cli.py", line 309, in _connect
    ssh = self.paramiko_conn._connect()
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/connection/paramiko_ssh.py", line 255, in _connect
    self.ssh = SSH_CONNECTION_CACHE[cache_key] = self._connect_uncached()
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/connection/paramiko_ssh.py", line 368, in _connect_uncached
    raise AnsibleAuthenticationFailure(msg)
AnsibleAuthenticationFailure: Invalid/incorrect username/password. Authentication failed.
fatal: [mikrotik]: FAILED! => {
    "msg": "Invalid/incorrect username/password. Authentication failed."
}
        to retry, use: --limit @/mnt/hgfs/docker/Ansible - full deployment/mik_test.retry

PLAY RECAP ********************************************************************************************
mikrotik                   : ok=0    changed=0    unreachable=0    failed=1   
```

I enabled SSH logging on the router, and it looks like ansible is trying public key authentication first (even though I am explicitly providing a password). 

Mikrotik SSH log:
```
Apr/09/2019 17:18:13 ssh,debug auth req: bogd ssh-connection publickey
Apr/09/2019 17:18:13 ssh,debug can't find matching key for user: bogd
Apr/09/2019 17:18:13 ssh,debug next auth methods: publickey,password
Apr/09/2019 17:18:13 ssh,debug,packet packet create: 51
Apr/09/2019 17:18:13 ssh,debug,packet ----- sending ----- 
Apr/09/2019 17:18:13 ssh,debug,packet => offset:68 [0x44]
Apr/09/2019 17:18:13 ssh,debug,packet => size:44 [0x44]
Apr/09/2019 17:18:13 ssh,debug,packet 0000 002c 1333 0000 0012 7075 626c 6963
Apr/09/2019 17:18:13 ssh,debug,packet 6b65 792c 7061 7373 776f 7264 00a2 d714
Apr/09/2019 17:18:13 ssh,debug,packet 49e1 c67a dd40 7363 e5c6 f5b8 3187 a726
Apr/09/2019 17:18:13 ssh,debug,packet 9131 fa19 3c45 19d4 fa87 8eb9 df3a b275
Apr/09/2019 17:18:13 ssh,debug,packet 3251 bfa6
Apr/09/2019 17:18:13 ssh,debug,packet --------------------
Apr/09/2019 17:18:13 ssh,debug,packet ----- recieved -----
Apr/09/2019 17:18:13 ssh,debug,packet => offset:34 [0x34]
Apr/09/2019 17:18:13 ssh,debug,packet => size:34 [0x34]
Apr/09/2019 17:18:13 ssh,debug,packet 0000 001c 0a05 0000 000c 7373 682d 7573
Apr/09/2019 17:18:13 ssh,debug,packet 6572 6175 7468 0000 0000 0000 0000 0000
Apr/09/2019 17:18:13 ssh,debug,packet b828 b2b1 5cf7 2302 b76d 46d4 62c8 98ec
Apr/09/2019 17:18:13 ssh,debug,packet ab71 0495
Apr/09/2019 17:18:13 ssh,debug,packet --------------------
Apr/09/2019 17:18:13 ssh,error expected msg: 50 got: 5
Apr/09/2019 17:18:13 ssh,debug code 0x01000002 closing..
Apr/09/2019 17:18:13 ssh,debug,packet packet create: 1
Apr/09/2019 17:18:13 ssh,debug,packet ----- sending ----- 
Apr/09/2019 17:18:13 ssh,debug,packet => offset:52 [0x34]
Apr/09/2019 17:18:13 ssh,debug,packet => size:34 [0x34]
Apr/09/2019 17:18:13 ssh,debug,packet 0000 001c 0e01 0000 0002 0000 0000 0000
Apr/09/2019 17:18:13 ssh,debug,packet 0000 21e0 28dc 0b9b cff3 9e73 c603 618c
Apr/09/2019 17:18:13 ssh,debug,packet e49e 2abf 3c7c c6ac ba17 4452 7bcb 6e8f
Apr/09/2019 17:18:13 ssh,debug,packet 259a 5ca9
Apr/09/2019 17:18:13 ssh,debug,packet --------------------
Apr/09/2019 17:18:13 ssh,debug transport state: 4 --> 0
Apr/09/2019 17:18:13 ssh,debug closing connection: <> 192.168.137.23:54972 (14)
```

I do not know how I could troubleshoot the issue further - I would appreciate any hint pointing me in the right direction.

Thank you!

**Comment by heuels** [comment] 2019-10-24 14:09
@bogd, I just found this issue when looking through mentions and I am terribly sorry for missing this issue on time! Please tell me, does it still persist? Because I am able to connect to any RouterOS router just fine.

**Comment by bogd** [comment] 2019-11-08 20:38
Sorry for the delay in answering, but since the original post there have been several updates (to both ansible and the mikrotik firmware), and I had to check if the issue is still present.

I can still reproduce the issue on ansible 2.9.0 on Ubuntu 18.04, with mikrotik firmware 6.45.6 .

The playbook fails with:

`    "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/lib/python3.6/runpy.py\", line 208, in run_module\n    return _run_code(code, {}, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_routeros_command_payload_djvoql6v/ansible_routeros_command_payload.zip/ansible/modules/network/routeros/routeros_command.py\", line 187, in <module>\n  File \"/tmp/ansible_routeros_command_payload_djvoql6v/ansible_routeros_command_payload.zip/ansible/modules/network/routeros/routeros_command.py\", line 157, in main\n  File \"/tmp/ansible_routeros_command_payload_djvoql6v/ansible_routeros_command_payload.zip/ansible/module_utils/network/routeros/routeros.py\", line 125, in run_commands\n  File \"/tmp/ansible_routeros_command_payload_djvoql6v/ansible_routeros_command_payload.zip/ansible/module_utils/network/routeros/routeros.py\", line 55, in get_connection\n  File \"/tmp/ansible_routeros_command_payload_djvoql6v/ansible_routeros_command_payload.zip/ansible/module_utils/network/routeros/routeros.py\", line 69, in get_capabilities\n  File \"/tmp/ansible_routeros_command_payload_djvoql6v/ansible_routeros_command_payload.zip/ansible/module_utils/connection.py\", line 185, in __rpc__\nansible.module_utils.connection.ConnectionError: Invalid/incorrect username/password. Authentication failed.\n", `


The router logs the same `expected msg: 50, got: 5` .

<img width="406" alt="sshot-41" src="https://user-images.githubusercontent.com/2977872/68508953-7629bf80-0278-11ea-8462-d78893dfaf3c.png">

**Comment by heuels** [comment] 2019-11-11 09:07
It's just a hunch, but can you try commenting out the following line from your `ansible.cfg`? Looks like that's the only difference between your config and mine.
```
DEFAULT_PRIVATE_KEY_FILE(/etc/ansible/ansible.cfg) = /root/ansible_key
```

**Comment by bogd** [comment] 2019-11-13 10:51
@heuels - nice hunch! It seems to be absolutely correct :)

After commenting out the configuration line, I can successfully connect to the router with a username/password combination. In the router logs,  the "expected msg" line is gone, replaced by a much more normal-looking `user ansible-test logged in from 10.1.1.1 via ssh`.

So if I'm reading this correctly, it means that when that configuration line is present the connection plugin (network_cli? paramiko?) is trying some kind of key-based auth. Even though the host variables as defined in the inventory file explicitly specify a username/password combination. Is there anything else I can configure to fix this (while keeping key-based authentication for the rest of my servers)?

Also, there is one additional problem - even though the connection now succeeds (as per the router's logs), command execution still fails with a timeout. Using the same playbook as before:

`
fatal: [mikrotik]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    }, 
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-local-10932tW3nXr/ansible-tmp-1573642207.07-159062156248088/AnsiballZ_routeros_command.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-local-10932tW3nXr/ansible-tmp-1573642207.07-159062156248088/AnsiballZ_routeros_command.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-local-10932tW3nXr/ansible-tmp-1573642207.07-159062156248088/AnsiballZ_routeros_command.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.network.routeros.routeros_command', init_globals=None, run_name='__main__', alter_sys=False)\n  File \"/usr/lib/python3.6/runpy.py\", line 208, in run_module\n    return _run_code(code, {}, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_routeros_command_payload_yz7viwzl/ansible_routeros_command_payload.zip/ansible/modules/network/routeros/routeros_command.py\", line 187, in <module>\n  File \"/tmp/ansible_routeros_command_payload_yz7viwzl/ansible_routeros_command_payload.zip/ansible/modules/network/routeros/routeros_command.py\", line 157, in main\n  File \"/tmp/ansible_routeros_command_payload_yz7viwzl/ansible_routeros_command_payload.zip/ansible/module_utils/network/routeros/routeros.py\", line 125, in run_commands\n  File \"/tmp/ansible_routeros_command_payload_yz7viwzl/ansible_routeros_command_payload.zip/ansible/module_utils/network/routeros/routeros.py\", line 55, in get_connection\n  File \"/tmp/ansible_routeros_command_payload_yz7viwzl/ansible_routeros_command_payload.zip/ansible/module_utils/network/routeros/routeros.py\", line 69, in get_capabilities\n  File \"/tmp/ansible_routeros_command_payload_yz7viwzl/ansible_routeros_command_payload.zip/ansible/module_utils/connection.py\", line 185, in __rpc__\nansible.module_utils.connection.ConnectionError: timeout value 30 seconds reached while trying to send command: /system resource print\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}
`

**Comment by heuels** [comment] 2019-11-13 15:40
> Also, there is one additional problem - even though the connection now succeeds (as per the router's logs), command execution still fails with a timeout. Using the same playbook as before:

There've been reports that adding a `+cet1024w` as a suffix to your username might help with that. Unfortunately mutating username by a network module or plugin is not something that is currently supported by Ansible, so you need to manually specify this suffix in usernames of your hosts files.

> So if I'm reading this correctly, it means that when that configuration line is present the connection plugin (network_cli? paramiko?) is trying some kind of key-based auth. Even though the host variables as defined in the inventory file explicitly specify a username/password combination. Is there anything else I can configure to fix this (while keeping key-based authentication for the rest of my servers)?

It looks like Ansible variable precedence rules are to blame here. If you have defined something in you config it will always be the default for every host. You can try applying private key to hosts in a more granular way, for example via `group_config` or even `host_config` files. [See this docs page for reference](https://docs.ansible.com/ansible/latest/reference_appendices/general_precedence.html).

**Comment by heuels** [comment] 2019-11-17 14:09
@bogd I would like to close this issue since the original problem you had is not a bug in `routeros_command` module. If you have any further questions on the topic feel free to comment on this one. Have a nice day :)

**Comment by heuels** [comment] 2019-11-17 14:10
notabug

**Closed as completed** 2019-11-17 14:17 UTC
Labels: networking, module, support:community, bug, traceback, affects_2.7

**Comment by bogd** [comment] 2019-11-21 09:17
Thank you for your help. Just one more note - maybe you could add that "+cet1024w" part to the documentation (including a brief description of what it does and why it is needed)? It might help other people who (like me) are trying to use the module with username/password auth. 

Maybe [here](https://docs.ansible.com/ansible/latest/network/user_guide/platform_routeros.html)?

Thank you for your help with this issue!

**Comment by heuels** [comment] 2019-11-21 09:50
@bogd, that's a great idea, thanks! I've opened a pull request #65140.
