### ISSUE TITLE
yum module on Oracle Linux does not work with multiple values for enablerepo

### ISSUE THREAD

**Issue by rchrd** [ansible/ansible#8033] opened 2014-07-03 15:27 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.6
##### Environment:

Host OS: OSX 10.9.4
Target OS: Oracle Linux Server release 6.5
##### Summary:

Installing a package with the yum module and option 'enablerepo' with 2 repo's fails with the message: 

```
failed: [localhost] => {"failed": true}
msg: Error setting/accessing repo puppetlabs-deps: Error getting repository data for puppetlabs-deps, repository not found
```
##### Steps To Reproduce:

After adding a new repo file to the /etc/yum.repos.d directory with all repo's in there disabled, this snippet is used to install the package:

```
- name: Install puppet-server package
  yum:
    name=puppet-server
    enablerepo=puppetlabs-products,puppetlabs-deps
```
##### Expected Results:

The package is installed
##### Actual Results:

The error described above is shown.
This works fine on CentOS 6.5

The yum module splits the enablerepo values and generates multiple `--enablerepo` tags. This works fine on CentOS 6.5 but not on Oracle Linux 6.5. For Oracle Linux only one `--enablerepo` must be specified where multiple repo's must be separated with a comma.

**Comment by Jmainguy** [comment] 2014-08-11 23:25
This is a duplicate of #7137

However this provides information on the possible fix.

**Comment by mpdehaan** [comment] 2014-09-29 20:26
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Closed as completed by mpdehaan** 2014-09-29 20:26 UTC
Labels: bug, packaging
