### ISSUE TITLE
Ansible 2.x: variables were not passed to role

### ISSUE THREAD

**Issue by ThomasSteinbach** [ansible/ansible#13617] opened 2015-12-21 01:38 UTC
I recognized a somewhat strange behavior (bug), it took me some hours to figure out, what's wrong. Let me explain it by the following example. We have three roles, each role comprising one file as following:

**/rolespath/role1/tasks/main.yml**

```

---
- name: print variable
  debug: msg="{{ role1_variable }}"
```

**/rolespath/role2/meta/main.yml**

```

---
dependencies:
  - role: role1
    role1_variable: "{{ role2_variable }}"
```

**/rolespath/role3/meta/main.yml**

```

---
dependencies:
  - role: role2
    role2_variable: "from role3"
```
## What is working

Now, when I call the **role2** within a playbook, everything works as expected. The playbook...

```
- name: calling role2 works
  hosts: localhost
  gather_facts: no
  roles:
    - role: role2
      role2_variable: "from playbook"
```

... would lead to the following correct output:

```
PLAY [calling role 2 works] ***********************************

TASK [role1 : print variable] *********************************
ok: [localhost] => {
    "changed": false, 
    "msg": "from playbook"
}
```
## What does not work

But when I call the **role3**, the playbook...

```
- name: calling role3 fails
  hosts: localhost
  gather_facts: no
  roles:
    - role: role3
```

... would lead to the following error output:

```
PLAY [calling role3 fails] ***********************************

TASK [role1 : print variable] ********************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "ERROR! ERROR! 'role2_variable' is undefined"}
```
## Further description

It doesn't matter If you set the _role2_variable_ within the third roles _meta/main.yml_ directly, as shown in the example, or introduce a _role3_variable_. Even when you introduce a further **role4** which calls **role3** and setting the _role3_variable_ (and even further roles in this scheme), the error remains that `'role2_variable' is undefined`.

**Comment by Yannig** [comment] 2015-12-21 10:03
Looking after this issue, the following patch is fixing the current issue:

``` patch
diff --git a/lib/ansible/vars/__init__.py b/lib/ansible/vars/__init__.py
index 1184ec5..65dfed3 100644
--- a/lib/ansible/vars/__init__.py
+++ b/lib/ansible/vars/__init__.py
@@ -308,7 +308,7 @@ class VariableManager:

             if not C.DEFAULT_PRIVATE_ROLE_VARS:
                 for role in play.get_roles():
-                    all_vars = combine_vars(all_vars, role.get_vars(include_params=False))
+                    all_vars = combine_vars(all_vars, role.get_vars(include_params=True))

         if task:
             if task._role:
```

Looking after the commit behind this change, I found https://github.com/ansible/ansible/commit/a22f7b883dbe89f67bec2ce9b05904809b77652f which fix the following issue: https://github.com/ansible/ansible/issues/12460

**Comment by Yannig** [comment] 2015-12-21 10:05
@jimi-c: what do you think about?

**Comment by ThomasSteinbach** [comment] 2015-12-21 11:35
Thank you @Yannig for your investigation. Your 'fix' would make my day as long as there is not the trick, satisfying both issues.

**Comment by Yannig** [comment] 2015-12-21 11:40
@ThomasSteinbach the problem is that, using this change, the previous issue raise again. So not very satisfying.

**Comment by ThomasSteinbach** [comment] 2015-12-21 11:54
Yes, what I meant is that it is just a temporary fix for me until there is a fix 'satisfying both issues' :)

**Comment by jimi-c** [comment] 2015-12-21 15:47
@ThomasSteinbach you could also try running with ANSIBLE_PRIVATE_ROLE_VARS=1 set in your environment (this is a new 2.0 only option), which may resolve this, as the given task will still see all of its variables from its parent role (and dependencies, I believe).

**Comment by Yannig** [comment] 2015-12-21 16:52
@jimi-c: using this variable does not change Ansible behaviour.

You can retrieve a copy at the following location: https://github.com/Yannig/ansible-issue-low-speed/tree/master/roles-issue

**Comment by jimi-c** [comment] 2015-12-21 17:15
Yep, I'm looking into it to see if there's a way to fix it without breaking the previous issue.

**Comment by Yannig** [comment] 2015-12-21 17:38
@jimi-c The following patch is working with both issue:

``` patch
diff --git a/lib/ansible/vars/__init__.py b/lib/ansible/vars/__init__.py
index 1184ec5..2a85489 100644
--- a/lib/ansible/vars/__init__.py
+++ b/lib/ansible/vars/__init__.py
@@ -308,6 +308,8 @@ class VariableManager:

             if not C.DEFAULT_PRIVATE_ROLE_VARS:
                 for role in play.get_roles():
+                    for dep in role.get_all_dependencies():
+                        all_vars = combine_vars(all_vars, dep._role_params)
                     all_vars = combine_vars(all_vars, role.get_vars(include_params=False))

         if task:

```

**Comment by Yannig** [comment] 2015-12-21 17:38
The bad thing is about accessing a private field.

**Comment by Yannig** [comment] 2015-12-21 17:44
A much cleaner version:

``` patch
diff --git a/lib/ansible/playbook/role/__init__.py b/lib/ansible/playbook/role/__init__.py
index f308954..ce82573 100644
--- a/lib/ansible/playbook/role/__init__.py
+++ b/lib/ansible/playbook/role/__init__.py
@@ -265,6 +265,12 @@ class Role(Base, Become, Conditional, Taggable):
                 inherited_vars = combine_vars(inherited_vars, parent._role_params)
         return inherited_vars

+    def get_role_params(self):
+        params = {}
+        for dep in self.get_all_dependencies():
+            params = combine_vars(params, dep._role_params)
+        return params
+
     def get_vars(self, dep_chain=[], include_params=True):
         all_vars = self.get_inherited_vars(dep_chain, include_params=include_params)

diff --git a/lib/ansible/vars/__init__.py b/lib/ansible/vars/__init__.py
index 1184ec5..699333a 100644
--- a/lib/ansible/vars/__init__.py
+++ b/lib/ansible/vars/__init__.py
@@ -308,6 +308,7 @@ class VariableManager:

             if not C.DEFAULT_PRIVATE_ROLE_VARS:
                 for role in play.get_roles():
+                    all_vars = combine_vars(all_vars, role.get_role_params())
                     all_vars = combine_vars(all_vars, role.get_vars(include_params=False))

         if task:
```

**Comment by jimi-c** [comment] 2015-12-21 18:04
@Yannig very nice, confirmed that does the trick so merged that in (giving you credit of course). Waiting for the full set of integration tests to run, and if they pass I'll merge this into stable-2.0 as well.

Thanks!

**Closed as completed** 2015-12-21 18:03 UTC
Labels: bug

**Comment by Yannig** [comment] 2015-12-21 18:42
Thanks :)

**Comment by ThomasSteinbach** [comment] 2015-12-21 18:50
Thans too - works like a charm.
