### ISSUE TITLE
pip constraint

### ISSUE THREAD

**Issue by gfelot** [ansible/ansible#72920] opened 2020-12-09 17:02 UTC
##### SUMMARY
Wanted to upgrade the installed version of Apache Airflow to 1.10.12 where they now have a `--constraint` arguments.
https://airflow.apache.org/docs/apache-airflow/stable/installation.html

I see that on this PR there is the option available : #47654
But I cannot make it work so I tried with the `extra_args` but the constraint is seems not to be played because I have error that I have to fix manually on my VM.

```
- name: Install airflow
  pip:
    name: apache-airflow=={{airflow_version}}
    executable: pip3
    state: present
    extra_args: --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-1.10.12/constraints-3.7.txt"
  environment:
    AIRFLOW_GPL_UNIDECODE: yes
```
##### ANSIBLE VERSION
```
ansible 2.10.3
  config file = /Users/gil/Code/LISEA/Architecture/gcp-sea-cloud/ansible/ansible.cfg
  configured module search path = ['/Users/gil/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.10.3_1/libexec/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.0 (default, Dec  2 2020, 10:36:36) [Clang 12.0.0 (clang-1200.0.32.27)]

```

##### CONFIGURATION

```
DEFAULT_BECOME(/Users/gil/Code/LISEA/Architecture/gcp-sea-cloud/ansible/ansible.cfg) = True
DEFAULT_HOST_LIST(/Users/gil/Code/LISEA/Architecture/gcp-sea-cloud/ansible/ansible.cfg) = ['/Users/gil/Code/LISEA/Architecture/gcp-sea-cloud/ansible/inventory/sea-cloud.gcp.yml']
DEFAULT_ROLES_PATH(/Users/gil/Code/LISEA/Architecture/gcp-sea-cloud/ansible/ansible.cfg) = ['/Users/gil/Code/LISEA/Architecture/gcp-sea-cloud/ansible/roles']
DEFAULT_VAULT_PASSWORD_FILE(/Users/gil/Code/LISEA/Architecture/gcp-sea-cloud/ansible/ansible.cfg) = /Users/gil/Code/LISEA/Architecture/gcp-sea-cloud/ansible/vault.txt
HOST_KEY_CHECKING(/Users/gil/Code/LISEA/Architecture/gcp-sea-cloud/ansible/ansible.cfg) = False
INVENTORY_ENABLED(/Users/gil/Code/LISEA/Architecture/gcp-sea-cloud/ansible/ansible.cfg) = ['auto']
RETRY_FILES_ENABLED(/Users/gil/Code/LISEA/Architecture/gcp-sea-cloud/ansible/ansible.cfg) = False
DEFAULT_BECOME(/Users/gil/Code/LISEA/Architecture/gcp-sea-cloud/ansible/ansible.cfg) = True
DEFAULT_HOST_LIST(/Users/gil/Code/LISEA/Architecture/gcp-sea-cloud/ansible/ansible.cfg) = ['/Users/gil/Code/LISEA/Architecture/gcp-sea-cloud/ansible/inventory/sea-cloud.gcp.yml']
DEFAULT_ROLES_PATH(/Users/gil/Code/LISEA/Architecture/gcp-sea-cloud/ansible/ansible.cfg) = ['/Users/gil/Code/LISEA/Architecture/gcp-sea-cloud/ansible/roles']
DEFAULT_VAULT_PASSWORD_FILE(/Users/gil/Code/LISEA/Architecture/gcp-sea-cloud/ansible/ansible.cfg) = /Users/gil/Code/LISEA/Architecture/gcp-sea-cloud/ansible/vault.txt
HOST_KEY_CHECKING(/Users/gil/Code/LISEA/Architecture/gcp-sea-cloud/ansible/ansible.cfg) = False
INVENTORY_ENABLED(/Users/gil/Code/LISEA/Architecture/gcp-sea-cloud/ansible/ansible.cfg) = ['auto']
RETRY_FILES_ENABLED(/Users/gil/Code/LISEA/Architecture/gcp-sea-cloud/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

MacOS 11

**Comment by sivel** [comment] 2020-12-09 17:07
Duplicate of the already opened feature request #47654

**Closed as completed by sivel** 2020-12-09 17:07 UTC
