### ISSUE TITLE
Variable value is changed after encryption with vault string

### ISSUE THREAD

**Issue by LegenJCdary** [ansible/ansible#81069] opened 2023-06-15 12:14 UTC
### Summary

Decrypting a variable that was previously encrypted to vault string results in a changed value visible e.g. using debug module.

### Issue Type

Bug Report

### Component Name

vault

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.0]
  config file = /home/fazi/ansible-code/worktrees/some_worktree/ansible.cfg
  configured module search path = ['/home/fazi/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/some_venv/lib64/python3.9/site-packages/ansible
  ansible collection location = /home/fazi/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/some_venv/bin/ansible
  python version = 3.9.7 (default, Apr 21 2022, 08:39:11) [GCC 8.5.0 20210514 (Red Hat 8.5.0-10)] (/usr/local/some_venv/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
ANSIBLE_NOCOLOR(/home/fazi/ansible-code/worktrees/some_worktree/ansible.cfg) = False
CACHE_PLUGIN(/home/fazi/ansible-code/worktrees/some_worktree/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/fazi/ansible-code/worktrees/some_worktree/ansible.cfg) = ~/.ansible_fact_cache.json
CALLBACKS_ENABLED(/home/fazi/ansible-code/worktrees/some_worktree/ansible.cfg) = ['profile_tasks']
CONFIG_FILE() = /home/fazi/ansible-code/worktrees/some_worktree/ansible.cfg
DEFAULT_BECOME(/home/fazi/ansible-code/worktrees/some_worktree/ansible.cfg) = True
DEFAULT_BECOME_METHOD(/home/fazi/ansible-code/worktrees/some_worktree/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/home/fazi/ansible-code/worktrees/some_worktree/ansible.cfg) = root
DEFAULT_FORKS(/home/fazi/ansible-code/worktrees/some_worktree/ansible.cfg) = 10
DEFAULT_GATHERING(/home/fazi/ansible-code/worktrees/some_worktree/ansible.cfg) = implicit
DEFAULT_HASH_BEHAVIOUR(/home/fazi/ansible-code/worktrees/some_worktree/ansible.cfg) = merge
DEFAULT_ROLES_PATH(/home/fazi/ansible-code/worktrees/some_worktree/ansible.cfg) = ['/home/fazi/ansible-code/worktrees/some_worktree/roles']
DEFAULT_STDOUT_CALLBACK(/home/fazi/ansible-code/worktrees/some_worktree/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/home/fazi/ansible-code/worktrees/some_worktree/ansible.cfg) = 90
DEFAULT_VAULT_PASSWORD_FILE(/home/fazi/ansible-code/worktrees/some_worktree/ansible.cfg) = /etc/ansible/vault-password
HOST_KEY_CHECKING(/home/fazi/ansible-code/worktrees/some_worktree/ansible.cfg) = False
INTERPRETER_PYTHON(/home/fazi/ansible-code/worktrees/some_worktree/ansible.cfg) = /usr/libexec/platform-python
INVENTORY_ENABLED(/home/fazi/ansible-code/worktrees/some_worktree/ansible.cfg) = ['auto', 'yaml', 'netbox.netbox.nb_inventory']

BECOME:
======

runas:
_____
become_user(/home/fazi/ansible-code/worktrees/some_worktree/ansible.cfg) = root

su:
__
become_user(/home/fazi/ansible-code/worktrees/some_worktree/ansible.cfg) = root

sudo:
____
become_user(/home/fazi/ansible-code/worktrees/some_worktree/ansible.cfg) = root

CACHE:
=====

jsonfile:
________
_uri(/home/fazi/ansible-code/worktrees/some_worktree/ansible.cfg) = /home/fazi/.ansible_fact_cache.json

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/home/fazi/ansible-code/worktrees/some_worktree/ansible.cfg) = False
ssh_args(/home/fazi/ansible-code/worktrees/some_worktree/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s -o ConnectionAttempts=2  -o ConnectTimeout=3

ssh:
___
host_key_checking(/home/fazi/ansible-code/worktrees/some_worktree/ansible.cfg) = False
pipelining(/home/fazi/ansible-code/worktrees/some_worktree/ansible.cfg) = True
ssh_args(/home/fazi/ansible-code/worktrees/some_worktree/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s -o ConnectionAttempts=2  -o ConnectTimeout=3
timeout(/home/fazi/ansible-code/worktrees/some_worktree/ansible.cfg) = 90

SHELL:
=====

sh:
__
remote_tmp(/home/fazi/ansible-code/worktrees/some_worktree/ansible.cfg) = /tmp/.ansible-${USER}/tm
```

### OS / Environment

RHEL8 (RockyLinux)

### Steps to Reproduce

```yaml (paste below)
1. Define an inventory with variables available in secrets.yml and vault.yml.

secret_inv/group_vars/all/secrets.yml
---
secret_integer_stringvaulted: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        37396663326632363734363133336562653532396161313736653530653163366635623166663935
        3363373961303532303633323339366237333333623463320a656338383135313266386337393963
        39666665646462383432346639623632356264323935323539303431626633316264376236343933
        6661346438353938330a336132643233633935376662386533323161303932343162666236623362
        6436

secret_inv/group_vars/all/vault.yml
secret_integer_vaulted: 456

2. Display variable values using debug and vars lookup modules.

pb.yml
---
- name: test
  hosts: all
  tasks:
    - name: get_vars_value
      debug:
        msg: "{{ lookup('vars', item.name) }}"
      loop:
        - { name: "secret_integer_vaulted", type: "integer" }
        - { name: "secret_integer_stringvaulted", type: "integer" }
```

### Expected Results

Value of a variable encrypted using vault string remains unchanged.

### Actual Results

```console
TASK [get_vars_value] *********************************************************************************************************************************************************************************************
task path: /home/fazi/ansible-code/worktrees/some_worktree/pb.yml:5
Thursday 15 June 2023  14:13:47 +0200 (0:00:01.463)       0:00:01.520 *********
ok: [localhost] => (item={'name': 'secret_integer_vaulted', 'type': 'integer'}) =>
  msg: '456'
ok: [localhost] => (item={'name': 'secret_integer_stringvaulted', 'type': 'integer'}) =>
  msg: |-
    123
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by sivel** [comment] 2023-06-15 13:35
Duplicate of https://github.com/ansible/ansible/issues/81067

**Closed as completed by sivel** 2023-06-15 13:35 UTC
Labels: bug, affects_2.14

**Comment by LegenJCdary** [comment] 2023-06-20 08:05
Hi @sivel,

Can you drop a few words why is this only a duplicate? Detecting data types is one topic (not as crucial in my opinion) and can be handled with some workarounds (proposed in the issue and overall online). Changing data value upon decryption seems much more impactful and perhaps requires more insight.
