### ISSUE TITLE
with_fileglob not matching *just* directories

### ISSUE THREAD

**Issue by charlienewey** [ansible/ansible#17269] opened 2016-08-27 00:21 UTC
##### ISSUE TYPE

 Bug Report
##### COMPONENT NAME

with_fileglob
##### ANSIBLE VERSION

```
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

nil/defaults
##### OS / ENVIRONMENT

Ubuntu 16.04
##### SUMMARY

Directories not being matched under file glob. This should be possible; some testing in various UNIX shells (bash, sh, zsh) and in the Python `glob` module itself seems to show that the following glob pattern: 

```
some/path/*/
```

will _just_ match directories under `{{variable_holding_some_path}}/`.
##### STEPS TO REPRODUCE

This task:

``` yml
- debug: "{{item}}"
  with_fileglob:
    - "{{variable_holding_some_path}}/*/"
```
##### EXPECTED RESULTS

A list of all directories under `some/path`.
##### ACTUAL RESULTS

No output, but task is supposedly run.

**Comment by charlienewey** [comment] 2016-08-27 00:36
Update: I can get this to work as expected by using the following:

``` yml
- debug: "{{item}}"
  vars:
    glob_: "{{variable_holding_some_path}}/*/"
  with_items:
    - "{{glob_ | fileglob}}"
```

**Comment by dagwieers** [comment] 2016-09-09 12:59
@charlienewey The implementation of the **fileglob** lookup plugin _only_ returns files, not directories. That's how it was implemented as the aim is to iterate over files. If the lookup plugin would return a mix of files and directories, it would not be obvious what would be a file or a directory. So this behaviour is on purpose. And that is why it is called **fileglob**, and not just **glob**.

If you are interested in listing directories, you can make use of the **filetree** lookup plugin, it does return a list of files/directories/symlinks using a recursive scan, and it does provide you with additional information (like whether a _file_ is a directory, symlink or regular file).

That said, there is an obvious mismatch between the **fileglob** lookup plugin and the **fileglob** filter plugin (jinja2). A fix is in the making :-)

**Comment by bcoca** [comment] 2016-10-14 13:23
closing as dupe of #17136

**Closed as completed by bcoca** 2016-10-14 13:23 UTC
Labels: affects_2.0, bug
