### ISSUE TITLE
Inconsitent behavior for "template list" and "playbook list"

### ISSUE THREAD

**Issue by netkgk** [ansible/ansible#12753] opened 2015-10-14 22:09 UTC
Here the code example:

```
- name: set fact
  set_fact: inventory_item={{ hostvars[item].ansible_ssh_host | ipaddr() }}
  with_items:
    - "{{ groups.all }}"
  register: foo_result

- name: make a list
  set_fact: >
    iptables_accept_address2="{{ foo_result.results |
    map(attribute='ansible_facts.inventory_item') | list }}"

- debug: var=iptables_accept_address2

- debug: msg="{% for ip in  iptables_accept_address2 %} >{{ ip }}< {% endfor %}"

- set_fact:
    iptables_accept_address:
      - 1.1.1.2
      - 1.1.3.4
      - 5.5.6.6

- debug: var=iptables_accept_address

- debug: msg="{% for ip in  iptables_accept_address %} >{{ ip }}< {% endfor %}"

```

The evaluation of first example, i.e.  iptables_accept_address2 gives me this output:

```
    "var": {
        "iptables_accept_address2": [
            "127.0.0.2", 
            "127.0.0.3", 
            "127.0.0.1", 
            "127.0.0.4", 
            "127.0.0.5"
        ]
    }


    "msg": " >[<  >u<  >'<  >1<  >2<  >7<  >.<  >0<  >.<  >0<  >.<  >2<  >'<  >,<  > <  >u<  >'<  >1<  >2<  >7<  >.<  >0<  >.<  >0<  >.<  >3<  >'<  >,<  > <  >u<  >'<  >1<  >2<  >7<  >.<  >0<  >.<  >0<  >.<  >1<  >'<  >,<  > <  >u<  >'<  >1<  >2<  >7<  >.<  >0<  >.<  >0<  >.<  >4<  >'<  >,<  > <  >u<  >'<  >1<  >2<  >7<  >.<  >0<  >.<  >0<  >.<  >5<  >'<  >]< "
}
```

While the evaluation of the second, gives me that:

```
    "var": {
        "iptables_accept_address": [
            "1.1.1.2", 
            "1.1.3.4", 
            "5.5.6.6"
        ]
    }

"msg": " >1.1.1.2<  >1.1.3.4<  >5.5.6.6< "
```

This is inconsistent behavior, hence a bug.

**Comment by chrrrles** [comment] 2015-10-15 13:03
What version of Ansible are you using?  I was unable to reproduce with 2.0:

```
 __________________________________________________ 
| -W 60 TASK [debug var=iptables_accept_address2]  |
 -------------------------------------------------- 
     \
      \
       ("`-'  '-/") .___..--' ' "`-._
         ` *_ *  )    `-.   (      ) .`-.__. `)
         (_Y_.) ' ._   )   `._` ;  `` -. .-'
      _.. `--'_..-_/   /--' _ .' ,4
   ( i l ),-''  ( l i),'  ( ( ! .-'    

ok: [foo -> localhost] => {
    "changed": false, 
    "iptables_accept_address2": [
        "127.0.0.1"
    ]
}
 ______________________________________________________________ 
| -W 60 TASK [debug msg={% for ip in iptables_accept_address2  |
| %} >{{ ip }}< {% endfor %}]                                  |
 -------------------------------------------------------------- 
  \
   \   \
        \ /\
        ( )
      .( o ).

ok: [foo -> localhost] => {
    "changed": false, 
    "msg": " >127.0.0.1< "
}
```

**Comment by netkgk** [comment] 2015-11-01 14:17
```
ansible --version
ansible 1.9.3
```

**Comment by bcoca** [comment] 2015-11-01 21:22
You need to use the list flter when using a var, not when creating it, since the first var is quoted I expect it to be a string.  In any case 2.0 does 're evaluation' to try to coerce strings into complex data types so closing this as it is fixed in devel and will be released shortly.

**Closed as completed by bcoca** 2015-11-01 21:22 UTC

**Comment by netkgk** [comment] 2015-11-13 04:30
How to break the line, so it is fit in 80-character limit, then?
