### ISSUE TITLE
Support decrypting files when using the copy module

### ISSUE THREAD

**Issue by dwcramer** [ansible/ansible#10349] opened 2015-02-27 05:04 UTC
Regarding #9556 and #9172, I would like to suggest the following feature request:
In ansible-playbooks support decrypting files on copy:
`copy: src=somefile.key dest=/etc/apache2/ssl/ decrypt=yes`
Where somefile.key is encrypted with ansible-vault. That would be better usability.

**Comment by bcoca** [comment] 2015-02-27 15:26
closing as duplicate of
https://github.com/ansible/ansible/issues/7298

**Closed as completed by bcoca** 2015-02-27 15:26 UTC
